Kaldi: bin/ali-to-pdf.cc File Reference
ali-to-pdf.cc File Reference
#include "base/kaldi-common.h"
#include "gmm/am-diag-gmm.h"
#include "hmm/transition-model.h"
#include "hmm/hmm-utils.h"
#include "util/common-utils.h"
#include "fst/fstlib.h"
Functions
int main (int argc, char *argv[])
Converts alignments (containing transition-ids) to pdf-ids, zero-based.
Function Documentation
main()
int main (int argc, char * argv[])
Converts alignments (containing transition-ids) to pdf-ids, zero-based.
Definition at line 29 of file ali-to-pdf.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), rnnlm::i, KALDI_LOG, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), TransitionModel::TransitionIdToPdf(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   using namespace kaldi;
   typedef kaldi::int32 int32;
   try {
     const char *usage =
         "Converts alignments (containing transition-ids) to pdf-ids, zero-based.\n"
         "Usage:  ali-to-pdf  [options] <model> <alignments-rspecifier> <pdfs-wspecifier>\n"
         "e.g.: \n"
         " ali-to-pdf 1.mdl ark:1.ali ark,t:-\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_filename = po.GetArg(1),
         alignments_rspecifier = po.GetArg(2),
         pdfs_wspecifier = po.GetArg(3);
     TransitionModel trans_model;
     ReadKaldiObject(model_filename, &trans_model);
     SequentialInt32VectorReader reader(alignments_rspecifier);
     Int32VectorWriter writer(pdfs_wspecifier);
     int32 num_done = 0;
     for (; !reader.Done(); reader.Next()) {
       std::string key = reader.Key();
       std::vector<int32> alignment = reader.Value();
       for (size_t i = 0; i < alignment.size(); i++)
         alignment[i] = trans_model.TransitionIdToPdf(alignment[i]);
       writer.Write(key, alignment);
       num_done++;
     }
     KALDI_LOG << "Converted " << num_done << " alignments to pdf sequences.";
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }