Kaldi: lm/arpa-lm-compiler-test.cc File Reference
arpa-lm-compiler-test.cc File Reference
#include <iostream>
#include <string>
#include <sstream>
#include "base/kaldi-error.h"
#include "base/kaldi-math.h"
#include "lm/arpa-lm-compiler.h"
#include "util/kaldi-io.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Enumerations
enum { kEps = 0, kDisambig, kBos, kEos }
Functions
static fst::StdVectorFst * CreateGenFst (bool seps, const fst::SymbolTable *pst)
ArpaLmCompiler * Compile (bool seps, const string &infile)
fst::StdArc::StateId AddToChainFsa (fst::StdMutableFst *fst, fst::StdArc::StateId last_state, int64 symbol)
void AddSelfLoops (fst::StdMutableFst *fst)
bool CoverageTest (bool seps, const string &infile)
bool ScoringTest (bool seps, const string &infile, const string &sentence, float expected)
bool ThrowsExceptionTest (bool seps, const string &infile)
bool RunAllTests (bool seps)
int main (int argc, char *argv[])
Variables
static const int kRandomSentences = 50
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 238 of file arpa-lm-compiler-test.cc.
References KALDI_LOG, KALDI_WARN, and RunAllTests().
{
   bool ok = true;
   ok &= RunAllTests(false);  // Without disambiguators (old behavior).
   ok &= RunAllTests(true);   // With epsilon substitution (new behavior).
   if (ok) {
     KALDI_LOG << "All tests passed";
     return 0;
   } else {
     KALDI_WARN << "Test FAILED";
     return 1;
   }
 }
RunAllTests()
bool RunAllTests (bool seps)
Definition at line 220 of file arpa-lm-compiler-test.cc.
References kaldi::CoverageTest(), KALDI_WARN, kaldi::ScoringTest(), and kaldi::ThrowsExceptionTest().
Referenced by main().
{
   bool ok = true;
   ok &= kaldi::CoverageTest(seps, "test_data/missing_backoffs.arpa");
   ok &= kaldi::CoverageTest(seps, "test_data/unused_backoffs.arpa");
   ok &= kaldi::CoverageTest(seps, "test_data/input.arpa");
   ok &= kaldi::ScoringTest(seps, "test_data/input.arpa", "b b b a", 59.2649);
   ok &= kaldi::ScoringTest(seps, "test_data/input.arpa", "a b", 4.36082);
   ok &= kaldi::ThrowsExceptionTest(seps, "test_data/missing_bos.arpa");
   if (!ok) {
     KALDI_WARN << "Tests " << (seps ? "with" : "without")
                << " epsilon substitution FAILED";
   }
   return ok;
 }