Kaldi: tree/build-tree-utils-test.cc File Reference
build-tree-utils-test.cc File Reference
#include "util/stl-utils.h"
#include "util/kaldi-io.h"
#include "tree/build-tree-utils.h"
#include "tree/clusterable-classes.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void TestTrivialTree ()
void TestPossibleValues ()
void TestConvertStats ()
void TestSplitStatsByKey ()
void TestFindAllKeys ()
void TestDoTableSplit ()
void TestClusterEventMapGetMappingAndRenumberEventMap ()
void TestClusterEventMapGetMappingAndRenumberEventMap2 ()
void TestClusterEventMap ()
void TestClusterEventMapRestricted ()
void TestShareEventMapLeaves ()
void TestQuestionsInitRand ()
void TestSplitDecisionTree ()
void TestBuildTreeStatsIo (bool binary)
int main ()
Function Documentation
main()
int main ()
Definition at line 872 of file build-tree-utils-test.cc.
References rnnlm::i, kaldi::TestBuildTreeStatsIo(), kaldi::TestClusterEventMap(), kaldi::TestClusterEventMapGetMappingAndRenumberEventMap(), kaldi::TestClusterEventMapGetMappingAndRenumberEventMap2(), kaldi::TestClusterEventMapRestricted(), kaldi::TestConvertStats(), kaldi::TestDoTableSplit(), kaldi::TestFindAllKeys(), kaldi::TestPossibleValues(), kaldi::TestQuestionsInitRand(), kaldi::TestShareEventMapLeaves(), kaldi::TestSplitDecisionTree(), kaldi::TestSplitStatsByKey(), and kaldi::TestTrivialTree().
            {
   using namespace kaldi;
   for (size_t i = 0;i < 2;i++) {
     TestTrivialTree();
     TestPossibleValues();
     TestDoTableSplit();
     TestClusterEventMapGetMappingAndRenumberEventMap();
     TestClusterEventMapGetMappingAndRenumberEventMap2();  // tests "with gaps"
     TestClusterEventMap();
     TestClusterEventMapRestricted();
     TestShareEventMapLeaves();
     TestQuestionsInitRand();
     TestSplitDecisionTree();
     TestBuildTreeStatsIo(false);
     TestBuildTreeStatsIo(true);
     TestConvertStats();
     TestSplitStatsByKey();
     TestFindAllKeys();  // put at end because it throws+catches internally.
   }
 }