Kaldi: BlockSoftmax Class Reference
BlockSoftmax Class Reference
#include <nnet-activation.h>
Public Member Functions
BlockSoftmax (int32 dim_in, int32 dim_out)
~BlockSoftmax ()
Component * Copy () const
Copy component (deep copy),.
ComponentType GetType () const
Get Type Identification of the component,.
void InitData (std::istream &is)
Virtual interface for initialization and I/O,.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
std::string Info () const
Print some additional info (after <ComponentName> and the dims),.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
Generic interface of a component,.
virtual ~Component ()
virtual bool IsUpdatable () const
Check if componeny has 'Updatable' interface (trainable components),.
virtual bool IsMultistream () const
Check if component has 'Recurrent' interface (trainable and recurrent),.
int32 InputDim () const
Get the dimension of the input,.
int32 OutputDim () const
Get the dimension of the output,.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward-pass propagation 'in' -> 'out',.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
void Write (std::ostream &os, bool binary) const
Write the component to a stream,.
virtual std::string InfoGradient () const
Print some additional info about gradient (after <...> and dims),.
Public Attributes
std::vector< int32 > block_dims
std::vector< int32 > block_offset
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjected, kBlstmProjected,
kRecurrentComponent, kActivationFunction = 0x0200, kSoftmax, kHiddenSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kParametricRelu,
kDropout, kLengthNormComponent, kTranform = 0x0400, kRbm,
kSplice, kCopy, kTranspose, kBlockLinearity,
kAddShift, kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent,
kSimpleSentenceAveragingComponent, kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent,
kMaxPooling2DComponent, kFramePoolingComponent, kParallelComponent, kMultiBasisComponent
}
Component type identification mechanism,.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Converts component type to marker,.
static ComponentType MarkerToType (const std::string &s)
Converts marker to component type (case insensitive),.
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file,.
static Component * Read (std::istream &is, bool binary)
Read the component from a stream (static method),.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Protected Attributes inherited from Component
int32 input_dim_
Data members,.
int32 output_dim_
Dimension of the output of the Component,.
Detailed Description
Definition at line 113 of file nnet-activation.h.
Constructor & Destructor Documentation
BlockSoftmax()
BlockSoftmax (int32 dim_in, int32 dim_out) inline
Definition at line 115 of file nnet-activation.h.
                                            :
     Component(dim_in, dim_out)
   { }
~BlockSoftmax()
~BlockSoftmax () inline
Definition at line 119 of file nnet-activation.h.
   { }
Member Function Documentation
BackpropagateFnc()
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 174 of file nnet-activation.h.
References CuVectorBase< Real >::Add(), CuVectorBase< Real >::AddColSumMat(), CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::MulRowsVec(), CuMatrixBase< Real >::NumRows(), and CuVectorBase< Real >::Scale().
{
     // copy the error derivative:
     // (assuming we already got softmax-cross-entropy derivative in out_diff)
     in_diff->CopyFromMat(out_diff);
     // Set the derivatives to zero for the matrix-lines in which
     // the sum of 'derivatives' was 1.0 (i.e. there was no target):
     for (int32 bl = 0; bl < block_dims.size(); bl++) {
       // get the block,
       CuSubMatrix<BaseFloat> diff_bl =
         in_diff->ColRange(block_offset[bl], block_dims[bl]);
       // get the sum of each row,
       CuVector<BaseFloat> row_sum(diff_bl.NumRows());
       row_sum.AddColSumMat(1.0, diff_bl, 0.0);  // 0: keep as-is, 1: zero-out
       // we'll scale rows by 0/1 masks,
       CuVector<BaseFloat> row_diff_mask(row_sum);
       row_diff_mask.Scale(-1.0);  // 0: keep as-is, -1: zero-out
       row_diff_mask.Add(1.0);  // 1: keep as-is, 0: zero-out
       // here we should have only 0's and 1's,
       diff_bl.MulRowsVec(row_diff_mask);
     }
   }
Copy()
Component* Copy () const inline virtual
Copy component (deep copy),.
Implements Component.
Definition at line 122 of file nnet-activation.h.
 { return new BlockSoftmax(*this); }
GetType()
ComponentType GetType () const inline virtual
Get Type Identification of the component,.
Implements Component.
Definition at line 123 of file nnet-activation.h.
References Component::kBlockSoftmax.
 { return kBlockSoftmax; }
Info()
std::string Info () const inline virtual
Print some additional info (after <ComponentName> and the dims),.
Reimplemented from Component.
Definition at line 200 of file nnet-activation.h.
References kaldi::nnet1::ToString().
{
     return "\n  softmax-dims " + ToString(block_dims);
   }
InitData()
void InitData (std::istream & is) inline virtual
Virtual interface for initialization and I/O,.
Initialize internal data of a component
Reimplemented from Component.
Definition at line 125 of file nnet-activation.h.
References rnnlm::i, KALDI_ASSERT, KALDI_ERR, Component::OutputDim(), kaldi::ReadToken(), and kaldi::SplitStringToIntegers().
{
     // parse config
     std::string token,
       dims_str;
     while (is >> std::ws, !is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<BlockDims>") is >> dims_str;
       else KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                      << " (BlockDims)";
     }
     // parse dims,
     if (!kaldi::SplitStringToIntegers(dims_str, ",:", false, &block_dims))
       KALDI_ERR << "Invalid block-dims " << dims_str;
     // sanity check
     int32 sum = 0;
     for (int32 i = 0; i < block_dims.size(); i++) {
       sum += block_dims[i];
     }
     KALDI_ASSERT(sum == OutputDim());
   }
PropagateFnc()
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 160 of file nnet-activation.h.
References CuMatrixBase< Real >::ApplySoftMaxPerRow(), and CuMatrixBase< Real >::ColRange().
{
     // perform softmax per block:
     for (int32 bl = 0; bl < block_dims.size(); bl++) {
       // get the blocks,
       CuSubMatrix<BaseFloat> in_bl =
         in.ColRange(block_offset[bl], block_dims[bl]);
       CuSubMatrix<BaseFloat> out_bl =
         out->ColRange(block_offset[bl], block_dims[bl]);
       // y = e^x_j/sum_j(e^x_j),
       out_bl.ApplySoftMaxPerRow(in_bl);
     }
   }
ReadData()
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 146 of file nnet-activation.h.
References rnnlm::i, KALDI_ASSERT, Component::OutputDim(), and kaldi::ReadIntegerVector().
{
     ReadIntegerVector(is, binary, &block_dims);
     block_offset.resize(block_dims.size()+1, 0);
     for (int32 i = 0; i < block_dims.size(); i++) {
       block_offset[i+1] = block_offset[i] + block_dims[i];
     }
     // check
     KALDI_ASSERT(OutputDim() == block_offset[block_offset.size()-1]);
   }
WriteData()
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 156 of file nnet-activation.h.
References kaldi::WriteIntegerVector().
{
     WriteIntegerVector(os, binary, block_dims);
   }
Member Data Documentation
block_dims
std::vector<int32> block_dims
Definition at line 204 of file nnet-activation.h.
block_offset
std::vector<int32> block_offset
Definition at line 205 of file nnet-activation.h.
The documentation for this class was generated from the following file:
nnet/nnet-activation.h