Kaldi: AmNnetSimple Class Reference
AmNnetSimple Class Reference
#include <am-nnet-simple.h>
Public Member Functions
AmNnetSimple ()
AmNnetSimple (const AmNnetSimple &other)
AmNnetSimple (const Nnet &nnet)
int32 NumPdfs () const
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
const Nnet & GetNnet () const
Nnet & GetNnet ()
Caution: if you structurally change the nnet, you should call SetContext() afterward.
void SetNnet (const Nnet &nnet)
void SetPriors (const VectorBase< BaseFloat > &priors)
const VectorBase< BaseFloat > & Priors () const
std::string Info () const
int32 LeftContext () const
Minimum left context required to compute an output.
int32 RightContext () const
Minimum right context required to compute an output.
int32 InputDim () const
Returns the input feature dim.
int32 IvectorDim () const
Returns the iVector dimension, or -1 if there is no such input.
void SetContext ()
This function works out the left_context_ and right_context_ variables from the network (it's a rather complex calculation).
Private Member Functions
const AmNnetSimple & operator= (const AmNnetSimple &other)
Private Attributes
Nnet nnet_
Vector< BaseFloat > priors_
int32 left_context_
int32 right_context_
Detailed Description
Definition at line 49 of file am-nnet-simple.h.
Constructor & Destructor Documentation
AmNnetSimple() [1/3]
AmNnetSimple () inline
Definition at line 51 of file am-nnet-simple.h.
 { }
AmNnetSimple() [2/3]
AmNnetSimple (const AmNnetSimple & other) inline
Definition at line 53 of file am-nnet-simple.h.
                                          :
     nnet_(other.nnet_),
     priors_(other.priors_),
     left_context_(other.left_context_),
     right_context_(other.right_context_) { }
AmNnetSimple() [3/3]
AmNnetSimple (const Nnet & nnet) inline explicit
Definition at line 59 of file am-nnet-simple.h.
References AmNnetSimple::NumPdfs(), AmNnetSimple::Read(), AmNnetSimple::SetContext(), and AmNnetSimple::Write().
                                          :
     nnet_(nnet) { SetContext(); }
Member Function Documentation
GetNnet() [1/2]
const Nnet& GetNnet () const inline
Definition at line 68 of file am-nnet-simple.h.
References AmNnetSimple::nnet_.
Referenced by DecodableAmNnetSimpleParallel::DecodableAmNnetSimpleParallel(), DecodableNnetSimpleLoopedInfo::DecodableNnetSimpleLoopedInfo(), main(), and Nnet::Read().
 { return nnet_; }
GetNnet() [2/2]
Nnet& GetNnet () inline
Caution: if you structurally change the nnet, you should call SetContext() afterward.
Definition at line 72 of file am-nnet-simple.h.
References AmNnetSimple::nnet_, AmNnetSimple::SetNnet(), and AmNnetSimple::SetPriors().
 { return nnet_; }
Info()
std::string Info () const
Definition at line 80 of file am-nnet-simple.cc.
References Nnet::Info(), Nnet::InputDim(), AmNnetSimple::nnet_, Nnet::OutputDim(), and AmNnetSimple::priors_.
Referenced by main(), and AmNnetSimple::Priors().
{
   std::ostringstream ostr;
   ostr << "input-dim: " << nnet_.InputDim("input") << "\n";
   ostr << "ivector-dim: " << nnet_.InputDim("ivector") << "\n";
   ostr << "num-pdfs: " << nnet_.OutputDim("output") << "\n";
   ostr << "prior-dimension: " << priors_.Dim() << "\n";
   if (priors_.Dim() != 0) {
     ostr << "prior-sum: " << priors_.Sum() << "\n";
     ostr << "prior-min: " << priors_.Min() << "\n";
     ostr << "prior-max: " << priors_.Max() << "\n";
   }
   ostr << "# Nnet info follows.\n";
   return ostr.str() + nnet_.Info();
 }
InputDim()
int32 InputDim () const inline
Returns the input feature dim.
Definition at line 89 of file am-nnet-simple.h.
References Nnet::InputDim(), and AmNnetSimple::nnet_.
 { return nnet_.InputDim("input"); }
IvectorDim()
int32 IvectorDim () const inline
Returns the iVector dimension, or -1 if there is no such input.
Definition at line 92 of file am-nnet-simple.h.
References Nnet::InputDim(), AmNnetSimple::nnet_, AmNnetSimple::operator=(), and AmNnetSimple::SetContext().
 { return nnet_.InputDim("ivector"); }
LeftContext()
int32 LeftContext () const inline
Minimum left context required to compute an output.
Definition at line 83 of file am-nnet-simple.h.
References AmNnetSimple::left_context_.
 { return left_context_; }
NumPdfs()
int32 NumPdfs () const
Definition at line 28 of file am-nnet-simple.cc.
References KALDI_ASSERT, AmNnetSimple::nnet_, and Nnet::OutputDim().
Referenced by AmNnetSimple::AmNnetSimple(), and kaldi::nnet3::SetPriors().
{
   int32 ans = nnet_.OutputDim("output");
   KALDI_ASSERT(ans > 0);
   return ans;
 }
operator=()
const AmNnetSimple& operator= (const AmNnetSimple & other) private
Referenced by AmNnetSimple::IvectorDim().
Priors()
const VectorBase<BaseFloat>& Priors () const inline
Definition at line 78 of file am-nnet-simple.h.
References AmNnetSimple::Info(), and AmNnetSimple::priors_.
Referenced by DecodableAmNnetSimpleParallel::DecodableAmNnetSimpleParallel(), and main().
 { return priors_; }
Read()
void Read (std::istream & is, bool binary)
Definition at line 47 of file am-nnet-simple.cc.
References kaldi::nnet3::ExpectToken(), AmNnetSimple::left_context_, AmNnetSimple::nnet_, AmNnetSimple::priors_, Nnet::Read(), kaldi::ReadBasicType(), AmNnetSimple::right_context_, and AmNnetSimple::SetContext().
Referenced by AmNnetSimple::AmNnetSimple(), main(), and Nnet::Read().
{
   nnet_.Read(is, binary);
   ExpectToken(is, binary, "<LeftContext>");
   ReadBasicType(is, binary, &left_context_);
   ExpectToken(is, binary, "<RightContext>");
   ReadBasicType(is, binary, &right_context_);
   SetContext();  // temporarily, I'm not trusting the written ones (there was
                  // briefly a bug)
   ExpectToken(is, binary, "<Priors>");
   priors_.Read(is, binary);
 }
RightContext()
int32 RightContext () const inline
Minimum right context required to compute an output.
Definition at line 86 of file am-nnet-simple.h.
References AmNnetSimple::right_context_.
 { return right_context_; }
SetContext()
void SetContext ()
This function works out the left_context_ and right_context_ variables from the network (it's a rather complex calculation).
You should call this if you have structurally changed the nnet without calling SetNnet(), e.g. using non-const GetNnet().
Definition at line 96 of file am-nnet-simple.cc.
References kaldi::nnet3::ComputeSimpleNnetContext(), kaldi::nnet3::IsSimpleNnet(), KALDI_ERR, AmNnetSimple::left_context_, AmNnetSimple::nnet_, and AmNnetSimple::right_context_.
Referenced by AmNnetSimple::AmNnetSimple(), AmNnetSimple::IvectorDim(), main(), AmNnetSimple::Read(), and AmNnetSimple::SetNnet().
{
   if (!IsSimpleNnet(nnet_)) {
     KALDI_ERR << "Class AmNnetSimple is only intended for a restricted type of "
               << "nnet, and this one does not meet the conditions.";
   }
   ComputeSimpleNnetContext(nnet_,
                            &left_context_,
                            &right_context_);
 }
SetNnet()
void SetNnet (const Nnet & nnet)
Definition at line 59 of file am-nnet-simple.cc.
References KALDI_WARN, AmNnetSimple::nnet_, Nnet::OutputDim(), AmNnetSimple::priors_, and AmNnetSimple::SetContext().
Referenced by AmNnetSimple::GetNnet(), and main().
{
   nnet_ = nnet;
   SetContext();
   if (priors_.Dim() != 0 && priors_.Dim() != nnet_.OutputDim("output")) {
     KALDI_WARN << "Removing priors since there is a dimension mismatch after "
                << "changing the nnet: " << priors_.Dim() << " vs. "
                << nnet_.OutputDim("output");
     priors_.Resize(0);
   }
 }
SetPriors()
void SetPriors (const VectorBase< BaseFloat > & priors)
Definition at line 70 of file am-nnet-simple.cc.
References VectorBase< Real >::Dim(), KALDI_ERR, AmNnetSimple::nnet_, Nnet::OutputDim(), and AmNnetSimple::priors_.
Referenced by AmNnetSimple::GetNnet(), main(), and kaldi::nnet3::SetPriors().
{
   priors_ = priors;
   if (priors_.Dim() != nnet_.OutputDim("output") &&
       priors_.Dim() != 0) {
     KALDI_ERR << "Dimension mismatch when setting priors: priors have dim "
               << priors.Dim() << ", model expects "
               << nnet_.OutputDim("output");
   }
 }
Write()
void Write (std::ostream & os, bool binary) const
Definition at line 34 of file am-nnet-simple.cc.
References AmNnetSimple::left_context_, AmNnetSimple::nnet_, AmNnetSimple::priors_, AmNnetSimple::right_context_, Nnet::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by AmNnetSimple::AmNnetSimple(), and main().
{
   // We don't write any header or footer like <AmNnetSimple> and </AmNnetSimple> -- we just
   // write the neural net and then the priors.  Who knows, there might be some
   // situation where we want to just read the neural net.
   nnet_.Write(os, binary);
   WriteToken(os, binary, "<LeftContext>");
   WriteBasicType(os, binary, left_context_);
   WriteToken(os, binary, "<RightContext>");
   WriteBasicType(os, binary, right_context_);
   WriteToken(os, binary, "<Priors>");
   priors_.Write(os, binary);
 }
Member Data Documentation
left_context_
int32 left_context_ private
Definition at line 107 of file am-nnet-simple.h.
Referenced by AmNnetSimple::LeftContext(), AmNnetSimple::Read(), AmNnetSimple::SetContext(), and AmNnetSimple::Write().
nnet_
Nnet nnet_ private
Definition at line 102 of file am-nnet-simple.h.
Referenced by AmNnetSimple::GetNnet(), AmNnetSimple::Info(), AmNnetSimple::InputDim(), AmNnetSimple::IvectorDim(), AmNnetSimple::NumPdfs(), AmNnetSimple::Read(), AmNnetSimple::SetContext(), AmNnetSimple::SetNnet(), AmNnetSimple::SetPriors(), and AmNnetSimple::Write().
priors_
Vector<BaseFloat> priors_ private
Definition at line 103 of file am-nnet-simple.h.
Referenced by AmNnetSimple::Info(), AmNnetSimple::Priors(), AmNnetSimple::Read(), AmNnetSimple::SetNnet(), AmNnetSimple::SetPriors(), and AmNnetSimple::Write().
right_context_
int32 right_context_ private
Definition at line 108 of file am-nnet-simple.h.
Referenced by AmNnetSimple::Read(), AmNnetSimple::RightContext(), AmNnetSimple::SetContext(), and AmNnetSimple::Write().
The documentation for this class was generated from the following files:
nnet3/am-nnet-simple.h
nnet3/am-nnet-simple.cc