Kaldi: StatisticsPoolingComponent Class Reference
StatisticsPoolingComponent Class Reference
#include <nnet-general-component.h>
Public Member Functions
StatisticsPoolingComponent ()
StatisticsPoolingComponent (const StatisticsPoolingComponent &other)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
void Check () const
StatisticsPoolingComponent & operator= (const StatisticsPoolingComponent &other)
Private Attributes
int32 input_dim_
int32 input_period_
int32 left_context_
int32 right_context_
int32 num_log_count_features_
bool output_stddevs_
BaseFloat variance_floor_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 336 of file nnet-general-component.h.
Constructor & Destructor Documentation
StatisticsPoolingComponent() [1/2]
StatisticsPoolingComponent ()
Definition at line 573 of file nnet-general-component.cc.
                                                       :
     input_dim_(-1), input_period_(1), left_context_(-1), right_context_(-1),
     num_log_count_features_(0), output_stddevs_(false),
     variance_floor_(1.0e-10) { }
StatisticsPoolingComponent() [2/2]
StatisticsPoolingComponent (const StatisticsPoolingComponent & other)
Definition at line 579 of file nnet-general-component.cc.
References StatisticsPoolingComponent::Check().
                                             :
     input_dim_(other.input_dim_), input_period_(other.input_period_),
     left_context_(other.left_context_), right_context_(other.right_context_),
     num_log_count_features_(other.num_log_count_features_),
     output_stddevs_(other.output_stddevs_),
     variance_floor_(1.0e-10) {
   Check();
 }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 820 of file nnet-general-component.cc.
References CuMatrixBase< Real >::AddRowRanges(), CuVectorBase< Real >::ApplyExp(), StatisticsPoolingComponentPrecomputedIndexes::backward_indexes, CuMatrixBase< Real >::ColRange(), CuVectorBase< Real >::CopyColFromMat(), CuVectorBase< Real >::Data(), CuMatrixBase< Real >::DivRowsVec(), StatisticsPoolingComponentPrecomputedIndexes::forward_indexes, StatisticsPoolingComponent::input_dim_, KALDI_ASSERT, kaldi::kUndefined, StatisticsPoolingComponent::num_log_count_features_, CuMatrixBase< Real >::NumRows(), StatisticsPoolingComponent::output_stddevs_, and CuVectorBase< Real >::SetZero().
{
   KALDI_ASSERT(indexes_in != NULL);
   const StatisticsPoolingComponentPrecomputedIndexes *indexes =
       dynamic_cast<const StatisticsPoolingComponentPrecomputedIndexes*>(
           indexes_in);
   int32 num_rows_out = out_deriv_in.NumRows();
   CuMatrix<BaseFloat> out_deriv(out_deriv_in);
   if (output_stddevs_) {
     // for now we actually ignore the covariance flooring in the backprop- this
     // is an approximation.  Typically the derivatives computed will be quite
     // tiny for floored variances (they should be zero), so it won't affect the
     // derivatives much.
     int32 feature_dim = (input_dim_ - 1) / 2;
     CuSubMatrix<BaseFloat> mean_deriv(out_deriv, 0, num_rows_out,
                                       num_log_count_features_, feature_dim),
         variance_deriv(out_deriv, 0, num_rows_out,
                        num_log_count_features_ + feature_dim, feature_dim),
         mean_value(out_value, 0, num_rows_out,
                    num_log_count_features_, feature_dim),
         stddev_value(out_value, 0, num_rows_out,
                      num_log_count_features_ + feature_dim, feature_dim);
     // we currently have the deriv w.r.t. the stddev.  step 1 is to get it
     // w.r.t. the centered variance.  If the centered variance is s,
     // and the stddev is sqrt(s), then d/ds sqrt(s) = 0.5 / sqrt(s),
     // so we need to multiply variance_deriv by 0.5 / the stddev.
     variance_deriv.DivElements(stddev_value);
     variance_deriv.Scale(0.5);
     // the deriv w.r.t. the uncentered variance is the same as w.r.t.  the
     // uncentered variance (since they difer by a constant term of -(mean *
     // mean), but we need to add to dF/dmean, the value -2.0 * mean *
     // dF/dvariance.
     mean_deriv.AddMatMatElements(-2.0, mean_value, variance_deriv, 1.0);
   }
   // now we have to account for the effect of division by the count, on
   // the derivative.
   CuVector<BaseFloat> counts(num_rows_out, kUndefined);
   if (num_log_count_features_ > 0) {
     counts.CopyColFromMat(out_value, 0);
     counts.ApplyExp();
   } else {
     counts.SetZero();
     // we need to recompute the counts from the input since they are not in the
     // output.  The submatrix initializer below takes num-rows, num-cols,
     // stride;  num-cols and stride are 1.
     CuSubMatrix<BaseFloat> counts_mat(counts.Data(), num_rows_out, 1, 1);
     counts_mat.AddRowRanges(in_value.ColRange(0, 1), indexes->forward_indexes);
   }
   // Divide the output derivative by the counts.  This is what we want as it
   // concerns the mean and x^2 stats.  As for the counts themselves, the
   // derivative will end up being discarded when we backprop to the
   // StatisticsExtractionComponent (as the count is not differentiable) so it
   // doesn't really matter.
   out_deriv.DivRowsVec(counts);
   // Now propagate the derivative back to the input.  we don't propagate it
   // back for the count's row since it's non-differentiable.
   in_deriv->ColRange(1, input_dim_ - 1).
       AddRowRanges(out_deriv.ColRange(num_log_count_features_, input_dim_ - 1),
                    indexes->backward_indexes);
 }
Check()
void Check () const private
Definition at line 589 of file nnet-general-component.cc.
References StatisticsPoolingComponent::input_dim_, StatisticsPoolingComponent::input_period_, KALDI_ASSERT, StatisticsPoolingComponent::left_context_, StatisticsPoolingComponent::output_stddevs_, StatisticsPoolingComponent::right_context_, and StatisticsPoolingComponent::variance_floor_.
Referenced by StatisticsPoolingComponent::Read(), and StatisticsPoolingComponent::StatisticsPoolingComponent().
{
   KALDI_ASSERT(input_dim_ > 0);
   KALDI_ASSERT(input_period_ > 0);
   KALDI_ASSERT(left_context_ >= 0 && right_context_ >= 0 &&
                left_context_ + right_context_ > 0);
   KALDI_ASSERT(left_context_ % input_period_ == 0 &&
                right_context_ % input_period_ == 0);
   KALDI_ASSERT(variance_floor_ > 0.0 && variance_floor_ < 1.0);
   KALDI_ASSERT(!output_stddevs_ || (input_dim_ - 1) % 2 == 0);
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 373 of file nnet-general-component.h.
References DistributeComponent::GetInputIndexes(), DistributeComponent::IsComputable(), DistributeComponent::PrecomputeIndexes(), and Component::ReorderIndexes().
{
     return new StatisticsPoolingComponent(*this);
   }
GetInputIndexes()
void GetInputIndexes (const MiscComputationInfo & misc_info, const Index & output_index, std::vector< Index > * desired_indexes) const virtual
This function only does something interesting for non-simple Components.
For a given index at the output of the component, tells us what indexes are required at its input (note: "required" encompasses also optionally-required things; it will enumerate all things that we'd like to have). See also IsComputable().
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. We will add members to misc_info as needed.
[in] output_index The Index at the output of the component, for which we are requesting the list of indexes at the component's input.
[out] desired_indexes A list of indexes that are desired at the input. are to be written to here. By "desired" we mean required or optionally-required.
The default implementation of this function is suitable for any SimpleComponent; it just copies the output_index to a single identical element in input_indexes.
Reimplemented from Component.
Definition at line 648 of file nnet-general-component.cc.
References StatisticsPoolingComponent::input_period_, KALDI_ASSERT, StatisticsPoolingComponent::left_context_, StatisticsPoolingComponent::right_context_, and Index::t.
{
   desired_indexes->clear();
   Index input_index(output_index);
   int32 middle_t = output_index.t,
       t_start = middle_t - left_context_,
       t_last = middle_t + right_context_;
   KALDI_ASSERT(middle_t % input_period_ == 0);
   for (int32 t = t_start; t <= t_last; t += input_period_) {
     input_index.t = t;
     desired_indexes->push_back(input_index);
   }
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 553 of file nnet-general-component.cc.
References StatisticsExtractionComponent::Check(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), StatisticsExtractionComponent::input_dim_, StatisticsExtractionComponent::input_period_, KALDI_ERR, StatisticsExtractionComponent::Type(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   bool ok = cfl->GetValue("input-dim", &input_dim_);
   cfl->GetValue("input-period", &input_period_);
   cfl->GetValue("left-context", &left_context_);
   cfl->GetValue("right-context", &right_context_);
   cfl->GetValue("num-log-count-features", &num_log_count_features_);
   cfl->GetValue("output-stddevs", &output_stddevs_);
   cfl->GetValue("variance-floor", &variance_floor_);
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   // do some basic checks here but Check() will check more completely.
   if (!ok || input_dim_ <= 0 || left_context_ + right_context_ <= 0 ||
       num_log_count_features_ < 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Check();
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 344 of file nnet-general-component.h.
References DistributeComponent::input_dim_.
 { return input_dim_; }
IsComputable()
bool IsComputable (const MiscComputationInfo & misc_info, const Index & output_index, const IndexSet & input_index_set, std::vector< Index > * used_inputs) const virtual
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
It tells the user whether a given output index is computable from a given set of input indexes, and if so, says which input indexes will be used in the computation.
Implementations of this function are required to have the property that adding an element to "input_index_set" can only ever change IsComputable from false to true, never vice versa.
Parameters
[in] misc_info Some information specific to the computation, such as minimum and maximum times for certain components to do adaptation on; it's a place to put things that don't easily fit in the framework.
[in] output_index The index that is to be computed at the output of this Component.
[in] input_index_set The set of indexes that is available at the input of this Component.
[out] used_inputs If this is non-NULL and the output is computable this will be set to the list of input indexes that will actually be used in the computation.
Returns
Returns true iff this output is computable from the provided inputs.
The default implementation of this function is suitable for any SimpleComponent: it just returns true if output_index is in input_index_set, and if so sets used_inputs to vector containing that one Index.
Reimplemented from Component.
Definition at line 664 of file nnet-general-component.cc.
References StatisticsPoolingComponent::input_period_, StatisticsPoolingComponent::left_context_, StatisticsPoolingComponent::right_context_, and Index::t.
{
   if (used_inputs)
     used_inputs->clear();
   // you are not supposed to access the output of this component other than at
   // multiples of the input period.  We could make this an error but decided to
   // just have it return false.
   if (output_index.t % input_period_ != 0)
     return false;
   Index input_index(output_index);
   int32 output_t = output_index.t,
       t_start = output_t - left_context_,
       t_last = output_t + right_context_;
   if (!used_inputs) {
     for (int32 t = t_start; t <= t_last; t += input_period_) {
       input_index.t = t;
       if (input_index_set(input_index))
         return true;
     }
     return false;
   } else {
     bool ans = false;
     for (int32 t = t_start; t <= t_last; t += input_period_) {
       input_index.t = t;
       if (input_index_set(input_index)) {
         ans = true;
         used_inputs->push_back(input_index);
       }
     }
     return ans;
   }
 }
operator=()
StatisticsPoolingComponent& operator= (const StatisticsPoolingComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 345 of file nnet-general-component.h.
References DistributeComponent::InitFromConfig(), and DistributeComponent::input_dim_.
Referenced by ConstantComponent::Info(), and StatisticsPoolingComponent::Propagate().
{
     return input_dim_ + num_log_count_features_ - 1;
   }
PrecomputeIndexes()
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo & misc_info, const std::vector< Index > & input_indexes, const std::vector< Index > & output_indexes, bool need_backprop) const virtual
This function must return NULL for simple Components.
Returns a pointer to a class that may contain some precomputed component-specific and computation-specific indexes to be in used in the Propagate and Backprop functions.
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. misc_info may not even ever be used here. We will add members to misc_info as needed.
[in] input_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the in/in_value/in_deriv matrices given to Propagate and Backprop will mean.
[in] output_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the out/out_value/out_deriv matrices given to Propagate and Backprop will mean.
[in] need_backprop True if we might need to do backprop with this component, so that if any different indexes are needed for backprop then those should be computed too.
Returns
Returns a child-class of class ComponentPrecomputedIndexes, or NULL if this component for does not need to precompute any indexes (e.g. if it is a simple component and does not care about indexes).
Reimplemented from Component.
Definition at line 702 of file nnet-general-component.cc.
References StatisticsPoolingComponentPrecomputedIndexes::backward_indexes, Int32Pair::first, StatisticsPoolingComponentPrecomputedIndexes::forward_indexes, rnnlm::i, StatisticsPoolingComponent::input_period_, KALDI_ASSERT, StatisticsPoolingComponent::left_context_, StatisticsPoolingComponent::right_context_, Int32Pair::second, and Index::t.
{
   int32 num_input_indexes = input_indexes.size(),
       num_output_indexes = output_indexes.size();
   StatisticsPoolingComponentPrecomputedIndexes *ans = new
       StatisticsPoolingComponentPrecomputedIndexes();
   Int32Pair invalid_pair;
   invalid_pair.first = -1;
   invalid_pair.second = -1;
   // forward_indexes_cpu[i] will be the (begin, end) of input indexes
   // included in the sum for the i'th output index.
   std::vector<Int32Pair> forward_indexes_cpu(num_output_indexes,
                                              invalid_pair);
   // backward_indexes_cpu[i] will be the (begin, end) of output indexes
   // for which the i'th input index participates in the sum.
   // because of the way the indexes are sorted (and the fact that only
   // required indexes are present at the input), it naturally has this
   // structure [i.e. no gaps in the sets of indexes].
   std::vector<Int32Pair> backward_indexes_cpu(num_input_indexes,
                                               invalid_pair);
   // this map maps from Index to the position in 'input_indexes'.
   unordered_map<Index, int32, IndexHasher> index_to_input_pos;
   for (int32 i = 0; i < num_input_indexes; i++)
     index_to_input_pos[input_indexes[i]] = i;
   for (int32 i = 0; i < num_output_indexes; i++) {
     Index input_index(output_indexes[i]);
     int32 middle_t = input_index.t,
         t_start = middle_t - left_context_,
         t_last = middle_t + right_context_;
     for (int32 t = t_start; t <= t_last; t += input_period_) {
       input_index.t = t;
       unordered_map<Index, int32, IndexHasher>::iterator iter =
           index_to_input_pos.find(input_index);
       if (iter != index_to_input_pos.end()) {
         int32 input_pos = iter->second;
         if (forward_indexes_cpu[i].first == -1) {
           forward_indexes_cpu[i].first = input_pos;
           forward_indexes_cpu[i].second = input_pos + 1;
         } else {
           KALDI_ASSERT(forward_indexes_cpu[i].second == input_pos);
           forward_indexes_cpu[i].second++;
         }
         if (backward_indexes_cpu[input_pos].first == -1) {
           backward_indexes_cpu[input_pos].first = i;
           backward_indexes_cpu[input_pos].second = i + 1;
         } else {
           KALDI_ASSERT(backward_indexes_cpu[input_pos].second == i);
           backward_indexes_cpu[input_pos].second++;
         }
       }
     }
     KALDI_ASSERT(forward_indexes_cpu[i].first != -1);
   }
   for (int32 i = 0; i < num_input_indexes; i++) {
     KALDI_ASSERT(backward_indexes_cpu[i].first != -1);
   }
   ans->forward_indexes = forward_indexes_cpu;
   if (need_backprop)
     ans->backward_indexes = backward_indexes_cpu;
   return ans;
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 771 of file nnet-general-component.cc.
References CuMatrixBase< Real >::AddMatMatElements(), CuMatrixBase< Real >::AddRowRanges(), CuMatrixBase< Real >::ApplyFloor(), CuMatrixBase< Real >::ApplyPow(), CuMatrixBase< Real >::ColRange(), CuArrayBase< T >::Dim(), CuMatrixBase< Real >::DivRowsVec(), StatisticsPoolingComponentPrecomputedIndexes::forward_indexes, StatisticsPoolingComponent::input_dim_, KALDI_ASSERT, kaldi::kUndefined, StatisticsPoolingComponent::num_log_count_features_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), StatisticsPoolingComponent::output_stddevs_, StatisticsPoolingComponent::OutputDim(), CuVectorBase< Real >::Set(), CuMatrixBase< Real >::SetZero(), and StatisticsPoolingComponent::variance_floor_.
{
   out->SetZero();
   KALDI_ASSERT(indexes_in != NULL);
   const StatisticsPoolingComponentPrecomputedIndexes *indexes =
       dynamic_cast<const StatisticsPoolingComponentPrecomputedIndexes*>(indexes_in);
   int32 num_rows_out = out->NumRows();
   KALDI_ASSERT(indexes != NULL &&
                indexes->forward_indexes.Dim() == num_rows_out &&
                in.NumCols() == input_dim_ &&
                out->NumCols() == OutputDim());
   CuVector<BaseFloat> counts(num_rows_out);
   // counts_mat is a fake matrix with one column, containing the counts.
   CuSubMatrix<BaseFloat> counts_mat(counts.Data(), num_rows_out, 1, 1);
   counts_mat.AddRowRanges(in.ColRange(0, 1), indexes->forward_indexes);
   CuSubMatrix<BaseFloat> out_non_count(*out, 0, num_rows_out,
                                        num_log_count_features_, input_dim_ - 1);
   out_non_count.AddRowRanges(in.ColRange(1, input_dim_ - 1),
                              indexes->forward_indexes);
   out_non_count.DivRowsVec(counts);
   if (num_log_count_features_ > 0) {
     counts.ApplyLog();
     CuVector<BaseFloat> ones(num_log_count_features_, kUndefined);
     ones.Set(1.0);
     out->ColRange(0, num_log_count_features_).AddVecVec(1.0, counts, ones);
   }
   if (output_stddevs_) {
     // if this is true, then we assume the input contains x^2 stats as well as x
     // stats, and we want to process them into a standard deviation.
     KALDI_ASSERT((input_dim_ - 1) % 2 == 0);
     int32 feature_dim = (input_dim_ - 1) / 2;
     CuSubMatrix<BaseFloat> mean(*out, 0, num_rows_out,
                                 num_log_count_features_, feature_dim),
         variance(*out, 0, num_rows_out,
                  num_log_count_features_ + feature_dim, feature_dim);
     // subtract mean-squared from average of x^2 to get the variance.
     variance.AddMatMatElements(-1.0, mean, mean, 1.0);
     variance.ApplyFloor(variance_floor_);
     // compute the standard deviation via square root.
     variance.ApplyPow(0.5);
   }
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 350 of file nnet-general-component.h.
References DistributeComponent::Backprop(), kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kBackpropNeedsOutput, kaldi::nnet3::kReordersIndexes, DistributeComponent::Propagate(), DistributeComponent::Read(), and DistributeComponent::Write().
{
     return kReordersIndexes|kBackpropAdds|
         (output_stddevs_ || num_log_count_features_ > 0 ?
          kBackpropNeedsOutput : 0) |
         (num_log_count_features_ == 0 ? kBackpropNeedsInput : 0);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 600 of file nnet-general-component.cc.
References StatisticsPoolingComponent::Check(), kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), StatisticsPoolingComponent::input_dim_, StatisticsPoolingComponent::input_period_, StatisticsPoolingComponent::left_context_, StatisticsPoolingComponent::num_log_count_features_, StatisticsPoolingComponent::output_stddevs_, kaldi::ReadBasicType(), StatisticsPoolingComponent::right_context_, and StatisticsPoolingComponent::variance_floor_.
{
   ExpectOneOrTwoTokens(is, binary, "<StatisticsPoolingComponent>",
                        "<InputDim>");
   ReadBasicType(is, binary, &input_dim_);
   ExpectToken(is, binary, "<InputPeriod>");
   ReadBasicType(is, binary, &input_period_);
   ExpectToken(is, binary, "<LeftContext>");
   ReadBasicType(is, binary, &left_context_);
   ExpectToken(is, binary, "<RightContext>");
   ReadBasicType(is, binary, &right_context_);
   ExpectToken(is, binary, "<NumLogCountFeatures>");
   ReadBasicType(is, binary, &num_log_count_features_);
   ExpectToken(is, binary, "<OutputStddevs>");
   ReadBasicType(is, binary, &output_stddevs_);
   ExpectToken(is, binary, "<VarianceFloor>");
   ReadBasicType(is, binary, &variance_floor_);
   ExpectToken(is, binary, "</StatisticsPoolingComponent>");
   Check();
 }
ReorderIndexes()
void ReorderIndexes (std::vector< Index > * input_indexes, std::vector< Index > * output_indexes) const virtual
This function only does something interesting for non-simple Components.
It provides an opportunity for a Component to reorder the or pad the indexes at its input and output. This might be useful, for instance, if a component requires a particular ordering of the indexes that doesn't correspond to their natural ordering. Components that might modify the indexes are required to return the kReordersIndexes flag in their Properties(). The ReorderIndexes() function is now allowed to insert blanks into the indexes. The 'blanks' must be of the form (n,kNoTime,x), where the marker kNoTime (a very negative number) is there where the 't' indexes normally live. The reason we don't just have, say, (-1,-1,-1), relates to the need to preserve a regular pattern over the 'n' indexes so that 'shortcut compilation' (c.f. ExpandComputation()) can work correctly
Parameters
[in,out] Indexes at the input of the Component.
[in,out] Indexes at the output of the Component
Reimplemented from Component.
Definition at line 639 of file nnet-general-component.cc.
{
     std::sort(input_indexes->begin(), input_indexes->end(),
               IndexLessNxt());
     std::sort(output_indexes->begin(), output_indexes->end(),
               IndexLessNxt());
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 349 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Info(), ConstantComponent::Info(), and BackpropTruncationComponent::InitFromConfig().
 { return "StatisticsPoolingComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 620 of file nnet-general-component.cc.
References StatisticsPoolingComponent::input_dim_, StatisticsPoolingComponent::input_period_, StatisticsPoolingComponent::left_context_, StatisticsPoolingComponent::num_log_count_features_, StatisticsPoolingComponent::output_stddevs_, StatisticsPoolingComponent::right_context_, StatisticsPoolingComponent::variance_floor_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<StatisticsPoolingComponent>");
   WriteToken(os, binary, "<InputDim>");
   WriteBasicType(os, binary, input_dim_);
   WriteToken(os, binary, "<InputPeriod>");
   WriteBasicType(os, binary, input_period_);
   WriteToken(os, binary, "<LeftContext>");
   WriteBasicType(os, binary, left_context_);
   WriteToken(os, binary, "<RightContext>");
   WriteBasicType(os, binary, right_context_);
   WriteToken(os, binary, "<NumLogCountFeatures>");
   WriteBasicType(os, binary, num_log_count_features_);
   WriteToken(os, binary, "<OutputStddevs>");
   WriteBasicType(os, binary, output_stddevs_);
   WriteToken(os, binary, "<VarianceFloor>");
   WriteBasicType(os, binary, variance_floor_);
   WriteToken(os, binary, "</StatisticsPoolingComponent>");
 }
Member Data Documentation
input_dim_
int32 input_dim_ private
Definition at line 407 of file nnet-general-component.h.
Referenced by StatisticsPoolingComponent::Backprop(), StatisticsPoolingComponent::Check(), StatisticsPoolingComponent::Propagate(), StatisticsPoolingComponent::Read(), and StatisticsPoolingComponent::Write().
input_period_
int32 input_period_ private
Definition at line 408 of file nnet-general-component.h.
Referenced by StatisticsPoolingComponent::Check(), StatisticsPoolingComponent::GetInputIndexes(), StatisticsPoolingComponent::IsComputable(), StatisticsPoolingComponent::PrecomputeIndexes(), StatisticsPoolingComponent::Read(), and StatisticsPoolingComponent::Write().
left_context_
int32 left_context_ private
Definition at line 409 of file nnet-general-component.h.
Referenced by StatisticsPoolingComponent::Check(), StatisticsPoolingComponent::GetInputIndexes(), StatisticsPoolingComponent::IsComputable(), StatisticsPoolingComponent::PrecomputeIndexes(), StatisticsPoolingComponent::Read(), and StatisticsPoolingComponent::Write().
num_log_count_features_
int32 num_log_count_features_ private
Definition at line 411 of file nnet-general-component.h.
Referenced by StatisticsPoolingComponent::Backprop(), StatisticsPoolingComponent::Propagate(), StatisticsPoolingComponent::Read(), and StatisticsPoolingComponent::Write().
output_stddevs_
bool output_stddevs_ private
Definition at line 412 of file nnet-general-component.h.
Referenced by StatisticsPoolingComponent::Backprop(), StatisticsPoolingComponent::Check(), StatisticsPoolingComponent::Propagate(), StatisticsPoolingComponent::Read(), and StatisticsPoolingComponent::Write().
right_context_
int32 right_context_ private
Definition at line 410 of file nnet-general-component.h.
Referenced by StatisticsPoolingComponent::Check(), StatisticsPoolingComponent::GetInputIndexes(), StatisticsPoolingComponent::IsComputable(), StatisticsPoolingComponent::PrecomputeIndexes(), StatisticsPoolingComponent::Read(), and StatisticsPoolingComponent::Write().
variance_floor_
BaseFloat variance_floor_ private
Definition at line 413 of file nnet-general-component.h.
Referenced by StatisticsPoolingComponent::Check(), StatisticsPoolingComponent::Propagate(), StatisticsPoolingComponent::Read(), and StatisticsPoolingComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc