Kaldi: NnetComputerFromEg Class Reference
NnetComputerFromEg Class Reference
Public Member Functions
NnetComputerFromEg (const Nnet &nnet)
void Compute (const NnetExample &eg, const std::string &output_name, Matrix< BaseFloat > *output)
NnetComputerFromEg (const Nnet &nnet)
void Compute (const NnetExample &eg, Matrix< BaseFloat > *output)
Private Attributes
const Nnet & nnet_
CachingOptimizingCompiler compiler_
Detailed Description
Definition at line 32 of file nnet3-compute-from-egs.cc.
Constructor & Destructor Documentation
NnetComputerFromEg() [1/2]
NnetComputerFromEg (const Nnet & nnet) inline
Definition at line 34 of file nnet3-compute-from-egs.cc.
Referenced by main().
                                       :
       nnet_(nnet), compiler_(nnet) { }
NnetComputerFromEg() [2/2]
NnetComputerFromEg (const Nnet & nnet) inline
Definition at line 34 of file nnet3-discriminative-compute-from-egs.cc.
                                       :
       nnet_(nnet), compiler_(nnet) { }
Member Function Documentation
Compute() [1/2]
void Compute (const NnetExample & eg, Matrix< BaseFloat > * output) inline
Definition at line 39 of file nnet3-discriminative-compute-from-egs.cc.
References NnetComputer::AcceptInputs(), CachingOptimizingCompiler::Compile(), NnetComputerFromEg::compiler_, CuMatrixBase< Real >::CopyToMat(), NnetComputeOptions::debug, kaldi::nnet3::GetComputationRequest(), kaldi::GetVerboseLevel(), NnetExample::io, NnetComputerFromEg::nnet_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and Matrix< Real >::Resize().
{
     ComputationRequest request;
     bool need_backprop = false, store_stats = false;
     GetComputationRequest(nnet_, eg, need_backprop, store_stats, &request);
     const NnetComputation &computation = *(compiler_.Compile(request));
     NnetComputeOptions options;
     if (GetVerboseLevel() >= 3)
       options.debug = true;
     NnetComputer computer(options, computation, nnet_, NULL);
     computer.AcceptInputs(nnet_, eg.io);
     computer.Run();
     const CuMatrixBase<BaseFloat> &nnet_output = computer.GetOutput("output");
     output->Resize(nnet_output.NumRows(), nnet_output.NumCols());
     nnet_output.CopyToMat(output);
   }
Compute() [2/2]
void Compute (const NnetExample & eg, const std::string & output_name, Matrix< BaseFloat > * output) inline
Definition at line 41 of file nnet3-compute-from-egs.cc.
References NnetComputer::AcceptInputs(), CachingOptimizingCompiler::Compile(), NnetComputerFromEg::compiler_, CuMatrixBase< Real >::CopyToMat(), NnetComputeOptions::debug, kaldi::nnet3::GetComputationRequest(), kaldi::GetVerboseLevel(), NnetExample::io, NnetComputerFromEg::nnet_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and Matrix< Real >::Resize().
Referenced by main().
{
     ComputationRequest request;
     bool need_backprop = false, store_stats = false;
     GetComputationRequest(nnet_, eg, need_backprop, store_stats, &request);
     const NnetComputation &computation = *(compiler_.Compile(request));
     NnetComputeOptions options;
     if (GetVerboseLevel() >= 3)
       options.debug = true;
     NnetComputer computer(options, computation, nnet_, NULL);
     computer.AcceptInputs(nnet_, eg.io);
     computer.Run();
     const CuMatrixBase<BaseFloat> &nnet_output = computer.GetOutput(output_name);
     output->Resize(nnet_output.NumRows(), nnet_output.NumCols());
     nnet_output.CopyToMat(output);
   }
Member Data Documentation
compiler_
CachingOptimizingCompiler compiler_ private
Definition at line 59 of file nnet3-compute-from-egs.cc.
Referenced by NnetComputerFromEg::Compute().
nnet_
const Nnet & nnet_ private
Definition at line 58 of file nnet3-compute-from-egs.cc.
Referenced by NnetComputerFromEg::Compute().
The documentation for this class was generated from the following files:
nnet3bin/nnet3-compute-from-egs.cc
nnet3bin/nnet3-discriminative-compute-from-egs.cc