Kaldi: Sgmm2GauPost Class Reference
Sgmm2GauPost Class Reference
indexed by time.
#include <am-sgmm2.h>
Public Member Functions
Sgmm2GauPost (size_t i)
Sgmm2GauPost ()
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
Detailed Description
indexed by time.
Definition at line 568 of file am-sgmm2.h.
Constructor & Destructor Documentation
Sgmm2GauPost() [1/2]
Sgmm2GauPost (size_t i) inline explicit
Definition at line 572 of file am-sgmm2.h.
 : std::vector<Sgmm2GauPostElement>(i) {}
Sgmm2GauPost() [2/2]
Sgmm2GauPost () inline
Definition at line 573 of file am-sgmm2.h.
 {}
Member Function Documentation
Read()
void Read (std::istream & is, bool binary)
Definition at line 1472 of file am-sgmm2.cc.
References kaldi::ExpectToken(), rnnlm::i, KALDI_ASSERT, kaldi::ReadBasicType(), kaldi::ReadIntegerVector(), and Sgmm2LikelihoodCache::t.
{
   ExpectToken(is, binary, "<Sgmm2GauPost>");
   int32 T;
   ReadBasicType(is, binary, &T);
   KALDI_ASSERT(T >= 0);
   this->resize(T);
   for (int32 t = 0; t < T; t++) {
     ExpectToken(is, binary, "<gselect>");
     ReadIntegerVector(is, binary, &((*this)[t].gselect));
     ExpectToken(is, binary, "<tids>");
     ReadIntegerVector(is, binary, &((*this)[t].tids));
     size_t sz = (*this)[t].tids.size();
     (*this)[t].posteriors.resize(sz);
     for (size_t i = 0; i < sz; i++)
       (*this)[t].posteriors[i].Read(is, binary);
   }
   ExpectToken(is, binary, "</Sgmm2GauPost>");
 }
Write()
void Write (std::ostream & os, bool binary) const
Definition at line 1454 of file am-sgmm2.cc.
References rnnlm::i, KALDI_ASSERT, Sgmm2LikelihoodCache::t, kaldi::WriteBasicType(), kaldi::WriteIntegerVector(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<Sgmm2GauPost>");
   int32 T = this->size();
   WriteBasicType(os, binary, T);
   for (int32 t = 0; t < T; t++) {
     WriteToken(os, binary, "<gselect>");
     WriteIntegerVector(os, binary, (*this)[t].gselect);
     WriteToken(os, binary, "<tids>");
     WriteIntegerVector(os, binary, (*this)[t].tids);
     KALDI_ASSERT((*this)[t].tids.size() == (*this)[t].posteriors.size());
     for (size_t i = 0; i < (*this)[t].posteriors.size(); i++) {
       (*this)[t].posteriors[i].Write(os, binary);
     }
   }
   WriteToken(os, binary, "</Sgmm2GauPost>");
 }
The documentation for this class was generated from the following files:
sgmm2/am-sgmm2.h
sgmm2/am-sgmm2.cc