Kaldi: TxpCexspec Class Reference
TxpCexspec Class Reference
#include <txpcexspec.h>
Public Member Functions
TxpCexspec ()
~TxpCexspec ()
void Init (const TxpParseOptions &opts, const std::string &name)
int32 MaxFeatureSize ()
return maximum width in bytes of feature string
enum CEXSPECPAU_HANDLER GetPauseHandling ()
int32 AddPauseNodes (pugi::xml_document *doc)
bool ExtractFeatures (const TxpCexspecContext &context, std::string *buf)
bool AppendValue (const TxpCexspecFeat &feat, bool error, const char *s, std::string *buf) const
bool AppendValue (const TxpCexspecFeat &feat, bool error, int32 i, std::string *buf) const
bool AppendNull (const TxpCexspecFeat &feat, std::string *buf) const
bool AppendError (const TxpCexspecFeat &feat, std::string *buf) const
const std::string Mapping (const TxpCexspecFeat &feat, const std::string &instr) const
void GetFunctionSpec (pugi::xml_node *header)
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
virtual void EndElement (const char *name)
Inherited class for bespoke end element handling.
virtual void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
virtual void StartCData ()
Inherited class for bespoke start cdata handling.
virtual void EndCData ()
Inherited class for bespoke start cdata handling.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
int32 GetFeatureIndex (const std::string &name)
utility to return index of a feature function
Private Attributes
LookupMapSet sets_
LookupMap setnull_
TxpCexspecFeatVector cexspecfeats_
LookupInt cexspecfeatlkp_
int32 cexspec_maxfieldlen_
enum CEXSPECPAU_HANDLER pauhand_
std::string curset_
std::string curfunc_
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
Definition at line 89 of file txpcexspec.h.
Constructor & Destructor Documentation
TxpCexspec()
TxpCexspec () inline explicit
Definition at line 91 of file txpcexspec.h.
                         :
       TxpXmlData(),
       cexspec_maxfieldlen_(CEXSPEC_MAXFIELDLEN),
       pauhand_(CEXSPECPAU_HANDLER_SPURT) {}
~TxpCexspec()
~TxpCexspec () inline
Definition at line 95 of file txpcexspec.h.
 {}
Member Function Documentation
AddPauseNodes()
int32 AddPauseNodes (pugi::xml_document * doc)
Definition at line 203 of file txpcexspec.cc.
References kaldi::CEXSPECPAU_HANDLER_UTTERANCE, and TxpCexspec::pauhand_.
Referenced by TxpCexspec::GetPauseHandling(), and TxpCex::Process().
{
   bool uttbreak, endbreak, internalbreak;
   pugi::xml_node node, childnode;
   pugi::xpath_node_set nodes =
       doc->document_element().select_nodes("//phon|//break");
   nodes.sort();
   for (pugi::xpath_node_set::const_iterator it = nodes.begin();
        it != nodes.end();
        ++it) {
     node = it->node();
     if (!strcmp(node.name(), "break")) {
       // determine break type
       if (!strcmp(node.attribute("type").value(), "4")) {
         uttbreak = true;
       } else {
         uttbreak = false;
       }
       if (it == nodes.begin()) {
         endbreak = false;
         internalbreak = false;
       } else if (it + 1 == nodes.end()) {
         endbreak = true;
         internalbreak = false;
       } else if (!strcmp((it - 1)->node().name(), "break")) {
         endbreak = false;
         internalbreak = true;
       } else {
         endbreak = true;
         internalbreak = true;
       }
       if (pauhand_ == CEXSPECPAU_HANDLER_UTTERANCE && !uttbreak &&
           internalbreak && !endbreak) continue;
       childnode = node.append_child("tk");
       childnode.append_attribute("pron").set_value("pau");
       childnode = childnode.append_child("syl");
       childnode.append_attribute("val").set_value("pau");
       childnode = childnode.append_child("phon");
       childnode.append_attribute("val").set_value("pau");
     }
   }
   return true;
 }
AppendError()
bool AppendError (const TxpCexspecFeat & feat, std::string * buf) const
Definition at line 303 of file txpcexspec.cc.
References CEXSPEC_ERROR, and TxpCexspecFeat::delim.
Referenced by TxpCexspec::AppendValue(), and TxpCexspec::GetPauseHandling().
{
   buf->append(feat.delim);
   buf->append(CEXSPEC_ERROR);
   return true;
 }
AppendNull()
bool AppendNull (const TxpCexspecFeat & feat, std::string * buf) const
Definition at line 297 of file txpcexspec.cc.
References TxpCexspecFeat::delim, TxpCexspec::Mapping(), and TxpCexspecFeat::nullvalue.
Referenced by kaldi::CexFuncStringBackwardBackwardPhone(), kaldi::CexFuncStringBackwardPhone(), kaldi::CexFuncStringForwardForwardPhone(), kaldi::CexFuncStringForwardPhone(), kaldi::CexFuncStringPhone(), kaldi::CexFuncStringPhraseTobiEndTone(), TxpCexspec::GetPauseHandling(), and kaldi::KaldiPhone().
{
   buf->append(feat.delim);
   buf->append(Mapping(feat, feat.nullvalue));
   return true;
 }
AppendValue() [1/2]
bool AppendValue (const TxpCexspecFeat & feat, bool error, const char * s, std::string * buf) const
Definition at line 268 of file txpcexspec.cc.
References TxpCexspec::AppendError(), TxpCexspecFeat::delim, rnnlm::i, TxpCexspec::Mapping(), TxpCexspecFeat::set, and TxpCexspec::sets_.
Referenced by kaldi::CexFuncIntBackwardSyllableNumPhones(), kaldi::CexFuncIntBackwardSyllableStress(), kaldi::CexFuncIntBackwardWordNumSyls(), kaldi::CexFuncIntForwardSyllableNumPhones(), kaldi::CexFuncIntForwardSyllableStress(), kaldi::CexFuncIntForwardWordNumSyls(), kaldi::CexFuncIntPhraseNumWords(), kaldi::CexFuncIntSegmentLocationFromBack(), kaldi::CexFuncIntSegmentLocationFromFront(), kaldi::CexFuncIntSyllableNumPhones(), kaldi::CexFuncIntSyllableStress(), kaldi::CexFuncIntWordNumSyls(), kaldi::CexFuncStringBackwardBackwardPhone(), kaldi::CexFuncStringBackwardPhone(), kaldi::CexFuncStringBackwardWordPosTag(), kaldi::CexFuncStringForwardForwardPhone(), kaldi::CexFuncStringForwardPhone(), kaldi::CexFuncStringForwardWordPosTag(), kaldi::CexFuncStringPhone(), kaldi::CexFuncStringPhraseTobiEndTone(), kaldi::CexFuncStringWordPosTag(), TxpCexspec::GetPauseHandling(), and kaldi::KaldiPhone().
{
   const StringSet* set;
   StringSet::iterator i;
   set = &(sets_.find(feat.set)->second);
   if (set->find(std::string(s)) == set->end()) {
     AppendError(feat, buf);
     return false;
   }
   buf->append(feat.delim);
   buf->append(Mapping(feat, s));
   return true;
 }
AppendValue() [2/2]
bool AppendValue (const TxpCexspecFeat & feat, bool error, int32 i, std::string * buf) const
Definition at line 282 of file txpcexspec.cc.
References TxpCexspec::AppendError(), kaldi::CEXSPEC_TYPE_INT, TxpCexspecFeat::delim, rnnlm::i, TxpCexspec::Mapping(), TxpCexspecFeat::max, TxpCexspecFeat::min, and TxpCexspecFeat::type.
{
   std::stringstream stream;
   if (feat.type != CEXSPEC_TYPE_INT) {
     AppendError(feat, buf);
     return false;
   }
   if (i < feat.min) i = feat.min;
   if (i > feat.max) i = feat.max;
   stream << i;
   buf->append(feat.delim);
   buf->append(Mapping(feat, stream.str()));
   return true;
 }
ExtractFeatures()
bool ExtractFeatures (const TxpCexspecContext & context, std::string * buf)
Definition at line 247 of file txpcexspec.cc.
References TxpCexspec::cexspecfeats_, and TxpCexspecFeat::func.
Referenced by TxpCexspec::GetPauseHandling(), and TxpCex::Process().
{
   TxpCexspecFeatVector::iterator iter;
   struct TxpCexspecFeat feat;
   bool rval = true;
   // iterate through features inserting nulls when required
   for (iter = cexspecfeats_.begin(); iter != cexspecfeats_.end(); ++iter) {
     feat = *iter;
     if (!feat.func(this, &feat, &context, buf))
       rval = false;
   }
   return rval;
 }
GetFeatureIndex()
int32 GetFeatureIndex (const std::string & name) private
utility to return index of a feature function
Definition at line 261 of file txpcexspec.cc.
References CEX_NO_FEATURES, kaldi::CEXFUNCLBL, rnnlm::i, and NO_INDEX.
Referenced by TxpCexspec::GetPauseHandling(), and TxpCexspec::StartElement().
{
   for (int i = 0; i < CEX_NO_FEATURES; i++) {
     if (!strcmp(CEXFUNCLBL[i], name.c_str())) return i;
   }
   return NO_INDEX;
 }
GetFunctionSpec()
void GetFunctionSpec (pugi::xml_node * header)
Definition at line 187 of file txpcexspec.cc.
References TxpCexspec::cexspecfeats_.
Referenced by TxpCexspec::GetPauseHandling(), and TxpCex::Process().
{
   TxpCexspecFeatVector::iterator iter;
   pugi::xml_node function;
   // iterate through features and add max size and delimiters
   for (iter = cexspecfeats_.begin(); iter != cexspecfeats_.end(); ++iter) {
     function = header->append_child("cexfunction");
     function.append_attribute("name").set_value((*iter).name.c_str());
     function.append_attribute("delim").set_value((*iter).delim.c_str());
     function.append_attribute("isinteger").set_value((*iter).type);
   }
 }
GetPauseHandling()
enum CEXSPECPAU_HANDLER GetPauseHandling () inline
Definition at line 102 of file txpcexspec.h.
References TxpCexspec::AddPauseNodes(), TxpCexspec::AppendError(), TxpCexspec::AppendNull(), TxpCexspec::AppendValue(), TxpCexspec::ExtractFeatures(), TxpCexspec::GetFeatureIndex(), TxpCexspec::GetFunctionSpec(), rnnlm::i, TxpCexspec::Mapping(), TxpCexspec::pauhand_, and TxpCexspec::StartElement().
Referenced by TxpCex::IsSptPauseHandling(), and TxpCex::Process().
 {return pauhand_;}
Init()
void Init (const TxpParseOptions & opts, const std::string & name) inline
Definition at line 96 of file txpcexspec.h.
References TxpXmlData::Init(), and TxpCexspec::MaxFeatureSize().
Referenced by TxpCex::Init(), and TxpCexspecModels::TxpCexspecModels().
{
     TxpXmlData::Init(opts, "cex", name);
   }
Mapping()
const std::string Mapping (const TxpCexspecFeat & feat, const std::string & instr) const
Definition at line 309 of file txpcexspec.cc.
References rnnlm::i, and TxpCexspecFeat::mapping.
Referenced by TxpCexspec::AppendNull(), TxpCexspec::AppendValue(), and TxpCexspec::GetPauseHandling().
{
   LookupMap::const_iterator i;
   i = feat.mapping.find(instr);
   if (i != feat.mapping.end()) {
     return i->second;
   } else {
     return instr;
   }
 }
MaxFeatureSize()
int32 MaxFeatureSize ()
return maximum width in bytes of feature string
Definition at line 176 of file txpcexspec.cc.
References CEXSPEC_MAXFIELDLEN, and TxpCexspec::cexspecfeats_.
Referenced by TxpCexspec::Init(), and TxpCexspecModels::Init().
{
   int32 maxsize = 0;
   TxpCexspecFeatVector::iterator iter;
   // iterate through features and add max size and delimiters
   for (iter = cexspecfeats_.begin(); iter != cexspecfeats_.end(); ++iter) {
     maxsize += CEXSPEC_MAXFIELDLEN;
     maxsize += (*iter).delim.size();
   }
   return maxsize;
 }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 26 of file txpcexspec.cc.
References kaldi::CEXFUNC, kaldi::CEXFUNCTYPE, TxpCexspec::cexspec_maxfieldlen_, CEXSPEC_NULL, kaldi::CEXSPEC_TYPE_INT, kaldi::CEXSPEC_TYPE_STR, TxpCexspec::cexspecfeatlkp_, TxpCexspec::cexspecfeats_, kaldi::CEXSPECPAU_HANDLER_UTTERANCE, TxpCexspec::curfunc_, TxpCexspec::curset_, TxpCexspecFeat::delim, TxpCexspecFeat::desc, TxpCexspecFeat::func, TxpCexspec::GetFeatureIndex(), TxpCexspecFeat::htsname, KALDI_WARN, TxpCexspecFeat::max, TxpCexspecFeat::min, TxpCexspecFeat::name, NO_INDEX, TxpCexspecFeat::nullvalue, TxpXmlData::parser_, TxpCexspec::pauhand_, TxpCexspecFeat::pause_context, TxpCexspecFeat::set, TxpXmlData::SetAttribute(), TxpCexspec::setnull_, TxpCexspec::sets_, and TxpCexspecFeat::type.
Referenced by TxpCexspec::GetPauseHandling().
{
   std::string att, att2;
   StringSet* set;
   TxpCexspecFeat feat;
   int32 featidx;
   // add features and other definitions
   // top level behaviour
   if (!strcmp(name, "cex")) {
     SetAttribute("maxfieldlen", atts, &att);
     if (!att.empty()) {
       cexspec_maxfieldlen_ = atoi(att.c_str());
     }
     SetAttribute("pausehandling", atts, &att);
     if (!att.empty()) {
       if (!strcmp(att.c_str(), "UTT")) {
         pauhand_ = CEXSPECPAU_HANDLER_UTTERANCE;
       }
     }
     // sets for string based feature functions
   } else if (!strcmp(name, "set")) {
     SetAttribute("name", atts, &att);
     if (att.empty()) {
       // throw an error
       KALDI_WARN << "Badly formed cex set: "
                  << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                  << " Col:" << XML_GetCurrentColumnNumber(parser_);
       return;
     }
     curset_ = att;
     SetAttribute("null", atts, &att);
     if (!att2.empty()) {
       att = CEXSPEC_NULL;
     }
     sets_.insert(LookupMapSetItem(curset_, StringSet()));
     setnull_.insert(LookupItem(curset_, att));
     // features
   } else if (!strcmp(name, "item")) {
     SetAttribute("name", atts, &att);
     if (att.empty()) {
       // throw an error
       KALDI_WARN << "Badly formed cex set item: "
                  << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                  << " Col:" << XML_GetCurrentColumnNumber(parser_);
       return;
     }
     set = &(sets_.find(curset_)->second);
     set->insert(att);
   } else if (!strcmp(name, "feat")) {
     SetAttribute("name", atts, &att);
     feat.name = att;
     if (att.empty()) {
       // throw an error
       KALDI_WARN << "Badly formed cex set item: "
                  << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                  << " Col:" << XML_GetCurrentColumnNumber(parser_);
       return;
     }
     featidx = GetFeatureIndex(att);
     if (featidx == NO_INDEX) {
       curfunc_ = "";
       // throw an error
       KALDI_WARN << "Missing feature in architecture: " << att
                  << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                  << " Col:" << XML_GetCurrentColumnNumber(parser_);
       return;
     }
     // valid function try to add rest of the features specification
     curfunc_ = att;
     SetAttribute("htsname", atts, &att);
     feat.htsname = att;
     SetAttribute("desc", atts, &att);
     feat.desc = att;
     SetAttribute("delim", atts, &att);
     if (att.empty() && cexspecfeats_.size()) {
       // throw an error
       KALDI_WARN << "Missing delimiter for feature architecture: " << curfunc_
                  << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                  << " Col:" << XML_GetCurrentColumnNumber(parser_);
       return;
     }
     feat.delim = att;
     feat.func = CEXFUNC[featidx];
     feat.pause_context = false;
     SetAttribute("pauctx", atts, &att);
     if (att == "true" || att == "True" || att == "TRUE") {
       feat.pause_context = true;
     }
     SetAttribute("pauctx", atts, &att2);
     feat.type = CEXFUNCTYPE[featidx];
     if (feat.type == CEXSPEC_TYPE_STR) {
       SetAttribute("set", atts, &att);
       if (att.empty()) {
         // throw an error
         KALDI_WARN << "Missing set name for string feature architecture: "
                    << curfunc_
                    << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                    << " Col:" << XML_GetCurrentColumnNumber(parser_);
         return;
       }
       // check set has been added
       if (sets_.find(att) == sets_.end()) {
         // throw an error
         KALDI_WARN << "Missing set for string feature architecture: "
                    << curfunc_
                    << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                    << " Col:" << XML_GetCurrentColumnNumber(parser_)
                    << " (must define before function)";
         return;
       }
       feat.set = att;
       feat.nullvalue = setnull_.find(att)->second;
     } else if (feat.type == CEXSPEC_TYPE_INT) {
       SetAttribute("min", atts, &att);
       if (!att.empty()) feat.min = atoi(att.c_str());
       SetAttribute("max", atts, &att);
       if (att.empty()) {
         // throw an error
         KALDI_WARN << "Missing maximum value for integer feature architecture: "
                    << curfunc_
                    << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                    << " Col:" << XML_GetCurrentColumnNumber(parser_);
         return;
       }
       feat.max = atoi(att.c_str());
     }
     // if we have got to here the feature is valid add it to the architecture
     cexspecfeatlkp_.insert(LookupIntItem(curfunc_, cexspecfeats_.size()));
     cexspecfeats_.push_back(feat);
   } else if (!strcmp(name, "mapping")) {
     SetAttribute("fromstr", atts, &att);
     SetAttribute("tostr", atts, &att2);
     if (att.empty() || att2.empty()) {
       // throw an error
       KALDI_WARN << "bad mapping item: " << curfunc_
                  << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                  << " Col:" << XML_GetCurrentColumnNumber(parser_);
       return;
     }
     if (!curfunc_.empty()) {
       LookupInt::iterator iter;
       iter = cexspecfeatlkp_.find(curfunc_);
       if (iter != cexspecfeatlkp_.end()) {
         cexspecfeats_[iter->second].mapping.insert(LookupItem(att, att2));
       }
     }
   }
 }
Member Data Documentation
cexspec_maxfieldlen_
int32 cexspec_maxfieldlen_ private
Definition at line 137 of file txpcexspec.h.
Referenced by TxpCexspec::StartElement().
cexspecfeatlkp_
LookupInt cexspecfeatlkp_ private
Definition at line 135 of file txpcexspec.h.
Referenced by TxpCexspec::StartElement().
cexspecfeats_
TxpCexspecFeatVector cexspecfeats_ private
Definition at line 133 of file txpcexspec.h.
Referenced by TxpCexspec::ExtractFeatures(), TxpCexspec::GetFunctionSpec(), TxpCexspec::MaxFeatureSize(), and TxpCexspec::StartElement().
curfunc_
std::string curfunc_ private
Definition at line 143 of file txpcexspec.h.
Referenced by TxpCexspec::StartElement().
curset_
std::string curset_ private
Definition at line 141 of file txpcexspec.h.
Referenced by TxpCexspec::StartElement().
pauhand_
enum CEXSPECPAU_HANDLER pauhand_ private
Definition at line 139 of file txpcexspec.h.
Referenced by TxpCexspec::AddPauseNodes(), TxpCexspec::GetPauseHandling(), and TxpCexspec::StartElement().
setnull_
LookupMap setnull_ private
Definition at line 131 of file txpcexspec.h.
Referenced by TxpCexspec::StartElement().
sets_
LookupMapSet sets_ private
Definition at line 129 of file txpcexspec.h.
Referenced by TxpCexspec::AppendValue(), and TxpCexspec::StartElement().
The documentation for this class was generated from the following files:
idlaktxp/txpcexspec.h
idlaktxp/txpcexspec.cc