Kaldi: Clusterable Class Reference
Clusterable Class Reference abstract
Classes and functions related to clustering
#include <clusterable-itf.h>
Public Member Functions
Functions that must be overridden
virtual Clusterable * Copy () const =0
Return a copy of this object.
virtual BaseFloat Objf () const =0
Return the objective function associated with the stats [assuming ML estimation].
virtual BaseFloat Normalizer () const =0
Return the normalizer (typically, count) associated with the stats.
virtual void SetZero ()=0
Set stats to empty.
virtual void Add (const Clusterable &other)=0
Add other stats.
virtual void Sub (const Clusterable &other)=0
Subtract other stats.
virtual void Scale (BaseFloat f)
Scale the stats by a positive number f [not mandatory to supply this].
virtual std::string Type () const =0
Return a string that describes the inherited type.
virtual void Write (std::ostream &os, bool binary) const =0
Write data to stream.
virtual Clusterable * ReadNew (std::istream &os, bool binary) const =0
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
virtual ~Clusterable ()
Functions that have default implementations
virtual BaseFloat ObjfPlus (const Clusterable &other) const
Return the objective function of the combined object this + other.
virtual BaseFloat ObjfMinus (const Clusterable &other) const
Return the objective function of the subtracted object this - other.
virtual BaseFloat Distance (const Clusterable &other) const
Return the objective function decrease from merging the two clusters, negated to be a positive number (or zero).
Detailed Description
Definition at line 38 of file clusterable-itf.h.
Constructor & Destructor Documentation
~Clusterable()
virtual ~Clusterable () inline virtual
Definition at line 72 of file clusterable-itf.h.
References Clusterable::Distance(), Clusterable::ObjfMinus(), and Clusterable::ObjfPlus().
 {}
Member Function Documentation
Add()
virtual void Add (const Clusterable & other) pure virtual
Add other stats.
Implemented in VectorClusterable, GaussClusterable, and ScalarClusterable.
Referenced by kaldi::AddToClustersOptimized(), Clusterable::Distance(), RefineClusterer::InitPoint(), main(), Clusterable::ObjfPlus(), kaldi::SumClusterable(), kaldi::SumStats(), kaldi::TestClusterUtils(), kaldi::TestClusterUtilsVector(), kaldi::TestContextDep(), and RefineClusterer::UpdateInfo().
Copy()
virtual Clusterable* Copy () const pure virtual
Return a copy of this object.
Implemented in VectorClusterable, GaussClusterable, and ScalarClusterable.
Referenced by kaldi::AddToClustersOptimized(), Clusterable::Distance(), kaldi::EnsureClusterableVectorNotNull(), RefineClusterer::InitPoint(), Clusterable::ObjfMinus(), Clusterable::ObjfPlus(), kaldi::SumClusterable(), kaldi::SumStats(), kaldi::TestClusterUtils(), kaldi::TestClusterUtilsVector(), kaldi::TestContextDep(), and RefineClusterer::UpdateInfo().
Distance()
BaseFloat Distance (const Clusterable & other) const virtual
Return the objective function decrease from merging the two clusters, negated to be a positive number (or zero).
Definition at line 49 of file clusterable-classes.cc.
References Clusterable::Add(), Clusterable::Copy(), KALDI_WARN, and Clusterable::Objf().
Referenced by DecisionTreeSplitter::DoSplitInternal(), and Clusterable::~Clusterable().
{
   Clusterable *copy = this->Copy();
   copy->Add(other);
   BaseFloat ans = this->Objf() + other.Objf() - copy->Objf();
   if (ans < 0) {
     // This should not happen. Check if it is more than just rounding error.
     if (std::fabs(ans) > 0.01 * (1.0 + std::fabs(copy->Objf()))) {
       KALDI_WARN << "Negative number returned (badly defined Clusterable "
                  << "class?): ans= " << ans;
     }
     ans = 0;
   }
   delete copy;
   return ans;
 }
Normalizer()
virtual BaseFloat Normalizer () const pure virtual
Return the normalizer (typically, count) associated with the stats.
Implemented in VectorClusterable, GaussClusterable, and ScalarClusterable.
Referenced by kaldi::AddToClustersOptimized(), kaldi::SumNormalizer(), kaldi::TestClusterUtils(), kaldi::TestClusterUtilsVector(), and kaldi::TestContextDep().
Objf()
virtual BaseFloat Objf () const pure virtual
Return the objective function associated with the stats [assuming ML estimation].
Implemented in VectorClusterable, GaussClusterable, and ScalarClusterable.
Referenced by kaldi::ClusterKMeansOnce(), kaldi::ComputeInitialSplit(), Clusterable::Distance(), Clusterable::ObjfMinus(), Clusterable::ObjfPlus(), kaldi::SumObjf(), kaldi::TestClusterUtils(), kaldi::TestClusterUtilsVector(), kaldi::TestContextDep(), kaldi::TestSum(), and RefineClusterer::UpdateInfo().
ObjfMinus()
BaseFloat ObjfMinus (const Clusterable & other) const virtual
Return the objective function of the subtracted object this - other.
Definition at line 41 of file clusterable-classes.cc.
References Clusterable::Copy(), Clusterable::Objf(), and Clusterable::Sub().
Referenced by Clusterable::~Clusterable().
{
   Clusterable *copy = this->Copy();
   copy->Sub(other);
   BaseFloat ans = copy->Objf();
   delete copy;
   return ans;
 }
ObjfPlus()
BaseFloat ObjfPlus (const Clusterable & other) const virtual
Return the objective function of the combined object this + other.
Definition at line 33 of file clusterable-classes.cc.
References Clusterable::Add(), Clusterable::Copy(), and Clusterable::Objf().
Referenced by Clusterable::~Clusterable().
{
   Clusterable *copy = this->Copy();
   copy->Add(other);
   BaseFloat ans = copy->Objf();
   delete copy;
   return ans;
 }
ReadNew()
virtual Clusterable* ReadNew (std::istream & os, bool binary) const pure virtual
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
Implemented in VectorClusterable, GaussClusterable, and ScalarClusterable.
Referenced by kaldi::ReadBuildTreeStats(), and Clusterable::Scale().
Scale()
virtual void Scale (BaseFloat f) inline virtual
Scale the stats by a positive number f [not mandatory to supply this].
Reimplemented in VectorClusterable, and GaussClusterable.
Definition at line 57 of file clusterable-itf.h.
References KALDI_ERR, Clusterable::ReadNew(), Clusterable::Type(), and Clusterable::Write().
Referenced by GaussClusterable::Normalizer().
{
     KALDI_ERR << "This Clusterable object does not implement Scale().";
   }
SetZero()
virtual void SetZero () pure virtual
Set stats to empty.
Implemented in VectorClusterable, GaussClusterable, and ScalarClusterable.
Referenced by kaldi::EnsureClusterableVectorNotNull().
Sub()
virtual void Sub (const Clusterable & other) pure virtual
Subtract other stats.
Implemented in VectorClusterable, GaussClusterable, and ScalarClusterable.
Referenced by Clusterable::ObjfMinus(), and RefineClusterer::UpdateInfo().
Type()
virtual std::string Type () const pure virtual
Return a string that describes the inherited type.
Implemented in VectorClusterable, GaussClusterable, and ScalarClusterable.
Referenced by ScalarClusterable::Add(), GaussClusterable::Add(), VectorClusterable::Add(), Clusterable::Scale(), ScalarClusterable::Sub(), GaussClusterable::Sub(), and VectorClusterable::Sub().
Write()
virtual void Write (std::ostream & os, bool binary) const pure virtual
Write data to stream.
Implemented in VectorClusterable, GaussClusterable, and ScalarClusterable.
Referenced by Clusterable::Scale().
The documentation for this class was generated from the following files:
itf/clusterable-itf.h
tree/clusterable-classes.cc