Kaldi: MaxpoolingComponent Class Reference
MaxpoolingComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
MaxpoolingComponent ()
MaxpoolingComponent (const MaxpoolingComponent &component)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Member Functions
void InputToInputPatches (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *patches) const
void InderivPatchesToInderiv (const CuMatrix< BaseFloat > &in_deriv_patches, CuMatrixBase< BaseFloat > *in_deriv) const
virtual void Check () const
Protected Attributes
int32 input_x_dim_
int32 input_y_dim_
int32 input_z_dim_
int32 pool_x_size_
int32 pool_y_size_
int32 pool_z_size_
int32 pool_x_step_
int32 pool_y_step_
int32 pool_z_step_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 2398 of file nnet-simple-component.h.
Constructor & Destructor Documentation
MaxpoolingComponent() [1/2]
MaxpoolingComponent () inline
Definition at line 2401 of file nnet-simple-component.h.
References Component::Info(), PnormComponent::InitFromConfig(), PnormComponent::InputDim(), and PnormComponent::OutputDim().
                        : input_x_dim_(0), input_y_dim_(0), input_z_dim_(0),
                            pool_x_size_(0), pool_y_size_(0), pool_z_size_(0),
                            pool_x_step_(0), pool_y_step_(0), pool_z_step_(0) { }
MaxpoolingComponent() [2/2]
MaxpoolingComponent (const MaxpoolingComponent & component)
Definition at line 4609 of file nnet-simple-component.cc.
                                          :
     input_x_dim_(component.input_x_dim_),
     input_y_dim_(component.input_y_dim_),
     input_z_dim_(component.input_z_dim_),
     pool_x_size_(component.pool_x_size_),
     pool_y_size_(component.pool_y_size_),
     pool_z_size_(component.pool_z_size_),
     pool_x_step_(component.pool_x_step_),
     pool_y_step_(component.pool_y_step_),
     pool_z_step_(component.pool_z_step_) { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 4786 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::EqualElementMask(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::InputToInputPatches(), kaldi::kUndefined, CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::NumRows(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_y_size_, and MaxpoolingComponent::pool_z_size_.
Referenced by CompositeComponent::Backprop().
{
   if (!in_deriv)
     return;
   int32 num_frames = in_value.NumRows();
   int32 num_pools = OutputDim();
   int32 pool_size = pool_x_size_ * pool_y_size_ * pool_z_size_;
   CuMatrix<BaseFloat> patches(num_frames, num_pools * pool_size, kUndefined);
   InputToInputPatches(in_value, &patches);
   for (int32 q = 0; q < pool_size; q++) {
     // zero-out mask
     CuMatrix<BaseFloat> mask;
     out_value.EqualElementMask(patches.ColRange(q * num_pools, num_pools), &mask);
     mask.MulElements(out_deriv);
     patches.ColRange(q * num_pools, num_pools).CopyFromMat(mask);
   }
   // combine the derivatives from the individual input deriv patches
   // to compute input deriv matrix
   InderivPatchesToInderiv(patches, in_deriv);
 }
Check()
void Check () const protected virtual
Definition at line 4630 of file nnet-simple-component.cc.
References MaxpoolingComponent::input_x_dim_, MaxpoolingComponent::input_y_dim_, MaxpoolingComponent::input_z_dim_, KALDI_ASSERT, MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_x_step_, MaxpoolingComponent::pool_y_size_, MaxpoolingComponent::pool_y_step_, MaxpoolingComponent::pool_z_size_, and MaxpoolingComponent::pool_z_step_.
Referenced by MaxpoolingComponent::InitFromConfig(), and MaxpoolingComponent::Read().
{
   // sanity check of the max pooling parameters
   KALDI_ASSERT(input_x_dim_ > 0);
   KALDI_ASSERT(input_y_dim_ > 0);
   KALDI_ASSERT(input_z_dim_ > 0);
   KALDI_ASSERT(pool_x_size_ > 0);
   KALDI_ASSERT(pool_y_size_ > 0);
   KALDI_ASSERT(pool_z_size_ > 0);
   KALDI_ASSERT(pool_x_step_ > 0);
   KALDI_ASSERT(pool_y_step_ > 0);
   KALDI_ASSERT(pool_z_step_ > 0);
   KALDI_ASSERT(input_x_dim_ >= pool_x_size_);
   KALDI_ASSERT(input_y_dim_ >= pool_y_size_);
   KALDI_ASSERT(input_z_dim_ >= pool_z_size_);
   KALDI_ASSERT(pool_x_size_ >= pool_x_step_);
   KALDI_ASSERT(pool_y_size_ >= pool_y_step_);
   KALDI_ASSERT(pool_z_size_ >= pool_z_step_);
   KALDI_ASSERT((input_x_dim_ - pool_x_size_) % pool_x_step_  == 0);
   KALDI_ASSERT((input_y_dim_ - pool_y_size_) % pool_y_step_  == 0);
   KALDI_ASSERT((input_z_dim_ - pool_z_size_) % pool_z_step_  == 0);
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 2435 of file nnet-simple-component.h.
Referenced by CompositeComponent::Copy().
 { return new MaxpoolingComponent(*this); }
InderivPatchesToInderiv()
void InderivPatchesToInderiv (const CuMatrix< BaseFloat > & in_deriv_patches, CuMatrixBase< BaseFloat > * in_deriv) const protected
Definition at line 4739 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddCols(), MaxpoolingComponent::input_x_dim_, MaxpoolingComponent::input_y_dim_, MaxpoolingComponent::input_z_dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_x_step_, MaxpoolingComponent::pool_y_size_, MaxpoolingComponent::pool_y_step_, MaxpoolingComponent::pool_z_size_, MaxpoolingComponent::pool_z_step_, and kaldi::nnet3::RearrangeIndexes().
Referenced by MaxpoolingComponent::Backprop().
{
   int32 num_pools_x = 1 + (input_x_dim_ - pool_x_size_) / pool_x_step_;
   int32 num_pools_y = 1 + (input_y_dim_ - pool_y_size_) / pool_y_step_;
   int32 num_pools_z = 1 + (input_z_dim_ - pool_z_size_) / pool_z_step_;
   std::vector<std::vector<int32> > reverse_column_map(in_deriv->NumCols());
   int32 rev_col_map_size = reverse_column_map.size();
   for (int32 x = 0, index = 0; x < pool_x_size_; x++) {
     for (int32 y = 0; y < pool_y_size_; y++) {
       for (int32 z = 0; z < pool_z_size_; z++) {
         for (int32 x_pool = 0; x_pool < num_pools_x; x_pool++) {
           for (int32 y_pool = 0; y_pool < num_pools_y; y_pool++) {
             for (int32 z_pool = 0; z_pool < num_pools_z; z_pool++, index++) {
               int32 vector_index = (x_pool * pool_x_step_ + x) * input_y_dim_ * input_z_dim_ +
                                   (y_pool * pool_y_step_ + y) * input_z_dim_ +
                                   (z_pool * pool_z_step_ + z);
               KALDI_ASSERT(vector_index < rev_col_map_size);
               reverse_column_map[vector_index].push_back(index);
             }
           }
         }
       }
     }
   }
   std::vector<std::vector<int32> > rearranged_column_map;
   RearrangeIndexes(reverse_column_map, &rearranged_column_map);
   for (int32 p = 0; p < rearranged_column_map.size(); p++) {
     CuArray<int32> cu_cols(rearranged_column_map[p]);
     in_deriv->AddCols(in_deriv_patches, cu_cols);
   }
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 4863 of file nnet-simple-component.cc.
References MaxpoolingComponent::input_x_dim_, MaxpoolingComponent::input_y_dim_, MaxpoolingComponent::input_z_dim_, MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_x_step_, MaxpoolingComponent::pool_y_size_, MaxpoolingComponent::pool_y_step_, MaxpoolingComponent::pool_z_size_, MaxpoolingComponent::pool_z_step_, and MaxpoolingComponent::Type().
Referenced by CompositeComponent::Info().
{
   std::ostringstream stream;
   stream << Type()
          << ", input-x-dim=" << input_x_dim_
          << ", input-y-dim=" << input_y_dim_
          << ", input-z-dim=" << input_z_dim_
          << ", pool-x-size=" << pool_x_size_
          << ", pool-y-size=" << pool_y_size_
          << ", pool-z-size=" << pool_z_size_
          << ", pool-x-step=" << pool_x_step_
          << ", pool-y-step=" << pool_y_step_
          << ", pool-z-step=" << pool_z_step_;
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 4653 of file nnet-simple-component.cc.
References MaxpoolingComponent::Check(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), MaxpoolingComponent::input_x_dim_, MaxpoolingComponent::input_y_dim_, MaxpoolingComponent::input_z_dim_, KALDI_ERR, MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_x_step_, MaxpoolingComponent::pool_y_size_, MaxpoolingComponent::pool_y_step_, MaxpoolingComponent::pool_z_size_, MaxpoolingComponent::pool_z_step_, ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   bool ok = true;
   ok = ok && cfl->GetValue("input-x-dim", &input_x_dim_);
   ok = ok && cfl->GetValue("input-y-dim", &input_y_dim_);
   ok = ok && cfl->GetValue("input-z-dim", &input_z_dim_);
   ok = ok && cfl->GetValue("pool-x-size", &pool_x_size_);
   ok = ok && cfl->GetValue("pool-y-size", &pool_y_size_);
   ok = ok && cfl->GetValue("pool-z-size", &pool_z_size_);
   ok = ok && cfl->GetValue("pool-x-step", &pool_x_step_);
   ok = ok && cfl->GetValue("pool-y-step", &pool_y_step_);
   ok = ok && cfl->GetValue("pool-z-step", &pool_z_step_);
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   if (!ok)
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
   Check();
 }
InputDim()
int32 InputDim () const virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 4605 of file nnet-simple-component.cc.
References ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, and ConvolutionComponent::input_z_dim_.
Referenced by CompositeComponent::Backprop(), CompositeComponent::Init(), and CompositeComponent::Propagate().
{
   return input_x_dim_ * input_y_dim_ * input_z_dim_;
 }
InputToInputPatches()
void InputToInputPatches (const CuMatrixBase< BaseFloat > & in, CuMatrix< BaseFloat > * patches) const protected
Definition at line 4678 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyCols(), MaxpoolingComponent::input_x_dim_, MaxpoolingComponent::input_y_dim_, MaxpoolingComponent::input_z_dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_x_step_, MaxpoolingComponent::pool_y_size_, MaxpoolingComponent::pool_y_step_, MaxpoolingComponent::pool_z_size_, and MaxpoolingComponent::pool_z_step_.
Referenced by MaxpoolingComponent::Backprop(), and MaxpoolingComponent::Propagate().
{
   int32 num_pools_x = 1 + (input_x_dim_ - pool_x_size_) / pool_x_step_;
   int32 num_pools_y = 1 + (input_y_dim_ - pool_y_size_) / pool_y_step_;
   int32 num_pools_z = 1 + (input_z_dim_ - pool_z_size_) / pool_z_step_;
   std::vector<int32> column_map(patches->NumCols());
   int32 column_map_size = column_map.size();
   for (int32 x = 0, index =0; x < pool_x_size_; x++) {
     for (int32 y = 0; y < pool_y_size_; y++) {
       for (int32 z = 0; z < pool_z_size_; z++) {
         // given the local node coordinate, group them from each pool
         // to form a patch
         for (int32 x_pool = 0; x_pool < num_pools_x; x_pool++) {
           for (int32 y_pool = 0; y_pool < num_pools_y; y_pool++) {
             for (int32 z_pool = 0; z_pool < num_pools_z; z_pool++, index++) {
               KALDI_ASSERT(index < column_map_size);
               column_map[index] = (x_pool * pool_x_step_ + x) * input_y_dim_ * input_z_dim_ +
                                   (y_pool * pool_y_step_ + y) * input_z_dim_ +
                                   (z_pool * pool_z_step_ + z);
             }
           }
         }
       }
     }
   }
   CuArray<int32> cu_cols(column_map);
   patches->CopyCols(in, cu_cols);
 }
OutputDim()
int32 OutputDim () const virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 4622 of file nnet-simple-component.cc.
References MaxpoolingComponent::input_x_dim_, MaxpoolingComponent::input_y_dim_, MaxpoolingComponent::input_z_dim_, MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_x_step_, MaxpoolingComponent::pool_y_size_, MaxpoolingComponent::pool_y_step_, MaxpoolingComponent::pool_z_size_, and MaxpoolingComponent::pool_z_step_.
Referenced by MaxpoolingComponent::Backprop(), CompositeComponent::Backprop(), CompositeComponent::Init(), MaxpoolingComponent::Propagate(), and CompositeComponent::Propagate().
{
   int32 num_pools_x = 1 + (input_x_dim_ - pool_x_size_) / pool_x_step_;
   int32 num_pools_y = 1 + (input_y_dim_ - pool_y_size_) / pool_y_step_;
   int32 num_pools_z = 1 + (input_z_dim_ - pool_z_size_) / pool_z_step_;
   return num_pools_x * num_pools_y * num_pools_z;
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 4721 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::ColRange(), MaxpoolingComponent::InputToInputPatches(), kaldi::kUndefined, CuMatrixBase< Real >::Max(), CuMatrixBase< Real >::NumRows(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_y_size_, MaxpoolingComponent::pool_z_size_, and CuMatrixBase< Real >::Set().
Referenced by CompositeComponent::Propagate().
{
   int32 num_frames = in.NumRows();
   int32 num_pools = OutputDim();
   int32 pool_size = pool_x_size_ * pool_y_size_ * pool_z_size_;
   CuMatrix<BaseFloat> patches(num_frames, num_pools * pool_size, kUndefined);
   InputToInputPatches(in, &patches);
   out->Set(-1e20); // reset a large negative value
   for (int32 q = 0; q < pool_size; q++)
     out->Max(patches.ColRange(q * num_pools, num_pools));
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 2413 of file nnet-simple-component.h.
References PnormComponent::Backprop(), kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kBackpropNeedsOutput, kaldi::nnet3::kSimpleComponent, PnormComponent::Propagate(), PnormComponent::Read(), and PnormComponent::Write().
Referenced by CompositeComponent::Backprop(), CompositeComponent::DotProduct(), CompositeComponent::FreezeNaturalGradient(), CompositeComponent::GetStrideType(), CompositeComponent::Init(), CompositeComponent::NumParameters(), CompositeComponent::PerturbParams(), CompositeComponent::SetActualLearningRate(), CompositeComponent::SetAsGradient(), CompositeComponent::SetUnderlyingLearningRate(), CompositeComponent::UnVectorize(), and CompositeComponent::Vectorize().
{
     return kSimpleComponent|kBackpropNeedsInput|kBackpropNeedsOutput|
            kBackpropAdds;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 4816 of file nnet-simple-component.cc.
References MaxpoolingComponent::Check(), kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), MaxpoolingComponent::input_x_dim_, MaxpoolingComponent::input_y_dim_, MaxpoolingComponent::input_z_dim_, MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_x_step_, MaxpoolingComponent::pool_y_size_, MaxpoolingComponent::pool_y_step_, MaxpoolingComponent::pool_z_size_, MaxpoolingComponent::pool_z_step_, and kaldi::ReadBasicType().
{
   ExpectOneOrTwoTokens(is, binary, "<MaxpoolingComponent>", "<InputXDim>");
   ReadBasicType(is, binary, &input_x_dim_);
   ExpectToken(is, binary, "<InputYDim>");
   ReadBasicType(is, binary, &input_y_dim_);
   ExpectToken(is, binary, "<InputZDim>");
   ReadBasicType(is, binary, &input_z_dim_);
   ExpectToken(is, binary, "<PoolXSize>");
   ReadBasicType(is, binary, &pool_x_size_);
   ExpectToken(is, binary, "<PoolYSize>");
   ReadBasicType(is, binary, &pool_y_size_);
   ExpectToken(is, binary, "<PoolZSize>");
   ReadBasicType(is, binary, &pool_z_size_);
   ExpectToken(is, binary, "<PoolXStep>");
   ReadBasicType(is, binary, &pool_x_step_);
   ExpectToken(is, binary, "<PoolYStep>");
   ReadBasicType(is, binary, &pool_y_step_);
   ExpectToken(is, binary, "<PoolZStep>");
   ReadBasicType(is, binary, &pool_z_step_);
   ExpectToken(is, binary, "</MaxpoolingComponent>");
   Check();
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 2412 of file nnet-simple-component.h.
Referenced by PermuteComponent::Info(), MaxpoolingComponent::Info(), CompositeComponent::Info(), and PermuteComponent::InitFromConfig().
 { return "MaxpoolingComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 4839 of file nnet-simple-component.cc.
References MaxpoolingComponent::input_x_dim_, MaxpoolingComponent::input_y_dim_, MaxpoolingComponent::input_z_dim_, MaxpoolingComponent::pool_x_size_, MaxpoolingComponent::pool_x_step_, MaxpoolingComponent::pool_y_size_, MaxpoolingComponent::pool_y_step_, MaxpoolingComponent::pool_z_size_, MaxpoolingComponent::pool_z_step_, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by CompositeComponent::Write().
{
   WriteToken(os, binary, "<MaxpoolingComponent>");
   WriteToken(os, binary, "<InputXDim>");
   WriteBasicType(os, binary, input_x_dim_);
   WriteToken(os, binary, "<InputYDim>");
   WriteBasicType(os, binary, input_y_dim_);
   WriteToken(os, binary, "<InputZDim>");
   WriteBasicType(os, binary, input_z_dim_);
   WriteToken(os, binary, "<PoolXSize>");
   WriteBasicType(os, binary, pool_x_size_);
   WriteToken(os, binary, "<PoolYSize>");
   WriteBasicType(os, binary, pool_y_size_);
   WriteToken(os, binary, "<PoolZSize>");
   WriteBasicType(os, binary, pool_z_size_);
   WriteToken(os, binary, "<PoolXStep>");
   WriteBasicType(os, binary, pool_x_step_);
   WriteToken(os, binary, "<PoolYStep>");
   WriteBasicType(os, binary, pool_y_step_);
   WriteToken(os, binary, "<PoolZStep>");
   WriteBasicType(os, binary, pool_z_step_);
   WriteToken(os, binary, "</MaxpoolingComponent>");
 }
Member Data Documentation
input_x_dim_
int32 input_x_dim_ protected
Definition at line 2446 of file nnet-simple-component.h.
Referenced by MaxpoolingComponent::Check(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::Info(), MaxpoolingComponent::InitFromConfig(), MaxpoolingComponent::InputToInputPatches(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Read(), and MaxpoolingComponent::Write().
input_y_dim_
int32 input_y_dim_ protected
Definition at line 2448 of file nnet-simple-component.h.
Referenced by MaxpoolingComponent::Check(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::Info(), MaxpoolingComponent::InitFromConfig(), MaxpoolingComponent::InputToInputPatches(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Read(), and MaxpoolingComponent::Write().
input_z_dim_
int32 input_z_dim_ protected
Definition at line 2450 of file nnet-simple-component.h.
Referenced by MaxpoolingComponent::Check(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::Info(), MaxpoolingComponent::InitFromConfig(), MaxpoolingComponent::InputToInputPatches(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Read(), and MaxpoolingComponent::Write().
pool_x_size_
int32 pool_x_size_ protected
Definition at line 2453 of file nnet-simple-component.h.
Referenced by MaxpoolingComponent::Backprop(), MaxpoolingComponent::Check(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::Info(), MaxpoolingComponent::InitFromConfig(), MaxpoolingComponent::InputToInputPatches(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Propagate(), MaxpoolingComponent::Read(), and MaxpoolingComponent::Write().
pool_x_step_
int32 pool_x_step_ protected
Definition at line 2457 of file nnet-simple-component.h.
Referenced by MaxpoolingComponent::Check(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::Info(), MaxpoolingComponent::InitFromConfig(), MaxpoolingComponent::InputToInputPatches(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Read(), and MaxpoolingComponent::Write().
pool_y_size_
int32 pool_y_size_ protected
Definition at line 2454 of file nnet-simple-component.h.
Referenced by MaxpoolingComponent::Backprop(), MaxpoolingComponent::Check(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::Info(), MaxpoolingComponent::InitFromConfig(), MaxpoolingComponent::InputToInputPatches(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Propagate(), MaxpoolingComponent::Read(), and MaxpoolingComponent::Write().
pool_y_step_
int32 pool_y_step_ protected
Definition at line 2459 of file nnet-simple-component.h.
Referenced by MaxpoolingComponent::Check(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::Info(), MaxpoolingComponent::InitFromConfig(), MaxpoolingComponent::InputToInputPatches(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Read(), and MaxpoolingComponent::Write().
pool_z_size_
int32 pool_z_size_ protected
Definition at line 2455 of file nnet-simple-component.h.
Referenced by MaxpoolingComponent::Backprop(), MaxpoolingComponent::Check(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::Info(), MaxpoolingComponent::InitFromConfig(), MaxpoolingComponent::InputToInputPatches(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Propagate(), MaxpoolingComponent::Read(), and MaxpoolingComponent::Write().
pool_z_step_
int32 pool_z_step_ protected
Definition at line 2461 of file nnet-simple-component.h.
Referenced by MaxpoolingComponent::Check(), MaxpoolingComponent::InderivPatchesToInderiv(), MaxpoolingComponent::Info(), MaxpoolingComponent::InitFromConfig(), MaxpoolingComponent::InputToInputPatches(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Read(), and MaxpoolingComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc