Kaldi: SentenceAveragingComponent Class Reference
SentenceAveragingComponent Class Reference
Deprecated!!!, keeping it as Katka Zmolikova used it in JSALT 2015.
#include <nnet-sentence-averaging-component.h>
Public Member Functions
SentenceAveragingComponent (int32 dim_in, int32 dim_out)
~SentenceAveragingComponent ()
Component * Copy () const
Copy component (deep copy),.
ComponentType GetType () const
Get Type Identification of the component,.
void InitData (std::istream &is)
Initialize the content of the component by the 'line' from the prototype,.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters,.
void GetGradient (VectorBase< BaseFloat > *gradient) const
Get gradient reshaped as a vector,.
void GetParams (VectorBase< BaseFloat > *params) const
Get the trainable parameters reshaped as a vector,.
void SetParams (const VectorBase< BaseFloat > &params)
Set the trainable parameters from, reshaped as a vector,.
std::string Info () const
Print some additional info (after <ComponentName> and the dims),.
std::string InfoGradient () const
Print some additional info about gradient (after <...> and dims),.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters,.
void SetTrainOptions (const NnetTrainOptions &opts)
Set the training options to the component,.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters,.
const NnetTrainOptions & GetTrainOptions () const
Get the training options from the component,.
virtual void SetLearnRateCoef (BaseFloat val)
Set the learn-rate coefficient,.
virtual void SetBiasLearnRateCoef (BaseFloat val)
Set the learn-rate coefficient for bias,.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
Generic interface of a component,.
virtual ~Component ()
virtual bool IsMultistream () const
Check if component has 'Recurrent' interface (trainable and recurrent),.
int32 InputDim () const
Get the dimension of the input,.
int32 OutputDim () const
Get the dimension of the output,.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward-pass propagation 'in' -> 'out',.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
void Write (std::ostream &os, bool binary) const
Write the component to a stream,.
Private Attributes
Nnet nnet_
float learn_rate_factor_
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjected, kBlstmProjected,
kRecurrentComponent, kActivationFunction = 0x0200, kSoftmax, kHiddenSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kParametricRelu,
kDropout, kLengthNormComponent, kTranform = 0x0400, kRbm,
kSplice, kCopy, kTranspose, kBlockLinearity,
kAddShift, kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent,
kSimpleSentenceAveragingComponent, kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent,
kMaxPooling2DComponent, kFramePoolingComponent, kParallelComponent, kMultiBasisComponent
}
Component type identification mechanism,.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Converts component type to marker,.
static ComponentType MarkerToType (const std::string &s)
Converts marker to component type (case insensitive),.
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file,.
static Component * Read (std::istream &is, bool binary)
Read the component from a stream (static method),.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters,.
BaseFloat learn_rate_coef_
Scalar applied to learning rate for weight matrices (to be used in ::Update method),.
BaseFloat bias_learn_rate_coef_
Scalar applied to learning rate for bias (to be used in ::Update method),.
Protected Attributes inherited from Component
int32 input_dim_
Data members,.
int32 output_dim_
Dimension of the output of the Component,.
Detailed Description
Deprecated!!!, keeping it as Katka Zmolikova used it in JSALT 2015.
Definition at line 180 of file nnet-sentence-averaging-component.h.
Constructor & Destructor Documentation
SentenceAveragingComponent()
SentenceAveragingComponent (int32 dim_in, int32 dim_out) inline
Definition at line 182 of file nnet-sentence-averaging-component.h.
                                                          :
     UpdatableComponent(dim_in, dim_out), learn_rate_factor_(100.0)
   { }
~SentenceAveragingComponent()
~SentenceAveragingComponent () inline
Definition at line 185 of file nnet-sentence-averaging-component.h.
   { }
Member Function Documentation
BackpropagateFnc()
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 267 of file nnet-sentence-averaging-component.h.
References CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyFromMat(), and CuMatrixBase< Real >::NumCols().
{
     if (in_diff == NULL) return;
     int32 num_inputs = in.NumCols(),
       nnet_outputs = nnet_.OutputDim();
     in_diff->CopyFromMat(out_diff.ColRange(nnet_outputs, num_inputs));
   }
Copy()
Component* Copy () const inline virtual
Copy component (deep copy),.
Implements Component.
Definition at line 188 of file nnet-sentence-averaging-component.h.
 { return new SentenceAveragingComponent(*this); }
GetGradient()
void GetGradient (VectorBase< BaseFloat > * gradient) const inline virtual
Get gradient reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 225 of file nnet-sentence-averaging-component.h.
References KALDI_ERR.
{
     KALDI_ERR << "Unimplemented!";
   }
GetParams()
void GetParams (VectorBase< BaseFloat > * params) const inline virtual
Get the trainable parameters reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 229 of file nnet-sentence-averaging-component.h.
References VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), and KALDI_ASSERT.
{
     KALDI_ASSERT(params->Dim() == NumParams());
     Vector<BaseFloat> params_aux;
     nnet_.GetParams(&params_aux);
     params->CopyFromVec(params_aux);
   }
GetType()
ComponentType GetType () const inline virtual
Get Type Identification of the component,.
Implements Component.
Definition at line 189 of file nnet-sentence-averaging-component.h.
References Component::kSentenceAveragingComponent.
 { return kSentenceAveragingComponent; }
Info()
std::string Info () const inline virtual
Print some additional info (after <ComponentName> and the dims),.
Reimplemented from Component.
Definition at line 240 of file nnet-sentence-averaging-component.h.
{
     return std::string("nested_network {\n") + nnet_.Info() + "}\n";
   }
InfoGradient()
std::string InfoGradient () const inline virtual
Print some additional info about gradient (after <...> and dims),.
Reimplemented from Component.
Definition at line 244 of file nnet-sentence-averaging-component.h.
{
     return std::string("nested_gradient {\n") + nnet_.InfoGradient() + "}\n";
   }
InitData()
void InitData (std::istream & is) inline virtual
Initialize the content of the component by the 'line' from the prototype,.
Implements UpdatableComponent.
Definition at line 191 of file nnet-sentence-averaging-component.h.
References Component::InputDim(), KALDI_ASSERT, KALDI_ERR, Component::OutputDim(), kaldi::ReadBasicType(), and kaldi::ReadToken().
{
     // define options
     std::string nested_nnet_filename;
     std::string nested_nnet_proto;
     // parse config
     std::string token;
     while (is >> std::ws, !is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<NestedNnetFilename>") ReadToken(is, false, &nested_nnet_filename);
       else if (token == "<NestedNnetProto>") ReadToken(is, false, &nested_nnet_proto);
       else if (token == "<LearnRateFactor>") ReadBasicType(is, false, &learn_rate_factor_);
       else KALDI_ERR << "Unknown token " << token << " Typo in config?";
     }
     // initialize (read already prepared nnet from file)
     KALDI_ASSERT((nested_nnet_proto != "") ^ (nested_nnet_filename != ""));  // xor,
     if (nested_nnet_filename != "") nnet_.Read(nested_nnet_filename);
     if (nested_nnet_proto != "") nnet_.Init(nested_nnet_proto);
     // check dims of nested nnet
     KALDI_ASSERT(InputDim() == nnet_.InputDim());
     KALDI_ASSERT(OutputDim() == nnet_.OutputDim() + InputDim());
   }
NumParams()
int32 NumParams () const inline virtual
Number of trainable parameters,.
Implements UpdatableComponent.
Definition at line 223 of file nnet-sentence-averaging-component.h.
 { return nnet_.NumParams(); }
PropagateFnc()
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 248 of file nnet-sentence-averaging-component.h.
References CuVectorBase< Real >::AddRowSumMat(), CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
     // Get NN output
     CuMatrix<BaseFloat> out_nnet;
     nnet_.Propagate(in, &out_nnet);
     // Get the average row (averaging over the time axis):
     // averaging corresponds to extraction of a 'constant vector'
     // code for single sentence,
     int32 num_inputs = in.NumCols(),
       nnet_outputs = nnet_.OutputDim(),
       num_frames = out_nnet.NumRows();
     CuVector<BaseFloat> average_row(nnet_outputs);
     average_row.AddRowSumMat(1.0/num_frames, out_nnet, 0.0);
     // Forwarding sentence codes along with input features
     out->ColRange(0, nnet_outputs).AddVecToRows(1.0, average_row, 0.0);
     out->ColRange(nnet_outputs, num_inputs).CopyFromMat(in);
   }
ReadData()
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 213 of file nnet-sentence-averaging-component.h.
References Component::InputDim(), KALDI_ASSERT, and Component::OutputDim().
{
     nnet_.Read(is, binary);
     KALDI_ASSERT(nnet_.InputDim() == InputDim());
     KALDI_ASSERT(nnet_.OutputDim() + InputDim() == OutputDim());
   }
SetParams()
void SetParams (const VectorBase< BaseFloat > & params) inline virtual
Set the trainable parameters from, reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 236 of file nnet-sentence-averaging-component.h.
References KALDI_ERR.
{
     KALDI_ERR << "Unimplemented!";
   }
SetTrainOptions()
void SetTrainOptions (const NnetTrainOptions & opts) inline virtual
Set the training options to the component,.
Reimplemented from UpdatableComponent.
Definition at line 297 of file nnet-sentence-averaging-component.h.
References NnetTrainOptions::learn_rate, and UpdatableComponent::SetTrainOptions().
{
     UpdatableComponent::SetTrainOptions(opts_);
     // Pass the train options to the nnet
     NnetTrainOptions o(opts);
     o.learn_rate *= learn_rate_factor_;
     nnet_.SetTrainOptions(opts_);
   }
Update()
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters,.
Implements UpdatableComponent.
Definition at line 277 of file nnet-sentence-averaging-component.h.
References CuVectorBase< Real >::AddRowSumMat(), CuMatrixBase< Real >::AddVecToRows(), CuMatrixBase< Real >::ColRange(), and CuMatrixBase< Real >::NumRows().
{
     // get useful dims,
     int32 nnet_outputs = nnet_.OutputDim(),
       num_frames = diff.NumRows();
     // Passing the derivative into the nested network. The loss derivative is averaged:
     // single frame from nested network influenced all the frames in the main network,
     // so to get the derivative w.r.t. single frame from nested network we sum derivatives
     // of all frames from main network (and scale by 1/Nframes constant).
     //
     // In fact all the frames from nested network influenced all the input frames to main nnet,
     // so the loss derivarive w.r.t. nested network output is same for all frames in sentence.
     CuVector<BaseFloat> average_diff(nnet_outputs);
     average_diff.AddRowSumMat(1.0 / num_frames, diff.ColRange(0, nnet_outputs), 0.0);
     CuMatrix<BaseFloat> nnet_out_diff(num_frames, nnet_outputs);
     nnet_out_diff.AddVecToRows(1.0, average_diff, 0.0);
     //
     nnet_.Backpropagate(nnet_out_diff, NULL);
   }
WriteData()
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 219 of file nnet-sentence-averaging-component.h.
{
     nnet_.Write(os, binary);
   }
Member Data Documentation
learn_rate_factor_
float learn_rate_factor_ private
Definition at line 307 of file nnet-sentence-averaging-component.h.
nnet_
Nnet nnet_ private
Definition at line 306 of file nnet-sentence-averaging-component.h.
The documentation for this class was generated from the following file:
nnet/nnet-sentence-averaging-component.h