Kaldi: TreeRenderer Class Reference
TreeRenderer Class Reference
#include <tree-renderer.h>
Public Member Functions
TreeRenderer (std::istream &is, bool binary, std::ostream &os, fst::SymbolTable &phone_syms, bool use_tooltips)
void Render (const EventType *query)
Static Public Attributes
static const int32 kEdgeWidth = 1
static const int32 kEdgeWidthQuery = 3
static const std::string kEdgeColor = "black"
static const std::string kEdgeColorQuery = "red"
Private Member Functions
void RenderSubTree (const EventType *query, int32 id)
void RenderConstant (const EventType *query, int32 id)
void RenderSplit (const EventType *query, int32 id)
void RenderTable (const EventType *query, int32 id)
std::string MakeEdgeLabel (const EventKeyType &key, const ConstIntegerSet< EventValueType > &intset)
void RenderNonLeaf (int32 id, const EventKeyType &key, bool in_query)
Private Attributes
fst::SymbolTable & phone_syms_
std::istream & is_
std::ostream & out_
bool binary_
int32 N_
int32 P_
bool use_tooltips_
int32 next_id_
Detailed Description
Definition at line 32 of file tree-renderer.h.
Constructor & Destructor Documentation
TreeRenderer()
TreeRenderer (std::istream & is, bool binary, std::ostream & os, fst::SymbolTable & phone_syms, bool use_tooltips) inline
Definition at line 39 of file tree-renderer.h.
References TreeRenderer::MakeEdgeLabel(), TreeRenderer::Render(), TreeRenderer::RenderConstant(), TreeRenderer::RenderNonLeaf(), TreeRenderer::RenderSplit(), TreeRenderer::RenderSubTree(), and TreeRenderer::RenderTable().
       : phone_syms_(phone_syms), is_(is), out_(os), binary_(binary),
         N_(-1), use_tooltips_(use_tooltips), next_id_(0) {}
Member Function Documentation
MakeEdgeLabel()
std::string MakeEdgeLabel (const EventKeyType & key, const ConstIntegerSet< EventValueType > & intset) private
Definition at line 59 of file tree-renderer.cc.
References ConstIntegerSet< I >::begin(), ConstIntegerSet< I >::end(), KALDI_ERR, kaldi::kPdfClass, and TreeRenderer::phone_syms_.
Referenced by TreeRenderer::RenderSplit(), and TreeRenderer::TreeRenderer().
{
   std::ostringstream oss;
   ConstIntegerSet<EventValueType>::iterator child = intset.begin();
   for (; child != intset.end(); ++child) {
     if (child != intset.begin())
       oss << ", ";
     if (key != kPdfClass) {
       std::string phone =
           phone_syms_.Find(static_cast<kaldi::int64>(*child));
       if (phone.empty())
         KALDI_ERR << "No phone found for Phone ID " << *child;
       oss << phone;
     } else {
       oss << *child;
     }
   }
   return oss.str();
 }
Render()
void Render (const EventType * query = 0)
Definition at line 184 of file tree-renderer.cc.
References TreeRenderer::binary_, kaldi::ExpectToken(), TreeRenderer::is_, KALDI_ERR, TreeRenderer::N_, TreeRenderer::next_id_, TreeRenderer::out_, TreeRenderer::P_, kaldi::ReadBasicType(), and TreeRenderer::RenderSubTree().
Referenced by main(), and TreeRenderer::TreeRenderer().
{
   ExpectToken(is_, binary_, "ContextDependency");
   ReadBasicType(is_, binary_, &N_);
   ReadBasicType(is_, binary_, &P_);
   ExpectToken(is_, binary_, "ToPdf");
   if (query && query->size() != N_+1)
     KALDI_ERR << "Invalid query size \"" << query->size() << "\"! Expected \""
               << N_+1 << '"';
   out_ << "digraph EventMap {\n";
   RenderSubTree(query, next_id_++);
   out_ << "}\n";
   ExpectToken(is_, binary_, "EndContextDependency");
 }
RenderConstant()
void RenderConstant (const EventType * query, int32 id) private
Definition at line 156 of file tree-renderer.cc.
References TreeRenderer::binary_, kaldi::ExpectToken(), TreeRenderer::is_, TreeRenderer::kEdgeColor, TreeRenderer::kEdgeColorQuery, TreeRenderer::kEdgeWidth, TreeRenderer::kEdgeWidthQuery, TreeRenderer::out_, and kaldi::ReadBasicType().
Referenced by TreeRenderer::RenderSubTree(), and TreeRenderer::TreeRenderer().
{
   ExpectToken(is_, binary_, "CE");
   EventAnswerType answer;
   ReadBasicType(is_, binary_, &answer);
   std::string color = (query!=NULL)? kEdgeColorQuery: kEdgeColor;
   int32 width = (query!=NULL)? kEdgeWidthQuery: kEdgeWidth;
   out_ << id << "[shape=doublecircle, label=" << answer
        << ",color=" << color << ", penwidth=" << width << "];\n";
 }
RenderNonLeaf()
void RenderNonLeaf (int32 id, const EventKeyType & key, bool in_query) private
Definition at line 29 of file tree-renderer.cc.
References KALDI_ERR, TreeRenderer::kEdgeColor, TreeRenderer::kEdgeColorQuery, TreeRenderer::kEdgeWidth, TreeRenderer::kEdgeWidthQuery, kaldi::kPdfClass, TreeRenderer::N_, TreeRenderer::out_, and TreeRenderer::P_.
Referenced by TreeRenderer::RenderSplit(), TreeRenderer::RenderTable(), and TreeRenderer::TreeRenderer().
{
   std::string color = in_query? kEdgeColorQuery: kEdgeColor;
   int32 width = in_query? kEdgeWidthQuery: kEdgeWidth;
   std::string label;
   if (key == kPdfClass) {
     label = "\"PdfClass = ?\"";
   } else if (key == 0) {
     if (N_ == 1 && P_ == 0) // monophone tree?
       label = "\"Phone = ?\"";
     else if (N_ == 3 && P_ == 1) // triphone tree?
       label = "\"LContext = ?\"";
   } else if (key == 2 && N_ == 3 && P_ == 1) {
     label = "\"RContext = ?\"";
   } else if (key >= 0 && key <= N_-1) {
     if (P_ == key)
       label = "\"Center = ?\"";
     else {
       std::ostringstream oss;
       oss << "\"Ctx Position " << key << " = ?\"";
       label = oss.str();
     }
   } else {
     KALDI_ERR << "Invalid decision tree key: " << key;
   }
   out_ << id << "[label=" << label << ", color=" << color
        << ", penwidth=" << width << "];" << std::endl;
 }
RenderSplit()
void RenderSplit (const EventType * query, int32 id) private
Definition at line 80 of file tree-renderer.cc.
References TreeRenderer::binary_, ConstIntegerSet< I >::count(), kaldi::ExpectToken(), TreeRenderer::is_, TreeRenderer::kEdgeColor, TreeRenderer::kEdgeColorQuery, TreeRenderer::kEdgeWidth, TreeRenderer::kEdgeWidthQuery, EventMap::Lookup(), TreeRenderer::MakeEdgeLabel(), TreeRenderer::next_id_, TreeRenderer::out_, ConstIntegerSet< I >::Read(), kaldi::ReadBasicType(), TreeRenderer::RenderNonLeaf(), TreeRenderer::RenderSubTree(), and TreeRenderer::use_tooltips_.
Referenced by TreeRenderer::RenderSubTree(), and TreeRenderer::TreeRenderer().
{
   ExpectToken(is_, binary_, "SE");
   EventKeyType key;
   ReadBasicType(is_, binary_, &key);
   ConstIntegerSet<EventValueType> yes_set;
   yes_set.Read(is_, binary_);
   ExpectToken(is_, binary_, "{");
   EventValueType value = -30000000; // just a value I guess is invalid
   if (query != NULL)
     EventMap::Lookup(*query, key, &value);
   const EventType *query_yes = yes_set.count(value)? query: NULL;
   const EventType *query_no = (query_yes == NULL)? query: NULL;
   std::string color_yes = (query_yes)? kEdgeColorQuery: kEdgeColor;
   std::string color_no = (query && !query_yes)? kEdgeColorQuery: kEdgeColor;
   int32 width_yes = (query_yes)? kEdgeWidthQuery: kEdgeWidth;
   int32 width_no = (query && !query_yes)? kEdgeWidthQuery: kEdgeWidth;
   RenderNonLeaf(id, key, (query != NULL)); // Draw the node itself
   std::string yes_label = MakeEdgeLabel(key, yes_set);
   out_ << "\t" << id << " -> " << next_id_++ << " ["; // YES edge
   if (use_tooltips_) {
     out_ << "tooltip=\"" << yes_label << "\", label=YES"
          << ", penwidth=" << width_yes << ", color=" << color_yes << "];\n";
   } else {
     out_ << "label=\"" << yes_label << "\", penwidth=" << width_yes
          << ", penwidth=" << width_yes << ", color=" << color_yes << "];\n";
   }
   RenderSubTree(query_yes, next_id_-1); // Render YES subtree
   out_ << "\t" << id << " -> " << next_id_++ << "[label=NO" // NO edge
        << ", color=" << color_no << ", penwidth=" << width_no << "];\n";
   RenderSubTree(query_no, next_id_-1); // Render NO subtree
   ExpectToken(is_, binary_, "}");
 }
RenderSubTree()
void RenderSubTree (const EventType * query, int32 id) private
Definition at line 167 of file tree-renderer.cc.
References TreeRenderer::binary_, kaldi::CharToString(), kaldi::ExpectToken(), TreeRenderer::is_, KALDI_ERR, kaldi::Peek(), TreeRenderer::RenderConstant(), TreeRenderer::RenderSplit(), and TreeRenderer::RenderTable().
Referenced by TreeRenderer::Render(), TreeRenderer::RenderSplit(), TreeRenderer::RenderTable(), and TreeRenderer::TreeRenderer().
{
   char c = Peek(is_, binary_);
   if (c == 'N') {
     ExpectToken(is_, binary_, "NULL"); // consume NULL entries
     return;
   } else if (c == 'C') {
     RenderConstant(query, id);
   } else if (c == 'T') {
     RenderTable(query, id);
   } else if (c == 'S') {
     RenderSplit(query, id);
   } else {
     KALDI_ERR << "EventMap::read, was not expecting character " << CharToString(c)
               << ", at file position " << is_.tellg();
   }
 }
RenderTable()
void RenderTable (const EventType * query, int32 id) private
Definition at line 115 of file tree-renderer.cc.
References TreeRenderer::binary_, kaldi::ExpectToken(), TreeRenderer::is_, KALDI_ERR, TreeRenderer::kEdgeColor, TreeRenderer::kEdgeColorQuery, TreeRenderer::kEdgeWidth, TreeRenderer::kEdgeWidthQuery, kaldi::kPdfClass, EventMap::Lookup(), TreeRenderer::N_, TreeRenderer::next_id_, TreeRenderer::out_, TreeRenderer::phone_syms_, kaldi::ReadBasicType(), TreeRenderer::RenderNonLeaf(), and TreeRenderer::RenderSubTree().
Referenced by TreeRenderer::RenderSubTree(), and TreeRenderer::TreeRenderer().
{
   ExpectToken(is_, binary_, "TE");
   EventKeyType key;
   ReadBasicType(is_, binary_, &key);
   uint32 size;
   ReadBasicType(is_, binary_, &size);
   ExpectToken(is_, binary_, "(");
   EventValueType value = -3000000; // just a value I hope is invalid
   if (query != NULL)
     EventMap::Lookup(*query, key, &value);
   RenderNonLeaf(id, key, (query != NULL));
   for (size_t t = 0; t < size; t++) {
     std::string color = (t == value)? kEdgeColorQuery: kEdgeColor;
     int32 width = (t==value)? kEdgeWidthQuery: kEdgeWidth;
     std::ostringstream label;
     if (key == kPdfClass) {
       label << t;
     } else if (key >= 0 && key < N_) {
       if (t == 0) {
         ExpectToken(is_, binary_, "NULL"); // consume the invalid/NULL entry
         continue;
       }
       std::string phone = phone_syms_.Find(static_cast<kaldi::int64>(t));
       if (phone.empty())
           KALDI_ERR << "Phone ID found in a TableEventMap, but not in the "
                     << "phone symbol table! ID: " << t;
       label << phone;
     } else {
       KALDI_ERR << "TableEventMap: Invalid event key: " << key;
     }
     // draw the edge to the child subtree
     out_ << "\t" << id << " -> " << next_id_++ << " [label=" << label.str()
          << ", color=" << color << ", penwidth=" << width <<  "];\n";
     const EventType *query_child = (t == value)? query: NULL;
     RenderSubTree(query_child, next_id_-1); // render the child subtree
   }
   ExpectToken(is_, binary_, ")");
 }
Member Data Documentation
binary_
bool binary_ private
Definition at line 76 of file tree-renderer.h.
Referenced by TreeRenderer::Render(), TreeRenderer::RenderConstant(), TreeRenderer::RenderSplit(), TreeRenderer::RenderSubTree(), and TreeRenderer::RenderTable().
is_
std::istream& is_ private
Definition at line 74 of file tree-renderer.h.
Referenced by TreeRenderer::Render(), TreeRenderer::RenderConstant(), TreeRenderer::RenderSplit(), TreeRenderer::RenderSubTree(), and TreeRenderer::RenderTable().
kEdgeColor
const std::string kEdgeColor = "black" static
Definition at line 36 of file tree-renderer.h.
Referenced by TreeRenderer::RenderConstant(), TreeRenderer::RenderNonLeaf(), TreeRenderer::RenderSplit(), and TreeRenderer::RenderTable().
kEdgeColorQuery
const std::string kEdgeColorQuery = "red" static
Definition at line 37 of file tree-renderer.h.
Referenced by TreeRenderer::RenderConstant(), TreeRenderer::RenderNonLeaf(), TreeRenderer::RenderSplit(), and TreeRenderer::RenderTable().
kEdgeWidth
const int32 kEdgeWidth = 1 static
Definition at line 34 of file tree-renderer.h.
Referenced by TreeRenderer::RenderConstant(), TreeRenderer::RenderNonLeaf(), TreeRenderer::RenderSplit(), and TreeRenderer::RenderTable().
kEdgeWidthQuery
const int32 kEdgeWidthQuery = 3 static
Definition at line 35 of file tree-renderer.h.
Referenced by TreeRenderer::RenderConstant(), TreeRenderer::RenderNonLeaf(), TreeRenderer::RenderSplit(), and TreeRenderer::RenderTable().
N_
int32 N_ private
Definition at line 77 of file tree-renderer.h.
Referenced by TreeRenderer::Render(), TreeRenderer::RenderNonLeaf(), and TreeRenderer::RenderTable().
next_id_
int32 next_id_ private
Definition at line 79 of file tree-renderer.h.
Referenced by TreeRenderer::Render(), TreeRenderer::RenderSplit(), and TreeRenderer::RenderTable().
out_
std::ostream& out_ private
Definition at line 75 of file tree-renderer.h.
Referenced by TreeRenderer::Render(), TreeRenderer::RenderConstant(), TreeRenderer::RenderNonLeaf(), TreeRenderer::RenderSplit(), and TreeRenderer::RenderTable().
P_
int32 P_ private
Definition at line 77 of file tree-renderer.h.
Referenced by TreeRenderer::Render(), and TreeRenderer::RenderNonLeaf().
phone_syms_
fst::SymbolTable& phone_syms_ private
Definition at line 73 of file tree-renderer.h.
Referenced by TreeRenderer::MakeEdgeLabel(), and TreeRenderer::RenderTable().
use_tooltips_
bool use_tooltips_ private
Definition at line 78 of file tree-renderer.h.
Referenced by TreeRenderer::RenderSplit().
The documentation for this class was generated from the following files:
tree/tree-renderer.h
tree/tree-renderer.cc