Kaldi: FmllrDiagGmmAccs Class Reference
FmllrDiagGmmAccs Class Reference
This does not work with multiple feature transforms.
#include <fmllr-diag-gmm.h>
Classes
struct SingleFrameStats
Public Member Functions
FmllrDiagGmmAccs (const FmllrOptions &opts=FmllrOptions())
FmllrDiagGmmAccs (const FmllrDiagGmmAccs &other)
FmllrDiagGmmAccs (int32 dim, const FmllrOptions &opts=FmllrOptions())
FmllrDiagGmmAccs (const DiagGmm &gmm, const AccumFullGmm &fgmm_accs)
void Init (size_t dim)
void Read (std::istream &in, bool binary, bool add)
BaseFloat AccumulateForGmm (const DiagGmm &gmm, const VectorBase< BaseFloat > &data, BaseFloat weight)
Accumulate stats for a single GMM in the model; returns log likelihood.
BaseFloat AccumulateForGmmPreselect (const DiagGmm &gmm, const std::vector< int32 > &gselect, const VectorBase< BaseFloat > &data, BaseFloat weight)
This is like AccumulateForGmm but when you have gselect (Gaussian selection) information.
void AccumulateFromPosteriors (const DiagGmm &gmm, const VectorBase< BaseFloat > &data, const VectorBase< BaseFloat > &posteriors)
Accumulate stats for a GMM, given supplied posteriors.
void AccumulateFromPosteriorsPreselect (const DiagGmm &gmm, const std::vector< int32 > &gselect, const VectorBase< BaseFloat > &data, const VectorBase< BaseFloat > &posteriors)
Accumulate stats for a GMM, given supplied posteriors.
void Update (const FmllrOptions &opts, MatrixBase< BaseFloat > *fmllr_mat, BaseFloat *objf_impr, BaseFloat *count)
Update.
Public Member Functions inherited from AffineXformStats
AffineXformStats ()
void Init (int32 dim, int32 num_gs)
int32 Dim () const
void SetZero ()
void CopyStats (const AffineXformStats &other)
void Add (const AffineXformStats &other)
void Write (std::ostream &out, bool binary) const
void Read (std::istream &in, bool binary, bool add)
AffineXformStats (const AffineXformStats &other)
Private Member Functions
void CommitSingleFrameStats ()
void InitSingleFrameStats (const VectorBase< BaseFloat > &data)
bool DataHasChanged (const VectorBase< BaseFloat > &data) const
Private Attributes
SingleFrameStats single_frame_stats_
FmllrOptions opts_
Additional Inherited Members
Public Attributes inherited from AffineXformStats
double beta_
beta_ is the occupation count.
Matrix< double > K_
K_ is the summed outer product of [mean times inverse variance] with [extended data], scaled by the occupation counts; dimension is dim by (dim+1)
std::vector< SpMatrix< double > > G_
G_ is the outer product of extended-data, scaled by inverse variance, for each dimension.
int32 dim_
dim_ is the feature dimension.
Detailed Description
This does not work with multiple feature transforms.
Definition at line 61 of file fmllr-diag-gmm.h.
Constructor & Destructor Documentation
FmllrDiagGmmAccs() [1/4]
FmllrDiagGmmAccs (const FmllrOptions & opts = FmllrOptions()) inline
Definition at line 66 of file fmllr-diag-gmm.h.
                                                              :
       opts_(opts) { }
FmllrDiagGmmAccs() [2/4]
FmllrDiagGmmAccs (const FmllrDiagGmmAccs & other) inline explicit
Definition at line 68 of file fmllr-diag-gmm.h.
                                                           :
       AffineXformStats(other), single_frame_stats_(other.single_frame_stats_),
       opts_(other.opts_) {}
FmllrDiagGmmAccs() [3/4]
FmllrDiagGmmAccs (int32 dim, const FmllrOptions & opts = FmllrOptions()) inline explicit
Definition at line 71 of file fmllr-diag-gmm.h.
                                                                                  :
       opts_(opts) { Init(dim); }
FmllrDiagGmmAccs() [4/4]
FmllrDiagGmmAccs (const DiagGmm & gmm, const AccumFullGmm & fgmm_accs)
Definition at line 67 of file fmllr-diag-gmm.cc.
References MatrixBase< Real >::AddVecVec(), AffineXformStats::beta_, MatrixBase< Real >::CopyColFromVec(), AccumFullGmm::covariance_accumulator(), rnnlm::d, DiagGmm::Dim(), AccumFullGmm::Dim(), AffineXformStats::G_, FmllrDiagGmmAccs::Init(), DiagGmm::inv_vars(), AffineXformStats::K_, KALDI_ASSERT, AccumFullGmm::mean_accumulator(), DiagGmm::means_invvars(), DiagGmm::NumGauss(), AccumFullGmm::NumGauss(), AccumFullGmm::occupancy(), VectorBase< Real >::Range(), MatrixBase< Real >::Range(), and MatrixBase< Real >::Row().
                                                                  :
     single_frame_stats_(gmm.Dim()), opts_(FmllrOptions()) {
   KALDI_ASSERT(gmm.NumGauss() == fgmm_accs.NumGauss()
                && gmm.Dim() == fgmm_accs.Dim());
   Init(gmm.Dim());
   int32 dim = gmm.Dim(), num_gauss = gmm.NumGauss();
   for (int32 g = 0; g < num_gauss; g++) {
     double this_occ = fgmm_accs.occupancy()(g);
     if (this_occ == 0) continue;
     SubVector<BaseFloat> this_mean_invvar(gmm.means_invvars(), g);
     SubVector<BaseFloat> this_invvar(gmm.inv_vars(), g);
     SubVector<double> this_mean_acc(fgmm_accs.mean_accumulator(), g);
     Vector<double> this_mean_invvar_dbl(this_mean_invvar);
     Vector<double> this_extended_mean_acc(dim+1);
     this_extended_mean_acc.Range(0, dim).CopyFromVec(this_mean_acc);
     this_extended_mean_acc(dim) = this_occ; // acc of x^+
     Matrix<double> this_cov_acc(fgmm_accs.covariance_accumulator()[g]); // copy to
     // regular Matrix.
     Matrix<double> this_extended_cov_acc(dim+1, dim+1); // make as if accumulated
     // using x^+, not x.
     this_extended_cov_acc.Range(0, dim, 0, dim).CopyFromMat(this_cov_acc);
     this_extended_cov_acc.Row(dim).CopyFromVec(this_extended_mean_acc);
     this_extended_cov_acc.CopyColFromVec(this_extended_mean_acc, dim); // since
     // there is no Col() function, use a member-function of the matrix class.
     SpMatrix<double> this_extended_cov_acc_sp(this_extended_cov_acc);
     beta_ += this_occ;
     K_.AddVecVec(1.0, this_mean_invvar_dbl, this_extended_mean_acc);
     for (int32 d = 0; d < dim; d++)
       G_[d].AddSp(this_invvar(d), this_extended_cov_acc_sp);
   }
 }
Member Function Documentation
AccumulateForGmm()
BaseFloat AccumulateForGmm (const DiagGmm & gmm, const VectorBase< BaseFloat > & data, BaseFloat weight)
Accumulate stats for a single GMM in the model; returns log likelihood.
Definition at line 101 of file fmllr-diag-gmm.cc.
References FmllrDiagGmmAccs::AccumulateFromPosteriors(), DiagGmm::ComponentPosteriors(), DiagGmm::NumGauss(), and VectorBase< Real >::Scale().
Referenced by kaldi::AccumulateForUtterance(), main(), kaldi::UnitTestFmllrDiagGmm(), kaldi::UnitTestFmllrDiagGmmDiagonal(), and kaldi::UnitTestFmllrDiagGmmOffset().
{
   int32 num_comp = pdf.NumGauss();
   Vector<BaseFloat> posterior(num_comp);
   BaseFloat loglike;
   loglike = pdf.ComponentPosteriors(data, &posterior);
   posterior.Scale(weight);
   AccumulateFromPosteriors(pdf, data, posterior);
   return loglike;
 }
AccumulateForGmmPreselect()
BaseFloat AccumulateForGmmPreselect (const DiagGmm & gmm, const std::vector< int32 > & gselect, const VectorBase< BaseFloat > & data, BaseFloat weight)
This is like AccumulateForGmm but when you have gselect (Gaussian selection) information.
Definition at line 114 of file fmllr-diag-gmm.cc.
References FmllrDiagGmmAccs::AccumulateFromPosteriorsPreselect(), KALDI_ASSERT, and DiagGmm::LogLikelihoodsPreselect().
                       {
   KALDI_ASSERT(!gselect.empty() && "Empty gselect information");
   Vector<BaseFloat> loglikes;
   pdf.LogLikelihoodsPreselect(data, gselect, &loglikes);
   BaseFloat loglike = loglikes.ApplySoftMax(); // they are now posteriors.
   loglikes.Scale(weight);
   AccumulateFromPosteriorsPreselect(pdf, gselect, data, loglikes);
   return loglike;
 }
AccumulateFromPosteriors()
void AccumulateFromPosteriors (const DiagGmm & gmm, const VectorBase< BaseFloat > & data, const VectorBase< BaseFloat > & posteriors)
Accumulate stats for a GMM, given supplied posteriors.
Definition at line 30 of file fmllr-diag-gmm.cc.
References FmllrDiagGmmAccs::SingleFrameStats::a, FmllrDiagGmmAccs::SingleFrameStats::b, FmllrDiagGmmAccs::CommitSingleFrameStats(), FmllrDiagGmmAccs::SingleFrameStats::count, FmllrDiagGmmAccs::DataHasChanged(), FmllrDiagGmmAccs::InitSingleFrameStats(), DiagGmm::inv_vars(), kaldi::kTrans, DiagGmm::means_invvars(), FmllrDiagGmmAccs::single_frame_stats_, and VectorBase< Real >::Sum().
Referenced by FmllrDiagGmmAccs::AccumulateForGmm(), kaldi::AccumulateForUtterance(), kaldi::UnitTestFmllrDiagGmm(), kaldi::UnitTestFmllrDiagGmmDiagonal(), and kaldi::UnitTestFmllrDiagGmmOffset().
{
   if (this->DataHasChanged(data)) {
     CommitSingleFrameStats();
     InitSingleFrameStats(data);
   }
   SingleFrameStats &stats = this->single_frame_stats_;
   stats.count += posterior.Sum();
   stats.a.AddMatVec(1.0, pdf.means_invvars(), kTrans, posterior, 1.0);
   stats.b.AddMatVec(1.0, pdf.inv_vars(), kTrans, posterior, 1.0);
 }
AccumulateFromPosteriorsPreselect()
void AccumulateFromPosteriorsPreselect (const DiagGmm & gmm, const std::vector< int32 > & gselect, const VectorBase< BaseFloat > & data, const VectorBase< BaseFloat > & posteriors)
Accumulate stats for a GMM, given supplied posteriors.
The "posteriors" vector should be have the same size as "gselect".
Definition at line 45 of file fmllr-diag-gmm.cc.
References FmllrDiagGmmAccs::SingleFrameStats::a, FmllrDiagGmmAccs::SingleFrameStats::b, FmllrDiagGmmAccs::CommitSingleFrameStats(), FmllrDiagGmmAccs::SingleFrameStats::count, FmllrDiagGmmAccs::DataHasChanged(), VectorBase< Real >::Dim(), rnnlm::i, FmllrDiagGmmAccs::InitSingleFrameStats(), DiagGmm::inv_vars(), KALDI_ASSERT, DiagGmm::means_invvars(), MatrixBase< Real >::Row(), FmllrDiagGmmAccs::single_frame_stats_, and VectorBase< Real >::Sum().
Referenced by FmllrDiagGmmAccs::AccumulateForGmmPreselect(), and kaldi::AccumulateForUtterance().
{
   if (this->DataHasChanged(data)) {
     CommitSingleFrameStats();
     InitSingleFrameStats(data);
   }
   SingleFrameStats &stats = this->single_frame_stats_;
   stats.count += posterior.Sum();
   const Matrix<BaseFloat> &means_invvars = pdf.means_invvars(),
       &inv_vars = pdf.inv_vars();
   KALDI_ASSERT(static_cast<int32>(gselect.size()) == posterior.Dim());
   for (size_t i = 0; i < gselect.size(); i++) {
     stats.a.AddVec(posterior(i), means_invvars.Row(gselect[i]));
     stats.b.AddVec(posterior(i), inv_vars.Row(gselect[i]));
   }
 }
CommitSingleFrameStats()
void CommitSingleFrameStats () private
Definition at line 562 of file fmllr-diag-gmm.cc.
References FmllrDiagGmmAccs::SingleFrameStats::a, SpMatrix< Real >::AddVec2(), MatrixBase< Real >::AddVecVec(), FmllrDiagGmmAccs::SingleFrameStats::b, AffineXformStats::beta_, FmllrDiagGmmAccs::SingleFrameStats::count, AffineXformStats::Dim(), AffineXformStats::G_, rnnlm::i, AffineXformStats::K_, KALDI_ASSERT, FmllrDiagGmmAccs::opts_, VectorBase< Real >::Range(), FmllrDiagGmmAccs::single_frame_stats_, FmllrOptions::update_type, and FmllrDiagGmmAccs::SingleFrameStats::x.
Referenced by FmllrDiagGmmAccs::AccumulateFromPosteriors(), FmllrDiagGmmAccs::AccumulateFromPosteriorsPreselect(), and FmllrDiagGmmAccs::Update().
{
   // Commit the stats for this from (in SingleFrameStats).
   int32 dim = Dim();
   SingleFrameStats &stats = single_frame_stats_;
   if (stats.count == 0.0) return;
   Vector<double> xplus(dim+1);
   xplus.Range(0, dim).CopyFromVec(stats.x);
   xplus(dim) = 1.0;
   this->beta_ += stats.count;
   this->K_.AddVecVec(1.0, Vector<double>(stats.a), xplus);
   if (opts_.update_type == "full") {
     SpMatrix<double> scatter(dim+1);
     scatter.AddVec2(1.0, xplus);
     KALDI_ASSERT(static_cast<size_t>(dim) == this->G_.size());
     for (int32 i = 0; i < dim; i++)
       this->G_[i].AddSp(stats.b(i), scatter);
   } else {
     // We only need some elements of these stats, so just update those elements.
     for (int32 i = 0; i < dim; i++) {
       BaseFloat scale = stats.b(i), x_i = xplus(i);
       this->G_[i](i, i) += scale * x_i * x_i;
       this->G_[i](dim, i) += scale * 1.0 * x_i;
       this->G_[i](dim, dim) += scale * 1.0 * 1.0;
     }
   }
   stats.count = 0.0;
   stats.a.SetZero();
   stats.b.SetZero();
 }
DataHasChanged()
bool DataHasChanged (const VectorBase< BaseFloat > & data) const private
Definition at line 542 of file fmllr-diag-gmm.cc.
References VectorBase< Real >::ApproxEqual(), AffineXformStats::Dim(), VectorBase< Real >::Dim(), KALDI_ASSERT, FmllrDiagGmmAccs::single_frame_stats_, and FmllrDiagGmmAccs::SingleFrameStats::x.
Referenced by FmllrDiagGmmAccs::AccumulateFromPosteriors(), and FmllrDiagGmmAccs::AccumulateFromPosteriorsPreselect().
{
   KALDI_ASSERT(data.Dim() == this->Dim());
   return !data.ApproxEqual(single_frame_stats_.x, 0.0);
 }
Init()
void Init (size_t dim) inline
Definition at line 81 of file fmllr-diag-gmm.h.
References AffineXformStats::Init().
Referenced by FmllrDiagGmmAccs::FmllrDiagGmmAccs().
{
     AffineXformStats::Init(dim, dim); single_frame_stats_.Init(dim);
   }
InitSingleFrameStats()
void InitSingleFrameStats (const VectorBase< BaseFloat > & data) private
Definition at line 554 of file fmllr-diag-gmm.cc.
References FmllrDiagGmmAccs::SingleFrameStats::a, FmllrDiagGmmAccs::SingleFrameStats::b, FmllrDiagGmmAccs::SingleFrameStats::count, FmllrDiagGmmAccs::single_frame_stats_, and FmllrDiagGmmAccs::SingleFrameStats::x.
Referenced by FmllrDiagGmmAccs::AccumulateFromPosteriors(), and FmllrDiagGmmAccs::AccumulateFromPosteriorsPreselect().
{
   SingleFrameStats &stats = single_frame_stats_;
   stats.x.CopyFromVec(data);
   stats.count = 0.0;
   stats.a.SetZero();
   stats.b.SetZero();
 }
Read()
void Read (std::istream & in, bool binary, bool add) inline
Definition at line 84 of file fmllr-diag-gmm.h.
References count, and AffineXformStats::Read().
{
       AffineXformStats::Read(in, binary, add);
       single_frame_stats_.Init(Dim());
   }
Update()
void Update (const FmllrOptions & opts, MatrixBase< BaseFloat > * fmllr_mat, BaseFloat * objf_impr, BaseFloat * count)
Update.
Definition at line 131 of file fmllr-diag-gmm.cc.
References AffineXformStats::beta_, FmllrDiagGmmAccs::CommitSingleFrameStats(), kaldi::ComputeFmllrMatrixDiagGmmDiagonal(), kaldi::ComputeFmllrMatrixDiagGmmFull(), kaldi::ComputeFmllrMatrixDiagGmmOffset(), MatrixBase< Real >::CopyFromMat(), MatrixBase< Real >::IsZero(), KALDI_ASSERT, KALDI_ERR, KALDI_WARN, FmllrOptions::min_count, FmllrOptions::num_iters, and FmllrOptions::update_type.
Referenced by main(), kaldi::UnitTestFmllrDiagGmm(), kaldi::UnitTestFmllrDiagGmmDiagonal(), and kaldi::UnitTestFmllrDiagGmmOffset().
{
   KALDI_ASSERT(fmllr_mat != NULL);
   CommitSingleFrameStats();
   if (fmllr_mat->IsZero())
     KALDI_ERR << "You must initialize the fMLLR matrix to a non-singular value "
         "(so we can report objective function changes); e.g. call SetUnit()";
   if (opts.update_type == "full" && this->opts_.update_type != "full") {
     KALDI_ERR << "You are requesting a full-fMLLR update but you accumulated "
               << "stats for more limited update type.";
   }
   if (beta_ > opts.min_count) {
     Matrix<BaseFloat> tmp_old(*fmllr_mat), tmp_new(*fmllr_mat);
     BaseFloat objf_change;
     if (opts.update_type == "full")
       objf_change = ComputeFmllrMatrixDiagGmmFull(tmp_old, *this, opts.num_iters, &tmp_new);
     else if (opts.update_type == "diag")
       objf_change = ComputeFmllrMatrixDiagGmmDiagonal(tmp_old, *this, &tmp_new);
     else if (opts.update_type == "offset")
       objf_change = ComputeFmllrMatrixDiagGmmOffset(tmp_old, *this, &tmp_new);
     else if (opts.update_type == "none")
       objf_change = 0.0;
     else
       KALDI_ERR << "Unknown fMLLR update type " << opts.update_type
                 << ", fmllr-update-type must be one of \"full\"|\"diag\"|\"offset\"|\"none\"";
     fmllr_mat->CopyFromMat(tmp_new);
     if (objf_impr) *objf_impr = objf_change;
     if (count) *count = beta_;
   } else {  // Not changing matrix.
     KALDI_WARN << "Not updating fMLLR since below min-count: count is " << beta_;
     if (objf_impr) *objf_impr = 0.0;
     if (count) *count = beta_;
   }
 }
Member Data Documentation
opts_
FmllrOptions opts_ private
Definition at line 155 of file fmllr-diag-gmm.h.
Referenced by FmllrDiagGmmAccs::CommitSingleFrameStats().
single_frame_stats_
SingleFrameStats single_frame_stats_ private
Definition at line 151 of file fmllr-diag-gmm.h.
Referenced by FmllrDiagGmmAccs::AccumulateFromPosteriors(), FmllrDiagGmmAccs::AccumulateFromPosteriorsPreselect(), FmllrDiagGmmAccs::CommitSingleFrameStats(), FmllrDiagGmmAccs::DataHasChanged(), and FmllrDiagGmmAccs::InitSingleFrameStats().
The documentation for this class was generated from the following files:
transform/fmllr-diag-gmm.h
transform/fmllr-diag-gmm.cc