Kaldi: CopyComponent Class Reference
CopyComponent Class Reference
Rearrange the matrix columns according to the indices in copy_from_indices_.
#include <nnet-various.h>
Public Member Functions
CopyComponent (int32 dim_in, int32 dim_out)
~CopyComponent ()
Component * Copy () const
Copy component (deep copy),.
ComponentType GetType () const
Get Type Identification of the component,.
void InitData (std::istream &is)
Virtual interface for initialization and I/O,.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
std::string Info () const
Print some additional info (after <ComponentName> and the dims),.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
Generic interface of a component,.
virtual ~Component ()
virtual bool IsUpdatable () const
Check if componeny has 'Updatable' interface (trainable components),.
virtual bool IsMultistream () const
Check if component has 'Recurrent' interface (trainable and recurrent),.
int32 InputDim () const
Get the dimension of the input,.
int32 OutputDim () const
Get the dimension of the output,.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward-pass propagation 'in' -> 'out',.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
void Write (std::ostream &os, bool binary) const
Write the component to a stream,.
virtual std::string InfoGradient () const
Print some additional info about gradient (after <...> and dims),.
Protected Attributes
CuArray< int32 > copy_from_indices_
Protected Attributes inherited from Component
int32 input_dim_
Data members,.
int32 output_dim_
Dimension of the output of the Component,.
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjected, kBlstmProjected,
kRecurrentComponent, kActivationFunction = 0x0200, kSoftmax, kHiddenSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kParametricRelu,
kDropout, kLengthNormComponent, kTranform = 0x0400, kRbm,
kSplice, kCopy, kTranspose, kBlockLinearity,
kAddShift, kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent,
kSimpleSentenceAveragingComponent, kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent,
kMaxPooling2DComponent, kFramePoolingComponent, kParallelComponent, kMultiBasisComponent
}
Component type identification mechanism,.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Converts component type to marker,.
static ComponentType MarkerToType (const std::string &s)
Converts marker to component type (case insensitive),.
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file,.
static Component * Read (std::istream &is, bool binary)
Read the component from a stream (static method),.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Detailed Description
Rearrange the matrix columns according to the indices in copy_from_indices_.
Definition at line 146 of file nnet-various.h.
Constructor & Destructor Documentation
CopyComponent()
CopyComponent (int32 dim_in, int32 dim_out) inline
Definition at line 148 of file nnet-various.h.
                                             :
     Component(dim_in, dim_out)
   { }
~CopyComponent()
~CopyComponent () inline
Definition at line 152 of file nnet-various.h.
   { }
Member Function Documentation
BackpropagateFnc()
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 221 of file nnet-various.h.
References Splice::GetType(), KALDI_WARN, CuMatrixBase< Real >::SetZero(), and Component::TypeToMarker().
{
     static bool warning_displayed = false;
     if (!warning_displayed) {
       KALDI_WARN << Component::TypeToMarker(GetType()) << " : "
                  << __func__ << "() Not implemented!";
       warning_displayed = true;
     }
     in_diff->SetZero();
   }
Copy()
Component* Copy () const inline virtual
Copy component (deep copy),.
Implements Component.
Definition at line 155 of file nnet-various.h.
 { return new CopyComponent(*this); }
GetType()
ComponentType GetType () const inline virtual
Get Type Identification of the component,.
Implements Component.
Definition at line 156 of file nnet-various.h.
References Component::kCopy.
 { return kCopy; }
Info()
std::string Info () const inline virtual
Print some additional info (after <ComponentName> and the dims),.
Reimplemented from Component.
Definition at line 211 of file nnet-various.h.
References kaldi::nnet1::ToString().
{
     return std::string("\n  min ") + ToString(copy_from_indices_.Min()) +
                          ", max "  + ToString(copy_from_indices_.Max());
   }
InitData()
void InitData (std::istream & is) inline virtual
Virtual interface for initialization and I/O,.
Initialize internal data of a component
Reimplemented from Component.
Definition at line 158 of file nnet-various.h.
References kaldi::nnet1::BuildIntegerVector(), Component::InputDim(), KALDI_ASSERT, KALDI_ERR, Component::OutputDim(), kaldi::ReadToken(), and kaldi::SplitStringToIntegers().
{
     // define options,
     std::vector<std::vector<int32> > build_vector;
     // parse config,
     std::string token;
     while (is >> std::ws, !is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<ReadVector>") {
         copy_from_indices_.Read(is, false);
       } else if (token == "<BuildVector>") {
         // <BuildVector> 1:1:1000 1:1:1000 1 2 3 1:10 </BuildVector>
         // 'matlab-line' indexing, read the colon-separated-lists:
         while (is >> std::ws, !is.eof()) {
           std::string colon_sep_list_or_end;
           ReadToken(is, false, &colon_sep_list_or_end);
           if (colon_sep_list_or_end == "</BuildVector>") break;
           std::vector<int32> v;
           SplitStringToIntegers(colon_sep_list_or_end, ":", false, &v);
           build_vector.push_back(v);
         }
       } else {
         KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                   << " (ReadVector|BuildVector)";
       }
     }
     if (build_vector.size() > 0) {
       // build the vector, using <BuildVector> ... </BuildVector> inputs,
       BuildIntegerVector(build_vector, &copy_from_indices_);
     }
     // decrease by 1,
     copy_from_indices_.Add(-1);
     // check range,
     KALDI_ASSERT(copy_from_indices_.Min() >= 0);
     KALDI_ASSERT(copy_from_indices_.Max() < InputDim());
     // check dim,
     KALDI_ASSERT(copy_from_indices_.Dim() == OutputDim());
   }
PropagateFnc()
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 216 of file nnet-various.h.
References kaldi::cu::Copy().
{
     cu::Copy(in, copy_from_indices_,out);
   }
ReadData()
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 199 of file nnet-various.h.
References KALDI_ASSERT, and Component::OutputDim().
{
     copy_from_indices_.Read(is, binary);
     KALDI_ASSERT(copy_from_indices_.Dim() == OutputDim());
     copy_from_indices_.Add(-1);  // -1 from each element,
   }
WriteData()
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 205 of file nnet-various.h.
References CuArrayBase< T >::Add(), and CuArray< T >::Write().
{
     CuArray<int32> tmp(copy_from_indices_);
     tmp.Add(1);  // +1 to each element,
     tmp.Write(os, binary);
   }
Member Data Documentation
copy_from_indices_
CuArray<int32> copy_from_indices_ protected
Definition at line 236 of file nnet-various.h.
The documentation for this class was generated from the following file:
nnet/nnet-various.h