Kaldi: OnlineTransform Class Reference
OnlineTransform Class Reference
OnlineFeatureExtraction
This online-feature class implements any affine or linear transform.
#include <online-feature.h>
Public Member Functions
virtual int32 Dim () const
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual BaseFloat FrameShiftInSeconds () const
virtual int32 NumFramesReady () const
returns the feature dimension.
virtual void GetFrame (int32 frame, VectorBase< BaseFloat > *feat)
Gets the feature vector for this frame.
OnlineTransform (const MatrixBase< BaseFloat > &transform, OnlineFeatureInterface *src)
The transform can be a linear transform, or an affine transform where the last column is the offset.
Public Member Functions inherited from OnlineFeatureInterface
virtual ~OnlineFeatureInterface ()
Virtual destructor.
Private Attributes
OnlineFeatureInterface * src_
Matrix< BaseFloat > linear_term_
Vector< BaseFloat > offset_
Detailed Description
This online-feature class implements any affine or linear transform.
Definition at line 457 of file online-feature.h.
Constructor & Destructor Documentation
OnlineTransform()
OnlineTransform (const MatrixBase< BaseFloat > & transform, OnlineFeatureInterface * src)
The transform can be a linear transform, or an affine transform where the last column is the offset.
Definition at line 409 of file online-feature.cc.
References OnlineFeatureInterface::Dim(), KALDI_ERR, OnlineTransform::linear_term_, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), OnlineTransform::offset_, MatrixBase< Real >::Range(), and OnlineTransform::src_.
                                                              :
     src_(src) {
   int32 src_dim = src_->Dim();
   if (transform.NumCols() == src_dim) {  // Linear transform
     linear_term_ = transform;
     offset_.Resize(transform.NumRows());  // Resize() will zero it.
   } else if (transform.NumCols() == src_dim + 1) {  // Affine transform
     linear_term_ = transform.Range(0, transform.NumRows(), 0, src_dim);
     offset_.Resize(transform.NumRows());
     offset_.CopyColFromMat(transform, src_dim);
   } else {
     KALDI_ERR << "Dimension mismatch: source features have dimension "
               << src_dim << " and LDA #cols is " << transform.NumCols();
   }
 }
Member Function Documentation
Dim()
virtual int32 Dim () const inline virtual
Implements OnlineFeatureInterface.
Definition at line 462 of file online-feature.h.
Referenced by OnlineDeltaFeature::GetFrame().
 { return offset_.Dim(); }
FrameShiftInSeconds()
virtual BaseFloat FrameShiftInSeconds () const inline virtual
Implements OnlineFeatureInterface.
Definition at line 467 of file online-feature.h.
{
     return src_->FrameShiftInSeconds();
   }
GetFrame()
void GetFrame (int32 frame, VectorBase< BaseFloat > * feat) virtual
Gets the feature vector for this frame.
Before calling this for a given frame, it is assumed that you called NumFramesReady() and it returned a number greater than "frame". Otherwise this call will likely crash with an assert failure. This function is not declared const, in case there is some kind of caching going on, but most of the time it shouldn't modify the class.
Implements OnlineFeatureInterface.
Definition at line 426 of file online-feature.cc.
References VectorBase< Real >::AddMatVec(), VectorBase< Real >::CopyFromVec(), OnlineFeatureInterface::GetFrame(), kaldi::kNoTrans, OnlineTransform::linear_term_, MatrixBase< Real >::NumCols(), OnlineTransform::offset_, and OnlineTransform::src_.
{
   Vector<BaseFloat> input_feat(linear_term_.NumCols());
   src_->GetFrame(frame, &input_feat);
   feat->CopyFromVec(offset_);
   feat->AddMatVec(1.0, linear_term_, kNoTrans, input_feat, 1.0);
 }
IsLastFrame()
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frame indices are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). This function may return false for some frame if we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. This function exists mainly to correctly handle end effects in feature extraction, and is not a mechanism to determine how many frames are in the decodable object (as it used to be, and for backward compatibility, still is, in the Decodable interface).
Implements OnlineFeatureInterface.
Definition at line 464 of file online-feature.h.
{
     return src_->IsLastFrame(frame);
   }
NumFramesReady()
virtual int32 NumFramesReady () const inline virtual
returns the feature dimension.
Returns the total number of frames, since the start of the utterance, that are now available. In an online-decoding context, this will likely increase with time as more data becomes available.
Implements OnlineFeatureInterface.
Definition at line 471 of file online-feature.h.
References OnlineGenericBaseFeature< C >::GetFrame().
Referenced by OnlineDeltaFeature::GetFrame().
 { return src_->NumFramesReady(); }
Member Data Documentation
linear_term_
Matrix<BaseFloat> linear_term_ private
Definition at line 487 of file online-feature.h.
Referenced by OnlineTransform::GetFrame(), and OnlineTransform::OnlineTransform().
offset_
Vector<BaseFloat> offset_ private
Definition at line 488 of file online-feature.h.
Referenced by OnlineTransform::GetFrame(), and OnlineTransform::OnlineTransform().
src_
OnlineFeatureInterface* src_ private
Definition at line 486 of file online-feature.h.
Referenced by OnlineDeltaFeature::Dim(), OnlineTransform::GetFrame(), OnlineDeltaFeature::GetFrame(), OnlineDeltaFeature::NumFramesReady(), and OnlineTransform::OnlineTransform().
The documentation for this class was generated from the following files:
feat/online-feature.h
feat/online-feature.cc