Kaldi: OutputImplBase Class Reference
OutputImplBase Class Reference abstract
Public Member Functions
virtual bool Open (const std::string &filename, bool binary)=0
virtual std::ostream & Stream ()=0
virtual bool Close ()=0
virtual ~OutputImplBase ()
Detailed Description
Definition at line 188 of file kaldi-io.cc.
Constructor & Destructor Documentation
~OutputImplBase()
virtual ~OutputImplBase () inline virtual
Definition at line 195 of file kaldi-io.cc.
 { }
Member Function Documentation
Close()
virtual bool Close () pure virtual
Implemented in PipeOutputImpl, StandardOutputImpl, and FileOutputImpl.
Referenced by Output::Close(), Output::~Output(), PipeInputImpl::~PipeInputImpl(), and PipeOutputImpl::~PipeOutputImpl().
Open()
virtual bool Open (const std::string & filename, bool binary) pure virtual
Implemented in PipeOutputImpl, StandardOutputImpl, and FileOutputImpl.
Referenced by Output::Open().
Stream()
virtual std::ostream& Stream () pure virtual
Implemented in PipeOutputImpl, StandardOutputImpl, and FileOutputImpl.
Referenced by Output::Open(), and Output::Stream().
The documentation for this class was generated from the following file:
util/kaldi-io.cc