Kaldi: Xent Class Reference
Xent Class Reference
#include <nnet-loss.h>
Public Member Functions
Xent (LossOptions &opts)
~Xent ()
void Eval (const VectorBase< BaseFloat > &frame_weights, const CuMatrixBase< BaseFloat > &net_out, const CuMatrixBase< BaseFloat > &target, CuMatrix< BaseFloat > *diff)
Evaluate cross entropy using target-matrix (supports soft labels),.
void Eval (const VectorBase< BaseFloat > &frame_weights, const CuMatrixBase< BaseFloat > &net_out, const Posterior &target, CuMatrix< BaseFloat > *diff)
Evaluate cross entropy using target-posteriors (supports soft labels),.
std::string Report ()
Generate string with error report,.
std::string ReportPerClass ()
Generate string with per-class error report,.
BaseFloat AvgLoss ()
Get loss value (frame average),.
Public Member Functions inherited from LossItf
LossItf (LossOptions &opts)
virtual ~LossItf ()
Private Attributes
CuVector< double > frames_
Vector< double > correct_
CuVector< double > xentropy_
CuVector< double > entropy_
double frames_progress_
double xentropy_progress_
double entropy_progress_
std::vector< float > loss_vec_
double elapsed_seconds_
CuVector< BaseFloat > frame_weights_
CuVector< BaseFloat > target_sum_
CuMatrix< BaseFloat > tgt_mat_
CuMatrix< BaseFloat > frames_aux_
CuMatrix< BaseFloat > xentropy_aux_
CuMatrix< BaseFloat > entropy_aux_
CuArray< int32 > max_id_out_
CuArray< int32 > max_id_tgt_
Additional Inherited Members
Protected Attributes inherited from LossItf
LossOptions opts_
Timer timer_
Detailed Description
Definition at line 82 of file nnet-loss.h.
Constructor & Destructor Documentation
Xent()
Xent (LossOptions & opts) inline
Definition at line 84 of file nnet-loss.h.
Referenced by MultiTaskLoss::InitFromString().
                          :
     LossItf(opts),
     frames_progress_(0.0),
     xentropy_progress_(0.0),
     entropy_progress_(0.0),
     elapsed_seconds_(0.0)
   { }
~Xent()
~Xent () inline
Definition at line 92 of file nnet-loss.h.
   { }
Member Function Documentation
AvgLoss()
BaseFloat AvgLoss () inline virtual
Get loss value (frame average),.
Implements LossItf.
Definition at line 114 of file nnet-loss.h.
Referenced by MultiTaskLoss::Report().
                       {
     if (frames_.Sum() == 0) return 0.0;
     return (xentropy_.Sum() - entropy_.Sum()) / frames_.Sum();
   }
Eval() [1/2]
void Eval (const VectorBase< BaseFloat > & frame_weights, const CuMatrixBase< BaseFloat > & net_out, const CuMatrixBase< BaseFloat > & target, CuMatrix< BaseFloat > * diff) virtual
Evaluate cross entropy using target-matrix (supports soft labels),.
Implements LossItf.
Definition at line 62 of file nnet-loss.cc.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddRowSumMat(), Xent::correct_, kaldi::nnet1::CountCorrectFramesWeighted(), VectorBase< Real >::Dim(), CuVectorBase< Real >::Dim(), Timer::Elapsed(), Xent::elapsed_seconds_, Xent::entropy_, Xent::entropy_aux_, Xent::entropy_progress_, CuMatrixBase< Real >::FindRowMaxId(), Xent::frame_weights_, Xent::frames_, Xent::frames_aux_, Xent::frames_progress_, KALDI_ASSERT, KALDI_ISFINITE, KALDI_LOG, LossOptions::loss_report_frames, Xent::loss_vec_, Xent::max_id_out_, Xent::max_id_tgt_, CuMatrixBase< Real >::MulRowsVec(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), LossItf::opts_, CuVector< Real >::Resize(), Vector< Real >::Resize(), CuVectorBase< Real >::Sum(), VectorBase< Real >::Sum(), CuMatrixBase< Real >::Sum(), Xent::target_sum_, LossItf::timer_, Xent::xentropy_, Xent::xentropy_aux_, and Xent::xentropy_progress_.
Referenced by Xent::Eval(), Mse::Eval(), and main().
{
   // check inputs,
   KALDI_ASSERT(net_out.NumCols() == targets.NumCols());
   KALDI_ASSERT(net_out.NumRows() == targets.NumRows());
   KALDI_ASSERT(net_out.NumRows() == frame_weights.Dim());
   KALDI_ASSERT(KALDI_ISFINITE(frame_weights.Sum()));
   KALDI_ASSERT(KALDI_ISFINITE(net_out.Sum()));
   KALDI_ASSERT(KALDI_ISFINITE(targets.Sum()));
   // buffer initialization,
   int32 num_classes = targets.NumCols();
   if (frames_.Dim() == 0) {
     frames_.Resize(num_classes);
     xentropy_.Resize(num_classes);
     entropy_.Resize(num_classes);
     correct_.Resize(num_classes);
   }
   // get frame_weights to GPU,
   frame_weights_ = frame_weights;
   // There may be frames for which the sum of targets is zero.
   // This happens in multi-lingual training when the frame
   // has target class in the softmax of another language.
   // We 'switch-off' such frames by masking the 'frame_weights_',
   target_sum_.Resize(targets.NumRows());
   target_sum_.AddColSumMat(1.0, targets, 0.0);
   frame_weights_.MulElements(target_sum_);
   // compute derivative wrt. activations of last layer of neurons,
   *diff = net_out;
   diff->AddMat(-1.0, targets);
   diff->MulRowsVec(frame_weights_);  // weighting,
   // count frames per class,
   frames_aux_ = targets;
   frames_aux_.MulRowsVec(frame_weights_);
   frames_.AddRowSumMat(1.0, CuMatrix<double>(frames_aux_));
   // evaluate the frame-level classification,
   net_out.FindRowMaxId(&max_id_out_);  // find max in nn-output
   targets.FindRowMaxId(&max_id_tgt_);  // find max in targets
   CountCorrectFramesWeighted(max_id_out_, max_id_tgt_,
                              frame_weights_, &correct_);
   // calculate cross_entropy (in GPU),
   xentropy_aux_ = net_out;  // y
   xentropy_aux_.Add(1e-20);  // avoid log(0)
   xentropy_aux_.ApplyLog();  // log(y)
   xentropy_aux_.MulElements(targets);  // t*log(y)
   xentropy_aux_.MulRowsVec(frame_weights_);  // w*t*log(y)
   xentropy_.AddRowSumMat(-1.0, CuMatrix<double>(xentropy_aux_));
   // caluculate entropy (in GPU),
   entropy_aux_ = targets;  // t
   entropy_aux_.Add(1e-20);  // avoid log(0)
   entropy_aux_.ApplyLog();  // log(t)
   entropy_aux_.MulElements(targets);  // t*log(t)
   entropy_aux_.MulRowsVec(frame_weights_);  // w*t*log(t)
   entropy_.AddRowSumMat(-1.0, CuMatrix<double>(entropy_aux_));
   // progressive loss reporting
   if (opts_.loss_report_frames > 0) {
     frames_progress_ += frame_weights_.Sum();
     xentropy_progress_ += -xentropy_aux_.Sum();
     entropy_progress_ += -entropy_aux_.Sum();
     KALDI_ASSERT(KALDI_ISFINITE(xentropy_progress_));
     KALDI_ASSERT(KALDI_ISFINITE(entropy_progress_));
     if (frames_progress_ > opts_.loss_report_frames) {
       // loss value,
       double progress_value =
         (xentropy_progress_ - entropy_progress_) / frames_progress_;
       // time-related info (fps is weighted),
       double time_now = timer_.Elapsed();
       double fps = frames_progress_ / (time_now - elapsed_seconds_);
       double elapsed_hours = time_now / 3600;
       elapsed_seconds_ = time_now; // store,
       // print,
       KALDI_LOG << "ProgressLoss[last "
                 << static_cast<int>(frames_progress_/100/3600) << "h of "
                 << static_cast<int>(frames_.Sum()/100/3600) << "h]: "
                 << progress_value << " (Xent)"
                 << ", fps=" << fps
                 << std::setprecision(3)
                 << ", elapsed " << elapsed_hours << "h";
       // store,
       loss_vec_.push_back(progress_value);
       // reset,
       frames_progress_ = 0;
       xentropy_progress_ = 0.0;
       entropy_progress_ = 0.0;
     }
   }
 }
Eval() [2/2]
void Eval (const VectorBase< BaseFloat > & frame_weights, const CuMatrixBase< BaseFloat > & net_out, const Posterior & target, CuMatrix< BaseFloat > * diff) virtual
Evaluate cross entropy using target-posteriors (supports soft labels),.
Implements LossItf.
Definition at line 166 of file nnet-loss.cc.
References Xent::Eval(), KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), kaldi::nnet1::PosteriorToMatrix(), and Xent::tgt_mat_.
{
   int32 num_frames = net_out.NumRows(),
     num_pdf = net_out.NumCols();
   KALDI_ASSERT(num_frames == post.size());
   // convert posterior to matrix,
   PosteriorToMatrix(post, num_pdf, &tgt_mat_);
   // call the other eval function,
   Eval(frame_weights, net_out, tgt_mat_, diff);
 }
Report()
std::string Report () virtual
Generate string with error report,.
Implements LossItf.
Definition at line 182 of file nnet-loss.cc.
References Xent::correct_, Xent::entropy_, Xent::frames_, Xent::loss_vec_, CuVectorBase< Real >::Sum(), VectorBase< Real >::Sum(), and Xent::xentropy_.
Referenced by main().
{
   double loss_value =
     (xentropy_.Sum() - entropy_.Sum()) / frames_.Sum();
   std::ostringstream oss;
   oss << "AvgLoss: " << loss_value << " (Xent), "
       << "[AvgXent: " << xentropy_.Sum() / frames_.Sum()
       << ", AvgTargetEnt: " << entropy_.Sum() / frames_.Sum()
       << "]" << std::endl;
   oss << "progress: [";
   std::copy(loss_vec_.begin(), loss_vec_.end(),
             std::ostream_iterator<float>(oss, " "));
   oss << "]" << std::endl;
   double frame_accuracy = 100.0 * correct_.Sum() / frames_.Sum();
   oss << "FRAME_ACCURACY >> " << frame_accuracy << "% <<" << std::endl;
   return oss.str();
 }
ReportPerClass()
std::string ReportPerClass ()
Generate string with per-class error report,.
Definition at line 203 of file nnet-loss.cc.
References CuVectorBase< Real >::Add(), CuVectorBase< Real >::AddVec(), CuVectorBase< Real >::ApplyPow(), Xent::correct_, Xent::entropy_, Xent::frames_, CuVectorBase< Real >::MulElements(), CuVectorBase< Real >::Scale(), and Xent::xentropy_.
Referenced by main().
{
   std::ostringstream oss;
   oss << "PER-CLASS PERFORMANCE:" << std::endl;
   oss << "@@@ Frames per-class:" << frames_;
   // get inverted counts,
   CuVector<double> inv_frames(frames_);
   inv_frames.Add(0.5);  // avoid 0-frames,
   inv_frames.ApplyPow(-1.0);
   // loss, kl = xentropy-entropy,
   CuVector<double> loss(xentropy_);
   loss.AddVec(-1.0, entropy_);
   loss.MulElements(inv_frames);
   oss << "@@@ Loss per-class:" << loss;
   // frame accuracy (assuming targets are binary),
   CuVector<double> frm_accu(correct_);
   frm_accu.MulElements(inv_frames);
   frm_accu.Scale(100.0);
   oss << "@@@ Frame-accuracy per-class:" << frm_accu;
   //
   return oss.str();
 }
Member Data Documentation
correct_
Vector<double> correct_ private
Definition at line 122 of file nnet-loss.h.
Referenced by Xent::Eval(), Xent::Report(), and Xent::ReportPerClass().
elapsed_seconds_
double elapsed_seconds_ private
Definition at line 131 of file nnet-loss.h.
Referenced by Xent::Eval().
entropy_
CuVector<double> entropy_ private
Definition at line 124 of file nnet-loss.h.
Referenced by Xent::Eval(), Xent::Report(), and Xent::ReportPerClass().
entropy_aux_
CuMatrix<BaseFloat> entropy_aux_ private
Definition at line 141 of file nnet-loss.h.
Referenced by Xent::Eval().
entropy_progress_
double entropy_progress_ private
Definition at line 129 of file nnet-loss.h.
Referenced by Xent::Eval().
frame_weights_
CuVector<BaseFloat> frame_weights_ private
Definition at line 134 of file nnet-loss.h.
Referenced by Xent::Eval(), and Mse::Eval().
frames_
CuVector<double> frames_ private
Definition at line 121 of file nnet-loss.h.
Referenced by Xent::Eval(), Mse::Eval(), Xent::Report(), Mse::Report(), and Xent::ReportPerClass().
frames_aux_
CuMatrix<BaseFloat> frames_aux_ private
Definition at line 139 of file nnet-loss.h.
Referenced by Xent::Eval().
frames_progress_
double frames_progress_ private
Definition at line 127 of file nnet-loss.h.
Referenced by Xent::Eval(), and Mse::Eval().
loss_vec_
std::vector<float> loss_vec_ private
Definition at line 130 of file nnet-loss.h.
Referenced by MultiTaskLoss::AvgLoss(), Xent::Eval(), Mse::Eval(), MultiTaskLoss::Eval(), MultiTaskLoss::InitFromString(), Xent::Report(), Mse::Report(), and MultiTaskLoss::Report().
max_id_out_
CuArray<int32> max_id_out_ private
Definition at line 144 of file nnet-loss.h.
Referenced by Xent::Eval().
max_id_tgt_
CuArray<int32> max_id_tgt_ private
Definition at line 145 of file nnet-loss.h.
Referenced by Xent::Eval().
target_sum_
CuVector<BaseFloat> target_sum_ private
Definition at line 135 of file nnet-loss.h.
Referenced by Xent::Eval().
tgt_mat_
CuMatrix<BaseFloat> tgt_mat_ private
Definition at line 138 of file nnet-loss.h.
Referenced by Xent::Eval(), Mse::Eval(), and MultiTaskLoss::Eval().
xentropy_
CuVector<double> xentropy_ private
Definition at line 123 of file nnet-loss.h.
Referenced by Xent::Eval(), Xent::Report(), and Xent::ReportPerClass().
xentropy_aux_
CuMatrix<BaseFloat> xentropy_aux_ private
Definition at line 140 of file nnet-loss.h.
Referenced by Xent::Eval().
xentropy_progress_
double xentropy_progress_ private
Definition at line 128 of file nnet-loss.h.
Referenced by Xent::Eval().
The documentation for this class was generated from the following files:
nnet/nnet-loss.h
nnet/nnet-loss.cc