Kaldi: DistributeComponent Class Reference
DistributeComponent Class Reference
This Component takes a larger input-dim than output-dim, where the input-dim must be a multiple of the output-dim, and distributes different blocks of the input dimension to different 'x' values.
#include <nnet-general-component.h>
Public Member Functions
DistributeComponent (int32 input_dim, int32 output_dim)
DistributeComponent ()
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
void Init (int32 input_dim, int32 output_dim)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
void ComputeInputIndexAndBlock (const Index &output_index, Index *input_index, int32 *block) const
void ComputeInputPointers (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, int32 num_output_rows, std::vector< const BaseFloat *> *input_pointers) const
void ComputeInputPointers (const ComponentPrecomputedIndexes *indexes, int32 num_output_rows, CuMatrixBase< BaseFloat > *in, std::vector< BaseFloat *> *input_pointers) const
Private Attributes
int32 input_dim_
int32 output_dim_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
This Component takes a larger input-dim than output-dim, where the input-dim must be a multiple of the output-dim, and distributes different blocks of the input dimension to different 'x' values.
In the normal case where the input is only valid at x=0, the first block of output goes to x=0, the second block at x=1, and so on. It also supports a more general usage, so in general a value 'x' at the output will map to block 'x % n_blocks' of the dimension blocks of the input, and to an x value 'x / n_blocks' of the input. For negative x values the % and / operations are always rounded down, not towards zero.
The config line is of the form input-dim=xx output-dim=xx where input-dim must be a multiple of the output-dim, and n_blocks is set to input-dim / output-dim.
Definition at line 56 of file nnet-general-component.h.
Constructor & Destructor Documentation
DistributeComponent() [1/2]
DistributeComponent (int32 input_dim, int32 output_dim) inline
Definition at line 58 of file nnet-general-component.h.
References DistributeComponent::Init().
{
     Init(input_dim, output_dim);
   }
DistributeComponent() [2/2]
DistributeComponent () inline
Definition at line 61 of file nnet-general-component.h.
Referenced by DistributeComponent::Copy().
 : input_dim_(0), output_dim_(0) { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 194 of file nnet-general-component.cc.
References DistributeComponent::ComputeInputPointers(), CuMatrixBase< Real >::CopyToRows(), DistributeComponent::input_dim_, CuMatrixBase< Real >::NumRows(), DistributeComponent::output_dim_, and CuMatrixBase< Real >::SetZero().
Referenced by DistributeComponent::Properties(), StatisticsExtractionComponent::Properties(), StatisticsPoolingComponent::Properties(), BackpropTruncationComponent::Properties(), ConstantComponent::Properties(), and GeneralDropoutComponent::Properties().
{
   if (in_deriv == NULL) return;
   int32 num_blocks = input_dim_ / output_dim_,
       num_output_rows = out_deriv.NumRows();
   if (num_output_rows != in_deriv->NumRows() * num_blocks) {
     // there could be some 'gaps', i.e. some input values that are not ever
     // referred to.  So we need to zero the input.  This would't happen in the
     // setups I plan to use this for.
     in_deriv->SetZero();
   }
   std::vector<BaseFloat*> input_pointers;
   ComputeInputPointers(indexes, num_output_rows, in_deriv, &input_pointers);
   CuArray<BaseFloat*> input_pointers_cuda(input_pointers);
   out_deriv.CopyToRows(input_pointers_cuda);
 }
ComputeInputIndexAndBlock()
void ComputeInputIndexAndBlock (const Index & output_index, Index * input_index, int32 * block) const inline private
Definition at line 46 of file nnet-general-component.cc.
References DistributeComponent::input_dim_, DistributeComponent::output_dim_, and Index::x.
Referenced by DistributeComponent::Copy(), DistributeComponent::GetInputIndexes(), DistributeComponent::IsComputable(), and DistributeComponent::PrecomputeIndexes().
{
   int32 num_blocks = input_dim_ / output_dim_;
   *input_index = output_index;
   int32 output_x = output_index.x, input_x;
   if (output_x >= 0) {
     input_x = output_x / num_blocks;
   } else {
     input_x = (output_x - num_blocks + 1) / num_blocks;
   }
   input_index->x = input_x;
   if (block)
     *block = output_x - (input_x * num_blocks);
 }
ComputeInputPointers() [1/2]
void ComputeInputPointers (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, int32 num_output_rows, std::vector< const BaseFloat *> * input_pointers) const inline private
Definition at line 134 of file nnet-general-component.cc.
References CuMatrixBase< Real >::Data(), rnnlm::i, KALDI_ASSERT, DistributeComponentPrecomputedIndexes::pairs, and CuMatrixBase< Real >::Stride().
Referenced by DistributeComponent::Backprop(), DistributeComponent::Copy(), and DistributeComponent::Propagate().
{
   const DistributeComponentPrecomputedIndexes *indexes =
       dynamic_cast<const DistributeComponentPrecomputedIndexes*>(indexes_in);
   KALDI_ASSERT(indexes != NULL && "Invalid pointer type");
   KALDI_ASSERT(num_output_rows == static_cast<int32>(indexes->pairs.size()));
   input_pointers->resize(num_output_rows);
   const BaseFloat *input_data = in.Data();
   int32 input_stride = in.Stride();
   const BaseFloat **input_pointers_data = &((*input_pointers)[0]);
   const std::pair<int32, int32> *pairs_data = &(indexes->pairs[0]);
   for (int32 i = 0; i < num_output_rows; i++) {
     input_pointers_data[i] = input_data +
         pairs_data[i].first * input_stride +
         pairs_data[i].second;
   }
 }
ComputeInputPointers() [2/2]
void ComputeInputPointers (const ComponentPrecomputedIndexes * indexes, int32 num_output_rows, CuMatrixBase< BaseFloat > * in, std::vector< BaseFloat *> * input_pointers) const inline private
Definition at line 156 of file nnet-general-component.cc.
References CuMatrixBase< Real >::Data(), rnnlm::i, KALDI_ASSERT, DistributeComponentPrecomputedIndexes::pairs, and CuMatrixBase< Real >::Stride().
{
   const DistributeComponentPrecomputedIndexes *indexes =
       dynamic_cast<const DistributeComponentPrecomputedIndexes*>(indexes_in);
   KALDI_ASSERT(indexes != NULL && "Invalid pointer type");
   KALDI_ASSERT(num_output_rows == static_cast<int32>(indexes->pairs.size()));
   input_pointers->resize(num_output_rows);
   BaseFloat *input_data = in->Data();
   int32 input_stride = in->Stride();
   BaseFloat **input_pointers_data = &((*input_pointers)[0]);
   const std::pair<int32, int32> *pairs_data = &(indexes->pairs[0]);
   for (int32 i = 0; i < num_output_rows; i++) {
     input_pointers_data[i] = input_data +
         pairs_data[i].first * input_stride +
         pairs_data[i].second;
   }
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 86 of file nnet-general-component.h.
References DistributeComponent::ComputeInputIndexAndBlock(), DistributeComponent::ComputeInputPointers(), DistributeComponent::DistributeComponent(), DistributeComponent::GetInputIndexes(), DistributeComponent::Init(), DistributeComponent::input_dim_, DistributeComponent::IsComputable(), DistributeComponent::output_dim_, and DistributeComponent::PrecomputeIndexes().
Referenced by DropoutMaskComponent::Backprop(), GeneralDropoutComponent::DeleteMemo(), BackpropTruncationComponent::Properties(), and ConstantComponent::Properties().
{
     return new DistributeComponent(input_dim_, output_dim_);
   }
GetInputIndexes()
void GetInputIndexes (const MiscComputationInfo & misc_info, const Index & output_index, std::vector< Index > * desired_indexes) const virtual
This function only does something interesting for non-simple Components.
For a given index at the output of the component, tells us what indexes are required at its input (note: "required" encompasses also optionally-required things; it will enumerate all things that we'd like to have). See also IsComputable().
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. We will add members to misc_info as needed.
[in] output_index The Index at the output of the component, for which we are requesting the list of indexes at the component's input.
[out] desired_indexes A list of indexes that are desired at the input. are to be written to here. By "desired" we mean required or optionally-required.
The default implementation of this function is suitable for any SimpleComponent; it just copies the output_index to a single identical element in input_indexes.
Reimplemented from Component.
Definition at line 63 of file nnet-general-component.cc.
References DistributeComponent::ComputeInputIndexAndBlock().
Referenced by DistributeComponent::Copy(), StatisticsExtractionComponent::Copy(), and StatisticsPoolingComponent::Copy().
{
   desired_indexes->resize(1);
   ComputeInputIndexAndBlock(output_index, &((*desired_indexes)[0]), NULL);
 }
Init()
void Init (int32 input_dim, int32 output_dim)
Definition at line 220 of file nnet-general-component.cc.
References DistributeComponent::input_dim_, KALDI_ASSERT, and DistributeComponent::output_dim_.
Referenced by BackpropTruncationComponent::BackpropTruncationComponent(), DistributeComponent::Copy(), DistributeComponent::DistributeComponent(), DistributeComponent::InitFromConfig(), and BackpropTruncationComponent::OutputDim().
{
   input_dim_ = input_dim;
   output_dim_ = output_dim;
   KALDI_ASSERT(input_dim > 0 && output_dim > 0 && input_dim % output_dim == 0);
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 227 of file nnet-general-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), DistributeComponent::Init(), KALDI_ERR, DistributeComponent::Type(), and ConfigLine::WholeLine().
Referenced by DistributeComponent::OutputDim(), StatisticsExtractionComponent::OutputDim(), StatisticsPoolingComponent::OutputDim(), BackpropTruncationComponent::OutputDim(), ConstantComponent::OutputDim(), DropoutMaskComponent::OutputDim(), and GeneralDropoutComponent::OutputDim().
{
   int32 input_dim, output_dim;
   bool ok = cfl->GetValue("input-dim", &input_dim) &&
       cfl->GetValue("output-dim", &output_dim);
   if (!ok || cfl->HasUnusedValues())
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   else
     Init(input_dim, output_dim);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 62 of file nnet-general-component.h.
References DistributeComponent::input_dim_.
 { return input_dim_; }
IsComputable()
bool IsComputable (const MiscComputationInfo & misc_info, const Index & output_index, const IndexSet & input_index_set, std::vector< Index > * used_inputs) const virtual
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
It tells the user whether a given output index is computable from a given set of input indexes, and if so, says which input indexes will be used in the computation.
Implementations of this function are required to have the property that adding an element to "input_index_set" can only ever change IsComputable from false to true, never vice versa.
Parameters
[in] misc_info Some information specific to the computation, such as minimum and maximum times for certain components to do adaptation on; it's a place to put things that don't easily fit in the framework.
[in] output_index The index that is to be computed at the output of this Component.
[in] input_index_set The set of indexes that is available at the input of this Component.
[out] used_inputs If this is non-NULL and the output is computable this will be set to the list of input indexes that will actually be used in the computation.
Returns
Returns true iff this output is computable from the provided inputs.
The default implementation of this function is suitable for any SimpleComponent: it just returns true if output_index is in input_index_set, and if so sets used_inputs to vector containing that one Index.
Reimplemented from Component.
Definition at line 72 of file nnet-general-component.cc.
References DistributeComponent::ComputeInputIndexAndBlock().
Referenced by DistributeComponent::Copy(), StatisticsExtractionComponent::Copy(), and StatisticsPoolingComponent::Copy().
{
   Index input_index;
   ComputeInputIndexAndBlock(output_index, &input_index, NULL);
   if (!input_index_set(input_index))
     return false;
   if (used_inputs) {
     used_inputs->clear();
     used_inputs->push_back(input_index);
   }
   return true;
 }
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 63 of file nnet-general-component.h.
References DistributeComponent::InitFromConfig(), and DistributeComponent::output_dim_.
 { return output_dim_; }
PrecomputeIndexes()
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo & misc_info, const std::vector< Index > & input_indexes, const std::vector< Index > & output_indexes, bool need_backprop) const virtual
This function must return NULL for simple Components.
Returns a pointer to a class that may contain some precomputed component-specific and computation-specific indexes to be in used in the Propagate and Backprop functions.
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. misc_info may not even ever be used here. We will add members to misc_info as needed.
[in] input_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the in/in_value/in_deriv matrices given to Propagate and Backprop will mean.
[in] output_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the out/out_value/out_deriv matrices given to Propagate and Backprop will mean.
[in] need_backprop True if we might need to do backprop with this component, so that if any different indexes are needed for backprop then those should be computed too.
Returns
Returns a child-class of class ComponentPrecomputedIndexes, or NULL if this component for does not need to precompute any indexes (e.g. if it is a simple component and does not care about indexes).
Reimplemented from Component.
Definition at line 102 of file nnet-general-component.cc.
References DistributeComponent::ComputeInputIndexAndBlock(), rnnlm::i, DistributeComponent::input_dim_, KALDI_ERR, DistributeComponent::output_dim_, and DistributeComponentPrecomputedIndexes::pairs.
Referenced by DistributeComponent::Copy(), StatisticsExtractionComponent::Copy(), StatisticsPoolingComponent::Copy(), GeneralDropoutComponent::DeleteMemo(), and BackpropTruncationComponent::Properties().
                 {  // the bool is 'need_backprop'- unused.
   unordered_map<Index, int32, IndexHasher> index_to_input_dim;
   int32 num_input_indexes = input_indexes.size(),
       num_output_indexes = output_indexes.size();
   for (int32 i = 0; i < num_input_indexes; i++)
     index_to_input_dim[input_indexes[i]] = i;
   DistributeComponentPrecomputedIndexes *ans = new
       DistributeComponentPrecomputedIndexes;
   ans->pairs.resize(output_indexes.size());
   int32 num_blocks = input_dim_ / output_dim_,
       block_size = input_dim_ / num_blocks;
   for (int32 i = 0; i < num_output_indexes; i++) {
     Index input_index;
     int32 block_index;
     ComputeInputIndexAndBlock(output_indexes[i], &input_index, &block_index);
     unordered_map<Index, int32, IndexHasher>::iterator iter =
         index_to_input_dim.find(input_index);
     if (iter == index_to_input_dim.end())
       KALDI_ERR << "Input index not found (code error)";
     int32 input_row = iter->second;
     ans->pairs[i] = std::pair<int32,int32>(input_row, block_index * block_size);
   }
   return ans;
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 180 of file nnet-general-component.cc.
References DistributeComponent::ComputeInputPointers(), CuMatrixBase< Real >::CopyRows(), DistributeComponent::input_dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and DistributeComponent::output_dim_.
Referenced by DistributeComponent::Properties(), StatisticsExtractionComponent::Properties(), StatisticsPoolingComponent::Properties(), BackpropTruncationComponent::Properties(), ConstantComponent::Properties(), DropoutMaskComponent::Properties(), and GeneralDropoutComponent::Properties().
{
   KALDI_ASSERT(indexes != NULL &&
                in.NumCols() == input_dim_ && out->NumCols() == output_dim_);
   int32 num_output_rows = out->NumRows();
   std::vector<const BaseFloat*> input_pointers;
   ComputeInputPointers(indexes, in, num_output_rows, &input_pointers);
   CuArray<const BaseFloat*> input_pointers_cuda(input_pointers);
   out->CopyRows(input_pointers_cuda);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 68 of file nnet-general-component.h.
References DistributeComponent::Backprop(), DistributeComponent::Propagate(), DistributeComponent::Read(), and DistributeComponent::Write().
 { return 0; }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 247 of file nnet-general-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), DistributeComponent::input_dim_, DistributeComponent::output_dim_, and kaldi::ReadBasicType().
Referenced by DropoutMaskComponent::Backprop(), DistributeComponentPrecomputedIndexes::Copy(), StatisticsExtractionComponentPrecomputedIndexes::Copy(), StatisticsPoolingComponentPrecomputedIndexes::Copy(), BackpropTruncationComponentPrecomputedIndexes::Copy(), GeneralDropoutComponentPrecomputedIndexes::Copy(), GeneralDropoutComponent::DeleteMemo(), DistributeComponent::Properties(), StatisticsExtractionComponent::Properties(), StatisticsPoolingComponent::Properties(), BackpropTruncationComponent::Properties(), and ConstantComponent::Properties().
{
   ExpectOneOrTwoTokens(is, binary, "<DistributeComponent>", "<InputDim>");
   ReadBasicType(is, binary, &input_dim_);
   ExpectToken(is, binary, "<OutputDim>");
   ReadBasicType(is, binary, &output_dim_);
   ExpectToken(is, binary, "</DistributeComponent>");
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 67 of file nnet-general-component.h.
Referenced by DistributeComponent::InitFromConfig().
 { return "DistributeComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 238 of file nnet-general-component.cc.
References DistributeComponent::input_dim_, DistributeComponent::output_dim_, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by DropoutMaskComponent::Backprop(), DistributeComponentPrecomputedIndexes::Copy(), StatisticsExtractionComponentPrecomputedIndexes::Copy(), StatisticsPoolingComponentPrecomputedIndexes::Copy(), BackpropTruncationComponentPrecomputedIndexes::Copy(), GeneralDropoutComponentPrecomputedIndexes::Copy(), GeneralDropoutComponent::DeleteMemo(), DistributeComponent::Properties(), StatisticsExtractionComponent::Properties(), StatisticsPoolingComponent::Properties(), BackpropTruncationComponent::Properties(), and ConstantComponent::Properties().
{
   WriteToken(os, binary, "<DistributeComponent>");
   WriteToken(os, binary, "<InputDim>");
   WriteBasicType(os, binary, input_dim_);
   WriteToken(os, binary, "<OutputDim>");
   WriteBasicType(os, binary, output_dim_);
   WriteToken(os, binary, "</DistributeComponent>");
 }
Member Data Documentation
input_dim_
int32 input_dim_ private
Definition at line 128 of file nnet-general-component.h.
Referenced by DistributeComponent::Backprop(), DistributeComponent::ComputeInputIndexAndBlock(), DistributeComponent::Copy(), DistributeComponent::Init(), DistributeComponent::InputDim(), StatisticsExtractionComponent::InputDim(), StatisticsPoolingComponent::InputDim(), StatisticsExtractionComponent::OutputDim(), StatisticsPoolingComponent::OutputDim(), DistributeComponent::PrecomputeIndexes(), DistributeComponent::Propagate(), DistributeComponent::Read(), and DistributeComponent::Write().
output_dim_
int32 output_dim_ private
Definition at line 129 of file nnet-general-component.h.
Referenced by DistributeComponent::Backprop(), DistributeComponent::ComputeInputIndexAndBlock(), DistributeComponent::Copy(), DistributeComponent::Init(), DropoutMaskComponent::InputDim(), DistributeComponent::OutputDim(), DropoutMaskComponent::OutputDim(), DistributeComponent::PrecomputeIndexes(), DistributeComponent::Propagate(), DistributeComponent::Read(), and DistributeComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc