Kaldi: OnlineGenericBaseFeature< C > Class Template Reference
OnlineGenericBaseFeature< C > Class Template Reference
OnlineFeatureExtraction
This is a templated class for online feature extraction; it's templated on a class like MfccComputer or PlpComputer that does the basic feature extraction.
#include <online-feature.h>
Public Member Functions
virtual int32 Dim () const
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual BaseFloat FrameShiftInSeconds () const
virtual int32 NumFramesReady () const
returns the feature dimension.
virtual void GetFrame (int32 frame, VectorBase< BaseFloat > *feat)
Gets the feature vector for this frame.
OnlineGenericBaseFeature (const typename C::Options &opts)
virtual void AcceptWaveform (BaseFloat sampling_rate, const VectorBase< BaseFloat > &waveform)
This would be called from the application, when you get more wave data.
virtual void InputFinished ()
InputFinished() tells the class you won't be providing any more waveform.
~OnlineGenericBaseFeature ()
Public Member Functions inherited from OnlineFeatureInterface
virtual ~OnlineFeatureInterface ()
Virtual destructor.
Private Member Functions
void ComputeFeatures ()
Private Attributes
C computer_
FeatureWindowFunction window_function_
std::vector< Vector< BaseFloat > * > features_
bool input_finished_
BaseFloat sampling_frequency_
int64 waveform_offset_
Vector< BaseFloat > waveform_remainder_
Detailed Description
template<class C>
class kaldi::OnlineGenericBaseFeature< C >
This is a templated class for online feature extraction; it's templated on a class like MfccComputer or PlpComputer that does the basic feature extraction.
Definition at line 48 of file online-feature.h.
Constructor & Destructor Documentation
OnlineGenericBaseFeature()
OnlineGenericBaseFeature (const typename C::Options & opts) explicit
Definition at line 35 of file online-feature.cc.
Referenced by OnlineGenericBaseFeature< C >::NumFramesReady().
                                   :
     computer_(opts), window_function_(computer_.GetFrameOptions()),
     input_finished_(false), waveform_offset_(0) { }
~OnlineGenericBaseFeature()
~OnlineGenericBaseFeature () inline
Definition at line 91 of file online-feature.h.
References OnlineGenericBaseFeature< C >::ComputeFeatures(), kaldi::DeletePointers(), and OnlineGenericBaseFeature< C >::features_.
{
     DeletePointers(&features_);
   }
Member Function Documentation
AcceptWaveform()
void AcceptWaveform (BaseFloat sampling_rate, const VectorBase< BaseFloat > & waveform) virtual
This would be called from the application, when you get more wave data.
Note: the sampling_rate is typically only provided so the code can assert that it matches the sampling rate expected in the options.
Implements OnlineBaseFeature.
Definition at line 41 of file online-feature.cc.
References OnlineGenericBaseFeature< C >::ComputeFeatures(), OnlineGenericBaseFeature< C >::computer_, VectorBase< Real >::Dim(), OnlineGenericBaseFeature< C >::input_finished_, KALDI_ERR, VectorBase< Real >::Range(), and OnlineGenericBaseFeature< C >::waveform_remainder_.
Referenced by OnlineGenericBaseFeature< C >::NumFramesReady(), kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), and kaldi::TestOnlineTransform().
{
   BaseFloat expected_sampling_rate = computer_.GetFrameOptions().samp_freq;
   if (sampling_rate != expected_sampling_rate)
     KALDI_ERR << "Sampling frequency mismatch, expected "
               << expected_sampling_rate << ", got " << sampling_rate;
   if (waveform.Dim() == 0)
     return;  // Nothing to do.
   if (input_finished_)
     KALDI_ERR << "AcceptWaveform called after InputFinished() was called.";
   // append 'waveform' to 'waveform_remainder_.'
   Vector<BaseFloat> appended_wave(waveform_remainder_.Dim() + waveform.Dim());
   if (waveform_remainder_.Dim() != 0)
     appended_wave.Range(0, waveform_remainder_.Dim()).CopyFromVec(
         waveform_remainder_);
   appended_wave.Range(waveform_remainder_.Dim(), waveform.Dim()).CopyFromVec(
       waveform);
   waveform_remainder_.Swap(&appended_wave);
   ComputeFeatures();
 }
ComputeFeatures()
void ComputeFeatures () private
Definition at line 63 of file online-feature.cc.
References OnlineGenericBaseFeature< C >::computer_, VectorBase< Real >::CopyFromVec(), kaldi::ExtractWindow(), OnlineGenericBaseFeature< C >::features_, kaldi::FirstSampleOfFrame(), OnlineGenericBaseFeature< C >::input_finished_, KALDI_ASSERT, kaldi::kUndefined, kaldi::NumFrames(), OnlineGenericBaseFeature< C >::waveform_offset_, OnlineGenericBaseFeature< C >::waveform_remainder_, and OnlineGenericBaseFeature< C >::window_function_.
Referenced by OnlineGenericBaseFeature< C >::AcceptWaveform(), OnlineGenericBaseFeature< C >::InputFinished(), and OnlineGenericBaseFeature< C >::~OnlineGenericBaseFeature().
{
   const FrameExtractionOptions &frame_opts = computer_.GetFrameOptions();
   int64 num_samples_total = waveform_offset_ + waveform_remainder_.Dim();
   int32 num_frames_old = features_.size(),
       num_frames_new = NumFrames(num_samples_total, frame_opts,
                                  input_finished_);
   KALDI_ASSERT(num_frames_new >= num_frames_old);
   features_.resize(num_frames_new, NULL);
   Vector<BaseFloat> window;
   bool need_raw_log_energy = computer_.NeedRawLogEnergy();
   for (int32 frame = num_frames_old; frame < num_frames_new; frame++) {
     BaseFloat raw_log_energy = 0.0;
     ExtractWindow(waveform_offset_, waveform_remainder_, frame,
                   frame_opts, window_function_, &window,
                   need_raw_log_energy ? &raw_log_energy : NULL);
     Vector<BaseFloat> *this_feature = new Vector<BaseFloat>(computer_.Dim(),
                                                             kUndefined);
     // note: this online feature-extraction code does not support VTLN.
     BaseFloat vtln_warp = 1.0;
     computer_.Compute(raw_log_energy, vtln_warp, &window, this_feature);
     features_[frame] = this_feature;
   }
   // OK, we will now discard any portion of the signal that will not be
   // necessary to compute frames in the future.
   int64 first_sample_of_next_frame = FirstSampleOfFrame(num_frames_new,
                                                         frame_opts);
   int32 samples_to_discard = first_sample_of_next_frame - waveform_offset_;
   if (samples_to_discard > 0) {
     // discard the leftmost part of the waveform that we no longer need.
     int32 new_num_samples = waveform_remainder_.Dim() - samples_to_discard;
     if (new_num_samples <= 0) {
       // odd, but we'll try to handle it.
       waveform_offset_ += waveform_remainder_.Dim();
       waveform_remainder_.Resize(0);
     } else {
       Vector<BaseFloat> new_remainder(new_num_samples);
       new_remainder.CopyFromVec(waveform_remainder_.Range(samples_to_discard,
                                                           new_num_samples));
       waveform_offset_ += samples_to_discard;
       waveform_remainder_.Swap(&new_remainder);
     }
   }
 }
Dim()
virtual int32 Dim () const inline virtual
Implements OnlineFeatureInterface.
Definition at line 53 of file online-feature.h.
References OnlineGenericBaseFeature< C >::computer_.
Referenced by kaldi::TestOnlineTransform().
 { return computer_.Dim(); }
FrameShiftInSeconds()
virtual BaseFloat FrameShiftInSeconds () const inline virtual
Implements OnlineFeatureInterface.
Definition at line 60 of file online-feature.h.
References OnlineGenericBaseFeature< C >::computer_.
{
     return computer_.GetFrameOptions().frame_shift_ms / 1000.0f;
   }
GetFrame()
void GetFrame (int32 frame, VectorBase< BaseFloat > * feat) virtual
Gets the feature vector for this frame.
Before calling this for a given frame, it is assumed that you called NumFramesReady() and it returned a number greater than "frame". Otherwise this call will likely crash with an assert failure. This function is not declared const, in case there is some kind of caching going on, but most of the time it shouldn't modify the class.
Implements OnlineFeatureInterface.
Definition at line 28 of file online-feature.cc.
References VectorBase< Real >::CopyFromVec().
Referenced by OnlineSpliceFrames::FrameShiftInSeconds(), OnlineDeltaFeature::FrameShiftInSeconds(), OnlineGenericBaseFeature< C >::NumFramesReady(), OnlineCmvn::NumFramesReady(), OnlineTransform::NumFramesReady(), OnlineCacheFeature::NumFramesReady(), and OnlineAppendFeature::NumFramesReady().
{
   // 'at' does size checking.
   feat->CopyFromVec(*(features_.at(frame)));
 };
InputFinished()
virtual void InputFinished () inline virtual
InputFinished() tells the class you won't be providing any more waveform.
This will help flush out the last few frames of delta or LDA features (it will typically affect the return value of IsLastFrame.
Implements OnlineBaseFeature.
Definition at line 86 of file online-feature.h.
References OnlineGenericBaseFeature< C >::ComputeFeatures(), and OnlineGenericBaseFeature< C >::input_finished_.
Referenced by kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), and kaldi::TestOnlineTransform().
{
     input_finished_ = true;
     ComputeFeatures();
   }
IsLastFrame()
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frame indices are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). This function may return false for some frame if we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. This function exists mainly to correctly handle end effects in feature extraction, and is not a mechanism to determine how many frames are in the decodable object (as it used to be, and for backward compatibility, still is, in the Decodable interface).
Implements OnlineFeatureInterface.
Definition at line 57 of file online-feature.h.
References OnlineGenericBaseFeature< C >::input_finished_, and OnlineGenericBaseFeature< C >::NumFramesReady().
{
     return input_finished_ && frame == NumFramesReady() - 1;
   }
NumFramesReady()
virtual int32 NumFramesReady () const inline virtual
returns the feature dimension.
Returns the total number of frames, since the start of the utterance, that are now available. In an online-decoding context, this will likely increase with time as more data becomes available.
Implements OnlineFeatureInterface.
Definition at line 64 of file online-feature.h.
References OnlineGenericBaseFeature< C >::AcceptWaveform(), OnlineGenericBaseFeature< C >::features_, OnlineGenericBaseFeature< C >::GetFrame(), and OnlineGenericBaseFeature< C >::OnlineGenericBaseFeature().
Referenced by OnlineSpliceFrames::FrameShiftInSeconds(), OnlineDeltaFeature::FrameShiftInSeconds(), and OnlineGenericBaseFeature< C >::IsLastFrame().
 { return features_.size(); }
Member Data Documentation
computer_
C computer_ private
Definition at line 104 of file online-feature.h.
Referenced by OnlineGenericBaseFeature< C >::AcceptWaveform(), OnlineGenericBaseFeature< C >::ComputeFeatures(), OnlineGenericBaseFeature< C >::Dim(), and OnlineGenericBaseFeature< C >::FrameShiftInSeconds().
features_
std::vector<Vector<BaseFloat>*> features_ private
Definition at line 110 of file online-feature.h.
Referenced by OnlineGenericBaseFeature< C >::ComputeFeatures(), OnlineGenericBaseFeature< C >::NumFramesReady(), and OnlineGenericBaseFeature< C >::~OnlineGenericBaseFeature().
input_finished_
bool input_finished_ private
Definition at line 113 of file online-feature.h.
Referenced by OnlineGenericBaseFeature< C >::AcceptWaveform(), OnlineGenericBaseFeature< C >::ComputeFeatures(), OnlineGenericBaseFeature< C >::InputFinished(), and OnlineGenericBaseFeature< C >::IsLastFrame().
sampling_frequency_
BaseFloat sampling_frequency_ private
Definition at line 117 of file online-feature.h.
waveform_offset_
int64 waveform_offset_ private
Definition at line 121 of file online-feature.h.
Referenced by OnlineGenericBaseFeature< C >::ComputeFeatures().
waveform_remainder_
Vector<BaseFloat> waveform_remainder_ private
Definition at line 126 of file online-feature.h.
Referenced by OnlineGenericBaseFeature< C >::AcceptWaveform(), and OnlineGenericBaseFeature< C >::ComputeFeatures().
window_function_
FeatureWindowFunction window_function_ private
Definition at line 106 of file online-feature.h.
Referenced by OnlineGenericBaseFeature< C >::ComputeFeatures().
The documentation for this class was generated from the following files:
feat/online-feature.h
feat/online-feature.cc