Kaldi: StatisticsExtractionComponentPrecomputedIndexes Class Reference
StatisticsExtractionComponentPrecomputedIndexes Class Reference
#include <nnet-general-component.h>
Public Member Functions
ComponentPrecomputedIndexes * Copy () const
virtual void Write (std::ostream &os, bool binary) const
virtual void Read (std::istream &is, bool binary)
virtual std::string Type () const
Public Member Functions inherited from ComponentPrecomputedIndexes
virtual ~ComponentPrecomputedIndexes ()
Public Attributes
CuArray< Int32Pair > forward_indexes
CuVector< BaseFloat > counts
CuArray< int32 > backward_indexes
Private Member Functions
virtual ~StatisticsExtractionComponentPrecomputedIndexes ()
Additional Inherited Members
Static Public Member Functions inherited from ComponentPrecomputedIndexes
static ComponentPrecomputedIndexes * ReadNew (std::istream &is, bool binary)
static ComponentPrecomputedIndexes * NewComponentPrecomputedIndexesOfType (const std::string &cpi_type)
Detailed Description
Definition at line 276 of file nnet-general-component.h.
Constructor & Destructor Documentation
~StatisticsExtractionComponentPrecomputedIndexes()
virtual ~StatisticsExtractionComponentPrecomputedIndexes () inline private virtual
Definition at line 304 of file nnet-general-component.h.
 { }
Member Function Documentation
Copy()
ComponentPrecomputedIndexes* Copy () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 294 of file nnet-general-component.h.
References DistributeComponent::Read(), and DistributeComponent::Write().
{
     return new StatisticsExtractionComponentPrecomputedIndexes(*this);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Implements ComponentPrecomputedIndexes.
Definition at line 271 of file nnet-general-component.cc.
References kaldi::nnet3::CopyPairVector(), kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), kaldi::ReadIntegerPairVector(), and kaldi::ReadIntegerVector().
{
   ExpectOneOrTwoTokens(is, binary,
                        "<StatisticsExtractionComponentPrecomputedIndexes>",
                        "<ForwardIndexes>");
   std::vector<std::pair<int32, int32> > pairs_cpu;
   ReadIntegerPairVector(is, binary, &pairs_cpu);
   CopyPairVector(pairs_cpu, &forward_indexes);
   ExpectToken(is, binary, "<Counts>");
   counts.Read(is, binary);
   ExpectToken(is, binary, "<BackwardIndexes>");
   std::vector<int32> backward_indexes_cpu;
   ReadIntegerVector(is, binary, &backward_indexes_cpu);
   backward_indexes.CopyFromVec(backward_indexes_cpu);
   ExpectToken(is, binary, "</StatisticsExtractionComponentPrecomputedIndexes>");
 }
Type()
virtual std::string Type () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 302 of file nnet-general-component.h.
 { return "StatisticsExtractionComponentPrecomputedIndexes"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Implements ComponentPrecomputedIndexes.
Definition at line 256 of file nnet-general-component.cc.
References kaldi::nnet3::CopyPairVector(), kaldi::WriteIntegerPairVector(), kaldi::WriteIntegerVector(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<StatisticsExtractionComponentPrecomputedIndexes>");
   WriteToken(os, binary, "<ForwardIndexes>");
   std::vector<std::pair<int32, int32> > pairs_cpu;
   CopyPairVector(forward_indexes, &pairs_cpu);
   WriteIntegerPairVector(os, binary, pairs_cpu);
   WriteToken(os, binary, "<Counts>");
   counts.Write(os, binary);
   WriteToken(os, binary, "<BackwardIndexes>");
   std::vector<int32> backward_indexes_cpu;
   backward_indexes.CopyToVec(&backward_indexes_cpu);
   WriteIntegerVector(os, binary, backward_indexes_cpu);
   WriteToken(os, binary, "</StatisticsExtractionComponentPrecomputedIndexes>");
 }
Member Data Documentation
backward_indexes
CuArray<int32> backward_indexes
Definition at line 292 of file nnet-general-component.h.
Referenced by StatisticsExtractionComponent::Backprop(), and StatisticsExtractionComponent::PrecomputeIndexes().
counts
CuVector<BaseFloat> counts
Definition at line 287 of file nnet-general-component.h.
Referenced by StatisticsExtractionComponent::PrecomputeIndexes(), and StatisticsExtractionComponent::Propagate().
forward_indexes
CuArray<Int32Pair> forward_indexes
Definition at line 282 of file nnet-general-component.h.
Referenced by StatisticsExtractionComponent::PrecomputeIndexes(), and StatisticsExtractionComponent::Propagate().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc