Kaldi: NnetStats Class Reference
NnetStats Class Reference
#include <nnet-stats.h>
Classes
struct StatsElement
Public Member Functions
NnetStats (int32 affine_component_index, BaseFloat bucket_width)
void AddStats (BaseFloat avg_deriv, BaseFloat avg_value)
void AddStatsFromNnet (const Nnet &nnet)
void PrintStats (std::ostream &os)
Private Member Functions
int32 BucketFor (BaseFloat avg_deriv)
Private Attributes
int32 affine_component_index_
BaseFloat bucket_width_
std::vector< StatsElement > buckets_
StatsElement global_
Detailed Description
Definition at line 44 of file nnet-stats.h.
Constructor & Destructor Documentation
NnetStats()
NnetStats (int32 affine_component_index, BaseFloat bucket_width) inline
Definition at line 46 of file nnet-stats.h.
Referenced by kaldi::nnet2::GetNnetStats().
                                                                  :
       affine_component_index_(affine_component_index),
       bucket_width_(bucket_width), global_(0, -1) { }
Member Function Documentation
AddStats()
void AddStats (BaseFloat avg_deriv, BaseFloat avg_value)
Definition at line 58 of file nnet-stats.cc.
References NnetStats::StatsElement::AddStats(), NnetStats::BucketFor(), NnetStats::buckets_, and NnetStats::global_.
{
   global_.AddStats(avg_deriv, avg_value);
   buckets_[BucketFor(avg_deriv)].AddStats(avg_deriv, avg_value);
 }
AddStatsFromNnet()
void AddStatsFromNnet (const Nnet & nnet)
Definition at line 63 of file nnet-stats.cc.
References NnetStats::StatsElement::AddStats(), NnetStats::affine_component_index_, NnetStats::StatsElement::count, NonlinearComponent::Count(), NnetStats::StatsElement::deriv_sum, NonlinearComponent::DerivSum(), CuVectorBase< Real >::Dim(), Nnet::GetComponent(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, KALDI_WARN, and NonlinearComponent::ValueSum().
{
   const AffineComponent *ac = dynamic_cast<const AffineComponent*>(
       &(nnet.GetComponent(affine_component_index_)));
   KALDI_ASSERT(ac != NULL); // would be an error in calling code.
   const NonlinearComponent *nc = dynamic_cast<const NonlinearComponent*>(
       &(nnet.GetComponent(affine_component_index_ + 1)));
   KALDI_ASSERT(nc != NULL); // would be an error in calling code.
   double count = nc->Count();
   if (count == 0) {
     KALDI_WARN << "No stats stored with nonlinear component";
     return;
   }
   const CuVector<double> &value_sum = nc->ValueSum();
   const CuVector<double> &deriv_sum = nc->DerivSum();
   if (value_sum.Dim() != deriv_sum.Dim())
     KALDI_ERR << "Error computing nnet stats: probably you are "
               << "trying to compute stats for a sigmoid layer.";
   for (int32 i = 0; i < value_sum.Dim(); i++) {
     BaseFloat avg_value = value_sum(i) / count,
         avg_deriv = deriv_sum(i) / count;
     AddStats(avg_deriv, avg_value);
   }
 }
BucketFor()
int32 BucketFor (BaseFloat avg_deriv) private
Definition at line 47 of file nnet-stats.cc.
References NnetStats::bucket_width_, NnetStats::buckets_, KALDI_ASSERT, and NnetStats::StatsElement::StatsElement().
Referenced by NnetStats::AddStats().
{
   KALDI_ASSERT(avg_deriv >= 0.0);
   KALDI_ASSERT(bucket_width_ > 0.0);
   // cast ratio to int.  Since we do +0.5, this rounds down.
   int32 index = static_cast<int32>(avg_deriv / bucket_width_ + 0.5);
   while (index >= static_cast<int32>(buckets_.size()))
     buckets_.push_back(StatsElement(buckets_.size() * bucket_width_,
                                     (buckets_.size() + 1) * bucket_width_));
   return index;
 }
PrintStats()
void PrintStats (std::ostream & os)
Definition at line 88 of file nnet-stats.cc.
References NnetStats::buckets_, NnetStats::global_, rnnlm::i, and NnetStats::StatsElement::PrintStats().
{
   os << "Stats for buckets:" << std::endl;
   for (size_t i = 0; i < buckets_.size(); i++) {
     buckets_[i].PrintStats(os);
     os << std::endl;
   }
   os << "Global stats: ";
   global_.PrintStats(os);
   os << std::endl;
 }
Member Data Documentation
affine_component_index_
int32 affine_component_index_ private
Definition at line 80 of file nnet-stats.h.
Referenced by NnetStats::AddStatsFromNnet().
bucket_width_
BaseFloat bucket_width_ private
Definition at line 82 of file nnet-stats.h.
Referenced by NnetStats::BucketFor().
buckets_
std::vector<StatsElement> buckets_ private
Definition at line 84 of file nnet-stats.h.
Referenced by NnetStats::AddStats(), NnetStats::BucketFor(), and NnetStats::PrintStats().
global_
StatsElement global_ private
Definition at line 85 of file nnet-stats.h.
Referenced by NnetStats::AddStats(), and NnetStats::PrintStats().
The documentation for this class was generated from the following files:
nnet2/nnet-stats.h
nnet2/nnet-stats.cc