Kaldi: RegtreeMllrDiagGmm Class Reference
RegtreeMllrDiagGmm Class Reference
An MLLR mean transformation is an affine transformation of Gaussian means.
#include <regtree-mllr-diag-gmm.h>
Public Member Functions
RegtreeMllrDiagGmm ()
void Init (int32 num_xforms, int32 dim)
Allocates memory for transform matrix & bias vector.
void SetUnit ()
Initialize transform matrix to identity and bias vector to zero.
void TransformModel (const RegressionTree &regtree, AmDiagGmm *am)
Apply the transform(s) to all the Gaussian means in the model.
void GetTransformedMeans (const RegressionTree &regtree, const AmDiagGmm &am, int32 pdf_index, MatrixBase< BaseFloat > *out) const
Get all the transformed means for a given pdf.
void Write (std::ostream &out_stream, bool binary) const
void Read (std::istream &in_stream, bool binary)
void SetParameters (const MatrixBase< BaseFloat > &mat, int32 regclass)
Mutators.
void set_bclass2xforms (const std::vector< int32 > &in)
const std::vector< Matrix< BaseFloat > > xform_matrices () const
Accessors.
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (RegtreeMllrDiagGmm)
Private Attributes
std::vector< Matrix< BaseFloat > > xform_matrices_
Transform matrices: size() = num_xforms_.
int32 num_xforms_
Number of transforms == xform_matrices_.size()
std::vector< int32 > bclass2xforms_
For each baseclass index of which transform to use; -1 => no xform.
int32 dim_
Dimension of feature vectors.
Detailed Description
An MLLR mean transformation is an affine transformation of Gaussian means.
Definition at line 53 of file regtree-mllr-diag-gmm.h.
Constructor & Destructor Documentation
RegtreeMllrDiagGmm()
RegtreeMllrDiagGmm () inline
Definition at line 55 of file regtree-mllr-diag-gmm.h.
 {}
Member Function Documentation
GetTransformedMeans()
void GetTransformedMeans (const RegressionTree & regtree, const AmDiagGmm & am, int32 pdf_index, MatrixBase< BaseFloat > * out) const
Get all the transformed means for a given pdf.
Definition at line 84 of file regtree-mllr-diag-gmm.cc.
References VectorBase< Real >::AddMatVec(), RegtreeMllrDiagGmm::bclass2xforms_, RegtreeMllrDiagGmm::dim_, RegressionTree::Gauss2BaseclassId(), AmDiagGmm::GetGaussianMean(), AmDiagGmm::GetPdf(), KALDI_ASSERT, kaldi::kNoTrans, RegtreeMllrDiagGmm::num_xforms_, RegressionTree::NumBaseclasses(), MatrixBase< Real >::NumCols(), DiagGmm::NumGauss(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::Row(), and RegtreeMllrDiagGmm::xform_matrices_.
Referenced by TestXformMean().
{
   KALDI_ASSERT(static_cast<int32>(bclass2xforms_.size()) ==
                regtree.NumBaseclasses());
   int32 num_gauss = am.GetPdf(pdf_index).NumGauss();
   KALDI_ASSERT(out->NumRows() == num_gauss && out->NumCols() == dim_);
   Vector<BaseFloat> extended_mean(dim_+1);
   extended_mean(dim_) = 1.0;
   for (int32 gauss_index = 0; gauss_index < num_gauss; gauss_index++) {
     int32 bclass_index = regtree.Gauss2BaseclassId(pdf_index, gauss_index);
     int32 xform_index = bclass2xforms_[bclass_index];
     if (xform_index > -1) {  // use a transform
       KALDI_ASSERT(xform_index < num_xforms_);
       SubVector<BaseFloat> tmp_mean(extended_mean.Range(0, dim_));
       am.GetGaussianMean(pdf_index, gauss_index, &tmp_mean);
       SubVector<BaseFloat> out_row(out->Row(gauss_index));
       out_row.AddMatVec(1.0, xform_matrices_[xform_index], kNoTrans,
                         extended_mean, 0.0);
     } else {  // Copy untransformed mean
       SubVector<BaseFloat> out_row(out->Row(gauss_index));
       am.GetGaussianMean(pdf_index, gauss_index, &out_row);
     }
   }
 }
Init()
void Init (int32 num_xforms, int32 dim)
Allocates memory for transform matrix & bias vector.
Definition at line 29 of file regtree-mllr-diag-gmm.cc.
References RegtreeMllrDiagGmm::bclass2xforms_, RegtreeMllrDiagGmm::dim_, KALDI_ASSERT, RegtreeMllrDiagGmm::num_xforms_, and RegtreeMllrDiagGmm::xform_matrices_.
Referenced by RegtreeMllrDiagGmmAccs::Update().
{
   if (num_xforms == 0) {  // empty transform
     xform_matrices_.clear();
     dim_ = 0;  // non-zero dimension is meaningless with empty transform
     num_xforms_ = 0;
     bclass2xforms_.clear();
   } else {
     KALDI_ASSERT(dim != 0);  // if not empty, dim = 0 is meaningless
     dim_ = dim;
     num_xforms_ = num_xforms;
     xform_matrices_.resize(num_xforms);
     vector< Matrix<BaseFloat> >::iterator xform_itr = xform_matrices_.begin(),
                                       xform_itr_end = xform_matrices_.end();
     for (; xform_itr != xform_itr_end; ++xform_itr) {
       xform_itr->Resize(dim, dim+1);
       xform_itr->SetUnit();
     }
   }
 }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (RegtreeMllrDiagGmm) private
Read()
void Read (std::istream & in_stream, bool binary)
Definition at line 134 of file regtree-mllr-diag-gmm.cc.
References RegtreeMllrDiagGmm::bclass2xforms_, RegtreeMllrDiagGmm::dim_, kaldi::ExpectToken(), KALDI_ASSERT, RegtreeMllrDiagGmm::num_xforms_, kaldi::ReadBasicType(), kaldi::ReadIntegerVector(), and RegtreeMllrDiagGmm::xform_matrices_.
{
   ExpectToken(in, binary, "<MLLRXFORM>");
   ExpectToken(in, binary, "<NUMXFORMS>");
   ReadBasicType(in, binary, &num_xforms_);
   ExpectToken(in, binary, "<DIMENSION>");
   ReadBasicType(in, binary, &dim_);
   KALDI_ASSERT(num_xforms_ >= 0 && dim_ >= 0);  // can be 0 for empty xform
   xform_matrices_.resize(num_xforms_);
   vector< Matrix<BaseFloat> >::iterator xform_itr = xform_matrices_.begin(),
                                     xform_itr_end = xform_matrices_.end();
   for (; xform_itr != xform_itr_end; ++xform_itr) {
     ExpectToken(in, binary, "<XFORM>");
     xform_itr->Read(in, binary);
     KALDI_ASSERT(xform_itr->NumRows() == (xform_itr->NumCols() - 1)
                  && xform_itr->NumRows() == dim_);
   }
   ExpectToken(in, binary, "<BCLASS2XFORMS>");
   ReadIntegerVector(in, binary, &bclass2xforms_);
   ExpectToken(in, binary, "</MLLRXFORM>");
 }
set_bclass2xforms()
void set_bclass2xforms (const std::vector< int32 > & in) inline
Definition at line 75 of file regtree-mllr-diag-gmm.h.
Referenced by RegtreeMllrDiagGmmAccs::Update().
 { bclass2xforms_ = in; }
SetParameters()
void SetParameters (const MatrixBase< BaseFloat > & mat, int32 regclass) inline
Mutators.
Definition at line 94 of file regtree-mllr-diag-gmm.h.
References kaldi::kNoTrans.
Referenced by RegtreeMllrDiagGmmAccs::Update().
{
   xform_matrices_[regclass].CopyFromMat(mat, kNoTrans);
 }
SetUnit()
void SetUnit ()
Initialize transform matrix to identity and bias vector to zero.
Definition at line 49 of file regtree-mllr-diag-gmm.cc.
References RegtreeMllrDiagGmm::xform_matrices_.
{
   vector< Matrix<BaseFloat> >::iterator xform_itr = xform_matrices_.begin(),
                                     xform_itr_end = xform_matrices_.end();
   for (; xform_itr != xform_itr_end; ++xform_itr) {
     xform_itr->SetUnit();
   }
 }
TransformModel()
void TransformModel (const RegressionTree & regtree, AmDiagGmm * am)
Apply the transform(s) to all the Gaussian means in the model.
Definition at line 57 of file regtree-mllr-diag-gmm.cc.
References RegtreeMllrDiagGmm::bclass2xforms_, AmDiagGmm::ComputeGconsts(), RegtreeMllrDiagGmm::dim_, RegressionTree::GetBaseclass(), AmDiagGmm::GetGaussianMean(), KALDI_ASSERT, kaldi::kNoTrans, RegtreeMllrDiagGmm::num_xforms_, RegressionTree::NumBaseclasses(), AmDiagGmm::SetGaussianMean(), and RegtreeMllrDiagGmm::xform_matrices_.
Referenced by TestMllrAccsIO(), and TestXformMean().
{
   KALDI_ASSERT(static_cast<int32>(bclass2xforms_.size()) ==
                regtree.NumBaseclasses());
   Vector<BaseFloat> extended_mean(dim_+1), xformed_mean(dim_);
   for (int32 bclass_index = 0, num_bclasses = regtree.NumBaseclasses();
        bclass_index < num_bclasses; ++bclass_index) {
     int32 xform_index;
     if ((xform_index = bclass2xforms_[bclass_index]) > -1) {
       KALDI_ASSERT(xform_index < num_xforms_);
       const vector< pair<int32, int32> > &bclass =
           regtree.GetBaseclass(bclass_index);
       for (vector< pair<int32, int32> >::const_iterator itr = bclass.begin(),
           end = bclass.end(); itr != end; ++itr) {
         SubVector<BaseFloat> tmp_mean(extended_mean.Range(0, dim_));
         am->GetGaussianMean(itr->first, itr->second, &tmp_mean);
         extended_mean(dim_) = 1.0;
         xformed_mean.AddMatVec(1.0, xform_matrices_[xform_index], kNoTrans,
                                extended_mean, 0.0);
         am->SetGaussianMean(itr->first, itr->second, xformed_mean);
       }  // end iterating over Gaussians in baseclass
     }  // else keep the means untransformed
   }  // end iterating over all baseclasses
   am->ComputeGconsts();
 }
Write()
void Write (std::ostream & out_stream, bool binary) const
Definition at line 114 of file regtree-mllr-diag-gmm.cc.
References RegtreeMllrDiagGmm::bclass2xforms_, RegtreeMllrDiagGmm::dim_, RegtreeMllrDiagGmm::num_xforms_, kaldi::WriteBasicType(), kaldi::WriteIntegerVector(), kaldi::WriteToken(), and RegtreeMllrDiagGmm::xform_matrices_.
{
   WriteToken(out, binary, "<MLLRXFORM>");
   WriteToken(out, binary, "<NUMXFORMS>");
   WriteBasicType(out, binary, num_xforms_);
   WriteToken(out, binary, "<DIMENSION>");
   WriteBasicType(out, binary, dim_);
   vector< Matrix<BaseFloat> >::const_iterator xform_itr =
       xform_matrices_.begin(), xform_itr_end = xform_matrices_.end();
   for (; xform_itr != xform_itr_end; ++xform_itr) {
     WriteToken(out, binary, "<XFORM>");
     xform_itr->Write(out, binary);
   }
   WriteToken(out, binary, "<BCLASS2XFORMS>");
   WriteIntegerVector(out, binary, bclass2xforms_);
   WriteToken(out, binary, "</MLLRXFORM>");
 }
xform_matrices()
const std::vector< Matrix<BaseFloat> > xform_matrices () const inline
Accessors.
Definition at line 78 of file regtree-mllr-diag-gmm.h.
{
     return xform_matrices_;
   }
Member Data Documentation
bclass2xforms_
std::vector<int32> bclass2xforms_ private
For each baseclass index of which transform to use; -1 => no xform.
Definition at line 87 of file regtree-mllr-diag-gmm.h.
Referenced by RegtreeMllrDiagGmm::GetTransformedMeans(), RegtreeMllrDiagGmm::Init(), RegtreeMllrDiagGmm::Read(), RegtreeMllrDiagGmm::TransformModel(), and RegtreeMllrDiagGmm::Write().
dim_
int32 dim_ private
Dimension of feature vectors.
Definition at line 88 of file regtree-mllr-diag-gmm.h.
Referenced by RegtreeMllrDiagGmmAccs::AccumulateForGaussian(), RegtreeMllrDiagGmmAccs::AccumulateForGmm(), RegtreeMllrDiagGmm::GetTransformedMeans(), RegtreeMllrDiagGmm::Init(), RegtreeMllrDiagGmmAccs::Init(), RegtreeMllrDiagGmm::Read(), RegtreeMllrDiagGmmAccs::Read(), RegtreeMllrDiagGmm::TransformModel(), RegtreeMllrDiagGmmAccs::Update(), RegtreeMllrDiagGmm::Write(), and RegtreeMllrDiagGmmAccs::Write().
num_xforms_
int32 num_xforms_ private
Number of transforms == xform_matrices_.size()
Definition at line 85 of file regtree-mllr-diag-gmm.h.
Referenced by RegtreeMllrDiagGmm::GetTransformedMeans(), RegtreeMllrDiagGmm::Init(), RegtreeMllrDiagGmm::Read(), RegtreeMllrDiagGmm::TransformModel(), and RegtreeMllrDiagGmm::Write().
xform_matrices_
std::vector< Matrix<BaseFloat> > xform_matrices_ private
Transform matrices: size() = num_xforms_.
Definition at line 84 of file regtree-mllr-diag-gmm.h.
Referenced by RegtreeMllrDiagGmm::GetTransformedMeans(), RegtreeMllrDiagGmm::Init(), RegtreeMllrDiagGmm::Read(), RegtreeMllrDiagGmm::SetUnit(), RegtreeMllrDiagGmm::TransformModel(), and RegtreeMllrDiagGmm::Write().
The documentation for this class was generated from the following files:
transform/regtree-mllr-diag-gmm.h
transform/regtree-mllr-diag-gmm.cc