Kaldi: DistributeComponentPrecomputedIndexes Class Reference
DistributeComponentPrecomputedIndexes Class Reference
#include <nnet-general-component.h>
Public Member Functions
virtual ~DistributeComponentPrecomputedIndexes ()
virtual ComponentPrecomputedIndexes * Copy () const
virtual void Write (std::ostream &ostream, bool binary) const
virtual void Read (std::istream &istream, bool binary)
virtual std::string Type () const
Public Member Functions inherited from ComponentPrecomputedIndexes
virtual ~ComponentPrecomputedIndexes ()
Public Attributes
std::vector< std::pair< int32, int32 > > pairs
Additional Inherited Members
Static Public Member Functions inherited from ComponentPrecomputedIndexes
static ComponentPrecomputedIndexes * ReadNew (std::istream &is, bool binary)
static ComponentPrecomputedIndexes * NewComponentPrecomputedIndexesOfType (const std::string &cpi_type)
Detailed Description
Definition at line 133 of file nnet-general-component.h.
Constructor & Destructor Documentation
~DistributeComponentPrecomputedIndexes()
virtual ~DistributeComponentPrecomputedIndexes () inline virtual
Definition at line 144 of file nnet-general-component.h.
 { }
Member Function Documentation
Copy()
virtual ComponentPrecomputedIndexes* Copy () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 146 of file nnet-general-component.h.
References DistributeComponent::Read(), and DistributeComponent::Write().
{
     return new DistributeComponentPrecomputedIndexes(*this);
   }
Read()
void Read (std::istream & istream, bool binary) virtual
Implements ComponentPrecomputedIndexes.
Definition at line 95 of file nnet-general-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), and kaldi::ReadIntegerPairVector().
{
   ExpectOneOrTwoTokens(istream, binary, "<DistributeComponentPrecomputedIndexes>", "<Pairs>");
   ReadIntegerPairVector(istream, binary, &pairs);
   ExpectToken(istream, binary, "</DistributeComponentPrecomputedIndexes>");
 }
Type()
virtual std::string Type () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 154 of file nnet-general-component.h.
 { return "DistributeComponentPrecomputedIndexes"; }
Write()
void Write (std::ostream & ostream, bool binary) const virtual
Implements ComponentPrecomputedIndexes.
Definition at line 88 of file nnet-general-component.cc.
References kaldi::WriteIntegerPairVector(), and kaldi::WriteToken().
{
   WriteToken(ostream, binary, "<DistributeComponentPrecomputedIndexes>");
   WriteToken(ostream, binary, "<Pairs>");
   WriteIntegerPairVector(ostream, binary, pairs);
   WriteToken(ostream, binary, "</DistributeComponentPrecomputedIndexes>");
 }
Member Data Documentation
pairs
std::vector<std::pair<int32, int32> > pairs
Definition at line 140 of file nnet-general-component.h.
Referenced by DistributeComponent::ComputeInputPointers(), and DistributeComponent::PrecomputeIndexes().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc