Kaldi: InverseContextFst Class Reference
InverseContextFst Class Reference
#include <context-fst.h>
Public Types
typedef StdArc Arc
typedef StdArc::StateId StateId
typedef StdArc::Weight Weight
typedef StdArc::Label Label
Public Types inherited from DeterministicOnDemandFst< StdArc >
typedef StdArc ::StateId StateId
typedef StdArc ::Weight Weight
typedef StdArc ::Label Label
Public Member Functions
InverseContextFst (Label subsequential_symbol, const vector< int32 > &phones, const vector< int32 > &disambig_syms, int32 context_width, int32 central_position)
Constructor.
virtual StateId Start ()
virtual Weight Final (StateId s)
virtual bool GetArc (StateId s, Label ilabel, Arc *arc)
Note: ilabel must not be epsilon.
~InverseContextFst ()
const vector< vector< int32 > > & IlabelInfo () const
void SwapIlabelInfo (vector< vector< int32 > > *vec)
Public Member Functions inherited from DeterministicOnDemandFst< StdArc >
virtual Weight Final (StateId s)=0
virtual bool GetArc (StateId s, Label ilabel, StdArc *oarc)=0
Note: ilabel must not be epsilon.
virtual ~DeterministicOnDemandFst ()
Private Types
typedef unordered_map< vector< int32 >, StateId, kaldi::VectorHasher< int32 > > VectorToStateMap
typedef unordered_map< vector< int32 >, Label, kaldi::VectorHasher< int32 > > VectorToLabelMap
Private Member Functions
StateId FindState (const vector< int32 > &seq)
Returns the state-id corresponding to this vector of phones; creates the state it if necessary.
Label FindLabel (const vector< int32 > &label_info)
Finds the label index corresponding to this context-window of phones (likely of width context_width_).
bool IsDisambigSymbol (Label lab)
bool IsPhoneSymbol (Label lab)
void CreateDisambigArc (StateId s, Label ilabel, Arc *arc)
Create disambiguation-symbol self-loop arc; where 'ilabel' must correspond to a disambiguation symbol.
void CreatePhoneOrEpsArc (StateId src, StateId dst, Label ilabel, const vector< int32 > &phone_seq, Arc *arc)
Creates an arc, this function is to be called only when 'ilabel' corresponds to a phone.
void ShiftSequenceLeft (Label label, std::vector< int32 > *phone_seq)
If phone_seq is nonempty then this function it left by one and appends 'label' to it, otherwise it does nothing.
void GetFullPhoneSequence (const std::vector< int32 > &seq, Label label, std::vector< int32 > *full_phone_sequence)
This utility function does something equivalent to the following 3 steps: *full_phone_sequence = seq; full_phone_sequence->append(label) Replace any values equal to 'subsequential_symbol_' in full_phone_sequence with zero (this is to avoid having to keep track of the value of 'subsequential_symbol_' outside of this program).
Private Attributes
int32 context_width_
int32 central_position_
kaldi::ConstIntegerSet< Label > phone_syms_
kaldi::ConstIntegerSet< Label > disambig_syms_
Label subsequential_symbol_
int32 pseudo_eps_symbol_
VectorToStateMap state_map_
vector< vector< int32 > > state_seqs_
VectorToLabelMap ilabel_map_
vector< vector< int32 > > ilabel_info_
Detailed Description
Definition at line 152 of file context-fst.h.
Member Typedef Documentation
Arc
typedef StdArc Arc
Definition at line 154 of file context-fst.h.
Label
typedef StdArc::Label Label
Definition at line 157 of file context-fst.h.
StateId
typedef StdArc::StateId StateId
Definition at line 155 of file context-fst.h.
VectorToLabelMap
typedef unordered_map<vector<int32>, Label, kaldi::VectorHasher<int32> > VectorToLabelMap private
Definition at line 256 of file context-fst.h.
VectorToStateMap
typedef unordered_map<vector<int32>, StateId, kaldi::VectorHasher<int32> > VectorToStateMap private
Definition at line 250 of file context-fst.h.
Weight
typedef StdArc::Weight Weight
Definition at line 156 of file context-fst.h.
Constructor & Destructor Documentation
InverseContextFst()
InverseContextFst (Label subsequential_symbol, const vector< int32 > & phones, const vector< int32 > & disambig_syms, int32 context_width, int32 central_position)
Constructor.
Parameters
[in] subsequential_symbol The integer id of the 'subsequential symbol' (usually represented as '$') that terminates sequences on the output of C.fst (input of InverseContextFst). Search for "quential" in https://cs.nyu.edu/~mohri/pub/hbka.pdf. This may just be the first unused integer id. Must be nonzer.
[in] phones List of integer ids of phones, as you would see in phones.txt
[in] disambig_syms List of integer ids of disambiguation symbols, e.g. the ids of #0, #1, #2 in phones.txt
[in] context_width Size of context window, e.g. 3 for triphone.
[in] central_position Central position in context window (zero-based), e.g. 1 for triphone. See The ContextFst object for more details.
Definition at line 26 of file context-fst.cc.
References InverseContextFst::central_position_, InverseContextFst::context_width_, ConstIntegerSet< I >::count(), InverseContextFst::disambig_syms_, ConstIntegerSet< I >::empty(), InverseContextFst::FindLabel(), InverseContextFst::FindState(), rnnlm::i, KALDI_ASSERT, KALDI_WARN, InverseContextFst::phone_syms_, and InverseContextFst::pseudo_eps_symbol_.
                            :
     context_width_(context_width),
     central_position_(central_position),
     phone_syms_(phones),
     disambig_syms_(disambig_syms),
     subsequential_symbol_(subsequential_symbol) {
   {  // This block checks the inputs.
     KALDI_ASSERT(subsequential_symbol != 0
                  && disambig_syms_.count(subsequential_symbol) == 0
                  && phone_syms_.count(subsequential_symbol) == 0);
     if (phone_syms_.empty())
       KALDI_WARN << "Context FST created but there are no phone symbols: probably "
           "input FST was empty.";
     KALDI_ASSERT(phone_syms_.count(0) == 0 && disambig_syms_.count(0) == 0 &&
                  central_position_ >= 0 && central_position_ < context_width_);
     for (size_t i = 0; i < phones.size(); i++) {
       KALDI_ASSERT(disambig_syms_.count(phones[i]) == 0);
     }
   }
   // empty vector, will be the ilabel_info vector that corresponds to epsilon,
   // in case our FST needs to output epsilons.
   vector<int32> empty_vec;
   Label epsilon_label = FindLabel(empty_vec);
   // epsilon_vec is the phonetic context window we have at the very start of a
   // sequence, meaning "no real phones have been seen yet".
   vector<int32> epsilon_vec(context_width_ - 1, 0);
   StateId start_state = FindState(epsilon_vec);
   KALDI_ASSERT(epsilon_label == 0 && start_state == 0);
   if (context_width_ > central_position_ + 1 && !disambig_syms_.empty()) {
     // We add a symbol whose sequence representation is [ 0 ], and whose
     // symbol-id is 1.  This is treated as a disambiguation symbol, we call it
     // #-1 in printed form.  It is necessary to ensure that all determinizable
     // LG's will have determinizable CLG's.  The problem it fixes is quite
     // subtle-- it relates to reordering of disambiguation symbols (they appear
     // earlier in CLG than in LG, relative to phones), and the fact that if a
     // disambig symbol appears at the very start of a sequence in CLG, it's not
     // clear exatly where it appeared on the corresponding sequence at the input
     // of LG.
     vector<int32> pseudo_eps_vec;
     pseudo_eps_vec.push_back(0);
     pseudo_eps_symbol_= FindLabel(pseudo_eps_vec);
     KALDI_ASSERT(pseudo_eps_symbol_ == 1);
   } else {
     pseudo_eps_symbol_ = 0;  // use actual epsilon.
   }
 }
~InverseContextFst()
~InverseContextFst () inline
Definition at line 188 of file context-fst.h.
 { }
Member Function Documentation
CreateDisambigArc()
void CreateDisambigArc (StateId s, Label ilabel, Arc * arc) inline private
Create disambiguation-symbol self-loop arc; where 'ilabel' must correspond to a disambiguation symbol.
Called from CreateArc().
Definition at line 183 of file context-fst.cc.
References InverseContextFst::FindLabel().
Referenced by InverseContextFst::GetArc(), and InverseContextFst::IsPhoneSymbol().
{
   // Creates a self-loop arc corresponding to the disambiguation symbol.
   vector<int32> label_info;       // This will be a vector containing just [ -olabel ].
   label_info.push_back(-ilabel);  // olabel is a disambiguation symbol.  Use its negative
                                   // so we can more easily distinguish them from phones.
   Label olabel = FindLabel(label_info);
   arc->ilabel = ilabel;
   arc->olabel = olabel;
   arc->weight = Weight::One();
   arc->nextstate = s;  // self-loop.
 }
CreatePhoneOrEpsArc()
void CreatePhoneOrEpsArc (StateId src, StateId dst, Label ilabel, const vector< int32 > & phone_seq, Arc * arc) inline private
Creates an arc, this function is to be called only when 'ilabel' corresponds to a phone.
Called from CreateArc(). The olabel may end be epsilon, instead of a phone-in-context, if the system has right context and we are very near the beginning of the phone sequence.
Definition at line 195 of file context-fst.cc.
References InverseContextFst::central_position_, InverseContextFst::FindLabel(), KALDI_PARANOID_ASSERT, InverseContextFst::pseudo_eps_symbol_, and InverseContextFst::subsequential_symbol_.
Referenced by InverseContextFst::GetArc(), and InverseContextFst::IsPhoneSymbol().
{
   KALDI_PARANOID_ASSERT(phone_seq[central_position_] != subsequential_symbol_);
   arc->ilabel = ilabel;
   arc->weight = Weight::One();
   arc->nextstate = dest;
   if (phone_seq[central_position_] == 0) {
     // This can happen at the beginning of the graph.  In this case we don't
     // output a real phone, we createdt an epsilon arc (but sometimes we need to
     // use a special disambiguation symbol instead of epsilon).
     arc->olabel = pseudo_eps_symbol_;
   } else {
     // We have a phone in the central position.
     arc->olabel = FindLabel(phone_seq);
   }
 }
Final()
InverseContextFst::Weight Final (StateId s) virtual
Definition at line 108 of file context-fst.cc.
References InverseContextFst::central_position_, InverseContextFst::context_width_, KALDI_ASSERT, InverseContextFst::state_seqs_, and InverseContextFst::subsequential_symbol_.
Referenced by InverseContextFst::Start().
{
   KALDI_ASSERT(static_cast<size_t>(s) < state_seqs_.size());
   const vector<int32> &phone_context = state_seqs_[s];
   KALDI_ASSERT(phone_context.size() == context_width_ - 1);
   bool has_final_prob;
   if (central_position_ < context_width_ - 1) {
     has_final_prob = (phone_context[central_position_] == subsequential_symbol_);
     // if phone_context[central_position_] != subsequential_symbol_ then we have
     // pending phones-in-context that we still need to output, so we need to
     // consume more subsequential symbols before we can terminate.
   } else {
     has_final_prob = true;
   }
   return has_final_prob ? Weight::One() : Weight::Zero();
 }
FindLabel()
StdArc::Label FindLabel (const vector< int32 > & label_info) private
Finds the label index corresponding to this context-window of phones (likely of width context_width_).
Inserts it into the ilabel_info_/ilabel_map_ tables if necessary.
Definition at line 230 of file context-fst.cc.
References InverseContextFst::ilabel_info_, and InverseContextFst::ilabel_map_.
Referenced by InverseContextFst::CreateDisambigArc(), InverseContextFst::CreatePhoneOrEpsArc(), InverseContextFst::InverseContextFst(), and InverseContextFst::SwapIlabelInfo().
{
   // Finds the ilabel corresponding to this vector (creates a new ilabel if
   // necessary).
   VectorToLabelMap::const_iterator iter = ilabel_map_.find(label_vec);
   if (iter == ilabel_map_.end()) {  // Not already in map.
     Label this_label = ilabel_info_.size();
     ilabel_info_.push_back(label_vec);
     ilabel_map_[label_vec] = this_label;
     return this_label;
   } else {
     return iter->second;
   }
 }
FindState()
StdArc::StateId FindState (const vector< int32 > & seq) private
Returns the state-id corresponding to this vector of phones; creates the state it if necessary.
Requires seq.size() == context_width_ - 1.
Definition at line 215 of file context-fst.cc.
References InverseContextFst::context_width_, KALDI_ASSERT, InverseContextFst::state_map_, and InverseContextFst::state_seqs_.
Referenced by InverseContextFst::GetArc(), InverseContextFst::InverseContextFst(), and InverseContextFst::SwapIlabelInfo().
{
   // Finds state-id corresponding to this vector of phones.  Inserts it if
   // necessary.
   KALDI_ASSERT(static_cast<int32>(seq.size()) == context_width_ - 1);
   VectorToStateMap::const_iterator iter = state_map_.find(seq);
   if (iter == state_map_.end()) {  // Not already in map.
     StateId this_state_id = (StateId)state_seqs_.size();
     state_seqs_.push_back(seq);
     state_map_[seq] = this_state_id;
     return this_state_id;
   } else {
     return iter->second;
   }
 }
GetArc()
bool GetArc (StateId s, Label ilabel, Arc * arc) virtual
Note: ilabel must not be epsilon.
Definition at line 128 of file context-fst.cc.
References InverseContextFst::central_position_, InverseContextFst::context_width_, InverseContextFst::CreateDisambigArc(), InverseContextFst::CreatePhoneOrEpsArc(), InverseContextFst::FindState(), InverseContextFst::GetFullPhoneSequence(), InverseContextFst::IsDisambigSymbol(), InverseContextFst::IsPhoneSymbol(), KALDI_ASSERT, KALDI_ERR, InverseContextFst::ShiftSequenceLeft(), InverseContextFst::state_seqs_, and InverseContextFst::subsequential_symbol_.
Referenced by InverseContextFst::Start().
{
   KALDI_ASSERT(ilabel != 0 && static_cast<size_t>(s) < state_seqs_.size() &&
                state_seqs_[s].size() == context_width_ - 1);
   if (IsDisambigSymbol(ilabel)) {
     // A disambiguation-symbol self-loop arc.
     CreateDisambigArc(s, ilabel, arc);
     return true;
   } else if (IsPhoneSymbol(ilabel)) {
     const vector<int32> &seq = state_seqs_[s];
     if (!seq.empty() && seq.back() == subsequential_symbol_) {
       return false;  // A real phone is not allowed to follow the subsequential
                      // symbol.
     }
     // next_seq will be 'seq' shifted left by 1, with 'ilabel' appended.
     vector<int32> next_seq(seq);
     ShiftSequenceLeft(ilabel, &next_seq);
     // full-seq will be the full context window of size context_width_.
     vector<int32> full_seq;
     GetFullPhoneSequence(seq, ilabel, &full_seq);
     StateId next_s = FindState(next_seq);
     CreatePhoneOrEpsArc(s, next_s, ilabel, full_seq, arc);
     return true;
   } else if (ilabel == subsequential_symbol_) {
     const vector<int32> &seq = state_seqs_[s];
     if (central_position_ + 1 == context_width_ ||
         seq[central_position_] == subsequential_symbol_) {
       // We already had "enough" subsequential symbols in a row and don't want to
       // accept any more, or we'd be making the subsequential symbol the central phone.
       return false;
     }
     // full-seq will be the full context window of size context_width_.
     vector<int32> full_seq;
     GetFullPhoneSequence(seq, ilabel, &full_seq);
     vector<int32> next_seq(seq);
     ShiftSequenceLeft(ilabel, &next_seq);
     StateId next_s = FindState(next_seq);
     CreatePhoneOrEpsArc(s, next_s, ilabel, full_seq, arc);
     return true;
   } else {
     KALDI_ERR << "ContextFst: CreateArc, invalid ilabel supplied [confusion "
               << "about phone list or disambig symbols?]: " << ilabel;
   }
   return false;  // won't get here.  suppress compiler error.
 }
GetFullPhoneSequence()
void GetFullPhoneSequence (const std::vector< int32 > & seq, Label label, std::vector< int32 > * full_phone_sequence) inline private
This utility function does something equivalent to the following 3 steps: *full_phone_sequence = seq; full_phone_sequence->append(label) Replace any values equal to 'subsequential_symbol_' in full_phone_sequence with zero (this is to avoid having to keep track of the value of 'subsequential_symbol_' outside of this program).
This function assumes that seq.size() == context_width_ - 1, and also that 'subsequential_symbol_' does not appear in positions 0 through central_position_ of 'seq'.
Definition at line 92 of file context-fst.cc.
References InverseContextFst::central_position_, InverseContextFst::context_width_, rnnlm::i, and InverseContextFst::subsequential_symbol_.
Referenced by InverseContextFst::GetArc(), and InverseContextFst::IsPhoneSymbol().
{
   int32 context_width = context_width_;
   full_phone_sequence->reserve(context_width);
   full_phone_sequence->insert(full_phone_sequence->end(),
                               seq.begin(), seq.end());
   full_phone_sequence->push_back(label);
   for (int32 i = central_position_ + 1; i < context_width; i++) {
     if ((*full_phone_sequence)[i] == subsequential_symbol_) {
       (*full_phone_sequence)[i] = 0;
     }
   }
 }
IlabelInfo()
const vector<vector<int32> >& IlabelInfo () const inline
Definition at line 194 of file context-fst.h.
References InverseContextFst::ilabel_info_.
Referenced by fst::TestContextFst().
{
     return ilabel_info_;
   }
IsDisambigSymbol()
bool IsDisambigSymbol (Label lab) inline private
Definition at line 213 of file context-fst.h.
References ConstIntegerSet< I >::count(), and InverseContextFst::disambig_syms_.
Referenced by InverseContextFst::GetArc().
 { return (disambig_syms_.count(lab) != 0); }
IsPhoneSymbol()
bool IsPhoneSymbol (Label lab) inline private
Definition at line 215 of file context-fst.h.
References ConstIntegerSet< I >::count(), InverseContextFst::CreateDisambigArc(), InverseContextFst::CreatePhoneOrEpsArc(), InverseContextFst::GetFullPhoneSequence(), InverseContextFst::phone_syms_, and InverseContextFst::ShiftSequenceLeft().
Referenced by InverseContextFst::GetArc().
 { return (phone_syms_.count(lab) != 0); }
ShiftSequenceLeft()
void ShiftSequenceLeft (Label label, std::vector< int32 > * phone_seq) inline private
If phone_seq is nonempty then this function it left by one and appends 'label' to it, otherwise it does nothing.
We expect (but do not check) that phone_seq->size() == context_width_ - 1.
Definition at line 84 of file context-fst.cc.
Referenced by InverseContextFst::GetArc(), and InverseContextFst::IsPhoneSymbol().
{
   if (!phone_seq->empty()) {
     phone_seq->erase(phone_seq->begin());
     phone_seq->push_back(label);
   }
 }
Start()
virtual StateId Start () inline virtual
Implements DeterministicOnDemandFst< StdArc >.
Definition at line 181 of file context-fst.h.
References InverseContextFst::Final(), and InverseContextFst::GetArc().
 { return 0; }
SwapIlabelInfo()
void SwapIlabelInfo (vector< vector< int32 > > * vec) inline
Definition at line 200 of file context-fst.h.
References InverseContextFst::FindLabel(), InverseContextFst::FindState(), and InverseContextFst::ilabel_info_.
Referenced by fst::ComposeContext().
 { ilabel_info_.swap(*vec); }
Member Data Documentation
central_position_
int32 central_position_ private
Definition at line 271 of file context-fst.h.
Referenced by InverseContextFst::CreatePhoneOrEpsArc(), InverseContextFst::Final(), InverseContextFst::GetArc(), InverseContextFst::GetFullPhoneSequence(), and InverseContextFst::InverseContextFst().
context_width_
int32 context_width_ private
Definition at line 262 of file context-fst.h.
Referenced by InverseContextFst::Final(), InverseContextFst::FindState(), InverseContextFst::GetArc(), InverseContextFst::GetFullPhoneSequence(), and InverseContextFst::InverseContextFst().
disambig_syms_
kaldi::ConstIntegerSet<Label> disambig_syms_ private
Definition at line 285 of file context-fst.h.
Referenced by InverseContextFst::InverseContextFst(), and InverseContextFst::IsDisambigSymbol().
ilabel_info_
vector<vector<int32> > ilabel_info_ private
Definition at line 333 of file context-fst.h.
Referenced by InverseContextFst::FindLabel(), InverseContextFst::IlabelInfo(), and InverseContextFst::SwapIlabelInfo().
ilabel_map_
VectorToLabelMap ilabel_map_ private
Definition at line 325 of file context-fst.h.
Referenced by InverseContextFst::FindLabel().
phone_syms_
kaldi::ConstIntegerSet<Label> phone_syms_ private
Definition at line 276 of file context-fst.h.
Referenced by InverseContextFst::InverseContextFst(), and InverseContextFst::IsPhoneSymbol().
pseudo_eps_symbol_
int32 pseudo_eps_symbol_ private
Definition at line 309 of file context-fst.h.
Referenced by InverseContextFst::CreatePhoneOrEpsArc(), and InverseContextFst::InverseContextFst().
state_map_
VectorToStateMap state_map_ private
Definition at line 314 of file context-fst.h.
Referenced by InverseContextFst::FindState().
state_seqs_
vector<vector<int32> > state_seqs_ private
Definition at line 318 of file context-fst.h.
Referenced by InverseContextFst::Final(), InverseContextFst::FindState(), and InverseContextFst::GetArc().
subsequential_symbol_
Label subsequential_symbol_ private
Definition at line 292 of file context-fst.h.
Referenced by InverseContextFst::CreatePhoneOrEpsArc(), InverseContextFst::Final(), InverseContextFst::GetArc(), and InverseContextFst::GetFullPhoneSequence().
The documentation for this class was generated from the following files:
fstext/context-fst.h
fstext/context-fst.cc