Kaldi: PushSpecialClass Class Reference
PushSpecialClass Class Reference
Public Member Functions
PushSpecialClass (VectorFst< StdArc > *fst, float delta)
Private Types
typedef StdArc Arc
typedef Arc::Weight Weight
typedef Arc::StateId StateId
Private Member Functions
double TestAccuracy ()
void Iterate (float delta)
void ModifyFst ()
Private Attributes
StateId num_states_
StateId initial_state_
std::vector< double > occ_
double lambda_
std::vector< std::vector< std::pair< StateId, double > > > pred_
VectorFst< StdArc > * fst_
Detailed Description
Definition at line 86 of file push-special.cc.
Member Typedef Documentation
Arc
typedef StdArc Arc private
Definition at line 87 of file push-special.cc.
StateId
typedef Arc::StateId StateId private
Definition at line 89 of file push-special.cc.
Weight
typedef Arc::Weight Weight private
Definition at line 88 of file push-special.cc.
Constructor & Destructor Documentation
PushSpecialClass()
PushSpecialClass (VectorFst< StdArc > * fst, float delta) inline
Definition at line 93 of file push-special.cc.
References kaldi::Exp(), PushSpecialClass::fst_, PushSpecialClass::initial_state_, PushSpecialClass::Iterate(), PushSpecialClass::ModifyFst(), PushSpecialClass::num_states_, PushSpecialClass::occ_, and PushSpecialClass::pred_.
                                : fst_(fst) {
     num_states_ = fst_->NumStates();
     initial_state_ = fst_->Start();
     occ_.resize(num_states_, 1.0 / sqrt(num_states_)); // unit length
     pred_.resize(num_states_);
     for (StateId s = 0; s < num_states_; s++) {
       for (ArcIterator<VectorFst<StdArc> > aiter(*fst, s);
            !aiter.Done(); aiter.Next()) {
         const Arc &arc = aiter.Value();
         StateId t = arc.nextstate;
         double weight = kaldi::Exp(-arc.weight.Value());
         pred_[t].push_back(std::make_pair(s, weight));
       }
       double final = kaldi::Exp(-fst_->Final(s).Value());
       if (final != 0.0)
         pred_[initial_state_].push_back(std::make_pair(s, final));
     }
     Iterate(delta);
     ModifyFst();
   }
Member Function Documentation
Iterate()
void Iterate (float delta) inline private
Definition at line 143 of file push-special.cc.
References rnnlm::i, rnnlm::j, KALDI_VLOG, KALDI_WARN, PushSpecialClass::lambda_, PushSpecialClass::num_states_, PushSpecialClass::occ_, PushSpecialClass::pred_, and PushSpecialClass::TestAccuracy().
Referenced by PushSpecialClass::PushSpecialClass().
{
     // This is like the power method to find the top eigenvalue of a matrix.
     // We limit it to 200 iters max, just in case something unanticipated
     // happens, but we should exit due to the "delta" thing, usually after
     // several tens of iterations.
     int iter, max_iter = 200;
     for (iter = 0; iter < max_iter; iter++) {
       std::vector<double> new_occ(num_states_);
       // We initialize new_occ to 0.1 * occ.  A simpler algorithm would
       // initialize them to zero, so it's like the pure power method.  This is
       // like the power method on (M + 0.1 I), and we do it this way to avoid a
       // problem we encountered with certain very simple linear FSTs where the
       // eigenvalues of the weight matrix (including negative and imaginary
       // ones) all have the same magnitude.
       for (int i = 0; i < num_states_; i++)
         new_occ[i] = 0.1 * occ_[i];
       for (int i = 0; i < num_states_; i++) {
         std::vector<std::pair<StateId, double> >::const_iterator iter,
             end = pred_[i].end();
         for (iter = pred_[i].begin(); iter != end; ++iter) {
           StateId j = iter->first;
           double p = iter->second;
           new_occ[j] += occ_[i] * p;
         }
       }
       double sumsq = 0.0;
       for (int i = 0; i < num_states_; i++) sumsq += new_occ[i] * new_occ[i];
       lambda_ = std::sqrt(sumsq);
       double inv_lambda = 1.0 / lambda_;
       for (int i = 0; i < num_states_; i++) occ_[i] = new_occ[i] * inv_lambda;
       KALDI_VLOG(4) << "Lambda is " << lambda_;
       if (iter % 5 == 0 && iter > 0 && TestAccuracy() <= delta) {
         KALDI_VLOG(3) << "Weight-pushing converged after " << iter
                       << " iterations.";
         return;
       }
     }
     KALDI_WARN << "push-special: finished " << iter
                << " iterations without converging.  Output will be inaccurate.";
   }
ModifyFst()
void ModifyFst () inline private
Definition at line 188 of file push-special.cc.
References PushSpecialClass::fst_, PushSpecialClass::initial_state_, KALDI_ISINF, KALDI_ISNAN, KALDI_WARN, kaldi::Log(), PushSpecialClass::num_states_, PushSpecialClass::occ_, and fst::Times().
Referenced by PushSpecialClass::PushSpecialClass().
                    {
     // First get the potentials as negative-logs, like the values
     // in the FST.
     for (StateId s = 0; s < num_states_; s++) {
       occ_[s] = -kaldi::Log(occ_[s]);
       if (KALDI_ISNAN(occ_[s]) || KALDI_ISINF(occ_[s]))
         KALDI_WARN << "NaN or inf found: " << occ_[s];
     }
     for (StateId s = 0; s < num_states_; s++) {
       for (MutableArcIterator<VectorFst<StdArc> > aiter(fst_, s);
            !aiter.Done(); aiter.Next()) {
         Arc arc = aiter.Value();
         StateId t = arc.nextstate;
         arc.weight = Weight(arc.weight.Value() + occ_[t] - occ_[s]);
         aiter.SetValue(arc);
       }
       fst_->SetFinal(s, Times(fst_->Final(s).Value(),
                               Weight(occ_[initial_state_] - occ_[s])));
     }
   }
TestAccuracy()
double TestAccuracy () inline private
Definition at line 116 of file push-special.cc.
References kaldi::Exp(), PushSpecialClass::fst_, PushSpecialClass::initial_state_, KALDI_VLOG, kaldi::Log(), PushSpecialClass::num_states_, and PushSpecialClass::occ_.
Referenced by PushSpecialClass::Iterate().
                         { // returns the error (the difference
     // between the min and max weights).
     double min_sum = 0, max_sum = 0;
     for (StateId s = 0; s < num_states_; s++) {
       double sum = 0.0;
       for (ArcIterator<VectorFst<StdArc> > aiter(*fst_, s);
            !aiter.Done(); aiter.Next()) {
         const Arc &arc = aiter.Value();
         StateId t = arc.nextstate;
         sum += kaldi::Exp(-arc.weight.Value()) * occ_[t] / occ_[s];
       }
       sum += kaldi::Exp(-(fst_->Final(s).Value())) * occ_[initial_state_] / occ_[s];
       if (s == 0) {
         min_sum = sum;
         max_sum = sum;
       } else {
         min_sum = std::min(min_sum, sum);
         max_sum = std::max(max_sum, sum);
       }
    }
     KALDI_VLOG(4) << "min,max is " << min_sum << " " << max_sum;
     return kaldi::Log(max_sum / min_sum); // In FST world we'll actually
     // dealing with logs, so the log of the ratio is more suitable
     // to compare with delta (makes testing the algorithm easier).
   }
Member Data Documentation
fst_
VectorFst<StdArc>* fst_ private
Definition at line 219 of file push-special.cc.
Referenced by PushSpecialClass::ModifyFst(), PushSpecialClass::PushSpecialClass(), and PushSpecialClass::TestAccuracy().
initial_state_
StateId initial_state_ private
Definition at line 211 of file push-special.cc.
Referenced by PushSpecialClass::ModifyFst(), PushSpecialClass::PushSpecialClass(), and PushSpecialClass::TestAccuracy().
lambda_
double lambda_ private
Definition at line 213 of file push-special.cc.
Referenced by PushSpecialClass::Iterate().
num_states_
StateId num_states_ private
Definition at line 210 of file push-special.cc.
Referenced by PushSpecialClass::Iterate(), PushSpecialClass::ModifyFst(), PushSpecialClass::PushSpecialClass(), and PushSpecialClass::TestAccuracy().
occ_
std::vector<double> occ_ private
Definition at line 212 of file push-special.cc.
Referenced by PushSpecialClass::Iterate(), PushSpecialClass::ModifyFst(), PushSpecialClass::PushSpecialClass(), and PushSpecialClass::TestAccuracy().
pred_
std::vector<std::vector<std::pair<StateId, double> > > pred_ private
Definition at line 215 of file push-special.cc.
Referenced by PushSpecialClass::Iterate(), and PushSpecialClass::PushSpecialClass().
The documentation for this class was generated from the following file:
fstext/push-special.cc