Kaldi: AffineComponent Class Reference
AffineComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
BaseFloat OrthonormalConstraint () const
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
AffineComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
virtual void SetParams (const CuVectorBase< BaseFloat > &bias, const CuMatrixBase< BaseFloat > &linear)
const CuVector< BaseFloat > & BiasParams () const
CuVector< BaseFloat > & BiasParams ()
const CuMatrix< BaseFloat > & LinearParams () const
CuMatrix< BaseFloat > & LinearParams ()
AffineComponent (const AffineComponent &other)
AffineComponent (const CuMatrixBase< BaseFloat > &linear_params, const CuVectorBase< BaseFloat > &bias_params, BaseFloat learning_rate)
virtual void Resize (int32 input_dim, int32 output_dim)
void Init (int32 input_dim, int32 output_dim, BaseFloat param_stddev, BaseFloat bias_stddev)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
virtual void FreezeNaturalGradient (bool freeze)
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Member Functions
void Init (std::string matrix_filename)
virtual void Update (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
virtual void UpdateSimple (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
const AffineComponent & operator= (const AffineComponent &other)
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes
CuMatrix< BaseFloat > linear_params_
CuVector< BaseFloat > bias_params_
BaseFloat orthonormal_constraint_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Friends
class NaturalGradientAffineComponent
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 406 of file nnet-simple-component.h.
Constructor & Destructor Documentation
AffineComponent() [1/3]
AffineComponent () inline
Definition at line 416 of file nnet-simple-component.h.
Referenced by AffineComponent::Copy().
 : orthonormal_constraint_(0.0) { } // use Init to really initialize.
AffineComponent() [2/3]
AffineComponent (const AffineComponent & other) explicit
Definition at line 1117 of file nnet-simple-component.cc.
                                                                 :
     UpdatableComponent(component),
     linear_params_(component.linear_params_),
     bias_params_(component.bias_params_),
     orthonormal_constraint_(component.orthonormal_constraint_) { }
AffineComponent() [3/3]
AffineComponent (const CuMatrixBase< BaseFloat > & linear_params, const CuVectorBase< BaseFloat > & bias_params, BaseFloat learning_rate)
Definition at line 1123 of file nnet-simple-component.cc.
References CuVectorBase< Real >::Dim(), KALDI_ASSERT, CuMatrixBase< Real >::NumRows(), and UpdatableComponent::SetUnderlyingLearningRate().
                                                          :
     linear_params_(linear_params),
     bias_params_(bias_params),
     orthonormal_constraint_(0.0) {
   SetUnderlyingLearningRate(learning_rate);
   KALDI_ASSERT(linear_params.NumRows() == bias_params.Dim()&&
                bias_params.Dim() != 0);
 }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 1109 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, KALDI_ASSERT, and AffineComponent::linear_params_.
{
   const AffineComponent *other =
       dynamic_cast<const AffineComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   linear_params_.AddMat(alpha, other->linear_params_);
   bias_params_.AddVec(alpha, other->bias_params_);
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 1252 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), UpdatableComponent::is_gradient_, kaldi::kNoTrans, AffineComponent::linear_params_, AffineComponent::Update(), and AffineComponent::UpdateSimple().
{
   AffineComponent *to_update = dynamic_cast<AffineComponent*>(to_update_in);
   // Propagate the derivative back to the input.
   // add with coefficient 1.0 since property kBackpropAdds is true.
   // If we wanted to add with coefficient 0.0 we'd need to zero the
   // in_deriv, in case of infinities.
   if (in_deriv)
     in_deriv->AddMatMat(1.0, out_deriv, kNoTrans, linear_params_, kNoTrans,
                         1.0);
   if (to_update != NULL) {
     // Next update the model (must do this 2nd so the derivatives we propagate
     // are accurate, in case this == to_update_in.)
     if (to_update->is_gradient_)
       to_update->UpdateSimple(in_value, out_deriv);
     else  // the call below is to a virtual function that may be re-implemented
       to_update->Update(debug_info, in_value, out_deriv);  // by child classes.
   }
 }
BiasParams() [1/2]
const CuVector<BaseFloat>& BiasParams () const inline
Definition at line 455 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsAffine(), ModelCollapser::CollapseComponentsScale(), SvdApplier::DecomposeComponent(), ModelCollapser::GetDiagonallyPreModifiedComponentIndex(), and kaldi::nnet3::ReduceRankOfComponents().
 { return bias_params_; }
BiasParams() [2/2]
CuVector<BaseFloat>& BiasParams () inline
Definition at line 456 of file nnet-simple-component.h.
 { return bias_params_; }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 1165 of file nnet-simple-component.cc.
References AffineComponent::AffineComponent().
Referenced by ModelCollapser::CollapseComponentsScale().
{
   AffineComponent *ans = new AffineComponent(*this);
   return ans;
 }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 1170 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, kaldi::kTrans, AffineComponent::linear_params_, kaldi::TraceMatMat(), and kaldi::VecVec().
{
   const AffineComponent *other =
       dynamic_cast<const AffineComponent*>(&other_in);
   return TraceMatMat(linear_params_, other->linear_params_, kTrans)
       + VecVec(bias_params_, other->bias_params_);
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 1151 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, kaldi::GetVerboseLevel(), UpdatableComponent::Info(), AffineComponent::linear_params_, AffineComponent::orthonormal_constraint_, and kaldi::nnet3::PrintParameterStats().
Referenced by NaturalGradientAffineComponent::Info().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info();
   if (orthonormal_constraint_ != 0.0)
     stream << ", orthonormal-constraint=" << orthonormal_constraint_;
   PrintParameterStats(stream, "linear-params", linear_params_,
                       false, // include_mean
                       true, // include_row_norms
                       true, // include_column_norms
                       GetVerboseLevel() >= 2); // include_singular_values
   PrintParameterStats(stream, "bias", bias_params_, true);
   return stream.str();
 }
Init() [1/2]
void Init (int32 input_dim, int32 output_dim, BaseFloat param_stddev, BaseFloat bias_stddev)
Definition at line 1177 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, KALDI_ASSERT, and AffineComponent::linear_params_.
Referenced by ModelCollapser::CollapseComponentsAffine(), and AffineComponent::InitFromConfig().
{
   linear_params_.Resize(output_dim, input_dim);
   bias_params_.Resize(output_dim);
   KALDI_ASSERT(output_dim > 0 && input_dim > 0 && param_stddev >= 0.0);
   linear_params_.SetRandn(); // sets to random normally distributed noise.
   linear_params_.Scale(param_stddev);
   bias_params_.SetRandn();
   bias_params_.Scale(bias_stddev);
 }
Init() [2/2]
void Init (std::string matrix_filename) protected
Definition at line 1188 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, KALDI_ASSERT, AffineComponent::linear_params_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Range(), and kaldi::ReadKaldiObject().
{
   CuMatrix<BaseFloat> mat;
   ReadKaldiObject(matrix_filename, &mat); // will abort on failure.
   KALDI_ASSERT(mat.NumCols() >= 2);
   int32 input_dim = mat.NumCols() - 1, output_dim = mat.NumRows();
   linear_params_.Resize(output_dim, input_dim);
   bias_params_.Resize(output_dim);
   linear_params_.CopyFromMat(mat.Range(0, output_dim, 0, input_dim));
   bias_params_.CopyColFromMat(mat, input_dim);
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 1199 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), AffineComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), AffineComponent::InputDim(), KALDI_ASSERT, KALDI_ERR, AffineComponent::orthonormal_constraint_, AffineComponent::OutputDim(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   bool ok = true;
   std::string matrix_filename;
   int32 input_dim = -1, output_dim = -1;
   InitLearningRatesFromConfig(cfl);
   if (cfl->GetValue("matrix", &matrix_filename)) {
     Init(matrix_filename);
     if (cfl->GetValue("input-dim", &input_dim))
       KALDI_ASSERT(input_dim == InputDim() &&
                    "input-dim mismatch vs. matrix.");
     if (cfl->GetValue("output-dim", &output_dim))
       KALDI_ASSERT(output_dim == OutputDim() &&
                    "output-dim mismatch vs. matrix.");
   } else {
     ok = ok && cfl->GetValue("input-dim", &input_dim);
     ok = ok && cfl->GetValue("output-dim", &output_dim);
     BaseFloat param_stddev = 1.0 / std::sqrt(input_dim),
         bias_stddev = 1.0;
     cfl->GetValue("param-stddev", &param_stddev);
     cfl->GetValue("bias-stddev", &bias_stddev);
     Init(input_dim, output_dim,
          param_stddev, bias_stddev);
   }
   cfl->GetValue("orthonormal-constraint", &orthonormal_constraint_);
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   if (!ok)
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 408 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsAffine(), SvdApplier::DecomposeComponent(), SvdApplier::DecomposeComponents(), AffineComponent::InitFromConfig(), NaturalGradientAffineComponent::InitFromConfig(), LinearComponent::InitFromConfig(), AffineComponent::NumParameters(), kaldi::nnet3::ReduceRankOfComponents(), AffineComponent::UnVectorize(), and AffineComponent::Vectorize().
 { return linear_params_.NumCols(); }
LinearParams() [1/2]
const CuMatrix<BaseFloat>& LinearParams () const inline
Definition at line 457 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsAffine(), ModelCollapser::CollapseComponentsScale(), kaldi::nnet3::ConstrainOrthonormal(), SvdApplier::DecomposeComponent(), ModelCollapser::GetDiagonallyPreModifiedComponentIndex(), and kaldi::nnet3::ReduceRankOfComponents().
 { return linear_params_; }
LinearParams() [2/2]
CuMatrix<BaseFloat>& LinearParams () inline
Definition at line 458 of file nnet-simple-component.h.
References PnormComponent::Init().
 { return linear_params_; }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 1314 of file nnet-simple-component.cc.
References AffineComponent::InputDim(), and AffineComponent::OutputDim().
Referenced by AffineComponent::UnVectorize(), and AffineComponent::Vectorize().
{
   return (InputDim() + 1) * OutputDim();
 }
operator=()
const AffineComponent& operator= (const AffineComponent & other) protected
OrthonormalConstraint()
BaseFloat OrthonormalConstraint () const inline
Definition at line 411 of file nnet-simple-component.h.
References Component::Info(), and PnormComponent::InitFromConfig().
Referenced by kaldi::nnet3::ConstrainOrthonormal().
 { return orthonormal_constraint_; }
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 409 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsAffine(), ModelCollapser::CollapseComponentsScale(), SvdApplier::DecomposeComponent(), SvdApplier::DecomposeComponents(), AffineComponent::InitFromConfig(), NaturalGradientAffineComponent::InitFromConfig(), LinearComponent::InitFromConfig(), AffineComponent::NumParameters(), kaldi::nnet3::ReduceRankOfComponents(), AffineComponent::UnVectorize(), and AffineComponent::Vectorize().
 { return linear_params_.NumRows(); }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 1141 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, AffineComponent::linear_params_, CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
{
   CuMatrix<BaseFloat> temp_linear_params(linear_params_);
   temp_linear_params.SetRandn();
   linear_params_.AddMat(stddev, temp_linear_params);
   CuVector<BaseFloat> temp_bias_params(bias_params_);
   temp_bias_params.SetRandn();
   bias_params_.AddVec(stddev, temp_bias_params);
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 1234 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), AffineComponent::bias_params_, CuMatrixBase< Real >::CopyRowsFromVec(), kaldi::kNoTrans, kaldi::kTrans, and AffineComponent::linear_params_.
{
   // No need for asserts as they'll happen within the matrix operations.
   out->CopyRowsFromVec(bias_params_); // copies bias_params_ to each row
   // of *out.
   out->AddMatMat(1.0, in, kNoTrans, linear_params_, kTrans, 1.0);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 418 of file nnet-simple-component.h.
References Component::Add(), PnormComponent::Backprop(), PnormComponent::Copy(), kaldi::nnet3::DotProduct(), kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kUpdatableComponent, kaldi::nnet3::NumParameters(), kaldi::nnet3::PerturbParams(), PnormComponent::Propagate(), PnormComponent::Read(), Component::Scale(), and PnormComponent::Write().
{
     return kSimpleComponent|kUpdatableComponent|
         kBackpropNeedsInput|kBackpropAdds;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 1280 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, AffineComponent::linear_params_, AffineComponent::orthonormal_constraint_, kaldi::PeekToken(), kaldi::ReadBasicType(), and UpdatableComponent::ReadUpdatableCommon().
{
   ReadUpdatableCommon(is, binary);  // read opening tag and learning rate.
   ExpectToken(is, binary, "<LinearParams>");
   linear_params_.Read(is, binary);
   ExpectToken(is, binary, "<BiasParams>");
   bias_params_.Read(is, binary);
   if (PeekToken(is, binary) == 'I') {
     // for back compatibility; we don't write this here any
     // more as it's written and read in Write/ReadUpdatableCommon
     ExpectToken(is, binary, "<IsGradient>");
     ReadBasicType(is, binary, &is_gradient_);
   }
   if (PeekToken(is, binary) == 'O') {
     ExpectToken(is, binary, "<OrthonormalConstraint>");
     ReadBasicType(is, binary, &orthonormal_constraint_);
   } else {
     orthonormal_constraint_ = 0.0;
   }
   ExpectToken(is, binary, "</AffineComponent>");
 }
Resize()
void Resize (int32 input_dim, int32 output_dim) virtual
Definition at line 1103 of file nnet-simple-component.cc.
References KALDI_ASSERT.
{
   KALDI_ASSERT(input_dim > 0 && output_dim > 0);
   bias_params_.Resize(output_dim);
   linear_params_.Resize(output_dim, input_dim);
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 1092 of file nnet-simple-component.cc.
Referenced by ModelCollapser::GetScaledComponentIndex().
{
   if (scale == 0.0) {
     // If scale == 0.0 we call SetZero() which will get rid of NaN's and inf's.
     linear_params_.SetZero();
     bias_params_.SetZero();
   } else {
     linear_params_.Scale(scale);
     bias_params_.Scale(scale);
   }
 }
SetParams()
void SetParams (const CuVectorBase< BaseFloat > & bias, const CuMatrixBase< BaseFloat > & linear) virtual
Definition at line 1134 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, KALDI_ASSERT, and AffineComponent::linear_params_.
Referenced by ModelCollapser::CollapseComponentsAffine(), ModelCollapser::CollapseComponentsScale(), and kaldi::nnet3::ReduceRankOfComponents().
{
   bias_params_ = bias;
   linear_params_ = linear;
   KALDI_ASSERT(bias_params_.Dim() == linear_params_.NumRows());
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 417 of file nnet-simple-component.h.
 { return "AffineComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 1323 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, VectorBase< Real >::Dim(), AffineComponent::InputDim(), KALDI_ASSERT, AffineComponent::linear_params_, AffineComponent::NumParameters(), AffineComponent::OutputDim(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params.Dim() == this->NumParameters());
   linear_params_.CopyRowsFromVec(params.Range(0, InputDim() * OutputDim()));
   bias_params_.CopyFromVec(params.Range(InputDim() * OutputDim(),
                                         OutputDim()));
 }
Update()
virtual void Update (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) inline protected virtual
Reimplemented in NaturalGradientAffineComponent.
Definition at line 476 of file nnet-simple-component.h.
Referenced by AffineComponent::Backprop().
{
     UpdateSimple(in_value, out_deriv);
   }
UpdateSimple()
void UpdateSimple (const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) protected virtual
Definition at line 1245 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, kaldi::kNoTrans, kaldi::kTrans, UpdatableComponent::learning_rate_, and AffineComponent::linear_params_.
Referenced by AffineComponent::Backprop().
{
   bias_params_.AddRowSumMat(learning_rate_, out_deriv, 1.0);
   linear_params_.AddMatMat(learning_rate_, out_deriv, kTrans,
                            in_value, kNoTrans, 1.0);
 }
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 1317 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, VectorBase< Real >::Dim(), AffineComponent::InputDim(), KALDI_ASSERT, AffineComponent::linear_params_, AffineComponent::NumParameters(), AffineComponent::OutputDim(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params->Dim() == this->NumParameters());
   params->Range(0, InputDim() * OutputDim()).CopyRowsFromMat(linear_params_);
   params->Range(InputDim() * OutputDim(),
                 OutputDim()).CopyFromVec(bias_params_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 1301 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, AffineComponent::linear_params_, AffineComponent::orthonormal_constraint_, kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate
   WriteToken(os, binary, "<LinearParams>");
   linear_params_.Write(os, binary);
   WriteToken(os, binary, "<BiasParams>");
   bias_params_.Write(os, binary);
   if (orthonormal_constraint_ != 0.0) {
     WriteToken(os, binary, "<OrthonormalConstraint>");
     WriteBasicType(os, binary, orthonormal_constraint_);
   }
   WriteToken(os, binary, "</AffineComponent>");
 }
Friends And Related Function Documentation
NaturalGradientAffineComponent
friend class NaturalGradientAffineComponent friend
Definition at line 473 of file nnet-simple-component.h.
Member Data Documentation
bias_params_
CuVector<BaseFloat> bias_params_ protected
Definition at line 490 of file nnet-simple-component.h.
Referenced by AffineComponent::Add(), NaturalGradientAffineComponent::Add(), AffineComponent::DotProduct(), AffineComponent::Info(), AffineComponent::Init(), NaturalGradientAffineComponent::InitFromConfig(), AffineComponent::PerturbParams(), AffineComponent::Propagate(), AffineComponent::Read(), NaturalGradientAffineComponent::Scale(), AffineComponent::SetParams(), AffineComponent::UnVectorize(), NaturalGradientAffineComponent::Update(), AffineComponent::UpdateSimple(), AffineComponent::Vectorize(), AffineComponent::Write(), and NaturalGradientAffineComponent::Write().
linear_params_
CuMatrix<BaseFloat> linear_params_ protected
Definition at line 489 of file nnet-simple-component.h.
Referenced by AffineComponent::Add(), NaturalGradientAffineComponent::Add(), AffineComponent::Backprop(), AffineComponent::DotProduct(), AffineComponent::Info(), AffineComponent::Init(), NaturalGradientAffineComponent::InitFromConfig(), AffineComponent::PerturbParams(), AffineComponent::Propagate(), AffineComponent::Read(), NaturalGradientAffineComponent::Scale(), AffineComponent::SetParams(), AffineComponent::UnVectorize(), NaturalGradientAffineComponent::Update(), AffineComponent::UpdateSimple(), AffineComponent::Vectorize(), AffineComponent::Write(), and NaturalGradientAffineComponent::Write().
orthonormal_constraint_
BaseFloat orthonormal_constraint_ protected
Definition at line 493 of file nnet-simple-component.h.
Referenced by AffineComponent::Info(), LinearComponent::Info(), AffineComponent::InitFromConfig(), NaturalGradientAffineComponent::InitFromConfig(), LinearComponent::InitFromConfig(), AffineComponent::Read(), LinearComponent::Read(), AffineComponent::Write(), NaturalGradientAffineComponent::Write(), and LinearComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc