Kaldi: CovarianceStats Class Reference
CovarianceStats Class Reference
Public Member Functions
CovarianceStats (int32 dim)
void GetTotalCovar (SpMatrix< double > *tot_covar) const
get total covariance, normalized per number of frames.
void GetWithinCovar (SpMatrix< double > *within_covar)
void AccStats (const Matrix< double > &utts_of_this_spk)
bool SingularTotCovar ()
Will return Empty() if the within-class covariance matrix would be zero.
bool Empty ()
std::string Info ()
int32 Dim ()
void AddStats (const CovarianceStats &other)
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (CovarianceStats)
Private Attributes
SpMatrix< double > tot_covar_
SpMatrix< double > between_covar_
int32 num_spk_
int32 num_utt_
Detailed Description
Definition at line 30 of file ivector-compute-lda.cc.
Constructor & Destructor Documentation
CovarianceStats()
CovarianceStats (int32 dim) inline
Definition at line 32 of file ivector-compute-lda.cc.
                             : tot_covar_(dim),
                               between_covar_(dim),
                               num_spk_(0),
                               num_utt_(0) { }
Member Function Documentation
AccStats()
void AccStats (const Matrix< double > & utts_of_this_spk) inline
Definition at line 49 of file ivector-compute-lda.cc.
References SpMatrix< Real >::AddMat2(), VectorBase< Real >::AddRowSumMat(), SpMatrix< Real >::AddVec2(), CovarianceStats::between_covar_, CovarianceStats::Dim(), kaldi::kTrans, CovarianceStats::num_spk_, CovarianceStats::num_utt_, MatrixBase< Real >::NumRows(), and CovarianceStats::tot_covar_.
Referenced by kaldi::ComputeLdaTransform().
{
     int32 num_utts = utts_of_this_spk.NumRows();
     tot_covar_.AddMat2(1.0, utts_of_this_spk, kTrans, 1.0);
     Vector<double> spk_average(Dim());
     spk_average.AddRowSumMat(1.0 / num_utts, utts_of_this_spk);
     between_covar_.AddVec2(num_utts, spk_average);
     num_utt_ += num_utts;
     num_spk_ += 1;
   }
AddStats()
void AddStats (const CovarianceStats & other) inline
Definition at line 68 of file ivector-compute-lda.cc.
References SpMatrix< Real >::AddSp(), CovarianceStats::between_covar_, CovarianceStats::KALDI_DISALLOW_COPY_AND_ASSIGN(), CovarianceStats::num_spk_, CovarianceStats::num_utt_, and CovarianceStats::tot_covar_.
{
     tot_covar_.AddSp(1.0, other.tot_covar_);
     between_covar_.AddSp(1.0, other.between_covar_);
     num_spk_ += other.num_spk_;
     num_utt_ += other.num_utt_;
   }
Dim()
int32 Dim () inline
Definition at line 66 of file ivector-compute-lda.cc.
References PackedMatrix< Real >::NumRows(), and CovarianceStats::tot_covar_.
Referenced by CovarianceStats::AccStats(), and CovarianceStats::SingularTotCovar().
 { return tot_covar_.NumRows(); }
Empty()
bool Empty () inline
Definition at line 60 of file ivector-compute-lda.cc.
References CovarianceStats::num_spk_, and CovarianceStats::num_utt_.
Referenced by kaldi::ComputeLdaTransform().
 { return (num_utt_ - num_spk_ == 0); }
GetTotalCovar()
void GetTotalCovar (SpMatrix< double > * tot_covar) const inline
get total covariance, normalized per number of frames.
Definition at line 38 of file ivector-compute-lda.cc.
References KALDI_ASSERT, CovarianceStats::num_utt_, PackedMatrix< Real >::Scale(), and CovarianceStats::tot_covar_.
Referenced by kaldi::ComputeLdaTransform().
{
     KALDI_ASSERT(num_utt_ > 0);
     *tot_covar = tot_covar_;
     tot_covar->Scale(1.0 / num_utt_);
   }
GetWithinCovar()
void GetWithinCovar (SpMatrix< double > * within_covar) inline
Definition at line 43 of file ivector-compute-lda.cc.
References SpMatrix< Real >::AddSp(), CovarianceStats::between_covar_, KALDI_ASSERT, CovarianceStats::num_spk_, CovarianceStats::num_utt_, PackedMatrix< Real >::Scale(), and CovarianceStats::tot_covar_.
Referenced by kaldi::ComputeLdaTransform().
{
     KALDI_ASSERT(num_utt_ - num_spk_ > 0);
     *within_covar = tot_covar_;
     within_covar->AddSp(-1.0, between_covar_);
     within_covar->Scale(1.0 / num_utt_);
   }
Info()
std::string Info () inline
Definition at line 61 of file ivector-compute-lda.cc.
References CovarianceStats::num_spk_, and CovarianceStats::num_utt_.
Referenced by kaldi::ComputeLdaTransform().
                    {
     std::ostringstream ostr;
     ostr << num_spk_ << " speakers, " << num_utt_ << " utterances. ";
     return ostr.str();
   }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (CovarianceStats) private
Referenced by CovarianceStats::AddStats().
SingularTotCovar()
bool SingularTotCovar () inline
Will return Empty() if the within-class covariance matrix would be zero.
Definition at line 59 of file ivector-compute-lda.cc.
References CovarianceStats::Dim(), and CovarianceStats::num_utt_.
Referenced by kaldi::ComputeLdaTransform().
 { return (num_utt_ < Dim()); }
Member Data Documentation
between_covar_
SpMatrix<double> between_covar_ private
Definition at line 77 of file ivector-compute-lda.cc.
Referenced by CovarianceStats::AccStats(), CovarianceStats::AddStats(), and CovarianceStats::GetWithinCovar().
num_spk_
int32 num_spk_ private
Definition at line 78 of file ivector-compute-lda.cc.
Referenced by CovarianceStats::AccStats(), CovarianceStats::AddStats(), CovarianceStats::Empty(), CovarianceStats::GetWithinCovar(), and CovarianceStats::Info().
num_utt_
int32 num_utt_ private
Definition at line 79 of file ivector-compute-lda.cc.
Referenced by CovarianceStats::AccStats(), CovarianceStats::AddStats(), CovarianceStats::Empty(), CovarianceStats::GetTotalCovar(), CovarianceStats::GetWithinCovar(), CovarianceStats::Info(), and CovarianceStats::SingularTotCovar().
tot_covar_
SpMatrix<double> tot_covar_ private
Definition at line 76 of file ivector-compute-lda.cc.
Referenced by CovarianceStats::AccStats(), CovarianceStats::AddStats(), CovarianceStats::Dim(), CovarianceStats::GetTotalCovar(), and CovarianceStats::GetWithinCovar().
The documentation for this class was generated from the following file:
ivectorbin/ivector-compute-lda.cc