Kaldi: DecodableAmDiagGmmUnmapped Class Reference
DecodableAmDiagGmmUnmapped Class Reference
DecodableAmDiagGmmUnmapped is a decodable object that takes indices that correspond to pdf-id's plus one.
#include <decodable-am-diag-gmm.h>
Classes
struct LikelihoodCacheRecord
Defines a cache record for a state.
Public Member Functions
DecodableAmDiagGmmUnmapped (const AmDiagGmm &am, const Matrix< BaseFloat > &feats, BaseFloat log_sum_exp_prune=-1.0)
If you set log_sum_exp_prune to a value greater than 0 it will prune in the LogSumExp operation (larger = more exact); I suggest 5.
virtual BaseFloat LogLikelihood (int32 frame, int32 state_index)
Returns the log likelihood, which will be negated in the decoder.
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Protected Member Functions
void ResetLogLikeCache ()
virtual BaseFloat LogLikelihoodZeroBased (int32 frame, int32 state_index)
Protected Attributes
const AmDiagGmm & acoustic_model_
const Matrix< BaseFloat > & feature_matrix_
int32 previous_frame_
BaseFloat log_sum_exp_prune_
std::vector< LikelihoodCacheRecord > log_like_cache_
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmDiagGmmUnmapped)
Private Attributes
Vector< BaseFloat > data_squared_
Cache for fast likelihood calculation.
Detailed Description
DecodableAmDiagGmmUnmapped is a decodable object that takes indices that correspond to pdf-id's plus one.
This may be used in future in a decoder that doesn't need to output alignments, if we create FSTs that have the pdf-ids plus one as the input labels (we couldn't use the pdf-ids themselves because they start from zero, and the graph might have epsilon transitions).
Definition at line 45 of file decodable-am-diag-gmm.h.
Constructor & Destructor Documentation
DecodableAmDiagGmmUnmapped()
DecodableAmDiagGmmUnmapped (const AmDiagGmm & am, const Matrix< BaseFloat > & feats, BaseFloat log_sum_exp_prune = -1.0) inline
If you set log_sum_exp_prune to a value greater than 0 it will prune in the LogSumExp operation (larger = more exact); I suggest 5.
This is advisable if it's spending a long time doing exp operations.
Definition at line 51 of file decodable-am-diag-gmm.h.
References DecodableAmDiagGmmUnmapped::ResetLogLikeCache().
                                                                 :
     acoustic_model_(am), feature_matrix_(feats),
     previous_frame_(-1), log_sum_exp_prune_(log_sum_exp_prune),
     data_squared_(feats.NumCols()) {
     ResetLogLikeCache();
   }
Member Function Documentation
IsLastFrame()
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frames are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). Caution: the behavior of this function in an online setting is being changed somewhat. In future it may return false in cases where we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. The plan in future is to rely more on NumFramesReady(), and in future, IsLastFrame() would always return false in an online-decoding setting, and would only return true in a decoding-from-matrix setting where we want to allow the last delta or LDA features to be flushed out for compatibility with the baseline setup.
Implements DecodableInterface.
Definition at line 70 of file decodable-am-diag-gmm.h.
References KALDI_ASSERT, DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmUnmapped::NumFramesReady(), and DecodableAmDiagGmmUnmapped::ResetLogLikeCache().
{
     KALDI_ASSERT(frame < NumFramesReady());
     return (frame == NumFramesReady() - 1);
   }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmDiagGmmUnmapped) private
LogLikelihood()
virtual BaseFloat LogLikelihood (int32 frame, int32 index) inline virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Reimplemented in DecodableAmDiagGmmScaled, DecodableAmDiagGmm, DecodableAmDiagGmmRegtreeMllr, and DecodableAmDiagGmmRegtreeFmllr.
Definition at line 62 of file decodable-am-diag-gmm.h.
References DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased().
{
     return LogLikelihoodZeroBased(frame, state_index - 1);
   }
LogLikelihoodZeroBased()
BaseFloat LogLikelihoodZeroBased (int32 frame, int32 state_index) protected virtual
Reimplemented in DecodableAmDiagGmmRegtreeMllr, and DecodableAmDiagGmmRegtreeFmllr.
Definition at line 28 of file decodable-am-diag-gmm.cc.
References DecodableAmDiagGmmUnmapped::acoustic_model_, VectorBase< Real >::AddMatVec(), DecodableAmDiagGmmUnmapped::data_squared_, VectorBase< Real >::Dim(), DiagGmm::Dim(), DecodableAmDiagGmmUnmapped::feature_matrix_, DiagGmm::gconsts(), AmDiagGmm::GetPdf(), DiagGmm::inv_vars(), KALDI_ASSERT, KALDI_ERR, KALDI_ISINF, KALDI_ISNAN, kaldi::kNoTrans, DecodableAmDiagGmmUnmapped::log_like_cache_, DecodableAmDiagGmmUnmapped::log_sum_exp_prune_, DiagGmm::means_invvars(), DecodableAmDiagGmmUnmapped::NumFramesReady(), DecodableAmDiagGmmUnmapped::NumIndices(), DecodableAmDiagGmmUnmapped::previous_frame_, MatrixBase< Real >::Row(), and DiagGmm::valid_gconsts().
Referenced by DecodableAmDiagGmmUnmapped::IsLastFrame(), DecodableAmDiagGmmUnmapped::LogLikelihood(), DecodableAmDiagGmm::LogLikelihood(), and DecodableAmDiagGmmScaled::LogLikelihood().
{
   KALDI_ASSERT(static_cast<size_t>(frame) <
                static_cast<size_t>(NumFramesReady()));
   KALDI_ASSERT(static_cast<size_t>(state) < static_cast<size_t>(NumIndices()) &&
                "Likely graph/model mismatch, e.g. using wrong HCLG.fst");
   if (log_like_cache_[state].hit_time == frame) {
     return log_like_cache_[state].log_like;  // return cached value, if found
   }
   if (frame != previous_frame_) {  // cache the squared stats.
     data_squared_.CopyFromVec(feature_matrix_.Row(frame));
     data_squared_.ApplyPow(2.0);
     previous_frame_ = frame;
   }
   const DiagGmm &pdf = acoustic_model_.GetPdf(state);
   const VectorBase<BaseFloat> &data = feature_matrix_.Row(frame);
   // check if everything is in order
   if (pdf.Dim() != data.Dim()) {
     KALDI_ERR << "Dim mismatch: data dim = "  << data.Dim()
         << " vs. model dim = " << pdf.Dim();
   }
   if (!pdf.valid_gconsts()) {
     KALDI_ERR << "State "  << (state)  << ": Must call ComputeGconsts() "
         "before computing likelihood.";
   }
   Vector<BaseFloat> loglikes(pdf.gconsts());  // need to recreate for each pdf
   // loglikes +=  means * inv(vars) * data.
   loglikes.AddMatVec(1.0, pdf.means_invvars(), kNoTrans, data, 1.0);
   // loglikes += -0.5 * inv(vars) * data_sq.
   loglikes.AddMatVec(-0.5, pdf.inv_vars(), kNoTrans, data_squared_, 1.0);
   BaseFloat log_sum = loglikes.LogSumExp(log_sum_exp_prune_);
   if (KALDI_ISNAN(log_sum) || KALDI_ISINF(log_sum))
     KALDI_ERR << "Invalid answer (overflow or invalid variances/features?)";
   log_like_cache_[state].log_like = log_sum;
   log_like_cache_[state].hit_time = frame;
   return log_sum;
 }
NumFramesReady()
virtual int32 NumFramesReady () const inline virtual
The call NumFramesReady() will return the number of frames currently available for this decodable object.
This is for use in setups where you don't want the decoder to block while waiting for input. This is newly added as of Jan 2014, and I hope, going forward, to rely on this mechanism more than IsLastFrame to know when to stop decoding.
Reimplemented from DecodableInterface.
Reimplemented in DecodableAmDiagGmmRegtreeMllr, and DecodableAmDiagGmmRegtreeFmllr.
Definition at line 65 of file decodable-am-diag-gmm.h.
References DecodableAmDiagGmmUnmapped::feature_matrix_, and MatrixBase< Real >::NumRows().
Referenced by DecodableAmDiagGmmUnmapped::IsLastFrame(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), and main().
 { return feature_matrix_.NumRows(); }
NumIndices()
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst).
Implements DecodableInterface.
Reimplemented in DecodableAmDiagGmmScaled, DecodableAmDiagGmm, DecodableAmDiagGmmRegtreeMllr, and DecodableAmDiagGmmRegtreeFmllr.
Definition at line 68 of file decodable-am-diag-gmm.h.
References DecodableAmDiagGmmUnmapped::acoustic_model_, and AmDiagGmm::NumPdfs().
Referenced by DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased().
 { return acoustic_model_.NumPdfs(); }
ResetLogLikeCache()
void ResetLogLikeCache () protected
Definition at line 74 of file decodable-am-diag-gmm.cc.
References DecodableAmDiagGmmUnmapped::acoustic_model_, DecodableAmDiagGmmUnmapped::log_like_cache_, and AmDiagGmm::NumPdfs().
Referenced by DecodableAmDiagGmmUnmapped::DecodableAmDiagGmmUnmapped(), DecodableAmDiagGmmRegtreeMllr::InitCache(), and DecodableAmDiagGmmUnmapped::IsLastFrame().
{
   if (static_cast<int32>(log_like_cache_.size()) != acoustic_model_.NumPdfs()) {
     log_like_cache_.resize(acoustic_model_.NumPdfs());
   }
   vector<LikelihoodCacheRecord>::iterator it = log_like_cache_.begin(),
       end = log_like_cache_.end();
   for (; it != end; ++it) { it->hit_time = -1; }
 }
Member Data Documentation
acoustic_model_
const AmDiagGmm& acoustic_model_ protected
Definition at line 79 of file decodable-am-diag-gmm.h.
Referenced by DecodableAmDiagGmmRegtreeMllr::GetXformedMeanInvVars(), DecodableAmDiagGmmRegtreeMllr::InitCache(), DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), DecodableAmDiagGmmUnmapped::NumIndices(), and DecodableAmDiagGmmUnmapped::ResetLogLikeCache().
data_squared_
Vector<BaseFloat> data_squared_ private
Cache for fast likelihood calculation.
Definition at line 91 of file decodable-am-diag-gmm.h.
Referenced by DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), and DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased().
feature_matrix_
const Matrix<BaseFloat>& feature_matrix_ protected
Definition at line 80 of file decodable-am-diag-gmm.h.
Referenced by DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeFmllr::NumFramesReady(), DecodableAmDiagGmmUnmapped::NumFramesReady(), and DecodableAmDiagGmmRegtreeMllr::NumFramesReady().
log_like_cache_
std::vector<LikelihoodCacheRecord> log_like_cache_ protected
Definition at line 89 of file decodable-am-diag-gmm.h.
Referenced by DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), and DecodableAmDiagGmmUnmapped::ResetLogLikeCache().
log_sum_exp_prune_
BaseFloat log_sum_exp_prune_ protected
Definition at line 82 of file decodable-am-diag-gmm.h.
Referenced by DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), and DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased().
previous_frame_
int32 previous_frame_ protected
Definition at line 81 of file decodable-am-diag-gmm.h.
Referenced by DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), and DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased().
The documentation for this class was generated from the following files:
gmm/decodable-am-diag-gmm.h
gmm/decodable-am-diag-gmm.cc