Kaldi: TxpPauses Class Reference
TxpPauses Class Reference
Convert punctuation and break tags into pauses /ref idlaktxp_pause_insertion.
#include <mod-pauses.h>
Public Member Functions
TxpPauses ()
~TxpPauses ()
bool Init (const TxpParseOptions &opts)
Load voice data.
bool Process (pugi::xml_document *input)
Process the XML, modifying the XML to reflect linguistic information.
Public Member Functions inherited from TxpModule
TxpModule (const std::string &name)
Construct module, also loads tpdb modules in specific instances.
virtual ~TxpModule ()
const std::string GetConfigValue (const std::string &key)
Return a configuration value for this module as a string (rendundant)
const char * GetOptValue (const char *key)
Return an option value for this module as a string.
bool GetConfigValueBool (const std::string &key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
bool GetOptValueBool (const char *key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
const std::string & GetName () const
Get the name of the module.
pugi::xml_node GetHeader (pugi::xml_document *input)
Gets or adds a module header to txpheader.
Private Member Functions
bool ProcessFile (pugi::xml_node *file)
Process a file (documents may have several files of information separated within file id elements).
Private Attributes
TxpPbreak pbreak_
Object containing lookup between punctuation and break strength and time.
bool hzone_
If true tries distinguish real line breaks from those at page left A hypenation zone (hzone) can then be used to remove phantom line breaks and reappend soft hypenation.
int32 hzone_start_
Column start for hzone.
int32 hzone_end_
Column end for hzone.
Additional Inherited Members
Protected Attributes inherited from TxpModule
const TxpParseOptions * opts_
Options structure for the module.
std::string tpdb_
Directory for text processing database (tpdb) files used by txpxmldata objectys in the module.
Detailed Description
Convert punctuation and break tags into pauses /ref idlaktxp_pause_insertion.
Definition at line 38 of file mod-pauses.h.
Constructor & Destructor Documentation
TxpPauses()
TxpPauses () explicit
Definition at line 29 of file mod-pauses.cc.
 : TxpModule("pauses") {}
~TxpPauses()
~TxpPauses ()
Definition at line 41 of file mod-pauses.cc.
                       {
 }
Member Function Documentation
Init()
bool Init (const TxpParseOptions & opts) virtual
Load voice data.
Reimplemented from TxpModule.
Definition at line 31 of file mod-pauses.cc.
References TxpModule::GetOptValue(), TxpModule::GetOptValueBool(), TxpParseOptions::GetTpdb(), TxpPauses::hzone_, TxpPauses::hzone_end_, TxpPauses::hzone_start_, TxpPbreak::Init(), TxpModule::opts_, TxpPbreak::Parse(), TxpPauses::pbreak_, and TxpModule::tpdb_.
Referenced by main().
{
   opts_ = &opts;
   tpdb_ = opts.GetTpdb();
   pbreak_.Init(opts, std::string(GetOptValue("arch")));
   hzone_ = GetOptValueBool("hzone");
   hzone_start_ = atoi(GetOptValue("hzone-start"));
   hzone_end_ = atoi(GetOptValue("hzone-end"));
   return pbreak_.Parse(tpdb_);
 }
Process()
bool Process (pugi::xml_document * input) virtual
Process the XML, modifying the XML to reflect linguistic information.
Reimplemented from TxpModule.
Definition at line 46 of file mod-pauses.cc.
References TxpPauses::ProcessFile().
Referenced by main().
{
   pugi::xpath_node_set files;
   files = input->document_element().select_nodes("//fileid");
   if (files.size()) {
     for (pugi::xpath_node_set::const_iterator it = files.begin();
          it != files.end();
          ++it) {
       pugi::xml_node file = (*it).node();
       ProcessFile(&file);
     }
   } else {
     pugi::xml_node document_element = input->document_element();
     ProcessFile(&document_element);
   }
   return true;
 }
ProcessFile()
bool ProcessFile (pugi::xml_node * file) private
Process a file (documents may have several files of information separated within file id elements).
Definition at line 65 of file mod-pauses.cc.
References kaldi::_insert_break_after(), kaldi::_insert_break_before(), TxpPbreakInfo::Clear(), TxpPbreak::get_default_time(), TxpPbreak::get_default_type(), TxpPbreak::GetPbreak(), TxpPbreak::GetPbreakPre(), TxpPbreak::GetPbreakPst(), TxpPbreak::GetWhitespaceBreaks(), TxpPauses::hzone_, TxpPauses::hzone_end_, TxpPauses::hzone_start_, TxpPauses::pbreak_, TxpPbreakInfo::time, kaldi::TXPPBREAK_POS_PRE, kaldi::TXPPBREAK_POS_PST, and TxpPbreakInfo::type.
Referenced by TxpPauses::Process().
{
   pugi::xml_node *breakitem = NULL, *ptk = NULL, pretk;
   const TxpPbreakInfo* pbreak;
   TxpPbreakInfo pbreakpunc;
   bool prebreak, pstbreak, newline = false, newline2 = false;
   pugi::xpath_node_set files;
   pugi::xpath_node_set tks =
       file->select_nodes(".//tk|.//break|.//ws");
   tks.sort();
   for (pugi::xpath_node_set::const_iterator it = tks.begin();
        it != tks.end();
        ++it) {
     pugi::xml_node tk = (*it).node();
     if (!strcmp(tk.name(), "break")) {
       if (!tk.attribute("type")) tk.append_attribute("type");
       if (!tk.attribute("time")) tk.append_attribute("time");
       if (!tk.attribute("strength").empty()) {
         pbreak = pbreak_.GetPbreakPst(tk.attribute("strength").value());
         if (pbreak) {
           tk.attribute("type").set_value(pbreak->type);
           tk.attribute("time").set_value(pbreak->time);
         }
       }
       // break tags override punctuation so keep a record of what happened
       // before tk
       if (!*tk.attribute("type").value()) {
         tk.attribute("type").set_value(pbreak_.get_default_type());
       }
       if (!*tk.attribute("time").value()) {
         tk.attribute("time").set_value(pbreak_.get_default_time());
       }
       breakitem = &tk;
       // tk.print(std::cout);
     } else if (!strcmp(tk.name(), "ws")) {
       pbreak_.GetWhitespaceBreaks(tk.first_child().value(),
                                   tk.attribute("col").as_int(0),
                                   hzone_, hzone_start_, hzone_end_,
                                   &newline, &newline2);
     } else if (!strcmp(tk.name(), "tk")) {
       // std::cout << "!" << tk.attribute("norm").value() << "\n";
       // if (ptk) std::cout << "P:" << ptk->attribute("norm").value() << " - ";
       // std::cout << "L:" << tk.attribute("norm").value() << std::endl;
       pbreakpunc.Clear();
       // Only add breaks if no break is present
       if (!breakitem) {
         // first token
         if (!ptk) {
           if (pbreak_.GetPbreak(tk.attribute("prepunc").value(),
                                 TXPPBREAK_POS_PRE, pbreakpunc)) {
             pbreak = &pbreakpunc;
           } else {
             // Insert default document start break
             pbreak = pbreak_.GetPbreakPre("DEFAULT");
           }
           _insert_break_before(&tk, pbreak);
         } else {
           // Between tokens
           // break caused by punctuation
           // std::cout << "X:" << tk.attribute("prepunc").value() << std::endl;
           pstbreak = pbreak_.GetPbreak(ptk->attribute("pstpunc").value(),
                                        TXPPBREAK_POS_PST, pbreakpunc);
           prebreak = pbreak_.GetPbreak(tk.attribute("prepunc").value(),
                                        TXPPBREAK_POS_PRE, pbreakpunc);
           pbreak = &pbreakpunc;
           if (!prebreak && !pstbreak) {
             // Break caused by whitespace
             if (newline2) {
             pbreak = pbreak_.GetPbreakPst("newlineX2");
             } else if (newline) {
               pbreak = pbreak_.GetPbreakPst("newlineX2");
             } else {
               pbreak = NULL;
             }
           }
           _insert_break_after(ptk, pbreak);
         }
       }
       pretk = (*it).node();
       ptk = &pretk;
       breakitem = NULL;
     }
   }
   // last item
   if (!breakitem && ptk) {
     if (pbreak_.GetPbreak(ptk->attribute("pstpunc").value(),
                           TXPPBREAK_POS_PST, pbreakpunc)) {
       pbreak = &pbreakpunc;
     } else {
       // Insert default document end break
       pbreak = pbreak_.GetPbreakPst("DEFAULT");
     }
     _insert_break_after(ptk, pbreak);
   }
   return true;
 }
Member Data Documentation
hzone_
bool hzone_ private
If true tries distinguish real line breaks from those at page left A hypenation zone (hzone) can then be used to remove phantom line breaks and reappend soft hypenation.
Definition at line 55 of file mod-pauses.h.
Referenced by TxpPauses::Init(), and TxpPauses::ProcessFile().
hzone_end_
int32 hzone_end_ private
Column end for hzone.
Definition at line 59 of file mod-pauses.h.
Referenced by TxpPauses::Init(), and TxpPauses::ProcessFile().
hzone_start_
int32 hzone_start_ private
Column start for hzone.
Definition at line 57 of file mod-pauses.h.
Referenced by TxpPauses::Init(), and TxpPauses::ProcessFile().
pbreak_
TxpPbreak pbreak_ private
Object containing lookup between punctuation and break strength and time.
Definition at line 51 of file mod-pauses.h.
Referenced by TxpPauses::Init(), and TxpPauses::ProcessFile().
The documentation for this class was generated from the following files:
idlaktxp/mod-pauses.h
idlaktxp/mod-pauses.cc