Kaldi: StatisticsPoolingComponentPrecomputedIndexes Class Reference
StatisticsPoolingComponentPrecomputedIndexes Class Reference
#include <nnet-general-component.h>
Public Member Functions
virtual ~StatisticsPoolingComponentPrecomputedIndexes ()
ComponentPrecomputedIndexes * Copy () const
virtual void Write (std::ostream &os, bool binary) const
virtual void Read (std::istream &is, bool binary)
virtual std::string Type () const
Public Member Functions inherited from ComponentPrecomputedIndexes
virtual ~ComponentPrecomputedIndexes ()
Public Attributes
CuArray< Int32Pair > forward_indexes
CuArray< Int32Pair > backward_indexes
Additional Inherited Members
Static Public Member Functions inherited from ComponentPrecomputedIndexes
static ComponentPrecomputedIndexes * ReadNew (std::istream &is, bool binary)
static ComponentPrecomputedIndexes * NewComponentPrecomputedIndexesOfType (const std::string &cpi_type)
Detailed Description
Definition at line 416 of file nnet-general-component.h.
Constructor & Destructor Documentation
~StatisticsPoolingComponentPrecomputedIndexes()
virtual ~StatisticsPoolingComponentPrecomputedIndexes () inline virtual
Definition at line 435 of file nnet-general-component.h.
 { }
Member Function Documentation
Copy()
ComponentPrecomputedIndexes* Copy () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 437 of file nnet-general-component.h.
References DistributeComponent::Read(), and DistributeComponent::Write().
{
     return new StatisticsPoolingComponentPrecomputedIndexes(*this);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Implements ComponentPrecomputedIndexes.
Definition at line 540 of file nnet-general-component.cc.
References kaldi::nnet3::CopyPairVector(), kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), and kaldi::ReadIntegerPairVector().
{
   ExpectOneOrTwoTokens(is, binary,
                        "<StatisticsPoolingComponentPrecomputedIndexes>",
                        "<ForwardIndexes>");
   std::vector<std::pair<int32, int32> > indexes_cpu;
   ReadIntegerPairVector(is, binary, &indexes_cpu);
   CopyPairVector(indexes_cpu, &forward_indexes);
   ExpectToken(is, binary, "<BackwardIndexes>");
   ReadIntegerPairVector(is, binary, &indexes_cpu);
   CopyPairVector(indexes_cpu, &backward_indexes);
   ExpectToken(is, binary, "</StatisticsPoolingComponentPrecomputedIndexes>");
 }
Type()
virtual std::string Type () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 445 of file nnet-general-component.h.
 { return "StatisticsPoolingComponentPrecomputedIndexes"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Implements ComponentPrecomputedIndexes.
Definition at line 528 of file nnet-general-component.cc.
References kaldi::nnet3::CopyPairVector(), kaldi::WriteIntegerPairVector(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<StatisticsPoolingComponentPrecomputedIndexes>");
   WriteToken(os, binary, "<ForwardIndexes>");
   std::vector<std::pair<int32, int32> > indexes_cpu;
   CopyPairVector(forward_indexes, &indexes_cpu);
   WriteIntegerPairVector(os, binary, indexes_cpu);
   WriteToken(os, binary, "<BackwardIndexes>");
   CopyPairVector(backward_indexes, &indexes_cpu);
   WriteIntegerPairVector(os, binary, indexes_cpu);
   WriteToken(os, binary, "</StatisticsPoolingComponentPrecomputedIndexes>");
 }
Member Data Documentation
backward_indexes
CuArray<Int32Pair> backward_indexes
Definition at line 433 of file nnet-general-component.h.
Referenced by StatisticsPoolingComponent::Backprop(), and StatisticsPoolingComponent::PrecomputeIndexes().
forward_indexes
CuArray<Int32Pair> forward_indexes
Definition at line 424 of file nnet-general-component.h.
Referenced by StatisticsPoolingComponent::Backprop(), StatisticsPoolingComponent::PrecomputeIndexes(), and StatisticsPoolingComponent::Propagate().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc