Kaldi: BackpropTruncationComponent Class Reference
BackpropTruncationComponent Class Reference
#include <nnet-general-component.h>
Public Member Functions
BackpropTruncationComponent (int32 dim, BaseFloat scale, BaseFloat clipping_threshold, BaseFloat zeroing_threshold, int32 zeroing_interval, int32 recurrence_interval)
BackpropTruncationComponent ()
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
void Init (int32 dim, BaseFloat scale, BaseFloat clipping_threshold, BaseFloat zeroing_threshold, int32 zeroing_interval, int32 recurrence_interval)
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual Component * Copy () const
Copies component (deep copy).
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual ~BackpropTruncationComponent ()
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Attributes
double num_clipped_
double num_zeroed_
double count_
double count_zeroing_boundaries_
Private Member Functions
BackpropTruncationComponent & operator= (const BackpropTruncationComponent &other)
Private Attributes
int32 dim_
BaseFloat scale_
BaseFloat clipping_threshold_
BaseFloat zeroing_threshold_
int32 zeroing_interval_
int32 recurrence_interval_
std::string debug_info_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 453 of file nnet-general-component.h.
Constructor & Destructor Documentation
BackpropTruncationComponent() [1/2]
BackpropTruncationComponent (int32 dim, BaseFloat scale, BaseFloat clipping_threshold, BaseFloat zeroing_threshold, int32 zeroing_interval, int32 recurrence_interval) inline
Definition at line 455 of file nnet-general-component.h.
References DistributeComponent::Init().
{
     Init(dim, scale, clipping_threshold, zeroing_threshold,
         zeroing_interval, recurrence_interval);}
BackpropTruncationComponent() [2/2]
BackpropTruncationComponent () inline
Definition at line 464 of file nnet-general-component.h.
                                : dim_(0), scale_(1.0), clipping_threshold_(-1),
     zeroing_threshold_(-1), zeroing_interval_(0), recurrence_interval_(0),
     num_clipped_(0), num_zeroed_(0), count_(0), count_zeroing_boundaries_(0) { }
~BackpropTruncationComponent()
virtual ~BackpropTruncationComponent () inline virtual
Definition at line 510 of file nnet-general-component.h.
{
   }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1190 of file nnet-general-component.cc.
References BackpropTruncationComponent::count_, BackpropTruncationComponent::count_zeroing_boundaries_, KALDI_ASSERT, BackpropTruncationComponent::num_clipped_, and BackpropTruncationComponent::num_zeroed_.
{
   const BackpropTruncationComponent *other =
       dynamic_cast<const BackpropTruncationComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   count_ += alpha * other->count_;
   count_zeroing_boundaries_ += alpha * other->count_zeroing_boundaries_;
   num_clipped_ += alpha * other->num_clipped_;
   num_zeroed_ += alpha * other->num_zeroed_;
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 1098 of file nnet-general-component.cc.
References CuMatrixBase< Real >::Add(), CuVectorBase< Real >::AddDiagMat2(), CuMatrixBase< Real >::ApplyHeaviside(), CuMatrixBase< Real >::CopyFromMat(), BackpropTruncationComponent::count_, BackpropTruncationComponent::count_zeroing_boundaries_, KALDI_ASSERT, kaldi::kNoTrans, CuVectorBase< Real >::MulElements(), CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::MulRowsVec(), BackpropTruncationComponent::num_clipped_, BackpropTruncationComponent::num_zeroed_, CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Scale(), CuMatrixBase< Real >::Set(), CuMatrixBase< Real >::Sum(), BackpropTruncationComponentPrecomputedIndexes::zeroing, and BackpropTruncationComponentPrecomputedIndexes::zeroing_sum.
{
   const BackpropTruncationComponentPrecomputedIndexes *indexes =
       dynamic_cast<const BackpropTruncationComponentPrecomputedIndexes*>(
           indexes_in);
   KALDI_ASSERT(indexes->zeroing.Dim() == out_deriv.NumRows());
   // the following statement will do nothing if in_deriv and out_deriv have same
   // memory.
   in_deriv->CopyFromMat(out_deriv);
   if (scale_ != 1.0)
     in_deriv->Scale(scale_);
   BackpropTruncationComponent *to_update =
       dynamic_cast<BackpropTruncationComponent*>(to_update_in);
   // computes clipping_scales
   BaseFloat clipping_threshold =
       (clipping_threshold_ <= 0.0 ? 1.0e+10 : clipping_threshold_);
   // each row in the derivative matrix, which corresponds to one sample in
   // the mini-batch, is scaled to have a max-norm of clipping_threshold_
   CuVector<BaseFloat> clipping_scales(in_deriv->NumRows());
   clipping_scales.AddDiagMat2(pow(clipping_threshold, -2), *in_deriv,
                               kNoTrans, 0.0);
   // now clipping_scales contains the squared (norm of each row divided by
   //  clipping_threshold)
   int32 num_not_scaled;
   clipping_scales.ApplyFloor(1.0, &num_not_scaled);
   // now clipping_scales contains min(1, squared-(norm/clipping_threshold))
   clipping_scales.ApplyPow(-0.5);
   // now clipping_scales contains max(1, clipping_threshold/vector_norm)
   if (to_update != NULL) {
     to_update->num_clipped_ += (clipping_scales.Dim() - num_not_scaled);
     to_update->count_ += clipping_scales.Dim();
   }
   // computes zeroing_scales
   BaseFloat zeroing_threshold =
       (zeroing_threshold_ <= 0.0 ? 1.0e+10 : zeroing_threshold_);
   // zeroing_scales_vec is actually a 1-row matrix.  (the ApplyHeaviside
   // function isn't defined for vectors).
   CuMatrix<BaseFloat> zeroing_scales(1, in_deriv->NumRows());
   CuSubVector<BaseFloat> zeroing_scales_vec(zeroing_scales, 0);
   zeroing_scales_vec.Set(-pow(zeroing_threshold, 2));
   // now zeroing_scales_vec contains -(squared zeroing_threshold)
   zeroing_scales_vec.AddDiagMat2(1.0, *in_deriv, kNoTrans, 1.0);
   // now zeroing_scales_vec contains squared norm of each row -
   // squared zeroing_threshold
   zeroing_scales.ApplyHeaviside();
   // now the element of zeroing_scales_vec is 1.0 if its corresponding
   // sample's norm exceeds zero_threshold, and 0.0 otherwise
   zeroing_scales_vec.MulElements(indexes->zeroing);
   // now the element of zeroing_scales_vec is -1.0 if we want to zero its
   // corresponding sample's gradient, and 0.0 otherwise
   if (to_update != NULL) {
     to_update->num_zeroed_ -= zeroing_scales_vec.Sum(); // since it is negative
     to_update->count_zeroing_boundaries_ += indexes->zeroing_sum;
   }
   zeroing_scales_vec.Add(1.0);
   // now the element of zeroing_scales_vec is 0.0 if we want to zero its
   // corresponding sample's gradient, and 1.0 otherwise
   // combines clipping_scales and zeroing_scales and applies combined_scales
   // to in_deriv all at once
   CuVector<BaseFloat> combined_scales(clipping_scales);
   combined_scales.MulElements(zeroing_scales_vec);
   in_deriv->MulRowsVec(combined_scales);
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 1035 of file nnet-general-component.cc.
References BackpropTruncationComponent::clipping_threshold_, BackpropTruncationComponent::count_, BackpropTruncationComponent::count_zeroing_boundaries_, BackpropTruncationComponent::dim_, BackpropTruncationComponent::num_clipped_, BackpropTruncationComponent::num_zeroed_, BackpropTruncationComponent::recurrence_interval_, BackpropTruncationComponent::scale_, BackpropTruncationComponent::zeroing_interval_, and BackpropTruncationComponent::zeroing_threshold_.
{
   BackpropTruncationComponent *ans = new BackpropTruncationComponent();
   ans->dim_ = dim_;
   ans->scale_ = scale_;
   ans->clipping_threshold_ = clipping_threshold_;
   ans->zeroing_threshold_ = zeroing_threshold_;
   ans->zeroing_interval_ = zeroing_interval_;
   ans->recurrence_interval_ = recurrence_interval_;
   ans->num_clipped_ = num_clipped_;
   ans->num_zeroed_ = num_zeroed_;
   ans->count_ = count_;
   ans->count_zeroing_boundaries_ = count_zeroing_boundaries_;
   return ans;
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 974 of file nnet-general-component.cc.
References StatisticsPoolingComponent::Type().
{
   std::ostringstream stream;
   stream << Type() << ", dim=" << dim_
          << ", scale=" << scale_
          << ", count=" << std::setprecision(3) << count_ << std::setprecision(6)
          << ", recurrence-interval=" << recurrence_interval_
          << ", clipping-threshold=" << clipping_threshold_
          << ", clipped-proportion="
          << (count_ > 0.0 ? num_clipped_ / count_ : 0)
          << ", zeroing-threshold=" << zeroing_threshold_
          << ", zeroing-interval=" << zeroing_interval_
          << ", zeroed-proportion="
          << (count_zeroing_boundaries_ > 0.0 ?
              num_zeroed_ / count_zeroing_boundaries_ : 0)
          << ", count-zeroing-boundaries="
          << static_cast<int32>(count_zeroing_boundaries_);
   return stream.str();
 }
Init()
void Init (int32 dim, BaseFloat scale, BaseFloat clipping_threshold, BaseFloat zeroing_threshold, int32 zeroing_interval, int32 recurrence_interval)
Definition at line 993 of file nnet-general-component.cc.
References KALDI_ASSERT.
{
   KALDI_ASSERT(clipping_threshold >= 0 && zeroing_threshold >= 0 &&
                scale > 0.0 && zeroing_interval > 0 &&
                recurrence_interval > 0 && dim > 0);
   dim_ = dim;
   scale_ = scale;
   clipping_threshold_ = clipping_threshold;
   zeroing_threshold_ = zeroing_threshold;
   zeroing_interval_ = zeroing_interval;
   recurrence_interval_ = recurrence_interval;
   num_clipped_ = 0.0;
   num_zeroed_ = 0.0;
   count_ = 0.0;
   count_zeroing_boundaries_ = 0.0;
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 1013 of file nnet-general-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), KALDI_ERR, StatisticsPoolingComponent::Type(), and ConfigLine::WholeLine().
{
   int32 dim = 0;
   bool ok = cfl->GetValue("dim", &dim);
   BaseFloat scale = 1.0,
       clipping_threshold = 30.0,
       zeroing_threshold = 15.0;
   int32 zeroing_interval = 20, recurrence_interval = 1;
   cfl->GetValue("scale", &scale);
   cfl->GetValue("clipping-threshold", &clipping_threshold);
   cfl->GetValue("zeroing-threshold", &zeroing_threshold);
   cfl->GetValue("zeroing-interval", &zeroing_interval);
   cfl->GetValue("recurrence-interval", &recurrence_interval);
   if (!ok || cfl->HasUnusedValues() ||
       clipping_threshold < 0 || zeroing_threshold < 0 || zeroing_interval < 1 ||
       recurrence_interval < 1 || dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(dim, scale, clipping_threshold, zeroing_threshold,
       zeroing_interval, recurrence_interval);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 468 of file nnet-general-component.h.
 { return dim_; }
operator=()
BackpropTruncationComponent& operator= (const BackpropTruncationComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 469 of file nnet-general-component.h.
References DistributeComponent::Init(), and DistributeComponent::InitFromConfig().
 { return dim_; }
PrecomputeIndexes()
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo & misc_info, const std::vector< Index > & input_indexes, const std::vector< Index > & output_indexes, bool need_backprop) const virtual
This function must return NULL for simple Components.
Returns a pointer to a class that may contain some precomputed component-specific and computation-specific indexes to be in used in the Propagate and Backprop functions.
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. misc_info may not even ever be used here. We will add members to misc_info as needed.
[in] input_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the in/in_value/in_deriv matrices given to Propagate and Backprop will mean.
[in] output_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the out/out_value/out_deriv matrices given to Propagate and Backprop will mean.
[in] need_backprop True if we might need to do backprop with this component, so that if any different indexes are needed for backprop then those should be computed too.
Returns
Returns a child-class of class ComponentPrecomputedIndexes, or NULL if this component for does not need to precompute any indexes (e.g. if it is a simple component and does not care about indexes).
Reimplemented from Component.
Definition at line 1052 of file nnet-general-component.cc.
References kaldi::DivideRoundingDown(), rnnlm::i, KALDI_ASSERT, VectorBase< Real >::Sum(), BackpropTruncationComponentPrecomputedIndexes::zeroing, and BackpropTruncationComponentPrecomputedIndexes::zeroing_sum.
{
   int32 num_input_indexes = input_indexes.size(),
       num_output_indexes = output_indexes.size();
   KALDI_ASSERT(num_input_indexes == num_output_indexes);
   Vector<BaseFloat> zeroing_cpu(num_output_indexes);
   for (int32 i = 0; i < num_output_indexes; i++) {
     const int32 output_n = output_indexes[i].n;
     const int32 output_t = output_indexes[i].t;
     // checks if output_t crosses a boundary that is a multiple of
     // zeroing_interval_. Note that frame (output_t - recurrence_interval_) is
     // right before frame output_t in RNNs. If the range
     // [output_t - recurrence_interval_, output_t] contains a multiple of
     // zeroing_interval_, then frame output_t crosses the boundary.
     // output_n is used to shift where we put the boundary, so that
     // we don't always zero out gradients on frame 0. It will help avoid
     // learning utterance-boundary effects.
     if (DivideRoundingDown(output_t - output_n, zeroing_interval_) !=
         DivideRoundingDown(output_t - recurrence_interval_ - output_n,
         zeroing_interval_))
       zeroing_cpu(i) = -1.0;
   }
   BackpropTruncationComponentPrecomputedIndexes *ans = new
       BackpropTruncationComponentPrecomputedIndexes();
   ans->zeroing = zeroing_cpu;
   ans->zeroing_sum = -zeroing_cpu.Sum();
   return ans;
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 1087 of file nnet-general-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), and CuMatrixBase< Real >::Scale().
{
   out->CopyFromMat(in);
   if (scale_ != 1.0)
     out->Scale(scale_);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 477 of file nnet-general-component.h.
References Component::Add(), DistributeComponent::Backprop(), DistributeComponent::Copy(), Component::Info(), kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kPropagateInPlace, DistributeComponent::PrecomputeIndexes(), DistributeComponent::Propagate(), DistributeComponent::Read(), Component::Scale(), DistributeComponent::Write(), and Component::ZeroStats().
{
     return kPropagateInPlace|kBackpropInPlace;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 891 of file nnet-general-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), KALDI_ASSERT, kaldi::ReadBasicType(), and kaldi::ReadToken().
{
   // might not see the "<NaturalGradientAffineComponent>" part because
   // of how ReadNew() works.
   ExpectOneOrTwoTokens(is, binary, "<BackpropTruncationComponent>",
                        "<Dim>");
   ReadBasicType(is, binary, &dim_);
   std::string tok;
   ReadToken(is, binary, &tok);
   if (tok == "<Scale>") {
     ReadBasicType(is, binary, &scale_);
     ReadToken(is, binary, &tok);
   } else {
     scale_ = 1.0;
   }
   KALDI_ASSERT(tok == "<ClippingThreshold>");
   ReadBasicType(is, binary, &clipping_threshold_);
   ExpectToken(is, binary, "<ZeroingThreshold>");
   ReadBasicType(is, binary, &zeroing_threshold_);
   ExpectToken(is, binary, "<ZeroingInterval>");
   ReadBasicType(is, binary, &zeroing_interval_);
   ExpectToken(is, binary, "<RecurrenceInterval>");
   ReadBasicType(is, binary, &recurrence_interval_);
   ExpectToken(is, binary, "<NumElementsClipped>");
   ReadBasicType(is, binary, &num_clipped_);
   ExpectToken(is, binary, "<NumElementsZeroed>");
   ReadBasicType(is, binary, &num_zeroed_);
   ExpectToken(is, binary, "<NumElementsProcessed>");
   ReadBasicType(is, binary, &count_);
   ExpectToken(is, binary, "<NumZeroingBoundaries>");
   ReadBasicType(is, binary, &count_zeroing_boundaries_);
   ExpectToken(is, binary, "</BackpropTruncationComponent>");
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1182 of file nnet-general-component.cc.
{
   count_ *= scale;
   count_zeroing_boundaries_ *= scale;
   num_clipped_ *= scale;
   num_zeroed_ *= scale;
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 475 of file nnet-general-component.h.
 { return "BackpropTruncationComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 925 of file nnet-general-component.cc.
References kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<BackpropTruncationComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<Scale>");
   WriteBasicType(os, binary, scale_);
   WriteToken(os, binary, "<ClippingThreshold>");
   WriteBasicType(os, binary, clipping_threshold_);
   WriteToken(os, binary, "<ZeroingThreshold>");
   WriteBasicType(os, binary, zeroing_threshold_);
   WriteToken(os, binary, "<ZeroingInterval>");
   WriteBasicType(os, binary, zeroing_interval_);
   WriteToken(os, binary, "<RecurrenceInterval>");
   WriteBasicType(os, binary, recurrence_interval_);
   WriteToken(os, binary, "<NumElementsClipped>");
   WriteBasicType(os, binary, num_clipped_);
   WriteToken(os, binary, "<NumElementsZeroed>");
   WriteBasicType(os, binary, num_zeroed_);
   WriteToken(os, binary, "<NumElementsProcessed>");
   WriteBasicType(os, binary, count_);
   WriteToken(os, binary, "<NumZeroingBoundaries>");
   WriteBasicType(os, binary, count_zeroing_boundaries_);
   WriteToken(os, binary, "</BackpropTruncationComponent>");
 }
ZeroStats()
void ZeroStats () virtual
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Other components that store other types of statistics (e.g. regarding gradient clipping) should implement ZeroStats() also.
Reimplemented from Component.
Definition at line 1174 of file nnet-general-component.cc.
{
   count_ = 0.0;
   count_zeroing_boundaries_ = 0.0;
   num_clipped_ = 0.0;
   num_zeroed_ = 0.0;
 }
Member Data Documentation
clipping_threshold_
BaseFloat clipping_threshold_ private
Definition at line 523 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Copy().
count_
double count_ protected
Definition at line 549 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Add(), BackpropTruncationComponent::Backprop(), and BackpropTruncationComponent::Copy().
count_zeroing_boundaries_
double count_zeroing_boundaries_ protected
Definition at line 550 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Add(), BackpropTruncationComponent::Backprop(), and BackpropTruncationComponent::Copy().
debug_info_
std::string debug_info_ private
Definition at line 539 of file nnet-general-component.h.
dim_
int32 dim_ private
Definition at line 514 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Copy().
num_clipped_
double num_clipped_ protected
Definition at line 547 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Add(), BackpropTruncationComponent::Backprop(), and BackpropTruncationComponent::Copy().
num_zeroed_
double num_zeroed_ protected
Definition at line 548 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Add(), BackpropTruncationComponent::Backprop(), and BackpropTruncationComponent::Copy().
recurrence_interval_
int32 recurrence_interval_ private
Definition at line 535 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Copy().
scale_
BaseFloat scale_ private
Definition at line 520 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Copy().
zeroing_interval_
int32 zeroing_interval_ private
Definition at line 530 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Copy().
zeroing_threshold_
BaseFloat zeroing_threshold_ private
Definition at line 526 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Copy().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc