Kaldi: SequentialTableReaderImplBase< Holder > Class Template Reference
SequentialTableReaderImplBase< Holder > Class Template Reference abstract
"Implementation classes for Table types"
#include <kaldi-table-inl.h>
Public Types
typedef Holder::T T
Public Member Functions
virtual bool Open (const std::string &rxfilename)=0
virtual bool Done () const =0
virtual bool IsOpen () const =0
virtual std::string Key ()=0
virtual T & Value ()=0
virtual void FreeCurrent ()=0
virtual void Next ()=0
virtual bool Close ()=0
virtual void SwapHolder (Holder *other_holder)=0
SequentialTableReaderImplBase ()
virtual ~SequentialTableReaderImplBase ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (SequentialTableReaderImplBase)
Detailed Description
template<class Holder>
class kaldi::SequentialTableReaderImplBase< Holder >
Definition at line 44 of file kaldi-table-inl.h.
Member Typedef Documentation
T
typedef Holder::T T
Definition at line 46 of file kaldi-table-inl.h.
Constructor & Destructor Documentation
SequentialTableReaderImplBase()
SequentialTableReaderImplBase () inline
Definition at line 78 of file kaldi-table-inl.h.
 { }
~SequentialTableReaderImplBase()
virtual ~SequentialTableReaderImplBase () inline virtual
Definition at line 79 of file kaldi-table-inl.h.
References SequentialTableReaderImplBase< Holder >::KALDI_DISALLOW_COPY_AND_ASSIGN().
 { }  // throws.
Member Function Documentation
Close()
virtual bool Close () pure virtual
Implemented in SequentialTableReaderBackgroundImpl< Holder >, SequentialTableReaderArchiveImpl< Holder >, and SequentialTableReaderScriptImpl< Holder >.
Referenced by SequentialTableReaderScriptImpl< Holder >::Open(), SequentialTableReaderArchiveImpl< Holder >::Open(), SequentialTableReaderArchiveImpl< Holder >::~SequentialTableReaderArchiveImpl(), SequentialTableReaderBackgroundImpl< Holder >::~SequentialTableReaderBackgroundImpl(), and SequentialTableReaderScriptImpl< Holder >::~SequentialTableReaderScriptImpl().
Done()
virtual bool Done () const pure virtual
Implemented in SequentialTableReaderBackgroundImpl< Holder >, SequentialTableReaderArchiveImpl< Holder >, and SequentialTableReaderScriptImpl< Holder >.
Referenced by SequentialTableReaderScriptImpl< Holder >::Next().
FreeCurrent()
virtual void FreeCurrent () pure virtual
Implemented in SequentialTableReaderBackgroundImpl< Holder >, SequentialTableReaderArchiveImpl< Holder >, and SequentialTableReaderScriptImpl< Holder >.
IsOpen()
virtual bool IsOpen () const pure virtual
Implemented in SequentialTableReaderBackgroundImpl< Holder >, SequentialTableReaderArchiveImpl< Holder >, and SequentialTableReaderScriptImpl< Holder >.
Referenced by SequentialTableReaderScriptImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::~SequentialTableReaderArchiveImpl(), and SequentialTableReaderScriptImpl< Holder >::~SequentialTableReaderScriptImpl().
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (SequentialTableReaderImplBase< Holder >) private
Referenced by SequentialTableReaderImplBase< Holder >::~SequentialTableReaderImplBase().
Key()
virtual std::string Key () pure virtual
Implemented in SequentialTableReaderBackgroundImpl< Holder >, SequentialTableReaderArchiveImpl< Holder >, and SequentialTableReaderScriptImpl< Holder >.
Next()
virtual void Next () pure virtual
Implemented in SequentialTableReaderBackgroundImpl< Holder >, SequentialTableReaderArchiveImpl< Holder >, and SequentialTableReaderScriptImpl< Holder >.
Referenced by SequentialTableReaderScriptImpl< Holder >::Open(), SequentialTableReaderArchiveImpl< Holder >::Open(), and SequentialTableReaderBackgroundImpl< Holder >::Open().
Open()
virtual bool Open (const std::string & rxfilename) pure virtual
Implemented in SequentialTableReaderBackgroundImpl< Holder >, SequentialTableReaderArchiveImpl< Holder >, and SequentialTableReaderScriptImpl< Holder >.
SwapHolder()
virtual void SwapHolder (Holder * other_holder) pure virtual
Implemented in SequentialTableReaderBackgroundImpl< Holder >, SequentialTableReaderArchiveImpl< Holder >, and SequentialTableReaderScriptImpl< Holder >.
Value()
virtual T& Value () pure virtual
Implemented in SequentialTableReaderBackgroundImpl< Holder >, SequentialTableReaderArchiveImpl< Holder >, and SequentialTableReaderScriptImpl< Holder >.
Referenced by SequentialTableReaderScriptImpl< Holder >::SwapHolder(), and SequentialTableReaderArchiveImpl< Holder >::SwapHolder().
The documentation for this class was generated from the following file:
util/kaldi-table-inl.h