Kaldi: TxpPhone Class Reference
TxpPhone Class Reference
Part of speech tagger see /ref idlaktxp_pos.
#include <txpphone.h>
Public Member Functions
TxpPhone ()
~TxpPhone ()
void Init (const TxpParseOptions &opts, const std::string &name)
bool Parse (const std::string &tpdb)
const TxpPhoneDescr * GetPhone (const char *phone_name)
Return the part of speech for word current with previous context POS prev.
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
virtual void EndElement (const char *name)
Inherited class for bespoke end element handling.
virtual void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
virtual void StartCData ()
Inherited class for bespoke start cdata handling.
virtual void EndCData ()
Inherited class for bespoke start cdata handling.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
Private Attributes
PhoneMap phonemes_
Map of phonemes, can be searched by name, i.e. the phoneme itself.
std::string phon_name_
name of currently parsed phoneme
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
Part of speech tagger see /ref idlaktxp_pos.
Definition at line 44 of file txpphone.h.
Constructor & Destructor Documentation
TxpPhone()
TxpPhone () inline explicit
Definition at line 46 of file txpphone.h.
 {}
~TxpPhone()
~TxpPhone () inline
Definition at line 47 of file txpphone.h.
 {}
Member Function Documentation
GetPhone()
const TxpPhoneDescr * GetPhone (const char * phone_name)
Return the part of speech for word current with previous context POS prev.
Definition at line 34 of file txpphone.cc.
References TxpPhone::phonemes_.
Referenced by TxpPhone::Init(), and TxpPronounce::Process().
{
   PhoneMap::iterator phone_lkp;
   phone_lkp = phonemes_.find(std::string(name));
   if (phone_lkp != phonemes_.end()) return &(phone_lkp->second);
   return NULL;
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & name) inline
Definition at line 48 of file txpphone.h.
References TxpPhone::GetPhone(), TxpXmlData::Init(), TxpPhone::Parse(), and TxpPhone::StartElement().
Referenced by TxpPronounce::Init().
{
     TxpXmlData::Init(opts, "phone", name);
   }
Parse()
bool Parse (const std::string & tpdb)
Definition at line 26 of file txpphone.cc.
References KALDI_WARN, and TxpXmlData::Parse().
Referenced by TxpPronounce::Init(), and TxpPhone::Init().
{
   bool r;
   r = TxpXmlData::Parse(tpdb);
   if (!r)
     KALDI_WARN << "Error reading part of phoneme file: " << tpdb;
   return r;
 }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 41 of file txpphone.cc.
References TxpPhoneDescr::ipa, TxpPhoneDescr::name, TxpPhone::phon_name_, TxpPhone::phonemes_, TxpPhoneDescr::pron_example, TxpXmlData::SetAttribute(), and TxpPhoneDescr::word_example.
Referenced by TxpPhone::Init().
{
   TxpPhoneDescr p_descr;
   if (!strcmp(name, "phone")) {
     SetAttribute("name", atts, &phon_name_);
   } else if (!strcmp(name, "description")) {
     p_descr.name = phon_name_;
     SetAttribute("word_example", atts, &(p_descr.word_example));
     SetAttribute("pron_example", atts, &(p_descr.pron_example));
     SetAttribute("ipa", atts, &(p_descr.ipa));
     phonemes_.insert(PhoneItem(phon_name_, p_descr));
   }
 }
Member Data Documentation
phon_name_
std::string phon_name_ private
name of currently parsed phoneme
Definition at line 61 of file txpphone.h.
Referenced by TxpPhone::StartElement().
phonemes_
PhoneMap phonemes_ private
Map of phonemes, can be searched by name, i.e. the phoneme itself.
Definition at line 59 of file txpphone.h.
Referenced by TxpPhone::GetPhone(), and TxpPhone::StartElement().
The documentation for this class was generated from the following files:
idlaktxp/txpphone.h
idlaktxp/txpphone.cc