Kaldi: TxpTokenise Class Reference
TxpTokenise Class Reference
Tokenise input text into tokens and whitespace Tokenisation.
#include <mod-tokenise.h>
Public Member Functions
TxpTokenise ()
~TxpTokenise ()
bool Init (const TxpParseOptions &opts)
Load voice data.
bool Process (pugi::xml_document *input)
Process the XML, modifying the XML to reflect linguistic information.
Public Member Functions inherited from TxpModule
TxpModule (const std::string &name)
Construct module, also loads tpdb modules in specific instances.
virtual ~TxpModule ()
const std::string GetConfigValue (const std::string &key)
Return a configuration value for this module as a string (rendundant)
const char * GetOptValue (const char *key)
Return an option value for this module as a string.
bool GetConfigValueBool (const std::string &key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
bool GetOptValueBool (const char *key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
const std::string & GetName () const
Get the name of the module.
pugi::xml_node GetHeader (pugi::xml_document *input)
Gets or adds a module header to txpheader.
Private Member Functions
int32 SetPuncCaseInfo (std::string *tkin, pugi::xml_node *tk)
Analyses the characters and sets flags giving case, foriegn charcater info.
Private Attributes
TxpTrules trules_
A normalisation rule database used to decide case etc.
TxpAbbrev abbrev_
Abbreviation data.
Additional Inherited Members
Protected Attributes inherited from TxpModule
const TxpParseOptions * opts_
Options structure for the module.
std::string tpdb_
Directory for text processing database (tpdb) files used by txpxmldata objectys in the module.
Detailed Description
Tokenise input text into tokens and whitespace Tokenisation.
Definition at line 35 of file mod-tokenise.h.
Constructor & Destructor Documentation
TxpTokenise()
TxpTokenise () explicit
Definition at line 23 of file mod-tokenise.cc.
 : TxpModule("tokenise") {}
~TxpTokenise()
~TxpTokenise () inline
Definition at line 38 of file mod-tokenise.h.
References TxpTokenise::Init(), TxpTokenise::Process(), and TxpTokenise::SetPuncCaseInfo().
 {}
Member Function Documentation
Init()
bool Init (const TxpParseOptions & opts) virtual
Load voice data.
Reimplemented from TxpModule.
Definition at line 25 of file mod-tokenise.cc.
References TxpTokenise::abbrev_, TxpModule::GetName(), TxpModule::GetOptValue(), TxpParseOptions::GetTpdb(), TxpParseOptions::GetValue(), TxpAbbrev::Init(), TxpTrules::Init(), TxpModule::opts_, TxpAbbrev::Parse(), TxpTrules::Parse(), TxpModule::tpdb_, and TxpTokenise::trules_.
Referenced by main(), and TxpTokenise::~TxpTokenise().
{
   opts_ = &opts;
   tpdb_ = opts.GetTpdb();
   trules_.Init(opts, std::string(opts_->GetValue(GetName().c_str(), "arch")));
   abbrev_.Init(opts, std::string(GetOptValue("arch")));
   return trules_.Parse(tpdb_) && abbrev_.Parse(tpdb_);
 }
Process()
bool Process (pugi::xml_document * input) virtual
Process the XML, modifying the XML to reflect linguistic information.
check for full token matches without partial punctuation i.e. :-) but not (US)
Reimplemented from TxpModule.
Definition at line 33 of file mod-tokenise.cc.
References TxpTokenise::abbrev_, TxpTrules::ConsumeWhitespaceToken(), TxpAbbrevInfo::expansions, rnnlm::i, TxpAbbrevInfo::lexentries, TxpAbbrev::LookupAbbrev(), rnnlm::n, TxpTrules::ReplaceUtf8Punc(), TxpTokenise::SetPuncCaseInfo(), and TxpTokenise::trules_.
Referenced by main(), and TxpTokenise::~TxpTokenise().
{
   const char* p;
   int32 n = 0;
   int32 offset, col = 0;
   std::string token, wspace, tmp;
   pugi::xml_node tkroot, tk, tkcopy, ws, ntxt, lex;
   TxpAbbrevInfo * abbrev_info;
   // all text nodes are tokenised
   pugi::xpath_node_set text =
       input->document_element().select_nodes("//text()");
   // iterate through text nodes
   text.sort();
   for (pugi::xpath_node_set::const_iterator it = text.begin();
        it != text.end();
        ++it) {
     pugi::xml_node node = (*it).node();
     p = node.value();
     while (*p) {
       // break off tokens and spacing and add as an element
       p = trules_.ConsumeWhitespaceToken(p, &token, &wspace);
       if (token.length()) {
         col += token.length();
         tkroot = tk = node.parent().insert_child_before("tk", node);
         ntxt = tk.append_child(pugi::node_pcdata);
         ntxt.set_value(token.c_str());
         n += 1;
         trules_.ReplaceUtf8Punc(token, &tmp);
         abbrev_info = abbrev_.LookupAbbrev(token.c_str());
         if (abbrev_info) {
           for(int32 i = 0; i < abbrev_info->expansions.size(); i++) {
             if (!i) {
               tk.append_attribute("tknorm");
               tk.attribute("tknorm").set_value(abbrev_info->expansions[0].c_str());
               if (!abbrev_info->lexentries[0].empty()) {
                 lex = tk.parent().insert_child_after("lex", tk);
                 lex.append_attribute("type").set_value(abbrev_info->lexentries[0].c_str());
                 tkcopy = lex.append_copy(tk);
                 tk.parent().remove_child(tk);
                 tk = tkcopy;
               }
             }
             else {
               if  (!abbrev_info->lexentries[i].empty()) {
                 lex = tk.parent().insert_child_after("lex", tk);
                 lex.append_attribute("type").set_value(abbrev_info->lexentries[i].c_str());
                 tk = lex.append_child("tk");
                 tk.append_attribute("tknorm").set_value(abbrev_info->expansions[i].c_str());
                 tk = lex; //so we add new tokens after the lex tag not inside it
               }
               else {
                 tk = tk.parent().insert_child_after("tk", tk);
                 tk.append_attribute("tknorm").set_value(abbrev_info->expansions[i].c_str());
               }
             }
           }
         }
         // if no full match of an abbreviation unpack punctuation
         else {
           SetPuncCaseInfo(&tmp, &tk);
         }
       }
       if (wspace.length()) {
         if (token.length())
           ws = tk.parent().insert_child_after("ws", tk);
         else
           ws = node.parent().insert_child_before("ws", node);
         ntxt = ws.append_child(pugi::node_pcdata);
         ntxt.set_value(wspace.c_str());
         // Set column position for carriage returns and newlines
         // Used to decide on soft hyphenation and phrasing
         offset = wspace.find("\n");
         if (offset == std::string::npos) offset = wspace.find("\r");
         if (offset != std::string::npos) {
           std::stringstream sstream;
           sstream << col + offset;
           ws.append_attribute("col").set_value(sstream.str().c_str());
           col = wspace.length() - offset;
         } else {
           col += wspace.length();
         }
       }
     }
     // Delete original text node
     node.parent().remove_child(node);
   }
   return true;
 }
SetPuncCaseInfo()
int32 SetPuncCaseInfo (std::string * tkin, pugi::xml_node * tk) private
Analyses the characters and sets flags giving case, foriegn charcater info.
Definition at line 124 of file mod-tokenise.cc.
References TxpTokenise::abbrev_, TxpTrulesCaseInfo::capitalised, TxpAbbrev::CheckPrePunc(), TxpAbbrev::CheckPstPunc(), TxpTrules::ConsumePunc(), TxpTrules::ConsumeToken(), TxpAbbrevInfo::expansions, TxpTrulesCaseInfo::foreign, rnnlm::i, TxpAbbrevInfo::lexentries, TxpAbbrev::LookupAbbrev(), TxpTrulesCaseInfo::lowercase, rnnlm::n, TxpTrules::NormCaseCharacter(), TxpTrulesCaseInfo::symbols, TxpTokenise::trules_, and TxpTrulesCaseInfo::uppercase.
Referenced by TxpTokenise::Process(), and TxpTokenise::~TxpTokenise().
{
   const char* p;
   TxpTrulesCaseInfo caseinfo;
   pugi::xml_node node, lex, tkcopy;
   int32 n = 0;
   std::string token;
   std::string prepunc;
   std::string pstpunc;
   TxpAbbrevInfo * abbrev_info;
   p = tkin->c_str();
   while (*p) {
     p = trules_.ConsumePunc(p, &prepunc);
     p = trules_.ConsumeToken(p, &token);
     p = trules_.ConsumePunc(p, &pstpunc);
     if (n) {
       *tk = tk->parent().insert_child_after("tk", *tk);
     }
     // check to see if there is an abbreviation that matches the token and
     // completely or partially matches the punctuation
     abbrev_info = abbrev_.LookupAbbrev(token.c_str(), prepunc.c_str(), pstpunc.c_str());
     if (abbrev_info) {
       // trim punctuation as appropriate
       prepunc = prepunc.substr(0, prepunc.size() - abbrev_.CheckPrePunc(prepunc.c_str(), abbrev_info));
       pstpunc = pstpunc.substr(abbrev_.CheckPstPunc(pstpunc.c_str(), abbrev_info),
                                                     pstpunc.size() - abbrev_.CheckPstPunc(pstpunc.c_str(),
                                                                                           abbrev_info));
       for(int32 i = 0; i < abbrev_info->expansions.size(); i++) {
         if (!i) {
           tk->append_attribute("tknorm");
           tk->attribute("tknorm").set_value(abbrev_info->expansions[0].c_str());
           if (!abbrev_info->lexentries[0].empty()) {
             lex = tk->parent().insert_child_after("lex", *tk);
             lex.append_attribute("type").set_value(abbrev_info->lexentries[0].c_str());
             tkcopy = lex.append_copy(*tk);
             tk->parent().remove_child(*tk);
             *tk = tkcopy;
           }
           if (prepunc.length()) {
             tk->append_attribute("prepunc");
             tk->attribute("prepunc").set_value(prepunc.c_str());
           }
         }
         else {
           if  (!abbrev_info->lexentries[i].empty()) {
             lex = tk->parent().insert_child_after("lex", *tk);
             lex.append_attribute("type").set_value(abbrev_info->lexentries[i].c_str());
             *tk = lex.append_child("tk");
             tk->append_attribute("tknorm").set_value(abbrev_info->expansions[i].c_str());
             *tk = lex;
           }
           else {
             *tk = tk->parent().insert_child_after("tk", *tk);
             tk->append_attribute("tknorm").set_value(abbrev_info->expansions[i].c_str());
           }
         }
       }
       if (pstpunc.length()) {
         tk->append_attribute("pstpunc");
         tk->attribute("pstpunc").set_value(pstpunc.c_str());
       }
     }
     else {
       if (prepunc.length()) {
         tk->append_attribute("prepunc");
         tk->attribute("prepunc").set_value(prepunc.c_str());
       }
       if (token.length()) {
         tk->append_attribute("tknorm");
         trules_.NormCaseCharacter(&token, caseinfo);
         tk->attribute("tknorm").set_value(token.c_str());
       }
       if (pstpunc.length()) {
         tk->append_attribute("pstpunc");
         tk->attribute("pstpunc").set_value(pstpunc.c_str());
       }
       if (caseinfo.lowercase) tk->append_attribute("lc").set_value("true");
       if (caseinfo.uppercase) tk->append_attribute("uc").set_value("true");
       if (caseinfo.foreign) tk->append_attribute("foreign").set_value("true");
       if (caseinfo.symbols) tk->append_attribute("symbols").set_value("true");
       if (caseinfo.capitalised) tk->append_attribute("caps").set_value("true");
     }
     n++;
   }
   return true;
 }
Member Data Documentation
abbrev_
TxpAbbrev abbrev_ private
Abbreviation data.
This overides normalisation by directly replacing matching tokens with normalised results i.e. Dr. -> doctor
Definition at line 53 of file mod-tokenise.h.
Referenced by TxpTokenise::Init(), TxpTokenise::Process(), and TxpTokenise::SetPuncCaseInfo().
trules_
TxpTrules trules_ private
A normalisation rule database used to decide case etc.
Currently this data will be loaded muliple times across multiple modules
Definition at line 49 of file mod-tokenise.h.
Referenced by TxpTokenise::Init(), TxpTokenise::Process(), and TxpTokenise::SetPuncCaseInfo().
The documentation for this class was generated from the following files:
idlaktxp/mod-tokenise.h
idlaktxp/mod-tokenise.cc