Kaldi: AmNnet Class Reference
AmNnet Class Reference
#include <am-nnet.h>
Public Member Functions
AmNnet ()
AmNnet (const AmNnet &other)
AmNnet (const Nnet &nnet)
void Init (std::istream &config_is)
Initialize the neural network based acoustic model from a config file.
void Init (const Nnet &nnet)
Initialize from a neural network that's already been set up.
int32 NumPdfs () const
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
const Nnet & GetNnet () const
Nnet & GetNnet ()
void SetPriors (const VectorBase< BaseFloat > &priors)
const VectorBase< BaseFloat > & Priors () const
std::string Info () const
void ResizeOutputLayer (int32 new_num_pdfs)
This function is used when doing transfer learning to a new system.
Private Member Functions
const AmNnet & operator= (const AmNnet &other)
Private Attributes
Nnet nnet_
Vector< BaseFloat > priors_
Detailed Description
Definition at line 38 of file am-nnet.h.
Constructor & Destructor Documentation
AmNnet() [1/3]
AmNnet () inline
Definition at line 40 of file am-nnet.h.
 { }
AmNnet() [2/3]
AmNnet (const AmNnet & other) inline
Definition at line 42 of file am-nnet.h.
 : nnet_(other.nnet_), priors_(other.priors_) { }
AmNnet() [3/3]
AmNnet (const Nnet & nnet) inline explicit
Definition at line 44 of file am-nnet.h.
References AmNnet::Init().
 : nnet_(nnet) { }
Member Function Documentation
GetNnet() [1/2]
const Nnet& GetNnet () const inline
Definition at line 61 of file am-nnet.h.
References AmNnet::nnet_.
Referenced by NnetDiscriminativeUpdater::Backprop(), DecodableNnet2Online::ComputeForFrame(), DecodableAmNnet::DecodableAmNnet(), NnetDiscriminativeUpdater::GetInputFeatures(), NnetDiscriminativeUpdater::LatticeComputations(), main(), kaldi::nnet2::NnetDiscriminativeUpdateParallel(), NnetDiscriminativeUpdater::NnetDiscriminativeUpdater(), and NnetDiscriminativeUpdater::Propagate().
 { return nnet_; }
GetNnet() [2/2]
Nnet& GetNnet () inline
Definition at line 63 of file am-nnet.h.
References AmNnet::nnet_, and AmNnet::SetPriors().
 { return nnet_; }
Info()
std::string Info () const
Definition at line 57 of file am-nnet.cc.
References Nnet::Info(), AmNnet::nnet_, and AmNnet::priors_.
Referenced by main(), and AmNnet::Priors().
{
   std::ostringstream ostr;
   ostr << "prior dimension: " << priors_.Dim();
   if (priors_.Dim() != 0) {
     ostr << ", prior sum: " << priors_.Sum() << ", prior min: " << priors_.Min()
          << "\n";
   }
   return nnet_.Info() + ostr.str();
 }
Init() [1/2]
void Init (std::istream & config_is)
Initialize the neural network based acoustic model from a config file.
At this point the priors won't be initialized; you'd have to do SetPriors for that.
Definition at line 26 of file am-nnet.cc.
References Nnet::Init(), and AmNnet::nnet_.
Referenced by AmNnet::AmNnet(), and main().
{
   nnet_.Init(config_is);
 }
Init() [2/2]
void Init (const Nnet & nnet)
Initialize from a neural network that's already been set up.
Again, the priors will be empty at this point.
Definition at line 67 of file am-nnet.cc.
References KALDI_WARN, AmNnet::nnet_, Nnet::OutputDim(), and AmNnet::priors_.
{
   nnet_ = nnet;
   if (priors_.Dim() != 0 && priors_.Dim() != nnet.OutputDim()) {
     KALDI_WARN << "Initializing neural net: prior dimension mismatch, "
                << "discarding old priors.";
     priors_.Resize(0);
   }
 }
NumPdfs()
int32 NumPdfs () const inline
Definition at line 55 of file am-nnet.h.
References AmNnet::nnet_, Nnet::OutputDim(), AmNnet::Read(), and AmNnet::Write().
Referenced by main(), kaldi::nnet2::SetPriors(), and AmNnet::SetPriors().
 { return nnet_.OutputDim(); }
operator=()
const AmNnet& operator= (const AmNnet & other) private
Referenced by AmNnet::Priors().
Priors()
const VectorBase<BaseFloat>& Priors () const inline
Definition at line 67 of file am-nnet.h.
References AmNnet::Info(), AmNnet::operator=(), AmNnet::priors_, and AmNnet::ResizeOutputLayer().
Referenced by DecodableAmNnet::DecodableAmNnet(), DecodableNnet2Online::DecodableNnet2Online(), NnetDiscriminativeUpdater::LatticeComputations(), and main().
 { return priors_; }
Read()
void Read (std::istream & is, bool binary)
Definition at line 39 of file am-nnet.cc.
References AmNnet::nnet_, AmNnet::priors_, and Nnet::Read().
Referenced by main(), AmNnet::NumPdfs(), and kaldi::nnet2::UnitTestAmNnet().
{
   nnet_.Read(is, binary);
   priors_.Read(is, binary);
 }
ResizeOutputLayer()
void ResizeOutputLayer (int32 new_num_pdfs)
This function is used when doing transfer learning to a new system.
It will set the priors to be all the same.
Definition at line 76 of file am-nnet.cc.
References AmNnet::nnet_, AmNnet::priors_, and Nnet::ResizeOutputLayer().
Referenced by main(), and AmNnet::Priors().
{
   nnet_.ResizeOutputLayer(new_num_pdfs);
   priors_.Resize(new_num_pdfs);
   priors_.Set(1.0 / new_num_pdfs);
 }
SetPriors()
void SetPriors (const VectorBase< BaseFloat > & priors)
Definition at line 44 of file am-nnet.cc.
References KALDI_ERR, KALDI_WARN, kaldi::kCopyData, AmNnet::NumPdfs(), and AmNnet::priors_.
Referenced by AmNnet::GetNnet(), main(), kaldi::nnet2::SetPriors(), kaldi::nnet2::UnitTestAmNnet(), and kaldi::nnet2::UnitTestNnetDecodable().
{
   priors_ = priors;
   if (priors_.Dim() > NumPdfs())
     KALDI_ERR << "Dimension of priors cannot exceed number of pdfs.";
   if (priors_.Dim() > 0 && priors_.Dim() < NumPdfs()) {
     KALDI_WARN << "Dimension of priors is " << priors_.Dim() << " < "
                << NumPdfs() << ": extending with zeros, in case you had "
                << "unseen pdf's, but this possibly indicates a serious problem.";
     priors_.Resize(NumPdfs(), kCopyData);
   }
 }
Write()
void Write (std::ostream & os, bool binary) const
Definition at line 31 of file am-nnet.cc.
References AmNnet::nnet_, AmNnet::priors_, and Nnet::Write().
Referenced by main(), AmNnet::NumPdfs(), and kaldi::nnet2::UnitTestAmNnet().
{
   // We don't write any header or footer like <AmNnet> and </AmNnet> -- we just
   // write the neural net and then the priors.  Who knows, there might be some
   // situation where we want to just read the neural net.
   nnet_.Write(os, binary);
   priors_.Write(os, binary);
 }
Member Data Documentation
nnet_
Nnet nnet_ private
Definition at line 77 of file am-nnet.h.
Referenced by AmNnet::GetNnet(), AmNnet::Info(), AmNnet::Init(), AmNnet::NumPdfs(), AmNnet::Read(), AmNnet::ResizeOutputLayer(), and AmNnet::Write().
priors_
Vector<BaseFloat> priors_ private
Definition at line 78 of file am-nnet.h.
Referenced by AmNnet::Info(), AmNnet::Init(), AmNnet::Priors(), AmNnet::Read(), AmNnet::ResizeOutputLayer(), AmNnet::SetPriors(), and AmNnet::Write().
The documentation for this class was generated from the following files:
nnet2/am-nnet.h
nnet2/am-nnet.cc