Kaldi: FixedAffineComponent Class Reference
FixedAffineComponent Class Reference
FixedAffineComponent is an affine transform that is supplied at network initialization time and is not trainable.
#include <nnet-simple-component.h>
Public Member Functions
FixedAffineComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
FixedAffineComponent (const AffineComponent &c)
void Init (const CuMatrixBase< BaseFloat > &matrix)
matrix should be of size input-dim+1 to output-dim, last col is offset
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
const CuMatrix< BaseFloat > & LinearParams () const
const CuVector< BaseFloat > & BiasParams () const
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedAffineComponent)
Protected Attributes
CuMatrix< BaseFloat > linear_params_
CuVector< BaseFloat > bias_params_
Friends
class AffineComponent
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
FixedAffineComponent is an affine transform that is supplied at network initialization time and is not trainable.
Definition at line 992 of file nnet-simple-component.h.
Constructor & Destructor Documentation
FixedAffineComponent() [1/2]
FixedAffineComponent () inline
Definition at line 994 of file nnet-simple-component.h.
Referenced by FixedAffineComponent::Copy().
 { }
FixedAffineComponent() [2/2]
FixedAffineComponent (const AffineComponent & c)
Definition at line 3372 of file nnet-simple-component.cc.
                                                                   :
     linear_params_(c.LinearParams()),
     bias_params_(c.BiasParams()) { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 3384 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), kaldi::kNoTrans, and FixedAffineComponent::linear_params_.
{
   // kBackpropAdds is true. It's the user's responsibility to zero out
   // <in_deriv> if they need it to be so.
   if (in_deriv)
     in_deriv->AddMatMat(1.0, out_deriv, kNoTrans,
                         linear_params_, kNoTrans, 1.0);
 }
BiasParams()
const CuVector<BaseFloat>& BiasParams () const inline
Definition at line 1032 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsAffine().
 { return bias_params_; }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 3399 of file nnet-simple-component.cc.
References FixedAffineComponent::bias_params_, FixedAffineComponent::FixedAffineComponent(), and FixedAffineComponent::linear_params_.
{
   FixedAffineComponent *ans = new FixedAffineComponent();
   ans->linear_params_ = linear_params_;
   ans->bias_params_ = bias_params_;
   return ans;
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 3328 of file nnet-simple-component.cc.
References Component::Info(), and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   stream << Component::Info();
   PrintParameterStats(stream, "linear-params", linear_params_);
   PrintParameterStats(stream, "bias", bias_params_, true);
   return stream.str();
 }
Init()
void Init (const CuMatrixBase< BaseFloat > & matrix)
matrix should be of size input-dim+1 to output-dim, last col is offset
Definition at line 3336 of file nnet-simple-component.cc.
References KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Range().
Referenced by SumGroupComponent::InitFromConfig(), FixedScaleComponent::InitFromConfig(), FixedBiasComponent::InitFromConfig(), NaturalGradientPerElementScaleComponent::InitFromConfig(), and SumGroupComponent::Read().
{
   KALDI_ASSERT(mat.NumCols() > 1);
   linear_params_ = mat.Range(0, mat.NumRows(), 0, mat.NumCols() - 1);
   bias_params_.Resize(mat.NumRows());
   bias_params_.CopyColFromMat(mat, mat.NumCols() - 1);
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 3343 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), KALDI_ASSERT, KALDI_ERR, CuMatrixBase< Real >::NumRows(), CuMatrix< Real >::Read(), CuMatrixBase< Real >::SetRandn(), Input::Stream(), LinearComponent::Type(), and ConfigLine::WholeLine().
{
   std::string filename;
   // Two forms allowed: "matrix=<rxfilename>", or "input-dim=x output-dim=y"
   // (for testing purposes only).
   if (cfl->GetValue("matrix", &filename)) {
     if (cfl->HasUnusedValues())
       KALDI_ERR << "Invalid initializer for layer of type "
                 << Type() << ": \"" << cfl->WholeLine() << "\"";
     bool binary;
     Input ki(filename, &binary);
     CuMatrix<BaseFloat> mat;
     mat.Read(ki.Stream(), binary);
     KALDI_ASSERT(mat.NumRows() != 0);
     Init(mat);
   } else {
     int32 input_dim = -1, output_dim = -1;
     if (!cfl->GetValue("input-dim", &input_dim) ||
         !cfl->GetValue("output-dim", &output_dim) || cfl->HasUnusedValues()) {
       KALDI_ERR << "Invalid initializer for layer of type "
                 << Type() << ": \"" << cfl->WholeLine() << "\"";
     }
     CuMatrix<BaseFloat> mat(output_dim, input_dim + 1);
     mat.SetRandn();
     Init(mat);
   }
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1011 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsAffine().
 { return linear_params_.NumCols(); }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedAffineComponent) protected
LinearParams()
const CuMatrix<BaseFloat>& LinearParams () const inline
Definition at line 1031 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsAffine().
 { return linear_params_; }
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1012 of file nnet-simple-component.h.
References PnormComponent::Backprop(), PnormComponent::Copy(), PnormComponent::Propagate(), PnormComponent::Read(), and PnormComponent::Write().
Referenced by ModelCollapser::CollapseComponentsAffine().
 { return linear_params_.NumRows(); }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 3376 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), FixedAffineComponent::bias_params_, CuMatrixBase< Real >::CopyRowsFromVec(), kaldi::kNoTrans, kaldi::kTrans, and FixedAffineComponent::linear_params_.
{
   out->CopyRowsFromVec(bias_params_); // Adds the bias term first.
   out->AddMatMat(1.0, in, kNoTrans, linear_params_, kTrans, 1.0);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1010 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropAdds, and kaldi::nnet3::kSimpleComponent.
 { return kSimpleComponent|kBackpropAdds; }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 3415 of file nnet-simple-component.cc.
References FixedAffineComponent::bias_params_, kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), and FixedAffineComponent::linear_params_.
{
   ExpectOneOrTwoTokens(is, binary, "<FixedAffineComponent>", "<LinearParams>");
   linear_params_.Read(is, binary);
   ExpectToken(is, binary, "<BiasParams>");
   bias_params_.Read(is, binary);
   ExpectToken(is, binary, "</FixedAffineComponent>");
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 995 of file nnet-simple-component.h.
References Component::Info(), PnormComponent::Init(), and PnormComponent::InitFromConfig().
Referenced by SumGroupComponent::InitFromConfig(), FixedScaleComponent::InitFromConfig(), FixedBiasComponent::InitFromConfig(), and NaturalGradientPerElementScaleComponent::InitFromConfig().
 { return "FixedAffineComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3406 of file nnet-simple-component.cc.
References FixedAffineComponent::bias_params_, FixedAffineComponent::linear_params_, and kaldi::WriteToken().
{
   WriteToken(os, binary, "<FixedAffineComponent>");
   WriteToken(os, binary, "<LinearParams>");
   linear_params_.Write(os, binary);
   WriteToken(os, binary, "<BiasParams>");
   bias_params_.Write(os, binary);
   WriteToken(os, binary, "</FixedAffineComponent>");
 }
Friends And Related Function Documentation
AffineComponent
friend class AffineComponent friend
Definition at line 1034 of file nnet-simple-component.h.
Member Data Documentation
bias_params_
CuVector<BaseFloat> bias_params_ protected
Definition at line 1036 of file nnet-simple-component.h.
Referenced by FixedAffineComponent::Copy(), FixedAffineComponent::Propagate(), FixedAffineComponent::Read(), and FixedAffineComponent::Write().
linear_params_
CuMatrix<BaseFloat> linear_params_ protected
Definition at line 1035 of file nnet-simple-component.h.
Referenced by FixedAffineComponent::Backprop(), FixedAffineComponent::Copy(), FixedAffineComponent::Propagate(), FixedAffineComponent::Read(), and FixedAffineComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc