Kaldi: FixedLinearComponent Class Reference
FixedLinearComponent Class Reference
FixedLinearComponent is a linear transform that is supplied at network initialization time and is not trainable.
#include <nnet-component.h>
Public Member Functions
FixedLinearComponent ()
virtual std::string Type () const
virtual std::string Info () const
void Init (const CuMatrixBase< BaseFloat > &matrix)
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual ~Component ()
Protected Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedLinearComponent)
Protected Attributes
CuMatrix< BaseFloat > mat_
Friends
class AffineComponent
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
FixedLinearComponent is a linear transform that is supplied at network initialization time and is not trainable.
Definition at line 1413 of file nnet-component.h.
Constructor & Destructor Documentation
FixedLinearComponent()
FixedLinearComponent () inline
Definition at line 1415 of file nnet-component.h.
 { }
Member Function Documentation
Backprop()
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 3214 of file nnet-component.cc.
References CuMatrixBase< Real >::AddMatMat(), kaldi::kNoTrans, CuMatrixBase< Real >::NumRows(), and CuMatrix< Real >::Resize().
{
   in_deriv->Resize(out_deriv.NumRows(), mat_.NumCols());
   in_deriv->AddMatMat(1.0, out_deriv, kNoTrans, mat_, kNoTrans, 0.0);
 }
BackpropNeedsInput()
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 1439 of file nnet-component.h.
 { return false; }
BackpropNeedsOutput()
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 1440 of file nnet-component.h.
References kaldi::cu::Copy().
 { return false; }
Copy()
Component * Copy () const virtual
Copy component (deep copy).
Implements Component.
Definition at line 3225 of file nnet-component.cc.
References FixedLinearComponent::Init().
{
   FixedLinearComponent *ans = new FixedLinearComponent();
   ans->Init(mat_);
   return ans;
 }
Info()
std::string Info () const virtual
Reimplemented from Component.
Definition at line 3193 of file nnet-component.cc.
References Component::Info(), kaldi::kTrans, and kaldi::TraceMatMat().
{
   std::stringstream stream;
   BaseFloat mat_size = static_cast<BaseFloat>(mat_.NumRows())
       * static_cast<BaseFloat>(mat_.NumCols()),
       mat_stddev = std::sqrt(TraceMatMat(mat_, mat_, kTrans) /
                          mat_size);
   stream << Component::Info() << ", params-stddev=" << mat_stddev;
   return stream.str();
 }
Init()
void Init (const CuMatrixBase< BaseFloat > & matrix) inline
Definition at line 1419 of file nnet-component.h.
Referenced by FixedLinearComponent::Copy(), and kaldi::nnet2::UnitTestFixedLinearComponent().
 { mat_ = matrix; }
InitFromString()
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 3175 of file nnet-component.cc.
References AffineComponentPreconditionedOnline::Init(), KALDI_ASSERT, KALDI_ERR, CuMatrixBase< Real >::NumRows(), kaldi::nnet2::ParseFromString(), CuMatrix< Real >::Read(), Input::Stream(), and AffineComponentPreconditionedOnline::Type().
{
   std::string orig_args = args;
   std::string filename;
   bool ok = ParseFromString("matrix", &args, &filename);
   if (!ok || !args.empty())
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << orig_args << "\"";
   bool binary;
   Input ki(filename, &binary);
   CuMatrix<BaseFloat> mat;
   mat.Read(ki.Stream(), binary);
   KALDI_ASSERT(mat.NumRows() != 0);
   Init(mat);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 1425 of file nnet-component.h.
 { return mat_.NumCols(); }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedLinearComponent) protected
OutputDim()
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 1426 of file nnet-component.h.
References Component::Propagate().
 { return mat_.NumRows(); }
Propagate()
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 3203 of file nnet-component.cc.
References CuMatrixBase< Real >::AddMatMat(), ChunkInfo::CheckSize(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, and ChunkInfo::NumChunks().
{
   in_info.CheckSize(in);
   out_info.CheckSize(*out);
   KALDI_ASSERT(in_info.NumChunks() == out_info.NumChunks());
   out->AddMatMat(1.0, in, kNoTrans, mat_, kTrans, 0.0);
 }
Read()
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 3239 of file nnet-component.cc.
References kaldi::nnet2::ExpectOneOrTwoTokens(), and kaldi::ExpectToken().
{
   ExpectOneOrTwoTokens(is, binary, "<FixedLinearComponent>", "<CuMatrix>");
   mat_.Read(is, binary);
   ExpectToken(is, binary, "</FixedLinearComponent>");
 }
Type()
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 1416 of file nnet-component.h.
 { return "FixedLinearComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3232 of file nnet-component.cc.
References kaldi::WriteToken().
{
   WriteToken(os, binary, "<FixedLinearComponent>");
   WriteToken(os, binary, "<CuMatrix>");
   mat_.Write(os, binary);
   WriteToken(os, binary, "</FixedLinearComponent>");
 }
Friends And Related Function Documentation
AffineComponent
friend class AffineComponent friend
Definition at line 1445 of file nnet-component.h.
Member Data Documentation
mat_
CuMatrix<BaseFloat> mat_ protected
Definition at line 1446 of file nnet-component.h.
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc