Kaldi: CompactLatticeHolder Class Reference
CompactLatticeHolder Class Reference
#include <kaldi-lattice.h>
Public Types
typedef CompactLattice T
Public Member Functions
CompactLatticeHolder ()
bool Read (std::istream &is)
T & Value ()
void Clear ()
void Swap (CompactLatticeHolder *other)
bool ExtractRange (const CompactLatticeHolder &other, const std::string &range)
~CompactLatticeHolder ()
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Attributes
T * t_
Detailed Description
Definition at line 69 of file kaldi-lattice.h.
Member Typedef Documentation
T
typedef CompactLattice T
Definition at line 71 of file kaldi-lattice.h.
Constructor & Destructor Documentation
CompactLatticeHolder()
CompactLatticeHolder () inline
Definition at line 73 of file kaldi-lattice.h.
References CompactLatticeHolder::t_.
 { t_ = NULL; }
~CompactLatticeHolder()
~CompactLatticeHolder () inline
Definition at line 102 of file kaldi-lattice.h.
References CompactLatticeHolder::Clear().
 { Clear(); }
Member Function Documentation
Clear()
void Clear () inline
Definition at line 91 of file kaldi-lattice.h.
References CompactLatticeHolder::t_.
Referenced by CompactLatticeHolder::~CompactLatticeHolder(), and LatticeHolder::~LatticeHolder().
 { delete t_; t_ = NULL; }
ExtractRange()
bool ExtractRange (const CompactLatticeHolder & other, const std::string & range) inline
Definition at line 97 of file kaldi-lattice.h.
References KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 84 of file kaldi-lattice.h.
 { return true; }
Read()
bool Read (std::istream & is)
Definition at line 366 of file kaldi-lattice.cc.
References KALDI_WARN, and kaldi::ReadCompactLattice().
Referenced by CompactLatticeHolder::Write(), and LatticeHolder::Write().
{
   Clear(); // in case anything currently stored.
   int c = is.peek();
   if (c == -1) {
     KALDI_WARN << "End of stream detected reading CompactLattice.";
     return false;
   } else if (isspace(c)) { // The text form of the lattice begins
     // with space (normally, '\n'), so this means it's text (the binary form
     // cannot begin with space because it starts with the FST Type() which is not
     // space).
     return ReadCompactLattice(is, false, &t_);
   } else if (c != 214) { // 214 is first char of FST magic number,
     // on little-endian machines which is all we support (\326 octal)
     KALDI_WARN << "Reading compact lattice: does not appear to be an FST "
                << " [non-space but no magic number detected], file pos is "
                << is.tellg();
     return false;
   } else {
     return ReadCompactLattice(is, true, &t_);
   }
 }
Swap()
void Swap (CompactLatticeHolder * other) inline
Definition at line 93 of file kaldi-lattice.h.
References kaldi::swap(), and CompactLatticeHolder::t_.
{
     std::swap(t_, other->t_);
   }
Value()
T& Value () inline
Definition at line 86 of file kaldi-lattice.h.
References KALDI_ASSERT, and CompactLatticeHolder::t_.
              {
     KALDI_ASSERT(t_ != NULL && "Called Value() on empty CompactLatticeHolder");
     return *t_;
   }
Write()
static bool Write (std::ostream & os, bool binary, const T & t) inline static
Definition at line 75 of file kaldi-lattice.h.
References CompactLatticeHolder::Read(), and kaldi::WriteCompactLattice().
{
     // Note: we don't include the binary-mode header when writing
     // this object to disk; this ensures that if we write to single
     // files, the result can be read by OpenFst.
     return WriteCompactLattice(os, binary, t);
   }
Member Data Documentation
t_
T* t_ private
Definition at line 104 of file kaldi-lattice.h.
Referenced by CompactLatticeHolder::Clear(), LatticeHolder::Clear(), CompactLatticeHolder::CompactLatticeHolder(), LatticeHolder::LatticeHolder(), CompactLatticeHolder::Swap(), LatticeHolder::Swap(), CompactLatticeHolder::Value(), and LatticeHolder::Value().
The documentation for this class was generated from the following files:
lat/kaldi-lattice.h
lat/kaldi-lattice.cc