Kaldi: BackpropTruncationComponentPrecomputedIndexes Class Reference
BackpropTruncationComponentPrecomputedIndexes Class Reference
#include <nnet-general-component.h>
Public Member Functions
BackpropTruncationComponentPrecomputedIndexes ()
virtual ~BackpropTruncationComponentPrecomputedIndexes ()
virtual ComponentPrecomputedIndexes * Copy () const
virtual void Write (std::ostream &ostream, bool binary) const
virtual void Read (std::istream &istream, bool binary)
virtual std::string Type () const
Public Member Functions inherited from ComponentPrecomputedIndexes
virtual ~ComponentPrecomputedIndexes ()
Public Attributes
CuVector< BaseFloat > zeroing
BaseFloat zeroing_sum
Additional Inherited Members
Static Public Member Functions inherited from ComponentPrecomputedIndexes
static ComponentPrecomputedIndexes * ReadNew (std::istream &is, bool binary)
static ComponentPrecomputedIndexes * NewComponentPrecomputedIndexesOfType (const std::string &cpi_type)
Detailed Description
Definition at line 556 of file nnet-general-component.h.
Constructor & Destructor Documentation
BackpropTruncationComponentPrecomputedIndexes()
BackpropTruncationComponentPrecomputedIndexes () inline
Definition at line 570 of file nnet-general-component.h.
 : zeroing_sum(0.0) {}
~BackpropTruncationComponentPrecomputedIndexes()
virtual ~BackpropTruncationComponentPrecomputedIndexes () inline virtual
Definition at line 574 of file nnet-general-component.h.
 { }
Member Function Documentation
Copy()
virtual ComponentPrecomputedIndexes* Copy () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 576 of file nnet-general-component.h.
References DistributeComponent::Read(), and DistributeComponent::Write().
{
     return new BackpropTruncationComponentPrecomputedIndexes(*this);
   }
Read()
void Read (std::istream & istream, bool binary) virtual
Implements ComponentPrecomputedIndexes.
Definition at line 962 of file nnet-general-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), and kaldi::ReadBasicType().
                  {
   ExpectOneOrTwoTokens(istream, binary,
                        "<BackpropTruncationComponentPrecomputedIndexes>",
                        "<Zeroing>");
   zeroing.Read(istream, binary);
   ExpectToken(istream, binary, "<ZeroingSum>");
   ReadBasicType(istream, binary, &zeroing_sum);
   ExpectToken(istream, binary,
               "</BackpropTruncationComponentPrecomputedIndexes>");
 }
Type()
virtual std::string Type () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 584 of file nnet-general-component.h.
{
     return "BackpropTruncationComponentPrecomputedIndexes";
   }
Write()
void Write (std::ostream & ostream, bool binary) const virtual
Implements ComponentPrecomputedIndexes.
Definition at line 950 of file nnet-general-component.cc.
References kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(ostream, binary,
              "<BackpropTruncationComponentPrecomputedIndexes>");
   WriteToken(ostream, binary, "<Zeroing>");
   zeroing.Write(ostream, binary);
   WriteToken(ostream, binary, "<ZeroingSum>");
   WriteBasicType(ostream, binary, zeroing_sum);
   WriteToken(ostream, binary,
              "</BackpropTruncationComponentPrecomputedIndexes>");
 }
Member Data Documentation
zeroing
CuVector<BaseFloat> zeroing
Definition at line 564 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Backprop(), and BackpropTruncationComponent::PrecomputeIndexes().
zeroing_sum
BaseFloat zeroing_sum
Definition at line 568 of file nnet-general-component.h.
Referenced by BackpropTruncationComponent::Backprop(), and BackpropTruncationComponent::PrecomputeIndexes().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc