Kaldi: TxpSyllabify Class Reference
TxpSyllabify Class Reference
Syllabifies pronunciations into onset, nucleus, coda items Allows laison from left to right.
#include <mod-syllabify.h>
Public Member Functions
TxpSyllabify ()
~TxpSyllabify ()
bool Init (const TxpParseOptions &opts)
Load voice data.
bool Process (pugi::xml_document *input)
Process the XML, modifying the XML to reflect linguistic information.
Public Member Functions inherited from TxpModule
TxpModule (const std::string &name)
Construct module, also loads tpdb modules in specific instances.
virtual ~TxpModule ()
const std::string GetConfigValue (const std::string &key)
Return a configuration value for this module as a string (rendundant)
const char * GetOptValue (const char *key)
Return an option value for this module as a string.
bool GetConfigValueBool (const std::string &key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
bool GetOptValueBool (const char *key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
const std::string & GetName () const
Get the name of the module.
pugi::xml_node GetHeader (pugi::xml_document *input)
Gets or adds a module header to txpheader.
Private Attributes
TxpSylmax sylmax_
Object containing specifications of valid nucleus and onset phone sequences.
Additional Inherited Members
Protected Attributes inherited from TxpModule
const TxpParseOptions * opts_
Options structure for the module.
std::string tpdb_
Directory for text processing database (tpdb) files used by txpxmldata objectys in the module.
Detailed Description
Syllabifies pronunciations into onset, nucleus, coda items Allows laison from left to right.
/ref idlaktxp_syll
Definition at line 38 of file mod-syllabify.h.
Constructor & Destructor Documentation
TxpSyllabify()
TxpSyllabify () explicit
Definition at line 27 of file mod-syllabify.cc.
 : TxpModule("syllabify") {}
~TxpSyllabify()
~TxpSyllabify ()
Definition at line 29 of file mod-syllabify.cc.
{
 }
Member Function Documentation
Init()
bool Init (const TxpParseOptions & opts) virtual
Load voice data.
Reimplemented from TxpModule.
Definition at line 32 of file mod-syllabify.cc.
References TxpModule::GetOptValue(), TxpParseOptions::GetTpdb(), TxpSylmax::Init(), TxpModule::opts_, TxpSylmax::Parse(), TxpSyllabify::sylmax_, and TxpModule::tpdb_.
Referenced by main().
{
   opts_ = &opts;
   tpdb_ = opts.GetTpdb();
   sylmax_.Init(opts, std::string(GetOptValue("arch")));
   return sylmax_.Parse(tpdb_);
 }
Process()
bool Process (pugi::xml_document * input) virtual
Process the XML, modifying the XML to reflect linguistic information.
Reimplemented from TxpModule.
Definition at line 39 of file mod-syllabify.cc.
References kaldi::_add_sylxml(), TxpSylmax::GetPhoneVector(), TxpSylmax::Maxonset(), TxpSyllabify::sylmax_, and TxpSylmax::Writespron().
Referenced by main().
{
   std::string sylpron;
   PhoneVector pvector;
   pugi::xpath_node_set spts = input->document_element().select_nodes("//spt");
   spts.sort();
   for (pugi::xpath_node_set::const_iterator it = spts.begin();
        it != spts.end();
        ++it) {
     pugi::xml_node pre_node;
     pugi::xml_node spt = (*it).node();
     pugi::xpath_node_set tks = spt.select_nodes("descendant::tk");
     tks.sort();
     for (pugi::xpath_node_set::const_iterator it2 = tks.begin();
          it2 != tks.end();
          ++it2) {
       pugi::xml_node node = (*it2).node();
       if (!node.attribute("pron").empty() && strlen(node.attribute("pron").value()) > 0) {
         sylmax_.GetPhoneVector(node.attribute("pron").value(), &pvector);
         if (it2 == tks.end() - 1) pvector[pvector.size() - 1].cross_word = false;
         sylmax_.Maxonset(&pvector);
         if (it2 != tks.begin()) {
           sylmax_.Writespron(&pvector, &sylpron);
           pre_node.append_attribute("spron").set_value(sylpron.c_str());
           // add syllabic xml structure
           _add_sylxml(sylpron.c_str(), &pre_node);
         }
         pre_node = node;
       }
       else {
           node.append_attribute("spron").set_value("");
       }
     }
     if (!pre_node.empty()) {
       sylmax_.Writespron(&pvector, &sylpron);
       pre_node.append_attribute("spron").set_value(sylpron.c_str());
       // add syllabic xml structure
       _add_sylxml(sylpron.c_str(), &pre_node);
     }
   }
   return true;
 }
Member Data Documentation
sylmax_
TxpSylmax sylmax_ private
Object containing specifications of valid nucleus and onset phone sequences.
Definition at line 48 of file mod-syllabify.h.
Referenced by TxpSyllabify::Init(), and TxpSyllabify::Process().
The documentation for this class was generated from the following files:
idlaktxp/mod-syllabify.h
idlaktxp/mod-syllabify.cc