Kaldi: ComputationExpander Class Reference
ComputationExpander Class Reference
Public Member Functions
ComputationExpander (const Nnet &nnet, const MiscComputationInfo &misc_info, const NnetComputation &computation, bool need_debug_info, int32 num_n_values, NnetComputation *expanded_computation)
void Expand ()
Private Member Functions
void InitStrideInfo ()
void ComputeMatrixInfo ()
void ComputeDebugInfo ()
void ComputeSubmatrixInfo ()
void ExpandRowsCommand (const NnetComputation::Command &c_in, NnetComputation::Command *c_out)
void ExpandRowsMultiCommand (const NnetComputation::Command &c_in, NnetComputation::Command *c_out)
void ExpandRowRangesCommand (const NnetComputation::Command &c_in, NnetComputation::Command *c_out)
void ComputePrecomputedIndexes ()
void ComputeCommands ()
void EnsureDebugInfoExists (int32 submatrix_index)
bool GetNewSubmatLocationInfo (int32 submat_index, int32 old_row_index, int32 *new_row_index, int32 *n_stride) const
int32 GetNewMatrixLocationInfo (int32 old_matrix_index, int32 old_row_index) const
This function is used in mapping row-indexes into matrices, from the old to the new computation.
void ExpandIndexes (const std::vector< Index > &indexes, std::vector< Index > *indexes_expanded) const
Private Attributes
std::vector< int32 > n_stride_
const Nnet & nnet_
const MiscComputationInfo & misc_info_
const NnetComputation & computation_
bool need_debug_info_
int32 num_n_values_
NnetComputation * expanded_computation_
Detailed Description
Definition at line 3138 of file nnet-optimize-utils.cc.
Constructor & Destructor Documentation
ComputationExpander()
ComputationExpander (const Nnet & nnet, const MiscComputationInfo & misc_info, const NnetComputation & computation, bool need_debug_info, int32 num_n_values, NnetComputation * expanded_computation) inline
Definition at line 3140 of file nnet-optimize-utils.cc.
References KALDI_ASSERT.
                                                             :
       nnet_(nnet), misc_info_(misc_info),
       computation_(computation),
       need_debug_info_(need_debug_info),
       num_n_values_(num_n_values),
       expanded_computation_(expanded_computation) {
     KALDI_ASSERT(num_n_values > 2);
   }
Member Function Documentation
ComputeCommands()
void ComputeCommands () private
Definition at line 3501 of file nnet-optimize-utils.cc.
References NnetComputation::Command::command_type, NnetComputation::commands, DerivativeTimeLimiter::computation_, kaldi::nnet3::kAcceptInput, kaldi::nnet3::kAddRowRanges, kaldi::nnet3::kAddRows, kaldi::nnet3::kAddRowsMulti, kaldi::nnet3::kAddToRowsMulti, KALDI_ERR, kaldi::nnet3::kAllocMatrix, kaldi::nnet3::kBackprop, kaldi::nnet3::kBackpropNoModelUpdate, kaldi::nnet3::kCompressMatrix, kaldi::nnet3::kCopyRows, kaldi::nnet3::kCopyRowsMulti, kaldi::nnet3::kCopyToRowsMulti, kaldi::nnet3::kDeallocMatrix, kaldi::nnet3::kDecompressMatrix, kaldi::nnet3::kGotoLabel, kaldi::nnet3::kMatrixAdd, kaldi::nnet3::kMatrixCopy, kaldi::nnet3::kNoOperation, kaldi::nnet3::kNoOperationLabel, kaldi::nnet3::kNoOperationMarker, kaldi::nnet3::kNoOperationPermanent, kaldi::nnet3::kPropagate, kaldi::nnet3::kProvideOutput, kaldi::nnet3::kSetConst, and kaldi::nnet3::kSwapMatrix.
{
   int32 num_commands = computation_.commands.size();
   expanded_computation_->commands.resize(num_commands);
   for (int32 command_index = 0; command_index < num_commands;
        command_index++) {
     const NnetComputation::Command &c = computation_.commands[command_index];
     NnetComputation::Command &c_out =
         expanded_computation_->commands[command_index];
     c_out = c;
     // Commands that only operate on submatrices, components and
     // precomputed-indexes do not have to be changed because we'll take care of
     // the expansion by suitably redefining the matrices and submatrices, and
     // recreating the precomputed-indexes.
     // However, commands that require, 'indexes', 'indexes_multi' or
     // 'indexes_ranges' do need to be modified.
     switch (c.command_type) {
       case kAllocMatrix:
       case kDeallocMatrix:
       case kSetConst:
       case kSwapMatrix:
       case kPropagate: case kBackprop:
       case kBackpropNoModelUpdate: case kMatrixCopy: case kMatrixAdd:
         break;
       case kCopyRows: case kAddRows:
         ExpandRowsCommand(c, &c_out);
         break;
       case kCopyRowsMulti: case kAddRowsMulti:
       case kCopyToRowsMulti: case kAddToRowsMulti:
         ExpandRowsMultiCommand(c, &c_out);
         break;
       case kAddRowRanges:
         ExpandRowRangesCommand(c, &c_out);
         break;
       case kCompressMatrix: case kDecompressMatrix:
       case kAcceptInput: case kProvideOutput: case kNoOperation:
       case kNoOperationPermanent: case kNoOperationMarker:
       case kNoOperationLabel: case kGotoLabel:
         break;
       default:
         KALDI_ERR << "Un-handled command type";
     }
   }
 }
ComputeDebugInfo()
void ComputeDebugInfo () private
Definition at line 3603 of file nnet-optimize-utils.cc.
References NnetComputation::MatrixDebugInfo::cindexes, DerivativeTimeLimiter::computation_, NnetComputation::MatrixDebugInfo::is_deriv, KALDI_ASSERT, NnetComputation::matrices, NnetComputation::matrix_debug_info, and rnnlm::n.
{
   int32 num_matrices = computation_.matrices.size();
   KALDI_ASSERT(computation_.matrix_debug_info.size() == num_matrices);
   expanded_computation_->matrix_debug_info.resize(num_matrices);
   // Matrix zero is a special case; it's the empty matrix.
   expanded_computation_->matrix_debug_info[0] =
       computation_.matrix_debug_info[0];
   int32 num_n_values = num_n_values_;
   for (int32 m = 1; m < num_matrices; m++) {
     const NnetComputation::MatrixDebugInfo &info_in =
         computation_.matrix_debug_info[m];
     NnetComputation::MatrixDebugInfo &info_out =
         expanded_computation_->matrix_debug_info[m];
     info_out.is_deriv = info_in.is_deriv;
     int32 num_rows_in = computation_.matrices[m].num_rows,
         num_rows_out = expanded_computation_->matrices[m].num_rows;
     KALDI_ASSERT(num_rows_in == info_in.cindexes.size());
     info_out.cindexes.resize(num_rows_out);
     const Cindex *cindexes_in = &(info_in.cindexes[0]);
     Cindex *cindexes_out = &(info_out.cindexes[0]);
     for (int32 r = 0; r < num_rows_in; r++) {
       if (info_in.cindexes[r].second.n == 0) {
         int32 new_r = GetNewMatrixLocationInfo(m, r),
             n_stride = n_stride_[m];
         for (int32 n = 0; n < num_n_values; n++) {
           int32 r_out = new_r + n * n_stride;
           cindexes_out[r_out] = cindexes_in[r];
           cindexes_out[r_out].second.n = n;
         }
       }
     }
   }
 }
ComputeMatrixInfo()
void ComputeMatrixInfo () private
Definition at line 3588 of file nnet-optimize-utils.cc.
References DerivativeTimeLimiter::computation_, and NnetComputation::matrices.
{
   int32 num_matrices = computation_.matrices.size();
   expanded_computation_->matrices.resize(num_matrices);
   // Matrix zero is a special case; it's the empty matrix.
   expanded_computation_->matrices[0] = computation_.matrices[0];
   int32 old_num_n_values = 2,
       new_num_n_values = num_n_values_;
   for (int32 m = 1; m < num_matrices; m++) {
     expanded_computation_->matrices[m] = computation_.matrices[m];
     expanded_computation_->matrices[m].num_rows =
         (computation_.matrices[m].num_rows / old_num_n_values) *
         new_num_n_values;
   }
 }
ComputePrecomputedIndexes()
void ComputePrecomputedIndexes () private
Definition at line 3676 of file nnet-optimize-utils.cc.
References NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::command_type, NnetComputation::commands, NnetComputation::component_precomputed_indexes, DerivativeTimeLimiter::computation_, NnetComputation::PrecomputedIndexesInfo::data, Nnet::GetComponent(), NnetComputation::PrecomputedIndexesInfo::input_indexes, KALDI_ASSERT, kaldi::nnet3::kBackprop, kaldi::nnet3::kBackpropNoModelUpdate, kaldi::nnet3::kPropagate, DerivativeTimeLimiter::nnet_, NnetComputation::PrecomputedIndexesInfo::output_indexes, and Component::PrecomputeIndexes().
{
   // for each element of 'component_precomputed_indexes',
   // we will try to work out the command-index of the associated
   // Propagate() command and of the associated Backprop() command,
   // if it exists.
   // We expect that each such element will be associated with
   // exactly one Propagate() command and at most one Backprop() command.
   int32 num_commands = computation_.commands.size(),
     num_precomputed_indexes = computation_.component_precomputed_indexes.size();
   std::vector<bool> need_backprop(num_precomputed_indexes, false);
   std::vector<int32> component_index(num_precomputed_indexes, -1);
   for (int32 command_index = 0; command_index < num_commands; command_index++) {
     const NnetComputation::Command &c = computation_.commands[command_index];
     if (c.command_type == kPropagate && c.arg2 > 0) {
       KALDI_ASSERT(c.arg2 < num_precomputed_indexes);
       component_index[c.arg2] = c.arg1;
     }
     if ((c.command_type == kBackprop ||
          c.command_type == kBackpropNoModelUpdate) && c.arg2 > 0) {
       KALDI_ASSERT(c.arg2 < num_precomputed_indexes);
       need_backprop[c.arg2] = true;
     }
   }
   for (size_t p = 1;
        p < expanded_computation_->component_precomputed_indexes.size();
        ++p)
     delete expanded_computation_->component_precomputed_indexes[p].data;
   expanded_computation_->component_precomputed_indexes.clear();
   expanded_computation_->component_precomputed_indexes.resize(
       num_precomputed_indexes);
   for (int32 p = 1; p < num_precomputed_indexes; ++p) {
     const NnetComputation::PrecomputedIndexesInfo &old_info =
         computation_.component_precomputed_indexes[p];
     NnetComputation::PrecomputedIndexesInfo &new_info =
         expanded_computation_->component_precomputed_indexes[p];
     KALDI_ASSERT(!old_info.input_indexes.empty() &&
                  !old_info.output_indexes.empty() &&
                  "Input/output indexes not present in precomputed info of "
                  "computation to be expanded.");
     // note: we could place these expanded indexes into 'new_info.input_indexes'
     // and 'new_info.output_indexes', but we actually don't need to keep them
     // there, because they are only required to be kept in computations where
     // the n indexes consist of the set (0, 1), and the computation we're
     // creating has more distinct n indexes than that.
     std::vector<Index> input_indexes, output_indexes;
     ExpandIndexes(old_info.input_indexes, &input_indexes);
     ExpandIndexes(old_info.output_indexes, &output_indexes);
     KALDI_ASSERT(component_index[p] >= 0);
     const Component *component = nnet_.GetComponent(component_index[p]);
     ComponentPrecomputedIndexes *expanded_precomputed_indexes =
         component->PrecomputeIndexes(misc_info_, input_indexes,
                                      output_indexes, need_backprop[p]);
     // this object should not be null because it was not NULL the
     // last time we generated it from the same component, for the
     // same computation.
     KALDI_ASSERT(expanded_precomputed_indexes != NULL);
     new_info.data = expanded_precomputed_indexes;
   }
 }
ComputeSubmatrixInfo()
void ComputeSubmatrixInfo () private
Definition at line 3637 of file nnet-optimize-utils.cc.
References NnetComputation::MatrixDebugInfo::cindexes, NnetComputation::SubMatrixInfo::col_offset, DerivativeTimeLimiter::computation_, NnetComputation::GetSubmatrixStrings(), KALDI_ERR, NnetComputation::matrix_debug_info, NnetComputation::SubMatrixInfo::matrix_index, DerivativeTimeLimiter::nnet_, NnetComputation::SubMatrixInfo::num_cols, NnetComputation::SubMatrixInfo::num_rows, NnetComputation::Print(), NnetComputation::SubMatrixInfo::row_offset, and NnetComputation::submatrices.
{
   int32 num_submatrices = computation_.submatrices.size();
   expanded_computation_->submatrices.resize(num_submatrices);
   // Sub-matrix zero is a special case; it's the empty submatrix.
   expanded_computation_->submatrices[0] = computation_.submatrices[0];
   for (int32 s = 1; s < num_submatrices; s++) {
     const NnetComputation::SubMatrixInfo &info_in = computation_.submatrices[s];
     int32 m = info_in.matrix_index;
     const NnetComputation::MatrixDebugInfo &debug_info_in =
         computation_.matrix_debug_info[m];
     // we may need to change the row_offset and num_rows.
     int32 first_row_in = info_in.row_offset,
         last_row_in = first_row_in + info_in.num_rows - 1;
     if (!(debug_info_in.cindexes[first_row_in].second.n == 0 &&
           debug_info_in.cindexes[last_row_in].second.n == 1)) {
       std::ostringstream computation_ss;
       std::vector<std::string> submat_strings;
       computation_.GetSubmatrixStrings(nnet_, &submat_strings);
       computation_.Print(computation_ss, nnet_);
       KALDI_ERR << "Submatrix s" << s << " = " << submat_strings[s]
                 << " has strange dimensions.  Computation is: "
                 << computation_ss.str();
     }
     int32 first_row_out = GetNewMatrixLocationInfo(m, first_row_in),
         last_row_out = GetNewMatrixLocationInfo(m, last_row_in),
         new_num_rows = (last_row_out + 1 - first_row_out);
     NnetComputation::SubMatrixInfo &info_out =
         expanded_computation_->submatrices[s];
     info_out.matrix_index = m;
     info_out.row_offset = first_row_out;
     info_out.num_rows = new_num_rows;
     info_out.col_offset = info_in.col_offset;
     info_out.num_cols = info_in.num_cols;
   }
 }
EnsureDebugInfoExists()
void EnsureDebugInfoExists (int32 submatrix_index) private
Expand()
void Expand ()
Definition at line 3573 of file nnet-optimize-utils.cc.
References DerivativeTimeLimiter::computation_, and NnetComputation::need_model_derivative.
Referenced by kaldi::nnet3::ExpandComputation().
{
   InitStrideInfo();
   ComputeMatrixInfo();
   if (need_debug_info_)
     ComputeDebugInfo();
   else
     expanded_computation_->matrix_debug_info.clear();
   ComputeSubmatrixInfo();
   ComputePrecomputedIndexes();
   ComputeCommands();
   expanded_computation_->need_model_derivative =
       computation_.need_model_derivative;
 }
ExpandIndexes()
void ExpandIndexes (const std::vector< Index > & indexes, std::vector< Index > * indexes_expanded) const private
Definition at line 3794 of file nnet-optimize-utils.cc.
References kaldi::nnet3::ConvertNumNValues(), kaldi::nnet3::FindNStride(), and KALDI_ASSERT.
{
   bool full_check = false;
   int32 n_stride = FindNStride(indexes, full_check);
   KALDI_ASSERT(n_stride > 0);
   ConvertNumNValues(n_stride, 2, num_n_values_,
                     indexes, indexes_expanded);
 }
ExpandRowRangesCommand()
void ExpandRowRangesCommand (const NnetComputation::Command & c_in, NnetComputation::Command * c_out) private
Definition at line 3426 of file nnet-optimize-utils.cc.
References NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::arg3, DerivativeTimeLimiter::computation_, NnetComputation::indexes_ranges, KALDI_ASSERT, rnnlm::n, and NnetComputation::submatrices.
{
   // we need to expand the pairs of row-indexes in c_in.arg2, and put the index
   // of the resulting vector<int> in expanded_computation_->indexes_ranges, in
   // 'c_out->arg2'.
   int32 s1 = c_in.arg1, s2 = c_in.arg2,
       num_rows_old = computation_.submatrices[s1].num_rows,
       num_rows_new = expanded_computation_->submatrices[s1].num_rows;
   KALDI_ASSERT(static_cast<size_t>(c_in.arg3) <
                computation_.indexes_ranges.size());
   int32 num_n_values = num_n_values_;
   int32 old_arg3 = c_out->arg3;
   c_out->arg3 = expanded_computation_->indexes_ranges.size();
   expanded_computation_->indexes_ranges.push_back(
       std::vector<std::pair<int32, int32> >());
   std::vector<std::pair<int32, int32> > &new_indexes_ranges =
       expanded_computation_->indexes_ranges.back();
   const std::vector<std::pair<int32, int32> > &old_indexes_ranges =
       computation_.indexes_ranges[old_arg3];
   // old_indexes_ranges is a vector that has the same size as the num-rows of
   // submatrix s1.  It contains pairs that are either two copies of the same
   // value (in practice the pair (-1, -1)), or pairs (begin-row-index,
   // end-row-index) representing the (begin,end) of a range in submatrix s2.
   // Note: end-row-index is one past the end of the range, as for C++ iterators.
   KALDI_ASSERT(static_cast<int32>(old_indexes_ranges.size()) == num_rows_old);
   new_indexes_ranges.resize(num_rows_new,
                            std::pair<int32,int32>(-1, -1));
   for (int32 i1 = 0; i1 < num_rows_old; i1++) {
     int32 new_i1_n0, n_stride1;
     if (GetNewSubmatLocationInfo(s1, i1, &new_i1_n0, &n_stride1)) {
       // GetNewSubmatLocationInfo() returns true if this corresponds to
       // a Cindex with n == 0.
       int32 i2_begin = old_indexes_ranges[i1].first,
           i2_end = old_indexes_ranges[i1].second;
       if (i2_end == i2_begin)
         continue;  // (-1, -1) pair, meaning an empty range.
                    // 'new_indexes_ranges' is filled with (-1, -1) pairs as a
                    // default so we don't have to do anything for these
                    // elements.
       int32 i2_last = i2_end - 1;
       int32 new_i2_n0_begin, new_i2_n0_last,
           n_stride2;  // only 1 stride variable; both calls will output
                           // the same value.
       bool ans1 = GetNewSubmatLocationInfo(s2, i2_begin, &new_i2_n0_begin,
                                            &n_stride2),
           ans2 = GetNewSubmatLocationInfo(s2, i2_last, &new_i2_n0_last,
                                           &n_stride2);
       KALDI_ASSERT(ans1 && ans2 && new_i2_n0_last >= new_i2_n0_begin &&
                    new_i2_n0_begin >= 0 && n_stride1 > 0 && n_stride2 > 0);
       // source should also be for n==0, because we don't (or at least
       // shouldn't) create computations that mix up the 'n' values
       int32 new_i1 = new_i1_n0,
           new_i2_begin = new_i2_n0_begin,
           new_i2_end = new_i2_n0_last + 1;
       for (int32 n = 0; n < num_n_values;
            n++, new_i1 += n_stride1, new_i2_begin += n_stride2,
                new_i2_end += n_stride2) {
         new_indexes_ranges[new_i1].first = new_i2_begin;
         new_indexes_ranges[new_i1].second = new_i2_end;
       }
     }
   }
 }
ExpandRowsCommand()
void ExpandRowsCommand (const NnetComputation::Command & c_in, NnetComputation::Command * c_out) private
Definition at line 3298 of file nnet-optimize-utils.cc.
References NnetComputation::Command::alpha, NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::arg3, DerivativeTimeLimiter::computation_, NnetComputation::indexes, KALDI_ASSERT, rnnlm::n, and NnetComputation::submatrices.
{
   // we need to expand the row-indexes in c_in.arg3, and put the index of the
   // resulting vector<int> in expanded_computation_->indexes, in 'c_out->arg3'.
   int32 s1 = c_in.arg1, s2 = c_in.arg2;
   // The command that gets called is something like
   // submat1.AddRows(submat2, indexes) if submat1 is the submatrix referred to in
   // 's1' and submat2 is the submatrix referred to in 's2'.
   // 'indexes' has the same size as the num-rows of submat1, and the values
   // in the vector are row-indexes into s2.
   int32 old_arg3 = c_out->arg3;
   c_out->arg3 = expanded_computation_->indexes.size();
   c_out->alpha = c_in.alpha;
   expanded_computation_->indexes.push_back(std::vector<int32>());
   std::vector<int32> &new_indexes = expanded_computation_->indexes.back();
   const std::vector<int32> &old_indexes = computation_.indexes[old_arg3];
   int32 old_size = old_indexes.size(),
       num_n_values = num_n_values_,
       new_s1_size = expanded_computation_->submatrices[s1].num_rows,
       new_s2_size = expanded_computation_->submatrices[s2].num_rows;
   KALDI_ASSERT(old_size == computation_.submatrices[s1].num_rows);
   new_indexes.resize(new_s1_size, -1);
   // A note on the variable names: i1 and i2 are indexes into the destination
   // submatrix and the source submatrix respectively, of the CopyRows or AddRows
   // command.
   // "n0" in the variable name means that this corresponds to an Index with n==0.
   // things without "new" in the name refer to the old computation; things with
   // "new" in the name refer to the computation that we are generating.
   for (int32 i1 = 0; i1 < old_size; i1++) {
     int32 new_i1_n0, n_stride1;
     if (GetNewSubmatLocationInfo(s1, i1, &new_i1_n0, &n_stride1)) {
       // GetNewSubmatLocationInfo() returns true if this corresponds to
       // a Cindex with n == 0.
       int32 i2 = old_indexes[i1];  // note: i2 is the row index into submatrix s2.
       int32 new_i2_n0, n_stride2;
       if (i2 < 0) {  // if i2 is -1, we'll just leave any relevant positions in
                      // 'new_indexes' with -1's in them.
         continue;
       } else {
         bool ans = GetNewSubmatLocationInfo(s2, i2, &new_i2_n0, &n_stride2);
         KALDI_ASSERT(ans);  // source should also be for n==0, because we don't
                             // (or at least shouldn't) create computations that
                             // mix up the 'n' values
         int32 new_i1 = new_i1_n0, new_i2 = new_i2_n0;
         for (int32 n = 0; n < num_n_values;
              ++n, new_i1 += n_stride1, new_i2 += n_stride2) {
           KALDI_ASSERT(new_i1 < new_s1_size && new_i2 < new_s2_size);
           new_indexes[new_i1] = new_i2;
         }
       }
     }
   }
 }
ExpandRowsMultiCommand()
void ExpandRowsMultiCommand (const NnetComputation::Command & c_in, NnetComputation::Command * c_out) private
Definition at line 3361 of file nnet-optimize-utils.cc.
References NnetComputation::Command::arg1, NnetComputation::Command::arg2, DerivativeTimeLimiter::computation_, NnetComputation::indexes_multi, KALDI_ASSERT, rnnlm::n, and NnetComputation::submatrices.
{
   // we need to expand the (submatrix,row)-index pairs in c_in.arg2, and put the
   // index of the resulting vector<int> in expanded_computation_->indexes_multi,
   // in 'c_out->arg2'.
   int32 s1 = c_in.arg1,
       num_rows_old = computation_.submatrices[s1].num_rows,
       num_rows_new = expanded_computation_->submatrices[s1].num_rows;
   KALDI_ASSERT(num_rows_old % 2 == 0);
   int32 num_n_values = num_n_values_;
   int32 old_arg2 = c_out->arg2;
   c_out->arg2 = expanded_computation_->indexes_multi.size();
   expanded_computation_->indexes_multi.push_back(
       std::vector<std::pair<int32, int32> >());
   std::vector<std::pair<int32, int32> > &new_indexes_multi =
       expanded_computation_->indexes_multi.back();
   const std::vector<std::pair<int32, int32> > &old_indexes_multi =
       computation_.indexes_multi[old_arg2];
   // old_indexes_multi is a vector that has the same size as the num-rows
   // of submatrix s1.  It contains pairs that are either (-1, -1), or
   // pairs (submatrix-index, row-index) referring to other submatrices
   // in the computation.
   KALDI_ASSERT(static_cast<int32>(old_indexes_multi.size()) == num_rows_old);
   new_indexes_multi.resize(num_rows_new,
                            std::pair<int32,int32>(-1, -1));
   for (int32 i1 = 0; i1 < num_rows_old; i1++) {
     int32 new_i1_n0, n_stride1;
     if (GetNewSubmatLocationInfo(s1, i1, &new_i1_n0, &n_stride1)) {
       // GetNewSubmatLocationInfo() returns true if this corresponds to
       // a Cindex with n == 0.
       int32 s2 = old_indexes_multi[i1].first,
           i2 = old_indexes_multi[i1].second;
       int32 new_i2_n0, n_stride2;
       if (s2 < 0) {  // if s2 is -1, we don't have to do anything... we'd have
                      // to fill any relevant positions in 'new_indexes_multi'
                      // with (-1,-1)'s, but it's filled with that by default.
         continue;
       } else {
         bool ans = GetNewSubmatLocationInfo(s2, i2, &new_i2_n0, &n_stride2);
         KALDI_ASSERT(ans);  // source should also be for n==0, because we don't
                             // (or at least shouldn't) create computations that
                             // mix up the 'n' values
         int32 new_i1 = new_i1_n0, new_i2 = new_i2_n0;
         for (int32 n = 0; n < num_n_values;
              n++, new_i1 += n_stride1, new_i2 += n_stride2) {
           new_indexes_multi[new_i1].first = s2;
           new_indexes_multi[new_i1].second = new_i2;
         }
       }
     }
   }
 }
GetNewMatrixLocationInfo()
int32 GetNewMatrixLocationInfo (int32 old_matrix_index, int32 old_row_index) const private
This function is used in mapping row-indexes into matrices, from the old to the new computation.
Parameters
[in] matrix_index The matrix-index > 0, for which we are mapping row-indexes. The matrix-indexes are the same in the old and new computations.
[in] old_row_index The old row-index into the matrix.
Returns
This function returns the row-index where the cindex referred to in 'old_matrix_index' will reside in the new, expanded computation, WITH THE CAVEAT THAT if the old cindex had n == 1, we'll output the location of the cindex with n == num_n_values_ - 1. This happens to be what we want (it maps the last n value on the input to the last n value on the output.
Definition at line 3761 of file nnet-optimize-utils.cc.
References DerivativeTimeLimiter::computation_, KALDI_ASSERT, and NnetComputation::matrix_debug_info.
{
   // to understand 'block_size', read the comment for FindNStride().
   int32 n_stride = n_stride_[matrix_index],
       old_num_n_values = 2, new_num_n_values = num_n_values_,
       old_block_size = old_num_n_values * n_stride,
       new_block_size = new_num_n_values * n_stride,
       block_index = old_row_index / old_block_size,
       offset_within_block = old_row_index % old_block_size;
   // within each block, we can show, given our assumptions, that
   // we must first have a sub-block of 'n_stride' values all with
   // n == 0, then another sub-clock of 'n_stride' values all with
   // n == 1, and so on.  [except there is no 'and so on' for the
   // input computation, where we expect the 'n' values to be the
   // set {0, 1}.]
   int32 old_n_value = offset_within_block / n_stride,
       index_within_subblock = offset_within_block % n_stride;
   const std::vector<Cindex> &cindexes =
       computation_.matrix_debug_info[matrix_index].cindexes;
   KALDI_ASSERT(old_n_value == cindexes[old_row_index].second.n &&
                (old_n_value == 0 || old_n_value == 1));
   // Search for CAVEAT in the comment for this function to see what this is
   // about.  Mapping old_n_value == 1 -> new_n_value == new_num_n_values - 1
   // just happens to be useful for the way we use this function... it maps the
   // end of an old submatrix to the end of a new submatrix.
   int32 new_n_value = (old_n_value == 0 ? 0 : new_num_n_values - 1);
   return block_index * new_block_size + index_within_subblock +
       new_n_value * n_stride;
 }
GetNewSubmatLocationInfo()
bool GetNewSubmatLocationInfo (int32 submat_index, int32 old_row_index, int32 * new_row_index, int32 * n_stride) const private
Definition at line 3743 of file nnet-optimize-utils.cc.
References NnetComputation::MatrixDebugInfo::cindexes, DerivativeTimeLimiter::computation_, NnetComputation::matrix_debug_info, and NnetComputation::submatrices.
{
   int32 matrix_index = computation_.submatrices[submat_index].matrix_index,
    old_row_offset = computation_.submatrices[submat_index].row_offset,
    new_row_offset = expanded_computation_->submatrices[submat_index].row_offset;
   const NnetComputation::MatrixDebugInfo &debug_info_in =
       computation_.matrix_debug_info[matrix_index];
   if (debug_info_in.cindexes[old_row_index + old_row_offset].second.n != 0)
     return false;
   *new_row_index = (GetNewMatrixLocationInfo(matrix_index,
                                              old_row_index + old_row_offset) -
                     new_row_offset);
   *n_stride = n_stride_[matrix_index];
   return true;
 }
InitStrideInfo()
void InitStrideInfo () private
Definition at line 3548 of file nnet-optimize-utils.cc.
References NnetComputation::MatrixDebugInfo::cindexes, DerivativeTimeLimiter::computation_, kaldi::nnet3::FindNStride(), KALDI_ASSERT, KALDI_ERR, NnetComputation::matrices, and NnetComputation::matrix_debug_info.
{
   // note: the zeroth matrix is not a real matrix, it's the empty matrix.
   int32 num_matrices = computation_.matrices.size();
   n_stride_.resize(num_matrices);
   n_stride_[0] = 0;
   // the input computation to class ComputationExpander is required to
   // have its debug info set up.
   KALDI_ASSERT(!computation_.matrix_debug_info.empty());
   for (int32 m = 1; m < num_matrices; m++) {
     int32 num_rows = computation_.matrices[m].num_rows;
     const NnetComputation::MatrixDebugInfo &debug_info = computation_.matrix_debug_info[m];
     KALDI_ASSERT(debug_info.cindexes.size() == num_rows);
     bool full_check = true;  // TODO: eventually change this to false.
     int32 n_stride = FindNStride(debug_info.cindexes, full_check);
     if (n_stride == 0) {
       KALDI_ERR << "Problem encountered in 'shortcut' compilation: the computation "
                 << "does not have the expected structure.  Try compiling with "
                 << "--use-shortcut=false.";
     }
     n_stride_[m] = n_stride;
   }
 }
Member Data Documentation
computation_
const NnetComputation& computation_ private
Definition at line 3290 of file nnet-optimize-utils.cc.
expanded_computation_
NnetComputation* expanded_computation_ private
Definition at line 3293 of file nnet-optimize-utils.cc.
misc_info_
const MiscComputationInfo& misc_info_ private
Definition at line 3289 of file nnet-optimize-utils.cc.
n_stride_
std::vector<int32> n_stride_ private
Definition at line 3286 of file nnet-optimize-utils.cc.
need_debug_info_
bool need_debug_info_ private
Definition at line 3291 of file nnet-optimize-utils.cc.
nnet_
const Nnet& nnet_ private
Definition at line 3288 of file nnet-optimize-utils.cc.
num_n_values_
int32 num_n_values_ private
Definition at line 3292 of file nnet-optimize-utils.cc.
The documentation for this class was generated from the following file:
nnet3/nnet-optimize-utils.cc