Kaldi: MessageLogger Class Reference
MessageLogger Class Reference
"Functions relating to logging and error reporting"
#include <kaldi-error.h>
Public Member Functions
MessageLogger (LogMessageEnvelope::Severity severity, const char *func, const char *file, int32 line)
Constructor stores the info,.
~MessageLogger () noexcept(false)
Destructor, calls 'HandleMessage' which prints the message, (since C++11 a 'throwing' destructor must be declared 'noexcept(false)')
std::ostream & stream ()
The hook for the 'insertion operator', e.g.
Protected Member Functions
std::string GetMessage () const
Static Protected Member Functions
static void HandleMessage (const LogMessageEnvelope &env, const char *msg)
The logging function,.
Protected Attributes
LogMessageEnvelope envelope_
Private Attributes
std::ostringstream ss_
Detailed Description
Definition at line 89 of file kaldi-error.h.
Constructor & Destructor Documentation
MessageLogger()
MessageLogger (LogMessageEnvelope::Severity severity, const char * func, const char * file, int32 line)
Constructor stores the info,.
Definition at line 140 of file kaldi-error.cc.
References MessageLogger::envelope_, LogMessageEnvelope::file, LogMessageEnvelope::func, kaldi::GetShortFileName(), LogMessageEnvelope::line, and LogMessageEnvelope::severity.
{
   // Obviously, we assume the strings survive the destruction of this object.
   envelope_.severity = severity;
   envelope_.func = func;
   envelope_.file = GetShortFileName(file);  // Pointer inside 'file'.
   envelope_.line = line;
 }
~MessageLogger()
~MessageLogger () noexcept
Destructor, calls 'HandleMessage' which prints the message, (since C++11 a 'throwing' destructor must be declared 'noexcept(false)')
Definition at line 150 of file kaldi-error.cc.
References MessageLogger::envelope_, MessageLogger::GetMessage(), and MessageLogger::HandleMessage().
{
   std::string str = GetMessage();
   // print the mesage (or send to logging handler),
   MessageLogger::HandleMessage(envelope_, str.c_str());
 }
Member Function Documentation
GetMessage()
std::string GetMessage () const protected
Definition at line 156 of file kaldi-error.cc.
References MessageLogger::ss_.
Referenced by FatalMessageLogger::~FatalMessageLogger(), and MessageLogger::~MessageLogger().
{
   // remove trailing '\n',
   std::string str = ss_.str();
   while (!str.empty() && str[str.length() - 1] == '\n')
     str.resize(str.length() - 1);
   return str;
 }
HandleMessage()
void HandleMessage (const LogMessageEnvelope & env, const char * msg) static protected
The logging function,.
Definition at line 165 of file kaldi-error.cc.
References LogMessageEnvelope::file, LogMessageEnvelope::func, kaldi::g_log_handler, kaldi::GetProgramName(), KALDI_VERSION, kaldi::KaldiGetStackTrace(), LogMessageEnvelope::kAssertFailed, LogMessageEnvelope::kError, LogMessageEnvelope::kInfo, LogMessageEnvelope::kWarning, LogMessageEnvelope::line, and LogMessageEnvelope::severity.
Referenced by FatalMessageLogger::~FatalMessageLogger(), and MessageLogger::~MessageLogger().
{
   // Send to a logging handler if provided.
   if (g_log_handler != NULL) {
     g_log_handler(envelope, message);
   } else {
     // Otherwise, we use the default Kaldi logging.
     // Build the log-message 'header',
     std::stringstream header;
     if (envelope.severity > LogMessageEnvelope::kInfo) {
       header << "VLOG[" << envelope.severity << "] (";
     } else {
       switch (envelope.severity) {
         case LogMessageEnvelope::kInfo :
           header << "LOG (";
           break;
         case LogMessageEnvelope::kWarning :
           header << "WARNING (";
           break;
         case LogMessageEnvelope::kError :
           header << "ERROR (";
           break;
         case LogMessageEnvelope::kAssertFailed :
           header << "ASSERTION_FAILED (";
           break;
         default:
           abort();  // coding error (unknown 'severity'),
       }
     }
     // fill the other info from the envelope,
     header << GetProgramName() << "[" KALDI_VERSION "]" << ':'
            << envelope.func << "():" << envelope.file << ':' << envelope.line
            << ")";
     // Printing the message,
     if (envelope.severity >= LogMessageEnvelope::kWarning) {
       // VLOG, LOG, WARNING:
       fprintf(stderr, "%s %s\n", header.str().c_str(), message);
     } else {
       // ERROR, ASSERT_FAILED (print with stack-trace):
       fprintf(stderr, "%s %s\n\n%s\n", header.str().c_str(), message,
               KaldiGetStackTrace().c_str());
     }
   }
 }
stream()
std::ostream& stream () inline
The hook for the 'insertion operator', e.g.
'KALDI_LOG << "Message,"',
Definition at line 103 of file kaldi-error.h.
Referenced by kaldi::KaldiAssertFailure_().
 { return ss_; }
Member Data Documentation
envelope_
LogMessageEnvelope envelope_ protected
Definition at line 111 of file kaldi-error.h.
Referenced by MessageLogger::MessageLogger(), FatalMessageLogger::~FatalMessageLogger(), and MessageLogger::~MessageLogger().
ss_
std::ostringstream ss_ private
Definition at line 114 of file kaldi-error.h.
Referenced by MessageLogger::GetMessage().
The documentation for this class was generated from the following files:
base/kaldi-error.h
base/kaldi-error.cc