Kaldi: TxpCexspecContext Class Reference
TxpCexspecContext Class Reference
#include <txpcexspec.h>
Public Member Functions
TxpCexspecContext (const pugi::xml_document &doc, enum CEXSPECPAU_HANDLER pauhand)
~TxpCexspecContext ()
bool Next ()
bool isBreak ()
bool isBreakInternal ()
bool isEndBreak ()
bool isUttBreak ()
pugi::xml_node GetPhone (const int32 idx, const bool pause_context) const
pugi::xml_node GetSyllable (const int32 idx, const bool pause_context) const
pugi::xml_node GetWord (const int32 idx, const bool pause_context) const
pugi::xml_node GetSpurt (const int32 idx, const bool pause_context) const
pugi::xml_node GetContextUp (const pugi::xml_node &node, const char *name) const
Private Attributes
bool isbreak_
bool endbreak_
bool internalbreak_
bool uttbreak_
enum CEXSPECPAU_HANDLER pauhand_
pugi::xpath_node_set phones_
pugi::xpath_node_set syllables_
pugi::xpath_node_set words_
pugi::xpath_node_set spurts_
pugi::xpath_node_set utterances_
pugi::xpath_node_set::const_iterator current_phone_
pugi::xpath_node_set::const_iterator current_syllable_
pugi::xpath_node_set::const_iterator current_word_
pugi::xpath_node_set::const_iterator current_spurt_
pugi::xpath_node_set::const_iterator current_utterance_
XmlNodeVector phone_contexts_
XmlNodeVector syllable_contexts_
XmlNodeVector word_contexts_
XmlNodeVector spurt_contexts_
XmlNodeVector utterance_contexts_
Detailed Description
Definition at line 198 of file txpcexspec.h.
Constructor & Destructor Documentation
TxpCexspecContext()
TxpCexspecContext (const pugi::xml_document & doc, enum CEXSPECPAU_HANDLER pauhand) explicit
Definition at line 346 of file txpcexspec.cc.
References TxpCexspecContext::current_phone_, TxpCexspecContext::current_spurt_, TxpCexspecContext::current_syllable_, TxpCexspecContext::current_utterance_, TxpCexspecContext::current_word_, TxpCexspecContext::phones_, TxpCexspecContext::spurts_, TxpCexspecContext::syllables_, TxpCexspecContext::utterances_, and TxpCexspecContext::words_.
                                                         : pauhand_(pauhand) {
   phones_ = doc.document_element().select_nodes("//phon");
   syllables_ = doc.document_element().select_nodes("//syl");
   words_ = doc.document_element().select_nodes("//tk");
   spurts_ = doc.document_element().select_nodes("//spt");
   utterances_ = doc.document_element().select_nodes("//utt");
   phones_.sort();
   syllables_.sort();
   words_.sort();
   spurts_.sort();
   utterances_.sort();
   current_phone_ = phones_.begin();
   current_syllable_ = syllables_.begin();
   current_word_ = words_.begin();
   current_spurt_ = spurts_.begin();
   current_utterance_ = utterances_.begin();
 }
~TxpCexspecContext()
~TxpCexspecContext () inline
Definition at line 202 of file txpcexspec.h.
 {}
Member Function Documentation
GetContextUp()
pugi::xml_node GetContextUp (const pugi::xml_node & node, const char * name) const
Definition at line 393 of file txpcexspec.cc.
Referenced by kaldi::KaldiPhone(), and TxpCexspecContext::Next().
{
   pugi::xml_node parent;
   pugi::xml_node empty;
   parent = node.parent();
   while (!parent.empty()) {
     if (!strcmp(parent.name(), name)) return parent;
     parent = parent.parent();
   }
   return empty;
 }
GetPhone()
pugi::xml_node GetPhone (const int32 idx, const bool pause_context) const
Definition at line 406 of file txpcexspec.cc.
References TxpCexspecContext::current_phone_, rnnlm::i, and TxpCexspecContext::phones_.
Referenced by kaldi::CexFuncIntSegmentLocationFromBack(), kaldi::CexFuncIntSegmentLocationFromFront(), kaldi::CexFuncStringBackwardBackwardPhone(), kaldi::CexFuncStringBackwardPhone(), kaldi::CexFuncStringForwardForwardPhone(), kaldi::CexFuncStringForwardPhone(), kaldi::CexFuncStringPhone(), and kaldi::KaldiPhone().
{
   int32 i;
   int32 pau_found = 0;
   pugi::xml_node empty;
   if (idx >= 0) {
     for (i = 0; i < idx; i++) {
       if ((current_phone_ + i) == phones_.end()) return empty;
       if (!strcmp("pau", (current_phone_ + i)->node().attribute("val").value()))
         pau_found++;
     }
   } else {
     for (i = 0; i > idx; i--) {
       if ((current_phone_ + i) == phones_.begin()) return empty;
       if (!strcmp("pau", (current_phone_ + i)->node().attribute("val").value()))
         pau_found++;
     }
   }
   if ((current_phone_ + i) == phones_.end()) return empty;
   if (pau_found == 2 && !pause_context) return empty;
   return (current_phone_ + i)->node();
 }
GetSpurt()
pugi::xml_node GetSpurt (const int32 idx, const bool pause_context) const
Definition at line 480 of file txpcexspec.cc.
References TxpCexspecContext::current_spurt_, rnnlm::i, and TxpCexspecContext::spurts_.
Referenced by kaldi::CexFuncIntPhraseNumWords(), and kaldi::CexFuncStringPhraseTobiEndTone().
{
   int32 i;
   // int32 pau_found = 0;
   pugi::xml_node empty;
   // Get the parent token node of the current phone.
   if (idx >= 0) {
     for (i = 0; i < idx; i++) {
       if ((current_spurt_ + i) == spurts_.end()) return empty;
       // if (!strcmp("pau", (cur_phon_ + i)->node().attribute("val").value()))
         // pau_found++;
     }
   } else {
     for (i = 0; i > idx; i--) {
       if ((current_spurt_ + i) == spurts_.begin()) return empty;
       // if (!strcmp("pau", (cur_phon_ + i)->node().attribute("val").value()))
         // pau_found++;
     }
   }
   if ((current_spurt_ + i) == spurts_.end()) return empty;
   // if (pau_found == 2 && !pauctx) return empty;
   return (current_spurt_ + i)->node();
 }
GetSyllable()
pugi::xml_node GetSyllable (const int32 idx, const bool pause_context) const
Definition at line 430 of file txpcexspec.cc.
References TxpCexspecContext::current_syllable_, rnnlm::i, and TxpCexspecContext::syllables_.
Referenced by kaldi::CexFuncIntBackwardSyllableNumPhones(), kaldi::CexFuncIntBackwardSyllableStress(), kaldi::CexFuncIntForwardSyllableNumPhones(), kaldi::CexFuncIntForwardSyllableStress(), kaldi::CexFuncIntSegmentLocationFromBack(), kaldi::CexFuncIntSyllableNumPhones(), and kaldi::CexFuncIntSyllableStress().
{
   int32 i;
   // int32 pau_found = 0;
   pugi::xml_node empty;
   // Get the parent syllable node of the current phone.
   if (idx >= 0) {
     for (i = 0; i < idx; i++) {
       if ((current_syllable_ + i) == syllables_.end()) return empty;
       // if (!strcmp("pau", (cur_phon_ + i)->node().attribute("val").value()))
         // pau_found++;
     }
   } else {
     for (i = 0; i > idx; i--) {
       if ((current_syllable_ + i) == syllables_.begin()) return empty;
       // if (!strcmp("pau", (cur_phon_ + i)->node().attribute("val").value()))
         // pau_found++;
     }
   }
   if ((current_syllable_ + i) == syllables_.end()) return empty;
   // if (pau_found == 2 && !pauctx) return empty;
   return (current_syllable_ + i)->node();
 }
GetWord()
pugi::xml_node GetWord (const int32 idx, const bool pause_context) const
Definition at line 455 of file txpcexspec.cc.
References TxpCexspecContext::current_word_, rnnlm::i, and TxpCexspecContext::words_.
Referenced by kaldi::CexFuncIntBackwardWordNumSyls(), kaldi::CexFuncIntForwardWordNumSyls(), kaldi::CexFuncIntWordNumSyls(), kaldi::CexFuncStringBackwardWordPosTag(), kaldi::CexFuncStringForwardWordPosTag(), and kaldi::CexFuncStringWordPosTag().
{
   int32 i;
   // int32 pau_found = 0;
   pugi::xml_node empty;
   // Get the parent token node of the current phone.
   if (idx >= 0) {
     for (i = 0; i < idx; i++) {
       if ((current_word_ + i) == words_.end()) return empty;
       // if (!strcmp("pau", (cur_phon_ + i)->node().attribute("val").value()))
         // pau_found++;
     }
   } else {
     for (i = 0; i > idx; i--) {
       if ((current_word_ + i) == words_.begin()) return empty;
       // if (!strcmp("pau", (cur_phon_ + i)->node().attribute("val").value()))
         // pau_found++;
     }
   }
   if ((current_word_ + i) == words_.end()) return empty;
   // if (pau_found == 2 && !pauctx) return empty;
   return (current_word_ + i)->node();
 }
isBreak()
bool isBreak () inline
Definition at line 206 of file txpcexspec.h.
 {return isbreak_;}
isBreakInternal()
bool isBreakInternal () inline
Definition at line 208 of file txpcexspec.h.
 {return internalbreak_;}
isEndBreak()
bool isEndBreak () inline
Definition at line 210 of file txpcexspec.h.
 {return endbreak_;}
isUttBreak()
bool isUttBreak () inline
Definition at line 212 of file txpcexspec.h.
 {return uttbreak_;}
Next()
bool Next ()
Definition at line 365 of file txpcexspec.cc.
References TxpCexspecContext::current_phone_, TxpCexspecContext::current_spurt_, TxpCexspecContext::current_syllable_, TxpCexspecContext::current_utterance_, TxpCexspecContext::current_word_, TxpCexspecContext::GetContextUp(), and TxpCexspecContext::phones_.
{
   pugi::xml_node node, phon, empty;
   // std::cout << (current_phone_->node()).attribute("val").value() << ":"
   //           << (current_syllable_->node()).attribute("val").value() << ":"
   //           << (current_word_->node()).attribute("norm").value() << ":"
   //           << (current_spurt_->node()).attribute("phraseid").value() << ":"
   //           << (current_utterance_->node()).attribute("uttid").value() << " "
   //           << (current_phone_->node()).attribute("type").value() << "\n";
   // iterate over phone/break items
   current_phone_++;
   if (current_phone_ == phones_.end()) return false;
   phon = current_phone_->node();
   // update other iterators as required
   // dummy pau items already added for tk and syl levels
   node = GetContextUp(phon, "syl");
   while (node != current_syllable_->node()) current_syllable_++;
   node = GetContextUp(phon, "tk");
   while (node != current_word_->node()) current_word_++;
   node = GetContextUp(phon, "spt");
   while (node != current_spurt_->node()) current_spurt_++;
   node = GetContextUp(phon, "utt");
   while (node != current_utterance_->node()) current_utterance_++;
   return true;
 }
Member Data Documentation
current_phone_
pugi::xpath_node_set::const_iterator current_phone_ private
Definition at line 236 of file txpcexspec.h.
Referenced by TxpCexspecContext::GetPhone(), TxpCexspecContext::Next(), and TxpCexspecContext::TxpCexspecContext().
current_spurt_
pugi::xpath_node_set::const_iterator current_spurt_ private
Definition at line 239 of file txpcexspec.h.
Referenced by TxpCexspecContext::GetSpurt(), TxpCexspecContext::Next(), and TxpCexspecContext::TxpCexspecContext().
current_syllable_
pugi::xpath_node_set::const_iterator current_syllable_ private
Definition at line 237 of file txpcexspec.h.
Referenced by TxpCexspecContext::GetSyllable(), TxpCexspecContext::Next(), and TxpCexspecContext::TxpCexspecContext().
current_utterance_
pugi::xpath_node_set::const_iterator current_utterance_ private
Definition at line 240 of file txpcexspec.h.
Referenced by TxpCexspecContext::Next(), and TxpCexspecContext::TxpCexspecContext().
current_word_
pugi::xpath_node_set::const_iterator current_word_ private
Definition at line 238 of file txpcexspec.h.
Referenced by TxpCexspecContext::GetWord(), TxpCexspecContext::Next(), and TxpCexspecContext::TxpCexspecContext().
endbreak_
bool endbreak_ private
Definition at line 227 of file txpcexspec.h.
internalbreak_
bool internalbreak_ private
Definition at line 228 of file txpcexspec.h.
isbreak_
bool isbreak_ private
Definition at line 226 of file txpcexspec.h.
pauhand_
enum CEXSPECPAU_HANDLER pauhand_ private
Definition at line 230 of file txpcexspec.h.
phone_contexts_
XmlNodeVector phone_contexts_ private
Definition at line 242 of file txpcexspec.h.
phones_
pugi::xpath_node_set phones_ private
Definition at line 231 of file txpcexspec.h.
Referenced by TxpCexspecContext::GetPhone(), TxpCexspecContext::Next(), and TxpCexspecContext::TxpCexspecContext().
spurt_contexts_
XmlNodeVector spurt_contexts_ private
Definition at line 248 of file txpcexspec.h.
spurts_
pugi::xpath_node_set spurts_ private
Definition at line 234 of file txpcexspec.h.
Referenced by TxpCexspecContext::GetSpurt(), and TxpCexspecContext::TxpCexspecContext().
syllable_contexts_
XmlNodeVector syllable_contexts_ private
Definition at line 244 of file txpcexspec.h.
syllables_
pugi::xpath_node_set syllables_ private
Definition at line 232 of file txpcexspec.h.
Referenced by TxpCexspecContext::GetSyllable(), and TxpCexspecContext::TxpCexspecContext().
uttbreak_
bool uttbreak_ private
Definition at line 229 of file txpcexspec.h.
utterance_contexts_
XmlNodeVector utterance_contexts_ private
Definition at line 250 of file txpcexspec.h.
utterances_
pugi::xpath_node_set utterances_ private
Definition at line 235 of file txpcexspec.h.
Referenced by TxpCexspecContext::TxpCexspecContext().
word_contexts_
XmlNodeVector word_contexts_ private
Definition at line 246 of file txpcexspec.h.
words_
pugi::xpath_node_set words_ private
Definition at line 233 of file txpcexspec.h.
Referenced by TxpCexspecContext::GetWord(), and TxpCexspecContext::TxpCexspecContext().
The documentation for this class was generated from the following files:
idlaktxp/txpcexspec.h
idlaktxp/txpcexspec.cc