Kaldi: PosteriorHolder Class Reference
PosteriorHolder Class Reference
Posterior_group
#include <posterior.h>
Public Types
typedef Posterior T
Public Member Functions
PosteriorHolder ()
void Clear ()
bool Read (std::istream &is)
T & Value ()
void Swap (PosteriorHolder *other)
bool ExtractRange (const PosteriorHolder &other, const std::string &range)
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (PosteriorHolder)
Private Attributes
T t_
Detailed Description
Definition at line 59 of file posterior.h.
Member Typedef Documentation
T
typedef Posterior T
Definition at line 61 of file posterior.h.
Constructor & Destructor Documentation
PosteriorHolder()
PosteriorHolder () inline
Definition at line 63 of file posterior.h.
References PosteriorHolder::Write().
 { }
Member Function Documentation
Clear()
void Clear () inline
Definition at line 67 of file posterior.h.
References PosteriorHolder::Read(), kaldi::swap(), and PosteriorHolder::t_.
 { Posterior tmp; std::swap(tmp, t_); }
ExtractRange()
bool ExtractRange (const PosteriorHolder & other, const std::string & range) inline
Definition at line 82 of file posterior.h.
References PosteriorHolder::KALDI_DISALLOW_COPY_AND_ASSIGN(), and KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 74 of file posterior.h.
 { return true; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (PosteriorHolder) private
Referenced by PosteriorHolder::ExtractRange(), and GaussPostHolder::ExtractRange().
Read()
bool Read (std::istream & is)
Definition at line 138 of file posterior.cc.
References kaldi::InitKaldiInputStream(), KALDI_WARN, kaldi::ReadPosterior(), and PosteriorHolder::t_.
Referenced by PosteriorHolder::Clear(), and GaussPostHolder::Clear().
{
   t_.clear();
   bool is_binary;
   if (!InitKaldiInputStream(is, &is_binary)) {
     KALDI_WARN << "Reading Table object, failed reading binary header";
     return false;
   }
   try {
     ReadPosterior(is, is_binary, &t_);
     return true;
   } catch (std::exception &e) {
     KALDI_WARN << "Exception caught reading table of posteriors. " << e.what();
     t_.clear();
     return false;
   }
 }
Swap()
void Swap (PosteriorHolder * other) inline
Definition at line 78 of file posterior.h.
References PosteriorHolder::t_.
{
     t_.swap(other->t_);
   }
Value()
T& Value () inline
Definition at line 76 of file posterior.h.
References PosteriorHolder::t_.
 { return t_; }
Write()
bool Write (std::ostream & os, bool binary, const T & t) static
Definition at line 127 of file posterior.cc.
References kaldi::InitKaldiOutputStream(), KALDI_WARN, and kaldi::WritePosterior().
Referenced by GaussPostHolder::GaussPostHolder(), and PosteriorHolder::PosteriorHolder().
{
   InitKaldiOutputStream(os, binary);  // Puts binary header if binary mode.
   try {
     WritePosterior(os, binary, t);
     return true;
   } catch(const std::exception &e) {
     KALDI_WARN << "Exception caught writing table of posteriors. " << e.what();
     return false;  // Write failure.
   }
 }
Member Data Documentation
t_
T t_ private
Definition at line 88 of file posterior.h.
Referenced by PosteriorHolder::Clear(), GaussPostHolder::Clear(), PosteriorHolder::Read(), GaussPostHolder::Read(), PosteriorHolder::Swap(), GaussPostHolder::Swap(), PosteriorHolder::Value(), and GaussPostHolder::Value().
The documentation for this class was generated from the following files:
hmm/posterior.h
hmm/posterior.cc