Kaldi: LstmNonlinearityComponent Class Reference
LstmNonlinearityComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
LstmNonlinearityComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update_in, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void FreezeNaturalGradient (bool freeze)
virtual
LstmNonlinearityComponent (const LstmNonlinearityComponent &other)
void Init (int32 cell_dim, bool use_dropout, BaseFloat param_stddev, BaseFloat tanh_self_repair_threshold, BaseFloat sigmoid_self_repair_threshold, BaseFloat self_repair_scale)
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
Component ()
virtual ~Component ()
Private Member Functions
void InitNaturalGradient ()
const LstmNonlinearityComponent & operator= (const LstmNonlinearityComponent &other)
Private Attributes
CuMatrix< BaseFloat > params_
bool use_dropout_
CuMatrix< double > value_sum_
CuMatrix< double > deriv_sum_
CuVector< BaseFloat > self_repair_config_
CuVector< double > self_repair_total_
double count_
OnlineNaturalGradient preconditioner_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Detailed Description
Definition at line 2245 of file nnet-simple-component.h.
Constructor & Destructor Documentation
LstmNonlinearityComponent() [1/2]
LstmNonlinearityComponent () inline
Definition at line 2252 of file nnet-simple-component.h.
 : use_dropout_(false) { }
LstmNonlinearityComponent() [2/2]
LstmNonlinearityComponent (const LstmNonlinearityComponent & other) explicit
Definition at line 5813 of file nnet-simple-component.cc.
                                            :
     UpdatableComponent(other),
     params_(other.params_),
     use_dropout_(other.use_dropout_),
     value_sum_(other.value_sum_),
     deriv_sum_(other.deriv_sum_),
     self_repair_config_(other.self_repair_config_),
     self_repair_total_(other.self_repair_total_),
     count_(other.count_),
     preconditioner_(other.preconditioner_) { }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 5712 of file nnet-simple-component.cc.
References LstmNonlinearityComponent::count_, LstmNonlinearityComponent::deriv_sum_, KALDI_ASSERT, LstmNonlinearityComponent::params_, LstmNonlinearityComponent::self_repair_total_, and LstmNonlinearityComponent::value_sum_.
{
   const LstmNonlinearityComponent *other =
       dynamic_cast<const LstmNonlinearityComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   params_.AddMat(alpha, other->params_);
   value_sum_.AddMat(alpha, other->value_sum_);
   deriv_sum_.AddMat(alpha, other->deriv_sum_);
   self_repair_total_.AddVec(alpha, other->self_repair_total_);
   count_ += alpha * other->count_;
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 5764 of file nnet-simple-component.cc.
References CuVectorBase< Real >::AddColSumMat(), CuVectorBase< Real >::AddVec(), kaldi::cu::BackpropLstmNonlinearity(), LstmNonlinearityComponent::count_, LstmNonlinearityComponent::deriv_sum_, UpdatableComponent::is_gradient_, KALDI_ASSERT, kaldi::kUndefined, UpdatableComponent::learning_rate_, CuMatrixBase< Real >::NumRows(), LstmNonlinearityComponent::params_, OnlineNaturalGradient::PreconditionDirections(), LstmNonlinearityComponent::preconditioner_, LstmNonlinearityComponent::self_repair_total_, and LstmNonlinearityComponent::value_sum_.
{
   if (to_update_in == NULL) {
     cu::BackpropLstmNonlinearity(in_value, params_, out_deriv,
                                  deriv_sum_, self_repair_config_,
                                  count_, in_deriv,
                                  (CuMatrixBase<BaseFloat>*) NULL,
                                  (CuMatrixBase<double>*) NULL,
                                  (CuMatrixBase<double>*) NULL,
                                  (CuMatrixBase<BaseFloat>*) NULL);
   } else {
     LstmNonlinearityComponent *to_update =
         dynamic_cast<LstmNonlinearityComponent*>(to_update_in);
     KALDI_ASSERT(to_update != NULL);
     int32 cell_dim = params_.NumCols();
     CuMatrix<BaseFloat> params_deriv(3, cell_dim, kUndefined);
     CuMatrix<BaseFloat> self_repair_total(5, cell_dim, kUndefined);
     cu::BackpropLstmNonlinearity(in_value, params_, out_deriv,
                                  deriv_sum_, self_repair_config_,
                                  count_, in_deriv, &params_deriv,
                                  &(to_update->value_sum_),
                                  &(to_update->deriv_sum_),
                                  &self_repair_total);
     CuVector<BaseFloat> self_repair_total_sum(5);
     self_repair_total_sum.AddColSumMat(1.0, self_repair_total, 0.0);
     to_update->self_repair_total_.AddVec(1.0, self_repair_total_sum);
     to_update->count_ += static_cast<double>(in_value.NumRows());
     BaseFloat scale = 1.0;
     if (!to_update->is_gradient_) {
       to_update->preconditioner_.PreconditionDirections(
           &params_deriv, &scale);
     }
     to_update->params_.AddMat(to_update->learning_rate_ * scale,
                               params_deriv);
   }
 }
ConsolidateMemory()
void ConsolidateMemory () virtual
This virtual function relates to memory management, and avoiding fragmentation.
It is called only once per model, after we do the first minibatch of training. The default implementation does nothing, but it can be overridden by child classes, where it may re-initialize certain quantities that may possibly have been allocated during the forward pass (e.g. certain statistics; OnlineNaturalGradient objects). We use our own CPU-based allocator (see cu-allocator.h) and since it can't do paging since we're not in control of the GPU page table, fragmentation can be a problem. The allocator always tries to put things in 'low-address memory' (i.e. at smaller memory addresses) near the beginning of the block it allocated, to avoid fragmentation; but if permanent things (belonging to the model) are allocated in the forward pass, they can permanently stay in high memory. This function helps to prevent that, by re-allocating those things into low-address memory (It's important that it's called after all the temporary buffers for the forward-backward have been freed, so that there is low-address memory available)).
Reimplemented from Component.
Definition at line 5914 of file nnet-simple-component.cc.
References LstmNonlinearityComponent::preconditioner_, and OnlineNaturalGradient::Swap().
{
   OnlineNaturalGradient preconditioner_temp(preconditioner_);
   preconditioner_.Swap(&preconditioner_);
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 5685 of file nnet-simple-component.cc.
{
   return new LstmNonlinearityComponent(*this);
 }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 5730 of file nnet-simple-component.cc.
References KALDI_ASSERT, kaldi::kTrans, LstmNonlinearityComponent::params_, and kaldi::TraceMatMat().
{
   const LstmNonlinearityComponent *other =
       dynamic_cast<const LstmNonlinearityComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   return TraceMatMat(params_, other->params_, kTrans);
 }
FreezeNaturalGradient()
void FreezeNaturalGradient (bool freeze) virtual
virtual
Reimplemented from UpdatableComponent.
Definition at line 5869 of file nnet-simple-component.cc.
References OnlineNaturalGradient::Freeze(), and LstmNonlinearityComponent::preconditioner_.
{
   preconditioner_.Freeze(freeze);
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 5645 of file nnet-simple-component.cc.
References rnnlm::i, UpdatableComponent::Info(), kaldi::nnet3::PrintParameterStats(), VectorBase< Real >::Scale(), and kaldi::nnet3::SummarizeVector().
{
   std::ostringstream stream;
   int32 cell_dim = params_.NumCols();
   stream << UpdatableComponent::Info() << ", cell-dim=" << cell_dim
          << ", use-dropout=" << (use_dropout_ ? "true" : "false");
   PrintParameterStats(stream, "w_ic", params_.Row(0));
   PrintParameterStats(stream, "w_fc", params_.Row(1));
   PrintParameterStats(stream, "w_oc", params_.Row(2));
   // Note: some of the following code mirrors the code in
   // UpdatableComponent::Info(), in nnet-component-itf.cc.
   if (count_ > 0) {
     stream << ", count=" << std::setprecision(3) << count_
            << std::setprecision(6);
   }
   static const char *nonlin_names[] = { "i_t_sigmoid", "f_t_sigmoid", "c_t_tanh",
                                         "o_t_sigmoid", "m_t_tanh" };
   for (int32 i = 0; i < 5; i++) {
     stream << ", " << nonlin_names[i] << "={";
     stream << " self-repair-lower-threshold=" << self_repair_config_(i)
            << ", self-repair-scale=" << self_repair_config_(i + 5);
     if (count_ != 0) {
       BaseFloat self_repaired_proportion =
           self_repair_total_(i) / (count_ * cell_dim);
       stream << ", self-repaired-proportion=" << self_repaired_proportion;
       Vector<double> value_sum(value_sum_.Row(i)),
           deriv_sum(deriv_sum_.Row(i));
       Vector<BaseFloat> value_avg(value_sum), deriv_avg(deriv_sum);
       value_avg.Scale(1.0 / count_);
       deriv_avg.Scale(1.0 / count_);
       stream << ", value-avg=" << SummarizeVector(value_avg)
              << ", deriv-avg=" << SummarizeVector(deriv_avg);
     }
     stream << " }";
   }
   return stream.str();
 }
Init()
void Init (int32 cell_dim, bool use_dropout, BaseFloat param_stddev, BaseFloat tanh_self_repair_threshold, BaseFloat sigmoid_self_repair_threshold, BaseFloat self_repair_scale)
Definition at line 5825 of file nnet-simple-component.cc.
References LstmNonlinearityComponent::count_, LstmNonlinearityComponent::deriv_sum_, LstmNonlinearityComponent::InitNaturalGradient(), KALDI_ASSERT, LstmNonlinearityComponent::params_, CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), LstmNonlinearityComponent::self_repair_config_, LstmNonlinearityComponent::self_repair_total_, LstmNonlinearityComponent::use_dropout_, and LstmNonlinearityComponent::value_sum_.
Referenced by LstmNonlinearityComponent::InitFromConfig().
{
   KALDI_ASSERT(cell_dim > 0 && param_stddev >= 0.0 &&
                tanh_self_repair_threshold >= 0.0 &&
                tanh_self_repair_threshold <= 1.0 &&
                sigmoid_self_repair_threshold >= 0.0 &&
                sigmoid_self_repair_threshold <= 0.25 &&
                self_repair_scale >= 0.0 && self_repair_scale <= 0.1);
   use_dropout_ = use_dropout;
   params_.Resize(3, cell_dim);
   params_.SetRandn();
   params_.Scale(param_stddev);
   value_sum_.Resize(5, cell_dim);
   deriv_sum_.Resize(5, cell_dim);
   self_repair_config_.Resize(10);
   self_repair_config_.Range(0, 5).Set(sigmoid_self_repair_threshold);
   self_repair_config_(2) = tanh_self_repair_threshold;
   self_repair_config_(4) = tanh_self_repair_threshold;
   self_repair_config_.Range(5, 5).Set(self_repair_scale);
   self_repair_total_.Resize(5);
   count_ = 0.0;
   InitNaturalGradient();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 5873 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), LstmNonlinearityComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), KALDI_ERR, LstmNonlinearityComponent::Type(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   InitLearningRatesFromConfig(cfl);
   bool ok = true;
   bool use_dropout = false;
   int32 cell_dim;
   // these self-repair thresholds are the normal defaults for tanh and sigmoid
   // respectively.  If, later on, we decide that we want to support different
   // self-repair config values for the individual sigmoid and tanh
   // nonlinearities, we can modify this code then.
   BaseFloat tanh_self_repair_threshold = 0.2,
       sigmoid_self_repair_threshold = 0.05,
       self_repair_scale = 1.0e-05;
   // param_stddev is the stddev of the parameters.  it may be better to
   // use a smaller value but this was the default in the python scripts
   // for a while.
   BaseFloat param_stddev = 1.0;
   ok = ok && cfl->GetValue("cell-dim", &cell_dim);
   cfl->GetValue("param-stddev", &param_stddev);
   cfl->GetValue("tanh-self-repair-threshold",
                 &tanh_self_repair_threshold);
   cfl->GetValue("sigmoid-self-repair-threshold",
                 &sigmoid_self_repair_threshold);
   cfl->GetValue("self-repair-scale", &self_repair_scale);
   cfl->GetValue("use-dropout", &use_dropout);
   // We may later on want to make it possible to initialize the different
   // parameters w_ic, w_fc and w_oc with different biases.  We'll implement
   // that when and if it's needed.
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   if (ok) {
     Init(cell_dim, use_dropout, param_stddev, tanh_self_repair_threshold,
          sigmoid_self_repair_threshold, self_repair_scale);
   } else {
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   }
 }
InitNaturalGradient()
void InitNaturalGradient () private
Definition at line 5854 of file nnet-simple-component.cc.
References LstmNonlinearityComponent::preconditioner_, OnlineNaturalGradient::SetNumSamplesHistory(), OnlineNaturalGradient::SetRank(), and OnlineNaturalGradient::SetUpdatePeriod().
Referenced by LstmNonlinearityComponent::Init().
{
   // As regards the configuration for the natural-gradient preconditioner, we
   // don't make it configurable from the command line-- it's unlikely that any
   // differences from changing this would be substantial enough to effectively
   // tune the configuration.  Because the preconditioning code doesn't 'see' the
   // derivatives from individual frames, but only averages over the minibatch,
   // there is a fairly small amount of data available to estimate the Fisher
   // information matrix, so we set the rank, update period and
   // num-samples-history to smaller values than normal.
   preconditioner_.SetRank(20);
   preconditioner_.SetUpdatePeriod(2);
   preconditioner_.SetNumSamplesHistory(1000.0);
 }
InputDim()
int32 InputDim () const virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 5553 of file nnet-simple-component.cc.
{
   int32 cell_dim = value_sum_.NumCols();
   return cell_dim * 5 + (use_dropout_ ? 3 : 0);
 }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 5738 of file nnet-simple-component.cc.
{
   return params_.NumRows() * params_.NumCols();
 }
operator=()
const LstmNonlinearityComponent& operator= (const LstmNonlinearityComponent & other) private
OutputDim()
int32 OutputDim () const virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 5558 of file nnet-simple-component.cc.
{
   int32 cell_dim = value_sum_.NumCols();
   return cell_dim * 2;
 }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 5724 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::SetRandn().
{
   CuMatrix<BaseFloat> temp_params(params_.NumRows(), params_.NumCols());
   temp_params.SetRandn();
   params_.AddMat(stddev, temp_params);
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 5755 of file nnet-simple-component.cc.
References kaldi::cu::ComputeLstmNonlinearity().
{
   cu::ComputeLstmNonlinearity(in, params_, out);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 2254 of file nnet-simple-component.h.
References Component::Add(), PnormComponent::Backprop(), Component::ConsolidateMemory(), PnormComponent::Copy(), kaldi::nnet3::DotProduct(), kaldi::nnet3::FreezeNaturalGradient(), PnormComponent::Init(), kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kUpdatableComponent, kaldi::nnet3::NumParameters(), kaldi::nnet3::PerturbParams(), PnormComponent::Propagate(), PnormComponent::Read(), Component::Scale(), PnormComponent::Write(), and Component::ZeroStats().
{
     return kSimpleComponent|kUpdatableComponent|kBackpropNeedsInput;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 5564 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectToken(), KALDI_ASSERT, kaldi::ReadBasicType(), and kaldi::ReadToken().
{
   ReadUpdatableCommon(is, binary);  // Read opening tag and learning rate.
   ExpectToken(is, binary, "<Params>");
   params_.Read(is, binary);
   ExpectToken(is, binary, "<ValueAvg>");
   value_sum_.Read(is, binary);
   ExpectToken(is, binary, "<DerivAvg>");
   deriv_sum_.Read(is, binary);
   ExpectToken(is, binary, "<SelfRepairConfig>");
   self_repair_config_.Read(is, binary);
   ExpectToken(is, binary, "<SelfRepairProb>");
   self_repair_total_.Read(is, binary);
   std::string tok;
   ReadToken(is, binary, &tok);
   if (tok == "<UseDropout>") {
     ReadBasicType(is, binary, &use_dropout_);
     ReadToken(is, binary, &tok);
   } else {
     use_dropout_ = false;
   }
   KALDI_ASSERT(tok == "<Count>");
   ReadBasicType(is, binary, &count_);
   // For the on-disk format, we normalze value_sum_, deriv_sum_ and
   // self_repair_total_ by dividing by the count, but in memory they are scaled
   // by the count.  [for self_repair_total_, the scaling factor is count_ *
   // cell_dim].
   value_sum_.Scale(count_);
   deriv_sum_.Scale(count_);
   int32 cell_dim = params_.NumCols();
   self_repair_total_.Scale(count_ * cell_dim);
   InitNaturalGradient();
   ExpectToken(is, binary, "</LstmNonlinearityComponent>");
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 5696 of file nnet-simple-component.cc.
{
   if (scale == 0.0) {
     params_.SetZero();
     value_sum_.SetZero();
     deriv_sum_.SetZero();
     self_repair_total_.SetZero();
     count_ = 0.0;
   } else {
     params_.Scale(scale);
     value_sum_.Scale(scale);
     deriv_sum_.Scale(scale);
     self_repair_total_.Scale(scale);
     count_ *= scale;
   }
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 2253 of file nnet-simple-component.h.
Referenced by LstmNonlinearityComponent::InitFromConfig().
 { return "LstmNonlinearityComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 5748 of file nnet-simple-component.cc.
References VectorBase< Real >::Dim(), KALDI_ASSERT, and kaldi::nnet3::NumParameters().
{
   KALDI_ASSERT(params.Dim() == NumParameters());
   params_.CopyRowsFromVec(params);
 }
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 5742 of file nnet-simple-component.cc.
References VectorBase< Real >::CopyRowsFromMat(), VectorBase< Real >::Dim(), KALDI_ASSERT, and kaldi::nnet3::NumParameters().
{
   KALDI_ASSERT(params->Dim() == NumParameters());
   params->CopyRowsFromMat(params_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 5603 of file nnet-simple-component.cc.
References MatrixBase< Real >::Scale(), VectorBase< Real >::Scale(), VectorBase< Real >::Write(), MatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteUpdatableCommon(os, binary);  // Read opening tag and learning rate.
   WriteToken(os, binary, "<Params>");
   params_.Write(os, binary);
   WriteToken(os, binary, "<ValueAvg>");
   {
     Matrix<BaseFloat> value_avg(value_sum_);
     if (count_ != 0.0)
       value_avg.Scale(1.0 / count_);
     value_avg.Write(os, binary);
   }
   WriteToken(os, binary, "<DerivAvg>");
   {
     Matrix<BaseFloat> deriv_avg(deriv_sum_);
     if (count_ != 0.0)
       deriv_avg.Scale(1.0 / count_);
     deriv_avg.Write(os, binary);
   }
   WriteToken(os, binary, "<SelfRepairConfig>");
   self_repair_config_.Write(os, binary);
   WriteToken(os, binary, "<SelfRepairProb>");
   {
     int32 cell_dim = params_.NumCols();
     Vector<BaseFloat> self_repair_prob(self_repair_total_);
     if (count_ != 0.0)
       self_repair_prob.Scale(1.0 / (count_ * cell_dim));
     self_repair_prob.Write(os, binary);
   }
   if (use_dropout_) {
     // only write this if true; we have back-compat code in reading anyway.
     // this makes the models without dropout easier to read with older code.
     WriteToken(os, binary, "<UseDropout>");
     WriteBasicType(os, binary, use_dropout_);
   }
   WriteToken(os, binary, "<Count>");
   WriteBasicType(os, binary, count_);
   WriteToken(os, binary, "</LstmNonlinearityComponent>");
 }
ZeroStats()
void ZeroStats () virtual
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Other components that store other types of statistics (e.g. regarding gradient clipping) should implement ZeroStats() also.
Reimplemented from Component.
Definition at line 5689 of file nnet-simple-component.cc.
{
   value_sum_.SetZero();
   deriv_sum_.SetZero();
   self_repair_total_.SetZero();
   count_ = 0.0;
 }
Member Data Documentation
count_
double count_ private
Definition at line 2343 of file nnet-simple-component.h.
Referenced by LstmNonlinearityComponent::Add(), LstmNonlinearityComponent::Backprop(), and LstmNonlinearityComponent::Init().
deriv_sum_
CuMatrix<double> deriv_sum_ private
Definition at line 2325 of file nnet-simple-component.h.
Referenced by LstmNonlinearityComponent::Add(), LstmNonlinearityComponent::Backprop(), and LstmNonlinearityComponent::Init().
params_
CuMatrix<BaseFloat> params_ private
Definition at line 2308 of file nnet-simple-component.h.
Referenced by LstmNonlinearityComponent::Add(), LstmNonlinearityComponent::Backprop(), LstmNonlinearityComponent::DotProduct(), and LstmNonlinearityComponent::Init().
preconditioner_
OnlineNaturalGradient preconditioner_ private
Definition at line 2349 of file nnet-simple-component.h.
Referenced by LstmNonlinearityComponent::Backprop(), LstmNonlinearityComponent::ConsolidateMemory(), LstmNonlinearityComponent::FreezeNaturalGradient(), and LstmNonlinearityComponent::InitNaturalGradient().
self_repair_config_
CuVector<BaseFloat> self_repair_config_ private
Definition at line 2332 of file nnet-simple-component.h.
Referenced by LstmNonlinearityComponent::Init().
self_repair_total_
CuVector<double> self_repair_total_ private
Definition at line 2339 of file nnet-simple-component.h.
Referenced by LstmNonlinearityComponent::Add(), LstmNonlinearityComponent::Backprop(), and LstmNonlinearityComponent::Init().
use_dropout_
bool use_dropout_ private
Definition at line 2312 of file nnet-simple-component.h.
Referenced by LstmNonlinearityComponent::Init().
value_sum_
CuMatrix<double> value_sum_ private
Definition at line 2318 of file nnet-simple-component.h.
Referenced by LstmNonlinearityComponent::Add(), LstmNonlinearityComponent::Backprop(), and LstmNonlinearityComponent::Init().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc