Kaldi: Vector< Real > Class Template Reference
Vector< Real > Class Template Reference
%Matrix and vector classes
A class representing a vector.
#include <kaldi-vector.h>
Public Member Functions
Vector ()
Constructor that takes no arguments. Initializes to empty.
Vector (const MatrixIndexT s, MatrixResizeType resize_type=kSetZero)
Constructor with specific size.
template<typename OtherReal >
Vector (const CuVectorBase< OtherReal > &cu)
Copy constructor from CUDA vector This is defined in ../cudamatrix/cu-vector.h.
Vector (const Vector< Real > &v)
Copy constructor. The need for this is controversial.
Vector (const VectorBase< Real > &v)
Copy-constructor from base-class, needed to copy from SubVector.
template<typename OtherReal >
Vector (const VectorBase< OtherReal > &v)
Type conversion constructor.
void Swap (Vector< Real > *other)
Swaps the contents of *this and *other. Shallow swap.
~Vector ()
Destructor. Deallocates memory.
void Read (std::istream &in, bool binary, bool add=false)
Read function using C++ streams.
void Resize (MatrixIndexT length, MatrixResizeType resize_type=kSetZero)
Set vector to a specified size (can be zero).
void RemoveElement (MatrixIndexT i)
Remove one element and shifts later elements down.
Vector< Real > & operator= (const Vector< Real > &other)
Assignment operator, protected so it can only be used by std::vector.
Vector< Real > & operator= (const VectorBase< Real > &other)
Assignment operator that takes VectorBase.
Public Member Functions inherited from VectorBase< Real >
void SetZero ()
Set vector to all zeros.
bool IsZero (Real cutoff=1.0e-06) const
Returns true if matrix is all zeros.
void Set (Real f)
Set all members of a vector to a specified value.
void SetRandn ()
Set vector to random normally-distributed noise.
void SetRandUniform ()
Sets to numbers uniformly distributed on (0,1)
MatrixIndexT RandCategorical () const
This function returns a random index into this vector, chosen with probability proportional to the corresponding element.
MatrixIndexT Dim () const
Returns the dimension of the vector.
MatrixIndexT SizeInBytes () const
Returns the size in memory of the vector, in bytes.
Real * Data ()
Returns a pointer to the start of the vector's data.
const Real * Data () const
Returns a pointer to the start of the vector's data (const).
Real operator() (MatrixIndexT i) const
Indexing operator (const).
Real & operator() (MatrixIndexT i)
Indexing operator (non-const).
SubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l)
Returns a sub-vector of a vector (a range of elements).
const SubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l) const
Returns a const sub-vector of a vector (a range of elements).
void CopyFromVec (const VectorBase< Real > &v)
Copy data from another vector (must match own size).
template<typename OtherReal >
void CopyFromPacked (const PackedMatrix< OtherReal > &M)
Copy data from a SpMatrix or TpMatrix (must match own size).
template<typename OtherReal >
void CopyFromVec (const VectorBase< OtherReal > &v)
Copy data from another vector of different type (double vs. float)
template<typename OtherReal >
void CopyFromVec (const CuVectorBase< OtherReal > &v)
Copy from CuVector. This is defined in ../cudamatrix/cu-vector.h.
void ApplyLog ()
Apply natural log to all elements.
void ApplyLogAndCopy (const VectorBase< Real > &v)
Apply natural log to another vector and put result in *this.
void ApplyExp ()
Apply exponential to each value in vector.
void ApplyAbs ()
Take absolute value of each of the elements.
void ApplyFloor (Real floor_val, MatrixIndexT *floored_count=nullptr)
Applies floor to all elements.
void ApplyCeiling (Real ceil_val, MatrixIndexT *ceiled_count=nullptr)
Applies ceiling to all elements.
MatrixIndexT ApplyFloor (const VectorBase< Real > &floor_vec)
Applies floor to all elements. Returns number of elements floored.
Real ApplySoftMax ()
Apply soft-max to vector and return normalizer (log sum of exponentials).
Real ApplyLogSoftMax ()
Applies log soft-max to vector and returns normalizer (log sum of exponentials).
void Tanh (const VectorBase< Real > &src)
Sets each element of *this to the tanh of the corresponding element of "src".
void Sigmoid (const VectorBase< Real > &src)
Sets each element of *this to the sigmoid function of the corresponding element of "src".
void ApplyPow (Real power)
Take all elements of vector to a power.
void ApplyPowAbs (Real power, bool include_sign=false)
Take the absolute value of all elements of a vector to a power.
Real Norm (Real p) const
Compute the p-th norm of the vector.
bool ApproxEqual (const VectorBase< Real > &other, float tol=0.01) const
Returns true if ((*this)-other).Norm(2.0) <= tol * (*this).Norm(2.0).
void InvertElements ()
Invert all elements.
template<typename OtherReal >
void AddVec (const Real alpha, const VectorBase< OtherReal > &v)
Add vector : *this = *this + alpha * rv (with casting between floats and doubles)
void AddVec2 (const Real alpha, const VectorBase< Real > &v)
Add vector : *this = *this + alpha * rv^2 [element-wise squaring].
template<typename OtherReal >
void AddVec2 (const Real alpha, const VectorBase< OtherReal > &v)
Add vector : *this = *this + alpha * rv^2 [element-wise squaring], with casting between floats and doubles.
void AddMatVec (const Real alpha, const MatrixBase< Real > &M, const MatrixTransposeType trans, const VectorBase< Real > &v, const Real beta)
Add matrix times vector : this <– beta*this + alpha*M*v.
void AddMatSvec (const Real alpha, const MatrixBase< Real > &M, const MatrixTransposeType trans, const VectorBase< Real > &v, const Real beta)
This is as AddMatVec, except optimized for where v contains a lot of zeros.
void AddSpVec (const Real alpha, const SpMatrix< Real > &M, const VectorBase< Real > &v, const Real beta)
Add symmetric positive definite matrix times vector: this <– beta*this + alpha*M*v.
void AddTpVec (const Real alpha, const TpMatrix< Real > &M, const MatrixTransposeType trans, const VectorBase< Real > &v, const Real beta)
Add triangular matrix times vector: this <– beta*this + alpha*M*v.
void ReplaceValue (Real orig, Real changed)
Set each element to y = (x == orig ? changed : x).
void MulElements (const VectorBase< Real > &v)
Multipy element-by-element by another vector.
template<typename OtherReal >
void MulElements (const VectorBase< OtherReal > &v)
Multipy element-by-element by another vector of different type.
void DivElements (const VectorBase< Real > &v)
Divide element-by-element by a vector.
template<typename OtherReal >
void DivElements (const VectorBase< OtherReal > &v)
Divide element-by-element by a vector of different type.
void Add (Real c)
Add a constant to each element of a vector.
void AddVecVec (Real alpha, const VectorBase< Real > &v, const VectorBase< Real > &r, Real beta)
Add element-by-element product of vectlrs:
void AddVecDivVec (Real alpha, const VectorBase< Real > &v, const VectorBase< Real > &r, Real beta)
Add element-by-element quotient of two vectors.
void Scale (Real alpha)
Multiplies all elements by this constant.
void MulTp (const TpMatrix< Real > &M, const MatrixTransposeType trans)
Multiplies this vector by lower-triangular marix: *this <– *this *M.
void Solve (const TpMatrix< Real > &M, const MatrixTransposeType trans)
If trans == kNoTrans, solves M x = b, where b is the value of *this at input and x is the value of *this at output.
void CopyRowsFromMat (const MatrixBase< Real > &M)
Performs a row stack of the matrix M.
template<typename OtherReal >
void CopyRowsFromMat (const MatrixBase< OtherReal > &M)
void CopyRowsFromMat (const CuMatrixBase< Real > &M)
The following is implemented in ../cudamatrix/cu-matrix.cc.
void CopyColsFromMat (const MatrixBase< Real > &M)
Performs a column stack of the matrix M.
void CopyRowFromMat (const MatrixBase< Real > &M, MatrixIndexT row)
Extracts a row of the matrix M.
template<typename OtherReal >
void CopyRowFromMat (const MatrixBase< OtherReal > &M, MatrixIndexT row)
Extracts a row of the matrix M with type conversion.
template<typename OtherReal >
void CopyRowFromSp (const SpMatrix< OtherReal > &S, MatrixIndexT row)
Extracts a row of the symmetric matrix S.
template<typename OtherReal >
void CopyColFromMat (const MatrixBase< OtherReal > &M, MatrixIndexT col)
Extracts a column of the matrix M.
void CopyDiagFromMat (const MatrixBase< Real > &M)
Extracts the diagonal of the matrix M.
void CopyDiagFromPacked (const PackedMatrix< Real > &M)
Extracts the diagonal of a packed matrix M; works for Sp or Tp.
void CopyDiagFromSp (const SpMatrix< Real > &M)
Extracts the diagonal of a symmetric matrix.
void CopyDiagFromTp (const TpMatrix< Real > &M)
Extracts the diagonal of a triangular matrix.
Real Max () const
Returns the maximum value of any element, or -infinity for the empty vector.
Real Max (MatrixIndexT *index) const
Returns the maximum value of any element, and the associated index.
Real Min () const
Returns the minimum value of any element, or +infinity for the empty vector.
Real Min (MatrixIndexT *index) const
Returns the minimum value of any element, and the associated index.
Real Sum () const
Returns sum of the elements.
Real SumLog () const
Returns sum of the logs of the elements.
void AddRowSumMat (Real alpha, const MatrixBase< Real > &M, Real beta=1.0)
Does *this = alpha * (sum of rows of M) + beta * *this.
void AddColSumMat (Real alpha, const MatrixBase< Real > &M, Real beta=1.0)
Does *this = alpha * (sum of columns of M) + beta * *this.
void AddDiagMat2 (Real alpha, const MatrixBase< Real > &M, MatrixTransposeType trans=kNoTrans, Real beta=1.0)
Add the diagonal of a matrix times itself: *this = diag(M M^T) + beta * *this (if trans == kNoTrans), or *this = diag(M^T M) + beta * *this (if trans == kTrans).
void AddDiagMatMat (Real alpha, const MatrixBase< Real > &M, MatrixTransposeType transM, const MatrixBase< Real > &N, MatrixTransposeType transN, Real beta=1.0)
Add the diagonal of a matrix product: *this = diag(M N), assuming the "trans" arguments are both kNoTrans; for transpose arguments, it behaves as you would expect.
Real LogSumExp (Real prune=-1.0) const
Returns log(sum(exp())) without exp overflow If prune > 0.0, ignores terms less than the max - prune.
void Read (std::istream &in, bool binary, bool add=false)
Reads from C++ stream (option to add to existing contents).
void Write (std::ostream &Out, bool binary) const
Writes to C++ stream (option to write in binary).
template<>
void AddVec (const float alpha, const VectorBase< float > &rv)
template<>
void AddVec (const double alpha, const VectorBase< double > &rv)
template<>
void AddVec (const float alpha, const VectorBase< float > &v)
template<>
void AddVec (const double alpha, const VectorBase< double > &v)
Private Member Functions
void Init (const MatrixIndexT dim)
Init assumes the current contents of the class are invalid (i.e.
void Destroy ()
Destroy function, called internally.
Additional Inherited Members
Protected Member Functions inherited from VectorBase< Real >
~VectorBase ()
Destructor; does not deallocate memory, this is handled by child classes.
VectorBase ()
Empty initializer, corresponds to vector of zero size.
void CopyFromPtr (const Real *Data, MatrixIndexT sz)
Load data into the vector: sz must match own size.
KALDI_DISALLOW_COPY_AND_ASSIGN (VectorBase)
Protected Attributes inherited from VectorBase< Real >
Real * data_
data memory area
MatrixIndexT dim_
dimension of vector
Detailed Description
template<typename Real>
class kaldi::Vector< Real >
A class representing a vector.
This class provides a way to work with vectors in kaldi. It encapsulates basic operations and memory optimizations.
Definition at line 390 of file kaldi-vector.h.
Constructor & Destructor Documentation
Vector() [1/6]
Vector () inline
Constructor that takes no arguments. Initializes to empty.
Definition at line 393 of file kaldi-vector.h.
 : VectorBase<Real>() {}
Vector() [2/6]
Vector (const MatrixIndexT s, MatrixResizeType resize_type = kSetZero) inline explicit
Constructor with specific size.
Sets to all-zero by default if set_zero == false, memory contents are undefined.
Definition at line 397 of file kaldi-vector.h.
       : VectorBase<Real>() {  Resize(s, resize_type);  }
Vector() [3/6]
Vector (const CuVectorBase< OtherReal > & cu) explicit
Copy constructor from CUDA vector This is defined in ../cudamatrix/cu-vector.h.
Definition at line 383 of file cu-vector.h.
{
   Init(cu.Dim());
   cu.CopyToVec(this);
 }
Vector() [4/6]
Vector (const Vector< Real > & v) inline
Copy constructor. The need for this is controversial.
Definition at line 407 of file kaldi-vector.h.
                                 : VectorBase<Real>()  { //  (cannot be explicit)
     Resize(v.Dim(), kUndefined);
     this->CopyFromVec(v);
   }
Vector() [5/6]
Vector (const VectorBase< Real > & v) inline explicit
Copy-constructor from base-class, needed to copy from SubVector.
Definition at line 413 of file kaldi-vector.h.
                                              : VectorBase<Real>() {
     Resize(v.Dim(), kUndefined);
     this->CopyFromVec(v);
   }
Vector() [6/6]
Vector (const VectorBase< OtherReal > & v) inline explicit
Type conversion constructor.
Definition at line 420 of file kaldi-vector.h.
                                                  : VectorBase<Real>() {
     Resize(v.Dim(), kUndefined);
     this->CopyFromVec(v);
   }
~Vector()
~Vector () inline
Destructor. Deallocates memory.
Definition at line 438 of file kaldi-vector.h.
 { Destroy(); }
Member Function Documentation
Destroy()
void Destroy () private
Destroy function, called internally.
Deallocates memory and sets object to empty vector.
we need to free the data block if it was defined
Definition at line 279 of file kaldi-vector.cc.
{
   if (this->data_ != NULL)
     KALDI_MEMALIGN_FREE(this->data_);
   this->data_ = NULL;
   this->dim_ = 0;
 }
Init()
void Init (const MatrixIndexT dim) inline private
Init assumes the current contents of the class are invalid (i.e.
junk or has already been freed), and it sets the vector to newly allocated memory with the specified dimension. dim == 0 is acceptable. The memory contents pointed to by data_ will be undefined.
Definition at line 167 of file kaldi-vector.cc.
{
   KALDI_ASSERT(dim >= 0);
   if (dim == 0) {
     this->dim_ = 0;
     this->data_ = NULL;
     return;
   }
   MatrixIndexT size;
   void *data;
   void *free_data;
   size = dim * sizeof(Real);
   if ((data = KALDI_MEMALIGN(16, size, &free_data)) != NULL) {
     this->data_ = static_cast<Real*> (data);
     this->dim_ = dim;
   } else {
     throw std::bad_alloc();
   }
 }
operator=() [1/2]
Vector<Real>& operator= (const Vector< Real > & other) inline
Assignment operator, protected so it can only be used by std::vector.
Definition at line 457 of file kaldi-vector.h.
{
     Resize(other.Dim(), kUndefined);
     this->CopyFromVec(other);
     return *this;
   }
operator=() [2/2]
Vector<Real>& operator= (const VectorBase< Real > & other) inline
Assignment operator that takes VectorBase.
Definition at line 464 of file kaldi-vector.h.
{
     Resize(other.Dim(), kUndefined);
     this->CopyFromVec(other);
     return *this;
   }
Read()
void Read (std::istream & in, bool binary, bool add = false)
Read function using C++ streams.
Can also add to existing contents of matrix.
Definition at line 1108 of file kaldi-vector.cc.
Referenced by FramePoolingComponent::InitData(), main(), kaldi::operator>>(), PdfPrior::PdfPrior(), AccumFullGmm::Read(), LdaEstimate::Read(), AccumDiagGmm::Read(), Plda::Read(), RestrictedAttentionComponent::Read(), CuVector< float >::Read(), VectorBase< float >::Read(), Vector< float >::Read(), IvectorExtractorStats::Read(), PermuteComponent::Read(), kaldi::nnet3::ReadVectorAsChar(), kaldi::TypeThreeUsage(), kaldi::UnitTestIo(), kaldi::UnitTestIoCross(), and UnitTestReadWave().
{
   if (add) {
     Vector<Real> tmp(this->Dim());
     tmp.Read(is, binary, false);  // read without adding.
     if (this->Dim() == 0) this->Resize(tmp.Dim());
     if (this->Dim() != tmp.Dim()) {
       KALDI_ERR << "Vector<Real>::Read, adding but dimensions mismatch "
                 << this->Dim() << " vs. " << tmp.Dim();
     }
     this->AddVec(1.0, tmp);
     return;
   } // now assume add == false.
   std::ostringstream specific_error;
   MatrixIndexT pos_at_start = is.tellg();
   if (binary) {
     int peekval = Peek(is, binary);
     const char *my_token =  (sizeof(Real) == 4 ? "FV" : "DV");
     char other_token_start = (sizeof(Real) == 4 ? 'D' : 'F');
     if (peekval == other_token_start) {  // need to instantiate the other type to read it.
       typedef typename OtherReal<Real>::Real OtherType;  // if Real == float, OtherType == double, and vice versa.
       Vector<OtherType> other(this->Dim());
       other.Read(is, binary, false);  // add is false at this point.
       if (this->Dim() != other.Dim()) this->Resize(other.Dim());
       this->CopyFromVec(other);
       return;
     }
     std::string token;
     ReadToken(is, binary, &token);
     if (token != my_token) {
       if (token.length() > 20) token = token.substr(0, 17) + "...";
       specific_error << ": Expected token " << my_token << ", got " << token;
       goto bad;
     }
     int32 size;
     ReadBasicType(is, binary, &size);  // throws on error.
     if ((MatrixIndexT)size != this->Dim())  this->Resize(size);
     if (size > 0)
       is.read(reinterpret_cast<char*>(this->data_), sizeof(Real)*size);
     if (is.fail()) {
       specific_error << "Error reading vector data (binary mode); truncated "
           "stream? (size = " << size << ")";
       goto bad;
     }
     return;
   } else {  // Text mode reading; format is " [ 1.1 2.0 3.4 ]\n"
     std::string s;
     is >> s;
     // if ((s.compare("DV") == 0) || (s.compare("FV") == 0)) {  // Back compatibility.
     //  is >> s;  // get dimension
     //  is >> s;  // get "["
     // }
     if (is.fail()) { specific_error << "EOF while trying to read vector."; goto bad; }
     if (s.compare("[]") == 0) { Resize(0); return; } // tolerate this variant.
     if (s.compare("[")) {
       if (s.length() > 20) s = s.substr(0, 17) + "...";
       specific_error << "Expected \"[\" but got " << s;
       goto bad;
     }
     std::vector<Real> data;
     while (1) {
       int i = is.peek();
       if (i == '-' || (i >= '0' && i <= '9')) {  // common cases first.
         Real r;
         is >> r;
         if (is.fail()) { specific_error << "Failed to read number."; goto bad; }
         if (! std::isspace(is.peek()) && is.peek() != ']') {
           specific_error << "Expected whitespace after number."; goto bad;
         }
         data.push_back(r);
         // But don't eat whitespace... we want to check that it's not newlines
         // which would be valid only for a matrix.
       } else if (i == ' ' || i == '\t') {
         is.get();
       } else if (i == ']') {
         is.get();  // eat the ']'
         this->Resize(data.size());
         for (size_t j = 0; j < data.size(); j++)
           this->data_[j] = data[j];
         i = is.peek();
         if (static_cast<char>(i) == '\r') {
           is.get();
           is.get();  // get \r\n (must eat what we wrote)
         } else if (static_cast<char>(i) == '\n') { is.get(); } // get \n (must eat what we wrote)
         if (is.fail()) {
           KALDI_WARN << "After end of vector data, read error.";
           // we got the data we needed, so just warn for this error.
         }
         return;  // success.
       } else if (i == -1) {
         specific_error << "EOF while reading vector data.";
         goto bad;
       } else if (i == '\n' || i == '\r') {
         specific_error << "Newline found while reading vector (maybe it's a matrix?)";
         goto bad;
       } else {
         is >> s;  // read string.
         if (!KALDI_STRCASECMP(s.c_str(), "inf") ||
             !KALDI_STRCASECMP(s.c_str(), "infinity")) {
           data.push_back(std::numeric_limits<Real>::infinity());
           KALDI_WARN << "Reading infinite value into vector.";
         } else if (!KALDI_STRCASECMP(s.c_str(), "nan")) {
           data.push_back(std::numeric_limits<Real>::quiet_NaN());
           KALDI_WARN << "Reading NaN value into vector.";
         } else {
           if (s.length() > 20) s = s.substr(0, 17) + "...";
           specific_error << "Expecting numeric vector data, got " << s;
           goto  bad;
         }
       }
     }
   }
   // we never reach this line (the while loop returns directly).
 bad:
   KALDI_ERR << "Failed to read vector from stream.  " << specific_error.str()
             << " File position at start is "
             << pos_at_start<<", currently "<<is.tellg();
 }
RemoveElement()
void RemoveElement (MatrixIndexT i)
Remove one element and shifts later elements down.
Definition at line 269 of file kaldi-vector.cc.
Referenced by kaldi::UnitTestRemoveRow().
{
   KALDI_ASSERT(i <  this->dim_ && "Access out of vector");
   for (MatrixIndexT j = i + 1; j <  this->dim_; j++)
     this->data_[j-1] =  this->data_[j];
   this->dim_--;
 }
Resize()
void Resize (MatrixIndexT length, MatrixResizeType resize_type = kSetZero)
Set vector to a specified size (can be zero).
The value of the new data depends on resize_type: -if kSetZero, the new data will be zero -if kUndefined, the new data will be undefined -if kCopyData, the new data will be the same as the old data in any shared positions, and zero elsewhere. This function takes time proportional to the number of data elements.
Definition at line 190 of file kaldi-vector.cc.
Referenced by RestrictedAttentionComponent::Add(), kaldi::AppendVector(), ApplyFmllrXform(), Plda::ApplyTransform(), kaldi::ComplexFftRecursive(), AmSgmm2::ComponentLogLikes(), DiagGmm::ComponentPosteriors(), kaldi::ComputeAndSubtractMean(), Plda::ComputeDerivedVars(), IvectorExtractor::ComputeDerivedVars(), AmSgmm2::ComputeFmllrPreXform(), AmSgmm2::ComputeGammaI(), kaldi::ComputePca(), BasisFmllrEstimate::ComputeTransform(), kaldi::ComputeVadEnergy(), FmllrRawAccs::ConvertToSimpleStats(), kaldi::ConvolveSignals(), SvdApplier::DecomposeComponent(), kaldi::EstPca(), Xent::Eval(), kaldi::ExtractObjectRange(), kaldi::ExtractWaveformRemainder(), kaldi::ExtractWindow(), kaldi::FFTbasedBlockConvolveSignals(), kaldi::FFTbasedConvolveSignals(), FmllrRawAccs::FmllrRawAccs(), kaldi::GetEqualLoudnessVector(), kaldi::GetFeatureMeanAndVariance(), Nnet::GetGradient(), kaldi::nnet2::GetInitialScaleParams(), LogisticRegression::GetLogPosteriors(), kaldi::GetOccs(), Nnet::GetParams(), MleAmSgmm2Accs::GetStateOccupancies(), LdaEstimate::GetStats(), LdaEstimate::Init(), OnlineNaturalGradientSimple::InitDefault(), OnlinePreconditionerSimple::InitDefault(), TransitionModel::InitStats(), IvectorExtractor::IvectorExtractor(), IvectorExtractorStats::IvectorExtractorStats(), AffineComponent::LimitRank(), FullGmm::LogLikelihoods(), DiagGmm::LogLikelihoods(), FullGmm::LogLikelihoodsPreselect(), DiagGmm::LogLikelihoodsPreselect(), main(), MleSgmm2SpeakerAccs::MleSgmm2SpeakerAccs(), LimitRankClass::operator()(), IvectorExtractTask::operator()(), MleAmSgmm2Accs::Read(), kaldi::ReadData(), kaldi::nnet3::ReadVectorAsChar(), LinearResample::Resample(), DiagGmmNormal::Resize(), FullGmmNormal::Resize(), AccumFullGmm::Resize(), AccumDiagGmm::Resize(), Sgmm2PerFrameDerivedVars::Resize(), MleAmSgmm2Accs::ResizeAccumulators(), kaldi::nnet3::RunNnetComputation(), kaldi::SelectLags(), RestrictedAttentionComponent::StoreStats(), CuVector< float >::Swap(), UnitTestEstimateLda(), kaldi::UnitTestIo(), UnitTestLinearResample(), UnitTestReadWave(), kaldi::UnitTestRegtreeFmllrDiagGmm(), kaldi::UnitTestResize(), kaldi::nnet3::UnitTestSummarizeVector(), MleSgmm2SpeakerAccs::UpdateNoU(), MleSgmm2SpeakerAccs::UpdateWithU(), and NonlinearComponent::Write().
{
   // the next block uses recursion to handle what we have to do if
   // resize_type == kCopyData.
   if (resize_type == kCopyData) {
     if (this->data_ == NULL || dim == 0) resize_type = kSetZero;  // nothing to copy.
     else if (this->dim_ == dim) { return; } // nothing to do.
     else {
       // set tmp to a vector of the desired size.
       Vector<Real> tmp(dim, kUndefined);
       if (dim > this->dim_) {
         memcpy(tmp.data_, this->data_, sizeof(Real)*this->dim_);
         memset(tmp.data_+this->dim_, 0, sizeof(Real)*(dim-this->dim_));
       } else {
         memcpy(tmp.data_, this->data_, sizeof(Real)*dim);
       }
       tmp.Swap(this);
       // and now let tmp go out of scope, deleting what was in *this.
       return;
     }
   }
   // At this point, resize_type == kSetZero or kUndefined.
   if (this->data_ != NULL) {
     if (this->dim_ == dim) {
       if (resize_type == kSetZero) this->SetZero();
       return;
     } else {
       Destroy();
     }
   }
   Init(dim);
   if (resize_type == kSetZero) this->SetZero();
 }
Swap()
void Swap (Vector< Real > * other)
Swaps the contents of *this and *other. Shallow swap.
Definition at line 1296 of file kaldi-vector.cc.
Referenced by kaldi::nnet3::PrintParameterStats(), Vector< float >::Resize(), and CuVector< float >::Swap().
{
   std::swap(this->data_, other->data_);
   std::swap(this->dim_, other->dim_);
 }
The documentation for this class was generated from the following files:
matrix/kaldi-vector.h
matrix/kaldi-vector.cc
cudamatrix/cu-vector.h