Kaldi: WaveInfo Class Reference
WaveInfo Class Reference
This class reads and hold wave file header information.
#include <wave-reader.h>
Public Member Functions
WaveInfo ()
bool IsStreamed () const
Is stream size unknown? Duration and SampleCount not valid if true.
BaseFloat SampFreq () const
Sample frequency, Hz.
uint32 SampleCount () const
Number of samples in stream. Invalid if IsStreamed() is true.
BaseFloat Duration () const
Approximate duration, seconds. Invalid if IsStreamed() is true.
int32 NumChannels () const
Number of channels, 1 to 16.
size_t BlockAlign () const
Bytes per sample.
size_t DataBytes () const
Wave data bytes. Invalid if IsStreamed() is true.
bool ReverseBytes () const
Is data file byte order different from machine byte order?
void Read (std::istream &is)
'is' should be opened in binary mode.
Private Attributes
BaseFloat samp_freq_
int32 samp_count_
uint8 num_channels_
bool reverse_bytes_
Detailed Description
This class reads and hold wave file header information.
Definition at line 65 of file wave-reader.h.
Constructor & Destructor Documentation
WaveInfo()
WaveInfo () inline
Definition at line 67 of file wave-reader.h.
Referenced by WaveInfoHolder::Clear().
              : samp_freq_(0), samp_count_(0),
                num_channels_(0), reverse_bytes_(0) {}
Member Function Documentation
BlockAlign()
size_t BlockAlign () const inline
Bytes per sample.
Definition at line 86 of file wave-reader.h.
References WaveInfo::num_channels_.
Referenced by WaveInfo::DataBytes(), and WaveData::Read().
 { return 2 * num_channels_; }
DataBytes()
size_t DataBytes () const inline
Wave data bytes. Invalid if IsStreamed() is true.
Definition at line 89 of file wave-reader.h.
References WaveInfo::BlockAlign(), and WaveInfo::samp_count_.
Referenced by WaveData::Read().
 { return samp_count_ * BlockAlign(); }
Duration()
BaseFloat Duration () const inline
Approximate duration, seconds. Invalid if IsStreamed() is true.
Definition at line 80 of file wave-reader.h.
References WaveInfo::samp_count_, and WaveInfo::samp_freq_.
Referenced by main().
 { return samp_count_ / samp_freq_; }
IsStreamed()
bool IsStreamed () const inline
Is stream size unknown? Duration and SampleCount not valid if true.
Definition at line 71 of file wave-reader.h.
References WaveInfo::samp_count_.
Referenced by main(), and WaveData::Read().
 { return samp_count_ < 0; }
NumChannels()
int32 NumChannels () const inline
Number of channels, 1 to 16.
Definition at line 83 of file wave-reader.h.
References WaveInfo::num_channels_.
Referenced by WaveData::Read().
 { return num_channels_; }
Read()
void Read (std::istream & is)
'is' should be opened in binary mode.
Read() will throw on error. On success 'is' will be positioned at the beginning of wave data.
Definition at line 114 of file wave-reader.cc.
References WaveHeaderReadGofer::Expect4ByteTag(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, KALDI_VLOG, KALDI_WARN, WaveHeaderReadGofer::Read4ByteTag(), WaveHeaderReadGofer::ReadUint16(), WaveHeaderReadGofer::ReadUint32(), WaveHeaderReadGofer::swap, and WaveHeaderReadGofer::tag.
Referenced by WaveData::Read(), WaveInfo::ReverseBytes(), and WaveData::WaveData().
{
   WaveHeaderReadGofer reader(is);
   reader.Read4ByteTag();
   if (strcmp(reader.tag, "RIFF") == 0)
     reverse_bytes_ = false;
   else if (strcmp(reader.tag, "RIFX") == 0)
     reverse_bytes_ = true;
   else
     KALDI_ERR << "WaveData: expected RIFF or RIFX, got " << reader.tag;
 #ifdef __BIG_ENDIAN__
   reverse_bytes_ = !reverse_bytes_;
 #endif
   reader.swap = reverse_bytes_;
   uint32 riff_chunk_size = reader.ReadUint32();
   reader.Expect4ByteTag("WAVE");
   uint32 riff_chunk_read = 0;
   riff_chunk_read += 4;  // WAVE included in riff_chunk_size.
   // Possibly skip any RIFF tags between 'WAVE' and 'fmt '.
   // Apple devices produce a filler tag 'JUNK' for memory alignment.
   reader.Read4ByteTag();
   riff_chunk_read += 4;
   while (strcmp(reader.tag,"fmt ") != 0) {
     uint32 filler_size = reader.ReadUint32();
     riff_chunk_read += 4;
     for (uint32 i = 0; i < filler_size; i++) {
       is.get(); // read 1 byte,
     }
     riff_chunk_read += filler_size;
     // get next RIFF tag,
     reader.Read4ByteTag();
     riff_chunk_read += 4;
   }
   KALDI_ASSERT(strcmp(reader.tag,"fmt ") == 0);
   uint32 subchunk1_size = reader.ReadUint32();
   uint16 audio_format = reader.ReadUint16();
   num_channels_ = reader.ReadUint16();
   uint32 sample_rate = reader.ReadUint32(),
       byte_rate = reader.ReadUint32(),
       block_align = reader.ReadUint16(),
       bits_per_sample = reader.ReadUint16();
   samp_freq_ = static_cast<BaseFloat>(sample_rate);
   uint32 fmt_chunk_read = 16;
   if (audio_format == 1) {
     if (subchunk1_size < 16) {
       KALDI_ERR << "WaveData: expect PCM format data to have fmt chunk "
                 << "of at least size 16.";
     }
   } else if (audio_format == 0xFFFE) {  // WAVE_FORMAT_EXTENSIBLE
     uint16 extra_size = reader.ReadUint16();
     if (subchunk1_size < 40 || extra_size < 22) {
       KALDI_ERR << "WaveData: malformed WAVE_FORMAT_EXTENSIBLE format data.";
     }
     reader.ReadUint16();  // Unused for PCM.
     reader.ReadUint32();  // Channel map: we do not care.
     uint32 guid1 = reader.ReadUint32(),
            guid2 = reader.ReadUint32(),
            guid3 = reader.ReadUint32(),
            guid4 = reader.ReadUint32();
     fmt_chunk_read = 40;
     // Support only KSDATAFORMAT_SUBTYPE_PCM for now. Interesting formats:
     // ("00000001-0000-0010-8000-00aa00389b71", KSDATAFORMAT_SUBTYPE_PCM)
     // ("00000003-0000-0010-8000-00aa00389b71", KSDATAFORMAT_SUBTYPE_IEEE_FLOAT)
     // ("00000006-0000-0010-8000-00aa00389b71", KSDATAFORMAT_SUBTYPE_ALAW)
     // ("00000007-0000-0010-8000-00aa00389b71", KSDATAFORMAT_SUBTYPE_MULAW)
     if (guid1 != 0x00000001 || guid2 != 0x00100000 ||
         guid3 != 0xAA000080 || guid4 != 0x719B3800) {
       KALDI_ERR << "WaveData: unsupported WAVE_FORMAT_EXTENSIBLE format.";
     }
   } else {
     KALDI_ERR << "WaveData: can read only PCM data, format id in file is: "
               << audio_format;
   }
   for (uint32 i = fmt_chunk_read; i < subchunk1_size; ++i)
     is.get();  // use up extra data.
   if (num_channels_ == 0)
     KALDI_ERR << "WaveData: no channels present";
   if (bits_per_sample != 16)
     KALDI_ERR << "WaveData: unsupported bits_per_sample = " << bits_per_sample;
   if (byte_rate != sample_rate * bits_per_sample/8 * num_channels_)
     KALDI_ERR << "Unexpected byte rate " << byte_rate << " vs. "
               << sample_rate << " * " << (bits_per_sample/8)
               << " * " << num_channels_;
   if (block_align != num_channels_ * bits_per_sample/8)
     KALDI_ERR << "Unexpected block_align: " << block_align << " vs. "
               << num_channels_ << " * " << (bits_per_sample/8);
   riff_chunk_read += 4 + subchunk1_size;
   // size of what we just read, 4 for subchunk1_size + subchunk1_size itself.
   // We support an optional "fact" chunk (which is useless but which
   // we encountered), and then a single "data" chunk.
   reader.Read4ByteTag();
   riff_chunk_read += 4;
   // Skip any subchunks between "fmt" and "data".  Usually there will
   // be a single "fact" subchunk, but on Windows there can also be a
   // "list" subchunk.
   while (strcmp(reader.tag, "data") != 0) {
     // We will just ignore the data in these chunks.
     uint32 chunk_sz = reader.ReadUint32();
     if (chunk_sz != 4 && strcmp(reader.tag, "fact") == 0)
       KALDI_WARN << "Expected fact chunk to be 4 bytes long.";
     for (uint32 i = 0; i < chunk_sz; i++)
       is.get();
     riff_chunk_read += 4 + chunk_sz;  // for chunk_sz (4) + chunk contents (chunk-sz)
     // Now read the next chunk name.
     reader.Read4ByteTag();
     riff_chunk_read += 4;
   }
   KALDI_ASSERT(strcmp(reader.tag, "data") == 0);
   uint32 data_chunk_size = reader.ReadUint32();
   riff_chunk_read += 4;
   // Figure out if the file is going to be read to the end. Values as
   // observed in the wild:
   bool is_stream_mode =
       riff_chunk_size == 0
       || riff_chunk_size == 0xFFFFFFFF
       || data_chunk_size == 0
       || data_chunk_size == 0xFFFFFFFF
       || data_chunk_size == 0x7FFFF000;  // This value is used by SoX.
   if (is_stream_mode)
     KALDI_VLOG(1) << "Read in RIFF chunk size: " << riff_chunk_size
                   << ", data chunk size: " << data_chunk_size
                   << ". Assume 'stream mode' (reading data to EOF).";
   if (!is_stream_mode
       && std::abs(static_cast<int64>(riff_chunk_read) +
                   static_cast<int64>(data_chunk_size) -
                   static_cast<int64>(riff_chunk_size)) > 1) {
     // We allow the size to be off by one without warning, because there is a
     // weirdness in the format of RIFF files that means that the input may
     // sometimes be padded with 1 unused byte to make the total size even.
     KALDI_WARN << "Expected " << riff_chunk_size << " bytes in RIFF chunk, but "
                << "after first data block there will be " << riff_chunk_read
                << " + " << data_chunk_size << " bytes "
                << "(we do not support reading multiple data chunks).";
   }
   if (is_stream_mode)
     samp_count_ = -1;
   else
     samp_count_ = data_chunk_size / block_align;
 }
ReverseBytes()
bool ReverseBytes () const inline
Is data file byte order different from machine byte order?
Definition at line 92 of file wave-reader.h.
References WaveInfo::Read(), and WaveInfo::reverse_bytes_.
Referenced by WaveData::Read().
 { return reverse_bytes_; }
SampFreq()
BaseFloat SampFreq () const inline
Sample frequency, Hz.
Definition at line 74 of file wave-reader.h.
References WaveInfo::samp_freq_.
Referenced by WaveData::Read().
 { return samp_freq_; }
SampleCount()
uint32 SampleCount () const inline
Number of samples in stream. Invalid if IsStreamed() is true.
Definition at line 77 of file wave-reader.h.
References WaveInfo::samp_count_.
 { return samp_count_; }
Member Data Documentation
num_channels_
uint8 num_channels_ private
Definition at line 101 of file wave-reader.h.
Referenced by WaveInfo::BlockAlign(), and WaveInfo::NumChannels().
reverse_bytes_
bool reverse_bytes_ private
Definition at line 102 of file wave-reader.h.
Referenced by WaveInfo::ReverseBytes().
samp_count_
int32 samp_count_ private
Definition at line 100 of file wave-reader.h.
Referenced by WaveInfo::DataBytes(), WaveInfo::Duration(), WaveInfo::IsStreamed(), and WaveInfo::SampleCount().
samp_freq_
BaseFloat samp_freq_ private
Definition at line 99 of file wave-reader.h.
Referenced by WaveData::Clear(), WaveData::CopyFrom(), WaveInfo::Duration(), WaveData::Duration(), WaveInfo::SampFreq(), WaveData::SampFreq(), and WaveData::Swap().
The documentation for this class was generated from the following files:
feat/wave-reader.h
feat/wave-reader.cc