Kaldi: DecodableNnetLoopedOnline Class Reference
DecodableNnetLoopedOnline Class Reference
#include <decodable-online-looped.h>
Public Member Functions
DecodableNnetLoopedOnline (const DecodableNnetSimpleLoopedInfo &info, OnlineFeatureInterface *input_features, OnlineFeatureInterface *ivector_features)
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
virtual BaseFloat LogLikelihood (int32 subsampled_frame, int32 index)
Returns the log likelihood, which will be negated in the decoder.
Public Member Functions inherited from DecodableNnetLoopedOnlineBase
DecodableNnetLoopedOnlineBase (const DecodableNnetSimpleLoopedInfo &info, OnlineFeatureInterface *input_features, OnlineFeatureInterface *ivector_features)
virtual bool IsLastFrame (int32 subsampled_frame) const
Returns true if this is the last frame.
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
int32 FrameSubsamplingFactor () const
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableNnetLoopedOnline)
Additional Inherited Members
Protected Member Functions inherited from DecodableNnetLoopedOnlineBase
void EnsureFrameIsComputed (int32 subsampled_frame)
If the neural-network outputs for this frame are not cached, this function computes them (and possibly also some later frames).
Protected Attributes inherited from DecodableNnetLoopedOnlineBase
Matrix< BaseFloat > current_log_post_
int32 num_chunks_computed_
int32 current_log_post_subsampled_offset_
const DecodableNnetSimpleLoopedInfo & info_
Detailed Description
Definition at line 137 of file decodable-online-looped.h.
Constructor & Destructor Documentation
DecodableNnetLoopedOnline()
DecodableNnetLoopedOnline (const DecodableNnetSimpleLoopedInfo & info, OnlineFeatureInterface * input_features, OnlineFeatureInterface * ivector_features) inline
Definition at line 139 of file decodable-online-looped.h.
                                                :
       DecodableNnetLoopedOnlineBase(info, input_features, ivector_features) { }
Member Function Documentation
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableNnetLoopedOnline) private
LogLikelihood()
BaseFloat LogLikelihood (int32 frame, int32 index) virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Definition at line 232 of file decodable-online-looped.cc.
References DecodableNnetLoopedOnlineBase::current_log_post_, DecodableNnetLoopedOnlineBase::current_log_post_subsampled_offset_, and DecodableNnetLoopedOnlineBase::EnsureFrameIsComputed().
{
   EnsureFrameIsComputed(subsampled_frame);
   // note: we index by 'inde
   return current_log_post_(
       subsampled_frame - current_log_post_subsampled_offset_,
       index - 1);
 }
NumIndices()
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst).
Implements DecodableInterface.
Definition at line 147 of file decodable-online-looped.h.
References DecodableNnetLoopedOnlineBase::info_, DecodableNnetLoopedOnlineBase::KALDI_DISALLOW_COPY_AND_ASSIGN(), DecodableInterface::LogLikelihood(), and DecodableNnetSimpleLoopedInfo::output_dim.
 { return info_.output_dim; }
The documentation for this class was generated from the following files:
nnet3/decodable-online-looped.h
nnet3/decodable-online-looped.cc