Kaldi: LinearVtln Class Reference
LinearVtln Class Reference
#include <lvtln.h>
Public Member Functions
LinearVtln ()
LinearVtln (int32 dim, int32 num_classes, int32 default_class)
void SetTransform (int32 i, const MatrixBase< BaseFloat > &transform)
void SetWarp (int32 i, BaseFloat warp)
BaseFloat GetWarp (int32 i) const
void GetTransform (int32 i, MatrixBase< BaseFloat > *transform) const
void ComputeTransform (const FmllrDiagGmmAccs &accs, std::string norm_type, BaseFloat logdet_scale, MatrixBase< BaseFloat > *Ws, int32 *class_idx, BaseFloat *logdet_out, BaseFloat *objf_impr=NULL, BaseFloat *count=NULL)
Compute the transform for the speaker.
void Read (std::istream &is, bool binary)
void Write (std::ostream &os, bool binary) const
int32 Dim () const
int32 NumClasses () const
void GetOffset (const FmllrDiagGmmAccs &speaker_stats, int32 class_idx, VectorBase< BaseFloat > *offset) const
Protected Attributes
int32 default_class_
std::vector< Matrix< BaseFloat > > A_
std::vector< BaseFloat > logdets_
std::vector< BaseFloat > warps_
Friends
class LinearVtlnStats
Detailed Description
Definition at line 40 of file lvtln.h.
Constructor & Destructor Documentation
LinearVtln() [1/2]
LinearVtln () inline
Definition at line 42 of file lvtln.h.
References LinearVtln::ComputeTransform(), count, LinearVtln::GetTransform(), LinearVtln::GetWarp(), rnnlm::i, LinearVtln::Read(), LinearVtln::SetTransform(), LinearVtln::SetWarp(), and LinearVtln::Write().
 { } // This initializer will probably be used prior to calling
LinearVtln() [2/2]
LinearVtln (int32 dim, int32 num_classes, int32 default_class)
Definition at line 29 of file lvtln.cc.
References LinearVtln::A_, LinearVtln::default_class_, rnnlm::i, KALDI_ASSERT, LinearVtln::logdets_, and LinearVtln::warps_.
{
   default_class_ = default_class;
   KALDI_ASSERT(default_class >= 0 && default_class < num_classes);
   A_.resize(num_classes);
   for (int32 i = 0; i < num_classes; i++) {
     A_[i].Resize(dim, dim);
     A_[i].SetUnit();
   }
   logdets_.clear();
   logdets_.resize(num_classes, 0.0);
   warps_.clear();
   warps_.resize(num_classes, 1.0);
 } // namespace kaldi
Member Function Documentation
ComputeTransform()
void ComputeTransform (const FmllrDiagGmmAccs & accs, std::string norm_type, BaseFloat logdet_scale, MatrixBase< BaseFloat > * Ws, int32 * class_idx, BaseFloat * logdet_out, BaseFloat * objf_impr = NULL, BaseFloat * count = NULL)
Compute the transform for the speaker.
Definition at line 97 of file lvtln.cc.
References LinearVtln::A_, kaldi::ApplyFeatureTransformToStats(), AffineXformStats::beta_, kaldi::ComposeTransforms(), kaldi::ComputeFmllrMatrixDiagGmm(), MatrixBase< Real >::CopyFromMat(), LinearVtln::default_class_, LinearVtln::Dim(), kaldi::FmllrAuxFuncDiagGmm(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, KALDI_WARN, LinearVtln::logdets_, LinearVtln::NumClasses(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::Range(), and MatrixBase< Real >::SetUnit().
Referenced by LinearVtln::LinearVtln(), and main().
{
   int32 dim = Dim();
   KALDI_ASSERT(dim != 0);
   if (norm_type != "none"  && norm_type != "offset" && norm_type != "diag")
     KALDI_ERR << "LinearVtln::ComputeTransform, norm_type should be "
         "one of \"none\", \"offset\" or \"diag\"";
   if (accs.beta_ == 0.0) {
     KALDI_WARN << "no stats, returning default transform";
     int32 dim = Dim();
     if (Ws) {
       KALDI_ASSERT(Ws->NumRows() == dim && Ws->NumCols() == dim+1);
       Ws->Range(0, dim, 0, dim).CopyFromMat(A_[default_class_]);
       Ws->Range(0, dim, dim, 1).SetZero();  // Set last column to zero.
     }
     if (class_idx) *class_idx = default_class_;
     if (logdet_out) *logdet_out = logdets_[default_class_];
     if (objf_impr) *objf_impr = 0;
     if (count) *count = 0;
     return;
   }
   Matrix<BaseFloat> best_transform(dim, dim+1);
   best_transform.SetUnit();
   BaseFloat old_objf = FmllrAuxFuncDiagGmm(best_transform, accs),
       best_objf = -1.0e+100;
   int32 best_class = -1;
   for (int32 i = 0; i < NumClasses(); i++) {
     FmllrDiagGmmAccs accs_tmp(accs);
     ApplyFeatureTransformToStats(A_[i], &accs_tmp);
     // "old_trans" just needed by next function as "initial" transform.
     Matrix<BaseFloat> old_trans(dim, dim+1); old_trans.SetUnit();
     Matrix<BaseFloat> trans(dim, dim+1);
     ComputeFmllrMatrixDiagGmm(old_trans, accs_tmp, norm_type,
                               100,  // num iters.. don't care since norm_type != "full"
                               &trans);
     Matrix<BaseFloat> product(dim, dim+1);
     // product = trans * A_[i] (modulo messing about with offsets)
     ComposeTransforms(trans, A_[i], false, &product);
     BaseFloat objf = FmllrAuxFuncDiagGmm(product, accs);
     if (logdet_scale != 1.0)
       objf += accs.beta_ * (logdet_scale - 1.0) * logdets_[i];
     if (objf > best_objf) {
       best_objf = objf;
       best_class = i;
       best_transform.CopyFromMat(product);
     }
   }
   KALDI_ASSERT(best_class != -1);
   if (Ws) Ws->CopyFromMat(best_transform);
   if (class_idx) *class_idx = best_class;
   if (logdet_out) *logdet_out = logdets_[best_class];
   if (objf_impr) *objf_impr = best_objf - old_objf;
   if (count) *count = accs.beta_;
 }
Dim()
int32 Dim () const inline
Definition at line 77 of file lvtln.h.
References LinearVtln::A_, and KALDI_ASSERT.
Referenced by LinearVtln::ComputeTransform(), LinearVtln::GetTransform(), main(), and LinearVtln::SetTransform().
 { KALDI_ASSERT(!A_.empty()); return A_[0].NumRows(); }
GetOffset()
void GetOffset (const FmllrDiagGmmAccs & speaker_stats, int32 class_idx, VectorBase< BaseFloat > * offset) const
Referenced by LinearVtln::NumClasses().
GetTransform()
void GetTransform (int32 i, MatrixBase< BaseFloat > * transform) const
Definition at line 185 of file lvtln.cc.
References LinearVtln::A_, MatrixBase< Real >::CopyFromMat(), LinearVtln::Dim(), KALDI_ASSERT, LinearVtln::NumClasses(), MatrixBase< Real >::NumCols(), and MatrixBase< Real >::NumRows().
Referenced by LinearVtln::LinearVtln().
{
   KALDI_ASSERT(i >= 0 && i < NumClasses());
   KALDI_ASSERT(transform->NumRows() == transform->NumCols() &&
                static_cast<int32>(transform->NumRows()) == Dim());
   transform->CopyFromMat(A_[i]);
 }
GetWarp()
BaseFloat GetWarp (int32 i) const
Definition at line 180 of file lvtln.cc.
References rnnlm::i, KALDI_ASSERT, LinearVtln::NumClasses(), and LinearVtln::warps_.
Referenced by LinearVtln::LinearVtln(), and main().
{
   KALDI_ASSERT(i >= 0 && i < NumClasses());
   return warps_[i];
 }
NumClasses()
int32 NumClasses () const inline
Definition at line 78 of file lvtln.h.
References LinearVtln::A_, and LinearVtln::GetOffset().
Referenced by LinearVtln::ComputeTransform(), LinearVtln::GetTransform(), LinearVtln::GetWarp(), main(), LinearVtln::SetTransform(), and LinearVtln::SetWarp().
 { return A_.size(); }
Read()
void Read (std::istream & is, bool binary)
Definition at line 45 of file lvtln.cc.
References LinearVtln::A_, LinearVtln::default_class_, kaldi::ExpectToken(), rnnlm::i, KALDI_ASSERT, LinearVtln::logdets_, kaldi::ReadBasicType(), kaldi::ReadToken(), and LinearVtln::warps_.
Referenced by LinearVtln::LinearVtln().
{
   int32 sz;
   ExpectToken(is, binary, "<LinearVtln>");
   ReadBasicType(is, binary, &sz);
   A_.resize(sz);
   logdets_.resize(sz);
   warps_.resize(sz);
   for (int32 i = 0; i < sz; i++) {
     ExpectToken(is, binary, "<A>");
     A_[i].Read(is, binary);
     ExpectToken(is, binary, "<logdet>");
     ReadBasicType(is, binary, &(logdets_[i]));
     ExpectToken(is, binary, "<warp>");
     ReadBasicType(is, binary, &(warps_[i]));
   }
   std::string token;
   ReadToken(is, binary, &token);
   if (token == "</LinearVtln>") {
     // the older code had a bug in that it wasn't writing or reading
     // default_class_.  The following guess at its value is likely to be
     // correct.
     default_class_ = (sz + 1) / 2;
   } else {
     KALDI_ASSERT(token == "<DefaultClass>");
     ReadBasicType(is, binary, &default_class_);
     ExpectToken(is, binary, "</LinearVtln>");
   }
 }
SetTransform()
void SetTransform (int32 i, const MatrixBase< BaseFloat > & transform)
Definition at line 166 of file lvtln.cc.
References LinearVtln::A_, LinearVtln::Dim(), rnnlm::i, KALDI_ASSERT, LinearVtln::logdets_, LinearVtln::NumClasses(), MatrixBase< Real >::NumCols(), and MatrixBase< Real >::NumRows().
Referenced by LinearVtln::LinearVtln(), and main().
{
   KALDI_ASSERT(i >= 0 && i < NumClasses());
   KALDI_ASSERT(transform.NumRows() == transform.NumCols() &&
                static_cast<int32>(transform.NumRows()) == Dim());
   A_[i].CopyFromMat(transform);
   logdets_[i] = A_[i].LogDet();
 }
SetWarp()
void SetWarp (int32 i, BaseFloat warp)
Definition at line 174 of file lvtln.cc.
References rnnlm::i, KALDI_ASSERT, LinearVtln::NumClasses(), and LinearVtln::warps_.
Referenced by LinearVtln::LinearVtln(), and main().
{
   KALDI_ASSERT(i >= 0 && i < NumClasses());
   KALDI_ASSERT(warps_.size() == static_cast<size_t>(NumClasses()));
   warps_[i] = warp;
 }
Write()
void Write (std::ostream & os, bool binary) const
Definition at line 74 of file lvtln.cc.
References LinearVtln::A_, LinearVtln::default_class_, rnnlm::i, KALDI_ASSERT, LinearVtln::logdets_, LinearVtln::warps_, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by LinearVtln::LinearVtln(), and main().
{
   WriteToken(os, binary, "<LinearVtln>");
   if(!binary) os << "\n";
   int32 sz = A_.size();
   KALDI_ASSERT(static_cast<size_t>(sz) == logdets_.size());
   KALDI_ASSERT(static_cast<size_t>(sz) == warps_.size());
   WriteBasicType(os, binary, sz);
   for (int32 i = 0; i < sz; i++) {
     WriteToken(os, binary, "<A>");
     A_[i].Write(os, binary);
     WriteToken(os, binary, "<logdet>");
     WriteBasicType(os, binary, logdets_[i]);
     WriteToken(os, binary, "<warp>");
     WriteBasicType(os, binary, warps_[i]);
     if(!binary) os << "\n";
   }
   WriteToken(os, binary, "<DefaultClass>");
   WriteBasicType(os, binary, default_class_);
   WriteToken(os, binary, "</LinearVtln>");
 }
Friends And Related Function Documentation
LinearVtlnStats
friend class LinearVtlnStats friend
Definition at line 85 of file lvtln.h.
Member Data Documentation
A_
std::vector<Matrix<BaseFloat> > A_ protected
Definition at line 88 of file lvtln.h.
Referenced by LinearVtln::ComputeTransform(), LinearVtln::Dim(), LinearVtln::GetTransform(), LinearVtln::LinearVtln(), LinearVtln::NumClasses(), LinearVtln::Read(), LinearVtln::SetTransform(), and LinearVtln::Write().
default_class_
int32 default_class_ protected
Definition at line 87 of file lvtln.h.
Referenced by LinearVtln::ComputeTransform(), LinearVtln::LinearVtln(), LinearVtln::Read(), and LinearVtln::Write().
logdets_
std::vector<BaseFloat> logdets_ protected
Definition at line 89 of file lvtln.h.
Referenced by LinearVtln::ComputeTransform(), LinearVtln::LinearVtln(), LinearVtln::Read(), LinearVtln::SetTransform(), and LinearVtln::Write().
warps_
std::vector<BaseFloat> warps_ protected
Definition at line 90 of file lvtln.h.
Referenced by LinearVtln::GetWarp(), LinearVtln::LinearVtln(), LinearVtln::Read(), LinearVtln::SetWarp(), and LinearVtln::Write().
The documentation for this class was generated from the following files:
transform/lvtln.h
transform/lvtln.cc