Kaldi: GeneralMatrix Class Reference
GeneralMatrix Class Reference
%Matrix and vector classes
This class is a wrapper that enables you to store a matrix in one of three forms: either as a Matrix<BaseFloat>, or a CompressedMatrix, or a SparseMatrix<BaseFloat>.
#include <sparse-matrix.h>
Public Member Functions
GeneralMatrixType Type () const
Returns the type of the matrix: kSparseMatrix, kCompressedMatrix or kFullMatrix.
void Compress ()
void Uncompress ()
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
Note: if you write a compressed matrix in text form, it will be read as a regular full matrix.
const SparseMatrix< BaseFloat > & GetSparseMatrix () const
Returns the contents as a SparseMatrix.
void SwapSparseMatrix (SparseMatrix< BaseFloat > *smat)
Swaps the with the given SparseMatrix.
const CompressedMatrix & GetCompressedMatrix () const
Returns the contents as a compressed matrix.
void SwapCompressedMatrix (CompressedMatrix *cmat)
Swaps the with the given CompressedMatrix.
const Matrix< BaseFloat > & GetFullMatrix () const
Returns the contents as a Matrix<BaseFloat>.
void GetMatrix (Matrix< BaseFloat > *mat) const
Outputs the contents as a matrix.
void SwapFullMatrix (Matrix< BaseFloat > *mat)
Swaps the with the given Matrix.
void CopyToMat (MatrixBase< BaseFloat > *mat, MatrixTransposeType trans=kNoTrans) const
Copies contents, regardless of type, to "mat", which must be correctly sized.
void CopyToMat (CuMatrixBase< BaseFloat > *cu_mat, MatrixTransposeType trans=kNoTrans) const
Copies contents, regardless of type, to "cu_mat", which must be correctly sized.
void AddToMat (BaseFloat alpha, MatrixBase< BaseFloat > *mat, MatrixTransposeType trans=kNoTrans) const
Adds alpha times *this to mat.
void AddToMat (BaseFloat alpha, CuMatrixBase< BaseFloat > *cu_mat, MatrixTransposeType trans=kNoTrans) const
Adds alpha times *this to cu_mat.
void Scale (BaseFloat alpha)
Scale each element of matrix by alpha.
GeneralMatrix & operator= (const MatrixBase< BaseFloat > &mat)
Assignment from regular matrix.
GeneralMatrix & operator= (const CompressedMatrix &mat)
Assignment from compressed matrix.
GeneralMatrix & operator= (const SparseMatrix< BaseFloat > &smat)
Assignment from SparseMatrix<BaseFloat>
MatrixIndexT NumRows () const
MatrixIndexT NumCols () const
GeneralMatrix (const MatrixBase< BaseFloat > &mat)
GeneralMatrix (const CompressedMatrix &cmat)
GeneralMatrix (const SparseMatrix< BaseFloat > &smat)
GeneralMatrix ()
GeneralMatrix & operator= (const GeneralMatrix &other)
GeneralMatrix (const GeneralMatrix &other)
void Clear ()
void Swap (GeneralMatrix *other)
Private Attributes
Matrix< BaseFloat > mat_
CompressedMatrix cmat_
SparseMatrix< BaseFloat > smat_
Detailed Description
This class is a wrapper that enables you to store a matrix in one of three forms: either as a Matrix<BaseFloat>, or a CompressedMatrix, or a SparseMatrix<BaseFloat>.
It handles the I/O for you, i.e. you read and write a single object type. It is useful for neural-net training targets which might be sparse or not, and might be compressed or not.
Definition at line 282 of file sparse-matrix.h.
Constructor & Destructor Documentation
GeneralMatrix() [1/5]
GeneralMatrix (const MatrixBase< BaseFloat > & mat) inline explicit
Definition at line 365 of file sparse-matrix.h.
 { *this = mat; }
GeneralMatrix() [2/5]
GeneralMatrix (const CompressedMatrix & cmat) inline explicit
Definition at line 367 of file sparse-matrix.h.
 { *this = cmat; }
GeneralMatrix() [3/5]
GeneralMatrix (const SparseMatrix< BaseFloat > & smat) inline explicit
Definition at line 369 of file sparse-matrix.h.
 { *this = smat; }
GeneralMatrix() [4/5]
GeneralMatrix () inline
Definition at line 371 of file sparse-matrix.h.
References SparseVector< Real >::operator=().
 { }
GeneralMatrix() [5/5]
GeneralMatrix (const GeneralMatrix & other) inline
Definition at line 375 of file sparse-matrix.h.
References SparseVector< Real >::Swap().
 { *this = other; }
Member Function Documentation
AddToMat() [1/2]
void AddToMat (BaseFloat alpha, MatrixBase< BaseFloat > * mat, MatrixTransposeType trans = kNoTrans) const
Adds alpha times *this to mat.
Definition at line 1144 of file sparse-matrix.cc.
References MatrixBase< Real >::AddMat(), KALDI_ERR, kaldi::kCompressedMatrix, kaldi::kFullMatrix, and kaldi::kSparseMatrix.
{
   switch (this->Type()) {
     case kFullMatrix: {
       mat->AddMat(alpha, mat_, trans);
       break;
     }
     case kSparseMatrix: {
       smat_.AddToMat(alpha, mat, trans);
       break;
     }
     case kCompressedMatrix: {
       Matrix<BaseFloat> temp_mat(cmat_);
       mat->AddMat(alpha, temp_mat, trans);
       break;
     }
     default:
       KALDI_ERR << "Invalid general-matrix type.";
   }
 }
AddToMat() [2/2]
void AddToMat (BaseFloat alpha, CuMatrixBase< BaseFloat > * cu_mat, MatrixTransposeType trans = kNoTrans) const
Adds alpha times *this to cu_mat.
Implemented in ../cudamatrix/cu-sparse-matrix.cc
Definition at line 679 of file cu-sparse-matrix.cc.
References CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::AddSmat(), KALDI_ERR, kaldi::kCompressedMatrix, kaldi::kFullMatrix, kaldi::kSparseMatrix, and CuMatrixBase< Real >::Mat().
{
   switch (Type()) {
     case kFullMatrix: {
 #if HAVE_CUDA == 1
       if (CuDevice::Instantiate().Enabled()) {
         CuMatrix<BaseFloat> cu_copy(mat_);
         cu_mat->AddMat(alpha, cu_copy);
         break;
       }
 #endif
       cu_mat->Mat().AddMat(alpha, mat_);
       break;
     }
     case kSparseMatrix: {
 #if HAVE_CUDA == 1
       if (CuDevice::Instantiate().Enabled()) {
         CuSparseMatrix<BaseFloat> cu_smat(smat_);
         cu_mat->AddSmat(alpha, cu_smat, trans);
         break;
       }
 #endif
       cu_mat->Mat().AddSmat(alpha, smat_, trans);
       break;
     }
     case kCompressedMatrix: {
       Matrix<BaseFloat> mat(cmat_);
 #if HAVE_CUDA == 1
       if (CuDevice::Instantiate().Enabled()) {
         CuMatrix<BaseFloat> cu_mat_copy(mat);
         cu_mat->AddMat(alpha, cu_mat_copy, trans);
         break;
       }
 #endif
       cu_mat->Mat().AddMat(alpha, mat, trans);
       break;
     }
     default:
       KALDI_ERR << "Invalid GeneralMatrix type.";
   }
 }
Clear()
void Clear ()
Definition at line 740 of file sparse-matrix.cc.
Referenced by kaldi::AppendGeneralMatrixRows(), kaldi::ExtractObjectRange(), kaldi::FilterGeneralMatrixRows(), and kaldi::UnitTestGeneralMatrix().
{
   mat_.Resize(0, 0);
   cmat_.Clear();
   smat_.Resize(0, 0);
 }
Compress()
void Compress ()
Definition at line 802 of file sparse-matrix.cc.
Referenced by kaldi::nnet3::GenerateSimpleNnetTrainingExample(), and kaldi::UnitTestGeneralMatrix().
{
   if (mat_.NumRows() != 0) {
     cmat_.CopyFromMat(mat_);
     mat_.Resize(0, 0);
   }
 }
CopyToMat() [1/2]
void CopyToMat (MatrixBase< BaseFloat > * mat, MatrixTransposeType trans = kNoTrans) const
Copies contents, regardless of type, to "mat", which must be correctly sized.
See also GetMatrix(), which will size its output for you.
Definition at line 830 of file sparse-matrix.cc.
References MatrixBase< Real >::CopyFromMat(), KALDI_ASSERT, and MatrixBase< Real >::NumRows().
Referenced by kaldi::AppendGeneralMatrixRows().
{
   if (mat_.NumRows() !=0) {
     mat->CopyFromMat(mat_, trans);
   } else if (cmat_.NumRows() != 0) {
     cmat_.CopyToMat(mat, trans);
   } else if (smat_.NumRows() != 0) {
     smat_.CopyToMat(mat, trans);
   } else {
     KALDI_ASSERT(mat->NumRows() == 0);
   }
 }
CopyToMat() [2/2]
void CopyToMat (CuMatrixBase< BaseFloat > * cu_mat, MatrixTransposeType trans = kNoTrans) const
Copies contents, regardless of type, to "cu_mat", which must be correctly sized.
Implemented in ../cudamatrix/cu-sparse-matrix.cc
Definition at line 582 of file cu-sparse-matrix.cc.
References CuMatrixBase< Real >::CopyFromMat(), CuSparseMatrix< Real >::CopyToMat(), KALDI_ERR, kaldi::kCompressedMatrix, kaldi::kFullMatrix, kaldi::kNoTrans, kaldi::kSparseMatrix, kaldi::kTrans, CuMatrixBase< Real >::Mat(), and CuMatrix< Real >::Swap().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     switch (Type()) {
       case kFullMatrix: {
         cu_mat->CopyFromMat(mat_);
         break;
       }
       case kSparseMatrix: {
         CuSparseMatrix<BaseFloat> smat(smat_);
         smat.CopyToMat(cu_mat, trans);
         break;
       }
       case kCompressedMatrix: {
         Matrix<BaseFloat> mat(cmat_);
         if (trans == kNoTrans) {
           cu_mat->CopyFromMat(mat);
           break;
         } else {
           CuMatrix<BaseFloat> temp_cu;
           temp_cu.Swap(&mat);
           cu_mat->CopyFromMat(temp_cu, kTrans);
           break;
         }
       }
       default:
         KALDI_ERR << "Invalid GeneralMatrix type.";
     }
     return;
   } else
 #endif
   {
     CopyToMat(&(cu_mat->Mat()), trans);
   }
 }
GetCompressedMatrix()
const CompressedMatrix & GetCompressedMatrix () const
Returns the contents as a compressed matrix.
This will only work if Type() returns kCompressedMatrix, or NumRows() == 0; otherwise it will crash.
Definition at line 871 of file sparse-matrix.cc.
References KALDI_ERR.
Referenced by kaldi::ExtractObjectRange(), kaldi::ExtractRowRangeWithPadding(), and kaldi::FilterGeneralMatrixRows().
{
   if (mat_.NumRows() != 0 || smat_.NumRows() != 0)
     KALDI_ERR << "GetCompressedMatrix called on GeneralMatrix of wrong type.";
   return cmat_;
 }
GetFullMatrix()
const Matrix< BaseFloat > & GetFullMatrix () const
Returns the contents as a Matrix<BaseFloat>.
This will only work if Type() returns kFullMatrix, or NumRows() == 0; otherwise it will crash.
Definition at line 877 of file sparse-matrix.cc.
References KALDI_ERR.
Referenced by kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), CuMatrixBase< float >::CopyFromGeneralMat(), kaldi::ExtractObjectRange(), kaldi::ExtractRowRangeWithPadding(), and kaldi::FilterGeneralMatrixRows().
{
   if (smat_.NumRows() != 0 || cmat_.NumRows() != 0)
     KALDI_ERR << "GetFullMatrix called on GeneralMatrix of wrong type.";
   return mat_;
 }
GetMatrix()
void GetMatrix (Matrix< BaseFloat > * mat) const
Outputs the contents as a matrix.
This will work regardless of Type(). Sizes its output, unlike CopyToMat().
Definition at line 816 of file sparse-matrix.cc.
References kaldi::kUndefined, and Matrix< Real >::Resize().
Referenced by NnetLdaStatsAccumulator::AccStatsFromOutput(), kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), CuMatrixBase< float >::CopyFromGeneralMat(), kaldi::nnet3::ExampleApproxEqual(), kaldi::ExtractObjectRange(), NnetIo::operator==(), kaldi::nnet3::PerturbImageInNnetExample(), and kaldi::UnitTestGeneralMatrix().
{
   if (mat_.NumRows() !=0) {
     *mat = mat_;
   } else if (cmat_.NumRows() != 0) {
     mat->Resize(cmat_.NumRows(), cmat_.NumCols(), kUndefined);
     cmat_.CopyToMat(mat);
   } else if (smat_.NumRows() != 0) {
     mat->Resize(smat_.NumRows(), smat_.NumCols(), kUndefined);
     smat_.CopyToMat(mat);
   } else {
     mat->Resize(0, 0);
   }
 }
GetSparseMatrix()
const SparseMatrix< BaseFloat > & GetSparseMatrix () const
Returns the contents as a SparseMatrix.
This will only work if Type() returns kSparseMatrix, or NumRows() == 0; otherwise it will crash.
Definition at line 853 of file sparse-matrix.cc.
References KALDI_ERR.
Referenced by NnetLdaStatsAccumulator::AccStatsFromOutput(), kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), CuMatrixBase< float >::CopyFromGeneralMat(), kaldi::ExtractRowRangeWithPadding(), and kaldi::FilterGeneralMatrixRows().
{
   if (mat_.NumRows() != 0 || cmat_.NumRows() != 0)
     KALDI_ERR << "GetSparseMatrix called on GeneralMatrix of wrong type.";
   return smat_;
 }
NumCols()
MatrixIndexT NumCols () const
Definition at line 791 of file sparse-matrix.cc.
Referenced by NnetComputer::AcceptInputs(), NnetLdaStatsAccumulator::AccStatsFromOutput(), kaldi::AppendGeneralMatrixRows(), kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), kaldi::nnet3::GetIoSizes(), NnetIoStructureCompare::operator()(), NnetIo::operator==(), NnetComputeProb::ProcessOutputs(), and kaldi::UnitTestGeneralMatrix().
{
   MatrixIndexT r = smat_.NumCols();
   if (r != 0)
     return r;
   r = cmat_.NumCols();
   if (r != 0)
     return r;
   return mat_.NumCols();
 }
NumRows()
MatrixIndexT NumRows () const
Definition at line 781 of file sparse-matrix.cc.
Referenced by NnetComputer::AcceptInputs(), NnetLdaStatsAccumulator::AccStatsFromOutput(), kaldi::AppendGeneralMatrixRows(), kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), kaldi::nnet3::FilterExample(), kaldi::FilterGeneralMatrixRows(), kaldi::nnet3::GetIoSizes(), main(), NnetIo::NnetIo(), NnetIoStructureCompare::operator()(), NnetIo::operator==(), kaldi::nnet3::ProcessFile(), kaldi::UnitTestGeneralMatrix(), and NnetIo::Write().
{
   MatrixIndexT r = smat_.NumRows();
   if (r != 0)
     return r;
   r = cmat_.NumRows();
   if (r != 0)
     return r;
   return mat_.NumRows();
 }
operator=() [1/4]
GeneralMatrix & operator= (const MatrixBase< BaseFloat > & mat)
Assignment from regular matrix.
Definition at line 746 of file sparse-matrix.cc.
{
   Clear();
   mat_ = mat;
   return *this;
 }
operator=() [2/4]
GeneralMatrix & operator= (const CompressedMatrix & mat)
Assignment from compressed matrix.
Definition at line 752 of file sparse-matrix.cc.
{
   Clear();
   cmat_ = cmat;
   return *this;
 }
operator=() [3/4]
GeneralMatrix & operator= (const SparseMatrix< BaseFloat > & smat)
Assignment from SparseMatrix<BaseFloat>
Definition at line 758 of file sparse-matrix.cc.
{
   Clear();
   smat_ = smat;
   return *this;
 }
operator=() [4/4]
GeneralMatrix & operator= (const GeneralMatrix & other)
Definition at line 764 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, GeneralMatrix::mat_, and GeneralMatrix::smat_.
{
   mat_ = gmat.mat_;
   smat_ = gmat.smat_;
   cmat_ = gmat.cmat_;
   return *this;
 }
Read()
void Read (std::istream & is, bool binary)
Note: if you write a compressed matrix in text form, it will be read as a regular full matrix.
Definition at line 900 of file sparse-matrix.cc.
Referenced by NnetIo::Read(), and kaldi::UnitTestGeneralMatrix().
{
   Clear();
   if (binary) {
     int peekval = is.peek();
     if (peekval == 'C') {
       // Token CM for compressed matrix
       cmat_.Read(is, binary);
     } else if (peekval == 'S') {
       // Token SM for sparse matrix
       smat_.Read(is, binary);
     } else {
       mat_.Read(is, binary);
     }
   } else {
     // note: in text mode we will only ever read regular
     // or sparse matrices, because the compressed-matrix format just
     // gets written as a regular matrix in text mode.
     is >> std::ws;  // Eat up white space.
     int peekval = is.peek();
     if (peekval == 'r') {  // sparse format starts rows=[int].
       smat_.Read(is, binary);
     } else {
       mat_.Read(is, binary);
     }
   }
 }
Scale()
void Scale (BaseFloat alpha)
Scale each element of matrix by alpha.
Definition at line 843 of file sparse-matrix.cc.
{
   if (mat_.NumRows() != 0) {
     mat_.Scale(alpha);
   } else if (cmat_.NumRows() != 0) {
     cmat_.Scale(alpha);
   } else if (smat_.NumRows() != 0) {
     smat_.Scale(alpha);
   }
 }
Swap()
void Swap (GeneralMatrix * other)
Definition at line 1225 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, GeneralMatrix::mat_, and GeneralMatrix::smat_.
Referenced by NnetIo::Swap().
{
   mat_.Swap(&(other->mat_));
   cmat_.Swap(&(other->cmat_));
   smat_.Swap(&(other->smat_));
 }
SwapCompressedMatrix()
void SwapCompressedMatrix (CompressedMatrix * cmat)
Swaps the with the given CompressedMatrix.
This will only work if Type() returns kCompressedMatrix, or NumRows() == 0.
Definition at line 865 of file sparse-matrix.cc.
References KALDI_ERR, and CompressedMatrix::Swap().
Referenced by kaldi::ExtractRowRangeWithPadding().
{
   if (mat_.NumRows() != 0 || smat_.NumRows() != 0)
     KALDI_ERR << "GetSparseMatrix called on GeneralMatrix of wrong type.";
   cmat->Swap(&cmat_);
 }
SwapFullMatrix()
void SwapFullMatrix (Matrix< BaseFloat > * mat)
Swaps the with the given Matrix.
This will only work if Type() returns kFullMatrix, or NumRows() == 0.
Definition at line 884 of file sparse-matrix.cc.
References KALDI_ERR, and Matrix< Real >::Swap().
Referenced by kaldi::AppendGeneralMatrixRows(), kaldi::ExtractObjectRange(), kaldi::ExtractRowRangeWithPadding(), and kaldi::FilterGeneralMatrixRows().
{
   if (cmat_.NumRows() != 0 || smat_.NumRows() != 0)
     KALDI_ERR << "SwapMatrix called on GeneralMatrix of wrong type.";
   mat->Swap(&mat_);
 }
SwapSparseMatrix()
void SwapSparseMatrix (SparseMatrix< BaseFloat > * smat)
Swaps the with the given SparseMatrix.
This will only work if Type() returns kSparseMatrix, or NumRows() == 0.
Definition at line 859 of file sparse-matrix.cc.
References KALDI_ERR, and SparseMatrix< Real >::Swap().
Referenced by kaldi::AppendGeneralMatrixRows(), kaldi::ExtractRowRangeWithPadding(), kaldi::FilterGeneralMatrixRows(), and kaldi::UnitTestGeneralMatrix().
{
   if (mat_.NumRows() != 0 || cmat_.NumRows() != 0)
     KALDI_ERR << "GetSparseMatrix called on GeneralMatrix of wrong type.";
   smat->Swap(&smat_);
 }
Type()
GeneralMatrixType Type () const
Returns the type of the matrix: kSparseMatrix, kCompressedMatrix or kFullMatrix.
If this matrix is empty, returns kFullMatrix.
Definition at line 772 of file sparse-matrix.cc.
References kaldi::kCompressedMatrix, kaldi::kFullMatrix, and kaldi::kSparseMatrix.
Referenced by NnetLdaStatsAccumulator::AccStatsFromOutput(), kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), CuMatrixBase< float >::CopyFromGeneralMat(), kaldi::ExtractObjectRange(), kaldi::ExtractRowRangeWithPadding(), and kaldi::FilterGeneralMatrixRows().
{
   if (smat_.NumRows() != 0)
     return kSparseMatrix;
   else if (cmat_.NumRows() != 0)
     return kCompressedMatrix;
   else
     return kFullMatrix;
 }
Uncompress()
void Uncompress ()
Definition at line 809 of file sparse-matrix.cc.
{
   if (cmat_.NumRows() != 0) {
     cmat_.CopyToMat(&mat_);
     cmat_.Clear();
   }
 }
Write()
void Write (std::ostream & os, bool binary) const
Definition at line 890 of file sparse-matrix.cc.
Referenced by kaldi::UnitTestGeneralMatrix(), and NnetIo::Write().
{
   if (smat_.NumRows() != 0) {
     smat_.Write(os, binary);
   } else if (cmat_.NumRows() != 0) {
     cmat_.Write(os, binary);
   } else {
     mat_.Write(os, binary);
   }
 }
Member Data Documentation
cmat_
CompressedMatrix cmat_ private
Definition at line 385 of file sparse-matrix.h.
Referenced by GeneralMatrix::operator=(), and GeneralMatrix::Swap().
mat_
Matrix<BaseFloat> mat_ private
Definition at line 384 of file sparse-matrix.h.
Referenced by GeneralMatrix::operator=(), and GeneralMatrix::Swap().
smat_
SparseMatrix<BaseFloat> smat_ private
Definition at line 386 of file sparse-matrix.h.
Referenced by GeneralMatrix::operator=(), and GeneralMatrix::Swap().
The documentation for this class was generated from the following files:
matrix/sparse-matrix.h
matrix/sparse-matrix.cc
cudamatrix/cu-sparse-matrix.cc