Kaldi: TdnnComponent Class Reference
TdnnComponent Class Reference
TdnnComponent is a more memory-efficient alternative to manually splicing several frames of input and then using a NaturalGradientAffineComponent or a LinearComponent.
#include <nnet-convolutional-component.h>
Classes
class PrecomputedIndexes
Public Member Functions
TdnnComponent ()
TdnnComponent (const TdnnComponent &other)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
virtual void FreezeNaturalGradient (bool freeze)
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
CuMatrixBase< BaseFloat > & LinearParams ()
CuVector< BaseFloat > & BiasParams ()
BaseFloat OrthonormalConstraint () const
void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
Component ()
virtual ~Component ()
Private Member Functions
void Check () const
void UpdateNaturalGradient (const PrecomputedIndexes &indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
void UpdateSimple (const PrecomputedIndexes &indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
Static Private Member Functions
static CuSubMatrix< BaseFloat > GetInputPart (const CuMatrixBase< BaseFloat > &input_matrix, int32 num_output_rows, int32 row_stride, int32 row_offset)
static void ModifyComputationIo (time_height_convolution::ConvolutionComputationIo *io)
Private Attributes
std::vector< int32 > time_offsets_
CuMatrix< BaseFloat > linear_params_
CuVector< BaseFloat > bias_params_
BaseFloat orthonormal_constraint_
bool use_natural_gradient_
OnlineNaturalGradient preconditioner_in_
OnlineNaturalGradient preconditioner_out_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Detailed Description
TdnnComponent is a more memory-efficient alternative to manually splicing several frames of input and then using a NaturalGradientAffineComponent or a LinearComponent.
It does the splicing of the input itself, using mechanisms similar to what TimeHeightConvolutionComponent uses. The implementation is in nnet-tdnn-component.cc
Parameters inherited from UpdatableComponent (see comment above declaration of UpdadableComponent in nnet-component-itf.h for details): learning-rate, learning-rate-factor, max-change
Important parameters:
input-dim The input feature dimension (before splicing).
output-dim The output feature dimension
time-offsets E.g. time-offsets=-1,0,1 or time-offsets=-3,0,3. The time offsets that we require at the input to produce a given output. comparable to the offsets used in TDNNs. They must be unique (no repeats). use-bias Defaults to true, but set to false if you want this to be linear rather than affine in its input.
Extra parameters: orthonormal-constraint=0.0 If you set this to 1.0, then the linear_params_ matrix will be (approximately) constrained during training to have orthonormal rows (or columns, whichever is fewer).. it turns out the real name for this is a "semi-orthogonal" matrix. You can choose a positive nonzero value different than 1.0 to have a scaled semi-orthgonal matrix, i.e. with singular values at the selected value (e.g. 0.5, or 2.0). This is not enforced inside the component itself; you have to call ConstrainOrthonormal() from the training code to do this. All this component does is return the OrthonormalConstraint() value. If you set this to a negative value, it's like saying "for any value", i.e. it will constrain the parameter matrix to be closer to "any alpha" times a semi-orthogonal matrix, without changing its overall norm.
Initialization parameters: param-stddev Standard deviation of the linear parameters of the convolution. Defaults to sqrt(1.0 / (input-dim * the number of time-offsets)) bias-stddev Standard deviation of bias terms. default=0.0. You should not set this if you set use-bias=false.
Natural-gradient related options are below; you won't normally have to set these as the defaults are reasonable.
use-natural-gradient e.g. use-natural-gradient=false (defaults to true). You can set this to false to disable the natural gradient updates (you won't normally want to do this). rank-out Rank used in low-rank-plus-unit estimate of the Fisher-matrix factor that has the dimension (num-rows of linear_params_), which equals output_dim. It defaults to the minimum of 80, or half of the output dim. rank-in Rank used in low-rank-plus-unit estimate of the Fisher matrix factor which has the dimension (num-cols of the parameter matrix), which is input-dim times the number of time offsets. It defaults to the minimum of 20, or half the num-rows of the parameter matrix. num-samples-history This becomes the 'num_samples_history' configuration value of the natural gradient objects. The default value is 2000.0.
Definition at line 450 of file nnet-convolutional-component.h.
Constructor & Destructor Documentation
TdnnComponent() [1/2]
TdnnComponent ()
Definition at line 33 of file nnet-tdnn-component.cc.
                             :
     orthonormal_constraint_(0.0),
     use_natural_gradient_(true) { }
TdnnComponent() [2/2]
TdnnComponent (const TdnnComponent & other)
Definition at line 38 of file nnet-tdnn-component.cc.
References TdnnComponent::Check().
                                :
     UpdatableComponent(other),  // initialize base-class
     time_offsets_(other.time_offsets_),
     linear_params_(other.linear_params_),
     bias_params_(other.bias_params_),
     orthonormal_constraint_(other.orthonormal_constraint_),
     use_natural_gradient_(other.use_natural_gradient_),
     preconditioner_in_(other.preconditioner_in_),
     preconditioner_out_(other.preconditioner_out_) {
   Check();
 }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 607 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, KALDI_ASSERT, and TdnnComponent::linear_params_.
{
   const TdnnComponent *other =
       dynamic_cast<const TdnnComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   linear_params_.AddMat(alpha, other->linear_params_);
   if (bias_params_.Dim() != 0)
     bias_params_.AddVec(alpha, other->bias_params_);
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 213 of file nnet-tdnn-component.cc.
References CuMatrixBase< Real >::AddMatMat(), TdnnComponent::GetInputPart(), rnnlm::i, TdnnComponent::InputDim(), UpdatableComponent::is_gradient_, KALDI_ASSERT, kaldi::kNoTrans, UpdatableComponent::learning_rate_, TdnnComponent::linear_params_, CuMatrixBase< Real >::NumRows(), TdnnComponent::PrecomputedIndexes::row_offsets, TdnnComponent::PrecomputedIndexes::row_stride, TdnnComponent::time_offsets_, TdnnComponent::UpdateNaturalGradient(), TdnnComponent::UpdateSimple(), and TdnnComponent::use_natural_gradient_.
{
   const PrecomputedIndexes *indexes =
       dynamic_cast<const PrecomputedIndexes*>(indexes_in);
   KALDI_ASSERT(indexes != NULL &&
                indexes->row_offsets.size() == time_offsets_.size());
   int32 num_offsets = time_offsets_.size(),
       input_dim = InputDim();
   if (in_deriv != NULL) {
     // Propagate the derivatives back to the input data.
     for (int32 i = 0; i < num_offsets; i++) {
       CuSubMatrix<BaseFloat> in_deriv_part =
           GetInputPart(*in_deriv, out_deriv.NumRows(),
                        indexes->row_stride, indexes->row_offsets[i]);
       CuSubMatrix<BaseFloat> linear_params_part(linear_params_,
                                                 0, linear_params_.NumRows(),
                                                 i * input_dim, input_dim);
       // note: this component has the property kBackpropAdds, which is why the
       // final 1.0 is there in the following call (otherwise we'd have to zero
       // *in_deriv first).
       in_deriv_part.AddMatMat(1.0, out_deriv, kNoTrans,
                               linear_params_part, kNoTrans, 1.0);
     }
   }
   if (to_update_in != NULL) {
     TdnnComponent *to_update =
         dynamic_cast<TdnnComponent*>(to_update_in);
     KALDI_ASSERT(to_update != NULL);
     if (to_update->learning_rate_ == 0.0)
       return;
     if (to_update->is_gradient_ || !to_update->use_natural_gradient_)
       to_update->UpdateSimple(*indexes, in_value, out_deriv);
     else
       to_update->UpdateNaturalGradient(*indexes, in_value, out_deriv);
   }
 }
BiasParams()
CuVector<BaseFloat>& BiasParams () inline
Definition at line 558 of file nnet-convolutional-component.h.
References TimeHeightConvolutionComponent::bias_params_.
Referenced by ModelCollapser::GetDiagonallyPreModifiedComponentIndex().
 { return bias_params_; }
Check()
void Check () const private
Definition at line 52 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, KALDI_ASSERT, TdnnComponent::linear_params_, and TdnnComponent::time_offsets_.
Referenced by TdnnComponent::Read(), and TdnnComponent::TdnnComponent().
{
   KALDI_ASSERT(linear_params_.NumRows() > 0 &&
                !time_offsets_.empty() &&
                std::set<int32>(time_offsets_.begin(),
                                time_offsets_.end()).size() ==
                time_offsets_.size() &&
                linear_params_.NumCols() % time_offsets_.size() == 0 &&
                (bias_params_.Dim() == 0 ||
                 bias_params_.Dim() == linear_params_.NumRows()));
 }
ConsolidateMemory()
void ConsolidateMemory () virtual
This virtual function relates to memory management, and avoiding fragmentation.
It is called only once per model, after we do the first minibatch of training. The default implementation does nothing, but it can be overridden by child classes, where it may re-initialize certain quantities that may possibly have been allocated during the forward pass (e.g. certain statistics; OnlineNaturalGradient objects). We use our own CPU-based allocator (see cu-allocator.h) and since it can't do paging since we're not in control of the GPU page table, fragmentation can be a problem. The allocator always tries to put things in 'low-address memory' (i.e. at smaller memory addresses) near the beginning of the block it allocated, to avoid fragmentation; but if permanent things (belonging to the model) are allocated in the forward pass, they can permanently stay in high memory. This function helps to prevent that, by re-allocating those things into low-address memory (It's important that it's called after all the temporary buffers for the forward-backward have been freed, so that there is low-address memory available)).
Reimplemented from Component.
Definition at line 697 of file nnet-tdnn-component.cc.
References TdnnComponent::preconditioner_in_, TdnnComponent::preconditioner_out_, and OnlineNaturalGradient::Swap().
{
   OnlineNaturalGradient temp_in(preconditioner_in_);
   preconditioner_in_.Swap(&temp_in);
   OnlineNaturalGradient temp_out(preconditioner_out_);
   preconditioner_out_.Swap(&temp_out);
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 486 of file nnet-convolutional-component.h.
References TimeHeightConvolutionComponent::Add(), TimeHeightConvolutionComponent::DotProduct(), TimeHeightConvolutionComponent::FreezeNaturalGradient(), TimeHeightConvolutionComponent::GetInputIndexes(), TimeHeightConvolutionComponent::IsComputable(), TimeHeightConvolutionComponent::NumParameters(), TimeHeightConvolutionComponent::PerturbParams(), TimeHeightConvolutionComponent::PrecomputeIndexes(), TimeHeightConvolutionComponent::ReorderIndexes(), TimeHeightConvolutionComponent::Scale(), TimeHeightConvolutionComponent::UnVectorize(), and TimeHeightConvolutionComponent::Vectorize().
Referenced by ModelCollapser::GetDiagonallyPreModifiedComponentIndex().
{
     return new TdnnComponent(*this);
   }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 629 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, KALDI_ASSERT, kaldi::kTrans, TdnnComponent::linear_params_, kaldi::TraceMatMat(), and kaldi::VecVec().
{
   const TdnnComponent *other =
       dynamic_cast<const TdnnComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   BaseFloat ans = TraceMatMat(linear_params_, other->linear_params_, kTrans);
   if (bias_params_.Dim() != 0)
     ans += VecVec(bias_params_, other->bias_params_);
   return ans;
 }
FreezeNaturalGradient()
void FreezeNaturalGradient (bool freeze) virtual
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
Reimplemented from UpdatableComponent.
Definition at line 666 of file nnet-tdnn-component.cc.
References OnlineNaturalGradient::Freeze(), TdnnComponent::preconditioner_in_, and TdnnComponent::preconditioner_out_.
{
   preconditioner_in_.Freeze(freeze);
   preconditioner_out_.Freeze(freeze);
 }
GetInputIndexes()
void GetInputIndexes (const MiscComputationInfo & misc_info, const Index & output_index, std::vector< Index > * desired_indexes) const virtual
This function only does something interesting for non-simple Components.
For a given index at the output of the component, tells us what indexes are required at its input (note: "required" encompasses also optionally-required things; it will enumerate all things that we'd like to have). See also IsComputable().
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. We will add members to misc_info as needed.
[in] output_index The Index at the output of the component, for which we are requesting the list of indexes at the component's input.
[out] desired_indexes A list of indexes that are desired at the input. are to be written to here. By "desired" we mean required or optionally-required.
The default implementation of this function is suitable for any SimpleComponent; it just copies the output_index to a single identical element in input_indexes.
Reimplemented from Component.
Definition at line 454 of file nnet-tdnn-component.cc.
References rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kNoTime, Index::n, Index::t, TdnnComponent::time_offsets_, and Index::x.
{
   KALDI_ASSERT(output_index.t != kNoTime);
   size_t size = time_offsets_.size();
   desired_indexes->resize(size);
   for (size_t i = 0; i < size; i++) {
     (*desired_indexes)[i].n = output_index.n;
     (*desired_indexes)[i].t = output_index.t + time_offsets_[i];
     (*desired_indexes)[i].x = output_index.x;
   }
 }
GetInputPart()
CuSubMatrix< BaseFloat > GetInputPart (const CuMatrixBase< BaseFloat > & input_matrix, int32 num_output_rows, int32 row_stride, int32 row_offset) static private
Definition at line 497 of file nnet-tdnn-component.cc.
References CuMatrixBase< Real >::Data(), KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by TdnnComponent::Backprop(), TdnnComponent::Propagate(), TdnnComponent::UpdateNaturalGradient(), and TdnnComponent::UpdateSimple().
{
   KALDI_ASSERT(row_offset >= 0 && row_stride >= 1 &&
                input_matrix.NumRows() >=
                row_offset + (row_stride * num_output_rows) - (row_stride - 1));
   // constructor takes args: (data, num_rows, num_cols, stride).
   return CuSubMatrix<BaseFloat>(
       input_matrix.Data() + input_matrix.Stride() * row_offset,
       num_output_rows,
       input_matrix.NumCols(),
       input_matrix.Stride() * row_stride);
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 63 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, OnlineNaturalGradient::GetAlpha(), OnlineNaturalGradient::GetNumSamplesHistory(), OnlineNaturalGradient::GetRank(), OnlineNaturalGradient::GetUpdatePeriod(), kaldi::GetVerboseLevel(), rnnlm::i, UpdatableComponent::Info(), TdnnComponent::linear_params_, TdnnComponent::orthonormal_constraint_, TdnnComponent::preconditioner_in_, TdnnComponent::preconditioner_out_, kaldi::nnet3::PrintParameterStats(), TdnnComponent::time_offsets_, and TdnnComponent::use_natural_gradient_.
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info();
   if (orthonormal_constraint_ != 0.0)
     stream << ", orthonormal-constraint=" << orthonormal_constraint_;
   stream << ", time-offsets=";
   for (size_t i = 0; i < time_offsets_.size(); i++) {
     if (i != 0) stream << ',';
     stream << time_offsets_[i];
   }
   PrintParameterStats(stream, "linear-params", linear_params_,
                       false, // include_mean
                       true, // include_row_norms
                       true, // include_column_norms
                       GetVerboseLevel() >= 2); // include_singular_values
   if (bias_params_.Dim() == 0) {
     stream << ", has-bias=false";
   } else {
     PrintParameterStats(stream, "bias", bias_params_, true);
   }
   if (!use_natural_gradient_) {
     stream << ", use-natural-gradient=false";
   } else {
     stream << ", rank-in=" << preconditioner_in_.GetRank()
            << ", rank-out=" << preconditioner_out_.GetRank()
            << ", num-samples-history=" << preconditioner_in_.GetNumSamplesHistory()
            << ", update-period=" << preconditioner_in_.GetUpdatePeriod()
            << ", alpha-in=" << preconditioner_in_.GetAlpha()
            << ", alpha-out=" << preconditioner_out_.GetAlpha();
   }
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 97 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, ConfigLine::GetValue(), UpdatableComponent::InitLearningRatesFromConfig(), KALDI_ERR, TdnnComponent::linear_params_, TdnnComponent::orthonormal_constraint_, TdnnComponent::preconditioner_in_, TdnnComponent::preconditioner_out_, OnlineNaturalGradient::SetAlpha(), OnlineNaturalGradient::SetNumSamplesHistory(), OnlineNaturalGradient::SetRank(), OnlineNaturalGradient::SetUpdatePeriod(), kaldi::SplitStringToIntegers(), TdnnComponent::time_offsets_, TdnnComponent::use_natural_gradient_, and ConfigLine::WholeLine().
{
   // 1. Config values inherited from UpdatableComponent.
   InitLearningRatesFromConfig(cfl);
   // 2. Structural config values
   std::string time_offsets;
   int32 input_dim = -1, output_dim = -1;
   bool ok = cfl->GetValue("time-offsets", &time_offsets) &&
       cfl->GetValue("input-dim", &input_dim) &&
       cfl->GetValue("output-dim", &output_dim);
   if (!ok || input_dim <= 0 || output_dim <= 0 ||
       !SplitStringToIntegers(time_offsets, ",", false, &time_offsets_) ||
       time_offsets_.empty()) {
     KALDI_ERR << "Bad initializer: there is a problem with "
         "time-offsets, input-dim or output-dim (not defined?): "
         << cfl->WholeLine();
   }
   if (std::set<int32>(time_offsets_.begin(),
                       time_offsets_.end()).size() != time_offsets_.size()) {
     KALDI_ERR << "Bad initializer: repeated time-offsets: "
               << cfl->WholeLine();
   }
   // 3. Parameter-initialization configs, "has-bias", and
   // orthonormal-constraint.
   orthonormal_constraint_ = 0.0;
   BaseFloat param_stddev = -1, bias_mean = 0.0, bias_stddev = 1.0;
   bool use_bias = true;
   cfl->GetValue("param-stddev", &param_stddev);
   cfl->GetValue("bias-stddev", &bias_stddev);
   cfl->GetValue("bias-mean", &bias_mean);
   cfl->GetValue("use-bias", &use_bias);
   cfl->GetValue("orthonormal-constraint", &orthonormal_constraint_);
   if (param_stddev < 0.0) {
     param_stddev = 1.0 / sqrt(input_dim * time_offsets_.size());
   }
   // initialize the parameters.
   linear_params_.Resize(output_dim,
                         input_dim * time_offsets_.size());
   linear_params_.SetRandn();
   linear_params_.Scale(param_stddev);
   if (use_bias) {
     bias_params_.Resize(output_dim);
     bias_params_.SetRandn();
     bias_params_.Scale(bias_stddev);
     bias_params_.Add(bias_mean);
   } else {
     bias_params_.Resize(0);
   }
   // 4. Natural-gradient related configs.
   use_natural_gradient_ = true;
   int32 rank_out = -1, rank_in = -1;
   BaseFloat alpha_out = 4.0, alpha_in = 4.0,
       num_samples_history = 2000.0;
   cfl->GetValue("use-natural-gradient", &use_natural_gradient_);
   cfl->GetValue("rank-in", &rank_in);
   cfl->GetValue("rank-out", &rank_out);
   cfl->GetValue("alpha-in", &alpha_in);
   cfl->GetValue("alpha-out", &alpha_out);
   cfl->GetValue("num-samples-history", &num_samples_history);
   int32 spliced_input_dim =
       input_dim * static_cast<int32>(time_offsets_.size());
   if (rank_in < 0)
     rank_in = std::min<int32>(20, (spliced_input_dim + 1) / 2);
   preconditioner_in_.SetRank(rank_in);
   if (rank_out < 0)
     rank_out = std::min<int32>(80, (output_dim + 1) / 2);
   preconditioner_out_.SetRank(rank_out);
   preconditioner_in_.SetNumSamplesHistory(num_samples_history);
   preconditioner_out_.SetNumSamplesHistory(num_samples_history);
   preconditioner_in_.SetAlpha(alpha_in);
   preconditioner_out_.SetAlpha(alpha_out);
   preconditioner_in_.SetUpdatePeriod(4);
   preconditioner_out_.SetUpdatePeriod(4);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 459 of file nnet-convolutional-component.h.
References TimeHeightConvolutionComponent::linear_params_.
Referenced by TdnnComponent::Backprop(), and TdnnComponent::Propagate().
{
     return linear_params_.NumCols() / static_cast<int32>(time_offsets_.size());
   }
IsComputable()
bool IsComputable (const MiscComputationInfo & misc_info, const Index & output_index, const IndexSet & input_index_set, std::vector< Index > * used_inputs) const virtual
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
It tells the user whether a given output index is computable from a given set of input indexes, and if so, says which input indexes will be used in the computation.
Implementations of this function are required to have the property that adding an element to "input_index_set" can only ever change IsComputable from false to true, never vice versa.
Parameters
[in] misc_info Some information specific to the computation, such as minimum and maximum times for certain components to do adaptation on; it's a place to put things that don't easily fit in the framework.
[in] output_index The index that is to be computed at the output of this Component.
[in] input_index_set The set of indexes that is available at the input of this Component.
[out] used_inputs If this is non-NULL and the output is computable this will be set to the list of input indexes that will actually be used in the computation.
Returns
Returns true iff this output is computable from the provided inputs.
The default implementation of this function is suitable for any SimpleComponent: it just returns true if output_index is in input_index_set, and if so sets used_inputs to vector containing that one Index.
Reimplemented from Component.
Definition at line 469 of file nnet-tdnn-component.cc.
References rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kNoTime, Index::t, and TdnnComponent::time_offsets_.
{
   KALDI_ASSERT(output_index.t != kNoTime);
   size_t size = time_offsets_.size();
   Index index(output_index);
   if (used_inputs != NULL) {
     used_inputs->clear();
     used_inputs->reserve(size);
   }
   for (size_t i = 0; i < size; i++) {
     index.t = output_index.t + time_offsets_[i];
     if (input_index_set(index)) {
       if (used_inputs != NULL) {
         // This input index is available.
         used_inputs->push_back(index);
       }
     } else {
       return false;
     }
   }
   return true;
 }
LinearParams()
CuMatrixBase<BaseFloat>& LinearParams () inline
Definition at line 554 of file nnet-convolutional-component.h.
References TimeHeightConvolutionComponent::linear_params_.
Referenced by kaldi::nnet3::ConstrainOrthonormal(), and ModelCollapser::GetDiagonallyPreModifiedComponentIndex().
 { return linear_params_; }
ModifyComputationIo()
void ModifyComputationIo (time_height_convolution::ConvolutionComputationIo * io) static private
Definition at line 513 of file nnet-tdnn-component.cc.
References KALDI_ASSERT, rnnlm::n, ConvolutionComputationIo::num_t_in, ConvolutionComputationIo::reorder_t_in, ConvolutionComputationIo::t_step_in, and ConvolutionComputationIo::t_step_out.
Referenced by TdnnComponent::PrecomputeIndexes(), and TdnnComponent::ReorderIndexes().
{
   if (io->t_step_out == 0) {
     // the 't_step' values may be zero if there was only one (input or output)
     // index so the time-stride could not be determined.  This code fixes them
     // up in that case.  (If there was only one value, the stride is a
     // don't-care actually).
     if (io->t_step_in == 0)
       io->t_step_in = 1;
     io->t_step_out = io->t_step_in;
   }
   // At this point the t_step_{in,out} values will be nonzero.
   KALDI_ASSERT(io->t_step_out % io->t_step_in == 0);
   // The following affects the ordering of the input indexes; it allows us to
   // reshape the input matrix in the way that we need to, in cases where there
   // is subsampling.  See the explanation where the variable was declared in
   // class ConvolutionComputationIo.
   io->reorder_t_in = io->t_step_out / io->t_step_in;
   // make sure that num_t_in is a multiple of io->reorder_t_in by rounding up.
   int32 n = io->reorder_t_in;
   io->num_t_in = n * ((io->num_t_in + n - 1) / n);
 }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 640 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, and TdnnComponent::linear_params_.
Referenced by TdnnComponent::UnVectorize(), and TdnnComponent::Vectorize().
{
   // note: bias_param_.Dim() may actually be zero.
   return linear_params_.NumRows() * linear_params_.NumCols() +
       bias_params_.Dim();
 }
OrthonormalConstraint()
BaseFloat OrthonormalConstraint () const inline
Definition at line 560 of file nnet-convolutional-component.h.
References TimeHeightConvolutionComponent::Check(), TimeHeightConvolutionComponent::ConsolidateMemory(), TimeHeightConvolutionComponent::UpdateNaturalGradient(), and TimeHeightConvolutionComponent::UpdateSimple().
Referenced by kaldi::nnet3::ConstrainOrthonormal().
 { return orthonormal_constraint_; }
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 462 of file nnet-convolutional-component.h.
References TimeHeightConvolutionComponent::Info(), TimeHeightConvolutionComponent::InitFromConfig(), and TimeHeightConvolutionComponent::linear_params_.
Referenced by ModelCollapser::GetDiagonallyPreModifiedComponentIndex().
 { return linear_params_.NumRows(); }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 617 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, kaldi::kUndefined, TdnnComponent::linear_params_, CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
{
   CuMatrix<BaseFloat> temp_mat(linear_params_.NumRows(),
                                linear_params_.NumCols(), kUndefined);
   temp_mat.SetRandn();
   linear_params_.AddMat(stddev, temp_mat);
   if (bias_params_.Dim() != 0) {
     CuVector<BaseFloat> temp_vec(bias_params_.Dim(), kUndefined);
     temp_vec.SetRandn();
     bias_params_.AddVec(stddev, temp_vec);
   }
 }
PrecomputeIndexes()
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo & misc_info, const std::vector< Index > & input_indexes, const std::vector< Index > & output_indexes, bool need_backprop) const virtual
This function must return NULL for simple Components.
Returns a pointer to a class that may contain some precomputed component-specific and computation-specific indexes to be in used in the Propagate and Backprop functions.
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. misc_info may not even ever be used here. We will add members to misc_info as needed.
[in] input_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the in/in_value/in_deriv matrices given to Propagate and Backprop will mean.
[in] output_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the out/out_value/out_deriv matrices given to Propagate and Backprop will mean.
[in] need_backprop True if we might need to do backprop with this component, so that if any different indexes are needed for backprop then those should be computed too.
Returns
Returns a child-class of class ComponentPrecomputedIndexes, or NULL if this component for does not need to precompute any indexes (e.g. if it is a simple component and does not care about indexes).
Reimplemented from Component.
Definition at line 537 of file nnet-tdnn-component.cc.
References kaldi::nnet3::time_height_convolution::GetComputationIo(), kaldi::nnet3::time_height_convolution::GetIndexesForComputation(), rnnlm::i, KALDI_ASSERT, TdnnComponent::ModifyComputationIo(), rnnlm::n, kaldi::RandInt(), TdnnComponent::PrecomputedIndexes::row_offsets, TdnnComponent::PrecomputedIndexes::row_stride, and TdnnComponent::time_offsets_.
{
   using namespace time_height_convolution;
   // The following figures out a regular structure for the input and
   // output indexes, in case there were gaps (which is unlikely in typical
   // situations).
   ConvolutionComputationIo io;
   GetComputationIo(input_indexes, output_indexes, &io);
   ModifyComputationIo(&io);
   if (RandInt(0, 10) == 0) {
     // Spot check that the provided indexes have the required properties;
     // this is like calling this->ReorderIndexes() and checking that it
     // doesn't change anything.
     std::vector<Index> modified_input_indexes,
         modified_output_indexes;
     GetIndexesForComputation(io, input_indexes, output_indexes,
                              &modified_input_indexes,
                              &modified_output_indexes);
     KALDI_ASSERT(modified_input_indexes == input_indexes &&
                  modified_output_indexes == output_indexes);
   }
   PrecomputedIndexes *ans = new PrecomputedIndexes();
   ans->row_stride = io.reorder_t_in;
   int32 num_offsets = time_offsets_.size();
   ans->row_offsets.resize(num_offsets);
   for (int32 i = 0; i < num_offsets; i++) {
     // For each offset, work out which row of the input has the same t value as
     // the first t value in the output plus that offset.  That becomes the start
     // row of the corresponding sub-part of the input.
     int32 time_offset = time_offsets_[i],
         required_input_t = io.start_t_out + time_offset,
         input_t = (required_input_t - io.start_t_in) / io.t_step_in;
     KALDI_ASSERT(required_input_t == io.start_t_in + io.t_step_in * input_t);
     // input_t is a kind of normalized time offset in the input, relative to the
     // first 't' value in the input and divided by the t-step in the input, so
     // it's the numbering "as if" the input 't' values were numbered from 0,1,2.
     // To turn input_t into an input row we need to take account of 'reorder_t_in'.
     // If this is 1 then the input row is input_t times io.num_images.
     // Otherwise it's a little more complicated and to understand it you should
     // read the comment where 'reorder_t_in' is declared in convolution.h.
     // Briefly: the part that is an integer multiple of 'reorder_t_in' gets
     // multiplied by io.num_images; the remainder does not.
     int32 n = io.reorder_t_in,
         input_t_multiple = n * (input_t / n), input_t_remainder = input_t % n;
     // note: input_t == input_t_multiple + input_t_remainder .
     int32 input_row_offset = input_t_multiple * io.num_images +
         input_t_remainder;
     ans->row_offsets[i] = input_row_offset;
   }
   return ans;
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 181 of file nnet-tdnn-component.cc.
References CuMatrixBase< Real >::AddMatMat(), TdnnComponent::bias_params_, CuMatrixBase< Real >::CopyRowsFromVec(), TdnnComponent::GetInputPart(), rnnlm::i, TdnnComponent::InputDim(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, TdnnComponent::linear_params_, CuMatrixBase< Real >::NumRows(), TdnnComponent::PrecomputedIndexes::row_offsets, TdnnComponent::PrecomputedIndexes::row_stride, and TdnnComponent::time_offsets_.
{
   const PrecomputedIndexes *indexes =
       dynamic_cast<const PrecomputedIndexes*>(indexes_in);
   KALDI_ASSERT(indexes != NULL);
   if (bias_params_.Dim() != 0)
     out->CopyRowsFromVec(bias_params_);
   // if bias_params_.Dim() == 0 we don't need to zero 'out' at
   // this point because in that case we set the flag kPropagateAdds,
   // so the calling code knows that the Propagate function *adds to*
   // the 'out' matrix, so it should (typicaly) be zeroed before calling
   // Propagate().
   KALDI_ASSERT(indexes->row_offsets.size() == time_offsets_.size());
   int32 num_offsets = time_offsets_.size(),
       input_dim = InputDim();
   for (int32 i = 0; i < num_offsets; i++) {
     CuSubMatrix<BaseFloat> in_part = GetInputPart(in, out->NumRows(),
                                                   indexes->row_stride,
                                                   indexes->row_offsets[i]);
     CuSubMatrix<BaseFloat> linear_params_part(linear_params_,
                                               0, linear_params_.NumRows(),
                                               i * input_dim, input_dim);
     out->AddMatMat(1.0, in_part, kNoTrans, linear_params_part, kTrans, 1.0);
   }
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 467 of file nnet-convolutional-component.h.
References TimeHeightConvolutionComponent::Backprop(), TimeHeightConvolutionComponent::bias_params_, kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kPropagateAdds, kaldi::nnet3::kReordersIndexes, kaldi::nnet3::kUpdatableComponent, TimeHeightConvolutionComponent::Propagate(), TimeHeightConvolutionComponent::PrecomputedIndexes::Read(), and TimeHeightConvolutionComponent::PrecomputedIndexes::Write().
{
     return kUpdatableComponent|kReordersIndexes|kBackpropAdds|
         (bias_params_.Dim() == 0 ? kPropagateAdds : 0)|
         kBackpropNeedsInput;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 407 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, TdnnComponent::Check(), kaldi::nnet3::ExpectToken(), KALDI_ASSERT, TdnnComponent::linear_params_, TdnnComponent::orthonormal_constraint_, TdnnComponent::preconditioner_in_, TdnnComponent::preconditioner_out_, kaldi::ReadBasicType(), kaldi::ReadIntegerVector(), kaldi::ReadToken(), UpdatableComponent::ReadUpdatableCommon(), OnlineNaturalGradient::SetAlpha(), OnlineNaturalGradient::SetNumSamplesHistory(), OnlineNaturalGradient::SetRank(), OnlineNaturalGradient::SetUpdatePeriod(), TdnnComponent::time_offsets_, and TdnnComponent::use_natural_gradient_.
{
   std::string token = ReadUpdatableCommon(is, binary);
   ExpectToken(is, binary, "<TimeOffsets>");
   ReadIntegerVector(is, binary, &time_offsets_);
   ExpectToken(is, binary, "<LinearParams>");
   linear_params_.Read(is, binary);
   ExpectToken(is, binary, "<BiasParams>");
   bias_params_.Read(is, binary);
   ExpectToken(is, binary, "<OrthonormalConstraint>");
   ReadBasicType(is, binary, &orthonormal_constraint_);
   ExpectToken(is, binary, "<UseNaturalGradient>");
   ReadBasicType(is, binary, &use_natural_gradient_);
   int32 rank_in,  rank_out;
   BaseFloat alpha_in, alpha_out,
       num_samples_history;
   ExpectToken(is, binary, "<NumSamplesHistory>");
   ReadBasicType(is, binary, &num_samples_history);
   { // This can be simplified after a while.  It's to read a format of the model
     // that was never checked into master, but with which I (Dan) did many of
     // the experiments while tuning the resnet TDNN-F.
     std::string token;
     ReadToken(is, binary, &token);
     if (token == "<AlphaInOut>") {
       ReadBasicType(is, binary, &alpha_in);
       ReadBasicType(is, binary, &alpha_out);
     } else {
       KALDI_ASSERT(token == "<Alpha>");
       ReadBasicType(is, binary, &alpha_in);
       alpha_out = alpha_in;
     }
   }
   preconditioner_in_.SetAlpha(alpha_in);
   preconditioner_out_.SetAlpha(alpha_out);
   ExpectToken(is, binary, "<RankInOut>");
   ReadBasicType(is, binary, &rank_in);
   ReadBasicType(is, binary, &rank_out);
   preconditioner_in_.SetRank(rank_in);
   preconditioner_out_.SetRank(rank_out);
   preconditioner_in_.SetNumSamplesHistory(num_samples_history);
   preconditioner_out_.SetNumSamplesHistory(num_samples_history);
   // the update periods are not configurable.
   preconditioner_in_.SetUpdatePeriod(4);
   preconditioner_out_.SetUpdatePeriod(4);
   ExpectToken(is, binary, "</TdnnComponent>");
   Check();
 }
ReorderIndexes()
void ReorderIndexes (std::vector< Index > * input_indexes, std::vector< Index > * output_indexes) const virtual
This function only does something interesting for non-simple Components.
It provides an opportunity for a Component to reorder the or pad the indexes at its input and output. This might be useful, for instance, if a component requires a particular ordering of the indexes that doesn't correspond to their natural ordering. Components that might modify the indexes are required to return the kReordersIndexes flag in their Properties(). The ReorderIndexes() function is now allowed to insert blanks into the indexes. The 'blanks' must be of the form (n,kNoTime,x), where the marker kNoTime (a very negative number) is there where the 't' indexes normally live. The reason we don't just have, say, (-1,-1,-1), relates to the need to preserve a regular pattern over the 'n' indexes so that 'shortcut compilation' (c.f. ExpandComputation()) can work correctly
Parameters
[in,out] Indexes at the input of the Component.
[in,out] Indexes at the output of the Component
Reimplemented from Component.
Definition at line 348 of file nnet-tdnn-component.cc.
References kaldi::nnet3::time_height_convolution::GetComputationIo(), kaldi::nnet3::time_height_convolution::GetIndexesForComputation(), and TdnnComponent::ModifyComputationIo().
{
   using namespace time_height_convolution;
   // The following figures out a regular structure for the input and
   // output indexes, in case there were gaps (which is unlikely in typical
   // situations).
   ConvolutionComputationIo io;
   GetComputationIo(*input_indexes, *output_indexes, &io);
   ModifyComputationIo(&io);
   std::vector<Index> modified_input_indexes,
       modified_output_indexes;
   // The following call ensures that 'modified_input_indexes' and
   // 'modified_output_indexes' have the required ordering (where t has the
   // largest stride and each (n,x) pair is repeated for each 't' value), as well
   // as doing padding (setting t values to kNoTime where it had to insert
   // elements to ensure regular structure).
   GetIndexesForComputation(io, *input_indexes, *output_indexes,
                            &modified_input_indexes,
                            &modified_output_indexes);
   // It will be quite rare that this function actually changes
   // 'input_indexes' or 'output_indexes', because in most cases,
   // the indexes will already have the required structure and
   // ordering.
   input_indexes->swap(modified_input_indexes);
   output_indexes->swap(modified_output_indexes);
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 597 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, and TdnnComponent::linear_params_.
Referenced by ModelCollapser::GetScaledComponentIndex().
{
   if (scale == 0.0) {
     linear_params_.SetZero();
     bias_params_.SetZero();
   } else {
     linear_params_.Scale(scale);
     bias_params_.Scale(scale);
   }
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 466 of file nnet-convolutional-component.h.
 { return "TdnnComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 656 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, VectorBase< Real >::Dim(), KALDI_ASSERT, TdnnComponent::linear_params_, TdnnComponent::NumParameters(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params.Dim() == NumParameters());
   int32 linear_size = linear_params_.NumRows() * linear_params_.NumCols(),
       bias_size = bias_params_.Dim();
   linear_params_.CopyRowsFromVec(params.Range(0, linear_size));
   if (bias_size != 0)
     bias_params_.CopyFromVec(params.Range(linear_size, bias_size));
 }
UpdateNaturalGradient()
void UpdateNaturalGradient (const PrecomputedIndexes & indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) private
Definition at line 284 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, CuVectorBase< Real >::CopyColFromMat(), TdnnComponent::GetInputPart(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, UpdatableComponent::learning_rate_, TdnnComponent::linear_params_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), OnlineNaturalGradient::PreconditionDirections(), TdnnComponent::preconditioner_in_, TdnnComponent::preconditioner_out_, TdnnComponent::PrecomputedIndexes::row_offsets, TdnnComponent::PrecomputedIndexes::row_stride, and TdnnComponent::time_offsets_.
Referenced by TdnnComponent::Backprop().
{
   int32 num_offsets = time_offsets_.size(),
       num_rows = out_deriv.NumRows(),
       input_dim = in_value.NumCols(),
       spliced_input_dim = num_offsets * input_dim,
       augmented_input_dim =
         spliced_input_dim + (bias_params_.Dim() != 0 ? 1 : 0);
   // in_value_temp is the fully spliced input with a column of ones appended to
   // it.
   CuMatrix<BaseFloat> in_value_temp(num_rows,
                                     augmented_input_dim);
   if (bias_params_.Dim() != 0) {
     // set the last column of in_value_temp to 1.0
     in_value_temp.Range(0, num_rows, spliced_input_dim, 1).Set(1.0);
   }
   for (int32 i = 0; i < num_offsets; i++) {
     CuSubMatrix<BaseFloat> in_value_temp_part(in_value_temp,
                                               0, num_rows,
                                               i * input_dim, input_dim),
         in_value_part = GetInputPart(in_value,
                                      num_rows,
                                      indexes.row_stride,
                                      indexes.row_offsets[i]);
     in_value_temp_part.CopyFromMat(in_value_part);
   }
   CuMatrix<BaseFloat> out_deriv_temp(out_deriv);
   // These "scale" values get will get multiplied into the learning rate (faster
   // than having the matrices scaled inside the preconditioning code).
   BaseFloat in_scale, out_scale;
   preconditioner_in_.PreconditionDirections(&in_value_temp, &in_scale);
   preconditioner_out_.PreconditionDirections(&out_deriv_temp, &out_scale);
   // "scale" is a scaling factor coming from the PreconditionDirections calls
   // (it's faster to have them output a scaling factor than to have them scale
   // their outputs).
   BaseFloat scale = in_scale * out_scale,
       local_lrate = scale * learning_rate_;
   if (bias_params_.Dim() != 0) {
     // this "precon_ones" is what happens to the vector of 1's representing
     // offsets, after multiplication by the preconditioner.
     CuVector<BaseFloat> precon_ones(num_rows);
     precon_ones.CopyColFromMat(in_value_temp, spliced_input_dim);
     bias_params_.AddMatVec(local_lrate, out_deriv_temp, kTrans,
                            precon_ones, 1.0);
   }
   CuSubMatrix<BaseFloat> in_value_precon_part(in_value_temp,
                                               0, num_rows,
                                               0, spliced_input_dim);
   linear_params_.AddMatMat(local_lrate, out_deriv_temp, kTrans,
                            in_value_precon_part, kNoTrans, 1.0);
 }
UpdateSimple()
void UpdateSimple (const PrecomputedIndexes & indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) private
Definition at line 261 of file nnet-tdnn-component.cc.
References CuMatrixBase< Real >::AddMatMat(), TdnnComponent::bias_params_, TdnnComponent::GetInputPart(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, UpdatableComponent::learning_rate_, TdnnComponent::linear_params_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), TdnnComponent::PrecomputedIndexes::row_offsets, TdnnComponent::PrecomputedIndexes::row_stride, and TdnnComponent::time_offsets_.
Referenced by TdnnComponent::Backprop().
{
   if (bias_params_.Dim() != 0)
     bias_params_.AddRowSumMat(learning_rate_, out_deriv);
   int32 input_dim = in_value.NumCols(),
       num_offsets = time_offsets_.size();
   for (int32 i = 0; i < num_offsets; i++) {
     CuSubMatrix<BaseFloat> in_value_part =
         GetInputPart(in_value, out_deriv.NumRows(),
                      indexes.row_stride,
                      indexes.row_offsets[i]);
     CuSubMatrix<BaseFloat> linear_params_part(linear_params_,
                                               0, linear_params_.NumRows(),
                                               i * input_dim, input_dim);
     linear_params_part.AddMatMat(learning_rate_, out_deriv, kTrans,
                                  in_value_part, kNoTrans, 1.0);
   }
 }
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 646 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, VectorBase< Real >::Dim(), KALDI_ASSERT, TdnnComponent::linear_params_, TdnnComponent::NumParameters(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params->Dim() == NumParameters());
   int32 linear_size = linear_params_.NumRows() * linear_params_.NumCols(),
       bias_size = bias_params_.Dim();
   params->Range(0, linear_size).CopyRowsFromMat(linear_params_);
   if (bias_size != 0)
     params->Range(linear_size, bias_size).CopyFromVec(bias_params_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 379 of file nnet-tdnn-component.cc.
References TdnnComponent::bias_params_, OnlineNaturalGradient::GetAlpha(), OnlineNaturalGradient::GetNumSamplesHistory(), OnlineNaturalGradient::GetRank(), TdnnComponent::linear_params_, TdnnComponent::orthonormal_constraint_, TdnnComponent::preconditioner_in_, TdnnComponent::preconditioner_out_, TdnnComponent::time_offsets_, TdnnComponent::use_natural_gradient_, kaldi::WriteBasicType(), kaldi::WriteIntegerVector(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate.
   WriteToken(os, binary, "<TimeOffsets>");
   WriteIntegerVector(os, binary, time_offsets_);
   WriteToken(os, binary, "<LinearParams>");
   linear_params_.Write(os, binary);
   WriteToken(os, binary, "<BiasParams>");
   bias_params_.Write(os, binary);
   WriteToken(os, binary, "<OrthonormalConstraint>");
   WriteBasicType(os, binary, orthonormal_constraint_);
   WriteToken(os, binary, "<UseNaturalGradient>");
   WriteBasicType(os, binary, use_natural_gradient_);
   int32 rank_in = preconditioner_in_.GetRank(),
       rank_out = preconditioner_out_.GetRank();
   BaseFloat alpha_in = preconditioner_in_.GetAlpha(),
       alpha_out = preconditioner_out_.GetAlpha(),
       num_samples_history = preconditioner_in_.GetNumSamplesHistory();
   WriteToken(os, binary, "<NumSamplesHistory>");
   WriteBasicType(os, binary, num_samples_history);
   WriteToken(os, binary, "<AlphaInOut>");
   WriteBasicType(os, binary, alpha_in);
   WriteBasicType(os, binary, alpha_out);
   WriteToken(os, binary, "<RankInOut>");
   WriteBasicType(os, binary, rank_in);
   WriteBasicType(os, binary, rank_out);
   WriteToken(os, binary, "</TdnnComponent>");
 }
Member Data Documentation
bias_params_
CuVector<BaseFloat> bias_params_ private
Definition at line 607 of file nnet-convolutional-component.h.
Referenced by TdnnComponent::Add(), TdnnComponent::Check(), TdnnComponent::DotProduct(), TdnnComponent::Info(), TdnnComponent::InitFromConfig(), TdnnComponent::NumParameters(), TdnnComponent::PerturbParams(), TdnnComponent::Propagate(), TdnnComponent::Read(), TdnnComponent::Scale(), TdnnComponent::UnVectorize(), TdnnComponent::UpdateNaturalGradient(), TdnnComponent::UpdateSimple(), TdnnComponent::Vectorize(), and TdnnComponent::Write().
linear_params_
CuMatrix<BaseFloat> linear_params_ private
Definition at line 603 of file nnet-convolutional-component.h.
Referenced by TdnnComponent::Add(), TdnnComponent::Backprop(), TdnnComponent::Check(), TdnnComponent::DotProduct(), TdnnComponent::Info(), TdnnComponent::InitFromConfig(), TdnnComponent::NumParameters(), TdnnComponent::PerturbParams(), TdnnComponent::Propagate(), TdnnComponent::Read(), TdnnComponent::Scale(), TdnnComponent::UnVectorize(), TdnnComponent::UpdateNaturalGradient(), TdnnComponent::UpdateSimple(), TdnnComponent::Vectorize(), and TdnnComponent::Write().
orthonormal_constraint_
BaseFloat orthonormal_constraint_ private
Definition at line 613 of file nnet-convolutional-component.h.
Referenced by TdnnComponent::Info(), TdnnComponent::InitFromConfig(), TdnnComponent::Read(), and TdnnComponent::Write().
preconditioner_in_
OnlineNaturalGradient preconditioner_in_ private
Definition at line 624 of file nnet-convolutional-component.h.
Referenced by TdnnComponent::ConsolidateMemory(), TdnnComponent::FreezeNaturalGradient(), TdnnComponent::Info(), TdnnComponent::InitFromConfig(), TdnnComponent::Read(), TdnnComponent::UpdateNaturalGradient(), and TdnnComponent::Write().
preconditioner_out_
OnlineNaturalGradient preconditioner_out_ private
Definition at line 628 of file nnet-convolutional-component.h.
Referenced by TdnnComponent::ConsolidateMemory(), TdnnComponent::FreezeNaturalGradient(), TdnnComponent::Info(), TdnnComponent::InitFromConfig(), TdnnComponent::Read(), TdnnComponent::UpdateNaturalGradient(), and TdnnComponent::Write().
time_offsets_
std::vector<int32> time_offsets_ private
Definition at line 599 of file nnet-convolutional-component.h.
Referenced by TdnnComponent::Backprop(), TdnnComponent::Check(), TdnnComponent::GetInputIndexes(), TdnnComponent::Info(), TdnnComponent::InitFromConfig(), TdnnComponent::IsComputable(), TdnnComponent::PrecomputeIndexes(), TdnnComponent::Propagate(), TdnnComponent::Read(), TdnnComponent::UpdateNaturalGradient(), TdnnComponent::UpdateSimple(), and TdnnComponent::Write().
use_natural_gradient_
bool use_natural_gradient_ private
Definition at line 618 of file nnet-convolutional-component.h.
Referenced by TdnnComponent::Backprop(), TdnnComponent::Info(), TdnnComponent::InitFromConfig(), TdnnComponent::Read(), and TdnnComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-convolutional-component.h
nnet3/nnet-tdnn-component.cc