Kaldi: DecodableSum Class Reference
DecodableSum Class Reference
#include <decodable-sum.h>
Public Member Functions
DecodableSum (DecodableInterface *d1, BaseFloat w1, DecodableInterface *d2, BaseFloat w2)
DecodableSum (const std::vector< std::pair< DecodableInterface *, BaseFloat > > &decodables)
void CheckSizes ()
virtual BaseFloat LogLikelihood (int32 frame, int32 state_index)
Returns the log likelihood, which will be negated in the decoder.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
Public Member Functions inherited from DecodableInterface
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual ~DecodableInterface ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableSum)
Private Attributes
std::vector< std::pair< DecodableInterface *, BaseFloat > > decodables_
Detailed Description
Definition at line 36 of file decodable-sum.h.
Constructor & Destructor Documentation
DecodableSum() [1/2]
DecodableSum (DecodableInterface * d1, BaseFloat w1, DecodableInterface * d2, BaseFloat w2) inline
Definition at line 40 of file decodable-sum.h.
References DecodableSum::CheckSizes(), and DecodableSum::decodables_.
{
     decodables_.push_back(std::make_pair(d1, w1));
     decodables_.push_back(std::make_pair(d2, w2));
     CheckSizes();
   }
DecodableSum() [2/2]
DecodableSum (const std::vector< std::pair< DecodableInterface *, BaseFloat > > & decodables) inline
Definition at line 48 of file decodable-sum.h.
References DecodableSum::CheckSizes().
                                                                              :
       decodables_(decodables) { CheckSizes(); }
Member Function Documentation
CheckSizes()
void CheckSizes () inline
Definition at line 52 of file decodable-sum.h.
References DecodableSum::decodables_, rnnlm::i, and KALDI_ASSERT.
Referenced by DecodableSum::DecodableSum().
                     {
     KALDI_ASSERT(decodables_.size() >= 1
                  && decodables_[0].first != NULL);
     for (size_t i = 1; i < decodables_.size(); i++)
       KALDI_ASSERT(decodables_[i].first != NULL &&
                    decodables_[i].first->NumIndices() ==
                    decodables_[0].first->NumIndices());
   }
IsLastFrame()
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frames are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). Caution: the behavior of this function in an online setting is being changed somewhat. In future it may return false in cases where we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. The plan in future is to rely more on NumFramesReady(), and in future, IsLastFrame() would always return false in an online-decoding setting, and would only return true in a decoding-from-matrix setting where we want to allow the last delta or LDA features to be flushed out for compatibility with the baseline setup.
Implements DecodableInterface.
Definition at line 80 of file decodable-sum.h.
References DecodableSum::decodables_.
{
     // We require all the decodables have the same #frames.  We don't check this though.
     return decodables_[0].first->IsLastFrame(frame);
   }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableSum) private
LogLikelihood()
virtual BaseFloat LogLikelihood (int32 frame, int32 index) inline virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Reimplemented in DecodableSumScaled.
Definition at line 63 of file decodable-sum.h.
References DecodableSum::decodables_.
Referenced by DecodableSumScaled::LogLikelihood().
{
     BaseFloat sum = 0.0;
     // int32 i=1;
     for (std::vector<std::pair<DecodableInterface*, BaseFloat> >::iterator iter = decodables_.begin();
          iter != decodables_.end();
          ++iter) {
       sum += iter->first->LogLikelihood(frame, state_index) * iter->second;
       // BaseFloat tmp = iter->first->LogLikelihood(frame, state_index);
       // KALDI_LOG << "ITEM " << i << " contributed with loglike=" << tmp << " scaled by=" << iter->second;
       // i+=1;
       // sum += tmp * iter->second;
      }
     return sum;
   }
NumIndices()
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst).
Implements DecodableInterface.
Definition at line 78 of file decodable-sum.h.
References DecodableSum::decodables_.
 { return decodables_[0].first->NumIndices(); }
Member Data Documentation
decodables_
std::vector<std::pair<DecodableInterface*, BaseFloat> > decodables_ private
Definition at line 86 of file decodable-sum.h.
Referenced by DecodableSum::CheckSizes(), DecodableSum::DecodableSum(), DecodableSum::IsLastFrame(), DecodableSum::LogLikelihood(), and DecodableSum::NumIndices().
The documentation for this class was generated from the following file:
decoder/decodable-sum.h