Kaldi: LogSoftmaxComponent Class Reference
LogSoftmaxComponent Class Reference
#include <nnet-component.h>
Public Member Functions
LogSoftmaxComponent (int32 dim)
LogSoftmaxComponent (const LogSoftmaxComponent &other)
LogSoftmaxComponent ()
virtual std::string Type () const
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual Component * Copy () const
Copy component (deep copy).
Public Member Functions inherited from NonlinearComponent
void Init (int32 dim)
NonlinearComponent (int32 dim)
NonlinearComponent ()
NonlinearComponent (const NonlinearComponent &other)
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void InitFromString (std::string args)
We implement InitFromString at this level.
virtual void Read (std::istream &is, bool binary)
We implement Read at this level as it just needs the Type().
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
void Scale (BaseFloat scale)
void Add (BaseFloat alpha, const NonlinearComponent &other)
const CuVector< double > & ValueSum () const
const CuVector< double > & DerivSum () const
double Count () const
void SetDim (int32 dim)
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual std::string Info () const
virtual ~Component ()
Private Member Functions
LogSoftmaxComponent & operator= (const LogSoftmaxComponent &other)
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Protected Member Functions inherited from NonlinearComponent
void UpdateStats (const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > *deriv=NULL)
const NonlinearComponent & operator= (const NonlinearComponent &other)
Protected Attributes inherited from NonlinearComponent
int32 dim_
CuVector< double > value_sum_
CuVector< double > deriv_sum_
double count_
std::mutex mutex_
Detailed Description
Definition at line 810 of file nnet-component.h.
Constructor & Destructor Documentation
LogSoftmaxComponent() [1/3]
LogSoftmaxComponent (int32 dim) inline explicit
Definition at line 812 of file nnet-component.h.
 : NonlinearComponent(dim) { }
LogSoftmaxComponent() [2/3]
LogSoftmaxComponent (const LogSoftmaxComponent & other) inline explicit
Definition at line 813 of file nnet-component.h.
 : NonlinearComponent(other) { }
LogSoftmaxComponent() [3/3]
LogSoftmaxComponent () inline
Definition at line 814 of file nnet-component.h.
 { }
Member Function Documentation
Backprop()
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 965 of file nnet-component.cc.
References CuMatrixBase< Real >::DiffLogSoftmaxPerRow(), KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrix< Real >::Resize(), kaldi::SameDim(), and NonlinearComponent::UpdateStats().
{
   /*
     Let the output be y, then
       y_i = x_i - log(sum_i exp(x_i))
     where x_i is the input to the component. The Jacobian matrix of this
     function is
       J = I - 1 exp(y^T)
     where 1 is a vector of ones. Let the derivative vector at the output be e,
     and at the input be d, then we have
       d = e - exp(y) Sum(e)
       d_i = e_i - exp(y_i) Sum(e)
   */
   in_deriv->Resize(out_deriv.NumRows(), out_deriv.NumCols());
   KALDI_ASSERT(SameDim(out_value, out_deriv) && SameDim(out_value, *in_deriv));
   in_deriv->DiffLogSoftmaxPerRow(out_value, out_deriv);
   // Updates stats.
   if (to_update != NULL) {
     NonlinearComponent *to_update_nonlinear =
         dynamic_cast<NonlinearComponent*>(to_update);
     to_update_nonlinear->UpdateStats(out_value);
   }
 }
BackpropNeedsInput()
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 816 of file nnet-component.h.
 { return false; }
BackpropNeedsOutput()
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 817 of file nnet-component.h.
References Component::Propagate().
 { return true; }
Copy()
virtual Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 831 of file nnet-component.h.
 { return new LogSoftmaxComponent(*this); }
operator=()
LogSoftmaxComponent& operator= (const LogSoftmaxComponent & other) private
Propagate()
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 949 of file nnet-component.cc.
References CuMatrixBase< Real >::ApplyFloor(), CuMatrixBase< Real >::ApplyLogSoftMaxPerRow(), ChunkInfo::CheckSize(), KALDI_ASSERT, kaldi::Log(), and ChunkInfo::NumChunks().
{
   in_info.CheckSize(in);
   out_info.CheckSize(*out);
   KALDI_ASSERT(in_info.NumChunks() == out_info.NumChunks());
   // Applies log softmax function to each row of the output. For each row, we do
   // x_i = x_i - log(sum_j exp(x_j))
   out->ApplyLogSoftMaxPerRow(in);
   // Just to be consistent with SoftmaxComponent::Propagate()
   out->ApplyFloor(Log(1.0e-20));
 }
Type()
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 815 of file nnet-component.h.
 { return "LogSoftmaxComponent"; }
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc