Kaldi: DropoutComponent Class Reference
DropoutComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
void Init (int32 dim, BaseFloat dropout_proportion=0.0, bool dropout_per_frame=false)
DropoutComponent (int32 dim, BaseFloat dropout=0.0, bool dropout_per_frame=false)
DropoutComponent ()
DropoutComponent (const DropoutComponent &other)
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual Component * Copy () const
Copies component (deep copy).
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
void SetDropoutProportion (BaseFloat dropout_proportion)
BaseFloat DropoutProportion () const
Public Member Functions inherited from RandomComponent
void ResetGenerator ()
void SetTestMode (bool test_mode)
RandomComponent ()
RandomComponent (const RandomComponent &other)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Attributes
int32 dim_
BaseFloat dropout_proportion_
dropout-proportion is the proportion that is dropped out, e.g.
bool dropout_per_frame_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Attributes inherited from RandomComponent
CuRand< BaseFloat > random_generator_
bool test_mode_
Detailed Description
Definition at line 92 of file nnet-simple-component.h.
Constructor & Destructor Documentation
DropoutComponent() [1/3]
DropoutComponent (int32 dim, BaseFloat dropout = 0.0, bool dropout_per_frame = false) inline
Definition at line 97 of file nnet-simple-component.h.
References PnormComponent::Init().
{
     Init(dim, dropout, dropout_per_frame);
   }
DropoutComponent() [2/3]
DropoutComponent () inline
Definition at line 102 of file nnet-simple-component.h.
Referenced by DropoutComponent::Copy().
                     : dim_(0), dropout_proportion_(0.0),
                       dropout_per_frame_(false) { }
DropoutComponent() [3/3]
DropoutComponent (const DropoutComponent & other)
Definition at line 93 of file nnet-simple-component.cc.
                                                                :
     RandomComponent(other),
     dim_(other.dim_),
     dropout_proportion_(other.dropout_proportion_),
     dropout_per_frame_(other.dropout_per_frame_) { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 178 of file nnet-simple-component.cc.
References KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::SetMatMatDivMat().
{
   KALDI_ASSERT(in_value.NumRows() == out_value.NumRows() &&
                in_value.NumCols() == out_value.NumCols());
   KALDI_ASSERT(in_value.NumRows() == out_deriv.NumRows() &&
                in_value.NumCols() == out_deriv.NumCols());
   in_deriv->SetMatMatDivMat(out_deriv, out_value, in_value);
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 99 of file nnet-simple-component.cc.
References DropoutComponent::DropoutComponent().
{
   DropoutComponent *ans = new DropoutComponent(*this);
   return ans;
 }
DropoutProportion()
BaseFloat DropoutProportion () const inline
Definition at line 144 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsDropout().
 { return dropout_proportion_; }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 130 of file nnet-simple-component.cc.
References DropoutComponent::dim_, DropoutComponent::dropout_per_frame_, DropoutComponent::dropout_proportion_, and DropoutComponent::Type().
{
   std::ostringstream stream;
   stream << Type() << ", dim=" << dim_
          << ", dropout-proportion=" << dropout_proportion_
          << ", dropout-per-frame=" << (dropout_per_frame_ ? "true" : "false");
   return stream.str();
 }
Init()
void Init (int32 dim, BaseFloat dropout_proportion = 0.0, bool dropout_per_frame = false)
Definition at line 104 of file nnet-simple-component.cc.
References DropoutComponent::dim_, DropoutComponent::dropout_per_frame_, and DropoutComponent::dropout_proportion_.
Referenced by DropoutComponent::InitFromConfig(), ElementwiseProductComponent::InitFromConfig(), and ClipGradientComponent::InitFromConfig().
{
   dropout_proportion_ = dropout_proportion;
   dropout_per_frame_ = dropout_per_frame;
   dim_ = dim;
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 111 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), DropoutComponent::Init(), KALDI_ERR, RandomComponent::test_mode_, DropoutComponent::Type(), and ConfigLine::WholeLine().
{
   int32 dim = 0;
   BaseFloat dropout_proportion = 0.0;
   bool dropout_per_frame = false;
   test_mode_ = false;
   bool ok = cfl->GetValue("dim", &dim) &&
     cfl->GetValue("dropout-proportion", &dropout_proportion);
   cfl->GetValue("dropout-per-frame", &dropout_per_frame);
   // It only makes sense to set test-mode in the config for testing purposes.
   cfl->GetValue("test-mode", &test_mode_);
     // for this stage, dropout is hard coded in
     // normal mode if not declared in config
   if (!ok || cfl->HasUnusedValues() || dim <= 0 ||
       dropout_proportion < 0.0 || dropout_proportion > 1.0)
        KALDI_ERR << "Invalid initializer for layer of type "
                  << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(dim, dropout_proportion, dropout_per_frame);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 115 of file nnet-simple-component.h.
 { return dim_; }
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 117 of file nnet-simple-component.h.
References PnormComponent::Backprop(), PnormComponent::Copy(), Component::Info(), PnormComponent::Propagate(), PnormComponent::Read(), and PnormComponent::Write().
 { return dim_; }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 138 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::Add(), CuMatrixBase< Real >::ApplyHeaviside(), CuMatrixBase< Real >::CopyColsFromVec(), CuMatrixBase< Real >::CopyFromMat(), DropoutComponent::dim_, DropoutComponent::dropout_per_frame_, DropoutComponent::dropout_proportion_, KALDI_ASSERT, kaldi::kUndefined, CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), RandomComponent::random_generator_, kaldi::RandUniform(), CuMatrixBase< Real >::Scale(), and RandomComponent::test_mode_.
{
   KALDI_ASSERT(out->NumRows() == in.NumRows() && out->NumCols() == in.NumCols()
                && in.NumCols() == dim_);
   BaseFloat dropout = dropout_proportion_;
   KALDI_ASSERT(dropout >= 0.0 && dropout <= 1.0);
   if (test_mode_) {
     out->CopyFromMat(in);
     out->Scale(1.0 - dropout);
     return NULL;
   }
   if (!dropout_per_frame_) {
     // This const_cast is only safe assuming you don't attempt
     // to use multi-threaded code with the GPU.
     const_cast<CuRand<BaseFloat>&>(random_generator_).RandUniform(out);
     out->Add(-dropout);  // now, a proportion "dropout" will be <0.0
     // apply the function (x>0?1:0).  Now, a proportion
     // "dropout" will be zero and (1 - dropout) will be 1.0.
     out->ApplyHeaviside();
     out->MulElements(in);
   } else {
     // randomize the dropout matrix by row,
     // i.e. [[1,1,1,1],[0,0,0,0],[0,0,0,0],[1,1,1,1],[0,0,0,0]]
     CuMatrix<BaseFloat> tmp(1, out->NumRows(), kUndefined);
     // This const_cast is only safe assuming you don't attempt
     // to use multi-threaded code with the GPU.
     const_cast<CuRand<BaseFloat>&>(random_generator_).RandUniform(&tmp);
     tmp.Add(-dropout);
     tmp.ApplyHeaviside();
     out->CopyColsFromVec(tmp.Row(0));
     out->MulElements(in);
   }
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 107 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kBackpropNeedsOutput, kaldi::nnet3::kRandomComponent, and kaldi::nnet3::kSimpleComponent.
{
     return kBackpropInPlace|kSimpleComponent|kBackpropNeedsInput|
         kBackpropNeedsOutput|kRandomComponent;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 196 of file nnet-simple-component.cc.
References DropoutComponent::dim_, DropoutComponent::dropout_per_frame_, DropoutComponent::dropout_proportion_, kaldi::nnet3::ExpectToken(), KALDI_ASSERT, kaldi::ReadBasicType(), kaldi::ReadToken(), and RandomComponent::test_mode_.
{
   std::string token;
   ReadToken(is, binary, &token);
   if (token == "<DropoutComponent>") {
     ReadToken(is, binary, &token);
   }
   KALDI_ASSERT(token == "<Dim>");
   ReadBasicType(is, binary, &dim_);  // read dimension.
   ReadToken(is, binary, &token);
   KALDI_ASSERT(token == "<DropoutProportion>");
   ReadBasicType(is, binary, &dropout_proportion_);  // read dropout rate
   ReadToken(is, binary, &token);
   if (token == "<DropoutPerFrame>") {
     ReadBasicType(is, binary, &dropout_per_frame_);  // read dropout mode
     ReadToken(is, binary, &token);
   } else {
     dropout_per_frame_ = false;
   }
   if (token == "<TestMode>") {
     ReadBasicType(is, binary, &test_mode_);  // read test mode
     ExpectToken(is, binary, "</DropoutComponent>");
   } else {
     test_mode_ = false;
     KALDI_ASSERT(token == "</DropoutComponent>");
   }
 }
SetDropoutProportion()
void SetDropoutProportion (BaseFloat dropout_proportion) inline
Definition at line 140 of file nnet-simple-component.h.
Referenced by kaldi::nnet3::ReadEditConfig(), and kaldi::nnet3::SetDropoutProportion().
{
     dropout_proportion_ = dropout_proportion;
   }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 111 of file nnet-simple-component.h.
References PnormComponent::InitFromConfig().
Referenced by DropoutComponent::Info(), NoOpComponent::Info(), ClipGradientComponent::Info(), DropoutComponent::InitFromConfig(), ElementwiseProductComponent::InitFromConfig(), NoOpComponent::InitFromConfig(), and ClipGradientComponent::InitFromConfig().
 { return "DropoutComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 223 of file nnet-simple-component.cc.
References DropoutComponent::dim_, DropoutComponent::dropout_per_frame_, DropoutComponent::dropout_proportion_, RandomComponent::test_mode_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<DropoutComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<DropoutProportion>");
   WriteBasicType(os, binary, dropout_proportion_);
   WriteToken(os, binary, "<DropoutPerFrame>");
   WriteBasicType(os, binary, dropout_per_frame_);
   WriteToken(os, binary, "<TestMode>");
   WriteBasicType(os, binary, test_mode_);
   WriteToken(os, binary, "</DropoutComponent>");
 }
Member Data Documentation
dim_
int32 dim_ private
Definition at line 146 of file nnet-simple-component.h.
Referenced by DropoutComponent::Info(), NoOpComponent::Info(), ClipGradientComponent::Info(), DropoutComponent::Init(), ClipGradientComponent::Init(), NoOpComponent::InitFromConfig(), DropoutComponent::Propagate(), DropoutComponent::Read(), NoOpComponent::Read(), ClipGradientComponent::Read(), SigmoidComponent::RepairGradients(), TanhComponent::RepairGradients(), RectifiedLinearComponent::RepairGradients(), DropoutComponent::Write(), NoOpComponent::Write(), and ClipGradientComponent::Write().
dropout_per_frame_
bool dropout_per_frame_ private
Definition at line 150 of file nnet-simple-component.h.
Referenced by DropoutComponent::Info(), DropoutComponent::Init(), DropoutComponent::Propagate(), DropoutComponent::Read(), and DropoutComponent::Write().
dropout_proportion_
BaseFloat dropout_proportion_ private
dropout-proportion is the proportion that is dropped out, e.g.
if 0.1, we set 10% to zero value.
Definition at line 149 of file nnet-simple-component.h.
Referenced by DropoutComponent::Info(), DropoutComponent::Init(), DropoutComponent::Propagate(), DropoutComponent::Read(), and DropoutComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc