Kaldi: HtkMatrixHolder Class Reference
HtkMatrixHolder Class Reference
"Holder types"
#include <kaldi-holder-inl.h>
Public Types
typedef std::pair< Matrix< BaseFloat >, HtkHeader > T
Public Member Functions
HtkMatrixHolder ()
void Clear ()
bool Read (std::istream &is)
T & Value ()
void Swap (HtkMatrixHolder *other)
bool ExtractRange (const HtkMatrixHolder &other, const std::string &range)
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (HtkMatrixHolder)
Private Attributes
T t_
Detailed Description
Definition at line 757 of file kaldi-holder-inl.h.
Member Typedef Documentation
T
typedef std::pair<Matrix<BaseFloat>, HtkHeader> T
Definition at line 759 of file kaldi-holder-inl.h.
Constructor & Destructor Documentation
HtkMatrixHolder()
HtkMatrixHolder () inline
Definition at line 761 of file kaldi-holder-inl.h.
 {}
Member Function Documentation
Clear()
void Clear () inline
Definition at line 772 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
 { t_.first.Resize(0, 0); }
ExtractRange()
bool ExtractRange (const HtkMatrixHolder & other, const std::string & range) inline
Definition at line 794 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::KALDI_DISALLOW_COPY_AND_ASSIGN(), and KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 785 of file kaldi-holder-inl.h.
 { return true; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (HtkMatrixHolder) private
Read()
bool Read (std::istream & is) inline
Definition at line 775 of file kaldi-holder-inl.h.
References KALDI_WARN, kaldi::ReadHtk(), and KaldiObjectHolder< KaldiType >::t_.
{
     bool ans = ReadHtk(is, &t_.first, &t_.second);
     if (!ans) {
       KALDI_WARN << "Error detected reading HTK-format matrix.";
       return false;
     }
     return ans;
   }
Swap()
void Swap (HtkMatrixHolder * other) inline
Definition at line 789 of file kaldi-holder-inl.h.
References kaldi::swap(), KaldiObjectHolder< KaldiType >::t_, and HtkMatrixHolder::t_.
{
     t_.first.Swap(&(other->t_.first));
     std::swap(t_.second, other->t_.second);
   }
Value()
T& Value () inline
Definition at line 787 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
 { return t_; }
Write()
static bool Write (std::ostream & os, bool binary, const T & t) inline static
Definition at line 763 of file kaldi-holder-inl.h.
References KALDI_ERR, KALDI_WARN, and kaldi::WriteHtk().
{
     if (!binary)
       KALDI_ERR << "Non-binary HTK-format write not supported.";
     bool ans = WriteHtk(os, t.first, t.second);
     if (!ans)
       KALDI_WARN << "Error detected writing HTK-format matrix.";
     return ans;
   }
Member Data Documentation
t_
T t_ private
Definition at line 802 of file kaldi-holder-inl.h.
Referenced by HtkMatrixHolder::Swap().
The documentation for this class was generated from the following file:
util/kaldi-holder-inl.h