Kaldi: SumBlockComponent Class Reference
SumBlockComponent Class Reference
SumBlockComponent sums over blocks of its input: for instance, if you create one with the config "input-dim=400 output-dim=100", its output will be the sum over the 4 100-dimensional blocks of the input.
#include <nnet-simple-component.h>
Public Member Functions
SumBlockComponent (const SumBlockComponent &other)
SumBlockComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual Component * Copy () const
Copies component (deep copy).
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
SumBlockComponent & operator= (const SumBlockComponent &other)
Private Attributes
int32 input_dim_
int32 output_dim_
BaseFloat scale_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
SumBlockComponent sums over blocks of its input: for instance, if you create one with the config "input-dim=400 output-dim=100", its output will be the sum over the 4 100-dimensional blocks of the input.
The "scale" config parameter may be used if you want to do averaging instead of summing, e.g. "input-dim=400 output-dim=100 scale=0.25" will accomplish averaging.
Accepted values on its config-file line are: input-dim The input dimension. Required. output-dim The block dimension. Required. Must divide input-dim. scale A scaling factor on the output. Defaults to 1.0.
Definition at line 1235 of file nnet-simple-component.h.
Constructor & Destructor Documentation
SumBlockComponent() [1/2]
SumBlockComponent (const SumBlockComponent & other) explicit
Definition at line 5919 of file nnet-simple-component.cc.
                                                                   :
     input_dim_(other.input_dim_), output_dim_(other.output_dim_),
     scale_(other.scale_) { }
SumBlockComponent() [2/2]
SumBlockComponent () inline
Definition at line 1238 of file nnet-simple-component.h.
 { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 5977 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatBlocks(), kaldi::kNoTrans, and SumBlockComponent::scale_.
{
   if (in_deriv) {
     in_deriv->AddMatBlocks(scale_, out_deriv, kNoTrans);
   }
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 1249 of file nnet-simple-component.h.
References PnormComponent::Backprop(), and PnormComponent::Propagate().
 { return new SumBlockComponent(*this); }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 5959 of file nnet-simple-component.cc.
References SumBlockComponent::input_dim_, SumBlockComponent::output_dim_, SumBlockComponent::scale_, and SumBlockComponent::Type().
{
   std::ostringstream stream;
   stream << Type() << ", input-dim=" << input_dim_
          << ", output-dim=" << output_dim_
          << ", scale=" << scale_;
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 5923 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), SumBlockComponent::input_dim_, KALDI_ERR, SumBlockComponent::output_dim_, SumBlockComponent::scale_, and ConfigLine::UnusedValues().
{
   scale_ = 1.0;
   bool ok = cfl->GetValue("input-dim", &input_dim_) &&
       cfl->GetValue("output-dim", &output_dim_);
   if (!ok)
     KALDI_ERR << "input-dim and output-dim must both be provided.";
   if (input_dim_ <= 0 || input_dim_ % output_dim_ != 0)
     KALDI_ERR << "Invalid values input-dim=" << input_dim_
               << " output-dim=" << output_dim_;
   cfl->GetValue("scale", &scale_);
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1244 of file nnet-simple-component.h.
References PnormComponent::input_dim_.
 { return input_dim_; }
operator=()
SumBlockComponent& operator= (const SumBlockComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1245 of file nnet-simple-component.h.
References Component::Info(), PnormComponent::output_dim_, PnormComponent::Read(), and PnormComponent::Write().
 { return output_dim_; }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 5967 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatBlocks(), SumBlockComponent::input_dim_, KALDI_ASSERT, kaldi::kNoTrans, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), SumBlockComponent::output_dim_, and SumBlockComponent::scale_.
{
   KALDI_ASSERT(out->NumRows() == in.NumRows() &&
                out->NumCols() == output_dim_ &&
                in.NumCols() == input_dim_);
   out->AddMatBlocks(scale_, in, kNoTrans);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1240 of file nnet-simple-component.h.
References PnormComponent::InitFromConfig(), kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kPropagateAdds, and kaldi::nnet3::kSimpleComponent.
{
     return kSimpleComponent|kPropagateAdds|kBackpropAdds;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 5938 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), SumBlockComponent::input_dim_, SumBlockComponent::output_dim_, kaldi::ReadBasicType(), and SumBlockComponent::scale_.
{
   ExpectOneOrTwoTokens(is, binary, "<SumBlockComponent>", "<InputDim>");
   ReadBasicType(is, binary, &input_dim_);
   ExpectToken(is, binary, "<OutputDim>");
   ReadBasicType(is, binary, &output_dim_);
   ExpectToken(is, binary, "<Scale>");
   ReadBasicType(is, binary, &scale_);
   ExpectToken(is, binary, "</SumBlockComponent>");
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 1239 of file nnet-simple-component.h.
Referenced by SumBlockComponent::Info().
 { return "SumBlockComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 5948 of file nnet-simple-component.cc.
References SumBlockComponent::input_dim_, SumBlockComponent::output_dim_, SumBlockComponent::scale_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<SumBlockComponent>");
   WriteToken(os, binary, "<InputDim>");
   WriteBasicType(os, binary, input_dim_);
   WriteToken(os, binary, "<OutputDim>");
   WriteBasicType(os, binary, output_dim_);
   WriteToken(os, binary, "<Scale>");
   WriteBasicType(os, binary, scale_);
   WriteToken(os, binary, "</SumBlockComponent>");
 }
Member Data Documentation
input_dim_
int32 input_dim_ private
Definition at line 1262 of file nnet-simple-component.h.
Referenced by SumBlockComponent::Info(), SumBlockComponent::InitFromConfig(), SumBlockComponent::Propagate(), SumBlockComponent::Read(), and SumBlockComponent::Write().
output_dim_
int32 output_dim_ private
Definition at line 1263 of file nnet-simple-component.h.
Referenced by SumBlockComponent::Info(), SumBlockComponent::InitFromConfig(), SumBlockComponent::Propagate(), SumBlockComponent::Read(), and SumBlockComponent::Write().
scale_
BaseFloat scale_ private
Definition at line 1264 of file nnet-simple-component.h.
Referenced by SumBlockComponent::Backprop(), SumBlockComponent::Info(), SumBlockComponent::InitFromConfig(), SumBlockComponent::Propagate(), SumBlockComponent::Read(), and SumBlockComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc