Kaldi: CuTpMatrix< Real > Class Template Reference
CuTpMatrix< Real > Class Template Reference
#include <matrix-common.h>
Public Member Functions
CuTpMatrix ()
CuTpMatrix (MatrixIndexT r, MatrixResizeType resize_type=kSetZero)
CuTpMatrix (const TpMatrix< Real > &orig)
CuTpMatrix (const CuTpMatrix< Real > &orig)
CuTpMatrix (const CuMatrixBase< Real > &orig, MatrixTransposeType trans=kNoTrans)
~CuTpMatrix ()
void CopyFromMat (const CuMatrixBase< Real > &M, MatrixTransposeType Trans=kNoTrans)
void CopyFromTp (const CuTpMatrix< Real > &other)
void CopyFromTp (const TpMatrix< Real > &other)
void Cholesky (const CuSpMatrix< Real > &Orig)
void Invert ()
CuTpMatrix< Real > & operator= (const CuTpMatrix< Real > &in)
Public Member Functions inherited from CuPackedMatrix< Real >
CuPackedMatrix ()
CuPackedMatrix (MatrixIndexT r, MatrixResizeType resize_type=kSetZero)
CuPackedMatrix (const PackedMatrix< Real > &orig)
CuPackedMatrix (const CuPackedMatrix< Real > &orig)
void SetZero ()
void SetUnit ()
< Set to zero
void SetRandn ()
< Set to unit matrix.
void SetDiag (Real alpha)
< Set to random values of a normal distribution
void AddToDiag (Real r)
< Set the diagonal value to alpha
void Scale (Real alpha)
void ScaleDiag (Real alpha)
Real Trace () const
~CuPackedMatrix ()
void Resize (MatrixIndexT nRows, MatrixResizeType resize_type=kSetZero)
Set packed matrix to a specified size (can be zero).
void CopyFromPacked (const CuPackedMatrix< Real > &src)
void CopyFromPacked (const PackedMatrix< Real > &src)
void CopyToPacked (PackedMatrix< Real > *dst) const
void Read (std::istream &in, bool binary)
void Write (std::ostream &out, bool binary) const
void Destroy ()
void Swap (CuPackedMatrix< Real > *other)
Swaps the contents of *this and *other. Shallow swap.
void Swap (PackedMatrix< Real > *other)
Swaps the contents of *this and *other.
Real * Data ()
const Real * Data () const
Real operator() (MatrixIndexT r, MatrixIndexT c) const
MatrixIndexT NumRows () const
MatrixIndexT NumCols () const
size_t SizeInBytes () const
Returns size in bytes of the data held by the matrix.
Protected Member Functions
const TpMatrix< Real > & Mat () const
TpMatrix< Real > & Mat ()
Protected Member Functions inherited from CuPackedMatrix< Real >
const PackedMatrix< Real > & Mat () const
PackedMatrix< Real > & Mat ()
void AddPacked (const Real alpha, const CuPackedMatrix< Real > &M)
Friends
class CuMatrixBase< float >
class CuMatrixBase< double >
class CuVectorBase< Real >
class CuSubMatrix< Real >
class CuRand< Real >
class CuTpMatrix< float >
class CuTpMatrix< double >
Additional Inherited Members
Protected Attributes inherited from CuPackedMatrix< Real >
Real * data_
MatrixIndexT num_rows_
Detailed Description
template<typename Real>
class kaldi::CuTpMatrix< Real >
Definition at line 77 of file matrix-common.h.
Constructor & Destructor Documentation
CuTpMatrix() [1/5]
CuTpMatrix () inline
Definition at line 48 of file cu-tp-matrix.h.
 : CuPackedMatrix<Real>() {}
CuTpMatrix() [2/5]
CuTpMatrix (MatrixIndexT r, MatrixResizeType resize_type = kSetZero) inline explicit
Definition at line 49 of file cu-tp-matrix.h.
       : CuPackedMatrix<Real>(r, resize_type) {}
CuTpMatrix() [3/5]
CuTpMatrix (const TpMatrix< Real > & orig) inline explicit
Definition at line 52 of file cu-tp-matrix.h.
       : CuPackedMatrix<Real>(orig) {}
CuTpMatrix() [4/5]
CuTpMatrix (const CuTpMatrix< Real > & orig) inline
Definition at line 56 of file cu-tp-matrix.h.
References kaldi::kNoTrans.
       : CuPackedMatrix<Real>(orig) {}
CuTpMatrix() [5/5]
CuTpMatrix (const CuMatrixBase< Real > & orig, MatrixTransposeType trans = kNoTrans) explicit
Definition at line 40 of file cu-tp-matrix.cc.
References CuTpMatrix< Real >::CopyFromMat(), KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
                                                                                      :
     CuPackedMatrix<Real>(orig.NumRows(), kUndefined) {
   KALDI_ASSERT(orig.NumRows() == orig.NumCols());
   this->CopyFromMat(orig, trans);
 }
~CuTpMatrix()
~CuTpMatrix () inline
Definition at line 63 of file cu-tp-matrix.h.
References CuTpMatrix< Real >::CopyFromMat(), and kaldi::kNoTrans.
 {}
Member Function Documentation
Cholesky()
void Cholesky (const CuSpMatrix< Real > & Orig)
Definition at line 48 of file cu-tp-matrix.cc.
References CuMatrixBase< Real >::Cholesky(), CuTpMatrix< Real >::CopyFromMat(), kaldi::kNoTrans, CuTpMatrix< Real >::Mat(), and CuSpMatrix< Real >::Mat().
Referenced by CuTpMatrix< Real >::CopyFromTp(), and kaldi::UnitTestCuTpMatrixCholesky().
{
 #if HAVE_CUDA==1
   if (CuDevice::Instantiate().Enabled()) {
     CuMatrix<Real> tmp(orig);
     tmp.Cholesky();
     this->CopyFromMat(tmp, kNoTrans);
   } else
 #endif
   {
     this->Mat().Cholesky(orig.Mat());
   }
 }
CopyFromMat()
void CopyFromMat (const CuMatrixBase< Real > & M, MatrixTransposeType Trans = kNoTrans)
Definition at line 89 of file cu-tp-matrix.cc.
References CU2DBLOCK, CuMatrixBase< Real >::Data(), CuPackedMatrix< Real >::data_, CuMatrixBase< Real >::Dim(), KALDI_ASSERT, kaldi::kNoTrans, CuTpMatrix< Real >::Mat(), CuMatrixBase< Real >::Mat(), CuPackedMatrix< Real >::num_rows_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
Referenced by CuTpMatrix< Real >::Cholesky(), CuTpMatrix< Real >::CuTpMatrix(), CuTpMatrix< Real >::Invert(), TpMatrix< float >::TpMatrix(), kaldi::UnitTestCuTpMatrixCopyFromMat(), and CuTpMatrix< Real >::~CuTpMatrix().
{
 #if HAVE_CUDA==1
   if (CuDevice::Instantiate().Enabled()) {
     MatrixIndexT num_rows = this->num_rows_;
     KALDI_ASSERT(num_rows == M.NumRows() && this->num_rows_ == M.NumCols());
     if (num_rows == 0) return;
     CuTimer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(num_rows, CU2DBLOCK), n_blocks(num_rows, CU2DBLOCK));
     if (Trans == kNoTrans) {
       cuda_take_lower(dimGrid, dimBlock, M.Data(), this->data_, M.Dim());
     } else {
       cuda_take_upper(dimGrid, dimBlock, M.Data(), this->data_, M.Dim());
     }
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim);
   } else
 #endif
   {
     Mat().CopyFromMat(M.Mat(), Trans);
   }
 }
CopyFromTp() [1/2]
void CopyFromTp (const CuTpMatrix< Real > & other) inline
Definition at line 68 of file cu-tp-matrix.h.
References CuPackedMatrix< Real >::CopyFromPacked().
Referenced by CuMatrixBase< float >::Cholesky(), and kaldi::UnitTestCuTpMatrixCopyFromTp().
{
     CuPackedMatrix<Real>::CopyFromPacked(other);
   }
CopyFromTp() [2/2]
void CopyFromTp (const TpMatrix< Real > & other) inline
Definition at line 71 of file cu-tp-matrix.h.
References CuTpMatrix< Real >::Cholesky(), CuPackedMatrix< Real >::CopyFromPacked(), CuTpMatrix< Real >::Invert(), and CuTpMatrix< Real >::operator=().
{
     CuPackedMatrix<Real>::CopyFromPacked(other);
   }
Invert()
void Invert ()
Definition at line 63 of file cu-tp-matrix.cc.
References CuTpMatrix< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyFromTp(), CU2DBLOCK, CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::Dim(), kaldi::kNoTrans, CuTpMatrix< Real >::Mat(), CuPackedMatrix< Real >::num_rows_, CuPackedMatrix< Real >::NumRows(), and MatrixDim_::stride.
Referenced by CuTpMatrix< Real >::CopyFromTp().
{
 #if HAVE_CUDA==1
   if (CuDevice::Instantiate().Enabled()) {
     if (this->num_rows_ == 0) return;
     CuTimer tim;
     int dimBlock(CU2DBLOCK);
     int dimGrid(n_blocks(this->NumRows(), CU2DBLOCK));
     CuMatrix<Real> tmp(this->NumRows(), this->NumRows());
     int dim = this->NumRows();
     Real alpha = 1.0;
     cuda_set_diag(dimGrid, dimBlock, tmp.Data(), alpha, tmp.Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuMatrix<Real> tmp2(dim, dim);
     tmp2.CopyFromTp(*this);
     CUBLAS_SAFE_CALL(cublas_trsm(GetCublasHandle(), dim, dim, alpha, tmp2.Data(), tmp2.Dim().stride,
       tmp.Data(), tmp.Dim().stride));
     this->CopyFromMat(tmp, kNoTrans);
     CuDevice::Instantiate().AccuProfile(__func__, tim);
   } else
 #endif
   {
     Mat().Invert();
   }
 }
Mat() [1/2]
const TpMatrix<Real>& Mat () const inline protected
Definition at line 80 of file cu-tp-matrix.h.
Referenced by CuVectorBase< float >::AddTpVec(), CuTpMatrix< Real >::Cholesky(), CuTpMatrix< Real >::CopyFromMat(), CuMatrixBase< float >::CopyFromTp(), CuTpMatrix< Real >::Invert(), and CuVectorBase< float >::MulTp().
{
     return *(reinterpret_cast<const TpMatrix<Real>* >(this));
   }
Mat() [2/2]
TpMatrix<Real>& Mat () inline protected
Definition at line 83 of file cu-tp-matrix.h.
{
     return *(reinterpret_cast<TpMatrix<Real>* >(this));
   }
operator=()
CuTpMatrix< Real > & operator= (const CuTpMatrix< Real > & in)
Definition at line 130 of file cu-tp-matrix.cc.
References CuPackedMatrix< Real >::CopyFromPacked(), kaldi::kUndefined, CuPackedMatrix< Real >::NumRows(), and CuPackedMatrix< Real >::Resize().
Referenced by CuTpMatrix< Real >::CopyFromTp().
{
   this->Resize(in.NumRows(), kUndefined);
   this->CopyFromPacked(in);
   return *this;
 }
Friends And Related Function Documentation
CuMatrixBase< double >
friend class CuMatrixBase< double > friend
Definition at line 41 of file cu-tp-matrix.h.
CuMatrixBase< float >
friend class CuMatrixBase< float > friend
Definition at line 40 of file cu-tp-matrix.h.
CuRand< Real >
friend class CuRand< Real > friend
Definition at line 44 of file cu-tp-matrix.h.
CuSubMatrix< Real >
friend class CuSubMatrix< Real > friend
Definition at line 43 of file cu-tp-matrix.h.
CuTpMatrix< double >
friend class CuTpMatrix< double > friend
Definition at line 46 of file cu-tp-matrix.h.
CuTpMatrix< float >
friend class CuTpMatrix< float > friend
Definition at line 45 of file cu-tp-matrix.h.
CuVectorBase< Real >
friend class CuVectorBase< Real > friend
Definition at line 42 of file cu-tp-matrix.h.
The documentation for this class was generated from the following files:
matrix/matrix-common.h
cudamatrix/cu-tp-matrix.h
cudamatrix/cu-tp-matrix.cc