Kaldi: CacheDeterministicOnDemandFst< Arc > Class Template Reference
CacheDeterministicOnDemandFst< Arc > Class Template Reference
"Classes and functions related to on-demand deterministic FST's"
#include <deterministic-fst.h>
Public Types
typedef Arc::StateId StateId
typedef Arc::Weight Weight
typedef Arc::Label Label
Public Types inherited from DeterministicOnDemandFst< Arc >
typedef Arc::StateId StateId
typedef Arc::Weight Weight
typedef Arc::Label Label
Public Member Functions
CacheDeterministicOnDemandFst (DeterministicOnDemandFst< Arc > *fst, StateId num_cached_arcs=100000)
We don't take ownership of this pointer. The argument is "really" const.
virtual StateId Start ()
virtual Weight Final (StateId s)
We don't bother caching the final-probs, just the arcs.
virtual bool GetArc (StateId s, Label ilabel, Arc *oarc)
Note: ilabel must not be epsilon.
Public Member Functions inherited from DeterministicOnDemandFst< Arc >
virtual ~DeterministicOnDemandFst ()
Private Member Functions
size_t GetIndex (StateId src_state, Label ilabel)
Private Attributes
DeterministicOnDemandFst< Arc > * fst_
StateId num_cached_arcs_
std::vector< std::pair< StateId, Arc > > cached_arcs_
Detailed Description
template<class Arc>
class fst::CacheDeterministicOnDemandFst< Arc >
Definition at line 230 of file deterministic-fst.h.
Member Typedef Documentation
Label
typedef Arc::Label Label
Definition at line 234 of file deterministic-fst.h.
StateId
typedef Arc::StateId StateId
Definition at line 232 of file deterministic-fst.h.
Weight
typedef Arc::Weight Weight
Definition at line 233 of file deterministic-fst.h.
Constructor & Destructor Documentation
CacheDeterministicOnDemandFst()
CacheDeterministicOnDemandFst (DeterministicOnDemandFst< Arc > * fst, StateId num_cached_arcs = 100000)
We don't take ownership of this pointer. The argument is "really" const.
Definition at line 223 of file deterministic-fst-inl.h.
References CacheDeterministicOnDemandFst< Arc >::cached_arcs_, rnnlm::i, and KALDI_ASSERT.
                             : fst_(fst),
                               num_cached_arcs_(num_cached_arcs),
                               cached_arcs_(num_cached_arcs) {
   KALDI_ASSERT(num_cached_arcs > 0);
   for (StateId i = 0; i < num_cached_arcs; i++)
     cached_arcs_[i].first = kNoStateId; // Invalidate all elements of the cache.
 }
Member Function Documentation
Final()
virtual Weight Final (StateId s) inline virtual
We don't bother caching the final-probs, just the arcs.
Implements DeterministicOnDemandFst< Arc >.
Definition at line 243 of file deterministic-fst.h.
References DeterministicOnDemandFst< Arc >::GetArc().
Referenced by fst::TestBackoffAndCache().
 { return fst_->Final(s); }
GetArc()
bool GetArc (StateId s, Label ilabel, Arc * oarc) virtual
Note: ilabel must not be epsilon.
Implements DeterministicOnDemandFst< Arc >.
Definition at line 234 of file deterministic-fst-inl.h.
References CacheDeterministicOnDemandFst< Arc >::cached_arcs_, CacheDeterministicOnDemandFst< Arc >::fst_, CacheDeterministicOnDemandFst< Arc >::GetIndex(), and KALDI_ASSERT.
Referenced by fst::TestBackoffAndCache().
{
   // Note: we don't cache anything in case a requested arc does not exist.
   // In the uses that we imagine this will be put to, essentially all the
   // requested arcs will exist.  This only affects efficiency.
   KALDI_ASSERT(s >= 0 && ilabel != 0);
   size_t index = this->GetIndex(s, ilabel);
   if (cached_arcs_[index].first == s &&
       cached_arcs_[index].second.ilabel == ilabel) {
     *oarc = cached_arcs_[index].second;
     return true;
   } else {
     Arc arc;
     if (fst_->GetArc(s, ilabel, &arc)) {
       cached_arcs_[index].first = s;
       cached_arcs_[index].second = arc;
       *oarc = arc;
       return true;
     } else {
       return false;
     }
   }
 }
GetIndex()
size_t GetIndex (StateId src_state, Label ilabel) inline private
Definition at line 210 of file deterministic-fst-inl.h.
Referenced by CacheDeterministicOnDemandFst< Arc >::GetArc().
{
   const StateId p1 = 26597, p2 = 50329; // these are two
   // values that I drew at random from a table of primes.
   // note: num_cached_arcs_ > 0.
   // We cast to size_t before the modulus, to ensure the
   // result is positive.
   return static_cast<size_t>(src_state * p1 + ilabel * p2) %
       static_cast<size_t>(num_cached_arcs_);
 }
Start()
virtual StateId Start () inline virtual
Implements DeterministicOnDemandFst< Arc >.
Definition at line 240 of file deterministic-fst.h.
Referenced by fst::TestCompose().
 { return fst_->Start(); }
Member Data Documentation
cached_arcs_
std::vector<std::pair<StateId, Arc> > cached_arcs_ private
Definition at line 253 of file deterministic-fst.h.
Referenced by CacheDeterministicOnDemandFst< Arc >::CacheDeterministicOnDemandFst(), and CacheDeterministicOnDemandFst< Arc >::GetArc().
fst_
DeterministicOnDemandFst<Arc>* fst_ private
Definition at line 251 of file deterministic-fst.h.
Referenced by CacheDeterministicOnDemandFst< Arc >::GetArc().
num_cached_arcs_
StateId num_cached_arcs_ private
Definition at line 252 of file deterministic-fst.h.
The documentation for this class was generated from the following files:
fstext/deterministic-fst.h
fstext/deterministic-fst-inl.h