Kaldi: InputImplBase Class Reference
InputImplBase Class Reference abstract
Public Member Functions
virtual bool Open (const std::string &filename, bool binary)=0
virtual std::istream & Stream ()=0
virtual int32 Close ()=0
virtual InputType MyType ()=0
virtual ~InputImplBase ()
Detailed Description
Definition at line 359 of file kaldi-io.cc.
Constructor & Destructor Documentation
~InputImplBase()
virtual ~InputImplBase () inline virtual
Definition at line 378 of file kaldi-io.cc.
 { }
Member Function Documentation
Close()
virtual int32 Close () pure virtual
Implemented in OffsetFileInputImpl, PipeInputImpl, StandardInputImpl, and FileInputImpl.
Referenced by Input::Close().
MyType()
virtual InputType MyType () pure virtual
Implemented in OffsetFileInputImpl, PipeInputImpl, StandardInputImpl, and FileInputImpl.
Referenced by Input::OpenInternal().
Open()
virtual bool Open (const std::string & filename, bool binary) pure virtual
Implemented in OffsetFileInputImpl, PipeInputImpl, StandardInputImpl, and FileInputImpl.
Referenced by Input::OpenInternal().
Stream()
virtual std::istream& Stream () pure virtual
Implemented in OffsetFileInputImpl, PipeInputImpl, StandardInputImpl, and FileInputImpl.
Referenced by Input::OpenInternal(), and Input::Stream().
The documentation for this class was generated from the following file:
util/kaldi-io.cc