Kaldi: OptionalSumDescriptor Class Reference
OptionalSumDescriptor Class Reference
This is the case of class SumDescriptor, in which we contain just one term, and that term is optional (an IfDefined() expression).
#include <nnet-descriptor.h>
Public Member Functions
virtual void GetDependencies (const Index &ind, std::vector< Cindex > *dependencies) const
Given an Index at the output of this Descriptor, append to "dependencies" a list of Cindexes that describes what inputs we potentially depend on.
virtual bool IsComputable (const Index &ind, const CindexSet &cindex_set, std::vector< Cindex > *used_inputs) const
This function exists to enable us to manage optional dependencies, i.e.
virtual int32 Dim (const Nnet &nnet) const
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
This function appends to "node_indexes" a list (not necessarily sorted or unique) of all the node indexes that this descriptor may forward data from.
virtual BaseFloat GetScaleForNode (int32 node_index) const
This function returns the scale on the node-index 'node_index' when it appears in expressions inside this descriptor.
virtual int32 Modulus () const
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
written form is: if required_ == true, "<written-form-of-src>" else "IfDefined(<written-form-of-src>)".
virtual SumDescriptor * Copy () const
OptionalSumDescriptor (SumDescriptor *src)
virtual ~OptionalSumDescriptor ()
Public Member Functions inherited from SumDescriptor
virtual ~SumDescriptor ()
Private Attributes
SumDescriptor * src_
Detailed Description
This is the case of class SumDescriptor, in which we contain just one term, and that term is optional (an IfDefined() expression).
That term is a general SumDescriptor. The written form is: `IfDefined(<descriptor>)`, e.g. `IfDefined(Offset(lstm2.s, -3))`
Definition at line 383 of file nnet-descriptor.h.
Constructor & Destructor Documentation
OptionalSumDescriptor()
OptionalSumDescriptor (SumDescriptor * src) inline
Definition at line 406 of file nnet-descriptor.h.
 : src_(src) { }
~OptionalSumDescriptor()
virtual ~OptionalSumDescriptor () inline virtual
Definition at line 407 of file nnet-descriptor.h.
 { delete src_; }
Member Function Documentation
Copy()
SumDescriptor * Copy () const virtual
Implements SumDescriptor.
Definition at line 253 of file nnet-descriptor.cc.
{
   return new OptionalSumDescriptor(src_->Copy());
 }
Dim()
int32 Dim (const Nnet & nnet) const virtual
Implements SumDescriptor.
Definition at line 271 of file nnet-descriptor.cc.
{
   return src_->Dim(nnet);
 }
GetDependencies()
void GetDependencies (const Index & ind, std::vector< Cindex > * dependencies) const virtual
Given an Index at the output of this Descriptor, append to "dependencies" a list of Cindexes that describes what inputs we potentially depend on.
The output list is not necessarily sorted, and this function doesn't make sure that it's unique.
Implements SumDescriptor.
Definition at line 257 of file nnet-descriptor.cc.
{
   src_->GetDependencies(ind, dependencies);
 }
GetNodeDependencies()
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
This function appends to "node_indexes" a list (not necessarily sorted or unique) of all the node indexes that this descriptor may forward data from.
Implements SumDescriptor.
Definition at line 289 of file nnet-descriptor.cc.
{
   src_->GetNodeDependencies(node_indexes);
 }
GetScaleForNode()
BaseFloat GetScaleForNode (int32 node_index) const virtual
This function returns the scale on the node-index 'node_index' when it appears in expressions inside this descriptor.
E.g. if the descriptor is just `Scale(tdnn2, 2.0)` and the node index for `tdnn2` is 4, then GetScaleForNode(4) would return 2.0. It will return +infinity if the node is >= 0 and does not appear in this descriptor. If node_index < 0, it returns the constant offset value from this descriptor, which will equal 0.0 if there is no expression like `Const(1.0, 512)` in this node. If a particular node_index > 0 appears in different sub-expressions of the descriptor with different scales it is an error (it's not supported) and this function would crash.
Implements SumDescriptor.
Definition at line 275 of file nnet-descriptor.cc.
References KALDI_ERR.
{
   BaseFloat ans = src_->GetScaleForNode(node_index);
   if (node_index < 0 && ans != 0.0) {
     // node_index < 0 means that the user is querying about the scale this
     // expression puts on the constant value.  If there is a nonzero scale
     // (i.e. a Const() expression) inside an IfDefined() expression, which
     // is what OptionalSumDescriptor handles, then it is an error: the user
     // is trying to code something that we do not currently support.
     KALDI_ERR << "Illegal combination of IfDefined() expression and "
         "Const() expression encountered.";
   }
   return ans;
 }
IsComputable()
virtual bool IsComputable (const Index & ind, const CindexSet & cindex_set, std::vector< Cindex > * used_inputs) const inline virtual
This function exists to enable us to manage optional dependencies, i.e.
for making sense of expressions like (A + (B is present)) and (A if present; if not, B). Suppose we are trying to compute the index "ind", and the user represents that "cindex_set" is the set of Cindexes are available to the computation; then this function will return true if we can compute the expression given these inputs; and if so, will output to "used_inputs" the list of Cindexes that this expression will be a summation over.
Parameters
[in] ind The index that we want to compute at the output of the Descriptor.
[in] cindex_set The set of Cindexes that are available at the input of the Descriptor.
[out] used_inputs If non-NULL, if this function returns true then to this vector will be *appended* the inputs that will actually participate in the computation. Else (if non-NULL) it will be left unchanged.
Returns
Returns true if this output is computable given the provided inputs.
Implements SumDescriptor.
Definition at line 387 of file nnet-descriptor.h.
References ForwardingDescriptor::Dim(), ForwardingDescriptor::GetNodeDependencies(), and ForwardingDescriptor::GetScaleForNode().
{
       return src_->IsComputable(ind, cindex_set, used_inputs) || true;
   }
Modulus()
virtual int32 Modulus () const inline virtual
Implements SumDescriptor.
Definition at line 399 of file nnet-descriptor.h.
References ForwardingDescriptor::Copy(), and ForwardingDescriptor::WriteConfig().
 { return src_->Modulus(); }
WriteConfig()
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
written form is: if required_ == true, "<written-form-of-src>" else "IfDefined(<written-form-of-src>)".
Implements SumDescriptor.
Definition at line 263 of file nnet-descriptor.cc.
{
   os << "IfDefined(";
   src_->WriteConfig(os, node_names);
   os << ")";
 }
Member Data Documentation
src_
SumDescriptor* src_ private
Definition at line 409 of file nnet-descriptor.h.
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc