Kaldi: ScalarClusterable Class Reference
ScalarClusterable Class Reference
Classes and functions related to clustering
ScalarClusterable clusters scalars with x^2 loss.
#include <clusterable-classes.h>
Public Member Functions
ScalarClusterable ()
ScalarClusterable (BaseFloat x)
virtual std::string Type () const
Return a string that describes the inherited type.
virtual BaseFloat Objf () const
Return the objective function associated with the stats [assuming ML estimation].
virtual void SetZero ()
Set stats to empty.
virtual void Add (const Clusterable &other_in)
Add other stats.
virtual void Sub (const Clusterable &other_in)
Subtract other stats.
virtual Clusterable * Copy () const
Return a copy of this object.
virtual BaseFloat Normalizer () const
Return the normalizer (typically, count) associated with the stats.
virtual void Write (std::ostream &os, bool binary) const
Write data to stream.
virtual Clusterable * ReadNew (std::istream &is, bool binary) const
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
std::string Info ()
BaseFloat Mean ()
Public Member Functions inherited from Clusterable
virtual void Scale (BaseFloat f)
Scale the stats by a positive number f [not mandatory to supply this].
virtual ~Clusterable ()
virtual BaseFloat ObjfPlus (const Clusterable &other) const
Return the objective function of the combined object this + other.
virtual BaseFloat ObjfMinus (const Clusterable &other) const
Return the objective function of the subtracted object this - other.
virtual BaseFloat Distance (const Clusterable &other) const
Return the objective function decrease from merging the two clusters, negated to be a positive number (or zero).
Private Member Functions
void Read (std::istream &is, bool binary)
Private Attributes
BaseFloat x_
BaseFloat x2_
BaseFloat count_
Detailed Description
ScalarClusterable clusters scalars with x^2 loss.
Definition at line 34 of file clusterable-classes.h.
Constructor & Destructor Documentation
ScalarClusterable() [1/2]
ScalarClusterable () inline
Definition at line 36 of file clusterable-classes.h.
 : x_(0), x2_(0), count_(0) {}
ScalarClusterable() [2/2]
ScalarClusterable (BaseFloat x) inline explicit
Definition at line 37 of file clusterable-classes.h.
 : x_(x), x2_(x*x), count_(1) {}
Member Function Documentation
Add()
void Add (const Clusterable & other) virtual
Add other stats.
Implements Clusterable.
Definition at line 78 of file clusterable-classes.cc.
References KALDI_ASSERT, Clusterable::Type(), and ScalarClusterable::x_.
Referenced by ScalarClusterable::Copy(), ScalarClusterable::SetZero(), kaldi::TestAddToClustersOptimized(), and GaussClusterable::Type().
{
   KALDI_ASSERT(other_in.Type() == "scalar");
   const ScalarClusterable *other =
       static_cast<const ScalarClusterable*>(&other_in);
   x_ += other->x_;
   x2_ += other->x2_;
   count_ += other->count_;
 }
Copy()
Clusterable * Copy () const virtual
Return a copy of this object.
Implements Clusterable.
Definition at line 96 of file clusterable-classes.cc.
References ScalarClusterable::Add().
Referenced by GaussClusterable::Normalizer(), ScalarClusterable::SetZero(), and kaldi::TestAddToClusters().
{
   ScalarClusterable *ans = new ScalarClusterable();
   ans->Add(*this);
   return ans;
 }
Info()
std::string Info ()
Definition at line 122 of file clusterable-classes.cc.
Referenced by ScalarClusterable::Normalizer().
{
   std::stringstream str;
   if (count_ == 0) {
     str << "[empty]";
   } else {
     str << "[mean " << (x_ / count_) << ", var " << (x2_ / count_ -
         (x_ * x_ / (count_ * count_))) << "]";
   }
   return str.str();
 }
Mean()
BaseFloat Mean () inline
Definition at line 53 of file clusterable-classes.h.
References ScalarClusterable::count_, and ScalarClusterable::x_.
Referenced by kaldi::TestAddToClusters().
 { return (count_ != 0 ? x_/count_ : 0.0); }
Normalizer()
virtual BaseFloat Normalizer () const inline virtual
Return the normalizer (typically, count) associated with the stats.
Implements Clusterable.
Definition at line 44 of file clusterable-classes.h.
References ScalarClusterable::count_, ScalarClusterable::Info(), ScalarClusterable::ReadNew(), and ScalarClusterable::Write().
{
     return static_cast<BaseFloat>(count_);
   }
Objf()
BaseFloat Objf () const virtual
Return the objective function associated with the stats [assuming ML estimation].
Implements Clusterable.
Definition at line 69 of file clusterable-classes.cc.
References KALDI_ASSERT.
Referenced by kaldi::TestDistance(), kaldi::TestObjfMinus(), kaldi::TestObjfPlus(), kaldi::TestSumObjfAndSumNormalizer(), ScalarClusterable::Type(), and GaussClusterable::Type().
{
   if (count_ == 0) {
     return 0;
   } else {
     KALDI_ASSERT(count_ > 0);
     return -(x2_ - x_ * x_ / count_);
   }
 }
Read()
void Read (std::istream & is, bool binary) private
Definition at line 115 of file clusterable-classes.cc.
References kaldi::ExpectToken(), and kaldi::ReadBasicType().
Referenced by ScalarClusterable::ReadNew().
{
   ExpectToken(is, binary, "SCL");
   ReadBasicType(is, binary, &x_);
   ReadBasicType(is, binary, &x2_);
   ReadBasicType(is, binary, &count_);
 }
ReadNew()
Clusterable * ReadNew (std::istream & os, bool binary) const virtual
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
Implements Clusterable.
Definition at line 109 of file clusterable-classes.cc.
References ScalarClusterable::Read().
Referenced by ScalarClusterable::Normalizer(), and GaussClusterable::Normalizer().
{
   ScalarClusterable *sc = new ScalarClusterable();
   sc->Read(is, binary);
   return sc;
 }
SetZero()
virtual void SetZero () inline virtual
Set stats to empty.
Implements Clusterable.
Definition at line 40 of file clusterable-classes.h.
References ScalarClusterable::Add(), ScalarClusterable::Copy(), ScalarClusterable::count_, ScalarClusterable::Sub(), ScalarClusterable::x2_, and ScalarClusterable::x_.
Referenced by GaussClusterable::Type().
 { count_ = x_ = x2_ = 0.0; }
Sub()
void Sub (const Clusterable & other) virtual
Subtract other stats.
Implements Clusterable.
Definition at line 87 of file clusterable-classes.cc.
References KALDI_ASSERT, Clusterable::Type(), and ScalarClusterable::x_.
Referenced by ScalarClusterable::SetZero(), and GaussClusterable::Type().
{
   KALDI_ASSERT(other_in.Type() == "scalar");
   const ScalarClusterable *other =
       static_cast<const ScalarClusterable*>(&other_in);
   x_ -= other->x_;
   x2_ -= other->x2_;
   count_ -= other->count_;
 }
Type()
virtual std::string Type () const inline virtual
Return a string that describes the inherited type.
Implements Clusterable.
Definition at line 38 of file clusterable-classes.h.
References ScalarClusterable::Objf().
 { return "scalar"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write data to stream.
Implements Clusterable.
Definition at line 102 of file clusterable-classes.cc.
References kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by ScalarClusterable::Normalizer(), and GaussClusterable::Normalizer().
{
   WriteToken(os, binary, "SCL");  // magic string.
   WriteBasicType(os, binary, x_);
   WriteBasicType(os, binary, x2_);
   WriteBasicType(os, binary, count_);
 }
Member Data Documentation
count_
BaseFloat count_ private
Definition at line 57 of file clusterable-classes.h.
Referenced by GaussClusterable::count(), ScalarClusterable::Mean(), ScalarClusterable::Normalizer(), GaussClusterable::Normalizer(), ScalarClusterable::SetZero(), and GaussClusterable::SetZero().
x2_
BaseFloat x2_ private
Definition at line 56 of file clusterable-classes.h.
Referenced by ScalarClusterable::SetZero().
x_
BaseFloat x_ private
Definition at line 55 of file clusterable-classes.h.
Referenced by ScalarClusterable::Add(), ScalarClusterable::Mean(), ScalarClusterable::SetZero(), and ScalarClusterable::Sub().
The documentation for this class was generated from the following files:
tree/clusterable-classes.h
tree/clusterable-classes.cc