Kaldi: DecodableAmNnetSimpleParallel Class Reference
DecodableAmNnetSimpleParallel Class Reference
#include <nnet-am-decodable-simple.h>
Public Member Functions
DecodableAmNnetSimpleParallel (const NnetSimpleComputationOptions &opts, const TransitionModel &trans_model, const AmNnetSimple &am_nnet, const MatrixBase< BaseFloat > &feats, const VectorBase< BaseFloat > *ivector=NULL, const MatrixBase< BaseFloat > *online_ivectors=NULL, int32 online_ivector_period=1)
This decodable object is for use in multi-threaded decoding.
virtual BaseFloat LogLikelihood (int32 frame, int32 transition_id)
Returns the log likelihood, which will be negated in the decoder.
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
~DecodableAmNnetSimpleParallel ()
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmNnetSimpleParallel)
void DeletePointers ()
Private Attributes
CachingOptimizingCompiler compiler_
const TransitionModel & trans_model_
Matrix< BaseFloat > * feats_copy_
Vector< BaseFloat > * ivector_copy_
Matrix< BaseFloat > * online_ivectors_copy_
DecodableNnetSimple * decodable_nnet_
Detailed Description
Definition at line 318 of file nnet-am-decodable-simple.h.
Constructor & Destructor Documentation
DecodableAmNnetSimpleParallel()
DecodableAmNnetSimpleParallel (const NnetSimpleComputationOptions & opts, const TransitionModel & trans_model, const AmNnetSimple & am_nnet, const MatrixBase< BaseFloat > & feats, const VectorBase< BaseFloat > * ivector = NULL, const MatrixBase< BaseFloat > * online_ivectors = NULL, int32 online_ivector_period = 1)
This decodable object is for use in multi-threaded decoding.
It differs from DecodableAmNnetSimple in two respects: (1) It doesn't keep around pointers to the features and iVectors; instead, it creates copies of them (so the caller can delete the originals). (2) It doesn't support the user passing in a pointer to the CachingOptimizingCompiler– because making that thread safe would be quite complicated, and in any case multi-threaded decoding probably makes the most sense when using CPU, and in that case we don't expect the compilation phase to dominate.
This constructor takes features as input, and you can either supply a single iVector input, estimated in batch-mode ('ivector'), or 'online' iVectors ('online_ivectors' and 'online_ivector_period', or none at all. Note: it stores references to all arguments to the constructor, so don't delete them till this goes out of scope.
Parameters
[in] opts The options class. Warning: it includes an acoustic weight, whose default is 0.1; you may sometimes want to change this to 1.0.
[in] trans_model The transition model to use. This takes care of the mapping from transition-id (which is an arg to LogLikelihood()) to pdf-id (which is used internally).
[in] am_nnet The neural net that we're going to do the computation with; it may provide priors to divide by.
[in] feats A pointer to the input feature matrix; must be non-NULL.
[in] ivector If you are using iVectors estimated in batch mode, a pointer to the iVector, else NULL.
[in] online_ivectors If you are using iVectors estimated 'online' a pointer to the iVectors, else NULL.
[in] online_ivector_period If you are using iVectors estimated 'online' (i.e. if online_ivectors != NULL) gives the periodicity (in frames) with which the iVectors are estimated.
Definition at line 313 of file nnet-am-decodable-simple.cc.
References DecodableAmNnetSimpleParallel::compiler_, DecodableAmNnetSimpleParallel::decodable_nnet_, DecodableAmNnetSimpleParallel::DeletePointers(), DecodableAmNnetSimpleParallel::feats_copy_, AmNnetSimple::GetNnet(), DecodableAmNnetSimpleParallel::ivector_copy_, KALDI_ERR, DecodableAmNnetSimpleParallel::online_ivectors_copy_, and AmNnetSimple::Priors().
                                 :
     compiler_(am_nnet.GetNnet(), opts.optimize_config, opts.compiler_config),
     trans_model_(trans_model),
     feats_copy_(NULL),
     ivector_copy_(NULL),
     online_ivectors_copy_(NULL),
     decodable_nnet_(NULL) {
   try {
     feats_copy_ = new Matrix<BaseFloat>(feats);
     if (ivector != NULL)
       ivector_copy_ = new Vector<BaseFloat>(*ivector);
     if (online_ivectors != NULL)
       online_ivectors_copy_ = new Matrix<BaseFloat>(*online_ivectors);
     decodable_nnet_ = new DecodableNnetSimple(opts, am_nnet.GetNnet(),
                                               am_nnet.Priors(), *feats_copy_,
                                               &compiler_, ivector_copy_,
                                               online_ivectors_copy_,
                                               online_ivector_period);
   } catch (...) {
     DeletePointers();
     KALDI_ERR << "Error occurred in constructor (see above)";
   }
 }
~DecodableAmNnetSimpleParallel()
~DecodableAmNnetSimpleParallel () inline
Definition at line 379 of file nnet-am-decodable-simple.h.
References kaldi::DeletePointers(), and KALDI_DISALLOW_COPY_AND_ASSIGN.
 { DeletePointers(); }
Member Function Documentation
DeletePointers()
void DeletePointers () private
Definition at line 345 of file nnet-am-decodable-simple.cc.
References DecodableAmNnetSimpleParallel::decodable_nnet_, DecodableAmNnetSimpleParallel::feats_copy_, DecodableAmNnetSimpleParallel::ivector_copy_, and DecodableAmNnetSimpleParallel::online_ivectors_copy_.
Referenced by DecodableAmNnetSimpleParallel::DecodableAmNnetSimpleParallel().
{
   // delete[] does nothing for null pointers, so we have no checks.
   delete decodable_nnet_;
   decodable_nnet_ = NULL;
   delete feats_copy_;
   feats_copy_ = NULL;
   delete ivector_copy_;
   ivector_copy_ = NULL;
   delete online_ivectors_copy_;
   online_ivectors_copy_ = NULL;
 }
IsLastFrame()
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frames are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). Caution: the behavior of this function in an online setting is being changed somewhat. In future it may return false in cases where we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. The plan in future is to rely more on NumFramesReady(), and in future, IsLastFrame() would always return false in an online-decoding setting, and would only return true in a decoding-from-matrix setting where we want to allow the last delta or LDA features to be flushed out for compatibility with the baseline setup.
Implements DecodableInterface.
Definition at line 374 of file nnet-am-decodable-simple.h.
References KALDI_ASSERT.
{
     KALDI_ASSERT(frame < NumFramesReady());
     return (frame == NumFramesReady() - 1);
   }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmNnetSimpleParallel) private
LogLikelihood()
BaseFloat LogLikelihood (int32 frame, int32 index) virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Definition at line 358 of file nnet-am-decodable-simple.cc.
References DecodableAmNnetSimpleParallel::decodable_nnet_, DecodableNnetSimple::GetOutput(), DecodableAmNnetSimpleParallel::trans_model_, and TransitionModel::TransitionIdToPdf().
{
   int32 pdf_id = trans_model_.TransitionIdToPdf(transition_id);
   return decodable_nnet_->GetOutput(frame, pdf_id);
 }
NumFramesReady()
virtual int32 NumFramesReady () const inline virtual
The call NumFramesReady() will return the number of frames currently available for this decodable object.
This is for use in setups where you don't want the decoder to block while waiting for input. This is newly added as of Jan 2014, and I hope, going forward, to rely on this mechanism more than IsLastFrame to know when to stop decoding.
Reimplemented from DecodableInterface.
Definition at line 368 of file nnet-am-decodable-simple.h.
{
     return decodable_nnet_->NumFrames();
   }
NumIndices()
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst).
Implements DecodableInterface.
Definition at line 372 of file nnet-am-decodable-simple.h.
 { return trans_model_.NumTransitionIds(); }
Member Data Documentation
compiler_
CachingOptimizingCompiler compiler_ private
Definition at line 384 of file nnet-am-decodable-simple.h.
Referenced by DecodableAmNnetSimpleParallel::DecodableAmNnetSimpleParallel().
decodable_nnet_
DecodableNnetSimple* decodable_nnet_ private
Definition at line 391 of file nnet-am-decodable-simple.h.
Referenced by DecodableAmNnetSimpleParallel::DecodableAmNnetSimpleParallel(), DecodableAmNnetSimpleParallel::DeletePointers(), and DecodableAmNnetSimpleParallel::LogLikelihood().
feats_copy_
Matrix<BaseFloat>* feats_copy_ private
Definition at line 387 of file nnet-am-decodable-simple.h.
Referenced by DecodableAmNnetSimpleParallel::DecodableAmNnetSimpleParallel(), and DecodableAmNnetSimpleParallel::DeletePointers().
ivector_copy_
Vector<BaseFloat>* ivector_copy_ private
Definition at line 388 of file nnet-am-decodable-simple.h.
Referenced by DecodableAmNnetSimpleParallel::DecodableAmNnetSimpleParallel(), and DecodableAmNnetSimpleParallel::DeletePointers().
online_ivectors_copy_
Matrix<BaseFloat>* online_ivectors_copy_ private
Definition at line 389 of file nnet-am-decodable-simple.h.
Referenced by DecodableAmNnetSimpleParallel::DecodableAmNnetSimpleParallel(), and DecodableAmNnetSimpleParallel::DeletePointers().
trans_model_
const TransitionModel& trans_model_ private
Definition at line 385 of file nnet-am-decodable-simple.h.
Referenced by DecodableAmNnetSimpleParallel::LogLikelihood().
The documentation for this class was generated from the following files:
nnet3/nnet-am-decodable-simple.h
nnet3/nnet-am-decodable-simple.cc