Kaldi: ParallelComponent Class Reference
ParallelComponent Class Reference
#include <nnet-parallel-component.h>
Public Member Functions
ParallelComponent (int32 dim_in, int32 dim_out)
~ParallelComponent ()
Component * Copy () const
Copy component (deep copy),.
ComponentType GetType () const
Get Type Identification of the component,.
const Nnet & GetNestedNnet (int32 id) const
Nnet & GetNestedNnet (int32 id)
void InitData (std::istream &is)
Initialize the content of the component by the 'line' from the prototype,.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters,.
void GetGradient (VectorBase< BaseFloat > *gradient) const
Get gradient reshaped as a vector,.
void GetParams (VectorBase< BaseFloat > *params) const
Get the trainable parameters reshaped as a vector,.
void SetParams (const VectorBase< BaseFloat > &params)
Set the trainable parameters from, reshaped as a vector,.
std::string Info () const
Print some additional info (after <ComponentName> and the dims),.
std::string InfoGradient () const
Print some additional info about gradient (after <...> and dims),.
std::string InfoPropagate () const
std::string InfoBackPropagate () const
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters,.
void SetTrainOptions (const NnetTrainOptions &opts)
Overriding the default, which was UpdatableComponent::SetTrainOptions(...)
void SetLearnRateCoef (BaseFloat val)
Overriding the default, which was UpdatableComponent::SetLearnRateCoef(...)
void SetBiasLearnRateCoef (BaseFloat val)
Overriding the default, which was UpdatableComponent::SetBiasLearnRateCoef(...)
void SetSeqLengths (const std::vector< int32 > &sequence_lengths)
Overriding the default, which was MultistreamComponent::SetSeqLengths(...)
Public Member Functions inherited from MultistreamComponent
MultistreamComponent (int32 input_dim, int32 output_dim)
bool IsMultistream () const
Check if component has 'Recurrent' interface (trainable and recurrent),.
int32 NumStreams () const
virtual void ResetStreams (const std::vector< int32 > &stream_reset_flag)
Optional function to reset the transfer of context (not used for BLSTMs.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters,.
const NnetTrainOptions & GetTrainOptions () const
Get the training options from the component,.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
Generic interface of a component,.
virtual ~Component ()
int32 InputDim () const
Get the dimension of the input,.
int32 OutputDim () const
Get the dimension of the output,.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward-pass propagation 'in' -> 'out',.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
void Write (std::ostream &os, bool binary) const
Write the component to a stream,.
Private Attributes
std::vector< Nnet > nnet_
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjected, kBlstmProjected,
kRecurrentComponent, kActivationFunction = 0x0200, kSoftmax, kHiddenSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kParametricRelu,
kDropout, kLengthNormComponent, kTranform = 0x0400, kRbm,
kSplice, kCopy, kTranspose, kBlockLinearity,
kAddShift, kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent,
kSimpleSentenceAveragingComponent, kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent,
kMaxPooling2DComponent, kFramePoolingComponent, kParallelComponent, kMultiBasisComponent
}
Component type identification mechanism,.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Converts component type to marker,.
static ComponentType MarkerToType (const std::string &s)
Converts marker to component type (case insensitive),.
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file,.
static Component * Read (std::istream &is, bool binary)
Read the component from a stream (static method),.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Protected Attributes inherited from MultistreamComponent
std::vector< int32 > sequence_lengths_
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters,.
BaseFloat learn_rate_coef_
Scalar applied to learning rate for weight matrices (to be used in ::Update method),.
BaseFloat bias_learn_rate_coef_
Scalar applied to learning rate for bias (to be used in ::Update method),.
Protected Attributes inherited from Component
int32 input_dim_
Data members,.
int32 output_dim_
Dimension of the output of the Component,.
Detailed Description
Definition at line 36 of file nnet-parallel-component.h.
Constructor & Destructor Documentation
ParallelComponent()
ParallelComponent (int32 dim_in, int32 dim_out) inline
Definition at line 38 of file nnet-parallel-component.h.
Referenced by ParallelComponent::Copy().
                                                 :
     MultistreamComponent(dim_in, dim_out)
   { }
~ParallelComponent()
~ParallelComponent () inline
Definition at line 42 of file nnet-parallel-component.h.
   { }
Member Function Documentation
BackpropagateFnc()
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 264 of file nnet-parallel-component.h.
References CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyFromMat(), rnnlm::i, and ParallelComponent::nnet_.
{
     // column-offsets for data buffers 'in,out',
     int32 input_offset = 0, output_offset = 0;
     // loop over nnets,
     for (int32 i = 0; i < nnet_.size(); i++) {
       // get the data 'windows',
       CuSubMatrix<BaseFloat> src(
         out_diff.ColRange(output_offset, nnet_[i].OutputDim())
       );
       CuSubMatrix<BaseFloat> tgt(
         in_diff->ColRange(input_offset, nnet_[i].InputDim())
       );
       // ::Backpropagate through auxiliary matrix (CuMatrix in the interface),
       CuMatrix<BaseFloat> tgt_aux;
       nnet_[i].Backpropagate(src, &tgt_aux);
       tgt.CopyFromMat(tgt_aux);
       // advance the offsets,
       input_offset += nnet_[i].InputDim();
       output_offset += nnet_[i].OutputDim();
     }
   }
Copy()
Component* Copy () const inline virtual
Copy component (deep copy),.
Implements Component.
Definition at line 45 of file nnet-parallel-component.h.
References ParallelComponent::ParallelComponent().
 { return new ParallelComponent(*this); }
GetGradient()
void GetGradient (VectorBase< BaseFloat > * gradient) const inline virtual
Get gradient reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 158 of file nnet-parallel-component.h.
References VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, ParallelComponent::nnet_, ParallelComponent::NumParams(), and VectorBase< Real >::Range().
{
     KALDI_ASSERT(gradient->Dim() == NumParams());
     int32 offset = 0;
     for (int32 i = 0; i < nnet_.size(); i++) {
       int32 n_params = nnet_[i].NumParams();
       Vector<BaseFloat> gradient_aux;  // we need 'Vector<>',
       nnet_[i].GetGradient(&gradient_aux);  // copy gradient from Nnet,
       gradient->Range(offset, n_params).CopyFromVec(gradient_aux);
       offset += n_params;
     }
     KALDI_ASSERT(offset == NumParams());
   }
GetNestedNnet() [1/2]
const Nnet& GetNestedNnet (int32 id) const inline
Definition at line 48 of file nnet-parallel-component.h.
References ParallelComponent::nnet_.
 { return nnet_.at(id); }
GetNestedNnet() [2/2]
Nnet& GetNestedNnet (int32 id) inline
Definition at line 49 of file nnet-parallel-component.h.
References ParallelComponent::nnet_.
 { return nnet_.at(id); }
GetParams()
void GetParams (VectorBase< BaseFloat > * params) const inline virtual
Get the trainable parameters reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 171 of file nnet-parallel-component.h.
References VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, ParallelComponent::nnet_, ParallelComponent::NumParams(), and VectorBase< Real >::Range().
{
     KALDI_ASSERT(params->Dim() == NumParams());
     int32 offset = 0;
     for (int32 i = 0; i < nnet_.size(); i++) {
       int32 n_params = nnet_[i].NumParams();
       Vector<BaseFloat> params_aux;  // we need 'Vector<>',
       nnet_[i].GetParams(&params_aux);  // copy params from Nnet,
       params->Range(offset, n_params).CopyFromVec(params_aux);
       offset += n_params;
     }
     KALDI_ASSERT(offset == NumParams());
   }
GetType()
ComponentType GetType () const inline virtual
Get Type Identification of the component,.
Implements Component.
Definition at line 46 of file nnet-parallel-component.h.
References Component::kParallelComponent.
 { return kParallelComponent; }
Info()
std::string Info () const inline virtual
Print some additional info (after <ComponentName> and the dims),.
Reimplemented from Component.
Definition at line 195 of file nnet-parallel-component.h.
References rnnlm::i, and ParallelComponent::nnet_.
{
     std::ostringstream os;
     os << "\n";
     for (int32 i = 0; i < nnet_.size(); i++) {
       os << "nested_network #" << i+1 << " {\n"
          << nnet_[i].Info()
          << "}\n";
     }
     std::string s(os.str());
     s.erase(s.end() -1);  // removing last '\n'
     return s;
   }
InfoBackPropagate()
std::string InfoBackPropagate () const inline
Definition at line 231 of file nnet-parallel-component.h.
References rnnlm::i, and ParallelComponent::nnet_.
{
     std::ostringstream os;
     for (int32 i = 0; i < nnet_.size(); i++) {
       os << "nested_backpropagate #" << i+1 << " {\n"
          << nnet_[i].InfoBackPropagate(false)
          << "}\n";
     }
     return os.str();
   }
InfoGradient()
std::string InfoGradient () const inline virtual
Print some additional info about gradient (after <...> and dims),.
Reimplemented from Component.
Definition at line 208 of file nnet-parallel-component.h.
References rnnlm::i, and ParallelComponent::nnet_.
{
     std::ostringstream os;
     os << "\n";
     for (int32 i = 0; i < nnet_.size(); i++) {
       os << "nested_gradient #" << i+1 << " {\n"
          << nnet_[i].InfoGradient(false)
          << "}\n";
     }
     std::string s(os.str());
     s.erase(s.end() -1);  // removing last '\n'
     return s;
   }
InfoPropagate()
std::string InfoPropagate () const inline
Definition at line 221 of file nnet-parallel-component.h.
References rnnlm::i, and ParallelComponent::nnet_.
{
     std::ostringstream os;
     for (int32 i = 0; i < nnet_.size(); i++) {
       os << "nested_propagate #" << i+1 << " {\n"
          << nnet_[i].InfoPropagate(false)
          << "}\n";
     }
     return os.str();
   }
InitData()
void InitData (std::istream & is) inline virtual
Initialize the content of the component by the 'line' from the prototype,.
Implements UpdatableComponent.
Definition at line 51 of file nnet-parallel-component.h.
References rnnlm::i, Nnet::Init(), Component::InputDim(), KALDI_ASSERT, KALDI_ERR, KALDI_LOG, ParallelComponent::nnet_, Component::OutputDim(), Nnet::Read(), and kaldi::ReadToken().
{
     // define options
     std::vector<std::string> nested_nnet_proto;
     std::vector<std::string> nested_nnet_filename;
     // parse config
     std::string token;
     while (is >> std::ws, !is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<NestedNnet>" || token == "<NestedNnetFilename>") {
         while (is >> std::ws, !is.eof()) {
           std::string file_or_end;
           ReadToken(is, false, &file_or_end);
           if (file_or_end == "</NestedNnet>" ||
               file_or_end == "</NestedNnetFilename>") break;
           nested_nnet_filename.push_back(file_or_end);
         }
       } else if (token == "<NestedNnetProto>") {
         while (is >> std::ws, !is.eof()) {
           std::string file_or_end;
           ReadToken(is, false, &file_or_end);
           if (file_or_end == "</NestedNnetProto>") break;
           nested_nnet_proto.push_back(file_or_end);
         }
       } else { KALDI_ERR << "Unknown token " << token << ", typo in config?"
                          << " (NestedNnet|NestedNnetFilename|NestedNnetProto)";
       }
     }
     // Initialize,
     // First, read nnets from files,
     if (nested_nnet_filename.size() > 0) {
       for (int32 i = 0; i < nested_nnet_filename.size(); i++) {
         Nnet nnet;
         nnet.Read(nested_nnet_filename[i]);
         nnet_.push_back(nnet);
         KALDI_LOG << "Loaded nested <Nnet> from file : "
                   << nested_nnet_filename[i];
       }
     }
     // Second, initialize nnets from prototypes,
     if (nested_nnet_proto.size() > 0) {
       for (int32 i = 0; i < nested_nnet_proto.size(); i++) {
         Nnet nnet;
         nnet.Init(nested_nnet_proto[i]);
         nnet_.push_back(nnet);
         KALDI_LOG << "Initialized nested <Nnet> from prototype : "
                   << nested_nnet_proto[i];
       }
     }
     // Check dim-sum of nested nnets,
     int32 nnet_input_sum = 0, nnet_output_sum = 0;
     for (int32 i = 0; i < nnet_.size(); i++) {
       nnet_input_sum += nnet_[i].InputDim();
       nnet_output_sum += nnet_[i].OutputDim();
     }
     KALDI_ASSERT(InputDim() == nnet_input_sum);
     KALDI_ASSERT(OutputDim() == nnet_output_sum);
   }
NumParams()
int32 NumParams () const inline virtual
Number of trainable parameters,.
Implements UpdatableComponent.
Definition at line 150 of file nnet-parallel-component.h.
References rnnlm::i, and ParallelComponent::nnet_.
Referenced by ParallelComponent::GetGradient(), ParallelComponent::GetParams(), and ParallelComponent::SetParams().
{
     int32 ans = 0;
     for (int32 i = 0; i < nnet_.size(); i++) {
       ans += nnet_[i].NumParams();
     }
     return ans;
   }
PropagateFnc()
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 241 of file nnet-parallel-component.h.
References CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyFromMat(), rnnlm::i, and ParallelComponent::nnet_.
{
     // column-offsets for data buffers 'in,out',
     int32 input_offset = 0, output_offset = 0;
     // loop over nnets,
     for (int32 i = 0; i < nnet_.size(); i++) {
       // get the data 'windows',
       CuSubMatrix<BaseFloat> src(
         in.ColRange(input_offset, nnet_[i].InputDim())
       );
       CuSubMatrix<BaseFloat> tgt(
         out->ColRange(output_offset, nnet_[i].OutputDim())
       );
       // forward through auxiliary matrix, as 'Propagate' requires 'CuMatrix',
       CuMatrix<BaseFloat> tgt_aux;
       nnet_[i].Propagate(src, &tgt_aux);
       tgt.CopyFromMat(tgt_aux);
       // advance the offsets,
       input_offset += nnet_[i].InputDim();
       output_offset += nnet_[i].OutputDim();
     }
   }
ReadData()
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 109 of file nnet-parallel-component.h.
References kaldi::ExpectToken(), rnnlm::i, Component::InputDim(), KALDI_ASSERT, ParallelComponent::nnet_, Component::OutputDim(), Nnet::Read(), and kaldi::ReadBasicType().
{
     // read
     ExpectToken(is, binary, "<NestedNnetCount>");
     int32 nnet_count;
     ReadBasicType(is, binary, &nnet_count);
     for (int32 i = 0; i < nnet_count; i++) {
       ExpectToken(is, binary, "<NestedNnet>");
       int32 dummy;
       ReadBasicType(is, binary, &dummy);
       Nnet nnet;
       nnet.Read(is, binary);
       nnet_.push_back(nnet);
     }
     ExpectToken(is, binary, "</ParallelComponent>");
     // check dim-sum of nested nnets
     int32 nnet_input_sum = 0, nnet_output_sum = 0;
     for (int32 i = 0; i < nnet_.size(); i++) {
       nnet_input_sum += nnet_[i].InputDim();
       nnet_output_sum += nnet_[i].OutputDim();
     }
     KALDI_ASSERT(InputDim() == nnet_input_sum);
     KALDI_ASSERT(OutputDim() == nnet_output_sum);
   }
SetBiasLearnRateCoef()
void SetBiasLearnRateCoef (BaseFloat val) inline virtual
Overriding the default, which was UpdatableComponent::SetBiasLearnRateCoef(...)
Reimplemented from UpdatableComponent.
Definition at line 327 of file nnet-parallel-component.h.
References rnnlm::i, rnnlm::j, ParallelComponent::nnet_, and UpdatableComponent::SetBiasLearnRateCoef().
{
     // loop over nnets,
     for (int32 i = 0; i < nnet_.size(); i++) {
       // loop over components,
       for (int32 j = 0; j < nnet_[i].NumComponents(); j++) {
         if (nnet_[i].GetComponent(j).IsUpdatable()) {
           UpdatableComponent& comp =
             dynamic_cast<UpdatableComponent&>(nnet_[i].GetComponent(j));
           // set the value,
           comp.SetBiasLearnRateCoef(val);
         }
       }
     }
   }
SetLearnRateCoef()
void SetLearnRateCoef (BaseFloat val) inline virtual
Overriding the default, which was UpdatableComponent::SetLearnRateCoef(...)
Reimplemented from UpdatableComponent.
Definition at line 308 of file nnet-parallel-component.h.
References rnnlm::i, rnnlm::j, ParallelComponent::nnet_, and UpdatableComponent::SetLearnRateCoef().
{
     // loop over nnets,
     for (int32 i = 0; i < nnet_.size(); i++) {
       // loop over components,
       for (int32 j = 0; j < nnet_[i].NumComponents(); j++) {
         if (nnet_[i].GetComponent(j).IsUpdatable()) {
           UpdatableComponent& comp =
             dynamic_cast<UpdatableComponent&>(nnet_[i].GetComponent(j));
           // set the value,
           comp.SetLearnRateCoef(val);
         }
       }
     }
   }
SetParams()
void SetParams (const VectorBase< BaseFloat > & params) inline virtual
Set the trainable parameters from, reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 184 of file nnet-parallel-component.h.
References VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, ParallelComponent::nnet_, ParallelComponent::NumParams(), and VectorBase< Real >::Range().
{
     KALDI_ASSERT(params.Dim() == NumParams());
     int32 offset = 0;
     for (int32 i = 0; i < nnet_.size(); i++) {
       int32 n_params = nnet_[i].NumParams();
       nnet_[i].SetParams(params.Range(offset, n_params));
       offset += n_params;
     }
     KALDI_ASSERT(offset == NumParams());
   }
SetSeqLengths()
void SetSeqLengths (const std::vector< int32 > & sequence_lengths) inline virtual
Overriding the default, which was MultistreamComponent::SetSeqLengths(...)
Reimplemented from MultistreamComponent.
Definition at line 346 of file nnet-parallel-component.h.
References rnnlm::i, ParallelComponent::nnet_, and MultistreamComponent::sequence_lengths_.
{
     sequence_lengths_ = sequence_lengths;
     // loop over nnets,
     for (int32 i = 0; i < nnet_.size(); i++) {
       nnet_[i].SetSeqLengths(sequence_lengths);
     }
   }
SetTrainOptions()
void SetTrainOptions (const NnetTrainOptions & opts) inline virtual
Overriding the default, which was UpdatableComponent::SetTrainOptions(...)
Reimplemented from UpdatableComponent.
Definition at line 298 of file nnet-parallel-component.h.
References rnnlm::i, and ParallelComponent::nnet_.
{
     for (int32 i = 0; i < nnet_.size(); i++) {
       nnet_[i].SetTrainOptions(opts);
     }
   }
Update()
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters,.
Implements UpdatableComponent.
Definition at line 289 of file nnet-parallel-component.h.
{
     { }  // do nothing
   }
WriteData()
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 134 of file nnet-parallel-component.h.
References rnnlm::i, ParallelComponent::nnet_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     // useful dims
     int32 nnet_count = nnet_.size();
     //
     WriteToken(os, binary, "<NestedNnetCount>");
     WriteBasicType(os, binary, nnet_count);
     if (!binary) os << "\n";
     for (int32 i = 0; i < nnet_count; i++) {
       WriteToken(os, binary, "<NestedNnet>");
       WriteBasicType(os, binary, i+1);
       if (!binary) os << "\n";
       nnet_[i].Write(os, binary);
     }
     WriteToken(os, binary, "</ParallelComponent>");
   }
Member Data Documentation
nnet_
std::vector<Nnet> nnet_ private
Definition at line 355 of file nnet-parallel-component.h.
Referenced by ParallelComponent::BackpropagateFnc(), ParallelComponent::GetGradient(), ParallelComponent::GetNestedNnet(), ParallelComponent::GetParams(), ParallelComponent::Info(), ParallelComponent::InfoBackPropagate(), ParallelComponent::InfoGradient(), ParallelComponent::InfoPropagate(), ParallelComponent::InitData(), ParallelComponent::NumParams(), ParallelComponent::PropagateFnc(), ParallelComponent::ReadData(), ParallelComponent::SetBiasLearnRateCoef(), ParallelComponent::SetLearnRateCoef(), ParallelComponent::SetParams(), ParallelComponent::SetSeqLengths(), ParallelComponent::SetTrainOptions(), and ParallelComponent::WriteData().
The documentation for this class was generated from the following file:
nnet/nnet-parallel-component.h