Kaldi: CuRand< Real > Class Template Reference
CuRand< Real > Class Template Reference
#include <cu-common.h>
Public Member Functions
CuRand ()
~CuRand ()
void SeedGpu ()
Generate new seed for the GPU,.
void RandUniform (CuMatrixBase< Real > *tgt)
Fill with uniform [0..1] floats,.
void RandUniform (CuMatrix< Real > *tgt)
void RandUniform (CuVectorBase< Real > *tgt)
void RandGaussian (CuMatrixBase< Real > *tgt)
Fill with Normal random numbers,.
void RandGaussian (CuMatrix< Real > *tgt)
void RandGaussian (CuVectorBase< Real > *tgt)
void BinarizeProbs (const CuMatrix< Real > &probs, CuMatrix< Real > *states)
align probabilities to discrete 0/1 states (use uniform sampling),
void AddGaussNoise (CuMatrix< Real > *tgt, Real gscale=1.0)
add gaussian noise to each element,
Detailed Description
template<typename Real>
class kaldi::CuRand< Real >
Definition at line 119 of file cu-common.h.
Constructor & Destructor Documentation
CuRand()
CuRand () inline
Definition at line 36 of file cu-rand.h.
            {
   #if HAVE_CUDA == 1
     if (CuDevice::Instantiate().Enabled()) {
       // Initialize the generator,
       CURAND_SAFE_CALL(curandCreateGenerator(&gen_, CURAND_RNG_PSEUDO_DEFAULT));
       // To get same random sequence, call srand() before the constructor is invoked,
       CURAND_SAFE_CALL(curandSetGeneratorOrdering(gen_, CURAND_ORDERING_PSEUDO_DEFAULT));
       CURAND_SAFE_CALL(curandSetPseudoRandomGeneratorSeed(gen_, RandInt(128, RAND_MAX)));
       CURAND_SAFE_CALL(curandSetGeneratorOffset(gen_, 0));
     }
   #endif
   }
~CuRand()
~CuRand () inline
Definition at line 49 of file cu-rand.h.
             {
   #if HAVE_CUDA == 1
     if (CuDevice::Instantiate().Enabled()) {
       // Release the generator,
       CURAND_SAFE_CALL(curandDestroyGenerator(gen_));
     }
   #endif
   }
Member Function Documentation
AddGaussNoise()
void AddGaussNoise (CuMatrix< Real > * tgt, Real gscale = 1.0)
add gaussian noise to each element,
add gaussian noise to each element
Definition at line 204 of file cu-rand.cc.
Referenced by main(), and CuRand< float >::SeedGpu().
{
   // Use the option kStrideEqualNumCols to ensure consistency (because when
   // memory is nearly exhausted, the stride of CudaMallocPitch may vary).
   CuMatrix<Real> tmp(tgt->NumRows(), tgt->NumCols(),
                      kUndefined, kStrideEqualNumCols);
   this->RandGaussian(&tmp);
   tgt->AddMat(gscale, tmp);
 }
BinarizeProbs()
void BinarizeProbs (const CuMatrix< Real > & probs, CuMatrix< Real > * states)
align probabilities to discrete 0/1 states (use uniform sampling),
convert probabilities binary values,
Definition at line 194 of file cu-rand.cc.
Referenced by main(), and CuRand< float >::SeedGpu().
{
   CuMatrix<Real> tmp(probs.NumRows(), probs.NumCols());
   this->RandUniform(&tmp);  // [0..1]
   tmp.Scale(-1.0);  // [-1..0]
   tmp.AddMat(1.0, probs);  // [-1..+1]
   states->Heaviside(tmp);  // negative
 }
RandGaussian() [1/3]
void RandGaussian (CuMatrixBase< Real > * tgt)
Fill with Normal random numbers,.
Definition at line 113 of file cu-rand.cc.
Referenced by kaldi::CuRandGaussianMatrixBaseSpeedTest(), kaldi::CuRandGaussianMatrixSpeedTest(), kaldi::CuRandGaussianVectorSpeedTest(), CuRand< float >::SeedGpu(), CuPackedMatrix< Real >::SetRandn(), CuVectorBase< float >::SetRandn(), and CuMatrixBase< float >::SetRandn().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     // Better use 'tmp' matrix, 'tgt' can be a window into a larger matrix,
     // so we should not use it to generate random numbers over whole stride.
     // Also, we ensure to have 'even' number of elements for calling 'curand'
     // by possibly adding one column. Even number of elements is required by
     // curandGenerateUniform(), curandGenerateUniformDouble().
     // Use the option kStrideEqualNumCols to ensure consistency
     // (because when memory is nearly exhausted, the stride of CudaMallocPitch
     // may vary).
     MatrixIndexT num_cols_even = tgt->NumCols() + (tgt->NumCols() % 2); // + 0 or 1,
     CuMatrix<Real> tmp(tgt->NumRows(), num_cols_even, kUndefined,
                        kStrideEqualNumCols);
     CURAND_SAFE_CALL(curandGenerateNormalWrap(gen_, tmp.Data(), tmp.NumRows()*tmp.Stride()));
     tgt->CopyFromMat(tmp.ColRange(0,tgt->NumCols()));
     CuDevice::Instantiate().AccuProfile(__func__, tim);
   } else
 #endif
   {
     tgt->Mat().SetRandn();
   }
 }
RandGaussian() [2/3]
void RandGaussian (CuMatrix< Real > * tgt)
Definition at line 139 of file cu-rand.cc.
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     // Here we don't need to use 'tmp' matrix, if the number of elements is even,
     MatrixIndexT num_elements = tgt->NumRows() * tgt->Stride();
     if (0 == (num_elements % 2)) {
       CURAND_SAFE_CALL(curandGenerateNormalWrap(gen_, tgt->Data(), num_elements));
     } else {
       // We use 'tmp' matrix with one column added, this guarantees an even
       // number of elements.  Use the option kStrideEqualNumCols to ensure
       // consistency (because when memory is nearly exhausted, the stride of
       // CudaMallocPitch may vary).
       MatrixIndexT num_cols_even = tgt->NumCols() + (tgt->NumCols() % 2); // + 0 or 1,
       CuMatrix<Real> tmp(tgt->NumRows(), num_cols_even, kUndefined,
                          kStrideEqualNumCols);
       CURAND_SAFE_CALL(curandGenerateNormalWrap(gen_, tmp.Data(),
                                             tmp.NumRows() * tmp.Stride()));
       tgt->CopyFromMat(tmp.ColRange(0,tgt->NumCols()));
     }
     CuDevice::Instantiate().AccuProfile(__func__, tim);
   } else
 #endif
   {
     tgt->Mat().SetRandn();
   }
 }
RandGaussian() [3/3]
void RandGaussian (CuVectorBase< Real > * tgt)
Definition at line 168 of file cu-rand.cc.
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     // To ensure 'even' number of elements, we use 'tmp' vector of even length.
     // Even number of elements is required by 'curand' functions:
     // curandGenerateUniform(), curandGenerateUniformDouble().
     MatrixIndexT num_elements = tgt->Dim();
     if (0 == (num_elements % 2)) {
       CURAND_SAFE_CALL(curandGenerateNormalWrap(gen_, tgt->Data(), tgt->Dim()));
     } else {
       MatrixIndexT dim_even = tgt->Dim() + (tgt->Dim() % 2); // + 0 or 1,
       CuVector<Real> tmp(dim_even, kUndefined);
       CURAND_SAFE_CALL(curandGenerateNormalWrap(gen_, tmp.Data(), tmp.Dim()));
       tgt->CopyFromVec(tmp.Range(0,tgt->Dim()));
     }
     CuDevice::Instantiate().AccuProfile(__func__, tim);
   } else
 #endif
   {
     tgt->Vec().SetRandn();
   }
 }
RandUniform() [1/3]
void RandUniform (CuMatrixBase< Real > * tgt)
Fill with uniform [0..1] floats,.
Definition at line 60 of file cu-rand.cc.
Referenced by kaldi::CuRandUniformMatrixBaseSpeedTest(), kaldi::CuRandUniformMatrixSpeedTest(), kaldi::CuRandUniformVectorSpeedTest(), CuRand< float >::SeedGpu(), CuVectorBase< float >::SetRandUniform(), and CuMatrixBase< float >::SetRandUniform().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     // Better use 'tmp' matrix, 'tgt' can be a window into a larger matrix,
     // so we should not use it to generate random numbers over whole stride.
     // Use the option kStrideEqualNumCols to ensure consistency
     // (because when memory is nearly exhausted, the stride of CudaMallocPitch
     // may vary).
     CuMatrix<Real> tmp(tgt->NumRows(), tgt->NumCols(), kUndefined,
                        kStrideEqualNumCols);
     size_t s = static_cast<size_t>(tmp.NumRows()) * static_cast<size_t>(tmp.Stride());
     CURAND_SAFE_CALL(curandGenerateUniformWrap(gen_, tmp.Data(), s));
     tgt->CopyFromMat(tmp);
     CuDevice::Instantiate().AccuProfile(__func__, tim);
   } else
 #endif
   {
     tgt->Mat().SetRandUniform();
   }
 }
RandUniform() [2/3]
void RandUniform (CuMatrix< Real > * tgt)
Definition at line 83 of file cu-rand.cc.
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     // Here we don't need to use 'tmp' matrix,
     size_t s = static_cast<size_t>(tgt->NumRows()) * static_cast<size_t>(tgt->Stride());
     CURAND_SAFE_CALL(curandGenerateUniformWrap(gen_, tgt->Data(), s));
     CuDevice::Instantiate().AccuProfile(__func__, tim);
   } else
 #endif
   {
     tgt->Mat().SetRandUniform();
   }
 }
RandUniform() [3/3]
void RandUniform (CuVectorBase< Real > * tgt)
Definition at line 99 of file cu-rand.cc.
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     CURAND_SAFE_CALL(curandGenerateUniformWrap(gen_, tgt->Data(), tgt->Dim()));
     CuDevice::Instantiate().AccuProfile(__func__, tim);
   } else
 #endif
   {
     tgt->Vec().SetRandUniform();
   }
 }
SeedGpu()
void SeedGpu () inline
Generate new seed for the GPU,.
Definition at line 59 of file cu-rand.h.
                  {
   #if HAVE_CUDA == 1
     if (CuDevice::Instantiate().Enabled()) {
       // To get same random sequence, call srand() before the method is invoked,
       CURAND_SAFE_CALL(curandSetPseudoRandomGeneratorSeed(gen_, RandInt(128, RAND_MAX)));
       CURAND_SAFE_CALL(curandSetGeneratorOffset(gen_, 0));
     }
   #endif
   }
The documentation for this class was generated from the following files:
cudamatrix/cu-common.h
cudamatrix/cu-rand.h
cudamatrix/cu-rand.cc