Kaldi: NormalizeComponent Class Reference
NormalizeComponent Class Reference
#include <nnet-normalize-component.h>
Public Member Functions
NormalizeComponent (const NormalizeComponent &other)
virtual int32 Properties () const
Return bitmask of the component's properties.
NormalizeComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual Component * Copy () const
Copies component (deep copy).
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Types
enum { kExpSquaredNormFloor = -66 }
Private Member Functions
NormalizeComponent & operator= (const NormalizeComponent &other)
Private Attributes
int32 input_dim_
int32 block_dim_
BaseFloat target_rms_
bool add_log_stddev_
Static Private Attributes
static const BaseFloat kSquaredNormFloor
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 73 of file nnet-normalize-component.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kExpSquaredNormFloor
Definition at line 107 of file nnet-normalize-component.h.
 { kExpSquaredNormFloor = -66 };
Constructor & Destructor Documentation
NormalizeComponent() [1/2]
NormalizeComponent (const NormalizeComponent & other) explicit
Definition at line 36 of file nnet-normalize-component.cc.
                                                                      :
     input_dim_(other.input_dim_), block_dim_(other.block_dim_),
     target_rms_(other.target_rms_),
     add_log_stddev_(other.add_log_stddev_) { }
NormalizeComponent() [2/2]
NormalizeComponent () inline
Definition at line 82 of file nnet-normalize-component.h.
Referenced by NormalizeComponent::Copy().
 { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 177 of file nnet-normalize-component.cc.
References NormalizeComponent::add_log_stddev_, NormalizeComponent::block_dim_, CuMatrixBase< Real >::Data(), kaldi::cu::DiffNormalizePerRow(), NormalizeComponent::input_dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Stride(), and NormalizeComponent::target_rms_.
Referenced by NormalizeComponent::Copy(), and BatchNormComponent::Properties().
{
   if (!in_deriv)
     return;
   if (block_dim_ != input_dim_) {
     int32 num_blocks = input_dim_ / block_dim_,
         new_num_rows = in_value.NumRows() * num_blocks,
         output_block_dim = block_dim_ + (add_log_stddev_ ? 1 : 0);
     KALDI_ASSERT(in_value.Stride() == in_value.NumCols() &&
                  out_deriv.Stride() == out_deriv.NumCols() &&
                  in_deriv->Stride() == in_deriv->NumCols());
     CuSubMatrix<BaseFloat> in_value_reshaped(in_value.Data(), new_num_rows,
                                              block_dim_, block_dim_),
         out_deriv_reshaped(out_deriv.Data(), new_num_rows,
                            output_block_dim, output_block_dim),
         in_deriv_reshaped(in_deriv->Data(), new_num_rows,
                           block_dim_, block_dim_);
     cu::DiffNormalizePerRow(in_value_reshaped, out_deriv_reshaped, target_rms_,
                             add_log_stddev_, &in_deriv_reshaped);
   } else {
     cu::DiffNormalizePerRow(in_value, out_deriv, target_rms_, add_log_stddev_,
                             in_deriv);
   }
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 85 of file nnet-normalize-component.h.
References NormalizeComponent::Backprop(), NormalizeComponent::NormalizeComponent(), NormalizeComponent::Propagate(), NormalizeComponent::Read(), and NormalizeComponent::Write().
 { return new NormalizeComponent(*this); }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 113 of file nnet-normalize-component.cc.
References NormalizeComponent::add_log_stddev_, NormalizeComponent::block_dim_, NormalizeComponent::input_dim_, NormalizeComponent::InputDim(), NormalizeComponent::OutputDim(), NormalizeComponent::target_rms_, and NormalizeComponent::Type().
Referenced by NormalizeComponent::OutputDim(), and BatchNormComponent::OutputDim().
{
   std::ostringstream stream;
   stream << Type() << ", input-dim=" << InputDim()
          << ", output-dim=" << OutputDim() << ", target-rms=" << target_rms_
          << ", add-log-stddev=" << std::boolalpha << add_log_stddev_;
   if (block_dim_ != input_dim_)
     stream << ", block-dim=" << block_dim_;
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 41 of file nnet-normalize-component.cc.
References NormalizeComponent::add_log_stddev_, NormalizeComponent::block_dim_, ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), NormalizeComponent::input_dim_, KALDI_ERR, NormalizeComponent::target_rms_, NormalizeComponent::Type(), and ConfigLine::WholeLine().
Referenced by BatchNormComponent::OutputDim(), and NormalizeComponent::Type().
{
   input_dim_ = 0;
   add_log_stddev_ = false;
   target_rms_ = 1.0;
   bool ok = cfl->GetValue("dim", &input_dim_) ||
       cfl->GetValue("input-dim", &input_dim_);
   block_dim_ = input_dim_;
   cfl->GetValue("block-dim", &block_dim_);
   cfl->GetValue("target-rms", &target_rms_);
   cfl->GetValue("add-log-stddev", &add_log_stddev_);
   if (!ok || cfl->HasUnusedValues() || input_dim_ <= 0 || target_rms_ <= 0.0 ||
       block_dim_ <= 0 || input_dim_ % block_dim_ != 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 100 of file nnet-normalize-component.h.
References NormalizeComponent::input_dim_.
Referenced by NormalizeComponent::Info(), and NormalizeComponent::Propagate().
 { return input_dim_; }
operator=()
NormalizeComponent& operator= (const NormalizeComponent & other) private
Referenced by NormalizeComponent::OutputDim().
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 101 of file nnet-normalize-component.h.
References NormalizeComponent::add_log_stddev_, NormalizeComponent::block_dim_, NormalizeComponent::Info(), NormalizeComponent::input_dim_, and NormalizeComponent::operator=().
Referenced by NormalizeComponent::Info(), and NormalizeComponent::Propagate().
{
     return (input_dim_ + (add_log_stddev_ ? (input_dim_ / block_dim_) : 0));
   }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 132 of file nnet-normalize-component.cc.
References NormalizeComponent::add_log_stddev_, NormalizeComponent::block_dim_, CuMatrixBase< Real >::Data(), NormalizeComponent::input_dim_, NormalizeComponent::InputDim(), KALDI_ASSERT, kaldi::cu::NormalizePerRow(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), NormalizeComponent::OutputDim(), CuMatrixBase< Real >::Stride(), and NormalizeComponent::target_rms_.
Referenced by NormalizeComponent::Copy(), and BatchNormComponent::Properties().
{
   KALDI_ASSERT(in.NumCols() == InputDim() && out->NumCols() == OutputDim() &&
                in.NumRows() == out->NumRows());
   if (block_dim_ != input_dim_) {
     int32 num_blocks = input_dim_ / block_dim_,
         new_num_rows = in.NumRows() * num_blocks,
         output_block_dim = block_dim_ + (add_log_stddev_ ? 1 : 0);
     KALDI_ASSERT(in.Stride() == in.NumCols() && out->Stride() == out->NumCols());
     CuSubMatrix<BaseFloat> in_reshaped(in.Data(), new_num_rows,
                                        block_dim_, block_dim_),
         out_reshaped(out->Data(), new_num_rows,
                      output_block_dim, output_block_dim);
     cu::NormalizePerRow(in_reshaped, target_rms_, add_log_stddev_,
                         &out_reshaped);
   } else {
     cu::NormalizePerRow(in, target_rms_, add_log_stddev_, out);
   }
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 77 of file nnet-normalize-component.h.
References NormalizeComponent::add_log_stddev_, NormalizeComponent::block_dim_, NormalizeComponent::input_dim_, kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kInputContiguous, kaldi::nnet3::kOutputContiguous, kaldi::nnet3::kPropagateInPlace, and kaldi::nnet3::kSimpleComponent.
{
     return kSimpleComponent|kBackpropNeedsInput|kBackpropAdds|
         (add_log_stddev_ ? 0 : kPropagateInPlace|kBackpropInPlace) |
         (block_dim_ != input_dim_ ? kInputContiguous|kOutputContiguous : 0);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 57 of file nnet-normalize-component.cc.
References NormalizeComponent::add_log_stddev_, NormalizeComponent::block_dim_, count, kaldi::nnet3::ExpectToken(), NormalizeComponent::input_dim_, KALDI_ASSERT, CuVector< Real >::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), and NormalizeComponent::target_rms_.
Referenced by NormalizeComponent::Copy(), and BatchNormComponent::Properties().
{
   std::string token;
   ReadToken(is, binary, &token);
   if (token == "<NormalizeComponent>") {
     ReadToken(is, binary, &token);
   }
   KALDI_ASSERT(token == "<Dim>" || token == "<InputDim>");
   ReadBasicType(is, binary, &input_dim_); // Read dimension.
   ReadToken(is, binary, &token);
   if (token == "<BlockDim>") {
     ReadBasicType(is, binary, &block_dim_);
     ReadToken(is, binary, &token);
   } else {
     block_dim_ = input_dim_;
   }
   // read target_rms_ if it is available.
   if (token == "<TargetRms>") {
     ReadBasicType(is, binary, &target_rms_);
     ReadToken(is, binary, &token);
   }
   //  Read add_log_stddev_ token, if it is available.
   if (token == "<AddLogStddev>") {
     ReadBasicType(is, binary, &add_log_stddev_);
     ReadToken(is, binary, &token);
   } else {
     add_log_stddev_ = false;
   }
   if (token == "<ValueAvg>") {
     // back-compatibility code.
     CuVector<double> temp;
     temp.Read(is, binary);
     ExpectToken(is, binary, "<DerivAvg>");
     temp.Read(is, binary);
     ExpectToken(is, binary, "<Count>");
     double count;
     ReadBasicType(is, binary, &count);
     ReadToken(is, binary, &token);
   }
   KALDI_ASSERT(token == "</NormalizeComponent>");
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 83 of file nnet-normalize-component.h.
References NormalizeComponent::InitFromConfig().
Referenced by NormalizeComponent::Info(), and NormalizeComponent::InitFromConfig().
 { return "NormalizeComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 98 of file nnet-normalize-component.cc.
References NormalizeComponent::add_log_stddev_, NormalizeComponent::block_dim_, NormalizeComponent::input_dim_, NormalizeComponent::target_rms_, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by NormalizeComponent::Copy(), and BatchNormComponent::Properties().
{
   WriteToken(os, binary, "<NormalizeComponent>");
   WriteToken(os, binary, "<InputDim>");
   WriteBasicType(os, binary, input_dim_);
   if (block_dim_ != input_dim_) {
     WriteToken(os, binary, "<BlockDim>");
     WriteBasicType(os, binary, block_dim_);
   }
   WriteToken(os, binary, "<TargetRms>");
   WriteBasicType(os, binary, target_rms_);
   WriteToken(os, binary, "<AddLogStddev>");
   WriteBasicType(os, binary, add_log_stddev_);
   WriteToken(os, binary, "</NormalizeComponent>");
 }
Member Data Documentation
add_log_stddev_
bool add_log_stddev_ private
Definition at line 116 of file nnet-normalize-component.h.
Referenced by NormalizeComponent::Backprop(), NormalizeComponent::Info(), NormalizeComponent::InitFromConfig(), NormalizeComponent::OutputDim(), NormalizeComponent::Propagate(), NormalizeComponent::Properties(), NormalizeComponent::Read(), and NormalizeComponent::Write().
block_dim_
int32 block_dim_ private
Definition at line 113 of file nnet-normalize-component.h.
Referenced by NormalizeComponent::Backprop(), BatchNormComponent::Check(), BatchNormComponent::ComputeDerived(), NormalizeComponent::Info(), NormalizeComponent::InitFromConfig(), NormalizeComponent::OutputDim(), NormalizeComponent::Propagate(), NormalizeComponent::Properties(), BatchNormComponent::Properties(), NormalizeComponent::Read(), and NormalizeComponent::Write().
input_dim_
int32 input_dim_ private
Definition at line 112 of file nnet-normalize-component.h.
Referenced by NormalizeComponent::Backprop(), NormalizeComponent::Info(), NormalizeComponent::InitFromConfig(), NormalizeComponent::InputDim(), NormalizeComponent::OutputDim(), NormalizeComponent::Propagate(), NormalizeComponent::Properties(), NormalizeComponent::Read(), and NormalizeComponent::Write().
kSquaredNormFloor
const BaseFloat kSquaredNormFloor static private
Initial value:
=
    pow(2.0, NormalizeComponent::kExpSquaredNormFloor)
Definition at line 111 of file nnet-normalize-component.h.
target_rms_
BaseFloat target_rms_ private
Definition at line 114 of file nnet-normalize-component.h.
Referenced by NormalizeComponent::Backprop(), BatchNormComponent::Check(), BatchNormComponent::ComputeDerived(), NormalizeComponent::Info(), NormalizeComponent::InitFromConfig(), NormalizeComponent::Propagate(), NormalizeComponent::Read(), and NormalizeComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-normalize-component.h
nnet3/nnet-normalize-component.cc