Kaldi: NnetLdaStatsAccumulator Class Reference
NnetLdaStatsAccumulator Class Reference
Public Member Functions
NnetLdaStatsAccumulator (BaseFloat rand_prune, const Nnet &nnet)
void AccStats (const NnetExample &eg)
void WriteStats (const std::string &stats_wxfilename, bool binary)
Private Member Functions
void AccStatsFromOutput (const NnetExample &eg, const CuMatrixBase< BaseFloat > &nnet_output)
Private Attributes
BaseFloat rand_prune_
const Nnet & nnet_
CachingOptimizingCompiler compiler_
LdaEstimate lda_stats_
Detailed Description
Definition at line 32 of file nnet3-acc-lda-stats.cc.
Constructor & Destructor Documentation
NnetLdaStatsAccumulator()
NnetLdaStatsAccumulator (BaseFloat rand_prune, const Nnet & nnet) inline
Definition at line 34 of file nnet3-acc-lda-stats.cc.
                                            :
       rand_prune_(rand_prune), nnet_(nnet), compiler_(nnet) { }
Member Function Documentation
AccStats()
void AccStats (const NnetExample & eg) inline
Definition at line 38 of file nnet3-acc-lda-stats.cc.
References NnetComputer::AcceptInputs(), NnetLdaStatsAccumulator::AccStatsFromOutput(), CachingOptimizingCompiler::Compile(), NnetLdaStatsAccumulator::compiler_, NnetComputeOptions::debug, kaldi::nnet3::GetComputationRequest(), kaldi::GetVerboseLevel(), NnetExample::io, and NnetLdaStatsAccumulator::nnet_.
Referenced by main().
{
     ComputationRequest request;
     bool need_backprop = false, store_stats = false;
     GetComputationRequest(nnet_, eg, need_backprop, store_stats, &request);
     const NnetComputation &computation = *(compiler_.Compile(request));
     NnetComputeOptions options;
     if (GetVerboseLevel() >= 3)
       options.debug = true;
     NnetComputer computer(options, computation, nnet_, NULL);
     computer.AcceptInputs(nnet_, eg.io);
     computer.Run();
     const CuMatrixBase<BaseFloat> &nnet_output = computer.GetOutput("output");
     AccStatsFromOutput(eg, nnet_output);
   }
AccStatsFromOutput()
void AccStatsFromOutput (const NnetExample & eg, const CuMatrixBase< BaseFloat > & nnet_output) inline private
Definition at line 65 of file nnet3-acc-lda-stats.cc.
References LdaEstimate::Accumulate(), SparseVector< Real >::Data(), VectorBase< Real >::Dim(), LdaEstimate::Dim(), NnetIo::features, GeneralMatrix::GetMatrix(), GeneralMatrix::GetSparseMatrix(), rnnlm::i, LdaEstimate::Init(), NnetExample::io, KALDI_ASSERT, kaldi::kSparseMatrix, NnetLdaStatsAccumulator::lda_stats_, CuMatrixBase< Real >::NumCols(), GeneralMatrix::NumCols(), SparseVector< Real >::NumElements(), CuMatrixBase< Real >::NumRows(), GeneralMatrix::NumRows(), NnetLdaStatsAccumulator::rand_prune_, kaldi::RandPrune(), SparseMatrix< Real >::Row(), and GeneralMatrix::Type().
Referenced by NnetLdaStatsAccumulator::AccStats().
{
     BaseFloat rand_prune = rand_prune_;
     const NnetIo *output_supervision = NULL;
     for (size_t i = 0; i < eg.io.size(); i++)
       if (eg.io[i].name == "output")
         output_supervision = &(eg.io[i]);
     KALDI_ASSERT(output_supervision != NULL && "no output in eg named 'output'");
     int32 num_rows = output_supervision->features.NumRows(),
         num_pdfs = output_supervision->features.NumCols();
     KALDI_ASSERT(num_rows == nnet_output.NumRows());
     if (lda_stats_.Dim() == 0)
       lda_stats_.Init(num_pdfs, nnet_output.NumCols());
     if (output_supervision->features.Type() == kSparseMatrix) {
       const SparseMatrix<BaseFloat> &smat =
           output_supervision->features.GetSparseMatrix();
       for (int32 r = 0; r < num_rows; r++) {
         // the following, transferring row by row to CPU, would be wasteful
         // if we actually were using a GPU, but we don't anticipate doing this
         // in this program.
         CuSubVector<BaseFloat> cu_row(nnet_output, r);
         // "row" is actually just a redudant copy, since we're likely on CPU,
         // but we're about to do an outer product, so this doesn't dominate.
         Vector<BaseFloat> row(cu_row);
         const SparseVector<BaseFloat> &post(smat.Row(r));
         const std::pair<MatrixIndexT, BaseFloat> *post_data = post.Data(),
             *post_end = post_data + post.NumElements();
         for (; post_data != post_end; ++post_data) {
           MatrixIndexT pdf = post_data->first;
           BaseFloat weight = post_data->second;
           BaseFloat pruned_weight = RandPrune(weight, rand_prune);
           if (pruned_weight != 0.0)
             lda_stats_.Accumulate(row, pdf, pruned_weight);
         }
       }
     } else {
       Matrix<BaseFloat> output_mat;
       output_supervision->features.GetMatrix(&output_mat);
       for (int32 r = 0; r < num_rows; r++) {
         // the following, transferring row by row to CPU, would be wasteful
         // if we actually were using a GPU, but we don't anticipate doing this
         // in this program.
         CuSubVector<BaseFloat> cu_row(nnet_output, r);
         // "row" is actually just a redudant copy, since we're likely on CPU,
         // but we're about to do an outer product, so this doesn't dominate.
         Vector<BaseFloat> row(cu_row);
         SubVector<BaseFloat> post(output_mat, r);
         int32 num_pdfs = post.Dim();
         for (int32 pdf = 0; pdf < num_pdfs; pdf++) {
           BaseFloat weight = post(pdf);
           BaseFloat pruned_weight = RandPrune(weight, rand_prune);
           if (pruned_weight != 0.0)
             lda_stats_.Accumulate(row, pdf, pruned_weight);
         }
       }
     }
   }
WriteStats()
void WriteStats (const std::string & stats_wxfilename, bool binary) inline
Definition at line 54 of file nnet3-acc-lda-stats.cc.
References KALDI_ERR, KALDI_LOG, NnetLdaStatsAccumulator::lda_stats_, LdaEstimate::TotCount(), and kaldi::WriteKaldiObject().
Referenced by main().
{
     if (lda_stats_.TotCount() == 0) {
       KALDI_ERR << "Accumulated no stats.";
     } else {
       WriteKaldiObject(lda_stats_, stats_wxfilename, binary);
       KALDI_LOG << "Accumulated stats, soft frame count = "
                 << lda_stats_.TotCount() << ".  Wrote to "
                 << stats_wxfilename;
     }
   }
Member Data Documentation
compiler_
CachingOptimizingCompiler compiler_ private
Definition at line 127 of file nnet3-acc-lda-stats.cc.
Referenced by NnetLdaStatsAccumulator::AccStats().
lda_stats_
LdaEstimate lda_stats_ private
Definition at line 128 of file nnet3-acc-lda-stats.cc.
Referenced by NnetLdaStatsAccumulator::AccStatsFromOutput(), and NnetLdaStatsAccumulator::WriteStats().
nnet_
const Nnet& nnet_ private
Definition at line 126 of file nnet3-acc-lda-stats.cc.
Referenced by NnetLdaStatsAccumulator::AccStats().
rand_prune_
BaseFloat rand_prune_ private
Definition at line 125 of file nnet3-acc-lda-stats.cc.
Referenced by NnetLdaStatsAccumulator::AccStatsFromOutput().
The documentation for this class was generated from the following file:
nnet3bin/nnet3-acc-lda-stats.cc