Kaldi: BasicVectorHolder< BasicType > Class Template Reference
BasicVectorHolder< BasicType > Class Template Reference
"Holder types"
A Holder for a vector of basic types, e.g.
#include <kaldi-holder-inl.h>
Public Types
typedef std::vector< BasicType > T
Public Member Functions
BasicVectorHolder ()
void Clear ()
bool Read (std::istream &is)
T & Value ()
void Swap (BasicVectorHolder< BasicType > *other)
bool ExtractRange (const BasicVectorHolder< BasicType > &other, const std::string &range)
~BasicVectorHolder ()
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (BasicVectorHolder)
Private Attributes
T t_
Detailed Description
template<class BasicType>
class kaldi::BasicVectorHolder< BasicType >
A Holder for a vector of basic types, e.g.
std::vector<int32>, std::vector<float>, and so on. Note: a basic type is defined as a type for which ReadBasicType and WriteBasicType are implemented, i.e. integer and floating types, and bool.
Definition at line 224 of file kaldi-holder-inl.h.
Member Typedef Documentation
T
typedef std::vector<BasicType> T
Definition at line 226 of file kaldi-holder-inl.h.
Constructor & Destructor Documentation
BasicVectorHolder()
BasicVectorHolder () inline
Definition at line 228 of file kaldi-holder-inl.h.
 { }
~BasicVectorHolder()
~BasicVectorHolder () inline
Definition at line 331 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::KALDI_DISALLOW_COPY_AND_ASSIGN().
 { }
Member Function Documentation
Clear()
void Clear () inline
Definition at line 260 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
 { t_.clear(); }
ExtractRange()
bool ExtractRange (const BasicVectorHolder< BasicType > & other, const std::string & range) inline
Definition at line 325 of file kaldi-holder-inl.h.
References KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 317 of file kaldi-holder-inl.h.
 { return true; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (BasicVectorHolder< BasicType >) private
Read()
bool Read (std::istream & is) inline
Definition at line 263 of file kaldi-holder-inl.h.
References kaldi::InitKaldiInputStream(), KALDI_WARN, kaldi::ReadBasicType(), and KaldiObjectHolder< KaldiType >::t_.
{
     t_.clear();
     bool is_binary;
     if (!InitKaldiInputStream(is, &is_binary)) {
       KALDI_WARN << "Reading Table object [integer type], failed reading binary"
           " header\n";
       return false;
     }
     if (!is_binary) {
       // In text mode, we terminate with newline.
       std::string line;
       getline(is, line);  // this will discard the \n, if present.
       if (is.fail()) {
         KALDI_WARN << "BasicVectorHolder::Read, error reading line " <<
             (is.eof() ? "[eof]" : "");
         return false;  // probably eof.  fail in any case.
       }
       std::istringstream line_is(line);
       try {
         while (1) {
           line_is >> std::ws;  // eat up whitespace.
           if (line_is.eof()) break;
           BasicType bt;
           ReadBasicType(line_is, false, &bt);
           t_.push_back(bt);
         }
         return true;
       } catch(const std::exception &e) {
         KALDI_WARN << "BasicVectorHolder::Read, could not interpret line: "
                    << "'" << line << "'" << "\n" << e.what();
         return false;
       }
     } else {  // binary mode.
       size_t filepos = is.tellg();
       try {
         int32 size;
         ReadBasicType(is, true, &size);
         t_.resize(size);
         for (typename std::vector<BasicType>::iterator iter = t_.begin();
              iter != t_.end();
              ++iter) {
           ReadBasicType(is, true, &(*iter));
         }
         return true;
       } catch(...) {
         KALDI_WARN << "BasicVectorHolder::Read, read error or unexpected data"
             " at archive entry beginning at file position " << filepos;
         return false;
       }
     }
   }
Swap()
void Swap (BasicVectorHolder< BasicType > * other) inline
Definition at line 321 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_, and BasicVectorHolder< BasicType >::t_.
{
     t_.swap(other->t_);
   }
Value()
T& Value () inline
Definition at line 319 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
 { return t_; }
Write()
static bool Write (std::ostream & os, bool binary, const T & t) inline static
Definition at line 230 of file kaldi-holder-inl.h.
References kaldi::InitKaldiOutputStream(), KALDI_ASSERT, KALDI_WARN, and kaldi::WriteBasicType().
{
     InitKaldiOutputStream(os, binary);  // Puts binary header if binary mode.
     try {
       if (binary) {  // need to write the size, in binary mode.
         KALDI_ASSERT(static_cast<size_t>(static_cast<int32>(t.size())) ==
                      t.size());
         // Or this Write routine cannot handle such a large vector.
         // use int32 because it's fixed size regardless of compilation.
         // change to int64 (plus in Read function) if this becomes a problem.
         WriteBasicType(os, binary, static_cast<int32>(t.size()));
         for (typename std::vector<BasicType>::const_iterator iter = t.begin();
              iter != t.end(); ++iter)
           WriteBasicType(os, binary, *iter);
       } else {
         for (typename std::vector<BasicType>::const_iterator iter = t.begin();
              iter != t.end(); ++iter)
           WriteBasicType(os, binary, *iter);
         os << '\n';  // Makes output format more readable and
         // easier to manipulate.  In text mode, this function writes something
         // like "1 2 3\n".
       }
       return os.good();
     } catch(const std::exception &e) {
       KALDI_WARN << "Exception caught writing Table object (BasicVector). "
                  << e.what();
       return false;  // Write failure.
     }
   }
Member Data Documentation
t_
T t_ private
Definition at line 334 of file kaldi-holder-inl.h.
Referenced by BasicVectorHolder< BasicType >::Swap().
The documentation for this class was generated from the following file:
util/kaldi-holder-inl.h