Kaldi: AccumAmDiagGmm Class Reference
AccumAmDiagGmm Class Reference
#include <mle-am-diag-gmm.h>
Public Member Functions
AccumAmDiagGmm ()
~AccumAmDiagGmm ()
void Read (std::istream &in_stream, bool binary, bool add=false)
void Write (std::ostream &out_stream, bool binary) const
void Init (const AmDiagGmm &model, GmmFlagsType flags)
Initializes accumulators for each GMM based on the number of components and dimension.
void Init (const AmDiagGmm &model, int32 dim, GmmFlagsType flags)
Initialization using different dimension than model.
void SetZero (GmmFlagsType flags)
BaseFloat AccumulateForGmm (const AmDiagGmm &model, const VectorBase< BaseFloat > &data, int32 gmm_index, BaseFloat weight)
Accumulate stats for a single GMM in the model; returns log likelihood.
BaseFloat AccumulateForGmmTwofeats (const AmDiagGmm &model, const VectorBase< BaseFloat > &data1, const VectorBase< BaseFloat > &data2, int32 gmm_index, BaseFloat weight)
Accumulate stats for a single GMM in the model; uses data1 for getting posteriors and data2 for stats.
void AccumulateFromPosteriors (const AmDiagGmm &model, const VectorBase< BaseFloat > &data, int32 gmm_index, const VectorBase< BaseFloat > &posteriors)
Accumulates stats for a single GMM in the model using pre-computed Gaussian posteriors.
void AccumulateForGaussian (const AmDiagGmm &am, const VectorBase< BaseFloat > &data, int32 gmm_index, int32 gauss_index, BaseFloat weight)
Accumulate stats for a single Gaussian component in the model.
int32 NumAccs ()
int32 NumAccs () const
BaseFloat TotStatsCount () const
BaseFloat TotCount () const
BaseFloat TotLogLike () const
const AccumDiagGmm & GetAcc (int32 index) const
AccumDiagGmm & GetAcc (int32 index)
void Add (BaseFloat scale, const AccumAmDiagGmm &other)
void Scale (BaseFloat scale)
int32 Dim () const
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (AccumAmDiagGmm)
Private Attributes
std::vector< AccumDiagGmm * > gmm_accumulators_
MLE accumulators and update methods for the GMMs.
double total_frames_
Total counts & likelihood (for diagnostics)
double total_log_like_
Detailed Description
Definition at line 34 of file mle-am-diag-gmm.h.
Constructor & Destructor Documentation
AccumAmDiagGmm()
AccumAmDiagGmm () inline
Definition at line 36 of file mle-am-diag-gmm.h.
References AccumAmDiagGmm::AccumulateForGaussian(), AccumAmDiagGmm::AccumulateForGmm(), AccumAmDiagGmm::AccumulateForGmmTwofeats(), AccumAmDiagGmm::AccumulateFromPosteriors(), AccumAmDiagGmm::Init(), AccumAmDiagGmm::Read(), AccumAmDiagGmm::SetZero(), AccumAmDiagGmm::Write(), and AccumAmDiagGmm::~AccumAmDiagGmm().
 : total_frames_(0.0), total_log_like_(0.0) {}
~AccumAmDiagGmm()
~AccumAmDiagGmm ()
Definition at line 37 of file mle-am-diag-gmm.cc.
References kaldi::DeletePointers(), and AccumAmDiagGmm::gmm_accumulators_.
Referenced by AccumAmDiagGmm::AccumAmDiagGmm().
{
   DeletePointers(&gmm_accumulators_);
 }
Member Function Documentation
AccumulateForGaussian()
void AccumulateForGaussian (const AmDiagGmm & am, const VectorBase< BaseFloat > & data, int32 gmm_index, int32 gauss_index, BaseFloat weight)
Accumulate stats for a single Gaussian component in the model.
Definition at line 108 of file mle-am-diag-gmm.cc.
References AmDiagGmm::GetPdf(), AccumAmDiagGmm::gmm_accumulators_, KALDI_ASSERT, AccumAmDiagGmm::NumAccs(), and DiagGmm::NumGauss().
Referenced by AccumAmDiagGmm::AccumAmDiagGmm().
{
   KALDI_ASSERT(gmm_index >= 0 && gmm_index < NumAccs());
   KALDI_ASSERT(gauss_index >= 0
       && gauss_index < am.GetPdf(gmm_index).NumGauss());
   gmm_accumulators_[gmm_index]->AccumulateForComponent(data, gauss_index, weight);
 }
AccumulateForGmm()
BaseFloat AccumulateForGmm (const AmDiagGmm & model, const VectorBase< BaseFloat > & data, int32 gmm_index, BaseFloat weight)
Accumulate stats for a single GMM in the model; returns log likelihood.
This does not work with multiple feature transforms.
Definition at line 69 of file mle-am-diag-gmm.cc.
References AmDiagGmm::GetPdf(), AccumAmDiagGmm::gmm_accumulators_, KALDI_ASSERT, AccumAmDiagGmm::total_frames_, and AccumAmDiagGmm::total_log_like_.
Referenced by AccumAmDiagGmm::AccumAmDiagGmm(), main(), TestAmDiagGmmAccsIO(), and kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   KALDI_ASSERT(static_cast<size_t>(gmm_index) < gmm_accumulators_.size());
   BaseFloat log_like =
       gmm_accumulators_[gmm_index]->AccumulateFromDiag(model.GetPdf(gmm_index),
                                                        data, weight);
   total_log_like_ += log_like * weight;
   total_frames_ += weight;
   return log_like;
 }
AccumulateForGmmTwofeats()
BaseFloat AccumulateForGmmTwofeats (const AmDiagGmm & model, const VectorBase< BaseFloat > & data1, const VectorBase< BaseFloat > & data2, int32 gmm_index, BaseFloat weight)
Accumulate stats for a single GMM in the model; uses data1 for getting posteriors and data2 for stats.
Returns log likelihood.
Definition at line 81 of file mle-am-diag-gmm.cc.
References AccumDiagGmm::AccumulateFromPosteriors(), AmDiagGmm::GetPdf(), AccumAmDiagGmm::gmm_accumulators_, KALDI_ASSERT, VectorBase< Real >::Scale(), AccumAmDiagGmm::total_frames_, and AccumAmDiagGmm::total_log_like_.
Referenced by AccumAmDiagGmm::AccumAmDiagGmm(), and main().
                       {
   KALDI_ASSERT(static_cast<size_t>(gmm_index) < gmm_accumulators_.size());
   const DiagGmm &gmm = model.GetPdf(gmm_index);
   AccumDiagGmm &acc = *(gmm_accumulators_[gmm_index]);
   Vector<BaseFloat> posteriors;
   BaseFloat log_like = gmm.ComponentPosteriors(data1, &posteriors);
   posteriors.Scale(weight);
   acc.AccumulateFromPosteriors(data2, posteriors);
   total_log_like_ += log_like * weight;
   total_frames_ += weight;
   return log_like;
 }
AccumulateFromPosteriors()
void AccumulateFromPosteriors (const AmDiagGmm & model, const VectorBase< BaseFloat > & data, int32 gmm_index, const VectorBase< BaseFloat > & posteriors)
Accumulates stats for a single GMM in the model using pre-computed Gaussian posteriors.
Definition at line 100 of file mle-am-diag-gmm.cc.
References AccumAmDiagGmm::gmm_accumulators_, KALDI_ASSERT, AccumAmDiagGmm::NumAccs(), VectorBase< Real >::Sum(), and AccumAmDiagGmm::total_frames_.
Referenced by AccumAmDiagGmm::AccumAmDiagGmm().
{
   KALDI_ASSERT(gmm_index >= 0 && gmm_index < NumAccs());
   gmm_accumulators_[gmm_index]->AccumulateFromPosteriors(data, posteriors);
   total_frames_ += posteriors.Sum();
 }
Add()
void Add (BaseFloat scale, const AccumAmDiagGmm & other)
Definition at line 279 of file mle-am-diag-gmm.cc.
References AccumAmDiagGmm::gmm_accumulators_, rnnlm::i, KALDI_ASSERT, AccumAmDiagGmm::NumAccs(), AccumAmDiagGmm::total_frames_, and AccumAmDiagGmm::total_log_like_.
Referenced by AccumAmDiagGmm::TotLogLike().
{
   total_frames_ += scale * other.total_frames_;
   total_log_like_ += scale * other.total_log_like_;
   int32 num_accs = NumAccs();
   KALDI_ASSERT(num_accs == other.NumAccs());
   for (int32 i = 0; i < num_accs; i++)
     gmm_accumulators_[i]->Add(scale, *(other.gmm_accumulators_[i]));
 }
Dim()
int32 Dim () const inline
Definition at line 94 of file mle-am-diag-gmm.h.
References AccumAmDiagGmm::gmm_accumulators_.
Referenced by kaldi::MapAmDiagGmmUpdate(), and kaldi::MleAmDiagGmmUpdate().
                     {
     return (gmm_accumulators_.empty() || !gmm_accumulators_[0] ?
             0 : gmm_accumulators_[0]->Dim());
   }
GetAcc() [1/2]
const AccumDiagGmm & GetAcc (int32 index) const
Definition at line 27 of file mle-am-diag-gmm.cc.
References AccumAmDiagGmm::gmm_accumulators_, and KALDI_ASSERT.
Referenced by kaldi::ComputeAmGmmFeatureDeriv(), kaldi::DoRescalingUpdate(), kaldi::GetStatsDerivative(), kaldi::IsmoothStatsAmDiagGmm(), kaldi::IsmoothStatsAmDiagGmmFromModel(), main(), kaldi::MapAmDiagGmmUpdate(), kaldi::MleAmDiagGmmUpdate(), AccumAmDiagGmm::Scale(), AccumAmDiagGmm::TotLogLike(), AccumAmDiagGmm::TotStatsCount(), kaldi::UpdateEbwAmDiagGmm(), and kaldi::UpdateEbwWeightsAmDiagGmm().
{
   KALDI_ASSERT(index >= 0 && index < static_cast<int32>(gmm_accumulators_.size()));
   return *(gmm_accumulators_[index]);
 }
GetAcc() [2/2]
AccumDiagGmm & GetAcc (int32 index)
Definition at line 32 of file mle-am-diag-gmm.cc.
References AccumAmDiagGmm::gmm_accumulators_, and KALDI_ASSERT.
{
   KALDI_ASSERT(index >= 0 && index < static_cast<int32>(gmm_accumulators_.size()));
   return *(gmm_accumulators_[index]);
 }
Init() [1/2]
void Init (const AmDiagGmm & model, GmmFlagsType flags)
Initializes accumulators for each GMM based on the number of components and dimension.
Definition at line 41 of file mle-am-diag-gmm.cc.
References kaldi::DeletePointers(), AmDiagGmm::GetPdf(), AccumAmDiagGmm::gmm_accumulators_, rnnlm::i, and AmDiagGmm::NumPdfs().
Referenced by AccumAmDiagGmm::AccumAmDiagGmm(), kaldi::GetStatsDerivative(), main(), TestAmDiagGmmAccsIO(), and kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   DeletePointers(&gmm_accumulators_);  // in case was non-empty when called.
   gmm_accumulators_.resize(model.NumPdfs(), NULL);
   for (int32 i = 0; i < model.NumPdfs(); i++) {
     gmm_accumulators_[i] = new AccumDiagGmm();
     gmm_accumulators_[i]->Resize(model.GetPdf(i), flags);
   }
 }
Init() [2/2]
void Init (const AmDiagGmm & model, int32 dim, GmmFlagsType flags)
Initialization using different dimension than model.
Definition at line 51 of file mle-am-diag-gmm.cc.
References kaldi::DeletePointers(), AmDiagGmm::GetPdf(), AccumAmDiagGmm::gmm_accumulators_, rnnlm::i, KALDI_ASSERT, DiagGmm::NumGauss(), and AmDiagGmm::NumPdfs().
{
   KALDI_ASSERT(dim > 0);
   DeletePointers(&gmm_accumulators_);  // in case was non-empty when called.
   gmm_accumulators_.resize(model.NumPdfs(), NULL);
   for (int32 i = 0; i < model.NumPdfs(); i++) {
     gmm_accumulators_[i] = new AccumDiagGmm();
     gmm_accumulators_[i]->Resize(model.GetPdf(i).NumGauss(),
                                  dim, flags);
   }
 }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (AccumAmDiagGmm) private
NumAccs() [1/2]
int32 NumAccs () inline
Definition at line 75 of file mle-am-diag-gmm.h.
References AccumAmDiagGmm::gmm_accumulators_.
Referenced by AccumAmDiagGmm::AccumulateForGaussian(), AccumAmDiagGmm::AccumulateFromPosteriors(), AccumAmDiagGmm::Add(), kaldi::DoRescalingUpdate(), kaldi::GetStatsDerivative(), kaldi::IsmoothStatsAmDiagGmm(), kaldi::IsmoothStatsAmDiagGmmFromModel(), main(), kaldi::MapAmDiagGmmUpdate(), kaldi::MleAmDiagGmmUpdate(), AccumAmDiagGmm::Scale(), AccumAmDiagGmm::TotStatsCount(), kaldi::UpdateEbwAmDiagGmm(), and kaldi::UpdateEbwWeightsAmDiagGmm().
 { return gmm_accumulators_.size(); }
NumAccs() [2/2]
int32 NumAccs () const inline
Definition at line 77 of file mle-am-diag-gmm.h.
References AccumAmDiagGmm::gmm_accumulators_, and AccumAmDiagGmm::TotStatsCount().
 { return gmm_accumulators_.size(); }
Read()
void Read (std::istream & in_stream, bool binary, bool add = false)
Definition at line 117 of file mle-am-diag-gmm.cc.
References kaldi::ExpectToken(), AccumAmDiagGmm::gmm_accumulators_, KALDI_ASSERT, KALDI_ERR, kaldi::ReadBasicType(), AccumAmDiagGmm::total_frames_, and AccumAmDiagGmm::total_log_like_.
Referenced by AccumAmDiagGmm::AccumAmDiagGmm(), main(), and TestAmDiagGmmAccsIO().
{
   int32 num_pdfs;
   ExpectToken(in_stream, binary, "<NUMPDFS>");
   ReadBasicType(in_stream, binary, &num_pdfs);
   KALDI_ASSERT(num_pdfs > 0);
   if (!add || (add && gmm_accumulators_.empty())) {
     gmm_accumulators_.resize(num_pdfs, NULL);
     for (std::vector<AccumDiagGmm*>::iterator it = gmm_accumulators_.begin(),
              end = gmm_accumulators_.end(); it != end; ++it) {
       delete *it;
       *it = new AccumDiagGmm();
       (*it)->Read(in_stream, binary, add);
     }
   } else {
     if (gmm_accumulators_.size() != static_cast<size_t> (num_pdfs))
       KALDI_ERR << "Adding accumulators but num-pdfs do not match: "
                 << (gmm_accumulators_.size()) << " vs. "
                 << (num_pdfs);
     for (std::vector<AccumDiagGmm*>::iterator it = gmm_accumulators_.begin(),
              end = gmm_accumulators_.end(); it != end; ++it)
       (*it)->Read(in_stream, binary, add);
   }
   // TODO(arnab): Bad hack! Need to make this self-delimiting.
   in_stream.peek();  // This will set the EOF bit for older accs.
   if (!in_stream.eof()) {
     double like, frames;
     ExpectToken(in_stream, binary, "<total_like>");
     ReadBasicType(in_stream, binary, &like);
     total_log_like_ = (add)? total_log_like_ + like : like;
     ExpectToken(in_stream, binary, "<total_frames>");
     ReadBasicType(in_stream, binary, &frames);
     total_frames_ = (add)? total_frames_ + frames : frames;
   }
 }
Scale()
void Scale (BaseFloat scale)
Definition at line 270 of file mle-am-diag-gmm.cc.
References AccumDiagGmm::Flags(), AccumAmDiagGmm::GetAcc(), rnnlm::i, AccumAmDiagGmm::NumAccs(), AccumDiagGmm::Scale(), AccumAmDiagGmm::total_frames_, and AccumAmDiagGmm::total_log_like_.
Referenced by AccumAmDiagGmm::TotLogLike().
{
   for (int32 i = 0; i < NumAccs(); i++) {
     AccumDiagGmm &acc = GetAcc(i);
     acc.Scale(scale, acc.Flags());
   }
   total_frames_ *= scale;
   total_log_like_ *= scale;
 }
SetZero()
void SetZero (GmmFlagsType flags)
Definition at line 63 of file mle-am-diag-gmm.cc.
References AccumAmDiagGmm::gmm_accumulators_, and rnnlm::i.
Referenced by AccumAmDiagGmm::AccumAmDiagGmm(), and main().
{
   for (size_t i = 0; i < gmm_accumulators_.size(); i++) {
     gmm_accumulators_[i]->SetZero(flags);
   }
 }
TotCount()
BaseFloat TotCount () const inline
Definition at line 83 of file mle-am-diag-gmm.h.
References AccumAmDiagGmm::total_frames_.
Referenced by main(), and TestAmDiagGmmAccsIO().
 { return total_frames_; }
TotLogLike()
BaseFloat TotLogLike () const inline
Definition at line 84 of file mle-am-diag-gmm.h.
References AccumAmDiagGmm::Add(), AccumAmDiagGmm::GetAcc(), AccumAmDiagGmm::Scale(), and AccumAmDiagGmm::total_log_like_.
Referenced by main(), and TestAmDiagGmmAccsIO().
 { return total_log_like_; }
TotStatsCount()
BaseFloat TotStatsCount () const
Definition at line 261 of file mle-am-diag-gmm.cc.
References AccumAmDiagGmm::GetAcc(), rnnlm::i, AccumAmDiagGmm::NumAccs(), and AccumDiagGmm::occupancy().
Referenced by main(), and AccumAmDiagGmm::NumAccs().
{
   double ans = 0.0;
   for (int32 i = 0; i < NumAccs(); i++) {
     const AccumDiagGmm &acc = GetAcc(i);
     ans += acc.occupancy().Sum();
   }
   return ans;
 }
Write()
void Write (std::ostream & out_stream, bool binary) const
Definition at line 153 of file mle-am-diag-gmm.cc.
References AccumAmDiagGmm::gmm_accumulators_, AccumAmDiagGmm::total_frames_, AccumAmDiagGmm::total_log_like_, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by AccumAmDiagGmm::AccumAmDiagGmm(), main(), and TestAmDiagGmmAccsIO().
{
   int32 num_pdfs = gmm_accumulators_.size();
   WriteToken(out_stream, binary, "<NUMPDFS>");
   WriteBasicType(out_stream, binary, num_pdfs);
   for (std::vector<AccumDiagGmm*>::const_iterator it =
       gmm_accumulators_.begin(), end = gmm_accumulators_.end(); it != end; ++it) {
     (*it)->Write(out_stream, binary);
   }
   WriteToken(out_stream, binary, "<total_like>");
   WriteBasicType(out_stream, binary, total_log_like_);
   WriteToken(out_stream, binary, "<total_frames>");
   WriteBasicType(out_stream, binary, total_frames_);
 }
Member Data Documentation
gmm_accumulators_
std::vector<AccumDiagGmm*> gmm_accumulators_ private
MLE accumulators and update methods for the GMMs.
Definition at line 101 of file mle-am-diag-gmm.h.
Referenced by AccumAmDiagGmm::AccumulateForGaussian(), AccumAmDiagGmm::AccumulateForGmm(), AccumAmDiagGmm::AccumulateForGmmTwofeats(), AccumAmDiagGmm::AccumulateFromPosteriors(), AccumAmDiagGmm::Add(), AccumAmDiagGmm::Dim(), AccumAmDiagGmm::GetAcc(), AccumAmDiagGmm::Init(), AccumAmDiagGmm::NumAccs(), AccumAmDiagGmm::Read(), AccumAmDiagGmm::SetZero(), AccumAmDiagGmm::Write(), and AccumAmDiagGmm::~AccumAmDiagGmm().
total_frames_
double total_frames_ private
Total counts & likelihood (for diagnostics)
Definition at line 104 of file mle-am-diag-gmm.h.
Referenced by AccumAmDiagGmm::AccumulateForGmm(), AccumAmDiagGmm::AccumulateForGmmTwofeats(), AccumAmDiagGmm::AccumulateFromPosteriors(), AccumAmDiagGmm::Add(), AccumAmDiagGmm::Read(), AccumAmDiagGmm::Scale(), AccumAmDiagGmm::TotCount(), and AccumAmDiagGmm::Write().
total_log_like_
double total_log_like_ private
Definition at line 104 of file mle-am-diag-gmm.h.
Referenced by AccumAmDiagGmm::AccumulateForGmm(), AccumAmDiagGmm::AccumulateForGmmTwofeats(), AccumAmDiagGmm::Add(), AccumAmDiagGmm::Read(), AccumAmDiagGmm::Scale(), AccumAmDiagGmm::TotLogLike(), and AccumAmDiagGmm::Write().
The documentation for this class was generated from the following files:
gmm/mle-am-diag-gmm.h
gmm/mle-am-diag-gmm.cc