Kaldi: ArpaFileParser Class Reference
ArpaFileParser Class Reference abstract
ArpaFileParser is an abstract base class for ARPA LM file conversion.
#include <arpa-file-parser.h>
Public Member Functions
ArpaFileParser (ArpaParseOptions options, fst::SymbolTable *symbols)
Constructs the parser with the given options and optional symbol table.
virtual ~ArpaFileParser ()
void Read (std::istream &is)
Read ARPA LM file from a stream.
const ArpaParseOptions & Options () const
Parser options.
Protected Member Functions
virtual void ReadStarted ()
Override called before reading starts.
virtual void HeaderAvailable ()
Override function called to signal that ARPA header with the expected number of n-grams has been read, and ngram_counts() is now valid.
virtual void ConsumeNGram (const NGram &)=0
Pure override that must be implemented to process current n-gram.
virtual void ReadComplete ()
Override function called after the last n-gram has been consumed.
const fst::SymbolTable * Symbols () const
Read-only access to symbol table. Not owned, do not make public.
int32 LineNumber () const
Inside ConsumeNGram(), provides the current line number.
std::string LineReference () const
Inside ConsumeNGram(), returns a formatted reference to the line being compiled, to print out as part of diagnostics.
bool ShouldWarn ()
Increments warning count, and returns true if a warning should be printed or false if the count has exceeded the set maximum.
const std::vector< int32 > & NgramCounts () const
N-gram counts. Valid from the point when HeaderAvailable() is called.
Private Attributes
ArpaParseOptions options_
fst::SymbolTable * symbols_
int32 line_number_
uint32 warning_count_
std::string current_line_
std::vector< int32 > ngram_counts_
Detailed Description
ArpaFileParser is an abstract base class for ARPA LM file conversion.
See ConstArpaLmBuilder and ArpaLmCompiler for usage examples.
Definition at line 81 of file arpa-file-parser.h.
Constructor & Destructor Documentation
ArpaFileParser()
ArpaFileParser (ArpaParseOptions options, fst::SymbolTable * symbols)
Constructs the parser with the given options and optional symbol table.
If symbol table is provided, then the file should contain text n-grams, and the words are mapped to symbols through it. bos_symbol and eos_symbol in the options structure must be valid symbols in the table, and so must be unk_symbol if provided. The table is not owned by the parser, but may be augmented, if oov_handling is set to kAddToSymbols. If symbol table is a null pointer, the file should contain integer symbol values, and oov_handling has no effect. bos_symbol and eos_symbol must be valid symbols still.
Definition at line 32 of file arpa-file-parser.cc.
     : options_(options), symbols_(symbols),
       line_number_(0), warning_count_(0) {
 }
~ArpaFileParser()
~ArpaFileParser () virtual
Definition at line 38 of file arpa-file-parser.cc.
{
 }
Member Function Documentation
ConsumeNGram()
virtual void ConsumeNGram (const NGram &) protected pure virtual
Pure override that must be implemented to process current n-gram.
The n-grams are sent in the file order, which guarantees that all (k-1)-grams are processed before the first k-gram is.
Implemented in ConstArpaLmBuilder, and ArpaLmCompiler.
Referenced by ArpaFileParser::Read().
HeaderAvailable()
virtual void HeaderAvailable () inline protected virtual
Override function called to signal that ARPA header with the expected number of n-grams has been read, and ngram_counts() is now valid.
Reimplemented in ConstArpaLmBuilder, and ArpaLmCompiler.
Definition at line 108 of file arpa-file-parser.h.
Referenced by ArpaFileParser::Read().
 { }
LineNumber()
int32 LineNumber () const inline protected
Inside ConsumeNGram(), provides the current line number.
Definition at line 122 of file arpa-file-parser.h.
 { return line_number_; }
LineReference()
std::string LineReference () const protected
Inside ConsumeNGram(), returns a formatted reference to the line being compiled, to print out as part of diagnostics.
Definition at line 270 of file arpa-file-parser.cc.
References ArpaFileParser::current_line_, and ArpaFileParser::line_number_.
Referenced by ArpaLmCompilerImpl< HistKey >::ConsumeNGram(), and ArpaFileParser::Read().
{
   std::stringstream ss;
   ss << "line " << line_number_ << " [" << current_line_ << "]";
   return ss.str();
 }
NgramCounts()
const std::vector<int32>& NgramCounts () const inline protected
N-gram counts. Valid from the point when HeaderAvailable() is called.
Definition at line 133 of file arpa-file-parser.h.
 { return ngram_counts_; }
Options()
const ArpaParseOptions& Options () const inline
Parser options.
Definition at line 99 of file arpa-file-parser.h.
 { return options_; }
Read()
void Read (std::istream & is)
Read ARPA LM file from a stream.
Definition at line 45 of file arpa-file-parser.cc.
References NGram::backoff, ArpaParseOptions::bos_symbol, ArpaFileParser::ConsumeNGram(), kaldi::ConvertStringToInteger(), kaldi::ConvertStringToReal(), ArpaFileParser::current_line_, ArpaParseOptions::eos_symbol, ArpaFileParser::HeaderAvailable(), ArpaParseOptions::kAddToSymbols, KALDI_ERR, KALDI_LOG, KALDI_WARN, ArpaParseOptions::kReplaceWithUnk, ArpaParseOptions::kSkipNGram, ArpaFileParser::line_number_, ArpaFileParser::LineReference(), NGram::logprob, M_LN10, ArpaParseOptions::max_warnings, ArpaFileParser::ngram_counts_, ArpaParseOptions::oov_handling, ArpaFileParser::options_, PARSE_ERR, ArpaFileParser::ReadComplete(), ArpaFileParser::ReadStarted(), ArpaFileParser::ShouldWarn(), kaldi::SplitStringToVector(), ArpaFileParser::symbols_, kaldi::TrimTrailingWhitespace(), ArpaParseOptions::unk_symbol, ArpaFileParser::warning_count_, and NGram::words.
Referenced by kaldi::BuildConstArpaLm(), and kaldi::Compile().
{
   // Argument sanity checks.
   if (options_.bos_symbol <= 0 || options_.eos_symbol <= 0 ||
       options_.bos_symbol == options_.eos_symbol)
     KALDI_ERR << "BOS and EOS symbols are required, must not be epsilons, and "
               << "differ from each other. Given:"
               << " BOS=" << options_.bos_symbol
               << " EOS=" << options_.eos_symbol;
   if (symbols_ != NULL &&
       options_.oov_handling == ArpaParseOptions::kReplaceWithUnk &&
       (options_.unk_symbol <= 0 ||
        options_.unk_symbol == options_.bos_symbol ||
        options_.unk_symbol == options_.eos_symbol))
     KALDI_ERR << "When symbol table is given and OOV mode is kReplaceWithUnk, "
               << "UNK symbol is required, must not be epsilon, and "
               << "differ from both BOS and EOS symbols. Given:"
               << " UNK=" << options_.unk_symbol
               << " BOS=" << options_.bos_symbol
               << " EOS=" << options_.eos_symbol;
   if (symbols_ != NULL && symbols_->Find(options_.bos_symbol).empty())
     KALDI_ERR << "BOS symbol must exist in symbol table";
   if (symbols_ != NULL && symbols_->Find(options_.eos_symbol).empty())
     KALDI_ERR << "EOS symbol must exist in symbol table";
   if (symbols_ != NULL && options_.unk_symbol > 0 &&
       symbols_->Find(options_.unk_symbol).empty())
     KALDI_ERR << "UNK symbol must exist in symbol table";
   ngram_counts_.clear();
   line_number_ = 0;
   warning_count_ = 0;
   current_line_.clear();
 #define PARSE_ERR (KALDI_ERR << LineReference() << ": ")
   // Give derived class an opportunity to prepare its state.
   ReadStarted();
   // Processes "\data\" section.
   bool keyword_found = false;
   while (++line_number_, getline(is, current_line_) && !is.eof()) {
     if (current_line_.find_first_not_of(" \t\n\r") == std::string::npos) {
       continue;
     }
     TrimTrailingWhitespace(&current_line_);
     // Continue skipping lines until the \data\ marker alone on a line is found.
     if (!keyword_found) {
       if (current_line_ == "\\data\\") {
         KALDI_LOG << "Reading \\data\\ section.";
         keyword_found = true;
       }
       continue;
     }
     if (current_line_[0] == '\\') break;
     // Enters "\data\" section, and looks for patterns like "ngram 1=1000",
     // which means there are 1000 unigrams.
     std::size_t equal_symbol_pos = current_line_.find("=");
     if (equal_symbol_pos != std::string::npos)
       // Guaranteed spaces around the "=".
       current_line_.replace(equal_symbol_pos, 1, " = ");
     std::vector<std::string> col;
     SplitStringToVector(current_line_, " \t", true, &col);
     if (col.size() == 4 && col[0] == "ngram" && col[2] == "=") {
       int32 order, ngram_count = 0;
       if (!ConvertStringToInteger(col[1], &order) ||
           !ConvertStringToInteger(col[3], &ngram_count)) {
         PARSE_ERR << "cannot parse ngram count";
       }
       if (ngram_counts_.size() <= order) {
         ngram_counts_.resize(order);
       }
       ngram_counts_[order - 1] = ngram_count;
     } else {
       KALDI_WARN << LineReference()
                  << ": uninterpretable line in \\data\\ section";
     }
   }
   if (ngram_counts_.size() == 0)
     PARSE_ERR << "\\data\\ section missing or empty.";
   // Signal that grammar order and n-gram counts are known.
   HeaderAvailable();
   NGram ngram;
   ngram.words.reserve(ngram_counts_.size());
   // Processes "\N-grams:" section.
   for (int32 cur_order = 1; cur_order <= ngram_counts_.size(); ++cur_order) {
     // Skips n-grams with zero count.
     if (ngram_counts_[cur_order - 1] == 0)
       KALDI_WARN << "Zero ngram count in ngram order " << cur_order
                  << "(look for 'ngram " << cur_order << "=0' in the \\data\\ "
                  << " section). There is possibly a problem with the file.";
     // Must be looking at a \k-grams: directive at this point.
     std::ostringstream keyword;
     keyword << "\\" << cur_order << "-grams:";
     if (current_line_ != keyword.str()) {
       PARSE_ERR << "invalid directive, expecting '" << keyword.str() << "'";
     }
     KALDI_LOG << "Reading " << current_line_ << " section.";
     int32 ngram_count = 0;
     while (++line_number_, getline(is, current_line_) && !is.eof()) {
       if (current_line_.find_first_not_of(" \n\t\r") == std::string::npos) {
         continue;
       }
       if (current_line_[0] == '\\') {
         TrimTrailingWhitespace(&current_line_);
         std::ostringstream next_keyword;
         next_keyword << "\\" << cur_order + 1 << "-grams:";
         if ((current_line_ != next_keyword.str()) &&
             (current_line_ != "\\end\\")) {
           if (ShouldWarn()) {
             KALDI_WARN << "ignoring possible directive '" << current_line_
                        << "' expecting '" << next_keyword.str() << "'";
             if (warning_count_ > 0 &&
                 warning_count_ > static_cast<uint32>(options_.max_warnings)) {
               KALDI_WARN << "Of " << warning_count_ << " parse warnings, "
                          << options_.max_warnings << " were reported. "
                          << "Run program with --max-arpa-warnings=-1 "
                          << "to see all warnings";
             }
           }
         } else {
           break;
         }
       }
       std::vector<std::string> col;
       SplitStringToVector(current_line_, " \t", true, &col);
       if (col.size() < 1 + cur_order ||
           col.size() > 2 + cur_order ||
           (cur_order == ngram_counts_.size() && col.size() != 1 + cur_order)) {
         PARSE_ERR << "Invalid n-gram data line";
       }
       ++ngram_count;
       // Parse out n-gram logprob and, if present, backoff weight.
       if (!ConvertStringToReal(col[0], &ngram.logprob)) {
         PARSE_ERR << "invalid n-gram logprob '" << col[0] << "'";
       }
       ngram.backoff = 0.0;
       if (col.size() > cur_order + 1) {
         if (!ConvertStringToReal(col[cur_order + 1], &ngram.backoff))
           PARSE_ERR << "invalid backoff weight '" << col[cur_order + 1] << "'";
       }
       // Convert to natural log.
       ngram.logprob *= M_LN10;
       ngram.backoff *= M_LN10;
       ngram.words.resize(cur_order);
       bool skip_ngram = false;
       for (int32 index = 0; !skip_ngram && index < cur_order; ++index) {
         int32 word;
         if (symbols_) {
           // Symbol table provided, so symbol labels are expected.
           if (options_.oov_handling == ArpaParseOptions::kAddToSymbols) {
             word = symbols_->AddSymbol(col[1 + index]);
           } else {
             word = symbols_->Find(col[1 + index]);
             if (word == -1) { // fst::kNoSymbol
               switch (options_.oov_handling) {
                 case ArpaParseOptions::kReplaceWithUnk:
                   word = options_.unk_symbol;
                   break;
                 case ArpaParseOptions::kSkipNGram:
                   if (ShouldWarn())
                     KALDI_WARN << LineReference() << " skipped: word '"
                                << col[1 + index] << "' not in symbol table";
                   skip_ngram = true;
                   break;
                 default:
                   PARSE_ERR << "word '"  << col[1 + index]
                             << "' not in symbol table";
               }
             }
           }
         } else {
           // Symbols not provided, LM file should contain integers.
           if (!ConvertStringToInteger(col[1 + index], &word) || word < 0) {
             PARSE_ERR << "invalid symbol '" << col[1 + index] << "'";
           }
         }
         // Whichever way we got it, an epsilon is invalid.
         if (word == 0) {
           PARSE_ERR << "epsilon symbol '" << col[1 + index]
                     << "' is illegal in ARPA LM";
         }
         ngram.words[index] = word;
       }
       if (!skip_ngram) {
         ConsumeNGram(ngram);
       }
     }
     if (ngram_count > ngram_counts_[cur_order - 1]) {
       PARSE_ERR << "header said there would be " << ngram_counts_[cur_order - 1]
                 << " n-grams of order " << cur_order
                 << ", but we saw more already.";
     }
   }
   if (current_line_ != "\\end\\") {
     PARSE_ERR << "invalid or unexpected directive line, expecting \\end\\";
   }
   if (warning_count_ > 0 &&
       warning_count_ > static_cast<uint32>(options_.max_warnings)) {
     KALDI_WARN << "Of " << warning_count_ << " parse warnings, "
                << options_.max_warnings << " were reported. Run program with "
                << "--max_warnings=-1 to see all warnings";
   }
   current_line_.empty();
   ReadComplete();
 #undef PARSE_ERR
 }
ReadComplete()
virtual void ReadComplete () inline protected virtual
Override function called after the last n-gram has been consumed.
Reimplemented in ConstArpaLmBuilder, and ArpaLmCompiler.
Definition at line 116 of file arpa-file-parser.h.
Referenced by ArpaFileParser::Read().
 { }
ReadStarted()
virtual void ReadStarted () inline protected virtual
Override called before reading starts.
This is the point to prepare any state in the derived class.
Definition at line 104 of file arpa-file-parser.h.
Referenced by ArpaFileParser::Read().
 { }
ShouldWarn()
bool ShouldWarn () protected
Increments warning count, and returns true if a warning should be printed or false if the count has exceeded the set maximum.
Definition at line 276 of file arpa-file-parser.cc.
References ArpaParseOptions::max_warnings, and ArpaFileParser::options_.
Referenced by ArpaLmCompilerImpl< HistKey >::ConsumeNGram(), and ArpaFileParser::Read().
{
   return ++warning_count_ <= static_cast<uint32>(options_.max_warnings);
 }
Symbols()
const fst::SymbolTable* Symbols () const inline protected
Read-only access to symbol table. Not owned, do not make public.
Definition at line 119 of file arpa-file-parser.h.
 { return symbols_; }
Member Data Documentation
current_line_
std::string current_line_ private
Definition at line 140 of file arpa-file-parser.h.
Referenced by ArpaFileParser::LineReference(), and ArpaFileParser::Read().
line_number_
int32 line_number_ private
Definition at line 138 of file arpa-file-parser.h.
Referenced by ArpaFileParser::LineReference(), and ArpaFileParser::Read().
ngram_counts_
std::vector<int32> ngram_counts_ private
Definition at line 141 of file arpa-file-parser.h.
Referenced by ArpaFileParser::Read().
options_
ArpaParseOptions options_ private
Definition at line 136 of file arpa-file-parser.h.
Referenced by ArpaFileParser::Read(), and ArpaFileParser::ShouldWarn().
symbols_
fst::SymbolTable* symbols_ private
Definition at line 137 of file arpa-file-parser.h.
Referenced by ArpaFileParser::Read().
warning_count_
uint32 warning_count_ private
Definition at line 139 of file arpa-file-parser.h.
Referenced by ArpaFileParser::Read().
The documentation for this class was generated from the following files:
lm/arpa-file-parser.h
lm/arpa-file-parser.cc