Kaldi: TxpLts Class Reference
TxpLts Class Reference
Contains a cart tree for each letter Questions are left and right context letters Trees are typically built from a source lexicon using speechtools wagon.
#include <txplts.h>
Public Member Functions
TxpLts ()
~TxpLts ()
void Init (const TxpParseOptions &opts, const std::string &name)
int GetPron (const std::string &word, TxpLexiconLkp *lkp)
Given a word return the result of looking up the pronciation of of each letter in a cart tree.
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
virtual void EndElement (const char *name)
Inherited class for bespoke end element handling.
virtual void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
virtual void StartCData ()
Inherited class for bespoke start cdata handling.
virtual void EndCData ()
Inherited class for bespoke start cdata handling.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
Private Attributes
LtsMap ltslkp_
Lookup from letter to cart tree.
std::string ltr_
holds parser status of current letter
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
Contains a cart tree for each letter Questions are left and right context letters Trees are typically built from a source lexicon using speechtools wagon.
Definition at line 49 of file txplts.h.
Constructor & Destructor Documentation
TxpLts()
TxpLts () inline explicit
Definition at line 51 of file txplts.h.
 {}
~TxpLts()
~TxpLts () inline
Definition at line 52 of file txplts.h.
 {}
Member Function Documentation
GetPron()
int GetPron (const std::string & word, TxpLexiconLkp * lkp)
Given a word return the result of looking up the pronciation of of each letter in a cart tree.
Definition at line 63 of file txplts.cc.
References kaldi::ApplyTree(), TxpUtf8::Clen(), KALDI_WARN, TxpLexiconLkp::lts, TxpLts::ltslkp_, and TxpLexiconLkp::pron.
Referenced by TxpPronounce::AppendPron(), and TxpLts::Init().
{
   TxpUtf8 utf8;
   int32 clen, pos = 0;
   const char *p, *phone, *stress;
   std::string ltr;
   LtsMap::iterator it;
   TxpLtsTree stress_tree;
   bool stress_tree_present = true;
   // get stress lookup
   it = ltslkp_.find(std::string("0"));
   if (it == ltslkp_.end()) {
     stress_tree_present = false;
     KALDI_WARN << "No stress lookup tree: name='0'";
   } else {
     stress_tree = it->second;
   }
   // process each letter
   p = word.c_str();
   while (*p) {
     clen = utf8.Clen(p);
     ltr = std::string(p, clen);
     it = ltslkp_.find(ltr);
     if (it != ltslkp_.end()) {
       phone = ApplyTree(it->second, word.c_str(), pos);
       const char * orig = phone;
       // If not a null result
       if (strcmp("0", phone)) {
         const char *sep = strchr(phone, '_');
         if (!lkp->pron.empty()) lkp->pron += " ";
         // Split the phone on "_" as LTS can return multiphone
         while (sep) {
           lkp->pron += std::string(phone, sep - phone);
           lkp->pron += " ";
           phone = sep + 1;
           sep = strchr(phone, '_');
         }
         // Check is syllabic and if so get stress
         if (phone[strlen(phone) - 1] == '0' && stress_tree_present) {
             stress = ApplyTree(stress_tree, word.c_str(), pos);
             lkp->pron += std::string(phone, strlen(phone) - 1);
             lkp->pron += stress;
             free((void *)stress);
         } else {
           lkp->pron += phone;
         }
       }
       free((void *)orig);
     } else {
       // HACKY: Remove annoying warning for English possessive form
       if (ltr.compare("'"))
         KALDI_WARN << "Letter not in LTS tree: " << ltr;
     }
     p += clen;
     pos++;
   }
   lkp->lts = true;
   return true;
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & name) inline
Definition at line 53 of file txplts.h.
References TxpLts::GetPron(), TxpXmlData::Init(), and TxpLts::StartElement().
Referenced by TxpPronounce::Init().
{
     TxpXmlData::Init(opts, "ccart", name);
   }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 30 of file txplts.cc.
References TxpLts::ltr_, TxpLts::ltslkp_, TxpLtsNode::no, TxpLtsNode::pos, kaldi::pos2int(), TxpLtsNode::posval, TxpLtsTree::root, TxpXmlData::SetAttribute(), TxpLtsNode::val, and TxpLtsNode::yes.
Referenced by TxpLts::Init().
{
   std::string terminal;
   std::string nonterminal;
   LtsMap::iterator it;
   if (!strcmp(name, "tree")) {
     SetAttribute("ltr", atts, &ltr_);
     SetAttribute("terminal", atts, &terminal);
     SetAttribute("nonterminal", atts, &nonterminal);
     TxpLtsTree tree;
     if (atoi(nonterminal.c_str()) == 0) tree.root = 0;
     else tree.root = atoi(terminal.c_str());
     ltslkp_.insert(LtsItem(ltr_, tree));
   } else if (!strcmp(name, "node")) {
     TxpLtsNode node;
     std::string pos;
     std::string yes;
     std::string no;
     SetAttribute("pos", atts, &pos);
     SetAttribute("posval", atts, &(node.posval));
     SetAttribute("yes", atts, &yes);
     SetAttribute("no", atts, &no);
     SetAttribute("val", atts, &(node.val));
     if (!pos.empty()) {
       // non terminal node
       node.yes = atoi(yes.c_str());
       node.no = atoi(no.c_str());
       node.pos = pos2int(pos);
     }
     it = ltslkp_.find(ltr_);
     (it->second).nodes.push_back(node);
   }
 }
Member Data Documentation
ltr_
std::string ltr_ private
holds parser status of current letter
Definition at line 65 of file txplts.h.
Referenced by TxpLts::StartElement().
ltslkp_
LtsMap ltslkp_ private
Lookup from letter to cart tree.
Definition at line 63 of file txplts.h.
Referenced by TxpLts::GetPron(), and TxpLts::StartElement().
The documentation for this class was generated from the following files:
idlaktxp/txplts.h
idlaktxp/txplts.cc