Kaldi: GeneralDropoutComponent Class Reference
GeneralDropoutComponent Class Reference
GeneralDropoutComponent implements dropout, including a continuous variant where the thing we multiply is not just zero or one, but may be a continuous value.
#include <nnet-general-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
GeneralDropoutComponent ()
GeneralDropoutComponent (const GeneralDropoutComponent &other)
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
void SetDropoutProportion (BaseFloat p)
Public Member Functions inherited from RandomComponent
void ResetGenerator ()
void SetTestMode (bool test_mode)
RandomComponent ()
RandomComponent (const RandomComponent &other)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
CuMatrix< BaseFloat > * GetMemo (int32 num_mask_rows) const
const GeneralDropoutComponent & operator= (const GeneralDropoutComponent &other)
Private Attributes
int32 dim_
int32 block_dim_
int32 time_period_
BaseFloat dropout_proportion_
bool continuous_
bool test_mode_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Attributes inherited from RandomComponent
CuRand< BaseFloat > random_generator_
bool test_mode_
Detailed Description
GeneralDropoutComponent implements dropout, including a continuous variant where the thing we multiply is not just zero or one, but may be a continuous value.
It is intended for the case where you want to either share the dropout mask across all of time, or across groups of 't' values (e.g. the first block of 10 values gets one dropout mask, the second block of 10 gets another one, and so on).
Configuration values accepted on the command line, with defaults:
dim Dimension of the input and output of this component, e.g. 512
block-dim Block size if you want the dropout mask to repeat, e.g. if dim=512 and you sent block-dim=128, there will be a mask of dimension 128 repeated 4 times. This can be useful in convolutional setups. If not specified, block-dim defaults to 'dim'; if specified, it must be a divisor of 'dim'.
dropout-proportion=0.5 For conventional dropout, this is the proportion of mask values that (in expectation) are zero; it would normally be between 0 and 0.5. The nonzero mask values will be given values 1.0 / dropout_proportion, so that the expected value is 1.0. This behavior is different from DropoutComponent and DropoutMaskComponent.
For continuous dropout (continuous==true), the dropout scales will have values (1.0 + 2 * dropout-proportion * Uniform[-1,1]). This might seem like a strange choice, but it means that dropout-proportion=0.5 gives us a kind of 'extremal' case where the dropout scales are distributed as Uniform[0, 2] and we can pass in the dropout scale as if it were a conventional dropout scale.
time-period=0 This determines how the dropout mask interacts with the time index (t). In all cases, different sequences (different 'n' values) get different dropout masks. If time-period==0, then the dropout mask is shared across all time values. If you set time-period > 0, then the dropout mask is shared across blocks of time values: for instance if time-period==10, then we'll use one dropout mask for t values 0 through 9, another for 10 through 19, and so on. In all cases, the dropout mask will be shared across all 'x' values, although in most setups the x values are just zero so this isn't very interesting. If you set time-period==1 it would be similar to regular dropout, and it would probably make more sense to just use the normal DropoutComponent.
Definition at line 841 of file nnet-general-component.h.
Constructor & Destructor Documentation
GeneralDropoutComponent() [1/2]
GeneralDropoutComponent ()
Definition at line 1533 of file nnet-general-component.cc.
Referenced by GeneralDropoutComponent::Copy().
                                                 :
     dim_(-1), block_dim_(-1), time_period_(0),
     dropout_proportion_(0.5), continuous_(false) { }
GeneralDropoutComponent() [2/2]
GeneralDropoutComponent (const GeneralDropoutComponent & other)
Definition at line 1537 of file nnet-general-component.cc.
                                          :
     dim_(other.dim_),
     block_dim_(other.block_dim_),
     time_period_(other.time_period_),
     dropout_proportion_(other.dropout_proportion_),
     continuous_(other.continuous_) { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 1578 of file nnet-general-component.cc.
References GeneralDropoutComponent::block_dim_, CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::Data(), GeneralDropoutComponent::dim_, GeneralDropoutComponent::dropout_proportion_, GeneralDropoutComponentPrecomputedIndexes::indexes, KALDI_ASSERT, CuMatrixBase< Real >::MulRows(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), kaldi::SameDim(), CuMatrixBase< Real >::Stride(), and GeneralDropoutComponent::test_mode_.
{
   KALDI_ASSERT(in_deriv != NULL && SameDim(*in_deriv, out_deriv));
   // The following will do no work if in_deriv->Data() == out_deriv.Data().
   in_deriv->CopyFromMat(out_deriv);
   if (test_mode_ || dropout_proportion_ == 0.0) {
     KALDI_ASSERT(memo == NULL);
     return;
   }
   const GeneralDropoutComponentPrecomputedIndexes *indexes =
      dynamic_cast<const GeneralDropoutComponentPrecomputedIndexes*>(indexes_in);
   KALDI_ASSERT(indexes != NULL && memo != NULL);
   CuMatrix<BaseFloat> *mask = reinterpret_cast<CuMatrix<BaseFloat>*>(memo);
   if (block_dim_ < dim_) {
     KALDI_ASSERT(in_deriv->Stride() == in_deriv->NumCols());
     int32 num_rows = in_deriv->NumRows(),
         dim_multiple = dim_  / block_dim_,
         num_rows_reshaped = num_rows * dim_multiple;
     CuSubMatrix<BaseFloat> in_deriv_reshaped(in_deriv->Data(),
                                              num_rows_reshaped,
                                              block_dim_, block_dim_);
     in_deriv_reshaped.MulRows(*mask, indexes->indexes);
   } else {
     in_deriv->MulRows(*mask, indexes->indexes);
   }
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 1658 of file nnet-general-component.cc.
References GeneralDropoutComponent::GeneralDropoutComponent().
{
   return new GeneralDropoutComponent(*this);
 }
DeleteMemo()
virtual void DeleteMemo (void * memo) const inline virtual
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
It's called by NnetComputer in cases where Propagate returns a memo but there will be no backprop to consume it.
Reimplemented from Component.
Definition at line 873 of file nnet-general-component.h.
References DistributeComponent::Copy(), DistributeComponent::PrecomputeIndexes(), DistributeComponent::Read(), and DistributeComponent::Write().
{
     delete static_cast<CuMatrix<BaseFloat>*>(memo);
   }
GetMemo()
CuMatrix< BaseFloat > * GetMemo (int32 num_mask_rows) const private
Definition at line 1682 of file nnet-general-component.cc.
References CuMatrixBase< Real >::Add(), CuMatrixBase< Real >::ApplyHeaviside(), GeneralDropoutComponent::block_dim_, GeneralDropoutComponent::continuous_, GeneralDropoutComponent::dropout_proportion_, KALDI_ASSERT, RandomComponent::random_generator_, kaldi::RandUniform(), CuMatrixBase< Real >::Scale(), and GeneralDropoutComponent::test_mode_.
Referenced by GeneralDropoutComponent::Propagate().
{
   KALDI_ASSERT(num_mask_rows > 0 && !test_mode_ &&
                dropout_proportion_ > 0.0);
   CuMatrix<BaseFloat> *ans = new CuMatrix<BaseFloat>(num_mask_rows, block_dim_);
   BaseFloat dropout_proportion = dropout_proportion_;
   // This const_cast is only safe assuming you don't attempt
   // to use multi-threaded code with the GPU.
   const_cast<CuRand<BaseFloat>&>(random_generator_).RandUniform(ans);
   if (!continuous_) {
     ans->Add(-dropout_proportion);
     // now, a proportion "dropout_proportion" will be < 0.0. After applying the
     // function (x>0?1:0), a proportion "dropout_proportion" will be zero and (1 -
     // dropout_proportion) will be 1.0.
     ans->ApplyHeaviside();
     ans->Scale(1.0 / dropout_proportion);
   } else {
     ans->Scale(dropout_proportion * 4.0);
     // make the expected value 1.0.
     ans->Add(1.0 - (2.0 * dropout_proportion));
   }
   return ans;
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 1520 of file nnet-general-component.cc.
References DropoutMaskComponent::continuous_, DropoutMaskComponent::dropout_proportion_, and DropoutMaskComponent::Type().
{
   std::ostringstream stream;
   stream << Type()
          << ", dim=" << dim_
          << ", block-dim=" << block_dim_
          << ", dropout-proportion=" << dropout_proportion_;
   if (continuous_)
     stream << ", continuous=true";
   if (time_period_ > 0)
     stream << ", time-period=" << time_period_;
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 1662 of file nnet-general-component.cc.
References GeneralDropoutComponent::block_dim_, GeneralDropoutComponent::continuous_, GeneralDropoutComponent::dim_, GeneralDropoutComponent::dropout_proportion_, ConfigLine::GetValue(), KALDI_ASSERT, KALDI_ERR, GeneralDropoutComponent::test_mode_, and GeneralDropoutComponent::time_period_.
{
   dim_ = 0;
   bool ok = cfl->GetValue("dim", &dim_);
   KALDI_ASSERT(ok && dim_ > 0);
   block_dim_ = dim_;
   cfl->GetValue("block-dim", &block_dim_);
   if (!(block_dim_ > 0 && dim_ % block_dim_ == 0))
     KALDI_ERR << "Invalid configuration dim=" << dim_
               << ", block-dim=" << block_dim_;
   time_period_ = 0;
   cfl->GetValue("time-period", &time_period_);
   dropout_proportion_ = 0.5;
   cfl->GetValue("dropout-proportion", &dropout_proportion_);
   continuous_ = false;
   cfl->GetValue("continuous", &continuous_);
   test_mode_ = false;
   cfl->GetValue("test-mode", &test_mode_);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 843 of file nnet-general-component.h.
 { return dim_; }
operator=()
const GeneralDropoutComponent& operator= (const GeneralDropoutComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 845 of file nnet-general-component.h.
References Component::Info(), and DistributeComponent::InitFromConfig().
 { return dim_; }
PrecomputeIndexes()
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo & misc_info, const std::vector< Index > & input_indexes, const std::vector< Index > & output_indexes, bool need_backprop) const virtual
This function must return NULL for simple Components.
Returns a pointer to a class that may contain some precomputed component-specific and computation-specific indexes to be in used in the Propagate and Backprop functions.
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. misc_info may not even ever be used here. We will add members to misc_info as needed.
[in] input_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the in/in_value/in_deriv matrices given to Propagate and Backprop will mean.
[in] output_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the out/out_value/out_deriv matrices given to Propagate and Backprop will mean.
[in] need_backprop True if we might need to do backprop with this component, so that if any different indexes are needed for backprop then those should be computed too.
Returns
Returns a child-class of class ComponentPrecomputedIndexes, or NULL if this component for does not need to precompute any indexes (e.g. if it is a simple component and does not care about indexes).
Reimplemented from Component.
Definition at line 1708 of file nnet-general-component.cc.
References GeneralDropoutComponent::block_dim_, CuArray< T >::CopyFromVec(), GeneralDropoutComponent::dim_, kaldi::DivideRoundingDown(), rnnlm::i, GeneralDropoutComponentPrecomputedIndexes::indexes, rnnlm::j, KALDI_ASSERT, rnnlm::n, GeneralDropoutComponentPrecomputedIndexes::num_mask_rows, and GeneralDropoutComponent::time_period_.
{
   KALDI_ASSERT(input_indexes == output_indexes);
   GeneralDropoutComponentPrecomputedIndexes *ans = new
       GeneralDropoutComponentPrecomputedIndexes;
   int32 size = input_indexes.size(), time_period = time_period_,
       cur_row = 0;
   std::vector<int32> indexes(size);
   // the map 'm' will map from a pair from (n, t) value to the row-index of the
   // dropout-mask matrix*.   However, the 't' isn't a real 't' value;
   // if time_period_ == 0, the 't' value will just be zero; otherwise,
   // it will be t divided by time_period_ (rounding towards negative infinity).
   // *before considering effects related to when block_dim_ != dim_.
   std::unordered_map<std::pair<int32,int32>, int32, PairHasher<int32> > m;
   for (int32 i = 0; i < size; i++) {
     int32 n = input_indexes[i].n,
         t = (time_period == 0 ? 0 : DivideRoundingDown(input_indexes[i].t,
                                                        time_period));
     std::pair<int32, int32> p(n, t);
     std::unordered_map<std::pair<int32,int32>, int32,
                        PairHasher<int32> >::const_iterator
         iter = m.find(p);
     if (iter != m.end()) {
       indexes[i] = iter->second;
     } else {
       m[p] = cur_row;
       indexes[i] = cur_row;
       cur_row++;
     }
   }
   int32 multiple = dim_ / block_dim_;
   ans->num_mask_rows = cur_row;
   if (multiple == 1) {
     ans->indexes.CopyFromVec(indexes);
   } else {
     ans->num_mask_rows = cur_row * multiple;
     std::vector<int32> repeated_indexes;
     repeated_indexes.reserve(size * multiple);
     for (int32 i = 0; i < size; i++) {
       int32 row = indexes[i];
       for (int32 j = 0; j < multiple; j++)
         repeated_indexes.push_back(row);
     }
     ans->indexes.CopyFromVec(repeated_indexes);
   }
   return ans;
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 1545 of file nnet-general-component.cc.
References GeneralDropoutComponent::block_dim_, CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::Data(), GeneralDropoutComponent::dim_, GeneralDropoutComponent::dropout_proportion_, GeneralDropoutComponent::GetMemo(), GeneralDropoutComponentPrecomputedIndexes::indexes, KALDI_ASSERT, CuMatrixBase< Real >::MulRows(), GeneralDropoutComponentPrecomputedIndexes::num_mask_rows, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), kaldi::SameDim(), CuMatrixBase< Real >::Stride(), and GeneralDropoutComponent::test_mode_.
{
   KALDI_ASSERT(SameDim(in, *out));
   // The following will do nothing if 'out' and 'in' refer to the same data.
   out->CopyFromMat(in);
   if (test_mode_ || dropout_proportion_ == 0.0)
     return NULL;
   const GeneralDropoutComponentPrecomputedIndexes *indexes =
     dynamic_cast<const GeneralDropoutComponentPrecomputedIndexes*>(indexes_in);
   KALDI_ASSERT(indexes != NULL);
   CuMatrix<BaseFloat> *mask = GetMemo(indexes->num_mask_rows);
   if (block_dim_ < dim_) {
     KALDI_ASSERT(out->Stride() == out->NumCols());
     int32 num_rows = out->NumRows(),
         dim_multiple = dim_  / block_dim_,
         num_rows_reshaped = num_rows * dim_multiple;
     CuSubMatrix<BaseFloat> out_reshaped(out->Data(), num_rows_reshaped,
                                         block_dim_, block_dim_);
     out_reshaped.MulRows(*mask, indexes->indexes);
   } else {
     out->MulRows(*mask, indexes->indexes);
   }
   return mask;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 856 of file nnet-general-component.h.
References DistributeComponent::Backprop(), kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kInputContiguous, kaldi::nnet3::kOutputContiguous, kaldi::nnet3::kPropagateInPlace, kaldi::nnet3::kRandomComponent, kaldi::nnet3::kUsesMemo, and DistributeComponent::Propagate().
{
     return kRandomComponent|kPropagateInPlace|kBackpropInPlace|kUsesMemo|
         (block_dim_ != dim_ ? (kInputContiguous|kOutputContiguous) : 0);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 1616 of file nnet-general-component.cc.
References GeneralDropoutComponent::block_dim_, GeneralDropoutComponent::continuous_, GeneralDropoutComponent::dim_, GeneralDropoutComponent::dropout_proportion_, kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), kaldi::PeekToken(), kaldi::ReadBasicType(), GeneralDropoutComponent::test_mode_, and GeneralDropoutComponent::time_period_.
{
   ExpectOneOrTwoTokens(is, binary, "<GeneralDropoutComponent>", "<Dim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<BlockDim>");
   ReadBasicType(is, binary, &block_dim_);
   ExpectToken(is, binary, "<TimePeriod>");
   ReadBasicType(is, binary, &time_period_);
   ExpectToken(is, binary, "<DropoutProportion>");
   ReadBasicType(is, binary, &dropout_proportion_);
   if (PeekToken(is, binary) == 'T') {
     ExpectToken(is, binary, "<TestMode>");
     test_mode_ = true;
   } else {
     test_mode_ = false;
   }
   if (PeekToken(is, binary) == 'C') {
     ExpectToken(is, binary, "<Continuous>");
     continuous_ = true;
   } else {
     continuous_ = false;
   }
   ExpectToken(is, binary, "</GeneralDropoutComponent>");
 }
SetDropoutProportion()
void SetDropoutProportion (BaseFloat p) inline
Definition at line 888 of file nnet-general-component.h.
Referenced by kaldi::nnet3::ReadEditConfig(), and kaldi::nnet3::SetDropoutProportion().
 { dropout_proportion_ = p; }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 855 of file nnet-general-component.h.
 { return "GeneralDropoutComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 1641 of file nnet-general-component.cc.
References GeneralDropoutComponent::block_dim_, GeneralDropoutComponent::continuous_, GeneralDropoutComponent::dim_, GeneralDropoutComponent::dropout_proportion_, GeneralDropoutComponent::test_mode_, GeneralDropoutComponent::time_period_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<GeneralDropoutComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<BlockDim>");
   WriteBasicType(os, binary, block_dim_);
   WriteToken(os, binary, "<TimePeriod>");
   WriteBasicType(os, binary, time_period_);
   WriteToken(os, binary, "<DropoutProportion>");
   WriteBasicType(os, binary, dropout_proportion_);
   if (test_mode_)
     WriteToken(os, binary, "<TestMode>");
   if (continuous_)
     WriteToken(os, binary, "<Continuous>");
   WriteToken(os, binary, "</GeneralDropoutComponent>");
 }
Member Data Documentation
block_dim_
int32 block_dim_ private
Definition at line 901 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::Backprop(), GeneralDropoutComponent::GetMemo(), GeneralDropoutComponent::InitFromConfig(), GeneralDropoutComponent::PrecomputeIndexes(), GeneralDropoutComponent::Propagate(), GeneralDropoutComponent::Read(), and GeneralDropoutComponent::Write().
continuous_
bool continuous_ private
Definition at line 911 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::GetMemo(), GeneralDropoutComponent::InitFromConfig(), GeneralDropoutComponent::Read(), and GeneralDropoutComponent::Write().
dim_
int32 dim_ private
Definition at line 898 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::Backprop(), GeneralDropoutComponent::InitFromConfig(), GeneralDropoutComponent::PrecomputeIndexes(), GeneralDropoutComponent::Propagate(), GeneralDropoutComponent::Read(), and GeneralDropoutComponent::Write().
dropout_proportion_
BaseFloat dropout_proportion_ private
Definition at line 909 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::Backprop(), GeneralDropoutComponent::GetMemo(), GeneralDropoutComponent::InitFromConfig(), GeneralDropoutComponent::Propagate(), GeneralDropoutComponent::Read(), and GeneralDropoutComponent::Write().
test_mode_
bool test_mode_ private
Definition at line 913 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::Backprop(), GeneralDropoutComponent::GetMemo(), GeneralDropoutComponent::InitFromConfig(), GeneralDropoutComponent::Propagate(), GeneralDropoutComponent::Read(), and GeneralDropoutComponent::Write().
time_period_
int32 time_period_ private
Definition at line 907 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::InitFromConfig(), GeneralDropoutComponent::PrecomputeIndexes(), GeneralDropoutComponent::Read(), and GeneralDropoutComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc