Kaldi: ArcIterator< GrammarFst > Class Template Reference
ArcIterator< GrammarFst > Class Template Reference
This is the overridden template for class ArcIterator for GrammarFst.
#include <grammar-fst.h>
Public Types
using Arc = typename GrammarFst::Arc
using BaseArc = StdArc
using StateId = typename Arc::StateId
using BaseStateId = typename StdArc::StateId
using ExpandedState = GrammarFst::ExpandedState
Public Member Functions
ArcIterator (const GrammarFst &fst_in, StateId s)
bool Done ()
void Next ()
const Arc & Value () const
Private Member Functions
void CopyArcToTemp ()
Private Attributes
ArcIteratorData< StdArc > data_
int32 dest_instance_
size_t i_
Arc arc_
Detailed Description
template<>
class fst::ArcIterator< GrammarFst >
This is the overridden template for class ArcIterator for GrammarFst.
This is only used in the decoder, and the GrammarFst is not a "real" FST (it just has a very similar-looking interface), so we don't need to implement all the functionality that the regular ArcIterator has.
Definition at line 488 of file grammar-fst.h.
Member Typedef Documentation
Arc
using Arc = typename GrammarFst::Arc
Definition at line 490 of file grammar-fst.h.
BaseArc
using BaseArc = StdArc
Definition at line 491 of file grammar-fst.h.
BaseStateId
using BaseStateId = typename StdArc::StateId
Definition at line 493 of file grammar-fst.h.
ExpandedState
using ExpandedState = GrammarFst::ExpandedState
Definition at line 494 of file grammar-fst.h.
StateId
using StateId = typename Arc::StateId
Definition at line 492 of file grammar-fst.h.
Constructor & Destructor Documentation
ArcIterator()
ArcIterator (const GrammarFst & fst_in, StateId s) inline
Definition at line 498 of file grammar-fst.h.
References GrammarFst::ExpandedState::arcs, data_, GrammarFst::ExpandedState::dest_fst_instance, GrammarFst::FstInstance::fst, GrammarFst::GetExpandedState(), GrammarFst::instances_, and KALDI_GRAMMAR_FST_SPECIAL_WEIGHT.
{
     GrammarFst &fst = const_cast<GrammarFst&>(fst_in);
     // 'instance_id' is the high order bits of the state.
     int32 instance_id = s >> 32;
     // 'base_state' is low order bits of the state.  It's important to
     // explicitly say int32 below, not BaseStateId == int, which might on some
     // compilers be a 64-bit type.
     BaseStateId base_state = static_cast<int32>(s);
     const GrammarFst::FstInstance &instance = fst.instances_[instance_id];
     const ConstFst<StdArc> *base_fst = instance.fst;
     if (base_fst->Final(base_state).Value() != KALDI_GRAMMAR_FST_SPECIAL_WEIGHT) {
       // A normal state
       dest_instance_ = instance_id;
       base_fst->InitArcIterator(s, &data_);
       i_ = 0;
     } else {
       // A special state
       ExpandedState *expanded_state = fst.GetExpandedState(instance_id,
                                                            base_state);
       dest_instance_ = expanded_state->dest_fst_instance;
       // it's ok to leave the other members of data_ uninitialized, as they will
       // never be interrogated.
       data_.arcs = &(expanded_state->arcs[0]);
       data_.narcs = expanded_state->arcs.size();
       i_ = 0;
     }
     // Ideally we want to call CopyArcToTemp() now, but we rely on the fact that
     // the calling code needs to call Done() before accessing Value(); we call
     // CopyArcToTemp() from Done().  Of course this is slightly against the
     // semantics of Done(), but it's more efficient to have Done() call
     // CopyArcToTemp() than this function or Next(), as Done() already has to
     // test that the arc-iterator has not reached the end.
   }
Member Function Documentation
CopyArcToTemp()
void CopyArcToTemp () inline private
Definition at line 556 of file grammar-fst.h.
References data_.
{
     const StdArc &src = data_.arcs[i_];
     arc_.ilabel = src.ilabel;
     arc_.olabel = src.olabel;
     arc_.weight = src.weight;
     arc_.nextstate = (static_cast<int64>(dest_instance_) << 32) |
         src.nextstate;
   }
Done()
bool Done () inline
Definition at line 532 of file grammar-fst.h.
References data_.
Referenced by fst::CopyToVectorFst().
                      {
     if (i_ < data_.narcs) {
       CopyArcToTemp();
       return false;
     } else {
       return true;
     }
   }
Next()
void Next () inline
Definition at line 541 of file grammar-fst.h.
Referenced by fst::CopyToVectorFst().
                      {
     i_++;
     // Note: logically, at this point we should do:
     // if (i_ < data_.size)
     //  CopyArcToTemp();
     // Instead we move this CopyArcToTemp() invocation into Done(), which we
     // know will always be called after Next() and before Value(), because the
     // user has no other way of knowing whether the iterator is still valid.
     // This is for efficiency.
   }
Value()
const Arc& Value () const inline
Definition at line 552 of file grammar-fst.h.
Referenced by fst::CopyToVectorFst().
 { return arc_; }
Member Data Documentation
arc_
Arc arc_ private
Definition at line 575 of file grammar-fst.h.
data_
ArcIteratorData<StdArc> data_ private
Definition at line 568 of file grammar-fst.h.
dest_instance_
int32 dest_instance_ private
Definition at line 571 of file grammar-fst.h.
i_
size_t i_ private
Definition at line 573 of file grammar-fst.h.
The documentation for this class was generated from the following file:
decoder/grammar-fst.h