Kaldi: OptionsItf Class Reference
OptionsItf Class Reference abstract
#include <options-itf.h>
Public Member Functions
virtual void Register (const std::string &name, bool *ptr, const std::string &doc)=0
virtual void Register (const std::string &name, int32 *ptr, const std::string &doc)=0
virtual void Register (const std::string &name, uint32 *ptr, const std::string &doc)=0
virtual void Register (const std::string &name, float *ptr, const std::string &doc)=0
virtual void Register (const std::string &name, double *ptr, const std::string &doc)=0
virtual void Register (const std::string &name, std::string *ptr, const std::string &doc)=0
virtual ~OptionsItf ()
Detailed Description
Definition at line 26 of file options-itf.h.
Constructor & Destructor Documentation
~OptionsItf()
virtual ~OptionsItf () inline virtual
Definition at line 42 of file options-itf.h.
 {}
Member Function Documentation
Register() [1/6]
virtual void Register (const std::string & name, bool * ptr, const std::string & doc) pure virtual
Implemented in ParseOptions, and SimpleOptions.
Referenced by PitchInterpolatorOptions::Register(), LogisticRegressionConfig::Register(), NnetLimitRankOpts::Register(), NnetStatsConfig::Register(), NnetSimpleTrainerConfig::Register(), LdaEstimateOptions::Register(), EbwOptions::Register(), KaldiRnnlmWrapperOpts::Register(), NnetMixupConfig::Register(), AlignConfig::Register(), NnetEnsembleTrainerConfig::Register(), NnetChainTrainingOptions::Register(), PhoneAlignLatticeOptions::Register(), NnetShrinkConfig::Register(), NnetWidenConfig::Register(), NnetComputeOptions::Register(), NnetDiscriminativeOptions::Register(), MatrixBufferOptions::Register(), RegtreeMllrOptions::Register(), FasterDecoderOptions::Register(), LossOptions::Register(), TrainingGraphCompilerOptions::Register(), PdfPriorOptions::Register(), NnetTrainOptions::Register(), DecodableNnet2OnlineOptions::Register(), SplitDiscriminativeSupervisionOptions::Register(), HTransducerConfig::Register(), SpectrogramOptions::Register(), AccumulateTreeStatsOptions::Register(), FeatureTransformEstimateOptions::Register(), FmllrOptions::Register(), RegtreeFmllrOptions::Register(), ArpaParseOptions::Register(), NnetDataRandomizerOptions::Register(), NnetCombineConfig::Register(), NnetDiscriminativeUpdateOptions::Register(), VadEnergyOptions::Register(), NnetCombineAconfig::Register(), BasisFmllrOptions::Register(), NnetFixConfig::Register(), EbwWeightOptions::Register(), DeltaFeaturesOptions::Register(), PldaConfig::Register(), LatticeSimpleDecoderConfig::Register(), MleFullGmmOptions::Register(), NnetRescaleConfig::Register(), IvectorEstimationOptions::Register(), MleDiagGmmOptions::Register(), AperiodicEnergyOptions::Register(), MelBanksOptions::Register(), NnetTrainerOptions::Register(), MfccOptions::Register(), WordBoundaryInfoOpts::Register(), FbankOptions::Register(), FrameExtractionOptions::Register(), LatticeFasterDecoderConfig::Register(), MinimumBayesRiskOptions::Register(), FrequencyBanksOptions::Register(), Sgmm2FmllrConfig::Register(), NnetSimpleLoopedComputationOptions::Register(), NnetSimpleComputationOptions::Register(), CuAllocatorOptions::Register(), PlpOptions::Register(), NnetCombineFastConfig::Register(), FmllrRawOptions::Register(), FmpeOptions::Register(), NnetComputeProbOptions::Register(), MleAmSgmm2Options::Register(), NnetOptimizeOptions::Register(), RbmTrainOptions::Register(), ShiftedDeltaFeaturesOptions::Register(), SplitDiscriminativeExampleConfig::Register(), MapDiagGmmOptions::Register(), DiscriminativeOptions::Register(), FmpeUpdateOptions::Register(), MleTransitionUpdateConfig::Register(), Sgmm2SplitSubstatesConfig::Register(), EbwAmSgmm2Options::Register(), WordBoundaryInfoNewOpts::Register(), ExampleGenerationConfig::Register(), MapTransitionUpdateConfig::Register(), IvectorExtractorOptions::Register(), DeterminizeLatticePrunedOptions::Register(), ComposeLatticePrunedOptions::Register(), Sgmm2GselectConfig::Register(), WordAlignLatticeLexiconOpts::Register(), PitchExtractionOptions::Register(), TaskSequencerConfig::Register(), DeterminizeLatticePhonePrunedOptions::Register(), SlidingWindowCmnOptions::Register(), UbmClusteringOptions::Register(), CachingOptimizingCompilerOptions::Register(), PldaEstimationConfig::Register(), PldaUnsupervisedAdaptorConfig::Register(), ExampleMergingConfig::Register(), IvectorExtractorStatsOptions::Register(), IvectorExtractorEstimationOptions::Register(), and ParseOptions::RegisterTmpl().
Register() [2/6]
virtual void Register (const std::string & name, int32 * ptr, const std::string & doc) pure virtual
Implemented in ParseOptions, and SimpleOptions.
Register() [3/6]
virtual void Register (const std::string & name, uint32 * ptr, const std::string & doc) pure virtual
Implemented in ParseOptions, and SimpleOptions.
Register() [4/6]
virtual void Register (const std::string & name, float * ptr, const std::string & doc) pure virtual
Implemented in ParseOptions, and SimpleOptions.
Register() [5/6]
virtual void Register (const std::string & name, double * ptr, const std::string & doc) pure virtual
Implemented in ParseOptions, and SimpleOptions.
Register() [6/6]
virtual void Register (const std::string & name, std::string * ptr, const std::string & doc) pure virtual
Implemented in ParseOptions, and SimpleOptions.
The documentation for this class was generated from the following file:
itf/options-itf.h