Kaldi: GeneralDropoutComponentPrecomputedIndexes Class Reference
GeneralDropoutComponentPrecomputedIndexes Class Reference
#include <nnet-general-component.h>
Public Member Functions
virtual ~GeneralDropoutComponentPrecomputedIndexes ()
ComponentPrecomputedIndexes * Copy () const
virtual void Write (std::ostream &os, bool binary) const
virtual void Read (std::istream &is, bool binary)
virtual std::string Type () const
Public Member Functions inherited from ComponentPrecomputedIndexes
virtual ~ComponentPrecomputedIndexes ()
Public Attributes
int32 num_mask_rows
CuArray< int32 > indexes
Additional Inherited Members
Static Public Member Functions inherited from ComponentPrecomputedIndexes
static ComponentPrecomputedIndexes * ReadNew (std::istream &is, bool binary)
static ComponentPrecomputedIndexes * NewComponentPrecomputedIndexesOfType (const std::string &cpi_type)
Detailed Description
Definition at line 922 of file nnet-general-component.h.
Constructor & Destructor Documentation
~GeneralDropoutComponentPrecomputedIndexes()
virtual ~GeneralDropoutComponentPrecomputedIndexes () inline virtual
Definition at line 939 of file nnet-general-component.h.
 { }
Member Function Documentation
Copy()
ComponentPrecomputedIndexes* Copy () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 941 of file nnet-general-component.h.
References DistributeComponent::Read(), and DistributeComponent::Write().
{
     return new GeneralDropoutComponentPrecomputedIndexes(*this);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Implements ComponentPrecomputedIndexes.
Definition at line 1775 of file nnet-general-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), and kaldi::ReadBasicType().
                  {
   ExpectOneOrTwoTokens(is, binary,
                        "<GeneralDropoutComponentPrecomputedIndexes>",
                        "<NumMaskRows>");
   ReadBasicType(is, binary, &num_mask_rows);
   ExpectToken(is, binary, "<Indexes>");
   indexes.Read(is, binary);
   ExpectToken(is, binary,
               "</GeneralDropoutComponentPrecomputedIndexes>");
 }
Type()
virtual std::string Type () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 949 of file nnet-general-component.h.
{
     return "GeneralDropoutComponentPrecomputedIndexes";
   }
Write()
void Write (std::ostream & os, bool binary) const virtual
Implements ComponentPrecomputedIndexes.
Definition at line 1763 of file nnet-general-component.cc.
References kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary,
              "<GeneralDropoutComponentPrecomputedIndexes>");
   WriteToken(os, binary, "<NumMaskRows>");
   WriteBasicType(os, binary, num_mask_rows);
   WriteToken(os, binary, "<Indexes>");
   indexes.Write(os, binary);
   WriteToken(os, binary,
              "</GeneralDropoutComponentPrecomputedIndexes>");
 }
Member Data Documentation
indexes
CuArray<int32> indexes
Definition at line 937 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::Backprop(), GeneralDropoutComponent::PrecomputeIndexes(), and GeneralDropoutComponent::Propagate().
num_mask_rows
int32 num_mask_rows
Definition at line 929 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::PrecomputeIndexes(), and GeneralDropoutComponent::Propagate().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc