Kaldi: SumGroupComponent Class Reference
SumGroupComponent Class Reference
SumGroupComponent is used to sum up groups of posteriors.
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
void Init (const std::vector< int32 > &sizes)
void Init (int32 input_dim, int32 output_dim)
void GetSizes (std::vector< int32 > *sizes) const
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
SumGroupComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (SumGroupComponent)
Private Attributes
CuArray< Int32Pair > indexes_
CuArray< int32 > reverse_indexes_
int32 input_dim_
int32 output_dim_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
SumGroupComponent is used to sum up groups of posteriors.
It's used to introduce a kind of Gaussian-mixture-model-like idea into neural nets. This is basically a degenerate case of MixtureProbComponent; we had to implement it separately to be efficient for CUDA (we can use this one regardless whether we have CUDA or not; it's the normal case we want anyway).
There are two forms of initialization in a config file: one where the number of elements are specified for each group individually as a vector, and one where only the total input dimension and the output dimension (number of groups) is specified. The second is used when all groups have the same size.
Definition at line 1053 of file nnet-simple-component.h.
Constructor & Destructor Documentation
SumGroupComponent()
SumGroupComponent () inline
Definition at line 1064 of file nnet-simple-component.h.
 { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 3534 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyCols().
{
   in_deriv->CopyCols(out_deriv, reverse_indexes_);
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 3482 of file nnet-simple-component.cc.
References SumGroupComponent::indexes_, SumGroupComponent::input_dim_, SumGroupComponent::output_dim_, and SumGroupComponent::reverse_indexes_.
{
   SumGroupComponent *ans = new SumGroupComponent();
   ans->indexes_ = indexes_;
   ans->reverse_indexes_ = reverse_indexes_;
   ans->input_dim_ = input_dim_;
   ans->output_dim_ = output_dim_;
   return ans;
 }
GetSizes()
void GetSizes (std::vector< int32 > * sizes) const
Definition at line 3505 of file nnet-simple-component.cc.
References rnnlm::i, and KALDI_ASSERT.
{
   std::vector<Int32Pair> indexes;
   indexes_.CopyToVec(&indexes);
   sizes->resize(indexes.size());
   for (size_t i = 0; i < indexes.size(); i++) {
     (*sizes)[i] = indexes[i].second - indexes[i].first;
     if (i == 0) { KALDI_ASSERT(indexes[i].first == 0); }
     else { KALDI_ASSERT(indexes[i].first == indexes[i-1].second); }
     KALDI_ASSERT(indexes[i].second > indexes[i].first);
     (*sizes)[i] = indexes[i].second - indexes[i].first;
   }
 }
Init() [1/2]
void Init (const std::vector< int32 > & sizes)
Definition at line 3423 of file nnet-simple-component.cc.
References rnnlm::i, rnnlm::j, and KALDI_ASSERT.
{
   KALDI_ASSERT(!sizes.empty());
   std::vector<Int32Pair> cpu_vec(sizes.size());
   std::vector<int32> reverse_cpu_vec;
   int32 cur_index = 0;
   for (size_t i = 0; i < sizes.size(); i++) {
     KALDI_ASSERT(sizes[i] > 0);
     cpu_vec[i].first = cur_index;
     cpu_vec[i].second = cur_index + sizes[i];
     cur_index += sizes[i];
     for (int32 j = cpu_vec[i].first; j < cpu_vec[i].second; j++)
       reverse_cpu_vec.push_back(i);
   }
   this->indexes_ = cpu_vec;
   this->reverse_indexes_ = reverse_cpu_vec;
   this->input_dim_ = cur_index;
   this->output_dim_ = sizes.size();
 }
Init() [2/2]
void Init (int32 input_dim, int32 output_dim)
Definition at line 3442 of file nnet-simple-component.cc.
References rnnlm::i, rnnlm::j, and KALDI_ASSERT.
{
   const int32 num_groups = output_dim;
   KALDI_ASSERT(input_dim % num_groups == 0);
   const int32 group_size = input_dim / num_groups;
   std::vector<Int32Pair> cpu_vec(num_groups);
   std::vector<int32> reverse_cpu_vec;
   int32 cur_index = 0;
   for (size_t i = 0; i < num_groups; i++) {
     cpu_vec[i].first = cur_index;
     cpu_vec[i].second = cur_index + group_size;
     cur_index += group_size;
     for (int32 j = cpu_vec[i].first; j < cpu_vec[i].second; j++)
       reverse_cpu_vec.push_back(i);
   }
   this->indexes_ = cpu_vec;
   this->reverse_indexes_ = reverse_cpu_vec;
   this->input_dim_ = input_dim;
   this->output_dim_ = num_groups;
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 3463 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), FixedAffineComponent::Init(), KALDI_ERR, FixedAffineComponent::Type(), and ConfigLine::WholeLine().
{
   std::vector<int32> sizes;
   bool has_sizes = cfl->GetValue("sizes", &sizes);
   if (has_sizes) {
     if (cfl->HasUnusedValues() || sizes.empty())
       KALDI_ERR << "Invalid initializer for layer of type "
                 << Type() << ": \"" << cfl->WholeLine() << "\"";
     this->Init(sizes);
   } else { // each group has the same size
     int32 input_dim = -1, output_dim = -1;
     if (!cfl->GetValue("input-dim", &input_dim) ||
         !cfl->GetValue("output-dim", &output_dim) || cfl->HasUnusedValues()) {
       KALDI_ERR << "Invalid initializer for layer of type "
                 << Type() << ": \"" << cfl->WholeLine() << "\"";
     }
     Init(input_dim, output_dim);
   }
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1055 of file nnet-simple-component.h.
References PnormComponent::input_dim_.
 { return input_dim_; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (SumGroupComponent) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1056 of file nnet-simple-component.h.
References PnormComponent::Init(), PnormComponent::InitFromConfig(), and PnormComponent::output_dim_.
 { return output_dim_; }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 3527 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::SumColumnRanges().
{
   out->SumColumnRanges(in, indexes_);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1066 of file nnet-simple-component.h.
References PnormComponent::Backprop(), PnormComponent::Copy(), Component::KALDI_DISALLOW_COPY_AND_ASSIGN(), kaldi::nnet3::kSimpleComponent, PnormComponent::Propagate(), PnormComponent::Read(), and PnormComponent::Write().
 { return kSimpleComponent; }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 3491 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), FixedAffineComponent::Init(), KALDI_ERR, kaldi::ReadIntegerVector(), and kaldi::ReadToken().
{
   ExpectOneOrTwoTokens(is, binary, "<SumGroupComponent>", "<Sizes>");
   std::vector<int32> sizes;
   ReadIntegerVector(is, binary, &sizes);
   std::string token;
   ReadToken(is, binary, &token);
   if (!(token == "<SumGroupComponent>" ||
         token == "</SumGroupComponent>")) {
     KALDI_ERR << "Expected </SumGroupComponent>, got " << token;
   }
   this->Init(sizes);
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 1065 of file nnet-simple-component.h.
 { return "SumGroupComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3518 of file nnet-simple-component.cc.
References kaldi::WriteIntegerVector(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<SumGroupComponent>");
   WriteToken(os, binary, "<Sizes>");
   std::vector<int32> sizes;
   this->GetSizes(&sizes);
   WriteIntegerVector(os, binary, sizes);
   WriteToken(os, binary, "</SumGroupComponent>");
 }
Member Data Documentation
indexes_
CuArray<Int32Pair> indexes_ private
Definition at line 1086 of file nnet-simple-component.h.
Referenced by SumGroupComponent::Copy().
input_dim_
int32 input_dim_ private
Definition at line 1089 of file nnet-simple-component.h.
Referenced by SumGroupComponent::Copy().
output_dim_
int32 output_dim_ private
Definition at line 1090 of file nnet-simple-component.h.
Referenced by SumGroupComponent::Copy().
reverse_indexes_
CuArray<int32> reverse_indexes_ private
Definition at line 1088 of file nnet-simple-component.h.
Referenced by SumGroupComponent::Copy().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc