Kaldi: PnormComponent Class Reference
PnormComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
void Init (int32 input_dim, int32 output_dim)
PnormComponent (int32 input_dim, int32 output_dim)
virtual int32 Properties () const
Return bitmask of the component's properties.
PnormComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Attributes
int32 input_dim_
int32 output_dim_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 48 of file nnet-simple-component.h.
Constructor & Destructor Documentation
PnormComponent() [1/2]
PnormComponent (int32 input_dim, int32 output_dim) inline explicit
Definition at line 51 of file nnet-simple-component.h.
References PnormComponent::Init().
{
     Init(input_dim, output_dim);
   }
PnormComponent() [2/2]
PnormComponent () inline
Definition at line 57 of file nnet-simple-component.h.
Referenced by PnormComponent::Copy().
 : input_dim_(0), output_dim_(0) { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 62 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::DiffGroupPnorm().
Referenced by SigmoidComponent::Copy(), NoOpComponent::Copy(), SumBlockComponent::Copy(), ClipGradientComponent::Copy(), PnormComponent::OutputDim(), DropoutComponent::OutputDim(), ElementwiseProductComponent::OutputDim(), FixedAffineComponent::OutputDim(), FixedScaleComponent::OutputDim(), FixedBiasComponent::OutputDim(), TanhComponent::Properties(), RectifiedLinearComponent::Properties(), AffineComponent::Properties(), BlockAffineComponent::Properties(), RepeatedAffineComponent::Properties(), SoftmaxComponent::Properties(), LogSoftmaxComponent::Properties(), LinearComponent::Properties(), SumGroupComponent::Properties(), PerElementScaleComponent::Properties(), PerElementOffsetComponent::Properties(), ConstantFunctionComponent::Properties(), ScaleAndOffsetComponent::Properties(), ConvolutionComponent::Properties(), LstmNonlinearityComponent::Properties(), MaxpoolingComponent::Properties(), CompositeComponent::Type(), and PermuteComponent::ZeroStats().
{
   if (!in_deriv)
     return;
   BaseFloat p = 2.0;
   in_deriv->DiffGroupPnorm(in_value, out_value, out_deriv, p);
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 73 of file nnet-simple-component.h.
References PnormComponent::input_dim_, PnormComponent::output_dim_, PnormComponent::PnormComponent(), PnormComponent::Read(), and PnormComponent::Write().
Referenced by LinearComponent::LinearComponent(), NaturalGradientAffineComponent::NaturalGradientAffineComponent(), DropoutComponent::OutputDim(), FixedAffineComponent::OutputDim(), FixedScaleComponent::OutputDim(), FixedBiasComponent::OutputDim(), AffineComponent::Properties(), BlockAffineComponent::Properties(), RepeatedAffineComponent::Properties(), SumGroupComponent::Properties(), PerElementScaleComponent::Properties(), PerElementOffsetComponent::Properties(), ConstantFunctionComponent::Properties(), ConvolutionComponent::Properties(), LstmNonlinearityComponent::Properties(), NaturalGradientRepeatedAffineComponent::Type(), NaturalGradientPerElementScaleComponent::Type(), and PermuteComponent::ZeroStats().
                                   { return new PnormComponent(input_dim_,
                                                               output_dim_); }
Init()
void Init (int32 input_dim, int32 output_dim)
Definition at line 35 of file nnet-simple-component.cc.
References PnormComponent::input_dim_, KALDI_ASSERT, and PnormComponent::output_dim_.
Referenced by ClipGradientComponent::ClipGradientComponent(), CompositeComponent::CompositeComponent(), DropoutComponent::DropoutComponent(), ElementwiseProductComponent::ElementwiseProductComponent(), PnormComponent::InitFromConfig(), AffineComponent::LinearParams(), RepeatedAffineComponent::LinearParams(), ConvolutionComponent::LinearParams(), SumGroupComponent::OutputDim(), ClipGradientComponent::OutputDim(), PermuteComponent::OutputDim(), PermuteComponent::PermuteComponent(), PnormComponent::PnormComponent(), FixedScaleComponent::Properties(), FixedBiasComponent::Properties(), PerElementScaleComponent::Properties(), LstmNonlinearityComponent::Properties(), FixedAffineComponent::Type(), and NaturalGradientPerElementScaleComponent::Type().
{
   input_dim_ = input_dim;
   output_dim_ = output_dim;
   KALDI_ASSERT(input_dim_ > 0 && output_dim_ > 0 &&
                input_dim_ % output_dim_ == 0);
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 42 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), PnormComponent::Init(), KALDI_ERR, PnormComponent::Type(), and ConfigLine::WholeLine().
Referenced by NoOpComponent::Copy(), LinearComponent::LinearComponent(), MaxpoolingComponent::MaxpoolingComponent(), NaturalGradientAffineComponent::NaturalGradientAffineComponent(), AffineComponent::OrthonormalConstraint(), BlockAffineComponent::OutputDim(), RepeatedAffineComponent::OutputDim(), SumGroupComponent::OutputDim(), ClipGradientComponent::OutputDim(), PermuteComponent::OutputDim(), PerElementScaleComponent::OutputDim(), PerElementOffsetComponent::OutputDim(), ConstantFunctionComponent::OutputDim(), ScaleAndOffsetComponent::OutputDim(), FixedScaleComponent::Properties(), FixedBiasComponent::Properties(), SumBlockComponent::Properties(), PnormComponent::Type(), DropoutComponent::Type(), ElementwiseProductComponent::Type(), and FixedAffineComponent::Type().
{
   int32 input_dim = 0;
   int32 output_dim = 0;
   bool ok = cfl->GetValue("output-dim", &output_dim) &&
       cfl->GetValue("input-dim", &input_dim);
   if (!ok || cfl->HasUnusedValues() || output_dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(input_dim, output_dim);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 60 of file nnet-simple-component.h.
References PnormComponent::input_dim_.
Referenced by MaxpoolingComponent::MaxpoolingComponent(), and ConstantFunctionComponent::Properties().
 { return input_dim_; }
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 61 of file nnet-simple-component.h.
References PnormComponent::Backprop(), PnormComponent::output_dim_, and PnormComponent::Propagate().
Referenced by MaxpoolingComponent::MaxpoolingComponent(), and ConstantFunctionComponent::Properties().
 { return output_dim_; }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 54 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::GroupPnorm().
Referenced by SigmoidComponent::Copy(), NoOpComponent::Copy(), SumBlockComponent::Copy(), ClipGradientComponent::Copy(), PnormComponent::OutputDim(), DropoutComponent::OutputDim(), ElementwiseProductComponent::OutputDim(), FixedAffineComponent::OutputDim(), FixedScaleComponent::OutputDim(), FixedBiasComponent::OutputDim(), TanhComponent::Properties(), RectifiedLinearComponent::Properties(), AffineComponent::Properties(), BlockAffineComponent::Properties(), RepeatedAffineComponent::Properties(), SoftmaxComponent::Properties(), LogSoftmaxComponent::Properties(), LinearComponent::Properties(), SumGroupComponent::Properties(), PerElementScaleComponent::Properties(), PerElementOffsetComponent::Properties(), ConstantFunctionComponent::Properties(), ScaleAndOffsetComponent::Properties(), ConvolutionComponent::Properties(), LstmNonlinearityComponent::Properties(), MaxpoolingComponent::Properties(), CompositeComponent::Type(), and PermuteComponent::ZeroStats().
{
   BaseFloat p = 2.0;
   out->GroupPnorm(in, p);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 54 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kBackpropNeedsOutput, and kaldi::nnet3::kSimpleComponent.
Referenced by CompositeComponent::Type().
{
     return kSimpleComponent|kBackpropNeedsInput|kBackpropNeedsOutput;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 76 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), PnormComponent::input_dim_, PnormComponent::output_dim_, and kaldi::ReadBasicType().
Referenced by PermuteComponent::Add(), PnormComponent::Copy(), ElementwiseProductComponent::Copy(), NoOpComponent::Copy(), ClipGradientComponent::Copy(), DropoutComponent::OutputDim(), FixedAffineComponent::OutputDim(), FixedScaleComponent::OutputDim(), FixedBiasComponent::OutputDim(), SumBlockComponent::OutputDim(), AffineComponent::Properties(), BlockAffineComponent::Properties(), RepeatedAffineComponent::Properties(), LinearComponent::Properties(), SumGroupComponent::Properties(), PerElementScaleComponent::Properties(), PerElementOffsetComponent::Properties(), ConstantFunctionComponent::Properties(), ScaleAndOffsetComponent::Properties(), ConvolutionComponent::Properties(), LstmNonlinearityComponent::Properties(), MaxpoolingComponent::Properties(), NaturalGradientAffineComponent::Type(), NaturalGradientPerElementScaleComponent::Type(), and CompositeComponent::Type().
{
   ExpectOneOrTwoTokens(is, binary, "<PnormComponent>", "<InputDim>");
   ReadBasicType(is, binary, &input_dim_);
   ExpectToken(is, binary, "<OutputDim>");
   ReadBasicType(is, binary, &output_dim_);
   ExpectToken(is, binary, "</PnormComponent>");
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 58 of file nnet-simple-component.h.
References PnormComponent::InitFromConfig().
Referenced by PnormComponent::InitFromConfig().
 { return "PnormComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 84 of file nnet-simple-component.cc.
References PnormComponent::input_dim_, PnormComponent::output_dim_, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by PermuteComponent::Add(), PnormComponent::Copy(), ElementwiseProductComponent::Copy(), NoOpComponent::Copy(), ClipGradientComponent::Copy(), DropoutComponent::OutputDim(), FixedAffineComponent::OutputDim(), FixedScaleComponent::OutputDim(), FixedBiasComponent::OutputDim(), SumBlockComponent::OutputDim(), AffineComponent::Properties(), BlockAffineComponent::Properties(), RepeatedAffineComponent::Properties(), LinearComponent::Properties(), SumGroupComponent::Properties(), PerElementScaleComponent::Properties(), PerElementOffsetComponent::Properties(), ConstantFunctionComponent::Properties(), ScaleAndOffsetComponent::Properties(), ConvolutionComponent::Properties(), LstmNonlinearityComponent::Properties(), MaxpoolingComponent::Properties(), NaturalGradientAffineComponent::Type(), NaturalGradientPerElementScaleComponent::Type(), and CompositeComponent::Type().
{
   WriteToken(os, binary, "<PnormComponent>");
   WriteToken(os, binary, "<InputDim>");
   WriteBasicType(os, binary, input_dim_);
   WriteToken(os, binary, "<OutputDim>");
   WriteBasicType(os, binary, output_dim_);
   WriteToken(os, binary, "</PnormComponent>");
 }
Member Data Documentation
input_dim_
int32 input_dim_ protected
Definition at line 83 of file nnet-simple-component.h.
Referenced by PnormComponent::Copy(), ElementwiseProductComponent::Copy(), PnormComponent::Init(), PnormComponent::InputDim(), ElementwiseProductComponent::InputDim(), SumGroupComponent::InputDim(), SumBlockComponent::InputDim(), ConstantFunctionComponent::InputDim(), PnormComponent::Read(), and PnormComponent::Write().
output_dim_
int32 output_dim_ protected
Definition at line 84 of file nnet-simple-component.h.
Referenced by PnormComponent::Copy(), ElementwiseProductComponent::Copy(), PnormComponent::Init(), PnormComponent::OutputDim(), ElementwiseProductComponent::OutputDim(), SumGroupComponent::OutputDim(), SumBlockComponent::OutputDim(), PnormComponent::Read(), and PnormComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc