Kaldi: TxpPosSet Class Reference
TxpPosSet Class Reference
Part of speech sets see /ref idlaktxp_pos.
#include <txppos.h>
Public Member Functions
TxpPosSet ()
~TxpPosSet ()
void Init (const TxpParseOptions &opts, const std::string &name)
bool Parse (const std::string &tpdb)
const char * GetPosSet (const char *pos)
Return the part of speech for word current with previous context POS prev.
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
virtual void EndElement (const char *name)
Inherited class for bespoke end element handling.
virtual void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
virtual void StartCData ()
Inherited class for bespoke start cdata handling.
virtual void EndCData ()
Inherited class for bespoke start cdata handling.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
Private Attributes
LookupMap posset_
unigram and POS_word bigram patterns.
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
Part of speech sets see /ref idlaktxp_pos.
Definition at line 88 of file txppos.h.
Constructor & Destructor Documentation
TxpPosSet()
TxpPosSet () inline explicit
Definition at line 90 of file txppos.h.
 {}
~TxpPosSet()
~TxpPosSet () inline
Definition at line 91 of file txppos.h.
 {}
Member Function Documentation
GetPosSet()
const char * GetPosSet (const char * pos)
Return the part of speech for word current with previous context POS prev.
Definition at line 118 of file txppos.cc.
Referenced by TxpPosTag::Process().
{
   LookupMap::iterator lkp;
   lkp = posset_.find(std::string(pos));
   if (lkp != posset_.end()) {
     return (lkp->second).c_str();
   }
   return NULL;
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & name) inline
Definition at line 92 of file txppos.h.
References TxpXmlData::Init(), TxpPos::Parse(), and TxpPos::StartElement().
Referenced by TxpPosTag::Init().
{
     TxpXmlData::Init(opts, "posset", name);
   }
Parse()
bool Parse (const std::string & tpdb)
Definition at line 100 of file txppos.cc.
References KALDI_WARN, and TxpXmlData::Parse().
Referenced by TxpPosTag::Init().
{
   bool r;
   r = TxpXmlData::Parse(tpdb);
   if (!r)
     KALDI_WARN << "Error reading part of speech set file: " << tpdb;
   return r;
 }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 108 of file txppos.cc.
References TxpXmlData::SetAttribute().
{
   std::string tagname;
   std::string set;
   if (!strcmp(name, "tag")) {
     SetAttribute("name", atts, &tagname);
     SetAttribute("set", atts, &set);
     posset_.insert(LookupItem(tagname, set));
   }
 }
Member Data Documentation
posset_
LookupMap posset_ private
unigram and POS_word bigram patterns.
Definition at line 103 of file txppos.h.
The documentation for this class was generated from the following files:
idlaktxp/txppos.h
idlaktxp/txppos.cc