Kaldi: TxpPronounce Class Reference
TxpPronounce Class Reference
Convert tokens into pronunications based on lexicons and lts rules.
#include <mod-pronounce.h>
Public Member Functions
TxpPronounce ()
~TxpPronounce ()
bool Init (const TxpParseOptions &opts)
Load voice data.
bool Process (pugi::xml_document *input)
Process the XML, modifying the XML to reflect linguistic information.
Public Member Functions inherited from TxpModule
TxpModule (const std::string &name)
Construct module, also loads tpdb modules in specific instances.
virtual ~TxpModule ()
const std::string GetConfigValue (const std::string &key)
Return a configuration value for this module as a string (rendundant)
const char * GetOptValue (const char *key)
Return an option value for this module as a string.
bool GetConfigValueBool (const std::string &key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
bool GetOptValueBool (const char *key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
const std::string & GetName () const
Get the name of the module.
pugi::xml_node GetHeader (pugi::xml_document *input)
Gets or adds a module header to txpheader.
Private Member Functions
void AppendPron (const char *entry, const std::string &word, TxpLexiconLkp *lexlkp)
Checks lexicon and lts to determine pronuciations and appends it to the lex lookup structure.
Private Attributes
TxpLexicon lex_
A pronuciation lexicon object.
TxpLts lts_
A cart based letter to sound rul object.
TxpPhone phone_
Phoneme set.
Additional Inherited Members
Protected Attributes inherited from TxpModule
const TxpParseOptions * opts_
Options structure for the module.
std::string tpdb_
Directory for text processing database (tpdb) files used by txpxmldata objectys in the module.
Detailed Description
Convert tokens into pronunications based on lexicons and lts rules.
Currently only one lexicon is supported. A user lexicon and ability to add bilingual lexicons may be added. /ref idlaktxp_pron
Definition at line 43 of file mod-pronounce.h.
Constructor & Destructor Documentation
TxpPronounce()
TxpPronounce () explicit
Definition at line 23 of file mod-pronounce.cc.
 : TxpModule("pronounce") {}
~TxpPronounce()
~TxpPronounce ()
Definition at line 25 of file mod-pronounce.cc.
{
 }
Member Function Documentation
AppendPron()
void AppendPron (const char * entry, const std::string & word, TxpLexiconLkp * lexlkp) private
Checks lexicon and lts to determine pronuciations and appends it to the lex lookup structure.
Definition at line 130 of file mod-pronounce.cc.
References TxpLts::GetPron(), TxpLexicon::GetPron(), TxpPronounce::lex_, TxpPronounce::lts_, and TxpLexiconLkp::pron.
Referenced by TxpPronounce::Process().
{
   bool found = false;
   if (!lexlkp->pron.empty()) lexlkp->pron += " ";
   if (entry) {
     found = lex_.GetPron(word, std::string(entry), lexlkp);
     if (!found) {
       found = lex_.GetPron(word, std::string(""), lexlkp);
     }
   } else {
     found = lex_.GetPron(word, std::string(""), lexlkp);
   }
   if (!found)
     found = lts_.GetPron(word, lexlkp);
 }
Init()
bool Init (const TxpParseOptions & opts) virtual
Load voice data.
Reimplemented from TxpModule.
Definition at line 28 of file mod-pronounce.cc.
References TxpModule::GetOptValue(), TxpParseOptions::GetTpdb(), TxpPhone::Init(), TxpLts::Init(), TxpLexicon::Init(), TxpPronounce::lex_, TxpPronounce::lts_, TxpModule::opts_, TxpPhone::Parse(), TxpXmlData::Parse(), TxpPronounce::phone_, and TxpModule::tpdb_.
Referenced by main().
{
   opts_ = &opts;
   tpdb_ = opts.GetTpdb();
   lex_.Init(opts, std::string(GetOptValue("arch")));
   lts_.Init(opts, std::string(GetOptValue("arch")));
   phone_.Init(opts, std::string(GetOptValue("arch")));
   if (lex_.Parse(tpdb_) && lts_.Parse(tpdb_) && phone_.Parse(tpdb_)) return true;
   return false;
 }
Process()
bool Process (pugi::xml_document * input) virtual
Process the XML, modifying the XML to reflect linguistic information.
Reimplemented from TxpModule.
Definition at line 38 of file mod-pronounce.cc.
References TxpLexiconLkp::altprons, TxpPronounce::AppendPron(), TxpPhone::GetPhone(), rnnlm::i, KALDI_ERR, TxpLexiconLkp::lts, TxpPronounce::phone_, TxpLexiconLkp::pron, and TxpLexiconLkp::Reset().
Referenced by main().
{
   pugi::xml_node parent, child;
   pugi::xpath_node_set tks = input->document_element().select_nodes("//tk");
   const char* lex_entry;
   const char* lex_pron;
   const char* word;
   std::string utfchar, word_str, altprons;
   TxpLexiconLkp lexlkp;
   int32 i;
   tks.sort();
   for (pugi::xpath_node_set::const_iterator it = tks.begin();
        it != tks.end();
        ++it) {
     pugi::xml_node node = (*it).node();
     word = node.attribute("norm").value();
     if (std::string(word).compare("") == 0)
         word = node.attribute("tknorm").value();
     lexlkp.Reset();
     // Check to see if token is first daughter of a lex tag
     parent = node.parent();
     lex_entry = NULL;
     lex_pron = NULL;
     while (parent) {
       if (!strcmp(parent.name(), "lex")) {
         if ((*(parent.select_nodes("descendant::tk[1]").begin())).node()
             == node) {
           lex_entry = parent.attribute("entry").value();
           lex_pron = parent.attribute("pron").value();
         }
       }
       parent = parent.parent();
     }
     word_str = std::string(word);
     // If pron is set use that pron
     if (lex_pron && *lex_pron) {
       node.append_attribute("pron").set_value(lex_pron);
     } else {
       // standard lookup of word
       AppendPron(lex_entry, std::string(word), &lexlkp);
       // in the received pronounciation lookup phonemes and check if they
       // exist in the phoneme set
       int32 st_phon_pos = 0, end_phon_pos = 0;
       std::string sub_word = lexlkp.pron.substr(st_phon_pos);
       std::string phone_2_chk = "";
       while (sub_word.length() > 0) {
         end_phon_pos = sub_word.find(" ");
         if (end_phon_pos == std::string::npos) {
           end_phon_pos = sub_word.length()-1;
           phone_2_chk = sub_word;
         } else
           phone_2_chk = sub_word.substr(0, end_phon_pos);
         // if the phoneme has a stress, remove it
         if (isdigit(phone_2_chk.substr(phone_2_chk.length()-1)[0])) {
           phone_2_chk = phone_2_chk.substr(0, phone_2_chk.length()-1);
         }
         // if a phoneme turns out to be an empty string, then it is wrong and
         // the pronounciation is removed.
         if (phone_2_chk.compare("") == 0) {
             lexlkp.pron = "";
             break;
         }
         // if no phoneme is found, pronounciation is removed
         const TxpPhoneDescr* found_phone = phone_.GetPhone(phone_2_chk.c_str());
         if (found_phone == NULL) {
           KALDI_ERR << "Phoneme " << phone_2_chk << " from word " << word << " could not be found";
           lexlkp.pron = "";
           break;
         }
         st_phon_pos = end_phon_pos + 1;
         sub_word = sub_word.substr(st_phon_pos);
       }
       node.append_attribute("pron").set_value(lexlkp.pron.c_str());
       if (lexlkp.lts) {
         node.append_attribute("lts").set_value("true");
       } else if (!lexlkp.lts && lexlkp.altprons.size() > 1) {
         altprons.clear();
         for (i = 0; i < lexlkp.altprons.size(); i++) {
           if (i) altprons = altprons + ", ";
           altprons = altprons + lexlkp.altprons[i];
         }
         node.append_attribute("altprons").set_value(altprons.c_str());
       }
     }
   }
   return true;
 }
Member Data Documentation
lex_
TxpLexicon lex_ private
A pronuciation lexicon object.
Definition at line 56 of file mod-pronounce.h.
Referenced by TxpPronounce::AppendPron(), and TxpPronounce::Init().
lts_
TxpLts lts_ private
A cart based letter to sound rul object.
Definition at line 58 of file mod-pronounce.h.
Referenced by TxpPronounce::AppendPron(), and TxpPronounce::Init().
phone_
TxpPhone phone_ private
Phoneme set.
Definition at line 60 of file mod-pronounce.h.
Referenced by TxpPronounce::Init(), and TxpPronounce::Process().
The documentation for this class was generated from the following files:
idlaktxp/mod-pronounce.h
idlaktxp/mod-pronounce.cc