Kaldi: TxpNRules Class Reference
TxpNRules Class Reference
The nrules object contains regular expressions, lookup tables and normalisation rules (not implemented yet) Required regular expresisons for tokenisation etc.
#include <txpnrules.h>
Public Member Functions
TxpNRules ()
Construct without loading voice data.
~TxpNRules ()
void Init (const TxpParseOptions &opts, const std::string &name)
Set up hard coded regular expressions and lookups.
bool Parse (const std::string &tpdb)
Checks to see what regexs have been found to determine whether to use hard coded defaults.
const std::string * Lkp (const std::string &name, const std::string &key)
Given a lookup table name and a key return the value as a std::string pointer.
const pcre * GetRgx (const std::string &name)
Given a regular expresison name return the pcre regex.
const char * ConsumeToken (const char *input, std::string *token, std::string *wspace)
Copies a token into token, following whitespace into wspace and returns nput pointer incremented to next token.
const char * ConsumePunc (const char *input, std::string *prepunc, std::string *token, std::string *pstpunc)
Takes a token as input and breaks off a token delimited by punctuation This is used in tokenise to split tokens into sub tokens based on punctuation symbols.
void ReplaceUtf8Punc (const std::string &tkin, std::string *tkout)
Replace non-ascii punctuation with an ascii equivilent.
void NormCaseCharacter (std::string *norm, TxpCaseInfo &caseinfo)
Replaces characters which are not in the languages lexicon into equivilents.
bool IsAlpha (const std::string &token)
True if token is only standard lexicon characters (i.e. English a-z)
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
void EndElement (const char *)
Inherited class for bespoke end element handling.
void StartCData ()
Inherited class for bespoke start cdata handling.
void EndCData ()
Inherited class for bespoke start cdata handling.
void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
int32 MakeLkp (LookupMapMap *lkps, const std::string &name, const std::string &cdata)
Parses the lookup format in the cdata into a map and adds it to lkps.
Private Attributes
bool incdata_
Parser status currently in cdata element.
std::string cdata_buffer_
Buffer for cdata data.
const pcre * lkp_item_
Regex to find a lookup item.
const pcre * lkp_open_
Regex to find start of lookup.
const pcre * rgxwspace_
Regex for finding whitespace.
const pcre * rgxsep_
Regex for finding individual symbols that separate tokens.
const pcre * rgxpunc_
Regex for finding punctuation symbols.
const pcre * rgxalpha_
Regex for finding lexicon valid character (e.g. English a-z)
const pcre * rgxwspace_default_
Regex for finding whitespace.
const pcre * rgxsep_default_
Regex for finding individual symbols that separate tokens.
const pcre * rgxpunc_default_
Regex for finding punctuation symbols.
const pcre * rgxalpha_default_
Regex for finding lexicon valid character (e.g. English a-z)
LookupMapMap locallkps_
Map of hard coded lookup tables.
LookupMapMap lkps_
Map of lookup tables in tpdb file.
RgxMap rgxs_
Map of Regexes in tpdb file.
std::string elementtype_
Records type of ellement during expat parse.
std::string elementname_
Records element name during expat parse.
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
The nrules object contains regular expressions, lookup tables and normalisation rules (not implemented yet) Required regular expresisons for tokenisation etc.
are also available as hard coded defaults
Example of a regex which finds items like 39°
  <regex name="int_degree">
      <exp>
          <![CDATA[^([0-9]+)(°)$]]>
      </exp>
  </regex>
Example of a lookup table which converts telphone prefixes into the word telephone
<lookup name="telephone_prefix_table">
  <exp>
    <![CDATA[{"tel":"telephone", "telephone":"telephone", "ph":"phone", "t":"telephone", "phone":"phone"}]]>
  </exp>
</lookup>
For rule information see Normalisation
Definition at line 75 of file txpnrules.h.
Constructor & Destructor Documentation
TxpNRules()
TxpNRules () explicit
Construct without loading voice data.
Definition at line 24 of file txpnrules.cc.
     : incdata_(false),
     cdata_buffer_(""),
     lkp_item_(NULL),
     lkp_open_(NULL),
     rgxwspace_(NULL),
     rgxsep_(NULL),
     rgxpunc_(NULL),
     rgxalpha_(NULL),
     rgxwspace_default_(NULL),
     rgxsep_default_(NULL),
     rgxpunc_default_(NULL),
     rgxalpha_default_(NULL) {
 }
~TxpNRules()
~TxpNRules ()
Definition at line 39 of file txpnrules.cc.
References TxpNRules::lkp_item_, TxpNRules::lkp_open_, TxpNRules::lkps_, TxpNRules::locallkps_, TxpNRules::rgxalpha_default_, TxpNRules::rgxpunc_default_, TxpNRules::rgxs_, TxpNRules::rgxsep_default_, and TxpNRules::rgxwspace_default_.
                       {
   RgxMap::iterator it;
   LookupMapMap::iterator itmap;
   for (it = rgxs_.begin(); it != rgxs_.end(); it++) {
     pcre_free(const_cast<pcre *>(it->second));
   }
   for (itmap = lkps_.begin(); itmap != lkps_.end(); itmap++) {
     delete (itmap->second);
   }
   for (itmap = locallkps_.begin(); itmap != locallkps_.end(); itmap++) {
     delete (itmap->second);
   }
   pcre_free(const_cast<pcre *>(lkp_item_));
   pcre_free(const_cast<pcre *>(lkp_open_));
   pcre_free(const_cast<pcre *>(rgxwspace_default_));
   pcre_free(const_cast<pcre *>(rgxsep_default_));
   pcre_free(const_cast<pcre *>(rgxpunc_default_));
   pcre_free(const_cast<pcre *>(rgxalpha_default_));
 }
Member Function Documentation
CharHandler()
void CharHandler (const char * data, int32 len) private virtual
Inherited class for bespoke character handling.
Reimplemented from TxpXmlData.
Definition at line 294 of file txpnrules.cc.
References TxpNRules::cdata_buffer_, and TxpNRules::incdata_.
{
   if (incdata_) cdata_buffer_.append(data, len);
 }
ConsumePunc()
const char * ConsumePunc (const char * input, std::string * prepunc, std::string * token, std::string * pstpunc)
Takes a token as input and breaks off a token delimited by punctuation This is used in tokenise to split tokens into sub tokens based on punctuation symbols.
Definition at line 195 of file txpnrules.cc.
References TxpPcre::Consume(), TxpNRules::rgxpunc_, and TxpPcre::SetMatch().
{
   TxpPcre pcre;
   const char* p;
   p = pcre.Consume(rgxpunc_, input);
   if (p) {
     pcre.SetMatch(0, prepunc);
     pcre.SetMatch(1, token);
     pcre.SetMatch(2, pstpunc);
     return p;
   } else {
     *prepunc = input;
     *token = "";
     *pstpunc = "";
     return input += strlen(input);
   }
 }
ConsumeToken()
const char * ConsumeToken (const char * input, std::string * token, std::string * wspace)
Copies a token into token, following whitespace into wspace and returns nput pointer incremented to next token.
Definition at line 128 of file txpnrules.cc.
References TxpUtf8::Clen(), TxpPcre::Consume(), TxpNRules::rgxsep_, TxpNRules::rgxwspace_, and TxpPcre::SetMatch().
{
   TxpPcre pcre;
   TxpUtf8 utf8;
   int32 clen;
   const char *p, *s, *w, *pre_s;
   // Check for initial whitespace
   *wspace = "";
   *token = "";
   w = pcre.Consume(rgxwspace_, input);
   if (w) {
     pcre.SetMatch(0, wspace);
     return w;
   }
   // Check for initial separator + whitespace
   clen = utf8.Clen(input);
   s =  pcre.Consume(rgxsep_, input, clen);
   if (s) {
     pcre.SetMatch(0, token);
     w = pcre.Consume(rgxwspace_, s);
     if (w) {
       pcre.SetMatch(0, wspace);
       return w;
     } else {
       return s;
     }
   }
   // Go through utf8 chars until we find whitespace or a separator
   p = input;
   while (*p) {
     clen = utf8.Clen(p);
     token->append(p, clen);
     // increment to next char
     p += clen;
     w = pcre.Consume(rgxwspace_, p);
     if (w) {
       pcre.SetMatch(0, wspace);
       return w;
     }
     pre_s = p;
     clen = utf8.Clen(p);
     s =  pcre.Consume(rgxsep_, p, clen);
     if (s) return pre_s;  // Next token
   }
   return p;
 }
EndCData()
void EndCData () private virtual
Inherited class for bespoke start cdata handling.
Reimplemented from TxpXmlData.
Definition at line 281 of file txpnrules.cc.
References TxpNRules::cdata_buffer_, TxpNRules::elementname_, TxpNRules::elementtype_, TxpNRules::incdata_, TxpNRules::lkps_, TxpNRules::MakeLkp(), and TxpNRules::rgxs_.
{
   const char* error;
   int erroffset;
   incdata_ = false;
   if (elementtype_ == "lookup") {
     MakeLkp(&lkps_, elementname_, cdata_buffer_);
   } else if (elementtype_ == "regex") {
     rgxs_.insert(RgxItem(elementname_, pcre_compile(cdata_buffer_.c_str(),
                                                     PCRE_UTF8, &error,
                                                     &erroffset, NULL)));
   }
 }
EndElement()
void EndElement (const char * name) private virtual
Inherited class for bespoke end element handling.
Reimplemented from TxpXmlData.
Definition at line 272 of file txpnrules.cc.
{
 }
GetRgx()
const pcre * GetRgx (const std::string & name)
Given a regular expresison name return the pcre regex.
Definition at line 118 of file txpnrules.cc.
References TxpNRules::rgxs_.
Referenced by TxpNRules::NormCaseCharacter(), and TxpNRules::Parse().
{
   RgxMap::iterator it;
   it = rgxs_.find(name);
   if (it != rgxs_.end())
     return it->second;
   else
     return NULL;
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & name)
Set up hard coded regular expressions and lookups.
Definition at line 59 of file txpnrules.cc.
References TxpPcre::Compile(), TxpXmlData::Init(), TxpNRules::lkp_item_, TxpNRules::lkp_open_, TxpNRules::locallkps_, TxpNRules::MakeLkp(), TxpNRules::rgxalpha_, TxpNRules::rgxalpha_default_, TxpNRules::rgxpunc_, TxpNRules::rgxpunc_default_, TxpNRules::rgxsep_, TxpNRules::rgxsep_default_, TxpNRules::rgxwspace_, and TxpNRules::rgxwspace_default_.
{
   TxpPcre pcre;
   TxpXmlData::Init(opts, "nrules", name);
   lkp_item_ = pcre.Compile("[\n\\s]*(u?[\\'\\\"](.*?)[\\'\\\"]\\s*:\\s*u?[\\'\\\"](.*?)[\\'\\\"])[\n\\s]*[,}][\n\\s]*");// NOLINT
   lkp_open_ = pcre.Compile("[\n\\s]*{");
   rgxwspace_ = rgxwspace_default_ = pcre.Compile("^([ \n\t\r]+)");
   rgxsep_ = rgxsep_default_ = pcre.Compile("^([\\-\\+\\=\\/@]$)");
   // rgxpunc_ = rgxpunc_default_ = pcre.Compile("^([\\(\\)\\[\\]\\{\\}\\\"'!\\?\\.,;:\\|]*)([^\\(\\)\\[\\]\\{\\}\\\"!\\?;:\\|]*?)([\\(\\)\\[\\]\\{\\}\\\"'!\\?\\.,;:\\|]*)");// NOLINT
   rgxpunc_ = rgxpunc_default_ = pcre.Compile("^([\\(\\)\\[\\]\\{\\}\\\"'!\\?\\.,;:\\|]*)(.*?)([\\(\\)\\[\\]\\{\\}\\\"'!\\?\\.,;:\\|]*)$");
   rgxalpha_ = rgxalpha_default_ = pcre.Compile("^[a-zA-Z_']+$");
   MakeLkp(&locallkps_, "downcase", "{\"A\":\"a\", \"B\":\"b\", \"C\":\"c\", \"D\":\"d\", \"E\":\"e\", \"F\":\"f\", \"G\":\"g\", \"H\":\"h\", \"I\":\"i\", \"J\":\"j\", \"K\":\"k\", \"L\":\"l\", \"M\":\"m\", \"N\":\"n\", \"O\":\"o\", \"P\":\"p\", \"Q\":\"q\", \"R\":\"r\", \"S\":\"s\", \"T\":\"t\", \"U\":\"u\", \"V\":\"v\", \"W\":\"w\", \"X\":\"x\", \"Y\":\"y\", \"Z\":\"z\"}");// NOLINT
   MakeLkp(&locallkps_, "convertillegal", "{\"À\":\"A\", \"Á\":\"A\", \"Â\":\"A\", \"Ã\":\"A\", \"Å\":\"A\", \"Æ\":\"AE\", \"à\":\"a\", \"á\":\"a\", \"â\":\"a\", \"ã\":\"a\", \"å\":\"a\", \"æ\":\"ae\", \"Ç\":\"C\", \"ç\":\"c\", \"È\":\"E\", \"É\":\"E\", \"Ê\":\"E\", \"Ë\":\"E\", \"è\":\"e\", \"é\":\"e\", \"ê\":\"e\", \"ë\":\"e\", \"Ì\":\"I\", \"Í\":\"I\", \"Î\":\"I\", \"Ï\":\"I\", \"ì\":\"i\", \"í\":\"i\", \"î\":\"i\", \"ï\":\"i\", \"Ñ\":\"N\", \"ñ\":\"n\", \"Ò\":\"O\", \"Ó\":\"O\", \"Ô\":\"O\", \"Õ\":\"O\", \"Ø\":\"O\", \"ò\":\"o\", \"ó\":\"o\", \"ô\":\"o\", \"õ\":\"o\", \"ø\":\"o\", \"Ù\":\"U\", \"Ú\":\"U\", \"Û\":\"U\", \"Ű\":u\"Ü\", \"ù\":\"u\", \"ú\":\"u\", \"û\":\"u\", \"ű\":u\"ü\", \"Ý\":\"Y\", \"ý\":\"y\"}");// NOLINT
   MakeLkp(&locallkps_, "utfpunc2ascii", "{\"‘\":\"'\", \"’\":\"'\", \"‛\":\"'\", '“':'\"', '”':'\"',\"΄\":\"'\", \"´\":\"'\", \"`\":\"'\", \"…\":\".\", \"„\":'\"', '–':'-', '–':'-', '–':'-', '—':'-', \"＇\":\"'\"}");// NOLINT
   MakeLkp(&locallkps_, "symbols", "{\"\\\":\"backslash\", \"_\": \"underscore\", \"*\":\"asterisk\", \"#\":\"hash\", \"@\":\"at\", \".\":\"dot\", \"~\":\"tilde\", \"%\":\"percent\", \"<\":\"less than\", \">\":\"more than\", \"=\":\"equals\", \"&\":\"ampersand\", \"+\":\"plus\", \"÷\": \"divided by\", \"¢\": \"cents\", \":\":\"colon\", \"/\":\"slash\", \",\":\"comma\", \"°\":\"degrees\", \"?\":\"question mark\", \"!\":\"exclamation mark\", \"½\":\"half\", \"¼\":\"quarter\", \"¾\":\"three quarters\", \"©\":\"copyright\", \"²\":\"squared\", \"³\":\"cubed\", \"×\":\"times\", \"·\":\"point\", \"√\":\"square root\"}");// NOLINT
   MakeLkp(&locallkps_, "asdigits", "\'0\':\'oh\', \'1\':\'one\', \'2\':\'two\', \'3\':\'three\', \'4\':\'four\', \'5\':\'five\', \'6\':\'six\', \'7\':\'seven\', \'8\':\'eight\', \'9\':\'nine\'}");// NOLINT
 }
IsAlpha()
bool IsAlpha (const std::string & token)
True if token is only standard lexicon characters (i.e. English a-z)
Definition at line 258 of file txpnrules.cc.
References TxpPcre::Execute(), and TxpNRules::rgxalpha_.
{
   TxpPcre pcre;
   if (pcre.Execute(rgxalpha_, token.c_str())) return true;
   return false;
 }
Lkp()
const std::string * Lkp (const std::string & name, const std::string & key)
Given a lookup table name and a key return the value as a std::string pointer.
Definition at line 97 of file txpnrules.cc.
References TxpNRules::lkps_, and TxpNRules::locallkps_.
Referenced by TxpNRules::NormCaseCharacter(), and TxpNRules::ReplaceUtf8Punc().
{
   std::string namekey;
   LookupMapMap::iterator itmap;
   LookupMap::iterator it, tmp;
   itmap = lkps_.find(name);
   if (itmap != lkps_.end()) {
     it = (itmap->second)->find(key);
     if (it != (itmap->second)->end()) return &(it->second);
     else return NULL;
   } else {
     itmap = locallkps_.find(name);
     if (itmap != locallkps_.end()) {
       it = (itmap->second)->find(key);
       if (it != (itmap->second)->end()) return &(it->second);
       else return NULL;
     }
   }
   return NULL;
 }
MakeLkp()
int32 MakeLkp (LookupMapMap * lkps, const std::string & name, const std::string & cdata) private
Parses the lookup format in the cdata into a map and adds it to lkps.
Definition at line 299 of file txpnrules.cc.
References TxpPcre::Consume(), TxpNRules::lkp_item_, TxpNRules::lkp_open_, and TxpPcre::SetMatch().
Referenced by TxpNRules::EndCData(), and TxpNRules::Init().
{
   TxpPcre pcre;
   int32 pplen;
   std::string key;
   std::string val;
   std::string tmp;
   const char* pp, *npp;
   LookupMapMap::iterator itmap;
   // see if we have already created the LookupMap
   itmap = lkps->find(name);
   if (itmap == lkps->end()) {
     // if not add one
     lkps->insert(LookupMapItem(name, new LookupMap));
     itmap = lkps->find(name);
   }
   pp = cdata.c_str();
   pplen = cdata.length();
   // consume opening {
   pp = pcre.Consume(lkp_open_, pp, pplen);
   // no bracket! ignore
   if (!pp) pp = cdata.c_str();
   while (*pp) {
     npp = pcre.Consume(lkp_item_, pp, pplen);
     if (npp) {
       pcre.SetMatch(1, &key);
       pcre.SetMatch(2, &val);
       (itmap->second)->insert(LookupItem(key, val));
       pplen -= npp - pp;
       pp = npp;
     } else {
       return false;
     }
   }
   return true;
 }
NormCaseCharacter()
void NormCaseCharacter (std::string * norm, TxpCaseInfo & caseinfo)
Replaces characters which are not in the languages lexicon into equivilents.
Downcases upper case and sets case information structure
Definition at line 215 of file txpnrules.cc.
References TxpCaseInfo::capitalised, TxpUtf8::Clen(), TxpPcre::Execute(), TxpCaseInfo::foreign, TxpNRules::GetRgx(), rnnlm::j, TxpNRules::Lkp(), TxpCaseInfo::lowercase, TxpCaseInfo::symbols, and TxpCaseInfo::uppercase.
{
   const char* p;
   const std::string* r;
   std::string c;
   std::string result;
   int32 clen, j = 0;
   bool alpha;
   TxpUtf8 utf8;
   TxpPcre pcre;
   p = norm->c_str();
   while (*p) {
     alpha = false;
     clen = utf8.Clen(p);
     c = std::string(p, clen);
     if (pcre.Execute(GetRgx(std::string("alpha")), c)) {
       alpha = true;
       caseinfo.lowercase = true;
     }
     r = Lkp(std::string("convertillegal"), c);
     if (r) {
       c = *r;
       caseinfo.foreign = true;
       alpha = true;
     }
     r = Lkp(std::string("downcase"), c);
     if (r) {
       caseinfo.uppercase = true;
       alpha = true;
       c = *r;
     }
     if (r && j > 0) caseinfo.capitalised = false;
     if (!r && j == 0) caseinfo.capitalised = false;
     if (!alpha) {
       caseinfo.symbols = true;
       caseinfo.capitalised = false;
     }
     result.append(c);
     p += clen;
     j += 1;
   }
   *norm = result;
 }
Parse()
bool Parse (const std::string & tpdb)
Checks to see what regexs have been found to determine whether to use hard coded defaults.
Definition at line 78 of file txpnrules.cc.
References TxpNRules::GetRgx(), KALDI_WARN, TxpXmlData::Parse(), TxpNRules::rgxalpha_, TxpNRules::rgxpunc_, TxpNRules::rgxsep_, and TxpNRules::rgxwspace_.
{
   const pcre* rgx;
   bool r;
   r = TxpXmlData::Parse(tpdb);
   if (r) {
     rgx = GetRgx("whitespace");
     if (rgx) rgxwspace_ = rgx;
     rgx = GetRgx("separators");
     if (rgx) rgxsep_ = rgx;
     rgx = GetRgx("punc_strip");
     if (rgx) rgxpunc_ = rgx;
     rgx = GetRgx("alpha");
     if (rgx) rgxalpha_ = rgx;
   } else {
     KALDI_WARN << "Error reading normaliser rule file: " << tpdb;
   }
   return r;
 }
ReplaceUtf8Punc()
void ReplaceUtf8Punc (const std::string & tkin, std::string * tkout)
Replace non-ascii punctuation with an ascii equivilent.
Definition at line 176 of file txpnrules.cc.
References TxpUtf8::Clen(), and TxpNRules::Lkp().
{
   const char* p;
   const std::string* r;
   TxpUtf8 utf8;
   int32 clen;
   p = tkin.c_str();
   *tkout = "";
   while (*p) {
     clen = utf8.Clen(p);
     r = Lkp(std::string("utfpunc2ascii"), std::string(p, clen));
     if (r)
       tkout->append(*r);
     else
       tkout->append(p, clen);
     p += clen;
   }
 }
StartCData()
void StartCData () private virtual
Inherited class for bespoke start cdata handling.
Reimplemented from TxpXmlData.
Definition at line 275 of file txpnrules.cc.
References TxpNRules::cdata_buffer_, and TxpNRules::incdata_.
{
   cdata_buffer_.clear();
   incdata_ = true;
 }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 264 of file txpnrules.cc.
References TxpNRules::elementname_, TxpNRules::elementtype_, and TxpXmlData::SetAttribute().
{
   // save name and type for procesing cdata
   if (!strcmp(name, "lookup") || !strcmp(name, "regex")) {
     elementtype_ = name;
     SetAttribute("name", atts, &elementname_);
   }
 }
Member Data Documentation
cdata_buffer_
std::string cdata_buffer_ private
Buffer for cdata data.
Definition at line 123 of file txpnrules.h.
Referenced by TxpNRules::CharHandler(), TxpNRules::EndCData(), and TxpNRules::StartCData().
elementname_
std::string elementname_ private
Records element name during expat parse.
Definition at line 156 of file txpnrules.h.
Referenced by TxpNRules::EndCData(), and TxpNRules::StartElement().
elementtype_
std::string elementtype_ private
Records type of ellement during expat parse.
Definition at line 154 of file txpnrules.h.
Referenced by TxpNRules::EndCData(), and TxpNRules::StartElement().
incdata_
bool incdata_ private
Parser status currently in cdata element.
Definition at line 121 of file txpnrules.h.
Referenced by TxpNRules::CharHandler(), TxpNRules::EndCData(), and TxpNRules::StartCData().
lkp_item_
const pcre* lkp_item_ private
Regex to find a lookup item.
Definition at line 125 of file txpnrules.h.
Referenced by TxpNRules::Init(), TxpNRules::MakeLkp(), and TxpNRules::~TxpNRules().
lkp_open_
const pcre* lkp_open_ private
Regex to find start of lookup.
Definition at line 127 of file txpnrules.h.
Referenced by TxpNRules::Init(), TxpNRules::MakeLkp(), and TxpNRules::~TxpNRules().
lkps_
LookupMapMap lkps_ private
Map of lookup tables in tpdb file.
Definition at line 150 of file txpnrules.h.
Referenced by TxpNRules::EndCData(), TxpNRules::Lkp(), and TxpNRules::~TxpNRules().
locallkps_
LookupMapMap locallkps_ private
Map of hard coded lookup tables.
Definition at line 148 of file txpnrules.h.
Referenced by TxpNRules::Init(), TxpNRules::Lkp(), and TxpNRules::~TxpNRules().
rgxalpha_
const pcre* rgxalpha_ private
Regex for finding lexicon valid character (e.g. English a-z)
Definition at line 137 of file txpnrules.h.
Referenced by TxpNRules::Init(), TxpNRules::IsAlpha(), and TxpNRules::Parse().
rgxalpha_default_
const pcre* rgxalpha_default_ private
Regex for finding lexicon valid character (e.g. English a-z)
Definition at line 146 of file txpnrules.h.
Referenced by TxpNRules::Init(), and TxpNRules::~TxpNRules().
rgxpunc_
const pcre* rgxpunc_ private
Regex for finding punctuation symbols.
Definition at line 135 of file txpnrules.h.
Referenced by TxpNRules::ConsumePunc(), TxpNRules::Init(), and TxpNRules::Parse().
rgxpunc_default_
const pcre* rgxpunc_default_ private
Regex for finding punctuation symbols.
Definition at line 144 of file txpnrules.h.
Referenced by TxpNRules::Init(), and TxpNRules::~TxpNRules().
rgxs_
RgxMap rgxs_ private
Map of Regexes in tpdb file.
Definition at line 152 of file txpnrules.h.
Referenced by TxpNRules::EndCData(), TxpNRules::GetRgx(), and TxpNRules::~TxpNRules().
rgxsep_
const pcre* rgxsep_ private
Regex for finding individual symbols that separate tokens.
Definition at line 133 of file txpnrules.h.
Referenced by TxpNRules::ConsumeToken(), TxpNRules::Init(), and TxpNRules::Parse().
rgxsep_default_
const pcre* rgxsep_default_ private
Regex for finding individual symbols that separate tokens.
Definition at line 142 of file txpnrules.h.
Referenced by TxpNRules::Init(), and TxpNRules::~TxpNRules().
rgxwspace_
const pcre* rgxwspace_ private
Regex for finding whitespace.
Definition at line 131 of file txpnrules.h.
Referenced by TxpNRules::ConsumeToken(), TxpNRules::Init(), and TxpNRules::Parse().
rgxwspace_default_
const pcre* rgxwspace_default_ private
Regex for finding whitespace.
Definition at line 140 of file txpnrules.h.
Referenced by TxpNRules::Init(), and TxpNRules::~TxpNRules().
The documentation for this class was generated from the following files:
idlaktxp/txpnrules.h
idlaktxp/txpnrules.cc