Kaldi: TokenHolder Class Reference
TokenHolder Class Reference
"Holder types"
#include <kaldi-holder-inl.h>
Public Types
typedef std::string T
Public Member Functions
TokenHolder ()
void Clear ()
bool Read (std::istream &is)
T & Value ()
~TokenHolder ()
void Swap (TokenHolder *other)
bool ExtractRange (const TokenHolder &other, const std::string &range)
Static Public Member Functions
static bool Write (std::ostream &os, bool, const T &t)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (TokenHolder)
Private Attributes
T t_
Detailed Description
Definition at line 639 of file kaldi-holder-inl.h.
Member Typedef Documentation
T
typedef std::string T
Definition at line 641 of file kaldi-holder-inl.h.
Constructor & Destructor Documentation
TokenHolder()
TokenHolder () inline
Definition at line 643 of file kaldi-holder-inl.h.
 {}
~TokenHolder()
~TokenHolder () inline
Definition at line 676 of file kaldi-holder-inl.h.
 { }
Member Function Documentation
Clear()
void Clear () inline
Definition at line 651 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
 { t_.clear(); }
ExtractRange()
bool ExtractRange (const TokenHolder & other, const std::string & range) inline
Definition at line 682 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::KALDI_DISALLOW_COPY_AND_ASSIGN(), and KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 672 of file kaldi-holder-inl.h.
 { return false; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (TokenHolder) private
Read()
bool Read (std::istream & is) inline
Definition at line 654 of file kaldi-holder-inl.h.
References kaldi::CharToString(), KALDI_WARN, and KaldiObjectHolder< KaldiType >::t_.
{
     is >> t_;
     if (is.fail()) return false;
     char c;
     while (isspace(c = is.peek()) && c!= '\n') is.get();
     if (is.peek() != '\n') {
       KALDI_WARN << "TokenHolder::Read, expected newline, got char "
         << CharToString(is.peek())
         << ", at stream pos " << is.tellg();
       return false;
     }
     is.get();  // get '\n'
     return true;
   }
Swap()
void Swap (TokenHolder * other) inline
Definition at line 678 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_, and TokenHolder::t_.
{
     t_.swap(other->t_);
   }
Value()
T& Value () inline
Definition at line 674 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
 { return t_; }
Write()
static bool Write (std::ostream & os, bool , const T & t) inline static
Definition at line 645 of file kaldi-holder-inl.h.
References kaldi::IsToken(), and KALDI_ASSERT.
                                                       {  // ignore binary-mode
     KALDI_ASSERT(IsToken(t));
     os << t << '\n';
     return os.good();
   }
Member Data Documentation
t_
T t_ private
Definition at line 690 of file kaldi-holder-inl.h.
Referenced by TokenHolder::Swap().
The documentation for this class was generated from the following file:
util/kaldi-holder-inl.h