Kaldi: EventMap Class Reference
EventMap Class Reference abstract
A class that is capable of representing a generic mapping from EventType (which is a vector of (key, value) pairs) to EventAnswerType which is just an integer.
#include <event-map.h>
Public Member Functions
virtual bool Map (const EventType &event, EventAnswerType *ans) const =0
virtual void MultiMap (const EventType &event, std::vector< EventAnswerType > *ans) const =0
virtual void GetChildren (std::vector< EventMap *> *out) const =0
virtual EventMap * Copy (const std::vector< EventMap *> &new_leaves) const =0
EventMap * Copy () const
virtual EventMap * MapValues (const unordered_set< EventKeyType > &keys_to_map, const unordered_map< EventValueType, EventValueType > &value_map) const =0
virtual EventMap * Prune () const =0
virtual EventAnswerType MaxResult () const
virtual void Write (std::ostream &os, bool binary)=0
Write to stream.
virtual ~EventMap ()
Static Public Member Functions
static void Check (const EventType &event)
static bool Lookup (const EventType &event, EventKeyType key, EventValueType *ans)
static void Write (std::ostream &os, bool binary, EventMap *emap)
a Write function that takes care of NULL pointers.
static EventMap * Read (std::istream &is, bool binary)
a Read function that reads an arbitrary EventMap; also works for NULL pointers.
Detailed Description
A class that is capable of representing a generic mapping from EventType (which is a vector of (key, value) pairs) to EventAnswerType which is just an integer.
See Decision tree internals for overview.
Definition at line 86 of file event-map.h.
Constructor & Destructor Documentation
~EventMap()
virtual ~EventMap () inline virtual
Definition at line 156 of file event-map.h.
 {}
Member Function Documentation
Check()
void Check (const EventType & event) static
Definition at line 281 of file event-map.cc.
References rnnlm::i, and KALDI_ASSERT.
Referenced by EventMap::Lookup(), kaldi::TestQuestionsInitRand(), and kaldi::TestSplitDecisionTree().
{
   // will crash if not sorted or has duplicates
   size_t sz = event.size();
   for (size_t i = 0;i+1 < sz;i++)
     KALDI_ASSERT(event[i].first < event[i+1].first);
 }
Copy() [1/2]
virtual EventMap* Copy (const std::vector< EventMap *> & new_leaves) const pure virtual
Implemented in SplitEventMap, TableEventMap, and ConstantEventMap.
Referenced by kaldi::ClusterEventMap(), kaldi::ClusterEventMapRestrictedByKeys(), kaldi::ClusterEventMapRestrictedByMap(), kaldi::ClusterEventMapToNClustersRestrictedByMap(), ContextDependency::Copy(), TableEventMap::Copy(), kaldi::DoTableSplit(), kaldi::DoTableSplitMultiple(), kaldi::MapEventMapLeaves(), kaldi::RenumberEventMap(), kaldi::ShareEventMapLeaves(), kaldi::SplitDecisionTree(), kaldi::TestClusterEventMapGetMappingAndRenumberEventMap(), kaldi::TestClusterEventMapGetMappingAndRenumberEventMap2(), and kaldi::TestEventMapPrune().
Copy() [2/2]
EventMap* Copy () const inline
Definition at line 117 of file event-map.h.
References EventMap::Copy().
Referenced by EventMap::Copy().
 { std::vector<EventMap*> new_leaves; return Copy(new_leaves); }
GetChildren()
virtual void GetChildren (std::vector< EventMap *> * out) const pure virtual
Implemented in SplitEventMap, TableEventMap, and ConstantEventMap.
Referenced by kaldi::_convert_tree(), kaldi::GetTreeStructureInternal(), and kaldi::IsLeafNode().
Lookup()
bool Lookup (const EventType & event, EventKeyType key, EventValueType * ans) static
Definition at line 290 of file event-map.cc.
References EventMap::Check().
Referenced by DecisionTreeSplitter::DoSplitInternal(), kaldi::FilterStatsByKey(), kaldi::PossibleValues(), TreeRenderer::RenderSplit(), TreeRenderer::RenderTable(), kaldi::SplitStatsByKey(), kaldi::TestDoTableSplit(), kaldi::TestGenRandStats(), and kaldi::TestSplitStatsByKey().
{
   // this assumes the the "event" array is sorted (e.g. on the KeyType value;
   // just doing std::sort will do this) and has no duplicate values with the same
   // key.  call Check() to verify this.
 #ifdef KALDI_PARANOID
   Check(event);
 #endif
   std::vector<std::pair<EventKeyType, EventValueType> >::const_iterator
       begin = event.begin(),
       end = event.end(),
       middle;  // "middle" is used as a temporary variable in the algorithm.
   // begin and sz store the current region where the first instance of
   // "value" might appear.
   // This is like this stl algorithm "lower_bound".
   size_t sz = end-begin, half;
   while (sz > 0) {
     half = sz >> 1;
     middle = begin + half;  // "end" here is now reallly the middle.
     if (middle->first < key) {
       begin = middle;
       ++begin;
       sz = sz - half - 1;
     } else {
       sz = half;
     }
   }
   if (begin != end && begin->first == key) {
     *ans = begin->second;
     return true;
   } else {
     return false;
   }
 }
Map()
virtual bool Map (const EventType & event, EventAnswerType * ans) const pure virtual
Implemented in SplitEventMap, TableEventMap, and ConstantEventMap.
Referenced by ContextDependency::Compute(), kaldi::ComputeTreeMapping(), kaldi::GetTreeStructure(), kaldi::GetTreeStructureInternal(), kaldi::InitAmGmmFromOld(), kaldi::SplitStatsByMap(), kaldi::TestBuildTree(), kaldi::TestClusterEventMap(), kaldi::TestDoTableSplit(), kaldi::TestEventMapMapValues(), kaldi::TestEventMapPrune(), and kaldi::TestTrivialTree().
MapValues()
virtual EventMap* MapValues (const unordered_set< EventKeyType > & keys_to_map, const unordered_map< EventValueType, EventValueType > & value_map) const pure virtual
Implemented in SplitEventMap, TableEventMap, and ConstantEventMap.
Referenced by TableEventMap::MapValues(), SplitEventMap::MapValues(), and kaldi::TestEventMapMapValues().
MaxResult()
virtual EventAnswerType MaxResult () const inline virtual
Definition at line 142 of file event-map.h.
References KALDI_WARN.
Referenced by kaldi::BuildTreeTwoLevel(), kaldi::ComputeTreeMapping(), kaldi::GetOccs(), kaldi::InitAmGmm(), kaldi::InitAmGmmFromOld(), ContextDependency::NumPdfs(), kaldi::TestClusterEventMapGetMappingAndRenumberEventMap(), and kaldi::TestEventMap().
                                             {  // child classes may override this for efficiency; here is basic version.
     // returns -1 if nothing found.
     std::vector<EventAnswerType> tmp; EventType empty_event;
     MultiMap(empty_event, &tmp);
     if (tmp.empty()) {
       KALDI_WARN << "EventMap::MaxResult(), empty result";
       return std::numeric_limits<EventAnswerType>::min();
     }
     else { return * std::max_element(tmp.begin(), tmp.end()); }
   }
MultiMap()
virtual void MultiMap (const EventType & event, std::vector< EventAnswerType > * ans) const pure virtual
Implemented in SplitEventMap, TableEventMap, and ConstantEventMap.
Referenced by ContextDependency::EnumeratePairs(), ContextDependency::GetPdfInfo(), kaldi::RenumberEventMap(), kaldi::ShareEventMapLeaves(), kaldi::TestClusterEventMapGetMappingAndRenumberEventMap(), kaldi::TestClusterEventMapGetMappingAndRenumberEventMap2(), kaldi::TestEventMapPrune(), and kaldi::TestShareEventMapLeaves().
Prune()
virtual EventMap* Prune () const pure virtual
Implemented in SplitEventMap, TableEventMap, and ConstantEventMap.
Referenced by TableEventMap::Prune(), SplitEventMap::Prune(), and kaldi::TestEventMapPrune().
Read()
EventMap * Read (std::istream & is, bool binary) static
a Read function that reads an arbitrary EventMap; also works for NULL pointers.
Definition at line 36 of file event-map.cc.
References kaldi::CharToString(), kaldi::ExpectToken(), KALDI_ERR, kaldi::Peek(), ConstantEventMap::Read(), TableEventMap::Read(), and SplitEventMap::Read().
Referenced by ContextDependency::Read(), TableEventMap::Read(), SplitEventMap::Read(), and kaldi::TestEventMapIo().
{
   char c = Peek(is, binary);
   if (c == 'N') {
     ExpectToken(is, binary, "NULL");
     return NULL;
   } else if (c == 'C') {
     return ConstantEventMap::Read(is, binary);
   } else if (c == 'T') {
     return TableEventMap::Read(is, binary);
   } else if (c == 'S') {
     return SplitEventMap::Read(is, binary);
   } else {
     KALDI_ERR << "EventMap::read, was not expecting character " << CharToString(c)
               << ", at file position " << is.tellg();
     return NULL;  // suppress warning.
   }
 }
Write() [1/2]
virtual void Write (std::ostream & os, bool binary) pure virtual
Write to stream.
Implemented in SplitEventMap, TableEventMap, and ConstantEventMap.
Referenced by kaldi::TestBuildTree(), kaldi::TestEventMapIo(), ContextDependency::Write(), EventMap::Write(), and TableEventMap::Write().
Write() [2/2]
void Write (std::ostream & os, bool binary, EventMap * emap) static
a Write function that takes care of NULL pointers.
Definition at line 28 of file event-map.cc.
References EventMap::Write(), and kaldi::WriteToken().
{
   if (emap == NULL) {
     WriteToken(os, binary, "NULL");
   } else {
     emap->Write(os, binary);
   }
 }
The documentation for this class was generated from the following files:
tree/event-map.h
tree/event-map.cc