Kaldi: TrainingGraphCompiler Class Reference
TrainingGraphCompiler Class Reference
#include <training-graph-compiler.h>
Public Member Functions
TrainingGraphCompiler (const TransitionModel &trans_model, const ContextDependency &ctx_dep, fst::VectorFst< fst::StdArc > *lex_fst, const std::vector< int32 > &disambig_syms, const TrainingGraphCompilerOptions &opts)
bool CompileGraph (const fst::VectorFst< fst::StdArc > &word_grammar, fst::VectorFst< fst::StdArc > *out_fst)
bool CompileGraphs (const std::vector< const fst::VectorFst< fst::StdArc > *> &word_fsts, std::vector< fst::VectorFst< fst::StdArc > *> *out_fsts)
bool CompileGraphFromText (const std::vector< int32 > &transcript, fst::VectorFst< fst::StdArc > *out_fst)
bool CompileGraphsFromText (const std::vector< std::vector< int32 > > &word_grammar, std::vector< fst::VectorFst< fst::StdArc > *> *out_fsts)
~TrainingGraphCompiler ()
Private Attributes
const TransitionModel & trans_model_
const ContextDependency & ctx_dep_
fst::VectorFst< fst::StdArc > * lex_fst_
std::vector< int32 > disambig_syms_
int32 subsequential_symbol_
fst::TableComposeCache< fst::Fst< fst::StdArc > > lex_cache_
TrainingGraphCompilerOptions opts_
Detailed Description
Definition at line 58 of file training-graph-compiler.h.
Constructor & Destructor Documentation
TrainingGraphCompiler()
TrainingGraphCompiler (const TransitionModel & trans_model, const ContextDependency & ctx_dep, fst::VectorFst< fst::StdArc > * lex_fst, const std::vector< int32 > & disambig_syms, const TrainingGraphCompilerOptions & opts)
Definition at line 26 of file training-graph-compiler.cc.
References fst::AddSubsequentialLoop(), ContextDependency::CentralPosition(), ContextDependency::ContextWidth(), TrainingGraphCompiler::disambig_syms_, TransitionModel::GetPhones(), rnnlm::i, kaldi::IsSortedAndUniq(), KALDI_ASSERT, KALDI_ERR, TrainingGraphCompiler::lex_fst_, kaldi::SortAndUniq(), TrainingGraphCompiler::subsequential_symbol_, and TrainingGraphCompiler::trans_model_.
                                                                                       :
     trans_model_(trans_model), ctx_dep_(ctx_dep), lex_fst_(lex_fst),
     disambig_syms_(disambig_syms), opts_(opts) {
   using namespace fst;
   const std::vector<int32> &phone_syms = trans_model_.GetPhones();  // needed to create context fst.
   KALDI_ASSERT(!phone_syms.empty());
   KALDI_ASSERT(IsSortedAndUniq(phone_syms));
   SortAndUniq(&disambig_syms_);
   for (int32 i = 0; i < disambig_syms_.size(); i++)
     if (std::binary_search(phone_syms.begin(), phone_syms.end(),
                            disambig_syms_[i]))
       KALDI_ERR << "Disambiguation symbol " << disambig_syms_[i]
                 << " is also a phone.";
   subsequential_symbol_ = 1 + phone_syms.back();
   if (!disambig_syms_.empty() && subsequential_symbol_ <= disambig_syms_.back())
     subsequential_symbol_ = 1 + disambig_syms_.back();
   {
     int32 N = ctx_dep.ContextWidth(),
         P = ctx_dep.CentralPosition();
     if (P != N-1)
       AddSubsequentialLoop(subsequential_symbol_, lex_fst_);  // This is needed for
     // systems with right-context or we will not successfully compose
     // with C.
   }
   {  // make sure lexicon is olabel sorted.
     fst::OLabelCompare<fst::StdArc> olabel_comp;
     fst::ArcSort(lex_fst_, olabel_comp);
   }
 }
~TrainingGraphCompiler()
~TrainingGraphCompiler () inline
Definition at line 93 of file training-graph-compiler.h.
 { delete lex_fst_; }
Member Function Documentation
CompileGraph()
bool CompileGraph (const fst::VectorFst< fst::StdArc > & word_grammar, fst::VectorFst< fst::StdArc > * out_fst)
Definition at line 73 of file training-graph-compiler.cc.
References kaldi::AddSelfLoops(), ContextDependency::CentralPosition(), fst::ComposeDeterministicOnDemandInverse(), ContextDependency::ContextWidth(), TrainingGraphCompiler::ctx_dep_, fst::DeterminizeStarInLog(), TrainingGraphCompiler::disambig_syms_, kaldi::GetHTransducer(), TransitionModel::GetPhones(), KALDI_ASSERT, TrainingGraphCompiler::lex_cache_, TrainingGraphCompiler::lex_fst_, fst::MinimizeEncoded(), TrainingGraphCompiler::opts_, fst::RemoveEpsLocal(), fst::RemoveSomeInputSymbols(), TrainingGraphCompilerOptions::reorder, TrainingGraphCompilerOptions::rm_eps, TrainingGraphCompilerOptions::self_loop_scale, TrainingGraphCompiler::subsequential_symbol_, fst::TableCompose(), TrainingGraphCompiler::trans_model_, TrainingGraphCompilerOptions::transition_scale, and HTransducerConfig::transition_scale.
Referenced by TrainingGraphCompiler::CompileGraphFromText(), and main().
{
   using namespace fst;
   KALDI_ASSERT(lex_fst_ !=NULL);
   KALDI_ASSERT(out_fst != NULL);
   VectorFst<StdArc> phone2word_fst;
   // TableCompose more efficient than compose.
   TableCompose(*lex_fst_, word_fst, &phone2word_fst, &lex_cache_);
   KALDI_ASSERT(phone2word_fst.Start() != kNoStateId);
   const std::vector<int32> &phone_syms = trans_model_.GetPhones();  // needed to create context fst.
   // inv_cfst will be expanded on the fly, as needed.
   InverseContextFst inv_cfst(subsequential_symbol_,
                              phone_syms,
                              disambig_syms_,
                              ctx_dep_.ContextWidth(),
                              ctx_dep_.CentralPosition());
   VectorFst<StdArc> ctx2word_fst;
   ComposeDeterministicOnDemandInverse(phone2word_fst, &inv_cfst, &ctx2word_fst);
   // now ctx2word_fst is C * LG, assuming phone2word_fst is written as LG.
   KALDI_ASSERT(ctx2word_fst.Start() != kNoStateId);
   HTransducerConfig h_cfg;
   h_cfg.transition_scale = opts_.transition_scale;
   std::vector<int32> disambig_syms_h; // disambiguation symbols on
   // input side of H.
   VectorFst<StdArc> *H = GetHTransducer(inv_cfst.IlabelInfo(),
                                         ctx_dep_,
                                         trans_model_,
                                         h_cfg,
                                         &disambig_syms_h);
   VectorFst<StdArc> &trans2word_fst = *out_fst;  // transition-id to word.
   TableCompose(*H, ctx2word_fst, &trans2word_fst);
   KALDI_ASSERT(trans2word_fst.Start() != kNoStateId);
   // Epsilon-removal and determinization combined. This will fail if not determinizable.
   DeterminizeStarInLog(&trans2word_fst);
   if (!disambig_syms_h.empty()) {
     RemoveSomeInputSymbols(disambig_syms_h, &trans2word_fst);
     // we elect not to remove epsilons after this phase, as it is
     // a little slow.
     if (opts_.rm_eps)
       RemoveEpsLocal(&trans2word_fst);
   }
   // Encoded minimization.
   MinimizeEncoded(&trans2word_fst);
   std::vector<int32> disambig;
   bool check_no_self_loops = true;
   AddSelfLoops(trans_model_,
                disambig,
                opts_.self_loop_scale,
                opts_.reorder,
                check_no_self_loops,
                &trans2word_fst);
   delete H;
   return true;
 }
CompileGraphFromText()
bool CompileGraphFromText (const std::vector< int32 > & transcript, fst::VectorFst< fst::StdArc > * out_fst)
Definition at line 64 of file training-graph-compiler.cc.
References TrainingGraphCompiler::CompileGraph(), and fst::MakeLinearAcceptor().
Referenced by main().
{
   using namespace fst;
   VectorFst<StdArc> word_fst;
   MakeLinearAcceptor(transcript, &word_fst);
   return CompileGraph(word_fst, out_fst);
 }
CompileGraphs()
bool CompileGraphs (const std::vector< const fst::VectorFst< fst::StdArc > *> & word_fsts, std::vector< fst::VectorFst< fst::StdArc > *> * out_fsts)
Definition at line 161 of file training-graph-compiler.cc.
References kaldi::AddSelfLoops(), ContextDependency::CentralPosition(), fst::ComposeDeterministicOnDemandInverse(), ContextDependency::ContextWidth(), TrainingGraphCompiler::ctx_dep_, fst::DeterminizeStarInLog(), TrainingGraphCompiler::disambig_syms_, kaldi::GetHTransducer(), TransitionModel::GetPhones(), rnnlm::i, KALDI_ASSERT, TrainingGraphCompiler::lex_cache_, TrainingGraphCompiler::lex_fst_, fst::MinimizeEncoded(), TrainingGraphCompiler::opts_, fst::RemoveEpsLocal(), fst::RemoveSomeInputSymbols(), TrainingGraphCompilerOptions::reorder, TrainingGraphCompilerOptions::rm_eps, TrainingGraphCompilerOptions::self_loop_scale, TrainingGraphCompiler::subsequential_symbol_, fst::TableCompose(), TrainingGraphCompiler::trans_model_, TrainingGraphCompilerOptions::transition_scale, and HTransducerConfig::transition_scale.
Referenced by TrainingGraphCompiler::CompileGraphsFromText(), and main().
{
   using namespace fst;
   KALDI_ASSERT(lex_fst_ !=NULL);
   KALDI_ASSERT(out_fsts != NULL && out_fsts->empty());
   out_fsts->resize(word_fsts.size(), NULL);
   if (word_fsts.empty()) return true;
   const std::vector<int32> &phone_syms = trans_model_.GetPhones();  // needed to create context fst.
   // inv_cfst will be expanded on the fly, as needed.
   InverseContextFst inv_cfst(subsequential_symbol_,
                              phone_syms,
                              disambig_syms_,
                              ctx_dep_.ContextWidth(),
                              ctx_dep_.CentralPosition());
   for (size_t i = 0; i < word_fsts.size(); i++) {
     VectorFst<StdArc> phone2word_fst;
     // TableCompose more efficient than compose.
     TableCompose(*lex_fst_, *(word_fsts[i]), &phone2word_fst, &lex_cache_);
     KALDI_ASSERT(phone2word_fst.Start() != kNoStateId &&
                  "Perhaps you have words missing in your lexicon?");
     VectorFst<StdArc> ctx2word_fst;
     ComposeDeterministicOnDemandInverse(phone2word_fst, &inv_cfst, &ctx2word_fst);
     // now ctx2word_fst is C * LG, assuming phone2word_fst is written as LG.
     KALDI_ASSERT(ctx2word_fst.Start() != kNoStateId);
     (*out_fsts)[i] = ctx2word_fst.Copy();  // For now this contains the FST with symbols
     // representing phones-in-context.
   }
   HTransducerConfig h_cfg;
   h_cfg.transition_scale = opts_.transition_scale;
   std::vector<int32> disambig_syms_h;
   VectorFst<StdArc> *H = GetHTransducer(inv_cfst.IlabelInfo(),
                                         ctx_dep_,
                                         trans_model_,
                                         h_cfg,
                                         &disambig_syms_h);
   for (size_t i = 0; i < out_fsts->size(); i++) {
     VectorFst<StdArc> &ctx2word_fst = *((*out_fsts)[i]);
     VectorFst<StdArc> trans2word_fst;
     TableCompose(*H, ctx2word_fst, &trans2word_fst);
     DeterminizeStarInLog(&trans2word_fst);
     if (!disambig_syms_h.empty()) {
       RemoveSomeInputSymbols(disambig_syms_h, &trans2word_fst);
       if (opts_.rm_eps)
         RemoveEpsLocal(&trans2word_fst);
     }
     // Encoded minimization.
     MinimizeEncoded(&trans2word_fst);
     std::vector<int32> disambig;
     bool check_no_self_loops = true;
     AddSelfLoops(trans_model_,
                  disambig,
                  opts_.self_loop_scale,
                  opts_.reorder,
                  check_no_self_loops,
                  &trans2word_fst);
     KALDI_ASSERT(trans2word_fst.Start() != kNoStateId);
     *((*out_fsts)[i]) = trans2word_fst;
   }
   delete H;
   return true;
 }
CompileGraphsFromText()
bool CompileGraphsFromText (const std::vector< std::vector< int32 > > & word_grammar, std::vector< fst::VectorFst< fst::StdArc > *> * out_fsts)
Definition at line 145 of file training-graph-compiler.cc.
References TrainingGraphCompiler::CompileGraphs(), rnnlm::i, and fst::MakeLinearAcceptor().
Referenced by main().
{
   using namespace fst;
   std::vector<const VectorFst<StdArc>* > word_fsts(transcripts.size());
   for (size_t i = 0; i < transcripts.size(); i++) {
     VectorFst<StdArc> *word_fst = new VectorFst<StdArc>();
     MakeLinearAcceptor(transcripts[i], word_fst);
     word_fsts[i] = word_fst;
   }
   bool ans = CompileGraphs(word_fsts, out_fsts);
   for (size_t i = 0; i < transcripts.size(); i++)
     delete word_fsts[i];
   return ans;
 }
Member Data Documentation
ctx_dep_
const ContextDependency& ctx_dep_ private
Definition at line 96 of file training-graph-compiler.h.
Referenced by TrainingGraphCompiler::CompileGraph(), and TrainingGraphCompiler::CompileGraphs().
disambig_syms_
std::vector<int32> disambig_syms_ private
Definition at line 99 of file training-graph-compiler.h.
Referenced by TrainingGraphCompiler::CompileGraph(), TrainingGraphCompiler::CompileGraphs(), and TrainingGraphCompiler::TrainingGraphCompiler().
lex_cache_
fst::TableComposeCache<fst::Fst<fst::StdArc> > lex_cache_ private
Definition at line 102 of file training-graph-compiler.h.
Referenced by TrainingGraphCompiler::CompileGraph(), and TrainingGraphCompiler::CompileGraphs().
lex_fst_
fst::VectorFst<fst::StdArc>* lex_fst_ private
Definition at line 97 of file training-graph-compiler.h.
Referenced by TrainingGraphCompiler::CompileGraph(), TrainingGraphCompiler::CompileGraphs(), and TrainingGraphCompiler::TrainingGraphCompiler().
opts_
TrainingGraphCompilerOptions opts_ private
Definition at line 105 of file training-graph-compiler.h.
Referenced by TrainingGraphCompiler::CompileGraph(), and TrainingGraphCompiler::CompileGraphs().
subsequential_symbol_
int32 subsequential_symbol_ private
Definition at line 100 of file training-graph-compiler.h.
Referenced by TrainingGraphCompiler::CompileGraph(), TrainingGraphCompiler::CompileGraphs(), and TrainingGraphCompiler::TrainingGraphCompiler().
trans_model_
const TransitionModel& trans_model_ private
Definition at line 95 of file training-graph-compiler.h.
Referenced by TrainingGraphCompiler::CompileGraph(), TrainingGraphCompiler::CompileGraphs(), and TrainingGraphCompiler::TrainingGraphCompiler().
The documentation for this class was generated from the following files:
decoder/training-graph-compiler.h
decoder/training-graph-compiler.cc