Kaldi: LatticeReader Class Reference
LatticeReader Class Reference
LatticeReader provides (static) functions for reading both Lattice and CompactLattice, in text form.
Static Public Member Functions
static std::pair< Lattice *, CompactLattice * > ReadText (std::istream &is)
This function reads from the FST text format; it does not know in advance whether it's a Lattice or CompactLattice in the stream so it tries to read both formats until it becomes clear which is the correct one.
static bool StrToWeight (const std::string &s, bool allow_zero, Weight *w)
static bool StrToCWeight (const std::string &s, bool allow_zero, CWeight *w)
Private Types
typedef LatticeArc Arc
typedef LatticeWeight Weight
typedef CompactLatticeArc CArc
typedef CompactLatticeWeight CWeight
typedef Arc::Label Label
typedef Arc::StateId StateId
Detailed Description
LatticeReader provides (static) functions for reading both Lattice and CompactLattice, in text form.
Definition at line 94 of file kaldi-lattice.cc.
Member Typedef Documentation
Arc
typedef LatticeArc Arc private
Definition at line 95 of file kaldi-lattice.cc.
CArc
typedef CompactLatticeArc CArc private
Definition at line 97 of file kaldi-lattice.cc.
CWeight
typedef CompactLatticeWeight CWeight private
Definition at line 98 of file kaldi-lattice.cc.
Label
typedef Arc::Label Label private
Definition at line 99 of file kaldi-lattice.cc.
StateId
typedef Arc::StateId StateId private
Definition at line 100 of file kaldi-lattice.cc.
Weight
typedef LatticeWeight Weight private
Definition at line 96 of file kaldi-lattice.cc.
Member Function Documentation
ReadText()
static std::pair<Lattice*, CompactLattice*> ReadText (std::istream & is) inline static
This function reads from the FST text format; it does not know in advance whether it's a Lattice or CompactLattice in the stream so it tries to read both formats until it becomes clear which is the correct one.
Definition at line 108 of file kaldi-lattice.cc.
References kaldi::ConvertStringToInteger(), rnnlm::d, KALDI_WARN, LatticeWeightTpl< BaseFloat >::One(), CompactLatticeWeightTpl< WeightType, IntType >::One(), kaldi::SplitStringToVector(), LatticeReader::StrToCWeight(), and LatticeReader::StrToWeight().
Referenced by kaldi::ReadCompactLatticeText(), and kaldi::ReadLatticeText().
                       {
     typedef std::pair<Lattice*, CompactLattice*> PairT;
     using std::string;
     using std::vector;
     Lattice *fst = new Lattice();
     CompactLattice *cfst = new CompactLattice();
     string line;
     size_t nline = 0;
     string separator = FLAGS_fst_field_separator + "\r\n";
     while (std::getline(is, line)) {
       nline++;
       vector<string> col;
       // on Windows we'll write in text and read in binary mode.
       SplitStringToVector(line, separator.c_str(), true, &col);
       if (col.size() == 0) break; // Empty line is a signal to stop, in our
       // archive format.
       if (col.size() > 5) {
         KALDI_WARN << "Reading lattice: bad line in FST: " << line;
         delete fst;
         delete cfst;
         return PairT(static_cast<Lattice*>(NULL),
                      static_cast<CompactLattice*>(NULL));
       }
       StateId s;
       if (!ConvertStringToInteger(col[0], &s)) {
         KALDI_WARN << "FstCompiler: bad line in FST: " << line;
         delete fst;
         delete cfst;
         return PairT(static_cast<Lattice*>(NULL),
                      static_cast<CompactLattice*>(NULL));
       }
       if (fst)
         while (s >= fst->NumStates())
           fst->AddState();
       if (cfst)
         while (s >= cfst->NumStates())
           cfst->AddState();
       if (nline == 1) {
         if (fst) fst->SetStart(s);
         if (cfst) cfst->SetStart(s);
       }
       if (fst) { // we still have fst; try to read that arc.
         bool ok = true;
         Arc arc;
         Weight w;
         StateId d = s;
         switch (col.size()) {
           case 1 :
             fst->SetFinal(s, Weight::One());
             break;
           case 2:
             if (!StrToWeight(col[1], true, &w)) ok = false;
             else fst->SetFinal(s, w);
             break;
           case 3: // 3 columns not ok for Lattice format; it's not an acceptor.
             ok = false;
             break;
           case 4:
             ok = ConvertStringToInteger(col[1], &arc.nextstate) &&
                 ConvertStringToInteger(col[2], &arc.ilabel) &&
                 ConvertStringToInteger(col[3], &arc.olabel);
             if (ok) {
               d = arc.nextstate;
               arc.weight = Weight::One();
               fst->AddArc(s, arc);
             }
             break;
           case 5:
             ok = ConvertStringToInteger(col[1], &arc.nextstate) &&
                 ConvertStringToInteger(col[2], &arc.ilabel) &&
                 ConvertStringToInteger(col[3], &arc.olabel) &&
                 StrToWeight(col[4], false, &arc.weight);
             if (ok) {
               d = arc.nextstate;
               fst->AddArc(s, arc);
             }
             break;
           default:
             ok = false;
         }
         while (d >= fst->NumStates())
           fst->AddState();
         if (!ok) {
           delete fst;
           fst = NULL;
         }
       }
       if (cfst) {
         bool ok = true;
         CArc arc;
         CWeight w;
         StateId d = s;
         switch (col.size()) {
           case 1 :
             cfst->SetFinal(s, CWeight::One());
             break;
           case 2:
             if (!StrToCWeight(col[1], true, &w)) ok = false;
             else cfst->SetFinal(s, w);
             break;
           case 3: // compact-lattice is acceptor format: state, next-state, label.
             ok = ConvertStringToInteger(col[1], &arc.nextstate) &&
                 ConvertStringToInteger(col[2], &arc.ilabel);
             if (ok) {
               d = arc.nextstate;
               arc.olabel = arc.ilabel;
               arc.weight = CWeight::One();
               cfst->AddArc(s, arc);
             }
             break;
           case 4:
             ok = ConvertStringToInteger(col[1], &arc.nextstate) &&
                 ConvertStringToInteger(col[2], &arc.ilabel) &&
                 StrToCWeight(col[3], false, &arc.weight);
             if (ok) {
               d = arc.nextstate;
               arc.olabel = arc.ilabel;
               cfst->AddArc(s, arc);
             }
             break;
           case 5: default:
             ok = false;
         }
         while (d >= cfst->NumStates())
           cfst->AddState();
         if (!ok) {
           delete cfst;
           cfst = NULL;
         }
       }
       if (!fst && !cfst) {
         KALDI_WARN << "Bad line in lattice text format: " << line;
         // read until we get an empty line, so at least we
         // have a chance to read the next one (although this might
         // be a bit futile since the calling code will get unhappy
         // about failing to read this one.
         while (std::getline(is, line)) {
           SplitStringToVector(line, separator.c_str(), true, &col);
           if (col.empty()) break;
         }
         return PairT(static_cast<Lattice*>(NULL),
                      static_cast<CompactLattice*>(NULL));
       }
     }
     return PairT(fst, cfst);
   }
StrToCWeight()
static bool StrToCWeight (const std::string & s, bool allow_zero, CWeight * w) inline static
Definition at line 266 of file kaldi-lattice.cc.
References CompactLatticeWeightTpl< WeightType, IntType >::Zero().
Referenced by LatticeReader::ReadText().
{
     std::istringstream strm(s);
     strm >> *w;
     if (!strm || (!allow_zero && *w == CWeight::Zero())) {
       return false;
     }
     return true;
   }
StrToWeight()
static bool StrToWeight (const std::string & s, bool allow_zero, Weight * w) inline static
Definition at line 257 of file kaldi-lattice.cc.
References LatticeWeightTpl< BaseFloat >::Zero().
Referenced by LatticeReader::ReadText().
{
     std::istringstream strm(s);
     strm >> *w;
     if (!strm || (!allow_zero && *w == Weight::Zero())) {
       return false;
     }
     return true;
   }
The documentation for this class was generated from the following file:
lat/kaldi-lattice.cc