Kaldi: DecodableMatrixScaledMapped Class Reference
DecodableMatrixScaledMapped Class Reference
#include <decodable-matrix.h>
Public Member Functions
DecodableMatrixScaledMapped (const TransitionModel &tm, const Matrix< BaseFloat > &likes, BaseFloat scale)
DecodableMatrixScaledMapped (const TransitionModel &tm, BaseFloat scale, const Matrix< BaseFloat > *likes)
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual BaseFloat LogLikelihood (int32 frame, int32 tid)
Returns the log likelihood, which will be negated in the decoder.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
virtual ~DecodableMatrixScaledMapped ()
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableMatrixScaledMapped)
Private Attributes
const TransitionModel & trans_model_
const Matrix< BaseFloat > * likes_
BaseFloat scale_
bool delete_likes_
Detailed Description
Definition at line 33 of file decodable-matrix.h.
Constructor & Destructor Documentation
DecodableMatrixScaledMapped() [1/2]
DecodableMatrixScaledMapped (const TransitionModel & tm, const Matrix< BaseFloat > & likes, BaseFloat scale) inline
Definition at line 37 of file decodable-matrix.h.
References KALDI_ERR, MatrixBase< Real >::NumCols(), and TransitionModel::NumPdfs().
                                               : trans_model_(tm), likes_(&likes),
                                                 scale_(scale), delete_likes_(false) {
     if (likes.NumCols() != tm.NumPdfs())
       KALDI_ERR << "DecodableMatrixScaledMapped: mismatch, matrix has "
                 << likes.NumCols() << " rows but transition-model has "
                 << tm.NumPdfs() << " pdf-ids.";
   }
DecodableMatrixScaledMapped() [2/2]
DecodableMatrixScaledMapped (const TransitionModel & tm, BaseFloat scale, const Matrix< BaseFloat > * likes) inline
Definition at line 49 of file decodable-matrix.h.
References KALDI_ERR, MatrixBase< Real >::NumCols(), and TransitionModel::NumPdfs().
                                                              :
       trans_model_(tm), likes_(likes),
       scale_(scale), delete_likes_(true) {
     if (likes->NumCols() != tm.NumPdfs())
       KALDI_ERR << "DecodableMatrixScaledMapped: mismatch, matrix has "
                 << likes->NumCols() << " rows but transition-model has "
                 << tm.NumPdfs() << " pdf-ids.";
   }
~DecodableMatrixScaledMapped()
virtual ~DecodableMatrixScaledMapped () inline virtual
Definition at line 75 of file decodable-matrix.h.
References DecodableMatrixScaledMapped::delete_likes_, and DecodableMatrixScaledMapped::likes_.
{
     if (delete_likes_) delete likes_;
   }
Member Function Documentation
IsLastFrame()
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frames are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). Caution: the behavior of this function in an online setting is being changed somewhat. In future it may return false in cases where we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. The plan in future is to rely more on NumFramesReady(), and in future, IsLastFrame() would always return false in an online-decoding setting, and would only return true in a decoding-from-matrix setting where we want to allow the last delta or LDA features to be flushed out for compatibility with the baseline setup.
Implements DecodableInterface.
Definition at line 62 of file decodable-matrix.h.
References KALDI_ASSERT, and DecodableMatrixScaledMapped::NumFramesReady().
{
     KALDI_ASSERT(frame < NumFramesReady());
     return (frame == NumFramesReady() - 1);
   }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableMatrixScaledMapped) private
LogLikelihood()
virtual BaseFloat LogLikelihood (int32 frame, int32 index) inline virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Definition at line 68 of file decodable-matrix.h.
References DecodableMatrixScaledMapped::scale_, DecodableMatrixScaledMapped::trans_model_, and TransitionModel::TransitionIdToPdf().
{
     return scale_ * (*likes_)(frame, trans_model_.TransitionIdToPdf(tid));
   }
NumFramesReady()
virtual int32 NumFramesReady () const inline virtual
The call NumFramesReady() will return the number of frames currently available for this decodable object.
This is for use in setups where you don't want the decoder to block while waiting for input. This is newly added as of Jan 2014, and I hope, going forward, to rely on this mechanism more than IsLastFrame to know when to stop decoding.
Reimplemented from DecodableInterface.
Definition at line 60 of file decodable-matrix.h.
References DecodableMatrixScaledMapped::likes_, and MatrixBase< Real >::NumRows().
Referenced by DecodableMatrixScaledMapped::IsLastFrame(), DecodableMatrixMappedOffset::IsLastFrame(), and DecodableMatrixScaled::IsLastFrame().
 { return likes_->NumRows(); }
NumIndices()
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst).
Implements DecodableInterface.
Definition at line 73 of file decodable-matrix.h.
References TransitionModel::NumTransitionIds(), and DecodableMatrixScaledMapped::trans_model_.
 { return trans_model_.NumTransitionIds(); }
Member Data Documentation
delete_likes_
bool delete_likes_ private
Definition at line 82 of file decodable-matrix.h.
Referenced by DecodableMatrixScaledMapped::~DecodableMatrixScaledMapped().
likes_
const Matrix<BaseFloat>* likes_ private
Definition at line 80 of file decodable-matrix.h.
Referenced by DecodableMatrixScaled::LogLikelihood(), DecodableMatrixScaledMapped::NumFramesReady(), DecodableMatrixScaled::NumFramesReady(), DecodableMatrixScaled::NumIndices(), and DecodableMatrixScaledMapped::~DecodableMatrixScaledMapped().
scale_
BaseFloat scale_ private
Definition at line 81 of file decodable-matrix.h.
Referenced by DecodableMatrixScaledMapped::LogLikelihood(), and DecodableMatrixScaled::LogLikelihood().
trans_model_
const TransitionModel& trans_model_ private
Definition at line 79 of file decodable-matrix.h.
Referenced by DecodableMatrixMappedOffset::AcceptLoglikes(), DecodableMatrixScaledMapped::LogLikelihood(), DecodableMatrixMappedOffset::LogLikelihood(), DecodableMatrixScaledMapped::NumIndices(), and DecodableMatrixMappedOffset::NumIndices().
The documentation for this class was generated from the following file:
decoder/decodable-matrix.h