Kaldi: TxpTrules Class Reference
TxpTrules Class Reference
The trules object contains regular expression and lookup tables.
#include <txptrules.h>
Public Member Functions
TxpTrules ()
Construct without loading voice data.
~TxpTrules ()
void Init (const TxpParseOptions &opts, const std::string &name)
Set up hard coded regular expressions and lookups.
bool Parse (const std::string &tpdb)
Checks to see what regexs have been found to determine whether to use hard coded defaults.
const std::string * Lkp (const std::string &name, const std::string &key)
Given a lookup table name and a key return the value as a std::string pointer.
const pcre * GetRgx (const std::string &name)
Given a regular expresison name return the pcre regex.
const char * ConsumeWhitespaceToken (const char *input, std::string *token, std::string *wspace)
Copies a token into token, following whitespace into wspace and returns nput pointer incremented to next token.
const char * ConsumePunc (const char *input, std::string *punc)
Takes a token as input and breaks off a token delimited by punctuation This is used in tokenise to split tokens into sub tokens based on punctuation symbols.
const char * ConsumeToken (const char *input, std::string *token)
Goes through a set of valid tokens and breaks off the first it finds.
void ReplaceUtf8Punc (const std::string &tkin, std::string *tkout)
Replace non-ascii punctuation with an ascii equivilent.
void NormCaseCharacter (std::string *norm, TxpTrulesCaseInfo &caseinfo)
Replaces characters which are not in the languages lexicon into equivilents.
bool IsAlpha (const std::string &token)
True if token is only standard lexicon characters (i.e. English a-z)
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
void EndElement (const char *)
Inherited class for bespoke end element handling.
void StartCData ()
Inherited class for bespoke start cdata handling.
void EndCData ()
Inherited class for bespoke start cdata handling.
void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
int32 MakeLkp (LookupMapMap *lkps, const std::string &name, const std::string &cdata)
Parses the lookup format in the cdata into a map and adds it to lkps.
Private Attributes
bool incdata_
Parser status currently in cdata element.
std::string cdata_buffer_
Buffer for cdata data.
const pcre * lkp_item_
Regex to find a lookup item.
const pcre * lkp_open_
Regex to find start of lookup.
const pcre * rgxwspace_
Regex for finding whitespace.
const pcre * rgxsep_
Regex for finding individual symbols that separate tokens.
const pcre * rgxpunc_
Regex for finding punctuation symbols.
const pcre * rgxalpha_
Regex for finding lexicon valid character (e.g. English a-z)
const pcre * rgxwspace_default_
Regex for finding whitespace.
LookupMapMap lkps_
Map of lookup tables in tpdb file.
RgxMap rgxs_
Map of Regexes in tpdb file.
RgxVector tokrgxs_
List of valid tokens for tokeinisation.
std::string elementtype_
Records type of ellement during expat parse.
std::string elementname_
Records element name during expat parse.
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
The trules object contains regular expression and lookup tables.
Example of a regex which finds items like 39°
  <regex name="int_degree">
      <exp>
          <![CDATA[^([0-9]+)(°)$]]>
      </exp>
  </regex>
Example of a lookup table which converts telphone prefixes into the word telephone
<lookup name="telephone_prefix_table">
  <exp>
    <![CDATA[{"tel":"telephone", "telephone":"telephone", "ph":"phone", "t":"telephone", "phone":"phone"}]]>
  </exp>
</lookup>
Definition at line 71 of file txptrules.h.
Constructor & Destructor Documentation
TxpTrules()
TxpTrules () explicit
Construct without loading voice data.
Definition at line 24 of file txptrules.cc.
     : incdata_(false),
       cdata_buffer_(""),
       lkp_item_(NULL),
       lkp_open_(NULL),
       rgxwspace_(NULL),
       rgxsep_(NULL),
       rgxpunc_(NULL),
       rgxalpha_(NULL),
       rgxwspace_default_(NULL) {
 }
~TxpTrules()
~TxpTrules ()
Definition at line 36 of file txptrules.cc.
References TxpTrules::lkp_item_, TxpTrules::lkp_open_, TxpTrules::lkps_, TxpTrules::rgxs_, and TxpTrules::tokrgxs_.
                       {
   RgxMap::iterator it;
   RgxVector::iterator itv;
   LookupMapMap::iterator itmap;
   for (it = rgxs_.begin(); it != rgxs_.end(); it++) {
     pcre_free(const_cast<pcre *>(it->second));
   }
   for (itmap = lkps_.begin(); itmap != lkps_.end(); itmap++) {
     delete (itmap->second);
   }
   for (itv = tokrgxs_.begin(); itv != tokrgxs_.end(); itv++) {
     pcre_free(const_cast<pcre *>(*itv));
   }
   pcre_free(const_cast<pcre *>(lkp_item_));
   pcre_free(const_cast<pcre *>(lkp_open_));
 }
Member Function Documentation
CharHandler()
void CharHandler (const char * data, int32 len) private virtual
Inherited class for bespoke character handling.
Reimplemented from TxpXmlData.
Definition at line 290 of file txptrules.cc.
References TxpTrules::cdata_buffer_, and TxpTrules::incdata_.
{
   if (incdata_) cdata_buffer_.append(data, len);
 }
ConsumePunc()
const char * ConsumePunc (const char * input, std::string * punc)
Takes a token as input and breaks off a token delimited by punctuation This is used in tokenise to split tokens into sub tokens based on punctuation symbols.
Definition at line 162 of file txptrules.cc.
References TxpPcre::Consume(), TxpTrules::rgxpunc_, and TxpPcre::SetMatch().
Referenced by TxpTokenise::SetPuncCaseInfo().
{
   TxpPcre pcre;
   const char* p;
   p = pcre.Consume(rgxpunc_, input);
   if (p) {
     pcre.SetMatch(0, punc);
     return p;
   } else {
     return NULL;
   }
 }
ConsumeToken()
const char * ConsumeToken (const char * input, std::string * token)
Goes through a set of valid tokens and breaks off the first it finds.
Definition at line 175 of file txptrules.cc.
References TxpUtf8::Clen(), TxpPcre::Consume(), TxpPcre::SetMatch(), and TxpTrules::tokrgxs_.
Referenced by TxpTokenise::SetPuncCaseInfo().
{
   TxpPcre pcre;
   const char* p;
   TxpUtf8 utf8;
   int32 clen;
   RgxVector::iterator it;
   // go through token regexes until we match
   for(it = tokrgxs_.begin(); it != tokrgxs_.end(); it++) {
     p = pcre.Consume(*(it), input);
     if (p) {
       pcre.SetMatch(0, token);
       return p;
     }
   }
   // otherwise throw out the first character as a token
   clen = utf8.Clen(input);
   *token = std::string(input, clen);
   return input + clen;
 }
ConsumeWhitespaceToken()
const char * ConsumeWhitespaceToken (const char * input, std::string * token, std::string * wspace)
Copies a token into token, following whitespace into wspace and returns nput pointer incremented to next token.
Definition at line 112 of file txptrules.cc.
References TxpUtf8::Clen(), TxpPcre::Consume(), TxpTrules::rgxwspace_, and TxpPcre::SetMatch().
Referenced by TxpTokenise::Process().
{
   TxpPcre pcre;
   TxpUtf8 utf8;
   int32 clen;
   const char *p, *w;
   // Check for initial whitespace
   *wspace = "";
   *token = "";
   w = pcre.Consume(rgxwspace_, input);
   if (w) {
     pcre.SetMatch(0, wspace);
     return w;
   }
   // Go through utf8 chars until we find whitespace
   p = input;
   while (*p) {
     clen = utf8.Clen(p);
     token->append(p, clen);
     // increment to next char
     p += clen;
     w = pcre.Consume(rgxwspace_, p);
     if (w) {
       pcre.SetMatch(0, wspace);
       return w;
     }
   }
   return p;
 }
EndCData()
void EndCData () private virtual
Inherited class for bespoke start cdata handling.
Reimplemented from TxpXmlData.
Definition at line 264 of file txptrules.cc.
References TxpTrules::cdata_buffer_, TxpTrules::elementname_, TxpTrules::elementtype_, TxpTrules::incdata_, TxpTrules::lkps_, TxpTrules::MakeLkp(), TxpTrules::rgxs_, and TxpTrules::tokrgxs_.
{
   const char* error;
   int erroffset;
   incdata_ = false;
   RgxMap::iterator it;
   if (elementtype_ == "lookup") {
     MakeLkp(&lkps_, elementname_, cdata_buffer_);
   } else if (elementtype_ == "regex") {
     if (elementname_.find("token", 0) == 0) {
       tokrgxs_.push_back(pcre_compile(cdata_buffer_.c_str(),
                                       PCRE_UTF8, &error,
                                       &erroffset, NULL));
     } else {
       // if already present replace
       it = rgxs_.find(elementname_);
       if (it != rgxs_.end()) {
         pcre_free(const_cast<pcre *>(it->second));
         rgxs_.erase(it);
       }
       rgxs_.insert(RgxItem(elementname_, pcre_compile(cdata_buffer_.c_str(),
                                                       PCRE_UTF8, &error,
                                                       &erroffset, NULL)));
     }
   }
 }
EndElement()
void EndElement (const char * name) private virtual
Inherited class for bespoke end element handling.
Reimplemented from TxpXmlData.
Definition at line 255 of file txptrules.cc.
{
 }
GetRgx()
const pcre * GetRgx (const std::string & name)
Given a regular expresison name return the pcre regex.
Definition at line 102 of file txptrules.cc.
References TxpTrules::rgxs_.
Referenced by TxpTrules::NormCaseCharacter(), and TxpTrules::Parse().
{
   RgxMap::iterator it;
   it = rgxs_.find(name);
   if (it != rgxs_.end())
     return it->second;
   else
     return NULL;
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & name)
Set up hard coded regular expressions and lookups.
Definition at line 53 of file txptrules.cc.
References TxpPcre::Compile(), TxpXmlData::Init(), TxpTrules::lkp_item_, TxpTrules::lkp_open_, TxpTrules::lkps_, TxpTrules::MakeLkp(), and TxpTrules::rgxs_.
Referenced by TxpTokenise::Init().
{
   TxpPcre pcre;
   TxpXmlData::Init(opts, "trules", name);
   lkp_item_ = pcre.Compile("[\n\\s]*(u?[\\'\\\"](.*?)[\\'\\\"]\\s*:\\s*u?[\\'\\\"](.*?)[\\'\\\"])[\n\\s]*[,}][\n\\s]*");// NOLINT
   lkp_open_ = pcre.Compile("[\n\\s]*{");
   rgxs_.insert(RgxItem("whitespace", pcre.Compile("^([ \n\t\r]+)")));
   rgxs_.insert(RgxItem("punctuation", pcre.Compile("^([\\(\\)\\[\\]\\{\\}\\\"'!\\?\\.,;:\\|]*)(.*?)([\\(\\)\\[\\]\\{\\}\\\"'!\\?\\.,;:\\|]*)$")));
   rgxs_.insert(RgxItem("alpha", pcre.Compile("^[a-zA-Z_']+$")));
   MakeLkp(&lkps_, "downcase", "{\"A\":\"a\", \"B\":\"b\", \"C\":\"c\", \"D\":\"d\", \"E\":\"e\", \"F\":\"f\", \"G\":\"g\", \"H\":\"h\", \"I\":\"i\", \"J\":\"j\", \"K\":\"k\", \"L\":\"l\", \"M\":\"m\", \"N\":\"n\", \"O\":\"o\", \"P\":\"p\", \"Q\":\"q\", \"R\":\"r\", \"S\":\"s\", \"T\":\"t\", \"U\":\"u\", \"V\":\"v\", \"W\":\"w\", \"X\":\"x\", \"Y\":\"y\", \"Z\":\"z\"}");// NOLINT
   MakeLkp(&lkps_, "convertillegal", "{\"À\":\"A\", \"Á\":\"A\", \"Â\":\"A\", \"Ã\":\"A\", \"Å\":\"A\", \"Æ\":\"AE\", \"à\":\"a\", \"á\":\"a\", \"â\":\"a\", \"ã\":\"a\", \"å\":\"a\", \"æ\":\"ae\", \"Ç\":\"C\", \"ç\":\"c\", \"È\":\"E\", \"É\":\"E\", \"Ê\":\"E\", \"Ë\":\"E\", \"è\":\"e\", \"é\":\"e\", \"ê\":\"e\", \"ë\":\"e\", \"Ì\":\"I\", \"Í\":\"I\", \"Î\":\"I\", \"Ï\":\"I\", \"ì\":\"i\", \"í\":\"i\", \"î\":\"i\", \"ï\":\"i\", \"Ñ\":\"N\", \"ñ\":\"n\", \"Ò\":\"O\", \"Ó\":\"O\", \"Ô\":\"O\", \"Õ\":\"O\", \"Ø\":\"O\", \"ò\":\"o\", \"ó\":\"o\", \"ô\":\"o\", \"õ\":\"o\", \"ø\":\"o\", \"Ù\":\"U\", \"Ú\":\"U\", \"Û\":\"U\", \"Ű\":u\"Ü\", \"ù\":\"u\", \"ú\":\"u\", \"û\":\"u\", \"ű\":u\"ü\", \"Ý\":\"Y\", \"ý\":\"y\"}");// NOLINT
   MakeLkp(&lkps_, "utfpunc2ascii", "{\"‘\":\"'\", \"’\":\"'\", \"‛\":\"'\", '“':'\"', '”':'\"',\"΄\":\"'\", \"´\":\"'\", \"`\":\"'\", \"…\":\".\", \"„\":'\"', '–':'-', '–':'-', '–':'-', '—':'-', \"＇\":\"'\"}");// NOLINT
 }
IsAlpha()
bool IsAlpha (const std::string & token)
True if token is only standard lexicon characters (i.e. English a-z)
Definition at line 241 of file txptrules.cc.
References TxpPcre::Execute(), and TxpTrules::rgxalpha_.
{
   TxpPcre pcre;
   if (pcre.Execute(rgxalpha_, token.c_str())) return true;
   return false;
 }
Lkp()
const std::string * Lkp (const std::string & name, const std::string & key)
Given a lookup table name and a key return the value as a std::string pointer.
Definition at line 88 of file txptrules.cc.
References TxpTrules::lkps_.
Referenced by TxpTrules::NormCaseCharacter(), and TxpTrules::ReplaceUtf8Punc().
{
   std::string namekey;
   LookupMapMap::iterator itmap;
   LookupMap::iterator it, tmp;
   itmap = lkps_.find(name);
   if (itmap != lkps_.end()) {
     it = (itmap->second)->find(key);
     if (it != (itmap->second)->end()) return &(it->second);
     else return NULL;
   }
   return NULL;
 }
MakeLkp()
int32 MakeLkp (LookupMapMap * lkps, const std::string & name, const std::string & cdata) private
Parses the lookup format in the cdata into a map and adds it to lkps.
Definition at line 295 of file txptrules.cc.
References TxpPcre::Consume(), TxpTrules::lkp_item_, TxpTrules::lkp_open_, and TxpPcre::SetMatch().
Referenced by TxpTrules::EndCData(), and TxpTrules::Init().
{
   TxpPcre pcre;
   int32 pplen;
   std::string key;
   std::string val;
   std::string tmp;
   const char* pp, *npp;
   LookupMapMap::iterator itmap;
   // see if we have already created the LookupMap
   itmap = lkps->find(name);
   if (itmap != lkps->end()) {
     // if so delete it and replace with the new one
     delete (itmap->second);
     lkps->erase(itmap);
   }
   // add a new lookup table
   lkps->insert(LookupMapItem(name, new LookupMap));
   itmap = lkps->find(name);
   pp = cdata.c_str();
   pplen = cdata.length();
   // consume opening {
   pp = pcre.Consume(lkp_open_, pp, pplen);
   // no bracket! ignore
   if (!pp) pp = cdata.c_str();
   while (*pp) {
     npp = pcre.Consume(lkp_item_, pp, pplen);
     if (npp) {
       pcre.SetMatch(1, &key);
       pcre.SetMatch(2, &val);
       (itmap->second)->insert(LookupItem(key, val));
       pplen -= npp - pp;
       pp = npp;
     } else {
       return false;
     }
   }
   return true;
 }
NormCaseCharacter()
void NormCaseCharacter (std::string * norm, TxpTrulesCaseInfo & caseinfo)
Replaces characters which are not in the languages lexicon into equivilents.
Downcases upper case and sets case information structure
Definition at line 197 of file txptrules.cc.
References TxpTrulesCaseInfo::capitalised, TxpUtf8::Clen(), TxpPcre::Execute(), TxpTrulesCaseInfo::foreign, TxpTrules::GetRgx(), rnnlm::j, TxpTrules::Lkp(), TxpTrulesCaseInfo::lowercase, TxpTrulesCaseInfo::symbols, and TxpTrulesCaseInfo::uppercase.
Referenced by TxpTokenise::SetPuncCaseInfo().
{
   const char* p;
   const std::string* r;
   std::string c;
   std::string result;
   int32 clen, j = 0;
   bool alpha;
   TxpUtf8 utf8;
   TxpPcre pcre;
   p = norm->c_str();
   while (*p) {
     alpha = false;
     clen = utf8.Clen(p);
     c = std::string(p, clen);
     if (pcre.Execute(GetRgx(std::string("alpha")), c)) {
       alpha = true;
       caseinfo.lowercase = true;
     }
     r = Lkp(std::string("convertillegal"), c);
     if (r) {
       c = *r;
       caseinfo.foreign = true;
       alpha = true;
     }
     r = Lkp(std::string("downcase"), c);
     if (r) {
       caseinfo.uppercase = true;
       alpha = true;
       c = *r;
     }
     if (r && j > 0) caseinfo.capitalised = false;
     if (!r && j == 0) caseinfo.capitalised = false;
     if (!alpha) {
       caseinfo.symbols = true;
       caseinfo.capitalised = false;
     }
     result.append(c);
     p += clen;
     j += 1;
   }
   *norm = result;
 }
Parse()
bool Parse (const std::string & tpdb)
Checks to see what regexs have been found to determine whether to use hard coded defaults.
Definition at line 68 of file txptrules.cc.
References TxpPcre::Compile(), TxpTrules::GetRgx(), KALDI_WARN, TxpXmlData::Parse(), TxpTrules::rgxalpha_, TxpTrules::rgxpunc_, TxpTrules::rgxwspace_, and TxpTrules::tokrgxs_.
Referenced by TxpTokenise::Init().
{
   TxpPcre pcre_funcs;
   const pcre* rgx;
   bool r;
   r = TxpXmlData::Parse(tpdb);
   if (r) {
     rgx = GetRgx("whitespace");
     if (rgx) rgxwspace_ = rgx;
     rgx = GetRgx("punctuation");
     if (rgx) rgxpunc_ = rgx;
     rgx = GetRgx("alpha");
     if (rgx) rgxalpha_ = rgx;
     // default to tokenising on whitespace only
     tokrgxs_.push_back(pcre_funcs.Compile("^(.*)"));
  } else {
     KALDI_WARN << "Error reading normaliser rule file: " << tpdb;
   }
   return r;
 }
ReplaceUtf8Punc()
void ReplaceUtf8Punc (const std::string & tkin, std::string * tkout)
Replace non-ascii punctuation with an ascii equivilent.
Definition at line 143 of file txptrules.cc.
References TxpUtf8::Clen(), and TxpTrules::Lkp().
Referenced by TxpTokenise::Process().
{
   const char* p;
   const std::string* r;
   TxpUtf8 utf8;
   int32 clen;
   p = tkin.c_str();
   *tkout = "";
   while (*p) {
     clen = utf8.Clen(p);
     r = Lkp(std::string("utfpunc2ascii"), std::string(p, clen));
     if (r)
       tkout->append(*r);
     else
       tkout->append(p, clen);
     p += clen;
   }
 }
StartCData()
void StartCData () private virtual
Inherited class for bespoke start cdata handling.
Reimplemented from TxpXmlData.
Definition at line 258 of file txptrules.cc.
References TxpTrules::cdata_buffer_, and TxpTrules::incdata_.
{
   cdata_buffer_.clear();
   incdata_ = true;
 }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 247 of file txptrules.cc.
References TxpTrules::elementname_, TxpTrules::elementtype_, and TxpXmlData::SetAttribute().
{
   // save name and type for procesing cdata
   if (!strcmp(name, "lookup") || !strcmp(name, "regex")) {
     elementtype_ = name;
     SetAttribute("name", atts, &elementname_);
   }
 }
Member Data Documentation
cdata_buffer_
std::string cdata_buffer_ private
Buffer for cdata data.
Definition at line 120 of file txptrules.h.
Referenced by TxpTrules::CharHandler(), TxpTrules::EndCData(), and TxpTrules::StartCData().
elementname_
std::string elementname_ private
Records element name during expat parse.
Definition at line 147 of file txptrules.h.
Referenced by TxpTrules::EndCData(), and TxpTrules::StartElement().
elementtype_
std::string elementtype_ private
Records type of ellement during expat parse.
Definition at line 145 of file txptrules.h.
Referenced by TxpTrules::EndCData(), and TxpTrules::StartElement().
incdata_
bool incdata_ private
Parser status currently in cdata element.
Definition at line 118 of file txptrules.h.
Referenced by TxpTrules::CharHandler(), TxpTrules::EndCData(), and TxpTrules::StartCData().
lkp_item_
const pcre* lkp_item_ private
Regex to find a lookup item.
Definition at line 122 of file txptrules.h.
Referenced by TxpTrules::Init(), TxpTrules::MakeLkp(), and TxpTrules::~TxpTrules().
lkp_open_
const pcre* lkp_open_ private
Regex to find start of lookup.
Definition at line 124 of file txptrules.h.
Referenced by TxpTrules::Init(), TxpTrules::MakeLkp(), and TxpTrules::~TxpTrules().
lkps_
LookupMapMap lkps_ private
Map of lookup tables in tpdb file.
Definition at line 139 of file txptrules.h.
Referenced by TxpTrules::EndCData(), TxpTrules::Init(), TxpTrules::Lkp(), and TxpTrules::~TxpTrules().
rgxalpha_
const pcre* rgxalpha_ private
Regex for finding lexicon valid character (e.g. English a-z)
Definition at line 134 of file txptrules.h.
Referenced by TxpTrules::IsAlpha(), and TxpTrules::Parse().
rgxpunc_
const pcre* rgxpunc_ private
Regex for finding punctuation symbols.
Definition at line 132 of file txptrules.h.
Referenced by TxpTrules::ConsumePunc(), and TxpTrules::Parse().
rgxs_
RgxMap rgxs_ private
Map of Regexes in tpdb file.
Definition at line 141 of file txptrules.h.
Referenced by TxpTrules::EndCData(), TxpTrules::GetRgx(), TxpTrules::Init(), and TxpTrules::~TxpTrules().
rgxsep_
const pcre* rgxsep_ private
Regex for finding individual symbols that separate tokens.
Definition at line 130 of file txptrules.h.
rgxwspace_
const pcre* rgxwspace_ private
Regex for finding whitespace.
Definition at line 128 of file txptrules.h.
Referenced by TxpTrules::ConsumeWhitespaceToken(), and TxpTrules::Parse().
rgxwspace_default_
const pcre* rgxwspace_default_ private
Regex for finding whitespace.
Definition at line 137 of file txptrules.h.
tokrgxs_
RgxVector tokrgxs_ private
List of valid tokens for tokeinisation.
Definition at line 143 of file txptrules.h.
Referenced by TxpTrules::ConsumeToken(), TxpTrules::EndCData(), TxpTrules::Parse(), and TxpTrules::~TxpTrules().
The documentation for this class was generated from the following files:
idlaktxp/txptrules.h
idlaktxp/txptrules.cc