Kaldi: PerElementOffsetComponent Class Reference
PerElementOffsetComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
PerElementOffsetComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
PerElementOffsetComponent (const PerElementOffsetComponent &other)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
virtual void FreezeNaturalGradient (bool freeze)
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Member Functions
const PerElementOffsetComponent & operator= (const PerElementOffsetComponent &other)
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes
CuVector< BaseFloat > offsets_
int32 dim_
bool use_natural_gradient_
OnlineNaturalGradient preconditioner_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 1615 of file nnet-simple-component.h.
Constructor & Destructor Documentation
PerElementOffsetComponent() [1/2]
PerElementOffsetComponent () inline
Definition at line 1623 of file nnet-simple-component.h.
Referenced by PerElementOffsetComponent::Copy().
 { } // use Init to really initialize.
PerElementOffsetComponent() [2/2]
PerElementOffsetComponent (const PerElementOffsetComponent & other) explicit
Definition at line 2116 of file nnet-simple-component.cc.
                                                :
     UpdatableComponent(component),
     offsets_(component.offsets_),
     dim_(component.dim_),
     use_natural_gradient_(component.use_natural_gradient_),
     preconditioner_(component.preconditioner_) { }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 2108 of file nnet-simple-component.cc.
References KALDI_ASSERT, and PerElementOffsetComponent::offsets_.
{
   const PerElementOffsetComponent *other =
       dynamic_cast<const PerElementOffsetComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   offsets_.AddVec(alpha, other->offsets_);
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 2210 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::Data(), PerElementOffsetComponent::dim_, UpdatableComponent::is_gradient_, KALDI_ASSERT, KALDI_LOG, UpdatableComponent::learning_rate_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), PerElementOffsetComponent::offsets_, OnlineNaturalGradient::PreconditionDirections(), PerElementOffsetComponent::preconditioner_, CuMatrixBase< Real >::Stride(), and PerElementOffsetComponent::use_natural_gradient_.
{
   PerElementOffsetComponent *to_update =
       dynamic_cast<PerElementOffsetComponent*>(to_update_in);
   if (in_deriv && in_deriv->Data() != out_deriv.Data()) {
     // Propagate the derivative back to the input.
     in_deriv->CopyFromMat(out_deriv);
   }
   if (to_update != NULL) {
     // we may have to reshape out_deriv, if "block-dim" was set
     // in the config file when initializing the object, leading
     // to dim_ being a multiple >1 of offset_.Dim().
     // To avoid having separate code paths we create a sub-matrix
     // in any case, but this may just be a copy of out_deriv.
     int32 block_dim = offsets_.Dim(), multiple = dim_ / block_dim,
         block_stride = (multiple == 1 ? out_deriv.Stride() : block_dim),
         num_rows = out_deriv.NumRows() * multiple;
     KALDI_ASSERT(multiple == 1 || out_deriv.Stride() == out_deriv.NumCols());
     CuSubMatrix<BaseFloat> out_deriv_reshaped(out_deriv.Data(), num_rows,
                                               block_dim, block_stride);
     if (!to_update->use_natural_gradient_ || to_update->is_gradient_) {
       KALDI_LOG << "Using non-NG update, lr = " << to_update->learning_rate_;
       to_update->offsets_.AddRowSumMat(to_update->learning_rate_,
                                        out_deriv_reshaped);
     } else {
       KALDI_LOG << "Using NG update, lr = " << to_update->learning_rate_;
       // make a copy as we don't want to modify the data of 'out_deriv', which
       // was const (even though CuSubMatrix does not respect const-ness in
       // this scenario)
       CuMatrix<BaseFloat> out_deriv_copy(out_deriv_reshaped);
       BaseFloat scale = 1.0;
       to_update->preconditioner_.PreconditionDirections(&out_deriv_copy,
                                                         &scale);
       to_update->offsets_.AddRowSumMat(scale * to_update->learning_rate_,
                                        out_deriv_copy);
     }
   }
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 2142 of file nnet-simple-component.cc.
References PerElementOffsetComponent::PerElementOffsetComponent().
{
   return new PerElementOffsetComponent(*this);
 }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 2146 of file nnet-simple-component.cc.
References PerElementOffsetComponent::offsets_, and kaldi::VecVec().
{
   const PerElementOffsetComponent *other =
       dynamic_cast<const PerElementOffsetComponent*>(&other_in);
   return VecVec(offsets_, other->offsets_);
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 2130 of file nnet-simple-component.cc.
References UpdatableComponent::Info(), PerElementOffsetComponent::offsets_, kaldi::nnet3::PrintParameterStats(), and PerElementOffsetComponent::use_natural_gradient_.
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info()
          << ", offsets-min=" << offsets_.Min()
          << ", offsets-max=" << offsets_.Max()
          << ", block-dim=" << offsets_.Dim()
          << ", use-natural-gradient="
          << (use_natural_gradient_ ? "true" : "false");
   PrintParameterStats(stream, "offsets", offsets_, true);
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 2154 of file nnet-simple-component.cc.
References PerElementOffsetComponent::dim_, ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), UpdatableComponent::InitLearningRatesFromConfig(), KALDI_ERR, PerElementOffsetComponent::offsets_, PerElementOffsetComponent::preconditioner_, kaldi::ReadKaldiObject(), OnlineNaturalGradient::SetRank(), OnlineNaturalGradient::SetUpdatePeriod(), ConfigLine::UnusedValues(), and PerElementOffsetComponent::use_natural_gradient_.
{
   std::string vector_filename;
   InitLearningRatesFromConfig(cfl);
   if (cfl->GetValue("vector", &vector_filename)) {
     ReadKaldiObject(vector_filename, &offsets_);
     dim_ = offsets_.Dim();  // if dim is not supplied, it defaults to this.
     cfl->GetValue("dim", &dim_);
     if (dim_ <= 0 || offsets_.Dim() % dim_ != 0)
       KALDI_ERR << "Invalid dimension dim=" << dim_;
   } else {
     if(!cfl->GetValue("dim", &dim_))
       KALDI_ERR << "'dim' not provided in the config line.";
     if (dim_ <= 0)
       KALDI_ERR << "Invalid dimension dim=" << dim_;
     BaseFloat param_mean = 0.0, param_stddev = 0.0;
     cfl->GetValue("param-mean", &param_mean);
     cfl->GetValue("param-stddev", &param_stddev);
     int32 block_dim = dim_;
     cfl->GetValue("block-dim", &block_dim);
     if (block_dim <= 0 || dim_ % block_dim !=  0)
       KALDI_ERR << "Invalid value block-dim=" << block_dim;
     offsets_.Resize(block_dim);
     offsets_.SetRandn();
     offsets_.Scale(param_stddev);
     offsets_.Add(param_mean);
   }
   use_natural_gradient_ = true;
   cfl->GetValue("use-natural-gradient", &use_natural_gradient_);
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   // For now you can't modify these defaults of the natural gradient.
   // This code must be kept in sync with the code in Read().
   preconditioner_.SetRank(20);
   preconditioner_.SetUpdatePeriod(4);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1617 of file nnet-simple-component.h.
 { return dim_; }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 2295 of file nnet-simple-component.cc.
References PerElementOffsetComponent::offsets_.
{
   return offsets_.Dim();
 }
operator=()
const PerElementOffsetComponent& operator= (const PerElementOffsetComponent & other) protected
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1618 of file nnet-simple-component.h.
References Component::Info(), and PnormComponent::InitFromConfig().
 { return dim_; }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 2124 of file nnet-simple-component.cc.
References kaldi::kUndefined, PerElementOffsetComponent::offsets_, and CuVectorBase< Real >::SetRandn().
{
   CuVector<BaseFloat> temp_offsets(offsets_.Dim(), kUndefined);
   temp_offsets.SetRandn();
   offsets_.AddVec(stddev, temp_offsets);
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 2191 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddVecToRows(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::Data(), PerElementOffsetComponent::dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), PerElementOffsetComponent::offsets_, and CuMatrixBase< Real >::Stride().
{
   if (in.Data() != out->Data())
     out->CopyFromMat(in);
   if (dim_ == offsets_.Dim()) {
     out->AddVecToRows(1.0, offsets_);
   } else {
     KALDI_ASSERT(out->Stride() == out->NumCols());
     int32 block_dim = offsets_.Dim(), multiple = dim_ / block_dim,
         num_rows = out->NumRows() * multiple;
     CuSubMatrix<BaseFloat> out_rearranged(out->Data(), num_rows,
                                           block_dim, block_dim);
     out_rearranged.AddVecToRows(1.0, offsets_);
   }
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1625 of file nnet-simple-component.h.
References Component::Add(), PnormComponent::Backprop(), PnormComponent::Copy(), kaldi::nnet3::DotProduct(), kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kOutputContiguous, kaldi::nnet3::kPropagateInPlace, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kUpdatableComponent, kaldi::nnet3::NumParameters(), kaldi::nnet3::PerturbParams(), PnormComponent::Propagate(), PnormComponent::Read(), Component::Scale(), and PnormComponent::Write().
{
     return kSimpleComponent|kUpdatableComponent|
            kBackpropInPlace|kPropagateInPlace|
         (dim_ != offsets_.Dim() ? kOutputContiguous : 0);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 2258 of file nnet-simple-component.cc.
References PerElementOffsetComponent::dim_, kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, PerElementOffsetComponent::offsets_, kaldi::PeekToken(), PerElementOffsetComponent::preconditioner_, kaldi::ReadBasicType(), UpdatableComponent::ReadUpdatableCommon(), OnlineNaturalGradient::SetRank(), OnlineNaturalGradient::SetUpdatePeriod(), and PerElementOffsetComponent::use_natural_gradient_.
{
   ReadUpdatableCommon(is, binary);  // Read opening tag and learning rate
   ExpectToken(is, binary, "<Offsets>");
   offsets_.Read(is, binary);
   if (PeekToken(is, binary) == 'I') {
     // for back compatibility; we don't write this here any
     // more as it's written and read in Write/ReadUpdatableCommon
     ExpectToken(is, binary, "<IsGradient>");
     ReadBasicType(is, binary, &is_gradient_);
   }
   if (PeekToken(is, binary) != '/') {
     ExpectToken(is, binary, "<Dim>");
     ReadBasicType(is, binary, &dim_);
     ExpectToken(is, binary, "<UseNaturalGradient>");
     ReadBasicType(is, binary, &use_natural_gradient_);
   } else {
     dim_ = offsets_.Dim();
     use_natural_gradient_ = true;
   }
   // For now you can't modify these defaults of the natural gradient.
   // This code must be kept in sync with the code in InitFromConfig().
   preconditioner_.SetRank(20);
   preconditioner_.SetUpdatePeriod(4);
   ExpectToken(is, binary, "</PerElementOffsetComponent>");
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 2099 of file nnet-simple-component.cc.
{
   if (scale == 0.0) {
     offsets_.SetZero();
   } else {
     offsets_.Scale(scale);
   }
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 1624 of file nnet-simple-component.h.
 { return "PerElementOffsetComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 2303 of file nnet-simple-component.cc.
References PerElementOffsetComponent::offsets_.
{
   offsets_.CopyFromVec(params);
 }
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 2299 of file nnet-simple-component.cc.
References VectorBase< Real >::CopyFromVec(), and PerElementOffsetComponent::offsets_.
{
   params->CopyFromVec(offsets_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 2284 of file nnet-simple-component.cc.
References PerElementOffsetComponent::dim_, PerElementOffsetComponent::offsets_, PerElementOffsetComponent::use_natural_gradient_, kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate
   WriteToken(os, binary, "<Offsets>");
   offsets_.Write(os, binary);
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<UseNaturalGradient>");
   WriteBasicType(os, binary, use_natural_gradient_);
   WriteToken(os, binary, "</PerElementOffsetComponent>");
 }
Member Data Documentation
dim_
int32 dim_ protected
Definition at line 1666 of file nnet-simple-component.h.
Referenced by PerElementOffsetComponent::Backprop(), ScaleAndOffsetComponent::Info(), PerElementOffsetComponent::InitFromConfig(), ScaleAndOffsetComponent::InitFromConfig(), PerElementOffsetComponent::Propagate(), PerElementOffsetComponent::Read(), ScaleAndOffsetComponent::Read(), PerElementOffsetComponent::Write(), and ScaleAndOffsetComponent::Write().
offsets_
CuVector<BaseFloat> offsets_ protected
Definition at line 1662 of file nnet-simple-component.h.
Referenced by PerElementOffsetComponent::Add(), ScaleAndOffsetComponent::Add(), PerElementOffsetComponent::Backprop(), PerElementOffsetComponent::DotProduct(), PerElementOffsetComponent::Info(), ScaleAndOffsetComponent::Info(), PerElementOffsetComponent::InitFromConfig(), ScaleAndOffsetComponent::InitFromConfig(), PerElementOffsetComponent::NumParameters(), PerElementOffsetComponent::PerturbParams(), PerElementOffsetComponent::Propagate(), PerElementOffsetComponent::Read(), ScaleAndOffsetComponent::Read(), ScaleAndOffsetComponent::Scale(), PerElementOffsetComponent::UnVectorize(), PerElementOffsetComponent::Vectorize(), PerElementOffsetComponent::Write(), and ScaleAndOffsetComponent::Write().
preconditioner_
OnlineNaturalGradient preconditioner_ protected
Definition at line 1668 of file nnet-simple-component.h.
Referenced by PerElementOffsetComponent::Backprop(), PerElementOffsetComponent::InitFromConfig(), and PerElementOffsetComponent::Read().
use_natural_gradient_
bool use_natural_gradient_ protected
Definition at line 1667 of file nnet-simple-component.h.
Referenced by PerElementOffsetComponent::Backprop(), PerElementOffsetComponent::Info(), PerElementOffsetComponent::InitFromConfig(), ScaleAndOffsetComponent::InitFromConfig(), PerElementOffsetComponent::Read(), ScaleAndOffsetComponent::Read(), PerElementOffsetComponent::Write(), and ScaleAndOffsetComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc