Kaldi: DiscriminativeExamplesRepository Class Reference
DiscriminativeExamplesRepository Class Reference
This struct stores neural net training examples to be used in multi-threaded training.
Public Member Functions
void AcceptExample (const DiscriminativeNnetExample &example)
The following function is called by the code that reads in the examples.
void ExamplesDone ()
The following function is called by the code that reads in the examples, when we're done reading examples; it signals this way to this class that the stream is now empty.
DiscriminativeNnetExample * ProvideExample ()
This function is called by the code that does the training.
DiscriminativeExamplesRepository ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DiscriminativeExamplesRepository)
Private Attributes
int32 buffer_size_
Semaphore full_semaphore_
Semaphore empty_semaphore_
std::mutex examples_mutex_
std::deque< DiscriminativeNnetExample * > examples_
bool done_
Detailed Description
This struct stores neural net training examples to be used in multi-threaded training.
Definition at line 33 of file nnet-compute-discriminative-parallel.cc.
Constructor & Destructor Documentation
DiscriminativeExamplesRepository()
DiscriminativeExamplesRepository () inline
Definition at line 49 of file nnet-compute-discriminative-parallel.cc.
                                     : buffer_size_(4),
                                       empty_semaphore_(buffer_size_),
                                       done_(false) { }
Member Function Documentation
AcceptExample()
void AcceptExample (const DiscriminativeNnetExample & example)
The following function is called by the code that reads in the examples.
Definition at line 64 of file nnet-compute-discriminative-parallel.cc.
References DiscriminativeExamplesRepository::empty_semaphore_, DiscriminativeExamplesRepository::examples_, DiscriminativeExamplesRepository::examples_mutex_, DiscriminativeExamplesRepository::full_semaphore_, Semaphore::Signal(), and Semaphore::Wait().
Referenced by kaldi::nnet2::NnetDiscriminativeUpdateParallel().
{
   empty_semaphore_.Wait();
   examples_mutex_.lock();
   examples_.push_back(new DiscriminativeNnetExample(example));
   examples_mutex_.unlock();
   full_semaphore_.Signal();
 }
ExamplesDone()
void ExamplesDone ()
The following function is called by the code that reads in the examples, when we're done reading examples; it signals this way to this class that the stream is now empty.
Definition at line 73 of file nnet-compute-discriminative-parallel.cc.
References DiscriminativeExamplesRepository::buffer_size_, DiscriminativeExamplesRepository::done_, DiscriminativeExamplesRepository::empty_semaphore_, DiscriminativeExamplesRepository::examples_, DiscriminativeExamplesRepository::examples_mutex_, DiscriminativeExamplesRepository::full_semaphore_, rnnlm::i, KALDI_ASSERT, Semaphore::Signal(), and Semaphore::Wait().
Referenced by kaldi::nnet2::NnetDiscriminativeUpdateParallel().
{
   for (int32 i = 0; i < buffer_size_; i++)
     empty_semaphore_.Wait();
   examples_mutex_.lock();
   KALDI_ASSERT(examples_.empty());
   examples_mutex_.unlock();
   done_ = true;
   full_semaphore_.Signal();
 }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (DiscriminativeExamplesRepository) private
ProvideExample()
DiscriminativeNnetExample * ProvideExample ()
This function is called by the code that does the training.
If there is an example available it will provide it, or it will sleep till one is available. It returns NULL when there are no examples left and ExamplesDone() has been called.
Definition at line 84 of file nnet-compute-discriminative-parallel.cc.
References DiscriminativeExamplesRepository::done_, DiscriminativeExamplesRepository::empty_semaphore_, DiscriminativeExamplesRepository::examples_, DiscriminativeExamplesRepository::examples_mutex_, DiscriminativeExamplesRepository::full_semaphore_, KALDI_ASSERT, Semaphore::Signal(), and Semaphore::Wait().
{
   full_semaphore_.Wait();
   if (done_) {
     KALDI_ASSERT(examples_.empty());
     full_semaphore_.Signal(); // Increment the semaphore so
     // the call by the next thread will not block.
     return NULL; // no examples to return-- all finished.
   } else {
     examples_mutex_.lock();
     KALDI_ASSERT(!examples_.empty());
     DiscriminativeNnetExample *ans = examples_.front();
     examples_.pop_front();
     examples_mutex_.unlock();
     empty_semaphore_.Signal();
     return ans;
   }
 }
Member Data Documentation
buffer_size_
int32 buffer_size_ private
Definition at line 53 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscriminativeExamplesRepository::ExamplesDone().
done_
bool done_ private
Definition at line 59 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscriminativeExamplesRepository::ExamplesDone(), and DiscriminativeExamplesRepository::ProvideExample().
empty_semaphore_
Semaphore empty_semaphore_ private
Definition at line 55 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscriminativeExamplesRepository::AcceptExample(), DiscriminativeExamplesRepository::ExamplesDone(), and DiscriminativeExamplesRepository::ProvideExample().
examples_
std::deque<DiscriminativeNnetExample*> examples_ private
Definition at line 58 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscriminativeExamplesRepository::AcceptExample(), DiscriminativeExamplesRepository::ExamplesDone(), and DiscriminativeExamplesRepository::ProvideExample().
examples_mutex_
std::mutex examples_mutex_ private
Definition at line 56 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscriminativeExamplesRepository::AcceptExample(), DiscriminativeExamplesRepository::ExamplesDone(), and DiscriminativeExamplesRepository::ProvideExample().
full_semaphore_
Semaphore full_semaphore_ private
Definition at line 54 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscriminativeExamplesRepository::AcceptExample(), DiscriminativeExamplesRepository::ExamplesDone(), and DiscriminativeExamplesRepository::ProvideExample().
The documentation for this class was generated from the following file:
nnet2/nnet-compute-discriminative-parallel.cc