Kaldi: PermuteComponent Class Reference
PermuteComponent Class Reference
PermuteComponent changes the order of the columns (i.e.
#include <nnet-simple-component.h>
Public Member Functions
PermuteComponent ()
PermuteComponent (const std::vector< int32 > &column_map)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
void Init (const std::vector< int32 > &column_map)
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual Component * Copy () const
Copies component (deep copy).
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
void ComputeReverseColumnMap ()
PermuteComponent & operator= (const PermuteComponent &other)
Private Attributes
CuArray< int32 > column_map_
CuArray< int32 > reverse_column_map_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
PermuteComponent changes the order of the columns (i.e.
the feature or activation dimensions). Output dimension i is mapped to input dimension column_map_[i], so it's like doing: for each row: for each feature/activation dimension i: output(row, i) = input(row, column_map_[i]).
The only config value it accepts is 'column-map', e.g.: column-map=0,10,1,11,...,9,19 ... which should be a permutation of a contiguous block of integers starting with 0 (i.e. something like '3,2,1,0' but not '0,4' or '0,0,2'). See the equation above for how it is used.
Definition at line 1440 of file nnet-simple-component.h.
Constructor & Destructor Documentation
PermuteComponent() [1/2]
PermuteComponent () inline
Definition at line 1442 of file nnet-simple-component.h.
 {}
PermuteComponent() [2/2]
PermuteComponent (const std::vector< int32 > & column_map) inline
Definition at line 1443 of file nnet-simple-component.h.
References PnormComponent::Init().
 { Init(column_map); }
Member Function Documentation
Add()
virtual void Add (BaseFloat alpha, const Component & other) inline virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1473 of file nnet-simple-component.h.
References Component::Info(), PnormComponent::Read(), and PnormComponent::Write().
 {}
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 4907 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyCols().
{
   in_deriv->CopyCols(out_deriv, reverse_column_map_);
 }
ComputeReverseColumnMap()
void ComputeReverseColumnMap () private
Definition at line 4878 of file nnet-simple-component.cc.
References rnnlm::i, KALDI_ASSERT, and KALDI_ERR.
{
   int32 dim = column_map_.Dim();
   KALDI_ASSERT(dim > 0);
   std::vector<int32> reverse_column_map_cpu(dim, -1),
       column_map_cpu(dim);
   column_map_.CopyToVec(&column_map_cpu);
   for (int32 i = 0; i < dim; i++) {
     int32 &dest = reverse_column_map_cpu[column_map_cpu[i]];
     if (dest != -1)
       KALDI_ERR << "Column map does not represent a permutation.";
     dest = i;
   }
   reverse_column_map_.Resize(dim);
   reverse_column_map_.CopyFromVec(reverse_column_map_cpu);
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 4894 of file nnet-simple-component.cc.
References PermuteComponent::column_map_, and PermuteComponent::reverse_column_map_.
{
   PermuteComponent *ans = new PermuteComponent();
   ans->column_map_ = column_map_;
   ans->reverse_column_map_ = reverse_column_map_;
   return ans;
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 4976 of file nnet-simple-component.cc.
References rnnlm::i, and MaxpoolingComponent::Type().
{
   std::ostringstream stream;
   stream << Type() << ", dim=" << column_map_.Dim();
   stream << " , column-map=[ ";
   std::vector<int32> column_map(column_map_.Dim());
   column_map_.CopyToVec(&column_map);
   int32 max_size = 5;
   for (size_t i = 0; i < column_map.size() && i < max_size; i++)
     stream << column_map[i] << ' ';
   if (static_cast<int32>(column_map.size()) > max_size)
     stream << "... ";
   stream << "]";
   return stream.str();
 }
Init()
void Init (const std::vector< int32 > & column_map)
Definition at line 4935 of file nnet-simple-component.cc.
References KALDI_ASSERT.
{
   KALDI_ASSERT(column_map.size() > 0);
   column_map_.CopyFromVec(column_map);
   ComputeReverseColumnMap();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 4918 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), KALDI_ERR, kaldi::SplitStringToIntegers(), MaxpoolingComponent::Type(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   bool ok = true;
   std::string column_map_str;
   ok = ok && cfl->GetValue("column-map", &column_map_str);
   std::vector<int32> column_map;
   if (!SplitStringToIntegers(column_map_str, ",", true, &column_map))
     KALDI_ERR << "Bad initializer in PermuteComponent: column-map="
               << column_map_str;
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   if (!ok)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(column_map);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1445 of file nnet-simple-component.h.
 { return column_map_.Dim(); }
operator=()
PermuteComponent& operator= (const PermuteComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1446 of file nnet-simple-component.h.
References PnormComponent::Init(), and PnormComponent::InitFromConfig().
 { return column_map_.Dim(); }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 4901 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyCols().
{
   out->CopyCols(in, column_map_);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1452 of file nnet-simple-component.h.
References kaldi::nnet3::kSimpleComponent.
{
     return kSimpleComponent;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 4941 of file nnet-simple-component.cc.
References VectorBase< Real >::Dim(), kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), rnnlm::i, Vector< Real >::Read(), and kaldi::ReadIntegerVector().
{
   ExpectOneOrTwoTokens(is, binary, "<PermuteComponent>", "<ColumnMap>");
   std::vector<int32> column_map;
   if (binary && is.peek() == 'F') {
     // back-compatibility code [temporary]
     Vector<BaseFloat> float_map;
     float_map.Read(is, binary);
     column_map.resize(float_map.Dim());
     for (int32 i = 0; i < float_map.Dim(); i++) {
       // note: casting truncates toward zero: add 0.5 to approximate rounding.
       column_map[i] = static_cast<int32>(float_map(i) + 0.5);
     }
     // the next line is a workaround for a bug in the old
     // writing code, which now causes an assert failure.  it's only
     // valid for the permutations we're currently using.  anyway all this
     // code is only temporary.
     column_map.back() = float_map.Dim() - 1;
   } else {
     ReadIntegerVector(is, binary, &column_map);
   }
   column_map_.CopyFromVec(column_map);
   ExpectToken(is, binary, "</PermuteComponent>");
   ComputeReverseColumnMap();
 }
Scale()
virtual void Scale (BaseFloat scale) inline virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1472 of file nnet-simple-component.h.
 {}
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 1450 of file nnet-simple-component.h.
 { return "PermuteComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 4966 of file nnet-simple-component.cc.
References kaldi::WriteIntegerVector(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<PermuteComponent>");
   WriteToken(os, binary, "<ColumnMap>");
   std::ostringstream buffer;
   std::vector<int32> column_map;
   column_map_.CopyToVec(&column_map);
   WriteIntegerVector(os, binary, column_map);
   WriteToken(os, binary, "</PermuteComponent>");
 }
ZeroStats()
virtual void ZeroStats () inline virtual
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Other components that store other types of statistics (e.g. regarding gradient clipping) should implement ZeroStats() also.
Reimplemented from Component.
Definition at line 1456 of file nnet-simple-component.h.
References PnormComponent::Backprop(), PnormComponent::Copy(), and PnormComponent::Propagate().
 {}
Member Data Documentation
column_map_
CuArray<int32> column_map_ private
Definition at line 1483 of file nnet-simple-component.h.
Referenced by PermuteComponent::Copy().
reverse_column_map_
CuArray<int32> reverse_column_map_ private
Definition at line 1486 of file nnet-simple-component.h.
Referenced by PermuteComponent::Copy().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc