Kaldi: SubVector< Real > Class Template Reference
SubVector< Real > Class Template Reference
%Matrix and vector classes
Represents a non-allocating general vector which can be defined as a sub-vector of higher-level vector [or as the row of a matrix].
#include <kaldi-vector.h>
Public Member Functions
SubVector (const VectorBase< Real > &t, const MatrixIndexT origin, const MatrixIndexT length)
Constructor from a Vector or SubVector.
SubVector (const PackedMatrix< Real > &M)
This constructor initializes the vector to point at the contents of this packed matrix (SpMatrix or TpMatrix).
SubVector (const SubVector &other)
Copy constructor.
SubVector (Real *data, MatrixIndexT length)
Constructor from a pointer to memory and a length.
SubVector (const MatrixBase< Real > &matrix, MatrixIndexT row)
This operation does not preserve const-ness, so be careful.
~SubVector ()
Destructor (does nothing; no pointers are owned here).
Public Member Functions inherited from VectorBase< Real >
void SetZero ()
Set vector to all zeros.
bool IsZero (Real cutoff=1.0e-06) const
Returns true if matrix is all zeros.
void Set (Real f)
Set all members of a vector to a specified value.
void SetRandn ()
Set vector to random normally-distributed noise.
void SetRandUniform ()
Sets to numbers uniformly distributed on (0,1)
MatrixIndexT RandCategorical () const
This function returns a random index into this vector, chosen with probability proportional to the corresponding element.
MatrixIndexT Dim () const
Returns the dimension of the vector.
MatrixIndexT SizeInBytes () const
Returns the size in memory of the vector, in bytes.
Real * Data ()
Returns a pointer to the start of the vector's data.
const Real * Data () const
Returns a pointer to the start of the vector's data (const).
Real operator() (MatrixIndexT i) const
Indexing operator (const).
Real & operator() (MatrixIndexT i)
Indexing operator (non-const).
SubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l)
Returns a sub-vector of a vector (a range of elements).
const SubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l) const
Returns a const sub-vector of a vector (a range of elements).
void CopyFromVec (const VectorBase< Real > &v)
Copy data from another vector (must match own size).
template<typename OtherReal >
void CopyFromPacked (const PackedMatrix< OtherReal > &M)
Copy data from a SpMatrix or TpMatrix (must match own size).
template<typename OtherReal >
void CopyFromVec (const VectorBase< OtherReal > &v)
Copy data from another vector of different type (double vs. float)
template<typename OtherReal >
void CopyFromVec (const CuVectorBase< OtherReal > &v)
Copy from CuVector. This is defined in ../cudamatrix/cu-vector.h.
void ApplyLog ()
Apply natural log to all elements.
void ApplyLogAndCopy (const VectorBase< Real > &v)
Apply natural log to another vector and put result in *this.
void ApplyExp ()
Apply exponential to each value in vector.
void ApplyAbs ()
Take absolute value of each of the elements.
void ApplyFloor (Real floor_val, MatrixIndexT *floored_count=nullptr)
Applies floor to all elements.
void ApplyCeiling (Real ceil_val, MatrixIndexT *ceiled_count=nullptr)
Applies ceiling to all elements.
MatrixIndexT ApplyFloor (const VectorBase< Real > &floor_vec)
Applies floor to all elements. Returns number of elements floored.
Real ApplySoftMax ()
Apply soft-max to vector and return normalizer (log sum of exponentials).
Real ApplyLogSoftMax ()
Applies log soft-max to vector and returns normalizer (log sum of exponentials).
void Tanh (const VectorBase< Real > &src)
Sets each element of *this to the tanh of the corresponding element of "src".
void Sigmoid (const VectorBase< Real > &src)
Sets each element of *this to the sigmoid function of the corresponding element of "src".
void ApplyPow (Real power)
Take all elements of vector to a power.
void ApplyPowAbs (Real power, bool include_sign=false)
Take the absolute value of all elements of a vector to a power.
Real Norm (Real p) const
Compute the p-th norm of the vector.
bool ApproxEqual (const VectorBase< Real > &other, float tol=0.01) const
Returns true if ((*this)-other).Norm(2.0) <= tol * (*this).Norm(2.0).
void InvertElements ()
Invert all elements.
template<typename OtherReal >
void AddVec (const Real alpha, const VectorBase< OtherReal > &v)
Add vector : *this = *this + alpha * rv (with casting between floats and doubles)
void AddVec2 (const Real alpha, const VectorBase< Real > &v)
Add vector : *this = *this + alpha * rv^2 [element-wise squaring].
template<typename OtherReal >
void AddVec2 (const Real alpha, const VectorBase< OtherReal > &v)
Add vector : *this = *this + alpha * rv^2 [element-wise squaring], with casting between floats and doubles.
void AddMatVec (const Real alpha, const MatrixBase< Real > &M, const MatrixTransposeType trans, const VectorBase< Real > &v, const Real beta)
Add matrix times vector : this <– beta*this + alpha*M*v.
void AddMatSvec (const Real alpha, const MatrixBase< Real > &M, const MatrixTransposeType trans, const VectorBase< Real > &v, const Real beta)
This is as AddMatVec, except optimized for where v contains a lot of zeros.
void AddSpVec (const Real alpha, const SpMatrix< Real > &M, const VectorBase< Real > &v, const Real beta)
Add symmetric positive definite matrix times vector: this <– beta*this + alpha*M*v.
void AddTpVec (const Real alpha, const TpMatrix< Real > &M, const MatrixTransposeType trans, const VectorBase< Real > &v, const Real beta)
Add triangular matrix times vector: this <– beta*this + alpha*M*v.
void ReplaceValue (Real orig, Real changed)
Set each element to y = (x == orig ? changed : x).
void MulElements (const VectorBase< Real > &v)
Multipy element-by-element by another vector.
template<typename OtherReal >
void MulElements (const VectorBase< OtherReal > &v)
Multipy element-by-element by another vector of different type.
void DivElements (const VectorBase< Real > &v)
Divide element-by-element by a vector.
template<typename OtherReal >
void DivElements (const VectorBase< OtherReal > &v)
Divide element-by-element by a vector of different type.
void Add (Real c)
Add a constant to each element of a vector.
void AddVecVec (Real alpha, const VectorBase< Real > &v, const VectorBase< Real > &r, Real beta)
Add element-by-element product of vectlrs:
void AddVecDivVec (Real alpha, const VectorBase< Real > &v, const VectorBase< Real > &r, Real beta)
Add element-by-element quotient of two vectors.
void Scale (Real alpha)
Multiplies all elements by this constant.
void MulTp (const TpMatrix< Real > &M, const MatrixTransposeType trans)
Multiplies this vector by lower-triangular marix: *this <– *this *M.
void Solve (const TpMatrix< Real > &M, const MatrixTransposeType trans)
If trans == kNoTrans, solves M x = b, where b is the value of *this at input and x is the value of *this at output.
void CopyRowsFromMat (const MatrixBase< Real > &M)
Performs a row stack of the matrix M.
template<typename OtherReal >
void CopyRowsFromMat (const MatrixBase< OtherReal > &M)
void CopyRowsFromMat (const CuMatrixBase< Real > &M)
The following is implemented in ../cudamatrix/cu-matrix.cc.
void CopyColsFromMat (const MatrixBase< Real > &M)
Performs a column stack of the matrix M.
void CopyRowFromMat (const MatrixBase< Real > &M, MatrixIndexT row)
Extracts a row of the matrix M.
template<typename OtherReal >
void CopyRowFromMat (const MatrixBase< OtherReal > &M, MatrixIndexT row)
Extracts a row of the matrix M with type conversion.
template<typename OtherReal >
void CopyRowFromSp (const SpMatrix< OtherReal > &S, MatrixIndexT row)
Extracts a row of the symmetric matrix S.
template<typename OtherReal >
void CopyColFromMat (const MatrixBase< OtherReal > &M, MatrixIndexT col)
Extracts a column of the matrix M.
void CopyDiagFromMat (const MatrixBase< Real > &M)
Extracts the diagonal of the matrix M.
void CopyDiagFromPacked (const PackedMatrix< Real > &M)
Extracts the diagonal of a packed matrix M; works for Sp or Tp.
void CopyDiagFromSp (const SpMatrix< Real > &M)
Extracts the diagonal of a symmetric matrix.
void CopyDiagFromTp (const TpMatrix< Real > &M)
Extracts the diagonal of a triangular matrix.
Real Max () const
Returns the maximum value of any element, or -infinity for the empty vector.
Real Max (MatrixIndexT *index) const
Returns the maximum value of any element, and the associated index.
Real Min () const
Returns the minimum value of any element, or +infinity for the empty vector.
Real Min (MatrixIndexT *index) const
Returns the minimum value of any element, and the associated index.
Real Sum () const
Returns sum of the elements.
Real SumLog () const
Returns sum of the logs of the elements.
void AddRowSumMat (Real alpha, const MatrixBase< Real > &M, Real beta=1.0)
Does *this = alpha * (sum of rows of M) + beta * *this.
void AddColSumMat (Real alpha, const MatrixBase< Real > &M, Real beta=1.0)
Does *this = alpha * (sum of columns of M) + beta * *this.
void AddDiagMat2 (Real alpha, const MatrixBase< Real > &M, MatrixTransposeType trans=kNoTrans, Real beta=1.0)
Add the diagonal of a matrix times itself: *this = diag(M M^T) + beta * *this (if trans == kNoTrans), or *this = diag(M^T M) + beta * *this (if trans == kTrans).
void AddDiagMatMat (Real alpha, const MatrixBase< Real > &M, MatrixTransposeType transM, const MatrixBase< Real > &N, MatrixTransposeType transN, Real beta=1.0)
Add the diagonal of a matrix product: *this = diag(M N), assuming the "trans" arguments are both kNoTrans; for transpose arguments, it behaves as you would expect.
Real LogSumExp (Real prune=-1.0) const
Returns log(sum(exp())) without exp overflow If prune > 0.0, ignores terms less than the max - prune.
void Read (std::istream &in, bool binary, bool add=false)
Reads from C++ stream (option to add to existing contents).
void Write (std::ostream &Out, bool binary) const
Writes to C++ stream (option to write in binary).
template<>
void AddVec (const float alpha, const VectorBase< float > &rv)
template<>
void AddVec (const double alpha, const VectorBase< double > &rv)
template<>
void AddVec (const float alpha, const VectorBase< float > &v)
template<>
void AddVec (const double alpha, const VectorBase< double > &v)
Private Member Functions
SubVector & operator= (const SubVector &other)
Disallow assignment operator.
Additional Inherited Members
Protected Member Functions inherited from VectorBase< Real >
~VectorBase ()
Destructor; does not deallocate memory, this is handled by child classes.
VectorBase ()
Empty initializer, corresponds to vector of zero size.
void CopyFromPtr (const Real *Data, MatrixIndexT sz)
Load data into the vector: sz must match own size.
KALDI_DISALLOW_COPY_AND_ASSIGN (VectorBase)
Protected Attributes inherited from VectorBase< Real >
Real * data_
data memory area
MatrixIndexT dim_
dimension of vector
Detailed Description
template<typename Real>
class kaldi::SubVector< Real >
Represents a non-allocating general vector which can be defined as a sub-vector of higher-level vector [or as the row of a matrix].
Definition at line 485 of file kaldi-vector.h.
Constructor & Destructor Documentation
SubVector() [1/5]
SubVector (const VectorBase< Real > & t, const MatrixIndexT origin, const MatrixIndexT length) inline
Constructor from a Vector or SubVector.
SubVectors are not const-safe and it's very hard to make them so for now we just give up. This function contains const_cast.
Definition at line 490 of file kaldi-vector.h.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), and KALDI_ASSERT.
                                        : VectorBase<Real>() {
     // following assert equiv to origin>=0 && length>=0 &&
     // origin+length <= rt.dim_
     KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(origin)+
                  static_cast<UnsignedMatrixIndexT>(length) <=
                  static_cast<UnsignedMatrixIndexT>(t.Dim()));
     VectorBase<Real>::data_ = const_cast<Real*> (t.Data()+origin);
     VectorBase<Real>::dim_   = length;
   }
SubVector() [2/5]
SubVector (const PackedMatrix< Real > & M) inline
This constructor initializes the vector to point at the contents of this packed matrix (SpMatrix or TpMatrix).
Definition at line 503 of file kaldi-vector.h.
References PackedMatrix< Real >::Data(), and PackedMatrix< Real >::NumRows().
{
     VectorBase<Real>::data_ = const_cast<Real*> (M.Data());
     VectorBase<Real>::dim_   = (M.NumRows()*(M.NumRows()+1))/2;
   }
SubVector() [3/5]
SubVector (const SubVector< Real > & other) inline
Copy constructor.
Definition at line 509 of file kaldi-vector.h.
References VectorBase< Real >::data_, and VectorBase< Real >::dim_.
                                     : VectorBase<Real> () {
     // this copy constructor needed for Range() to work in base class.
     VectorBase<Real>::data_ = other.data_;
     VectorBase<Real>::dim_ = other.dim_;
   }
SubVector() [4/5]
SubVector (Real * data, MatrixIndexT length) inline
Constructor from a pointer to memory and a length.
Keeps a pointer to the data but does not take ownership (will never delete).
Definition at line 517 of file kaldi-vector.h.
                                              : VectorBase<Real> () {
     VectorBase<Real>::data_ = data;
     VectorBase<Real>::dim_   = length;
   }
SubVector() [5/5]
SubVector (const MatrixBase< Real > & matrix, MatrixIndexT row) inline
This operation does not preserve const-ness, so be careful.
Definition at line 524 of file kaldi-vector.h.
References MatrixBase< Real >::NumCols(), and MatrixBase< Real >::RowData().
{
     VectorBase<Real>::data_ = const_cast<Real*>(matrix.RowData(row));
     VectorBase<Real>::dim_   = matrix.NumCols();
   }
~SubVector()
~SubVector () inline
Destructor (does nothing; no pointers are owned here).
Definition at line 529 of file kaldi-vector.h.
Member Function Documentation
operator=()
SubVector& operator= (const SubVector< Real > & other) inline private
Disallow assignment operator.
Definition at line 533 of file kaldi-vector.h.
References kaldi::operator>>().
 {}
The documentation for this class was generated from the following file:
matrix/kaldi-vector.h