Kaldi: Rescale Class Reference
Rescale Class Reference
Rescale the data column-wise by a vector (can be used for global variance normalization)
#include <nnet-various.h>
Public Member Functions
Rescale (int32 dim_in, int32 dim_out)
~Rescale ()
Component * Copy () const
Copy component (deep copy),.
ComponentType GetType () const
Get Type Identification of the component,.
void InitData (std::istream &is)
Initialize the content of the component by the 'line' from the prototype,.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters,.
void GetGradient (VectorBase< BaseFloat > *gradient) const
Get gradient reshaped as a vector,.
void GetParams (VectorBase< BaseFloat > *params) const
Get the trainable parameters reshaped as a vector,.
void SetParams (const VectorBase< BaseFloat > &params)
Set the trainable parameters from, reshaped as a vector,.
std::string Info () const
Print some additional info (after <ComponentName> and the dims),.
std::string InfoGradient () const
Print some additional info about gradient (after <...> and dims),.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters,.
void SetLearnRateCoef (BaseFloat c)
Set the learn-rate coefficient,.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters,.
virtual void SetTrainOptions (const NnetTrainOptions &opts)
Set the training options to the component,.
const NnetTrainOptions & GetTrainOptions () const
Get the training options from the component,.
virtual void SetBiasLearnRateCoef (BaseFloat val)
Set the learn-rate coefficient for bias,.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
Generic interface of a component,.
virtual ~Component ()
virtual bool IsMultistream () const
Check if component has 'Recurrent' interface (trainable and recurrent),.
int32 InputDim () const
Get the dimension of the input,.
int32 OutputDim () const
Get the dimension of the output,.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward-pass propagation 'in' -> 'out',.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
void Write (std::ostream &os, bool binary) const
Write the component to a stream,.
Protected Attributes
CuVector< BaseFloat > scale_data_
CuVector< BaseFloat > scale_data_grad_
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters,.
BaseFloat learn_rate_coef_
Scalar applied to learning rate for weight matrices (to be used in ::Update method),.
BaseFloat bias_learn_rate_coef_
Scalar applied to learning rate for bias (to be used in ::Update method),.
Protected Attributes inherited from Component
int32 input_dim_
Data members,.
int32 output_dim_
Dimension of the output of the Component,.
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjected, kBlstmProjected,
kRecurrentComponent, kActivationFunction = 0x0200, kSoftmax, kHiddenSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kParametricRelu,
kDropout, kLengthNormComponent, kTranform = 0x0400, kRbm,
kSplice, kCopy, kTranspose, kBlockLinearity,
kAddShift, kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent,
kSimpleSentenceAveragingComponent, kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent,
kMaxPooling2DComponent, kFramePoolingComponent, kParallelComponent, kMultiBasisComponent
}
Component type identification mechanism,.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Converts component type to marker,.
static ComponentType MarkerToType (const std::string &s)
Converts marker to component type (case insensitive),.
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file,.
static Component * Read (std::istream &is, bool binary)
Read the component from a stream (static method),.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Detailed Description
Rescale the data column-wise by a vector (can be used for global variance normalization)
Definition at line 404 of file nnet-various.h.
Constructor & Destructor Documentation
Rescale()
Rescale (int32 dim_in, int32 dim_out) inline
Definition at line 406 of file nnet-various.h.
                                       :
     UpdatableComponent(dim_in, dim_out),
     scale_data_(dim_in)
   { }
~Rescale()
~Rescale () inline
Definition at line 411 of file nnet-various.h.
   { }
Member Function Documentation
BackpropagateFnc()
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 486 of file nnet-various.h.
References CuMatrixBase< Real >::CopyFromMat(), and CuMatrixBase< Real >::MulColsVec().
{
     // derivatives are scaled with the scale_data_,
     in_diff->CopyFromMat(out_diff);
     in_diff->MulColsVec(scale_data_);
   }
Copy()
Component* Copy () const inline virtual
Copy component (deep copy),.
Implements Component.
Definition at line 414 of file nnet-various.h.
 { return new Rescale(*this); }
GetGradient()
void GetGradient (VectorBase< BaseFloat > * gradient) const inline virtual
Get gradient reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 452 of file nnet-various.h.
References VectorBase< Real >::Dim(), and KALDI_ASSERT.
{
     KALDI_ASSERT(gradient->Dim() == NumParams());
     scale_data_grad_.CopyToVec(gradient);
   }
GetParams()
void GetParams (VectorBase< BaseFloat > * params) const inline virtual
Get the trainable parameters reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 457 of file nnet-various.h.
References VectorBase< Real >::Dim(), and KALDI_ASSERT.
Referenced by kaldi::ConvertRescaleComponent().
{
     KALDI_ASSERT(params->Dim() == NumParams());
     scale_data_.CopyToVec(params);
   }
GetType()
ComponentType GetType () const inline virtual
Get Type Identification of the component,.
Implements Component.
Definition at line 415 of file nnet-various.h.
References Component::kRescale.
 { return kRescale; }
Info()
std::string Info () const inline virtual
Print some additional info (after <ComponentName> and the dims),.
Reimplemented from Component.
Definition at line 467 of file nnet-various.h.
References kaldi::nnet1::MomentStatistics(), and kaldi::nnet1::ToString().
{
     return std::string("\n  scale_data") +
       MomentStatistics(scale_data_) +
       ", lr-coef " + ToString(learn_rate_coef_);
   }
InfoGradient()
std::string InfoGradient () const inline virtual
Print some additional info about gradient (after <...> and dims),.
Reimplemented from Component.
Definition at line 473 of file nnet-various.h.
References kaldi::nnet1::MomentStatistics(), and kaldi::nnet1::ToString().
{
     return std::string("\n  scale_data_grad") +
       MomentStatistics(scale_data_grad_) +
       ", lr-coef " + ToString(learn_rate_coef_);
   }
InitData()
void InitData (std::istream & is) inline virtual
Initialize the content of the component by the 'line' from the prototype,.
Implements UpdatableComponent.
Definition at line 417 of file nnet-various.h.
References Component::InputDim(), KALDI_ERR, kaldi::kSetZero, kaldi::ReadBasicType(), and kaldi::ReadToken().
{
     // define options
     float init_param = 0.0;
     // parse config
     std::string token;
     while (is >> std::ws, !is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<InitParam>") ReadBasicType(is, false, &init_param);
       else if (token == "<LearnRateCoef>") ReadBasicType(is, false, &learn_rate_coef_);
       else KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                      << " (InitParam)";
     }
     // initialize
     scale_data_.Resize(InputDim(), kSetZero);
     scale_data_.Set(init_param);
   }
NumParams()
int32 NumParams () const inline virtual
Number of trainable parameters,.
Implements UpdatableComponent.
Definition at line 450 of file nnet-various.h.
Referenced by kaldi::ConvertRescaleComponent().
 { return scale_data_.Dim(); }
PropagateFnc()
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 479 of file nnet-various.h.
References CuMatrixBase< Real >::CopyFromMat(), and CuMatrixBase< Real >::MulColsVec().
{
     // copy, rescale the data,
     out->CopyFromMat(in);
     out->MulColsVec(scale_data_);
   }
ReadData()
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 434 of file nnet-various.h.
References kaldi::ExpectToken(), kaldi::Peek(), and kaldi::ReadBasicType().
{
     // optional learning-rate coef,
     if ('<' == Peek(is, binary)) {
       ExpectToken(is, binary, "<LearnRateCoef>");
       ReadBasicType(is, binary, &learn_rate_coef_);
     }
     // read the shift data
     scale_data_.Read(is, binary);
   }
SetLearnRateCoef()
void SetLearnRateCoef (BaseFloat val) inline virtual
Set the learn-rate coefficient,.
Reimplemented from UpdatableComponent.
Definition at line 508 of file nnet-various.h.
Referenced by main().
 { learn_rate_coef_ = c; }
SetParams()
void SetParams (const VectorBase< BaseFloat > & params) inline virtual
Set the trainable parameters from, reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 462 of file nnet-various.h.
References VectorBase< Real >::Dim(), and KALDI_ASSERT.
Referenced by main().
{
     KALDI_ASSERT(params.Dim() == NumParams());
     scale_data_.CopyFromVec(params);
   }
Update()
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters,.
Implements UpdatableComponent.
Definition at line 495 of file nnet-various.h.
References Component::InputDim(), kaldi::kSetZero, and CuMatrixBase< Real >::MulElements().
{
     // we use following hyperparameters from the option class,
     const BaseFloat lr = opts_.learn_rate;
     // gradient,
     scale_data_grad_.Resize(InputDim(), kSetZero);  // reset,
     CuMatrix<BaseFloat> gradient_aux(diff);
     gradient_aux.MulElements(input);
     scale_data_grad_.AddRowSumMat(1.0, gradient_aux, 0.0);
     // update,
     scale_data_.AddVec(-lr * learn_rate_coef_, scale_data_grad_);
   }
WriteData()
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 444 of file nnet-various.h.
References kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     WriteToken(os, binary, "<LearnRateCoef>");
     WriteBasicType(os, binary, learn_rate_coef_);
     scale_data_.Write(os, binary);
   }
Member Data Documentation
scale_data_
CuVector<BaseFloat> scale_data_ protected
Definition at line 511 of file nnet-various.h.
scale_data_grad_
CuVector<BaseFloat> scale_data_grad_ protected
Definition at line 512 of file nnet-various.h.
The documentation for this class was generated from the following file:
nnet/nnet-various.h