Kaldi: DecodableMatrixScaled Class Reference
DecodableMatrixScaled Class Reference
#include <decodable-matrix.h>
Public Member Functions
DecodableMatrixScaled (const Matrix< BaseFloat > &likes, BaseFloat scale)
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual BaseFloat LogLikelihood (int32 frame, int32 index)
Returns the log likelihood, which will be negated in the decoder.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableMatrixScaled)
Private Attributes
const Matrix< BaseFloat > & likes_
BaseFloat scale_
Detailed Description
Definition at line 169 of file decodable-matrix.h.
Constructor & Destructor Documentation
DecodableMatrixScaled()
DecodableMatrixScaled (const Matrix< BaseFloat > & likes, BaseFloat scale) inline
Definition at line 171 of file decodable-matrix.h.
                                         :
     likes_(likes), scale_(scale) { }
Member Function Documentation
IsLastFrame()
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frames are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). Caution: the behavior of this function in an online setting is being changed somewhat. In future it may return false in cases where we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. The plan in future is to rely more on NumFramesReady(), and in future, IsLastFrame() would always return false in an online-decoding setting, and would only return true in a decoding-from-matrix setting where we want to allow the last delta or LDA features to be flushed out for compatibility with the baseline setup.
Implements DecodableInterface.
Definition at line 177 of file decodable-matrix.h.
References KALDI_ASSERT, and DecodableMatrixScaledMapped::NumFramesReady().
{
     KALDI_ASSERT(frame < NumFramesReady());
     return (frame == NumFramesReady() - 1);
   }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableMatrixScaled) private
LogLikelihood()
virtual BaseFloat LogLikelihood (int32 frame, int32 index) inline virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Definition at line 183 of file decodable-matrix.h.
References KALDI_ERR, DecodableMatrixScaledMapped::likes_, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and DecodableMatrixScaledMapped::scale_.
{
     if (index > likes_.NumCols() || index <= 0 ||
         frame < 0 || frame >= likes_.NumRows())
       KALDI_ERR << "Invalid (frame, index - 1) = ("
                 << frame << ", " << index - 1 << ") for matrix of size "
                 << likes_.NumRows() << " x " << likes_.NumCols();
     return scale_ * likes_(frame, index - 1);
   }
NumFramesReady()
virtual int32 NumFramesReady () const inline virtual
The call NumFramesReady() will return the number of frames currently available for this decodable object.
This is for use in setups where you don't want the decoder to block while waiting for input. This is newly added as of Jan 2014, and I hope, going forward, to rely on this mechanism more than IsLastFrame to know when to stop decoding.
Reimplemented from DecodableInterface.
Definition at line 175 of file decodable-matrix.h.
References DecodableMatrixScaledMapped::likes_, and MatrixBase< Real >::NumRows().
 { return likes_.NumRows(); }
NumIndices()
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst).
Implements DecodableInterface.
Definition at line 193 of file decodable-matrix.h.
References DecodableMatrixScaledMapped::likes_, and MatrixBase< Real >::NumCols().
 { return likes_.NumCols(); }
Member Data Documentation
likes_
const Matrix<BaseFloat>& likes_ private
Definition at line 196 of file decodable-matrix.h.
scale_
BaseFloat scale_ private
Definition at line 197 of file decodable-matrix.h.
The documentation for this class was generated from the following file:
decoder/decodable-matrix.h