Kaldi: RegtreeFmllrDiagGmm Class Reference
RegtreeFmllrDiagGmm Class Reference
An FMLLR (feature-space MLLR) transformation, also called CMLLR (constrained MLLR) is an affine transformation of the feature vectors.
#include <regtree-fmllr-diag-gmm.h>
Public Member Functions
RegtreeFmllrDiagGmm ()
RegtreeFmllrDiagGmm (const RegtreeFmllrDiagGmm &other)
~RegtreeFmllrDiagGmm ()
void Init (size_t num_xforms, size_t dim)
Allocates memory for transform matrix & bias vector.
void Validate ()
Checks whether the various parameters are consistent.
void SetUnit ()
Sets transform matrix to identity and bias vector to zero.
void ComputeLogDets ()
Computes the log-determinant of the Jacobians for each transform.
void TransformFeature (const VectorBase< BaseFloat > &in, std::vector< Vector< BaseFloat > > *out) const
Get the transformed features for each of the transforms.
void Write (std::ostream &out_stream, bool binary) const
void Read (std::istream &in_stream, bool binary)
int32 Dim () const
Accessors.
int32 NumBaseClasses () const
int32 NumRegClasses () const
void GetXformMatrix (int32 xform_index, Matrix< BaseFloat > *out) const
void GetLogDets (VectorBase< BaseFloat > *out) const
int32 Base2RegClass (int32 bclass) const
void SetParameters (const MatrixBase< BaseFloat > &mat, size_t regclass)
Mutators.
void set_bclass2xforms (const std::vector< int32 > &in)
Private Member Functions
void operator= (const RegtreeFmllrDiagGmm &)
Private Attributes
int32 dim_
Dimension of feature vectors.
int32 num_xforms_
Number of transform matrices.
std::vector< Matrix< BaseFloat > > xform_matrices_
Transform matrices.
Vector< BaseFloat > logdet_
Log-determinants of the Jacobians.
bool valid_logdet_
Whether logdets are for current transforms.
std::vector< int32 > bclass2xforms_
For each baseclass index of which transform to use; -1 => no xform.
Detailed Description
An FMLLR (feature-space MLLR) transformation, also called CMLLR (constrained MLLR) is an affine transformation of the feature vectors.
This class supports multiple transforms, and a regression tree. For a single, feature-level transformation see fmllr-diag-gmm-global.h Note: the "regression classes" are the classes after tree-clustering, which are smaller in number than the "base classes" (these correspond to the leaves of the tree).
Definition at line 69 of file regtree-fmllr-diag-gmm.h.
Constructor & Destructor Documentation
RegtreeFmllrDiagGmm() [1/2]
RegtreeFmllrDiagGmm () inline
Definition at line 71 of file regtree-fmllr-diag-gmm.h.
 : dim_(-1), num_xforms_(-1), valid_logdet_(false) {}
RegtreeFmllrDiagGmm() [2/2]
RegtreeFmllrDiagGmm (const RegtreeFmllrDiagGmm & other) inline explicit
Definition at line 72 of file regtree-fmllr-diag-gmm.h.
       : dim_(other.dim_), num_xforms_(other.num_xforms_),
         xform_matrices_(other.xform_matrices_), logdet_(other.logdet_),
         valid_logdet_(other.valid_logdet_),
         bclass2xforms_(other.bclass2xforms_) {}
~RegtreeFmllrDiagGmm()
~RegtreeFmllrDiagGmm () inline
Definition at line 77 of file regtree-fmllr-diag-gmm.h.
 {}
Member Function Documentation
Base2RegClass()
int32 Base2RegClass (int32 bclass) const inline
Definition at line 97 of file regtree-fmllr-diag-gmm.h.
Referenced by DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased().
 { return bclass2xforms_[bclass]; }
ComputeLogDets()
void ComputeLogDets ()
Computes the log-determinant of the Jacobians for each transform.
Definition at line 107 of file regtree-fmllr-diag-gmm.cc.
References RegtreeFmllrDiagGmm::dim_, KALDI_ASSERT, KALDI_ISNAN, MatrixBase< Real >::LogDet(), RegtreeFmllrDiagGmm::logdet_, RegtreeFmllrDiagGmm::num_xforms_, RegtreeFmllrDiagGmm::valid_logdet_, and RegtreeFmllrDiagGmm::xform_matrices_.
Referenced by RegtreeFmllrDiagGmm::Read().
{
   logdet_.Resize(num_xforms_);
   for (int32 r = 0; r < num_xforms_; r++) {
     SubMatrix<BaseFloat> tmp_a(xform_matrices_[r], 0, dim_, 0,
                                dim_);
     logdet_(r) = tmp_a.LogDet();
     KALDI_ASSERT(!KALDI_ISNAN(logdet_(r)));
   }
   valid_logdet_ = true;
 }
Dim()
int32 Dim () const inline
Accessors.
Definition at line 92 of file regtree-fmllr-diag-gmm.h.
 { return dim_; }
GetLogDets()
void GetLogDets (VectorBase< BaseFloat > * out) const inline
Definition at line 131 of file regtree-fmllr-diag-gmm.h.
References VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), and KALDI_ASSERT.
Referenced by DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), and kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   KALDI_ASSERT(valid_logdet_ && out->Dim() == logdet_.Dim());
   out->CopyFromVec(logdet_);
 }
GetXformMatrix()
void GetXformMatrix (int32 xform_index, Matrix< BaseFloat > * out) const inline
Definition at line 115 of file regtree-fmllr-diag-gmm.h.
References MatrixBase< Real >::CopyFromMat(), KALDI_ERR, kaldi::kNoTrans, and Matrix< Real >::Resize().
{
   if (xform_index >= num_xforms_) {
     KALDI_ERR << "Index (" << xform_index << ") out of range [0, "
         << num_xforms_ << "]";
   }
   out->Resize(dim_, dim_ + 1);
   out->CopyFromMat(xform_matrices_[xform_index], kNoTrans);
 }
Init()
void Init (size_t num_xforms, size_t dim)
Allocates memory for transform matrix & bias vector.
Definition at line 31 of file regtree-fmllr-diag-gmm.cc.
References RegtreeFmllrDiagGmm::dim_, KALDI_ASSERT, RegtreeFmllrDiagGmm::logdet_, RegtreeFmllrDiagGmm::num_xforms_, RegtreeFmllrDiagGmm::valid_logdet_, and RegtreeFmllrDiagGmm::xform_matrices_.
Referenced by RegtreeFmllrDiagGmmAccs::Update().
{
   if (num_xforms == 0) {  // empty transform
     xform_matrices_.clear();
     logdet_.Resize(0);
     valid_logdet_ = false;
     dim_ = 0;  // non-zero dimension is meaningless with empty transform
     num_xforms_ = 0;
   } else {
     KALDI_ASSERT(dim != 0);  // if not empty, dim = 0 is meaningless
     dim_ = dim;
     num_xforms_ = num_xforms;
     xform_matrices_.resize(num_xforms);
     logdet_.Resize(num_xforms);
     vector< Matrix<BaseFloat> >::iterator xform_itr = xform_matrices_.begin(),
         xform_itr_end = xform_matrices_.end();
     for (; xform_itr != xform_itr_end; ++xform_itr) {
       xform_itr->Resize(dim, dim+1);
       xform_itr->SetUnit();
     }
     valid_logdet_ = true;
   }
 }
NumBaseClasses()
int32 NumBaseClasses () const inline
Definition at line 93 of file regtree-fmllr-diag-gmm.h.
Referenced by kaldi::UnitTestRegtreeFmllrDiagGmm().
 { return bclass2xforms_.size(); }
NumRegClasses()
int32 NumRegClasses () const inline
Definition at line 94 of file regtree-fmllr-diag-gmm.h.
Referenced by DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), and kaldi::UnitTestRegtreeFmllrDiagGmm().
 { return num_xforms_; }
operator=()
void operator= (const RegtreeFmllrDiagGmm &) private
Read()
void Read (std::istream & in_stream, bool binary)
Definition at line 168 of file regtree-fmllr-diag-gmm.cc.
References RegtreeFmllrDiagGmm::bclass2xforms_, RegtreeFmllrDiagGmm::ComputeLogDets(), RegtreeFmllrDiagGmm::dim_, kaldi::ExpectToken(), KALDI_ASSERT, RegtreeFmllrDiagGmm::num_xforms_, kaldi::ReadBasicType(), kaldi::ReadIntegerVector(), and RegtreeFmllrDiagGmm::xform_matrices_.
Referenced by kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   ExpectToken(in, binary, "<FMLLRXFORM>");
   ExpectToken(in, binary, "<NUMXFORMS>");
   ReadBasicType(in, binary, &num_xforms_);
   ExpectToken(in, binary, "<DIMENSION>");
   ReadBasicType(in, binary, &dim_);
   KALDI_ASSERT(num_xforms_ >= 0 && dim_ >= 0);  // can be 0 for empty xform
   xform_matrices_.resize(num_xforms_);
   vector< Matrix<BaseFloat> >::iterator xform_itr = xform_matrices_.begin(),
       xform_itr_end = xform_matrices_.end();
   for (; xform_itr != xform_itr_end; ++xform_itr) {
     ExpectToken(in, binary, "<XFORM>");
     xform_itr->Read(in, binary);
     KALDI_ASSERT(xform_itr->NumRows() == (xform_itr->NumCols() - 1)
            && xform_itr->NumRows() == dim_);
   }
   ExpectToken(in, binary, "<BCLASS2XFORMS>");
   ReadIntegerVector(in, binary, &bclass2xforms_);
   ExpectToken(in, binary, "</FMLLRXFORM>");
   ComputeLogDets();  // so that the transforms can be used.
 }
set_bclass2xforms()
void set_bclass2xforms (const std::vector< int32 > & in) inline
Definition at line 101 of file regtree-fmllr-diag-gmm.h.
Referenced by RegtreeFmllrDiagGmmAccs::Update().
 { bclass2xforms_ = in; }
SetParameters()
void SetParameters (const MatrixBase< BaseFloat > & mat, size_t regclass) inline
Mutators.
Definition at line 125 of file regtree-fmllr-diag-gmm.h.
References kaldi::kNoTrans.
Referenced by RegtreeFmllrDiagGmmAccs::Update().
{
   xform_matrices_[regclass].CopyFromMat(mat, kNoTrans);
   valid_logdet_ = false;
 }
SetUnit()
void SetUnit ()
Sets transform matrix to identity and bias vector to zero.
Definition at line 54 of file regtree-fmllr-diag-gmm.cc.
References RegtreeFmllrDiagGmm::dim_, KALDI_ASSERT, RegtreeFmllrDiagGmm::num_xforms_, and RegtreeFmllrDiagGmm::xform_matrices_.
{
   KALDI_ASSERT(num_xforms_ > 0 && dim_ > 0);
   vector< Matrix<BaseFloat> >::iterator xform_itr = xform_matrices_.begin(),
       xform_itr_end = xform_matrices_.end();
   for (; xform_itr != xform_itr_end; ++xform_itr) {
     xform_itr->SetUnit();
   }
 }
TransformFeature()
void TransformFeature (const VectorBase< BaseFloat > & in, std::vector< Vector< BaseFloat > > * out) const
Get the transformed features for each of the transforms.
Definition at line 118 of file regtree-fmllr-diag-gmm.cc.
References VectorBase< Real >::Dim(), RegtreeFmllrDiagGmm::dim_, KALDI_ASSERT, KALDI_WARN, kaldi::kNoTrans, RegtreeFmllrDiagGmm::logdet_, RegtreeFmllrDiagGmm::num_xforms_, and RegtreeFmllrDiagGmm::xform_matrices_.
Referenced by DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), and kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   KALDI_ASSERT(out != NULL);
   if (xform_matrices_.size() == 0) {  // empty transform
     KALDI_ASSERT(num_xforms_ == 0 && dim_ == 0 && logdet_.Dim() == 0);
     KALDI_WARN << "Asked to apply empty feature transform. Copying instead.";
     out->resize(1);
     (*out)[0].Resize(in.Dim());
     (*out)[0].CopyFromVec(in);
     return;
   } else {
     KALDI_ASSERT(in.Dim() == dim_);
     // if (!valid_logdet_)
     // KALDI_ERR << "Must call ComputeLogDets() before transforming data.";
     // [no need for this check].
     Vector<BaseFloat> extended_feat(dim_ + 1);
     extended_feat.Range(0, dim_).CopyFromVec(in);
     extended_feat(dim_) = 1.0;
     KALDI_ASSERT(num_xforms_ > 0);
     out->resize(num_xforms_);
     for (int32 xform_index = 0; xform_index < num_xforms_;
          ++xform_index) {
       (*out)[xform_index].Resize(dim_);
       (*out)[xform_index].AddMatVec(1.0, xform_matrices_[xform_index],
                                     kNoTrans, extended_feat, 0.0);
     }
   }
 }
Validate()
void Validate ()
Checks whether the various parameters are consistent.
Definition at line 63 of file regtree-fmllr-diag-gmm.cc.
References RegtreeFmllrDiagGmm::bclass2xforms_, RegtreeFmllrDiagGmm::dim_, rnnlm::i, KALDI_ASSERT, KALDI_ERR, KALDI_WARN, RegtreeFmllrDiagGmm::logdet_, RegtreeFmllrDiagGmm::num_xforms_, and RegtreeFmllrDiagGmm::xform_matrices_.
Referenced by kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   if (dim_ < 0 || num_xforms_ < 0) {  // uninitialized case
     KALDI_ERR <<"Do not call Validate() with an uninitialized object (dim = "
               << (dim_) << ", # transforms = " << (num_xforms_);
   } else if (dim_ * num_xforms_ == 0) {  // empty case
     KALDI_ASSERT(num_xforms_ == 0 && dim_ == 0);
     if (xform_matrices_.size() != 0 || logdet_.Dim() != 0) {
       KALDI_ERR << "Number of transforms = " << (xform_matrices_.size())
                 << ", number of log-determinant terms = " << (logdet_.Dim())
                 << ". Expected number = 0";
     }
     return;
   }
   // non-empty case: typical usage scenario
   if (xform_matrices_.size() != static_cast<size_t>(num_xforms_)
       || logdet_.Dim() != num_xforms_) {
     KALDI_ERR << "Number of transforms = " << (xform_matrices_.size())
               << ", number of log-determinant terms = " << (logdet_.Dim())
               << ". `Expected number = " << (num_xforms_);
   }
   for (int32 i = 0; i < num_xforms_; i++) {
     if (xform_matrices_[i].NumRows() != dim_ ||
         xform_matrices_[i].NumCols() != (dim_+1)) {
       KALDI_ERR << "For transform " << (i) << ": inconsistent size: rows = "
                 << (xform_matrices_[i].NumRows()) << ", cols = "
                 << xform_matrices_[i].NumCols() << ", dim = " << (dim_);
     }
   }
   if (bclass2xforms_.size() > 0) {
     for (int32 i = 0, maxi = bclass2xforms_.size(); i < maxi; i++) {
       if (bclass2xforms_[i] >= num_xforms_) {
         KALDI_ERR << "For baseclass " << (i) << ", transform index "
                   << (bclass2xforms_[i]) << " exceeds total transforms "
                   << (num_xforms_);
       }
     }
   } else {
     if (num_xforms_ > 1) {
       KALDI_WARN << "Multiple FMLLR transforms found without baseclass info.";
     }
   }
 }
Write()
void Write (std::ostream & out_stream, bool binary) const
Definition at line 148 of file regtree-fmllr-diag-gmm.cc.
References RegtreeFmllrDiagGmm::bclass2xforms_, RegtreeFmllrDiagGmm::dim_, RegtreeFmllrDiagGmm::num_xforms_, kaldi::WriteBasicType(), kaldi::WriteIntegerVector(), kaldi::WriteToken(), and RegtreeFmllrDiagGmm::xform_matrices_.
Referenced by kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   WriteToken(out, binary, "<FMLLRXFORM>");
   WriteToken(out, binary, "<NUMXFORMS>");
   WriteBasicType(out, binary, num_xforms_);
   WriteToken(out, binary, "<DIMENSION>");
   WriteBasicType(out, binary, dim_);
   vector< Matrix<BaseFloat> >::const_iterator xform_itr =
       xform_matrices_.begin(), xform_itr_end = xform_matrices_.end();
   for (; xform_itr != xform_itr_end; ++xform_itr) {
     WriteToken(out, binary, "<XFORM>");
     xform_itr->Write(out, binary);
   }
   WriteToken(out, binary, "<BCLASS2XFORMS>");
   WriteIntegerVector(out, binary, bclass2xforms_);
   WriteToken(out, binary, "</FMLLRXFORM>");
 }
Member Data Documentation
bclass2xforms_
std::vector<int32> bclass2xforms_ private
For each baseclass index of which transform to use; -1 => no xform.
Definition at line 110 of file regtree-fmllr-diag-gmm.h.
Referenced by RegtreeFmllrDiagGmm::Read(), RegtreeFmllrDiagGmm::Validate(), and RegtreeFmllrDiagGmm::Write().
dim_
int32 dim_ private
Dimension of feature vectors.
Definition at line 104 of file regtree-fmllr-diag-gmm.h.
Referenced by RegtreeFmllrDiagGmmAccs::AccumulateForGaussian(), RegtreeFmllrDiagGmmAccs::AccumulateForGmm(), RegtreeFmllrDiagGmm::ComputeLogDets(), RegtreeFmllrDiagGmm::Init(), RegtreeFmllrDiagGmmAccs::Init(), RegtreeFmllrDiagGmm::Read(), RegtreeFmllrDiagGmmAccs::Read(), RegtreeFmllrDiagGmm::SetUnit(), RegtreeFmllrDiagGmm::TransformFeature(), RegtreeFmllrDiagGmmAccs::Update(), RegtreeFmllrDiagGmm::Validate(), RegtreeFmllrDiagGmm::Write(), and RegtreeFmllrDiagGmmAccs::Write().
logdet_
Vector<BaseFloat> logdet_ private
Log-determinants of the Jacobians.
Definition at line 107 of file regtree-fmllr-diag-gmm.h.
Referenced by RegtreeFmllrDiagGmm::ComputeLogDets(), RegtreeFmllrDiagGmm::Init(), RegtreeFmllrDiagGmm::TransformFeature(), and RegtreeFmllrDiagGmm::Validate().
num_xforms_
int32 num_xforms_ private
Number of transform matrices.
Definition at line 105 of file regtree-fmllr-diag-gmm.h.
Referenced by RegtreeFmllrDiagGmm::ComputeLogDets(), RegtreeFmllrDiagGmm::Init(), RegtreeFmllrDiagGmm::Read(), RegtreeFmllrDiagGmm::SetUnit(), RegtreeFmllrDiagGmm::TransformFeature(), RegtreeFmllrDiagGmm::Validate(), and RegtreeFmllrDiagGmm::Write().
valid_logdet_
bool valid_logdet_ private
Whether logdets are for current transforms.
Definition at line 108 of file regtree-fmllr-diag-gmm.h.
Referenced by RegtreeFmllrDiagGmm::ComputeLogDets(), and RegtreeFmllrDiagGmm::Init().
xform_matrices_
std::vector< Matrix<BaseFloat> > xform_matrices_ private
Transform matrices.
Definition at line 106 of file regtree-fmllr-diag-gmm.h.
Referenced by RegtreeFmllrDiagGmm::ComputeLogDets(), RegtreeFmllrDiagGmm::Init(), RegtreeFmllrDiagGmm::Read(), RegtreeFmllrDiagGmm::SetUnit(), RegtreeFmllrDiagGmm::TransformFeature(), RegtreeFmllrDiagGmm::Validate(), and RegtreeFmllrDiagGmm::Write().
The documentation for this class was generated from the following files:
transform/regtree-fmllr-diag-gmm.h
transform/regtree-fmllr-diag-gmm.cc