Kaldi: SoftmaxComponent Class Reference
SoftmaxComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
SoftmaxComponent (const SoftmaxComponent &other)
SoftmaxComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual Component * Copy () const
Copies component (deep copy).
Public Member Functions inherited from NonlinearComponent
NonlinearComponent ()
NonlinearComponent (const NonlinearComponent &other)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual void Read (std::istream &is, bool binary)
We implement Read at this level as it just needs the Type().
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
const CuVector< double > & ValueSum () const
const CuVector< double > & DerivSum () const
double Count () const
Public Member Functions inherited from Component
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
Component ()
virtual ~Component ()
Private Member Functions
SoftmaxComponent & operator= (const SoftmaxComponent &other)
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Types inherited from NonlinearComponent
enum { kUnsetThreshold = -1000 }
Protected Member Functions inherited from NonlinearComponent
void StoreStatsInternal (const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > *deriv=NULL)
void StoreBackpropStats (const CuMatrixBase< BaseFloat > &out_deriv)
const NonlinearComponent & operator= (const NonlinearComponent &other)
Protected Attributes inherited from NonlinearComponent
int32 dim_
int32 block_dim_
CuVector< double > value_sum_
CuVector< double > deriv_sum_
double count_
CuVector< double > oderiv_sumsq_
double oderiv_count_
double num_dims_self_repaired_
double num_dims_processed_
BaseFloat self_repair_lower_threshold_
BaseFloat self_repair_upper_threshold_
BaseFloat self_repair_scale_
Detailed Description
Definition at line 677 of file nnet-simple-component.h.
Constructor & Destructor Documentation
SoftmaxComponent() [1/2]
SoftmaxComponent (const SoftmaxComponent & other) inline explicit
Definition at line 679 of file nnet-simple-component.h.
                                                           :
       NonlinearComponent(other) { }
SoftmaxComponent() [2/2]
SoftmaxComponent () inline
Definition at line 681 of file nnet-simple-component.h.
 { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 3560 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::DiffSoftmaxPerRow(), and NonlinearComponent::StoreBackpropStats().
{
   if (to_update_in) {
     SoftmaxComponent *to_update =
         dynamic_cast<SoftmaxComponent*>(to_update_in);
     to_update->StoreBackpropStats(out_deriv);
   }
   if (in_deriv == NULL)
     return;
   /*
     Note on the derivative of the softmax function: let it be
     p_i = exp(x_i) / sum_i exp_i
     The [matrix-valued] Jacobian of this function is
     diag(p) - p p^T
     Let the derivative vector at the output be e, and at the input be
     d.  We have
     d = diag(p) e - p (p^T e).
     d_i = p_i e_i - p_i (p^T e).
   */
   in_deriv->DiffSoftmaxPerRow(out_value, out_deriv);
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 701 of file nnet-simple-component.h.
 { return new SoftmaxComponent(*this); }
operator=()
SoftmaxComponent& operator= (const SoftmaxComponent & other) private
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 3545 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::ApplyFloor(), and CuMatrixBase< Real >::ApplySoftMaxPerRow().
{
   // Apply softmax function to each row of the output...
   // for that row, we do
   // x_i = exp(x_i) / sum_j exp(x_j).
   out->ApplySoftMaxPerRow(in);
   // This floor on the output helps us deal with
   // almost-zeros in a way that doesn't lead to overflow.
   out->ApplyFloor(1.0e-20);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 683 of file nnet-simple-component.h.
References PnormComponent::Backprop(), kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kBackpropNeedsOutput, kaldi::nnet3::kPropagateInPlace, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kStoresStats, PnormComponent::Propagate(), and Component::StoreStats().
{
     return kSimpleComponent|kPropagateInPlace|kBackpropInPlace|
         kBackpropNeedsOutput|kStoresStats;
   }
StoreStats()
void StoreStats (const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, void * memo) virtual
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
It only does something for those components that have nonzero Properties()&kStoresStats.
Parameters
[in] in_value The input to the Propagate() function. Note: if the component sets the flag kPropagateInPlace, this should not be used; the empty matrix will be provided here if in-place propagation was used.
[in] out_value The output of the Propagate() function.
[in] memo The 'memo' returned by the Propagate() function; this will usually be NULL.
Reimplemented from Component.
Definition at line 3590 of file nnet-simple-component.cc.
{
   // We don't store derivative stats for this component type, just activation
   // stats.
   StoreStatsInternal(out_value, NULL);
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 682 of file nnet-simple-component.h.
 { return "SoftmaxComponent"; }
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc