Kaldi: DiscriminativeExampleSplitter Class Reference
DiscriminativeExampleSplitter Class Reference
For each frame, judge:
Classes
struct FrameInfo
Public Member Functions
DiscriminativeExampleSplitter (const SplitDiscriminativeExampleConfig &config, const TransitionModel &tmodel, const DiscriminativeNnetExample &eg, std::vector< DiscriminativeNnetExample > *egs_out)
void Excise (SplitExampleStats *stats)
void Split (SplitExampleStats *stats)
Private Types
typedef LatticeArc Arc
typedef Arc::StateId StateId
typedef Arc::Label Label
Private Member Functions
void PrepareLattice (bool first_time)
void CollapseTransitionIds ()
bool ComputeFrameInfo ()
void OutputOneSplit (int32 seg_begin, int32 seg_end)
void DoSplit (SplitExampleStats *stats)
void DoExcise (SplitExampleStats *stats)
int32 NumFrames () const
int32 RightContext ()
void CreateOutputLattice (int32 seg_begin, int32 seg_end, CompactLattice *clat_out)
StateId GetOutputStateId (StateId s, unordered_map< StateId, StateId > *state_map, Lattice *lat_out)
Static Private Member Functions
static void RemoveAllOutputSymbols (Lattice *lat)
Private Attributes
const SplitDiscriminativeExampleConfig & config_
const TransitionModel & tmodel_
const DiscriminativeNnetExample & eg_
std::vector< DiscriminativeNnetExample > * egs_out_
Lattice lat_
std::vector< FrameInfo > frame_info_
std::vector< int32 > state_times_
Detailed Description
For each frame, judge:
does it produce a nonzero derivative? [this differs MMI vs MPE]
can it be split here [or what is the penalty for splitting here.]
depends whether lattice has just one path at that point.
Time taken to process segment of a certain length: [must be sub-linear.] [use quadratic function that's max at specified segment length and zero at zero.]
No penalty for processing frames we don't need to process (already implicit in segment-processing time above.)
Penalty for splitting where we should not split. [Make it propto log(#paths).]
Definition at line 100 of file nnet-example-functions.cc.
Member Typedef Documentation
Arc
typedef LatticeArc Arc private
Definition at line 134 of file nnet-example-functions.cc.
Label
typedef Arc::Label Label private
Definition at line 136 of file nnet-example-functions.cc.
StateId
typedef Arc::StateId StateId private
Definition at line 135 of file nnet-example-functions.cc.
Constructor & Destructor Documentation
DiscriminativeExampleSplitter()
DiscriminativeExampleSplitter (const SplitDiscriminativeExampleConfig & config, const TransitionModel & tmodel, const DiscriminativeNnetExample & eg, std::vector< DiscriminativeNnetExample > * egs_out) inline
Definition at line 102 of file nnet-example-functions.cc.
                                                     :
       config_(config), tmodel_(tmodel), eg_(eg), egs_out_(egs_out) { }
Member Function Documentation
CollapseTransitionIds()
void CollapseTransitionIds () private
Definition at line 236 of file nnet-example-functions.cc.
References count, KALDI_ASSERT, DiscriminativeExampleSplitter::lat_, kaldi::LatticeStateTimes(), DiscriminativeExampleSplitter::tmodel_, and TransitionModel::TransitionIdToPdf().
Referenced by DiscriminativeExampleSplitter::PrepareLattice().
{
   std::vector<int32> times;
   TopSort(&lat_); // Topologically sort the lattice (required by
                   // LatticeStateTimes)
   int32 num_frames = LatticeStateTimes(lat_, &times);
   StateId num_states = lat_.NumStates();
   std::vector<std::map<int32, int32> > pdf_to_tid(num_frames);
   for (StateId s = 0; s < num_states; s++) {
     int32 t = times[s];
     for (fst::MutableArcIterator<Lattice> aiter(&lat_, s);
          !aiter.Done(); aiter.Next()) {
       KALDI_ASSERT(t >= 0 && t < num_frames);
       Arc arc = aiter.Value();
       KALDI_ASSERT(arc.ilabel != 0 && arc.ilabel == arc.olabel);
       int32 pdf = tmodel_.TransitionIdToPdf(arc.ilabel);
       if (pdf_to_tid[t].count(pdf) != 0) {
         arc.ilabel = arc.olabel = pdf_to_tid[t][pdf];
         aiter.SetValue(arc);
       } else {
         pdf_to_tid[t][pdf] = arc.ilabel;
       }
     }
   }
 }
ComputeFrameInfo()
bool ComputeFrameInfo () private
Definition at line 299 of file nnet-example-functions.cc.
References DiscriminativeExampleSplitter::FrameInfo::can_excise_frame, DiscriminativeExampleSplitter::config_, SplitDiscriminativeExampleConfig::criterion, DiscriminativeExampleSplitter::FrameInfo::den_pdf_count, DiscriminativeExampleSplitter::FrameInfo::den_state_count, SplitDiscriminativeExampleConfig::drop_frames, DiscriminativeExampleSplitter::eg_, DiscriminativeExampleSplitter::FrameInfo::end_state, DiscriminativeExampleSplitter::frame_info_, rnnlm::i, KALDI_ASSERT, DiscriminativeExampleSplitter::lat_, kaldi::LatticeStateTimes(), DiscriminativeExampleSplitter::FrameInfo::multiple_transition_ids, DiscriminativeExampleSplitter::FrameInfo::nonzero_derivative, DiscriminativeNnetExample::num_ali, DiscriminativeExampleSplitter::FrameInfo::num_den_overlap, DiscriminativeExampleSplitter::NumFrames(), DiscriminativeExampleSplitter::FrameInfo::start_state, DiscriminativeExampleSplitter::state_times_, DiscriminativeExampleSplitter::tmodel_, and TransitionModel::TransitionIdToPdf().
Referenced by DiscriminativeExampleSplitter::Excise(), and DiscriminativeExampleSplitter::Split().
{
   int32 num_frames = NumFrames();
   frame_info_.clear();
   frame_info_.resize(num_frames + 1);
   LatticeStateTimes(lat_, &state_times_);
   std::vector<std::set<int32> > pdfs_per_frame(num_frames),
       tids_per_frame(num_frames);
   int32 num_states = lat_.NumStates();
   for (int32 state = 0; state < num_states; state++) {
     int32 t = state_times_[state];
     KALDI_ASSERT(t >= 0 && t <= num_frames);
     frame_info_[t].den_state_count++;
     for (fst::ArcIterator<Lattice> aiter(lat_, state); !aiter.Done();
          aiter.Next()) {
       const LatticeArc &arc = aiter.Value();
       KALDI_ASSERT(arc.ilabel != 0 && arc.ilabel == arc.olabel);
       int32 transition_id = arc.ilabel,
           pdf_id = tmodel_.TransitionIdToPdf(transition_id);
       tids_per_frame[t].insert(transition_id);
       pdfs_per_frame[t].insert(pdf_id);
     }
     if (t < num_frames)
       frame_info_[t+1].start_state = std::min(state,
                                               frame_info_[t+1].start_state);
     frame_info_[t].end_state = std::max(state,
                                         frame_info_[t].end_state);
   }
   for (int32 i = 1; i <= NumFrames(); i++)
     frame_info_[i].end_state = std::max(frame_info_[i-1].end_state,
                                         frame_info_[i].end_state);
   for (int32 i = NumFrames() - 1; i >= 0; i--)
     frame_info_[i].start_state = std::min(frame_info_[i+1].start_state,
                                           frame_info_[i].start_state);
   for (int32 t = 0; t < num_frames; t++) {
     FrameInfo &frame_info = frame_info_[t];
     int32 transition_id = eg_.num_ali[t],
         pdf_id = tmodel_.TransitionIdToPdf(transition_id);
     frame_info.num_den_overlap = (pdfs_per_frame[t].count(pdf_id) != 0);
     frame_info.multiple_transition_ids = (tids_per_frame[t].size() > 1);
     KALDI_ASSERT(!pdfs_per_frame[t].empty());
     frame_info.den_pdf_count = pdfs_per_frame[t].size();
     if (config_.criterion == "mpfe" || config_.criterion == "smbr") {
       frame_info.nonzero_derivative = (frame_info.den_pdf_count > 1);
     } else {
       KALDI_ASSERT(config_.criterion == "mmi");
       if (config_.drop_frames) {
         // With frame dropping, we'll get nonzero derivative only
         // if num and den overlap, *and* den has >1 active pdf.
         frame_info.nonzero_derivative = frame_info.num_den_overlap  &&
             frame_info.den_state_count > 1;
       } else {
         // Without frame dropping, we'll get nonzero derivative if num and den
         // do not overlap , or den has >1 active pdf.
         frame_info.nonzero_derivative = !frame_info.num_den_overlap ||
             frame_info.den_state_count > 1;
       }
     }
     // If a frame is part of a segment, but it's not going to contribute
     // to the derivative and the den lattice has only one pdf active
     // at that time, then this frame can be excised from the lattice
     // because it will not affect the posteriors around it.
     if (config_.criterion == "mpfe") {
       frame_info.can_excise_frame =
           !frame_info.nonzero_derivative && \
           !frame_info.multiple_transition_ids;
       // in the mpfe case, if there are multiple transition-ids on a
       // frame there may be multiple phones on a frame, which could
       // contribute to the objective function even if they share pdf-ids.
       // (this was an issue that came up during testing).
     } else {
       frame_info.can_excise_frame =
           !frame_info.nonzero_derivative && frame_info.den_pdf_count == 1;
     }
   }
   return true;
 }
CreateOutputLattice()
void CreateOutputLattice (int32 seg_begin, int32 seg_end, CompactLattice * clat_out) private
Definition at line 644 of file nnet-example-functions.cc.
References fst::ConvertLattice(), DiscriminativeExampleSplitter::frame_info_, DiscriminativeExampleSplitter::GetOutputStateId(), KALDI_ASSERT, DiscriminativeExampleSplitter::lat_, DiscriminativeExampleSplitter::NumFrames(), LatticeWeightTpl< BaseFloat >::One(), DiscriminativeExampleSplitter::RemoveAllOutputSymbols(), DiscriminativeExampleSplitter::FrameInfo::start_state, and DiscriminativeExampleSplitter::state_times_.
Referenced by DiscriminativeExampleSplitter::OutputOneSplit(), and DiscriminativeExampleSplitter::RightContext().
{
   Lattice lat_out;
   // Below, state_map will map from states in the original lattice
   // lat_ to ones in the new lattice lat_out.
   unordered_map<StateId, StateId> state_map;
   // The range of the loop over s could be made over the
   // entire lattice, but we limit it for efficiency.
   for (StateId s = frame_info_[seg_begin].start_state;
        s <= frame_info_[seg_end].end_state; s++) {
     int32 t = state_times_[s];
     if (t < seg_begin || t > seg_end) // state out of range.
       continue;
     int32 this_state = GetOutputStateId(s, &state_map, &lat_out);
     if (t == seg_begin) // note: we only split on frames with just one
       lat_out.SetStart(this_state); // state, so we reach this only once.
     if (t == seg_end) { // Make it final and don't process its arcs out.
       if (seg_end == NumFrames()) {
         lat_out.SetFinal(this_state, lat_.Final(s));
       } else {
         lat_out.SetFinal(this_state, LatticeWeight::One());
       }
       continue; // don't process arcs out of this state.
     }
     for (fst::ArcIterator<Lattice> aiter(lat_, s); !aiter.Done(); aiter.Next()) {
       const Arc &arc = aiter.Value();
       StateId next_state = GetOutputStateId(arc.nextstate,
                                             &state_map, &lat_out);
       KALDI_ASSERT(arc.ilabel != 0 && arc.ilabel == arc.olabel); // We expect no epsilons.
       lat_out.AddArc(this_state, Arc(arc.ilabel, arc.olabel, arc.weight,
                                       next_state));
     }
   }
   Connect(&lat_out); // this is not really necessary, it's only to make sure
                      // the assert below fails when it should. TODO: remove it.
   KALDI_ASSERT(lat_out.NumStates() > 0);
   RemoveAllOutputSymbols(&lat_out);
   ConvertLattice(lat_out, clat_out);
 }
DoExcise()
void DoExcise (SplitExampleStats * stats) private
Definition at line 398 of file nnet-example-functions.cc.
References DiscriminativeNnetExample::Check(), fst::ConvertLattice(), VectorBase< Real >::CopyFromVec(), DiscriminativeNnetExample::den_lat, DiscriminativeExampleSplitter::eg_, DiscriminativeExampleSplitter::egs_out_, DiscriminativeExampleSplitter::frame_info_, rnnlm::i, DiscriminativeNnetExample::input_frames, KALDI_ASSERT, KALDI_WARN, DiscriminativeExampleSplitter::lat_, DiscriminativeNnetExample::left_context, SplitExampleStats::longest_segment_after_excise, DiscriminativeNnetExample::num_ali, SplitExampleStats::num_frames_kept_after_excise, MatrixBase< Real >::NumCols(), DiscriminativeExampleSplitter::NumFrames(), DiscriminativeExampleSplitter::RemoveAllOutputSymbols(), Matrix< Real >::Resize(), DiscriminativeExampleSplitter::RightContext(), DiscriminativeNnetExample::spk_info, DiscriminativeExampleSplitter::state_times_, and DiscriminativeNnetExample::weight.
Referenced by DiscriminativeExampleSplitter::Excise().
{
   int32 left_context = eg_.left_context,
       right_context = RightContext(),
       num_frames = NumFrames();
   // Compute, for each frame, whether we can excise it.
   //
   std::vector<bool> can_excise(num_frames, false);
   bool need_some_frame = false;
   for (int32 t = 0; t < num_frames; t++) {
     can_excise[t] = frame_info_[t].can_excise_frame;
     if (!can_excise[t])
       need_some_frame = true;
   }
   if (!need_some_frame) { // We don't need any frame within this file, so simply
                           // delete the segment.
     KALDI_WARN << "Example completely removed when excising."; // unexpected,
     // as the segment should have been deleted when splitting.
     egs_out_->clear();
     return;
   }
   egs_out_->resize(1);
   DiscriminativeNnetExample &eg_out = (*egs_out_)[0];
   // start_t and end_t will be the central part of the segment, excluding any
   // frames at the edges that we can excise.
   int32 start_t, end_t;
   for (start_t = 0; can_excise[start_t]; start_t++);
   for (end_t = num_frames; can_excise[end_t-1]; end_t--);
   // for frames from start_t to end_t-1, do not excise them if
   // they are within the context-window of a frame that we need to keep.
   // Note: we do t2 = t - right_context to t + left_context, because we're
   // concerned whether frame t2 has frame t in its window... it might
   // seem a bit backwards.
   std::vector<bool> will_excise(can_excise);
   for (int32 t = start_t; t < end_t; t++) {
     for (int32 t2 = t - right_context; t2 <= t + left_context; t2++)
       if (t2 >= start_t && t2 < end_t && !can_excise[t2])
         will_excise[t] = false; // can't excise this frame, it's needed for
                                 // context.
   }
   // Remove all un-needed frames from the lattice by replacing the
   // symbols with epsilon and then removing the epsilons.
   // Note, this operation is destructive (it changes lat_).
   int32 num_states = lat_.NumStates();
   for (int32 state = 0; state < num_states; state++) {
     int32 t = state_times_[state];
     for (::fst::MutableArcIterator<Lattice> aiter(&lat_, state); !aiter.Done();
          aiter.Next()) {
       Arc arc = aiter.Value();
       if (will_excise[t]) {
         arc.ilabel = arc.olabel = 0;
         aiter.SetValue(arc);
       }
     }
   }
   RmEpsilon(&lat_);
   RemoveAllOutputSymbols(&lat_);
   ConvertLattice(lat_, &eg_out.den_lat);
   eg_out.num_ali.clear();
   int32 num_frames_kept = 0;
   for (int32 t = 0; t < num_frames; t++) {
     if (!will_excise[t]) {
       eg_out.num_ali.push_back(eg_.num_ali[t]);
       num_frames_kept++;
     }
   }
   stats->num_frames_kept_after_excise += num_frames_kept;
   stats->longest_segment_after_excise = std::max(stats->longest_segment_after_excise,
                                                  num_frames_kept);
   int32 num_frames_kept_plus = num_frames_kept + left_context + right_context;
   eg_out.input_frames.Resize(num_frames_kept_plus,
                              eg_.input_frames.NumCols());
   // the left-context of the output will be shifted to the right by
   // start_t.
   for (int32 i = 0; i < left_context; i++) {
     SubVector<BaseFloat> dst(eg_out.input_frames, i);
     SubVector<BaseFloat> src(eg_.input_frames, start_t + i);
     dst.CopyFromVec(src);
   }
   // the right-context will also be shifted, we take the frames
   // to the right of end_t.
   for (int32 i = 0; i < right_context; i++) {
     SubVector<BaseFloat> dst(eg_out.input_frames,
                              num_frames_kept + left_context + i);
     SubVector<BaseFloat> src(eg_.input_frames,
                              end_t + left_context + i);
     dst.CopyFromVec(src);
   }
   // now copy the central frames (those that were not excised).
   int32 dst_t = 0;
   for (int32 t = start_t; t < end_t; t++) {
     if (!will_excise[t]) {
       SubVector<BaseFloat> dst(eg_out.input_frames,
                                left_context + dst_t);
       SubVector<BaseFloat> src(eg_.input_frames,
                                left_context + t);
       dst.CopyFromVec(src);
       dst_t++;
     }
   }
   KALDI_ASSERT(dst_t == num_frames_kept);
   eg_out.weight = eg_.weight;
   eg_out.left_context = eg_.left_context;
   eg_out.spk_info = eg_.spk_info;
   eg_out.Check();
 }
DoSplit()
void DoSplit (SplitExampleStats * stats) private
Definition at line 516 of file nnet-example-functions.cc.
References DiscriminativeExampleSplitter::FrameInfo::den_state_count, DiscriminativeExampleSplitter::egs_out_, DiscriminativeExampleSplitter::frame_info_, SplitExampleStats::longest_lattice, SplitExampleStats::longest_segment_after_split, DiscriminativeExampleSplitter::FrameInfo::nonzero_derivative, SplitExampleStats::num_frames_kept_after_split, SplitExampleStats::num_frames_must_keep, SplitExampleStats::num_frames_orig, SplitExampleStats::num_kept_segments, SplitExampleStats::num_lattices, SplitExampleStats::num_segments, DiscriminativeExampleSplitter::NumFrames(), and DiscriminativeExampleSplitter::OutputOneSplit().
Referenced by DiscriminativeExampleSplitter::Split().
{
   std::vector<int32> split_points;
   int32 num_frames = NumFrames();
   {
     // Make the "split points" 0 and num_frames, and
     // any frame that has just one state on it and the previous
     // frame had >1 state.  This gives us one split for each
     // "pinch point" in the lattice.  Later we may move each split
     // to a more optimal location.
     split_points.push_back(0);
     for (int32 t = 1; t < num_frames; t++) {
       if (frame_info_[t].den_state_count == 1 &&
           frame_info_[t-1].den_state_count > 1)
         split_points.push_back(t);
     }
     split_points.push_back(num_frames);
   }
   std::vector<bool> is_kept(split_points.size() - 1);
   { // A "split" is a pair of successive split points.  Work out for each split
     // whether we must keep it (we must if it contains at least one frame for
     // which "nonzero_derivative" == true.)
     for (size_t s = 0; s < is_kept.size(); s++) {
       int32 start = split_points[s], end = split_points[s+1];
       bool keep_this_split = false;
       for (int32 t = start; t < end; t++)
         if (frame_info_[t].nonzero_derivative)
           keep_this_split = true;
       is_kept[s] = keep_this_split;
     }
   }
   egs_out_->clear();
   egs_out_->reserve(is_kept.size());
   stats->num_lattices++;
   stats->longest_lattice = std::max(stats->longest_lattice, num_frames);
   stats->num_segments += is_kept.size();
   stats->num_frames_orig += num_frames;
   for (int32 t = 0; t < num_frames; t++)
     if (frame_info_[t].nonzero_derivative)
       stats->num_frames_must_keep++;
   for (size_t s = 0; s < is_kept.size(); s++) {
     if (is_kept[s]) {
       stats->num_kept_segments++;
       OutputOneSplit(split_points[s], split_points[s+1]);
       int32 segment_len = split_points[s+1] - split_points[s];
       stats->num_frames_kept_after_split += segment_len;
       stats->longest_segment_after_split =
           std::max(stats->longest_segment_after_split, segment_len);
     }
   }
 }
Excise()
void Excise (SplitExampleStats * stats) inline
Definition at line 109 of file nnet-example-functions.cc.
References DiscriminativeNnetExample::Check(), DiscriminativeExampleSplitter::ComputeFrameInfo(), DiscriminativeExampleSplitter::config_, DiscriminativeExampleSplitter::DoExcise(), DiscriminativeExampleSplitter::eg_, DiscriminativeExampleSplitter::egs_out_, SplitDiscriminativeExampleConfig::excise, and DiscriminativeExampleSplitter::PrepareLattice().
Referenced by kaldi::nnet2::ExciseDiscriminativeExample().
{
     eg_.Check();
     PrepareLattice(false);
     ComputeFrameInfo();
     if (!config_.excise) {
       egs_out_->resize(1);
       (*egs_out_)[0] = eg_;
     } else {
       DoExcise(stats);
     }
   }
GetOutputStateId()
DiscriminativeExampleSplitter::StateId GetOutputStateId (StateId s, unordered_map< StateId, StateId > * state_map, Lattice * lat_out) private
Definition at line 635 of file nnet-example-functions.cc.
Referenced by DiscriminativeExampleSplitter::CreateOutputLattice(), and DiscriminativeExampleSplitter::RightContext().
{
   if (state_map->count(s) == 0) {
     return ((*state_map)[s] = lat_out->AddState());
   } else {
     return (*state_map)[s];
   }
 }
NumFrames()
int32 NumFrames () const inline private
Definition at line 159 of file nnet-example-functions.cc.
References DiscriminativeExampleSplitter::eg_, and DiscriminativeNnetExample::num_ali.
Referenced by DiscriminativeExampleSplitter::ComputeFrameInfo(), DiscriminativeExampleSplitter::CreateOutputLattice(), DiscriminativeExampleSplitter::DoExcise(), DiscriminativeExampleSplitter::DoSplit(), DiscriminativeExampleSplitter::OutputOneSplit(), and DiscriminativeExampleSplitter::RightContext().
 { return static_cast<int32>(eg_.num_ali.size()); }
OutputOneSplit()
void OutputOneSplit (int32 seg_begin, int32 seg_end) private
Definition at line 596 of file nnet-example-functions.cc.
References DiscriminativeNnetExample::Check(), DiscriminativeExampleSplitter::CreateOutputLattice(), DiscriminativeNnetExample::den_lat, DiscriminativeExampleSplitter::eg_, DiscriminativeExampleSplitter::egs_out_, DiscriminativeNnetExample::input_frames, KALDI_ASSERT, DiscriminativeNnetExample::left_context, DiscriminativeNnetExample::num_ali, MatrixBase< Real >::NumCols(), DiscriminativeExampleSplitter::NumFrames(), MatrixBase< Real >::Range(), DiscriminativeExampleSplitter::RightContext(), DiscriminativeNnetExample::spk_info, and DiscriminativeNnetExample::weight.
Referenced by DiscriminativeExampleSplitter::DoSplit().
{
   KALDI_ASSERT(seg_begin >= 0 && seg_end > seg_begin && seg_end <= NumFrames());
   egs_out_->resize(egs_out_->size() + 1);
   int32 left_context = eg_.left_context, right_context = RightContext(),
       tot_context = left_context + right_context;
   DiscriminativeNnetExample &eg_out = egs_out_->back();
   eg_out.weight = eg_.weight;
   eg_out.num_ali.insert(eg_out.num_ali.end(),
                         eg_.num_ali.begin() + seg_begin,
                         eg_.num_ali.begin() + seg_end);
   CreateOutputLattice(seg_begin, seg_end, &(eg_out.den_lat));
   eg_out.input_frames = eg_.input_frames.Range(seg_begin, seg_end - seg_begin +
                                                tot_context,
                                                0, eg_.input_frames.NumCols());
   eg_out.left_context = eg_.left_context;
   eg_out.spk_info = eg_.spk_info;
   eg_out.Check();
 }
PrepareLattice()
void PrepareLattice (bool first_time) private
Definition at line 263 of file nnet-example-functions.cc.
References SplitDiscriminativeExampleConfig::collapse_transition_ids, DiscriminativeExampleSplitter::CollapseTransitionIds(), DiscriminativeExampleSplitter::config_, fst::ConvertLattice(), SplitDiscriminativeExampleConfig::criterion, DiscriminativeNnetExample::den_lat, SplitDiscriminativeExampleConfig::determinize, DiscriminativeExampleSplitter::eg_, DiscriminativeExampleSplitter::lat_, and SplitDiscriminativeExampleConfig::minimize.
Referenced by DiscriminativeExampleSplitter::Excise(), and DiscriminativeExampleSplitter::Split().
{
   ::fst::ConvertLattice(eg_.den_lat, &lat_);
   Project(&lat_, fst::PROJECT_INPUT); // Get rid of the word labels and put the
                                       // transition-ids on both sides.
   RmEpsilon(&lat_); // Remove epsilons.. this simplifies
                     // certain things.
   if (first_time) {
     if (config_.collapse_transition_ids && config_.criterion != "mpfe")
       CollapseTransitionIds();
     if (config_.determinize) {
       if (!config_.minimize) {
         Lattice det_lat;
         Determinize(lat_, &det_lat);
         lat_ = det_lat;
       } else {
         Lattice tmp_lat;
         Reverse(lat_, &tmp_lat);
         Determinize(tmp_lat, &lat_);
         Reverse(lat_, &tmp_lat);
         Determinize(tmp_lat, &lat_);
         RmEpsilon(&lat_);
         // Previously we determinized, then did
         // Minimize(&lat_);
         // but this was too slow.
       }
     }
   }
   TopSort(&lat_); // Topologically sort the lattice.
 }
RemoveAllOutputSymbols()
void RemoveAllOutputSymbols (Lattice * lat) static private
Definition at line 623 of file nnet-example-functions.cc.
Referenced by DiscriminativeExampleSplitter::CreateOutputLattice(), and DiscriminativeExampleSplitter::DoExcise().
{
   for (StateId s = 0; s < lat->NumStates(); s++) {
     for (::fst::MutableArcIterator<Lattice> aiter(lat, s); !aiter.Done();
          aiter.Next()) {
       Arc arc = aiter.Value();
       arc.olabel = 0;
       aiter.SetValue(arc);
     }
   }
 }
RightContext()
int32 RightContext () inline private
Definition at line 161 of file nnet-example-functions.cc.
References DiscriminativeExampleSplitter::CreateOutputLattice(), DiscriminativeExampleSplitter::eg_, DiscriminativeExampleSplitter::GetOutputStateId(), DiscriminativeNnetExample::input_frames, DiscriminativeNnetExample::left_context, DiscriminativeExampleSplitter::NumFrames(), and MatrixBase< Real >::NumRows().
Referenced by DiscriminativeExampleSplitter::DoExcise(), and DiscriminativeExampleSplitter::OutputOneSplit().
 { return eg_.input_frames.NumRows() - NumFrames() - eg_.left_context; }
Split()
void Split (SplitExampleStats * stats) inline
Definition at line 121 of file nnet-example-functions.cc.
References DiscriminativeNnetExample::Check(), DiscriminativeExampleSplitter::ComputeFrameInfo(), DiscriminativeExampleSplitter::config_, DiscriminativeExampleSplitter::DoSplit(), DiscriminativeExampleSplitter::eg_, DiscriminativeExampleSplitter::egs_out_, DiscriminativeExampleSplitter::PrepareLattice(), and SplitDiscriminativeExampleConfig::split.
Referenced by kaldi::nnet2::SplitDiscriminativeExample().
{
     if (!config_.split) {
       egs_out_->resize(1);
       (*egs_out_)[0] = eg_;
     } else {
       eg_.Check();
       PrepareLattice(true);
       ComputeFrameInfo();
       DoSplit(stats);
     }
   }
Member Data Documentation
config_
const SplitDiscriminativeExampleConfig& config_ private
Definition at line 213 of file nnet-example-functions.cc.
Referenced by DiscriminativeExampleSplitter::ComputeFrameInfo(), DiscriminativeExampleSplitter::Excise(), DiscriminativeExampleSplitter::PrepareLattice(), and DiscriminativeExampleSplitter::Split().
eg_
const DiscriminativeNnetExample& eg_ private
Definition at line 215 of file nnet-example-functions.cc.
Referenced by DiscriminativeExampleSplitter::ComputeFrameInfo(), DiscriminativeExampleSplitter::DoExcise(), DiscriminativeExampleSplitter::Excise(), DiscriminativeExampleSplitter::NumFrames(), DiscriminativeExampleSplitter::OutputOneSplit(), DiscriminativeExampleSplitter::PrepareLattice(), DiscriminativeExampleSplitter::RightContext(), and DiscriminativeExampleSplitter::Split().
egs_out_
std::vector<DiscriminativeNnetExample>* egs_out_ private
Definition at line 216 of file nnet-example-functions.cc.
Referenced by DiscriminativeExampleSplitter::DoExcise(), DiscriminativeExampleSplitter::DoSplit(), DiscriminativeExampleSplitter::Excise(), DiscriminativeExampleSplitter::OutputOneSplit(), and DiscriminativeExampleSplitter::Split().
frame_info_
std::vector<FrameInfo> frame_info_ private
Definition at line 223 of file nnet-example-functions.cc.
Referenced by DiscriminativeExampleSplitter::ComputeFrameInfo(), DiscriminativeExampleSplitter::CreateOutputLattice(), DiscriminativeExampleSplitter::DoExcise(), and DiscriminativeExampleSplitter::DoSplit().
lat_
Lattice lat_ private
Definition at line 218 of file nnet-example-functions.cc.
Referenced by DiscriminativeExampleSplitter::CollapseTransitionIds(), DiscriminativeExampleSplitter::ComputeFrameInfo(), DiscriminativeExampleSplitter::CreateOutputLattice(), DiscriminativeExampleSplitter::DoExcise(), and DiscriminativeExampleSplitter::PrepareLattice().
state_times_
std::vector<int32> state_times_ private
Definition at line 226 of file nnet-example-functions.cc.
Referenced by DiscriminativeExampleSplitter::ComputeFrameInfo(), DiscriminativeExampleSplitter::CreateOutputLattice(), and DiscriminativeExampleSplitter::DoExcise().
tmodel_
const TransitionModel& tmodel_ private
Definition at line 214 of file nnet-example-functions.cc.
Referenced by DiscriminativeExampleSplitter::CollapseTransitionIds(), and DiscriminativeExampleSplitter::ComputeFrameInfo().
The documentation for this class was generated from the following file:
nnet2/nnet-example-functions.cc