Kaldi: CuCompressedMatrix< I > Class Template Reference
CuCompressedMatrix< I > Class Template Reference
Class CuCompressedMatrix, templated on an integer type (expected to be one of: int8, uint8, int16, uint16), this provides a way to approximate a CuMatrix in a more memory-efficient format.
#include <cu-compressed-matrix.h>
Public Member Functions
CuCompressedMatrix (BaseFloat range, bool truncate=true)
Constructor which sets 'scale_' according to scale_ = range / std::numeric_limits<I>::max().
virtual void CopyFromMat (const CuMatrixBase< BaseFloat > &mat)
Sets *this to an appropriately compressed copy of 'mat', which includes resizing *this.
virtual void CopyToMat (CuMatrixBase< BaseFloat > *mat) const
Copies the contents of *this to 'mat', which should be correctly sized beforehand.
virtual MatrixIndexT NumRows () const
virtual MatrixIndexT NumCols () const
virtual ~CuCompressedMatrix ()
Public Member Functions inherited from CuCompressedMatrixBase
virtual ~CuCompressedMatrixBase ()
Private Member Functions
void Destroy ()
Private Attributes
I * data_
BaseFloat scale_
bool truncate_
MatrixIndexT num_rows_
MatrixIndexT num_cols_
MatrixIndexT stride_
Detailed Description
template<typename I>
class kaldi::CuCompressedMatrix< I >
Class CuCompressedMatrix, templated on an integer type (expected to be one of: int8, uint8, int16, uint16), this provides a way to approximate a CuMatrix in a more memory-efficient format.
It's used in nnet3 to reduce memory use for large networks.
It is *not* a CUDA equivalent for class CompressedMatrix (of ../matrix/compressed-matrix.h). Note: this class is only to be used when you are using a GPU. If you didn't compile for CUDA or you are not using a GPU, you are not supposed to create an instance of this class, and doing so will cause a runtime error.
Definition at line 72 of file cu-compressed-matrix.h.
Constructor & Destructor Documentation
CuCompressedMatrix()
CuCompressedMatrix (BaseFloat range, bool truncate = true)
Constructor which sets 'scale_' according to scale_ = range / std::numeric_limits<I>::max().
range = 0 (only supported for I == int8) is a special case in which only the sign of the input is retained; and when we reconstruct, the output will be -1, 0 or 1.
truncate (only relevant if range != 0) should be true if it's possible that the input could exceed the allowed input range, i.e. [0, range] if I is unsigned, and [-range, range] if I is signed; and it may be false if you know that the input (the matrix given to CopyFromMat) will have elements only in the allowed range. Setting 'truncate' to false allows the compression code to avoid the bounds check.
Definition at line 38 of file cu-compressed-matrix.cc.
References KALDI_ASSERT, and KALDI_ERR.
                                                                        :
     data_(NULL), scale_(range / std::numeric_limits<I>::max()),
     truncate_(truncate), num_rows_(0), num_cols_(0), stride_(0) {
 #if HAVE_CUDA == 1
   KALDI_ASSERT(CuDevice::Instantiate().Enabled());
 #else
   KALDI_ERR << "You instantiated CuCompressedMatrix while GPU use "
       "was not compiled in.";
 #endif
 }
~CuCompressedMatrix()
virtual ~CuCompressedMatrix () inline virtual
Definition at line 99 of file cu-compressed-matrix.h.
 { Destroy(); }
Member Function Documentation
CopyFromMat()
void CopyFromMat (const CuMatrixBase< BaseFloat > & mat) virtual
Sets *this to an appropriately compressed copy of 'mat', which includes resizing *this.
The details of how this is done will be different in different child classes.
Implements CuCompressedMatrixBase.
Definition at line 65 of file cu-compressed-matrix.cc.
References CuMatrixBase< Real >::Data(), CuCompressedMatrix< I >::data_, CuCompressedMatrix< I >::Destroy(), CuMatrixBase< Real >::Dim(), KALDI_ASSERT, CuCompressedMatrix< I >::num_cols_, CuCompressedMatrix< I >::num_rows_, CuCompressedMatrix< I >::NumCols(), CuMatrixBase< Real >::NumCols(), CuCompressedMatrix< I >::NumRows(), CuMatrixBase< Real >::NumRows(), CuCompressedMatrix< I >::scale_, CuCompressedMatrix< I >::stride_, and CuCompressedMatrix< I >::truncate_.
{
 #if HAVE_CUDA == 1
   KALDI_ASSERT(CuDevice::Instantiate().Enabled());
   if (mat.NumRows() == 0)
     return;
   if (num_rows_ != mat.NumRows() || num_cols_ != mat.NumCols()) {
     Destroy();
     num_rows_ = mat.NumRows();
     num_cols_ = mat.NumCols();
     data_ = static_cast<I*>(
         CuDevice::Instantiate().Malloc(sizeof(I) * num_rows_ * num_cols_));
     stride_ = num_cols_;
   }
   {
     CuTimer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     if (scale_ == 0.0) { // scale == 0 calls a different kernel from the others.
       cuda_mat_compress_sign(dimGrid, dimBlock, mat.Data(), mat.Dim(),
                              data_, stride_);
     } else {
       cuda_mat_compress(dimGrid, dimBlock, mat.Data(), mat.Dim(),
                         data_, stride_, float(1.0 / scale_),
                         truncate_);
     }
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim);
   }
 #endif
 }
CopyToMat()
void CopyToMat (CuMatrixBase< BaseFloat > * mat) const virtual
Copies the contents of *this to 'mat', which should be correctly sized beforehand.
Implements CuCompressedMatrixBase.
Definition at line 102 of file cu-compressed-matrix.cc.
References CuMatrixBase< Real >::Data(), CuCompressedMatrix< I >::data_, CuMatrixBase< Real >::Dim(), KALDI_ASSERT, CuCompressedMatrix< I >::num_cols_, CuCompressedMatrix< I >::num_rows_, CuCompressedMatrix< I >::NumCols(), CuMatrixBase< Real >::NumCols(), CuCompressedMatrix< I >::NumRows(), CuMatrixBase< Real >::NumRows(), CuCompressedMatrix< I >::scale_, and CuCompressedMatrix< I >::stride_.
{
 #if HAVE_CUDA == 1
   KALDI_ASSERT(CuDevice::Instantiate().Enabled());
   KALDI_ASSERT(mat->NumRows() == num_rows_ && mat->NumCols() == num_cols_);
   {
     CuTimer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     BaseFloat scale = (scale_ == 0.0 ? 1.0 : scale_);
     cuda_mat_uncompress(dimGrid, dimBlock, mat->Data(), mat->Dim(),
                         data_, stride_, float(scale));
   }
 #endif
 }
Destroy()
void Destroy () private
Definition at line 50 of file cu-compressed-matrix.cc.
References CuCompressedMatrix< I >::data_, CuCompressedMatrix< I >::num_cols_, CuCompressedMatrix< I >::num_rows_, and CuCompressedMatrix< I >::stride_.
Referenced by CuCompressedMatrix< I >::CopyFromMat().
{
 #if HAVE_CUDA == 1
   if (data_ != NULL) {
     // we don't bother timing this because Free() won't normally have to
     // access the GPU at all (due to caching).
     CuDevice::Instantiate().Free(data_);
     data_ = NULL;
     num_rows_ = 0;
     num_cols_ = 0;
     stride_ = 0;
   }
 #endif
 }
NumCols()
virtual MatrixIndexT NumCols () const inline virtual
Implements CuCompressedMatrixBase.
Definition at line 96 of file cu-compressed-matrix.h.
Referenced by CuCompressedMatrix< I >::CopyFromMat(), and CuCompressedMatrix< I >::CopyToMat().
 { return num_cols_; }
NumRows()
virtual MatrixIndexT NumRows () const inline virtual
Implements CuCompressedMatrixBase.
Definition at line 94 of file cu-compressed-matrix.h.
Referenced by CuCompressedMatrix< I >::CopyFromMat(), and CuCompressedMatrix< I >::CopyToMat().
 { return num_rows_; }
Member Data Documentation
data_
I* data_ private
Definition at line 106 of file cu-compressed-matrix.h.
Referenced by CuCompressedMatrix< I >::CopyFromMat(), CuCompressedMatrix< I >::CopyToMat(), and CuCompressedMatrix< I >::Destroy().
num_cols_
MatrixIndexT num_cols_ private
Definition at line 129 of file cu-compressed-matrix.h.
Referenced by CuCompressedMatrix< I >::CopyFromMat(), CuCompressedMatrix< I >::CopyToMat(), and CuCompressedMatrix< I >::Destroy().
num_rows_
MatrixIndexT num_rows_ private
Definition at line 128 of file cu-compressed-matrix.h.
Referenced by CuCompressedMatrix< I >::CopyFromMat(), CuCompressedMatrix< I >::CopyToMat(), and CuCompressedMatrix< I >::Destroy().
scale_
BaseFloat scale_ private
Definition at line 117 of file cu-compressed-matrix.h.
Referenced by CuCompressedMatrix< I >::CopyFromMat(), and CuCompressedMatrix< I >::CopyToMat().
stride_
MatrixIndexT stride_ private
Definition at line 132 of file cu-compressed-matrix.h.
Referenced by CuCompressedMatrix< I >::CopyFromMat(), CuCompressedMatrix< I >::CopyToMat(), and CuCompressedMatrix< I >::Destroy().
truncate_
bool truncate_ private
Definition at line 126 of file cu-compressed-matrix.h.
Referenced by CuCompressedMatrix< I >::CopyFromMat().
The documentation for this class was generated from the following files:
cudamatrix/cu-compressed-matrix.h
cudamatrix/cu-compressed-matrix.cc