Kaldi: RandomAccessTableReaderDSortedArchiveImpl< Holder > Class Template Reference
RandomAccessTableReaderDSortedArchiveImpl< Holder > Class Template Reference
"Implementation classes for Table types"
#include <kaldi-table-inl.h>
Public Types
typedef Holder::T T
Public Types inherited from RandomAccessTableReaderArchiveImplBase< Holder >
typedef Holder::T T
Public Types inherited from RandomAccessTableReaderImplBase< Holder >
typedef Holder::T T
Public Member Functions
RandomAccessTableReaderDSortedArchiveImpl ()
virtual bool Close ()
virtual bool HasKey (const std::string &key)
virtual const T & Value (const std::string &key)
virtual ~RandomAccessTableReaderDSortedArchiveImpl ()
Public Member Functions inherited from RandomAccessTableReaderArchiveImplBase< Holder >
RandomAccessTableReaderArchiveImplBase ()
virtual bool Open (const std::string &rspecifier)
void ReadNextObject ()
virtual bool IsOpen () const
bool CloseInternal ()
~RandomAccessTableReaderArchiveImplBase ()
Public Member Functions inherited from RandomAccessTableReaderImplBase< Holder >
virtual ~RandomAccessTableReaderImplBase ()
Private Member Functions
bool FindKeyInternal (const std::string &key)
Private Attributes
std::string last_requested_key_
Last string provided to HasKey() or Value();.
Additional Inherited Members
Protected Types inherited from RandomAccessTableReaderArchiveImplBase< Holder >
enum {
kUninitialized, kNoObject, kHaveObject, kEof,
kError
}
Protected Attributes inherited from RandomAccessTableReaderArchiveImplBase< Holder >
std::string cur_key_
Holder * holder_
std::string rspecifier_
std::string archive_rxfilename_
RspecifierOptions opts_
enum kaldi::RandomAccessTableReaderArchiveImplBase:: { ... } state_
Detailed Description
template<class Holder>
class kaldi::RandomAccessTableReaderDSortedArchiveImpl< Holder >
Definition at line 2051 of file kaldi-table-inl.h.
Member Typedef Documentation
T
typedef Holder::T T
Definition at line 2066 of file kaldi-table-inl.h.
Constructor & Destructor Documentation
RandomAccessTableReaderDSortedArchiveImpl()
RandomAccessTableReaderDSortedArchiveImpl () inline
Definition at line 2068 of file kaldi-table-inl.h.
 { }
~RandomAccessTableReaderDSortedArchiveImpl()
virtual ~RandomAccessTableReaderDSortedArchiveImpl () inline virtual
Definition at line 2089 of file kaldi-table-inl.h.
References TableWriter< Holder >::Close(), TableWriter< Holder >::IsOpen(), and KALDI_ERR.
{
     if (this->IsOpen())
       if (!Close())  // more specific warning will already have been printed.
         // we are in some kind of error state & user did not find out by
         // calling Close().
         KALDI_ERR << "Error closing RandomAccessTableReader: rspecifier is "
                   << rspecifier_;
   }
Member Function Documentation
Close()
virtual bool Close () inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 2070 of file kaldi-table-inl.h.
{
     // We don't have anything additional to clean up, so just
     // call generic base-class one.
     return this->CloseInternal();
   }
FindKeyInternal()
bool FindKeyInternal (const std::string & key) inline private
Definition at line 2101 of file kaldi-table-inl.h.
References KALDI_ASSERT, and KALDI_ERR.
{
     // First check that the user is calling us right: should be
     // in sorted order.  If not, error.
     if (!last_requested_key_.empty()) {
       if (key.compare(last_requested_key_) < 0) {  // key < last_requested_key_
         KALDI_ERR << "You provided the \"cs\" option "
                   << "but are not calling with keys in sorted order: "
                   << key << " < " << last_requested_key_ << ": rspecifier is "
                   << rspecifier_;
       }
     }
     // last_requested_key_ is just for debugging of order of calling.
     last_requested_key_ = key;
     if (state_ == kNoObject)
       ReadNextObject();  // This can only happen
       // once, the first time someone calls HasKey() or Value().  We don't
       // do it in the initializer to stop the program hanging too soon,
       // if reading from a pipe.
     if (state_ == kEof || state_ == kError) return false;
     if (state_ == kUninitialized)
       KALDI_ERR << "Trying to access a RandomAccessTableReader object that is"
                    " not open.";
     std::string last_key_;  // To check that
     // the archive we're reading is in sorted order.
     while (1) {
       KALDI_ASSERT(state_ == kHaveObject);
       int compare = key.compare(cur_key_);
       if (compare == 0) {  // key == key_
         return true;  // we got it..
       } else if (compare < 0) {  // key < cur_key_, so we already read past the
         // place where we want to be.  This implies that we will never find it
         // [due to the sorting etc., this means it just isn't in the archive].
         return false;
       } else {  // compare > 0, key > cur_key_.  We need to read further ahead.
         last_key_ = cur_key_;
         // read next object.. we have to set state to kNoObject first.
         KALDI_ASSERT(holder_ != NULL);
         delete holder_;
         holder_ = NULL;
         state_ = kNoObject;
         ReadNextObject();
         if (state_ != kHaveObject)
           return false;  // eof or read error.
         if (cur_key_.compare(last_key_) <= 0) {
           KALDI_ERR << "You provided the \"s\" option "
                     << " (sorted order), but keys are out of order or"
                        " duplicated: "
                     << last_key_ << " is followed by " << cur_key_
                     << ": rspecifier is " << rspecifier_;
         }
       }
     }
   }
HasKey()
virtual bool HasKey (const std::string & key) inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 2076 of file kaldi-table-inl.h.
{
     return FindKeyInternal(key);
   }
Value()
virtual const T& Value (const std::string & key) inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 2079 of file kaldi-table-inl.h.
References KALDI_ASSERT, KALDI_ERR, and kaldi::PrintableRxfilename().
{
     if (!FindKeyInternal(key)) {
       KALDI_ERR << "Value() called but no such key " << key
                 << " in archive " << PrintableRxfilename(archive_rxfilename_);
     }
     KALDI_ASSERT(this->state_ == kHaveObject && key == this->cur_key_
                  && holder_ != NULL);
     return this->holder_->Value();
   }
Member Data Documentation
last_requested_key_
std::string last_requested_key_ private
Last string provided to HasKey() or Value();.
Definition at line 2160 of file kaldi-table-inl.h.
The documentation for this class was generated from the following file:
util/kaldi-table-inl.h