Kaldi: KlHmm Class Reference
KlHmm Class Reference
#include <nnet-kl-hmm.h>
Public Member Functions
KlHmm (int32 dim_in, int32 dim_out)
~KlHmm ()
Component * Copy () const
Copy component (deep copy),.
ComponentType GetType () const
Get Type Identification of the component,.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
void SetStats (const Matrix< BaseFloat > mat)
Set the statistics matrix.
void Accumulate (const Matrix< BaseFloat > &posteriors, const std::vector< int32 > &alignment)
Accumulate the statistics for KL-HMM paramter estimation,.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
Generic interface of a component,.
virtual ~Component ()
virtual bool IsUpdatable () const
Check if componeny has 'Updatable' interface (trainable components),.
virtual bool IsMultistream () const
Check if component has 'Recurrent' interface (trainable and recurrent),.
int32 InputDim () const
Get the dimension of the input,.
int32 OutputDim () const
Get the dimension of the output,.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward-pass propagation 'in' -> 'out',.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
void Write (std::ostream &os, bool binary) const
Write the component to a stream,.
virtual std::string Info () const
Print some additional info (after <ComponentName> and the dims),.
virtual std::string InfoGradient () const
Print some additional info about gradient (after <...> and dims),.
Private Attributes
Matrix< double > kl_stats_
CuMatrix< BaseFloat > kl_inv_q_
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjected, kBlstmProjected,
kRecurrentComponent, kActivationFunction = 0x0200, kSoftmax, kHiddenSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kParametricRelu,
kDropout, kLengthNormComponent, kTranform = 0x0400, kRbm,
kSplice, kCopy, kTranspose, kBlockLinearity,
kAddShift, kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent,
kSimpleSentenceAveragingComponent, kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent,
kMaxPooling2DComponent, kFramePoolingComponent, kParallelComponent, kMultiBasisComponent
}
Component type identification mechanism,.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Converts component type to marker,.
static ComponentType MarkerToType (const std::string &s)
Converts marker to component type (case insensitive),.
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file,.
static Component * Read (std::istream &is, bool binary)
Read the component from a stream (static method),.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Protected Member Functions inherited from Component
virtual void InitData (std::istream &is)
Virtual interface for initialization and I/O,.
Protected Attributes inherited from Component
int32 input_dim_
Data members,.
int32 output_dim_
Dimension of the output of the Component,.
Detailed Description
Definition at line 37 of file nnet-kl-hmm.h.
Constructor & Destructor Documentation
KlHmm()
KlHmm (int32 dim_in, int32 dim_out) inline
Definition at line 39 of file nnet-kl-hmm.h.
Referenced by KlHmm::Copy().
                                     :
     Component(dim_in, dim_out),
     kl_stats_(dim_out, dim_in, kSetZero)
   { }
~KlHmm()
~KlHmm () inline
Definition at line 44 of file nnet-kl-hmm.h.
   { }
Member Function Documentation
Accumulate()
void Accumulate (const Matrix< BaseFloat > & posteriors, const std::vector< int32 > & alignment) inline
Accumulate the statistics for KL-HMM paramter estimation,.
Definition at line 133 of file nnet-kl-hmm.h.
References rnnlm::i, KALDI_ASSERT, KlHmm::kl_stats_, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Row().
{
     KALDI_ASSERT(posteriors.NumRows() == alignment.size());
     KALDI_ASSERT(posteriors.NumCols() == kl_stats_.NumCols());
     int32 num_frames = alignment.size();
     for (int32 i = 0; i < num_frames; i++) {
       // Casting float posterior to double (fixing numerical issue),
       Vector<double> temp(posteriors.Row(i));
       // Sum the postiors grouped by states from the alignment,
       kl_stats_.Row(alignment[i]).AddVec(1, temp);
     }
   }
BackpropagateFnc()
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 105 of file nnet-kl-hmm.h.
References KALDI_ERR.
{
     KALDI_ERR << "Unimplemented";
   }
Copy()
Component* Copy () const inline virtual
Copy component (deep copy),.
Implements Component.
Definition at line 47 of file nnet-kl-hmm.h.
References KlHmm::KlHmm().
 { return new KlHmm(*this); }
GetType()
ComponentType GetType () const inline virtual
Get Type Identification of the component,.
Implements Component.
Definition at line 48 of file nnet-kl-hmm.h.
References Component::kKlHmm.
 { return kKlHmm; }
PropagateFnc()
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 50 of file nnet-kl-hmm.h.
References CuVectorBase< Real >::AddColSumMat(), VectorBase< Real >::AddColSumMat(), CuMatrixBase< Real >::AddMatMat(), CuMatrixBase< Real >::AddVecToCols(), MatrixBase< Real >::ApplyFloor(), MatrixBase< Real >::ApplyLog(), kaldi::ApproxEqual(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyToMat(), MatrixBase< Real >::InvertElements(), KALDI_ASSERT, KlHmm::kl_inv_q_, KlHmm::kl_stats_, kaldi::kNoTrans, kaldi::kSetZero, kaldi::kTrans, CuMatrixBase< Real >::MulElements(), MatrixBase< Real >::MulRowsVec(), MatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Scale().
{
     if (kl_inv_q_.NumRows() == 0) {
       // Copy the CudaMatrix to a Matrix
       Matrix<BaseFloat> in_tmp(in.NumRows(), in.NumCols());
       in.CopyToMat(&in_tmp);
       // Check if there are posteriors in the Matrix (check on first row),
       BaseFloat post_sum = in_tmp.Row(0).Sum();
       KALDI_ASSERT(ApproxEqual(post_sum, 1.0));
       // Get a tmp Matrix of the stats
       Matrix<BaseFloat> kl_stats_tmp(kl_stats_);
       // Init a vector to get the sum of the rows (for normalization)
       Vector<BaseFloat> row_sum(kl_stats_.NumRows(), kSetZero);
       // Get the sum of the posteriors for normalization
       row_sum.AddColSumMat(1, kl_stats_tmp);
       // Apply floor to make sure there is no zero
       row_sum.ApplyFloor(1e-20);
       // Invert the sum (to normalize)
       row_sum.InvertElements();
       // Normalizing the statistics vector
       kl_stats_tmp.MulRowsVec(row_sum);
       // Apply floor before inversion and logarithm
       kl_stats_tmp.ApplyFloor(1e-20);
       // Apply invesion
       kl_stats_tmp.InvertElements();
       // Apply logarithm
       kl_stats_tmp.ApplyLog();
       // Inverted and logged values
       kl_inv_q_.Resize(kl_stats_.NumRows(), kl_stats_.NumCols());
       // Holds now log (1/Q)
       kl_inv_q_.CopyFromMat(kl_stats_tmp);
     }
     // Get the logarithm of the features for the Entropy calculation
     // Copy the CudaMatrix to a Matrix
     Matrix<BaseFloat> in_log_tmp(in.NumRows(), in.NumCols());
     in.CopyToMat(&in_log_tmp);
     // Flooring and log
     in_log_tmp.ApplyFloor(1e-20);
     in_log_tmp.ApplyLog();
     CuMatrix<BaseFloat> log_in(in.NumRows(), in.NumCols());
     log_in.CopyFromMat(in_log_tmp);
     // P*logP
     CuMatrix<BaseFloat> tmp_entropy(in);
     tmp_entropy.MulElements(log_in);
     // Getting the entropy (sum P*logP)
     CuVector<BaseFloat> in_entropy(in.NumRows(), kSetZero);
     in_entropy.AddColSumMat(1, tmp_entropy);
     // sum P*log (1/Q)
     out->AddMatMat(1, in, kNoTrans, kl_inv_q_, kTrans, 0);
     // (sum P*logP) + (sum P*log(1/Q)
     out->AddVecToCols(1, in_entropy);
     // return the negative KL-divergence
     out->Scale(-1);
   }
ReadData()
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 113 of file nnet-kl-hmm.h.
References Component::input_dim_, KALDI_ASSERT, KlHmm::kl_stats_, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), Component::output_dim_, and Matrix< Real >::Read().
{
     kl_stats_.Read(is, binary);
     KALDI_ASSERT(kl_stats_.NumRows() == output_dim_);
     KALDI_ASSERT(kl_stats_.NumCols() == input_dim_);
   }
SetStats()
void SetStats (const Matrix< BaseFloat > mat) inline
Set the statistics matrix.
Definition at line 125 of file nnet-kl-hmm.h.
References MatrixBase< Real >::CopyFromMat(), Component::input_dim_, KALDI_ASSERT, KlHmm::kl_stats_, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), Component::output_dim_, and Matrix< Real >::Resize().
{
     KALDI_ASSERT(mat.NumRows() == output_dim_);
     KALDI_ASSERT(mat.NumCols() == input_dim_);
     kl_stats_.Resize(mat.NumRows(), mat.NumCols());
     kl_stats_.CopyFromMat(mat);
   }
WriteData()
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 120 of file nnet-kl-hmm.h.
References KlHmm::kl_stats_, and MatrixBase< Real >::Write().
{
     kl_stats_.Write(os, binary);
   }
Member Data Documentation
kl_inv_q_
CuMatrix<BaseFloat> kl_inv_q_ private
Definition at line 148 of file nnet-kl-hmm.h.
Referenced by KlHmm::PropagateFnc().
kl_stats_
Matrix<double> kl_stats_ private
Definition at line 147 of file nnet-kl-hmm.h.
Referenced by KlHmm::Accumulate(), KlHmm::PropagateFnc(), KlHmm::ReadData(), KlHmm::SetStats(), and KlHmm::WriteData().
The documentation for this class was generated from the following file:
nnet/nnet-kl-hmm.h