Kaldi: VectorFstTplHolder< Arc > Class Template Reference
VectorFstTplHolder< Arc > Class Template Reference
#include <kaldi-fst-io.h>
Public Types
typedef VectorFst< Arc > T
Public Member Functions
VectorFstTplHolder ()
void Copy (const T &t)
bool Read (std::istream &is)
T & Value ()
void Clear ()
void Swap (VectorFstTplHolder< Arc > *other)
bool ExtractRange (const VectorFstTplHolder< Arc > &other, const std::string &range)
~VectorFstTplHolder ()
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (VectorFstTplHolder)
Private Attributes
T * t_
Detailed Description
template<class Arc>
class fst::VectorFstTplHolder< Arc >
Definition at line 96 of file kaldi-fst-io.h.
Member Typedef Documentation
T
typedef VectorFst<Arc> T
Definition at line 98 of file kaldi-fst-io.h.
Constructor & Destructor Documentation
VectorFstTplHolder()
VectorFstTplHolder () inline
Definition at line 100 of file kaldi-fst-io.h.
References VectorFstTplHolder< Arc >::Write().
 : t_(NULL) { }
~VectorFstTplHolder()
~VectorFstTplHolder () inline
Definition at line 142 of file kaldi-fst-io.h.
References VectorFstTplHolder< Arc >::Clear(), and VectorFstTplHolder< Arc >::KALDI_DISALLOW_COPY_AND_ASSIGN().
 { Clear(); }
Member Function Documentation
Clear()
void Clear () inline
Definition at line 125 of file kaldi-fst-io.h.
References VectorFstTplHolder< Arc >::t_.
Referenced by VectorFstTplHolder< Arc >::Copy(), and VectorFstTplHolder< Arc >::~VectorFstTplHolder().
                {
     if (t_) {
       delete t_;
       t_ = NULL;
     }
   }
Copy()
void Copy (const T & t) inline
Definition at line 104 of file kaldi-fst-io.h.
References VectorFstTplHolder< Arc >::Clear(), VectorFstTplHolder< Arc >::Read(), and VectorFstTplHolder< Arc >::t_.
                         {  // copies it into the holder.
     Clear();
     t_ = new T(t);
   }
ExtractRange()
bool ExtractRange (const VectorFstTplHolder< Arc > & other, const std::string & range) inline
Definition at line 136 of file kaldi-fst-io.h.
References KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 117 of file kaldi-fst-io.h.
 { return true; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (VectorFstTplHolder< Arc >) private
Referenced by VectorFstTplHolder< Arc >::~VectorFstTplHolder().
Read()
bool Read (std::istream & is)
Definition at line 180 of file kaldi-fst-io-inl.h.
References KALDI_WARN, and fst::ReadFstKaldi().
Referenced by VectorFstTplHolder< Arc >::Copy().
{
   Clear();
   int c = is.peek();
   if (c == -1) {
     KALDI_WARN << "End of stream detected reading Fst";
     return false;
   } else if (isspace(c)) { // The text form of the FST begins
     // with space (normally, '\n'), so this means it's text (the binary form
     // cannot begin with space because it starts with the FST Type() which is not
     // space).
     try {
       t_ = new VectorFst<Arc>();
       ReadFstKaldi(is, false, t_);
     } catch (...) {
       Clear();
       return false;
     }
   } else {  // reading a binary FST.
     try {
       t_ = new VectorFst<Arc>();
       ReadFstKaldi(is, true, t_);
     } catch (...) {
       Clear();
       return false;
     }
   }
   return true;
 }
Swap()
void Swap (VectorFstTplHolder< Arc > * other) inline
Definition at line 132 of file kaldi-fst-io.h.
References kaldi::swap(), and VectorFstTplHolder< Arc >::t_.
{
     std::swap(t_, other->t_);
   }
Value()
T& Value () inline
Definition at line 119 of file kaldi-fst-io.h.
References KALDI_ERR, and VectorFstTplHolder< Arc >::t_.
              {
     // code error if !t_.
     if (!t_) KALDI_ERR << "VectorFstTplHolder::Value() called wrongly.";
     return *t_;
   }
Write()
bool Write (std::ostream & os, bool binary, const T & t) static
Definition at line 170 of file kaldi-fst-io-inl.h.
References fst::WriteFstKaldi().
Referenced by VectorFstTplHolder< Arc >::VectorFstTplHolder().
{
   try {
     WriteFstKaldi(os, binary, t);
     return true;
   } catch (...) {
     return false;
   }
 }
Member Data Documentation
t_
T* t_ private
Definition at line 147 of file kaldi-fst-io.h.
Referenced by VectorFstTplHolder< Arc >::Clear(), VectorFstTplHolder< Arc >::Copy(), VectorFstTplHolder< Arc >::Swap(), and VectorFstTplHolder< Arc >::Value().
The documentation for this class was generated from the following files:
fstext/kaldi-fst-io.h
fstext/kaldi-fst-io-inl.h