Kaldi: ReplaceIndexForwardingDescriptor Class Reference
ReplaceIndexForwardingDescriptor Class Reference
This ForwardingDescriptor modifies the indexes (n, t, x) by replacing one of them (normally t) with a constant value and keeping the rest.
#include <nnet-descriptor.h>
Public Types
enum VariableName { kN = 0, kT = 1, kX = 2 }
Public Member Functions
virtual Cindex MapToInput (const Index &ind) const
virtual int32 Dim (const Nnet &nnet) const
virtual ForwardingDescriptor * Copy () const
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
This function appends to "node_indexes" all the node indexes.
virtual BaseFloat GetScaleForNode (int32 node_index) const
This function returns the scale on the node-index 'node_index' when it appears in expressions inside this descriptor, or +infinity if it does not appear.
ReplaceIndexForwardingDescriptor (ForwardingDescriptor *src, VariableName variable_name, int32 value)
virtual ~ReplaceIndexForwardingDescriptor ()
Public Member Functions inherited from ForwardingDescriptor
virtual int32 Modulus () const
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
virtual ~ForwardingDescriptor ()
ForwardingDescriptor ()
Private Attributes
ForwardingDescriptor * src_
VariableName variable_name_
int32 value_
Detailed Description
This ForwardingDescriptor modifies the indexes (n, t, x) by replacing one of them (normally t) with a constant value and keeping the rest.
Written form is: `ReplaceIndex(<descriptor>, <variable-name>,
)` e.g. `ReplaceIndex(ivector, t, 0)`
Definition at line 273 of file nnet-descriptor.h.
Member Enumeration Documentation
VariableName
enum VariableName
Enumerator
kN
kT
kX
Definition at line 275 of file nnet-descriptor.h.
 { kN = 0, kT = 1, kX = 2};
Constructor & Destructor Documentation
ReplaceIndexForwardingDescriptor()
ReplaceIndexForwardingDescriptor (ForwardingDescriptor * src, VariableName variable_name, int32 value) inline
Definition at line 291 of file nnet-descriptor.h.
                                                :
       src_(src), variable_name_(variable_name), value_(value) { }
~ReplaceIndexForwardingDescriptor()
virtual ~ReplaceIndexForwardingDescriptor () inline virtual
Definition at line 296 of file nnet-descriptor.h.
 { delete src_; }
Member Function Documentation
Copy()
ForwardingDescriptor * Copy () const virtual
Implements ForwardingDescriptor.
Definition at line 237 of file nnet-descriptor.cc.
{
   return new ReplaceIndexForwardingDescriptor(src_->Copy(),
                                               variable_name_, value_);
 }
Dim()
virtual int32 Dim (const Nnet & nnet) const inline virtual
Implements ForwardingDescriptor.
Definition at line 278 of file nnet-descriptor.h.
References ForwardingDescriptor::Copy(), ForwardingDescriptor::GetNodeDependencies(), ForwardingDescriptor::GetScaleForNode(), and ForwardingDescriptor::WriteConfig().
 { return src_->Dim(nnet); }
GetNodeDependencies()
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
This function appends to "node_indexes" all the node indexes.
Implements ForwardingDescriptor.
Definition at line 215 of file nnet-descriptor.cc.
{
   src_->GetNodeDependencies(node_indexes);
 }
GetScaleForNode()
BaseFloat GetScaleForNode (int32 node_index) const virtual
This function returns the scale on the node-index 'node_index' when it appears in expressions inside this descriptor, or +infinity if it does not appear.
E.g. if the descriptor is just `Scale(tdnn2, 2.0)` and the node index for `tdnn2` is 4, then GetScaleForNode(4) would return 2.0. If a particular node_index > 0 appears in different sub-expressions of the descriptor with different scales it is an error (it's not supported) and this function would crash.
Implements ForwardingDescriptor.
Definition at line 220 of file nnet-descriptor.cc.
{
   return src_->GetScaleForNode(node_index);
 }
MapToInput()
Cindex MapToInput (const Index & ind) const virtual
Implements ForwardingDescriptor.
Definition at line 225 of file nnet-descriptor.cc.
References KALDI_ERR, Index::t, and Index::x.
{
   Index ind_mod(ind);
   switch (variable_name_) {
     case kT: ind_mod.t = value_; break;
     case kX: ind_mod.x = value_; break;
     default:  // kN or any other value is not allowed (doesn't make sense
       // to change the minibatch index in this way).
       KALDI_ERR << "Invalid variable name";
   }
   return src_->MapToInput(ind_mod);
 }
WriteConfig()
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
Implements ForwardingDescriptor.
Definition at line 243 of file nnet-descriptor.cc.
References KALDI_ASSERT.
{
   os << "ReplaceIndex(";
   src_->WriteConfig(os, node_names);
   KALDI_ASSERT(variable_name_ == kT || variable_name_ == kX);
   os << ", " << (variable_name_ == kT  ? "t" : "x") << ", "
      << value_ << ")";
 }
Member Data Documentation
src_
ForwardingDescriptor* src_ private
Definition at line 298 of file nnet-descriptor.h.
value_
int32 value_ private
Definition at line 300 of file nnet-descriptor.h.
variable_name_
VariableName variable_name_ private
Definition at line 299 of file nnet-descriptor.h.
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc