Kaldi: WaveData Class Reference
WaveData Class Reference
This class's purpose is to read in Wave files.
#include <wave-reader.h>
Public Member Functions
WaveData (BaseFloat samp_freq, const MatrixBase< BaseFloat > &data)
WaveData ()
void Read (std::istream &is)
Read() will throw on error.
void Write (std::ostream &os) const
Write() will throw on error. os should be opened in binary mode.
const Matrix< BaseFloat > & Data () const
BaseFloat SampFreq () const
BaseFloat Duration () const
void CopyFrom (const WaveData &other)
void Clear ()
void Swap (WaveData *other)
Private Attributes
Matrix< BaseFloat > data_
BaseFloat samp_freq_
Static Private Attributes
static const uint32 kBlockSize = 1024 * 1024
Detailed Description
This class's purpose is to read in Wave files.
Definition at line 106 of file wave-reader.h.
Constructor & Destructor Documentation
WaveData() [1/2]
WaveData (BaseFloat samp_freq, const MatrixBase< BaseFloat > & data) inline
Definition at line 108 of file wave-reader.h.
       : data_(data), samp_freq_(samp_freq) {}
WaveData() [2/2]
WaveData () inline
Definition at line 111 of file wave-reader.h.
References WaveInfo::Read().
 : samp_freq_(0.0) {}
Member Function Documentation
Clear()
void Clear () inline
Definition at line 136 of file wave-reader.h.
References data_, and WaveInfo::samp_freq_.
                {
     data_.Resize(0, 0);
     samp_freq_ = 0.0;
   }
CopyFrom()
void CopyFrom (const WaveData & other) inline
Definition at line 131 of file wave-reader.h.
References data_, WaveData::data_, WaveInfo::samp_freq_, and WaveData::samp_freq_.
{
     samp_freq_ = other.samp_freq_;
     data_.CopyFromMat(other.data_);
   }
Data()
const Matrix<BaseFloat>& Data () const inline
Definition at line 124 of file wave-reader.h.
References data_.
Referenced by main(), kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), kaldi::TestOnlineTransform(), kaldi::UnitTestAperiodic(), UnitTestEndless1(), UnitTestEndless2(), UnitTestHTKCompare1(), UnitTestHTKCompare2(), UnitTestHTKCompare3(), UnitTestHTKCompare4(), UnitTestHTKCompare5(), UnitTestHTKCompare6(), UnitTestMono22K(), UnitTestReadWave(), kaldi::UnitTestSnipEdges(), and UnitTestStereo8K().
 { return data_; }
Duration()
BaseFloat Duration () const inline
Definition at line 129 of file wave-reader.h.
References data_, and WaveInfo::samp_freq_.
Referenced by main(), UnitTestMono22K(), and UnitTestStereo8K().
 { return data_.NumCols() / samp_freq_; }
Read()
void Read (std::istream & is)
Read() will throw on error.
It's valid to call Read() more than once– in this case it will destroy what was there before. "is" should be opened in binary mode.
Definition at line 272 of file wave-reader.cc.
References WaveInfo::BlockAlign(), data_, WaveInfo::DataBytes(), rnnlm::i, WaveInfo::IsStreamed(), rnnlm::j, KALDI_ERR, KALDI_SWAP2, KALDI_WARN, WaveInfo::NumChannels(), WaveInfo::Read(), WaveInfo::ReverseBytes(), and WaveInfo::SampFreq().
Referenced by main(), kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), kaldi::TestOnlineTransform(), kaldi::UnitTestAperiodic(), kaldi::UnitTestDiffSampleRate(), UnitTestEndless1(), UnitTestEndless2(), UnitTestHTKCompare1(), UnitTestHTKCompare2(), UnitTestHTKCompare3(), UnitTestHTKCompare4(), UnitTestHTKCompare5(), UnitTestHTKCompare6(), kaldi::UnitTestKeele(), kaldi::UnitTestKeeleNccfBallast(), UnitTestMono22K(), kaldi::UnitTestPenaltyFactor(), kaldi::UnitTestPitchExtractionSpeed(), kaldi::UnitTestPitchExtractorCompareKeele(), kaldi::UnitTestProcess(), UnitTestReadWave(), kaldi::UnitTestSnipEdges(), and UnitTestStereo8K().
{
   const uint32 kBlockSize = 1024 * 1024;
   WaveInfo header;
   header.Read(is);
   data_.Resize(0, 0);  // clear the data.
   samp_freq_ = header.SampFreq();
   std::vector<char> buffer;
   uint32 bytes_to_go = header.IsStreamed() ? kBlockSize : header.DataBytes();
   // Once in a while header.DataBytes() will report an insane value;
   // read the file to the end
   while (is && bytes_to_go > 0) {
     uint32 block_bytes = std::min(bytes_to_go, kBlockSize);
     uint32 offset = buffer.size();
     buffer.resize(offset + block_bytes);
     is.read(&buffer[offset], block_bytes);
     uint32 bytes_read = is.gcount();
     buffer.resize(offset + bytes_read);
     if (!header.IsStreamed())
       bytes_to_go -= bytes_read;
   }
   if (is.bad())
     KALDI_ERR << "WaveData: file read error";
   if (buffer.size() == 0)
     KALDI_ERR << "WaveData: empty file (no data)";
   if (!header.IsStreamed() && buffer.size() < header.DataBytes()) {
     KALDI_WARN << "Expected " << header.DataBytes() << " bytes of wave data, "
                << "but read only " << buffer.size() << " bytes. "
                << "Truncated file?";
   }
   uint16 *data_ptr = reinterpret_cast<uint16*>(&buffer[0]);
   // The matrix is arranged row per channel, column per sample.
   data_.Resize(header.NumChannels(),
                buffer.size() / header.BlockAlign());
   for (uint32 i = 0; i < data_.NumCols(); ++i) {
     for (uint32 j = 0; j < data_.NumRows(); ++j) {
       int16 k = *data_ptr++;
       if (header.ReverseBytes())
         KALDI_SWAP2(k);
       data_(j, i) =  k;
     }
   }
 }
SampFreq()
BaseFloat SampFreq () const inline
Definition at line 126 of file wave-reader.h.
References WaveInfo::samp_freq_.
Referenced by main(), kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), kaldi::TestOnlineTransform(), UnitTestMono22K(), kaldi::UnitTestSnipEdges(), and UnitTestStereo8K().
 { return samp_freq_; }
Swap()
void Swap (WaveData * other) inline
Definition at line 141 of file wave-reader.h.
References data_, WaveData::data_, WaveInfo::samp_freq_, WaveData::samp_freq_, and kaldi::swap().
{
     data_.Swap(&(other->data_));
     std::swap(samp_freq_, other->samp_freq_);
   }
Write()
void Write (std::ostream & os) const
Write() will throw on error. os should be opened in binary mode.
Definition at line 332 of file wave-reader.cc.
References data_, rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_ERR, KALDI_SWAP2, KALDI_WARN, kaldi::WriteUint16(), and kaldi::WriteUint32().
Referenced by main(), and WaveHolder::Write().
{
   os << "RIFF";
   if (data_.NumRows() == 0)
     KALDI_ERR << "Error: attempting to write empty WAVE file";
   int32 num_chan = data_.NumRows(),
       num_samp = data_.NumCols(),
       bytes_per_samp = 2;
   int32 subchunk2size = (num_chan * num_samp * bytes_per_samp);
   int32 chunk_size = 36 + subchunk2size;
   WriteUint32(os, chunk_size);
   os << "WAVE";
   os << "fmt ";
   WriteUint32(os, 16);
   WriteUint16(os, 1);
   WriteUint16(os, num_chan);
   KALDI_ASSERT(samp_freq_ > 0);
   WriteUint32(os, static_cast<int32>(samp_freq_));
   WriteUint32(os, static_cast<int32>(samp_freq_) * num_chan * bytes_per_samp);
   WriteUint16(os, num_chan * bytes_per_samp);
   WriteUint16(os, 8 * bytes_per_samp);
   os << "data";
   WriteUint32(os, subchunk2size);
   const BaseFloat *data_ptr = data_.Data();
   int32 stride = data_.Stride();
   int num_clipped = 0;
   for (int32 i = 0; i < num_samp; i++) {
     for (int32 j = 0; j < num_chan; j++) {
       int32 elem = static_cast<int32>(trunc(data_ptr[j * stride + i]));
       int16 elem_16 = static_cast<int16>(elem);
       if (elem < std::numeric_limits<int16>::min()) {
         elem_16 = std::numeric_limits<int16>::min();
         ++num_clipped;
       } else if (elem > std::numeric_limits<int16>::max()) {
         elem_16 = std::numeric_limits<int16>::max();
         ++num_clipped;
       }
 #ifdef __BIG_ENDIAN__
       KALDI_SWAP2(elem_16);
 #endif
       os.write(reinterpret_cast<char*>(&elem_16), 2);
     }
   }
   if (os.fail())
     KALDI_ERR << "Error writing wave data to stream.";
   if (num_clipped > 0)
     KALDI_WARN << "WARNING: clipped " << num_clipped
                << " samples out of total " << num_chan * num_samp
                << ". Reduce volume?";
 }
Member Data Documentation
data_
Matrix<BaseFloat> data_ private
Definition at line 148 of file wave-reader.h.
Referenced by WaveData::CopyFrom(), and WaveData::Swap().
kBlockSize
const uint32 kBlockSize = 1024 * 1024 static private
Definition at line 147 of file wave-reader.h.
samp_freq_
BaseFloat samp_freq_ private
Definition at line 149 of file wave-reader.h.
Referenced by WaveData::CopyFrom(), and WaveData::Swap().
The documentation for this class was generated from the following files:
feat/wave-reader.h
feat/wave-reader.cc