Kaldi: PdfPrior Class Reference
PdfPrior Class Reference
#include <nnet-pdf-prior.h>
Public Member Functions
PdfPrior (const PdfPriorOptions &opts)
Initialize pdf-prior from options.
void SubtractOnLogpost (CuMatrixBase< BaseFloat > *llk)
Subtract pdf priors from log-posteriors to get pseudo log-likelihoods.
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (PdfPrior)
Private Attributes
BaseFloat prior_scale_
CuVector< BaseFloat > log_priors_
Detailed Description
Definition at line 59 of file nnet-pdf-prior.h.
Constructor & Destructor Documentation
PdfPrior()
PdfPrior (const PdfPriorOptions & opts) explicit
Initialize pdf-prior from options.
Definition at line 26 of file nnet-pdf-prior.cc.
References VectorBase< Real >::Add(), VectorBase< Real >::ApplyLog(), PdfPriorOptions::class_frame_counts, Input::Close(), VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, KALDI_ISFINITE, KALDI_LOG, PdfPrior::log_priors_, Input::OpenTextMode(), PdfPriorOptions::prior_floor, Vector< Real >::Read(), VectorBase< Real >::Scale(), Input::Stream(), and VectorBase< Real >::Sum().
     : prior_scale_(opts.prior_scale) {
   if (opts.class_frame_counts == "") {
     // class_frame_counts is empty, the PdfPrior is deactivated...
     // (for example when 'nnet-forward' generates bottleneck features)
     return;
   }
   KALDI_LOG << "Computing pdf-priors from : " << opts.class_frame_counts;
   Vector<double> frame_counts, rel_freq, log_priors;
   {
     Input in;
     in.OpenTextMode(opts.class_frame_counts);
     frame_counts.Read(in.Stream(), false);
     in.Close();
   }
   // get relative frequencies,
   rel_freq = frame_counts;
   rel_freq.Scale(1.0/frame_counts.Sum());
   // get the log-prior,
   log_priors = rel_freq;
   log_priors.Add(1e-20);
   log_priors.ApplyLog();
   // Make the priors for classes with low counts +inf (i.e. -log(0))
   // such that the classes have 0 likelihood (i.e. -inf log-likelihood).
   // We use sqrt(FLT_MAX) instead of -kLogZeroFloat to prevent NANs
   // from appearing in computation.
   int32 num_floored = 0;
   for (int32 i = 0; i < log_priors.Dim(); i++) {
     if (rel_freq(i) < opts.prior_floor) {
       log_priors(i) = sqrt(FLT_MAX);
       num_floored++;
     }
   }
   KALDI_LOG << "Floored " << num_floored << " pdf-priors "
             << "(hard-set to " << sqrt(FLT_MAX)
             << ", which disables DNN output when decoding)";
   // sanity check,
   KALDI_ASSERT(KALDI_ISFINITE(log_priors.Sum()));
   // push to GPU,
   log_priors_ = Vector<BaseFloat>(log_priors);
 }
Member Function Documentation
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (PdfPrior) private
SubtractOnLogpost()
void SubtractOnLogpost (CuMatrixBase< BaseFloat > * llk)
Subtract pdf priors from log-posteriors to get pseudo log-likelihoods.
Definition at line 76 of file nnet-pdf-prior.cc.
References CuMatrixBase< Real >::AddVecToRows(), KALDI_ERR, PdfPrior::log_priors_, CuMatrixBase< Real >::NumCols(), and PdfPrior::prior_scale_.
Referenced by main().
{
   if (log_priors_.Dim() == 0) {
     KALDI_ERR << "--class-frame-counts is empty: Cannot initialize priors "
               << "without the counts.";
   }
   if (log_priors_.Dim() != llk->NumCols()) {
     KALDI_ERR << "Dimensionality mismatch,"
               << " class_frame_counts " << log_priors_.Dim()
               << " pdf_output_llk " << llk->NumCols();
   }
   llk->AddVecToRows(-prior_scale_, log_priors_);
 }
Member Data Documentation
log_priors_
CuVector<BaseFloat> log_priors_ private
Definition at line 69 of file nnet-pdf-prior.h.
Referenced by PdfPrior::PdfPrior(), and PdfPrior::SubtractOnLogpost().
prior_scale_
BaseFloat prior_scale_ private
Definition at line 68 of file nnet-pdf-prior.h.
Referenced by PdfPrior::SubtractOnLogpost().
The documentation for this class was generated from the following files:
nnet/nnet-pdf-prior.h
nnet/nnet-pdf-prior.cc