Kaldi: TxpParseOptions Class Reference
TxpParseOptions Class Reference
Class derived from standard ParseOptions in order to allow txp system to load a voice specific set of configurations switches from <tpdb path>="">/default.conf and set txp options to default values before overiding with –config=<file> and command line swithes.
#include <txpparse-options.h>
Public Member Functions
TxpParseOptions (const char *usage)
Set defaults and register switches in txpoptions_.
~TxpParseOptions ()
Delete added switches in txpoptions_.
int Read (int argc, const char *const *argv)
Read in tpdb path, set tpdb, load default.conf from voice.
const char * GetValue (const char *module, const char *key) const
Return txp switch value used by txp modules.
const char * GetValue (const char *key) const
const char * GetTpdb () const
Return path to tpdb.
void SetTpdb (const std::string &tpdb)
Override path to tpdb.
std::vector< std::string > Keys ()
Get all valid keys.
std::string DocString (const std::string &key)
Get the document string for the given key.
Public Member Functions inherited from ParseOptions
ParseOptions (const char *usage)
ParseOptions (const std::string &prefix, OptionsItf *other)
This is a constructor for the special case where some options are registered with a prefix to avoid conflicts.
~ParseOptions ()
void Register (const std::string &name, bool *ptr, const std::string &doc)
void Register (const std::string &name, int32 *ptr, const std::string &doc)
void Register (const std::string &name, uint32 *ptr, const std::string &doc)
void Register (const std::string &name, float *ptr, const std::string &doc)
void Register (const std::string &name, double *ptr, const std::string &doc)
void Register (const std::string &name, std::string *ptr, const std::string &doc)
void DisableOption (const std::string &name)
If called after registering an option and before calling Read(), disables that option from being used.
template<typename T >
void RegisterStandard (const std::string &name, T *ptr, const std::string &doc)
This one is used for registering standard parameters of all the programs.
int Read (int argc, const char *const *argv)
Parses the command line options and fills the ParseOptions-registered variables.
void PrintUsage (bool print_command_line=false)
Prints the usage documentation [provided in the constructor].
void PrintConfig (std::ostream &os)
Prints the actual configuration of all the registered variables.
void ReadConfigFile (const std::string &filename)
Reads the options values from a config file.
int NumArgs () const
Number of positional parameters (c.f. argc-1).
std::string GetArg (int param) const
Returns one of the positional parameters; 1-based indexing for argc/argv compatibility.
std::string GetOptArg (int param) const
Public Member Functions inherited from OptionsItf
virtual ~OptionsItf ()
Private Attributes
std::string tpdb_
Path to tpdb (text processing database) used by the voice.
LookupMapPtr txpoptions_
holds txp specific switch settings
Additional Inherited Members
Static Public Member Functions inherited from ParseOptions
static std::string Escape (const std::string &str)
The following function will return a possibly quoted and escaped version of "str", according to the current shell.
Protected Member Functions inherited from ParseOptions
void SplitLongArg (std::string in, std::string *key, std::string *value, bool *has_equal_sign)
SplitLongArg parses an argument of the form –a=b, –a=, or –a,.
void NormalizeArgName (std::string *str)
const DocMapType & DocMap () const
Detailed Description
Class derived from standard ParseOptions in order to allow txp system to load a voice specific set of configurations switches from <tpdb path>="">/default.conf and set txp options to default values before overiding with –config=<file> and command line swithes.
txp variables are all std::string and are stored in this class for txp modules to access as required.
Definition at line 49 of file txpparse-options.h.
Constructor & Destructor Documentation
TxpParseOptions()
TxpParseOptions (const char * usage) explicit
Set defaults and register switches in txpoptions_.
Definition at line 54 of file txpparse-options.cc.
References ParseOptions::NormalizeArgName(), ParseOptions::Register(), ParseOptions::RegisterStandard(), ParseOptions::SplitLongArg(), TxpParseOptions::tpdb_, kaldi::Trim(), and TxpParseOptions::txpoptions_.
     : ParseOptions(usage) {
   std::istringstream is(txpconfigdefault);
   std::string line, key, value, *stringptr;
   RegisterStandard("tpdb", &tpdb_,
                    "Text processing database (directory XML language/speaker files)"); //NOLINT
   while (std::getline(is, line)) {
     // trim out the comments
     size_t pos;
     if ((pos = line.find_first_of('#')) != std::string::npos) {
       line.erase(pos);
     }
     // skip empty lines
     Trim(&line);
     if (line.length() == 0) continue;
     // parse option
     bool has_equal_sign;
     SplitLongArg(line, &key, &value, &has_equal_sign);
     NormalizeArgName(&key);
     Trim(&value);
     stringptr = new std::string(value);
     txpoptions_.insert(LookupItemPtr(key, stringptr));
     Register(key.c_str(), stringptr,
              "Idlak Text Processing Option");
   }
 }
~TxpParseOptions()
~TxpParseOptions ()
Delete added switches in txpoptions_.
Definition at line 82 of file txpparse-options.cc.
References TxpParseOptions::txpoptions_.
{
   for (LookupMapPtr::iterator iter = txpoptions_.begin();
       iter != txpoptions_.end(); iter++) {
     delete iter->second;
   }
 }
Member Function Documentation
DocString()
std::string DocString (const std::string & key)
Get the document string for the given key.
Definition at line 159 of file txpparse-options.cc.
References ParseOptions::DocMap().
Referenced by TxpParseOptions::SetTpdb().
{
   auto doc = DocMap().find(key);
   if (doc == DocMap().end())
     return std::string("");
   return std::string(doc->second.use_msg_);
 }
GetTpdb()
const char * GetTpdb () const
Return path to tpdb.
Definition at line 134 of file txpparse-options.cc.
References TxpParseOptions::tpdb_.
Referenced by TxpParseOptions::GetValue(), TxpCex::Init(), TxpPosTag::Init(), TxpTokenise::Init(), TxpPhrasing::Init(), TxpPauses::Init(), TxpSyllabify::Init(), and TxpPronounce::Init().
{
   return tpdb_.c_str();
 }
GetValue() [1/2]
const char * GetValue (const char * module, const char * key) const
Return txp switch value used by txp modules.
Definition at line 117 of file txpparse-options.cc.
References TxpParseOptions::txpoptions_.
Referenced by TxpModule::GetOptValue(), TxpXmlData::GetOptValue(), TxpModule::GetOptValueBool(), and TxpTokenise::Init().
{
   LookupMapPtr::const_iterator lookup;
   std::string optkey(module);
   optkey = optkey + "-" + key;
   lookup = txpoptions_.find(optkey);
   if (lookup == txpoptions_.end()) {
     // if general section also look for field without section
     // description
     if (!strcmp(module, "general")) {
       optkey = key;
       lookup = txpoptions_.find(optkey);
       if (lookup == txpoptions_.end()) return NULL;
       else return (lookup->second)->c_str();
     }
   }
   return (lookup->second)->c_str();
 }
GetValue() [2/2]
const char * GetValue (const char * key) const
Definition at line 138 of file txpparse-options.cc.
References TxpParseOptions::GetTpdb(), and TxpParseOptions::txpoptions_.
{
   LookupMapPtr::const_iterator lookup = txpoptions_.find(key);
   if (lookup == txpoptions_.end()) {
     if (!strcmp(key, "tpdb")) {
       return GetTpdb();
     }
     return nullptr;
   }
   else {
     return (lookup->second)->c_str();
   }
 }
Keys()
std::vector< std::string > Keys ()
Get all valid keys.
Definition at line 151 of file txpparse-options.cc.
References ParseOptions::DocMap().
Referenced by TxpParseOptions::SetTpdb().
{
   std::vector<std::string> keys;
   for (auto const& doc : DocMap() ) {
     keys.push_back(std::string(doc.first));
   }
   return keys;
 }
Read()
int Read (int argc, const char *const * argv)
Read in tpdb path, set tpdb, load default.conf from voice.
Definition at line 89 of file txpparse-options.cc.
References rnnlm::i, ParseOptions::NormalizeArgName(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::ReadConfigFile(), ParseOptions::SplitLongArg(), and kaldi::Trim().
Referenced by main().
{
   std::string key, value;
   int i;
   // first pass: look for tpdb parameter
   for (i = 1; i < argc; i++) {
     if (std::strncmp(argv[i], "--", 2) == 0) {
       bool has_equal_sign;
       SplitLongArg(argv[i], &key, &value, &has_equal_sign);
       NormalizeArgName(&key);
       Trim(&value);
       if (key.compare("tpdb") == 0) {
         // check for tpdb configuration file
         std::ifstream is((value + "/default.conf").c_str(), std::ifstream::in);
         if (is.good()) {
           is.close();
           ReadConfigFile(value + "/default.conf");
         }
       }
       if (key.compare("help") == 0) {
         PrintUsage();
         exit(0);
       }
     }
   }
   return ParseOptions::Read(argc, argv);
 }
SetTpdb()
void SetTpdb (const std::string & tpdb) inline
Override path to tpdb.
Definition at line 63 of file txpparse-options.h.
References TxpParseOptions::DocString(), TxpParseOptions::Keys(), and TxpParseOptions::tpdb_.
Referenced by main().
 {tpdb_ = tpdb;}
Member Data Documentation
tpdb_
std::string tpdb_ private
Path to tpdb (text processing database) used by the voice.
Definition at line 71 of file txpparse-options.h.
Referenced by TxpParseOptions::GetTpdb(), TxpParseOptions::SetTpdb(), and TxpParseOptions::TxpParseOptions().
txpoptions_
LookupMapPtr txpoptions_ private
holds txp specific switch settings
Definition at line 73 of file txpparse-options.h.
Referenced by TxpParseOptions::GetValue(), TxpParseOptions::TxpParseOptions(), and TxpParseOptions::~TxpParseOptions().
The documentation for this class was generated from the following files:
idlaktxp/txpparse-options.h
idlaktxp/txpparse-options.cc