Kaldi: ConvolutionComponent Class Reference
ConvolutionComponent Class Reference
WARNING, this component is deprecated in favor of TimeHeightConvolutionComponent, and will be deleted.
#include <nnet-simple-component.h>
Public Types
enum TensorVectorizationType { kYzx = 0, kZyx = 1 }
Public Member Functions
ConvolutionComponent ()
ConvolutionComponent (const ConvolutionComponent &component)
ConvolutionComponent (const CuMatrixBase< BaseFloat > &filter_params, const CuVectorBase< BaseFloat > &bias_params, int32 input_x_dim, int32 input_y_dim, int32 input_z_dim, int32 filt_x_dim, int32 filt_y_dim, int32 filt_x_step, int32 filt_y_step, TensorVectorizationType input_vectorization, BaseFloat learning_rate)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update_in, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
void Update (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv, const std::vector< CuSubMatrix< BaseFloat > *> &out_deriv_batch)
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
void SetParams (const VectorBase< BaseFloat > &bias, const MatrixBase< BaseFloat > &filter)
const CuVector< BaseFloat > & BiasParams () const
const CuMatrix< BaseFloat > & LinearParams () const
void Init (int32 input_x_dim, int32 input_y_dim, int32 input_z_dim, int32 filt_x_dim, int32 filt_y_dim, int32 filt_x_step, int32 filt_y_step, int32 num_filters, TensorVectorizationType input_vectorization, BaseFloat param_stddev, BaseFloat bias_stddev)
void Init (int32 input_x_dim, int32 input_y_dim, int32 input_z_dim, int32 filt_x_dim, int32 filt_y_dim, int32 filt_x_step, int32 filt_y_step, TensorVectorizationType input_vectorization, std::string matrix_filename)
void Resize (int32 input_dim, int32 output_dim)
void Update (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
virtual void FreezeNaturalGradient (bool freeze)
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
void InputToInputPatches (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *patches) const
void InderivPatchesToInderiv (const CuMatrix< BaseFloat > &in_deriv_patches, CuMatrixBase< BaseFloat > *in_deriv) const
const ConvolutionComponent & operator= (const ConvolutionComponent &other)
Private Attributes
int32 input_x_dim_
int32 input_y_dim_
int32 input_z_dim_
int32 filt_x_dim_
int32 filt_y_dim_
int32 filt_x_step_
int32 filt_y_step_
TensorVectorizationType input_vectorization_
CuMatrix< BaseFloat > filter_params_
CuVector< BaseFloat > bias_params_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Detailed Description
WARNING, this component is deprecated in favor of TimeHeightConvolutionComponent, and will be deleted.
ConvolutionalComponent implements 2d-convolution. It uses 3D filters on 3D inputs, but the 3D filters hop only over 2 dimensions as it has same size as the input along the 3rd dimension. Input : A matrix where each row is a vectorized 3D-tensor. The 3D tensor has dimensions x: (e.g. time) y: (e.g. frequency) z: (e.g. channels like features/delta/delta-delta)
The component supports input vectorizations of type zyx and yzx. The default vectorization type is zyx. e.g. for input vectorization of type zyx the input is vectorized by spanning axes z, y and x of the tensor in that order. Given 3d tensor A with sizes (2, 2, 2) along the three dimensions the zyx vectorized input looks like A(0,0,0) A(0,0,1) A(0,1,0) A(0,1,1) A(1,0,0) A(1,0,1) A(1,1,0) A(1,1,1)
Output : The output is also a 3D tensor vectorized in the zyx format. The channel axis (z) in the output corresponds to the output of different filters. The first channel corresponds to the first filter i.e., first row of the filter_params_ matrix.
Note: The component has to support yzx input vectorization as the binaries like add-deltas generate yz vectorized output. These input vectors are concatenated using the Append descriptor across time steps to form a yzx vectorized 3D tensor input. e.g. Append(Offset(input, -1), input, Offset(input, 1))
For information on the hyperparameters and parameters of this component see the variable declarations.
Propagation: ------------ Convolution operation consists of a dot-products between the filter tensor and input tensor patch, for various shifts of filter tensor along the x and y axes input tensor. (Note: there is no shift along z-axis as the filter and input tensor have same size along this axis).
For a particular shift (i,j) of the filter tensor along input tensor dimensions x and y, the elements of the input tensor which overlap with the filter form the input tensor patch. This patch is vectorized in zyx format. All the patches corresponding to various samples in the mini-batch are stacked into a matrix, where each row corresponds to one patch. Let this matrix be represented by X_{i,j}. The dot products with various filters are computed simultaneously by computing the matrix product with the filter_params_ matrix (W) Y_{i,j} = X_{i,j}*W^T. Each row of W corresponds to one filter 3D tensor vectorized in zyx format.
All the matrix products corresponding to various shifts (i,j) of the filter tensor are computed simultaneously using the AddMatMatBatched call of CuMatrixBase class.
BackPropagation: ---------------- Backpropagation to compute the input derivative (X_{i,j}) consists of the a series of matrix products. {i,j} = {i,j}*W where {i,j} corresponds to the output derivative for a particular shift of the filter.
Once again these matrix products are computed simultaneously.
Update: ------- The weight gradient is computed as = {i,j} (X_{i,j}^T *{i,j})
Definition at line 2024 of file nnet-simple-component.h.
Member Enumeration Documentation
TensorVectorizationType
enum TensorVectorizationType
Enumerator
kYzx
kZyx
Definition at line 2026 of file nnet-simple-component.h.
{
     kYzx = 0,
     kZyx = 1
   };
Constructor & Destructor Documentation
ConvolutionComponent() [1/3]
ConvolutionComponent ()
Definition at line 3946 of file nnet-simple-component.cc.
Referenced by ConvolutionComponent::Copy().
                                           :
     UpdatableComponent(),
     input_x_dim_(0), input_y_dim_(0), input_z_dim_(0),
     filt_x_dim_(0), filt_y_dim_(0),
     filt_x_step_(0), filt_y_step_(0),
     input_vectorization_(kZyx) { }
ConvolutionComponent() [2/3]
ConvolutionComponent (const ConvolutionComponent & component)
Definition at line 3953 of file nnet-simple-component.cc.
                                           :
     UpdatableComponent(component),
     input_x_dim_(component.input_x_dim_),
     input_y_dim_(component.input_y_dim_),
     input_z_dim_(component.input_z_dim_),
     filt_x_dim_(component.filt_x_dim_),
     filt_y_dim_(component.filt_y_dim_),
     filt_x_step_(component.filt_x_step_),
     filt_y_step_(component.filt_y_step_),
     input_vectorization_(component.input_vectorization_),
     filter_params_(component.filter_params_),
     bias_params_(component.bias_params_) { }
ConvolutionComponent() [3/3]
ConvolutionComponent (const CuMatrixBase< BaseFloat > & filter_params, const CuVectorBase< BaseFloat > & bias_params, int32 input_x_dim, int32 input_y_dim, int32 input_z_dim, int32 filt_x_dim, int32 filt_y_dim, int32 filt_x_step, int32 filt_y_step, TensorVectorizationType input_vectorization, BaseFloat learning_rate)
Definition at line 3967 of file nnet-simple-component.cc.
References CuVectorBase< Real >::Dim(), UpdatableComponent::is_gradient_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and UpdatableComponent::SetUnderlyingLearningRate().
                             :
     input_x_dim_(input_x_dim),
     input_y_dim_(input_y_dim),
     input_z_dim_(input_z_dim),
     filt_x_dim_(filt_x_dim),
     filt_y_dim_(filt_y_dim),
     filt_x_step_(filt_x_step),
     filt_y_step_(filt_y_step),
     input_vectorization_(input_vectorization),
     filter_params_(filter_params),
     bias_params_(bias_params){
   KALDI_ASSERT(filter_params.NumRows() == bias_params.Dim() &&
                bias_params.Dim() != 0);
   KALDI_ASSERT(filter_params.NumCols() == filt_x_dim * filt_y_dim * input_z_dim);
   SetUnderlyingLearningRate(learning_rate);
   is_gradient_ = false;
 }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 4260 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, ConvolutionComponent::filter_params_, and KALDI_ASSERT.
{
   const ConvolutionComponent *other =
       dynamic_cast<const ConvolutionComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   filter_params_.AddMat(alpha, other->filter_params_);
   bias_params_.AddVec(alpha, other->bias_params_);
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 4355 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::ColRange(), ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kSetZero, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and ConvolutionComponent::Update().
{
   ConvolutionComponent *to_update =
       dynamic_cast<ConvolutionComponent*>(to_update_in);
   const int32 num_x_steps = (1 + (input_x_dim_ - filt_x_dim_) / filt_x_step_),
               num_y_steps = (1 + (input_y_dim_ - filt_y_dim_) / filt_y_step_),
               num_filters = filter_params_.NumRows(),
               num_frames = out_deriv.NumRows(),
               filter_dim = filter_params_.NumCols();
   KALDI_ASSERT(out_deriv.NumRows() == num_frames &&
                out_deriv.NumCols() ==
                (num_filters * num_x_steps * num_y_steps));
   // Compute inderiv patches
   CuMatrix<BaseFloat> in_deriv_patches(num_frames,
                                        num_x_steps * num_y_steps * filter_dim,
                                        kSetZero);
   std::vector<CuSubMatrix<BaseFloat>* > patch_deriv_batch, out_deriv_batch,
       filter_params_batch;
   CuSubMatrix<BaseFloat>* filter_params_elem = new CuSubMatrix<BaseFloat>(
       filter_params_, 0, filter_params_.NumRows(), 0, filter_params_.NumCols());
   for (int32 x_step = 0; x_step < num_x_steps; x_step++)  {
     for (int32 y_step = 0; y_step < num_y_steps; y_step++)  {
       int32 patch_number = x_step * num_y_steps + y_step;
       patch_deriv_batch.push_back(new CuSubMatrix<BaseFloat>(
               in_deriv_patches.ColRange(
               patch_number * filter_dim, filter_dim)));
       out_deriv_batch.push_back(new CuSubMatrix<BaseFloat>(out_deriv.ColRange(
               patch_number * num_filters, num_filters)));
       filter_params_batch.push_back(filter_params_elem);
     }
   }
   AddMatMatBatched<BaseFloat>(1.0, patch_deriv_batch,
                               out_deriv_batch, kNoTrans,
                               filter_params_batch, kNoTrans, 0.0);
   if (in_deriv) {
     // combine the derivatives from the individual input deriv patches
     // to compute input deriv matrix
     InderivPatchesToInderiv(in_deriv_patches, in_deriv);
   }
   if (to_update != NULL)  {
     to_update->Update(debug_info, in_value, out_deriv, out_deriv_batch);
   }
   // release memory
   delete filter_params_elem;
   for (int32 p = 0; p < patch_deriv_batch.size(); p++) {
     delete patch_deriv_batch[p];
     delete out_deriv_batch[p];
   }
 }
BiasParams()
const CuVector<BaseFloat>& BiasParams () const inline
Definition at line 2089 of file nnet-simple-component.h.
 { return bias_params_; }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 4565 of file nnet-simple-component.cc.
References ConvolutionComponent::ConvolutionComponent().
{
   ConvolutionComponent *ans = new ConvolutionComponent(*this);
   return ans;
 }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 4558 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, ConvolutionComponent::filter_params_, kaldi::kTrans, kaldi::TraceMatMat(), and kaldi::VecVec().
{
   const ConvolutionComponent *other =
       dynamic_cast<const ConvolutionComponent*>(&other_in);
   return TraceMatMat(filter_params_, other->filter_params_, kTrans)
          + VecVec(bias_params_, other->bias_params_);
 }
InderivPatchesToInderiv()
void InderivPatchesToInderiv (const CuMatrix< BaseFloat > & in_deriv_patches, CuMatrixBase< BaseFloat > * in_deriv) const private
Definition at line 4299 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddCols(), ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::input_vectorization_, ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, ConvolutionComponent::input_z_dim_, KALDI_ASSERT, ConvolutionComponent::kYzx, ConvolutionComponent::kZyx, CuMatrixBase< Real >::NumCols(), kaldi::nnet3::RearrangeIndexes(), kaldi::nnet3::YzxVectorIndex(), and kaldi::nnet3::ZyxVectorIndex().
Referenced by ConvolutionComponent::Backprop().
{
   const int32 num_x_steps = (1 + (input_x_dim_ - filt_x_dim_) / filt_x_step_),
               num_y_steps = (1 + (input_y_dim_ - filt_y_dim_) / filt_y_step_),
               filt_x_step = filt_x_step_,
               filt_y_step = filt_y_step_,
               filt_x_dim = filt_x_dim_,
               filt_y_dim = filt_y_dim_,
               input_x_dim = input_x_dim_,
               input_y_dim = input_y_dim_,
               input_z_dim = input_z_dim_,
               filter_dim = filter_params_.NumCols();
   // Compute the reverse column_map from the matrix with input
   // derivative patches to input derivative matrix
   std::vector<std::vector<int32> > reverse_column_map(in_deriv->NumCols());
   int32 rev_col_map_size = reverse_column_map.size();
   for (int32 x_step = 0; x_step < num_x_steps; x_step++) {
     for (int32 y_step = 0; y_step < num_y_steps; y_step++)  {
       int32 patch_number = x_step * num_y_steps + y_step;
       int32 patch_start_index = patch_number * filter_dim;
       for (int32 x = 0, index = patch_start_index; x < filt_x_dim; x++)  {
         for (int32 y = 0; y < filt_y_dim; y++)  {
           for (int32 z = 0; z < input_z_dim; z++, index++)  {
             int32 vector_index;
             if (input_vectorization_ == kZyx)  {
               vector_index = ZyxVectorIndex(x_step * filt_x_step + x,
                                             y_step * filt_y_step + y, z,
                                             input_x_dim, input_y_dim,
                                             input_z_dim);
             } else {
               KALDI_ASSERT(input_vectorization_ == kYzx);
               vector_index = YzxVectorIndex(x_step * filt_x_step + x,
                                             y_step * filt_y_step + y, z,
                                             input_x_dim, input_y_dim,
                                             input_z_dim);
             }
             KALDI_ASSERT(vector_index < rev_col_map_size);
             reverse_column_map[vector_index].push_back(index);
           }
         }
       }
     }
   }
   std::vector<std::vector<int32> > rearranged_column_map;
   RearrangeIndexes(reverse_column_map, &rearranged_column_map);
   for (int32 p = 0; p < rearranged_column_map.size(); p++) {
     CuArray<int32> cu_cols(rearranged_column_map[p]);
     in_deriv->AddCols(in_deriv_patches, cu_cols);
   }
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 4059 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, UpdatableComponent::Info(), ConvolutionComponent::input_vectorization_, ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, ConvolutionComponent::input_z_dim_, and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info()
          << ", input-x-dim=" << input_x_dim_
          << ", input-y-dim=" << input_y_dim_
          << ", input-z-dim=" << input_z_dim_
          << ", filt-x-dim=" << filt_x_dim_
          << ", filt-y-dim=" << filt_y_dim_
          << ", filt-x-step=" << filt_x_step_
          << ", filt-y-step=" << filt_y_step_
          << ", input-vectorization=" << input_vectorization_
          << ", num-filters=" << filter_params_.NumRows();
   PrintParameterStats(stream, "filter-params", filter_params_);
   PrintParameterStats(stream, "bias-params", bias_params_, true);
   return stream.str();
 }
Init() [1/2]
void Init (int32 input_x_dim, int32 input_y_dim, int32 input_z_dim, int32 filt_x_dim, int32 filt_y_dim, int32 filt_x_step, int32 filt_y_step, int32 num_filters, TensorVectorizationType input_vectorization, BaseFloat param_stddev, BaseFloat bias_stddev)
Definition at line 4006 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::input_vectorization_, ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, ConvolutionComponent::input_z_dim_, and KALDI_ASSERT.
Referenced by ConvolutionComponent::InitFromConfig().
{
   input_x_dim_ = input_x_dim;
   input_y_dim_ = input_y_dim;
   input_z_dim_ = input_z_dim;
   filt_x_dim_ = filt_x_dim;
   filt_y_dim_ = filt_y_dim;
   filt_x_step_ = filt_x_step;
   filt_y_step_ = filt_y_step;
   input_vectorization_ = input_vectorization;
   KALDI_ASSERT((input_x_dim_ - filt_x_dim_) % filt_x_step_ == 0);
   KALDI_ASSERT((input_y_dim_ - filt_y_dim_) % filt_y_step_ == 0);
   int32 filter_dim = filt_x_dim_ * filt_y_dim_ * input_z_dim_;
   filter_params_.Resize(num_filters, filter_dim);
   bias_params_.Resize(num_filters);
   KALDI_ASSERT(param_stddev >= 0.0 && bias_stddev >= 0.0);
   filter_params_.SetRandn();
   filter_params_.Scale(param_stddev);
   bias_params_.SetRandn();
   bias_params_.Scale(bias_stddev);
 }
Init() [2/2]
void Init (int32 input_x_dim, int32 input_y_dim, int32 input_z_dim, int32 filt_x_dim, int32 filt_y_dim, int32 filt_x_step, int32 filt_y_step, TensorVectorizationType input_vectorization, std::string matrix_filename)
Definition at line 4033 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::input_vectorization_, ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, ConvolutionComponent::input_z_dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Range(), and kaldi::ReadKaldiObject().
{
   input_x_dim_ = input_x_dim;
   input_y_dim_ = input_y_dim;
   input_z_dim_ = input_z_dim;
   filt_x_dim_ = filt_x_dim;
   filt_y_dim_ = filt_y_dim;
   filt_x_step_ = filt_x_step;
   filt_y_step_ = filt_y_step;
   input_vectorization_ = input_vectorization;
   CuMatrix<BaseFloat> mat;
   ReadKaldiObject(matrix_filename, &mat);
   int32 filter_dim = (filt_x_dim_ * filt_y_dim_ * input_z_dim_);
   int32 num_filters = mat.NumRows();
   KALDI_ASSERT(mat.NumCols() == (filter_dim + 1));
   filter_params_.Resize(num_filters, filter_dim);
   bias_params_.Resize(num_filters);
   filter_params_.CopyFromMat(mat.Range(0, num_filters, 0, filter_dim));
   bias_params_.CopyColFromMat(mat, filter_dim);
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 4077 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), ConvolutionComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), KALDI_ERR, ConvolutionComponent::kYzx, ConvolutionComponent::kZyx, ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   bool ok = true;
   std::string matrix_filename;
   int32 input_x_dim = -1, input_y_dim = -1, input_z_dim = -1,
         filt_x_dim = -1, filt_y_dim = -1,
         filt_x_step = -1, filt_y_step = -1,
         num_filters = -1;
   std::string input_vectorization_order = "zyx";
   InitLearningRatesFromConfig(cfl);
   ok = ok && cfl->GetValue("input-x-dim", &input_x_dim);
   ok = ok && cfl->GetValue("input-y-dim", &input_y_dim);
   ok = ok && cfl->GetValue("input-z-dim", &input_z_dim);
   ok = ok && cfl->GetValue("filt-x-dim", &filt_x_dim);
   ok = ok && cfl->GetValue("filt-y-dim", &filt_y_dim);
   ok = ok && cfl->GetValue("filt-x-step", &filt_x_step);
   ok = ok && cfl->GetValue("filt-y-step", &filt_y_step);
   if (!ok)
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
   // optional argument
   TensorVectorizationType input_vectorization;
   cfl->GetValue("input-vectorization-order", &input_vectorization_order);
   if (input_vectorization_order.compare("zyx") == 0) {
     input_vectorization = kZyx;
   } else if (input_vectorization_order.compare("yzx") == 0) {
     input_vectorization = kYzx;
   } else {
     KALDI_ERR << "Unknown or unsupported input vectorization order "
               << input_vectorization_order
               << " accepted candidates are 'yzx' and 'zyx'";
   }
   if (cfl->GetValue("matrix", &matrix_filename)) {
     // initialize from prefined parameter matrix
     Init(input_x_dim, input_y_dim, input_z_dim,
          filt_x_dim, filt_y_dim,
          filt_x_step, filt_y_step,
          input_vectorization,
          matrix_filename);
   } else {
     ok = ok && cfl->GetValue("num-filters", &num_filters);
     if (!ok)
       KALDI_ERR << "Bad initializer " << cfl->WholeLine();
     // initialize from configuration
     int32 filter_input_dim = filt_x_dim * filt_y_dim * input_z_dim;
     BaseFloat param_stddev = 1.0 / std::sqrt(filter_input_dim), bias_stddev = 1.0;
     cfl->GetValue("param-stddev", &param_stddev);
     cfl->GetValue("bias-stddev", &bias_stddev);
     Init(input_x_dim, input_y_dim, input_z_dim,
          filt_x_dim, filt_y_dim, filt_x_step, filt_y_step, num_filters,
          input_vectorization, param_stddev, bias_stddev);
   }
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   if (!ok)
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
 }
InputDim()
int32 InputDim () const virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 3993 of file nnet-simple-component.cc.
References ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, and ConvolutionComponent::input_z_dim_.
{
   return input_x_dim_ * input_y_dim_ * input_z_dim_;
 }
InputToInputPatches()
void InputToInputPatches (const CuMatrixBase< BaseFloat > & in, CuMatrix< BaseFloat > * patches) const private
Definition at line 4157 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyCols(), ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::input_vectorization_, ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, ConvolutionComponent::input_z_dim_, KALDI_ASSERT, ConvolutionComponent::kYzx, ConvolutionComponent::kZyx, CuMatrixBase< Real >::NumCols(), kaldi::nnet3::YzxVectorIndex(), and kaldi::nnet3::ZyxVectorIndex().
Referenced by ConvolutionComponent::Propagate(), and ConvolutionComponent::Update().
{
   int32 num_x_steps = (1 + (input_x_dim_ - filt_x_dim_) / filt_x_step_);
   int32 num_y_steps = (1 + (input_y_dim_ - filt_y_dim_) / filt_y_step_);
   const int32 filt_x_step = filt_x_step_,
               filt_y_step = filt_y_step_,
               filt_x_dim = filt_x_dim_,
               filt_y_dim = filt_y_dim_,
               input_x_dim = input_x_dim_,
               input_y_dim = input_y_dim_,
               input_z_dim = input_z_dim_,
               filter_dim = filter_params_.NumCols();
   std::vector<int32> column_map(patches->NumCols());
   int32 column_map_size = column_map.size();
   for (int32 x_step = 0; x_step < num_x_steps; x_step++) {
     for (int32 y_step = 0; y_step < num_y_steps; y_step++)  {
       int32 patch_number = x_step * num_y_steps + y_step;
       int32 patch_start_index = patch_number * filter_dim;
       for (int32 x = 0, index = patch_start_index; x < filt_x_dim; x++)  {
         for (int32 y = 0; y < filt_y_dim; y++)  {
           for (int32 z = 0; z < input_z_dim; z++, index++)  {
             KALDI_ASSERT(index < column_map_size);
             if (input_vectorization_ == kZyx)  {
               column_map[index] = ZyxVectorIndex(x_step * filt_x_step + x,
                                                  y_step * filt_y_step + y, z,
                                                  input_x_dim, input_y_dim,
                                                  input_z_dim);
             } else if (input_vectorization_ == kYzx)  {
               column_map[index] = YzxVectorIndex(x_step * filt_x_step + x,
                                                   y_step * filt_y_step + y, z,
                                                   input_x_dim, input_y_dim,
                                                   input_z_dim);
             }
           }
         }
       }
     }
   }
   CuArray<int32> cu_cols(column_map);
   patches->CopyCols(in, cu_cols);
 }
LinearParams()
const CuMatrix<BaseFloat>& LinearParams () const inline
Definition at line 2090 of file nnet-simple-component.h.
References PnormComponent::Init().
 { return filter_params_; }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 4587 of file nnet-simple-component.cc.
References ConvolutionComponent::filter_params_.
Referenced by ConvolutionComponent::UnVectorize(), and ConvolutionComponent::Vectorize().
{
   return (filter_params_.NumCols() + 1) * filter_params_.NumRows();
 }
operator=()
const ConvolutionComponent& operator= (const ConvolutionComponent & other) private
OutputDim()
int32 OutputDim () const virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 3998 of file nnet-simple-component.cc.
References ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::input_x_dim_, and ConvolutionComponent::input_y_dim_.
{
   int32 num_x_steps = (1 + (input_x_dim_ - filt_x_dim_) / filt_x_step_);
   int32 num_y_steps = (1 + (input_y_dim_ - filt_y_dim_) / filt_y_step_);
   int32 num_filters = filter_params_.NumRows();
   return num_x_steps * num_y_steps * num_filters;
 }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 4570 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, ConvolutionComponent::filter_params_, CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
{
   CuMatrix<BaseFloat> temp_filter_params(filter_params_);
   temp_filter_params.SetRandn();
   filter_params_.AddMat(stddev, temp_filter_params);
   CuVector<BaseFloat> temp_bias_params(bias_params_);
   temp_bias_params.SetRandn();
   bias_params_.AddVec(stddev, temp_bias_params);
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 4204 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddVecToRows(), ConvolutionComponent::bias_params_, CuMatrixBase< Real >::ColRange(), ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, ConvolutionComponent::InputToInputPatches(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
   const int32 num_x_steps = (1 + (input_x_dim_ - filt_x_dim_) / filt_x_step_),
               num_y_steps = (1 + (input_y_dim_ - filt_y_dim_) / filt_y_step_),
               num_filters = filter_params_.NumRows(),
               num_frames = in.NumRows(),
               filter_dim = filter_params_.NumCols();
   KALDI_ASSERT((*out).NumRows() == num_frames &&
                (*out).NumCols() == (num_filters * num_x_steps * num_y_steps));
   CuMatrix<BaseFloat> patches(num_frames,
                               num_x_steps * num_y_steps * filter_dim,
                               kUndefined);
   InputToInputPatches(in, &patches);
   CuSubMatrix<BaseFloat>* filter_params_elem = new CuSubMatrix<BaseFloat>(
       filter_params_, 0, filter_params_.NumRows(), 0, filter_params_.NumCols());
   std::vector<CuSubMatrix<BaseFloat>* > tgt_batch, patch_batch,
       filter_params_batch;
   for (int32 x_step = 0; x_step < num_x_steps; x_step++)  {
     for (int32 y_step = 0; y_step < num_y_steps; y_step++)  {
       int32 patch_number = x_step * num_y_steps + y_step;
       tgt_batch.push_back(new CuSubMatrix<BaseFloat>(
               out->ColRange(patch_number * num_filters, num_filters)));
       patch_batch.push_back(new CuSubMatrix<BaseFloat>(
               patches.ColRange(patch_number * filter_dim, filter_dim)));
       filter_params_batch.push_back(filter_params_elem);
       tgt_batch[patch_number]->AddVecToRows(1.0, bias_params_, 1.0); // add bias
     }
   }
   // apply all filters
   AddMatMatBatched<BaseFloat>(1.0, tgt_batch, patch_batch,
                               kNoTrans, filter_params_batch,
                               kTrans, 1.0);
   // release memory
   delete filter_params_elem;
   for (int32 p = 0; p < tgt_batch.size(); p++) {
     delete tgt_batch[p];
     delete patch_batch[p];
   }
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 2050 of file nnet-simple-component.h.
References Component::Add(), PnormComponent::Backprop(), PnormComponent::Copy(), kaldi::nnet3::DotProduct(), kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kPropagateAdds, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kUpdatableComponent, kaldi::nnet3::NumParameters(), kaldi::nnet3::PerturbParams(), PnormComponent::Propagate(), PnormComponent::Read(), Component::Scale(), and PnormComponent::Write().
{
     return kSimpleComponent|kUpdatableComponent|kBackpropNeedsInput|
            kBackpropAdds|kPropagateAdds;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 4496 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, kaldi::nnet3::ExpectToken(), ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::input_vectorization_, ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, ConvolutionComponent::input_z_dim_, UpdatableComponent::is_gradient_, KALDI_ASSERT, kaldi::ReadBasicType(), kaldi::ReadToken(), and UpdatableComponent::ReadUpdatableCommon().
{
   ReadUpdatableCommon(is, binary);  // Read opening tag and learning rate.
   ExpectToken(is, binary, "<InputXDim>");
   ReadBasicType(is, binary, &input_x_dim_);
   ExpectToken(is, binary, "<InputYDim>");
   ReadBasicType(is, binary, &input_y_dim_);
   ExpectToken(is, binary, "<InputZDim>");
   ReadBasicType(is, binary, &input_z_dim_);
   ExpectToken(is, binary, "<FiltXDim>");
   ReadBasicType(is, binary, &filt_x_dim_);
   ExpectToken(is, binary, "<FiltYDim>");
   ReadBasicType(is, binary, &filt_y_dim_);
   ExpectToken(is, binary, "<FiltXStep>");
   ReadBasicType(is, binary, &filt_x_step_);
   ExpectToken(is, binary, "<FiltYStep>");
   ReadBasicType(is, binary, &filt_y_step_);
   ExpectToken(is, binary, "<InputVectorization>");
   int32 input_vectorization;
   ReadBasicType(is, binary, &input_vectorization);
   input_vectorization_ = static_cast<TensorVectorizationType>(input_vectorization);
   ExpectToken(is, binary, "<FilterParams>");
   filter_params_.Read(is, binary);
   ExpectToken(is, binary, "<BiasParams>");
   bias_params_.Read(is, binary);
   std::string tok;
   ReadToken(is, binary, &tok);
   if (tok == "<IsGradient>") {
     ReadBasicType(is, binary, &is_gradient_);
     ExpectToken(is, binary, "</ConvolutionComponent>");
   } else {
     is_gradient_ = false;
     KALDI_ASSERT(tok == "</ConvolutionComponent>");
   }
 }
Resize()
void Resize (int32 input_dim, int32 output_dim)
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 4249 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, and ConvolutionComponent::filter_params_.
{
   if (scale == 0.0) {
     filter_params_.SetZero();
     bias_params_.SetZero();
   } else {
     filter_params_.Scale(scale);
     bias_params_.Scale(scale);
   }
 }
SetParams()
void SetParams (const VectorBase< BaseFloat > & bias, const MatrixBase< BaseFloat > & filter)
Definition at line 4580 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, ConvolutionComponent::filter_params_, and KALDI_ASSERT.
{
   bias_params_ = bias;
   filter_params_ = filter;
   KALDI_ASSERT(bias_params_.Dim() == filter_params_.NumRows());
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 2049 of file nnet-simple-component.h.
 { return "ConvolutionComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 4597 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, VectorBase< Real >::Dim(), ConvolutionComponent::filter_params_, KALDI_ASSERT, ConvolutionComponent::NumParameters(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params.Dim() == this->NumParameters());
   int32 num_filter_params = filter_params_.NumCols() * filter_params_.NumRows();
   filter_params_.CopyRowsFromVec(params.Range(0, num_filter_params));
   bias_params_.CopyFromVec(params.Range(num_filter_params, bias_params_.Dim()));
 }
Update() [1/2]
void Update (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv, const std::vector< CuSubMatrix< BaseFloat > *> & out_deriv_batch)
Definition at line 4422 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatBlocks(), CuVectorBase< Real >::AddRowSumMat(), ConvolutionComponent::bias_params_, CuMatrixBase< Real >::ColRange(), ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, ConvolutionComponent::InputToInputPatches(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kSetZero, kaldi::kTrans, kaldi::kUndefined, UpdatableComponent::learning_rate_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuVector< Real >::Resize(), and CuMatrix< Real >::Resize().
Referenced by ConvolutionComponent::Backprop().
{
   // useful dims
   const int32 num_x_steps = (1 + (input_x_dim_ - filt_x_dim_) / filt_x_step_),
               num_y_steps = (1 + (input_y_dim_ - filt_y_dim_) / filt_y_step_),
               num_filters = filter_params_.NumRows(),
               num_frames = out_deriv.NumRows(),
               filter_dim = filter_params_.NumCols();
   KALDI_ASSERT(out_deriv.NumRows() == num_frames &&
                out_deriv.NumCols() ==
                (num_filters * num_x_steps * num_y_steps));
   CuMatrix<BaseFloat> filters_grad;
   CuVector<BaseFloat> bias_grad;
   CuMatrix<BaseFloat> input_patches(num_frames,
                                     filter_dim * num_x_steps * num_y_steps,
                                     kUndefined);
   InputToInputPatches(in_value, &input_patches);
   filters_grad.Resize(num_filters, filter_dim, kSetZero); // reset
   bias_grad.Resize(num_filters, kSetZero); // reset
   // create a single large matrix holding the smaller matrices
   // from the vector container filters_grad_batch along the rows
   CuMatrix<BaseFloat> filters_grad_blocks_batch(
       num_x_steps * num_y_steps * filters_grad.NumRows(),
       filters_grad.NumCols());
   std::vector<CuSubMatrix<BaseFloat>* > filters_grad_batch, input_patch_batch;
   for (int32 x_step = 0; x_step < num_x_steps; x_step++)  {
     for (int32 y_step = 0; y_step < num_y_steps; y_step++)  {
       int32 patch_number = x_step * num_y_steps + y_step;
       filters_grad_batch.push_back(new CuSubMatrix<BaseFloat>(
           filters_grad_blocks_batch.RowRange(
               patch_number * filters_grad.NumRows(), filters_grad.NumRows())));
       input_patch_batch.push_back(new CuSubMatrix<BaseFloat>(
               input_patches.ColRange(patch_number * filter_dim, filter_dim)));
     }
   }
   AddMatMatBatched<BaseFloat>(1.0, filters_grad_batch, out_deriv_batch, kTrans,
                               input_patch_batch, kNoTrans, 1.0);
   // add the row blocks together to filters_grad
   filters_grad.AddMatBlocks(1.0, filters_grad_blocks_batch);
   // create a matrix holding the col blocks sum of out_deriv
   CuMatrix<BaseFloat> out_deriv_col_blocks_sum(out_deriv.NumRows(),
                                                num_filters);
   // add the col blocks together to out_deriv_col_blocks_sum
   out_deriv_col_blocks_sum.AddMatBlocks(1.0, out_deriv);
   bias_grad.AddRowSumMat(1.0, out_deriv_col_blocks_sum, 1.0);
   // release memory
   for (int32 p = 0; p < input_patch_batch.size(); p++) {
     delete filters_grad_batch[p];
     delete input_patch_batch[p];
   }
   //
   // update
   //
   filter_params_.AddMat(learning_rate_, filters_grad);
   bias_params_.AddVec(learning_rate_, bias_grad);
 }
Update() [2/2]
void Update (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv)
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 4591 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, VectorBase< Real >::Dim(), ConvolutionComponent::filter_params_, KALDI_ASSERT, ConvolutionComponent::NumParameters(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params->Dim() == this->NumParameters());
   int32 num_filter_params = filter_params_.NumCols() * filter_params_.NumRows();
   params->Range(0, num_filter_params).CopyRowsFromMat(filter_params_);
   params->Range(num_filter_params, bias_params_.Dim()).CopyFromVec(bias_params_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 4531 of file nnet-simple-component.cc.
References ConvolutionComponent::bias_params_, ConvolutionComponent::filt_x_dim_, ConvolutionComponent::filt_x_step_, ConvolutionComponent::filt_y_dim_, ConvolutionComponent::filt_y_step_, ConvolutionComponent::filter_params_, ConvolutionComponent::input_vectorization_, ConvolutionComponent::input_x_dim_, ConvolutionComponent::input_y_dim_, ConvolutionComponent::input_z_dim_, UpdatableComponent::is_gradient_, kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // write opening tag and learning rate.
   WriteToken(os, binary, "<InputXDim>");
   WriteBasicType(os, binary, input_x_dim_);
   WriteToken(os, binary, "<InputYDim>");
   WriteBasicType(os, binary, input_y_dim_);
   WriteToken(os, binary, "<InputZDim>");
   WriteBasicType(os, binary, input_z_dim_);
   WriteToken(os, binary, "<FiltXDim>");
   WriteBasicType(os, binary, filt_x_dim_);
   WriteToken(os, binary, "<FiltYDim>");
   WriteBasicType(os, binary, filt_y_dim_);
   WriteToken(os, binary, "<FiltXStep>");
   WriteBasicType(os, binary, filt_x_step_);
   WriteToken(os, binary, "<FiltYStep>");
   WriteBasicType(os, binary, filt_y_step_);
   WriteToken(os, binary, "<InputVectorization>");
   WriteBasicType(os, binary, static_cast<int32>(input_vectorization_));
   WriteToken(os, binary, "<FilterParams>");
   filter_params_.Write(os, binary);
   WriteToken(os, binary, "<BiasParams>");
   bias_params_.Write(os, binary);
   WriteToken(os, binary, "<IsGradient>");
   WriteBasicType(os, binary, is_gradient_);
   WriteToken(os, binary, "</ConvolutionComponent>");
 }
Member Data Documentation
bias_params_
CuVector<BaseFloat> bias_params_ private
Definition at line 2152 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::Add(), ConvolutionComponent::DotProduct(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::PerturbParams(), ConvolutionComponent::Propagate(), ConvolutionComponent::Read(), ConvolutionComponent::Scale(), ConvolutionComponent::SetParams(), ConvolutionComponent::UnVectorize(), ConvolutionComponent::Update(), ConvolutionComponent::Vectorize(), and ConvolutionComponent::Write().
filt_x_dim_
int32 filt_x_dim_ private
Definition at line 2124 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::Backprop(), ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::InputToInputPatches(), ConvolutionComponent::OutputDim(), ConvolutionComponent::Propagate(), ConvolutionComponent::Read(), ConvolutionComponent::Update(), and ConvolutionComponent::Write().
filt_x_step_
int32 filt_x_step_ private
Definition at line 2131 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::Backprop(), ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::InputToInputPatches(), ConvolutionComponent::OutputDim(), ConvolutionComponent::Propagate(), ConvolutionComponent::Read(), ConvolutionComponent::Update(), and ConvolutionComponent::Write().
filt_y_dim_
int32 filt_y_dim_ private
Definition at line 2126 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::Backprop(), ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::InputToInputPatches(), ConvolutionComponent::OutputDim(), ConvolutionComponent::Propagate(), ConvolutionComponent::Read(), ConvolutionComponent::Update(), and ConvolutionComponent::Write().
filt_y_step_
int32 filt_y_step_ private
Definition at line 2135 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::Backprop(), ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::InputToInputPatches(), ConvolutionComponent::OutputDim(), ConvolutionComponent::Propagate(), ConvolutionComponent::Read(), ConvolutionComponent::Update(), and ConvolutionComponent::Write().
filter_params_
CuMatrix<BaseFloat> filter_params_ private
Definition at line 2144 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::Add(), ConvolutionComponent::Backprop(), ConvolutionComponent::DotProduct(), ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::InputToInputPatches(), ConvolutionComponent::NumParameters(), ConvolutionComponent::OutputDim(), ConvolutionComponent::PerturbParams(), ConvolutionComponent::Propagate(), ConvolutionComponent::Read(), ConvolutionComponent::Scale(), ConvolutionComponent::SetParams(), ConvolutionComponent::UnVectorize(), ConvolutionComponent::Update(), ConvolutionComponent::Vectorize(), and ConvolutionComponent::Write().
input_vectorization_
TensorVectorizationType input_vectorization_ private
Definition at line 2141 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::InputToInputPatches(), ConvolutionComponent::Read(), and ConvolutionComponent::Write().
input_x_dim_
int32 input_x_dim_ private
Definition at line 2114 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::Backprop(), ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::InputDim(), MaxpoolingComponent::InputDim(), ConvolutionComponent::InputToInputPatches(), ConvolutionComponent::OutputDim(), ConvolutionComponent::Propagate(), ConvolutionComponent::Read(), ConvolutionComponent::Update(), and ConvolutionComponent::Write().
input_y_dim_
int32 input_y_dim_ private
Definition at line 2117 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::Backprop(), ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::InputDim(), MaxpoolingComponent::InputDim(), ConvolutionComponent::InputToInputPatches(), ConvolutionComponent::OutputDim(), ConvolutionComponent::Propagate(), ConvolutionComponent::Read(), ConvolutionComponent::Update(), and ConvolutionComponent::Write().
input_z_dim_
int32 input_z_dim_ private
Definition at line 2120 of file nnet-simple-component.h.
Referenced by ConvolutionComponent::InderivPatchesToInderiv(), ConvolutionComponent::Info(), ConvolutionComponent::Init(), ConvolutionComponent::InputDim(), MaxpoolingComponent::InputDim(), ConvolutionComponent::InputToInputPatches(), ConvolutionComponent::Read(), and ConvolutionComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc