Kaldi: TxpCex Class Reference
TxpCex Class Reference
Linguistic context extraction: Converts output from text normalisation into full context model names.
#include <mod-cex.h>
Public Member Functions
TxpCex ()
~TxpCex ()
bool Init (const TxpParseOptions &opts)
Load voice data.
bool Process (pugi::xml_document *input)
Process the XML, modifying the XML to reflect linguistic information.
bool IsSptPauseHandling ()
Returns true if the system is splitting mid phrase pauses to allow spurt processing of model names.
Public Member Functions inherited from TxpModule
TxpModule (const std::string &name)
Construct module, also loads tpdb modules in specific instances.
virtual ~TxpModule ()
const std::string GetConfigValue (const std::string &key)
Return a configuration value for this module as a string (rendundant)
const char * GetOptValue (const char *key)
Return an option value for this module as a string.
bool GetConfigValueBool (const std::string &key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
bool GetOptValueBool (const char *key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
const std::string & GetName () const
Get the name of the module.
pugi::xml_node GetHeader (pugi::xml_document *input)
Gets or adds a module header to txpheader.
Private Attributes
TxpCexspec cexspec_
Object containing specification for feature extraction.
TxpCexspecModels models_
Additional Inherited Members
Protected Attributes inherited from TxpModule
const TxpParseOptions * opts_
Options structure for the module.
std::string tpdb_
Directory for text processing database (tpdb) files used by txpxmldata objectys in the module.
Detailed Description
Linguistic context extraction: Converts output from text normalisation into full context model names.
Definition at line 34 of file mod-cex.h.
Constructor & Destructor Documentation
TxpCex()
TxpCex () explicit
Definition at line 23 of file mod-cex.cc.
 : TxpModule("cex") {}
~TxpCex()
~TxpCex ()
Definition at line 25 of file mod-cex.cc.
                 {
 }
Member Function Documentation
Init()
bool Init (const TxpParseOptions & opts) virtual
Load voice data.
Reimplemented from TxpModule.
Definition at line 28 of file mod-cex.cc.
References TxpCex::cexspec_, TxpModule::GetOptValue(), TxpParseOptions::GetTpdb(), TxpCexspec::Init(), TxpModule::opts_, TxpXmlData::Parse(), and TxpModule::tpdb_.
Referenced by main().
{
   opts_ = &opts;
   tpdb_ = opts.GetTpdb();
   cexspec_.Init(opts, std::string(GetOptValue("arch")));
   return cexspec_.Parse(tpdb_);
 }
IsSptPauseHandling()
bool IsSptPauseHandling ()
Returns true if the system is splitting mid phrase pauses to allow spurt processing of model names.
Definition at line 59 of file mod-cex.cc.
References TxpCex::cexspec_, kaldi::CEXSPECPAU_HANDLER_SPURT, and TxpCexspec::GetPauseHandling().
{
   if (cexspec_.GetPauseHandling() == CEXSPECPAU_HANDLER_SPURT) return true;
   return false;
 }
Process()
bool Process (pugi::xml_document * input) virtual
Process the XML, modifying the XML to reflect linguistic information.
Reimplemented from TxpModule.
Definition at line 35 of file mod-cex.cc.
References TxpCexspec::AddPauseNodes(), TxpCex::cexspec_, TxpCexspec::ExtractFeatures(), TxpCexspec::GetFunctionSpec(), TxpModule::GetHeader(), TxpCexspec::GetPauseHandling(), and rnnlm::i.
Referenced by main().
{
   std::string* model = new std::string();
   std::string cexfunctions;
   pugi::xml_node header = GetHeader(input);
   cexspec_.GetFunctionSpec(&header);
   cexspec_.AddPauseNodes(input);
   pugi::xpath_node_set tks =
       input->document_element().select_nodes("//phon");
   tks.sort();
   TxpCexspecContext context(*input,  cexspec_.GetPauseHandling());
   kaldi::int32 i = 0;
   for (pugi::xpath_node_set::const_iterator it = tks.begin();
        it != tks.end();
        ++it, i++, context.Next()) {
     pugi::xml_node phon = (*it).node();
     model->clear();
     cexspec_.ExtractFeatures(context, model);
     phon.text() = model->c_str();
   }
   delete model;
   // should set to error status
   return true;
 }
Member Data Documentation
cexspec_
TxpCexspec cexspec_ private
Object containing specification for feature extraction.
Definition at line 46 of file mod-cex.h.
Referenced by TxpCex::Init(), TxpCex::IsSptPauseHandling(), and TxpCex::Process().
models_
TxpCexspecModels models_ private
Definition at line 47 of file mod-cex.h.
The documentation for this class was generated from the following files:
idlaktxp/mod-cex.h
idlaktxp/mod-cex.cc