Kaldi: SimpleDecoder::Token Class Reference
SimpleDecoder::Token Class Reference
Public Member Functions
Token (const StdArc &arc, BaseFloat acoustic_cost, Token *prev)
bool operator< (const Token &other)
Static Public Member Functions
static void TokenDelete (Token *tok)
Public Attributes
LatticeArc arc_
Token * prev_
int32 ref_count_
double cost_
Detailed Description
Definition at line 93 of file simple-decoder.h.
Constructor & Destructor Documentation
Token()
Token (const StdArc & arc, BaseFloat acoustic_cost, Token * prev) inline
Definition at line 101 of file simple-decoder.h.
References SimpleDecoder::Token::cost_, and SimpleDecoder::Token::ref_count_.
                       : prev_(prev), ref_count_(1) {
       arc_.ilabel = arc.ilabel;
       arc_.olabel = arc.olabel;
       arc_.weight = LatticeWeight(arc.weight.Value(), acoustic_cost);
       arc_.nextstate = arc.nextstate;
       if (prev) {
         prev->ref_count_++;
         cost_ = prev->cost_ + (arc.weight.Value() + acoustic_cost);
       } else {
         cost_ = arc.weight.Value() + acoustic_cost;
       }
     }
Member Function Documentation
operator<()
bool operator< (const Token & other) inline
Definition at line 115 of file simple-decoder.h.
References SimpleDecoder::Token::cost_.
{
       return cost_ > other.cost_;
     }
TokenDelete()
static void TokenDelete (Token * tok) inline static
Definition at line 119 of file simple-decoder.h.
References KALDI_ASSERT, SimpleDecoder::Token::prev_, SimpleDecoder::ProcessEmitting(), SimpleDecoder::ProcessNonemitting(), and SimpleDecoder::Token::ref_count_.
Referenced by SimpleDecoder::ClearToks(), SimpleDecoder::ProcessEmitting(), SimpleDecoder::ProcessNonemitting(), and SimpleDecoder::PruneToks().
{
       while (--tok->ref_count_ == 0) {
         Token *prev = tok->prev_;
         delete tok;
         if (prev == NULL) return;
         else tok = prev;
       }
 #ifdef KALDI_PARANOID
       KALDI_ASSERT(tok->ref_count_ > 0);
 #endif
     }
Member Data Documentation
arc_
LatticeArc arc_
Definition at line 95 of file simple-decoder.h.
Referenced by SimpleDecoder::GetBestPath(), SimpleDecoder::ProcessEmitting(), and SimpleDecoder::ProcessNonemitting().
cost_
double cost_
Definition at line 100 of file simple-decoder.h.
Referenced by SimpleDecoder::GetBestPath(), SimpleDecoder::Token::operator<(), SimpleDecoder::ProcessEmitting(), SimpleDecoder::ProcessNonemitting(), and SimpleDecoder::Token::Token().
prev_
Token* prev_
Definition at line 98 of file simple-decoder.h.
Referenced by SimpleDecoder::GetBestPath(), and SimpleDecoder::Token::TokenDelete().
ref_count_
int32 ref_count_
Definition at line 99 of file simple-decoder.h.
Referenced by SimpleDecoder::Token::Token(), and SimpleDecoder::Token::TokenDelete().
The documentation for this class was generated from the following file:
decoder/simple-decoder.h