Kaldi: NnetDiscriminativeUpdater Class Reference
NnetDiscriminativeUpdater Class Reference
Public Member Functions
NnetDiscriminativeUpdater (const AmNnet &am_nnet, const TransitionModel &tmodel, const NnetDiscriminativeUpdateOptions &opts, const DiscriminativeNnetExample &eg, Nnet *nnet_to_update, NnetDiscriminativeStats *stats)
void Update ()
void Propagate ()
The forward-through-the-layers part of the computation.
void LatticeComputations ()
Does the parts between Propagate() and Backprop(), that involve forward-backward over the lattice.
void Backprop ()
double GetDiscriminativePosteriors (Posterior *post)
Assuming the lattice already has the correct scores in it, this function does the MPE or MMI forward-backward and puts the resulting discriminative posteriors (which may have positive or negative weight) into "post".
SubMatrix< BaseFloat > GetInputFeatures () const
CuMatrixBase< BaseFloat > & GetOutput ()
Static Public Member Functions
static Int32Pair MakePair (int32 first, int32 second)
Private Types
typedef LatticeArc Arc
typedef Arc::StateId StateId
Private Attributes
const AmNnet & am_nnet_
const TransitionModel & tmodel_
const NnetDiscriminativeUpdateOptions & opts_
const DiscriminativeNnetExample & eg_
Nnet * nnet_to_update_
NnetDiscriminativeStats * stats_
std::vector< ChunkInfo > chunk_info_out_
std::vector< CuMatrix< BaseFloat > > forward_data_
Lattice lat_
CuMatrix< BaseFloat > backward_data_
std::vector< int32 > silence_phones_
Detailed Description
Definition at line 32 of file nnet-compute-discriminative.cc.
Member Typedef Documentation
Arc
typedef LatticeArc Arc private
Definition at line 78 of file nnet-compute-discriminative.cc.
StateId
typedef Arc::StateId StateId private
Definition at line 79 of file nnet-compute-discriminative.cc.
Constructor & Destructor Documentation
NnetDiscriminativeUpdater()
NnetDiscriminativeUpdater (const AmNnet & am_nnet, const TransitionModel & tmodel, const NnetDiscriminativeUpdateOptions & opts, const DiscriminativeNnetExample & eg, Nnet * nnet_to_update, NnetDiscriminativeStats * stats)
Definition at line 101 of file nnet-compute-discriminative.cc.
References NnetDiscriminativeUpdater::am_nnet_, NnetDiscriminativeUpdater::chunk_info_out_, Nnet::ComputeChunkInfo(), NnetDiscriminativeUpdater::eg_, AmNnet::GetNnet(), DiscriminativeNnetExample::input_frames, KALDI_ERR, MatrixBase< Real >::NumRows(), NnetDiscriminativeUpdater::opts_, NnetDiscriminativeUpdater::silence_phones_, NnetDiscriminativeUpdateOptions::silence_phones_str, and kaldi::SplitStringToIntegers().
                                    :
     am_nnet_(am_nnet), tmodel_(tmodel), opts_(opts), eg_(eg),
     nnet_to_update_(nnet_to_update), stats_(stats) {
   if (!SplitStringToIntegers(opts_.silence_phones_str, ":", false,
                              &silence_phones_)) {
     KALDI_ERR << "Bad value for --silence-phones option: "
               << opts_.silence_phones_str;
   }
   const Nnet &nnet = am_nnet_.GetNnet();
   nnet.ComputeChunkInfo(eg_.input_frames.NumRows(), 1, &chunk_info_out_);
 }
Member Function Documentation
Backprop()
void Backprop ()
Definition at line 349 of file nnet-compute-discriminative.cc.
References NnetDiscriminativeUpdater::am_nnet_, Component::Backprop(), NnetDiscriminativeUpdater::backward_data_, NnetDiscriminativeUpdater::chunk_info_out_, NnetDiscriminativeUpdater::forward_data_, Nnet::GetComponent(), AmNnet::GetNnet(), NnetDiscriminativeUpdater::nnet_to_update_, and Nnet::NumComponents().
Referenced by NnetDiscriminativeUpdater::Update().
{
   const Nnet &nnet = am_nnet_.GetNnet();
   for (int32 c = nnet.NumComponents() - 1; c >= 0; c--) {
     const Component &component = nnet.GetComponent(c);
     Component *component_to_update = &(nnet_to_update_->GetComponent(c));
     const CuMatrix<BaseFloat>  &input = forward_data_[c],
                             &output = forward_data_[c+1],
                       &output_deriv = backward_data_;
     CuMatrix<BaseFloat> input_deriv;
     component.Backprop(chunk_info_out_[c], chunk_info_out_[c+1], input, output, output_deriv,
                        component_to_update, &input_deriv);
     backward_data_.Swap(&input_deriv); // backward_data_ = input_deriv.
   }
 }
GetDiscriminativePosteriors()
double GetDiscriminativePosteriors (Posterior * post)
Assuming the lattice already has the correct scores in it, this function does the MPE or MMI forward-backward and puts the resulting discriminative posteriors (which may have positive or negative weight) into "post".
It returns, for MPFE/SMBR, the objective function, or for MMI, the negative of the denominator-lattice log-likelihood.
Definition at line 326 of file nnet-compute-discriminative.cc.
References kaldi::ConvertPosteriorToPdfs(), NnetDiscriminativeUpdateOptions::criterion, NnetDiscriminativeUpdateOptions::drop_frames, NnetDiscriminativeUpdater::eg_, KALDI_ASSERT, NnetDiscriminativeUpdater::lat_, kaldi::LatticeForwardBackwardMmi(), kaldi::LatticeForwardBackwardMpeVariants(), DiscriminativeNnetExample::num_ali, NnetDiscriminativeUpdateOptions::one_silence_class, NnetDiscriminativeUpdater::opts_, NnetDiscriminativeUpdater::silence_phones_, and NnetDiscriminativeUpdater::tmodel_.
Referenced by NnetDiscriminativeUpdater::LatticeComputations(), and NnetDiscriminativeUpdater::Update().
{
   if (opts_.criterion == "mpfe" || opts_.criterion == "smbr") {
     Posterior tid_post;
     double ans;
     ans = LatticeForwardBackwardMpeVariants(tmodel_, silence_phones_, lat_,
                                             eg_.num_ali, opts_.criterion,
                                             opts_.one_silence_class,
                                             &tid_post);
     ConvertPosteriorToPdfs(tmodel_, tid_post, post);
     return ans; // returns the objective function.
   } else {
     KALDI_ASSERT(opts_.criterion == "mmi");
     bool convert_to_pdfs = true, cancel = true;
     // we'll return the denominator-lattice forward backward likelihood,
     // which is one term in the objective function.
     return LatticeForwardBackwardMmi(tmodel_, lat_, eg_.num_ali,
                                      opts_.drop_frames, convert_to_pdfs,
                                      cancel, post);
   }
 }
GetInputFeatures()
SubMatrix< BaseFloat > GetInputFeatures () const
Definition at line 121 of file nnet-compute-discriminative.cc.
References NnetDiscriminativeUpdater::am_nnet_, NnetDiscriminativeUpdater::eg_, AmNnet::GetNnet(), DiscriminativeNnetExample::input_frames, KALDI_ASSERT, DiscriminativeNnetExample::left_context, Nnet::LeftContext(), DiscriminativeNnetExample::num_ali, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and Nnet::RightContext().
Referenced by NnetDiscriminativeUpdater::Propagate(), and NnetDiscriminativeUpdater::Update().
{
   int32 num_frames_output = eg_.num_ali.size();
   int32 eg_left_context = eg_.left_context,
       eg_right_context = eg_.input_frames.NumRows() -
       num_frames_output - eg_left_context;
   KALDI_ASSERT(eg_right_context >= 0);
   const Nnet &nnet = am_nnet_.GetNnet();
   // Make sure the example has enough acoustic left and right
   // context... normally we'll use examples generated using the same model,
   // which will have the exact context, but we enable a mismatch in context as
   // long as it is more, not less.
   KALDI_ASSERT(eg_left_context >= nnet.LeftContext() &&
                eg_right_context >= nnet.RightContext());
   int32 offset = eg_left_context - nnet.LeftContext(),
       num_output_frames =
       num_frames_output + nnet.LeftContext() + nnet.RightContext();
   SubMatrix<BaseFloat> ans(eg_.input_frames, offset, num_output_frames,
                            0, eg_.input_frames.NumCols());
   return ans;
 }
GetOutput()
CuMatrixBase<BaseFloat>& GetOutput () inline
Definition at line 68 of file nnet-compute-discriminative.cc.
References NnetDiscriminativeUpdater::forward_data_.
 { return forward_data_.back(); }
LatticeComputations()
void LatticeComputations ()
Does the parts between Propagate() and Backprop(), that involve forward-backward over the lattice.
Definition at line 178 of file nnet-compute-discriminative.cc.
References NnetDiscriminativeUpdateOptions::acoustic_scale, NnetDiscriminativeUpdater::am_nnet_, NnetDiscriminativeUpdater::backward_data_, NnetDiscriminativeUpdateOptions::boost, fst::ConvertLattice(), NnetDiscriminativeUpdateOptions::criterion, DiscriminativeNnetExample::den_lat, VectorBase< Real >::Dim(), NnetDiscriminativeUpdater::eg_, NnetDiscriminativeUpdater::forward_data_, NnetDiscriminativeUpdater::GetDiscriminativePosteriors(), AmNnet::GetNnet(), rnnlm::i, KALDI_ASSERT, KALDI_ISINF, KALDI_ISNAN, KALDI_WARN, NnetDiscriminativeUpdater::lat_, kaldi::LatticeBoost(), kaldi::LatticeStateTimes(), kaldi::Log(), CuMatrixBase< Real >::Lookup(), NnetDiscriminativeUpdater::MakePair(), DiscriminativeNnetExample::num_ali, CuMatrixBase< Real >::NumCols(), Nnet::NumComponents(), CuMatrixBase< Real >::NumRows(), NnetDiscriminativeUpdater::opts_, AmNnet::Priors(), kaldi::ScalePosterior(), NnetDiscriminativeUpdater::silence_phones_, NnetDiscriminativeUpdater::stats_, NnetDiscriminativeUpdater::tmodel_, NnetDiscriminativeStats::tot_den_objf, NnetDiscriminativeStats::tot_num_count, NnetDiscriminativeStats::tot_num_objf, NnetDiscriminativeStats::tot_t, NnetDiscriminativeStats::tot_t_weighted, TransitionModel::TransitionIdToPdf(), DiscriminativeNnetExample::weight, and LatticeWeightTpl< BaseFloat >::Zero().
Referenced by NnetDiscriminativeUpdater::Update().
{
   ConvertLattice(eg_.den_lat, &lat_); // convert to Lattice.
   TopSort(&lat_); // Topologically sort (required by forward-backward algorithms)
   if (opts_.criterion == "mmi" && opts_.boost != 0.0) {
     BaseFloat max_silence_error = 0.0;
     LatticeBoost(tmodel_, eg_.num_ali, silence_phones_,
                  opts_.boost, max_silence_error, &lat_);
   }
   int32 num_frames = static_cast<int32>(eg_.num_ali.size());
   stats_->tot_t += num_frames;
   stats_->tot_t_weighted += num_frames * eg_.weight;
   const VectorBase<BaseFloat> &priors = am_nnet_.Priors();
   const CuMatrix<BaseFloat> &posteriors = forward_data_.back();
   KALDI_ASSERT(posteriors.NumRows() == num_frames);
   int32 num_pdfs = posteriors.NumCols();
   KALDI_ASSERT(num_pdfs == priors.Dim());
   // We need to look up the posteriors of some pdf-ids in the matrix
   // "posteriors".  Rather than looking them all up using operator (), which is
   // very slow because each lookup involves a separate CUDA call with
   // communication over PciExpress, we look them up all at once using
   // CuMatrix::Lookup().
   // Note: regardless of the criterion, we evaluate the likelihoods in
   // the numerator alignment.  Even though they may be irrelevant to
   // the optimization, they will affect the value of the objective function.
   std::vector<Int32Pair> requested_indexes;
   BaseFloat wiggle_room = 1.3; // value not critical.. it's just 'reserve'
   requested_indexes.reserve(num_frames + wiggle_room * lat_.NumStates());
   if (opts_.criterion == "mmi") { // need numerator probabilities...
     for (int32 t = 0; t < num_frames; t++) {
       int32 tid = eg_.num_ali[t], pdf_id = tmodel_.TransitionIdToPdf(tid);
       KALDI_ASSERT(pdf_id >= 0 && pdf_id < num_pdfs);
       requested_indexes.push_back(MakePair(t, pdf_id));
     }
   }
   std::vector<int32> state_times;
   int32 T = LatticeStateTimes(lat_, &state_times);
   KALDI_ASSERT(T == num_frames);
   StateId num_states = lat_.NumStates();
   for (StateId s = 0; s < num_states; s++) {
     StateId t = state_times[s];
     for (fst::ArcIterator<Lattice> aiter(lat_, s); !aiter.Done(); aiter.Next()) {
       const Arc &arc = aiter.Value();
       if (arc.ilabel != 0) { // input-side has transition-ids, output-side empty
         int32 tid = arc.ilabel, pdf_id = tmodel_.TransitionIdToPdf(tid);
         requested_indexes.push_back(MakePair(t, pdf_id));
       }
     }
   }
   std::vector<BaseFloat> answers;
   CuArray<Int32Pair> cu_requested_indexes(requested_indexes);
   answers.resize(requested_indexes.size());
   posteriors.Lookup(cu_requested_indexes, &(answers[0]));
   int32 num_floored = 0;
   BaseFloat floor_val = 1.0e-20; // floor for posteriors.
   size_t index;
   // Replace "answers" with the vector of scaled log-probs.  If this step takes
   // too much time, we can look at other ways to do it, using the CUDA card.
   for (index = 0; index < answers.size(); index++) {
     BaseFloat post = answers[index];
     if (post < floor_val) {
       post = floor_val;
       num_floored++;
     }
     int32 pdf_id = requested_indexes[index].second;
     BaseFloat pseudo_loglike = Log(post / priors(pdf_id)) * opts_.acoustic_scale;
     KALDI_ASSERT(!KALDI_ISINF(pseudo_loglike) && !KALDI_ISNAN(pseudo_loglike));
     answers[index] = pseudo_loglike;
   }
   if (num_floored > 0) {
     KALDI_WARN << "Floored " << num_floored << " probabilities from nnet.";
   }
   index = 0;
   if (opts_.criterion == "mmi") {
     double tot_num_like = 0.0;
     for (; index < eg_.num_ali.size(); index++)
       tot_num_like += answers[index];
     stats_->tot_num_objf += eg_.weight * tot_num_like;
   }
   // Now put the (scaled) acoustic log-likelihoods in the lattice.
   for (StateId s = 0; s < num_states; s++) {
     for (fst::MutableArcIterator<Lattice> aiter(&lat_, s);
          !aiter.Done(); aiter.Next()) {
       Arc arc = aiter.Value();
       if (arc.ilabel != 0) { // input-side has transition-ids, output-side empty
         arc.weight.SetValue2(-answers[index]);
         index++;
         aiter.SetValue(arc);
       }
     }
     LatticeWeight final = lat_.Final(s);
     if (final != LatticeWeight::Zero()) {
       final.SetValue2(0.0); // make sure no acoustic term in final-prob.
       lat_.SetFinal(s, final);
     }
   }
   KALDI_ASSERT(index == answers.size());
   // Get the MPE or MMI posteriors.
   Posterior post;
   stats_->tot_den_objf += eg_.weight * GetDiscriminativePosteriors(&post);
   ScalePosterior(eg_.weight, &post);
   double tot_num_post = 0.0, tot_den_post = 0.0;
   std::vector<MatrixElement<BaseFloat> > sv_labels;
   sv_labels.reserve(answers.size());
   for (int32 t = 0; t < post.size(); t++) {
     for (int32 i = 0; i < post[t].size(); i++) {
       int32 pdf_id = post[t][i].first;
       BaseFloat weight = post[t][i].second;
       if (weight > 0.0) { tot_num_post += weight; }
       else { tot_den_post -= weight; }
       MatrixElement<BaseFloat> elem = {t, pdf_id, weight};
       sv_labels.push_back(elem);
     }
   }
   stats_->tot_num_count += tot_num_post;
   int32 num_components = am_nnet_.GetNnet().NumComponents();
   const CuMatrix<BaseFloat> &output(forward_data_[num_components]);
   backward_data_.Resize(output.NumRows(), output.NumCols()); // zeroes it.
   { // We don't actually need tot_objf and tot_weight; we have already
     // computed the objective function.
     BaseFloat tot_objf, tot_weight;
     backward_data_.CompObjfAndDeriv(sv_labels, output, &tot_objf, &tot_weight);
     // Now backward_data_ will contan the derivative at the output.
     // Our work here is done..
   }
 }
MakePair()
static Int32Pair MakePair (int32 first, int32 second) inline static
Definition at line 70 of file nnet-compute-discriminative.cc.
References Int32Pair::first, and Int32Pair::second.
Referenced by NnetDiscriminativeUpdater::LatticeComputations().
{
     Int32Pair ans;
     ans.first = first;
     ans.second = second;
     return ans;
   }
Propagate()
void Propagate ()
The forward-through-the-layers part of the computation.
Definition at line 142 of file nnet-compute-discriminative.cc.
References NnetDiscriminativeUpdater::am_nnet_, Component::BackpropNeedsInput(), Component::BackpropNeedsOutput(), NnetDiscriminativeUpdater::chunk_info_out_, NnetDiscriminativeUpdater::eg_, NnetDiscriminativeUpdater::forward_data_, Nnet::GetComponent(), NnetDiscriminativeUpdater::GetInputFeatures(), AmNnet::GetNnet(), NnetDiscriminativeUpdater::nnet_to_update_, MatrixBase< Real >::NumCols(), Nnet::NumComponents(), MatrixBase< Real >::NumRows(), Component::Propagate(), and DiscriminativeNnetExample::spk_info.
Referenced by NnetDiscriminativeUpdater::Update().
{
   const Nnet &nnet = am_nnet_.GetNnet();
   forward_data_.resize(nnet.NumComponents() + 1);
   SubMatrix<BaseFloat> input_feats = GetInputFeatures();
   int32 spk_dim = eg_.spk_info.Dim();
   if (spk_dim == 0) {
     forward_data_[0] = input_feats;
   } else {
     forward_data_[0].Resize(input_feats.NumRows(),
                             input_feats.NumCols() + eg_.spk_info.Dim());
     forward_data_[0].Range(0, input_feats.NumRows(),
                            0, input_feats.NumCols()).CopyFromMat(input_feats);
     forward_data_[0].Range(0, input_feats.NumRows(),
                            input_feats.NumCols(), spk_dim).CopyRowsFromVec(
                                eg_.spk_info);
   }
   for (int32 c = 0; c < nnet.NumComponents(); c++) {
     const Component &component = nnet.GetComponent(c);
     CuMatrix<BaseFloat> &input = forward_data_[c],
         &output = forward_data_[c+1];
     component.Propagate(chunk_info_out_[c] , chunk_info_out_[c+1], input, &output);
     const Component *prev_component = (c == 0 ? NULL :
                                        &(nnet.GetComponent(c-1)));
     bool will_do_backprop = (nnet_to_update_ != NULL),
         keep_last_output = will_do_backprop &&
         ((c>0 && prev_component->BackpropNeedsOutput()) ||
          component.BackpropNeedsInput());
     if (!keep_last_output)
       forward_data_[c].Resize(0, 0); // We won't need this data; save memory.
   }
 }
Update()
void Update () inline
Definition at line 42 of file nnet-compute-discriminative.cc.
References NnetDiscriminativeUpdater::Backprop(), NnetDiscriminativeUpdater::GetDiscriminativePosteriors(), NnetDiscriminativeUpdater::GetInputFeatures(), NnetDiscriminativeUpdater::LatticeComputations(), NnetDiscriminativeUpdater::nnet_to_update_, and NnetDiscriminativeUpdater::Propagate().
Referenced by kaldi::nnet2::NnetDiscriminativeUpdate().
                 {
     Propagate();
     LatticeComputations();
     if (nnet_to_update_ != NULL)
       Backprop();
   }
Member Data Documentation
am_nnet_
const AmNnet& am_nnet_ private
Definition at line 82 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::Backprop(), NnetDiscriminativeUpdater::GetInputFeatures(), NnetDiscriminativeUpdater::LatticeComputations(), NnetDiscriminativeUpdater::NnetDiscriminativeUpdater(), and NnetDiscriminativeUpdater::Propagate().
backward_data_
CuMatrix<BaseFloat> backward_data_ private
Definition at line 95 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::Backprop(), and NnetDiscriminativeUpdater::LatticeComputations().
chunk_info_out_
std::vector<ChunkInfo> chunk_info_out_ private
Definition at line 90 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::Backprop(), NnetDiscriminativeUpdater::NnetDiscriminativeUpdater(), and NnetDiscriminativeUpdater::Propagate().
eg_
const DiscriminativeNnetExample& eg_ private
Definition at line 85 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::GetDiscriminativePosteriors(), NnetDiscriminativeUpdater::GetInputFeatures(), NnetDiscriminativeUpdater::LatticeComputations(), NnetDiscriminativeUpdater::NnetDiscriminativeUpdater(), and NnetDiscriminativeUpdater::Propagate().
forward_data_
std::vector<CuMatrix<BaseFloat> > forward_data_ private
Definition at line 93 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::Backprop(), NnetDiscriminativeUpdater::GetOutput(), NnetDiscriminativeUpdater::LatticeComputations(), and NnetDiscriminativeUpdater::Propagate().
lat_
Lattice lat_ private
Definition at line 94 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::GetDiscriminativePosteriors(), and NnetDiscriminativeUpdater::LatticeComputations().
nnet_to_update_
Nnet* nnet_to_update_ private
Definition at line 86 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::Backprop(), NnetDiscriminativeUpdater::Propagate(), and NnetDiscriminativeUpdater::Update().
opts_
const NnetDiscriminativeUpdateOptions& opts_ private
Definition at line 84 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::GetDiscriminativePosteriors(), NnetDiscriminativeUpdater::LatticeComputations(), and NnetDiscriminativeUpdater::NnetDiscriminativeUpdater().
silence_phones_
std::vector<int32> silence_phones_ private
Definition at line 96 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::GetDiscriminativePosteriors(), NnetDiscriminativeUpdater::LatticeComputations(), and NnetDiscriminativeUpdater::NnetDiscriminativeUpdater().
stats_
NnetDiscriminativeStats* stats_ private
Definition at line 89 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::LatticeComputations().
tmodel_
const TransitionModel& tmodel_ private
Definition at line 83 of file nnet-compute-discriminative.cc.
Referenced by NnetDiscriminativeUpdater::GetDiscriminativePosteriors(), and NnetDiscriminativeUpdater::LatticeComputations().
The documentation for this class was generated from the following file:
nnet2/nnet-compute-discriminative.cc