Kaldi: SigmoidComponent Class Reference
SigmoidComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
SigmoidComponent (const SigmoidComponent &other)
SigmoidComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual Component * Copy () const
Copies component (deep copy).
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
Public Member Functions inherited from NonlinearComponent
NonlinearComponent ()
NonlinearComponent (const NonlinearComponent &other)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual void Read (std::istream &is, bool binary)
We implement Read at this level as it just needs the Type().
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
const CuVector< double > & ValueSum () const
const CuVector< double > & DerivSum () const
double Count () const
Public Member Functions inherited from Component
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
Component ()
virtual ~Component ()
Private Member Functions
void RepairGradients (const CuMatrixBase< BaseFloat > &out_value, CuMatrixBase< BaseFloat > *in_deriv, SigmoidComponent *to_update) const
SigmoidComponent & operator= (const SigmoidComponent &other)
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Types inherited from NonlinearComponent
enum { kUnsetThreshold = -1000 }
Protected Member Functions inherited from NonlinearComponent
void StoreStatsInternal (const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > *deriv=NULL)
void StoreBackpropStats (const CuMatrixBase< BaseFloat > &out_deriv)
const NonlinearComponent & operator= (const NonlinearComponent &other)
Protected Attributes inherited from NonlinearComponent
int32 dim_
int32 block_dim_
CuVector< double > value_sum_
CuVector< double > deriv_sum_
double count_
CuVector< double > oderiv_sumsq_
double oderiv_count_
double num_dims_self_repaired_
double num_dims_processed_
BaseFloat self_repair_lower_threshold_
BaseFloat self_repair_upper_threshold_
BaseFloat self_repair_scale_
Detailed Description
Definition at line 222 of file nnet-simple-component.h.
Constructor & Destructor Documentation
SigmoidComponent() [1/2]
SigmoidComponent (const SigmoidComponent & other) inline explicit
Definition at line 224 of file nnet-simple-component.h.
 : NonlinearComponent(other) { }
SigmoidComponent() [2/2]
SigmoidComponent () inline
Definition at line 225 of file nnet-simple-component.h.
 { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 325 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::DiffSigmoid(), and NonlinearComponent::StoreBackpropStats().
{
   if (in_deriv != NULL) {
     in_deriv->DiffSigmoid(out_value, out_deriv);
     SigmoidComponent *to_update = dynamic_cast<SigmoidComponent*>(to_update_in);
     if (to_update != NULL) {
       RepairGradients(out_value, in_deriv, to_update);
       to_update->StoreBackpropStats(out_deriv);
     }
   }
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 230 of file nnet-simple-component.h.
References PnormComponent::Backprop(), PnormComponent::Propagate(), and Component::StoreStats().
 { return new SigmoidComponent(*this); }
operator=()
SigmoidComponent& operator= (const SigmoidComponent & other) private
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 318 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::Sigmoid().
{
   out->Sigmoid(in);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 227 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropNeedsOutput, kaldi::nnet3::kPropagateInPlace, kaldi::nnet3::kSimpleComponent, and kaldi::nnet3::kStoresStats.
{
     return kSimpleComponent|kBackpropNeedsOutput|kPropagateInPlace|kStoresStats;
   }
RepairGradients()
void RepairGradients (const CuMatrixBase< BaseFloat > & out_value, CuMatrixBase< BaseFloat > * in_deriv, SigmoidComponent * to_update) const private
Definition at line 343 of file nnet-simple-component.cc.
References CuVectorBase< Real >::Add(), CuMatrixBase< Real >::AddMatDiagVec(), CuVectorBase< Real >::AddVec(), CuMatrixBase< Real >::AddVecToRows(), CuMatrixBase< Real >::ApplyHeaviside(), DropoutComponent::dim_, KALDI_ASSERT, KALDI_ERR, kaldi::kNoTrans, NonlinearComponent::num_dims_processed_, NonlinearComponent::num_dims_self_repaired_, kaldi::RandUniform(), and CuVectorBase< Real >::Sum().
{
   KALDI_ASSERT(to_update != NULL);
   // maximum possible derivative of SigmoidComponent is 0.25.
   // the default lower-threshold on the derivative, below which we
   // add a term to the derivative to encourage the inputs to the sigmoid
   // to be closer to zero, is 0.05, which means the derivative is on average
   // 5 times smaller than its maximum possible value.
   BaseFloat default_lower_threshold = 0.05;
   // we use this 'repair_probability' (hardcoded for now) to limit
   // this code to running on about half of the minibatches.
   BaseFloat repair_probability = 0.5;
   to_update->num_dims_processed_ += dim_;
   if (self_repair_scale_ == 0.0 || count_ == 0.0 || deriv_sum_.Dim() != dim_ ||
       RandUniform() > repair_probability)
     return;
   // check that the self-repair scale is in a reasonable range.
   KALDI_ASSERT(self_repair_scale_ > 0.0 && self_repair_scale_ < 0.1);
   BaseFloat unset = kUnsetThreshold; // -1000.0
   BaseFloat lower_threshold = (self_repair_lower_threshold_ == unset ?
                                default_lower_threshold :
                                self_repair_lower_threshold_) *
       count_;
   if (self_repair_upper_threshold_ != unset) {
     KALDI_ERR << "Do not set the self-repair-upper-threshold for sigmoid "
               << "components, it does nothing.";
   }
   // thresholds_vec is actually a 1-row matrix.  (the ApplyHeaviside
   // function isn't defined for vectors).
   CuMatrix<BaseFloat> thresholds(1, dim_);
   CuSubVector<BaseFloat> thresholds_vec(thresholds, 0);
   thresholds_vec.AddVec(-1.0, deriv_sum_);
   thresholds_vec.Add(lower_threshold);
   thresholds.ApplyHeaviside();
   to_update->num_dims_self_repaired_ += thresholds_vec.Sum();
   // At this point, 'thresholds_vec' contains a 1 for each dimension of
   // the output that is 'problematic', i.e. for which the avg-deriv
   // is less than the self-repair lower threshold, and a 0 for
   // each dimension that is not problematic.
   // what we want to do is to add
   // -self_repair_scale_ / repair_probability times (2 * output-valiue - 1.0)
   // to the input derivative for each problematic dimension.
   // Here, 2 * output - 1.0 is a version of the sigmoid that goes from -1.0 to
   // 1.0, like a tanh.  the negative sign is so that for inputs <0, we push them
   // up towards 0, and for inputs >0, we push them down towards 0.
   // Our use of this sigmoid-type function here is just a convenience since
   // we have it available.  We could use just about any function that is positive
   // for inputs < 0 and negative for inputs > 0.
   // We can rearrange the above as: for only the problematic columns,
   //   input-deriv -= 2 * self-repair-scale / repair-probabilty * output
   //   input-deriv +=  self-repair-scale / repair-probabilty
   // which we can write as:
   //   input-deriv -= 2 * self-repair-scale / repair-probabilty * output * thresholds-vec
   //   input-deriv +=  self-repair-scale / repair-probabilty * thresholds-vec
   in_deriv->AddMatDiagVec(-2.0 * self_repair_scale_ / repair_probability,
                           out_value, kNoTrans, thresholds_vec);
   in_deriv->AddVecToRows(self_repair_scale_ / repair_probability,
                          thresholds_vec);
 }
StoreStats()
void StoreStats (const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, void * memo) virtual
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
It only does something for those components that have nonzero Properties()&kStoresStats.
Parameters
[in] in_value The input to the Propagate() function. Note: if the component sets the flag kPropagateInPlace, this should not be used; the empty matrix will be provided here if in-place propagation was used.
[in] out_value The output of the Propagate() function.
[in] memo The 'memo' returned by the Propagate() function; this will usually be NULL.
Reimplemented from Component.
Definition at line 417 of file nnet-simple-component.cc.
References kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), kaldi::RandInt(), and CuMatrixBase< Real >::Set().
{
   // Only store stats about every other minibatch (but on the first minibatch,
   // always store it, which is necessary for the ConsolidateMemory() operation
   // to work correctly.
   if (RandInt(0, 1) == 0 && count_ != 0)
     return;
   // derivative of the nonlinearity is out_value * (1.0 - out_value);
   CuMatrix<BaseFloat> temp_deriv(out_value.NumRows(), out_value.NumCols(),
                                  kUndefined);
   temp_deriv.Set(1.0);
   temp_deriv.AddMat(-1.0, out_value);
   temp_deriv.MulElements(out_value);
   StoreStatsInternal(out_value, &temp_deriv);
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 226 of file nnet-simple-component.h.
 { return "SigmoidComponent"; }
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc