Kaldi: FixedScaleComponent Class Reference
FixedScaleComponent Class Reference
FixedScaleComponent applies a fixed per-element scale; it's similar to the Rescale component in the nnet1 setup (and only needed for nnet1 model conversion).
#include <nnet-simple-component.h>
Public Member Functions
FixedScaleComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual int32 Properties () const
Return bitmask of the component's properties.
void Init (const CuVectorBase< BaseFloat > &scales)
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
const CuVector< BaseFloat > & Scales () const
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedScaleComponent)
Protected Attributes
CuVector< BaseFloat > scales_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
FixedScaleComponent applies a fixed per-element scale; it's similar to the Rescale component in the nnet1 setup (and only needed for nnet1 model conversion).
Definition at line 1097 of file nnet-simple-component.h.
Constructor & Destructor Documentation
FixedScaleComponent()
FixedScaleComponent () inline
Definition at line 1099 of file nnet-simple-component.h.
 { }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 3677 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), and CuMatrixBase< Real >::MulColsVec().
{
   in_deriv->CopyFromMat(out_deriv);  // does nothing if same memory.
   in_deriv->MulColsVec(scales_);
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 3689 of file nnet-simple-component.cc.
References FixedScaleComponent::scales_.
{
   FixedScaleComponent *ans = new FixedScaleComponent();
   ans->scales_ = scales_;
   return ans;
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 3662 of file nnet-simple-component.cc.
References Component::Info(), and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   stream << Component::Info();
   PrintParameterStats(stream, "scales", scales_, true);
   return stream.str();
 }
Init()
void Init (const CuVectorBase< BaseFloat > & scales)
Definition at line 3627 of file nnet-simple-component.cc.
References CuVectorBase< Real >::Dim(), and KALDI_ASSERT.
{
   KALDI_ASSERT(scales.Dim() != 0);
   scales_ = scales;
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 3633 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), FixedAffineComponent::Init(), KALDI_ASSERT, KALDI_ERR, kaldi::ReadKaldiObject(), CuVectorBase< Real >::Set(), CuVectorBase< Real >::SetRandn(), FixedAffineComponent::Type(), and ConfigLine::WholeLine().
{
   std::string filename;
   // Accepts "scales" config (for filename) or "dim" -> random init, for testing.
   if (cfl->GetValue("scales", &filename)) {
     if (cfl->HasUnusedValues())
       KALDI_ERR << "Invalid initializer for layer of type "
                 << Type() << ": \"" << cfl->WholeLine() << "\"";
     CuVector<BaseFloat> vec;
     ReadKaldiObject(filename, &vec);
     Init(vec);
   } else {
     int32 dim;
     BaseFloat scale = 1.0;
     bool scale_is_set = cfl->GetValue("scale", &scale);
     if (!cfl->GetValue("dim", &dim) || cfl->HasUnusedValues())
       KALDI_ERR << "Invalid initializer for layer of type "
                 << Type() << ": \"" << cfl->WholeLine() << "\"";
     KALDI_ASSERT(dim > 0);
     CuVector<BaseFloat> vec(dim);
     if (scale_is_set) {
       vec.Set(scale);
     } else {
       vec.SetRandn();
     }
     Init(vec);
   }
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1112 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsScale().
 { return scales_.Dim(); }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedScaleComponent) protected
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1113 of file nnet-simple-component.h.
References PnormComponent::Backprop(), PnormComponent::Copy(), PnormComponent::Propagate(), PnormComponent::Read(), and PnormComponent::Write().
 { return scales_.Dim(); }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 3669 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), and CuMatrixBase< Real >::MulColsVec().
{
   out->CopyFromMat(in);  // does nothing if same matrix.
   out->MulColsVec(scales_);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1102 of file nnet-simple-component.h.
References PnormComponent::Init(), PnormComponent::InitFromConfig(), kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kPropagateInPlace, and kaldi::nnet3::kSimpleComponent.
{
     return kSimpleComponent|kPropagateInPlace|kBackpropInPlace;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 3703 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), and kaldi::nnet3::ExpectToken().
{
   ExpectOneOrTwoTokens(is, binary, "<FixedScaleComponent>", "<Scales>");
   scales_.Read(is, binary);
   ExpectToken(is, binary, "</FixedScaleComponent>");
 }
Scales()
const CuVector<BaseFloat>& Scales () const inline
Definition at line 1130 of file nnet-simple-component.h.
Referenced by ModelCollapser::CollapseComponentsScale().
 { return scales_; }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 1100 of file nnet-simple-component.h.
References Component::Info().
 { return "FixedScaleComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3696 of file nnet-simple-component.cc.
References kaldi::WriteToken().
{
   WriteToken(os, binary, "<FixedScaleComponent>");
   WriteToken(os, binary, "<Scales>");
   scales_.Write(os, binary);
   WriteToken(os, binary, "</FixedScaleComponent>");
 }
Member Data Documentation
scales_
CuVector<BaseFloat> scales_ protected
Definition at line 1132 of file nnet-simple-component.h.
Referenced by FixedScaleComponent::Copy().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc