Kaldi: TokenVectorHolder Class Reference
TokenVectorHolder Class Reference
"Holder types"
#include <kaldi-holder-inl.h>
Public Types
typedef std::vector< std::string > T
Public Member Functions
TokenVectorHolder ()
void Clear ()
bool Read (std::istream &is)
T & Value ()
void Swap (TokenVectorHolder *other)
bool ExtractRange (const TokenVectorHolder &other, const std::string &range)
Static Public Member Functions
static bool Write (std::ostream &os, bool, const T &t)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (TokenVectorHolder)
Private Attributes
T t_
Detailed Description
Definition at line 695 of file kaldi-holder-inl.h.
Member Typedef Documentation
T
typedef std::vector<std::string> T
Definition at line 697 of file kaldi-holder-inl.h.
Constructor & Destructor Documentation
TokenVectorHolder()
TokenVectorHolder () inline
Definition at line 699 of file kaldi-holder-inl.h.
 { }
Member Function Documentation
Clear()
void Clear () inline
Definition at line 713 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
 { t_.clear(); }
ExtractRange()
bool ExtractRange (const TokenVectorHolder & other, const std::string & range) inline
Definition at line 745 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::KALDI_DISALLOW_COPY_AND_ASSIGN(), and KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 737 of file kaldi-holder-inl.h.
 { return false; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (TokenVectorHolder) private
Read()
bool Read (std::istream & is) inline
Definition at line 717 of file kaldi-holder-inl.h.
References KALDI_WARN, kaldi::SplitStringToVector(), and KaldiObjectHolder< KaldiType >::t_.
{
     t_.clear();
     // there is no binary/non-binary mode.
     std::string line;
     getline(is, line);  // this will discard the \n, if present.
     if (is.fail()) {
       KALDI_WARN << "BasicVectorHolder::Read, error reading line " << (is.eof()
                                                                        ? "[eof]" : "");
       return false;  // probably eof.  fail in any case.
     }
     const char *white_chars = " \t\n\r\f\v";
     SplitStringToVector(line, white_chars, true, &t_);  // true== omit
     // empty strings e.g. between spaces.
     return true;
   }
Swap()
void Swap (TokenVectorHolder * other) inline
Definition at line 741 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_, and TokenVectorHolder::t_.
{
     t_.swap(other->t_);
   }
Value()
T& Value () inline
Definition at line 739 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
 { return t_; }
Write()
static bool Write (std::ostream & os, bool , const T & t) inline static
Definition at line 701 of file kaldi-holder-inl.h.
References kaldi::IsToken(), and KALDI_ASSERT.
                                                       {  // ignore binary-mode
     for (std::vector<std::string>::const_iterator iter = t.begin();
          iter != t.end();
          ++iter) {
       KALDI_ASSERT(IsToken(*iter));  // make sure it's whitespace-free,
       // printable and nonempty.
       os << *iter << ' ';
     }
     os << '\n';
     return os.good();
   }
Member Data Documentation
t_
T t_ private
Definition at line 753 of file kaldi-holder-inl.h.
Referenced by TokenVectorHolder::Swap().
The documentation for this class was generated from the following file:
util/kaldi-holder-inl.h