Kaldi: MultiBasisComponent Class Reference
MultiBasisComponent Class Reference
#include <nnet-multibasis-component.h>
Public Member Functions
MultiBasisComponent (int32 dim_in, int32 dim_out)
~MultiBasisComponent ()
Component * Copy () const
Copy component (deep copy),.
ComponentType GetType () const
Get Type Identification of the component,.
void InitData (std::istream &is)
Initialize the content of the component by the 'line' from the prototype,.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
Nnet & GetBasis (int32 id)
const Nnet & GetBasis (int32 id) const
int32 NumParams () const
Number of trainable parameters,.
void GetGradient (VectorBase< BaseFloat > *gradient) const
Get gradient reshaped as a vector,.
void GetParams (VectorBase< BaseFloat > *params) const
Get the trainable parameters reshaped as a vector,.
void SetParams (const VectorBase< BaseFloat > &params)
Set the trainable parameters from, reshaped as a vector,.
std::string Info () const
Print some additional info (after <ComponentName> and the dims),.
std::string InfoGradient () const
Print some additional info about gradient (after <...> and dims),.
std::string InfoPropagate () const
std::string InfoBackPropagate () const
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters,.
void SetTrainOptions (const NnetTrainOptions &opts)
Overriding the default, which was UpdatableComponent::SetTrainOptions(...)
void SetLearnRateCoef (BaseFloat val)
Overriding the default, which was UpdatableComponent::SetLearnRateCoef(...)
void SetBiasLearnRateCoef (BaseFloat val)
Overriding the default, which was UpdatableComponent::SetBiasLearnRateCoef(...)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters,.
const NnetTrainOptions & GetTrainOptions () const
Get the training options from the component,.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
Generic interface of a component,.
virtual ~Component ()
virtual bool IsMultistream () const
Check if component has 'Recurrent' interface (trainable and recurrent),.
int32 InputDim () const
Get the dimension of the input,.
int32 OutputDim () const
Get the dimension of the output,.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward-pass propagation 'in' -> 'out',.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
void Write (std::ostream &os, bool binary) const
Write the component to a stream,.
Private Attributes
std::vector< Nnet > nnet_basis_
The vector of 'basis' networks (output of basis is combined according to the posterior_ from the selector_)
std::vector< CuMatrix< BaseFloat > > basis_out_
Nnet selector_
Selector network,.
BaseFloat selector_lr_coef_
CuMatrix< BaseFloat > posterior_
The output of 'selector_',.
Vector< BaseFloat > posterior_sum_
BaseFloat threshold_
Threshold, applied to posterior_sum_, disables the unused basis,.
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjected, kBlstmProjected,
kRecurrentComponent, kActivationFunction = 0x0200, kSoftmax, kHiddenSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kParametricRelu,
kDropout, kLengthNormComponent, kTranform = 0x0400, kRbm,
kSplice, kCopy, kTranspose, kBlockLinearity,
kAddShift, kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent,
kSimpleSentenceAveragingComponent, kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent,
kMaxPooling2DComponent, kFramePoolingComponent, kParallelComponent, kMultiBasisComponent
}
Component type identification mechanism,.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Converts component type to marker,.
static ComponentType MarkerToType (const std::string &s)
Converts marker to component type (case insensitive),.
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file,.
static Component * Read (std::istream &is, bool binary)
Read the component from a stream (static method),.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters,.
BaseFloat learn_rate_coef_
Scalar applied to learning rate for weight matrices (to be used in ::Update method),.
BaseFloat bias_learn_rate_coef_
Scalar applied to learning rate for bias (to be used in ::Update method),.
Protected Attributes inherited from Component
int32 input_dim_
Data members,.
int32 output_dim_
Dimension of the output of the Component,.
Detailed Description
Definition at line 34 of file nnet-multibasis-component.h.
Constructor & Destructor Documentation
MultiBasisComponent()
MultiBasisComponent (int32 dim_in, int32 dim_out) inline
Definition at line 36 of file nnet-multibasis-component.h.
Referenced by MultiBasisComponent::Copy().
                                                    :
     UpdatableComponent(dim_in, dim_out),
     selector_lr_coef_(1.0),
     threshold_(0.1)
   { }
~MultiBasisComponent()
~MultiBasisComponent () inline
Definition at line 42 of file nnet-multibasis-component.h.
   { }
Member Function Documentation
BackpropagateFnc()
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 338 of file nnet-multibasis-component.h.
References CuMatrixBase< Real >::AddDiagVecMat(), CuMatrixBase< Real >::AddMat(), Nnet::Backpropagate(), MultiBasisComponent::basis_out_, CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyFromMat(), rnnlm::i, Nnet::InputDim(), kaldi::kNoTrans, kaldi::kTrans, MultiBasisComponent::nnet_basis_, CuMatrixBase< Real >::NumRows(), Component::OutputDim(), MultiBasisComponent::posterior_, MultiBasisComponent::posterior_sum_, CuMatrixBase< Real >::Row(), CuMatrixBase< Real >::Scale(), MultiBasisComponent::selector_, MultiBasisComponent::selector_lr_coef_, MultiBasisComponent::threshold_, and CuMatrix< Real >::Transpose().
{
     // dimensions,
     int32 num_basis = nnet_basis_.size(),
           num_frames = in.NumRows();
     // split the in_diff,
     CuSubMatrix<BaseFloat> in_diff_basis(
         in_diff->ColRange(0, nnet_basis_[0].InputDim())
     );
     CuSubMatrix<BaseFloat> in_diff_selector(
         in_diff->ColRange(nnet_basis_[0].InputDim(), selector_.InputDim())
     );
     // backprop through 'selector',
     CuMatrix<BaseFloat> selector_out_diff(num_basis, num_frames);
     for (int32 i = 0; i < num_basis; i++) {
       if (posterior_sum_(i) > threshold_) {
         selector_out_diff.Row(i).AddDiagMatMat(1.0, out_diff, kNoTrans, basis_out_[i], kTrans, 0.0);
       }
     }
     selector_out_diff.Transpose();
     selector_out_diff.Scale(selector_lr_coef_);
     CuMatrix<BaseFloat> in_diff_selector_tmp;
     selector_.Backpropagate(selector_out_diff, &in_diff_selector_tmp);
     in_diff_selector.CopyFromMat(in_diff_selector_tmp);
     // backprop through 'basis',
     CuMatrix<BaseFloat> out_diff_scaled(num_frames, OutputDim()),
                         in_diff_basis_tmp;
     for (int32 i = 0; i < num_basis; i++) {
       // use only basis with occupancy >0.1,
       if (posterior_sum_(i) > threshold_) {
         out_diff_scaled.AddDiagVecMat(1.0, posterior_.Row(i), out_diff, kNoTrans, 0.0);
         nnet_basis_[i].Backpropagate(out_diff_scaled, &in_diff_basis_tmp);
         in_diff_basis.AddMat(1.0, in_diff_basis_tmp);
       }
     }
   }
Copy()
Component* Copy () const inline virtual
Copy component (deep copy),.
Implements Component.
Definition at line 45 of file nnet-multibasis-component.h.
References MultiBasisComponent::MultiBasisComponent().
 { return new MultiBasisComponent(*this); }
GetBasis() [1/2]
Nnet& GetBasis (int32 id) inline
Definition at line 196 of file nnet-multibasis-component.h.
References MultiBasisComponent::nnet_basis_.
 { return nnet_basis_.at(id); }
GetBasis() [2/2]
const Nnet& GetBasis (int32 id) const inline
Definition at line 197 of file nnet-multibasis-component.h.
References MultiBasisComponent::nnet_basis_.
 { return nnet_basis_.at(id); }
GetGradient()
void GetGradient (VectorBase< BaseFloat > * gradient) const inline virtual
Get gradient reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 207 of file nnet-multibasis-component.h.
References KALDI_ERR.
{
     KALDI_ERR << "TODO, not yet implemented!";
   }
GetParams()
void GetParams (VectorBase< BaseFloat > * params) const inline virtual
Get the trainable parameters reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 211 of file nnet-multibasis-component.h.
References VectorBase< Real >::Dim(), Nnet::GetParams(), rnnlm::i, KALDI_ASSERT, MultiBasisComponent::nnet_basis_, MultiBasisComponent::NumParams(), VectorBase< Real >::Range(), and MultiBasisComponent::selector_.
{
     int32 offset = 0;
     Vector<BaseFloat> params_tmp;
     // selector,
     selector_.GetParams(&params_tmp);
     params->Range(offset, params_tmp.Dim()).CopyFromVec(params_tmp);
     offset += params_tmp.Dim();
     // basis,
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       nnet_basis_[i].GetParams(&params_tmp);
       params->Range(offset, params_tmp.Dim()).CopyFromVec(params_tmp);
       offset += params_tmp.Dim();
     }
     KALDI_ASSERT(offset == NumParams());
   }
GetType()
ComponentType GetType () const inline virtual
Get Type Identification of the component,.
Implements Component.
Definition at line 46 of file nnet-multibasis-component.h.
References Component::kMultiBasisComponent.
 { return kMultiBasisComponent; }
Info()
std::string Info () const inline virtual
Print some additional info (after <ComponentName> and the dims),.
Reimplemented from Component.
Definition at line 240 of file nnet-multibasis-component.h.
References rnnlm::i, Nnet::Info(), MultiBasisComponent::nnet_basis_, and MultiBasisComponent::selector_.
{
     std::ostringstream os;
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       os << "basis_network #" << i+1 << " {\n"
          << nnet_basis_[i].Info()
          << "}\n";
     }
     os << "\nselector {\n"
        << selector_.Info()
        << "}";
     return os.str();
   }
InfoBackPropagate()
std::string InfoBackPropagate () const inline
Definition at line 283 of file nnet-multibasis-component.h.
References rnnlm::i, Nnet::InfoBackPropagate(), MultiBasisComponent::nnet_basis_, MultiBasisComponent::posterior_sum_, MultiBasisComponent::selector_, and MultiBasisComponent::threshold_.
{
     std::ostringstream os;
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       if (posterior_sum_(i) > threshold_) {
         os << "basis_backpropagate #" << i+1 << "{\n"
            << nnet_basis_[i].InfoBackPropagate(false)
            << "}\n";
       }
     }
     os << "selector_backpropagate {\n"
        << selector_.InfoBackPropagate(false)
        << "}\n";
     return os.str();
   }
InfoGradient()
std::string InfoGradient () const inline virtual
Print some additional info about gradient (after <...> and dims),.
Reimplemented from Component.
Definition at line 253 of file nnet-multibasis-component.h.
References rnnlm::i, Nnet::InfoGradient(), MultiBasisComponent::nnet_basis_, MultiBasisComponent::posterior_sum_, MultiBasisComponent::selector_, and MultiBasisComponent::threshold_.
{
     std::ostringstream os;
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       if (posterior_sum_(i) > threshold_) {
         os << "basis_gradient #" << i+1 << " {\n"
            << nnet_basis_[i].InfoGradient(false)
            << "}\n";
       }
     }
     os << "selector_gradient {\n"
        << selector_.InfoGradient(false)
        << "}";
     return os.str();
   }
InfoPropagate()
std::string InfoPropagate () const inline
Definition at line 268 of file nnet-multibasis-component.h.
References rnnlm::i, Nnet::InfoPropagate(), MultiBasisComponent::nnet_basis_, MultiBasisComponent::posterior_sum_, MultiBasisComponent::selector_, and MultiBasisComponent::threshold_.
{
     std::ostringstream os;
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       if (posterior_sum_(i) > threshold_) {
         os << "basis_propagate #" << i+1 << " {\n"
            << nnet_basis_[i].InfoPropagate(false)
            << "}\n";
       }
     }
     os << "selector_propagate {\n"
        << selector_.InfoPropagate(false)
        << "}\n";
     return os.str();
   }
InitData()
void InitData (std::istream & is) inline virtual
Initialize the content of the component by the 'line' from the prototype,.
Implements UpdatableComponent.
Definition at line 48 of file nnet-multibasis-component.h.
References rnnlm::i, Nnet::Init(), Nnet::InputDim(), Component::InputDim(), KALDI_ASSERT, KALDI_ERR, KALDI_LOG, MultiBasisComponent::nnet_basis_, Nnet::OutputDim(), Component::OutputDim(), Nnet::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), MultiBasisComponent::selector_, MultiBasisComponent::selector_lr_coef_, AffineTransform::SetLinearity(), and MatrixBase< Real >::SetUnit().
{
     // define options,
     std::string selector_proto;
     std::string selector_filename;
     std::string basis_proto;
     std::string basis_filename;
     std::vector<std::string> basis_filename_vector;
     // parse config
     std::string token;
     while (is >> std::ws, !is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<SelectorProto>") ReadToken(is, false, &selector_proto);
       else if (token == "<SelectorFilename>") ReadToken(is, false, &selector_filename);
       else if (token == "<SelectorLearnRateCoef>") ReadBasicType(is, false, &selector_lr_coef_);
       else if (token == "<BasisProto>") ReadToken(is, false, &basis_proto);
       else if (token == "<BasisFilename>") ReadToken(is, false, &basis_filename);
       else if (token == "<BasisFilenameVector>") {
         while(is >> std::ws, !is.eof()) {
           std::string file_or_end;
           ReadToken(is, false, &file_or_end);
           if (file_or_end == "</BasisFilenameVector>") break;
           basis_filename_vector.push_back(file_or_end);
         }
       } else KALDI_ERR << "Unknown token " << token << ", typo in config?"
                << " (SelectorProto|SelectorFilename|BasisProto|BasisFilename|BasisFilenameVector)";
     }
     // selector,
     if (selector_proto != "") {
       KALDI_LOG << "Initializing 'selector' from : " << selector_proto;
       selector_.Init(selector_proto);
     }
     if (selector_filename != "") {
       KALDI_LOG << "Reading 'selector' from : " << selector_filename;
       selector_.Read(selector_filename);
     }
     // as many empty basis as outputs of the selector,
     nnet_basis_.resize(selector_.OutputDim());
     // fill the basis,
     if (basis_proto != "") {
       // Initialized from prototype,
       KALDI_LOG << "Initializing 'basis' from : " << basis_proto;
       for (int32 i = 0; i < nnet_basis_.size(); i++) {
         nnet_basis_[i].Init(basis_proto);
       }
     } else if (basis_filename != "") {
       // Load 1 initial basis repeateadly,
       KALDI_LOG << "Reading 'basis' from : " << basis_filename;
       for (int32 i = 0; i < nnet_basis_.size(); i++) {
         nnet_basis_[i].Read(basis_filename);
       }
     } else if (basis_filename_vector.size() > 0) {
       // Read a list of basis functions,
       if (basis_filename_vector.size() != nnet_basis_.size()) {
         KALDI_ERR << "We need " << nnet_basis_.size() << " filenames. "
                   << "We got " << basis_filename_vector.size();
       }
       for (int32 i = 0; i < nnet_basis_.size(); i++) {
         KALDI_LOG << "Reading 'basis' from : "
                   << basis_filename_vector[i];
         nnet_basis_[i].Read(basis_filename_vector[i]);
       }
     } else {
       // Initialize basis by square identity matrix,
       int32 basis_input_dim = InputDim() - selector_.InputDim();
       KALDI_LOG << "Initializing 'basis' to Identity <AffineTransform> "
                 << OutputDim() << "x" << basis_input_dim;
       KALDI_ASSERT(OutputDim() == basis_input_dim);  // has to be square!
       Matrix<BaseFloat> m(OutputDim(), basis_input_dim);
       m.SetUnit();
       // wrap identity into AffineTransform,
       // (bias is vector of zeros),
       AffineTransform identity_comp(basis_input_dim, OutputDim());
       identity_comp.SetLinearity(CuMatrix<BaseFloat>(m));
       //
       for (int32 i = 0; i < nnet_basis_.size(); i++) {
         nnet_basis_[i].AppendComponent(identity_comp);
       }
     }
     // check,
     KALDI_ASSERT(InputDim() == selector_.InputDim() + nnet_basis_[0].InputDim());
     KALDI_ASSERT(OutputDim() == nnet_basis_[0].OutputDim());
   }
NumParams()
int32 NumParams () const inline virtual
Number of trainable parameters,.
Implements UpdatableComponent.
Definition at line 199 of file nnet-multibasis-component.h.
References rnnlm::i, MultiBasisComponent::nnet_basis_, Nnet::NumParams(), and MultiBasisComponent::selector_.
Referenced by MultiBasisComponent::GetParams(), and MultiBasisComponent::SetParams().
{
     int32 num_params_sum = selector_.NumParams();
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       num_params_sum += nnet_basis_[i].NumParams();
     }
     return num_params_sum;
   }
PropagateFnc()
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 298 of file nnet-multibasis-component.h.
References CuVectorBase< Real >::AddColSumMat(), CuMatrixBase< Real >::AddDiagVecMat(), kaldi::ApproxEqual(), MultiBasisComponent::basis_out_, CuMatrixBase< Real >::ColRange(), rnnlm::i, Nnet::InputDim(), KALDI_ASSERT, kaldi::kNoTrans, MultiBasisComponent::nnet_basis_, MultiBasisComponent::posterior_, MultiBasisComponent::posterior_sum_, Nnet::Propagate(), MultiBasisComponent::selector_, and MultiBasisComponent::threshold_.
{
     // dimensions,
     int32 num_basis = nnet_basis_.size();
     // make sure we have all the buffers,
     if (basis_out_.size() != num_basis) {
       basis_out_.resize(num_basis);
     }
     // split the input,
     const CuSubMatrix<BaseFloat> in_basis(
         in.ColRange(0, nnet_basis_[0].InputDim())
     );
     const CuSubMatrix<BaseFloat> in_selector(
         in.ColRange(nnet_basis_[0].InputDim(), selector_.InputDim())
     );
     // get the 'selector_' posteriors,
     selector_.Propagate(in_selector, &posterior_);
     KALDI_ASSERT(posterior_.Row(0).Min() >= 0.0);
     KALDI_ASSERT(posterior_.Row(0).Max() <= 1.0);
     KALDI_ASSERT(ApproxEqual(posterior_.Row(0).Sum(), 1.0));
     posterior_.Transpose();  // trans,
     // sum 'selector_' posteriors over time,
     CuVector<BaseFloat> posterior_sum(num_basis);
     posterior_sum.AddColSumMat(1.0, posterior_, 0.0);
     posterior_sum_ = Vector<BaseFloat>(posterior_sum);
     // combine the 'basis' outputs,
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       if (posterior_sum_(i) > threshold_) {
         // use only basis with occupancy >0.1,
         nnet_basis_[i].Propagate(in_basis, &basis_out_[i]);
         out->AddDiagVecMat(1.0, posterior_.Row(i), basis_out_[i], kNoTrans);
       }
     }
   }
ReadData()
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 137 of file nnet-multibasis-component.h.
References kaldi::ExpectToken(), rnnlm::i, Nnet::InputDim(), Component::InputDim(), KALDI_ASSERT, KALDI_ERR, MultiBasisComponent::nnet_basis_, Nnet::OutputDim(), Component::OutputDim(), kaldi::Peek(), kaldi::PeekToken(), Nnet::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), MultiBasisComponent::selector_, and MultiBasisComponent::selector_lr_coef_.
{
     // Read all the '<Tokens>' in arbitrary order,
     bool end_loop = false;
     while (!end_loop && '<' == Peek(is, binary)) {
       std::string token;
       int first_char = PeekToken(is, binary);
       switch (first_char) {
         case 'S': ReadToken(is, false, &token);
            if (token == "<SelectorLearnRateCoef>") ReadBasicType(is, binary, &selector_lr_coef_);
           else if (token == "<Selector>") selector_.Read(is, binary);
           else KALDI_ERR << "Unknown token: " << token;
           break;
         case 'N': ExpectToken(is, binary, "<NumBasis>");
           int32 num_basis;
           ReadBasicType(is, binary, &num_basis);
           nnet_basis_.resize(num_basis);
           for (int32 i = 0; i < num_basis; i++) {
             int32 dummy;
             ExpectToken(is, binary, "<Basis>");
             ReadBasicType(is, binary, &dummy);
             nnet_basis_[i].Read(is, binary);
           }
           break;
         case '!':
           ExpectToken(is, binary, "<!EndOfComponent>");
           end_loop=true;
           break;
         default:
           ReadToken(is, false, &token);
           KALDI_ERR << "Unknown token: " << token;
       }
     }
     // check,
     KALDI_ASSERT(nnet_basis_.size() == selector_.OutputDim());
     KALDI_ASSERT(InputDim() == selector_.InputDim() + nnet_basis_[0].InputDim());
     KALDI_ASSERT(OutputDim() == nnet_basis_[0].OutputDim());
   }
SetBiasLearnRateCoef()
void SetBiasLearnRateCoef (BaseFloat val) inline virtual
Overriding the default, which was UpdatableComponent::SetBiasLearnRateCoef(...)
Reimplemented from UpdatableComponent.
Definition at line 419 of file nnet-multibasis-component.h.
References rnnlm::i, rnnlm::j, MultiBasisComponent::nnet_basis_, and UpdatableComponent::SetBiasLearnRateCoef().
{
     // loop over nnets,
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       // loop over components,
       for (int32 j = 0; j < nnet_basis_[i].NumComponents(); j++) {
         if (nnet_basis_[i].GetComponent(j).IsUpdatable()) {
           UpdatableComponent& comp =
             dynamic_cast<UpdatableComponent&>(nnet_basis_[i].GetComponent(j));
           // set the value,
           comp.SetBiasLearnRateCoef(val);
         }
       }
     }
   }
SetLearnRateCoef()
void SetLearnRateCoef (BaseFloat val) inline virtual
Overriding the default, which was UpdatableComponent::SetLearnRateCoef(...)
Reimplemented from UpdatableComponent.
Definition at line 400 of file nnet-multibasis-component.h.
References rnnlm::i, rnnlm::j, MultiBasisComponent::nnet_basis_, and UpdatableComponent::SetLearnRateCoef().
{
     // loop over nnets,
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       // loop over components,
       for (int32 j = 0; j < nnet_basis_[i].NumComponents(); j++) {
         if (nnet_basis_[i].GetComponent(j).IsUpdatable()) {
           UpdatableComponent& comp =
             dynamic_cast<UpdatableComponent&>(nnet_basis_[i].GetComponent(j));
           // set the value,
           comp.SetLearnRateCoef(val);
         }
       }
     }
   }
SetParams()
void SetParams (const VectorBase< BaseFloat > & params) inline virtual
Set the trainable parameters from, reshaped as a vector,.
Implements UpdatableComponent.
Definition at line 227 of file nnet-multibasis-component.h.
References rnnlm::i, KALDI_ASSERT, MultiBasisComponent::nnet_basis_, Nnet::NumParams(), MultiBasisComponent::NumParams(), VectorBase< Real >::Range(), MultiBasisComponent::selector_, and Nnet::SetParams().
{
     int32 offset = 0;
     // selector,
     selector_.SetParams(params.Range(offset, selector_.NumParams()));
     offset += selector_.NumParams();
     // basis,
     for (int32 i = 0; i < nnet_basis_.size(); i++) {
       nnet_basis_[i].SetParams(params.Range(offset, nnet_basis_[i].NumParams()));
       offset += nnet_basis_[i].NumParams();
     }
     KALDI_ASSERT(offset == NumParams());
   }
SetTrainOptions()
void SetTrainOptions (const NnetTrainOptions & opts) inline virtual
Overriding the default, which was UpdatableComponent::SetTrainOptions(...)
Reimplemented from UpdatableComponent.
Definition at line 389 of file nnet-multibasis-component.h.
References rnnlm::i, MultiBasisComponent::nnet_basis_, MultiBasisComponent::selector_, and Nnet::SetTrainOptions().
{
     selector_.SetTrainOptions(opts);
     for (int32 i=0; i<nnet_basis_.size(); i++) {
       nnet_basis_[i].SetTrainOptions(opts);
     }
   }
Update()
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters,.
Implements UpdatableComponent.
Definition at line 380 of file nnet-multibasis-component.h.
{
     { }  // do nothing
   }
WriteData()
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 176 of file nnet-multibasis-component.h.
References rnnlm::i, MultiBasisComponent::nnet_basis_, MultiBasisComponent::selector_, MultiBasisComponent::selector_lr_coef_, Nnet::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     int32 num_basis = nnet_basis_.size();
     WriteToken(os, binary, "<SelectorLearnRateCoef>");
     WriteBasicType(os, binary, selector_lr_coef_);
     if (!binary) os << "\n\n";
     WriteToken(os, binary, "<Selector>");
     if (!binary) os << "\n";
     selector_.Write(os, binary);
     if (!binary) os << "\n";
     WriteToken(os, binary, "<NumBasis>");
     WriteBasicType(os, binary, num_basis);
     if (!binary) os << "\n";
     for (int32 i = 0; i < num_basis; i++) {
       WriteToken(os, binary, "<Basis>");
       WriteBasicType(os, binary, i+1);
       if (!binary) os << "\n";
       nnet_basis_.at(i).Write(os, binary);
     }
   }
Member Data Documentation
basis_out_
std::vector<CuMatrix<BaseFloat> > basis_out_ private
Definition at line 438 of file nnet-multibasis-component.h.
Referenced by MultiBasisComponent::BackpropagateFnc(), and MultiBasisComponent::PropagateFnc().
nnet_basis_
std::vector<Nnet> nnet_basis_ private
The vector of 'basis' networks (output of basis is combined according to the posterior_ from the selector_)
Definition at line 437 of file nnet-multibasis-component.h.
Referenced by MultiBasisComponent::BackpropagateFnc(), MultiBasisComponent::GetBasis(), MultiBasisComponent::GetParams(), MultiBasisComponent::Info(), MultiBasisComponent::InfoBackPropagate(), MultiBasisComponent::InfoGradient(), MultiBasisComponent::InfoPropagate(), MultiBasisComponent::InitData(), MultiBasisComponent::NumParams(), MultiBasisComponent::PropagateFnc(), MultiBasisComponent::ReadData(), MultiBasisComponent::SetBiasLearnRateCoef(), MultiBasisComponent::SetLearnRateCoef(), MultiBasisComponent::SetParams(), MultiBasisComponent::SetTrainOptions(), and MultiBasisComponent::WriteData().
posterior_
CuMatrix<BaseFloat> posterior_ private
The output of 'selector_',.
Definition at line 445 of file nnet-multibasis-component.h.
Referenced by MultiBasisComponent::BackpropagateFnc(), and MultiBasisComponent::PropagateFnc().
posterior_sum_
Vector<BaseFloat> posterior_sum_ private
Definition at line 446 of file nnet-multibasis-component.h.
Referenced by MultiBasisComponent::BackpropagateFnc(), MultiBasisComponent::InfoBackPropagate(), MultiBasisComponent::InfoGradient(), MultiBasisComponent::InfoPropagate(), and MultiBasisComponent::PropagateFnc().
selector_
Nnet selector_ private
Selector network,.
Definition at line 441 of file nnet-multibasis-component.h.
Referenced by MultiBasisComponent::BackpropagateFnc(), MultiBasisComponent::GetParams(), MultiBasisComponent::Info(), MultiBasisComponent::InfoBackPropagate(), MultiBasisComponent::InfoGradient(), MultiBasisComponent::InfoPropagate(), MultiBasisComponent::InitData(), MultiBasisComponent::NumParams(), MultiBasisComponent::PropagateFnc(), MultiBasisComponent::ReadData(), MultiBasisComponent::SetParams(), MultiBasisComponent::SetTrainOptions(), and MultiBasisComponent::WriteData().
selector_lr_coef_
BaseFloat selector_lr_coef_ private
Definition at line 442 of file nnet-multibasis-component.h.
Referenced by MultiBasisComponent::BackpropagateFnc(), MultiBasisComponent::InitData(), MultiBasisComponent::ReadData(), and MultiBasisComponent::WriteData().
threshold_
BaseFloat threshold_ private
Threshold, applied to posterior_sum_, disables the unused basis,.
Definition at line 449 of file nnet-multibasis-component.h.
Referenced by MultiBasisComponent::BackpropagateFnc(), MultiBasisComponent::InfoBackPropagate(), MultiBasisComponent::InfoGradient(), MultiBasisComponent::InfoPropagate(), and MultiBasisComponent::PropagateFnc().
The documentation for this class was generated from the following file:
nnet/nnet-multibasis-component.h