Kaldi: StringRepository< Label, StringId > Class Template Reference
StringRepository< Label, StringId > Class Template Reference
#include <determinize-star-inl.h>
Classes
class VectorEqual
class VectorKey
Public Types
typedef unordered_map< const vector< Label > *, StringId, VectorKey, VectorEqual > MapType
Public Member Functions
StringId IdOfEmpty ()
StringId IdOfLabel (Label l)
StringId IdOfSeq (const vector< Label > &v)
bool IsEmptyString (StringId id)
void SeqOfId (StringId id, vector< Label > *v)
StringId RemovePrefix (StringId id, size_t prefix_len)
StringRepository ()
void Destroy ()
~StringRepository ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (StringRepository)
StringId IdOfSeqInternal (const vector< Label > &v)
Private Attributes
vector< vector< Label > *> vec_
MapType map_
StringId string_end
StringId no_symbol
StringId single_symbol_start
StringId single_symbol_range
Static Private Attributes
static const StringId string_start = (StringId) 0
Detailed Description
template<class Label, class StringId>
class fst::StringRepository< Label, StringId >
Definition at line 38 of file determinize-star-inl.h.
Member Typedef Documentation
MapType
typedef unordered_map<const vector<Label>*, StringId, VectorKey, VectorEqual> MapType
Definition at line 65 of file determinize-star-inl.h.
Constructor & Destructor Documentation
StringRepository()
StringRepository () inline
Definition at line 111 of file determinize-star-inl.h.
References StringRepository< Label, StringId >::no_symbol, StringRepository< Label, StringId >::single_symbol_range, StringRepository< Label, StringId >::single_symbol_start, and StringRepository< Label, StringId >::string_end.
                      {
     // The following are really just constants but don't want to complicate compilation so make them
     // class variables.  Due to the brokenness of <limits>, they can't be accessed as constants.
     string_end = (numeric_limits<StringId>::max() / 2) - 1;  // all hash values must be <= this.
     no_symbol = (numeric_limits<StringId>::max() / 2);  // reserved for empty sequence.
     single_symbol_start =  (numeric_limits<StringId>::max() / 2) + 1;
     single_symbol_range =  numeric_limits<StringId>::max() - single_symbol_start;
   }
~StringRepository()
~StringRepository () inline
Definition at line 127 of file determinize-star-inl.h.
References StringRepository< Label, StringId >::Destroy(), and StringRepository< Label, StringId >::KALDI_DISALLOW_COPY_AND_ASSIGN().
                       {
     Destroy();
   }
Member Function Documentation
Destroy()
void Destroy () inline
Definition at line 119 of file determinize-star-inl.h.
References StringRepository< Label, StringId >::map_, and StringRepository< Label, StringId >::vec_.
Referenced by StringRepository< Label, StringId >::~StringRepository().
                  {
     for (typename vector<vector<Label>* >::iterator iter = vec_.begin(); iter != vec_.end(); ++iter)
       delete *iter;
     vector<vector<Label>* > tmp_vec;
     tmp_vec.swap(vec_);
     MapType tmp_map;
     tmp_map.swap(map_);
   }
IdOfEmpty()
StringId IdOfEmpty () inline
Definition at line 67 of file determinize-star-inl.h.
References StringRepository< Label, StringId >::no_symbol.
Referenced by fst::TestFactor(), and fst::TestStringRepository().
 { return no_symbol; }
IdOfLabel()
StringId IdOfLabel (Label l) inline
Definition at line 69 of file determinize-star-inl.h.
References StringRepository< Label, StringId >::IdOfSeqInternal(), StringRepository< Label, StringId >::single_symbol_range, and StringRepository< Label, StringId >::single_symbol_start.
Referenced by StringRepository< Label, StringId >::IdOfSeq(), fst::TestFactor(), and fst::TestStringRepository().
{
     if (l>= 0 && l <= (Label) single_symbol_range) {
       return l + single_symbol_start;
     } else {
       // l is out of the allowed range so we have to treat it as a sequence of length one.  Should be v. rare.
       vector<Label> v; v.push_back(l);
       return IdOfSeqInternal(v);
     }
   }
IdOfSeq()
StringId IdOfSeq (const vector< Label > & v) inline
Definition at line 79 of file determinize-star-inl.h.
References StringRepository< Label, StringId >::IdOfLabel(), StringRepository< Label, StringId >::IdOfSeqInternal(), and StringRepository< Label, StringId >::no_symbol.
Referenced by StringRepository< Label, StringId >::RemovePrefix(), fst::TestFactor(), and fst::TestStringRepository().
                                            {  // also works for sizes 0 and 1.
     size_t sz = v.size();
     if (sz == 0) return no_symbol;
     else if (v.size() == 1) return IdOfLabel(v[0]);
     else return IdOfSeqInternal(v);
   }
IdOfSeqInternal()
StringId IdOfSeqInternal (const vector< Label > & v) inline private
Definition at line 134 of file determinize-star-inl.h.
References StringRepository< Label, StringId >::map_, StringRepository< Label, StringId >::string_end, and StringRepository< Label, StringId >::vec_.
Referenced by StringRepository< Label, StringId >::IdOfLabel(), and StringRepository< Label, StringId >::IdOfSeq().
{
     typename MapType::iterator iter = map_.find(&v);
     if (iter != map_.end()) {
       return iter->second;
     } else {  // must add it to map.
       StringId this_id = (StringId) vec_.size();
       vector<Label> *v_new = new vector<Label> (v);
       vec_.push_back(v_new);
       map_[v_new] = this_id;
       assert(this_id < string_end);  // or we used up the labels.
       return this_id;
     }
   }
IsEmptyString()
bool IsEmptyString (StringId id) inline
Definition at line 86 of file determinize-star-inl.h.
References StringRepository< Label, StringId >::no_symbol.
{
     return id == no_symbol;
   }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (StringRepository< Label, StringId >) private
Referenced by DeterminizerStar< F >::ProcessSubset(), and StringRepository< Label, StringId >::~StringRepository().
RemovePrefix()
StringId RemovePrefix (StringId id, size_t prefix_len) inline
Definition at line 98 of file determinize-star-inl.h.
References rnnlm::i, StringRepository< Label, StringId >::IdOfSeq(), and StringRepository< Label, StringId >::SeqOfId().
Referenced by fst::TestFactor(), and fst::TestStringRepository().
{
     if (prefix_len == 0) return id;
     else {
       vector<Label> v;
       SeqOfId(id, &v);
       size_t sz = v.size();
       assert(sz >= prefix_len);
       vector<Label> v_noprefix(sz - prefix_len);
       for (size_t i = 0;i < sz-prefix_len;i++) v_noprefix[i] = v[i+prefix_len];
       return IdOfSeq(v_noprefix);
     }
   }
SeqOfId()
void SeqOfId (StringId id, vector< Label > * v) inline
Definition at line 89 of file determinize-star-inl.h.
References StringRepository< Label, StringId >::no_symbol, StringRepository< Label, StringId >::single_symbol_start, and StringRepository< Label, StringId >::vec_.
Referenced by StringRepository< Label, StringId >::RemovePrefix(), fst::TestFactor(), and fst::TestStringRepository().
{
     if (id == no_symbol) v->clear();
     else if (id>=single_symbol_start) {
       v->resize(1); (*v)[0] = id - single_symbol_start;
     } else {
       assert(static_cast<size_t>(id) < vec_.size());
       *v = *(vec_[id]);
     }
   }
Member Data Documentation
map_
MapType map_ private
Definition at line 149 of file determinize-star-inl.h.
Referenced by StringRepository< Label, StringId >::Destroy(), and StringRepository< Label, StringId >::IdOfSeqInternal().
no_symbol
StringId no_symbol private
Definition at line 153 of file determinize-star-inl.h.
Referenced by StringRepository< Label, StringId >::IdOfEmpty(), StringRepository< Label, StringId >::IdOfSeq(), StringRepository< Label, StringId >::IsEmptyString(), StringRepository< Label, StringId >::SeqOfId(), and StringRepository< Label, StringId >::StringRepository().
single_symbol_range
StringId single_symbol_range private
Definition at line 155 of file determinize-star-inl.h.
Referenced by StringRepository< Label, StringId >::IdOfLabel(), and StringRepository< Label, StringId >::StringRepository().
single_symbol_start
StringId single_symbol_start private
Definition at line 154 of file determinize-star-inl.h.
Referenced by StringRepository< Label, StringId >::IdOfLabel(), StringRepository< Label, StringId >::SeqOfId(), and StringRepository< Label, StringId >::StringRepository().
string_end
StringId string_end private
Definition at line 152 of file determinize-star-inl.h.
Referenced by StringRepository< Label, StringId >::IdOfSeqInternal(), and StringRepository< Label, StringId >::StringRepository().
string_start
const StringId string_start = (StringId) 0 static private
Definition at line 151 of file determinize-star-inl.h.
vec_
vector<vector<Label>* > vec_ private
Definition at line 148 of file determinize-star-inl.h.
Referenced by StringRepository< Label, StringId >::Destroy(), StringRepository< Label, StringId >::IdOfSeqInternal(), and StringRepository< Label, StringId >::SeqOfId().
The documentation for this class was generated from the following file:
fstext/determinize-star-inl.h