Kaldi: LinearComponent Class Reference
LinearComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
LinearComponent ()
void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
virtual void FreezeNaturalGradient (bool freeze)
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
LinearComponent (const LinearComponent &other)
LinearComponent (const CuMatrix< BaseFloat > &params)
BaseFloat OrthonormalConstraint () const
CuMatrixBase< BaseFloat > & Params ()
const CuMatrixBase< BaseFloat > & Params () const
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
Component ()
virtual ~Component ()
Private Member Functions
LinearComponent & operator= (const LinearComponent &)
Private Attributes
CuMatrix< BaseFloat > params_
BaseFloat orthonormal_constraint_
bool use_natural_gradient_
OnlineNaturalGradient preconditioner_in_
OnlineNaturalGradient preconditioner_out_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Detailed Description
Definition at line 927 of file nnet-simple-component.h.
Constructor & Destructor Documentation
LinearComponent() [1/3]
LinearComponent () inline
Definition at line 952 of file nnet-simple-component.h.
References Component::Add(), Component::ConsolidateMemory(), PnormComponent::Copy(), kaldi::nnet3::DotProduct(), kaldi::nnet3::FreezeNaturalGradient(), Component::Info(), PnormComponent::InitFromConfig(), kaldi::nnet3::NumParameters(), kaldi::nnet3::PerturbParams(), and Component::Scale().
 { }
LinearComponent() [2/3]
LinearComponent (const LinearComponent & other) explicit
Definition at line 3259 of file nnet-simple-component.cc.
                                  :
     UpdatableComponent(other),
     params_(other.params_),
     orthonormal_constraint_(other.orthonormal_constraint_),
     use_natural_gradient_(other.use_natural_gradient_),
     preconditioner_in_(other.preconditioner_in_),
     preconditioner_out_(other.preconditioner_out_) { }
LinearComponent() [3/3]
LinearComponent (const CuMatrix< BaseFloat > & params) explicit
Definition at line 3268 of file nnet-simple-component.cc.
References LinearComponent::preconditioner_in_, LinearComponent::preconditioner_out_, OnlineNaturalGradient::SetRank(), and OnlineNaturalGradient::SetUpdatePeriod().
                                                                  :
     params_(params),
     orthonormal_constraint_(0.0),
     use_natural_gradient_(true) {
   // Set defaults for natural gradient.
   preconditioner_in_.SetRank(40);
   preconditioner_out_.SetRank(80);
   preconditioner_in_.SetUpdatePeriod(4);
   preconditioner_out_.SetUpdatePeriod(4);
   // the component-level defaults of alpha and num_samples_history, at 4.0 and
   // 2000.0, are the same as in the NaturalGradientOnline code, so there is no
   // need to set those here.
 }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 3287 of file nnet-simple-component.cc.
References KALDI_ASSERT, and LinearComponent::params_.
{
   const LinearComponent *other =
       dynamic_cast<const LinearComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   params_.AddMat(alpha, other->params_);
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 3216 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), UpdatableComponent::is_gradient_, kaldi::kNoTrans, kaldi::kTrans, UpdatableComponent::learning_rate_, LinearComponent::params_, OnlineNaturalGradient::PreconditionDirections(), LinearComponent::preconditioner_in_, and LinearComponent::preconditioner_out_.
{
   LinearComponent *to_update = dynamic_cast<LinearComponent*>(to_update_in);
   // Propagate the derivative back to the input.  add with coefficient 1.0 since
   // property kBackpropAdds is true.  If we wanted to add with coefficient 0.0
   // we'd need to zero the in_deriv, in case of infinities.
   if (in_deriv)
     in_deriv->AddMatMat(1.0, out_deriv, kNoTrans, params_, kNoTrans, 1.0);
   if (to_update != NULL) {
     if (!to_update->is_gradient_) {
       CuMatrix<BaseFloat> in_value_temp(in_value), out_deriv_temp(out_deriv);
       // These "scale" values get will get multiplied into the learning rate (faster
       // than having the matrices scaled inside the preconditioning code).
       BaseFloat in_scale, out_scale;
       to_update->preconditioner_in_.PreconditionDirections(&in_value_temp,
                                                            &in_scale);
       to_update->preconditioner_out_.PreconditionDirections(&out_deriv_temp,
                                                             &out_scale);
       BaseFloat local_lrate = in_scale * out_scale * to_update->learning_rate_;
       to_update->params_.AddMatMat(local_lrate, out_deriv_temp, kTrans,
                                    in_value_temp, kNoTrans, 1.0);
     } else {
       to_update->params_.AddMatMat(to_update->learning_rate_,
                                    out_deriv, kTrans,
                                    in_value, kNoTrans, 1.0);
     }
   }
 }
ConsolidateMemory()
void ConsolidateMemory () virtual
This virtual function relates to memory management, and avoiding fragmentation.
It is called only once per model, after we do the first minibatch of training. The default implementation does nothing, but it can be overridden by child classes, where it may re-initialize certain quantities that may possibly have been allocated during the forward pass (e.g. certain statistics; OnlineNaturalGradient objects). We use our own CPU-based allocator (see cu-allocator.h) and since it can't do paging since we're not in control of the GPU page table, fragmentation can be a problem. The allocator always tries to put things in 'low-address memory' (i.e. at smaller memory addresses) near the beginning of the block it allocated, to avoid fragmentation; but if permanent things (belonging to the model) are allocated in the forward pass, they can permanently stay in high memory. This function helps to prevent that, by re-allocating those things into low-address memory (It's important that it's called after all the temporary buffers for the forward-backward have been freed, so that there is low-address memory available)).
Reimplemented from Component.
Definition at line 3321 of file nnet-simple-component.cc.
References LinearComponent::preconditioner_in_, LinearComponent::preconditioner_out_, and OnlineNaturalGradient::Swap().
{
   OnlineNaturalGradient temp_in(preconditioner_in_);
   preconditioner_in_.Swap(&temp_in);
   OnlineNaturalGradient temp_out(preconditioner_out_);
   preconditioner_out_.Swap(&temp_out);
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 3255 of file nnet-simple-component.cc.
{
   return new LinearComponent(*this);
 }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 3310 of file nnet-simple-component.cc.
References kaldi::kTrans, LinearComponent::params_, and kaldi::TraceMatMat().
{
   const LinearComponent *other =
       dynamic_cast<const LinearComponent*>(&other_in);
   return TraceMatMat(params_, other->params_, kTrans);
 }
FreezeNaturalGradient()
void FreezeNaturalGradient (bool freeze) virtual
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
Reimplemented from UpdatableComponent.
Definition at line 3316 of file nnet-simple-component.cc.
References OnlineNaturalGradient::Freeze(), LinearComponent::preconditioner_in_, and LinearComponent::preconditioner_out_.
{
   preconditioner_in_.Freeze(freeze);
   preconditioner_out_.Freeze(freeze);
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 3188 of file nnet-simple-component.cc.
References OnlineNaturalGradient::GetAlpha(), OnlineNaturalGradient::GetNumSamplesHistory(), OnlineNaturalGradient::GetRank(), OnlineNaturalGradient::GetUpdatePeriod(), kaldi::GetVerboseLevel(), UpdatableComponent::Info(), AffineComponent::orthonormal_constraint_, NaturalGradientAffineComponent::preconditioner_in_, NaturalGradientAffineComponent::preconditioner_out_, and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info();
   PrintParameterStats(stream, "params", params_,
                       false, // include_mean
                       true, // include_row_norms
                       true, // include_column_norms
                       GetVerboseLevel() >= 2); // include_singular_values
   if (orthonormal_constraint_ != 0.0)
     stream << ", orthonormal-constraint=" << orthonormal_constraint_;
   stream << ", use-natural-gradient="
          << (use_natural_gradient_ ? "true" : "false")
          << ", rank-in=" << preconditioner_in_.GetRank()
          << ", rank-out=" << preconditioner_out_.GetRank()
          << ", num-samples-history="
          << preconditioner_in_.GetNumSamplesHistory()
          << ", update-period=" << preconditioner_in_.GetUpdatePeriod()
          << ", alpha=" << preconditioner_in_.GetAlpha();
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 3093 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), UpdatableComponent::InitLearningRatesFromConfig(), AffineComponent::InputDim(), UpdatableComponent::is_gradient_, KALDI_ASSERT, KALDI_ERR, AffineComponent::orthonormal_constraint_, AffineComponent::OutputDim(), NaturalGradientAffineComponent::preconditioner_in_, NaturalGradientAffineComponent::preconditioner_out_, kaldi::ReadKaldiObject(), OnlineNaturalGradient::SetAlpha(), OnlineNaturalGradient::SetNumSamplesHistory(), OnlineNaturalGradient::SetRank(), OnlineNaturalGradient::SetUpdatePeriod(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   bool ok = true;
   std::string matrix_filename;
   is_gradient_ = false;  // not configurable; there's no reason you'd want this
   InitLearningRatesFromConfig(cfl);
   int32 input_dim = -1, output_dim = -1;
   if (cfl->GetValue("matrix", &matrix_filename)) {
     ReadKaldiObject(matrix_filename, &params_); // will abort on failure.
     KALDI_ASSERT(params_.NumRows() != 0);
     if (cfl->GetValue("input-dim", &input_dim))
       KALDI_ASSERT(input_dim == InputDim() &&
                    "input-dim mismatch vs. matrix.");
     if (cfl->GetValue("output-dim", &output_dim))
       KALDI_ASSERT(output_dim == OutputDim() &&
                    "output-dim mismatch vs. matrix.");
   } else {
     ok = ok && cfl->GetValue("input-dim", &input_dim);
     ok = ok && cfl->GetValue("output-dim", &output_dim);
     if (!ok)
       KALDI_ERR << "Bad initializer " << cfl->WholeLine();
     BaseFloat param_stddev = 1.0 / std::sqrt(input_dim);
     cfl->GetValue("param-stddev", &param_stddev);
     params_.Resize(output_dim, input_dim);
     KALDI_ASSERT(output_dim > 0 && input_dim > 0 && param_stddev >= 0.0);
     params_.SetRandn(); // sets to random normally distributed noise.
     params_.Scale(param_stddev);
   }
   // Read various natural-gradient-related configs.
   int32 rank_in = -1, rank_out = -1, update_period = 4;
   BaseFloat alpha = 4.0,
       num_samples_history = 2000.0;
   use_natural_gradient_ = true;
   cfl->GetValue("num-samples-history", &num_samples_history);
   cfl->GetValue("alpha", &alpha);
   cfl->GetValue("rank-in", &rank_in);
   cfl->GetValue("rank-out", &rank_out);
   cfl->GetValue("update-period", &update_period);
   cfl->GetValue("use-natural-gradient", &use_natural_gradient_);
   if (rank_in < 0)
     rank_in = std::min<int32>(20, (InputDim() + 1) / 2);
   if (rank_out < 0)
     rank_out = std::min<int32>(80, (OutputDim() + 1) / 2);
   preconditioner_in_.SetAlpha(alpha);
   preconditioner_out_.SetAlpha(alpha);
   preconditioner_in_.SetRank(rank_in);
   preconditioner_out_.SetRank(rank_out);
   preconditioner_in_.SetNumSamplesHistory(num_samples_history);
   preconditioner_out_.SetNumSamplesHistory(num_samples_history);
   preconditioner_in_.SetUpdatePeriod(update_period);
   preconditioner_out_.SetUpdatePeriod(update_period);
   orthonormal_constraint_ = 0.0;
   cfl->GetValue("orthonormal-constraint", &orthonormal_constraint_);
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 929 of file nnet-simple-component.h.
 { return params_.NumCols(); }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 3299 of file nnet-simple-component.cc.
References LinearComponent::params_.
Referenced by LinearComponent::UnVectorize(), and LinearComponent::Vectorize().
{
   return params_.NumRows() * params_.NumCols();
 }
operator=()
LinearComponent& operator= (const LinearComponent &) private
OrthonormalConstraint()
BaseFloat OrthonormalConstraint () const inline
Definition at line 971 of file nnet-simple-component.h.
Referenced by kaldi::nnet3::ConstrainOrthonormal().
 { return orthonormal_constraint_; }
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 930 of file nnet-simple-component.h.
Referenced by ModelCollapser::GetDiagonallyPreModifiedComponentIndex().
 { return params_.NumRows(); }
Params() [1/2]
CuMatrixBase<BaseFloat>& Params () inline
Definition at line 972 of file nnet-simple-component.h.
Referenced by kaldi::nnet3::ConstrainOrthonormal(), and ModelCollapser::GetDiagonallyPreModifiedComponentIndex().
 { return params_; }
Params() [2/2]
const CuMatrixBase<BaseFloat>& Params () const inline
Definition at line 973 of file nnet-simple-component.h.
 { return params_; }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 3294 of file nnet-simple-component.cc.
References LinearComponent::params_, and CuMatrixBase< Real >::SetRandn().
{
   CuMatrix<BaseFloat> temp_params(params_);
   temp_params.SetRandn();
   params_.AddMat(stddev, temp_params);
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 3209 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), kaldi::kNoTrans, and kaldi::kTrans.
{
   out->AddMatMat(1.0, in, kNoTrans, params_, kTrans, 1.0);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 933 of file nnet-simple-component.h.
References PnormComponent::Backprop(), kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kPropagateAdds, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kUpdatableComponent, PnormComponent::Propagate(), PnormComponent::Read(), and PnormComponent::Write().
{
     return kSimpleComponent|kUpdatableComponent|kBackpropNeedsInput|
         kPropagateAdds|kBackpropAdds;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 3054 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectToken(), KALDI_ASSERT, AffineComponent::orthonormal_constraint_, kaldi::PeekToken(), NaturalGradientAffineComponent::preconditioner_in_, NaturalGradientAffineComponent::preconditioner_out_, kaldi::ReadBasicType(), UpdatableComponent::ReadUpdatableCommon(), OnlineNaturalGradient::SetAlpha(), OnlineNaturalGradient::SetNumSamplesHistory(), OnlineNaturalGradient::SetRank(), and OnlineNaturalGradient::SetUpdatePeriod().
{
   std::string token = ReadUpdatableCommon(is, binary);
   KALDI_ASSERT(token == "");
   ExpectToken(is, binary, "<Params>");
   params_.Read(is, binary);
   if (PeekToken(is, binary) == 'O') {
     ExpectToken(is, binary, "<OrthonormalConstraint>");
     ReadBasicType(is, binary, &orthonormal_constraint_);
   } else {
     orthonormal_constraint_ = 0.0;
   }
   ExpectToken(is, binary, "<UseNaturalGradient>");
   ReadBasicType(is, binary, &use_natural_gradient_);
   // Read various natural-gradient-related configs.
   int32 rank_in,  rank_out, update_period;
   BaseFloat alpha, num_samples_history;
   ExpectToken(is, binary, "<RankInOut>");
   ReadBasicType(is, binary, &rank_in);
   ReadBasicType(is, binary, &rank_out);
   ExpectToken(is, binary, "<Alpha>");
   ReadBasicType(is, binary, &alpha);
   ExpectToken(is, binary, "<NumSamplesHistory>");
   ReadBasicType(is, binary, &num_samples_history);
   ExpectToken(is, binary, "<UpdatePeriod>");
   ReadBasicType(is, binary, &update_period);
   preconditioner_in_.SetAlpha(alpha);
   preconditioner_out_.SetAlpha(alpha);
   preconditioner_in_.SetRank(rank_in);
   preconditioner_out_.SetRank(rank_out);
   preconditioner_in_.SetNumSamplesHistory(num_samples_history);
   preconditioner_out_.SetNumSamplesHistory(num_samples_history);
   preconditioner_in_.SetUpdatePeriod(update_period);
   preconditioner_out_.SetUpdatePeriod(update_period);
   ExpectToken(is, binary, "</LinearComponent>");
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 3282 of file nnet-simple-component.cc.
References LinearComponent::params_.
Referenced by ModelCollapser::GetScaledComponentIndex().
{
   if (scale == 0.0) params_.SetZero();
   else params_.Scale(scale);
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 932 of file nnet-simple-component.h.
Referenced by FixedAffineComponent::InitFromConfig().
 { return "LinearComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 3306 of file nnet-simple-component.cc.
References VectorBase< Real >::Dim(), KALDI_ASSERT, LinearComponent::NumParameters(), and LinearComponent::params_.
{
   KALDI_ASSERT(params.Dim() == this->NumParameters());
   params_.CopyRowsFromVec(params);
 }
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 3302 of file nnet-simple-component.cc.
References VectorBase< Real >::CopyRowsFromMat(), VectorBase< Real >::Dim(), KALDI_ASSERT, LinearComponent::NumParameters(), and LinearComponent::params_.
{
   KALDI_ASSERT(params->Dim() == this->NumParameters());
   params->CopyRowsFromMat(params_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3159 of file nnet-simple-component.cc.
References OnlineNaturalGradient::GetAlpha(), OnlineNaturalGradient::GetNumSamplesHistory(), OnlineNaturalGradient::GetRank(), OnlineNaturalGradient::GetUpdatePeriod(), AffineComponent::orthonormal_constraint_, NaturalGradientAffineComponent::preconditioner_in_, NaturalGradientAffineComponent::preconditioner_out_, kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write the opening tag and learning rate
   WriteToken(os, binary, "<Params>");
   params_.Write(os, binary);
   if (orthonormal_constraint_ != 0.0) {
     WriteToken(os, binary, "<OrthonormalConstraint>");
     WriteBasicType(os, binary, orthonormal_constraint_);
   }
   WriteToken(os, binary, "<UseNaturalGradient>");
   WriteBasicType(os, binary, use_natural_gradient_);
   int32 rank_in = preconditioner_in_.GetRank(),
       rank_out = preconditioner_out_.GetRank(),
       update_period = preconditioner_in_.GetUpdatePeriod();
   BaseFloat alpha = preconditioner_in_.GetAlpha(),
       num_samples_history = preconditioner_in_.GetNumSamplesHistory();
   WriteToken(os, binary, "<RankInOut>");
   WriteBasicType(os, binary, rank_in);
   WriteBasicType(os, binary, rank_out);
   WriteToken(os, binary, "<Alpha>");
   WriteBasicType(os, binary, alpha);
   WriteToken(os, binary, "<NumSamplesHistory>");
   WriteBasicType(os, binary, num_samples_history);
   WriteToken(os, binary, "<UpdatePeriod>");
   WriteBasicType(os, binary, update_period);
   WriteToken(os, binary, "</LinearComponent>");
 }
Member Data Documentation
orthonormal_constraint_
BaseFloat orthonormal_constraint_ private
Definition at line 982 of file nnet-simple-component.h.
params_
CuMatrix<BaseFloat> params_ private
Definition at line 980 of file nnet-simple-component.h.
Referenced by LinearComponent::Add(), LinearComponent::Backprop(), LinearComponent::DotProduct(), LinearComponent::NumParameters(), LinearComponent::PerturbParams(), LinearComponent::Scale(), LinearComponent::UnVectorize(), and LinearComponent::Vectorize().
preconditioner_in_
OnlineNaturalGradient preconditioner_in_ private
Definition at line 985 of file nnet-simple-component.h.
Referenced by LinearComponent::Backprop(), LinearComponent::ConsolidateMemory(), LinearComponent::FreezeNaturalGradient(), and LinearComponent::LinearComponent().
preconditioner_out_
OnlineNaturalGradient preconditioner_out_ private
Definition at line 986 of file nnet-simple-component.h.
Referenced by LinearComponent::Backprop(), LinearComponent::ConsolidateMemory(), LinearComponent::FreezeNaturalGradient(), and LinearComponent::LinearComponent().
use_natural_gradient_
bool use_natural_gradient_ private
Definition at line 984 of file nnet-simple-component.h.
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc