Kaldi: StatisticsExtractionComponent Class Reference
StatisticsExtractionComponent Class Reference
#include <nnet-general-component.h>
Public Member Functions
StatisticsExtractionComponent ()
StatisticsExtractionComponent (const StatisticsExtractionComponent &other)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
void Check () const
StatisticsExtractionComponent & operator= (const StatisticsExtractionComponent &other)
Private Attributes
int32 input_dim_
int32 input_period_
int32 output_period_
bool include_variance_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 201 of file nnet-general-component.h.
Constructor & Destructor Documentation
StatisticsExtractionComponent() [1/2]
StatisticsExtractionComponent ()
Definition at line 353 of file nnet-general-component.cc.
                                                             :
     input_dim_(-1), input_period_(1), output_period_(1),
     include_variance_(true) { }
StatisticsExtractionComponent() [2/2]
StatisticsExtractionComponent (const StatisticsExtractionComponent & other)
Definition at line 357 of file nnet-general-component.cc.
References StatisticsExtractionComponent::Check().
                                                :
     input_dim_(other.input_dim_),
     input_period_(other.input_period_),
     output_period_(other.output_period_),
     include_variance_(other.include_variance_) {
   Check();
 }
Member Function Documentation
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 476 of file nnet-general-component.cc.
References CuMatrixBase< Real >::AddMatMatElements(), CuMatrixBase< Real >::AddRows(), StatisticsExtractionComponentPrecomputedIndexes::backward_indexes, CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyRows(), StatisticsExtractionComponent::include_variance_, StatisticsExtractionComponent::input_dim_, KALDI_ASSERT, kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::SetZero().
{
   KALDI_ASSERT(indexes_in != NULL);
   const StatisticsExtractionComponentPrecomputedIndexes *indexes =
       dynamic_cast<const StatisticsExtractionComponentPrecomputedIndexes*>(indexes_in);
   in_deriv->SetZero();
   in_deriv->AddRows(1.0, out_deriv.ColRange(1, input_dim_),
                     indexes->backward_indexes);
   if (include_variance_) {
     CuMatrix<BaseFloat> variance_deriv(in_value.NumRows(),
                                        in_value.NumCols(),
                                        kUndefined);
     variance_deriv.CopyRows(out_deriv.ColRange(1 + input_dim_, input_dim_),
                             indexes->backward_indexes);
     in_deriv->AddMatMatElements(2.0, variance_deriv, in_value, 1.0);
   }
 }
Check()
void Check () const private
Definition at line 382 of file nnet-general-component.cc.
References StatisticsExtractionComponent::input_dim_, StatisticsExtractionComponent::input_period_, KALDI_ERR, and StatisticsExtractionComponent::output_period_.
Referenced by StatisticsExtractionComponent::InitFromConfig(), StatisticsPoolingComponent::InitFromConfig(), StatisticsExtractionComponent::Read(), and StatisticsExtractionComponent::StatisticsExtractionComponent().
{
   if (!(input_dim_ > 0 && input_period_ > 0 && output_period_ > 0 &&
         (output_period_ % input_period_) == 0))
     KALDI_ERR << "Invalid configuration of StatisticsExtractionComponent";
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 237 of file nnet-general-component.h.
References DistributeComponent::GetInputIndexes(), DistributeComponent::IsComputable(), DistributeComponent::PrecomputeIndexes(), and Component::ReorderIndexes().
{
     return new StatisticsExtractionComponent(*this);
   }
GetInputIndexes()
void GetInputIndexes (const MiscComputationInfo & misc_info, const Index & output_index, std::vector< Index > * desired_indexes) const virtual
This function only does something interesting for non-simple Components.
For a given index at the output of the component, tells us what indexes are required at its input (note: "required" encompasses also optionally-required things; it will enumerate all things that we'd like to have). See also IsComputable().
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. We will add members to misc_info as needed.
[in] output_index The Index at the output of the component, for which we are requesting the list of indexes at the component's input.
[out] desired_indexes A list of indexes that are desired at the input. are to be written to here. By "desired" we mean required or optionally-required.
The default implementation of this function is suitable for any SimpleComponent; it just copies the output_index to a single identical element in input_indexes.
Reimplemented from Component.
Definition at line 429 of file nnet-general-component.cc.
References StatisticsExtractionComponent::input_period_, StatisticsExtractionComponent::output_period_, and Index::t.
{
   desired_indexes->clear();
   Index input_index(output_index);
   int32 t = output_index.t,
       t_start = output_period_ * (t / output_period_);
   if (t_start > t)                // could happen for negative t due to
     t_start -= output_period_;    // the way modulus works in C
   int32 t_end = t_start + output_period_;
   for (int32 t = t_start; t < t_end; t += input_period_) {
     input_index.t = t;
     desired_indexes->push_back(input_index);
   }
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 366 of file nnet-general-component.cc.
References StatisticsExtractionComponent::Check(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), StatisticsExtractionComponent::include_variance_, StatisticsExtractionComponent::input_dim_, StatisticsExtractionComponent::input_period_, KALDI_ERR, StatisticsExtractionComponent::output_period_, StatisticsExtractionComponent::Type(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   // input-dim is required.
   bool ok = cfl->GetValue("input-dim", &input_dim_);
   cfl->GetValue("input-period", &input_period_);
   cfl->GetValue("output-period", &output_period_);
   cfl->GetValue("include-variance", &include_variance_);
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   if (!ok || input_dim_ <= 0 || input_period_ <= 0 || output_period_ <= 0 ||
       (output_period_ % input_period_ != 0))
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Check();
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 209 of file nnet-general-component.h.
References DistributeComponent::input_dim_.
 { return input_dim_; }
IsComputable()
bool IsComputable (const MiscComputationInfo & misc_info, const Index & output_index, const IndexSet & input_index_set, std::vector< Index > * used_inputs) const virtual
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
It tells the user whether a given output index is computable from a given set of input indexes, and if so, says which input indexes will be used in the computation.
Implementations of this function are required to have the property that adding an element to "input_index_set" can only ever change IsComputable from false to true, never vice versa.
Parameters
[in] misc_info Some information specific to the computation, such as minimum and maximum times for certain components to do adaptation on; it's a place to put things that don't easily fit in the framework.
[in] output_index The index that is to be computed at the output of this Component.
[in] input_index_set The set of indexes that is available at the input of this Component.
[out] used_inputs If this is non-NULL and the output is computable this will be set to the list of input indexes that will actually be used in the computation.
Returns
Returns true iff this output is computable from the provided inputs.
The default implementation of this function is suitable for any SimpleComponent: it just returns true if output_index is in input_index_set, and if so sets used_inputs to vector containing that one Index.
Reimplemented from Component.
Definition at line 397 of file nnet-general-component.cc.
References StatisticsExtractionComponent::input_period_, StatisticsExtractionComponent::output_period_, and Index::t.
{
   Index input_index(output_index);
   int32 t = output_index.t,
       t_start = output_period_ * (t / output_period_);
   if (t_start > t)                // could happen for negative t_start due to
     t_start -= output_period_;    // the way modulus works in C.
   int32 t_end = t_start + output_period_;
   if (!used_inputs) {
     for (int32 t = t_start; t < t_end; t += input_period_) {
       input_index.t = t;
       if (input_index_set(input_index))
         return true;
     }
     return false;
   } else {
     used_inputs->clear();
     bool ans = false;
     for (int32 t = t_start; t < t_end; t += input_period_) {
       input_index.t = t;
       if (input_index_set(input_index)) {
         ans = true;
         used_inputs->push_back(input_index);
       }
     }
     return ans;
   }
 }
operator=()
StatisticsExtractionComponent& operator= (const StatisticsExtractionComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 210 of file nnet-general-component.h.
References DistributeComponent::InitFromConfig(), and DistributeComponent::input_dim_.
Referenced by StatisticsExtractionComponent::Propagate().
{
     // count + sum stats [ + sum-squared stats].
     return 1 + input_dim_ + (include_variance_ ? input_dim_ : 0);
   }
PrecomputeIndexes()
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo & misc_info, const std::vector< Index > & input_indexes, const std::vector< Index > & output_indexes, bool need_backprop) const virtual
This function must return NULL for simple Components.
Returns a pointer to a class that may contain some precomputed component-specific and computation-specific indexes to be in used in the Propagate and Backprop functions.
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. misc_info may not even ever be used here. We will add members to misc_info as needed.
[in] input_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the in/in_value/in_deriv matrices given to Propagate and Backprop will mean.
[in] output_indexes A vector of indexes that explains what time-indexes (and other indexes) each row of the out/out_value/out_deriv matrices given to Propagate and Backprop will mean.
[in] need_backprop True if we might need to do backprop with this component, so that if any different indexes are needed for backprop then those should be computed too.
Returns
Returns a child-class of class ComponentPrecomputedIndexes, or NULL if this component for does not need to precompute any indexes (e.g. if it is a simple component and does not care about indexes).
Reimplemented from Component.
Definition at line 288 of file nnet-general-component.cc.
References StatisticsExtractionComponentPrecomputedIndexes::backward_indexes, StatisticsExtractionComponentPrecomputedIndexes::counts, Int32Pair::first, StatisticsExtractionComponentPrecomputedIndexes::forward_indexes, rnnlm::i, KALDI_ASSERT, Int32Pair::second, and Index::t.
{
   int32 num_input_indexes = input_indexes.size(),
       num_output_indexes = output_indexes.size();
   StatisticsExtractionComponentPrecomputedIndexes *ans = new
       StatisticsExtractionComponentPrecomputedIndexes();
   // both input and output indexes are assumed sorted first on
   // n and x, then on t.
   Int32Pair invalid_pair;
   invalid_pair.first = -1;
   invalid_pair.second = -1;
   std::vector<Int32Pair> forward_indexes_cpu(output_indexes.size(),
                                              invalid_pair);
   std::vector<int32> backward_indexes_cpu(input_indexes.size(), -1);
   Vector<BaseFloat> counts_cpu(output_indexes.size());
   // this map maps from Index to the position in 'input_indexes'.
   unordered_map<Index, int32, IndexHasher> index_to_input_pos;
   for (int32 i = 0; i < num_input_indexes; i++)
     index_to_input_pos[input_indexes[i]] = i;
   for (int32 i = 0; i < num_output_indexes; i++) {
     Index output_index = output_indexes[i];
     Index input_index(output_index);
     int32 t = output_index.t,
         t_start = output_period_ * (t / output_period_);
     if (t_start > t)                // could happen for negative t_start due to
       t_start -= output_period_;    // the way modulus works in C.
     int32 t_end = t_start + output_period_;
     for (int32 t = t_start; t < t_end; t += input_period_) {
       input_index.t = t;
       unordered_map<Index, int32, IndexHasher>::iterator iter =
           index_to_input_pos.find(input_index);
       if (iter != index_to_input_pos.end()) {
         int32 input_pos = iter->second;
         if (forward_indexes_cpu[i].first == -1) {
           forward_indexes_cpu[i].first = input_pos;
           forward_indexes_cpu[i].second = input_pos + 1;
           counts_cpu(i) = 1.0;
         } else {
           // the following might fail, for instance, if the sorting
           // of the input or output indexes was not as expected.
           KALDI_ASSERT(forward_indexes_cpu[i].second == input_pos);
           forward_indexes_cpu[i].second++;
           counts_cpu(i) += 1.0;
         }
         KALDI_ASSERT(backward_indexes_cpu[input_pos] == -1);
         backward_indexes_cpu[input_pos] = i;
       }
     }
     KALDI_ASSERT(counts_cpu(i) != 0.0);
   }
   for (int32 i = 0; i < num_input_indexes; i++) {
     KALDI_ASSERT(backward_indexes_cpu[i] != -1);
   }
   ans->forward_indexes = forward_indexes_cpu;
   ans->counts = counts_cpu;
   if (need_backprop)
     ans->backward_indexes = backward_indexes_cpu;
   return ans;
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 447 of file nnet-general-component.cc.
References CuMatrixBase< Real >::ApplyPow(), CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyColFromVec(), StatisticsExtractionComponentPrecomputedIndexes::counts, CuArrayBase< T >::Dim(), StatisticsExtractionComponentPrecomputedIndexes::forward_indexes, StatisticsExtractionComponent::include_variance_, StatisticsExtractionComponent::input_dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), StatisticsExtractionComponent::OutputDim(), and CuMatrixBase< Real >::SetZero().
{
   KALDI_ASSERT(indexes_in != NULL);
   const StatisticsExtractionComponentPrecomputedIndexes *indexes =
      dynamic_cast<const StatisticsExtractionComponentPrecomputedIndexes*>(
          indexes_in);
   int32 num_rows_out = out->NumRows();
   KALDI_ASSERT(indexes != NULL &&
                indexes->forward_indexes.Dim() == num_rows_out &&
                in.NumCols() == input_dim_ &&
                out->NumCols() == OutputDim());
   out->SetZero();
   // store the counts.
   out->CopyColFromVec(indexes->counts, 0);
   // store the mean stats
   out->ColRange(1, input_dim_).AddRowRanges(in, indexes->forward_indexes);
   if (include_variance_) {
     // store the variance (sum-squared) stats.
     CuMatrix<BaseFloat> in_squared(in);
     in_squared.ApplyPow(2.0);
     out->ColRange(input_dim_ + 1,
                   input_dim_).AddRowRanges(in_squared,
                                            indexes->forward_indexes);
   }
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 216 of file nnet-general-component.h.
References DistributeComponent::Backprop(), kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kPropagateAdds, kaldi::nnet3::kReordersIndexes, DistributeComponent::Propagate(), DistributeComponent::Read(), and DistributeComponent::Write().
{
     return kPropagateAdds|kReordersIndexes|
         (include_variance_ ? kBackpropNeedsInput : 0);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 501 of file nnet-general-component.cc.
References StatisticsExtractionComponent::Check(), kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), StatisticsExtractionComponent::include_variance_, StatisticsExtractionComponent::input_dim_, StatisticsExtractionComponent::input_period_, StatisticsExtractionComponent::output_period_, and kaldi::ReadBasicType().
{
   ExpectOneOrTwoTokens(is, binary, "<StatisticsExtractionComponent>",
                        "<InputDim>");
   ReadBasicType(is, binary, &input_dim_);
   ExpectToken(is, binary, "<InputPeriod>");
   ReadBasicType(is, binary, &input_period_);
   ExpectToken(is, binary, "<OutputPeriod>");
   ReadBasicType(is, binary, &output_period_);
   ExpectToken(is, binary, "<IncludeVarinance>");
   ReadBasicType(is, binary, &include_variance_);
   ExpectToken(is, binary, "</StatisticsExtractionComponent>");
   Check();
 }
ReorderIndexes()
void ReorderIndexes (std::vector< Index > * input_indexes, std::vector< Index > * output_indexes) const virtual
This function only does something interesting for non-simple Components.
It provides an opportunity for a Component to reorder the or pad the indexes at its input and output. This might be useful, for instance, if a component requires a particular ordering of the indexes that doesn't correspond to their natural ordering. Components that might modify the indexes are required to return the kReordersIndexes flag in their Properties(). The ReorderIndexes() function is now allowed to insert blanks into the indexes. The 'blanks' must be of the form (n,kNoTime,x), where the marker kNoTime (a very negative number) is there where the 't' indexes normally live. The reason we don't just have, say, (-1,-1,-1), relates to the need to preserve a regular pattern over the 'n' indexes so that 'shortcut compilation' (c.f. ExpandComputation()) can work correctly
Parameters
[in,out] Indexes at the input of the Component.
[in,out] Indexes at the output of the Component
Reimplemented from Component.
Definition at line 388 of file nnet-general-component.cc.
{
     std::sort(input_indexes->begin(), input_indexes->end(),
               IndexLessNxt());
     std::sort(output_indexes->begin(), output_indexes->end(),
               IndexLessNxt());
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 215 of file nnet-general-component.h.
Referenced by StatisticsExtractionComponent::InitFromConfig(), and StatisticsPoolingComponent::InitFromConfig().
 { return "StatisticsExtractionComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 515 of file nnet-general-component.cc.
References StatisticsExtractionComponent::include_variance_, StatisticsExtractionComponent::input_dim_, StatisticsExtractionComponent::input_period_, StatisticsExtractionComponent::output_period_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<StatisticsExtractionComponent>");
   WriteToken(os, binary, "<InputDim>");
   WriteBasicType(os, binary, input_dim_);
   WriteToken(os, binary, "<InputPeriod>");
   WriteBasicType(os, binary, input_period_);
   WriteToken(os, binary, "<OutputPeriod>");
   WriteBasicType(os, binary, output_period_);
   WriteToken(os, binary, "<IncludeVarinance>");
   WriteBasicType(os, binary, include_variance_);
   WriteToken(os, binary, "</StatisticsExtractionComponent>");
 }
Member Data Documentation
include_variance_
bool include_variance_ private
Definition at line 273 of file nnet-general-component.h.
Referenced by StatisticsExtractionComponent::Backprop(), StatisticsExtractionComponent::InitFromConfig(), StatisticsExtractionComponent::Propagate(), StatisticsExtractionComponent::Read(), and StatisticsExtractionComponent::Write().
input_dim_
int32 input_dim_ private
Definition at line 270 of file nnet-general-component.h.
Referenced by StatisticsExtractionComponent::Backprop(), StatisticsExtractionComponent::Check(), StatisticsExtractionComponent::InitFromConfig(), StatisticsPoolingComponent::InitFromConfig(), StatisticsExtractionComponent::Propagate(), StatisticsExtractionComponent::Read(), and StatisticsExtractionComponent::Write().
input_period_
int32 input_period_ private
Definition at line 271 of file nnet-general-component.h.
Referenced by StatisticsExtractionComponent::Check(), StatisticsExtractionComponent::GetInputIndexes(), StatisticsExtractionComponent::InitFromConfig(), StatisticsPoolingComponent::InitFromConfig(), StatisticsExtractionComponent::IsComputable(), StatisticsExtractionComponent::Read(), and StatisticsExtractionComponent::Write().
output_period_
int32 output_period_ private
Definition at line 272 of file nnet-general-component.h.
Referenced by StatisticsExtractionComponent::Check(), StatisticsExtractionComponent::GetInputIndexes(), StatisticsExtractionComponent::InitFromConfig(), StatisticsExtractionComponent::IsComputable(), StatisticsExtractionComponent::Read(), and StatisticsExtractionComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc