Kaldi: DropoutMaskComponent Class Reference
DropoutMaskComponent Class Reference
#include <nnet-general-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
DropoutMaskComponent ()
DropoutMaskComponent (const DropoutMaskComponent &other)
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
void SetDropoutProportion (BaseFloat p)
Public Member Functions inherited from RandomComponent
void ResetGenerator ()
void SetTestMode (bool test_mode)
RandomComponent ()
RandomComponent (const RandomComponent &other)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
const DropoutMaskComponent & operator= (const DropoutMaskComponent &other)
Private Attributes
int32 output_dim_
BaseFloat dropout_proportion_
bool continuous_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Attributes inherited from RandomComponent
CuRand< BaseFloat > random_generator_
bool test_mode_
Detailed Description
Definition at line 709 of file nnet-general-component.h.
Constructor & Destructor Documentation
DropoutMaskComponent() [1/2]
DropoutMaskComponent ()
Definition at line 1403 of file nnet-general-component.cc.
Referenced by DropoutMaskComponent::Copy().
                                           :
     output_dim_(-1), dropout_proportion_(0.5), continuous_(false) { }
DropoutMaskComponent() [2/2]
DropoutMaskComponent (const DropoutMaskComponent & other)
Definition at line 1406 of file nnet-general-component.cc.
                                       :
     output_dim_(other.output_dim_),
     dropout_proportion_(other.dropout_proportion_),
     continuous_(other.continuous_) { }
Member Function Documentation
Backprop()
virtual void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const inline virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 740 of file nnet-general-component.h.
References DistributeComponent::Copy(), DistributeComponent::Read(), and DistributeComponent::Write().
                                                                  { }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 1503 of file nnet-general-component.cc.
References DropoutMaskComponent::DropoutMaskComponent().
{
   return new DropoutMaskComponent(*this);
 }
GetInputIndexes()
virtual void GetInputIndexes (const MiscComputationInfo & misc_info, const Index & output_index, std::vector< Index > * desired_indexes) const inline virtual
This function only does something interesting for non-simple Components.
For a given index at the output of the component, tells us what indexes are required at its input (note: "required" encompasses also optionally-required things; it will enumerate all things that we'd like to have). See also IsComputable().
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. We will add members to misc_info as needed.
[in] output_index The Index at the output of the component, for which we are requesting the list of indexes at the component's input.
[out] desired_indexes A list of indexes that are desired at the input. are to be written to here. By "desired" we mean required or optionally-required.
The default implementation of this function is suitable for any SimpleComponent; it just copies the output_index to a single identical element in input_indexes.
Reimplemented from Component.
Definition at line 755 of file nnet-general-component.h.
{
     desired_indexes->clear();  // requires no inputs.
   }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 1393 of file nnet-general-component.cc.
References ConstantComponent::Type().
{
   std::ostringstream stream;
   stream << Type()
          << ", output-dim=" << output_dim_
          << ", dropout-proportion=" << dropout_proportion_;
   if (continuous_)
     stream << ", continuous=true";
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 1507 of file nnet-general-component.cc.
References DropoutMaskComponent::continuous_, DropoutMaskComponent::dropout_proportion_, ConfigLine::GetValue(), KALDI_ASSERT, DropoutMaskComponent::output_dim_, and RandomComponent::test_mode_.
{
   output_dim_ = 0;
   bool ok = cfl->GetValue("output-dim", &output_dim_);
   KALDI_ASSERT(ok && output_dim_ > 0);
   dropout_proportion_ = 0.5;
   cfl->GetValue("dropout-proportion", &dropout_proportion_);
   continuous_ = false;
   cfl->GetValue("continuous", &continuous_);
   test_mode_ = false;
   cfl->GetValue("test-mode", &test_mode_);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 713 of file nnet-general-component.h.
References DistributeComponent::output_dim_.
 { return output_dim_; }
IsComputable()
virtual bool IsComputable (const MiscComputationInfo & misc_info, const Index & output_index, const IndexSet & input_index_set, std::vector< Index > * used_inputs) const inline virtual
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
It tells the user whether a given output index is computable from a given set of input indexes, and if so, says which input indexes will be used in the computation.
Implementations of this function are required to have the property that adding an element to "input_index_set" can only ever change IsComputable from false to true, never vice versa.
Parameters
[in] misc_info Some information specific to the computation, such as minimum and maximum times for certain components to do adaptation on; it's a place to put things that don't easily fit in the framework.
[in] output_index The index that is to be computed at the output of this Component.
[in] input_index_set The set of indexes that is available at the input of this Component.
[out] used_inputs If this is non-NULL and the output is computable this will be set to the list of input indexes that will actually be used in the computation.
Returns
Returns true iff this output is computable from the provided inputs.
The default implementation of this function is suitable for any SimpleComponent: it just returns true if output_index is in input_index_set, and if so sets used_inputs to vector containing that one Index.
Reimplemented from Component.
Definition at line 764 of file nnet-general-component.h.
{
     if (used_inputs) used_inputs->clear();
     return true;
   }
operator=()
const DropoutMaskComponent& operator= (const DropoutMaskComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 715 of file nnet-general-component.h.
References Component::Info(), DistributeComponent::InitFromConfig(), and DistributeComponent::output_dim_.
 { return output_dim_; }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 1412 of file nnet-general-component.cc.
References CuVectorBase< Real >::Add(), CuMatrixBase< Real >::Add(), CuMatrixBase< Real >::ApplyHeaviside(), DropoutMaskComponent::continuous_, CuMatrixBase< Real >::CopyColFromVec(), DropoutMaskComponent::dropout_proportion_, KALDI_ASSERT, kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), DropoutMaskComponent::output_dim_, RandomComponent::random_generator_, kaldi::RandUniform(), CuVectorBase< Real >::Scale(), CuMatrixBase< Real >::Scale(), CuMatrixBase< Real >::Set(), and RandomComponent::test_mode_.
{
   KALDI_ASSERT(in.NumRows() == 0 && out->NumCols() == output_dim_);
   BaseFloat dropout_proportion = dropout_proportion_;
   KALDI_ASSERT(dropout_proportion >= 0.0 && dropout_proportion <= 1.0);
   if (dropout_proportion == 0) {
     out->Set(1.0);
     return NULL;
   }
   if (continuous_) {
     if (test_mode_) {
       out->Set(1.0);
     } else {
       const_cast<CuRand<BaseFloat>&>(random_generator_).RandUniform(out);
       out->Scale(dropout_proportion * 4.0);
       // make the expected value 1.0.
       out->Add(1.0 - (2.0 * dropout_proportion));
     }
     return NULL;
   }
   if (test_mode_) {
     out->Set(1.0 - dropout_proportion);
     return NULL;
   }
   const_cast<CuRand<BaseFloat>&>(random_generator_).RandUniform(out);
   out->Add(-dropout_proportion);
   out->ApplyHeaviside();
   if (out->NumCols() == 2 || out->NumCols() == 3) {
     // This is a kind of special case relevant to LSTms.
     // To generate data where it's never the case that both of the dimensions
     // for a row are zero, we generate uniformly distributed data (call this u_i),
     // and for row i, set (*out)(i, 0) = (0 if u_i < dropout_proportion else 1)
     //                and (*out)(i, 1) = (0 if u_i > 1-dropout_proportion else 1)
     int32 num_rows = out->NumRows();
     // later we may make this a bit more efficient.
     CuVector<BaseFloat> temp(num_rows, kUndefined);
     const_cast<CuRand<BaseFloat>&>(random_generator_).RandUniform(&temp);
     temp.Add(-dropout_proportion);
     out->CopyColFromVec(temp, 0);
     temp.Add(-1.0 + (2.0 * dropout_proportion));
     // Now, 'temp' contains the original uniformly-distributed data plus
     // -(1 - dropout_proportion).
     temp.Scale(-1.0);
     out->CopyColFromVec(temp, 1);
     out->ApplyHeaviside();
   }
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 733 of file nnet-general-component.h.
References kaldi::nnet3::kRandomComponent, and DistributeComponent::Propagate().
 { return kRandomComponent; }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 1469 of file nnet-general-component.cc.
References DropoutMaskComponent::continuous_, DropoutMaskComponent::dropout_proportion_, kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), DropoutMaskComponent::output_dim_, kaldi::PeekToken(), kaldi::ReadBasicType(), and RandomComponent::test_mode_.
{
   ExpectOneOrTwoTokens(is, binary, "<DropoutMaskComponent>", "<OutputDim>");
   ReadBasicType(is, binary, &output_dim_);
   ExpectToken(is, binary, "<DropoutProportion>");
   ReadBasicType(is, binary, &dropout_proportion_);
   if (PeekToken(is, binary) == 'T') {
     ExpectToken(is, binary, "<TestMode>");
     ReadBasicType(is, binary, &test_mode_);  // read test mode
   } else {
     test_mode_ = false;
   }
   if (PeekToken(is, binary) == 'C') {
     ExpectToken(is, binary, "<Continuous>");
     continuous_ = true;
   } else {
     continuous_ = false;
   }
   ExpectToken(is, binary, "</DropoutMaskComponent>");
 }
SetDropoutProportion()
void SetDropoutProportion (BaseFloat p) inline
Definition at line 772 of file nnet-general-component.h.
Referenced by kaldi::nnet3::ReadEditConfig(), and kaldi::nnet3::SetDropoutProportion().
 { dropout_proportion_ = p; }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 732 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::Info().
 { return "DropoutMaskComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 1490 of file nnet-general-component.cc.
References DropoutMaskComponent::continuous_, DropoutMaskComponent::dropout_proportion_, DropoutMaskComponent::output_dim_, RandomComponent::test_mode_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<DropoutMaskComponent>");
   WriteToken(os, binary, "<OutputDim>");
   WriteBasicType(os, binary, output_dim_);
   WriteToken(os, binary, "<DropoutProportion>");
   WriteBasicType(os, binary, dropout_proportion_);
   WriteToken(os, binary, "<TestMode>");
   WriteBasicType(os, binary, test_mode_);
   if (continuous_)
     WriteToken(os, binary, "<Continuous>");
   WriteToken(os, binary, "</DropoutMaskComponent>");
 }
Member Data Documentation
continuous_
bool continuous_ private
Definition at line 781 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::Info(), DropoutMaskComponent::InitFromConfig(), DropoutMaskComponent::Propagate(), DropoutMaskComponent::Read(), and DropoutMaskComponent::Write().
dropout_proportion_
BaseFloat dropout_proportion_ private
Definition at line 779 of file nnet-general-component.h.
Referenced by GeneralDropoutComponent::Info(), DropoutMaskComponent::InitFromConfig(), DropoutMaskComponent::Propagate(), DropoutMaskComponent::Read(), and DropoutMaskComponent::Write().
output_dim_
int32 output_dim_ private
Definition at line 777 of file nnet-general-component.h.
Referenced by DropoutMaskComponent::InitFromConfig(), DropoutMaskComponent::Propagate(), DropoutMaskComponent::Read(), and DropoutMaskComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc