Kaldi: LatticeHolder Class Reference
LatticeHolder Class Reference
#include <kaldi-lattice.h>
Public Types
typedef Lattice T
Public Member Functions
LatticeHolder ()
bool Read (std::istream &is)
T & Value ()
void Clear ()
void Swap (LatticeHolder *other)
bool ExtractRange (const LatticeHolder &other, const std::string &range)
~LatticeHolder ()
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Attributes
T * t_
Detailed Description
Definition at line 107 of file kaldi-lattice.h.
Member Typedef Documentation
T
typedef Lattice T
Definition at line 109 of file kaldi-lattice.h.
Constructor & Destructor Documentation
LatticeHolder()
LatticeHolder () inline
Definition at line 111 of file kaldi-lattice.h.
References CompactLatticeHolder::t_.
 { t_ = NULL; }
~LatticeHolder()
~LatticeHolder () inline
Definition at line 140 of file kaldi-lattice.h.
References CompactLatticeHolder::Clear().
 { Clear(); }
Member Function Documentation
Clear()
void Clear () inline
Definition at line 129 of file kaldi-lattice.h.
References CompactLatticeHolder::t_.
 {  delete t_; t_ = NULL; }
ExtractRange()
bool ExtractRange (const LatticeHolder & other, const std::string & range) inline
Definition at line 135 of file kaldi-lattice.h.
References KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 122 of file kaldi-lattice.h.
 { return true; }
Read()
bool Read (std::istream & is)
Definition at line 482 of file kaldi-lattice.cc.
References KALDI_WARN, and kaldi::ReadLattice().
{
   Clear(); // in case anything currently stored.
   int c = is.peek();
   if (c == -1) {
     KALDI_WARN << "End of stream detected reading Lattice.";
     return false;
   } else if (isspace(c)) { // The text form of the lattice begins
     // with space (normally, '\n'), so this means it's text (the binary form
     // cannot begin with space because it starts with the FST Type() which is not
     // space).
     return ReadLattice(is, false, &t_);
   } else if (c != 214) { // 214 is first char of FST magic number,
     // on little-endian machines which is all we support (\326 octal)
     KALDI_WARN << "Reading compact lattice: does not appear to be an FST "
                << " [non-space but no magic number detected], file pos is "
                << is.tellg();
     return false;
   } else {
     return ReadLattice(is, true, &t_);
   }
 }
Swap()
void Swap (LatticeHolder * other) inline
Definition at line 131 of file kaldi-lattice.h.
References kaldi::swap(), CompactLatticeHolder::t_, and LatticeHolder::t_.
{
     std::swap(t_, other->t_);
   }
Value()
T& Value () inline
Definition at line 124 of file kaldi-lattice.h.
References KALDI_ASSERT, and CompactLatticeHolder::t_.
              {
     KALDI_ASSERT(t_ != NULL && "Called Value() on empty LatticeHolder");
     return *t_;
   }
Write()
static bool Write (std::ostream & os, bool binary, const T & t) inline static
Definition at line 113 of file kaldi-lattice.h.
References CompactLatticeHolder::Read(), and kaldi::WriteLattice().
{
     // Note: we don't include the binary-mode header when writing
     // this object to disk; this ensures that if we write to single
     // files, the result can be read by OpenFst.
     return WriteLattice(os, binary, t);
   }
Member Data Documentation
t_
T* t_ private
Definition at line 142 of file kaldi-lattice.h.
Referenced by LatticeHolder::Swap().
The documentation for this class was generated from the following files:
lat/kaldi-lattice.h
lat/kaldi-lattice.cc