Kaldi: ClipGradientComponent Class Reference
ClipGradientComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
ClipGradientComponent (int32 dim, BaseFloat clipping_threshold, bool norm_based_clipping, BaseFloat self_repair_clipped_proportion_threshold, BaseFloat self_repair_target, BaseFloat self_repair_scale, int32 num_clipped, int32 count, int32 num_self_repaired, int32 num_backpropped)
ClipGradientComponent ()
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
void Init (int32 dim, BaseFloat clipping_threshold, bool norm_based_clipping, BaseFloat self_repair_clipped_proportion_threshold, BaseFloat self_repair_target, BaseFloat self_repair_scale, int32 num_clipped, int32 count, int32 num_self_repaired, int32 num_backpropped)
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual Component * Copy () const
Copies component (deep copy).
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual ~ClipGradientComponent ()
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Attributes
int32 num_clipped_
int32 count_
int32 num_self_repaired_
int32 num_backpropped_
Private Member Functions
void RepairGradients (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, CuMatrixBase< BaseFloat > *in_deriv, ClipGradientComponent *to_update) const
ClipGradientComponent & operator= (const ClipGradientComponent &other)
Private Attributes
int32 dim_
BaseFloat clipping_threshold_
bool norm_based_clipping_
BaseFloat self_repair_clipped_proportion_threshold_
BaseFloat self_repair_target_
BaseFloat self_repair_scale_
std::string debug_info_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 1294 of file nnet-simple-component.h.
Constructor & Destructor Documentation
ClipGradientComponent() [1/2]
ClipGradientComponent (int32 dim, BaseFloat clipping_threshold, bool norm_based_clipping, BaseFloat self_repair_clipped_proportion_threshold, BaseFloat self_repair_target, BaseFloat self_repair_scale, int32 num_clipped, int32 count, int32 num_self_repaired, int32 num_backpropped) inline
Definition at line 1296 of file nnet-simple-component.h.
References PnormComponent::Init().
{
     Init(dim, clipping_threshold, norm_based_clipping,
          self_repair_clipped_proportion_threshold,
          self_repair_target,
          self_repair_scale,
          num_clipped, count,
          num_self_repaired, num_backpropped);}
ClipGradientComponent() [2/2]
ClipGradientComponent () inline
Definition at line 1312 of file nnet-simple-component.h.
                          : dim_(0), clipping_threshold_(-1),
     norm_based_clipping_(false),
     self_repair_clipped_proportion_threshold_(1.0),
     self_repair_target_(0.0),
     self_repair_scale_(0.0),
     num_clipped_(0), count_(0),
     num_self_repaired_(0), num_backpropped_(0) { }
~ClipGradientComponent()
virtual ~ClipGradientComponent () inline virtual
Definition at line 1370 of file nnet-simple-component.h.
References KALDI_LOG.
{
     if (num_self_repaired_ > 0)
       KALDI_LOG << "ClipGradientComponent(node_name=" << debug_info_
                 << ")'s self-repair was activated " << num_self_repaired_
                 << " time(s) out of " << num_backpropped_
                 << " times of calling Backprop() in this training job.";
   }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 830 of file nnet-simple-component.cc.
References ClipGradientComponent::count_, KALDI_ASSERT, and ClipGradientComponent::num_clipped_.
{
   const ClipGradientComponent *other =
       dynamic_cast<const ClipGradientComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   count_ += alpha * other->count_;
   num_clipped_ += alpha * other->num_clipped_;
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 675 of file nnet-simple-component.cc.
References CuVectorBase< Real >::AddDiagMat2(), CuMatrixBase< Real >::ApplyCeiling(), CuMatrixBase< Real >::ApplyFloor(), CuMatrixBase< Real >::CopyFromMat(), ClipGradientComponent::count_, kaldi::kNoTrans, CuMatrixBase< Real >::MulRowsVec(), ClipGradientComponent::num_backpropped_, ClipGradientComponent::num_clipped_, CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::SetZero().
{
   // the following statement will do nothing if in_deriv and out_deriv have same
   // memory.
   in_deriv->CopyFromMat(out_deriv);
   ClipGradientComponent *to_update =
       dynamic_cast<ClipGradientComponent*>(to_update_in);
   if (clipping_threshold_ > 0) {
     if (norm_based_clipping_) {
       // each row in the derivative matrix, which corresponds to one sample in
       // the mini-batch, is scaled to have a max-norm of clipping_threshold_
       CuVector<BaseFloat> clipping_scales(in_deriv->NumRows());
       clipping_scales.AddDiagMat2(pow(clipping_threshold_, -2), *in_deriv,
                                   kNoTrans, 0.0);
      // now clipping_scales contains the squared (norm of each row divided by
      //  clipping_threshold)
       int32 num_not_scaled;
       clipping_scales.ApplyFloor(1.0, &num_not_scaled);
      // now clipping_scales contains min(1,
      //    squared-(norm/clipping_threshold))
       if (num_not_scaled != clipping_scales.Dim()) {
         clipping_scales.ApplyPow(-0.5);
         // now clipping_scales contains max(1,
         //       clipping_threshold/vector_norm)
         in_deriv->MulRowsVec(clipping_scales);
         if (to_update != NULL)
           to_update->num_clipped_ += (clipping_scales.Dim() - num_not_scaled);
        }
       if (to_update != NULL)
         to_update->count_ += clipping_scales.Dim();
     } else {
       // each element of the derivative matrix, is clipped to be below the
       // clipping_threshold_
       in_deriv->ApplyCeiling(clipping_threshold_);
       in_deriv->ApplyFloor(-1 * clipping_threshold_);
     }
     if (to_update != NULL) {
       to_update->num_backpropped_ += 1;
       RepairGradients(debug_info, in_value, in_deriv, to_update);
     }
   } else if (clipping_threshold_ == 0.0) {
     in_deriv->SetZero();
   }
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 1339 of file nnet-simple-component.h.
References Component::Add(), PnormComponent::Backprop(), Component::Info(), PnormComponent::Propagate(), PnormComponent::Read(), Component::Scale(), and PnormComponent::Write().
{
     return new ClipGradientComponent(dim_,
                                      clipping_threshold_,
                                      norm_based_clipping_,
                                      self_repair_clipped_proportion_threshold_,
                                      self_repair_target_,
                                      self_repair_scale_,
                                      num_clipped_,
                                      count_,
                                      num_self_repaired_,
                                      num_backpropped_);}
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 597 of file nnet-simple-component.cc.
References DropoutComponent::dim_, and DropoutComponent::Type().
{
   std::ostringstream stream;
   stream << Type() << ", dim=" << dim_
          << ", norm-based-clipping="
          << (norm_based_clipping_ ? "true" : "false")
          << ", clipping-threshold=" << clipping_threshold_
          << ", clipped-proportion="
          << (count_ > 0 ? static_cast<BaseFloat>(num_clipped_)/count_ : 0);
   if (self_repair_scale_ != 0.0)
     stream << ", self-repair-clipped-proportion-threshold="
            << self_repair_clipped_proportion_threshold_
            << ", self-repair-target=" << self_repair_target_
            << ", self-repair-scale=" << self_repair_scale_;
   return stream.str();
 }
Init()
void Init (int32 dim, BaseFloat clipping_threshold, bool norm_based_clipping, BaseFloat self_repair_clipped_proportion_threshold, BaseFloat self_repair_target, BaseFloat self_repair_scale, int32 num_clipped, int32 count, int32 num_self_repaired, int32 num_backpropped)
Definition at line 613 of file nnet-simple-component.cc.
References count, DropoutComponent::dim_, and KALDI_ASSERT.
{
   KALDI_ASSERT(clipping_threshold >= 0 && dim > 0 &&
       self_repair_clipped_proportion_threshold >= 0.0 &&
       self_repair_target >= 0.0 && self_repair_scale >= 0.0);
   dim_ = dim;
   norm_based_clipping_ = norm_based_clipping;
   clipping_threshold_ = clipping_threshold;
   self_repair_clipped_proportion_threshold_ =
       self_repair_clipped_proportion_threshold;
   self_repair_target_ = self_repair_target;
   self_repair_scale_ = self_repair_scale;
   num_clipped_ = num_clipped;
   count_ = count;
   num_self_repaired_ = num_self_repaired;
   num_backpropped_ = num_backpropped;
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 639 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), DropoutComponent::Init(), KALDI_ERR, DropoutComponent::Type(), and ConfigLine::WholeLine().
{
   int32 dim = 0;
   bool ok = cfl->GetValue("dim", &dim);
   bool norm_based_clipping = false;
   BaseFloat clipping_threshold = 15.0;
   BaseFloat self_repair_clipped_proportion_threshold = 0.01;
   BaseFloat self_repair_target = 0.0;
   BaseFloat self_repair_scale = 1.0;
   cfl->GetValue("clipping-threshold", &clipping_threshold);
   cfl->GetValue("norm-based-clipping", &norm_based_clipping);
   cfl->GetValue("self-repair-clipped-proportion-threshold",
                 &self_repair_clipped_proportion_threshold);
   cfl->GetValue("self-repair-target",
                 &self_repair_target);
   cfl->GetValue("self-repair-scale", &self_repair_scale);
   if (!ok || cfl->HasUnusedValues() ||
       clipping_threshold < 0 || dim <= 0 ||
       self_repair_clipped_proportion_threshold < 0.0 ||
       self_repair_target < 0.0 || self_repair_scale < 0.0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(dim, clipping_threshold, norm_based_clipping,
        self_repair_clipped_proportion_threshold,
        self_repair_target,
        self_repair_scale, 0, 0, 0, 0);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1320 of file nnet-simple-component.h.
 { return dim_; }
operator=()
ClipGradientComponent& operator= (const ClipGradientComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1321 of file nnet-simple-component.h.
References count, PnormComponent::Init(), and PnormComponent::InitFromConfig().
 { return dim_; }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 666 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyFromMat().
{
   out->CopyFromMat(in);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1332 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kPropagateInPlace, kaldi::nnet3::kSimpleComponent, and Component::ZeroStats().
{
     return kSimpleComponent|kPropagateInPlace|kBackpropInPlace|
            kBackpropNeedsInput;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 531 of file nnet-simple-component.cc.
References DropoutComponent::dim_, kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), KALDI_ASSERT, kaldi::ReadBasicType(), and kaldi::ReadToken().
{
   // might not see the "<NaturalGradientAffineComponent>" part because
   // of how ReadNew() works.
   ExpectOneOrTwoTokens(is, binary, "<ClipGradientComponent>",
                        "<Dim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<ClippingThreshold>");
   ReadBasicType(is, binary, &clipping_threshold_);
   ExpectToken(is, binary, "<NormBasedClipping>");
   ReadBasicType(is, binary, &norm_based_clipping_);
   std::string token;
   ReadToken(is, binary, &token);
   if (token == "<SelfRepairClippedProportionThreshold>") {
     ReadBasicType(is, binary, &self_repair_clipped_proportion_threshold_);
     ExpectToken(is, binary, "<SelfRepairTarget>");
     ReadBasicType(is, binary, &self_repair_target_);
     ExpectToken(is, binary, "<SelfRepairScale>");
     ReadBasicType(is, binary, &self_repair_scale_);
     ExpectToken(is, binary, "<NumElementsClipped>");
   } else {
     self_repair_clipped_proportion_threshold_ = 1.0;
     self_repair_target_ = 0.0;
     self_repair_scale_ = 0.0;
     KALDI_ASSERT(token == "<NumElementsClipped>");
   }
   ReadBasicType(is, binary, &num_clipped_);
   ExpectToken(is, binary, "<NumElementsProcessed>");
   ReadBasicType(is, binary, &count_);
   ReadToken(is, binary, &token);
   if (token == "<NumSelfRepaired>") {
     ReadBasicType(is, binary, &num_self_repaired_);
     ExpectToken(is, binary, "<NumBackpropped>");
     ReadBasicType(is, binary, &num_backpropped_);
     ExpectToken(is, binary, "</ClipGradientComponent>");
   } else {
     num_self_repaired_ = 0;
     num_backpropped_ = 0;
     KALDI_ASSERT(token == "</ClipGradientComponent>");
   }
 }
RepairGradients()
void RepairGradients (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, CuMatrixBase< BaseFloat > * in_deriv, ClipGradientComponent * to_update) const private
Definition at line 738 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::Add(), CuVectorBase< Real >::AddDiagMat2(), CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::ApplyFloor(), CuMatrixBase< Real >::ApplyHeaviside(), CuMatrixBase< Real >::ApplyPowAbs(), ClipGradientComponent::debug_info_, KALDI_ASSERT, KALDI_LOG, kaldi::kNoTrans, CuMatrixBase< Real >::MulElements(), ClipGradientComponent::num_backpropped_, ClipGradientComponent::num_self_repaired_, CuMatrixBase< Real >::NumRows(), kaldi::RandUniform(), and CuMatrixBase< Real >::Scale().
{
   KALDI_ASSERT(to_update != NULL);
   // we use this 'repair_probability' (hardcoded for now) to limit
   // this code to running on about half of the minibatches.
   BaseFloat repair_probability = 0.5;
   if (self_repair_clipped_proportion_threshold_ >= 1.0 ||
       self_repair_scale_ == 0.0 || count_ == 0 ||
       RandUniform() > repair_probability)
     return;
   KALDI_ASSERT(self_repair_target_ >= 0.0 && self_repair_scale_ > 0.0);
   BaseFloat clipped_proportion =
     (count_ > 0 ? static_cast<BaseFloat>(num_clipped_) / count_ : 0);
   // in-deriv would be modified only when clipped_proportion exceeds the
   // threshold
   if (clipped_proportion <= self_repair_clipped_proportion_threshold_)
     return;
   to_update->num_self_repaired_ += 1;
   if (to_update->debug_info_ == "") // get the component-node name
     to_update->debug_info_ = debug_info;
   if (to_update->num_self_repaired_ == 1)
     KALDI_LOG << "ClipGradientComponent(node_name=" << debug_info
               << ")'s self-repair was activated as the first time at the "
               << to_update->num_backpropped_
               << "-th call of Backprop() in this training job.";
   // sign_mat = sign(in_value), i.e.,
   // An element in sign_mat is 1 if its corresponding element in in_value > 0,
   // or -1 otherwise
   CuMatrix<BaseFloat> sign_mat(in_value);
   sign_mat.ApplyHeaviside();
   sign_mat.Scale(2.0);
   sign_mat.Add(-1.0);
   // repair_mat =
   // floor(abs(in_value) - self_repair_target_, 0) .* sign(in_value)
   CuMatrix<BaseFloat> repair_mat(in_value);
   repair_mat.ApplyPowAbs(1.0);
   repair_mat.Add(-self_repair_target_);
   repair_mat.ApplyFloor(0.0);
   repair_mat.MulElements(sign_mat);
   // magnitude =
   // self_repair_scale_ * clipped_proportion * average norm of in-deriv
   CuVector<BaseFloat> in_deriv_norm_vec(in_deriv->NumRows());
   in_deriv_norm_vec.AddDiagMat2(1.0, *in_deriv, kNoTrans, 0.0);
   in_deriv_norm_vec.ApplyPow(0.5);
   double in_deriv_norm_sum = in_deriv_norm_vec.Sum();
   BaseFloat magnitude = self_repair_scale_ * clipped_proportion *
                         (in_deriv_norm_sum / in_deriv_norm_vec.Dim());
   CuVector<BaseFloat> repair_mat_norm_vec(repair_mat.NumRows());
   repair_mat_norm_vec.AddDiagMat2(1.0, repair_mat, kNoTrans, 0.0);
   repair_mat_norm_vec.ApplyPow(0.5);
   double repair_mat_norm_sum = repair_mat_norm_vec.Sum();
   double scale = 0.0;
   if (repair_mat_norm_sum != 0.0)
     scale = magnitude / (repair_mat_norm_sum / repair_mat_norm_vec.Dim());
   // repair_mat is scaled so that on average the rows have the norm
   // (magnitude / repair_probability). This will give higher magnitude of
   // self-repair to input vectors that have larger absolute value, which tend to
   // be those that are diverging.
   in_deriv->AddMat(-scale / repair_probability, repair_mat);
   CuVector<BaseFloat> in_deriv_repaired_norm_vec(in_deriv->NumRows());
   in_deriv_repaired_norm_vec.AddDiagMat2(1.0, *in_deriv, kNoTrans, 0.0);
   in_deriv_repaired_norm_vec.ApplyPow(0.5);
   // scale in_deriv to have the same norm as that before adding the self-repair
   // term, in order to avoid increase of the norm caused by self-repair,
   // which may incur more clip of gradient and thus more self-repair
   double in_deriv_repaired_norm_sum = in_deriv_repaired_norm_vec.Sum();
   if (in_deriv_repaired_norm_sum != 0.0)
     in_deriv->Scale(in_deriv_norm_sum / in_deriv_repaired_norm_sum);
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 825 of file nnet-simple-component.cc.
{
   count_ *= scale;
   num_clipped_ *= scale;
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 1330 of file nnet-simple-component.h.
 { return "ClipGradientComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 572 of file nnet-simple-component.cc.
References DropoutComponent::dim_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<ClipGradientComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<ClippingThreshold>");
   WriteBasicType(os, binary, clipping_threshold_);
   WriteToken(os, binary, "<NormBasedClipping>");
   WriteBasicType(os, binary, norm_based_clipping_);
   WriteToken(os, binary, "<SelfRepairClippedProportionThreshold>");
   WriteBasicType(os, binary, self_repair_clipped_proportion_threshold_);
   WriteToken(os, binary, "<SelfRepairTarget>");
   WriteBasicType(os, binary, self_repair_target_);
   WriteToken(os, binary, "<SelfRepairScale>");
   WriteBasicType(os, binary, self_repair_scale_);
   WriteToken(os, binary, "<NumElementsClipped>");
   WriteBasicType(os, binary, num_clipped_);
   WriteToken(os, binary, "<NumElementsProcessed>");
   WriteBasicType(os, binary, count_);
   WriteToken(os, binary, "<NumSelfRepaired>");
   WriteBasicType(os, binary, num_self_repaired_);
   WriteToken(os, binary, "<NumBackpropped>");
   WriteBasicType(os, binary, num_backpropped_);
   WriteToken(os, binary, "</ClipGradientComponent>");
 }
ZeroStats()
void ZeroStats () virtual
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Other components that store other types of statistics (e.g. regarding gradient clipping) should implement ZeroStats() also.
Reimplemented from Component.
Definition at line 818 of file nnet-simple-component.cc.
{
   count_ = 0.0;
   num_clipped_ = 0.0;
   num_self_repaired_ = 0;
   num_backpropped_ = 0;
 }
Member Data Documentation
clipping_threshold_
BaseFloat clipping_threshold_ private
Definition at line 1379 of file nnet-simple-component.h.
count_
int32 count_ protected
Definition at line 1421 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Add(), and ClipGradientComponent::Backprop().
debug_info_
std::string debug_info_ private
Definition at line 1395 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::RepairGradients().
dim_
int32 dim_ private
Definition at line 1378 of file nnet-simple-component.h.
norm_based_clipping_
bool norm_based_clipping_ private
Definition at line 1383 of file nnet-simple-component.h.
num_backpropped_
int32 num_backpropped_ protected
Definition at line 1423 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Backprop(), and ClipGradientComponent::RepairGradients().
num_clipped_
int32 num_clipped_ protected
Definition at line 1420 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Add(), and ClipGradientComponent::Backprop().
num_self_repaired_
int32 num_self_repaired_ protected
Definition at line 1422 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::RepairGradients().
self_repair_clipped_proportion_threshold_
BaseFloat self_repair_clipped_proportion_threshold_ private
Definition at line 1388 of file nnet-simple-component.h.
self_repair_scale_
BaseFloat self_repair_scale_ private
Definition at line 1394 of file nnet-simple-component.h.
self_repair_target_
BaseFloat self_repair_target_ private
Definition at line 1392 of file nnet-simple-component.h.
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc