Kaldi: ConstantComponent Class Reference
ConstantComponent Class Reference
#include <nnet-general-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
ConstantComponent ()
ConstantComponent (const ConstantComponent &other)
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
virtual void FreezeNaturalGradient (bool freeze)
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
Component ()
virtual ~Component ()
Private Member Functions
const ConstantComponent & operator= (const ConstantComponent &other)
Private Attributes
CuVector< BaseFloat > output_
bool is_updatable_
bool use_natural_gradient_
OnlineNaturalGradient preconditioner_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Detailed Description
Definition at line 615 of file nnet-general-component.h.
Constructor & Destructor Documentation
ConstantComponent() [1/2]
ConstantComponent ()
Definition at line 1214 of file nnet-general-component.cc.
Referenced by ConstantComponent::Copy().
                                     :
     UpdatableComponent(), is_updatable_(true),
     use_natural_gradient_(true) { }
ConstantComponent() [2/2]
ConstantComponent (const ConstantComponent & other)
Definition at line 1218 of file nnet-general-component.cc.
                                    :
     UpdatableComponent(other), output_(other.output_),
     is_updatable_(other.is_updatable_),
     use_natural_gradient_(other.use_natural_gradient_),
     preconditioner_(other.preconditioner_) { }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1332 of file nnet-general-component.cc.
References ConstantComponent::is_updatable_, KALDI_ASSERT, and ConstantComponent::output_.
{
   if (is_updatable_) {
     const ConstantComponent *other =
         dynamic_cast<const ConstantComponent*>(&other_in);
     KALDI_ASSERT(other != NULL);
     output_.AddVec(alpha, other->output_);
   }
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 1233 of file nnet-general-component.cc.
References UpdatableComponent::is_gradient_, ConstantComponent::is_updatable_, KALDI_ASSERT, UpdatableComponent::learning_rate_, ConstantComponent::output_, OnlineNaturalGradient::PreconditionDirections(), ConstantComponent::preconditioner_, and ConstantComponent::use_natural_gradient_.
{
   // we don't update in_deriv, since we set the flag
   // kBackpropAdds, and the output doesn't depend on the
   // input, so the input-derivative is zero.
   if (to_update_in) {
     ConstantComponent *to_update =
       dynamic_cast<ConstantComponent*>(to_update_in);
     if (to_update->is_updatable_) {
       // only do the update if the is_updatable_ flag is set.
       KALDI_ASSERT(to_update && to_update->is_updatable_);
       if (to_update->use_natural_gradient_ && !to_update->is_gradient_) {
         CuMatrix<BaseFloat> out_deriv_copy(out_deriv);
         BaseFloat scale = 1.0;
         to_update->preconditioner_.PreconditionDirections(&out_deriv_copy,
                                                           &scale);
         to_update->output_.AddRowSumMat(scale * to_update->learning_rate_,
                                         out_deriv_copy);
       } else {
         to_update->output_.AddRowSumMat(to_update->learning_rate_,
                                         out_deriv);
       }
     }
   }
 }
ConsolidateMemory()
void ConsolidateMemory () virtual
This virtual function relates to memory management, and avoiding fragmentation.
It is called only once per model, after we do the first minibatch of training. The default implementation does nothing, but it can be overridden by child classes, where it may re-initialize certain quantities that may possibly have been allocated during the forward pass (e.g. certain statistics; OnlineNaturalGradient objects). We use our own CPU-based allocator (see cu-allocator.h) and since it can't do paging since we're not in control of the GPU page table, fragmentation can be a problem. The allocator always tries to put things in 'low-address memory' (i.e. at smaller memory addresses) near the beginning of the block it allocated, to avoid fragmentation; but if permanent things (belonging to the model) are allocated in the forward pass, they can permanently stay in high memory. This function helps to prevent that, by re-allocating those things into low-address memory (It's important that it's called after all the temporary buffers for the forward-backward have been freed, so that there is low-address memory available)).
Reimplemented from Component.
Definition at line 1388 of file nnet-general-component.cc.
References ConstantComponent::preconditioner_, and OnlineNaturalGradient::Swap().
{
   OnlineNaturalGradient temp(preconditioner_);
   preconditioner_.Swap(&temp);
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 1318 of file nnet-general-component.cc.
References ConstantComponent::ConstantComponent().
{
   return new ConstantComponent(*this);
 }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 1347 of file nnet-general-component.cc.
References ConstantComponent::is_updatable_, KALDI_ASSERT, ConstantComponent::output_, and kaldi::VecVec().
{
   KALDI_ASSERT(is_updatable_);
   const ConstantComponent *other =
       dynamic_cast<const ConstantComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   return VecVec(output_, other->output_);
 }
GetInputIndexes()
virtual void GetInputIndexes (const MiscComputationInfo & misc_info, const Index & output_index, std::vector< Index > * desired_indexes) const inline virtual
This function only does something interesting for non-simple Components.
For a given index at the output of the component, tells us what indexes are required at its input (note: "required" encompasses also optionally-required things; it will enumerate all things that we'd like to have). See also IsComputable().
Parameters
[in] misc_info This argument is supplied to handle things that the framework can't very easily supply: information like which time indexes are needed for AggregateComponent, which time-indexes are available at the input of a recurrent network, and so on. We will add members to misc_info as needed.
[in] output_index The Index at the output of the component, for which we are requesting the list of indexes at the component's input.
[out] desired_indexes A list of indexes that are desired at the input. are to be written to here. By "desired" we mean required or optionally-required.
The default implementation of this function is suitable for any SimpleComponent; it just copies the output_index to a single identical element in input_indexes.
Reimplemented from Component.
Definition at line 657 of file nnet-general-component.h.
{
     desired_indexes->clear();  // requires no inputs.
   }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 1202 of file nnet-general-component.cc.
References UpdatableComponent::Info(), StatisticsPoolingComponent::OutputDim(), kaldi::nnet3::PrintParameterStats(), and StatisticsPoolingComponent::Type().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info()
          << ", " << Type()
          << ", output-dim=" << OutputDim()
          << ", is-updatable=" << std::boolalpha << is_updatable_
          << ", use-natural-gradient=" << std::boolalpha
          << use_natural_gradient_;
   PrintParameterStats(stream, "output", output_, true);
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 1356 of file nnet-general-component.cc.
References VectorBase< Real >::Add(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), UpdatableComponent::InitLearningRatesFromConfig(), ConstantComponent::is_updatable_, KALDI_ERR, ConstantComponent::output_, VectorBase< Real >::Scale(), VectorBase< Real >::SetRandn(), ConstantComponent::use_natural_gradient_, and ConfigLine::WholeLine().
{
   int32 output_dim = 0;
   InitLearningRatesFromConfig(cfl);
   bool ok = cfl->GetValue("output-dim", &output_dim);
   cfl->GetValue("is-updatable", &is_updatable_);
   cfl->GetValue("use-natural-gradient", &use_natural_gradient_);
   BaseFloat output_mean = 0.0, output_stddev = 0.0;
   cfl->GetValue("output-mean", &output_mean);
   cfl->GetValue("output-stddev", &output_stddev);
   if (!ok || cfl->HasUnusedValues() || output_dim <= 0) {
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
   }
   Vector<BaseFloat> output(output_dim);
   output.SetRandn();
   output.Scale(output_stddev);
   output.Add(output_mean);
   output_ = output;
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 619 of file nnet-general-component.h.
 { return output_.Dim(); }
IsComputable()
virtual bool IsComputable (const MiscComputationInfo & misc_info, const Index & output_index, const IndexSet & input_index_set, std::vector< Index > * used_inputs) const inline virtual
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
It tells the user whether a given output index is computable from a given set of input indexes, and if so, says which input indexes will be used in the computation.
Implementations of this function are required to have the property that adding an element to "input_index_set" can only ever change IsComputable from false to true, never vice versa.
Parameters
[in] misc_info Some information specific to the computation, such as minimum and maximum times for certain components to do adaptation on; it's a place to put things that don't easily fit in the framework.
[in] output_index The index that is to be computed at the output of this Component.
[in] input_index_set The set of indexes that is available at the input of this Component.
[out] used_inputs If this is non-NULL and the output is computable this will be set to the list of input indexes that will actually be used in the computation.
Returns
Returns true iff this output is computable from the provided inputs.
The default implementation of this function is suitable for any SimpleComponent: it just returns true if output_index is in input_index_set, and if so sets used_inputs to vector containing that one Index.
Reimplemented from Component.
Definition at line 666 of file nnet-general-component.h.
References Component::Add(), Component::ConsolidateMemory(), kaldi::nnet3::DotProduct(), kaldi::nnet3::NumParameters(), kaldi::nnet3::PerturbParams(), and Component::Scale().
{
     if (used_inputs) used_inputs->clear();
     return true;
   }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 1375 of file nnet-general-component.cc.
References ConstantComponent::is_updatable_, KALDI_ASSERT, and ConstantComponent::output_.
{
   KALDI_ASSERT(is_updatable_);
   return output_.Dim();
 }
operator=()
const ConstantComponent& operator= (const ConstantComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 621 of file nnet-general-component.h.
References Component::Info(), and DistributeComponent::InitFromConfig().
 { return output_.Dim(); }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 1341 of file nnet-general-component.cc.
References kaldi::kUndefined, ConstantComponent::output_, and CuVectorBase< Real >::SetRandn().
{
   CuVector<BaseFloat> temp_output(output_.Dim(), kUndefined);
   temp_output.SetRandn();
   output_.AddVec(stddev, temp_output);
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 1225 of file nnet-general-component.cc.
References CuMatrixBase< Real >::CopyRowsFromVec(), and ConstantComponent::output_.
{
   out->CopyRowsFromVec(output_);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 635 of file nnet-general-component.h.
References DistributeComponent::Backprop(), DistributeComponent::Copy(), kaldi::nnet3::kUpdatableComponent, DistributeComponent::Propagate(), DistributeComponent::Read(), and DistributeComponent::Write().
{
     return
         (is_updatable_ ? kUpdatableComponent : 0);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 1266 of file nnet-general-component.cc.
References kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, ConstantComponent::is_updatable_, KALDI_ERR, UpdatableComponent::learning_rate_, UpdatableComponent::learning_rate_factor_, UpdatableComponent::max_change_, ConstantComponent::output_, kaldi::ReadBasicType(), kaldi::ReadToken(), and ConstantComponent::use_natural_gradient_.
{
   std::string token;
   ReadToken(is, binary, &token);
   if (token == "<ConstantComponent>") {
     ReadToken(is, binary, &token);
   }
   if (token == "<LearningRateFactor>") {
     ReadBasicType(is, binary, &learning_rate_factor_);
     ReadToken(is, binary, &token);
   } else {
     learning_rate_factor_ = 1.0;
   }
   if (token == "<IsGradient>") {
     ReadBasicType(is, binary, &is_gradient_);
     ReadToken(is, binary, &token);
   } else {
     is_gradient_ = false;
   }
   if (token == "<MaxChange>") {
     ReadBasicType(is, binary, &max_change_);
     ReadToken(is, binary, &token);
   } else {
     max_change_ = 0.0;
   }
   if (token == "<LearningRate>") {
     ReadBasicType(is, binary, &learning_rate_);
     ReadToken(is, binary, &token);
   } else {
     learning_rate_ = 0.001;
   }
   if (token != "<Output>") {
     KALDI_ERR << "Expected token <Output>, got " << token;
   }
   output_.Read(is, binary);
   ExpectToken(is, binary, "<IsUpdatable>");
   ReadBasicType(is, binary, &is_updatable_);
   ExpectToken(is, binary, "<UseNaturalGradient>");
   ReadBasicType(is, binary, &use_natural_gradient_);
   ExpectToken(is, binary, "</ConstantComponent>");
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1322 of file nnet-general-component.cc.
References ConstantComponent::is_updatable_, and ConstantComponent::output_.
{
   if (is_updatable_) {
     if (scale == 0.0) {
       output_.SetZero();
     } else {
       output_.Scale(scale);
     }
   }
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 634 of file nnet-general-component.h.
Referenced by DropoutMaskComponent::Info().
 { return "ConstantComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 1384 of file nnet-general-component.cc.
References ConstantComponent::output_.
{
   output_.CopyFromVec(params);
 }
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 1380 of file nnet-general-component.cc.
References VectorBase< Real >::CopyFromVec(), and ConstantComponent::output_.
{
   params->CopyFromVec(output_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 1307 of file nnet-general-component.cc.
References ConstantComponent::is_updatable_, ConstantComponent::output_, ConstantComponent::use_natural_gradient_, kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write the opening tag and learning rate
   WriteToken(os, binary, "<Output>");
   output_.Write(os, binary);
   WriteToken(os, binary, "<IsUpdatable>");
   WriteBasicType(os, binary, is_updatable_);
   WriteToken(os, binary, "<UseNaturalGradient>");
   WriteBasicType(os, binary, use_natural_gradient_);
   WriteToken(os, binary, "</ConstantComponent>");
 }
Member Data Documentation
is_updatable_
bool is_updatable_ private
Definition at line 689 of file nnet-general-component.h.
Referenced by ConstantComponent::Add(), ConstantComponent::Backprop(), ConstantComponent::DotProduct(), ConstantComponent::InitFromConfig(), ConstantComponent::NumParameters(), ConstantComponent::Read(), ConstantComponent::Scale(), and ConstantComponent::Write().
output_
CuVector<BaseFloat> output_ private
Definition at line 687 of file nnet-general-component.h.
Referenced by ConstantComponent::Add(), ConstantComponent::Backprop(), ConstantComponent::DotProduct(), ConstantComponent::InitFromConfig(), ConstantComponent::NumParameters(), ConstantComponent::PerturbParams(), ConstantComponent::Propagate(), ConstantComponent::Read(), ConstantComponent::Scale(), ConstantComponent::UnVectorize(), ConstantComponent::Vectorize(), and ConstantComponent::Write().
preconditioner_
OnlineNaturalGradient preconditioner_ private
Definition at line 692 of file nnet-general-component.h.
Referenced by ConstantComponent::Backprop(), and ConstantComponent::ConsolidateMemory().
use_natural_gradient_
bool use_natural_gradient_ private
Definition at line 691 of file nnet-general-component.h.
Referenced by ConstantComponent::Backprop(), ConstantComponent::InitFromConfig(), ConstantComponent::Read(), and ConstantComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-general-component.h
nnet3/nnet-general-component.cc