Kaldi: TxpPbreak Class Reference
TxpPbreak Class Reference
Holds mapping between punctuation characters and what strength (in terms of break index) and time (seconds).
#include <txppbreak.h>
Public Member Functions
TxpPbreak ()
~TxpPbreak ()
void Init (const TxpParseOptions &opts, const std::string &name)
bool Parse (const std::string &tpdb)
bool GetPbreak (const char *punc, enum TXPPBREAK_POS pos, TxpPbreakInfo &info)
Lookup a punctuation symbol and depending whether before or after token fill info with time and strength if it is stronger or longer than current values.
const TxpPbreakInfo * GetPbreakPre (const char *punc)
Get info for punctuation symbol before token.
const TxpPbreakInfo * GetPbreakPst (const char *punc)
Get info for punctuation symbol after token.
void GetWhitespaceBreaks (const char *ws, int32 col, bool hzone, int32 hzone_start, int32 hzone_end, bool *newline, bool *newline2)
Given whitespace, column number and hzone info set flags for repeated or single linebreak.
int32 get_default_type ()
Return default break strength.
float32 get_default_time ()
Return default break time.
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
virtual void EndElement (const char *name)
Inherited class for bespoke end element handling.
virtual void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
virtual void StartCData ()
Inherited class for bespoke start cdata handling.
virtual void EndCData ()
Inherited class for bespoke start cdata handling.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
Private Attributes
PbreakMap pre_pbreak_
Map of punctuation characters that fire breaks before tokens.
PbreakMap pst_pbreak_
Map of punctuation characters that fire breaks after tokens.
int32 default_type_
Default break strength.
float32 default_time_
Default break time.
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
Holds mapping between punctuation characters and what strength (in terms of break index) and time (seconds).
Also holds whether this is valid when the punctuation is before or after a token
Definition at line 49 of file txppbreak.h.
Constructor & Destructor Documentation
TxpPbreak()
TxpPbreak () inline explicit
Definition at line 51 of file txppbreak.h.
 : default_type_(4), default_time_(0.2f) {}
~TxpPbreak()
~TxpPbreak () inline
Definition at line 52 of file txppbreak.h.
 {}
Member Function Documentation
get_default_time()
float32 get_default_time () inline
Return default break time.
Definition at line 76 of file txppbreak.h.
References TxpPbreak::default_time_, and TxpPbreak::StartElement().
Referenced by TxpPauses::ProcessFile().
 {return default_time_;}
get_default_type()
int32 get_default_type () inline
Return default break strength.
Definition at line 74 of file txppbreak.h.
References TxpPbreak::default_type_.
Referenced by TxpPauses::ProcessFile().
 {return default_type_;}
GetPbreak()
bool GetPbreak (const char * punc, enum TXPPBREAK_POS pos, TxpPbreakInfo & info)
Lookup a punctuation symbol and depending whether before or after token fill info with time and strength if it is stronger or longer than current values.
Definition at line 33 of file txppbreak.cc.
References TxpUtf8::Clen(), TxpPbreak::pre_pbreak_, TxpPbreak::pst_pbreak_, TxpPbreakInfo::time, kaldi::TXPPBREAK_POS_PRE, and TxpPbreakInfo::type.
Referenced by TxpPbreak::Init(), and TxpPauses::ProcessFile().
{
   PbreakMap::iterator lkp;
   const char* p;
   TxpUtf8 utf8;
   int32 clen;
   bool found = false;
   p = punc;
   while (*p) {
     clen = utf8.Clen(p);
     if (pos == TXPPBREAK_POS_PRE) {
       lkp = pre_pbreak_.find(std::string(p, clen));
       if (lkp != pre_pbreak_.end()) found = true;
     } else {
       lkp = pst_pbreak_.find(std::string(p, clen));
       if (lkp != pst_pbreak_.end()) found = true;
     }
     if (found && lkp->second.time > info.time) info.time = lkp->second.time;
     if (found && lkp->second.type > info.type) info.type = lkp->second.type;
     p += clen;
   }
   return found;
 }
GetPbreakPre()
const TxpPbreakInfo * GetPbreakPre (const char * punc)
Get info for punctuation symbol before token.
Definition at line 97 of file txppbreak.cc.
References TxpPbreak::pre_pbreak_.
Referenced by TxpPbreak::Init(), and TxpPauses::ProcessFile().
{
   PbreakMap::iterator lkp;
   lkp = pre_pbreak_.find(std::string(punc));
   if (lkp !=  pre_pbreak_.end()) return &(lkp->second);
   return NULL;
 }
GetPbreakPst()
const TxpPbreakInfo * GetPbreakPst (const char * punc)
Get info for punctuation symbol after token.
Definition at line 90 of file txppbreak.cc.
References TxpPbreak::pst_pbreak_.
Referenced by TxpPbreak::Init(), and TxpPauses::ProcessFile().
{
   PbreakMap::iterator lkp;
   lkp = pst_pbreak_.find(std::string(punc));
   if (lkp !=  pst_pbreak_.end()) return &(lkp->second);
   return NULL;
 }
GetWhitespaceBreaks()
void GetWhitespaceBreaks (const char * ws, int32 col, bool hzone, int32 hzone_start, int32 hzone_end, bool * newline, bool * newline2)
Given whitespace, column number and hzone info set flags for repeated or single linebreak.
Definition at line 58 of file txppbreak.cc.
References TxpUtf8::Clen().
Referenced by TxpPbreak::Init(), and TxpPauses::ProcessFile().
{
   const char* p = ws;
   TxpUtf8 utf8;
   int32 clen;
   int32 nls = 0;
   bool wspstnl = false;
   *newline = false;
   *newline2 = false;
   while (*p) {
     clen = utf8.Clen(p);
     if (!strncmp(p, "\r", clen)) {
       if (!strncmp(p + 1, "\n", 1)) p++;
       nls++;
     } else if (!strncmp(p, "\n", clen)) {
       if (!strncmp(p + 1, "\r", 1)) p++;
       nls++;
     }
     if (nls && !strncmp(p, " ", 1)) wspstnl = true;
     p += clen;
   }
   if (nls > 1) *newline2 = true;
   if (nls == 1) {
     if (!wspstnl && hzone && col > hzone_start && col < hzone_end)
       *newline = false;
     else
       *newline = true;
   }
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & name) inline
Definition at line 53 of file txppbreak.h.
References TxpPbreak::GetPbreak(), TxpPbreak::GetPbreakPre(), TxpPbreak::GetPbreakPst(), TxpPbreak::GetWhitespaceBreaks(), TxpXmlData::Init(), and TxpPbreak::Parse().
Referenced by TxpPauses::Init().
{
     TxpXmlData::Init(opts, "pbreak", name);
   }
Parse()
bool Parse (const std::string & tpdb)
Definition at line 25 of file txppbreak.cc.
References KALDI_WARN, and TxpXmlData::Parse().
Referenced by TxpPauses::Init(), and TxpPbreak::Init().
{
   bool r;
   r = TxpXmlData::Parse(tpdb);
   if (!r)
     KALDI_WARN << "Error reading phrase break file: " << tpdb;
   return r;
 }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 104 of file txppbreak.cc.
References TxpPbreak::pre_pbreak_, TxpPbreak::pst_pbreak_, TxpXmlData::SetAttribute(), TxpPbreakInfo::time, and TxpPbreakInfo::type.
Referenced by TxpPbreak::get_default_time().
{
   std::string punc;
   std::string pos;
   std::string time;
   std::string type;
   TxpPbreakInfo pbreak;
   if (!strcmp(name, "break")) {
     SetAttribute("name", atts, &punc);
     SetAttribute("pos", atts, &pos);
     SetAttribute("time", atts, &time);
     SetAttribute("type", atts, &type);
     pbreak.time = atof(time.c_str());
     pbreak.type = atoi(type.c_str());
     if (pos == "pstpunc") {
       pst_pbreak_.insert(PbreakItem(punc, pbreak));
     } else {
       pre_pbreak_.insert(PbreakItem(punc, pbreak));
     }
   }
 }
Member Data Documentation
default_time_
float32 default_time_ private
Default break time.
Definition at line 88 of file txppbreak.h.
Referenced by TxpPbreak::get_default_time().
default_type_
int32 default_type_ private
Default break strength.
Definition at line 86 of file txppbreak.h.
Referenced by TxpPbreak::get_default_type().
pre_pbreak_
PbreakMap pre_pbreak_ private
Map of punctuation characters that fire breaks before tokens.
Definition at line 82 of file txppbreak.h.
Referenced by TxpPbreak::GetPbreak(), TxpPbreak::GetPbreakPre(), and TxpPbreak::StartElement().
pst_pbreak_
PbreakMap pst_pbreak_ private
Map of punctuation characters that fire breaks after tokens.
Definition at line 84 of file txppbreak.h.
Referenced by TxpPbreak::GetPbreak(), TxpPbreak::GetPbreakPst(), and TxpPbreak::StartElement().
The documentation for this class was generated from the following files:
idlaktxp/txppbreak.h
idlaktxp/txppbreak.cc