Kaldi: WordAlignedLatticeTester Class Reference
WordAlignedLatticeTester Class Reference
Public Member Functions
WordAlignedLatticeTester (const CompactLattice &lat, const TransitionModel &tmodel, const WordBoundaryInfo &info, const CompactLattice &aligned_lat)
void Test ()
Private Member Functions
void TestArc (const CompactLatticeArc &arc)
bool TestArcEmpty (const CompactLatticeArc &arc)
bool TestArcSilence (const CompactLatticeArc &arc)
bool TestArcOnePhoneWord (const CompactLatticeArc &arc)
bool TestArcNormalWord (const CompactLatticeArc &arc)
bool TestArcPartialWord (const CompactLatticeArc &arc)
void TestFinal (const CompactLatticeWeight &w)
void TestEquivalent ()
Private Attributes
const CompactLattice & lat_
const TransitionModel & tmodel_
const WordBoundaryInfo & info_
const CompactLattice & aligned_lat_
Detailed Description
Definition at line 734 of file word-align-lattice.cc.
Constructor & Destructor Documentation
WordAlignedLatticeTester()
WordAlignedLatticeTester (const CompactLattice & lat, const TransitionModel & tmodel, const WordBoundaryInfo & info, const CompactLattice & aligned_lat) inline
Definition at line 736 of file word-align-lattice.cc.
                                                              :
       lat_(lat), tmodel_(tmodel), info_(info), aligned_lat_(aligned_lat) { }
Member Function Documentation
Test()
void Test () inline
Definition at line 742 of file word-align-lattice.cc.
References CompactLatticeWeightTpl< WeightType, IntType >::Zero().
Referenced by kaldi::TestWordAlignedLattice().
               {
     // First test that each aligned arc is valid.
     typedef CompactLattice::StateId StateId ;
     for (StateId s = 0; s < aligned_lat_.NumStates(); s++) {
       for (fst::ArcIterator<CompactLattice> iter(aligned_lat_, s);
            !iter.Done();
            iter.Next()) {
         TestArc(iter.Value());
       }
       if (aligned_lat_.Final(s) != CompactLatticeWeight::Zero()) {
         TestFinal(aligned_lat_.Final(s));
       }
     }
     TestEquivalent();
   }
TestArc()
void TestArc (const CompactLatticeArc & arc) inline private
Definition at line 758 of file word-align-lattice.cc.
References KALDI_ERR.
{
     if (! (TestArcSilence(arc) || TestArcNormalWord(arc) || TestArcOnePhoneWord(arc)
            || TestArcEmpty(arc)))
       KALDI_ERR << "Invalid arc in aligned CompactLattice: "
                 << arc.ilabel << " " << arc.olabel << " " << arc.nextstate
                 << " " << arc.weight;
   }
TestArcEmpty()
bool TestArcEmpty (const CompactLatticeArc & arc) inline private
Definition at line 765 of file word-align-lattice.cc.
{
     if (arc.ilabel != 0) return false; // Check there is no label.  Note, ilabel==olabel.
     const std::vector<int32> &tids = arc.weight.String();
     return tids.empty();
   }
TestArcNormalWord()
bool TestArcNormalWord (const CompactLatticeArc & arc) inline private
Definition at line 828 of file word-align-lattice.cc.
References rnnlm::i, LatticeWordAligner::info_, TransitionModel::IsFinal(), TransitionModel::IsSelfLoop(), rnnlm::j, WordBoundaryInfo::kWordBeginPhone, WordBoundaryInfo::kWordEndPhone, WordBoundaryInfo::kWordInternalPhone, WordBoundaryInfo::reorder, LatticeWordAligner::tmodel_, TransitionModel::TransitionIdToPhone(), TransitionModel::TransitionIdToTransitionState(), and WordBoundaryInfo::TypeOfPhone().
{
     if (arc.ilabel == 0) return false; // Check there's a label.  Note, ilabel==olabel.
     const std::vector<int32> &tids = arc.weight.String();
     if (tids.empty()) return false;
     int32 first_phone = tmodel_.TransitionIdToPhone(tids.front());
     if (info_.TypeOfPhone(first_phone) != WordBoundaryInfo::kWordBeginPhone)
       return false;
     size_t i;
     { // first phone.
       int num_final = 0;
       for (i = 0; i < tids.size(); i++) {
         if (tmodel_.TransitionIdToPhone(tids[i]) != first_phone) break;
         if (tmodel_.IsFinal(tids[i])) num_final++;
       }
       if (num_final != 1)
         return false; // Something went wrong-- perhaps we
       // got two beginning phones in a row.
     }
     { // middle phones.  Skip over them.
       while (i < tids.size() &&
              info_.TypeOfPhone(tmodel_.TransitionIdToPhone(tids[i]))
              == WordBoundaryInfo::kWordInternalPhone)
         i++;
     }
     if (i == tids.size()) return false;
     int32 final_phone = tmodel_.TransitionIdToPhone(tids[i]);
     if (info_.TypeOfPhone(final_phone) != WordBoundaryInfo::kWordEndPhone)
       return false; // not word-ending.
     for (size_t j = i; j < tids.size(); j++) // make sure only this final phone till end.
       if (tmodel_.TransitionIdToPhone(tids[j]) != final_phone)
         return false; // Other phones after final phone.
     for (size_t j = i; j < tids.size(); j++) {
       if (tmodel_.IsFinal(tids[j])) { // Found "final transition"..   Note:
         // may be "reordered" with its self loops.
         if (!info_.reorder) return (j+1 == tids.size());
         else {
           // Make sure the only thing that follows this is self-loops
           // of the final transition-state.
           for (size_t k = j + 1; k < tids.size(); k++)
             if (tmodel_.TransitionIdToTransitionState(tids[k])
                 != tmodel_.TransitionIdToTransitionState(tids[j])
                 || !tmodel_.IsSelfLoop(tids[k]))
               return false;
           return true;
         }
       }
     }
     return false; // Found no final state.
   }
TestArcOnePhoneWord()
bool TestArcOnePhoneWord (const CompactLatticeArc & arc) inline private
Definition at line 800 of file word-align-lattice.cc.
References rnnlm::i, LatticeWordAligner::info_, TransitionModel::IsFinal(), rnnlm::j, WordBoundaryInfo::kWordBeginAndEndPhone, WordBoundaryInfo::reorder, LatticeWordAligner::tmodel_, TransitionModel::TransitionIdToPhone(), TransitionModel::TransitionIdToTransitionState(), and WordBoundaryInfo::TypeOfPhone().
{
     if (arc.ilabel == 0) return false; // Check there's a label.  Note, ilabel==olabel.
     const std::vector<int32> &tids = arc.weight.String();
     if (tids.empty()) return false;
     int32 first_phone = tmodel_.TransitionIdToPhone(tids.front());
     if (info_.TypeOfPhone(first_phone) !=
         WordBoundaryInfo::kWordBeginAndEndPhone) return false;
     for (size_t i = 0; i < tids.size(); i++)
       if (tmodel_.TransitionIdToPhone(tids[i]) != first_phone) return false;
     if (!info_.reorder) return tmodel_.IsFinal(tids.back());
     else {
       for (size_t i = 0; i < tids.size(); i++) {
         if (tmodel_.IsFinal(tids[i])) { // got the "final" transition, which is
           // reordered to actually not be final.  Make sure that all the
           // rest of the transition ids are the self-loop of that same
           // transition-state.
           for (size_t j = i+1; j < tids.size(); j++) {
             if (tmodel_.TransitionIdToTransitionState(tids[j])
                 != tmodel_.TransitionIdToTransitionState(tids[i])) return false;
           }
           return true;
         }
       }
       return false; // fell off loop.  No final-state present.
     }
   }
TestArcPartialWord()
bool TestArcPartialWord (const CompactLatticeArc & arc) inline private
Definition at line 879 of file word-align-lattice.cc.
References LatticeWordAligner::info_, and WordBoundaryInfo::partial_word_label.
{
     if (arc.ilabel != info_.partial_word_label) return false; // label should
     // be the partial-word label.
     const std::vector<int32> &tids = arc.weight.String();
     if (tids.empty()) return false;
     return true; // We're pretty liberal when it comes to partial words here.
   }
TestArcSilence()
bool TestArcSilence (const CompactLatticeArc & arc) inline private
Definition at line 770 of file word-align-lattice.cc.
References rnnlm::i, LatticeWordAligner::info_, TransitionModel::IsFinal(), rnnlm::j, WordBoundaryInfo::kNonWordPhone, WordBoundaryInfo::reorder, WordBoundaryInfo::silence_label, LatticeWordAligner::tmodel_, TransitionModel::TransitionIdToPhone(), TransitionModel::TransitionIdToTransitionState(), and WordBoundaryInfo::TypeOfPhone().
{
     // This only applies when silence doesn't have word labels.
     if (arc.ilabel !=  info_.silence_label) return false; // Check the label is
     // the silence label. Note, ilabel==olabel.
     const std::vector<int32> &tids = arc.weight.String();
     if (tids.empty()) return false;
     int32 first_phone = tmodel_.TransitionIdToPhone(tids.front());
     if (info_.TypeOfPhone(first_phone) != WordBoundaryInfo::kNonWordPhone)
       return false;
     for (size_t i = 0; i < tids.size(); i++)
       if (tmodel_.TransitionIdToPhone(tids[i]) != first_phone) return false;
     if (!info_.reorder) return tmodel_.IsFinal(tids.back());
     else {
       for (size_t i = 0; i < tids.size(); i++) {
         if (tmodel_.IsFinal(tids[i])) { // got the "final" transition, which is
           // reordered to actually not be final.  Make sure that all the
           // rest of the transition ids are the self-loop of that same
           // transition-state.
           for (size_t j = i+1; j < tids.size(); j++) {
             if (!(tmodel_.TransitionIdToTransitionState(tids[j])
                   == tmodel_.TransitionIdToTransitionState(tids[i]))) return false;
           }
           return true;
         }
       }
       return false; // fell off loop.  No final-state present.
     }
   }
TestEquivalent()
void TestEquivalent () inline private
Definition at line 891 of file word-align-lattice.cc.
References LatticeWordAligner::info_, KALDI_ERR, LatticeWordAligner::lat_, kaldi::Rand(), fst::RemoveSomeInputSymbols(), and WordBoundaryInfo::silence_label.
{
     CompactLattice aligned_lat(aligned_lat_);
     if (info_.silence_label != 0) { // remove silence labels.
       std::vector<int32> to_remove;
       to_remove.push_back(info_.silence_label);
       RemoveSomeInputSymbols(to_remove, &aligned_lat);
       Project(&aligned_lat, fst::PROJECT_INPUT);
     }
     if (!RandEquivalent(lat_, aligned_lat, 5/*paths*/, 1.0e+10/*delta*/, Rand()/*seed*/,
                         200/*path length (max?)*/))
       KALDI_ERR << "Equivalence test failed (testing word-alignment of lattices.) "
                 << "Make sure your model and lattices match!";
   }
TestFinal()
void TestFinal (const CompactLatticeWeight & w) inline private
Definition at line 887 of file word-align-lattice.cc.
References KALDI_ERR, and CompactLatticeWeightTpl< WeightType, IntType >::String().
{
     if (!w.String().empty())
       KALDI_ERR << "Expect to have no strings on final-weights of lattices.";
   }
Member Data Documentation
aligned_lat_
const CompactLattice& aligned_lat_ private
Definition at line 909 of file word-align-lattice.cc.
info_
const WordBoundaryInfo& info_ private
Definition at line 908 of file word-align-lattice.cc.
lat_
const CompactLattice& lat_ private
Definition at line 906 of file word-align-lattice.cc.
tmodel_
const TransitionModel& tmodel_ private
Definition at line 907 of file word-align-lattice.cc.
The documentation for this class was generated from the following file:
lat/word-align-lattice.cc