Kaldi: PldaStats Class Reference
PldaStats Class Reference
#include <plda.h>
Classes
struct ClassInfo
Public Member Functions
PldaStats ()
void AddSamples (double weight, const Matrix< double > &group)
The dimension is set up the first time you add samples.
int32 Dim () const
void Init (int32 dim)
void Sort ()
bool IsSorted () const
~PldaStats ()
Protected Attributes
int32 dim_
int64 num_classes_
int64 num_examples_
double class_weight_
double example_weight_
Vector< double > sum_
SpMatrix< double > offset_scatter_
std::vector< ClassInfo > class_info_
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (PldaStats)
Friends
class PldaEstimator
Detailed Description
Definition at line 172 of file plda.h.
Constructor & Destructor Documentation
PldaStats()
PldaStats () inline
Definition at line 174 of file plda.h.
 : dim_(0) { }
~PldaStats()
~PldaStats ()
Definition at line 313 of file plda.cc.
References rnnlm::i.
                       {
   for (size_t i = 0; i < class_info_.size(); i++)
     delete class_info_[i].mean;
 }
Member Function Documentation
AddSamples()
void AddSamples (double weight, const Matrix< double > & group)
The dimension is set up the first time you add samples.
This function adds training samples corresponding to one class (e.g. a speaker). Each row is a separate sample from this group. The "weight" would normally be 1.0, but you can set it to other values if you want to weight your training samples.
Definition at line 286 of file plda.cc.
References VectorBase< Real >::AddRowSumMat(), KALDI_ASSERT, kaldi::kTrans, rnnlm::n, MatrixBase< Real >::NumCols(), and MatrixBase< Real >::NumRows().
Referenced by main(), and kaldi::UnitTestPldaEstimation().
{
   if (dim_ == 0) {
     Init(group.NumCols());
   } else {
     KALDI_ASSERT(dim_ == group.NumCols());
   }
   int32 n = group.NumRows(); // number of examples for this class
   Vector<double> *mean = new Vector<double>(dim_);
   mean->AddRowSumMat(1.0 / n, group);
   offset_scatter_.AddMat2(weight, group, kTrans, 1.0);
   // the following statement has the same effect as if we
   // had first subtracted the mean from each element of
   // the group before the statement above.
   offset_scatter_.AddVec2(-n * weight, *mean);
   class_info_.push_back(ClassInfo(weight, mean, n));
   num_classes_ ++;
   num_examples_ += n;
   class_weight_ += weight;
   example_weight_ += weight * n;
   sum_.AddVec(weight, *mean);
 }
Dim()
int32 Dim () const inline
Definition at line 184 of file plda.h.
Referenced by main().
 { return dim_; }
Init()
void Init (int32 dim)
Definition at line 325 of file plda.cc.
References KALDI_ASSERT.
{
   KALDI_ASSERT(dim_ == 0);
   dim_ = dim;
   num_classes_ = 0;
   num_examples_ = 0;
   class_weight_ = 0.0;
   example_weight_ = 0.0;
   sum_.Resize(dim);
   offset_scatter_.Resize(dim);
   KALDI_ASSERT(class_info_.empty());
 }
IsSorted()
bool IsSorted () const
Definition at line 318 of file plda.cc.
References rnnlm::i.
Referenced by PldaEstimator::PldaEstimator().
{
   for (size_t i = 0; i + 1 < class_info_.size(); i++)
     if (class_info_[i+1] < class_info_[i])
       return false;
   return true;
 }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (PldaStats) private
Sort()
void Sort () inline
Definition at line 188 of file plda.h.
References kaldi::IsSorted().
Referenced by main(), and kaldi::UnitTestPldaEstimation().
 { std::sort(class_info_.begin(), class_info_.end()); }
Friends And Related Function Documentation
PldaEstimator
friend class PldaEstimator friend
Definition at line 193 of file plda.h.
Member Data Documentation
class_info_
std::vector<ClassInfo> class_info_ protected
Definition at line 220 of file plda.h.
Referenced by PldaEstimator::ComputeObjfPart2(), and PldaEstimator::GetStatsFromClassMeans().
class_weight_
double class_weight_ protected
Definition at line 198 of file plda.h.
Referenced by PldaEstimator::ComputeObjfPart1(), PldaEstimator::ComputeObjfPart2(), PldaEstimator::GetOutput(), PldaEstimator::GetStatsFromClassMeans(), and PldaEstimator::GetStatsFromIntraClass().
dim_
int32 dim_ protected
Definition at line 195 of file plda.h.
example_weight_
double example_weight_ protected
Definition at line 199 of file plda.h.
Referenced by PldaEstimator::ComputeObjf(), PldaEstimator::ComputeObjfPart1(), PldaEstimator::Estimate(), and PldaEstimator::GetStatsFromIntraClass().
num_classes_
int64 num_classes_ protected
Definition at line 196 of file plda.h.
num_examples_
int64 num_examples_ protected
Definition at line 197 of file plda.h.
offset_scatter_
SpMatrix<double> offset_scatter_ protected
Definition at line 204 of file plda.h.
Referenced by PldaEstimator::ComputeObjfPart1(), and PldaEstimator::GetStatsFromIntraClass().
sum_
Vector<double> sum_ protected
Definition at line 201 of file plda.h.
Referenced by PldaEstimator::ComputeObjfPart2(), PldaEstimator::GetOutput(), and PldaEstimator::GetStatsFromClassMeans().
The documentation for this class was generated from the following files:
ivector/plda.h
ivector/plda.cc