Kaldi: TxpAbbrev Class Reference
TxpAbbrev Class Reference
Holds mapping between punctuation characters and what strength (in terms of break index) and time (seconds).
#include <txpabbrev.h>
Public Member Functions
TxpAbbrev ()
~TxpAbbrev ()
void Init (const TxpParseOptions &opts, const std::string &name)
bool Parse (const std::string &tpdb)
TxpAbbrevInfo * LookupAbbrev (const char *tk, const char *prepunc, const char *pstpunc)
TxpAbbrevInfo * LookupAbbrev (const char *tk)
int32 CheckPrePunc (const char *prepunc, TxpAbbrevInfo *abb)
int32 CheckPstPunc (const char *pstpunc, TxpAbbrevInfo *abb)
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
virtual void StartCData ()
Inherited class for bespoke start cdata handling.
virtual void EndCData ()
Inherited class for bespoke start cdata handling.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
void EndElement (const char *)
Inherited class for bespoke end element handling.
void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
Private Attributes
AbbrevVector abbreviations_
vector of abbreviations to expand before normalisation
TxpAbbrevInfo * current_abbrev_
Parser status currently operating on this abbreviation.
std::string current_lexentry_
Parser status in this lex tag.
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
Holds mapping between punctuation characters and what strength (in terms of break index) and time (seconds).
Also holds whether this is valid when the punctuation is before or after a token
Definition at line 42 of file txpabbrev.h.
Constructor & Destructor Documentation
TxpAbbrev()
TxpAbbrev () inline explicit
Definition at line 44 of file txpabbrev.h.
References TxpAbbrev::~TxpAbbrev().
 {}
~TxpAbbrev()
~TxpAbbrev ()
Definition at line 25 of file txpabbrev.cc.
References TxpAbbrev::abbreviations_, and rnnlm::i.
Referenced by TxpAbbrev::TxpAbbrev().
                       {
   int32 i;
   for (i = 0; i < abbreviations_.size(); i++) {
     delete(abbreviations_[i]);
   }
 }
Member Function Documentation
CharHandler()
void CharHandler (const char * data, int32 len) private virtual
Inherited class for bespoke character handling.
Reimplemented from TxpXmlData.
Definition at line 114 of file txpabbrev.cc.
References TxpAbbrevInfo::AddExpansionToken(), TxpAbbrev::current_abbrev_, TxpAbbrev::current_lexentry_, and rnnlm::i.
Referenced by TxpAbbrev::Init().
{
   const char * p = NULL, * word = NULL;
   int32 i = 0, wordlen = 0;
   p = data;
   if (!p) return;
   for (i = 0; i < len; p++, i++) {
     if (!*p) break;
     if (*p == ' ' || *p == '\n') {
       if (word) {
         current_abbrev_->AddExpansionToken(word, wordlen,
                                            current_lexentry_.c_str());
         word = NULL;
         wordlen = 0;
       }
     } else {
       if (!word) word = p;
       wordlen++;
     }
   }
   if (word) current_abbrev_->AddExpansionToken(word, wordlen,
                                                current_lexentry_.c_str());
 }
CheckPrePunc()
int32 CheckPrePunc (const char * prepunc, TxpAbbrevInfo * abb)
Definition at line 58 of file txpabbrev.cc.
References NO_INDEX, and TxpAbbrevInfo::prepunc.
Referenced by TxpAbbrev::Init(), TxpAbbrev::LookupAbbrev(), and TxpTokenise::SetPuncCaseInfo().
{
   // no prepunc specified
   if (abb->prepunc.empty()) return 0;
   // prepunc matches
   if (!strcmp(prepunc + strlen(prepunc) - abb->prepunc.size(),
               abb->prepunc.c_str()))
     return abb->prepunc.size();
   // prepunc does not match
   return NO_INDEX;
 }
CheckPstPunc()
int32 CheckPstPunc (const char * pstpunc, TxpAbbrevInfo * abb)
Definition at line 69 of file txpabbrev.cc.
References NO_INDEX, and TxpAbbrevInfo::pstpunc.
Referenced by TxpAbbrev::Init(), TxpAbbrev::LookupAbbrev(), and TxpTokenise::SetPuncCaseInfo().
{
   // no pstpunc specified
   if (abb->pstpunc.empty()) return 0;
   // pstpunc matches
   if (!strncmp(pstpunc, abb->pstpunc.c_str(), abb->pstpunc.size()))
     return abb->pstpunc.size();
   // prepunc does not match
   return NO_INDEX;
 }
EndElement()
void EndElement (const char * name) private virtual
Inherited class for bespoke end element handling.
Reimplemented from TxpXmlData.
Definition at line 106 of file txpabbrev.cc.
References TxpAbbrev::abbreviations_, TxpAbbrev::current_abbrev_, and TxpAbbrev::current_lexentry_.
Referenced by TxpAbbrev::Init().
{
   if (!strcmp(name, "lex")) {
     current_lexentry_ = "";
   } else if (!strcmp(name, "abb")) {
     abbreviations_.push_back(current_abbrev_);
   }
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & name) inline
Definition at line 46 of file txpabbrev.h.
References TxpAbbrev::CharHandler(), TxpAbbrev::CheckPrePunc(), TxpAbbrev::CheckPstPunc(), TxpAbbrev::EndElement(), TxpXmlData::Init(), TxpAbbrev::LookupAbbrev(), TxpAbbrev::Parse(), and TxpAbbrev::StartElement().
Referenced by TxpTokenise::Init().
{
     TxpXmlData::Init(opts, "abbrev", name);
   }
LookupAbbrev() [1/2]
TxpAbbrevInfo * LookupAbbrev (const char * tk, const char * prepunc, const char * pstpunc)
Definition at line 31 of file txpabbrev.cc.
References TxpAbbrev::abbreviations_, TxpAbbrev::CheckPrePunc(), TxpAbbrev::CheckPstPunc(), and NO_INDEX.
Referenced by TxpAbbrev::Init(), TxpTokenise::Process(), and TxpTokenise::SetPuncCaseInfo().
{
   for (AbbrevVector::const_iterator it = abbreviations_.begin();
        it != abbreviations_.end();
        ++it) {
     if (!strcmp(tk, (*it)->token.c_str())) {
       if (CheckPrePunc(prepunc, (*it)) != NO_INDEX &&
           (CheckPstPunc(pstpunc, (*it)) != NO_INDEX))
         return (*it);
     }
   }
   return NULL;
 }
LookupAbbrev() [2/2]
TxpAbbrevInfo * LookupAbbrev (const char * tk)
Definition at line 46 of file txpabbrev.cc.
References TxpAbbrev::abbreviations_.
{
   for (AbbrevVector::const_iterator it = abbreviations_.begin();
        it != abbreviations_.end();
        ++it) {
     if (!strcmp(tk, (*it)->token.c_str())) {
       if ((*it)->prepunc.empty() && (*it)->pstpunc.empty())
         return (*it);
     }
   }
   return NULL;
 }
Parse()
bool Parse (const std::string & tpdb)
Definition at line 86 of file txpabbrev.cc.
References KALDI_WARN, and TxpXmlData::Parse().
Referenced by TxpTokenise::Init(), and TxpAbbrev::Init().
{
   bool r;
   r = TxpXmlData::Parse(tpdb);
   if (!r)
     KALDI_WARN << "Error reading abbreviation file: " << tpdb;
   return r;
 }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 94 of file txpabbrev.cc.
References TxpAbbrev::current_abbrev_, TxpAbbrev::current_lexentry_, TxpAbbrevInfo::prepunc, TxpAbbrevInfo::pstpunc, TxpXmlData::SetAttribute(), and TxpAbbrevInfo::token.
Referenced by TxpAbbrev::Init().
{
   if (!strcmp(name, "lex")) {
     SetAttribute("entry", atts, &current_lexentry_);
   } else if (!strcmp(name, "abb")) {
     // create abbinfo
     current_abbrev_ = new TxpAbbrevInfo();
     SetAttribute("pstpunc", atts, &(current_abbrev_->pstpunc));
     SetAttribute("token", atts, &(current_abbrev_->token));
     SetAttribute("prepunc", atts, &(current_abbrev_->prepunc));
   }
 }
Member Data Documentation
abbreviations_
AbbrevVector abbreviations_ private
vector of abbreviations to expand before normalisation
Definition at line 61 of file txpabbrev.h.
Referenced by TxpAbbrev::EndElement(), TxpAbbrev::LookupAbbrev(), and TxpAbbrev::~TxpAbbrev().
current_abbrev_
TxpAbbrevInfo* current_abbrev_ private
Parser status currently operating on this abbreviation.
Definition at line 63 of file txpabbrev.h.
Referenced by TxpAbbrev::CharHandler(), TxpAbbrev::EndElement(), and TxpAbbrev::StartElement().
current_lexentry_
std::string current_lexentry_ private
Parser status in this lex tag.
Definition at line 65 of file txpabbrev.h.
Referenced by TxpAbbrev::CharHandler(), TxpAbbrev::EndElement(), and TxpAbbrev::StartElement().
The documentation for this class was generated from the following files:
idlaktxp/txpabbrev.h
idlaktxp/txpabbrev.cc