Kaldi: ScaleAndOffsetComponent Class Reference
ScaleAndOffsetComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
ScaleAndOffsetComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
ScaleAndOffsetComponent (const ScaleAndOffsetComponent &other)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
virtual void FreezeNaturalGradient (bool freeze)
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
Component ()
virtual ~Component ()
Private Member Functions
void PropagateInternal (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
void BackpropInternal (const std::string &debug_info, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, ScaleAndOffsetComponent *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
BaseFloat Epsilon () const
void Update (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
const ScaleAndOffsetComponent & operator= (const ScaleAndOffsetComponent &other)
Private Attributes
int32 dim_
CuVector< BaseFloat > scales_
CuVector< BaseFloat > offsets_
bool use_natural_gradient_
OnlineNaturalGradient scale_preconditioner_
OnlineNaturalGradient offset_preconditioner_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Detailed Description
Definition at line 1854 of file nnet-simple-component.h.
Constructor & Destructor Documentation
ScaleAndOffsetComponent() [1/2]
ScaleAndOffsetComponent () inline
Definition at line 1862 of file nnet-simple-component.h.
 { } // use Init to really initialize.
ScaleAndOffsetComponent() [2/2]
ScaleAndOffsetComponent (const ScaleAndOffsetComponent & other) explicit
Definition at line 2402 of file nnet-simple-component.cc.
                                              :
     UpdatableComponent(component),
     dim_(component.dim_),
     scales_(component.scales_),
     offsets_(component.offsets_),
     use_natural_gradient_(component.use_natural_gradient_),
     scale_preconditioner_(component.scale_preconditioner_),
     offset_preconditioner_(component.offset_preconditioner_) { }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 2393 of file nnet-simple-component.cc.
References KALDI_ASSERT, PerElementOffsetComponent::offsets_, ScaleAndOffsetComponent::offsets_, and ScaleAndOffsetComponent::scales_.
{
   const ScaleAndOffsetComponent *other =
       dynamic_cast<const ScaleAndOffsetComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   scales_.AddVec(alpha, other->scales_);
   offsets_.AddVec(alpha, other->offsets_);
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 2474 of file nnet-simple-component.cc.
References ScaleAndOffsetComponent::BackpropInternal(), CuMatrixBase< Real >::Data(), ScaleAndOffsetComponent::dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), kaldi::SameDim(), kaldi::SameDimAndStride(), ScaleAndOffsetComponent::scales_, and CuMatrixBase< Real >::Stride().
{
   ScaleAndOffsetComponent *to_update =
       dynamic_cast<ScaleAndOffsetComponent*>(to_update_in);
   KALDI_ASSERT(SameDim(out_value, out_deriv));
   if (dim_ == scales_.Dim()) {
     BackpropInternal(debug_info, out_value, out_deriv,
                      to_update, in_deriv);
   } else {
     KALDI_ASSERT(out_value.NumCols() == out_value.Stride() &&
                  SameDimAndStride(out_value, out_deriv) &&
                  (!in_deriv || SameDimAndStride(out_value, *in_deriv)));
     int32 multiple = dim_ / scales_.Dim(),
         num_rows = out_value.NumRows(),
         block_dim = scales_.Dim();
     CuSubMatrix<BaseFloat> out_value_rearranged(out_value.Data(),
                                                 num_rows * multiple,
                                                 block_dim, block_dim),
         out_deriv_rearranged(out_deriv.Data(), num_rows * multiple,
                              block_dim, block_dim);
     if (in_deriv) {
       CuSubMatrix<BaseFloat> in_deriv_rearranged(in_deriv->Data(),
                                                  num_rows * multiple,
                                                  block_dim, block_dim);
       BackpropInternal(debug_info, out_value_rearranged,
                        out_deriv_rearranged, to_update,
                        &in_deriv_rearranged);
     } else {
       BackpropInternal(debug_info, out_value_rearranged,
                        out_deriv_rearranged, to_update,
                        NULL);
     }
   }
 }
BackpropInternal()
void BackpropInternal (const std::string & debug_info, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, ScaleAndOffsetComponent * to_update, CuMatrixBase< BaseFloat > * in_deriv) const private
Definition at line 2521 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddVecToRows(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::Data(), kaldi::cu::EnsureNonzero(), ScaleAndOffsetComponent::Epsilon(), CuVectorBase< Real >::InvertElements(), UpdatableComponent::is_gradient_, kaldi::kUndefined, UpdatableComponent::learning_rate_, CuMatrixBase< Real >::MulColsVec(), CuMatrixBase< Real >::MulElements(), ScaleAndOffsetComponent::offset_preconditioner_, ScaleAndOffsetComponent::offsets_, OnlineNaturalGradient::PreconditionDirections(), ScaleAndOffsetComponent::scale_preconditioner_, ScaleAndOffsetComponent::scales_, and ScaleAndOffsetComponent::use_natural_gradient_.
Referenced by ScaleAndOffsetComponent::Backprop().
{
   if (to_update) {
     if (!to_update->use_natural_gradient_ || to_update->is_gradient_) {
       to_update->offsets_.AddRowSumMat(to_update->learning_rate_,
                                        out_deriv);
     } else {
       BaseFloat scale = 1.0;
       CuMatrix<BaseFloat> out_deriv_copy(out_deriv);
       to_update->offset_preconditioner_.PreconditionDirections(
           &out_deriv_copy, &scale);
       to_update->offsets_.AddRowSumMat(scale * to_update->learning_rate_,
                                        out_deriv_copy);
     }
     // The backprop actually needs the input to the component, not the output;
     // but we make the output available because in the common topologies that
     // will already be required for backprop-- it's for memory efficiency.
     CuMatrix<BaseFloat> in_value_reconstructed(out_value);
     int32 dim = scales_.Dim();
     CuVector<BaseFloat> scales_nonzero(dim, kUndefined);
     BaseFloat epsilon = Epsilon();
     cu::EnsureNonzero(scales_, epsilon, &scales_nonzero);
     scales_nonzero.InvertElements();
     in_value_reconstructed.AddVecToRows(-1.0, offsets_);
     // Actually scales_nonzero are now the inverses of the scales.
     in_value_reconstructed.MulColsVec(scales_nonzero);
     // OK, at this point in_value_reconstructed is the input to the component.
     // Multiply its elements by 'out_deriv' to get the derivatives
     // (for each frame) w.r.t. the scales.
     in_value_reconstructed.MulElements(out_deriv);
     BaseFloat scale = 1.0;
     if (to_update->use_natural_gradient_ && !to_update->is_gradient_) {
       to_update->scale_preconditioner_.PreconditionDirections(
           &in_value_reconstructed, &scale);
     }
     to_update->scales_.AddRowSumMat(scale * to_update->learning_rate_,
                                     in_value_reconstructed);
   }
   if (in_deriv) {
     if (in_deriv->Data() != out_deriv.Data())
       in_deriv->CopyFromMat(out_deriv);
     in_deriv->MulColsVec(scales_);
   }
 }
ConsolidateMemory()
void ConsolidateMemory () virtual
This virtual function relates to memory management, and avoiding fragmentation.
It is called only once per model, after we do the first minibatch of training. The default implementation does nothing, but it can be overridden by child classes, where it may re-initialize certain quantities that may possibly have been allocated during the forward pass (e.g. certain statistics; OnlineNaturalGradient objects). We use our own CPU-based allocator (see cu-allocator.h) and since it can't do paging since we're not in control of the GPU page table, fragmentation can be a problem. The allocator always tries to put things in 'low-address memory' (i.e. at smaller memory addresses) near the beginning of the block it allocated, to avoid fragmentation; but if permanent things (belonging to the model) are allocated in the forward pass, they can permanently stay in high memory. This function helps to prevent that, by re-allocating those things into low-address memory (It's important that it's called after all the temporary buffers for the forward-backward have been freed, so that there is low-address memory available)).
Reimplemented from Component.
Definition at line 2570 of file nnet-simple-component.cc.
References ScaleAndOffsetComponent::offset_preconditioner_, ScaleAndOffsetComponent::scale_preconditioner_, and OnlineNaturalGradient::Swap().
{
   OnlineNaturalGradient temp_scale(scale_preconditioner_);
   scale_preconditioner_.Swap(&temp_scale);
   OnlineNaturalGradient temp_offset(offset_preconditioner_);
   offset_preconditioner_.Swap(&temp_offset);
 }
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 1892 of file nnet-simple-component.h.
References Component::Add(), kaldi::nnet3::DotProduct(), kaldi::nnet3::PerturbParams(), and Component::Scale().
 { return new ScaleAndOffsetComponent(*this); }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 2420 of file nnet-simple-component.cc.
References ScaleAndOffsetComponent::offsets_, ScaleAndOffsetComponent::scales_, and kaldi::VecVec().
{
   const ScaleAndOffsetComponent *other =
       dynamic_cast<const ScaleAndOffsetComponent*>(&other_in);
   return VecVec(other->scales_, scales_) + VecVec(other->offsets_, offsets_);
 }
Epsilon()
BaseFloat Epsilon () const inline private
Definition at line 1922 of file nnet-simple-component.h.
Referenced by ScaleAndOffsetComponent::BackpropInternal(), and ScaleAndOffsetComponent::PropagateInternal().
 { return 1.0e-04; }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 2308 of file nnet-simple-component.cc.
References PerElementOffsetComponent::dim_, UpdatableComponent::Info(), PerElementOffsetComponent::offsets_, and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info()
          << ", rank=" << scale_preconditioner_.GetRank();
   if (dim_ != scales_.Dim())
     stream << ", block-size=" << scales_.Dim();
   PrintParameterStats(stream, "scales", scales_, true);
   PrintParameterStats(stream, "offsets", offsets_, true);
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 2319 of file nnet-simple-component.cc.
References PerElementOffsetComponent::dim_, ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), UpdatableComponent::InitLearningRatesFromConfig(), KALDI_ERR, PerElementOffsetComponent::offsets_, ConfigLine::UnusedValues(), PerElementOffsetComponent::use_natural_gradient_, and ConfigLine::WholeLine().
{
   InitLearningRatesFromConfig(cfl);
   if (!cfl->GetValue("dim", &dim_) || dim_ <= 0) {
     KALDI_ERR << "Dimension 'dim' must be specified and >0: "
               << cfl->WholeLine();
   }
   use_natural_gradient_ = true;
   cfl->GetValue("use-natural-gradient", &use_natural_gradient_);
   int32 block_dim = dim_,
       rank = 20;
   cfl->GetValue("block-dim", &block_dim);
   if (block_dim <= 0 || dim_ % block_dim != 0) {
     KALDI_ERR << "Invalid block-dim: " << cfl->WholeLine();
   }
   cfl->GetValue("rank", &rank);
   scales_.Resize(block_dim);
   scales_.Set(1.0);
   offsets_.Resize(block_dim);
   // offsets are all zero when initialized.
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   offset_preconditioner_.SetRank(rank);
   scale_preconditioner_.SetRank(rank);
   // the update period can't be configured for now; we'll add an option if we
   // want to.
   offset_preconditioner_.SetUpdatePeriod(4);
   scale_preconditioner_.SetUpdatePeriod(4);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1856 of file nnet-simple-component.h.
Referenced by ConstantFunctionComponent::Info().
 { return dim_; }
NumParameters()
virtual int32 NumParameters () const inline virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 1899 of file nnet-simple-component.h.
References Component::ConsolidateMemory().
 { return 2 * scales_.Dim(); }
operator=()
const ScaleAndOffsetComponent& operator= (const ScaleAndOffsetComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1857 of file nnet-simple-component.h.
References Component::Info(), and PnormComponent::InitFromConfig().
Referenced by ConstantFunctionComponent::Info().
 { return dim_; }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 2412 of file nnet-simple-component.cc.
References kaldi::kUndefined, ScaleAndOffsetComponent::offsets_, ScaleAndOffsetComponent::scales_, and CuVectorBase< Real >::SetRandn().
{
   CuVector<BaseFloat> temp(scales_.Dim(), kUndefined);
   temp.SetRandn();
   scales_.AddVec(stddev, temp);
   temp.SetRandn();
   offsets_.AddVec(stddev, temp);
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 2440 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::Data(), ScaleAndOffsetComponent::dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), ScaleAndOffsetComponent::PropagateInternal(), kaldi::SameDimAndStride(), ScaleAndOffsetComponent::scales_, and CuMatrixBase< Real >::Stride().
{
   if (dim_ == scales_.Dim()) {
     PropagateInternal(in, out);
   } else {
     int32 multiple = dim_ / scales_.Dim(),
         num_rows = in.NumRows(), block_dim = scales_.Dim();
     KALDI_ASSERT(in.NumCols() == in.Stride() &&
                  SameDimAndStride(in, *out));
     // Reinterpret the data as matrices with more rows but fewer columns.
     CuSubMatrix<BaseFloat> in_rearranged(in.Data(), num_rows * multiple,
                                          block_dim, block_dim),
         out_rearranged(out->Data(), num_rows * multiple,
                        block_dim, block_dim);
     PropagateInternal(in_rearranged, &out_rearranged);
   }
   return NULL;
 }
PropagateInternal()
void PropagateInternal (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const private
Definition at line 2461 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddVecToRows(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::Data(), kaldi::cu::EnsureNonzero(), ScaleAndOffsetComponent::Epsilon(), kaldi::kUndefined, CuMatrixBase< Real >::MulColsVec(), ScaleAndOffsetComponent::offsets_, and ScaleAndOffsetComponent::scales_.
Referenced by ScaleAndOffsetComponent::Propagate().
{
   if (out->Data() != in.Data())
     out->CopyFromMat(in);
   BaseFloat epsilon = Epsilon();
   int32 dim = scales_.Dim();
   CuVector<BaseFloat> scales_nonzero(dim, kUndefined);
   cu::EnsureNonzero(scales_, epsilon, &scales_nonzero);
   out->MulColsVec(scales_nonzero);
   out->AddVecToRows(1.0, offsets_);
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1864 of file nnet-simple-component.h.
References PnormComponent::Backprop(), kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kBackpropNeedsOutput, kaldi::nnet3::kInputContiguous, kaldi::nnet3::kOutputContiguous, kaldi::nnet3::kPropagateInPlace, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kUpdatableComponent, PnormComponent::Propagate(), PnormComponent::Read(), and PnormComponent::Write().
{
     // Note: the backprop would most naturally consume the input, but we
     // have arranged things so that the backprop consumes the output value
     // instead; this allows less memory use, since in typical configurations,
     // this will be followed by an affine component which needs its input
     // for the backprop (so requiring it to be present adds no extra
     // burden).
     return kSimpleComponent|kUpdatableComponent|
            kBackpropInPlace|kPropagateInPlace|
            kBackpropNeedsOutput|
         (dim_ != scales_.Dim() ?
          (kInputContiguous|kOutputContiguous) : 0);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 2350 of file nnet-simple-component.cc.
References PerElementOffsetComponent::dim_, kaldi::nnet3::ExpectToken(), PerElementOffsetComponent::offsets_, kaldi::ReadBasicType(), UpdatableComponent::ReadUpdatableCommon(), and PerElementOffsetComponent::use_natural_gradient_.
{
   ReadUpdatableCommon(is, binary);  // Read opening tag and learning rate
   ExpectToken(is, binary, "<Dim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<Scales>");
   scales_.Read(is, binary);
   ExpectToken(is, binary, "<Offsets>");
   offsets_.Read(is, binary);
   ExpectToken(is, binary, "<UseNaturalGradient>");
   ReadBasicType(is, binary, &use_natural_gradient_);
   int32 rank;
   ExpectToken(is, binary, "<Rank>");
   ReadBasicType(is, binary, &rank);
   scale_preconditioner_.SetRank(rank);
   offset_preconditioner_.SetRank(rank);
   ExpectToken(is, binary, "</ScaleAndOffsetComponent>");
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 2383 of file nnet-simple-component.cc.
References PerElementOffsetComponent::offsets_.
{
   if (scale == 0.0) {
     scales_.SetZero();
     offsets_.SetZero();
   } else {
     scales_.Scale(scale);
     offsets_.Scale(scale);
   }
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 1863 of file nnet-simple-component.h.
Referenced by ConstantFunctionComponent::Info().
 { return "ScaleAndOffsetComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 2433 of file nnet-simple-component.cc.
References ScaleAndOffsetComponent::offsets_, VectorBase< Real >::Range(), and ScaleAndOffsetComponent::scales_.
{
   int32 dim = scales_.Dim();
   scales_.CopyFromVec(params.Range(0, dim));
   offsets_.CopyFromVec(params.Range(dim, dim));
 }
Update()
void Update (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) private
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 2427 of file nnet-simple-component.cc.
References ScaleAndOffsetComponent::offsets_, VectorBase< Real >::Range(), and ScaleAndOffsetComponent::scales_.
{
   int32 dim = scales_.Dim();
   params->Range(0, dim).CopyFromVec(scales_);
   params->Range(dim, dim).CopyFromVec(offsets_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 2368 of file nnet-simple-component.cc.
References PerElementOffsetComponent::dim_, PerElementOffsetComponent::offsets_, PerElementOffsetComponent::use_natural_gradient_, kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<Scales>");
   scales_.Write(os, binary);
   WriteToken(os, binary, "<Offsets>");
   offsets_.Write(os, binary);
   WriteToken(os, binary, "<UseNaturalGradient>");
   WriteBasicType(os, binary, use_natural_gradient_);
   WriteToken(os, binary, "<Rank>");
   WriteBasicType(os, binary, scale_preconditioner_.GetRank());
   WriteToken(os, binary, "</ScaleAndOffsetComponent>");
 }
Member Data Documentation
dim_
int32 dim_ private
Definition at line 1939 of file nnet-simple-component.h.
Referenced by ScaleAndOffsetComponent::Backprop(), and ScaleAndOffsetComponent::Propagate().
offset_preconditioner_
OnlineNaturalGradient offset_preconditioner_ private
Definition at line 1946 of file nnet-simple-component.h.
Referenced by ScaleAndOffsetComponent::BackpropInternal(), and ScaleAndOffsetComponent::ConsolidateMemory().
offsets_
CuVector<BaseFloat> offsets_ private
Definition at line 1943 of file nnet-simple-component.h.
Referenced by ScaleAndOffsetComponent::Add(), ScaleAndOffsetComponent::BackpropInternal(), ScaleAndOffsetComponent::DotProduct(), ScaleAndOffsetComponent::PerturbParams(), ScaleAndOffsetComponent::PropagateInternal(), ScaleAndOffsetComponent::UnVectorize(), and ScaleAndOffsetComponent::Vectorize().
scale_preconditioner_
OnlineNaturalGradient scale_preconditioner_ private
Definition at line 1945 of file nnet-simple-component.h.
Referenced by ScaleAndOffsetComponent::BackpropInternal(), and ScaleAndOffsetComponent::ConsolidateMemory().
scales_
CuVector<BaseFloat> scales_ private
Definition at line 1942 of file nnet-simple-component.h.
Referenced by ScaleAndOffsetComponent::Add(), ScaleAndOffsetComponent::Backprop(), ScaleAndOffsetComponent::BackpropInternal(), ScaleAndOffsetComponent::DotProduct(), ScaleAndOffsetComponent::PerturbParams(), ScaleAndOffsetComponent::Propagate(), ScaleAndOffsetComponent::PropagateInternal(), ScaleAndOffsetComponent::UnVectorize(), and ScaleAndOffsetComponent::Vectorize().
use_natural_gradient_
bool use_natural_gradient_ private
Definition at line 1944 of file nnet-simple-component.h.
Referenced by ScaleAndOffsetComponent::BackpropInternal(), and ConstantFunctionComponent::Info().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc