Kaldi: RandomAccessTableReader< Holder > Class Template Reference
RandomAccessTableReader< Holder > Class Template Reference
"Table types and related functions"
Allows random access to a collection of objects in an archive or script file; see The Table concept.
#include <kaldi-table.h>
Public Types
typedef Holder::T T
Public Member Functions
RandomAccessTableReader ()
RandomAccessTableReader (const std::string &rspecifier)
bool Open (const std::string &rspecifier)
bool IsOpen () const
bool Close ()
bool HasKey (const std::string &key)
const T & Value (const std::string &key)
~RandomAccessTableReader ()
RandomAccessTableReader (const RandomAccessTableReader< Holder > &other)
Private Member Functions
RandomAccessTableReader & operator= (const RandomAccessTableReader< Holder > &)
void CheckImpl () const
Private Attributes
RandomAccessTableReaderImplBase< Holder > * impl_
Detailed Description
template<class Holder>
class kaldi::RandomAccessTableReader< Holder >
Allows random access to a collection of objects in an archive or script file; see The Table concept.
Definition at line 233 of file kaldi-table.h.
Member Typedef Documentation
T
typedef Holder::T T
Definition at line 235 of file kaldi-table.h.
Constructor & Destructor Documentation
RandomAccessTableReader() [1/2]
RandomAccessTableReader () inline
Definition at line 237 of file kaldi-table.h.
 : impl_(NULL) { }
RandomAccessTableReader() [2/2]
RandomAccessTableReader (const RandomAccessTableReader< Holder > & other) inline
Definition at line 271 of file kaldi-table.h.
                                  :
       impl_(NULL) { KALDI_ASSERT(other.impl_ == NULL); }
Member Function Documentation
IsOpen()
bool IsOpen () const inline
Definition at line 247 of file kaldi-table.h.
Referenced by kaldi::AccCmvnStatsWrapper(), kaldi::AccMinmaxStatsWrapper(), kaldi::AccumulateForUtterance(), main(), and kaldi::ReadData().
 { return (impl_ != NULL); }
operator=()
RandomAccessTableReader& operator= (const RandomAccessTableReader< Holder > &) private
Member Data Documentation
impl_
RandomAccessTableReaderImplBase<Holder>* impl_ private
Definition at line 279 of file kaldi-table.h.
Referenced by RandomAccessTableReader< kaldi::TokenHolder >::RandomAccessTableReader().
The documentation for this class was generated from the following files:
util/kaldi-table.h
util/kaldi-table-inl.h