Kaldi: NnetComputer Class Reference
NnetComputer Class Reference
Public Member Functions
NnetComputer (const Nnet &nnet, const CuMatrixBase< BaseFloat > &input_feats, bool pad, Nnet *nnet_to_update=NULL)
void Propagate ()
The forward-through-the-layers part of the computation.
void Backprop (CuMatrix< BaseFloat > *tmp_deriv)
BaseFloat ComputeLastLayerDeriv (const Posterior &pdf_post, CuMatrix< BaseFloat > *deriv) const
Computes objf derivative at last layer, and returns objective function summed over labels and multiplied by utterance_weight.
CuMatrixBase< BaseFloat > & GetOutput ()
Private Attributes
const Nnet & nnet_
std::vector< CuMatrix< BaseFloat > > forward_data_
Nnet * nnet_to_update_
std::vector< ChunkInfo > chunk_info_
Detailed Description
Definition at line 32 of file nnet-compute.cc.
Constructor & Destructor Documentation
NnetComputer()
NnetComputer (const Nnet & nnet, const CuMatrixBase< BaseFloat > & input_feats, bool pad, Nnet * nnet_to_update = NULL)
Definition at line 64 of file nnet-compute.cc.
References NnetComputer::chunk_info_, Nnet::ComputeChunkInfo(), NnetComputer::forward_data_, rnnlm::i, Nnet::InputDim(), KALDI_ERR, Nnet::LeftContext(), NnetComputer::nnet_, CuMatrixBase< Real >::NumCols(), Nnet::NumComponents(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Range(), CuMatrix< Real >::Resize(), Nnet::RightContext(), and CuMatrixBase< Real >::Row().
                                                 :
     nnet_(nnet), nnet_to_update_(nnet_to_update) {
   int32 dim = input_feats.NumCols();
   if (dim != nnet.InputDim()) {
     KALDI_ERR << "Feature dimension is " << dim << " but network expects "
               << nnet.InputDim();
   }
   forward_data_.resize(nnet.NumComponents() + 1);
   int32 left_context = (pad ? nnet_.LeftContext() : 0),
        right_context = (pad ? nnet_.RightContext() : 0);
   int32 num_rows = left_context + input_feats.NumRows() + right_context;
   nnet.ComputeChunkInfo(num_rows, 1, &chunk_info_);
   CuMatrix<BaseFloat> &input(forward_data_[0]);
   input.Resize(num_rows, dim);
   input.Range(left_context, input_feats.NumRows(),
               0, dim).CopyFromMat(input_feats);
   for (int32 i = 0; i < left_context; i++)
     input.Row(i).CopyFromVec(input_feats.Row(0));
   int32 last_row = input_feats.NumRows() - 1;
   for (int32 i = 0; i < right_context; i++)
     input.Row(num_rows - i - 1).CopyFromVec(input_feats.Row(last_row));
 }
Member Function Documentation
Backprop()
void Backprop (CuMatrix< BaseFloat > * tmp_deriv)
Definition at line 141 of file nnet-compute.cc.
References Component::Backprop(), NnetComputer::chunk_info_, NnetComputer::forward_data_, Nnet::GetComponent(), KALDI_ASSERT, NnetComputer::nnet_, NnetComputer::nnet_to_update_, and Nnet::NumComponents().
Referenced by kaldi::nnet2::NnetGradientComputation().
{
   KALDI_ASSERT(nnet_to_update_ != NULL); // Or why do backprop?
   // If later this reasoning changes, we can change this
   // statement and add logic to make component_to_update, below,
   // NULL if necessary.
   for (int32 c = nnet_.NumComponents() - 1; c >= 0; c--) {
     const Component &component = nnet_.GetComponent(c);
     Component *component_to_update = &(nnet_to_update_->GetComponent(c));
     const CuMatrix<BaseFloat>  &input = forward_data_[c],
                             &output = forward_data_[c+1],
                       &output_deriv = *tmp_deriv;
     CuMatrix<BaseFloat> input_deriv;
     component.Backprop(chunk_info_[c], chunk_info_[c+1], input, output, output_deriv,
                        component_to_update, &input_deriv);
     *tmp_deriv = input_deriv;
   }
 }
ComputeLastLayerDeriv()
BaseFloat ComputeLastLayerDeriv (const Posterior & pdf_post, CuMatrix< BaseFloat > * deriv) const
Computes objf derivative at last layer, and returns objective function summed over labels and multiplied by utterance_weight.
[Note: utterance_weight will normally be 1.0].
Definition at line 111 of file nnet-compute.cc.
References NnetComputer::forward_data_, rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_VLOG, kaldi::Log(), NnetComputer::nnet_, CuMatrixBase< Real >::NumCols(), Nnet::NumComponents(), CuMatrixBase< Real >::NumRows(), and CuMatrix< Real >::Resize().
Referenced by kaldi::nnet2::NnetGradientComputation().
{
   // TODO: convert this to proper CUDA code, c.f. ComputeObjfAndDeriv
   // in nnet-update.cc (I'm not sure, though, that this code is ever reached.)
   int32 num_components = nnet_.NumComponents();
   double tot_objf = 0.0, tot_weight = 0.0;
   const CuMatrix<BaseFloat> &last_layer_output = forward_data_[num_components];
   int32 num_frames = last_layer_output.NumRows(),
           num_pdfs = last_layer_output.NumCols();
   KALDI_ASSERT(pdf_post.size() == static_cast<size_t>(num_frames));
   deriv->Resize(num_frames, num_pdfs); // will zero it.
   for (int32 i = 0; i < deriv->NumRows(); i++) {
     for (size_t j = 0; j < pdf_post[i].size(); j++) {
       int32 label = pdf_post[i][j].first;
       BaseFloat weight = pdf_post[i][j].second;
       KALDI_ASSERT(label >= 0 && label < num_pdfs);
       BaseFloat this_prob = last_layer_output(i, label);
       KALDI_ASSERT(this_prob > 0.99e-20); // We floored to 1.0e-20 in SoftmaxLayer.
       tot_objf += weight * Log(this_prob);
       tot_weight += weight;
       (*deriv)(i, label) += weight / this_prob; // could be "=", assuming the
       // labels are all distinct.
     }
   }
   KALDI_VLOG(4) << "Objective function is " << (tot_objf/tot_weight) <<
       " per frame over " << tot_weight << " samples.";
   return tot_objf;
 }
GetOutput()
CuMatrixBase<BaseFloat>& GetOutput () inline
Definition at line 54 of file nnet-compute.cc.
References NnetComputer::forward_data_.
Referenced by kaldi::nnet2::NnetComputation(), and kaldi::nnet2::NnetComputationChunked().
 { return forward_data_.back(); }
Propagate()
void Propagate ()
The forward-through-the-layers part of the computation.
This is the forward part of the computation.
Definition at line 95 of file nnet-compute.cc.
References Component::BackpropNeedsInput(), Component::BackpropNeedsOutput(), NnetComputer::chunk_info_, NnetComputer::forward_data_, Nnet::GetComponent(), NnetComputer::nnet_, NnetComputer::nnet_to_update_, Nnet::NumComponents(), and Component::Propagate().
Referenced by kaldi::nnet2::NnetComputation(), kaldi::nnet2::NnetComputationChunked(), and kaldi::nnet2::NnetGradientComputation().
{
   for (int32 c = 0; c < nnet_.NumComponents(); c++) {
     const Component &component = nnet_.GetComponent(c);
     CuMatrix<BaseFloat> &input = forward_data_[c],
                      &output = forward_data_[c+1];
     component.Propagate(chunk_info_[c], chunk_info_[c+1], input, &output);
     const Component *prev_component = (c == 0 ? NULL : &(nnet_.GetComponent(c-1)));
     bool will_do_backprop = (nnet_to_update_ != NULL),
          keep_last_output = will_do_backprop &&
                              ((c>0 && prev_component->BackpropNeedsOutput()) ||
                               component.BackpropNeedsInput());
     if (!keep_last_output)
       forward_data_[c].Resize(0, 0); // We won't need this data; save memory.
   }
 }
Member Data Documentation
chunk_info_
std::vector<ChunkInfo> chunk_info_ private
Definition at line 61 of file nnet-compute.cc.
Referenced by NnetComputer::Backprop(), NnetComputer::NnetComputer(), and NnetComputer::Propagate().
forward_data_
std::vector<CuMatrix<BaseFloat> > forward_data_ private
Definition at line 58 of file nnet-compute.cc.
Referenced by NnetComputer::Backprop(), NnetComputer::ComputeLastLayerDeriv(), NnetComputer::GetOutput(), NnetComputer::NnetComputer(), and NnetComputer::Propagate().
nnet_
const Nnet& nnet_ private
Definition at line 57 of file nnet-compute.cc.
Referenced by NnetComputer::Backprop(), NnetComputer::ComputeLastLayerDeriv(), NnetComputer::NnetComputer(), and NnetComputer::Propagate().
nnet_to_update_
Nnet* nnet_to_update_ private
Definition at line 59 of file nnet-compute.cc.
Referenced by NnetComputer::Backprop(), and NnetComputer::Propagate().
The documentation for this class was generated from the following file:
nnet2/nnet-compute.cc