Kaldi: CuSpMatrix< Real > Class Template Reference
CuSpMatrix< Real > Class Template Reference
#include <matrix-common.h>
Public Member Functions
CuSpMatrix ()
CuSpMatrix (MatrixIndexT r, MatrixResizeType resize_type=kSetZero)
CuSpMatrix (const SpMatrix< Real > &orig)
CuSpMatrix (const CuSpMatrix< Real > &orig)
CuSpMatrix (const CuMatrixBase< Real > &orig, SpCopyType copy_type=kTakeLower)
CuSpMatrix< Real > & operator= (const CuSpMatrix< Real > &in)
~CuSpMatrix ()
void Resize (MatrixIndexT nRows, MatrixResizeType resize_type=kSetZero)
Real FrobeniusNorm () const
bool IsUnit (Real tol=0.001) const
bool ApproxEqual (const CuSpMatrix< Real > &other, Real tol=0.001) const
void CopyFromSp (const CuSpMatrix< Real > &other)
void CopyFromSp (const SpMatrix< Real > &other)
void CopyFromMat (const CuMatrixBase< Real > &orig, SpCopyType copy_type=kTakeLower)
void CopyToSp (SpMatrix< Real > *dst) const
CuValue< Real > operator() (MatrixIndexT r, MatrixIndexT c)
Real operator() (MatrixIndexT r, MatrixIndexT c) const
void Invert ()
Note: the CuMatrix version of the Invert() function will only work for positive definite matrices; it is based on Cholesky.
void AddVec2 (const Real alpha, const CuVectorBase< Real > &v)
void AddMat2 (const Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType transM, const Real beta)
void AddSp (const Real alpha, const CuSpMatrix< Real > &Ma)
Public Member Functions inherited from CuPackedMatrix< Real >
CuPackedMatrix ()
CuPackedMatrix (MatrixIndexT r, MatrixResizeType resize_type=kSetZero)
CuPackedMatrix (const PackedMatrix< Real > &orig)
CuPackedMatrix (const CuPackedMatrix< Real > &orig)
void SetZero ()
void SetUnit ()
< Set to zero
void SetRandn ()
< Set to unit matrix.
void SetDiag (Real alpha)
< Set to random values of a normal distribution
void AddToDiag (Real r)
< Set the diagonal value to alpha
void Scale (Real alpha)
void ScaleDiag (Real alpha)
Real Trace () const
~CuPackedMatrix ()
void Resize (MatrixIndexT nRows, MatrixResizeType resize_type=kSetZero)
Set packed matrix to a specified size (can be zero).
void CopyFromPacked (const CuPackedMatrix< Real > &src)
void CopyFromPacked (const PackedMatrix< Real > &src)
void CopyToPacked (PackedMatrix< Real > *dst) const
void Read (std::istream &in, bool binary)
void Write (std::ostream &out, bool binary) const
void Destroy ()
void Swap (CuPackedMatrix< Real > *other)
Swaps the contents of *this and *other. Shallow swap.
void Swap (PackedMatrix< Real > *other)
Swaps the contents of *this and *other.
Real * Data ()
const Real * Data () const
Real operator() (MatrixIndexT r, MatrixIndexT c) const
MatrixIndexT NumRows () const
MatrixIndexT NumCols () const
size_t SizeInBytes () const
Returns size in bytes of the data held by the matrix.
Protected Member Functions
const SpMatrix< Real > & Mat () const
SpMatrix< Real > & Mat ()
Protected Member Functions inherited from CuPackedMatrix< Real >
const PackedMatrix< Real > & Mat () const
PackedMatrix< Real > & Mat ()
void AddPacked (const Real alpha, const CuPackedMatrix< Real > &M)
Friends
class CuMatrixBase< Real >
class CuVectorBase< Real >
class CuTpMatrix< Real >
class CuSubMatrix< Real >
class CuRand< Real >
template<class R , class S >
R TraceSpSp (const CuSpMatrix< R > &A, const CuSpMatrix< S > &B)
Additional Inherited Members
Protected Attributes inherited from CuPackedMatrix< Real >
Real * data_
MatrixIndexT num_rows_
Detailed Description
template<typename Real>
class kaldi::CuSpMatrix< Real >
Definition at line 76 of file matrix-common.h.
Constructor & Destructor Documentation
CuSpMatrix() [1/5]
CuSpMatrix () inline
Definition at line 52 of file cu-sp-matrix.h.
 : CuPackedMatrix<Real>() {}
CuSpMatrix() [2/5]
CuSpMatrix (MatrixIndexT r, MatrixResizeType resize_type = kSetZero) inline explicit
Definition at line 54 of file cu-sp-matrix.h.
     : CuPackedMatrix<Real>(r, resize_type) {}
CuSpMatrix() [3/5]
CuSpMatrix (const SpMatrix< Real > & orig) inline explicit
Definition at line 57 of file cu-sp-matrix.h.
     : CuPackedMatrix<Real>(orig) {}
CuSpMatrix() [4/5]
CuSpMatrix (const CuSpMatrix< Real > & orig) inline
Definition at line 62 of file cu-sp-matrix.h.
     : CuPackedMatrix<Real>(orig) {}
CuSpMatrix() [5/5]
CuSpMatrix (const CuMatrixBase< Real > & orig, SpCopyType copy_type = kTakeLower) inline explicit
Definition at line 65 of file cu-sp-matrix.h.
References CuSpMatrix< Real >::CopyFromMat(), and CuSpMatrix< Real >::operator=().
       : CuPackedMatrix<Real>(orig.NumRows(), kUndefined) {
     CopyFromMat(orig, copy_type);
   }
~CuSpMatrix()
~CuSpMatrix () inline
Definition at line 73 of file cu-sp-matrix.h.
 {}
Member Function Documentation
AddMat2()
void AddMat2 (const Real alpha, const CuMatrixBase< Real > & M, MatrixTransposeType transM, const Real beta)
Definition at line 130 of file cu-sp-matrix.cc.
References CuMatrixBase< Real >::Data(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTakeLower, kaldi::kTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by CuSpMatrix< Real >::operator()(), OnlinePreconditioner::SelfTest(), OnlineNaturalGradient::SelfTest(), kaldi::UnitTestCuSpMatrixAddMat2(), kaldi::UnitTestCuSpMatrixInvert(), and kaldi::nnet2::UnitTestPreconditionDirections().
{
   KALDI_ASSERT((transM == kNoTrans && this->NumRows() == M.NumRows())
                || (transM == kTrans && this->NumRows() == M.NumCols()));
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (this->num_rows_ == 0) return;
     CuTimer tim;
     MatrixIndexT this_dim = this->NumRows(),
         m_other_dim = (transM == kNoTrans ? M.NumCols() : M.NumRows());
     if (this_dim == 0) return;
     if (alpha == 0.0) {
       if (beta != 1.0) this->Scale(beta);
       return;
     }
     cublasOperation_t trans = (transM == kTrans ? CUBLAS_OP_N : CUBLAS_OP_T);
     CuMatrix<Real> tmp_mat(*this);
     cublas_syrk(GetCublasHandle(), CUBLAS_FILL_MODE_UPPER, trans, this_dim, m_other_dim, alpha, M.Data(),
                 M.Stride(), beta, tmp_mat.Data(), tmp_mat.Stride());
     this->CopyFromMat(tmp_mat, kTakeLower);
     CuDevice::Instantiate().AccuProfile("CuSpMatrix::AddMat2", tim);
   } else
 #endif
   {
     Mat().AddMat2(alpha, M.Mat(), transM, beta);
   }
 }
AddSp()
void AddSp (const Real alpha, const CuSpMatrix< Real > & Ma) inline
Definition at line 127 of file cu-sp-matrix.h.
References CuPackedMatrix< Real >::AddPacked().
Referenced by kaldi::UnitTestCuSpMatrixAddSp().
{
     this->AddPacked(alpha, Ma);
   }
AddVec2()
void AddVec2 (const Real alpha, const CuVectorBase< Real > & v)
Definition at line 108 of file cu-sp-matrix.cc.
References CU2DBLOCK, CuVectorBase< Real >::Data(), CuVectorBase< Real >::Dim(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
Referenced by CuSpMatrix< Real >::operator()(), kaldi::UnitTestCuSpMatrixAddVec2(), and kaldi::nnet2::UnitTestPreconditionDirections().
{
   KALDI_ASSERT(v.Dim() == this->NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (this->num_rows_ == 0) return;
     CuTimer tim;
     size_t nr = this->num_rows_;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(nr, CU2DBLOCK), n_blocks(nr, CU2DBLOCK));
     CUBLAS_SAFE_CALL(cublas_spr(GetCublasHandle(), CUBLAS_FILL_MODE_UPPER, this->num_rows_, alpha, v.Data(),
                                 1, this->Data()));
     CuDevice::Instantiate().AccuProfile("CuSpMatrix::AddVec2", tim);
   } else
 #endif
   {
     Mat().AddVec2(alpha, v.Vec());
   }
 }
ApproxEqual()
bool ApproxEqual (const CuSpMatrix< Real > & other, Real tol = 0.001) const
Definition at line 200 of file cu-sp-matrix.cc.
References rnnlm::d, CuSpMatrix< Real >::FrobeniusNorm(), KALDI_ASSERT, and CuPackedMatrix< Real >::NumRows().
Referenced by kaldi::AssertEqual(), and CuSpMatrix< Real >::FrobeniusNorm().
{
   KALDI_ASSERT(this->NumRows() == B.NumRows());
   CuSpMatrix<Real> diff(*this);
   diff.AddSp(-1.0, B);
   Real a = this->FrobeniusNorm(), b = B.FrobeniusNorm(),
       d = diff.FrobeniusNorm();
   return (d <= tol * std::max(a, b));
 }
CopyFromMat()
void CopyFromMat (const CuMatrixBase< Real > & orig, SpCopyType copy_type = kTakeLower)
Definition at line 39 of file cu-sp-matrix.cc.
References CU1DBLOCK, CU2DBLOCK, CuMatrixBase< Real >::Data(), data_, CuMatrixBase< Real >::Dim(), KALDI_ASSERT, KALDI_ERR, kaldi::kTakeLower, kaldi::kTakeMean, kaldi::kTakeMeanAndCheck, kaldi::kTakeUpper, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
Referenced by CuMatrixBase< float >::Cholesky(), CuSpMatrix< Real >::CopyFromSp(), CuSpMatrix< Real >::CuSpMatrix(), kaldi::UnitTestCopyFromMat(), and kaldi::UnitTestCuSpMatrixCopyFromMat().
{
   KALDI_ASSERT(this->num_rows_ == M.NumRows() &&
                this->num_rows_ == M.NumCols());
   if (this->num_rows_ == 0)
     return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     MatrixIndexT D = this->NumRows();
     if (D == 0)
       return;
     switch (copy_type) {
       case kTakeMeanAndCheck:
         KALDI_ERR << "kTakeMeanAndCheck not supported!";
       // The grid/block dimensions have been very roughly tuned for the
       // individual cases.
       case kTakeMean:
         {
           dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
           dim3 dimGrid(n_blocks(D, CU2DBLOCK), n_blocks(D, CU2DBLOCK));
           cuda_take_mean(dimGrid, dimBlock, M.Data(), this->data_, M.Dim());
           CU_SAFE_CALL(cudaGetLastError());
         }
         break;
       case kTakeLower:
         {
           int32 block_size = std::min(CU1DBLOCK, this->num_rows_);
           dim3 dimBlock(1, block_size);
           dim3 dimGrid(D, n_blocks(D, block_size));
           cuda_take_lower(dimGrid, dimBlock, M.Data(), this->data_, M.Dim());
           CU_SAFE_CALL(cudaGetLastError());
         }
         break;
       case kTakeUpper:
         {
           dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
           dim3 dimGrid(n_blocks(D, CU2DBLOCK), n_blocks(D, CU2DBLOCK));
           cuda_take_upper(dimGrid, dimBlock, M.Data(), this->data_, M.Dim());
           CU_SAFE_CALL(cudaGetLastError());
         }
         break;
       default:
         KALDI_ASSERT("Invalid argument to CuSpMatrix::CopyFromMat");
     }
     CuDevice::Instantiate().AccuProfile("CuSpMatrix::CopyFromMat(from CuMatrixBase)", tim);
   } else
 #endif
   {
     Mat().CopyFromMat(M.Mat(), copy_type);
   }
 }
CopyFromSp() [1/2]
void CopyFromSp (const CuSpMatrix< Real > & other) inline
Definition at line 85 of file cu-sp-matrix.h.
References CuPackedMatrix< Real >::CopyFromPacked().
Referenced by kaldi::UnitTestCuSpMatrixOperator().
{
     CuPackedMatrix<Real>::CopyFromPacked(other);
   }
CopyFromSp() [2/2]
void CopyFromSp (const SpMatrix< Real > & other) inline
Definition at line 88 of file cu-sp-matrix.h.
References CuSpMatrix< Real >::CopyFromMat(), CuPackedMatrix< Real >::CopyFromPacked(), and kaldi::kTakeLower.
{
     CuPackedMatrix<Real>::CopyFromPacked(other);
   }
CopyToSp()
void CopyToSp (SpMatrix< Real > * dst) const inline
Definition at line 95 of file cu-sp-matrix.h.
References CuPackedMatrix< Real >::CopyToPacked().
Referenced by kaldi::UnitTestConstructor(), kaldi::UnitTestCopyFromMat(), kaldi::UnitTestCuSpMatrixAddMat2(), kaldi::UnitTestCuSpMatrixAddSp(), kaldi::UnitTestCuSpMatrixAddToDiag(), kaldi::UnitTestCuSpMatrixAddVec2(), kaldi::UnitTestCuSpMatrixConstructor(), and kaldi::UnitTestCuSpMatrixInvert().
{
     CuPackedMatrix<Real>::CopyToPacked(dst);
   }
FrobeniusNorm()
Real FrobeniusNorm () const inline
Definition at line 79 of file cu-sp-matrix.h.
References CuSpMatrix< Real >::ApproxEqual(), CuSpMatrix< Real >::IsUnit(), and CuSpMatrix< Real >::TraceSpSp.
Referenced by CuSpMatrix< Real >::ApproxEqual().
 { return sqrt(TraceSpSp(*this, *this)); }
Invert()
void Invert ()
Note: the CuMatrix version of the Invert() function will only work for positive definite matrices; it is based on Cholesky.
Definition at line 93 of file cu-sp-matrix.cc.
References CuMatrixBase< Real >::CopyFromSp(), and CuMatrixBase< Real >::SymInvertPosDef().
Referenced by CuSpMatrix< Real >::operator()(), kaldi::UnitTestCuSpMatrixInvert(), and kaldi::nnet2::UnitTestPreconditionDirections().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuMatrix<Real> mat(this->num_rows_, this->num_rows_);
     mat.CopyFromSp(*this);
     mat.SymInvertPosDef();
     this->CopyFromMat(mat);
   } else
 #endif
   { // Use inversion of CPU-based SpMatrix.
     Mat().Invert();
   }
 }
IsUnit()
bool IsUnit (Real tol = 0.001) const
Definition at line 210 of file cu-sp-matrix.cc.
References kaldi::TraceSpSp().
Referenced by CuSpMatrix< Real >::FrobeniusNorm().
{
   // want to return:
   //FrobeniusNorm(*this - I) <= tol * NumRows(), i.e.:
   //sqrt (trace((*this - I)(*this-I)) <= tol * NumRows()
   //    trace((*this - I)(*this - I)) <= tol * NumRows()
   // trace(*this * *this) + trace(I) - 2 * trace(*this) <= tol * NumRows()
   // trace(*this * *this) + dim - 2*this.Trace() <= tol * NumRows()
   // Note: we could do this more efficiently still, by slightly changing the
   // definition of IsUnit and getting rid of the extra stuff inside TraceSpSp
   // that corrects for the diagonal being counted twice.
   return (TraceSpSp(*this, *this) + this->NumRows() - 2.0 * this->Trace() <=
           tol * this->NumRows());
 }
Mat() [1/2]
const SpMatrix<Real>& Mat () const inline protected
Definition at line 132 of file cu-sp-matrix.h.
Referenced by CuVectorBase< float >::AddSpVec(), CuTpMatrix< Real >::Cholesky(), CuMatrixBase< float >::CopyFromSp(), and kaldi::TraceSpSp().
{
     return *(reinterpret_cast<const SpMatrix<Real>* >(this));
   }
Mat() [2/2]
SpMatrix<Real>& Mat () inline protected
Definition at line 135 of file cu-sp-matrix.h.
{
     return *(reinterpret_cast<SpMatrix<Real>* >(this));
   }
operator()() [1/2]
CuValue<Real> operator() (MatrixIndexT r, MatrixIndexT c) inline
Definition at line 99 of file cu-sp-matrix.h.
References CuPackedMatrix< Real >::data_, KALDI_ASSERT, CuPackedMatrix< Real >::num_rows_, and kaldi::swap().
{
     if (static_cast<UnsignedMatrixIndexT>(c) >
         static_cast<UnsignedMatrixIndexT>(r))
       std::swap(c, r);
     KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(r) <
                  static_cast<UnsignedMatrixIndexT>(this->num_rows_));
     return CuValue<Real>(this->data_ + (r * (r+1)) / 2 + c);
   }
operator()() [2/2]
Real operator() (MatrixIndexT r, MatrixIndexT c) const inline
Definition at line 108 of file cu-sp-matrix.h.
References CuSpMatrix< Real >::AddMat2(), CuSpMatrix< Real >::AddVec2(), CuPackedMatrix< Real >::data_, CuSpMatrix< Real >::Invert(), KALDI_ASSERT, CuPackedMatrix< Real >::num_rows_, and kaldi::swap().
{
     if (static_cast<UnsignedMatrixIndexT>(c) >
         static_cast<UnsignedMatrixIndexT>(r))
       std::swap(c, r);
     KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(r) <
                  static_cast<UnsignedMatrixIndexT>(this->num_rows_));
     return CuValue<Real>(this->data_ + (r * (r+1)) / 2 + c); // will be
     // casted to Real.
   }
operator=()
CuSpMatrix< Real > & operator= (const CuSpMatrix< Real > & in)
Definition at line 226 of file cu-sp-matrix.cc.
References kaldi::kUndefined, and CuPackedMatrix< Real >::NumRows().
Referenced by CuSpMatrix< Real >::CuSpMatrix().
{
   this->Resize(in.NumRows(), kUndefined);
   this->CopyFromPacked(in);
   return *this;
 }
Resize()
void Resize (MatrixIndexT nRows, MatrixResizeType resize_type = kSetZero) inline
Definition at line 75 of file cu-sp-matrix.h.
References CuPackedMatrix< Real >::Resize().
Referenced by SpMatrix< float >::SpMatrix().
{
     CuPackedMatrix<Real>::Resize(nRows, resize_type);
   }
Friends And Related Function Documentation
CuMatrixBase< Real >
friend class CuMatrixBase< Real > friend
Definition at line 42 of file cu-sp-matrix.h.
CuRand< Real >
friend class CuRand< Real > friend
Definition at line 46 of file cu-sp-matrix.h.
CuSubMatrix< Real >
friend class CuSubMatrix< Real > friend
Definition at line 45 of file cu-sp-matrix.h.
CuTpMatrix< Real >
friend class CuTpMatrix< Real > friend
Definition at line 44 of file cu-sp-matrix.h.
CuVectorBase< Real >
friend class CuVectorBase< Real > friend
Definition at line 43 of file cu-sp-matrix.h.
TraceSpSp
R TraceSpSp (const CuSpMatrix< R > & A, const CuSpMatrix< S > & B) friend
Referenced by CuSpMatrix< Real >::FrobeniusNorm().
The documentation for this class was generated from the following files:
matrix/matrix-common.h
cudamatrix/cu-sp-matrix.h
cudamatrix/cu-sp-matrix.cc