Kaldi: GaussPostHolder Class Reference
GaussPostHolder Class Reference
Posterior_group
#include <posterior.h>
Public Types
typedef GaussPost T
Public Member Functions
GaussPostHolder ()
void Clear ()
bool Read (std::istream &is)
const T & Value () const
void Swap (GaussPostHolder *other)
bool ExtractRange (const GaussPostHolder &other, const std::string &range)
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (GaussPostHolder)
Private Attributes
T t_
Detailed Description
Definition at line 103 of file posterior.h.
Member Typedef Documentation
T
typedef GaussPost T
Definition at line 105 of file posterior.h.
Constructor & Destructor Documentation
GaussPostHolder()
GaussPostHolder () inline
Definition at line 107 of file posterior.h.
References PosteriorHolder::Write().
 { }
Member Function Documentation
Clear()
void Clear () inline
Definition at line 111 of file posterior.h.
References PosteriorHolder::Read(), kaldi::swap(), and PosteriorHolder::t_.
 {  GaussPost tmp;  std::swap(tmp, t_); }
ExtractRange()
bool ExtractRange (const GaussPostHolder & other, const std::string & range) inline
Definition at line 126 of file posterior.h.
References PosteriorHolder::KALDI_DISALLOW_COPY_AND_ASSIGN(), and KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 118 of file posterior.h.
 { return true; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (GaussPostHolder) private
Read()
bool Read (std::istream & is)
Definition at line 181 of file posterior.cc.
References kaldi::InitKaldiInputStream(), KALDI_ERR, KALDI_WARN, kaldi::ReadBasicType(), and PosteriorHolder::t_.
{
   t_.clear();
   bool is_binary;
   if (!InitKaldiInputStream(is, &is_binary)) {
     KALDI_WARN << "Reading Table object, failed reading binary header";
     return false;
   }
   try {
     int32 sz;
     ReadBasicType(is, is_binary, &sz);
     if (sz < 0)
       KALDI_ERR << "Reading posteriors: got negative size";
     t_.resize(sz);
     for (GaussPost::iterator iter = t_.begin(); iter != t_.end(); ++iter) {
       int32 sz2;
       ReadBasicType(is, is_binary, &sz2);
       if (sz2 < 0)
         KALDI_ERR << "Reading posteriors: got negative size";
       iter->resize(sz2);
       for (std::vector<std::pair<int32, Vector<BaseFloat> > >::iterator
                iter2=iter->begin();
            iter2 != iter->end();
            iter2++) {
         ReadBasicType(is, is_binary, &(iter2->first));
         iter2->second.Read(is, is_binary);
       }
     }
     return true;
   } catch (std::exception &e) {
     KALDI_WARN << "Exception caught reading table of posteriors. " << e.what();
     t_.clear();
     return false;
   }
 }
Swap()
void Swap (GaussPostHolder * other) inline
Definition at line 122 of file posterior.h.
References PosteriorHolder::t_, and GaussPostHolder::t_.
{
     t_.swap(other->t_);
   }
Value()
const T& Value () const inline
Definition at line 120 of file posterior.h.
References PosteriorHolder::t_.
 { return t_; }
Write()
bool Write (std::ostream & os, bool binary, const T & t) static
Definition at line 157 of file posterior.cc.
References kaldi::InitKaldiOutputStream(), KALDI_WARN, and kaldi::WriteBasicType().
{
   InitKaldiOutputStream(os, binary);  // Puts binary header if binary mode.
   try {
     // We don't bother making this a one-line format.
     int32 sz = t.size();
     WriteBasicType(os, binary, sz);
     for (GaussPost::const_iterator iter = t.begin(); iter != t.end(); ++iter) {
       int32 sz2 = iter->size();
       WriteBasicType(os, binary, sz2);
       for (std::vector<std::pair<int32, Vector<BaseFloat> > >::const_iterator iter2=iter->begin();
            iter2 != iter->end();
            iter2++) {
         WriteBasicType(os, binary, iter2->first);
         iter2->second.Write(os, binary);
       }
     }
     if(!binary) os << '\n';
     return os.good();
   } catch (const std::exception &e) {
     KALDI_WARN << "Exception caught writing table of posteriors. " << e.what();
     return false;  // Write failure.
   }
 }
Member Data Documentation
t_
T t_ private
Definition at line 132 of file posterior.h.
Referenced by GaussPostHolder::Swap().
The documentation for this class was generated from the following files:
hmm/posterior.h
hmm/posterior.cc