Kaldi: DeterminizeLatticeTask Class Reference
DeterminizeLatticeTask Class Reference
Public Member Functions
DeterminizeLatticeTask (const TransitionModel &trans_model, fst::DeterminizeLatticePhonePrunedOptions &opts, std::string key, BaseFloat acoustic_scale, BaseFloat beam, Lattice *lat, CompactLatticeWriter *clat_writer, int32 *num_warn)
void operator() ()
~DeterminizeLatticeTask ()
DeterminizeLatticeTask (fst::DeterminizeLatticePrunedOptions &opts, std::string key, BaseFloat acoustic_scale, BaseFloat beam, bool minimize, Lattice *lat, CompactLatticeWriter *clat_writer, int32 *num_warn)
void operator() ()
~DeterminizeLatticeTask ()
Private Attributes
const TransitionModel * trans_model_
const fst::DeterminizeLatticePhonePrunedOptions & opts_
std::string key_
BaseFloat acoustic_scale_
BaseFloat beam_
Lattice * lat_
CompactLattice det_clat_
CompactLatticeWriter * clat_writer_
int32 * num_warn_
const fst::DeterminizeLatticePrunedOptions & opts_
bool minimize_
Detailed Description
Definition at line 30 of file lattice-determinize-phone-pruned-parallel.cc.
Constructor & Destructor Documentation
DeterminizeLatticeTask() [1/2]
DeterminizeLatticeTask (const TransitionModel & trans_model, fst::DeterminizeLatticePhonePrunedOptions & opts, std::string key, BaseFloat acoustic_scale, BaseFloat beam, Lattice * lat, CompactLatticeWriter * clat_writer, int32 * num_warn) inline
Definition at line 33 of file lattice-determinize-phone-pruned-parallel.cc.
Referenced by main().
                       :
       trans_model_(&trans_model), opts_(opts), key_(key),
       acoustic_scale_(acoustic_scale), beam_(beam),
       lat_(lat), clat_writer_(clat_writer), num_warn_(num_warn) { }
~DeterminizeLatticeTask() [1/2]
~DeterminizeLatticeTask () inline
Definition at line 66 of file lattice-determinize-phone-pruned-parallel.cc.
References DeterminizeLatticeTask::clat_writer_, DeterminizeLatticeTask::det_clat_, KALDI_VLOG, DeterminizeLatticeTask::key_, and TableWriter< Holder >::Write().
{
     KALDI_VLOG(2) << "Wrote lattice with " << det_clat_.NumStates()
                   << " for key " << key_;
     clat_writer_->Write(key_, det_clat_);
   }
DeterminizeLatticeTask() [2/2]
DeterminizeLatticeTask (fst::DeterminizeLatticePrunedOptions & opts, std::string key, BaseFloat acoustic_scale, BaseFloat beam, bool minimize, Lattice * lat, CompactLatticeWriter * clat_writer, int32 * num_warn) inline
Definition at line 33 of file lattice-determinize-pruned-parallel.cc.
                       :
       opts_(opts), key_(key), acoustic_scale_(acoustic_scale), beam_(beam),
       minimize_(minimize), lat_(lat), clat_writer_(clat_writer),
       num_warn_(num_warn) { }
~DeterminizeLatticeTask() [2/2]
~DeterminizeLatticeTask () inline
Definition at line 75 of file lattice-determinize-pruned-parallel.cc.
References DeterminizeLatticeTask::clat_writer_, DeterminizeLatticeTask::det_clat_, KALDI_VLOG, DeterminizeLatticeTask::key_, and TableWriter< Holder >::Write().
{
     KALDI_VLOG(2) << "Wrote lattice with " << det_clat_.NumStates()
                   << " for key " << key_;
     clat_writer_->Write(key_, det_clat_);
   }
Member Function Documentation
operator()() [1/2]
void operator() () inline
Definition at line 46 of file lattice-determinize-phone-pruned-parallel.cc.
References DeterminizeLatticeTask::acoustic_scale_, fst::AcousticLatticeScale(), DeterminizeLatticeTask::beam_, DeterminizeLatticeTask::det_clat_, fst::DeterminizeLatticePhonePrunedWrapper(), KALDI_WARN, DeterminizeLatticeTask::key_, DeterminizeLatticeTask::lat_, DeterminizeLatticeTask::opts_, fst::ScaleLattice(), and DeterminizeLatticeTask::trans_model_.
                       {
     // We apply the acoustic scale before determinization and will undo it
     // afterward, since it can affect the result.
     fst::ScaleLattice(fst::AcousticLatticeScale(acoustic_scale_), lat_);
     if (!DeterminizeLatticePhonePrunedWrapper(
             *trans_model_, lat_, beam_, &det_clat_, opts_)) {
       KALDI_WARN << "For key " << key_ << ", determinization did not succeed"
           "(partial output will be pruned tighter than the specified beam.)";
       (*num_warn_)++;
     }
     delete lat_;
     lat_ = NULL;
     // Invert the original acoustic scaling
     fst::ScaleLattice(fst::AcousticLatticeScale(1.0/acoustic_scale_),
                       &det_clat_);
   }
operator()() [2/2]
void operator() () inline
Definition at line 46 of file lattice-determinize-pruned-parallel.cc.
References DeterminizeLatticeTask::acoustic_scale_, fst::AcousticLatticeScale(), DeterminizeLatticeTask::beam_, DeterminizeLatticeTask::det_clat_, fst::DeterminizeLatticePruned(), KALDI_WARN, DeterminizeLatticeTask::key_, DeterminizeLatticeTask::lat_, DeterminizeLatticeTask::minimize_, fst::MinimizeCompactLattice(), DeterminizeLatticeTask::opts_, fst::PushCompactLatticeStrings(), fst::PushCompactLatticeWeights(), and fst::ScaleLattice().
                       {
     Invert(lat_); // to get word labels on the input side.
     // We apply the acoustic scale before determinization and will undo it
     // afterward, since it can affect the result.
     fst::ScaleLattice(fst::AcousticLatticeScale(acoustic_scale_), lat_);
     if (!TopSort(lat_)) {
       KALDI_WARN << "Could not topologically sort lattice: this probably means it"
           " has bad properties e.g. epsilon cycles.  Your LM or lexicon might "
           "be broken, e.g. LM with epsilon cycles or lexicon with empty words.";
       (*num_warn_)++;
     }
     fst::ArcSort(lat_, fst::ILabelCompare<LatticeArc>());
     if (!DeterminizeLatticePruned(*lat_, beam_, &det_clat_, opts_)) {
       KALDI_WARN << "For key " << key_ << ", determinization did not succeed"
           "(partial output will be pruned tighter than the specified beam.)";
       (*num_warn_)++;
     }
     delete lat_; // This is no longer needed so we can delete it now;
     lat_ = NULL;
     fst::Connect(&det_clat_); // remove states not leading to any final state,
     if (minimize_) {
       PushCompactLatticeStrings(&det_clat_);
       PushCompactLatticeWeights(&det_clat_);
       MinimizeCompactLattice(&det_clat_);
     }
     // Invert the original acoustic scaling
     fst::ScaleLattice(fst::AcousticLatticeScale(1.0/acoustic_scale_),
                       &det_clat_);
   }
Member Data Documentation
acoustic_scale_
BaseFloat acoustic_scale_ private
Definition at line 75 of file lattice-determinize-phone-pruned-parallel.cc.
Referenced by DeterminizeLatticeTask::operator()().
beam_
BaseFloat beam_ private
Definition at line 76 of file lattice-determinize-phone-pruned-parallel.cc.
Referenced by DeterminizeLatticeTask::operator()().
clat_writer_
CompactLatticeWriter * clat_writer_ private
Definition at line 82 of file lattice-determinize-phone-pruned-parallel.cc.
Referenced by DeterminizeLatticeTask::~DeterminizeLatticeTask().
det_clat_
CompactLattice det_clat_ private
Definition at line 81 of file lattice-determinize-phone-pruned-parallel.cc.
Referenced by DeterminizeLatticeTask::operator()(), and DeterminizeLatticeTask::~DeterminizeLatticeTask().
key_
std::string key_ private
Definition at line 74 of file lattice-determinize-phone-pruned-parallel.cc.
Referenced by DeterminizeLatticeTask::operator()(), and DeterminizeLatticeTask::~DeterminizeLatticeTask().
lat_
Lattice * lat_ private
Definition at line 78 of file lattice-determinize-phone-pruned-parallel.cc.
Referenced by DeterminizeLatticeTask::operator()().
minimize_
bool minimize_ private
Definition at line 85 of file lattice-determinize-pruned-parallel.cc.
Referenced by DeterminizeLatticeTask::operator()().
num_warn_
int32 * num_warn_ private
Definition at line 83 of file lattice-determinize-phone-pruned-parallel.cc.
opts_ [1/2]
const fst::DeterminizeLatticePhonePrunedOptions& opts_ private
Definition at line 73 of file lattice-determinize-phone-pruned-parallel.cc.
Referenced by DeterminizeLatticeTask::operator()().
opts_ [2/2]
const fst::DeterminizeLatticePrunedOptions& opts_ private
Definition at line 81 of file lattice-determinize-pruned-parallel.cc.
trans_model_
const TransitionModel* trans_model_ private
Definition at line 72 of file lattice-determinize-phone-pruned-parallel.cc.
Referenced by DeterminizeLatticeTask::operator()().
The documentation for this class was generated from the following files:
latbin/lattice-determinize-phone-pruned-parallel.cc
latbin/lattice-determinize-pruned-parallel.cc