Kaldi: ExamplesRepository Class Reference
ExamplesRepository Class Reference
This class stores neural net training examples to be used in multi-threaded training.
#include <nnet-example.h>
Public Member Functions
void AcceptExamples (std::vector< NnetExample > *examples)
The following function is called by the code that reads in the examples, with a batch of examples.
void ExamplesDone ()
The following function is called by the code that reads in the examples, when we're done reading examples.
bool ProvideExamples (std::vector< NnetExample > *examples)
This function is called by the code that does the training.
ExamplesRepository ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (ExamplesRepository)
Private Attributes
Semaphore full_semaphore_
Semaphore empty_semaphore_
std::vector< NnetExample > examples_
bool done_
Detailed Description
This class stores neural net training examples to be used in multi-threaded training.
Definition at line 99 of file nnet-example.h.
Constructor & Destructor Documentation
ExamplesRepository()
ExamplesRepository () inline
Definition at line 115 of file nnet-example.h.
 : empty_semaphore_(1), done_(false) { }
Member Function Documentation
AcceptExamples()
void AcceptExamples (std::vector< NnetExample > * examples)
The following function is called by the code that reads in the examples, with a batch of examples.
[It will empty the vector "examples").
Definition at line 209 of file nnet-example.cc.
References KALDI_ASSERT.
Referenced by kaldi::nnet2::DoBackpropParallel().
{
   KALDI_ASSERT(!examples->empty());
   empty_semaphore_.Wait();
   KALDI_ASSERT(examples_.empty());
   examples_.swap(*examples);
   full_semaphore_.Signal();
 }
ExamplesDone()
void ExamplesDone ()
The following function is called by the code that reads in the examples, when we're done reading examples.
Definition at line 218 of file nnet-example.cc.
References KALDI_ASSERT.
Referenced by kaldi::nnet2::DoBackpropParallel().
{
   empty_semaphore_.Wait();
   KALDI_ASSERT(examples_.empty());
   done_ = true;
   full_semaphore_.Signal();
 }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (ExamplesRepository) private
ProvideExamples()
bool ProvideExamples (std::vector< NnetExample > * examples)
This function is called by the code that does the training.
It gets the training examples, and if they are available, puts them in "examples" and returns true. It returns false when there are no examples left and ExamplesDone() has been called.
Definition at line 225 of file nnet-example.cc.
References KALDI_ASSERT.
Referenced by DoBackpropParallelClass::operator()().
{
   full_semaphore_.Wait();
   if (done_) {
     KALDI_ASSERT(examples_.empty());
     full_semaphore_.Signal(); // Increment the semaphore so
     // the call by the next thread will not block.
     return false; // no examples to return-- all finished.
   } else {
     KALDI_ASSERT(!examples_.empty() && examples->empty());
     examples->swap(examples_);
     empty_semaphore_.Signal();
     return true;
   }
 }
Member Data Documentation
done_
bool done_ private
Definition at line 121 of file nnet-example.h.
empty_semaphore_
Semaphore empty_semaphore_ private
Definition at line 118 of file nnet-example.h.
examples_
std::vector<NnetExample> examples_ private
Definition at line 120 of file nnet-example.h.
full_semaphore_
Semaphore full_semaphore_ private
Definition at line 117 of file nnet-example.h.
The documentation for this class was generated from the following files:
nnet2/nnet-example.h
nnet2/nnet-example.cc