Kaldi: TxpSylmax Class Reference
TxpSylmax Class Reference
Applies maximal onset rule to create syllables see Syllabification.
#include <txpsylmax.h>
Public Member Functions
TxpSylmax ()
~TxpSylmax ()
void Init (const TxpParseOptions &opts, const std::string &name)
bool Parse (const std::string &tpdb)
void Maxonset (PhoneVector *pronptr)
Apply maximal onset rules to the phones in the array.
void Writespron (PhoneVector *pronptr, std::string *sylpron)
Convert phone array to a string based pronunciation for XML.
int32 GetPhoneVector (const char *pron, PhoneVector *phonevectorptr)
Append a pronunciation onto a phone array.
bool IsSyllabic (const char *phone)
Decide if a phone is syllabic or not.
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
virtual void EndElement (const char *name)
Inherited class for bespoke end element handling.
virtual void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
virtual void StartCData ()
Inherited class for bespoke start cdata handling.
virtual void EndCData ()
Inherited class for bespoke start cdata handling.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
int32 AddSylBound (PhoneVector *pron)
Based on codas, onsets and nuclei set syllable boundaries in phone array.
int32 FindNucleus (const PhoneVector &pron, int32 pos)
Find if a valid nucleus begins here.
int32 FindOnset (const PhoneVector &pron, int32 pos)
Find if a valid onset ends here.
void InsertPhone (PhoneVector *phonevectorptr, const char *p, int32 len, bool wbnd)
Append a phone starting at p into the phone array.
bool GetPhoneNucleusPattern (const PhoneVector &pron, int32 pos, int32 len, bool with_stress, std::string *pat)
Set nucleus pattern based on position and length in phone array return true if not blocked by a word boundary and sufficient items are available.
bool GetPhoneOnsetPattern (const PhoneVector &pron, int32 pos, int32 len, std::string *pat)
Set onset pattern based on position and length backwards in phone array return true if not blocked by a word boundary and sufficient items are available.
Private Attributes
StringSet syllabic_
phones which are syllabic
StringSet nuclei_
valid nucleus patterns
StringSet onsets_
valid onset patterns
bool stress_
If stress true nucleus patterns must match correct stress.
int32 max_onset_
longest onset pattern
int32 max_nucleus_
longest nucleus pattern
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
Applies maximal onset rule to create syllables see Syllabification.
Definition at line 48 of file txpsylmax.h.
Constructor & Destructor Documentation
TxpSylmax()
TxpSylmax () inline explicit
Definition at line 50 of file txpsylmax.h.
 : stress_(false), max_onset_(0), max_nucleus_(0) {}
~TxpSylmax()
~TxpSylmax () inline
Definition at line 51 of file txpsylmax.h.
 {}
Member Function Documentation
AddSylBound()
int32 AddSylBound (PhoneVector * pron) private
Based on codas, onsets and nuclei set syllable boundaries in phone array.
Definition at line 101 of file txpsylmax.cc.
References rnnlm::i, kaldi::TXPSYLMAX_TYPE_CODA, kaldi::TXPSYLMAX_TYPE_NUCLEUS, and kaldi::TXPSYLMAX_TYPE_ONSET.
Referenced by TxpSylmax::Init(), and TxpSylmax::Maxonset().
{
   PhoneVector &pron = *pronptr;
   enum TXPSYLMAX_TYPE ltype = pron[0].type;
   bool codab = pron[0].codab;
   int i, coda;
   for (i = 1; i < pron.size(); i++) {
     if (codab &&
         !((ltype == TXPSYLMAX_TYPE_ONSET &&
            pron[i].type == TXPSYLMAX_TYPE_NUCLEUS) ||
           (ltype == TXPSYLMAX_TYPE_NUCLEUS &&
            pron[i].type == TXPSYLMAX_TYPE_CODA)))
       pron[i - 1].sylb = true;
     ltype = pron[i].type;
     codab = pron[i].codab;
   }
   // Returns position of the start of the last coda in the word
   // if cross word syllabification
   if (pron[pron.size() - 1].cross_word) {
     for (i = i - 1; i >= 0; i--) {
       if (pron[i].type != TXPSYLMAX_TYPE_CODA) {
         coda = i + 1;
         break;
       } else if (i == 0 && pron[i].type == TXPSYLMAX_TYPE_CODA) {
         coda = 1;
       }
     }
     return coda;
   } else {
     pron[pron.size() - 1].sylb = true;
   }
   return 0;
 }
FindNucleus()
int32 FindNucleus (const PhoneVector & pron, int32 pos) private
Find if a valid nucleus begins here.
Definition at line 134 of file txpsylmax.cc.
References TxpSylmax::GetPhoneNucleusPattern(), TxpSylmax::max_nucleus_, TxpSylmax::nuclei_, and TxpSylmax::stress_.
Referenced by TxpSylmax::Init(), and TxpSylmax::Maxonset().
{
   int len;
   std::string pat;
   StringSet::iterator it;
   for (len = max_nucleus_; len > 0; len--) {
     if (GetPhoneNucleusPattern(pron, pos, len, stress_, &pat)) {
       it = nuclei_.find(pat);
       if (it != nuclei_.end())
         return len;
     }
   }
   return 0;
 }
FindOnset()
int32 FindOnset (const PhoneVector & pron, int32 pos) private
Find if a valid onset ends here.
Definition at line 148 of file txpsylmax.cc.
References TxpSylmax::GetPhoneOnsetPattern(), TxpSylmax::max_onset_, and TxpSylmax::onsets_.
Referenced by TxpSylmax::Init(), and TxpSylmax::Maxonset().
{
   int len;
   std::string pat;
   StringSet::iterator it;
   for (len = max_onset_; len > 0; len--) {
     if (GetPhoneOnsetPattern(pron, pos, len, &pat)) {
       it = onsets_.find(pat);
       if (it != onsets_.end())
         return len;
     }
   }
   return 0;
 }
GetPhoneNucleusPattern()
bool GetPhoneNucleusPattern (const PhoneVector & pron, int32 pos, int32 len, bool with_stress, std::string * pat) private
Set nucleus pattern based on position and length in phone array return true if not blocked by a word boundary and sufficient items are available.
Definition at line 209 of file txpsylmax.cc.
References rnnlm::i.
Referenced by TxpSylmax::FindNucleus(), and TxpSylmax::Init().
{
   PhoneVector::const_iterator it;
   int32 i;
   pat->clear();
   for (i = 0, it = pron.begin() + pos; i < len; ++it, ++i) {
     if (it == pron.end()) {
       pat->clear();
       return false;
     }
     if (!pat->empty()) *pat += " ";
     // Remove stress marks if required (forward only for nucleus)
     if (!with_stress)
       *pat += it->name;
     else
       *pat += it->name + it->stress;
   }
   return true;
 }
GetPhoneOnsetPattern()
bool GetPhoneOnsetPattern (const PhoneVector & pron, int32 pos, int32 len, std::string * pat) private
Set onset pattern based on position and length backwards in phone array return true if not blocked by a word boundary and sufficient items are available.
Definition at line 230 of file txpsylmax.cc.
References rnnlm::i.
Referenced by TxpSylmax::FindOnset(), and TxpSylmax::Init().
{
   PhoneVector::const_reverse_iterator it;
   int32 i;
   pat->clear();
   for (i = 0, it = pron.rbegin() + (pron.size() - pos); i < len; ++it, ++i) {
     if (it == pron.rend()) {
       pat->clear();
       return false;
     }
     // word boundary blocks onset pattern
     if (it->wrdb && !it->cross_word) {
       pat->clear();
       return false;
     }
     if (!pat->empty()) *pat = " " + *pat;
     *pat = it->name + *pat;
   }
   return true;
 }
GetPhoneVector()
int32 GetPhoneVector (const char * pron, PhoneVector * phonevectorptr)
Append a pronunciation onto a phone array.
Definition at line 164 of file txpsylmax.cc.
References array, rnnlm::i, and TxpSylmax::InsertPhone().
Referenced by TxpSylmax::Init(), TxpSyllabify::Process(), and TxpSylmax::StartElement().
{
   PhoneVector &phonevector = *phonevectorptr;
   std::vector<std::string> array;
   const char *p, *s;
   int32 i, len;
   p = pron;
   i = 0;
   if (!p) return 0;
   while (*p) {
     s = strstr(p, " ");
     if (s) {
       len = static_cast<int32>(s - p);
       InsertPhone(phonevectorptr, p, len, false);
       p = s;
       p++;
     } else {
       len = strlen(p);
       InsertPhone(phonevectorptr, p, len, true);
       p += len;
       }
     i++;
   }
   return phonevector.size();
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & name) inline
Definition at line 52 of file txpsylmax.h.
References TxpSylmax::AddSylBound(), TxpSylmax::FindNucleus(), TxpSylmax::FindOnset(), TxpSylmax::GetPhoneNucleusPattern(), TxpSylmax::GetPhoneOnsetPattern(), TxpSylmax::GetPhoneVector(), TxpXmlData::Init(), TxpSylmax::InsertPhone(), TxpSylmax::IsSyllabic(), TxpSylmax::Maxonset(), TxpSylmax::Parse(), TxpSylmax::StartElement(), and TxpSylmax::Writespron().
Referenced by TxpSyllabify::Init().
{
     TxpXmlData::Init(opts, "sylmax", name);
   }
InsertPhone()
void InsertPhone (PhoneVector * phonevectorptr, const char * p, int32 len, bool wbnd) private
Append a phone starting at p into the phone array.
Definition at line 191 of file txpsylmax.cc.
References TxpSylItem::Clear(), TxpSylItem::cross_word, TxpSylItem::name, TxpSylItem::stress, and TxpSylItem::wrdb.
Referenced by TxpSylmax::GetPhoneVector(), and TxpSylmax::Init().
{
   PhoneVector &phonevector = *phonevectorptr;
   TxpSylItem item;
   item.Clear();
   item.wrdb = wrdb;
   if (p[len - 1] >= '0' && p[len - 1] <= '9') {
     item.name = std::string(p, len -1);
     item.stress = std::string(p + len - 1, 1);
   } else if (p[len - 1] == '+') {
     item.name = std::string(p, len -1);
         item.cross_word = true;
   } else {
     item.name = std::string(p, len);
   }
   phonevector.push_back(item);
 }
IsSyllabic()
bool IsSyllabic (const char * phone)
Decide if a phone is syllabic or not.
Definition at line 252 of file txpsylmax.cc.
References TxpSylmax::onsets_, and TxpSylmax::syllabic_.
Referenced by TxpSylmax::Init().
{
   StringSet::iterator it = syllabic_.find(std::string(phone));
   return (it != onsets_.end());
 }
Maxonset()
void Maxonset (PhoneVector * pronptr)
Apply maximal onset rules to the phones in the array.
Definition at line 34 of file txpsylmax.cc.
References TxpSylmax::AddSylBound(), TxpSylmax::FindNucleus(), TxpSylmax::FindOnset(), rnnlm::i, kaldi::TXPSYLMAX_TYPE_NUCLEUS, and kaldi::TXPSYLMAX_TYPE_ONSET.
Referenced by TxpSylmax::Init(), and TxpSyllabify::Process().
{
   std::string pat;
   int32 nlen, olen, pos, i;
   PhoneVector &pron = *pronptr;
   StringSet::iterator it;
   // move forwards trying to find the nucleus
   for (pos = 0; pos < pron.size(); pos++) {
     // try largest nuclei first
     nlen = FindNucleus(pron, pos);
     if (nlen) {
       olen = FindOnset(pron, pos);
       if (olen) {
         if (pos - olen - 1 >= 0) pron[pos - olen - 1].codab = true;
         for (i = pos - olen; i < pos; i++)
           pron[i].type = TXPSYLMAX_TYPE_ONSET;
       }
       if (pos > 0) pron[pos - 1].codab = true;
       // mark nucleus
       for (i = pos; i < pos + nlen; i++)
         pron[i].type = TXPSYLMAX_TYPE_NUCLEUS;
       pron[pos + nlen - 1].codab = true;
       if (nlen > 1) pos += nlen - 1;
     }
   }
   AddSylBound(&pron);
 }
Parse()
bool Parse (const std::string & tpdb)
Definition at line 26 of file txpsylmax.cc.
References KALDI_WARN, and TxpXmlData::Parse().
Referenced by TxpSyllabify::Init(), and TxpSylmax::Init().
{
   bool r;
   r = TxpXmlData::Parse(tpdb);
   if (!r)
     KALDI_WARN << "Error reading phrase break file: " << tpdb;
   return r;
 }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 258 of file txpsylmax.cc.
References TxpXmlData::fname_, TxpXmlData::GetCurrentLineNumber(), TxpSylmax::GetPhoneVector(), KALDI_ERR, TxpSylmax::max_nucleus_, TxpSylmax::max_onset_, TxpSylmax::nuclei_, TxpSylmax::onsets_, TxpXmlData::SetAttribute(), TxpSylmax::stress_, and TxpSylmax::syllabic_.
Referenced by TxpSylmax::Init().
{
   std::string item;
   PhoneVector pv;
   int32 size;
   if (!strcmp("nuclei", name)) {
     SetAttribute("stress", atts, &item);
     stress_ = false;
     if (item == "true" || item == "True" || item == "TRUE")
       stress_ = true;
   } else if (!strcmp("s", name)) {
     SetAttribute("name", atts, &item);
     if (item.empty()) {
       KALDI_ERR << fname_ << ": error missing 'name' attribute on line " << GetCurrentLineNumber();
       return;
     }
     syllabic_.insert(item);
   } else if (!strcmp("o", name)) {
     SetAttribute("pat", atts, &item);
     if (item.empty()) {
       KALDI_ERR << fname_ << ": error missing 'pat' attribute on line " << GetCurrentLineNumber();
       return;
     }
     onsets_.insert(item);
     size = GetPhoneVector(item.c_str(), &pv);
     if (size > max_onset_) max_onset_ = size;
   } else if (!strcmp("n", name)) {
     SetAttribute("pat", atts, &item);
     if (item.empty()) {
       KALDI_ERR << fname_ << ": error missing 'pat' attribute on line " << GetCurrentLineNumber();
       return;
     }
     nuclei_.insert(item);
     size = GetPhoneVector(item.c_str(), &pv);
     if (size > max_nucleus_) max_nucleus_ = size;
   }
 }
Writespron()
void Writespron (PhoneVector * pronptr, std::string * sylpron)
Convert phone array to a string based pronunciation for XML.
Definition at line 61 of file txpsylmax.cc.
References rnnlm::i.
Referenced by TxpSylmax::Init(), and TxpSyllabify::Process().
{
   int32 pos, newwrdb = -1, i;
   const char* bound;
   PhoneVector &pron = *pronptr;
   sylpron->clear();
   // if wrdb is at a cross word point move it back to the end of
   // the previous syllable
   for (pos = 0; pos < pron.size(); pos++) {
     if (pron[pos].wrdb == true) {
       if (pron[pos].cross_word == false) {
         newwrdb = pos;
         break;
       } else {
         // move word boundary back
         newwrdb = pos;
         while (newwrdb >=0 && !pron[newwrdb].sylb) {
           newwrdb--;
         }
         if (newwrdb >=0) pron[newwrdb].wrdb = true;
         pron[pos].wrdb = false;
         break;
       }
     }
   }
   // copy coda of previous word if held back
   // for cross word syllabification
   // if newwrdb == -1 there is no pron for this token anymore
   for (i = 0; i <= newwrdb; i++) {
     if (pron[i].sylb) bound = "|";
     else if (pron[i].codab)
       bound = "+";
     else
       bound = "_";
     *sylpron += pron[i].name + pron[i].stress + bound;
   }
   // remove processed phones from the front of the array
   pron.erase(pron.begin(), pron.begin() + newwrdb + 1);
 }
Member Data Documentation
max_nucleus_
int32 max_nucleus_ private
longest nucleus pattern
Definition at line 100 of file txpsylmax.h.
Referenced by TxpSylmax::FindNucleus(), and TxpSylmax::StartElement().
max_onset_
int32 max_onset_ private
longest onset pattern
Definition at line 98 of file txpsylmax.h.
Referenced by TxpSylmax::FindOnset(), and TxpSylmax::StartElement().
nuclei_
StringSet nuclei_ private
valid nucleus patterns
Definition at line 92 of file txpsylmax.h.
Referenced by TxpSylmax::FindNucleus(), and TxpSylmax::StartElement().
onsets_
StringSet onsets_ private
valid onset patterns
Definition at line 94 of file txpsylmax.h.
Referenced by TxpSylmax::FindOnset(), TxpSylmax::IsSyllabic(), and TxpSylmax::StartElement().
stress_
bool stress_ private
If stress true nucleus patterns must match correct stress.
Definition at line 96 of file txpsylmax.h.
Referenced by TxpSylmax::FindNucleus(), and TxpSylmax::StartElement().
syllabic_
StringSet syllabic_ private
phones which are syllabic
Definition at line 90 of file txpsylmax.h.
Referenced by TxpSylmax::IsSyllabic(), and TxpSylmax::StartElement().
The documentation for this class was generated from the following files:
idlaktxp/txpsylmax.h
idlaktxp/txpsylmax.cc