Kaldi: CompositeComponent Class Reference
CompositeComponent Class Reference
CompositeComponent is a component representing a sequence of [simple] components.
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual Component * Copy () const
Copies component (deep copy).
CompositeComponent ()
void Init (const std::vector< Component *> &components, int32 max_rows_process)
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
virtual void FreezeNaturalGradient (bool freeze)
virtual
int32 NumComponents () const
const Component * GetComponent (int32 i) const
Gets the ith component in this component.
void SetComponent (int32 i, Component *component)
Sets the ith component.
virtual ~CompositeComponent ()
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
MatrixStrideType GetStrideType (int32 i) const
bool IsUpdatable () const
Private Attributes
int32 max_rows_process_
std::vector< Component * > components_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Detailed Description
CompositeComponent is a component representing a sequence of [simple] components.
The config line would be something like the following (imagine this is all on one line):
component name=composite1 type=CompositeComponent max-rows-process=2048 num-components=3 \ component1='type=BlockAffineComponent input-dim=1000 output-dim=10000 num-blocks=100' \ component2='type=RectifiedLinearComponent dim=10000' \ component3='type=BlockAffineComponent input-dim=10000 output-dim=1000 num-blocks=100'
The reason you might want to use this component, instead of directly using the same sequence of components in the config file, is to save GPU memory (at the expense of more compute)– because doing it like this means we have to re-do parts of the forward pass in the backprop phase, but we avoid using much memory for very long (and you can make the memory usage very small by making max-rows-process small). We inherit from UpdatableComponent just in case one or more of the components in the sequence are updatable.
It is an error to nest a CompositeComponent inside a CompositeComponent. The same effect can be accomplished by specifying a smaller max-rows-process in a single CompositeComponent.
Definition at line 2489 of file nnet-simple-component.h.
Constructor & Destructor Documentation
CompositeComponent()
CompositeComponent () inline
Definition at line 2500 of file nnet-simple-component.h.
References PnormComponent::Init().
 { } // use Init() or InitFromConfig() to really initialize.
~CompositeComponent()
virtual ~CompositeComponent () inline virtual
Definition at line 2568 of file nnet-simple-component.h.
References kaldi::DeletePointers().
 { DeletePointers(&components_); }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 5332 of file nnet-simple-component.cc.
References Component::Add(), CompositeComponent::components_, rnnlm::i, and KALDI_ASSERT.
{
   const CompositeComponent *other = dynamic_cast<const CompositeComponent*>(
       &other_in);
   KALDI_ASSERT(other != NULL && other->components_.size() ==
                components_.size() && "Mismatching nnet topologies");
   for (size_t i = 0; i < components_.size(); i++)
     components_[i]->Add(alpha, *(other->components_[i]));
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 5187 of file nnet-simple-component.cc.
References MaxpoolingComponent::Backprop(), rnnlm::i, MaxpoolingComponent::InputDim(), KALDI_ASSERT, kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kBackpropNeedsOutput, kaldi::nnet3::kPropagateAdds, kaldi::kSetZero, kaldi::nnet3::kStoresStats, kaldi::kUndefined, kaldi::nnet3::kUpdatableComponent, kaldi::nnet3::kUsesMemo, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), MaxpoolingComponent::OutputDim(), MaxpoolingComponent::Properties(), and Component::StoreStats().
{
   KALDI_ASSERT(in_value.NumRows() == out_deriv.NumRows() &&
                in_value.NumCols() == InputDim() &&
                out_deriv.NumCols() == OutputDim());
   int32 num_rows = in_value.NumRows(),
       num_components = components_.size();
   if (max_rows_process_ > 0 && num_rows > max_rows_process_) {
     KALDI_ASSERT(max_rows_process_ > 0);
     // recurse and process smaller parts of the data, to save memory.
     for (int32 row_offset = 0; row_offset < num_rows;
          row_offset += max_rows_process_) {
       bool have_output_value = (out_value.NumRows() != 0);
       int32 this_num_rows = std::min<int32>(max_rows_process_,
                                             num_rows - row_offset);
       // out_value_part will only be used if out_value is nonempty; otherwise we
       // make it a submatrix of 'out_deriv' to avoid errors in the constructor.
       const CuSubMatrix<BaseFloat> out_value_part(have_output_value ? out_value : out_deriv,
                                                   row_offset, this_num_rows,
                                                   0, out_deriv.NumCols());
       // in_deriv_value_part will only be used if in_deriv != NULL; otherwise we
       // make it a submatrix of 'in_value' to avoid errors in the constructor.
       CuSubMatrix<BaseFloat> in_deriv_part(in_deriv != NULL ? *in_deriv : in_value,
                                             row_offset, this_num_rows,
                                             0, in_value.NumCols());
       CuSubMatrix<BaseFloat> in_value_part(in_value, row_offset, this_num_rows,
                                            0, in_value.NumCols());
       const CuSubMatrix<BaseFloat> out_deriv_part(out_deriv,
                                                   row_offset, this_num_rows,
                                                   0, out_deriv.NumCols());
       CuMatrix<BaseFloat>  empty_mat;
       this->Backprop(debug_info, NULL, in_value_part,
                      (have_output_value ? static_cast<const CuMatrixBase<BaseFloat>&>(out_value_part) :
                       static_cast<const CuMatrixBase<BaseFloat>&>(empty_mat)),
                      out_deriv_part, NULL, to_update,
                      in_deriv != NULL ? &in_deriv_part : NULL);
     }
     return;
   }
   // For now, assume all intermediate values and derivatives need to be
   // computed.  in_value and out_deriv will always be supplied.
   // intermediate_outputs[i] contains the output of component i.
   std::vector<CuMatrix<BaseFloat> > intermediate_outputs(num_components);
   // intermediate_derivs[i] contains the deriative at the output of component i.
   std::vector<CuMatrix<BaseFloat> > intermediate_derivs(num_components - 1);
   KALDI_ASSERT(memo == NULL);
   // note: only a very few components use memos, but we need to support them.
   std::vector<void*> memos(num_components, NULL);
   int32 num_components_to_propagate = num_components;
   if (!(components_[num_components - 1]->Properties() & kUsesMemo)) {
     // we only need to propagate the very last component if it uses a memo.
     num_components_to_propagate--;
     if (num_components > 1) {
       // skip the last-but-one component's propagate if the last component's
       // backprop doesn't need the input and the last-but-one component's
       // backprop doesn't need the output.  This is the lowest hanging fruit for
       // optimization; other propagates might also be skippable.
       int32 properties = components_[num_components - 2]->Properties(),
           next_properties = components_[num_components - 1]->Properties();
       if (!(properties & (kBackpropNeedsOutput || kUsesMemo)) &&
           !(next_properties & kBackpropNeedsInput)) {
         num_components_to_propagate--;
       }
     }
   }
   // Do the propagation again.
   for (int32 i = 0; i < num_components_to_propagate; i++) {
     MatrixResizeType resize_type =
         ((components_[i]->Properties() & kPropagateAdds) ?
          kSetZero : kUndefined);
     intermediate_outputs[i].Resize(num_rows, components_[i]->OutputDim(),
                                    resize_type, GetStrideType(i));
     memos[i] =
         components_[i]->Propagate(NULL,
                              (i == 0 ? in_value : intermediate_outputs[i-1]),
                               &(intermediate_outputs[i]));
   }
   for (int32 i = num_components - 1; i >= 0; i--) {
     const CuMatrixBase<BaseFloat> &this_in_value =
         (i == 0 ? in_value : intermediate_outputs[i-1]),
         &this_out_value =
         (i == num_components - 1 ? out_value : intermediate_outputs[i]);
     Component *component_to_update =
         (to_update == NULL ? NULL :
          dynamic_cast<CompositeComponent*>(to_update)->components_[i]);
     if (component_to_update != NULL  &&
         components_[i]->Properties() & kStoresStats)
       component_to_update->StoreStats(this_in_value, this_out_value, memos[i]);
     if (i > 0) {
       MatrixResizeType resize_type =
           ((components_[i]->Properties() & kBackpropAdds) ?
            kSetZero : kUndefined);
       intermediate_derivs[i-1].Resize(num_rows, components_[i]->InputDim(),
                                       resize_type, GetStrideType(i - 1));
     }
     // skip the first component's backprop if it's not updatable and in_deriv is
     // not requested.  Again, this is the lowest-hanging fruit to optimize.
     if (!(i == 0 && !(components_[0]->Properties() & kUpdatableComponent) &&
           in_deriv == NULL)) {
       components_[i]->Backprop(debug_info, NULL,
                 this_in_value, this_out_value,
                 (i + 1 == num_components ? out_deriv : intermediate_derivs[i]),
                 memos[i], component_to_update,
                 (i == 0 ? in_deriv : &(intermediate_derivs[i-1])));
     }
     if (memos[i] != NULL)
       components_[i]->DeleteMemo(memos[i]);
   }
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 5476 of file nnet-simple-component.cc.
References MaxpoolingComponent::Copy(), rnnlm::i, and CompositeComponent::Init().
{
   std::vector<Component*> components(components_.size());
   for (size_t i = 0; i < components_.size(); i++)
     components[i] = components_[i]->Copy();
   CompositeComponent *ans = new CompositeComponent();
   ans->Init(components, max_rows_process_);
   return ans;
 }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 5443 of file nnet-simple-component.cc.
References CompositeComponent::components_, UpdatableComponent::DotProduct(), rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kUpdatableComponent, and MaxpoolingComponent::Properties().
{
   const CompositeComponent *other = dynamic_cast<const CompositeComponent*>(
       &other_in);
   KALDI_ASSERT(other != NULL && other->components_.size() ==
                components_.size() && "Mismatching nnet topologies");
   BaseFloat ans = 0.0;
   for (size_t i = 0.0; i < components_.size(); i++) {
     if (components_[i]->Properties() & kUpdatableComponent) {
       UpdatableComponent *uc =
           dynamic_cast<UpdatableComponent*>(components_[i]);
       const UpdatableComponent *uc_other =
           dynamic_cast<UpdatableComponent*>(other->components_[i]);
       KALDI_ASSERT(uc != NULL && uc_other != NULL);
       ans += uc->DotProduct(*uc_other);
     }
   }
   return ans;
 }
FreezeNaturalGradient()
void FreezeNaturalGradient (bool freeze) virtual
virtual
Reimplemented from UpdatableComponent.
Definition at line 5464 of file nnet-simple-component.cc.
References UpdatableComponent::FreezeNaturalGradient(), rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kUpdatableComponent, and MaxpoolingComponent::Properties().
{
   for (size_t i = 0; i < components_.size(); i++) {
     if (components_[i]->Properties() & kUpdatableComponent) {
       UpdatableComponent *uc =
           dynamic_cast<UpdatableComponent*>(components_[i]);
       KALDI_ASSERT(uc != NULL);
       uc->FreezeNaturalGradient(freeze);
     }
   }
 }
GetComponent()
const Component * GetComponent (int32 i) const
Gets the ith component in this component.
The ordering is the same as in the config line. The caller does not own the received component.
Definition at line 5542 of file nnet-simple-component.cc.
References rnnlm::i, and KALDI_ASSERT.
Referenced by kaldi::nnet3::ConvertRepeatedToBlockAffine(), and kaldi::nnet3::UnitTestConvertRepeatedToBlockAffineComposite().
{
   KALDI_ASSERT(static_cast<size_t>(i) < components_.size());
   return components_[i];
 }
GetStrideType()
MatrixStrideType GetStrideType (int32 i) const inline private
Definition at line 5035 of file nnet-simple-component.cc.
References kaldi::kDefaultStride, kaldi::nnet3::kInputContiguous, kaldi::nnet3::kOutputContiguous, kaldi::kStrideEqualNumCols, and MaxpoolingComponent::Properties().
{
   int32 num_components = components_.size();
   if ((components_[i]->Properties() & kOutputContiguous) ||
       (i + 1 < num_components &&
        (components_[i + 1]->Properties() & kInputContiguous)))
     return kStrideEqualNumCols;
   else
     return kDefaultStride;
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 5314 of file nnet-simple-component.cc.
References rnnlm::i, MaxpoolingComponent::Info(), and MaxpoolingComponent::Type().
{
   std::ostringstream stream;
   stream << Type() << " ";
   for (size_t i = 0; i < components_.size(); i++) {
     if (i > 0) stream << ", ";
     stream << "sub-component" << (i+1) << " = { "
            << components_[i]->Info() << " }";
   }
   return stream.str();
 }
Init()
void Init (const std::vector< Component *> & components, int32 max_rows_process)
Definition at line 5094 of file nnet-simple-component.cc.
References kaldi::DeletePointers(), rnnlm::i, MaxpoolingComponent::InputDim(), KALDI_ASSERT, kaldi::nnet3::kSimpleComponent, MaxpoolingComponent::OutputDim(), and MaxpoolingComponent::Properties().
Referenced by CompositeComponent::Copy().
{
   DeletePointers(&components_);  // clean up.
   components_ = components;
   KALDI_ASSERT(!components.empty());
   max_rows_process_ = max_rows_process;
   for (size_t i = 0; i < components_.size(); i++) {
     // make sure all constituent components are simple.
     KALDI_ASSERT(components_[i]->Properties() & kSimpleComponent);
     if (i > 0) {
       // make sure all the internal dimensions match up.
       KALDI_ASSERT(components_[i]->InputDim() ==
                    components_[i-1]->OutputDim());
     }
   }
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 5487 of file nnet-simple-component.cc.
References kaldi::DeletePointers(), ConfigLine::FirstToken(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), rnnlm::i, Component::InitFromConfig(), KALDI_ERR, kaldi::nnet3::kRandomComponent, kaldi::nnet3::kSimpleComponent, Component::NewComponentOfType(), ConfigLine::ParseLine(), Component::Properties(), Component::Type(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   int32 max_rows_process = 4096, num_components = -1;
   cfl->GetValue("max-rows-process", &max_rows_process);
   if (!cfl->GetValue("num-components", &num_components) ||
       num_components < 1)
     KALDI_ERR << "Expected num-components to be defined in "
               << "CompositeComponent config line '" << cfl->WholeLine() << "'";
   std::vector<Component*> components;
   for (int32 i = 1; i <= num_components; i++) {
     std::ostringstream name_stream;
     name_stream << "component" << i;
     std::string component_config;
     if (!cfl->GetValue(name_stream.str(), &component_config)) {
       DeletePointers(&components);
       KALDI_ERR << "Expected '" << name_stream.str() << "' to be defined in "
                 << "CompositeComponent config line '" << cfl->WholeLine() << "'";
     }
     ConfigLine nested_line;
     // note: the nested line may not contain comments.
     std::string component_type;
     Component *this_component = NULL;
     if (!nested_line.ParseLine(component_config) ||
         !nested_line.GetValue("type", &component_type) ||
         !(this_component = NewComponentOfType(component_type)) ||
         nested_line.FirstToken() != "") {
       DeletePointers(&components);
       KALDI_ERR << "Could not parse config line for '" << name_stream.str()
                 << "(or undefined or bad component type [type=xxx]), in "
                 << "CompositeComponent config line '" << cfl->WholeLine() << "'";
     }
     if(this_component->Type() == "CompositeComponent") {
       DeletePointers(&components);
       delete this_component;
       // This is not allowed.  If memory is too much with just one
       // CompositeComponent, try decreasing max-rows-process instead.
       KALDI_ERR << "Found CompositeComponent nested within CompositeComponent."
                 << "Nested line: '" << nested_line.WholeLine() << "'\n"
                 << "Toplevel CompositeComponent line '" << cfl->WholeLine()
                 << "'";
     }
     this_component->InitFromConfig(&nested_line);
     int32 props = this_component->Properties();
     if ((props & kRandomComponent) != 0 ||
         (props & kSimpleComponent) == 0) {
       KALDI_ERR << "CompositeComponent contains disallowed component type: "
                 << nested_line.WholeLine();
     }
     components.push_back(this_component);
   }
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   this->Init(components, max_rows_process);
 }
InputDim()
int32 InputDim () const virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 5001 of file nnet-simple-component.cc.
References KALDI_ASSERT.
{
   KALDI_ASSERT(!components_.empty());
   return components_.front()->InputDim();
 };
IsUpdatable()
bool IsUpdatable () const private
Definition at line 4992 of file nnet-simple-component.cc.
References kaldi::nnet3::kUpdatableComponent.
{
   for (std::vector<Component*>::const_iterator iter = components_.begin(),
            end = components_.end(); iter != end; ++iter)
     if (((*iter)->Properties() & kUpdatableComponent) != 0)
       return true;
   return false;
 }
NumComponents()
int32 NumComponents () const inline
Definition at line 2558 of file nnet-simple-component.h.
References rnnlm::i.
Referenced by kaldi::nnet3::ConvertRepeatedToBlockAffine(), and kaldi::nnet3::UnitTestConvertRepeatedToBlockAffineComposite().
 { return components_.size(); }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 5395 of file nnet-simple-component.cc.
References rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kUpdatableComponent, UpdatableComponent::NumParameters(), and MaxpoolingComponent::Properties().
{
   KALDI_ASSERT(this->IsUpdatable());  // or should not be called.
   int32 ans = 0;
   for (size_t i = 0; i < components_.size(); i++) {
     if (components_[i]->Properties() & kUpdatableComponent) {
       UpdatableComponent *uc =
           dynamic_cast<UpdatableComponent*>(components_[i]);
       ans += uc->NumParameters();
     }
   }
   return ans;
 }
OutputDim()
int32 OutputDim () const virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 5007 of file nnet-simple-component.cc.
References KALDI_ASSERT.
{
   KALDI_ASSERT(!components_.empty());
   return components_.back()->OutputDim();
 };
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 5342 of file nnet-simple-component.cc.
References rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kUpdatableComponent, UpdatableComponent::PerturbParams(), and MaxpoolingComponent::Properties().
{
   KALDI_ASSERT(this->IsUpdatable());  // or should not be called.
   for (size_t i = 0; i < components_.size(); i++) {
     if (components_[i]->Properties() & kUpdatableComponent) {
       UpdatableComponent *uc =
           dynamic_cast<UpdatableComponent*>(components_[i]);
       uc->PerturbParams(stddev);
     }
   }
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 5047 of file nnet-simple-component.cc.
References rnnlm::i, MaxpoolingComponent::InputDim(), KALDI_ASSERT, kaldi::nnet3::kPropagateAdds, kaldi::kSetZero, kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), MaxpoolingComponent::OutputDim(), and MaxpoolingComponent::Propagate().
{
   KALDI_ASSERT(in.NumRows() == out->NumRows() && in.NumCols() == InputDim() &&
                out->NumCols() == OutputDim());
   int32 num_rows = in.NumRows(),
       num_components = components_.size();
   if (max_rows_process_ > 0 && num_rows > max_rows_process_) {
     // recurse and process smaller parts of the data, to save memory.
     for (int32 row_offset = 0; row_offset < num_rows;
          row_offset += max_rows_process_) {
       int32 this_num_rows = std::min<int32>(max_rows_process_,
                                             num_rows - row_offset);
       const CuSubMatrix<BaseFloat> in_part(in, row_offset, this_num_rows,
                                            0, in.NumCols());
       CuSubMatrix<BaseFloat> out_part(*out, row_offset, this_num_rows,
                                       0, out->NumCols());
       this->Propagate(NULL, in_part, &out_part);
     }
     return NULL;
   }
   std::vector<CuMatrix<BaseFloat> > intermediate_outputs(num_components - 1);
   for (int32 i = 0; i < num_components; i++) {
     if (i + 1 < num_components) {
       MatrixResizeType resize_type =
           ((components_[i]->Properties() & kPropagateAdds) ?
            kSetZero : kUndefined);
       intermediate_outputs[i].Resize(num_rows, components_[i]->OutputDim(),
                                      resize_type, GetStrideType(i));
     }
     const CuMatrixBase<BaseFloat> &this_in = (i == 0 ? in :
                                               intermediate_outputs[i-1]);
     CuMatrixBase<BaseFloat> *this_out = (i + 1 == num_components ?
                                          out : &(intermediate_outputs[i]));
     void *memo =  components_[i]->Propagate(NULL, this_in, this_out);
     // we'll re-do the forward propagation in the backprop, and we can
     // regenerate any memos there, so no need to keep them.
     if (memo != NULL)
       components_[i]->DeleteMemo(memo);
     if (i > 0)
       intermediate_outputs[i-1].Resize(0, 0);
   }
   return NULL;
 }
Properties()
int32 Properties () const virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 5013 of file nnet-simple-component.cc.
References KALDI_ASSERT, kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kBackpropNeedsOutput, kaldi::nnet3::kInputContiguous, kaldi::nnet3::kOutputContiguous, kaldi::nnet3::kPropagateAdds, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kStoresStats, and kaldi::nnet3::kUpdatableComponent.
{
   KALDI_ASSERT(!components_.empty());
   int32 last_component_properties = components_.back()->Properties(),
       first_component_properties = components_.front()->Properties();
   // We always assume backprop needs the input, as this would be necessary to
   // get the activations at intermediate layers, if these were not needed in
   // backprop, there would be no reason to use a CompositeComponent.
   int32 ans = kSimpleComponent | kBackpropNeedsInput |
       (last_component_properties &
        (kPropagateAdds|kBackpropNeedsOutput|kOutputContiguous)) |
        (first_component_properties &
         (kBackpropAdds|kInputContiguous)) |
        (IsUpdatable() ? kUpdatableComponent : 0);
   // note, we don't return the kStoresStats property because that function is
   // not implemented; instead, for efficiency, we call StoreStats() on any
   // sub-components as part of the backprop phase.
   if (last_component_properties & kStoresStats)
     ans |= kBackpropNeedsOutput;
   return ans;
 };
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 5113 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectToken(), rnnlm::i, KALDI_ERR, kaldi::ReadBasicType(), Component::ReadNew(), and kaldi::ReadToken().
{
   // Because we didn't previously write out the learning rate,
   // we need some temporary code.
   int32 max_rows_process;
   if (false) {
     ReadUpdatableCommon(is, binary);
     ExpectToken(is, binary, "<MaxRowsProcess>");
     ReadBasicType(is, binary, &max_rows_process);
   } else {  // temporary code.
     std::string token;
     ReadToken(is, binary, &token);
     if (token == "<CompositeComponent>") {
       // if the first token is the opening tag, then
       // ignore it and get the next tag.
       ReadToken(is, binary, &token);
     }
     if (token == "<LearningRateFactor>") {
       ReadBasicType(is, binary, &learning_rate_factor_);
       ReadToken(is, binary, &token);
     } else {
       learning_rate_factor_ = 1.0;
     }
     if (token == "<IsGradient>") {
       ReadBasicType(is, binary, &is_gradient_);
       ReadToken(is, binary, &token);
     } else {
       is_gradient_ = false;
     }
     if (token == "<LearningRate>") {
       ReadBasicType(is, binary, &learning_rate_);
       ReadToken(is, binary, &token);
     }
     if (token != "<MaxRowsProcess>") {
       KALDI_ERR << "Expected token <MaxRowsProcess>, got "
                 << token;
     }
     ReadBasicType(is, binary, &max_rows_process);
   }
   ExpectToken(is, binary, "<NumComponents>");
   int32 num_components;
   ReadBasicType(is, binary, &num_components); // Read dimension.
   if (num_components < 0 || num_components > 100000)
     KALDI_ERR << "Bad num-components";
   std::vector<Component*> components(num_components);
   for (int32 i = 0; i < num_components; i++)
     components[i] = ReadNew(is, binary);
   Init(components, max_rows_process);
   ExpectToken(is, binary, "</CompositeComponent>");
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 5326 of file nnet-simple-component.cc.
References rnnlm::i, and Component::Scale().
{
   for (size_t i = 0; i < components_.size(); i++)
     components_[i]->Scale(scale);
 }
SetActualLearningRate()
void SetActualLearningRate (BaseFloat lrate) virtual
Sets the learning rate directly, bypassing learning_rate_factor_.
Reimplemented from UpdatableComponent.
Definition at line 5369 of file nnet-simple-component.cc.
References rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kUpdatableComponent, MaxpoolingComponent::Properties(), and UpdatableComponent::SetActualLearningRate().
{
   KALDI_ASSERT(this->IsUpdatable());  // or should not be called.
   UpdatableComponent::SetActualLearningRate(lrate);
   for (size_t i = 0; i < components_.size(); i++) {
     if (components_[i]->Properties() & kUpdatableComponent) {
       UpdatableComponent *uc =
           dynamic_cast<UpdatableComponent*>(components_[i]);
       uc->SetActualLearningRate(lrate);
     }
   }
 }
SetAsGradient()
void SetAsGradient () virtual
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
Reimplemented from UpdatableComponent.
Definition at line 5382 of file nnet-simple-component.cc.
References rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kUpdatableComponent, MaxpoolingComponent::Properties(), and UpdatableComponent::SetAsGradient().
{
   KALDI_ASSERT(this->IsUpdatable());  // or should not be called.
   UpdatableComponent::SetAsGradient();
   for (size_t i = 0; i < components_.size(); i++) {
     if (components_[i]->Properties() & kUpdatableComponent) {
       UpdatableComponent *uc =
           dynamic_cast<UpdatableComponent*>(components_[i]);
       uc->SetAsGradient();
     }
   }
 }
SetComponent()
void SetComponent (int32 i, Component * component)
Sets the ith component.
After this call, CompositeComponent owns the reference to the argument component. Frees the previous ith component.
Definition at line 5547 of file nnet-simple-component.cc.
References rnnlm::i, and KALDI_ASSERT.
Referenced by kaldi::nnet3::ConvertRepeatedToBlockAffine().
{
   KALDI_ASSERT(static_cast<size_t>(i) < components_.size());
   delete components_[i];
   components_[i] = component;
 }
SetUnderlyingLearningRate()
void SetUnderlyingLearningRate (BaseFloat lrate) virtual
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
Reimplemented from UpdatableComponent.
Definition at line 5353 of file nnet-simple-component.cc.
References rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kUpdatableComponent, MaxpoolingComponent::Properties(), and UpdatableComponent::SetUnderlyingLearningRate().
{
   KALDI_ASSERT(this->IsUpdatable());  // or should not be called.
   UpdatableComponent::SetUnderlyingLearningRate(lrate);
   // apply any learning-rate-factor that's set at this level (ill-advised, but
   // we'll do it.)
   BaseFloat effective_lrate = LearningRate();
   for (size_t i = 0; i < components_.size(); i++) {
     if (components_[i]->Properties() & kUpdatableComponent) {
       UpdatableComponent *uc =
           dynamic_cast<UpdatableComponent*>(components_[i]);
       uc->SetUnderlyingLearningRate(effective_lrate);
     }
   }
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 2506 of file nnet-simple-component.h.
References Component::Add(), PnormComponent::Backprop(), kaldi::nnet3::DotProduct(), kaldi::nnet3::FreezeNaturalGradient(), kaldi::nnet3::NumParameters(), kaldi::nnet3::PerturbParams(), PnormComponent::Propagate(), PnormComponent::Properties(), PnormComponent::Read(), Component::Scale(), PnormComponent::Write(), and Component::ZeroStats().
 { return "CompositeComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 5426 of file nnet-simple-component.cc.
References VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kUpdatableComponent, UpdatableComponent::NumParameters(), MaxpoolingComponent::Properties(), and UpdatableComponent::UnVectorize().
{
   int32 cur_offset = 0;
   KALDI_ASSERT(this->IsUpdatable());  // or should not be called.
   for (size_t i = 0; i < components_.size(); i++) {
     if (components_[i]->Properties() & kUpdatableComponent) {
       UpdatableComponent *uc =
           dynamic_cast<UpdatableComponent*>(components_[i]);
       int32 this_size = uc->NumParameters();
       SubVector<BaseFloat> params_range(params, cur_offset, this_size);
       uc->UnVectorize(params_range);
       cur_offset += this_size;
     }
   }
   KALDI_ASSERT(cur_offset == params.Dim());
 }
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 5409 of file nnet-simple-component.cc.
References VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, kaldi::nnet3::kUpdatableComponent, UpdatableComponent::NumParameters(), MaxpoolingComponent::Properties(), and UpdatableComponent::Vectorize().
{
   int32 cur_offset = 0;
   KALDI_ASSERT(this->IsUpdatable());  // or should not be called.
   for (size_t i = 0; i < components_.size(); i++) {
     if (components_[i]->Properties() & kUpdatableComponent) {
       UpdatableComponent *uc =
           dynamic_cast<UpdatableComponent*>(components_[i]);
       int32 this_size = uc->NumParameters();
       SubVector<BaseFloat> params_range(*params, cur_offset, this_size);
       uc->Vectorize(&params_range);
       cur_offset += this_size;
     }
   }
   KALDI_ASSERT(cur_offset == params->Dim());
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 5173 of file nnet-simple-component.cc.
References rnnlm::i, MaxpoolingComponent::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate.
   WriteToken(os, binary, "<MaxRowsProcess>");
   WriteBasicType(os, binary, max_rows_process_);
   WriteToken(os, binary, "<NumComponents>");
   int32 num_components = components_.size();
   WriteBasicType(os, binary, num_components);
   for (int32 i = 0; i < num_components; i++)
     components_[i]->Write(os, binary);
   WriteToken(os, binary, "</CompositeComponent>");
 }
ZeroStats()
void ZeroStats () virtual
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Other components that store other types of statistics (e.g. regarding gradient clipping) should implement ZeroStats() also.
Reimplemented from Component.
Definition at line 5164 of file nnet-simple-component.cc.
References rnnlm::i, and Component::ZeroStats().
{
   // we call ZeroStats() on all components without checking their flags; this
   // will do nothing if the component doesn't store stats.  (components like
   // ReLU and sigmoid and tanh store stats on activations).
   for (size_t i = 0; i < components_.size(); i++)
    components_[i]->ZeroStats();
 }
Member Data Documentation
components_
std::vector<Component*> components_ private
Definition at line 2580 of file nnet-simple-component.h.
Referenced by CompositeComponent::Add(), and CompositeComponent::DotProduct().
max_rows_process_
int32 max_rows_process_ private
Definition at line 2579 of file nnet-simple-component.h.
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc