Kaldi: CuPackedMatrix< Real > Class Template Reference
CuPackedMatrix< Real > Class Template Reference
Matrix for CUDA computing.
#include <matrix-common.h>
Public Member Functions
CuPackedMatrix ()
CuPackedMatrix (MatrixIndexT r, MatrixResizeType resize_type=kSetZero)
CuPackedMatrix (const PackedMatrix< Real > &orig)
CuPackedMatrix (const CuPackedMatrix< Real > &orig)
void SetZero ()
void SetUnit ()
< Set to zero
void SetRandn ()
< Set to unit matrix.
void SetDiag (Real alpha)
< Set to random values of a normal distribution
void AddToDiag (Real r)
< Set the diagonal value to alpha
void Scale (Real alpha)
void ScaleDiag (Real alpha)
Real Trace () const
~CuPackedMatrix ()
void Resize (MatrixIndexT nRows, MatrixResizeType resize_type=kSetZero)
Set packed matrix to a specified size (can be zero).
void CopyFromPacked (const CuPackedMatrix< Real > &src)
void CopyFromPacked (const PackedMatrix< Real > &src)
void CopyToPacked (PackedMatrix< Real > *dst) const
void Read (std::istream &in, bool binary)
void Write (std::ostream &out, bool binary) const
void Destroy ()
void Swap (CuPackedMatrix< Real > *other)
Swaps the contents of *this and *other. Shallow swap.
void Swap (PackedMatrix< Real > *other)
Swaps the contents of *this and *other.
Real * Data ()
const Real * Data () const
Real operator() (MatrixIndexT r, MatrixIndexT c) const
MatrixIndexT NumRows () const
MatrixIndexT NumCols () const
size_t SizeInBytes () const
Returns size in bytes of the data held by the matrix.
Protected Member Functions
const PackedMatrix< Real > & Mat () const
PackedMatrix< Real > & Mat ()
void AddPacked (const Real alpha, const CuPackedMatrix< Real > &M)
Protected Attributes
Real * data_
MatrixIndexT num_rows_
Private Member Functions
PackedMatrix< Real > & operator= (const PackedMatrix< Real > &other)
Friends
class CuMatrixBase< Real >
class CuVectorBase< Real >
class CuSubMatrix< Real >
class CuRand< Real >
Detailed Description
template<typename Real>
class kaldi::CuPackedMatrix< Real >
Matrix for CUDA computing.
This is a base class for packed triangular and symmetric matrices. Does the computation on the CUDA card when CUDA is compiled in and we have a suitable GPU (CuDevice::Instantiate().Enabled() == true); otherwise, does it on the CPU.Packed CUDA matrix: base class for triangular and symmetric matrices on a GPU card.
Definition at line 75 of file matrix-common.h.
Constructor & Destructor Documentation
CuPackedMatrix() [1/4]
CuPackedMatrix () inline
Definition at line 60 of file cu-packed-matrix.h.
 : data_(NULL), num_rows_(0) {}
CuPackedMatrix() [2/4]
CuPackedMatrix (MatrixIndexT r, MatrixResizeType resize_type = kSetZero) inline explicit
Definition at line 62 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::Resize().
                                                                   :
       data_(NULL), num_rows_(0) {  Resize(r, resize_type);  }
CuPackedMatrix() [3/4]
CuPackedMatrix (const PackedMatrix< Real > & orig) inline explicit
Definition at line 66 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::CopyFromPacked(), kaldi::kUndefined, PackedMatrix< Real >::num_rows_, and CuPackedMatrix< Real >::Resize().
                                                           : data_(NULL), num_rows_(0) {
     Resize(orig.num_rows_, kUndefined);
     CopyFromPacked(orig);
   }
CuPackedMatrix() [4/4]
CuPackedMatrix (const CuPackedMatrix< Real > & orig) inline explicit
Definition at line 71 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::AddToDiag(), CuPackedMatrix< Real >::CopyFromPacked(), kaldi::kUndefined, CuPackedMatrix< Real >::Resize(), CuPackedMatrix< Real >::Scale(), CuPackedMatrix< Real >::ScaleDiag(), CuPackedMatrix< Real >::SetDiag(), CuPackedMatrix< Real >::SetRandn(), CuPackedMatrix< Real >::SetUnit(), CuPackedMatrix< Real >::SetZero(), and CuPackedMatrix< Real >::Trace().
                                                             : data_(NULL), num_rows_(0) {
     Resize(orig.NumRows(), kUndefined);
     CopyFromPacked(orig);
   }
~CuPackedMatrix()
~CuPackedMatrix () inline
Definition at line 86 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::CopyFromPacked(), CuPackedMatrix< Real >::CopyToPacked(), CuPackedMatrix< Real >::Destroy(), kaldi::kSetZero, CuPackedMatrix< Real >::Read(), CuPackedMatrix< Real >::Resize(), CuPackedMatrix< Real >::Swap(), and CuPackedMatrix< Real >::Write().
 { Destroy(); }
Member Function Documentation
AddPacked()
void AddPacked (const Real alpha, const CuPackedMatrix< Real > & M) protected
Definition at line 329 of file cu-packed-matrix.cc.
References CuPackedMatrix< Real >::Data(), data_, KALDI_ASSERT, CuPackedMatrix< Real >::Mat(), and CuPackedMatrix< Real >::NumRows().
Referenced by CuSpMatrix< Real >::AddSp().
{
   KALDI_ASSERT(num_rows_ == M.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return;
     CuTimer tim;
     size_t nr = num_rows_,
         sz = (nr * (nr + 1)) / 2;
     cublas_axpy(GetCublasHandle(), sz, alpha, M.Data(), 1, data_, 1);
     CuDevice::Instantiate().AccuProfile("CuPackedMatrix::AddPacked", tim);
   } else
 #endif
   {
     Mat().AddPacked(alpha, M.Mat());
   }
 }
AddToDiag()
void AddToDiag (Real r)
< Set the diagonal value to alpha
Add this quantity to the diagonal of the matrix.
Definition at line 347 of file cu-packed-matrix.cc.
References CU1DBLOCK, and data_.
Referenced by CuPackedMatrix< Real >::CuPackedMatrix(), kaldi::UnitTestCuPackedMatrixAddToDiag(), kaldi::UnitTestCuSpMatrixAddToDiag(), kaldi::UnitTestCuSpMatrixInvert(), and kaldi::UnitTestCuSpMatrixSetUnit().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return;
     CuTimer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(NumRows(),CU1DBLOCK));
     cuda_add_diag_packed(dimGrid,dimBlock,data_,r,num_rows_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuPackedMatrix::AddToDiag", tim);
   } else
 #endif
   {
     // TODO
     Mat().AddToDiag(r);
   }
 }
CopyFromPacked() [1/2]
void CopyFromPacked (const CuPackedMatrix< Real > & src)
Definition at line 137 of file cu-packed-matrix.cc.
References data_, CuPackedMatrix< Real >::data_, KALDI_ASSERT, CuPackedMatrix< Real >::Mat(), and CuPackedMatrix< Real >::NumRows().
Referenced by CuSpMatrix< Real >::CopyFromSp(), CuTpMatrix< Real >::CopyFromTp(), CuPackedMatrix< Real >::CuPackedMatrix(), CuTpMatrix< Real >::operator=(), kaldi::UnitTestCuPackedMatrixCopy(), and CuPackedMatrix< Real >::~CuPackedMatrix().
{
   KALDI_ASSERT(src.NumRows() == num_rows_);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return; // Nothing to do.
     CuTimer tim;
     size_t nr = static_cast<size_t>(num_rows_),
         num_bytes = ((nr * (nr+1)) / 2) * sizeof(Real);
     CU_SAFE_CALL(cudaMemcpy(data_, src.data_, num_bytes,
                             cudaMemcpyDeviceToDevice));
     CuDevice::Instantiate().AccuProfile("CuPackedMatrix::CopyFromPacked1",
                                         tim);
   } else
 #endif
   {
     Mat().CopyFromPacked(src.Mat());
   }
 }
CopyFromPacked() [2/2]
void CopyFromPacked (const PackedMatrix< Real > & src)
Definition at line 158 of file cu-packed-matrix.cc.
References data_, PackedMatrix< Real >::data_, KALDI_ASSERT, PackedMatrix< Real >::NumRows(), and PackedMatrix< Real >::SizeInBytes().
{
   KALDI_ASSERT(src.NumRows() == num_rows_);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return; // Nothing to do.
     CuTimer tim;
     CU_SAFE_CALL(cudaMemcpy(data_, src.data_, src.SizeInBytes(),
                             cudaMemcpyHostToDevice));
     CuDevice::Instantiate().AccuProfile("CuPackedMatrix::CopyFromPacked2", tim);
   } else
 #endif
   {
     Mat().CopyFromPacked(src);
     //memcpy(data_, src.Data(), SizeInBytes());
   }
 }
CopyToPacked()
void CopyToPacked (PackedMatrix< Real > * dst) const
Definition at line 176 of file cu-packed-matrix.cc.
References PackedMatrix< Real >::CopyFromPacked(), data_, PackedMatrix< Real >::data_, KALDI_ASSERT, and PackedMatrix< Real >::NumRows().
Referenced by TpMatrix< float >::CopyFromMat(), CuSpMatrix< Real >::CopyToSp(), kaldi::UnitTestCuPackedMatrixCopy(), and CuPackedMatrix< Real >::~CuPackedMatrix().
{
   KALDI_ASSERT(dst->NumRows() == NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return; // Nothing to do.
     CuTimer tim;
     size_t nr = static_cast<size_t>(num_rows_),
       num_bytes = ((nr * (nr+1)) / 2) * sizeof(Real);
     CU_SAFE_CALL(cudaMemcpy(dst->data_, data_, num_bytes,
                             cudaMemcpyDeviceToHost));
     CuDevice::Instantiate().AccuProfile("CuPackedMatrix::CopyToPackedD2H", tim);
   } else
 #endif
   {
     //memcpy(data_, dst->Data(), SizeInBytes());
     dst->CopyFromPacked(Mat());
   }
 }
Data() [1/2]
Real* Data () inline
Definition at line 113 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::data_.
Referenced by CuPackedMatrix< Real >::AddPacked(), CuVectorBase< float >::AddSpVec(), CuVectorBase< float >::CopyDiagFromPacked(), CuMatrixBase< float >::CopyFromSp(), CuMatrixBase< float >::CopyFromTp(), CuVectorBase< float >::MulTp(), and kaldi::TraceSpSp().
 { return data_; }
Data() [2/2]
const Real* Data () const inline
Definition at line 114 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::data_.
 { return data_; }
Destroy()
void Destroy ()
Definition at line 85 of file cu-packed-matrix.cc.
References data_, and KALDI_MEMALIGN_FREE.
Referenced by CuPackedMatrix< Real >::~CuPackedMatrix().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (this->data_ != NULL) {
       CuDevice::Instantiate().Free(this->data_);
     }
   } else
 #endif
   {
     if (this->data_ != NULL) KALDI_MEMALIGN_FREE(this->data_);
   }
   this->data_ = NULL;
   this->num_rows_ = 0;
 }
Mat() [1/2]
const PackedMatrix<Real>& Mat () const inline protected
Definition at line 148 of file cu-packed-matrix.h.
Referenced by CuPackedMatrix< Real >::AddPacked(), CuVectorBase< float >::CopyDiagFromPacked(), and CuPackedMatrix< Real >::CopyFromPacked().
{
     return *(reinterpret_cast<const PackedMatrix<Real>* >(this));
   }
Mat() [2/2]
PackedMatrix<Real>& Mat () inline protected
Definition at line 151 of file cu-packed-matrix.h.
{
     return *(reinterpret_cast<PackedMatrix<Real>* >(this));
   }
NumCols()
MatrixIndexT NumCols () const inline
Definition at line 134 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::num_rows_.
Referenced by CuVectorBase< float >::AddSpVec(), and CuMatrix< float >::CuMatrix().
 { return num_rows_; }
NumRows()
MatrixIndexT NumRows () const inline
Definition at line 133 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::num_rows_.
Referenced by CuPackedMatrix< Real >::AddPacked(), CuVectorBase< float >::AddSpVec(), CuVectorBase< float >::AddTpVec(), CuSpMatrix< Real >::ApproxEqual(), kaldi::AssertEqual(), CuVectorBase< float >::CopyDiagFromPacked(), CuPackedMatrix< Real >::CopyFromPacked(), CuMatrixBase< float >::CopyFromSp(), CuMatrixBase< float >::CopyFromTp(), CuMatrix< float >::CuMatrix(), CuTpMatrix< Real >::Invert(), CuVectorBase< float >::MulTp(), CuSpMatrix< Real >::operator=(), CuTpMatrix< Real >::operator=(), TpMatrix< float >::TpMatrix(), kaldi::TraceSpSp(), and kaldi::UnitTestCuPackedMatrixSetUnit().
 { return num_rows_; }
operator()()
Real operator() (MatrixIndexT r, MatrixIndexT c) const inline
Definition at line 116 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::data_, KALDI_ASSERT, CuPackedMatrix< Real >::num_rows_, and kaldi::swap().
{
     if (static_cast<UnsignedMatrixIndexT>(c) >
         static_cast<UnsignedMatrixIndexT>(r))
       std::swap(c, r);
     KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(r) <
                  static_cast<UnsignedMatrixIndexT>(this->num_rows_));
 #if HAVE_CUDA == 1
     if (CuDevice::Instantiate().Enabled()) {
       Real value;
       CU_SAFE_CALL(cudaMemcpy(&value, this->data_ + (r * (r+1)) / 2 + c,
                               sizeof(Real), cudaMemcpyDeviceToHost));
       return value;
     } else
 #endif
     return this->data_[(r * (r+1)) / 2 + c];
   }
operator=()
PackedMatrix<Real>& operator= (const PackedMatrix< Real > & other) private
Read()
void Read (std::istream & in, bool binary)
Definition at line 228 of file cu-packed-matrix.cc.
References PackedMatrix< Real >::Read().
Referenced by kaldi::UnitTestCuSpMatrixIO(), kaldi::UnitTestCuTpMatrixIO(), and CuPackedMatrix< Real >::~CuPackedMatrix().
{
   PackedMatrix<Real> temp;
   temp.Read(is, binary);
   Destroy();
   Swap(&temp);
 }
Resize()
void Resize (MatrixIndexT nRows, MatrixResizeType resize_type = kSetZero)
Set packed matrix to a specified size (can be zero).
The value of the new data depends on resize_type: -if kSetZero, the new data will be zero -if kUndefined, the new data will be undefined -if kCopyData, the new data will be the same as the old data in any shared positions, and zero elsewhere. This function takes time proportional to the number of data elements.
Definition at line 40 of file cu-packed-matrix.cc.
References data_, KALDI_ASSERT, kaldi::kSetZero, and kaldi::kUndefined.
Referenced by CuPackedMatrix< Real >::CuPackedMatrix(), CuTpMatrix< Real >::operator=(), CuSpMatrix< Real >::Resize(), TpMatrix< float >::TpMatrix(), and CuPackedMatrix< Real >::~CuPackedMatrix().
{
   // This code does not currently support the other resize_type options.
   KALDI_ASSERT(resize_type == kSetZero || resize_type == kUndefined);
   if (this->num_rows_ == rows) {
     if (resize_type == kSetZero) this->SetZero();
     return;
   }
   if (this->num_rows_ != 0)
     this->Destroy();
   if (rows == 0) return;
 #if HAVE_CUDA == 1
   CuDevice &device = CuDevice::Instantiate();
   if (device.Enabled()) {
     CuTimer tim;
     this->num_rows_ = rows;
     size_t nr = static_cast<size_t>(num_rows_),
         num_bytes = ((nr * (nr+1)) / 2) * sizeof(Real);
     this->data_ = static_cast<Real*>(device.Malloc(num_bytes));
     if (resize_type == kSetZero) this->SetZero();
     device.AccuProfile("CuPackedMatrix::Resize", tim);
   } else
 #endif
   { // Let the initializer of SpMatrix<Real> handle the allocation,
     // and then just do Swap which will switch the pointers.
     // This wastes a few instructions but is simple to code.
     SpMatrix<Real> mat(rows, resize_type);
     this->Swap(&mat);
   }
 }
Scale()
void Scale (Real alpha)
Definition at line 295 of file cu-packed-matrix.cc.
References data_.
Referenced by CuPackedMatrix< Real >::CuPackedMatrix(), and kaldi::UnitTestCuPackedMatrixScale().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     size_t nr = static_cast<size_t>(num_rows_),
         num_elements = ((nr * (nr+1)) / 2);
     CUBLAS_SAFE_CALL(cublas_scal(GetCublasHandle(), num_elements, alpha, data_, 1));
     CuDevice::Instantiate().AccuProfile("CuPackedMatrix::Scale", tim);
   } else
 #endif
   {
     Mat().Scale(alpha);
   }
 }
ScaleDiag()
void ScaleDiag (Real alpha)
Definition at line 312 of file cu-packed-matrix.cc.
References CU1DBLOCK, and data_.
Referenced by CuPackedMatrix< Real >::CuPackedMatrix(), kaldi::UnitTestCuPackedMatrixScaleDiag(), and kaldi::nnet2::UnitTestPreconditionDirections().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(NumRows(),CU1DBLOCK));
     cuda_scale_diag_packed(dimGrid,dimBlock,data_,alpha,num_rows_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuPackedMatrix::ScaleDiag", tim);
   } else
 #endif
   {
     Mat().ScaleDiag(alpha);
   }
 }
SetDiag()
void SetDiag (Real alpha)
< Set to random values of a normal distribution
Definition at line 277 of file cu-packed-matrix.cc.
References CU1DBLOCK, and data_.
Referenced by CuPackedMatrix< Real >::CuPackedMatrix().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return;
     CuTimer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(NumRows(),CU1DBLOCK));
     cuda_set_diag_packed(dimGrid,dimBlock,data_,alpha,num_rows_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuPackedMatrix::SetDiag", tim);
   } else
 #endif
   {
     Mat().SetDiag(alpha);
   }
 }
SetRandn()
void SetRandn ()
< Set to unit matrix.
Definition at line 75 of file cu-packed-matrix.cc.
References data_, and CuRand< Real >::RandGaussian().
Referenced by CuPackedMatrix< Real >::CuPackedMatrix(), kaldi::CuVectorUnitTestAddSpVec(), kaldi::CuVectorUnitTestCopyDiagFromPacked(), kaldi::TestCuMatrixCopyFromSp(), kaldi::TestCuMatrixCopyFromTp(), kaldi::UnitTestCuSpMatrixInvert(), kaldi::UnitTestCuSpMatrixIO(), kaldi::UnitTestCuSpMatrixSetUnit(), and kaldi::UnitTestCuTpMatrixIO().
{
   if (num_rows_ != 0) {
     MatrixIndexT size = num_rows_ * (num_rows_ + 1) / 2;
     CuSubVector<Real> tmp(data_, size);
     CuRand<Real> rand;
     rand.RandGaussian(&tmp);
   }
 }
SetUnit()
void SetUnit ()
< Set to zero
Definition at line 366 of file cu-packed-matrix.cc.
Referenced by CuPackedMatrix< Real >::CuPackedMatrix(), kaldi::UnitTestCuPackedMatrixSetUnit(), and kaldi::nnet2::UnitTestPreconditionDirections().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     this->SetZero();
     this->SetDiag(1.0);
   } else
 #endif
   {
     Mat().SetUnit();
   }
 }
SetZero()
void SetZero ()
Definition at line 243 of file cu-packed-matrix.cc.
References data_.
Referenced by CuPackedMatrix< Real >::CuPackedMatrix(), and kaldi::UnitTestCuSpMatrixSetUnit().
{
   #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuTimer tim;
     size_t nr = static_cast<size_t>(num_rows_),
       num_bytes = ((nr * (nr+1)) / 2) * sizeof(Real);
     CU_SAFE_CALL(cudaMemset(reinterpret_cast<void*>(this->data_), 0, num_bytes));
     CuDevice::Instantiate().AccuProfile("CuPackedMatrix::SetZero", tim);
   } else
   #endif
   {
     Mat().SetZero();
   }
 }
SizeInBytes()
size_t SizeInBytes () const inline
Returns size in bytes of the data held by the matrix.
Definition at line 137 of file cu-packed-matrix.h.
References CuPackedMatrix< Real >::num_rows_.
{
     size_t nr = static_cast<size_t>(num_rows_),
       num_bytes = ((nr * (nr+1)) / 2) * sizeof(Real);
     return num_bytes;
   }
Swap() [1/2]
void Swap (CuPackedMatrix< Real > * other)
Swaps the contents of *this and *other. Shallow swap.
Referenced by CuPackedMatrix< Real >::~CuPackedMatrix().
Swap() [2/2]
void Swap (PackedMatrix< Real > * other)
Swaps the contents of *this and *other.
Definition at line 101 of file cu-packed-matrix.cc.
References PackedMatrix< Real >::data_, kaldi::kUndefined, PackedMatrix< Real >::num_rows_, PackedMatrix< Real >::Resize(), PackedMatrix< Real >::Swap(), and kaldi::swap().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (this->num_rows_ == 0) {
       if (mat->num_rows_ != 0) {
         // *this is empty, but mat is nonempty.
         Resize(mat->num_rows_, kUndefined);
         CopyFromPacked(*mat);
         mat->Resize(0);
       }
       // else both are empty.
     } else { // *this is nonempty.
       if (mat->num_rows_ != 0) {
         // Both *this and *mat are nonempty.  Recurse to simpler cases.
         // this could be done more efficiently in the case where
         // the size does not change.
         PackedMatrix<Real> temp;
         this->Swap(&temp); // now temp is full, *this is empty.
         mat->Swap(&temp); // now mat has data from *this, temp has
         // data from mat.
         this->Swap(&temp); // copy data in mat to *this, which is now empty.
       } else { // *this is full but *mat is empty.
         mat->Resize(this->num_rows_, kUndefined);
         this->CopyToPacked(mat);
         this->Destroy();
       }
     }
   } else
 #endif
   {
     std::swap(mat->data_, this->data_);
     std::swap(mat->num_rows_, this->num_rows_);
   }
 }
Trace()
Real Trace () const
Definition at line 260 of file cu-packed-matrix.cc.
References CuVectorBase< Real >::CopyDiagFromPacked(), kaldi::kUndefined, and CuVectorBase< Real >::Sum().
Referenced by CuPackedMatrix< Real >::CuPackedMatrix(), kaldi::UnitTestCuPackedMatrixTrace(), kaldi::UnitTestCuSpMatrixInvert(), and kaldi::UnitTestTrace().
{
   Real result = 0.0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return 0.0;
     CuVector<Real> tmp(num_rows_, kUndefined);
     tmp.CopyDiagFromPacked(*this);
     return tmp.Sum();
   } else
 #endif
   {
     result = Mat().Trace();
   }
   return result;
 }
Write()
void Write (std::ostream & out, bool binary) const
Definition at line 236 of file cu-packed-matrix.cc.
References kaldi::kUndefined, and PackedMatrix< Real >::Write().
Referenced by kaldi::UnitTestCuSpMatrixIO(), kaldi::UnitTestCuTpMatrixIO(), and CuPackedMatrix< Real >::~CuPackedMatrix().
{
   PackedMatrix<Real> temp(this->num_rows_, kUndefined);
   this->CopyToPacked(&temp);
   temp.Write(os, binary);
 }
Friends And Related Function Documentation
CuMatrixBase< Real >
friend class CuMatrixBase< Real > friend
Definition at line 55 of file cu-packed-matrix.h.
CuRand< Real >
friend class CuRand< Real > friend
Definition at line 58 of file cu-packed-matrix.h.
CuSubMatrix< Real >
friend class CuSubMatrix< Real > friend
Definition at line 57 of file cu-packed-matrix.h.
CuVectorBase< Real >
friend class CuVectorBase< Real > friend
Definition at line 56 of file cu-packed-matrix.h.
Member Data Documentation
data_
Real* data_ protected
Definition at line 158 of file cu-packed-matrix.h.
Referenced by CuTpMatrix< Real >::CopyFromMat(), CuPackedMatrix< Real >::CopyFromPacked(), CuPackedMatrix< Real >::Data(), CuSpMatrix< Real >::operator()(), and CuPackedMatrix< Real >::operator()().
num_rows_
MatrixIndexT num_rows_ protected
Definition at line 159 of file cu-packed-matrix.h.
Referenced by CuTpMatrix< Real >::CopyFromMat(), CuTpMatrix< Real >::Invert(), CuPackedMatrix< Real >::NumCols(), CuPackedMatrix< Real >::NumRows(), CuSpMatrix< Real >::operator()(), CuPackedMatrix< Real >::operator()(), and CuPackedMatrix< Real >::SizeInBytes().
The documentation for this class was generated from the following files:
matrix/matrix-common.h
cudamatrix/cu-packed-matrix.h
cudamatrix/cu-packed-matrix.cc