Kaldi: FisherComputationClass Class Reference
FisherComputationClass Class Reference
Public Member Functions
FisherComputationClass (const Nnet &nnet, const std::vector< Nnet > &nnets, const std::vector< NnetExample > &egs, int32 minibatch_size, SpMatrix< double > *scatter)
FisherComputationClass (const FisherComputationClass &other)
void operator() ()
~FisherComputationClass ()
Public Member Functions inherited from MultiThreadable
virtual ~MultiThreadable ()
Private Attributes
const Nnet & nnet_
const std::vector< Nnet > & nnets_
const std::vector< NnetExample > & egs_
int32 minibatch_size_
SpMatrix< double > * scatter_ptr_
SpMatrix< double > scatter_
Additional Inherited Members
Public Attributes inherited from MultiThreadable
int32 thread_id_
int32 num_threads_
Detailed Description
Definition at line 31 of file combine-nnet-fast.cc.
Constructor & Destructor Documentation
FisherComputationClass() [1/2]
FisherComputationClass (const Nnet & nnet, const std::vector< Nnet > & nnets, const std::vector< NnetExample > & egs, int32 minibatch_size, SpMatrix< double > * scatter) inline
Definition at line 33 of file combine-nnet-fast.cc.
                                                    :
       nnet_(nnet), nnets_(nnets), egs_(egs), minibatch_size_(minibatch_size),
       scatter_ptr_(scatter) { } // This initializer is only used to create a
FisherComputationClass() [2/2]
FisherComputationClass (const FisherComputationClass & other) inline
Definition at line 43 of file combine-nnet-fast.cc.
References FisherComputationClass::nnet_, FisherComputationClass::nnets_, Nnet::NumUpdatableComponents(), SpMatrix< Real >::Resize(), and FisherComputationClass::scatter_.
                                                              :
       MultiThreadable(other),
       nnet_(other.nnet_), nnets_(other.nnets_), egs_(other.egs_),
       minibatch_size_(other.minibatch_size_), scatter_ptr_(other.scatter_ptr_) {
     scatter_.Resize(nnets_.size() * nnet_.NumUpdatableComponents());  }
~FisherComputationClass()
~FisherComputationClass () inline
Definition at line 82 of file combine-nnet-fast.cc.
References SpMatrix< Real >::AddSp(), PackedMatrix< Real >::NumRows(), SpMatrix< Real >::Resize(), FisherComputationClass::scatter_, and FisherComputationClass::scatter_ptr_.
{
     if (scatter_.NumRows() != 0) {
       if (scatter_ptr_->NumRows() == 0)
         scatter_ptr_->Resize(scatter_.NumRows());
       scatter_ptr_->AddSp(1.0, scatter_);
     }
   }
Member Function Documentation
operator()()
void operator() () inline virtual
Implements MultiThreadable.
Definition at line 49 of file combine-nnet-fast.cc.
References SpMatrix< Real >::AddVec2(), VectorBase< Real >::Dim(), kaldi::nnet2::DoBackprop(), UpdatableComponent::DotProduct(), FisherComputationClass::egs_, Nnet::GetComponent(), rnnlm::i, KALDI_ASSERT, FisherComputationClass::minibatch_size_, rnnlm::n, FisherComputationClass::nnet_, FisherComputationClass::nnets_, MultiThreadable::num_threads_, Nnet::NumComponents(), Nnet::NumUpdatableComponents(), FisherComputationClass::scatter_, Nnet::SetZero(), and MultiThreadable::thread_id_.
                       {
     // b is the "minibatch id."
     int32 num_egs = static_cast<int32>(egs_.size());
     Nnet nnet_gradient(nnet_);
     for (int32 b = 0; b * minibatch_size_ < num_egs; b++) {
       if (b % num_threads_ != thread_id_)
         continue; // We're not responsible for this minibatch.
       int32 offset = b * minibatch_size_,
           length = std::min(minibatch_size_,
                        num_egs - offset);
       bool is_gradient = true;
       nnet_gradient.SetZero(is_gradient);
       std::vector<NnetExample> minibatch(egs_.begin() + offset,
                                                  egs_.begin() + offset + length);
       DoBackprop(nnet_, minibatch, &nnet_gradient);
       Vector<double> gradient(nnets_.size() * nnet_.NumUpdatableComponents());
       int32 i = 0;
       for (int32 n = 0; n < static_cast<int32>(nnets_.size()); n++) {
         for (int32 c = 0; c < nnet_.NumComponents(); c++) {
           const UpdatableComponent *uc = dynamic_cast<const UpdatableComponent*>(
               &(nnet_gradient.GetComponent(c))),
               *uc_other = dynamic_cast<const UpdatableComponent*>(
                   &(nnets_[n].GetComponent(c)));
           if (uc != NULL) {
             gradient(i) = uc->DotProduct(*uc_other);
             i++;
           }
         }
       }
       KALDI_ASSERT(i == gradient.Dim());
       scatter_.AddVec2(1.0, gradient);
     }
   }
Member Data Documentation
egs_
const std::vector<NnetExample>& egs_ private
Definition at line 94 of file combine-nnet-fast.cc.
Referenced by FastNnetCombiner::ComputeObjfAndGradient(), FastNnetCombiner::ComputePreconditioner(), FastNnetCombiner::GetInitialParams(), and FisherComputationClass::operator()().
minibatch_size_
int32 minibatch_size_ private
Definition at line 95 of file combine-nnet-fast.cc.
Referenced by FisherComputationClass::operator()().
nnet_
const Nnet& nnet_ private
Definition at line 91 of file combine-nnet-fast.cc.
Referenced by FisherComputationClass::FisherComputationClass(), and FisherComputationClass::operator()().
nnets_
const std::vector<Nnet>& nnets_ private
Definition at line 92 of file combine-nnet-fast.cc.
Referenced by FastNnetCombiner::ComputeCurrentNnet(), FastNnetCombiner::ComputeObjfAndGradient(), FastNnetCombiner::ComputePreconditioner(), FisherComputationClass::FisherComputationClass(), FastNnetCombiner::GetInitialParams(), and FisherComputationClass::operator()().
scatter_
SpMatrix<double> scatter_ private
Definition at line 98 of file combine-nnet-fast.cc.
Referenced by FisherComputationClass::FisherComputationClass(), FisherComputationClass::operator()(), and FisherComputationClass::~FisherComputationClass().
scatter_ptr_
SpMatrix<double>* scatter_ptr_ private
Definition at line 97 of file combine-nnet-fast.cc.
Referenced by FisherComputationClass::~FisherComputationClass().
The documentation for this class was generated from the following file:
nnet2/combine-nnet-fast.cc