Kaldi: ConstIntegerSet< I > Class Template Reference
ConstIntegerSet< I > Class Template Reference
#include <const-integer-set.h>
Public Types
typedef std::vector< I >::const_iterator iterator
Public Member Functions
ConstIntegerSet ()
void Init (const std::vector< I > &input)
void Init (const std::set< I > &input)
ConstIntegerSet (const std::vector< I > &input)
ConstIntegerSet (const std::set< I > &input)
ConstIntegerSet (const ConstIntegerSet< I > &other)
int count (I i) const
iterator begin () const
iterator end () const
size_t size () const
bool empty () const
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
Private Member Functions
void InitInternal ()
Private Attributes
I lowest_member_
I highest_member_
bool contiguous_
bool quick_
std::vector< bool > quick_set_
std::vector< I > slow_set_
Detailed Description
template<class I>
class kaldi::ConstIntegerSet< I >
Definition at line 43 of file const-integer-set.h.
Member Typedef Documentation
iterator
typedef std::vector<I>::const_iterator iterator
Definition at line 73 of file const-integer-set.h.
Constructor & Destructor Documentation
ConstIntegerSet() [1/4]
ConstIntegerSet () inline
Definition at line 45 of file const-integer-set.h.
 : lowest_member_(1), highest_member_(0) { }
ConstIntegerSet() [2/4]
ConstIntegerSet (const std::vector< I > & input) inline explicit
Definition at line 58 of file const-integer-set.h.
                                                      : slow_set_(input) {
     SortAndUniq(&slow_set_);
     InitInternal();
   }
ConstIntegerSet() [3/4]
ConstIntegerSet (const std::set< I > & input) inline explicit
Definition at line 62 of file const-integer-set.h.
{
     CopySetToVector(input, &slow_set_);
     InitInternal();
   }
ConstIntegerSet() [4/4]
ConstIntegerSet (const ConstIntegerSet< I > & other) inline explicit
Definition at line 66 of file const-integer-set.h.
                                                            :
                            slow_set_(other.slow_set_) {
     InitInternal();
   }
Member Function Documentation
begin()
iterator begin () const inline
Definition at line 74 of file const-integer-set.h.
Referenced by kaldi::_convert_tree(), TreeRenderer::MakeEdgeLabel(), SplitEventMap::MapValues(), and kaldi::TestSetOfNumbers().
 { return slow_set_.begin(); }
count()
int count (I i) const
Definition at line 62 of file const-integer-set-inl.h.
Referenced by ConstIntegerSet< EventValueType >::ConstIntegerSet(), InverseLeftBiphoneContextFst::Final(), InverseLeftBiphoneContextFst::GetArc(), InverseContextFst::InverseContextFst(), InverseContextFst::IsDisambigSymbol(), InverseContextFst::IsPhoneSymbol(), fst::MakePrecedingInputSymbolsSameClass(), fst::PenalizeArcsWithSomeInputSymbols(), fst::RemoveArcsWithSomeInputSymbols(), TreeRenderer::RenderSplit(), kaldi::TestSetOfNumbers(), kaldi::WeightSilencePost(), and kaldi::WeightSilencePostDistributed().
{
   if (i < lowest_member_ || i > highest_member_) {
     return 0;
   } else {
     if (contiguous_) return true;
     if (quick_) {
       return (quick_set_[i-lowest_member_] ? 1 : 0);
     } else {
       bool ans = std::binary_search(slow_set_.begin(), slow_set_.end(), i);
       return (ans ? 1 : 0);
     }
   }
 }
empty()
bool empty () const inline
Definition at line 77 of file const-integer-set.h.
Referenced by InverseContextFst::InverseContextFst(), and InverseLeftBiphoneContextFst::InverseLeftBiphoneContextFst().
 { return slow_set_.empty(); }
end()
iterator end () const inline
Definition at line 75 of file const-integer-set.h.
Referenced by kaldi::_convert_tree(), TreeRenderer::MakeEdgeLabel(), and kaldi::TestSetOfNumbers().
 { return slow_set_.end(); }
Init() [1/2]
void Init (const std::vector< I > & input) inline
Definition at line 47 of file const-integer-set.h.
Referenced by kaldi::TestSetOfNumbers().
{
     slow_set_ = input;
     SortAndUniq(&slow_set_);
     InitInternal();
   }
Init() [2/2]
void Init (const std::set< I > & input) inline
Definition at line 53 of file const-integer-set.h.
{
     CopySetToVector(input, &slow_set_);
     InitInternal();
   }
InitInternal()
void InitInternal () private
Definition at line 30 of file const-integer-set-inl.h.
Referenced by ConstIntegerSet< EventValueType >::ConstIntegerSet(), and ConstIntegerSet< EventValueType >::Init().
{
   KALDI_ASSERT_IS_INTEGER_TYPE(I);
   quick_set_.clear();  // just in case we previously had data.
   if (slow_set_.size() == 0) {
     lowest_member_=(I) 1;
     highest_member_=(I) 0;
     contiguous_ = false;
     quick_ = false;
   } else {
     lowest_member_ = slow_set_.front();
     highest_member_ = slow_set_.back();
     size_t range = highest_member_ + 1 - lowest_member_;
     if (range == slow_set_.size()) {
       contiguous_ = true;
       quick_= false;
     } else {
       contiguous_ = false;
       // If it would be more compact to store as bool
       if (range < slow_set_.size() * 8 * sizeof(I)) {
         // (assuming 1 bit per element)...
         quick_set_.resize(range, false);
         for (size_t i = 0;i < slow_set_.size();i++)
           quick_set_[slow_set_[i] - lowest_member_] = true;
         quick_ = true;
       } else {
         quick_ = false;
       }
     }
   }
 }
Read()
void Read (std::istream & is, bool binary)
Definition at line 82 of file const-integer-set-inl.h.
Referenced by ConstIntegerSet< EventValueType >::empty(), SplitEventMap::Read(), TreeRenderer::RenderSplit(), and kaldi::TestSetOfNumbers().
{
   ReadIntegerVector(is, binary, &slow_set_);
   InitInternal();
 }
size()
size_t size () const inline
Definition at line 76 of file const-integer-set.h.
Referenced by kaldi::TestSetOfNumbers().
 { return slow_set_.size(); }
Write()
void Write (std::ostream & os, bool binary) const
Definition at line 77 of file const-integer-set-inl.h.
Referenced by ConstIntegerSet< EventValueType >::empty(), and kaldi::TestSetOfNumbers().
{
   WriteIntegerVector(os, binary, slow_set_);
 }
Member Data Documentation
contiguous_
bool contiguous_ private
Definition at line 85 of file const-integer-set.h.
highest_member_
I highest_member_ private
Definition at line 84 of file const-integer-set.h.
lowest_member_
I lowest_member_ private
Definition at line 83 of file const-integer-set.h.
quick_
bool quick_ private
Definition at line 86 of file const-integer-set.h.
quick_set_
std::vector<bool> quick_set_ private
Definition at line 87 of file const-integer-set.h.
slow_set_
std::vector<I> slow_set_ private
Definition at line 88 of file const-integer-set.h.
Referenced by ConstIntegerSet< EventValueType >::begin(), ConstIntegerSet< EventValueType >::ConstIntegerSet(), ConstIntegerSet< EventValueType >::empty(), ConstIntegerSet< EventValueType >::end(), ConstIntegerSet< EventValueType >::Init(), and ConstIntegerSet< EventValueType >::size().
The documentation for this class was generated from the following files:
util/const-integer-set.h
util/const-integer-set-inl.h