Kaldi: DeterministicOnDemandFst< Arc > Class Template Reference
DeterministicOnDemandFst< Arc > Class Template Reference abstract
"Classes and functions related to on-demand deterministic FST's"
class DeterministicOnDemandFst is an "FST-like" base-class.
#include <deterministic-fst.h>
Public Types
typedef Arc::StateId StateId
typedef Arc::Weight Weight
typedef Arc::Label Label
Public Member Functions
virtual StateId Start ()=0
virtual Weight Final (StateId s)=0
virtual bool GetArc (StateId s, Label ilabel, Arc *oarc)=0
Note: ilabel must not be epsilon.
virtual ~DeterministicOnDemandFst ()
Detailed Description
template<class Arc>
class fst::DeterministicOnDemandFst< Arc >
class DeterministicOnDemandFst is an "FST-like" base-class.
It does not actually inherit from any Fst class because its interface is not exactly the same; it's much smaller. It assumes that the FST can have only one arc for any given input symbol, which makes the GetArc function below possible. (The FST is also assumed to be free of input epsilons). Note: we don't use "const" in this interface, because it creates problems when we do things like caching.
Definition at line 75 of file deterministic-fst.h.
Member Typedef Documentation
Label
typedef Arc::Label Label
Definition at line 79 of file deterministic-fst.h.
StateId
typedef Arc::StateId StateId
Definition at line 77 of file deterministic-fst.h.
Weight
typedef Arc::Weight Weight
Definition at line 78 of file deterministic-fst.h.
Constructor & Destructor Documentation
~DeterministicOnDemandFst()
virtual ~DeterministicOnDemandFst () inline virtual
Definition at line 88 of file deterministic-fst.h.
 { }
Member Function Documentation
Final()
virtual Weight Final (StateId s) pure virtual
Implemented in LmExampleDeterministicOnDemandFst< Arc >, CacheDeterministicOnDemandFst< Arc >, ComposeDeterministicOnDemandFst< Arc >, UnweightedNgramFst< Arc >, and BackoffDeterministicOnDemandFst< Arc >.
Referenced by kaldi::ComposeCompactLatticeDeterministic(), fst::ComposeDeterministicOnDemand(), fst::ComposeDeterministicOnDemandInverse(), PrunedCompactLatticeComposer::ProcessQueueElement(), LatticeBiglmFasterDecoder::PruneForwardLinksFinal(), BackoffDeterministicOnDemandFst< Arc >::Start(), UnweightedNgramFst< Arc >::Start(), ComposeDeterministicOnDemandFst< Arc >::Start(), LmExampleDeterministicOnDemandFst< Arc >::Start(), and fst::WalkSinglePath().
GetArc()
virtual bool GetArc (StateId s, Label ilabel, Arc * oarc) pure virtual
Note: ilabel must not be epsilon.
Implemented in LmExampleDeterministicOnDemandFst< Arc >, CacheDeterministicOnDemandFst< Arc >, ComposeDeterministicOnDemandFst< Arc >, UnweightedNgramFst< Arc >, and BackoffDeterministicOnDemandFst< Arc >.
Referenced by kaldi::ComposeCompactLatticeDeterministic(), fst::ComposeDeterministicOnDemand(), fst::ComposeDeterministicOnDemandInverse(), CacheDeterministicOnDemandFst< Arc >::Final(), PrunedCompactLatticeComposer::ProcessTransition(), LatticeBiglmFasterDecoder::PropagateLm(), BackoffDeterministicOnDemandFst< Arc >::Start(), UnweightedNgramFst< Arc >::Start(), ComposeDeterministicOnDemandFst< Arc >::Start(), LmExampleDeterministicOnDemandFst< Arc >::Start(), and fst::WalkSinglePath().
Start()
virtual StateId Start () pure virtual
Implemented in ConstArpaLmDeterministicFst, LmExampleDeterministicOnDemandFst< Arc >, CacheDeterministicOnDemandFst< Arc >, ComposeDeterministicOnDemandFst< Arc >, InverseLeftBiphoneContextFst, InverseContextFst, UnweightedNgramFst< Arc >, ScaleDeterministicOnDemandFst, BackoffDeterministicOnDemandFst< Arc >, and RnnlmDeterministicFst.
Referenced by PrunedCompactLatticeComposer::AddFirstState(), BiglmFasterDecoder::BiglmFasterDecoder(), kaldi::ComposeCompactLatticeDeterministic(), fst::ComposeDeterministicOnDemand(), fst::ComposeDeterministicOnDemandInverse(), LatticeBiglmFasterDecoder::Decode(), LatticeBiglmFasterDecoder::LatticeBiglmFasterDecoder(), and fst::WalkSinglePath().
The documentation for this class was generated from the following file:
fstext/deterministic-fst.h