Kaldi: TxpXmlData Class Reference
TxpXmlData Class Reference
Base class for all objects which require voice data.
#include <txpxmldata.h>
Public Member Functions
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
virtual void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
virtual void EndElement (const char *name)
Inherited class for bespoke end element handling.
virtual void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
virtual void StartCData ()
Inherited class for bespoke start cdata handling.
virtual void EndCData ()
Inherited class for bespoke start cdata handling.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Static Public Member Functions
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
Base class for all objects which require voice data.
The class wraps expat and has virtual fuctions to handle the XML parsing. In the objects derived from this, a file will typically be built into a bespoke structure for rapid processing. The callback functions need to be static to be set in expat, these then call the virtual functions.
Definition at line 39 of file txpxmldata.h.
Constructor & Destructor Documentation
TxpXmlData()
TxpXmlData () inline explicit
Definition at line 54 of file txpxmldata.h.
References TxpXmlData::Init(), and TxpXmlData::~TxpXmlData().
 : parser_(NULL) {}
~TxpXmlData()
~TxpXmlData () virtual
Definition at line 25 of file txpxmldata.cc.
References TxpXmlData::parser_.
Referenced by TxpXmlData::TxpXmlData().
{
   if (parser_) {
     XML_ParserFree(parser_);
   }
 }
Member Function Documentation
CharHandler()
virtual void CharHandler (const char * data, int32 len) inline virtual
Inherited class for bespoke character handling.
Reimplemented in TxpNRules, TxpTrules, TxpLexicon, and TxpAbbrev.
Definition at line 65 of file txpxmldata.h.
Referenced by TxpXmlData::CharHandlerCB().
 {}
CharHandlerCB()
void CharHandlerCB (void * userData, const char * data, int32 len) static
Callback functions set in expat for handling characters.
Definition at line 53 of file txpxmldata.cc.
References TxpXmlData::CharHandler().
Referenced by TxpXmlData::Init().
{
   reinterpret_cast<TxpXmlData*>(userData)->CharHandler(data, len);
 }
EndCData()
virtual void EndCData () inline virtual
Inherited class for bespoke start cdata handling.
Reimplemented in TxpNRules, and TxpTrules.
Definition at line 69 of file txpxmldata.h.
References TxpXmlData::Parse().
Referenced by TxpXmlData::EndCDataCB().
 {}
EndCDataCB()
void EndCDataCB (void * userData) static
Callback functions set in expat for end of Cdata.
Definition at line 61 of file txpxmldata.cc.
References TxpXmlData::EndCData().
Referenced by TxpXmlData::Init().
{
   reinterpret_cast<TxpXmlData*>(userData)->EndCData();
 }
EndElement()
virtual void EndElement (const char * name) inline virtual
Inherited class for bespoke end element handling.
Reimplemented in TxpNRules, TxpTrules, TxpLexicon, and TxpAbbrev.
Definition at line 63 of file txpxmldata.h.
Referenced by TxpXmlData::EndElementCB().
 {}
EndElementCB()
void EndElementCB (void * userData, const char * name) static
Callback functions set in expat for end element.
Definition at line 49 of file txpxmldata.cc.
References TxpXmlData::EndElement().
Referenced by TxpXmlData::Init().
{
   reinterpret_cast<TxpXmlData*>(userData)->EndElement(name);
 }
GetCurrentLineNumber()
int GetCurrentLineNumber () inline
Definition at line 80 of file txpxmldata.h.
References TxpXmlData::GetOptValue(), TxpXmlData::parser_, and TxpXmlData::SetAttribute().
Referenced by TxpSylmax::StartElement().
 {return XML_GetCurrentLineNumber(parser_);}
GetOptValue()
const char * GetOptValue (const char * key)
Return a general option value.
Definition at line 221 of file txpxmldata.cc.
References TxpParseOptions::GetValue(), and TxpXmlData::opts_.
Referenced by TxpXmlData::GetCurrentLineNumber(), and TxpXmlData::Parse().
{
   return opts_->GetValue("general", key);
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & type, const std::string & name) virtual
Initialise the data structure by processing a tpdb file.
Definition at line 31 of file txpxmldata.cc.
References TxpXmlData::CharHandlerCB(), TxpXmlData::EndCDataCB(), TxpXmlData::EndElementCB(), TxpXmlData::name_, TxpXmlData::opts_, TxpXmlData::parser_, TxpXmlData::StartCDataCB(), TxpXmlData::StartElementCB(), and TxpXmlData::type_.
Referenced by TxpAbbrev::Init(), TxpPhone::Init(), TxpSylmax::Init(), TxpPos::Init(), TxpLts::Init(), TxpPbreak::Init(), TxpLexicon::Init(), TxpTrules::Init(), TxpNRules::Init(), TxpPosSet::Init(), TxpCexspec::Init(), and TxpXmlData::TxpXmlData().
{
   opts_ = &opts;
   type_ = type;
   name_ = name;
   parser_ = XML_ParserCreate("UTF-8");
   ::XML_SetUserData(parser_, this);
   ::XML_SetElementHandler(parser_, StartElementCB, EndElementCB);
   ::XML_SetCharacterDataHandler(parser_, CharHandlerCB);
   ::XML_SetStartCdataSectionHandler(parser_, StartCDataCB);
   ::XML_SetEndCdataSectionHandler(parser_, EndCDataCB);
 }
Parse() [1/2]
bool Parse (const std::string & tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
Definition at line 96 of file txpxmldata.cc.
Referenced by TxpXmlData::EndCData(), TxpCex::Init(), TxpPronounce::Init(), TxpAbbrev::Parse(), TxpPhone::Parse(), TxpSylmax::Parse(), TxpPbreak::Parse(), TxpPos::Parse(), TxpTrules::Parse(), TxpNRules::Parse(), and TxpPosSet::Parse().
{
   return Parse(tpdb, std::string(""));
 }
Parse() [2/2]
bool Parse (const std::string & tpdb, const std::string & fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
Definition at line 100 of file txpxmldata.cc.
References TxpXmlData::buffer_, Input::Close(), TxpXmlData::fname_, TxpXmlData::GetOptValue(), KALDI_ERR, KALDI_VLOG, KALDI_WARN, TxpXmlData::name_, Input::Open(), TxpXmlData::parser_, TxpXmlData::path_, Input::Stream(), TxpXmlData::tpdb_, and TxpXmlData::type_.
{
   const char *lang, *region, *acc, *spk;
   bool binary, fileopen = false;
   enum XML_Status r;
   Input ki;
   std::string dataroot;
   tpdb_ = tpdb;
   fname_.clear();
   // if no fname specified use architecture and default type name
   if (!fname.empty()) fname_ = fname;
   else fname_ = type_ + "-" + name_ + ".xml";
   // get general settings from the configuration
   lang = GetOptValue("lang");
   region = GetOptValue("region");
   acc = GetOptValue("acc");
   spk = GetOptValue("spk");
   if (!lang) {
     KALDI_ERR << "No language specified: i.e. --general-lang=en";
   }
   // if fname specified override architecture and default type name
   // and only accept this file (no default names)
   if (!fname.empty()) {
     fname_ = fname;
   } else {
     // first search for architecture file <type_>-<name_>.xml
     fname_ = type_ + "-" + name_ + ".xml";
   }
   // If we are in a kaldi flat directory structure look for the file
   // first as fname_ and second as default value
   if (ki.Open((tpdb + "/idlak-data-flat").c_str())) {
     path_ = tpdb_;
     // search in this directory only
     if (!ki.Open((path_ + "/" + fname_).c_str(), &binary)) {
       KALDI_WARN << "Can't find xml data:" << path_ << "/" << fname_;
     }
   } else {
     if (spk && *spk) {
       path_ = tpdb_ + "/" + lang + "/" + acc + "/" + spk;
       fileopen = ki.Open((path_ + "/" + fname_).c_str(), &binary);
     }
     if (!fileopen && acc && *acc) {
       path_ = tpdb_ + "/" + lang + "/" + acc;
       fileopen = ki.Open((path_ + "/" + fname_).c_str(), &binary);
     }
     if (!fileopen && region && *region) {
       path_ = tpdb_ + "/" + lang + "/" + region;
         fileopen = ki.Open((path_ + "/" + fname_).c_str(), &binary);
     }
     if (!fileopen) {
       path_ = tpdb_ + "/" + lang;
       fileopen = ki.Open((path_ + "/" + fname_).c_str(), &binary);
     }
     if (!fileopen)  KALDI_WARN << "Can't find xml data in " <<
                         "speaker/accent/region/language directories:" <<
                         "tpdb root:" << path_ << " fname:" << fname_;
   }
   // if still not found and fname is not overridden
   // try to open a default data file
   if (!fileopen && fname.empty() && name_ != "default") {
     fname_.clear();
     fname_ = type_ + "-default.xml";
     if (ki.Open((tpdb + "/idlak-data-flat").c_str())) {
       path_ = tpdb_;
       // search in this directory only
       if (!ki.Open((path_ + "/" + fname_).c_str(), &binary)) {
         KALDI_ERR << "Can't find xml data:" << path_ << "/" << fname_;
       }
     } else {
       if (spk && *spk) {
         path_ = tpdb_ + "/" + lang + "/" + acc + "/" + spk;
         fileopen = ki.Open((path_ + "/" + fname_).c_str(), &binary);
       }
       if (!fileopen && acc && *acc) {
         path_ = tpdb_ + "/" + lang + "/" + acc;
         fileopen = ki.Open((path_ + "/" + fname_).c_str(), &binary);
       }
       if (!fileopen && region && *region) {
         path_ = tpdb_ + "/" + lang + "/" + region;
         fileopen = ki.Open((path_ + "/" + fname_).c_str(), &binary);
       }
       if (!fileopen) {
         path_ = tpdb_ + "/" + lang;
         fileopen = ki.Open((path_ + "/" + fname_).c_str(), &binary);
       }
     }
   }
   if (!fileopen) KALDI_ERR << "Can't find xml data in speaker/accent/region/language directories:" <<
                      "tpdb root:" << tpdb_ << " fname:" << fname_;
   KALDI_VLOG(1) << "Loading: " << path_ << "/" << fname_;
   while (getline(ki.Stream(), buffer_)) {
     // Reappend line break to get correct error reporting
     buffer_.append("\n");
     r = XML_Parse(parser_, buffer_.c_str(), buffer_.length(), false);
     if (r == XML_STATUS_ERROR) {
       KALDI_WARN << "Expat XML Parse error: " <<
           XML_ErrorString(::XML_GetErrorCode(parser_))
                  << " Line: " << ::XML_GetCurrentLineNumber(parser_)
                  << " Col:" << XML_GetCurrentColumnNumber(parser_);
       return false;
     }
   }
   XML_Parse(parser_, "", 0, true);
   ki.Close();
   return true;
 }
SetAttribute()
int32 SetAttribute (const char * name, const char ** atts, std::string * val)
Utility to set a named attribute from an expat array of attribute key value pairs.
Definition at line 210 of file txpxmldata.cc.
References rnnlm::i.
Referenced by TxpXmlData::GetCurrentLineNumber(), TxpAbbrev::StartElement(), TxpPhone::StartElement(), TxpLts::StartElement(), TxpPos::StartElement(), TxpSylmax::StartElement(), TxpPbreak::StartElement(), TxpLexicon::StartElement(), TxpPosSet::StartElement(), TxpTrules::StartElement(), TxpNRules::StartElement(), and TxpCexspec::StartElement().
{
   int32 i = 0;
   val->clear();
   while (atts[i]) {
     if (!strcmp(atts[i], name)) *val = atts[i + 1];
     i += 2;
   }
   return i / 2;
 }
StartCData()
virtual void StartCData () inline virtual
Inherited class for bespoke start cdata handling.
Reimplemented in TxpNRules, and TxpTrules.
Definition at line 67 of file txpxmldata.h.
Referenced by TxpXmlData::StartCDataCB().
 {}
StartCDataCB()
void StartCDataCB (void * userData) static
Callback functions set in expat for start of Cdata (used for regular expressions)
Definition at line 57 of file txpxmldata.cc.
References TxpXmlData::StartCData().
Referenced by TxpXmlData::Init().
{
   reinterpret_cast<TxpXmlData*>(userData)->StartCData();
 }
StartElement()
virtual void StartElement (const char * name, const char ** atts) inline virtual
Inherited class for bespoke start element handling.
Reimplemented in TxpCexspec, TxpNRules, TxpTrules, TxpPosSet, TxpLexicon, TxpPbreak, TxpSylmax, TxpPos, TxpLts, TxpAbbrev, and TxpPhone.
Definition at line 61 of file txpxmldata.h.
Referenced by TxpXmlData::StartElementCB().
 {}
StartElementCB()
void StartElementCB (void * userData, const char * name, const char ** atts) static
Callback functions set in expat for start element.
Definition at line 44 of file txpxmldata.cc.
References TxpXmlData::StartElement().
Referenced by TxpXmlData::Init().
{
   reinterpret_cast<TxpXmlData*>(userData)->StartElement(name, atts);
 }
Member Data Documentation
buffer_
std::string buffer_ protected
Input file is read line by line into this buffer for processing.
Definition at line 103 of file txpxmldata.h.
Referenced by TxpXmlData::Parse().
fname_
std::string fname_ protected
Final filename of input file.
Definition at line 101 of file txpxmldata.h.
Referenced by TxpXmlData::Parse(), and TxpSylmax::StartElement().
name_
std::string name_ protected
Name of object e.g. default or user etc.
Definition at line 95 of file txpxmldata.h.
Referenced by TxpXmlData::Init(), and TxpXmlData::Parse().
opts_
const TxpParseOptions* opts_ protected
Options structure as all xmldats classes use the general section.
Definition at line 89 of file txpxmldata.h.
Referenced by TxpXmlData::GetOptValue(), and TxpXmlData::Init().
parser_
XML_Parser parser_ protected
Expat parser structure.
Definition at line 91 of file txpxmldata.h.
Referenced by TxpXmlData::GetCurrentLineNumber(), TxpXmlData::Init(), TxpXmlData::Parse(), TxpCexspec::StartElement(), and TxpXmlData::~TxpXmlData().
path_
std::string path_ protected
Final pathname of input file.
Definition at line 99 of file txpxmldata.h.
Referenced by TxpXmlData::Parse().
tpdb_
std::string tpdb_ protected
Directory of the tpdb (text processing database) files.
Definition at line 97 of file txpxmldata.h.
Referenced by TxpXmlData::Parse().
type_
std::string type_ protected
Type of object e.g. lexicon.
Definition at line 93 of file txpxmldata.h.
Referenced by TxpXmlData::Init(), and TxpXmlData::Parse().
The documentation for this class was generated from the following files:
idlaktxp/txpxmldata.h
idlaktxp/txpxmldata.cc