Kaldi: RestrictedAttentionComponent::PrecomputedIndexes Class Reference
RestrictedAttentionComponent::PrecomputedIndexes Class Reference
#include <nnet-attention-component.h>
Public Member Functions
PrecomputedIndexes ()
PrecomputedIndexes (const PrecomputedIndexes &other)
virtual PrecomputedIndexes * Copy () const
virtual void Write (std::ostream &os, bool binary) const
virtual void Read (std::istream &os, bool binary)
virtual std::string Type () const
virtual ~PrecomputedIndexes ()
Public Member Functions inherited from ComponentPrecomputedIndexes
virtual ~ComponentPrecomputedIndexes ()
Public Attributes
time_height_convolution::ConvolutionComputationIo io
Additional Inherited Members
Static Public Member Functions inherited from ComponentPrecomputedIndexes
static ComponentPrecomputedIndexes * ReadNew (std::istream &is, bool binary)
static ComponentPrecomputedIndexes * NewComponentPrecomputedIndexesOfType (const std::string &cpi_type)
Detailed Description
Definition at line 185 of file nnet-attention-component.h.
Constructor & Destructor Documentation
PrecomputedIndexes() [1/2]
PrecomputedIndexes () inline
Definition at line 187 of file nnet-attention-component.h.
 { }
PrecomputedIndexes() [2/2]
PrecomputedIndexes (const PrecomputedIndexes & other) inline
Definition at line 188 of file nnet-attention-component.h.
References RestrictedAttentionComponent::PrecomputedIndexes::Copy(), RestrictedAttentionComponent::PrecomputedIndexes::Read(), and RestrictedAttentionComponent::PrecomputedIndexes::Write().
                                                        :
         io(other.io) { }
~PrecomputedIndexes()
virtual ~PrecomputedIndexes () inline virtual
Definition at line 196 of file nnet-attention-component.h.
 { }
Member Function Documentation
Copy()
RestrictedAttentionComponent::PrecomputedIndexes * Copy () const virtual
Implements ComponentPrecomputedIndexes.
Definition at line 648 of file nnet-attention-component.cc.
Referenced by RestrictedAttentionComponent::PrecomputedIndexes::PrecomputedIndexes().
{
   return new PrecomputedIndexes(*this);
 }
Read()
void Read (std::istream & os, bool binary) virtual
Implements ComponentPrecomputedIndexes.
Definition at line 660 of file nnet-attention-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), and kaldi::nnet3::ExpectToken().
Referenced by RestrictedAttentionComponent::PrecomputedIndexes::PrecomputedIndexes().
{
   ExpectOneOrTwoTokens(is, binary,
                        "<RestrictedAttentionComponentPrecomputedIndexes>",
                        "<Io>");
   io.Read(is, binary);
   ExpectToken(is, binary, "</RestrictedAttentionComponentPrecomputedIndexes>");
 }
Type()
virtual std::string Type () const inline virtual
Implements ComponentPrecomputedIndexes.
Definition at line 193 of file nnet-attention-component.h.
{
       return "RestrictedAttentionComponentPrecomputedIndexes";
     }
Write()
void Write (std::ostream & os, bool binary) const virtual
Implements ComponentPrecomputedIndexes.
Definition at line 652 of file nnet-attention-component.cc.
References kaldi::WriteToken().
Referenced by RestrictedAttentionComponent::PrecomputedIndexes::PrecomputedIndexes().
{
   WriteToken(os, binary, "<RestrictedAttentionComponentPrecomputedIndexes>");
   WriteToken(os, binary, "<Io>");
   io.Write(os, binary);
   WriteToken(os, binary, "</RestrictedAttentionComponentPrecomputedIndexes>");
 }
Member Data Documentation
io
time_height_convolution::ConvolutionComputationIo io
Definition at line 198 of file nnet-attention-component.h.
Referenced by RestrictedAttentionComponent::Backprop(), RestrictedAttentionComponent::PrecomputeIndexes(), and RestrictedAttentionComponent::Propagate().
The documentation for this class was generated from the following files:
nnet3/nnet-attention-component.h
nnet3/nnet-attention-component.cc