Kaldi: BatchNormComponent Class Reference
BatchNormComponent Class Reference
#include <nnet-normalize-component.h>
Classes
struct Memo
Public Member Functions
BatchNormComponent ()
void SetTestMode (bool test_mode)
BatchNormComponent (const BatchNormComponent &other)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
const CuVector< BaseFloat > & Offset () const
const CuVector< BaseFloat > & Scale () const
Public Member Functions inherited from Component
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Private Member Functions
void Check () const
void ComputeDerived ()
Static Private Member Functions
static void ComputeOffsetAndScale (double count, BaseFloat epsilon, const Vector< double > &stats_sum, const Vector< double > &stats_sumsq, Vector< BaseFloat > *offset, Vector< BaseFloat > *scale)
Private Attributes
int32 dim_
int32 block_dim_
BaseFloat epsilon_
BaseFloat target_rms_
bool test_mode_
double count_
CuVector< double > stats_sum_
CuVector< double > stats_sumsq_
CuVector< BaseFloat > offset_
CuVector< BaseFloat > scale_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 159 of file nnet-normalize-component.h.
Constructor & Destructor Documentation
BatchNormComponent() [1/2]
BatchNormComponent () inline
Definition at line 162 of file nnet-normalize-component.h.
 { }
BatchNormComponent() [2/2]
BatchNormComponent (const BatchNormComponent & other)
Definition at line 258 of file nnet-normalize-component.cc.
References BatchNormComponent::Check(), and BatchNormComponent::ComputeDerived().
                                                                      :
     dim_(other.dim_), block_dim_(other.block_dim_),
     epsilon_(other.epsilon_), target_rms_(other.target_rms_),
     test_mode_(other.test_mode_), count_(other.count_),
     stats_sum_(other.stats_sum_), stats_sumsq_(other.stats_sumsq_) {
   ComputeDerived();
   Check();
 }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 655 of file nnet-normalize-component.cc.
References CuVectorBase< Real >::AddVec(), BatchNormComponent::ComputeDerived(), BatchNormComponent::count_, BatchNormComponent::stats_sum_, and BatchNormComponent::stats_sumsq_.
{
   const BatchNormComponent *other =
       dynamic_cast<const BatchNormComponent*>(&other_in);
   count_ += alpha * other->count_;
   stats_sum_.AddVec(alpha, other->stats_sum_);
   stats_sumsq_.AddVec(alpha, other->stats_sumsq_);
   // this operation might change offset_ and scale_, so we recompute them
   // in this instance (but not in Scale()).
   ComputeDerived();
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 466 of file nnet-normalize-component.cc.
References CuMatrixBase< Real >::AddMatDiagVec(), CuMatrixBase< Real >::AddVecToRows(), BatchNormComponent::block_dim_, CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::Data(), BatchNormComponent::dim_, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, BatchNormComponent::Memo::mean_uvar_scale, CuMatrixBase< Real >::MulColsVec(), BatchNormComponent::Memo::num_frames, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), BatchNormComponent::offset_, kaldi::SameDim(), BatchNormComponent::scale_, CuMatrixBase< Real >::Stride(), BatchNormComponent::target_rms_, and BatchNormComponent::test_mode_.
{
   KALDI_ASSERT(SameDim(out_value, out_deriv) &&
                SameDim(out_value, *in_deriv) &&
                (out_value.NumCols() == dim_ ||
                 out_value.NumCols() == block_dim_));
   if (out_value.NumCols() != block_dim_) {
     // if block_dim_ != dim_, we recurse; this helps keep the main code
     // simple.
     KALDI_ASSERT(out_value.Stride() == out_value.NumCols() &&
                  out_deriv.Stride() == out_deriv.NumCols() &&
                  in_deriv->Stride() == in_deriv->NumCols());
     int32 ratio = dim_ / block_dim_,
         orig_rows = out_value.NumRows(),
         orig_cols = out_value.NumCols(),
         new_rows = orig_rows * ratio, new_cols = orig_cols / ratio;
     CuSubMatrix<BaseFloat> out_value_reshaped(out_value.Data(), new_rows,
                                               new_cols, new_cols),
         out_deriv_reshaped(out_deriv.Data(), new_rows, new_cols, new_cols),
         in_deriv_reshaped(in_deriv->Data(), new_rows, new_cols, new_cols);
     // we'll never use in_value, so pass it in unchanged.
     Backprop(debug_info, indexes, in_value,
              out_value_reshaped, out_deriv_reshaped,
              memo_in, to_update, &in_deriv_reshaped);
     return;
   }
   Memo *memo = static_cast<Memo*>(memo_in);
   if (!test_mode_) {
     // search above for BACKWARD PASS for a comment describing the math.
     KALDI_ASSERT(memo != NULL && "memo not passed into backprop");
     int32 num_frames = memo->num_frames;
     KALDI_ASSERT(out_value.NumRows() == num_frames);
     CuSubVector<BaseFloat>
         scale(memo->mean_uvar_scale, 2),
         var_deriv_mod(memo->mean_uvar_scale, 3),
         temp(memo->mean_uvar_scale, 4);
     // var_deriv_mod is going to contain:
     //  2 * power * target-rms^{1/power} * (1/I \sum_i z'(i) z(i)) * scale^{-(1+power)/power}
     // which for power = -0.5 simplifies to:
     // -1.0 / (target_rms * target_rms).
     // but for now we don't have the power of 'scale', we'll add that later.
     BaseFloat coeff = -1.0 / (target_rms_ * target_rms_ * num_frames);
     var_deriv_mod.AddDiagMatMat(coeff, out_value, kTrans,
                                 out_deriv, kNoTrans, 0.0);
     var_deriv_mod.MulElements(scale);
     temp.AddRowSumMat(-1.0 / num_frames, out_deriv, 0.0);
     // the following statement does no work if in_deriv and out_deriv are the
     // same matrix.
     in_deriv->CopyFromMat(out_deriv);
     in_deriv->AddVecToRows(1.0, temp);
     // At this point, *in_deriv contains
     // (z'(i) - 1/I * \sum_i z'(i))
     in_deriv->MulColsVec(scale);
     // At this point, *in_deriv contains
     // scale * (z'(i) - 1/I * \sum_i z'(i))
     in_deriv->AddMatDiagVec(1.0, out_value, kNoTrans,
                             var_deriv_mod, 1.0);
     // At this point, *in_deriv contains what we described in the comment
     // starting BATCHNORM_MATH as:
     // x'(i) = scale * (z'(i) - 1/I * \sum_i z'(i))  + z(i) var_deriv_mod
   } else {
     KALDI_ASSERT(offset_.Dim() == block_dim_);
     // the next call does no work if they point to the same memory.
     in_deriv->CopyFromMat(out_deriv);
     in_deriv->MulColsVec(scale_);
   }
 }
Check()
void Check () const private
Definition at line 253 of file nnet-normalize-component.cc.
References NormalizeComponent::block_dim_, KALDI_ASSERT, and NormalizeComponent::target_rms_.
Referenced by BatchNormComponent::BatchNormComponent(), BatchNormComponent::Read(), and BatchNormComponent::Write().
{
   KALDI_ASSERT(dim_ > 0 && block_dim_ > 0 && dim_ % block_dim_ == 0 &&
                epsilon_ > 0.0 && target_rms_ > 0.0);
 }
ComputeDerived()
void ComputeDerived () private
Definition at line 208 of file nnet-normalize-component.cc.
References NormalizeComponent::block_dim_, KALDI_WARN, and NormalizeComponent::target_rms_.
Referenced by BatchNormComponent::Add(), BatchNormComponent::BatchNormComponent(), BatchNormComponent::InitFromConfig(), and BatchNormComponent::Read().
{
   if (!test_mode_) {
     offset_.Resize(0);
     scale_.Resize(0);
     return;
   }
   if (count_ == 0.0) {
     KALDI_WARN << "Test-mode is set but there is no data count.  "
         "Creating random counts.  This only makes sense "
         "in unit-tests (or compute_prob_*.0.log).  If you see this "
         "elsewhere, something is very wrong.";
     count_ = 1.0;
     stats_sum_.SetRandn();
     stats_sumsq_.SetRandn();
     stats_sumsq_.AddVecVec(1.0, stats_sum_, stats_sum_, 1.0);
   }
   offset_.Resize(block_dim_);
   scale_.Resize(block_dim_);
   offset_.CopyFromVec(stats_sum_);
   offset_.Scale(-1.0 / count_);
   // now offset_ is -mean.
   scale_.CopyFromVec(stats_sumsq_);
   scale_.Scale(1.0 / count_);
   scale_.AddVecVec(-1.0, offset_, offset_, 1.0);
   // now scale_ is variance.
   // Mathematically the ApplyFloor statement should be a no-op; this is in case
   // of numerical roundoff.
   scale_.ApplyFloor(0.0);
   scale_.Add(epsilon_);
   BaseFloat power = -0.5;
   scale_.ApplyPow(power);
   // now scale_ = min(variance, epsilon)^power
   // next, multiply by the target RMS (normally 1.0).
   scale_.Scale(target_rms_);
   offset_.MulElements(scale_);
   // now offset_ is -(scale*mean).
 }
ComputeOffsetAndScale()
static void ComputeOffsetAndScale (double count, BaseFloat epsilon, const Vector< double > & stats_sum, const Vector< double > & stats_sumsq, Vector< BaseFloat > * offset, Vector< BaseFloat > * scale) static private
Copy()
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 209 of file nnet-normalize-component.h.
References Component::Add(), Component::Scale(), and Component::ZeroStats().
 { return new BatchNormComponent(*this); }
DeleteMemo()
virtual void DeleteMemo (void * memo) const inline virtual
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
It's called by NnetComputer in cases where Propagate returns a memo but there will be no backprop to consume it.
Reimplemented from Component.
Definition at line 216 of file nnet-normalize-component.h.
References Component::StoreStats().
 { delete static_cast<Memo*>(memo); }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 268 of file nnet-normalize-component.cc.
References VectorBase< Real >::AddVecVec(), VectorBase< Real >::ApplyFloor(), VectorBase< Real >::ApplyPow(), BatchNormComponent::block_dim_, BatchNormComponent::count_, BatchNormComponent::dim_, BatchNormComponent::epsilon_, VectorBase< Real >::Scale(), BatchNormComponent::stats_sum_, BatchNormComponent::stats_sumsq_, kaldi::nnet3::SummarizeVector(), BatchNormComponent::target_rms_, BatchNormComponent::test_mode_, and BatchNormComponent::Type().
{
   std::ostringstream stream;
   stream << Type() << ", dim=" << dim_ << ", block-dim=" << block_dim_
          << ", epsilon=" << epsilon_ << ", target-rms=" << target_rms_
          << ", count=" << count_
          << ", test-mode=" << (test_mode_ ? "true" : "false");
   if (count_ > 0) {
     Vector<BaseFloat> mean(stats_sum_), var(stats_sumsq_);
     mean.Scale(1.0 / count_);
     var.Scale(1.0 / count_);
     // subtract mean^2 from var.
     var.AddVecVec(-1.0, mean, mean, 1.0);
     var.ApplyFloor(0.0);
     var.ApplyPow(0.5);  // make it the stddev.
     stream << ", data-mean=" << SummarizeVector(mean)
            << ", data-stddev=" << SummarizeVector(var);
   }
   return stream.str();
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 288 of file nnet-normalize-component.cc.
References BatchNormComponent::block_dim_, BatchNormComponent::ComputeDerived(), BatchNormComponent::count_, BatchNormComponent::dim_, BatchNormComponent::epsilon_, ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), KALDI_ERR, CuVector< Real >::Resize(), BatchNormComponent::stats_sum_, BatchNormComponent::stats_sumsq_, BatchNormComponent::target_rms_, BatchNormComponent::test_mode_, and ConfigLine::UnusedValues().
{
   dim_ = -1;
   block_dim_ = -1;
   epsilon_ = 1.0e-03;
   target_rms_ = 1.0;
   test_mode_ = false;
   bool ok = cfl->GetValue("dim", &dim_);
   cfl->GetValue("block-dim", &block_dim_);
   cfl->GetValue("epsilon", &epsilon_);
   cfl->GetValue("target-rms", &target_rms_);
   cfl->GetValue("test-mode", &test_mode_);
   if (!ok || dim_ <= 0) {
     KALDI_ERR << "BatchNormComponent must have 'dim' specified, and > 0";
   }
   if (block_dim_ == -1)
     block_dim_ = dim_;
   if (!(block_dim_ > 0 && dim_ % block_dim_ == 0 &&
         epsilon_ > 0 && target_rms_ > 0))
     KALDI_ERR << "Invalid configuration in BatchNormComponent.";
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   count_ = 0;
   stats_sum_.Resize(block_dim_);
   stats_sumsq_.Resize(block_dim_);
   if (test_mode_) {
     ComputeDerived();
   }
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 176 of file nnet-normalize-component.h.
 { return dim_; }
Offset()
const CuVector<BaseFloat>& Offset () const inline
Definition at line 224 of file nnet-normalize-component.h.
Referenced by ModelCollapser::CollapseComponentsBatchnorm().
 { return offset_; }
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 177 of file nnet-normalize-component.h.
References NormalizeComponent::Info(), and NormalizeComponent::InitFromConfig().
 { return dim_; }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 400 of file nnet-normalize-component.cc.
References CuVectorBase< Real >::Add(), CuMatrixBase< Real >::AddVecToRows(), CuVectorBase< Real >::AddVecVec(), CuVectorBase< Real >::ApplyFloor(), CuVectorBase< Real >::ApplyPow(), BatchNormComponent::block_dim_, CuMatrixBase< Real >::CopyFromMat(), CuVectorBase< Real >::CopyFromVec(), BatchNormComponent::count_, CuMatrixBase< Real >::Data(), BatchNormComponent::dim_, BatchNormComponent::epsilon_, KALDI_ASSERT, KALDI_ERR, kaldi::kTrans, BatchNormComponent::Memo::mean_uvar_scale, CuMatrixBase< Real >::MulColsVec(), BatchNormComponent::Memo::num_frames, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), BatchNormComponent::offset_, kaldi::SameDim(), BatchNormComponent::scale_, CuMatrixBase< Real >::Stride(), BatchNormComponent::target_rms_, and BatchNormComponent::test_mode_.
{
   KALDI_ASSERT(SameDim(in, *out) &&
                (in.NumCols() == dim_ || in.NumCols() == block_dim_));
   if (in.NumCols() != block_dim_) {
     // if block_dim_ != dim_, we recurse; this helps keep the main code
     // simple.
     KALDI_ASSERT(in.Stride() == in.NumCols() && out->Stride() == out->NumCols());
     int32 ratio = dim_ / block_dim_, orig_rows = in.NumRows(),
         orig_cols = in.NumCols(), new_rows = orig_rows * ratio,
         new_cols = orig_cols / ratio;
     CuSubMatrix<BaseFloat> in_reshaped(in.Data(), new_rows, new_cols, new_cols),
         out_reshaped(out->Data(), new_rows, new_cols, new_cols);
     return Propagate(indexes, in_reshaped, &out_reshaped);
   }
   // From this point, we can assume that the num-cols of 'in' and 'out'
   // equals block_dim_.
   if (!test_mode_) {
     // search in the comment above for FORWARD PASS to see what is being
     // implemented here.
     // if this takes too much time due to multiple different CUDA calls,
     // we'll consider making a single kernel for some of it.
     Memo *memo = new Memo;
     int32 num_frames = in.NumRows(), dim = block_dim_;
     memo->num_frames = num_frames;
     memo->mean_uvar_scale.Resize(5, dim);
     CuSubVector<BaseFloat> mean(memo->mean_uvar_scale, 0),
         uvar(memo->mean_uvar_scale, 1),
         scale(memo->mean_uvar_scale, 2);
     mean.AddRowSumMat(1.0 / num_frames, in, 0.0);
     uvar.AddDiagMat2(1.0 / num_frames, in, kTrans, 0.0);
     scale.CopyFromVec(uvar);
     // by applying this scale at this point, we save a multiply later on.
     BaseFloat var_scale = 1.0 / (target_rms_ * target_rms_);
     scale.AddVecVec(-var_scale, mean, mean, var_scale);
     // at this point, 'scale' contains just the variance (times target-rms^{-2}).
     scale.ApplyFloor(0.0);
     scale.Add(var_scale * epsilon_);
     // Now 'scale' contains the variance floored to zero and then with epsilon
     // added [both times 1/target-rms^2].
     scale.ApplyPow(-0.5);
     // now 'scale' is the actual scale we'll use.
     // the next command will do no work if out == in, for in-place propagation.
     out->CopyFromMat(in);
     out->AddVecToRows(-1.0, mean, 1.0);
     out->MulColsVec(scale);
     return static_cast<void*>(memo);
   } else {
     if (offset_.Dim() != block_dim_) {
       if (count_ == 0)
         KALDI_ERR << "Test mode set in BatchNormComponent, but no stats.";
       else  // why was ComputeDerived() not called?
         KALDI_ERR << "Code error in BatchNormComponent";
     }
     out->CopyFromMat(in);
     out->MulColsVec(scale_);
     out->AddVecToRows(1.0, offset_, 1.0);
     return NULL;
   }
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 182 of file nnet-normalize-component.h.
References NormalizeComponent::Backprop(), NormalizeComponent::block_dim_, kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kBackpropNeedsOutput, kaldi::nnet3::kInputContiguous, kaldi::nnet3::kOutputContiguous, kaldi::nnet3::kPropagateInPlace, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kStoresStats, kaldi::nnet3::kUsesMemo, NormalizeComponent::Propagate(), NormalizeComponent::Read(), and NormalizeComponent::Write().
{
     // If the block-dim is less than the dim, we need the input and output
     // matrices to be contiguous (stride==num-cols), as we'll be reshaping
     // internally.  This is not much of a cost, because this will be used
     // in convnets where we have to do this anyway.
     return kSimpleComponent|kBackpropNeedsOutput|kPropagateInPlace|
         kBackpropInPlace|
         (block_dim_ < dim_ ? kInputContiguous|kOutputContiguous : 0)|
         (test_mode_ ? 0 : kUsesMemo|kStoresStats);
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 589 of file nnet-normalize-component.cc.
References CuVectorBase< Real >::AddVecVec(), BatchNormComponent::block_dim_, BatchNormComponent::Check(), BatchNormComponent::ComputeDerived(), BatchNormComponent::count_, BatchNormComponent::dim_, BatchNormComponent::epsilon_, kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), CuVector< Real >::Read(), kaldi::ReadBasicType(), CuVectorBase< Real >::Scale(), BatchNormComponent::stats_sum_, BatchNormComponent::stats_sumsq_, BatchNormComponent::target_rms_, and BatchNormComponent::test_mode_.
{
   ExpectOneOrTwoTokens(is, binary, "<BatchNormComponent>", "<Dim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<BlockDim>");
   ReadBasicType(is, binary, &block_dim_);
   ExpectToken(is, binary, "<Epsilon>");
   ReadBasicType(is, binary, &epsilon_);
   ExpectToken(is, binary, "<TargetRms>");
   ReadBasicType(is, binary, &target_rms_);
   ExpectToken(is, binary, "<TestMode>");
   ReadBasicType(is, binary, &test_mode_);
   ExpectToken(is, binary, "<Count>");
   ReadBasicType(is, binary, &count_);
   ExpectToken(is, binary, "<StatsMean>");
   stats_sum_.Read(is, binary);
   ExpectToken(is, binary, "<StatsVar>");
   stats_sumsq_.Read(is, binary);
   stats_sumsq_.AddVecVec(1.0, stats_sum_, stats_sum_, 1.0);
   stats_sum_.Scale(count_);
   stats_sumsq_.Scale(count_);
   ExpectToken(is, binary, "</BatchNormComponent>");
   ComputeDerived();
   Check();
 }
Scale() [1/2]
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 642 of file nnet-normalize-component.cc.
References BatchNormComponent::count_, CuVectorBase< Real >::Scale(), CuVectorBase< Real >::SetZero(), BatchNormComponent::stats_sum_, and BatchNormComponent::stats_sumsq_.
Referenced by ModelCollapser::CollapseComponentsBatchnorm(), and kaldi::nnet3::ScaleBatchnormStats().
{
   if (scale == 0) {
     count_ = 0.0;
     stats_sum_.SetZero();
     stats_sumsq_.SetZero();
   } else {
     count_ *= scale;
     stats_sum_.Scale(scale);
     stats_sumsq_.Scale(scale);
   }
 }
Scale() [2/2]
const CuVector<BaseFloat>& Scale () const inline
Definition at line 225 of file nnet-normalize-component.h.
 { return scale_; }
SetTestMode()
void SetTestMode (bool test_mode)
Definition at line 248 of file nnet-normalize-component.cc.
Referenced by kaldi::nnet3::SetBatchnormTestMode().
{
   test_mode_ = test_mode;
   ComputeDerived();
 }
StoreStats()
void StoreStats (const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, void * memo) virtual
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
It only does something for those components that have nonzero Properties()&kStoresStats.
Parameters
[in] in_value The input to the Propagate() function. Note: if the component sets the flag kPropagateInPlace, this should not be used; the empty matrix will be provided here if in-place propagation was used.
[in] out_value The output of the Propagate() function.
[in] memo The 'memo' returned by the Propagate() function; this will usually be NULL.
Reimplemented from Component.
Definition at line 549 of file nnet-normalize-component.cc.
References CuVectorBase< Real >::AddVec(), BatchNormComponent::block_dim_, BatchNormComponent::count_, CuMatrixBase< Real >::Data(), CuVectorBase< Real >::Dim(), BatchNormComponent::dim_, KALDI_ASSERT, BatchNormComponent::Memo::mean_uvar_scale, BatchNormComponent::Memo::num_frames, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuVector< Real >::Resize(), BatchNormComponent::stats_sum_, BatchNormComponent::stats_sumsq_, CuMatrixBase< Real >::Stride(), and BatchNormComponent::test_mode_.
                    {
   // in test mode this component does not store stats, it doesn't provide the
   // kStoresStats flag.
   KALDI_ASSERT(!test_mode_);
   KALDI_ASSERT(out_value.NumCols() == dim_ || out_value.NumCols() == block_dim_);
   if (out_value.NumCols() != block_dim_) {
     // if block_dim_ != dim_, we recurse; this helps keep the main code
     // simple.
     KALDI_ASSERT(out_value.Stride() == out_value.NumCols());
     int32 ratio = dim_ / block_dim_,
         orig_rows = out_value.NumRows(),
         orig_cols = out_value.NumCols(),
         new_rows = orig_rows * ratio, new_cols = orig_cols / ratio;
     CuSubMatrix<BaseFloat> out_value_reshaped(out_value.Data(), new_rows,
                                               new_cols, new_cols);
     // we'll never use in_value, so just pass it in unchanged.
     StoreStats(in_value, out_value_reshaped, memo_in);
     return;
   }
   Memo *memo = static_cast<Memo*>(memo_in);
   KALDI_ASSERT(out_value.NumRows() == memo->num_frames);
   CuSubVector<BaseFloat> mean(memo->mean_uvar_scale, 0),
       uvar(memo->mean_uvar_scale, 1);
   KALDI_ASSERT(mean.Dim() == block_dim_ && memo->num_frames > 0);
   BaseFloat num_frames = memo->num_frames;
   if (stats_sum_.Dim() != block_dim_) {
     stats_sum_.Resize(block_dim_);
     stats_sumsq_.Resize(block_dim_);
     KALDI_ASSERT(count_ == 0);
   }
   count_ += num_frames;
   stats_sum_.AddVec(num_frames, mean, 1.0);
   stats_sumsq_.AddVec(num_frames, uvar, 1.0);
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 181 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Info().
 { return "BatchNormComponent"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 614 of file nnet-normalize-component.cc.
References CuVectorBase< Real >::AddVecVec(), BatchNormComponent::block_dim_, BatchNormComponent::Check(), BatchNormComponent::count_, BatchNormComponent::dim_, BatchNormComponent::epsilon_, CuVectorBase< Real >::Scale(), BatchNormComponent::stats_sum_, BatchNormComponent::stats_sumsq_, BatchNormComponent::target_rms_, BatchNormComponent::test_mode_, CuVector< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   Check();
   WriteToken(os, binary, "<BatchNormComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<BlockDim>");
   WriteBasicType(os, binary, block_dim_);
   WriteToken(os, binary, "<Epsilon>");
   WriteBasicType(os, binary, epsilon_);
   WriteToken(os, binary, "<TargetRms>");
   WriteBasicType(os, binary, target_rms_);
   WriteToken(os, binary, "<TestMode>");
   WriteBasicType(os, binary, test_mode_);
   WriteToken(os, binary, "<Count>");
   WriteBasicType(os, binary,  count_);
   CuVector<BaseFloat> mean(stats_sum_), var(stats_sumsq_);
   if (count_ != 0) {
     mean.Scale(1.0 / count_);
     var.Scale(1.0 / count_);
     var.AddVecVec(-1.0, mean, mean, 1.0);
   }
   WriteToken(os, binary, "<StatsMean>");
   mean.Write(os, binary);
   WriteToken(os, binary, "<StatsVar>");
   var.Write(os, binary);
   WriteToken(os, binary, "</BatchNormComponent>");
 }
ZeroStats()
void ZeroStats () virtual
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Other components that store other types of statistics (e.g. regarding gradient clipping) should implement ZeroStats() also.
Reimplemented from Component.
Definition at line 666 of file nnet-normalize-component.cc.
References BatchNormComponent::count_, CuVectorBase< Real >::SetZero(), BatchNormComponent::stats_sum_, BatchNormComponent::stats_sumsq_, and BatchNormComponent::test_mode_.
{
   // We only zero the stats if we're not in test mode.  In test mode, this would
   // be dangerous as the stats are the source for the transform, and zeroing
   // them and then calling ComputeDerived() again would remove the transform
   // parameters (offset_ and scale_).
   if (!test_mode_) {
     count_ = 0.0;
     stats_sum_.SetZero();
     stats_sumsq_.SetZero();
   }
 }
Member Data Documentation
block_dim_
int32 block_dim_ private
Definition at line 261 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Backprop(), BatchNormComponent::Info(), BatchNormComponent::InitFromConfig(), BatchNormComponent::Propagate(), BatchNormComponent::Read(), BatchNormComponent::StoreStats(), and BatchNormComponent::Write().
count_
double count_ private
Definition at line 282 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Add(), BatchNormComponent::Info(), BatchNormComponent::InitFromConfig(), BatchNormComponent::Propagate(), BatchNormComponent::Read(), BatchNormComponent::Scale(), BatchNormComponent::StoreStats(), BatchNormComponent::Write(), and BatchNormComponent::ZeroStats().
dim_
int32 dim_ private
Definition at line 254 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Backprop(), BatchNormComponent::Info(), BatchNormComponent::InitFromConfig(), BatchNormComponent::Propagate(), BatchNormComponent::Read(), BatchNormComponent::StoreStats(), and BatchNormComponent::Write().
epsilon_
BaseFloat epsilon_ private
Definition at line 265 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Info(), BatchNormComponent::InitFromConfig(), BatchNormComponent::Propagate(), BatchNormComponent::Read(), and BatchNormComponent::Write().
offset_
CuVector<BaseFloat> offset_ private
Definition at line 293 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Backprop(), and BatchNormComponent::Propagate().
scale_
CuVector<BaseFloat> scale_ private
Definition at line 294 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Backprop(), and BatchNormComponent::Propagate().
stats_sum_
CuVector<double> stats_sum_ private
Definition at line 284 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Add(), BatchNormComponent::Info(), BatchNormComponent::InitFromConfig(), BatchNormComponent::Read(), BatchNormComponent::Scale(), BatchNormComponent::StoreStats(), BatchNormComponent::Write(), and BatchNormComponent::ZeroStats().
stats_sumsq_
CuVector<double> stats_sumsq_ private
Definition at line 286 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Add(), BatchNormComponent::Info(), BatchNormComponent::InitFromConfig(), BatchNormComponent::Read(), BatchNormComponent::Scale(), BatchNormComponent::StoreStats(), BatchNormComponent::Write(), and BatchNormComponent::ZeroStats().
target_rms_
BaseFloat target_rms_ private
Definition at line 270 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Backprop(), BatchNormComponent::Info(), BatchNormComponent::InitFromConfig(), BatchNormComponent::Propagate(), BatchNormComponent::Read(), and BatchNormComponent::Write().
test_mode_
bool test_mode_ private
Definition at line 278 of file nnet-normalize-component.h.
Referenced by BatchNormComponent::Backprop(), BatchNormComponent::Info(), BatchNormComponent::InitFromConfig(), BatchNormComponent::Propagate(), BatchNormComponent::Read(), BatchNormComponent::StoreStats(), BatchNormComponent::Write(), and BatchNormComponent::ZeroStats().
The documentation for this class was generated from the following files:
nnet3/nnet-normalize-component.h
nnet3/nnet-normalize-component.cc