Kaldi: BasicHolder< BasicType > Class Template Reference
BasicHolder< BasicType > Class Template Reference
"Holder types"
BasicHolder is valid for float, double, bool, and integer types.
#include <kaldi-holder-inl.h>
Public Types
typedef BasicType T
Public Member Functions
BasicHolder ()
void Clear ()
bool Read (std::istream &is)
T & Value ()
void Swap (BasicHolder< T > *other)
bool ExtractRange (const BasicHolder< T > &other, const std::string &range)
~BasicHolder ()
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (BasicHolder)
Private Attributes
T t_
Detailed Description
template<class BasicType>
class kaldi::BasicHolder< BasicType >
BasicHolder is valid for float, double, bool, and integer types.
There will be a compile time error otherwise, because we make sure that the {Write, Read}BasicType functions do not get instantiated for other types.
Definition at line 127 of file kaldi-holder-inl.h.
Member Typedef Documentation
T
typedef BasicType T
Definition at line 129 of file kaldi-holder-inl.h.
Constructor & Destructor Documentation
BasicHolder()
BasicHolder () inline
Definition at line 131 of file kaldi-holder-inl.h.
 : t_(static_cast<T>(-1)) { }
~BasicHolder()
~BasicHolder () inline
Definition at line 211 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::KALDI_DISALLOW_COPY_AND_ASSIGN().
 { }
Member Function Documentation
Clear()
void Clear () inline
Definition at line 146 of file kaldi-holder-inl.h.
 { }
ExtractRange()
bool ExtractRange (const BasicHolder< T > & other, const std::string & range) inline
Definition at line 206 of file kaldi-holder-inl.h.
References KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 196 of file kaldi-holder-inl.h.
 { return true; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (BasicHolder< BasicType >) private
Read()
bool Read (std::istream & is) inline
Definition at line 149 of file kaldi-holder-inl.h.
References kaldi::CharToString(), kaldi::InitKaldiInputStream(), KALDI_WARN, kaldi::ReadBasicType(), and KaldiObjectHolder< KaldiType >::t_.
{
     bool is_binary;
     if (!InitKaldiInputStream(is, &is_binary)) {
       KALDI_WARN << "Reading Table object [integer type], failed reading binary"
           " header\n";
       return false;
     }
     try {
       int c;
       if (!is_binary) {  // This is to catch errors, the class would work
         // without it..
         // Eat up any whitespace and make sure it's not newline.
         while (isspace((c = is.peek())) && c != static_cast<int>('\n')) {
           is.get();
         }
         if (is.peek() == '\n') {
           KALDI_WARN << "Found newline but expected basic type.";
           return false;  // This is just to catch a more-
           // likely-than average type of error (empty line before the token),
           // since ReadBasicType will eat it up.
         }
       }
       ReadBasicType(is, is_binary, &t_);
       if (!is_binary) {  // This is to catch errors, the class would work
         // without it..
         // make sure there is a newline.
         while (isspace((c = is.peek())) && c != static_cast<int>('\n')) {
           is.get();
         }
         if (is.peek() != '\n') {
           KALDI_WARN << "BasicHolder::Read, expected newline, got "
                      << CharToString(is.peek()) << ", position " << is.tellg();
           return false;
         }
         is.get();  // Consume the newline.
       }
       return true;
     } catch(const std::exception &e) {
       KALDI_WARN << "Exception caught reading Table object. " << e.what();
       return false;
     }
   }
Swap()
void Swap (BasicHolder< T > * other) inline
Definition at line 202 of file kaldi-holder-inl.h.
References kaldi::swap(), KaldiObjectHolder< KaldiType >::t_, and BasicHolder< BasicType >::t_.
{
     std::swap(t_, other->t_);
   }
Value()
T& Value () inline
Definition at line 198 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
              {
     return t_;
   }
Write()
static bool Write (std::ostream & os, bool binary, const T & t) inline static
Definition at line 133 of file kaldi-holder-inl.h.
References kaldi::InitKaldiOutputStream(), KALDI_WARN, and kaldi::WriteBasicType().
{
     InitKaldiOutputStream(os, binary);  // Puts binary header if binary mode.
     try {
       WriteBasicType(os, binary, t);
       if (!binary) os << '\n';  // Makes output format more readable and
       // easier to manipulate.
       return os.good();
     } catch(const std::exception &e) {
       KALDI_WARN << "Exception caught writing Table object. " << e.what();
       return false;  // Write failure.
     }
   }
Member Data Documentation
t_
T t_ private
Definition at line 215 of file kaldi-holder-inl.h.
Referenced by BasicHolder< BasicType >::Swap().
The documentation for this class was generated from the following file:
util/kaldi-holder-inl.h