Kaldi: BlockAffineComponent Class Reference
BlockAffineComponent Class Reference
This class implements an affine transform using a block diagonal matrix e.g., one whose weight matrix is all zeros except for blocks on the diagonal.
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
BlockAffineComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
BlockAffineComponent (const BlockAffineComponent &other)
BlockAffineComponent (const RepeatedAffineComponent &rac)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
virtual void FreezeNaturalGradient (bool freeze)
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Attributes
CuMatrix< BaseFloat > linear_params_
CuVector< BaseFloat > bias_params_
int32 num_blocks_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Private Member Functions
void Init (int32 input_dim, int32 output_dim, int32 num_blocks, BaseFloat param_stddev, BaseFloat bias_mean, BaseFloat bias_stddev)
const BlockAffineComponent & operator= (const BlockAffineComponent &other)
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Detailed Description
This class implements an affine transform using a block diagonal matrix e.g., one whose weight matrix is all zeros except for blocks on the diagonal.
All these blocks have the same dimensions. input-dim: num cols of block diagonal matrix. output-dim: num rows of block diagonal matrix. num-blocks: number of blocks in diagonal of the matrix. num-blocks must divide both input-dim and output-dim
Definition at line 505 of file nnet-simple-component.h.
Constructor & Destructor Documentation
BlockAffineComponent() [1/3]
BlockAffineComponent () inline
Definition at line 513 of file nnet-simple-component.h.
Referenced by BlockAffineComponent::Copy(), and RepeatedAffineComponent::LinearParams().
 { }
BlockAffineComponent() [2/3]
BlockAffineComponent (const BlockAffineComponent & other) explicit
Definition at line 1652 of file nnet-simple-component.cc.
                                                                             :
   UpdatableComponent(other),
   linear_params_(other.linear_params_),
   bias_params_(other.bias_params_),
   num_blocks_(other.num_blocks_) {}
BlockAffineComponent() [3/3]
BlockAffineComponent (const RepeatedAffineComponent & rac) explicit
Definition at line 1658 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, RepeatedAffineComponent::bias_params_, CuMatrixBase< Real >::CopyFromMat(), CuVectorBase< Real >::CopyFromVec(), BlockAffineComponent::linear_params_, RepeatedAffineComponent::linear_params_, and BlockAffineComponent::num_blocks_.
                                                                              :
   UpdatableComponent(rac),
   linear_params_(rac.num_repeats_ * rac.linear_params_.NumRows(),
                  rac.linear_params_.NumCols(), kUndefined),
   bias_params_(rac.num_repeats_ * rac.linear_params_.NumRows(), kUndefined),
   num_blocks_(rac.num_repeats_) {
   // copy rac's linear_params_ and bias_params_ to this.
   int32 num_rows_in_block = rac.linear_params_.NumRows();
   for(int32 block_counter = 0; block_counter < num_blocks_; block_counter++) {
     int32 row_offset = block_counter * num_rows_in_block;
     CuSubMatrix<BaseFloat> block = this->linear_params_.RowRange(row_offset,
                                                                  num_rows_in_block);
     block.CopyFromMat(rac.linear_params_);
     CuSubVector<BaseFloat> block_bias = this->bias_params_.Range(row_offset,
                                                                  num_rows_in_block);
     block_bias.CopyFromVec(rac.bias_params_);
   }
 }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1862 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, KALDI_ASSERT, and BlockAffineComponent::linear_params_.
{
   const BlockAffineComponent *other =
     dynamic_cast<const BlockAffineComponent *>(&other_in);
   KALDI_ASSERT(other != NULL);
   linear_params_.AddMat(alpha, other->linear_params_);
   bias_params_.AddVec(alpha, other->bias_params_);
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 1766 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, CuMatrixBase< Real >::ColRange(), kaldi::DeletePointers(), kaldi::kNoTrans, kaldi::kTrans, UpdatableComponent::learning_rate_, BlockAffineComponent::linear_params_, and BlockAffineComponent::num_blocks_.
{
   BlockAffineComponent *to_update = dynamic_cast<BlockAffineComponent*>(to_update_in);
   const int32 num_rows_in_block = linear_params_.NumRows() / num_blocks_;
   const int32 num_cols_in_block = linear_params_.NumCols();
   // Propagate the derivative back to the input.
   // add with coefficient 1.0 since property kBackpropAdds is true.
   // If we wanted to add with coefficient 0.0 we'd need to zero the
   // in_deriv, in case of infinities.
   if (in_deriv) {
     std::vector<CuSubMatrix<BaseFloat> *> in_deriv_batch, out_deriv_batch, linear_params_batch;
     for(int block_counter = 0; block_counter < num_blocks_; block_counter++) {
       CuSubMatrix<BaseFloat> *in_deriv_block =
         new CuSubMatrix<BaseFloat>(in_deriv->ColRange(block_counter * num_cols_in_block,
                                                       num_cols_in_block));
       in_deriv_batch.push_back(in_deriv_block);
       CuSubMatrix<BaseFloat> *out_deriv_block =
         new CuSubMatrix<BaseFloat>(out_deriv.ColRange(block_counter * num_rows_in_block,
                                                        num_rows_in_block));
       out_deriv_batch.push_back(out_deriv_block);
       CuSubMatrix<BaseFloat> *linear_params_block =
         new CuSubMatrix<BaseFloat>(linear_params_.RowRange(block_counter * num_rows_in_block,
                                                           num_rows_in_block));
       linear_params_batch.push_back(linear_params_block);
     }
     AddMatMatBatched<BaseFloat>(1.0, in_deriv_batch, out_deriv_batch, kNoTrans,
                                 linear_params_batch, kNoTrans, 1.0);
     DeletePointers(&in_deriv_batch);
     DeletePointers(&out_deriv_batch);
     DeletePointers(&linear_params_batch);
   }
   if (to_update != NULL) {
     { // linear params update
       std::vector<CuSubMatrix<BaseFloat> *> in_value_batch,
         out_deriv_batch, linear_params_batch;
       for (int block_counter = 0; block_counter < num_blocks_; block_counter++) {
         CuSubMatrix<BaseFloat> *in_value_block =
           new CuSubMatrix<BaseFloat>(in_value.ColRange(block_counter * num_cols_in_block,
                                                        num_cols_in_block));
         in_value_batch.push_back(in_value_block);
         CuSubMatrix<BaseFloat> *out_deriv_block =
           new CuSubMatrix<BaseFloat>(out_deriv.ColRange(block_counter * num_rows_in_block,
                                                         num_rows_in_block));
         out_deriv_batch.push_back(out_deriv_block);
         CuSubMatrix<BaseFloat> *linear_params_block =
           new CuSubMatrix<BaseFloat>(to_update->linear_params_.RowRange(block_counter * num_rows_in_block,
                                                                         num_rows_in_block));
         linear_params_batch.push_back(linear_params_block);
       }
       AddMatMatBatched<BaseFloat>(to_update->learning_rate_,
                                   linear_params_batch,
                                   out_deriv_batch, kTrans,
                                   in_value_batch, kNoTrans, 1.0);
       DeletePointers(&in_value_batch);
       DeletePointers(&out_deriv_batch);
       DeletePointers(&linear_params_batch);
     } // end linear params update
     { // bias update
       to_update->bias_params_.AddRowSumMat(to_update->learning_rate_,
                                            out_deriv, 1.0);
     } // end bias update
   }
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 1677 of file nnet-simple-component.cc.
References BlockAffineComponent::BlockAffineComponent().
{
   BlockAffineComponent *ans = new BlockAffineComponent(*this);
   return ans;
 }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 1880 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, kaldi::kTrans, BlockAffineComponent::linear_params_, kaldi::TraceMatMat(), and kaldi::VecVec().
{
   const BlockAffineComponent *other =
     dynamic_cast<const BlockAffineComponent*>(&other_in);
   return TraceMatMat(linear_params_, other->linear_params_, kTrans) +
     VecVec(bias_params_, other->bias_params_);
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 1682 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, UpdatableComponent::Info(), BlockAffineComponent::linear_params_, BlockAffineComponent::num_blocks_, and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info()
          << ", num-blocks=" << num_blocks_;
   PrintParameterStats(stream, "linear-params", linear_params_);
   PrintParameterStats(stream, "bias", bias_params_, true);
   return stream.str();
 }
Init()
void Init (int32 input_dim, int32 output_dim, int32 num_blocks, BaseFloat param_stddev, BaseFloat bias_mean, BaseFloat bias_stddev) private
Definition at line 1691 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, KALDI_ASSERT, BlockAffineComponent::linear_params_, and BlockAffineComponent::num_blocks_.
Referenced by BlockAffineComponent::InitFromConfig().
{
   KALDI_ASSERT(input_dim > 0 && output_dim > 0 && num_blocks >= 1);
   KALDI_ASSERT(output_dim % num_blocks == 0 && input_dim % num_blocks == 0);
   const int32 num_columns_per_block = input_dim / num_blocks;
   linear_params_.Resize(output_dim, num_columns_per_block);
   bias_params_.Resize(output_dim);
   KALDI_ASSERT(param_stddev >= 0.0 && bias_stddev >= 0.0);
   linear_params_.SetRandn();
   linear_params_.Scale(param_stddev);
   bias_params_.SetRandn();
   bias_params_.Scale(bias_stddev);
   bias_params_.Add(bias_mean);
   num_blocks_ = num_blocks;
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 1709 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), BlockAffineComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), KALDI_ERR, BlockAffineComponent::Type(), and ConfigLine::WholeLine().
{
   int32 input_dim = -1, output_dim = -1, num_blocks = -1;
   if(!cfl->GetValue("input-dim", &input_dim) ||
      !cfl->GetValue("output-dim", &output_dim) ||
      !cfl->GetValue("num-blocks", &num_blocks))
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   InitLearningRatesFromConfig(cfl);
   BaseFloat param_stddev = 1.0 / std::sqrt(input_dim / num_blocks),
       bias_mean = 0.0, bias_stddev = 1.0;
   cfl->GetValue("param-stddev", &param_stddev);
   cfl->GetValue("bias-stddev", &bias_stddev);
   cfl->GetValue("bias-mean", &bias_mean);
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(input_dim, output_dim, num_blocks,
        param_stddev, bias_mean, bias_stddev);
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 507 of file nnet-simple-component.h.
 { return linear_params_.NumCols() * num_blocks_; }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 1915 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, and BlockAffineComponent::linear_params_.
Referenced by BlockAffineComponent::UnVectorize(), and BlockAffineComponent::Vectorize().
{
   return linear_params_.NumCols() * linear_params_.NumRows() + bias_params_.Dim();
 }
operator=()
const BlockAffineComponent& operator= (const BlockAffineComponent & other) private
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 508 of file nnet-simple-component.h.
References Component::Info(), and PnormComponent::InitFromConfig().
 { return linear_params_.NumRows(); }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 1870 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, BlockAffineComponent::linear_params_, CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
{
   CuMatrix<BaseFloat> temp_linear_params(linear_params_);
   temp_linear_params.SetRandn();
   linear_params_.AddMat(stddev, temp_linear_params);
   CuVector<BaseFloat> temp_bias_params(bias_params_);
   temp_bias_params.SetRandn();
   bias_params_.AddVec(stddev, temp_bias_params);
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 1731 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyRowsFromVec(), kaldi::DeletePointers(), kaldi::kNoTrans, kaldi::kTrans, BlockAffineComponent::linear_params_, and BlockAffineComponent::num_blocks_.
{
   out->CopyRowsFromVec(bias_params_);
   // block_dimension is both the number of columns, and the number of rows,
   // of a block.
   int32 num_rows_in_block = linear_params_.NumRows() / num_blocks_;
   int32 num_cols_in_block = linear_params_.NumCols();
   std::vector<CuSubMatrix<BaseFloat> *> in_batch, out_batch,
     linear_params_batch;
   for(int block_counter = 0; block_counter < num_blocks_; block_counter++) {
     CuSubMatrix<BaseFloat> *in_block =
       new CuSubMatrix<BaseFloat>(in.ColRange(block_counter * num_cols_in_block,
                                    num_cols_in_block));
     in_batch.push_back(in_block);
     CuSubMatrix<BaseFloat> *out_block =
       new CuSubMatrix<BaseFloat>(out->ColRange(block_counter * num_rows_in_block,
                                     num_rows_in_block));
     out_batch.push_back(out_block);
     CuSubMatrix<BaseFloat> *linear_params_block =
       new CuSubMatrix<BaseFloat>(linear_params_.RowRange(block_counter * num_rows_in_block,
                                               num_rows_in_block));
     linear_params_batch.push_back(linear_params_block);
   }
   AddMatMatBatched<BaseFloat>(1.0, out_batch, in_batch, kNoTrans,
                               linear_params_batch, kTrans, 1.0);
   DeletePointers(&in_batch);
   DeletePointers(&out_batch);
   DeletePointers(&linear_params_batch);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 515 of file nnet-simple-component.h.
References Component::Add(), PnormComponent::Backprop(), PnormComponent::Copy(), kaldi::nnet3::DotProduct(), kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kUpdatableComponent, kaldi::nnet3::NumParameters(), kaldi::nnet3::PerturbParams(), PnormComponent::Propagate(), PnormComponent::Read(), Component::Scale(), and PnormComponent::Write().
{
     return kSimpleComponent|kUpdatableComponent|
       kBackpropNeedsInput|kBackpropAdds;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 1887 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, BlockAffineComponent::linear_params_, BlockAffineComponent::num_blocks_, kaldi::PeekToken(), kaldi::ReadBasicType(), and UpdatableComponent::ReadUpdatableCommon().
{
   ReadUpdatableCommon(is, binary);  // read opening tag and learning rate.
   ExpectToken(is, binary, "<NumBlocks>");
   ReadBasicType(is, binary, &num_blocks_);
   ExpectToken(is, binary, "<LinearParams>");
   linear_params_.Read(is, binary);
   ExpectToken(is, binary, "<BiasParams>");
   bias_params_.Read(is, binary);
   if (PeekToken(is, binary) == 'I') {
     // for back compatibility; we don't write this here any
     // more as it's written and read in Write/ReadUpdatableCommon
     ExpectToken(is, binary, "<IsGradient>");
     ReadBasicType(is, binary, &is_gradient_);
   }
   ExpectToken(is, binary, "</BlockAffineComponent>");
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1852 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, and BlockAffineComponent::linear_params_.
{
   if (scale == 0.0) {
     linear_params_.SetZero();
     bias_params_.SetZero();
   } else {
     linear_params_.Scale(scale);
     bias_params_.Scale(scale);
   }
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 514 of file nnet-simple-component.h.
Referenced by BlockAffineComponent::InitFromConfig().
 { return "BlockAffineComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 1927 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, VectorBase< Real >::Dim(), KALDI_ASSERT, BlockAffineComponent::linear_params_, BlockAffineComponent::NumParameters(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params.Dim() == this->NumParameters());
   int32 num_linear_params = linear_params_.NumCols() * linear_params_.NumRows();
   int32 num_bias_params = bias_params_.Dim();
   linear_params_.CopyRowsFromVec(params.Range(0, num_linear_params));
   bias_params_.CopyFromVec(params.Range(num_linear_params, num_bias_params));
 }
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 1919 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, VectorBase< Real >::Dim(), KALDI_ASSERT, BlockAffineComponent::linear_params_, BlockAffineComponent::NumParameters(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params->Dim() == this->NumParameters());
   int32 num_linear_params = linear_params_.NumCols() * linear_params_.NumRows();
   int32 num_bias_params = bias_params_.Dim();
   params->Range(0, num_linear_params).CopyRowsFromMat(linear_params_);
   params->Range(num_linear_params, num_bias_params).CopyFromVec(bias_params_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 1904 of file nnet-simple-component.cc.
References BlockAffineComponent::bias_params_, BlockAffineComponent::linear_params_, BlockAffineComponent::num_blocks_, kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate
   WriteToken(os, binary, "<NumBlocks>");
   WriteBasicType(os, binary, num_blocks_);
   WriteToken(os, binary, "<LinearParams>");
   linear_params_.Write(os, binary);
   WriteToken(os, binary, "<BiasParams>");
   bias_params_.Write(os, binary);
   WriteToken(os, binary, "</BlockAffineComponent>");
 }
Member Data Documentation
bias_params_
CuVector<BaseFloat> bias_params_ protected
Definition at line 559 of file nnet-simple-component.h.
Referenced by BlockAffineComponent::Add(), BlockAffineComponent::Backprop(), BlockAffineComponent::BlockAffineComponent(), BlockAffineComponent::DotProduct(), BlockAffineComponent::Info(), BlockAffineComponent::Init(), BlockAffineComponent::NumParameters(), BlockAffineComponent::PerturbParams(), BlockAffineComponent::Propagate(), BlockAffineComponent::Read(), BlockAffineComponent::Scale(), BlockAffineComponent::UnVectorize(), BlockAffineComponent::Vectorize(), and BlockAffineComponent::Write().
linear_params_
CuMatrix<BaseFloat> linear_params_ protected
Definition at line 558 of file nnet-simple-component.h.
Referenced by BlockAffineComponent::Add(), BlockAffineComponent::Backprop(), BlockAffineComponent::BlockAffineComponent(), BlockAffineComponent::DotProduct(), BlockAffineComponent::Info(), BlockAffineComponent::Init(), BlockAffineComponent::NumParameters(), BlockAffineComponent::PerturbParams(), BlockAffineComponent::Propagate(), BlockAffineComponent::Read(), BlockAffineComponent::Scale(), BlockAffineComponent::UnVectorize(), BlockAffineComponent::Vectorize(), and BlockAffineComponent::Write().
num_blocks_
int32 num_blocks_ protected
Definition at line 560 of file nnet-simple-component.h.
Referenced by BlockAffineComponent::Backprop(), BlockAffineComponent::BlockAffineComponent(), BlockAffineComponent::Info(), BlockAffineComponent::Init(), BlockAffineComponent::Propagate(), BlockAffineComponent::Read(), and BlockAffineComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc