Kaldi: SpectrogramComputer Class Reference
SpectrogramComputer Class Reference
FeatureExtraction
Class for computing spectrogram features.
#include <feature-spectrogram.h>
Public Types
typedef SpectrogramOptions Options
Public Member Functions
SpectrogramComputer (const SpectrogramOptions &opts)
SpectrogramComputer (const SpectrogramComputer &other)
const FrameExtractionOptions & GetFrameOptions () const
int32 Dim () const
bool NeedRawLogEnergy ()
void Compute (BaseFloat signal_log_energy, BaseFloat vtln_warp, VectorBase< BaseFloat > *signal_frame, VectorBase< BaseFloat > *feature)
Function that computes one frame of spectrogram features from one frame of signal.
~SpectrogramComputer ()
Private Member Functions
SpectrogramComputer & operator= (const SpectrogramComputer &other)
Private Attributes
SpectrogramOptions opts_
BaseFloat log_energy_floor_
SplitRadixRealFft< BaseFloat > * srfft_
Detailed Description
Class for computing spectrogram features.
Definition at line 61 of file feature-spectrogram.h.
Member Typedef Documentation
Options
typedef SpectrogramOptions Options
Definition at line 63 of file feature-spectrogram.h.
Constructor & Destructor Documentation
SpectrogramComputer() [1/2]
SpectrogramComputer (const SpectrogramOptions & opts) explicit
Definition at line 27 of file feature-spectrogram.cc.
References SpectrogramOptions::energy_floor, SpectrogramOptions::frame_opts, kaldi::Log(), SpectrogramComputer::log_energy_floor_, FrameExtractionOptions::PaddedWindowSize(), and SpectrogramComputer::srfft_.
     : opts_(opts), srfft_(NULL) {
   if (opts.energy_floor > 0.0)
     log_energy_floor_ = Log(opts.energy_floor);
   int32 padded_window_size = opts.frame_opts.PaddedWindowSize();
   if ((padded_window_size & (padded_window_size-1)) == 0)  // Is a power of two
     srfft_ = new SplitRadixRealFft<BaseFloat>(padded_window_size);
 }
SpectrogramComputer() [2/2]
SpectrogramComputer (const SpectrogramComputer & other)
Definition at line 37 of file feature-spectrogram.cc.
References SpectrogramComputer::srfft_.
                                                                         :
     opts_(other.opts_), log_energy_floor_(other.log_energy_floor_), srfft_(NULL) {
   if (other.srfft_ != NULL)
     srfft_ = new SplitRadixRealFft<BaseFloat>(*other.srfft_);
 }
~SpectrogramComputer()
~SpectrogramComputer ()
Definition at line 43 of file feature-spectrogram.cc.
References SpectrogramComputer::srfft_.
{
   delete srfft_;
 }
Member Function Documentation
Compute()
void Compute (BaseFloat signal_log_energy, BaseFloat vtln_warp, VectorBase< BaseFloat > * signal_frame, VectorBase< BaseFloat > * feature)
Function that computes one frame of spectrogram features from one frame of signal.
Parameters
[in] signal_raw_log_energy The log-energy of the frame of the signal prior to windowing and pre-emphasis, or log(numeric_limits<float>::min()), whichever is greater. Must be ignored by this function if this class returns false from this->NeedsRawLogEnergy().
[in] vtln_warp This is ignored by this function, it's only needed for interface compatibility.
[in] signal_frame One frame of the signal, as extracted using the function ExtractWindow() using the options returned by this->GetFrameOptions(). The function will use the vector as a workspace, which is why it's a non-const pointer.
[out] feature Pointer to a vector of size this->Dim(), to which the computed feature will be written.
Definition at line 47 of file feature-spectrogram.cc.
References VectorBase< Real >::ApplyFloor(), kaldi::ComputePowerSpectrum(), VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Data(), VectorBase< Real >::Dim(), SpectrogramComputer::Dim(), SpectrogramOptions::energy_floor, SpectrogramOptions::frame_opts, KALDI_ASSERT, kaldi::Log(), SpectrogramComputer::log_energy_floor_, SpectrogramComputer::opts_, FrameExtractionOptions::PaddedWindowSize(), SpectrogramOptions::raw_energy, kaldi::RealFft(), SpectrogramComputer::srfft_, and kaldi::VecVec().
{
   KALDI_ASSERT(signal_frame->Dim() == opts_.frame_opts.PaddedWindowSize() &&
                feature->Dim() == this->Dim());
   // Compute energy after window function (not the raw one)
   if (!opts_.raw_energy)
     signal_log_energy = Log(std::max(VecVec(*signal_frame, *signal_frame),
                                      std::numeric_limits<float>::epsilon()));
   if (srfft_ != NULL)  // Compute FFT using split-radix algorithm.
     srfft_->Compute(signal_frame->Data(), true);
   else  // An alternative algorithm that works for non-powers-of-two
     RealFft(signal_frame, true);
   // Convert the FFT into a power spectrum.
   ComputePowerSpectrum(signal_frame);
   SubVector<BaseFloat> power_spectrum(*signal_frame,
                                       0, signal_frame->Dim() / 2 + 1);
   power_spectrum.ApplyFloor(std::numeric_limits<float>::epsilon());
   power_spectrum.ApplyLog();
   feature->CopyFromVec(power_spectrum);
   if (opts_.energy_floor > 0.0 && signal_log_energy < log_energy_floor_)
     signal_log_energy = log_energy_floor_;
   // The zeroth spectrogram component is always set to the signal energy,
   // instead of the square of the constant component of the signal.
   (*feature)(0) = signal_log_energy;
 }
Dim()
int32 Dim () const inline
Definition at line 71 of file feature-spectrogram.h.
Referenced by SpectrogramComputer::Compute().
 { return opts_.frame_opts.PaddedWindowSize() / 2 + 1; }
GetFrameOptions()
const FrameExtractionOptions& GetFrameOptions () const inline
Definition at line 67 of file feature-spectrogram.h.
{
     return opts_.frame_opts;
   }
NeedRawLogEnergy()
bool NeedRawLogEnergy () inline
Definition at line 73 of file feature-spectrogram.h.
 { return opts_.raw_energy; }
operator=()
SpectrogramComputer& operator= (const SpectrogramComputer & other) private
Member Data Documentation
log_energy_floor_
BaseFloat log_energy_floor_ private
Definition at line 103 of file feature-spectrogram.h.
Referenced by SpectrogramComputer::Compute(), and SpectrogramComputer::SpectrogramComputer().
opts_
SpectrogramOptions opts_ private
Definition at line 102 of file feature-spectrogram.h.
Referenced by SpectrogramComputer::Compute().
srfft_
SplitRadixRealFft<BaseFloat>* srfft_ private
Definition at line 104 of file feature-spectrogram.h.
Referenced by SpectrogramComputer::Compute(), SpectrogramComputer::SpectrogramComputer(), and SpectrogramComputer::~SpectrogramComputer().
The documentation for this class was generated from the following files:
feat/feature-spectrogram.h
feat/feature-spectrogram.cc