Kaldi: AffineXformStats Class Reference
AffineXformStats Class Reference
#include <transform-common.h>
Public Member Functions
AffineXformStats ()
void Init (int32 dim, int32 num_gs)
int32 Dim () const
void SetZero ()
void CopyStats (const AffineXformStats &other)
void Add (const AffineXformStats &other)
void Write (std::ostream &out, bool binary) const
void Read (std::istream &in, bool binary, bool add)
AffineXformStats (const AffineXformStats &other)
Public Attributes
double beta_
beta_ is the occupation count.
Matrix< double > K_
K_ is the summed outer product of [mean times inverse variance] with [extended data], scaled by the occupation counts; dimension is dim by (dim+1)
std::vector< SpMatrix< double > > G_
G_ is the outer product of extended-data, scaled by inverse variance, for each dimension.
int32 dim_
dim_ is the feature dimension.
Detailed Description
Definition at line 30 of file transform-common.h.
Constructor & Destructor Documentation
AffineXformStats() [1/2]
AffineXformStats () inline
Definition at line 44 of file transform-common.h.
References AffineXformStats::Init().
 : beta_(0.0), dim_(0.0) {}
AffineXformStats() [2/2]
AffineXformStats (const AffineXformStats & other) inline
Definition at line 52 of file transform-common.h.
References kaldi::ApplyAffineTransform(), and kaldi::ComposeTransforms().
                                                  : beta_(other.beta_),
                                                    K_(other.K_),
                                                    G_(other.G_),
                                                    dim_(other.dim_) {}
Member Function Documentation
Add()
void Add (const AffineXformStats & other)
Definition at line 123 of file transform-common.cc.
References MatrixBase< Real >::AddMat(), AffineXformStats::beta_, AffineXformStats::dim_, AffineXformStats::G_, rnnlm::i, AffineXformStats::K_, KALDI_ASSERT, and kaldi::kNoTrans.
Referenced by AffineXformStats::Dim().
{
   KALDI_ASSERT(G_.size() == other.G_.size());
   KALDI_ASSERT(dim_ == other.dim_);
   beta_ += other.beta_;
   K_.AddMat(1.0, other.K_, kNoTrans);
   for (size_t i = 0; i < G_.size(); i++)
     G_[i].AddSp(1.0, other.G_[i]);
 }
CopyStats()
void CopyStats (const AffineXformStats & other)
Definition at line 114 of file transform-common.cc.
References AffineXformStats::beta_, MatrixBase< Real >::CopyFromMat(), AffineXformStats::dim_, AffineXformStats::G_, rnnlm::i, AffineXformStats::K_, KALDI_ASSERT, and kaldi::kNoTrans.
Referenced by AffineXformStats::Dim().
{
   KALDI_ASSERT(G_.size() == other.G_.size());
   KALDI_ASSERT(dim_ == other.dim_);
   beta_ = other.beta_;
   K_.CopyFromMat(other.K_, kNoTrans);
   for (size_t i = 0; i < G_.size(); i++)
     G_[i].CopyFromSp(other.G_[i]);
 }
Dim()
int32 Dim () const inline
Definition at line 46 of file transform-common.h.
References AffineXformStats::Add(), AffineXformStats::CopyStats(), AffineXformStats::dim_, AffineXformStats::Read(), AffineXformStats::SetZero(), and AffineXformStats::Write().
Referenced by kaldi::ApplyFeatureTransformToStats(), kaldi::ApplyModelTransformToStats(), FmllrDiagGmmAccs::CommitSingleFrameStats(), CompressedAffineXformStats::CopyFromAffineXformStats(), CompressedAffineXformStats::CopyToAffineXformStats(), and FmllrDiagGmmAccs::DataHasChanged().
 { return dim_; }
Init()
void Init (int32 dim, int32 num_gs)
Definition at line 28 of file transform-common.cc.
References AffineXformStats::beta_, AffineXformStats::dim_, AffineXformStats::G_, rnnlm::i, AffineXformStats::K_, KALDI_WARN, kaldi::kSetZero, and Matrix< Real >::Resize().
Referenced by AffineXformStats::AffineXformStats(), CompressedAffineXformStats::CopyToAffineXformStats(), and FmllrDiagGmmAccs::Init().
{
   if (dim == 0) {
     if (num_gs != 0) {
       KALDI_WARN << "Ignoring 'num_gs' (=" << num_gs << ") argument since "
                  << "dim = 0.";
     }
     beta_ = 0.0;
     K_.Resize(0, 0);
     G_.clear();
     dim_ = 0;
   } else {
     beta_ = 0.0;
     K_.Resize(dim, dim + 1, kSetZero);
     G_.resize(num_gs);
     for (int32 i = 0; i < num_gs; i++)
       G_[i].Resize(dim + 1, kSetZero);
     dim_ = dim;
   }
 }
Read()
void Read (std::istream & in, bool binary, bool add)
Definition at line 69 of file transform-common.cc.
References MatrixBase< Real >::AddMat(), AffineXformStats::beta_, MatrixBase< Real >::CopyFromMat(), SpMatrix< Real >::CopyFromSp(), AffineXformStats::dim_, kaldi::ExpectToken(), AffineXformStats::G_, rnnlm::i, AffineXformStats::K_, kaldi::kNoTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), PackedMatrix< Real >::NumRows(), PackedMatrix< Real >::Read(), Matrix< Real >::Read(), kaldi::ReadBasicType(), SpMatrix< Real >::Resize(), and Matrix< Real >::Resize().
Referenced by AffineXformStats::Dim(), and FmllrDiagGmmAccs::Read().
{
   ExpectToken(in, binary, "<DIMENSION>");
   ReadBasicType(in, binary, &dim_);
   ExpectToken(in, binary, "<BETA>");
   ReadBasicType(in, binary, &beta_);
   ExpectToken(in, binary, "<K>");
   Matrix<BaseFloat> tmp_k;
   tmp_k.Read(in, binary);
   K_.Resize(tmp_k.NumRows(), tmp_k.NumCols());
   if (add) {
     Matrix<double> tmp_k_d(tmp_k);
     K_.AddMat(1.0, tmp_k_d, kNoTrans);
   } else {
     K_.CopyFromMat(tmp_k, kNoTrans);
   }
   ExpectToken(in, binary, "<G>");
   int32 g_size;
   ReadBasicType(in, binary, &g_size);
   G_.resize(g_size);
   SpMatrix<BaseFloat> tmp_g;
   SpMatrix<double> tmp_g_d;
   if (add) { tmp_g_d.Resize(tmp_g.NumRows()); }
   for (size_t i = 0; i < G_.size(); i++) {
     tmp_g.Read(in, binary, false /*no add*/);
     G_[i].Resize(tmp_g.NumRows());
     if (add) {
       tmp_g_d.CopyFromSp(tmp_g);
       G_[i].AddSp(1.0, tmp_g_d);
     } else {
       G_[i].CopyFromSp(tmp_g);
     }
   }
 }
SetZero()
void SetZero ()
Definition at line 105 of file transform-common.cc.
References AffineXformStats::beta_, AffineXformStats::G_, AffineXformStats::K_, and MatrixBase< Real >::SetZero().
Referenced by AffineXformStats::Dim().
{
   beta_ = 0.0;
   K_.SetZero();
   for (std::vector< SpMatrix<double> >::iterator it = G_.begin(),
       end = G_.end(); it != end; ++it) {
     it->SetZero();
   }
 }
Write()
void Write (std::ostream & out, bool binary) const
Definition at line 48 of file transform-common.cc.
References AffineXformStats::beta_, AffineXformStats::dim_, AffineXformStats::G_, AffineXformStats::K_, PackedMatrix< Real >::Write(), MatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by AffineXformStats::Dim().
{
   WriteToken(out, binary, "<DIMENSION>");
   WriteBasicType(out, binary, dim_);
   if (!binary) out << '\n';
   WriteToken(out, binary, "<BETA>");
   WriteBasicType(out, binary, beta_);
   if (!binary) out << '\n';
   WriteToken(out, binary, "<K>");
   Matrix<BaseFloat> tmp_k(K_);
   tmp_k.Write(out, binary);
   WriteToken(out, binary, "<G>");
   int32 g_size = static_cast<int32>(G_.size());
   WriteBasicType(out, binary, g_size);
   if (!binary) out << '\n';
   for (std::vector< SpMatrix<double> >::const_iterator itr = G_.begin(),
       end = G_.end(); itr != end; ++itr) {
     SpMatrix<BaseFloat> tmp_g(*itr);
     tmp_g.Write(out, binary);
   }
 }
Member Data Documentation
beta_
double beta_
beta_ is the occupation count.
Definition at line 33 of file transform-common.h.
Referenced by BasisFmllrAccus::AccuGradientScatter(), AffineXformStats::Add(), kaldi::CalBasisFmllrStepSize(), kaldi::CalcFmllrStepSize(), FmllrDiagGmmAccs::CommitSingleFrameStats(), kaldi::ComputeFmllrMatrixDiagGmmDiagonal(), kaldi::ComputeFmllrMatrixDiagGmmFull(), LinearVtln::ComputeTransform(), BasisFmllrEstimate::ComputeTransform(), CompressedAffineXformStats::CopyFromAffineXformStats(), AffineXformStats::CopyStats(), CompressedAffineXformStats::CopyToAffineXformStats(), kaldi::FmllrAuxfGradient(), kaldi::FmllrAuxFuncDiagGmm(), FmllrDiagGmmAccs::FmllrDiagGmmAccs(), AffineXformStats::Init(), AffineXformStats::Read(), AffineXformStats::SetZero(), FmllrDiagGmmAccs::Update(), and AffineXformStats::Write().
dim_
int32 dim_
dim_ is the feature dimension.
Definition at line 43 of file transform-common.h.
Referenced by AffineXformStats::Add(), kaldi::CalBasisFmllrStepSize(), BasisFmllrEstimate::ComputeTransform(), AffineXformStats::CopyStats(), AffineXformStats::Dim(), AffineXformStats::Init(), AffineXformStats::Read(), and AffineXformStats::Write().
G_
std::vector< SpMatrix<double> > G_
G_ is the outer product of extended-data, scaled by inverse variance, for each dimension.
These are the quadratic stats in fMLLR; in the diagonal-fMLLR case G will be indexed 0 to dim_ - 1, but in the full-fMLLR case it will be indexed 0 to ((dim)(dim+1))/2. Each G_[i] is of dimension dim+1 by dim+1.
Definition at line 41 of file transform-common.h.
Referenced by BasisFmllrAccus::AccuGradientScatter(), AffineXformStats::Add(), kaldi::ApplyFeatureTransformToStats(), kaldi::ApplyModelTransformToStats(), kaldi::CalcFmllrStepSize(), FmllrDiagGmmAccs::CommitSingleFrameStats(), kaldi::ComputeFmllrMatrixDiagGmmDiagonal(), kaldi::ComputeFmllrMatrixDiagGmmFull(), kaldi::ComputeFmllrMatrixDiagGmmOffset(), BasisFmllrEstimate::ComputeTransform(), CompressedAffineXformStats::CopyFromAffineXformStats(), AffineXformStats::CopyStats(), CompressedAffineXformStats::CopyToAffineXformStats(), kaldi::FmllrAuxfGradient(), kaldi::FmllrAuxFuncDiagGmm(), FmllrDiagGmmAccs::FmllrDiagGmmAccs(), AffineXformStats::Init(), kaldi::MllrAuxFunction(), AffineXformStats::Read(), AffineXformStats::SetZero(), and AffineXformStats::Write().
K_
Matrix<double> K_
K_ is the summed outer product of [mean times inverse variance] with [extended data], scaled by the occupation counts; dimension is dim by (dim+1)
Definition at line 36 of file transform-common.h.
Referenced by BasisFmllrAccus::AccuGradientScatter(), AffineXformStats::Add(), kaldi::ApplyFeatureTransformToStats(), kaldi::ApplyModelTransformToStats(), kaldi::CalcFmllrStepSize(), FmllrDiagGmmAccs::CommitSingleFrameStats(), kaldi::ComputeFmllrMatrixDiagGmmDiagonal(), kaldi::ComputeFmllrMatrixDiagGmmFull(), kaldi::ComputeFmllrMatrixDiagGmmOffset(), BasisFmllrEstimate::ComputeTransform(), CompressedAffineXformStats::CopyFromAffineXformStats(), AffineXformStats::CopyStats(), CompressedAffineXformStats::CopyToAffineXformStats(), kaldi::FmllrAuxfGradient(), kaldi::FmllrAuxFuncDiagGmm(), FmllrDiagGmmAccs::FmllrDiagGmmAccs(), AffineXformStats::Init(), kaldi::MllrAuxFunction(), AffineXformStats::Read(), AffineXformStats::SetZero(), and AffineXformStats::Write().
The documentation for this class was generated from the following files:
transform/transform-common.h
transform/transform-common.cc