Kaldi: SphinxMatrixHolder< kFeatDim > Class Template Reference
SphinxMatrixHolder< kFeatDim > Class Template Reference
"Holder types"
A class for reading/writing Sphinx format matrices.
#include <kaldi-holder-inl.h>
Public Types
typedef Matrix< BaseFloat > T
Public Member Functions
SphinxMatrixHolder ()
void Clear ()
bool Read (std::istream &is)
T & Value ()
void Swap (SphinxMatrixHolder *other)
bool ExtractRange (const SphinxMatrixHolder &other, const std::string &range)
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &m)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (SphinxMatrixHolder)
Private Attributes
T feats_
Detailed Description
template<int kFeatDim>
class kaldi::SphinxMatrixHolder< kFeatDim >
A class for reading/writing Sphinx format matrices.
Definition at line 816 of file kaldi-holder-inl.h.
Member Typedef Documentation
T
typedef Matrix<BaseFloat> T
Definition at line 818 of file kaldi-holder-inl.h.
Constructor & Destructor Documentation
SphinxMatrixHolder()
SphinxMatrixHolder () inline
Definition at line 820 of file kaldi-holder-inl.h.
 {}
Member Function Documentation
Clear()
void Clear () inline
Definition at line 822 of file kaldi-holder-inl.h.
 { feats_.Resize(0, 0); }
ExtractRange()
bool ExtractRange (const SphinxMatrixHolder< kFeatDim > & other, const std::string & range) inline
Definition at line 904 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::KALDI_DISALLOW_COPY_AND_ASSIGN(), and KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 896 of file kaldi-holder-inl.h.
 { return true; }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (SphinxMatrixHolder< kFeatDim >) private
Read()
bool Read (std::istream & is) inline
Definition at line 851 of file kaldi-holder-inl.h.
References rnnlm::i, rnnlm::j, KALDI_SWAP4, KALDI_VLOG, KALDI_WARN, and kaldi::MachineIsLittleEndian().
{
     int32 nmfcc;
     is.read(reinterpret_cast<char*> (&nmfcc), sizeof(nmfcc));
     if (MachineIsLittleEndian())
       KALDI_SWAP4(nmfcc);
     KALDI_VLOG(2) << "#feats: " << nmfcc;
     int32 nfvec = nmfcc / kFeatDim;
     if ((nmfcc % kFeatDim) != 0) {
       KALDI_WARN << "Sphinx feature count is inconsistent with vector length ";
       return false;
     }
     feats_.Resize(nfvec, kFeatDim);
     for (MatrixIndexT i = 0; i < feats_.NumRows(); i++) {
       if (sizeof(BaseFloat) == sizeof(float32)) {
         is.read(reinterpret_cast<char*> (feats_.RowData(i)),
                 kFeatDim * sizeof(float32));
         if (!is.good()) {
           KALDI_WARN << "Unexpected error/EOF while reading Sphinx features ";
           return false;
         }
         if (MachineIsLittleEndian()) {
           for (MatrixIndexT j = 0; j < kFeatDim; j++)
             KALDI_SWAP4(feats_(i, j));
         }
       } else {  // KALDI_DOUBLEPRECISION=1
         float32 tmp[kFeatDim];
         is.read(reinterpret_cast<char*> (tmp), sizeof(tmp));
         if (!is.good()) {
           KALDI_WARN << "Unexpected error/EOF while reading Sphinx features ";
           return false;
         }
         for (MatrixIndexT j = 0; j < kFeatDim; j++) {
           if (MachineIsLittleEndian())
             KALDI_SWAP4(tmp[j]);
           feats_(i, j) = static_cast<BaseFloat>(tmp[j]);
         }
       }
     }
     return true;
   }
Swap()
void Swap (SphinxMatrixHolder< kFeatDim > * other) inline
Definition at line 900 of file kaldi-holder-inl.h.
References SphinxMatrixHolder< kFeatDim >::feats_.
{
     feats_.Swap(&(other->feats_));
   }
Value()
T& Value () inline
Definition at line 898 of file kaldi-holder-inl.h.
 { return feats_; }
Write()
static bool Write (std::ostream & os, bool binary, const T & m) inline static
Definition at line 825 of file kaldi-holder-inl.h.
References rnnlm::i, rnnlm::j, KALDI_SWAP4, KALDI_WARN, kaldi::MachineIsLittleEndian(), MatrixBase< Real >::NumCols(), and MatrixBase< Real >::NumRows().
{
     if (!binary) {
       KALDI_WARN << "SphinxMatrixHolder can't write Sphinx features in text ";
       return false;
     }
     int32 size = m.NumRows() * m.NumCols();
     if (MachineIsLittleEndian())
       KALDI_SWAP4(size);
     // write the header
     os.write(reinterpret_cast<char*> (&size), sizeof(size));
     for (MatrixIndexT i = 0; i < m.NumRows(); i++) {
       std::vector<float32> tmp(m.NumCols());
       for (MatrixIndexT j = 0; j < m.NumCols(); j++) {
         tmp[j] = static_cast<float32>(m(i, j));
         if (MachineIsLittleEndian())
           KALDI_SWAP4(tmp[j]);
       }
       os.write(reinterpret_cast<char*>(&(tmp[0])),
                tmp.size() * 4);
     }
     return true;
   }
Member Data Documentation
feats_
T feats_ private
Definition at line 912 of file kaldi-holder-inl.h.
Referenced by SphinxMatrixHolder< kFeatDim >::Swap().
The documentation for this class was generated from the following file:
util/kaldi-holder-inl.h