Kaldi: WaveHolder Class Reference
WaveHolder Class Reference
#include <wave-reader.h>
Public Types
typedef WaveData T
Public Member Functions
void Copy (const T &t)
void Clear ()
T & Value ()
WaveHolder & operator= (const WaveHolder &other)
WaveHolder (const WaveHolder &other)
WaveHolder ()
bool Read (std::istream &is)
void Swap (WaveHolder *other)
bool ExtractRange (const WaveHolder &other, const std::string &range)
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Attributes
T t_
Detailed Description
Definition at line 158 of file wave-reader.h.
Member Typedef Documentation
T
typedef WaveData T
Definition at line 160 of file wave-reader.h.
Constructor & Destructor Documentation
WaveHolder() [1/2]
WaveHolder (const WaveHolder & other) inline
Definition at line 187 of file wave-reader.h.
 : t_(other.t_) {}
WaveHolder() [2/2]
WaveHolder () inline
Definition at line 189 of file wave-reader.h.
 {}
Member Function Documentation
Clear()
void Clear () inline
Definition at line 179 of file wave-reader.h.
 { t_.Clear(); }
Copy()
void Copy (const T & t) inline
Definition at line 175 of file wave-reader.h.
 { t_.CopyFrom(t); }
ExtractRange()
bool ExtractRange (const WaveHolder & other, const std::string & range) inline
Definition at line 206 of file wave-reader.h.
References KALDI_ERR.
{
     KALDI_ERR << "ExtractRange is not defined for this type of holder.";
     return false;
   }
IsReadInBinary()
static bool IsReadInBinary () inline static
Definition at line 177 of file wave-reader.h.
 { return true; }
operator=()
WaveHolder& operator= (const WaveHolder & other) inline
Definition at line 183 of file wave-reader.h.
References WaveHolder::t_.
{
     t_.CopyFrom(other.t_);
     return *this;
   }
Read()
bool Read (std::istream & is) inline
Definition at line 191 of file wave-reader.h.
References KALDI_WARN.
Referenced by main().
{
     // We don't look for the binary-mode header here [always binary]
     try {
       t_.Read(is);  // Throws exception on failure.
       return true;
     } catch (const std::exception &e) {
       KALDI_WARN << "Exception caught in WaveHolder::Read(). " << e.what();
       return false;
     }
   }
Swap()
void Swap (WaveHolder * other) inline
Definition at line 202 of file wave-reader.h.
References WaveHolder::t_.
{
     t_.Swap(&(other->t_));
   }
Value()
T& Value () inline
Definition at line 181 of file wave-reader.h.
Referenced by main().
 { return t_; }
Write()
static bool Write (std::ostream & os, bool binary, const T & t) inline static
Definition at line 162 of file wave-reader.h.
References KALDI_ERR, KALDI_WARN, and WaveData::Write().
Referenced by main().
{
     // We don't write the binary-mode header here [always binary].
     if (!binary)
       KALDI_ERR << "Wave data can only be written in binary mode.";
     try {
       t.Write(os);  // throws exception on failure.
       return true;
     } catch (const std::exception &e) {
       KALDI_WARN << "Exception caught in WaveHolder object (writing). "
                  << e.what();
       return false;  // write failure.
     }
   }
Member Data Documentation
t_
T t_ private
Definition at line 212 of file wave-reader.h.
Referenced by WaveHolder::operator=(), and WaveHolder::Swap().
The documentation for this class was generated from the following file:
feat/wave-reader.h