Kaldi: BackoffDeterministicOnDemandFst< Arc > Class Template Reference
BackoffDeterministicOnDemandFst< Arc > Class Template Reference
"Classes and functions related to on-demand deterministic FST's"
This class wraps an Fst, representing a language model, using the interface for "BackoffDeterministicOnDemandFst".
#include <deterministic-fst.h>
Public Types
typedef Arc::Weight Weight
typedef Arc::StateId StateId
typedef Arc::Label Label
Public Types inherited from DeterministicOnDemandFst< Arc >
typedef Arc::StateId StateId
typedef Arc::Weight Weight
typedef Arc::Label Label
Public Member Functions
BackoffDeterministicOnDemandFst (const Fst< Arc > &fst)
StateId Start ()
Weight Final (StateId s)
bool GetArc (StateId s, Label ilabel, Arc *oarc)
Note: ilabel must not be epsilon.
Public Member Functions inherited from DeterministicOnDemandFst< Arc >
virtual ~DeterministicOnDemandFst ()
Private Member Functions
StateId GetBackoffState (StateId s, Weight *w)
Private Attributes
const Fst< Arc > & fst_
Detailed Description
template<class Arc>
class fst::BackoffDeterministicOnDemandFst< Arc >
This class wraps an Fst, representing a language model, using the interface for "BackoffDeterministicOnDemandFst".
We expect that backoff arcs in the language model will have the epsilon label (label 0) on the arcs, and that there will be no other epsilons in the language model. We follow the epsilon arcs as long as a particular arc (or a final-prob) is not found at the current state.
Definition at line 100 of file deterministic-fst.h.
Member Typedef Documentation
Label
typedef Arc::Label Label
Definition at line 104 of file deterministic-fst.h.
StateId
typedef Arc::StateId StateId
Definition at line 103 of file deterministic-fst.h.
Weight
typedef Arc::Weight Weight
Definition at line 102 of file deterministic-fst.h.
Constructor & Destructor Documentation
BackoffDeterministicOnDemandFst()
BackoffDeterministicOnDemandFst (const Fst< Arc > & fst) explicit
Definition at line 58 of file deterministic-fst-inl.h.
References BackoffDeterministicOnDemandFst< Arc >::fst_, and KALDI_ASSERT.
                         : fst_(fst) {
 #ifdef KALDI_PARANOID
   KALDI_ASSERT(fst_.Properties(kILabelSorted|kIDeterministic, true) ==
                (kILabelSorted|kIDeterministic) &&
                "Input FST is not i-label sorted and deterministic.");
 #endif
 }
Member Function Documentation
Final()
Arc::Weight Final (StateId s) virtual
Implements DeterministicOnDemandFst< Arc >.
Definition at line 48 of file deterministic-fst-inl.h.
References fst::Times().
{
   Weight w = fst_.Final(state);
   if (w != Weight::Zero()) return w;
   Weight backoff_w;
   StateId backoff_state = GetBackoffState(state, &backoff_w);
   if (backoff_state == kNoStateId) return Weight::Zero();
   else return Times(backoff_w, this->Final(backoff_state));
 }
GetArc()
bool GetArc (StateId s, Label ilabel, Arc * oarc) virtual
Note: ilabel must not be epsilon.
Implements DeterministicOnDemandFst< Arc >.
Definition at line 68 of file deterministic-fst-inl.h.
References BackoffDeterministicOnDemandFst< Arc >::fst_, BackoffDeterministicOnDemandFst< Arc >::GetBackoffState(), KALDI_ASSERT, and fst::Times().
{
   KALDI_ASSERT(ilabel != 0); //  We don't allow GetArc for epsilon.
   SortedMatcher<Fst<Arc> > sm(fst_, MATCH_INPUT, 1);
   sm.SetState(s);
   if (sm.Find(ilabel)) {
     const Arc &arc = sm.Value();
     *oarc = arc;
     return true;
   } else {
     Weight backoff_w;
     StateId backoff_state = GetBackoffState(s, &backoff_w);
     if (backoff_state == kNoStateId) return false;
     if (!this->GetArc(backoff_state, ilabel, oarc)) return false;
     oarc->weight = Times(oarc->weight, backoff_w);
     return true;
   }
 }
GetBackoffState()
Arc::StateId GetBackoffState (StateId s, Weight * w) inline private
Definition at line 33 of file deterministic-fst-inl.h.
Referenced by BackoffDeterministicOnDemandFst< Arc >::GetArc().
{
   ArcIterator<Fst<Arc> > aiter(fst_, s);
   if (aiter.Done()) // no arcs.
     return kNoStateId;
   const Arc &arc = aiter.Value();
   if (arc.ilabel == 0) {
     *w = arc.weight;
     return arc.nextstate;
   } else {
     return kNoStateId;
   }
 }
Start()
StateId Start () inline virtual
Implements DeterministicOnDemandFst< Arc >.
Definition at line 108 of file deterministic-fst.h.
References DeterministicOnDemandFst< Arc >::Final(), and DeterministicOnDemandFst< Arc >::GetArc().
 { return fst_.Start(); }
Member Data Documentation
fst_
const Fst<Arc>& fst_ private
Definition at line 117 of file deterministic-fst.h.
Referenced by BackoffDeterministicOnDemandFst< Arc >::BackoffDeterministicOnDemandFst(), and BackoffDeterministicOnDemandFst< Arc >::GetArc().
The documentation for this class was generated from the following files:
fstext/deterministic-fst.h
fstext/deterministic-fst-inl.h