Kaldi: ArcPosteriorComputer Class Reference
ArcPosteriorComputer Class Reference
Public Member Functions
ArcPosteriorComputer (const CompactLattice &clat, BaseFloat min_post, bool print_alignment, const TransitionModel *trans_model=NULL)
int32 OutputPosteriors (const std::string &utterance, std::ostream &os)
Private Attributes
const CompactLattice & clat_
std::vector< double > alpha_
std::vector< double > beta_
std::vector< int32 > state_times_
BaseFloat min_post_
bool print_alignment_
const TransitionModel * trans_model_
Detailed Description
Definition at line 31 of file lattice-arc-post.cc.
Constructor & Destructor Documentation
ArcPosteriorComputer()
ArcPosteriorComputer (const CompactLattice & clat, BaseFloat min_post, bool print_alignment, const TransitionModel * trans_model = NULL) inline
Definition at line 34 of file lattice-arc-post.cc.
                                                                  :
       clat_(clat), min_post_(min_post), print_alignment_(print_alignment),
       trans_model_(trans_model) { }
Member Function Documentation
OutputPosteriors()
int32 OutputPosteriors (const std::string & utterance, std::ostream & os) inline
Definition at line 42 of file lattice-arc-post.cc.
References ArcPosteriorComputer::alpha_, ArcPosteriorComputer::beta_, ArcPosteriorComputer::clat_, kaldi::CompactLatticeStateTimes(), kaldi::ComputeCompactLatticeAlphas(), kaldi::ComputeCompactLatticeBetas(), fst::ConvertToCost(), TransitionModel::IsFinal(), KALDI_ASSERT, ArcPosteriorComputer::min_post_, ArcPosteriorComputer::print_alignment_, ArcPosteriorComputer::state_times_, ArcPosteriorComputer::trans_model_, and TransitionModel::TransitionIdToPhone().
Referenced by main().
{
     int32 num_post = 0;
     if (!ComputeCompactLatticeAlphas(clat_, &alpha_))
       return num_post;
     if (!ComputeCompactLatticeBetas(clat_, &beta_))
       return num_post;
     CompactLatticeStateTimes(clat_, &state_times_);
     if (clat_.Start() < 0)
       return 0;
     double tot_like = beta_[clat_.Start()];
     int32 num_states = clat_.NumStates();
     for (int32 state = 0; state < num_states; state++) {
       for (fst::ArcIterator<CompactLattice> aiter(clat_, state);
            !aiter.Done(); aiter.Next()) {
         const CompactLatticeArc &arc = aiter.Value();
         double arc_loglike = -ConvertToCost(arc.weight) +
             alpha_[state] + beta_[arc.nextstate] - tot_like;
         KALDI_ASSERT(arc_loglike < 0.1 &&
                      "Bad arc posterior in forward-backward computation");
         if (arc_loglike > 0.0) arc_loglike = 0.0;
         int32 num_frames = arc.weight.String().size(),
             word = arc.ilabel;
         BaseFloat arc_post = exp(arc_loglike);
         if (arc_post <= min_post_) continue;
         os << utterance << '\t' << state_times_[state] << '\t' << num_frames
            << '\t' << arc_post << '\t' << word;
         if (print_alignment_) {
           os << '\t';
           const std::vector<int32> &ali = arc.weight.String();
           for (int32 frame = 0; frame < num_frames; frame++) {
             os << ali[frame];
             if (frame + 1 < num_frames) os << ',';
           }
         }
         if (trans_model_ != NULL) {
           // we want to print the phone sequence too.
           os << '\t';
           const std::vector<int32> &ali = arc.weight.String();
           bool first_phone = true;
           for (int32 frame = 0; frame < num_frames; frame++) {
             if (trans_model_->IsFinal(ali[frame])) {
               if (first_phone) first_phone = false;
               else os << ' ';
               os << trans_model_->TransitionIdToPhone(ali[frame]);
             }
           }
         }
         os << std::endl;
         num_post++;
       }
     }
     return num_post;
   }
Member Data Documentation
alpha_
std::vector<double> alpha_ private
Definition at line 100 of file lattice-arc-post.cc.
Referenced by ArcPosteriorComputer::OutputPosteriors().
beta_
std::vector<double> beta_ private
Definition at line 101 of file lattice-arc-post.cc.
Referenced by ArcPosteriorComputer::OutputPosteriors().
clat_
const CompactLattice& clat_ private
Definition at line 99 of file lattice-arc-post.cc.
Referenced by ArcPosteriorComputer::OutputPosteriors().
min_post_
BaseFloat min_post_ private
Definition at line 104 of file lattice-arc-post.cc.
Referenced by ArcPosteriorComputer::OutputPosteriors().
print_alignment_
bool print_alignment_ private
Definition at line 105 of file lattice-arc-post.cc.
Referenced by ArcPosteriorComputer::OutputPosteriors().
state_times_
std::vector<int32> state_times_ private
Definition at line 102 of file lattice-arc-post.cc.
Referenced by ArcPosteriorComputer::OutputPosteriors().
trans_model_
const TransitionModel* trans_model_ private
Definition at line 106 of file lattice-arc-post.cc.
Referenced by ArcPosteriorComputer::OutputPosteriors().
The documentation for this class was generated from the following file:
latbin/lattice-arc-post.cc