Kaldi: ArpaLmCompilerImplInterface Class Reference
ArpaLmCompilerImplInterface Class Reference abstract
Public Member Functions
virtual ~ArpaLmCompilerImplInterface ()
virtual void ConsumeNGram (const NGram &ngram, bool is_highest)=0
Detailed Description
Definition at line 35 of file arpa-lm-compiler.cc.
Constructor & Destructor Documentation
~ArpaLmCompilerImplInterface()
virtual ~ArpaLmCompilerImplInterface () inline virtual
Definition at line 37 of file arpa-lm-compiler.cc.
References ArpaLmCompilerImplInterface::ConsumeNGram(), fst::operator==(), and vector_.
 { }
Member Function Documentation
ConsumeNGram()
virtual void ConsumeNGram (const NGram & ngram, bool is_highest) pure virtual
Implemented in ArpaLmCompilerImpl< HistKey >.
Referenced by ArpaLmCompilerImplInterface::~ArpaLmCompilerImplInterface().
The documentation for this class was generated from the following file:
lm/arpa-lm-compiler.cc