Kaldi: RandomizerMask Class Reference
RandomizerMask Class Reference
Generates randomly ordered vector of indices,.
#include <nnet-randomizer.h>
Public Member Functions
RandomizerMask ()
RandomizerMask (const NnetDataRandomizerOptions &conf)
void Init (const NnetDataRandomizerOptions &conf)
Init, call srand,.
const std::vector< int32 > & Generate (int32 mask_size)
Generate randomly ordered vector of integers 0..[mask_size -1],.
Private Attributes
std::vector< int32 > mask_
Detailed Description
Generates randomly ordered vector of indices,.
Definition at line 64 of file nnet-randomizer.h.
Constructor & Destructor Documentation
RandomizerMask() [1/2]
RandomizerMask () inline
Definition at line 66 of file nnet-randomizer.h.
   { }
RandomizerMask() [2/2]
RandomizerMask (const NnetDataRandomizerOptions & conf) inline explicit
Definition at line 69 of file nnet-randomizer.h.
{
     Init(conf);
   }
Member Function Documentation
Generate()
const std::vector< int32 > & Generate (int32 mask_size)
Generate randomly ordered vector of integers 0..[mask_size -1],.
Definition at line 36 of file nnet-randomizer.cc.
References rnnlm::i, and RandomizerMask::mask_.
Referenced by main(), and UnitTestRandomizerMask().
{
   mask_.resize(mask_size);
   for (int32 i = 0; i < mask_size; i++) mask_[i] = i;
   // shuffle using built-in random generator:
   std::random_shuffle(mask_.begin(), mask_.end());
   return mask_;
 }
Init()
void Init (const NnetDataRandomizerOptions & conf)
Init, call srand,.
Definition at line 31 of file nnet-randomizer.cc.
References KALDI_LOG, and NnetDataRandomizerOptions::randomizer_seed.
Referenced by UnitTestRandomizerMask().
{
   KALDI_LOG << "Seeding by srand with : " << conf.randomizer_seed;
   srand(conf.randomizer_seed);
 }
Member Data Documentation
mask_
std::vector<int32> mask_ private
Definition at line 80 of file nnet-randomizer.h.
Referenced by RandomizerMask::Generate().
The documentation for this class was generated from the following files:
nnet/nnet-randomizer.h
nnet/nnet-randomizer.cc