Kaldi: TxpPhrasing Class Reference
TxpPhrasing Class Reference
Using pauses contruct a phrase structure in the XML by adding spt elements.
#include <mod-phrasing.h>
Public Member Functions
TxpPhrasing ()
~TxpPhrasing ()
bool Init (const TxpParseOptions &opts)
Load voice data.
bool Process (pugi::xml_document *input)
Process the XML, modifying the XML to reflect linguistic information.
Public Member Functions inherited from TxpModule
TxpModule (const std::string &name)
Construct module, also loads tpdb modules in specific instances.
virtual ~TxpModule ()
const std::string GetConfigValue (const std::string &key)
Return a configuration value for this module as a string (rendundant)
const char * GetOptValue (const char *key)
Return an option value for this module as a string.
bool GetConfigValueBool (const std::string &key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
bool GetOptValueBool (const char *key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
const std::string & GetName () const
Get the name of the module.
pugi::xml_node GetHeader (pugi::xml_document *input)
Gets or adds a module header to txpheader.
Private Member Functions
bool ProcessFile (pugi::xml_node *file)
Process a file (documents may have several files of information separated within file id elements).
Additional Inherited Members
Protected Attributes inherited from TxpModule
const TxpParseOptions * opts_
Options structure for the module.
std::string tpdb_
Directory for text processing database (tpdb) files used by txpxmldata objectys in the module.
Detailed Description
Using pauses contruct a phrase structure in the XML by adding spt elements.
/ref idlaktxp_phrase
Definition at line 37 of file mod-phrasing.h.
Constructor & Destructor Documentation
TxpPhrasing()
TxpPhrasing () explicit
Definition at line 31 of file mod-phrasing.cc.
 : TxpModule("phrasing") {}
~TxpPhrasing()
~TxpPhrasing ()
Definition at line 33 of file mod-phrasing.cc.
{
 }
Member Function Documentation
Init()
bool Init (const TxpParseOptions & opts) virtual
Load voice data.
Reimplemented from TxpModule.
Definition at line 36 of file mod-phrasing.cc.
References TxpParseOptions::GetTpdb(), TxpModule::opts_, and TxpModule::tpdb_.
Referenced by main().
{
   opts_ = &opts;
   tpdb_ = opts.GetTpdb();
   return true;
 }
Process()
bool Process (pugi::xml_document * input) virtual
Process the XML, modifying the XML to reflect linguistic information.
Reimplemented from TxpModule.
Definition at line 42 of file mod-phrasing.cc.
References TxpPhrasing::ProcessFile().
Referenced by main().
{
   pugi::xml_node rootnode;
   pugi::xpath_node_set files;
   files = input->document_element().select_nodes("//fileid");
   if (files.size()) {
     for (pugi::xpath_node_set::const_iterator it = files.begin();
          it != files.end();
          ++it) {
       pugi::xml_node file = (*it).node();
       ProcessFile(&file);
     }
   } else {
     rootnode = input->document_element();
     ProcessFile(&rootnode);
   }
   return true;
 }
ProcessFile()
bool ProcessFile (pugi::xml_node * file) private
Process a file (documents may have several files of information separated within file id elements).
Definition at line 60 of file mod-phrasing.cc.
References kaldi::_copy_until_break(), and kaldi::_is_utt_final().
Referenced by TxpPhrasing::Process().
{
   bool final = false;
   pugi::xml_node uttnode, phrasenode, lastbreak, firstbreak;
   int32 phraseid = 1;
   int32 uttid = 1;
   int32 wordid = 1;
   pugi::xpath_node_set breaks;
   // Handle empty spurt
   breaks = rootnode->select_nodes(".//break");
   if (breaks.size() == 0) return true;
   uttnode = rootnode->append_child("utt");
   uttnode.append_attribute("uttid").set_value(uttid);
   lastbreak = rootnode->select_nodes("(.//break)[last()]").first().node();
   firstbreak = rootnode->select_nodes("(.//break)[1]").first().node();
   while (!final) {
     phrasenode = uttnode.append_child("spt");
     phrasenode.append_attribute("phraseid").set_value(phraseid);
     wordid = 1;
     final = _copy_until_break(rootnode, &phrasenode,
                               &firstbreak, &lastbreak, &wordid);
     firstbreak = rootnode->select_nodes(".//break[1]").first().node();
     phrasenode.append_attribute("no_wrds").set_value(wordid - 1);
     if (_is_utt_final(phrasenode)) {
       uttnode.append_attribute("no_phrases").set_value(phraseid);
       phraseid = 0;
       if (!final) {
         uttnode = rootnode->append_child("utt");
         uttid++;
         uttnode.append_attribute("uttid").set_value(uttid);
       }
     }
     phraseid++;
   }
   return true;
 }
The documentation for this class was generated from the following files:
idlaktxp/mod-phrasing.h
idlaktxp/mod-phrasing.cc