Kaldi: DiagGmmNormal Class Reference
DiagGmmNormal Class Reference
Definition for Gaussian Mixture Model with diagonal covariances in normal mode: where the parameters are stored as means and variances (instead of the exponential form that the DiagGmm class is stored as).
#include <diag-gmm-normal.h>
Public Member Functions
DiagGmmNormal ()
Empty constructor.
DiagGmmNormal (const DiagGmm &gmm)
void Resize (int32 nMix, int32 dim)
Resizes arrays to this dim. Does not initialize data.
void CopyFromDiagGmm (const DiagGmm &diaggmm)
Copies from given DiagGmm.
void CopyToDiagGmm (DiagGmm *diaggmm, GmmFlagsType flags=kGmmAll) const
Copies to DiagGmm the requested parameters.
int32 NumGauss ()
int32 Dim ()
KALDI_DISALLOW_COPY_AND_ASSIGN (DiagGmmNormal)
Public Attributes
Vector< double > weights_
weights (not log).
Matrix< double > means_
Means.
Matrix< double > vars_
diagonal variance
Detailed Description
Definition for Gaussian Mixture Model with diagonal covariances in normal mode: where the parameters are stored as means and variances (instead of the exponential form that the DiagGmm class is stored as).
This class will be used in the update (since the update formulas are for the standard parameterization) and then copied to the exponential form of the DiagGmm class. The DiagGmmNormal class will not be used anywhere else, and should not have any extra methods that are not needed.
Definition at line 45 of file diag-gmm-normal.h.
Constructor & Destructor Documentation
DiagGmmNormal() [1/2]
DiagGmmNormal () inline
Empty constructor.
Definition at line 48 of file diag-gmm-normal.h.
 { }
DiagGmmNormal() [2/2]
DiagGmmNormal (const DiagGmm & gmm) inline explicit
Definition at line 50 of file diag-gmm-normal.h.
References DiagGmmNormal::CopyFromDiagGmm(), DiagGmmNormal::CopyToDiagGmm(), kaldi::kGmmAll, and DiagGmmNormal::Resize().
{
     CopyFromDiagGmm(gmm);
   }
Member Function Documentation
CopyFromDiagGmm()
void CopyFromDiagGmm (const DiagGmm & diaggmm)
Copies from given DiagGmm.
Definition at line 46 of file diag-gmm-normal.cc.
References MatrixBase< Real >::CopyFromMat(), VectorBase< Real >::CopyFromVec(), DiagGmm::Dim(), DiagGmm::inv_vars_, MatrixBase< Real >::InvertElements(), DiagGmmNormal::means_, DiagGmm::means_invvars_, MatrixBase< Real >::MulElements(), DiagGmmNormal::Resize(), DiagGmmNormal::vars_, DiagGmmNormal::weights_, and DiagGmm::weights_.
Referenced by DiagGmmNormal::DiagGmmNormal(), kaldi::UpdateEbwDiagGmm(), and kaldi::UpdateEbwWeightsDiagGmm().
{
   int32 num_comp = diaggmm.weights_.Dim(), dim = diaggmm.Dim();
   Resize(num_comp, dim);
   weights_.CopyFromVec(diaggmm.weights_);
   vars_.CopyFromMat(diaggmm.inv_vars_);
   vars_.InvertElements();
   means_.CopyFromMat(diaggmm.means_invvars_);
   means_.MulElements(vars_);
 }
CopyToDiagGmm()
void CopyToDiagGmm (DiagGmm * diaggmm, GmmFlagsType flags = kGmmAll) const
Copies to DiagGmm the requested parameters.
Definition at line 57 of file diag-gmm-normal.cc.
References MatrixBase< Real >::CopyFromMat(), VectorBase< Real >::Dim(), DiagGmm::Dim(), DiagGmm::inv_vars_, MatrixBase< Real >::InvertElements(), KALDI_ASSERT, kaldi::kGmmMeans, kaldi::kGmmVariances, kaldi::kGmmWeights, DiagGmmNormal::means_, DiagGmm::means_invvars_, MatrixBase< Real >::MulElements(), MatrixBase< Real >::NumCols(), DiagGmm::valid_gconsts_, DiagGmmNormal::vars_, DiagGmmNormal::weights_, and DiagGmm::weights_.
Referenced by DiagGmm::CopyFromNormal(), DiagGmmNormal::DiagGmmNormal(), kaldi::DoRescalingUpdate(), kaldi::MapDiagGmmUpdate(), kaldi::MleDiagGmmUpdate(), UnitTestEstimateDiagGmm(), kaldi::UpdateEbwDiagGmm(), and kaldi::UpdateEbwWeightsDiagGmm().
{
     KALDI_ASSERT((static_cast<int32>(diaggmm->Dim()) == means_.NumCols())
                  && (static_cast<int32>(diaggmm->weights_.Dim()) == weights_.Dim()));
     DiagGmmNormal oldg(*diaggmm);
     if (flags & kGmmWeights)
       diaggmm->weights_.CopyFromVec(weights_);
     if (flags & kGmmVariances) {
       diaggmm->inv_vars_.CopyFromMat(vars_);
       diaggmm->inv_vars_.InvertElements();
       // update the mean related natural part with the old mean, if necessary
       if (!(flags & kGmmMeans)) {
         diaggmm->means_invvars_.CopyFromMat(oldg.means_);
         diaggmm->means_invvars_.MulElements(diaggmm->inv_vars_);
       }
     }
     if (flags & kGmmMeans) {
       diaggmm->means_invvars_.CopyFromMat(means_);
       diaggmm->means_invvars_.MulElements(diaggmm->inv_vars_);
     }
     diaggmm->valid_gconsts_ = false;
 }
Dim()
int32 Dim () inline
Definition at line 64 of file diag-gmm-normal.h.
References DiagGmmNormal::means_, and MatrixBase< Real >::NumCols().
 { return means_.NumCols(); }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (DiagGmmNormal)
NumGauss()
int32 NumGauss () inline
Definition at line 63 of file diag-gmm-normal.h.
References VectorBase< Real >::Dim(), and DiagGmmNormal::weights_.
Referenced by Fmpe::ComputeC().
 { return weights_.Dim(); }
Resize()
void Resize (int32 nMix, int32 dim)
Resizes arrays to this dim. Does not initialize data.
Definition at line 31 of file diag-gmm-normal.cc.
References VectorBase< Real >::Dim(), KALDI_ASSERT, DiagGmmNormal::means_, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), Vector< Real >::Resize(), Matrix< Real >::Resize(), DiagGmmNormal::vars_, and DiagGmmNormal::weights_.
Referenced by DiagGmmNormal::CopyFromDiagGmm(), and DiagGmmNormal::DiagGmmNormal().
{
   KALDI_ASSERT(nmix > 0 && dim > 0);
   if (weights_.Dim() != nmix)
     weights_.Resize(nmix);
   if (vars_.NumRows() != nmix ||
       vars_.NumCols() != dim)
     vars_.Resize(nmix, dim);
   if (means_.NumRows() != nmix ||
       means_.NumCols() != dim)
     means_.Resize(nmix, dim);
 }
Member Data Documentation
means_
Matrix<double> means_
Means.
Definition at line 67 of file diag-gmm-normal.h.
Referenced by Fmpe::ComputeC(), DiagGmmNormal::CopyFromDiagGmm(), DiagGmmNormal::CopyToDiagGmm(), kaldi::DiagGmmToStats(), DiagGmmNormal::Dim(), kaldi::DoRescalingUpdate(), kaldi::GetStatsDerivative(), kaldi::InitGmmFromRandomFrames(), DiagGmm::Interpolate(), kaldi::MapDiagGmmUpdate(), kaldi::MleDiagGmmUpdate(), DiagGmmNormal::Resize(), UnitTestEstimateDiagGmm(), and kaldi::UpdateEbwDiagGmm().
vars_
Matrix<double> vars_
diagonal variance
Definition at line 68 of file diag-gmm-normal.h.
Referenced by Fmpe::ComputeC(), DiagGmmNormal::CopyFromDiagGmm(), DiagGmmNormal::CopyToDiagGmm(), kaldi::DiagGmmToStats(), kaldi::DoRescalingUpdate(), kaldi::GetStatsDerivative(), kaldi::InitGmmFromRandomFrames(), DiagGmm::Interpolate(), kaldi::MapDiagGmmUpdate(), kaldi::MleDiagGmmUpdate(), DiagGmmNormal::Resize(), UnitTestEstimateDiagGmm(), and kaldi::UpdateEbwDiagGmm().
weights_
Vector<double> weights_
weights (not log).
Definition at line 66 of file diag-gmm-normal.h.
Referenced by Fmpe::ComputeC(), DiagGmmNormal::CopyFromDiagGmm(), DiagGmmNormal::CopyToDiagGmm(), kaldi::DiagGmmToStats(), kaldi::InitGmmFromRandomFrames(), DiagGmm::Interpolate(), kaldi::MapDiagGmmUpdate(), kaldi::MleDiagGmmUpdate(), DiagGmmNormal::NumGauss(), DiagGmmNormal::Resize(), and kaldi::UpdateEbwWeightsDiagGmm().
The documentation for this class was generated from the following files:
gmm/diag-gmm-normal.h
gmm/diag-gmm-normal.cc