Kaldi: MultistreamComponent Class Reference
MultistreamComponent Class Reference
Class MultistreamComponent is an extension of UpdatableComponent for recurrent networks, which are trained with parallel sequences.
#include <nnet-component.h>
Public Member Functions
MultistreamComponent (int32 input_dim, int32 output_dim)
bool IsMultistream () const
Check if component has 'Recurrent' interface (trainable and recurrent),.
virtual void SetSeqLengths (const std::vector< int32 > &sequence_lengths)
int32 NumStreams () const
virtual void ResetStreams (const std::vector< int32 > &stream_reset_flag)
Optional function to reset the transfer of context (not used for BLSTMs.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters,.
virtual int32 NumParams () const =0
Number of trainable parameters,.
virtual void GetGradient (VectorBase< BaseFloat > *gradient) const =0
Get gradient reshaped as a vector,.
virtual void GetParams (VectorBase< BaseFloat > *params) const =0
Get the trainable parameters reshaped as a vector,.
virtual void SetParams (const VectorBase< BaseFloat > &params)=0
Set the trainable parameters from, reshaped as a vector,.
virtual void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)=0
Compute gradient and update parameters,.
virtual void SetTrainOptions (const NnetTrainOptions &opts)
Set the training options to the component,.
const NnetTrainOptions & GetTrainOptions () const
Get the training options from the component,.
virtual void SetLearnRateCoef (BaseFloat val)
Set the learn-rate coefficient,.
virtual void SetBiasLearnRateCoef (BaseFloat val)
Set the learn-rate coefficient for bias,.
virtual void InitData (std::istream &is)=0
Initialize the content of the component by the 'line' from the prototype,.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
Generic interface of a component,.
virtual ~Component ()
virtual Component * Copy () const =0
Copy component (deep copy),.
virtual ComponentType GetType () const =0
Get Type Identification of the component,.
int32 InputDim () const
Get the dimension of the input,.
int32 OutputDim () const
Get the dimension of the output,.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward-pass propagation 'in' -> 'out',.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
void Write (std::ostream &os, bool binary) const
Write the component to a stream,.
virtual std::string Info () const
Print some additional info (after <ComponentName> and the dims),.
virtual std::string InfoGradient () const
Print some additional info about gradient (after <...> and dims),.
Protected Attributes
std::vector< int32 > sequence_lengths_
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters,.
BaseFloat learn_rate_coef_
Scalar applied to learning rate for weight matrices (to be used in ::Update method),.
BaseFloat bias_learn_rate_coef_
Scalar applied to learning rate for bias (to be used in ::Update method),.
Protected Attributes inherited from Component
int32 input_dim_
Data members,.
int32 output_dim_
Dimension of the output of the Component,.
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjected, kBlstmProjected,
kRecurrentComponent, kActivationFunction = 0x0200, kSoftmax, kHiddenSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kParametricRelu,
kDropout, kLengthNormComponent, kTranform = 0x0400, kRbm,
kSplice, kCopy, kTranspose, kBlockLinearity,
kAddShift, kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent,
kSimpleSentenceAveragingComponent, kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent,
kMaxPooling2DComponent, kFramePoolingComponent, kParallelComponent, kMultiBasisComponent
}
Component type identification mechanism,.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Converts component type to marker,.
static ComponentType MarkerToType (const std::string &s)
Converts marker to component type (case insensitive),.
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file,.
static Component * Read (std::istream &is, bool binary)
Read the component from a stream (static method),.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Protected Member Functions inherited from Component
virtual void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)=0
Abstract interface for propagation/backpropagation.
virtual void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)=0
Backward pass transformation (to be implemented by descending class...)
virtual void ReadData (std::istream &is, bool binary)
Reads the component content.
virtual void WriteData (std::ostream &os, bool binary) const
Writes the component content.
Detailed Description
Class MultistreamComponent is an extension of UpdatableComponent for recurrent networks, which are trained with parallel sequences.
Definition at line 284 of file nnet-component.h.
Constructor & Destructor Documentation
MultistreamComponent()
MultistreamComponent (int32 input_dim, int32 output_dim) inline
Definition at line 286 of file nnet-component.h.
                                                          :
     UpdatableComponent(input_dim, output_dim)
   { }
Member Function Documentation
IsMultistream()
bool IsMultistream () const inline virtual
Check if component has 'Recurrent' interface (trainable and recurrent),.
Reimplemented from Component.
Definition at line 290 of file nnet-component.h.
{
     return true;
   }
NumStreams()
int32 NumStreams () const inline
Definition at line 298 of file nnet-component.h.
Referenced by RecurrentComponent::BackpropagateFnc(), LstmProjected::BackpropagateFnc(), BlstmProjected::BackpropagateFnc(), RecurrentComponent::PropagateFnc(), LstmProjected::PropagateFnc(), BlstmProjected::PropagateFnc(), LstmProjected::ResetStreams(), and RecurrentComponent::Update().
{
     return std::max<int32>(1, sequence_lengths_.size());
   }
ResetStreams()
virtual void ResetStreams (const std::vector< int32 > & stream_reset_flag) inline virtual
Optional function to reset the transfer of context (not used for BLSTMs.
Reimplemented in LstmProjected.
Definition at line 303 of file nnet-component.h.
Referenced by Nnet::ResetStreams().
   { }
SetSeqLengths()
virtual void SetSeqLengths (const std::vector< int32 > & sequence_lengths) inline virtual
Reimplemented in ParallelComponent.
Definition at line 294 of file nnet-component.h.
Referenced by Nnet::SetSeqLengths().
{
     sequence_lengths_ = sequence_lengths;
   }
Member Data Documentation
sequence_lengths_
std::vector<int32> sequence_lengths_ protected
Definition at line 307 of file nnet-component.h.
Referenced by RecurrentComponent::BackpropagateFnc(), LstmProjected::BackpropagateFnc(), BlstmProjected::BackpropagateFnc(), RecurrentComponent::PropagateFnc(), LstmProjected::PropagateFnc(), BlstmProjected::PropagateFnc(), and ParallelComponent::SetSeqLengths().
The documentation for this class was generated from the following file:
nnet/nnet-component.h