Kaldi: LatticeWeightTpl< FloatType > Class Template Reference
LatticeWeightTpl< FloatType > Class Template Reference
#include <lattice-weight.h>
Public Types
typedef FloatType T
typedef LatticeWeightTpl ReverseWeight
Public Member Functions
T Value1 () const
T Value2 () const
void SetValue1 (T f)
void SetValue2 (T f)
LatticeWeightTpl ()
LatticeWeightTpl (T a, T b)
LatticeWeightTpl (const LatticeWeightTpl &other)
LatticeWeightTpl & operator= (const LatticeWeightTpl &w)
LatticeWeightTpl< FloatType > Reverse () const
bool Member () const
LatticeWeightTpl Quantize (float delta=kDelta) const
istream & Read (istream &strm)
ostream & Write (ostream &strm) const
size_t Hash () const
Static Public Member Functions
static const LatticeWeightTpl Zero ()
static const LatticeWeightTpl One ()
static const string & Type ()
static const LatticeWeightTpl NoWeight ()
static constexpr uint64 Properties ()
Protected Member Functions
istream & ReadNoParen (istream &strm, char separator)
Static Protected Member Functions
static void WriteFloatType (ostream &strm, const T &f)
static void ReadFloatType (istream &strm, T &f)
Private Attributes
T value1_
T value2_
Friends
istream & operator>> (istream &, LatticeWeightTpl< FloatType > &)
ostream & operator (ostream &, const LatticeWeightTpl< FloatType > &)
Detailed Description
template<class FloatType>
class fst::LatticeWeightTpl< FloatType >
Definition at line 37 of file lattice-weight.h.
Member Typedef Documentation
ReverseWeight
typedef LatticeWeightTpl ReverseWeight
Definition at line 50 of file lattice-weight.h.
T
typedef FloatType T
Definition at line 49 of file lattice-weight.h.
Constructor & Destructor Documentation
LatticeWeightTpl() [1/3]
LatticeWeightTpl () inline
Definition at line 60 of file lattice-weight.h.
Referenced by LatticeWeightTpl< BaseFloat >::NoWeight(), LatticeWeightTpl< BaseFloat >::One(), LatticeWeightTpl< BaseFloat >::Quantize(), and LatticeWeightTpl< BaseFloat >::Zero().
 : value1_{}, value2_{} { }
LatticeWeightTpl() [2/3]
LatticeWeightTpl (T a, T b) inline
Definition at line 62 of file lattice-weight.h.
 : value1_(a), value2_(b) {}
LatticeWeightTpl() [3/3]
LatticeWeightTpl (const LatticeWeightTpl< FloatType > & other) inline
Definition at line 64 of file lattice-weight.h.
 : value1_(other.value1_), value2_(other.value2_) { }
Member Function Documentation
Hash()
size_t Hash () const inline
Definition at line 147 of file lattice-weight.h.
                       {
     size_t ans;
     union {
       T f;
       size_t s;
     } u;
     u.s = 0;
     u.f = value1_;
     ans = u.s;
     u.f = value2_;
     ans += u.s;
     return ans;
   }
Member()
bool Member () const inline
Definition at line 95 of file lattice-weight.h.
Referenced by fst::LatticeWeightTest().
                       {
     // value1_ == value1_ tests for NaN.
     // also test for no -inf, and either both or neither
     // must be +inf, and
     if (value1_ != value1_ || value2_ != value2_) return false; // NaN
     if (value1_ == -numeric_limits<T>::infinity()  ||
        value2_ == -numeric_limits<T>::infinity()) return false; // -infty not allowed
     if (value1_ == numeric_limits<T>::infinity() ||
         value2_ == numeric_limits<T>::infinity()) {
       if (value1_ != numeric_limits<T>::infinity() ||
           value2_ != numeric_limits<T>::infinity()) return false; // both must be +infty;
       // this is necessary so that the semiring has only one zero.
     }
     return true;
   }
NoWeight()
static const LatticeWeightTpl NoWeight () inline static
Definition at line 90 of file lattice-weight.h.
{
     return LatticeWeightTpl(numeric_limits<FloatType>::quiet_NaN(),
                             numeric_limits<FloatType>::quiet_NaN());
   }
One()
static const LatticeWeightTpl One () inline static
Definition at line 81 of file lattice-weight.h.
{
     return LatticeWeightTpl(0.0, 0.0);
   }
operator=()
LatticeWeightTpl& operator= (const LatticeWeightTpl< FloatType > & w) inline
Definition at line 66 of file lattice-weight.h.
{
     value1_ = w.value1_;
     value2_ = w.value2_;
     return *this;
   }
Properties()
static constexpr uint64 Properties () inline static
Definition at line 122 of file lattice-weight.h.
{
     return kLeftSemiring | kRightSemiring | kCommutative |
         kPath | kIdempotent;
   }
Quantize()
LatticeWeightTpl Quantize (float delta = kDelta) const inline
Definition at line 111 of file lattice-weight.h.
Referenced by fst::LatticeWeightTest().
{
     if (value1_+value2_ == -numeric_limits<T>::infinity()) {
       return LatticeWeightTpl(-numeric_limits<T>::infinity(), -numeric_limits<T>::infinity());
     } else if (value1_+value2_ == numeric_limits<T>::infinity()) {
       return LatticeWeightTpl(numeric_limits<T>::infinity(), numeric_limits<T>::infinity());
     } else if (value1_+value2_ != value1_+value2_) { // NaN
       return LatticeWeightTpl(value1_+value2_, value1_+value2_);
     } else {
       return LatticeWeightTpl(floor(value1_/delta + 0.5F)*delta, floor(value2_/delta + 0.5F) * delta);
     }
   }
Read()
istream& Read (istream & strm) inline
Definition at line 129 of file lattice-weight.h.
Referenced by fst::LatticeWeightTest().
{
     // Always read/write as float, even if T is double,
     // so we can use OpenFst-style read/write and still maintain
     // compatibility when compiling with different FloatTypes
     ReadType(strm, &value1_);
     ReadType(strm, &value2_);
     return strm;
   }
ReadFloatType()
static void ReadFloatType (istream & strm, T & f) inline static protected
Definition at line 174 of file lattice-weight.h.
Referenced by LatticeWeightTpl< BaseFloat >::ReadNoParen().
{
     string s;
     strm >> s;
     if (s == "Infinity") {
       f = numeric_limits<T>::infinity();
     } else if (s == "-Infinity") {
       f = -numeric_limits<T>::infinity();
     } else if (s == "BadNumber") {
       f = numeric_limits<T>::infinity();
       f -= f; // get NaN
     } else {
       char *p;
       f = strtod(s.c_str(), &p);
       if (p < s.c_str() + s.size())
         strm.clear(std::ios::badbit);
     }
   }
ReadNoParen()
istream& ReadNoParen (istream & strm, char separator) inline protected
Definition at line 194 of file lattice-weight.h.
Referenced by fst::operator>>().
{
     int c;
     do {
       c = strm.get();
     } while (isspace(c));
     string s1;
     while (c != separator) {
       if (c == EOF) {
         strm.clear(std::ios::badbit);
         return strm;
       }
       s1 += c;
       c = strm.get();
     }
     istringstream strm1(s1);
     ReadFloatType(strm1, value1_); // ReadFloatType is class member function
     // read second element
     ReadFloatType(strm, value2_);
     return strm;
   }
Reverse()
LatticeWeightTpl<FloatType> Reverse () const inline
Definition at line 72 of file lattice-weight.h.
Referenced by fst::LatticeWeightTest().
{
     return *this;
   }
SetValue1()
void SetValue1 (T f) inline
Definition at line 56 of file lattice-weight.h.
Referenced by kaldi::AddWordInsPenToCompactLattice(), kaldi::CompactLatticeNormalize(), fst::ConvertLatticeWeight(), and DiscriminativeSupervisionSplitter::CreateRangeLattice().
 { value1_ = f; }
SetValue2()
void SetValue2 (T f) inline
Definition at line 58 of file lattice-weight.h.
Referenced by fst::ConvertLatticeWeight(), DiscriminativeSupervisionSplitter::CreateRangeLattice(), DiscriminativeComputation::LatticeAcousticRescore(), kaldi::ReplaceAcousticScoresFromMap(), and kaldi::RescoreCompactLatticeInternal().
 { value2_ = f; }
Type()
static const string& Type () inline static
Definition at line 85 of file lattice-weight.h.
{
     static const string type = (sizeof(T) == 4 ? "lattice4" : "lattice8") ;
     return type;
   }
Value1()
T Value1 () const inline
Definition at line 52 of file lattice-weight.h.
Referenced by kaldi::AddWordInsPenToCompactLattice(), kaldi::AlignUtteranceWrapper(), fst::ApproxEqual(), kaldi::CompactLatticeNormalize(), fst::Compare(), fst::ConvertLatticeWeight(), fst::ConvertToCost(), kaldi::DecodeUtterance(), kaldi::DecodeUtteranceLatticeFaster(), kaldi::DecodeUtteranceLatticeSimple(), fst::Divide(), fst::LatticeWeightTest(), main(), fst::operator!=(), fst::operator==(), fst::ScaleTupleWeight(), fst::Times(), and DecodeUtteranceLatticeFasterClass::~DecodeUtteranceLatticeFasterClass().
 { return value1_; }
Value2()
T Value2 () const inline
Definition at line 54 of file lattice-weight.h.
Referenced by kaldi::AlignUtteranceWrapper(), fst::ApproxEqual(), fst::Compare(), kaldi::ComputeAcousticScoresMap(), fst::ConvertLatticeWeight(), fst::ConvertToCost(), kaldi::DecodeUtterance(), kaldi::DecodeUtteranceLatticeFaster(), kaldi::DecodeUtteranceLatticeSimple(), fst::Divide(), fst::LatticeWeightTest(), main(), fst::operator!=(), fst::operator==(), fst::ScaleTupleWeight(), fst::Times(), and DecodeUtteranceLatticeFasterClass::~DecodeUtteranceLatticeFasterClass().
 { return value2_; }
Write()
ostream& Write (ostream & strm) const inline
Definition at line 141 of file lattice-weight.h.
{
     WriteType(strm, value1_);
     WriteType(strm, value2_);
     return strm;
   }
WriteFloatType()
static void WriteFloatType (ostream & strm, const T & f) inline static protected
Definition at line 162 of file lattice-weight.h.
Referenced by fst::operator<<().
{
     if (f == numeric_limits<T>::infinity())
       strm << "Infinity";
     else if (f == -numeric_limits<T>::infinity())
       strm << "-Infinity";
     else if (f != f)
       strm << "BadNumber";
     else
       strm << f;
   }
Zero()
static const LatticeWeightTpl Zero () inline static
Definition at line 76 of file lattice-weight.h.
Referenced by fst::Divide().
{
     return LatticeWeightTpl(numeric_limits<T>::infinity(),
                             numeric_limits<T>::infinity());
   }
Friends And Related Function Documentation
operator
ostream& operator (ostream & , const LatticeWeightTpl< FloatType > &) friend
operator>>
istream& operator>> (istream & strm, LatticeWeightTpl< FloatType > & w) friend
Definition at line 408 of file lattice-weight.h.
{
   CHECK(FLAGS_fst_weight_separator.size() == 1);
   // separator defaults to ','
   return w1.ReadNoParen(strm, FLAGS_fst_weight_separator[0]);
 }
Member Data Documentation
value1_
T value1_ private
Definition at line 221 of file lattice-weight.h.
Referenced by LatticeWeightTpl< BaseFloat >::Hash(), LatticeWeightTpl< BaseFloat >::Member(), LatticeWeightTpl< BaseFloat >::operator=(), LatticeWeightTpl< BaseFloat >::Quantize(), LatticeWeightTpl< BaseFloat >::Read(), LatticeWeightTpl< BaseFloat >::ReadNoParen(), LatticeWeightTpl< BaseFloat >::SetValue1(), LatticeWeightTpl< BaseFloat >::Value1(), and LatticeWeightTpl< BaseFloat >::Write().
value2_
T value2_ private
Definition at line 222 of file lattice-weight.h.
Referenced by LatticeWeightTpl< BaseFloat >::Hash(), LatticeWeightTpl< BaseFloat >::LatticeWeightTpl(), LatticeWeightTpl< BaseFloat >::Member(), LatticeWeightTpl< BaseFloat >::operator=(), LatticeWeightTpl< BaseFloat >::Quantize(), LatticeWeightTpl< BaseFloat >::Read(), LatticeWeightTpl< BaseFloat >::ReadNoParen(), LatticeWeightTpl< BaseFloat >::SetValue2(), LatticeWeightTpl< BaseFloat >::Value2(), and LatticeWeightTpl< BaseFloat >::Write().
The documentation for this class was generated from the following file:
fstext/lattice-weight.h