Kaldi: IvectorExtractTask Class Reference
IvectorExtractTask Class Reference
Public Member Functions
IvectorExtractTask (const IvectorExtractor &extractor, std::string utt, const Matrix< BaseFloat > &feats, const Posterior &posterior, BaseFloatVectorWriter *writer, double *tot_auxf_change)
void operator() ()
~IvectorExtractTask ()
Private Attributes
const IvectorExtractor & extractor_
std::string utt_
Matrix< BaseFloat > feats_
Posterior posterior_
BaseFloatVectorWriter * writer_
double * tot_auxf_change_
Vector< double > ivector_
double auxf_change_
Detailed Description
Definition at line 32 of file ivector-extract.cc.
Constructor & Destructor Documentation
IvectorExtractTask()
IvectorExtractTask (const IvectorExtractor & extractor, std::string utt, const Matrix< BaseFloat > & feats, const Posterior & posterior, BaseFloatVectorWriter * writer, double * tot_auxf_change) inline
Definition at line 34 of file ivector-extract.cc.
Referenced by main().
                                              :
       extractor_(extractor), utt_(utt), feats_(feats), posterior_(posterior),
       writer_(writer), tot_auxf_change_(tot_auxf_change) { }
~IvectorExtractTask()
~IvectorExtractTask () inline
Definition at line 64 of file ivector-extract.cc.
References IvectorExtractTask::auxf_change_, IvectorExtractTask::extractor_, IvectorExtractTask::ivector_, KALDI_VLOG, VectorBase< Real >::Norm(), IvectorExtractTask::posterior_, IvectorExtractor::PriorOffset(), IvectorExtractTask::tot_auxf_change_, kaldi::TotalPosterior(), IvectorExtractTask::utt_, TableWriter< Holder >::Write(), and IvectorExtractTask::writer_.
{
     if (tot_auxf_change_ != NULL) {
       double T = TotalPosterior(posterior_);
       *tot_auxf_change_ += auxf_change_;
       KALDI_VLOG(2) << "Auxf change for utterance " << utt_ << " was "
                     << (auxf_change_ / T) << " per frame over " << T
                     << " frames (weighted)";
     }
     // We actually write out the offset of the iVectors from the mean of the
     // prior distribution; this is the form we'll need it in for scoring.  (most
     // formulations of iVectors have zero-mean priors so this is not normally an
     // issue).
     ivector_(0) -= extractor_.PriorOffset();
     KALDI_VLOG(2) << "Ivector norm for utterance " << utt_
                   << " was " << ivector_.Norm(2.0);
     writer_->Write(utt_, Vector<BaseFloat>(ivector_));
   }
Member Function Documentation
operator()()
void operator() () inline
Definition at line 43 of file ivector-extract.cc.
References IvectorExtractorUtteranceStats::AccStats(), IvectorExtractTask::auxf_change_, IvectorExtractTask::extractor_, IvectorExtractor::FeatDim(), IvectorExtractTask::feats_, IvectorExtractor::GetAuxf(), IvectorExtractor::GetIvectorDistribution(), IvectorExtractTask::ivector_, IvectorExtractor::IvectorDim(), IvectorExtractor::NumGauss(), IvectorExtractTask::posterior_, IvectorExtractor::PriorOffset(), Vector< Real >::Resize(), and IvectorExtractTask::tot_auxf_change_.
                       {
     bool need_2nd_order_stats = false;
     IvectorExtractorUtteranceStats utt_stats(extractor_.NumGauss(),
                                              extractor_.FeatDim(),
                                              need_2nd_order_stats);
     utt_stats.AccStats(feats_, posterior_);
     ivector_.Resize(extractor_.IvectorDim());
     ivector_(0) = extractor_.PriorOffset();
     if (tot_auxf_change_ != NULL) {
       double old_auxf = extractor_.GetAuxf(utt_stats, ivector_);
       extractor_.GetIvectorDistribution(utt_stats, &ivector_, NULL);
       double new_auxf = extractor_.GetAuxf(utt_stats, ivector_);
       auxf_change_ = new_auxf - old_auxf;
     } else {
       extractor_.GetIvectorDistribution(utt_stats, &ivector_, NULL);
     }
   }
Member Data Documentation
auxf_change_
double auxf_change_ private
Definition at line 89 of file ivector-extract.cc.
Referenced by IvectorExtractTask::operator()(), and IvectorExtractTask::~IvectorExtractTask().
extractor_
const IvectorExtractor& extractor_ private
Definition at line 82 of file ivector-extract.cc.
Referenced by IvectorExtractTask::operator()(), and IvectorExtractTask::~IvectorExtractTask().
feats_
Matrix<BaseFloat> feats_ private
Definition at line 84 of file ivector-extract.cc.
Referenced by IvectorExtractTask::operator()().
ivector_
Vector<double> ivector_ private
Definition at line 88 of file ivector-extract.cc.
Referenced by IvectorExtractTask::operator()(), and IvectorExtractTask::~IvectorExtractTask().
posterior_
Posterior posterior_ private
Definition at line 85 of file ivector-extract.cc.
Referenced by IvectorExtractTask::operator()(), and IvectorExtractTask::~IvectorExtractTask().
tot_auxf_change_
double* tot_auxf_change_ private
Definition at line 87 of file ivector-extract.cc.
Referenced by IvectorExtractTask::operator()(), and IvectorExtractTask::~IvectorExtractTask().
utt_
std::string utt_ private
Definition at line 83 of file ivector-extract.cc.
Referenced by IvectorExtractTask::~IvectorExtractTask().
writer_
BaseFloatVectorWriter* writer_ private
Definition at line 86 of file ivector-extract.cc.
Referenced by IvectorExtractTask::~IvectorExtractTask().
The documentation for this class was generated from the following file:
ivectorbin/ivector-extract.cc