Kaldi: FullGmmNormal Class Reference
FullGmmNormal Class Reference
Definition for Gaussian Mixture Model with full covariances in normal mode: where the parameters are stored as means and variances (instead of the exponential form that the FullGmm class is stored as).
#include <full-gmm-normal.h>
Public Member Functions
FullGmmNormal ()
Empty constructor.
FullGmmNormal (const FullGmm &gmm)
void Resize (int32 nMix, int32 dim)
Resizes arrays to this dim. Does not initialize data.
void CopyFromFullGmm (const FullGmm &fullgmm)
Copies from given FullGmm.
void CopyToFullGmm (FullGmm *fullgmm, GmmFlagsType flags=kGmmAll)
Copies to FullGmm.
void Rand (MatrixBase< BaseFloat > *feats)
Generates random features from the model.
KALDI_DISALLOW_COPY_AND_ASSIGN (FullGmmNormal)
Public Attributes
Vector< double > weights_
weights (not log).
Matrix< double > means_
Means.
std::vector< SpMatrix< double > > vars_
covariances
Detailed Description
Definition for Gaussian Mixture Model with full covariances in normal mode: where the parameters are stored as means and variances (instead of the exponential form that the FullGmm class is stored as).
This class will be used in the update (since the update formulas are for the standard parameterization) and then copied to the exponential form of the FullGmm class. The FullGmmNormal class will not be used anywhere else, and should not have any extra methods that are not needed.
Definition at line 45 of file full-gmm-normal.h.
Constructor & Destructor Documentation
FullGmmNormal() [1/2]
FullGmmNormal () inline
Empty constructor.
Definition at line 48 of file full-gmm-normal.h.
 { }
FullGmmNormal() [2/2]
FullGmmNormal (const FullGmm & gmm) inline explicit
Definition at line 50 of file full-gmm-normal.h.
References FullGmmNormal::CopyFromFullGmm(), FullGmmNormal::CopyToFullGmm(), kaldi::kGmmAll, FullGmmNormal::Rand(), and FullGmmNormal::Resize().
{
     CopyFromFullGmm(gmm);
   }
Member Function Documentation
CopyFromFullGmm()
void CopyFromFullGmm (const FullGmm & fullgmm)
Copies from given FullGmm.
resize the variables to fit the gmm
copy weights
we need to split the natural components for each gaussian
Definition at line 53 of file full-gmm-normal.cc.
References VectorBase< Real >::CopyFromVec(), FullGmm::Dim(), rnnlm::i, FullGmm::inv_covars_, FullGmmNormal::means_, FullGmm::means_invcovars_, FullGmm::NumGauss(), FullGmmNormal::Resize(), MatrixBase< Real >::Row(), FullGmmNormal::vars_, FullGmmNormal::weights_, and FullGmm::weights_.
Referenced by FullGmmNormal::FullGmmNormal().
{
   size_t dim = fullgmm.Dim();
   size_t num_gauss = fullgmm.NumGauss();
   Resize(num_gauss, dim);
   weights_.CopyFromVec(fullgmm.weights_);
   Vector<double> mean_times_invcovar(dim);
   for (size_t i = 0; i < num_gauss; i++) {
     // copy and invert (inverse) covariance matrix
     vars_[i].CopyFromSp(fullgmm.inv_covars_[i]);
     vars_[i].InvertDouble();
     // multiply the (mean x icov) by (cov) to get the means back
     mean_times_invcovar.CopyFromVec(fullgmm.means_invcovars_.Row(i));
     (means_.Row(i)).AddSpVec(1.0, vars_[i], mean_times_invcovar, 0.0);
   }
 }
CopyToFullGmm()
void CopyToFullGmm (FullGmm * fullgmm, GmmFlagsType flags = kGmmAll)
Copies to FullGmm.
Definition at line 76 of file full-gmm-normal.cc.
References VectorBase< Real >::AddSpVec(), FullGmm::Dim(), VectorBase< Real >::Dim(), rnnlm::i, FullGmm::inv_covars_, KALDI_ASSERT, kaldi::kGmmMeans, kaldi::kGmmVariances, kaldi::kGmmWeights, FullGmmNormal::means_, FullGmm::means_invcovars_, MatrixBase< Real >::NumCols(), FullGmm::NumGauss(), MatrixBase< Real >::Row(), FullGmm::valid_gconsts_, FullGmmNormal::vars_, FullGmmNormal::weights_, and FullGmm::weights_.
Referenced by Sgmm2Project::ApplyProjection(), FullGmmNormal::FullGmmNormal(), kaldi::MleFullGmmUpdate(), and UnitTestEstimateFullGmm().
{
   KALDI_ASSERT(weights_.Dim() == fullgmm->weights_.Dim()
                && means_.NumCols() == fullgmm->Dim());
   FullGmmNormal oldg(*fullgmm);
   if (flags & kGmmWeights)
     fullgmm->weights_.CopyFromVec(weights_);
   size_t num_comp = fullgmm->NumGauss(), dim = fullgmm->Dim();
   for (size_t i = 0; i < num_comp; i++) {
     if (flags & kGmmVariances) {
       fullgmm->inv_covars_[i].CopyFromSp(vars_[i]);
       fullgmm->inv_covars_[i].InvertDouble();
       // update the mean-related natural part with old mean, if necessary
       if (!(flags & kGmmMeans)) {
         Vector<BaseFloat> mean_times_inv(dim);
         Vector<BaseFloat> mhelp(oldg.means_.Row(i));
         mean_times_inv.AddSpVec(1.0, fullgmm->inv_covars_[i], mhelp, 0.0f);
         fullgmm->means_invcovars_.Row(i).CopyFromVec(mean_times_inv);
       }
     }
     if (flags & kGmmMeans) {
       Vector<BaseFloat> mean_times_inv(dim), mean(means_.Row(i));
       mean_times_inv.AddSpVec(1.0, fullgmm->inv_covars_[i], mean, 0.0f);
       fullgmm->means_invcovars_.Row(i).CopyFromVec(mean_times_inv);
     }
   }
   fullgmm->valid_gconsts_ = false;
 }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (FullGmmNormal)
Rand()
void Rand (MatrixBase< BaseFloat > * feats)
Generates random features from the model.
Definition at line 110 of file full-gmm-normal.cc.
References VectorBase< Real >::AddTpVec(), VectorBase< Real >::CopyFromVec(), rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, FullGmmNormal::means_, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), VectorBase< Real >::RandCategorical(), MatrixBase< Real >::Row(), VectorBase< Real >::SetRandn(), FullGmmNormal::vars_, and FullGmmNormal::weights_.
Referenced by FullGmmNormal::FullGmmNormal(), UnitTestFullGmmEst(), and kaldi::UnitTestIvectorExtractor().
{
   int32 dim = means_.NumCols(), num_frames = feats->NumRows(),
       num_gauss = means_.NumRows();
   KALDI_ASSERT(feats->NumCols() == dim);
   std::vector<TpMatrix<BaseFloat> > sqrt_var(num_gauss);
   for (int32 i = 0; i < num_gauss; i++) {
     sqrt_var[i].Resize(dim);
     sqrt_var[i].Cholesky(SpMatrix<BaseFloat>(vars_[i]));
   }
   Vector<BaseFloat> rand(dim);
   for (int32 t = 0; t < num_frames; t++) {
     int32 i = weights_.RandCategorical(); // index with prob propto weights_[i].
     SubVector<BaseFloat> frame(*feats, t);
     frame.CopyFromVec(means_.Row(i));
     rand.SetRandn();
     frame.AddTpVec(1.0, sqrt_var[i], kNoTrans, rand, 1.0);
   }
 }
Resize()
void Resize (int32 nMix, int32 dim)
Resizes arrays to this dim. Does not initialize data.
Definition at line 33 of file full-gmm-normal.cc.
References VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, FullGmmNormal::means_, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), Vector< Real >::Resize(), Matrix< Real >::Resize(), FullGmmNormal::vars_, and FullGmmNormal::weights_.
Referenced by FullGmmNormal::CopyFromFullGmm(), and FullGmmNormal::FullGmmNormal().
{
   KALDI_ASSERT(nmix > 0 && dim > 0);
   if (weights_.Dim() != nmix)
     weights_.Resize(nmix);
   if (means_.NumRows() != nmix ||
       means_.NumCols() != dim)
     means_.Resize(nmix, dim);
   if (vars_.size() != nmix)
     vars_.resize(nmix);
   for (int32 i = 0; i < nmix; i++) {
     if (vars_[i].NumRows() != nmix ||
         vars_[i].NumCols() != dim) {
       vars_[i].Resize(dim);
     }
   }
 }
Member Data Documentation
means_
Matrix<double> means_
Means.
Definition at line 67 of file full-gmm-normal.h.
Referenced by Sgmm2Project::ApplyProjection(), Sgmm2Project::ComputeLdaStats(), FullGmmNormal::CopyFromFullGmm(), FullGmmNormal::CopyToFullGmm(), FullGmm::Interpolate(), DiagGmm::Interpolate(), kaldi::MleFullGmmUpdate(), FullGmmNormal::Rand(), FullGmmNormal::Resize(), and UnitTestEstimateFullGmm().
vars_
std::vector<SpMatrix<double> > vars_
covariances
Definition at line 68 of file full-gmm-normal.h.
Referenced by Sgmm2Project::ApplyProjection(), Sgmm2Project::ComputeLdaStats(), FullGmmNormal::CopyFromFullGmm(), FullGmmNormal::CopyToFullGmm(), FullGmm::Interpolate(), DiagGmm::Interpolate(), kaldi::MleFullGmmUpdate(), FullGmmNormal::Rand(), FullGmmNormal::Resize(), and UnitTestEstimateFullGmm().
weights_
Vector<double> weights_
weights (not log).
Definition at line 66 of file full-gmm-normal.h.
Referenced by FullGmmNormal::CopyFromFullGmm(), FullGmmNormal::CopyToFullGmm(), FullGmm::Interpolate(), DiagGmm::Interpolate(), kaldi::MleFullGmmUpdate(), FullGmmNormal::Rand(), and FullGmmNormal::Resize().
The documentation for this class was generated from the following files:
gmm/full-gmm-normal.h
gmm/full-gmm-normal.cc