Kaldi: TxpPcre Class Reference
TxpPcre Class Reference
Idlak_utils
Simple C++ wrapper around pcre.
#include <txppcre.h>
Public Member Functions
const pcre * Compile (const char *rgx)
Convert string into a pcre regular expression.
bool Execute (const pcre *rgx, const std::string &input)
Apply a regular expression to some input.
const char * Consume (const pcre *rgx, const char *input, int32 len)
Apply a regular expression to a string and return remaining unmatched string.
const char * Consume (const pcre *rgx, const char *input)
bool SetMatch (int32 match, std::string *tgt)
Copy matched element of input into tgt.
int32 Matches ()
Return number of matches.
Private Attributes
const char * input_
Hold pointer to last matched string.
int32 ovector_ [KALDI_TXPPCRE_MAXMATCH *3]
Hold integer offsets to matches in input.
int32 n_
Number of matches in regex.
Detailed Description
Simple C++ wrapper around pcre.
Definition at line 37 of file txppcre.h.
Member Function Documentation
Compile()
const pcre * Compile (const char * rgx)
Convert string into a pcre regular expression.
Definition at line 24 of file txppcre.cc.
Referenced by TxpTrules::Init(), TxpNRules::Init(), and TxpTrules::Parse().
{
   const char* error;
   int erroffset;
   return pcre_compile(rgx, PCRE_UTF8, &error, &erroffset, NULL);
 }
Consume() [1/2]
const char * Consume (const pcre * rgx, const char * input, int32 len)
Apply a regular expression to a string and return remaining unmatched string.
Definition at line 41 of file txppcre.cc.
References TxpPcre::input_, KALDI_TXPPCRE_MAXMATCH, TxpPcre::n_, and TxpPcre::ovector_.
Referenced by TxpPcre::Consume(), TxpTrules::ConsumePunc(), TxpNRules::ConsumePunc(), TxpNRules::ConsumeToken(), TxpTrules::ConsumeToken(), TxpTrules::ConsumeWhitespaceToken(), TxpTrules::MakeLkp(), and TxpNRules::MakeLkp().
{
   input_ = input;
   n_ = pcre_exec(rgx, NULL, input, len, 0, PCRE_NO_UTF8_CHECK,
                  ovector_,
                  KALDI_TXPPCRE_MAXMATCH * 3);
   if (n_ >= 0) {
     return input + ovector_[1];
   }
   return NULL;
 }
Consume() [2/2]
const char * Consume (const pcre * rgx, const char * input)
Definition at line 52 of file txppcre.cc.
References TxpPcre::Consume().
{
   return Consume(rgx, input, strlen(input));
 }
Execute()
bool Execute (const pcre * rgx, const std::string & input)
Apply a regular expression to some input.
Definition at line 31 of file txppcre.cc.
References TxpPcre::input_, KALDI_TXPPCRE_MAXMATCH, TxpPcre::n_, and TxpPcre::ovector_.
Referenced by TxpTrules::IsAlpha(), TxpNRules::IsAlpha(), TxpTrules::NormCaseCharacter(), and TxpNRules::NormCaseCharacter().
{
   input_ = input.c_str();
   n_ = pcre_exec(rgx, NULL, input_, input.length(), 0, PCRE_NO_UTF8_CHECK,
                  ovector_,
                  KALDI_TXPPCRE_MAXMATCH * 3);
   if (n_ >= 0) return true;
   return false;
 }
Matches()
int32 Matches () inline
Return number of matches.
Definition at line 50 of file txppcre.h.
References TxpPcre::n_.
 {return n_ - 1;}
SetMatch()
bool SetMatch (int32 match, std::string * tgt)
Copy matched element of input into tgt.
Definition at line 57 of file txppcre.cc.
References TxpPcre::input_, TxpPcre::n_, and TxpPcre::ovector_.
Referenced by TxpTrules::ConsumePunc(), TxpNRules::ConsumePunc(), TxpNRules::ConsumeToken(), TxpTrules::ConsumeToken(), TxpTrules::ConsumeWhitespaceToken(), TxpTrules::MakeLkp(), and TxpNRules::MakeLkp().
{
   if (n >= 0 && n < n_) {
     *tgt = std::string(input_ + ovector_[(n + 1) * 2],
                       ovector_[((n + 1) * 2) + 1] - ovector_[(n + 1) * 2]);
     return true;
   }
   return false;
 }
Member Data Documentation
input_
const char* input_ private
Hold pointer to last matched string.
Definition at line 53 of file txppcre.h.
Referenced by TxpPcre::Consume(), TxpPcre::Execute(), and TxpPcre::SetMatch().
n_
int32 n_ private
Number of matches in regex.
Definition at line 57 of file txppcre.h.
Referenced by TxpPcre::Consume(), TxpPcre::Execute(), TxpPcre::Matches(), and TxpPcre::SetMatch().
ovector_
int32 ovector_[KALDI_TXPPCRE_MAXMATCH *3] private
Hold integer offsets to matches in input.
Definition at line 55 of file txppcre.h.
Referenced by TxpPcre::Consume(), TxpPcre::Execute(), and TxpPcre::SetMatch().
The documentation for this class was generated from the following files:
idlaktxp/txppcre.h
idlaktxp/txppcre.cc