Kaldi: SwitchingForwardingDescriptor Class Reference
SwitchingForwardingDescriptor Class Reference
Chooses from different inputs based on the the time index modulo (the number of ForwardingDescriptors given as inputs).
#include <nnet-descriptor.h>
Public Member Functions
virtual Cindex MapToInput (const Index &ind) const
virtual int32 Dim (const Nnet &nnet) const
virtual ForwardingDescriptor * Copy () const
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
virtual int32 Modulus () const
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
This function appends to "node_indexes" all the node indexes.
virtual BaseFloat GetScaleForNode (int32 node_index) const
This function returns the scale on the node-index 'node_index' when it appears in expressions inside this descriptor, or +infinity if it does not appear.
SwitchingForwardingDescriptor (std::vector< ForwardingDescriptor *> &src)
virtual ~SwitchingForwardingDescriptor ()
Public Member Functions inherited from ForwardingDescriptor
virtual ~ForwardingDescriptor ()
ForwardingDescriptor ()
Private Attributes
std::vector< ForwardingDescriptor * > src_
Detailed Description
Chooses from different inputs based on the the time index modulo (the number of ForwardingDescriptors given as inputs).
This is rarely if ever used. Written form is: `Switch(<descriptor>, <descriptor> [, <descriptor> ...])` e.g. `Switch(tdnn2a, tdnn2b, tdnn2c)`
Definition at line 210 of file nnet-descriptor.h.
Constructor & Destructor Documentation
SwitchingForwardingDescriptor()
SwitchingForwardingDescriptor (std::vector< ForwardingDescriptor *> & src) inline
Definition at line 227 of file nnet-descriptor.h.
                                                                       :
       src_(src) { }
~SwitchingForwardingDescriptor()
virtual ~SwitchingForwardingDescriptor () inline virtual
Definition at line 229 of file nnet-descriptor.h.
References kaldi::DeletePointers().
 { DeletePointers(&src_); }
Member Function Documentation
Copy()
ForwardingDescriptor * Copy () const virtual
Implements ForwardingDescriptor.
Definition at line 161 of file nnet-descriptor.cc.
References kaldi::cu::Copy(), and rnnlm::i.
{
   std::vector<ForwardingDescriptor*> src_copy(src_.size());
   for (size_t i = 0; i < src_.size(); i++)
     src_copy[i] = src_[i]->Copy();
   return new SwitchingForwardingDescriptor(src_copy);
 }
Dim()
virtual int32 Dim (const Nnet & nnet) const inline virtual
Implements ForwardingDescriptor.
Definition at line 213 of file nnet-descriptor.h.
References ForwardingDescriptor::Copy(), ForwardingDescriptor::GetNodeDependencies(), ForwardingDescriptor::GetScaleForNode(), ForwardingDescriptor::Modulus(), and ForwardingDescriptor::WriteConfig().
 { return src_[0]->Dim(nnet); }
GetNodeDependencies()
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
This function appends to "node_indexes" all the node indexes.
Implements ForwardingDescriptor.
Definition at line 146 of file nnet-descriptor.cc.
References Descriptor::GetNodeDependencies(), and rnnlm::i.
{
   for (size_t i = 0; i < src_.size(); i++)
     src_[i]->GetNodeDependencies(node_indexes);
 }
GetScaleForNode()
BaseFloat GetScaleForNode (int32 node_index) const virtual
This function returns the scale on the node-index 'node_index' when it appears in expressions inside this descriptor, or +infinity if it does not appear.
E.g. if the descriptor is just `Scale(tdnn2, 2.0)` and the node index for `tdnn2` is 4, then GetScaleForNode(4) would return 2.0. If a particular node_index > 0 appears in different sub-expressions of the descriptor with different scales it is an error (it's not supported) and this function would crash.
Implements ForwardingDescriptor.
Definition at line 473 of file nnet-descriptor.cc.
References rnnlm::i, and KALDI_ERR.
{
   BaseFloat inf = std::numeric_limits<BaseFloat>::infinity(),
       ans = inf;
   for (size_t i = 0; i < src_.size(); i++) {
     BaseFloat this_ans = src_[i]->GetScaleForNode(node_index);
     if (this_ans != inf) {
       if (ans != inf && ans != this_ans)
         KALDI_ERR << "Invalid Descriptor encountered: for node-index "
                   << node_index << ", got two different scales "
                   << this_ans << " vs. " << ans;
       ans = this_ans;
     }
   }
   return ans;
 }
MapToInput()
Cindex MapToInput (const Index & ind) const virtual
Implements ForwardingDescriptor.
Definition at line 152 of file nnet-descriptor.cc.
References KALDI_ASSERT, and Index::t.
{
   KALDI_ASSERT(!src_.empty());
   int32 size = src_.size(), mod = ind.t % size;
   // next line gets "mathematical" modulus, not broken "C" modulus.
   if (mod < 0) mod += size;
   return src_[mod]->MapToInput(ind);
 }
Modulus()
int32 Modulus () const virtual
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
It returns the smallest modulus to which this descriptor is invariant; the lowest common multiple of all descriptors in the network gives you the modulus for the whole network.
Reimplemented from ForwardingDescriptor.
Definition at line 466 of file nnet-descriptor.cc.
References rnnlm::i, kaldi::Lcm(), and ConstantSumDescriptor::Modulus().
{
   int32 ans = src_.size();;
   for (size_t i = 0; i < src_.size(); i++)
     ans = Lcm(ans, src_[i]->Modulus());
   return ans;
 }
WriteConfig()
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
Implements ForwardingDescriptor.
Definition at line 169 of file nnet-descriptor.cc.
References rnnlm::i, and KALDI_ASSERT.
{
   KALDI_ASSERT(!src_.empty());
   os << "Switch(";
   for (size_t i = 0; i < src_.size(); i++) {
     src_[i]->WriteConfig(os, node_names);
     if (i + 1 < src_.size())
       os << ", ";
   }
   os << ")";
 }
Member Data Documentation
src_
std::vector<ForwardingDescriptor*> src_ private
Definition at line 232 of file nnet-descriptor.h.
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc