Kaldi: TxpPos Class Reference
TxpPos Class Reference
Part of speech tagger see /ref idlaktxp_pos.
#include <txppos.h>
Public Member Functions
TxpPos ()
~TxpPos ()
void Init (const TxpParseOptions &opts, const std::string &name)
bool Parse (const std::string &tpdb)
const char * GetPos (const char *prev, const char *current)
Return the part of speech for word current with previous context POS prev.
Public Member Functions inherited from TxpXmlData
TxpXmlData ()
virtual ~TxpXmlData ()
virtual void Init (const TxpParseOptions &opts, const std::string &type, const std::string &name)
Initialise the data structure by processing a tpdb file.
virtual void EndElement (const char *name)
Inherited class for bespoke end element handling.
virtual void CharHandler (const char *data, int32 len)
Inherited class for bespoke character handling.
virtual void StartCData ()
Inherited class for bespoke start cdata handling.
virtual void EndCData ()
Inherited class for bespoke start cdata handling.
bool Parse (const std::string &tpdb)
Load and parse a file belonging to the object in the tpdb directory file name is based on the object type and name set on construction the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
bool Parse (const std::string &tpdb, const std::string &fname)
Load and parse a file fname belonging to the object in the tpdb directory the system first searches spk then acc then region then lang directories unless marked as an idlak-data-flat with a dummy file of that name.
int GetCurrentLineNumber ()
int32 SetAttribute (const char *name, const char **atts, std::string *val)
Utility to set a named attribute from an expat array of attribute key value pairs.
const char * GetOptValue (const char *key)
Return a general option value.
Private Member Functions
void StartElement (const char *name, const char **atts)
Inherited class for bespoke start element handling.
Private Attributes
std::string word_
For loading pattern tagger.
std::string most_common_
Most common part of speech (default pos)
PosRgxVector rgxtagger_
Array of regular expression taggers.
LookupMap patterntagger_
unigram and POS_word bigram patterns.
Additional Inherited Members
Static Public Member Functions inherited from TxpXmlData
static void StartElementCB (void *userData, const char *name, const char **atts)
Callback functions set in expat for start element.
static void EndElementCB (void *userData, const char *name)
Callback functions set in expat for end element.
static void CharHandlerCB (void *userData, const char *data, int32 len)
Callback functions set in expat for handling characters.
static void StartCDataCB (void *userData)
Callback functions set in expat for start of Cdata (used for regular expressions)
static void EndCDataCB (void *userData)
Callback functions set in expat for end of Cdata.
Protected Attributes inherited from TxpXmlData
const TxpParseOptions * opts_
Options structure as all xmldats classes use the general section.
XML_Parser parser_
Expat parser structure.
std::string type_
Type of object e.g. lexicon.
std::string name_
Name of object e.g. default or user etc.
std::string tpdb_
Directory of the tpdb (text processing database) files.
std::string path_
Final pathname of input file.
std::string fname_
Final filename of input file.
std::string buffer_
Input file is read line by line into this buffer for processing.
Detailed Description
Part of speech tagger see /ref idlaktxp_pos.
Definition at line 49 of file txppos.h.
Constructor & Destructor Documentation
TxpPos()
TxpPos () inline explicit
Definition at line 51 of file txppos.h.
 {}
~TxpPos()
~TxpPos () inline
Definition at line 52 of file txppos.h.
 {}
Member Function Documentation
GetPos()
const char * GetPos (const char * prev, const char * current)
Return the part of speech for word current with previous context POS prev.
Definition at line 34 of file txppos.cc.
References TxpPos::most_common_, TxpPos::patterntagger_, TxpPos::rgxtagger_, kaldi::TXPPOSRGX_POS_PREFIX, kaldi::TXPPOSRGX_POS_SUFFIX, and kaldi::TXPPOSRGX_POS_WORD.
Referenced by TxpPos::Init(), and TxpPosTag::Process().
{
   PosRgxVector::iterator it;
   LookupMap::iterator lkp;
   const char* current_tag;
   current_tag =  most_common_.c_str();
   // Regex tagger
   for (it = rgxtagger_.begin(); it != rgxtagger_.end(); ++it) {
     if ((*it).pos == TXPPOSRGX_POS_WORD &&
         !strcmp((*it).pattern.c_str(), word)) {
       current_tag = (*it).tag.c_str();
       break;
     } else if ((*it).pos == TXPPOSRGX_POS_PREFIX &&
              !strncmp((*it).pattern.c_str(), word, (*it).pattern.length())) {
       current_tag = (*it).tag.c_str();
       break;
     } else if ((*it).pos == TXPPOSRGX_POS_SUFFIX &&
              (*it).pattern.length() < strlen(word) &&
              !strcmp((*it).pattern.c_str(),
                      word + (strlen(word) - (*it).pattern.length()))) {
       current_tag = (*it).tag.c_str();
       break;
     }
   }
   // Pattern tagger: unigram
   lkp = patterntagger_.find(std::string(word));
   if (lkp != patterntagger_.end()) {
     current_tag = (lkp->second).c_str();
   }
   // bigram
   if (*ptag) {
     lkp = patterntagger_.find(std::string(ptag) + "_" + std::string(word));
     if (lkp != patterntagger_.end()) {
       current_tag = lkp->second.c_str();
     }
   }
   return current_tag;
 }
Init()
void Init (const TxpParseOptions & opts, const std::string & name) inline
Definition at line 53 of file txppos.h.
References TxpPos::GetPos(), TxpXmlData::Init(), TxpPos::Parse(), and TxpPos::StartElement().
Referenced by TxpPosTag::Init().
{
     TxpXmlData::Init(opts, "postags", name);
   }
Parse()
bool Parse (const std::string & tpdb)
Definition at line 26 of file txppos.cc.
References KALDI_WARN, and TxpXmlData::Parse().
Referenced by TxpPosTag::Init(), TxpPos::Init(), and TxpPosSet::Init().
{
   bool r;
   r = TxpXmlData::Parse(tpdb);
   if (!r)
     KALDI_WARN << "Error reading part of speech tagger file: " << tpdb;
   return r;
 }
StartElement()
void StartElement (const char * name, const char ** atts) private virtual
Inherited class for bespoke start element handling.
Reimplemented from TxpXmlData.
Definition at line 72 of file txppos.cc.
References TxpPos::most_common_, TxpPosRgx::pattern, TxpPos::patterntagger_, TxpPosRgx::pos, TxpPos::rgxtagger_, TxpXmlData::SetAttribute(), TxpPosRgx::tag, kaldi::TXPPOSRGX_POS_PREFIX, kaldi::TXPPOSRGX_POS_SUFFIX, kaldi::TXPPOSRGX_POS_WORD, and TxpPos::word_.
Referenced by TxpPos::Init(), and TxpPosSet::Init().
{
   std::string pos;
   std::string tag;
   std::string ptag;
   TxpPosRgx rgx;
   if (!strcmp(name, "most_common")) {
     SetAttribute("tag", atts, &most_common_);
   }
   if (!strcmp(name, "r")) {
     SetAttribute("pos", atts, &pos);
     if (pos == "WORD") rgx.pos = TXPPOSRGX_POS_WORD;
     else if (pos == "PREFIX") rgx.pos = TXPPOSRGX_POS_PREFIX;
     else if (pos == "SUFFIX") rgx.pos = TXPPOSRGX_POS_SUFFIX;
     SetAttribute("pat", atts, &(rgx.pattern));
     SetAttribute("tag", atts, &(rgx.tag));
     rgxtagger_.push_back(rgx);
   } else if (!strcmp(name, "w")) {
     SetAttribute("name", atts, &word_);
   } else if (!strcmp(name, "p")) {
     SetAttribute("tag", atts, &tag);
     SetAttribute("ptag", atts, &ptag);
     if (ptag.empty())
       patterntagger_.insert(LookupItem(word_, tag));
     else
       patterntagger_.insert(LookupItem(word_, tag + "_" + word_));
   }
 }
Member Data Documentation
most_common_
std::string most_common_ private
Most common part of speech (default pos)
Definition at line 67 of file txppos.h.
Referenced by TxpPos::GetPos(), and TxpPos::StartElement().
patterntagger_
LookupMap patterntagger_ private
unigram and POS_word bigram patterns.
Definition at line 72 of file txppos.h.
Referenced by TxpPos::GetPos(), and TxpPos::StartElement().
rgxtagger_
PosRgxVector rgxtagger_ private
Array of regular expression taggers.
Note this doesn't use pcre because the regexs are only ever whole words, prefixes or suffixes
Definition at line 70 of file txppos.h.
Referenced by TxpPos::GetPos(), and TxpPos::StartElement().
word_
std::string word_ private
For loading pattern tagger.
Definition at line 64 of file txppos.h.
Referenced by TxpPos::StartElement().
The documentation for this class was generated from the following files:
idlaktxp/txppos.h
idlaktxp/txppos.cc