Kaldi: PerElementScaleComponent Class Reference
PerElementScaleComponent Class Reference
PerElementScaleComponent scales each dimension of its input with a separate trainable scale; it's like a linear component with a diagonal matrix.
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
PerElementScaleComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void * Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, void *memo, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
PerElementScaleComponent (const PerElementScaleComponent &other)
void Init (int32 dim, BaseFloat param_mean, BaseFloat param_stddev)
void Init (std::string vector_filename)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetUnderlyingLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent- gets multiplied by learning_rate_factor_.
virtual void SetActualLearningRate (BaseFloat lrate)
Sets the learning rate directly, bypassing learning_rate_factor_.
virtual void SetAsGradient ()
Sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual BaseFloat LearningRateFactor ()
virtual void SetLearningRateFactor (BaseFloat lrate_factor)
void SetUpdatableConfigs (const UpdatableComponent &other)
virtual void FreezeNaturalGradient (bool freeze)
freezes/unfreezes NaturalGradient updates, if applicable (to be overriden by components that use Natural Gradient).
BaseFloat LearningRate () const
Gets the learning rate to be used in gradient descent.
BaseFloat MaxChange () const
Returns the per-component max-change value, which is interpreted as the maximum change (in l2 norm) in parameters that is allowed per minibatch for this component.
void SetMaxChange (BaseFloat max_change)
BaseFloat L2Regularization () const
Returns the l2 regularization constant, which may be set in any updatable component (usually from the config file).
void SetL2Regularization (BaseFloat a)
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, void *memo)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function must return NULL for simple Components.
virtual void DeleteMemo (void *memo) const
This virtual function only needs to be overwritten by Components that return a non-NULL memo from their Propagate() function.
virtual void ConsolidateMemory ()
This virtual function relates to memory management, and avoiding fragmentation.
Component ()
virtual ~Component ()
Protected Member Functions
virtual void Update (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
virtual void UpdateSimple (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
const PerElementScaleComponent & operator= (const PerElementScaleComponent &other)
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
std::string ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes
CuVector< BaseFloat > scales_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
BaseFloat l2_regularize_
L2 regularization constant.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
BaseFloat max_change_
configuration value for imposing max-change
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
PerElementScaleComponent scales each dimension of its input with a separate trainable scale; it's like a linear component with a diagonal matrix.
This version (and its child class NaturalGradientPerElementScaleComponent) requires the input for backprop. See also ScaleAndOffsetComponent.
Accepted values on its config line, with defaults if applicable:
vector If specified, the offsets will be read from this file ('vector' is interpreted as an rxfilename).
dim The dimension that this component inputs and outputs. Only required if 'vector' is not specified.
param-mean=1.0 Mean of randomly initialized offset parameters; should only be supplied if 'vector' is not supplied. param-stddev=0.0 Standard deviation of randomly initialized offset parameters; should only be supplied if 'vector' is not supplied.
Definition at line 1513 of file nnet-simple-component.h.
Constructor & Destructor Documentation
PerElementScaleComponent() [1/2]
PerElementScaleComponent () inline
Definition at line 1521 of file nnet-simple-component.h.
Referenced by PerElementScaleComponent::Copy().
 { } // use Init to really initialize.
PerElementScaleComponent() [2/2]
PerElementScaleComponent (const PerElementScaleComponent & other) explicit
Definition at line 1951 of file nnet-simple-component.cc.
                                               :
     UpdatableComponent(component),
     scales_(component.scales_) { }
Member Function Documentation
Add()
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent (or another component that stores stats, like BatchNormComponent)– it relates to adding stats. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1943 of file nnet-simple-component.cc.
References KALDI_ASSERT, and PerElementScaleComponent::scales_.
{
   const PerElementScaleComponent *other =
       dynamic_cast<const PerElementScaleComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   scales_.AddVec(alpha, other->scales_);
 }
Backprop()
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, void * memo, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[in] memo This will normally be NULL, but for component types that set the flag kUsesMemo, this will be the return value of the Propagate() function that corresponds to this Backprop() function. Ownership of any pointers is not transferred to the Backprop function; DeleteMemo() will be called to delete it.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this. If supplied, you can assume that to_update->Properties() & kUpdatableComponent is nonzero.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 2037 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::Data(), UpdatableComponent::is_gradient_, CuMatrixBase< Real >::MulColsVec(), PerElementScaleComponent::scales_, PerElementScaleComponent::Update(), and PerElementScaleComponent::UpdateSimple().
{
   PerElementScaleComponent *to_update =
       dynamic_cast<PerElementScaleComponent*>(to_update_in);
   if (to_update != NULL) {
     // Next update the model (must do this 2nd so the derivatives we propagate
     // are accurate, in case this == to_update_in.)
     if (to_update->is_gradient_)
       to_update->UpdateSimple(in_value, out_deriv);
     else  // the call below is to a virtual function that may be re-implemented
       to_update->Update(debug_info, in_value, out_deriv);  // by child classes.
   }
   if (in_deriv) {
     // Propagate the derivative back to the input.
     if (in_deriv->Data() != out_deriv.Data())
       in_deriv->CopyFromMat(out_deriv);
     in_deriv->MulColsVec(scales_);
   }
 }
Copy()
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Reimplemented in NaturalGradientPerElementScaleComponent.
Definition at line 1971 of file nnet-simple-component.cc.
References PerElementScaleComponent::PerElementScaleComponent().
{
   return new PerElementScaleComponent(*this);
 }
DotProduct()
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 1975 of file nnet-simple-component.cc.
References PerElementScaleComponent::scales_, and kaldi::VecVec().
{
   const PerElementScaleComponent *other =
       dynamic_cast<const PerElementScaleComponent*>(&other_in);
   return VecVec(scales_, other->scales_);
 }
Info()
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Reimplemented in NaturalGradientPerElementScaleComponent.
Definition at line 1962 of file nnet-simple-component.cc.
References UpdatableComponent::Info(), kaldi::nnet3::PrintParameterStats(), and PerElementScaleComponent::scales_.
Referenced by NaturalGradientPerElementScaleComponent::Info().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info()
          << ", scales-min=" << scales_.Min()
          << ", scales-max=" << scales_.Max();
   PrintParameterStats(stream, "scales", scales_, true);
   return stream.str();
 }
Init() [1/2]
void Init (int32 dim, BaseFloat param_mean, BaseFloat param_stddev)
Definition at line 1982 of file nnet-simple-component.cc.
References KALDI_ASSERT, and PerElementScaleComponent::scales_.
Referenced by NaturalGradientPerElementScaleComponent::Init(), and PerElementScaleComponent::InitFromConfig().
{
   KALDI_ASSERT(dim > 0 && param_stddev >= 0.0);
   scales_.Resize(dim);
   scales_.SetRandn();
   scales_.Scale(param_stddev);
   scales_.Add(param_mean);
 }
Init() [2/2]
void Init (std::string vector_filename)
Definition at line 1992 of file nnet-simple-component.cc.
References CuVectorBase< Real >::Dim(), kaldi::ReadKaldiObject(), and PerElementScaleComponent::scales_.
{
   CuVector<BaseFloat> vec;
   ReadKaldiObject(vector_filename, &vec); // will abort on failure.
   scales_.Resize(vec.Dim());
   scales_.CopyFromVec(vec);
 }
InitFromConfig()
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Reimplemented in NaturalGradientPerElementScaleComponent.
Definition at line 1999 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), PerElementScaleComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), PerElementScaleComponent::InputDim(), KALDI_ASSERT, KALDI_ERR, and ConfigLine::UnusedValues().
{
   std::string vector_filename;
   int32 dim = -1;
   InitLearningRatesFromConfig(cfl);
   if (cfl->GetValue("vector", &vector_filename)) {
     Init(vector_filename);
     if (cfl->GetValue("dim", &dim))
       KALDI_ASSERT(dim == InputDim() &&
                    "input-dim mismatch vs. vector.");
   } else {
     if(!cfl->GetValue("dim", &dim))
       KALDI_ERR << "'dim' not provided in the config line.";
     BaseFloat param_mean = 1.0, param_stddev = 0.0;
     cfl->GetValue("param-mean", &param_mean);
     cfl->GetValue("param-stddev", &param_stddev);
     Init(dim, param_mean, param_stddev);
   }
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
 }
InputDim()
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1515 of file nnet-simple-component.h.
Referenced by PerElementScaleComponent::InitFromConfig(), and PerElementScaleComponent::NumParameters().
 { return scales_.Dim(); }
NumParameters()
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 2086 of file nnet-simple-component.cc.
References PerElementScaleComponent::InputDim().
{
   return InputDim();
 }
operator=()
const PerElementScaleComponent& operator= (const PerElementScaleComponent & other) protected
OutputDim()
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1516 of file nnet-simple-component.h.
References Component::Info(), and PnormComponent::InitFromConfig().
 { return scales_.Dim(); }
PerturbParams()
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 1956 of file nnet-simple-component.cc.
References kaldi::kUndefined, PerElementScaleComponent::scales_, and CuVectorBase< Real >::SetRandn().
{
   CuVector<BaseFloat> temp_scales(scales_.Dim(), kUndefined);
   temp_scales.SetRandn();
   scales_.AddVec(stddev, temp_scales);
 }
Propagate()
void * Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Returns
Normally returns NULL, but may return a non-NULL value for components which have the flag kUsesMemo set. This value will be passed into the corresponding Backprop routine.
Implements Component.
Definition at line 2021 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::MulColsVec(), and PerElementScaleComponent::scales_.
{
   out->CopyFromMat(in);
   out->MulColsVec(scales_);
   return NULL;
 }
Properties()
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1523 of file nnet-simple-component.h.
References Component::Add(), PnormComponent::Backprop(), PnormComponent::Copy(), kaldi::nnet3::DotProduct(), PnormComponent::Init(), kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kPropagateInPlace, kaldi::nnet3::kSimpleComponent, kaldi::nnet3::kUpdatableComponent, kaldi::nnet3::NumParameters(), kaldi::nnet3::PerturbParams(), PnormComponent::Propagate(), PnormComponent::Read(), Component::Scale(), and PnormComponent::Write().
{
     return kSimpleComponent|kUpdatableComponent|kBackpropNeedsInput|
         kPropagateInPlace|kBackpropInPlace;
   }
Read()
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Reimplemented in NaturalGradientPerElementScaleComponent.
Definition at line 2066 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, kaldi::PeekToken(), kaldi::ReadBasicType(), UpdatableComponent::ReadUpdatableCommon(), and PerElementScaleComponent::scales_.
{
   ReadUpdatableCommon(is, binary);  // Read opening tag and learning rate.
   ExpectToken(is, binary, "<Params>");
   scales_.Read(is, binary);
   if (PeekToken(is, binary) == 'I') {
     // for back compatibility; we don't write this here any
     // more as it's written and read in Write/ReadUpdatableCommon
     ExpectToken(is, binary, "<IsGradient>");
     ReadBasicType(is, binary, &is_gradient_);
   }
   ExpectToken(is, binary, "</PerElementScaleComponent>");
 }
Scale()
void Scale (BaseFloat scale) virtual
This virtual function when called on – an UpdatableComponent scales the parameters by "scale" when called by an UpdatableComponent.
– a Nonlinear component (or another component that stores stats, like BatchNormComponent)– it relates to scaling activation stats, not parameters. Otherwise it will normally do nothing.
Reimplemented from Component.
Definition at line 1935 of file nnet-simple-component.cc.
{
   if (scale == 0.0) {
     scales_.SetZero();
   } else {
     scales_.Scale(scale);
   }
 }
Type()
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Reimplemented in NaturalGradientPerElementScaleComponent.
Definition at line 1522 of file nnet-simple-component.h.
 { return "PerElementScaleComponent"; }
UnVectorize()
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 2094 of file nnet-simple-component.cc.
References PerElementScaleComponent::scales_.
{
   scales_.CopyFromVec(params);
 }
Update()
virtual void Update (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) inline protected virtual
Reimplemented in NaturalGradientPerElementScaleComponent.
Definition at line 1564 of file nnet-simple-component.h.
Referenced by PerElementScaleComponent::Backprop().
{
     UpdateSimple(in_value, out_deriv);
   }
UpdateSimple()
void UpdateSimple (const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) protected virtual
Definition at line 2030 of file nnet-simple-component.cc.
References kaldi::kNoTrans, kaldi::kTrans, UpdatableComponent::learning_rate_, and PerElementScaleComponent::scales_.
Referenced by PerElementScaleComponent::Backprop().
{
   scales_.AddDiagMatMat(learning_rate_, out_deriv, kTrans,
                         in_value, kNoTrans, 1.0);
 }
Vectorize()
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 2090 of file nnet-simple-component.cc.
References VectorBase< Real >::CopyFromVec(), and PerElementScaleComponent::scales_.
{
   params->CopyFromVec(scales_);
 }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Reimplemented in NaturalGradientPerElementScaleComponent.
Definition at line 2079 of file nnet-simple-component.cc.
References PerElementScaleComponent::scales_, kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate.
   WriteToken(os, binary, "<Params>");
   scales_.Write(os, binary);
   WriteToken(os, binary, "</PerElementScaleComponent>");
 }
Member Data Documentation
scales_
CuVector<BaseFloat> scales_ protected
Definition at line 1578 of file nnet-simple-component.h.
Referenced by PerElementScaleComponent::Add(), PerElementScaleComponent::Backprop(), PerElementScaleComponent::DotProduct(), PerElementScaleComponent::Info(), PerElementScaleComponent::Init(), PerElementScaleComponent::PerturbParams(), PerElementScaleComponent::Propagate(), PerElementScaleComponent::Read(), PerElementScaleComponent::UnVectorize(), NaturalGradientPerElementScaleComponent::Update(), PerElementScaleComponent::UpdateSimple(), PerElementScaleComponent::Vectorize(), and PerElementScaleComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc