Kaldi: VectorClusterable Class Reference
VectorClusterable Class Reference
VectorClusterable wraps vectors in a form accessible to generic clustering algorithms.
#include <clusterable-classes.h>
Public Member Functions
VectorClusterable ()
VectorClusterable (const Vector< BaseFloat > &vector, BaseFloat weight)
virtual std::string Type () const
Return a string that describes the inherited type.
virtual BaseFloat Objf () const
Return the objective function associated with the stats [assuming ML estimation].
virtual void SetZero ()
Set stats to empty.
virtual void Add (const Clusterable &other_in)
Add other stats.
virtual void Sub (const Clusterable &other_in)
Subtract other stats.
virtual BaseFloat Normalizer () const
Return the normalizer (typically, count) associated with the stats.
virtual Clusterable * Copy () const
Return a copy of this object.
virtual void Scale (BaseFloat f)
Scale the stats by a positive number f [not mandatory to supply this].
virtual void Write (std::ostream &os, bool binary) const
Write data to stream.
virtual Clusterable * ReadNew (std::istream &is, bool binary) const
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
virtual ~VectorClusterable ()
Public Member Functions inherited from Clusterable
virtual ~Clusterable ()
virtual BaseFloat ObjfPlus (const Clusterable &other) const
Return the objective function of the combined object this + other.
virtual BaseFloat ObjfMinus (const Clusterable &other) const
Return the objective function of the subtracted object this - other.
virtual BaseFloat Distance (const Clusterable &other) const
Return the objective function decrease from merging the two clusters, negated to be a positive number (or zero).
Private Member Functions
void Read (std::istream &is, bool binary)
Private Attributes
double weight_
Vector< double > stats_
double sumsq_
Detailed Description
VectorClusterable wraps vectors in a form accessible to generic clustering algorithms.
Each vector is associated with a weight; these could be 1.0. The objective function (to be maximized) is the negated sum of squared distances from the cluster center to each vector, times that vector's weight.
Definition at line 121 of file clusterable-classes.h.
Constructor & Destructor Documentation
VectorClusterable() [1/2]
VectorClusterable () inline
Definition at line 123 of file clusterable-classes.h.
 : weight_(0.0), sumsq_(0.0) {}
VectorClusterable() [2/2]
VectorClusterable (const Vector< BaseFloat > & vector, BaseFloat weight)
Definition at line 296 of file clusterable-classes.cc.
References KALDI_ASSERT, VectorBase< Real >::Scale(), VectorClusterable::stats_, VectorClusterable::sumsq_, and kaldi::VecVec().
                                                       :
     weight_(weight), stats_(vector), sumsq_(0.0) {
   stats_.Scale(weight);
   KALDI_ASSERT(weight >= 0.0);
   sumsq_ = VecVec(vector, vector) * weight;
 }
~VectorClusterable()
virtual ~VectorClusterable () inline virtual
Definition at line 139 of file clusterable-classes.h.
 {}
Member Function Documentation
Add()
void Add (const Clusterable & other) virtual
Add other stats.
Implements Clusterable.
Definition at line 225 of file clusterable-classes.cc.
References KALDI_ASSERT, Clusterable::Type(), and VectorClusterable::weight_.
Referenced by kaldi::TestClusterUtilsVector().
{
   KALDI_ASSERT(other_in.Type() == "vector");
   const VectorClusterable *other =
       static_cast<const VectorClusterable*>(&other_in);
   weight_ += other->weight_;
   stats_.AddVec(1.0, other->stats_);
   sumsq_ += other->sumsq_;
 }
Copy()
Clusterable * Copy () const virtual
Return a copy of this object.
Implements Clusterable.
Definition at line 255 of file clusterable-classes.cc.
References VectorClusterable::stats_, VectorClusterable::sumsq_, and VectorClusterable::weight_.
{
   VectorClusterable *ans = new VectorClusterable();
   ans->weight_ = weight_;
   ans->sumsq_ = sumsq_;
   ans->stats_ = stats_;
   return ans;
 }
Normalizer()
virtual BaseFloat Normalizer () const inline virtual
Return the normalizer (typically, count) associated with the stats.
Implements Clusterable.
Definition at line 134 of file clusterable-classes.h.
References GaussClusterable::Copy(), GaussClusterable::ReadNew(), GaussClusterable::Scale(), and GaussClusterable::Write().
 { return weight_; }
Objf()
BaseFloat Objf () const virtual
Return the objective function associated with the stats [assuming ML estimation].
Implements Clusterable.
Definition at line 305 of file clusterable-classes.cc.
References KALDI_WARN, VectorClusterable::stats_, VectorClusterable::sumsq_, kaldi::VecVec(), and VectorClusterable::weight_.
Referenced by kaldi::TestClusterUtilsVector().
{
   double direct_sumsq;
   if (weight_ > std::numeric_limits<BaseFloat>::min()) {
     direct_sumsq = VecVec(stats_, stats_) / weight_;
   } else {
     direct_sumsq = 0.0;
   }
   // ans is a negated weighted sum of squared distances; it should not be
   // positive.
   double ans = -(sumsq_ - direct_sumsq);
   if (ans > 0.0) {
     if (ans > 1.0) {
       KALDI_WARN << "Positive objective function encountered (treating as zero): "
                  << ans;
     }
     ans = 0.0;
   }
   return ans;
 }
Read()
void Read (std::istream & is, bool binary) private
Definition at line 286 of file clusterable-classes.cc.
References kaldi::ExpectToken(), and kaldi::ReadBasicType().
Referenced by VectorClusterable::ReadNew().
{
   ExpectToken(is, binary, "VCL");  // magic string.
   ExpectToken(is, binary, "<Weight>");
   ReadBasicType(is, binary, &weight_);
   ExpectToken(is, binary, "<Sumsq>");
   ReadBasicType(is, binary, &sumsq_);
   ExpectToken(is, binary, "<Stats>");
   stats_.Read(is, binary);
 }
ReadNew()
Clusterable * ReadNew (std::istream & os, bool binary) const virtual
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
Implements Clusterable.
Definition at line 280 of file clusterable-classes.cc.
References VectorClusterable::Read().
{
   VectorClusterable *vc = new VectorClusterable();
   vc->Read(is, binary);
   return vc;
 }
Scale()
void Scale (BaseFloat f) virtual
Scale the stats by a positive number f [not mandatory to supply this].
Reimplemented from Clusterable.
Definition at line 263 of file clusterable-classes.cc.
References KALDI_ASSERT.
{
   KALDI_ASSERT(f >= 0.0);
   weight_ *= f;
   stats_.Scale(f);
   sumsq_ *= f;
 }
SetZero()
virtual void SetZero () inline virtual
Set stats to empty.
Implements Clusterable.
Definition at line 131 of file clusterable-classes.h.
References GaussClusterable::Add(), MatrixBase< Real >::Set(), GaussClusterable::stats_, and GaussClusterable::Sub().
 { weight_ = 0.0; sumsq_ = 0.0; stats_.Set(0.0); }
Sub()
void Sub (const Clusterable & other) virtual
Subtract other stats.
Implements Clusterable.
Definition at line 234 of file clusterable-classes.cc.
References KALDI_ASSERT, KALDI_WARN, Clusterable::Type(), and VectorClusterable::weight_.
{
   KALDI_ASSERT(other_in.Type() == "vector");
   const VectorClusterable *other =
       static_cast<const VectorClusterable*>(&other_in);
   weight_ -= other->weight_;
   sumsq_ -= other->sumsq_;
   stats_.AddVec(-1.0, other->stats_);
   if (weight_ < 0.0) {
     if (weight_ < -0.1 && weight_ < -0.0001 * fabs(other->weight_)) {
       // a negative weight may indicate an algorithmic error if it is
       // encountered.
       KALDI_WARN << "Negative weight encountered " << weight_;
     }
     weight_ = 0.0;
   }
   if (weight_ == 0.0) {
     sumsq_ = 0.0;
     stats_.Set(0.0);
   }
 }
Type()
virtual std::string Type () const inline virtual
Return a string that describes the inherited type.
Implements Clusterable.
Definition at line 128 of file clusterable-classes.h.
References GaussClusterable::Objf().
 {  return "vector"; }
Write()
void Write (std::ostream & os, bool binary) const virtual
Write data to stream.
Implements Clusterable.
Definition at line 270 of file clusterable-classes.cc.
References kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "VCL");  // magic string.
   WriteToken(os, binary, "<Weight>");
   WriteBasicType(os, binary, weight_);
   WriteToken(os, binary, "<Sumsq>");
   WriteBasicType(os, binary, sumsq_);
   WriteToken(os, binary, "<Stats>");
   stats_.Write(os, binary);
 }
Member Data Documentation
stats_
Vector<double> stats_ private
Definition at line 143 of file clusterable-classes.h.
Referenced by VectorClusterable::Copy(), VectorClusterable::Objf(), and VectorClusterable::VectorClusterable().
sumsq_
double sumsq_ private
Definition at line 144 of file clusterable-classes.h.
Referenced by VectorClusterable::Copy(), VectorClusterable::Objf(), and VectorClusterable::VectorClusterable().
weight_
double weight_ private
Definition at line 142 of file clusterable-classes.h.
Referenced by VectorClusterable::Add(), VectorClusterable::Copy(), VectorClusterable::Objf(), and VectorClusterable::Sub().
The documentation for this class was generated from the following files:
tree/clusterable-classes.h
tree/clusterable-classes.cc