Kaldi: CompactLatticeWeightCommonDivisorTpl< BaseWeightType, IntType > Class Template Reference
CompactLatticeWeightCommonDivisorTpl< BaseWeightType, IntType > Class Template Reference
#include <lattice-weight.h>
Public Types
typedef CompactLatticeWeightTpl< BaseWeightType, IntType > Weight
Public Member Functions
Weight operator() (const Weight &w1, const Weight &w2) const
Detailed Description
template<class BaseWeightType, class IntType>
class fst::CompactLatticeWeightCommonDivisorTpl< BaseWeightType, IntType >
Definition at line 785 of file lattice-weight.h.
Member Typedef Documentation
Weight
typedef CompactLatticeWeightTpl<BaseWeightType, IntType> Weight
Definition at line 787 of file lattice-weight.h.
Member Function Documentation
operator()()
Weight operator() (const Weight & w1, const Weight & w2) const inline
Definition at line 789 of file lattice-weight.h.
References fst::Plus(), CompactLatticeWeightTpl< WeightType, IntType >::String(), and CompactLatticeWeightTpl< WeightType, IntType >::Weight().
{
     // First find longest common prefix of the strings.
     typename vector<IntType>::const_iterator s1b = w1.String().begin(),
         s1e = w1.String().end(), s2b = w2.String().begin(), s2e = w2.String().end();
     while (s1b < s1e && s2b < s2e && *s1b == *s2b) {
       s1b++;
       s2b++;
     }
     return Weight(Plus(w1.Weight(), w2.Weight()), vector<IntType>(w1.String().begin(), s1b));
   }
The documentation for this class was generated from the following file:
fstext/lattice-weight.h