Kaldi: ComponentPrecomputedIndexes Class Reference
ComponentPrecomputedIndexes Class Reference abstract
#include <nnet-component-itf.h>
Public Member Functions
virtual ComponentPrecomputedIndexes * Copy () const =0
virtual void Write (std::ostream &os, bool binary) const =0
virtual void Read (std::istream &os, bool binary)=0
virtual std::string Type () const =0
virtual ~ComponentPrecomputedIndexes ()
Static Public Member Functions
static ComponentPrecomputedIndexes * ReadNew (std::istream &is, bool binary)
static ComponentPrecomputedIndexes * NewComponentPrecomputedIndexesOfType (const std::string &cpi_type)
Detailed Description
Definition at line 97 of file nnet-component-itf.h.
Constructor & Destructor Documentation
~ComponentPrecomputedIndexes()
virtual ~ComponentPrecomputedIndexes () inline virtual
Definition at line 107 of file nnet-component-itf.h.
 { }
Member Function Documentation
Copy()
virtual ComponentPrecomputedIndexes* Copy () const pure virtual
Implemented in GeneralDropoutComponentPrecomputedIndexes, BackpropTruncationComponentPrecomputedIndexes, TdnnComponent::PrecomputedIndexes, StatisticsPoolingComponentPrecomputedIndexes, StatisticsExtractionComponentPrecomputedIndexes, TimeHeightConvolutionComponent::PrecomputedIndexes, RestrictedAttentionComponent::PrecomputedIndexes, and DistributeComponentPrecomputedIndexes.
Referenced by Component::PrecomputeIndexes().
NewComponentPrecomputedIndexesOfType()
ComponentPrecomputedIndexes * NewComponentPrecomputedIndexesOfType (const std::string & cpi_type) static
Definition at line 54 of file nnet-component-itf.cc.
References KALDI_ASSERT, and ComponentPrecomputedIndexes::Type().
Referenced by ComponentPrecomputedIndexes::ReadNew().
{
   ComponentPrecomputedIndexes *ans = NULL;
   if (cpi_type == "DistributeComponentPrecomputedIndexes") {
     ans = new DistributeComponentPrecomputedIndexes();
   } else if (cpi_type == "StatisticsExtractionComponentPrecomputedIndexes") {
     ans = new StatisticsExtractionComponentPrecomputedIndexes();
   } else if (cpi_type == "StatisticsPoolingComponentPrecomputedIndexes") {
     ans = new StatisticsPoolingComponentPrecomputedIndexes();
   } else if (cpi_type == "BackpropTruncationComponentPrecomputedIndexes") {
     ans = new BackpropTruncationComponentPrecomputedIndexes();
   } else if (cpi_type == "TimeHeightConvolutionComponentPrecomputedIndexes") {
     ans = new TimeHeightConvolutionComponent::PrecomputedIndexes();
   } else if (cpi_type == "RestrictedAttentionComponentPrecomputedIndexes") {
     ans = new RestrictedAttentionComponent::PrecomputedIndexes();
   } else if (cpi_type == "GeneralDropoutComponentPrecomputedIndexes") {
     ans = new GeneralDropoutComponentPrecomputedIndexes();
   } else if (cpi_type == "TdnnComponentPrecomputedIndexes") {
     ans = new TdnnComponent::PrecomputedIndexes();
   }
   if (ans != NULL) {
     KALDI_ASSERT(cpi_type == ans->Type());
   }
   return ans;
 }
Read()
virtual void Read (std::istream & os, bool binary) pure virtual
Implemented in GeneralDropoutComponentPrecomputedIndexes, BackpropTruncationComponentPrecomputedIndexes, TdnnComponent::PrecomputedIndexes, StatisticsPoolingComponentPrecomputedIndexes, StatisticsExtractionComponentPrecomputedIndexes, TimeHeightConvolutionComponent::PrecomputedIndexes, RestrictedAttentionComponent::PrecomputedIndexes, and DistributeComponentPrecomputedIndexes.
Referenced by NonlinearComponent::OutputDim(), Component::PrecomputeIndexes(), and ComponentPrecomputedIndexes::ReadNew().
ReadNew()
ComponentPrecomputedIndexes * ReadNew (std::istream & is, bool binary) static
Definition at line 41 of file nnet-component-itf.cc.
References KALDI_ERR, ComponentPrecomputedIndexes::NewComponentPrecomputedIndexesOfType(), ComponentPrecomputedIndexes::Read(), and kaldi::ReadToken().
Referenced by Component::PrecomputeIndexes(), and NnetComputation::Read().
{
   std::string token;
   ReadToken(is, binary, &token); // e.g. "<DistributePrecomputedComponentIndexes>".
   token.erase(0, 1); // erase "<".
   token.erase(token.length()-1); // erase ">".
   ComponentPrecomputedIndexes *ans = NewComponentPrecomputedIndexesOfType(token);
   if (!ans)
    KALDI_ERR << "Unknown ComponentPrecomputedIndexes type " << token;
   ans->Read(is, binary);
   return ans;
 }
Type()
virtual std::string Type () const pure virtual
Implemented in GeneralDropoutComponentPrecomputedIndexes, BackpropTruncationComponentPrecomputedIndexes, TdnnComponent::PrecomputedIndexes, StatisticsPoolingComponentPrecomputedIndexes, StatisticsExtractionComponentPrecomputedIndexes, TimeHeightConvolutionComponent::PrecomputedIndexes, RestrictedAttentionComponent::PrecomputedIndexes, and DistributeComponentPrecomputedIndexes.
Referenced by Component::Info(), ComponentPrecomputedIndexes::NewComponentPrecomputedIndexesOfType(), and Component::PrecomputeIndexes().
Write()
virtual void Write (std::ostream & os, bool binary) const pure virtual
Implemented in GeneralDropoutComponentPrecomputedIndexes, BackpropTruncationComponentPrecomputedIndexes, TdnnComponent::PrecomputedIndexes, StatisticsPoolingComponentPrecomputedIndexes, StatisticsExtractionComponentPrecomputedIndexes, TimeHeightConvolutionComponent::PrecomputedIndexes, RestrictedAttentionComponent::PrecomputedIndexes, and DistributeComponentPrecomputedIndexes.
Referenced by NonlinearComponent::OutputDim(), Component::PrecomputeIndexes(), and NnetComputation::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-component-itf.h
nnet3/nnet-component-itf.cc