Kaldi: CuCompressedMatrixBase Class Reference
CuCompressedMatrixBase Class Reference abstract
Class CuCompressedMatrixBase is an abstract base class that allows you to compress a matrix of type CuMatrix<BaseFloat>.
#include <cu-compressed-matrix.h>
Public Member Functions
virtual void CopyFromMat (const CuMatrixBase< BaseFloat > &mat)=0
Sets *this to an appropriately compressed copy of 'mat', which includes resizing *this.
virtual void CopyToMat (CuMatrixBase< BaseFloat > *mat) const =0
Copies the contents of *this to 'mat', which should be correctly sized beforehand.
virtual int32 NumRows () const =0
virtual int32 NumCols () const =0
virtual ~CuCompressedMatrixBase ()
Detailed Description
Class CuCompressedMatrixBase is an abstract base class that allows you to compress a matrix of type CuMatrix<BaseFloat>.
When you instantiate it you would choose the child-class type (by allocating the appropriate child-class type via 'new').
Definition at line 35 of file cu-compressed-matrix.h.
Constructor & Destructor Documentation
~CuCompressedMatrixBase()
virtual ~CuCompressedMatrixBase () inline virtual
Definition at line 54 of file cu-compressed-matrix.h.
 { }
Member Function Documentation
CopyFromMat()
virtual void CopyFromMat (const CuMatrixBase< BaseFloat > & mat) pure virtual
Sets *this to an appropriately compressed copy of 'mat', which includes resizing *this.
The details of how this is done will be different in different child classes.
Implemented in CuCompressedMatrix< I >.
Referenced by kaldi::CuCompressedMatrixTestNonnegative(), kaldi::CuCompressedMatrixTestSign(), and kaldi::CuCompressedMatrixTestSymmetric().
CopyToMat()
virtual void CopyToMat (CuMatrixBase< BaseFloat > * mat) const pure virtual
Copies the contents of *this to 'mat', which should be correctly sized beforehand.
Implemented in CuCompressedMatrix< I >.
Referenced by kaldi::CuCompressedMatrixTestNonnegative(), kaldi::CuCompressedMatrixTestSign(), kaldi::CuCompressedMatrixTestSymmetric(), and NnetComputer::ExecuteCommand().
NumCols()
virtual int32 NumCols () const pure virtual
Implemented in CuCompressedMatrix< I >.
Referenced by NnetComputer::ExecuteCommand().
NumRows()
virtual int32 NumRows () const pure virtual
Implemented in CuCompressedMatrix< I >.
Referenced by NnetComputer::ExecuteCommand().
The documentation for this class was generated from the following file:
cudamatrix/cu-compressed-matrix.h