Kaldi: ConvertCex Class Reference
ConvertCex Class Reference
#include <convert-tree-pdf-hts.h>
Public Member Functions
ConvertCex ()
void Init (const std::string &name, const std::string &prvdelim, const std::string &pstdelim, bool isinteger)
int32 AddVal (const std::string &val)
const std::string & LookupVal (int32 index) const
void SetVal (int32 index, const std::string &val)
const std::string & GetName () const
bool GetIsinteger () const
const std::string & GetPrvdelim () const
const std::string & GetPstdelim () const
Private Attributes
std::string name_
Context name.
bool isinteger_
Whether a string or integer feature.
std::string prvdelim_
HTS delimeter string before context.
std::string pstdelim_
HTS delimeter string after context.
StringVector vals_
integer to value lookup if required
std::string empty
empty string
Detailed Description
Definition at line 99 of file convert-tree-pdf-hts.h.
Constructor & Destructor Documentation
ConvertCex()
ConvertCex () inline explicit
Definition at line 101 of file convert-tree-pdf-hts.h.
 {}
Member Function Documentation
AddVal()
int32 AddVal (const std::string & val) inline
Definition at line 113 of file convert-tree-pdf-hts.h.
Referenced by kaldi::_read_context_setup().
{
     vals_.push_back(val);
     return vals_.size();
   }
GetIsinteger()
bool GetIsinteger () const inline
Definition at line 128 of file convert-tree-pdf-hts.h.
Referenced by kaldi::_convert_tree().
 {return isinteger_;}
GetName()
const std::string& GetName () const inline
Definition at line 127 of file convert-tree-pdf-hts.h.
Referenced by kaldi::_convert_tree().
 {return name_;}
GetPrvdelim()
const std::string& GetPrvdelim () const inline
Definition at line 129 of file convert-tree-pdf-hts.h.
Referenced by kaldi::_convert_tree().
 {return prvdelim_;}
GetPstdelim()
const std::string& GetPstdelim () const inline
Definition at line 130 of file convert-tree-pdf-hts.h.
Referenced by kaldi::_convert_tree().
 {return pstdelim_;}
Init()
void Init (const std::string & name, const std::string & prvdelim, const std::string & pstdelim, bool isinteger) inline
Definition at line 102 of file convert-tree-pdf-hts.h.
Referenced by kaldi::_read_context_setup().
{
     name_ = name;
     prvdelim_ = prvdelim;
     pstdelim_ = pstdelim;
     isinteger_ = isinteger;
     vals_.clear();
     //std::cout << vals_.size() << "\n";
   }
LookupVal()
const std::string& LookupVal (int32 index) const inline
Definition at line 117 of file convert-tree-pdf-hts.h.
Referenced by kaldi::_convert_tree().
{
     if (index < 0 || index >= vals_.size()) return empty;
     return vals_.at(index);
   }
SetVal()
void SetVal (int32 index, const std::string & val) inline
Definition at line 121 of file convert-tree-pdf-hts.h.
Referenced by kaldi::_read_context_setup().
{
     if (index < 0) index = 0;
     if (index >= vals_.size()) vals_.resize(index + 1);
     //std::cout << vals_.size() << " " << index << " " << val << "\n";
     vals_.at(index) = val;
   }
Member Data Documentation
empty
std::string empty private
empty string
Definition at line 144 of file convert-tree-pdf-hts.h.
isinteger_
bool isinteger_ private
Whether a string or integer feature.
Definition at line 136 of file convert-tree-pdf-hts.h.
name_
std::string name_ private
Context name.
Definition at line 134 of file convert-tree-pdf-hts.h.
prvdelim_
std::string prvdelim_ private
HTS delimeter string before context.
Definition at line 138 of file convert-tree-pdf-hts.h.
pstdelim_
std::string pstdelim_ private
HTS delimeter string after context.
Definition at line 140 of file convert-tree-pdf-hts.h.
vals_
StringVector vals_ private
integer to value lookup if required
Definition at line 142 of file convert-tree-pdf-hts.h.
The documentation for this class was generated from the following file:
idlaktxpbin/convert-tree-pdf-hts.h