Kaldi: TxpModule Class Reference
TxpModule Class Reference
Base class for all modules.
#include <txpmodule.h>
Public Member Functions
TxpModule (const std::string &name)
Construct module, also loads tpdb modules in specific instances.
virtual ~TxpModule ()
virtual bool Init (const TxpParseOptions &opts)
Load voice data.
virtual bool Process (pugi::xml_document *input)
Process the XML, modifying the XML to reflect linguistic information.
const std::string GetConfigValue (const std::string &key)
Return a configuration value for this module as a string (rendundant)
const char * GetOptValue (const char *key)
Return an option value for this module as a string.
bool GetConfigValueBool (const std::string &key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
bool GetOptValueBool (const char *key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
const std::string & GetName () const
Get the name of the module.
pugi::xml_node GetHeader (pugi::xml_document *input)
Gets or adds a module header to txpheader.
Protected Attributes
const TxpParseOptions * opts_
Options structure for the module.
std::string tpdb_
Directory for text processing database (tpdb) files used by txpxmldata objectys in the module.
Private Attributes
std::string name_
Name of the module.
Detailed Description
Base class for all modules.
Takes puji XML input and modifies it for puji XML output Has a configuration section which can be accessed using utility functions
Definition at line 40 of file txpmodule.h.
Constructor & Destructor Documentation
TxpModule()
TxpModule (const std::string & name) inline explicit
Construct module, also loads tpdb modules in specific instances.
Definition at line 43 of file txpmodule.h.
 : opts_(NULL), name_(name) {}
~TxpModule()
virtual ~TxpModule () inline virtual
Definition at line 44 of file txpmodule.h.
 {}
Member Function Documentation
GetConfigValue()
const std::string GetConfigValue (const std::string & key)
Return a configuration value for this module as a string (rendundant)
Referenced by TxpModule::Process().
GetConfigValueBool()
bool GetConfigValueBool (const std::string & key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
Referenced by TxpModule::Process().
GetHeader()
pugi::xml_node GetHeader (pugi::xml_document * input)
Gets or adds a module header to txpheader.
Definition at line 35 of file txpmodule.cc.
References TxpModule::name_.
Referenced by TxpModule::GetName(), and TxpCex::Process().
{
   // check we have a txpheader node for definition information
   pugi::xml_node txpheader =
       input->document_element().child("txpheader");
   if (!txpheader) txpheader =
                       input->document_element().prepend_child("txpheader");
   // remove a module entry if it is already present
   txpheader.remove_child(name_.c_str());
   return txpheader.append_child(name_.c_str());
 }
GetName()
const std::string& GetName () const inline
Get the name of the module.
Definition at line 61 of file txpmodule.h.
References TxpModule::GetHeader(), and TxpModule::name_.
Referenced by TxpTokenise::Init(), and testModule().
 {return name_;}
GetOptValue()
const char * GetOptValue (const char * key)
Return an option value for this module as a string.
Definition at line 23 of file txpmodule.cc.
References TxpParseOptions::GetValue(), TxpModule::name_, and TxpModule::opts_.
Referenced by TxpCex::Init(), TxpPosTag::Init(), TxpTokenise::Init(), TxpSyllabify::Init(), TxpPauses::Init(), TxpPronounce::Init(), and TxpModule::Process().
{
   return opts_->GetValue(name_.c_str(), key);
 }
GetOptValueBool()
bool GetOptValueBool (const char * key)
Return a boolean configuration True/true/TRUE -> true, False, false, FALSE, anything else -> false.
Definition at line 28 of file txpmodule.cc.
References TxpParseOptions::GetValue(), TxpModule::name_, and TxpModule::opts_.
Referenced by TxpPauses::Init(), and TxpModule::Process().
{
   const std::string val = opts_->GetValue(name_.c_str(), key);
   if ((val == "True") || (val == "true") || (val == "TRUE"))
     return true;
   return false;
 }
Init()
virtual bool Init (const TxpParseOptions & opts) inline virtual
Load voice data.
Reimplemented in TxpPronounce, TxpPauses, TxpSyllabify, TxpPhrasing, TxpTokenise, TxpCex, and TxpPosTag.
Definition at line 46 of file txpmodule.h.
 {return true;}
Process()
virtual bool Process (pugi::xml_document * input) inline virtual
Process the XML, modifying the XML to reflect linguistic information.
Reimplemented in TxpPronounce, TxpPauses, TxpSyllabify, TxpPhrasing, TxpTokenise, TxpCex, and TxpPosTag.
Definition at line 49 of file txpmodule.h.
References TxpModule::GetConfigValue(), TxpModule::GetConfigValueBool(), TxpModule::GetOptValue(), and TxpModule::GetOptValueBool().
Referenced by testModule().
 {return true;}
Member Data Documentation
name_
std::string name_ private
Name of the module.
Definition at line 74 of file txpmodule.h.
Referenced by TxpModule::GetHeader(), TxpModule::GetName(), TxpModule::GetOptValue(), and TxpModule::GetOptValueBool().
opts_
const TxpParseOptions* opts_ protected
Options structure for the module.
Definition at line 67 of file txpmodule.h.
Referenced by TxpModule::GetOptValue(), TxpModule::GetOptValueBool(), TxpPosTag::Init(), TxpCex::Init(), TxpTokenise::Init(), TxpPhrasing::Init(), TxpPauses::Init(), TxpSyllabify::Init(), and TxpPronounce::Init().
tpdb_
std::string tpdb_ protected
Directory for text processing database (tpdb) files used by txpxmldata objectys in the module.
Definition at line 70 of file txpmodule.h.
Referenced by TxpCex::Init(), TxpPosTag::Init(), TxpTokenise::Init(), TxpPhrasing::Init(), TxpPauses::Init(), TxpSyllabify::Init(), and TxpPronounce::Init().
The documentation for this class was generated from the following files:
idlaktxp/txpmodule.h
idlaktxp/txpmodule.cc