Kaldi: ConstantEventMap Class Reference
ConstantEventMap Class Reference
#include <event-map.h>
Public Member Functions
virtual bool Map (const EventType &event, EventAnswerType *ans) const
virtual void MultiMap (const EventType &, std::vector< EventAnswerType > *ans) const
virtual void GetChildren (std::vector< EventMap *> *out) const
virtual EventMap * Copy (const std::vector< EventMap *> &new_leaves) const
virtual EventMap * MapValues (const unordered_set< EventKeyType > &keys_to_map, const unordered_map< EventValueType, EventValueType > &value_map) const
virtual EventMap * Prune () const
ConstantEventMap (EventAnswerType answer)
virtual void Write (std::ostream &os, bool binary)
Write to stream.
Public Member Functions inherited from EventMap
EventMap * Copy () const
virtual EventAnswerType MaxResult () const
virtual ~EventMap ()
Static Public Member Functions
static ConstantEventMap * Read (std::istream &is, bool binary)
Static Public Member Functions inherited from EventMap
static void Check (const EventType &event)
static bool Lookup (const EventType &event, EventKeyType key, EventValueType *ans)
static void Write (std::ostream &os, bool binary, EventMap *emap)
a Write function that takes care of NULL pointers.
static EventMap * Read (std::istream &is, bool binary)
a Read function that reads an arbitrary EventMap; also works for NULL pointers.
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (ConstantEventMap)
Private Attributes
EventAnswerType answer_
Detailed Description
Definition at line 166 of file event-map.h.
Constructor & Destructor Documentation
ConstantEventMap()
ConstantEventMap (EventAnswerType answer) inline explicit
Definition at line 197 of file event-map.h.
 : answer_(answer) { }
Member Function Documentation
Copy()
virtual EventMap* Copy (const std::vector< EventMap *> & new_leaves) const inline virtual
Implements EventMap.
Definition at line 180 of file event-map.h.
References ConstantEventMap::Copy().
Referenced by ConstantEventMap::Copy().
{
     if (answer_ < 0 || answer_ >= (EventAnswerType)new_leaves.size() ||
         new_leaves[answer_] == NULL)
       return new ConstantEventMap(answer_);
     else return new_leaves[answer_]->Copy();
   }
GetChildren()
virtual void GetChildren (std::vector< EventMap *> * out) const inline virtual
Implements EventMap.
Definition at line 178 of file event-map.h.
 { out->clear(); }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (ConstantEventMap) private
Map()
virtual bool Map (const EventType & event, EventAnswerType * ans) const inline virtual
Implements EventMap.
Definition at line 168 of file event-map.h.
{
     *ans = answer_;
     return true;
   }
MapValues()
virtual EventMap* MapValues (const unordered_set< EventKeyType > & keys_to_map, const unordered_map< EventValueType, EventValueType > & value_map) const inline virtual
Implements EventMap.
Definition at line 187 of file event-map.h.
{
     return new ConstantEventMap(answer_);
   }
MultiMap()
virtual void MultiMap (const EventType & , std::vector< EventAnswerType > * ans) const inline virtual
Implements EventMap.
Definition at line 173 of file event-map.h.
{
      ans->push_back(answer_);
   }
Prune()
virtual EventMap* Prune () const inline virtual
Implements EventMap.
Definition at line 193 of file event-map.h.
{
     return (answer_ == -1 ? NULL : new ConstantEventMap(answer_));
   }
Read()
ConstantEventMap * Read (std::istream & is, bool binary) static
Definition at line 64 of file event-map.cc.
References kaldi::ExpectToken(), and kaldi::ReadBasicType().
Referenced by EventMap::Read().
{
   ExpectToken(is, binary, "CE");
   EventAnswerType answer;
   ReadBasicType(is, binary, &answer);
   return new ConstantEventMap(answer);
 }
Write()
void Write (std::ostream & os, bool binary) virtual
Write to stream.
Implements EventMap.
Definition at line 55 of file event-map.cc.
References KALDI_ERR, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "CE");
   WriteBasicType(os, binary, answer_);
   if (os.fail()) {
     KALDI_ERR << "ConstantEventMap::Write(), could not write to stream.";
   }
 }
Member Data Documentation
answer_
EventAnswerType answer_ private
Definition at line 202 of file event-map.h.
The documentation for this class was generated from the following files:
tree/event-map.h
tree/event-map.cc