Kaldi: tree/cluster-utils-test.cc File Reference
cluster-utils-test.cc File Reference
#include "tree/cluster-utils.h"
#include "tree/clusterable-classes.h"
#include "util/stl-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
static void TestClusterUtils ()
static void TestClusterUtilsVector ()
static void TestObjfPlus ()
static void TestObjfMinus ()
static void TestDistance ()
static void TestSumObjfAndSumNormalizer ()
static void TestSum ()
static void TestEnsureClusterableVectorNotNull ()
static void TestAddToClusters ()
static void TestAddToClustersOptimized ()
static void TestClusterBottomUp ()
static void TestRefineClusters ()
static void TestClusterKMeans ()
static void TestClusterKMeansVector ()
static void TestTreeCluster ()
static void TestClusterTopDown ()
int main ()
Function Documentation
main()
int main ()
Definition at line 554 of file cluster-utils-test.cc.
References rnnlm::i, kaldi::TestAddToClusters(), kaldi::TestAddToClustersOptimized(), kaldi::TestClusterBottomUp(), kaldi::TestClusterKMeans(), kaldi::TestClusterKMeansVector(), kaldi::TestClusterTopDown(), kaldi::TestClusterUtils(), kaldi::TestClusterUtilsVector(), kaldi::TestDistance(), kaldi::TestEnsureClusterableVectorNotNull(), kaldi::TestObjfMinus(), kaldi::TestObjfPlus(), kaldi::TestRefineClusters(), kaldi::TestSum(), kaldi::TestSumObjfAndSumNormalizer(), and kaldi::TestTreeCluster().
            {
   using namespace kaldi;
   for (size_t i = 0; i < 2; i++) {
     TestClusterUtils();
     TestClusterUtilsVector();
   }
   TestAddToClustersOptimized();
   TestObjfPlus();
   TestObjfMinus();
   TestDistance();
   TestSumObjfAndSumNormalizer();
   TestSum();
   TestEnsureClusterableVectorNotNull();
   TestAddToClusters();
   TestClusterTopDown();
   TestTreeCluster();
   TestClusterKMeans();
   TestClusterKMeansVector();
   TestClusterBottomUp();
   TestRefineClusters();
 }