Kaldi: ivectorbin/compute-eer.cc File Reference
compute-eer.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
BaseFloat ComputeEer (std::vector< BaseFloat > *target_scores, std::vector< BaseFloat > *nontarget_scores, BaseFloat *threshold)
ComputeEer computes the Equal Error Rate (EER) for the given scores and returns it as a proportion beween 0 and 1.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 77 of file compute-eer.cc.
References kaldi::ComputeEer(), kaldi::ConvertStringToReal(), ParseOptions::GetArg(), KALDI_ERR, KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::SplitStringToVector(), and Input::Stream().
{
   using namespace kaldi;
   typedef kaldi::int32 int32;
   try {
     const char *usage =
         "Computes Equal Error Rate\n"
         "Input is a series of lines, each with two fields.\n"
         "The first field must be a numeric score, and the second\n"
         "either the string 'target' or 'nontarget'. \n"
         "The EER will be printed to the standard output.\n"
         "\n"
         "Usage: compute-eer <scores-in>\n"
         "e.g.: compute-eer -\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 1) {
       po.PrintUsage();
       exit(1);
     }
     std::string scores_rxfilename = po.GetArg(1);
     std::vector<BaseFloat> target_scores, nontarget_scores;
     Input ki(scores_rxfilename);
     std::string line;
     while (std::getline(ki.Stream(), line)) {
       std::vector<std::string> split_line;
       SplitStringToVector(line, " \t", true, &split_line);
       BaseFloat score;
       if (split_line.size() != 2) {
         KALDI_ERR << "Invalid input line (must have two fields): "
                   << line;
       }
       if (!ConvertStringToReal(split_line[0], &score)) {
         KALDI_ERR << "Invalid input line (first field must be float): "
                   << line;
       }
       if (split_line[1] == "target")
         target_scores.push_back(score);
       else if (split_line[1] == "nontarget")
         nontarget_scores.push_back(score);
       else {
         KALDI_ERR << "Invalid input line (second field must be "
                   << "'target' or 'nontarget')";
       }
     }
     if (target_scores.empty() && nontarget_scores.empty())
       KALDI_ERR << "Empty input.";
     if (target_scores.empty())
       KALDI_ERR << "No target scores seen.";
     if (nontarget_scores.empty())
       KALDI_ERR << "No non-target scores seen.";
     BaseFloat threshold;
     BaseFloat eer = ComputeEer(&target_scores, &nontarget_scores, &threshold);
     KALDI_LOG << "Equal error rate is " << (100.0 * eer)
               << "%, at threshold " << threshold;
     std::cout.precision(4);
     std::cout << (100.0 * eer);
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }