Kaldi: bin/compile-questions.cc File Reference
compile-questions.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/hmm-topology.h"
#include "tree/build-tree-questions.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
int32 ProcessTopo (const HmmTopology &topo, const std::vector< std::vector< int32 > > &questions)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 57 of file compile-questions.cc.
References ParseOptions::GetArg(), rnnlm::i, QuestionsForKey::initial_questions, kaldi::IsSortedAndUniq(), rnnlm::j, KALDI_ERR, KALDI_LOG, KALDI_WARN, kaldi::kPdfClass, rnnlm::n, ParseOptions::NumArgs(), kaldi::PrintableRxfilename(), ParseOptions::PrintUsage(), kaldi::ProcessTopo(), ParseOptions::Read(), kaldi::ReadIntegerVectorVectorSimple(), kaldi::ReadKaldiObject(), ParseOptions::Register(), Questions::SetQuestionsOf(), kaldi::SortAndUniq(), and kaldi::WriteKaldiObject().
{
   using namespace kaldi;
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Compile questions\n"
         "Usage:  compile-questions [options] <topo> <questions-text-file> <questions-out>\n"
         "e.g.: \n"
         " compile-questions questions.txt questions.qst\n";
     bool binary = true;
     int32 P = 1, N = 3;
     int32 num_iters_refine = 0;
     ParseOptions po(usage);
     po.Register("binary", &binary,
                 "Write output in binary mode");
     po.Register("context-width", &N,
                 "Context window size [must match acc-tree-stats].");
     po.Register("central-position", &P,
                 "Central position in phone context window [must match acc-tree-stats]");
     po.Register("num-iters-refine", &num_iters_refine,
                 "Number of iters of refining questions at each node.  >0 --> questions "
                 "not refined");
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string
         topo_filename = po.GetArg(1),
         questions_rxfilename = po.GetArg(2),
         questions_out_filename = po.GetArg(3);
     HmmTopology topo;  // just needed for checking, and to get the
     // largest number of pdf-classes for any phone.
     ReadKaldiObject(topo_filename, &topo);
     std::vector<std::vector<int32> > questions;  // sets of phones.
     if (!ReadIntegerVectorVectorSimple(questions_rxfilename, &questions))
       KALDI_ERR << "Could not read questions from "
                  << PrintableRxfilename(questions_rxfilename);
     for (size_t i = 0; i < questions.size(); i++) {
       std::sort(questions[i].begin(), questions[i].end());
       if (!IsSortedAndUniq(questions[i]))
         KALDI_ERR << "Questions contain duplicate phones";
     }
     size_t nq = static_cast<int32>(questions.size());
     SortAndUniq(&questions);
     if (questions.size() != nq)
       KALDI_WARN << (nq-questions.size())
                  << " duplicate questions present in " << questions_rxfilename;
     // ProcessTopo checks that all phones in the topo are
     // represented in at least one questions (else warns), and
     // returns the max # pdf classes in any given phone (normally
     // 3).
     int32 max_num_pdfclasses = ProcessTopo(topo, questions);
     Questions qo;
     QuestionsForKey phone_opts(num_iters_refine);
     // the questions-options corresponding to keys 0, 1, .. N-1 which
     // represent the phonetic context positions (including the central phone).
     for (int32 n = 0; n < N; n++) {
       KALDI_LOG << "Setting questions for phonetic-context position "<< n;
       phone_opts.initial_questions = questions;
       qo.SetQuestionsOf(n, phone_opts);
     }
     QuestionsForKey pdfclass_opts(num_iters_refine);
     std::vector<std::vector<int32> > pdfclass_questions(max_num_pdfclasses-1);
     for (int32 i = 0; i < max_num_pdfclasses - 1; i++)
       for (int32 j = 0; j <= i; j++)
         pdfclass_questions[i].push_back(j);
     // E.g. if max_num_pdfclasses == 3,  pdfclass_questions is now [ [0], [0, 1] ].
     pdfclass_opts.initial_questions = pdfclass_questions;
     KALDI_LOG << "Setting questions for hmm-position [hmm-position ranges from 0 to "<< (max_num_pdfclasses-1) <<"]";
     qo.SetQuestionsOf(kPdfClass, pdfclass_opts);
     WriteKaldiObject(qo, questions_out_filename, binary);
     KALDI_LOG << "Wrote questions to "<<questions_out_filename;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }