Kaldi: featbin/concat-feats.cc File Reference
concat-feats.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-matrix.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void ConcatFeats (const std::vector< Matrix< BaseFloat > > &in, Matrix< BaseFloat > *out)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 57 of file concat-feats.cc.
References kaldi::ConcatFeats(), ParseOptions::GetArg(), rnnlm::i, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     using namespace std;
     const char *usage =
         "Concatenate feature files (assuming they have the same dimensions),\n"
         "so the output file has the sum of the num-frames of the inputs.\n"
         "Usage: concat-feats <in-rxfilename1> <in-rxfilename2> [<in-rxfilename3> ...] <out-wxfilename>\n"
         " e.g. concat-feats mfcc/foo.ark:12343 mfcc/foo.ark:56789 -\n"
         "See also: copy-feats, append-vector-to-feats, paste-feats\n";
     ParseOptions po(usage);
     bool binary = true;
     po.Register("binary", &binary, "If true, output files in binary "
                 "(only relevant for single-file operation, i.e. no tables)");
     po.Read(argc, argv);
     if (po.NumArgs() < 3) {
       po.PrintUsage();
       exit(1);
     }
     std::vector<Matrix<BaseFloat> > feats(po.NumArgs() - 1);
     for (int32 i = 1; i < po.NumArgs(); i++)
       ReadKaldiObject(po.GetArg(i), &(feats[i-1]));
     Matrix<BaseFloat> output;
     ConcatFeats(feats, &output);
     std::string output_wxfilename = po.GetArg(po.NumArgs());
     WriteKaldiObject(output, output_wxfilename, binary);
     // This will tend to produce too much output if we have a logging mesage.
     // KALDI_LOG << "Wrote concatenated features to " << output_wxfilename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }