Kaldi: idlaktxpbin/convert-tree-pdf-hts.cc File Reference
convert-tree-pdf-hts.cc File Reference
#include "idlaktxpbin/convert-tree-pdf-hts.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void _convert_tree (const std::string &tab, const EventMap *emap, bool yes, const ConvertCexVector &cvncex_array, TreeNodeVector *treenode_array, LookupInt *contextname2index, int32 state, TreeNode *parent)
void _read_context_setup (std::string kaldicontextsetup_filename, int32 N, const fst::SymbolTable &phones_symtab, ConvertCexVector *cvncex_array)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 38 of file convert-tree-pdf-hts.cc.
References kaldi::_convert_tree(), kaldi::_read_context_setup(), DiagGmm::Dim(), ParseOptions::GetArg(), DiagGmm::GetMeans(), AmDiagGmm::GetPdf(), DiagGmm::GetVars(), rnnlm::i, rnnlm::j, KALDI_ERR, ParseOptions::NumArgs(), DiagGmm::NumGauss(), AmDiagGmm::NumPdfs(), ParseOptions::PrintUsage(), AmDiagGmm::Read(), ParseOptions::Read(), TransitionModel::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), Output::Stream(), Input::Stream(), ContextDependency::ToPdfMap(), and DiagGmm::weights().
{
   using namespace kaldi;
   ConvertCexVector cvncex_array;
   // lookup to ensure question names generated for hts are unique
   LookupInt contextname2index;
   kaldi::int32 N = 5;
   kaldi::int32 num_states = 5;
   bool pitchdata = false;
   kaldi::int32 stateno;
   kaldi::int32 nodeno;
   kaldi::int32 leafno = 0;
   kaldi::int32 totleaves = 0;
   kaldi::int32 totmodels = 0;
   const char *usage =
       "Convert kaldi tree and gmm based model to an HTS format\n"
       "Usage: convert-tree-pdf-hts [options] kaldiphoneset kaldicontextsetup tree model htstreeout htsmodelout\n";
   // input output variables
   std::string tree_in_filename;
   std::string model_in_filename;
   std::string tree_out_filename;
   std::string model_out_filename;
   std::string phones_symtab_filename;
   std::string kaldicontextsetup_filename;
   std::string kaldiqset_filename;
   std::string htsqset_filename;
   std::string tab;
   ContextDependency ctx_dep;
   TransitionModel trans_model;
   AmDiagGmm am_gmm;
   const DiagGmm * pdf;
   StringVector kaldivals;
   kaldi::int32 i, j;
   kaldi::Vector<BaseFloat> weights;
   kaldi::Matrix<BaseFloat> means;
   kaldi::Matrix<BaseFloat> vars;
   try {
     kaldi::ParseOptions po(usage);
     po.Register("context-width", &N, "Context window size");
     po.Register("number-states", &num_states, "Number of states in hmm topology");
     // add option to produce 'streamed lf0'
     po.Register("pitch", &pitchdata, "Indicates this is pitch data: The first parameter is interpreted as probability of voicing and output as a stream weight for HTS. ");
     // how do we write to two files in kaldi? Can't stream what so waht is the etiquette?
     po.Read(argc, argv);
     if (po.NumArgs() != 6) {
       po.PrintUsage();
       exit(1);
     }
     phones_symtab_filename = po.GetArg(1);
     kaldicontextsetup_filename = po.GetArg(2);
     tree_in_filename = po.GetArg(3);
     model_in_filename = po.GetArg(4);
     tree_out_filename = po.GetArg(5);
     model_out_filename = po.GetArg(6);
     kaldi::Output treeout(tree_out_filename, false); // not binary
     std::filebuf fb;
     // Can't use kaldi to open the stream because it adds a header code when its in binary
     fb.open(model_out_filename.c_str(),std::ios::out);
     std::ostream os(&fb);
     //kaldi::Output modelout(model_out_filename, true); // binary
     // read the kaldi phone to integer mapping
     fst::SymbolTable *phones_symtab = NULL;
     {
       std::ifstream is(phones_symtab_filename.c_str());
       phones_symtab = fst::SymbolTable::ReadText(is, phones_symtab_filename);
       if (!phones_symtab || phones_symtab->NumSymbols() == 0)
         KALDI_ERR << "Error opening symbol table file "<<phones_symtab_filename;
     }
     _read_context_setup(kaldicontextsetup_filename, N,
                         *phones_symtab,
                         &cvncex_array);
     ReadKaldiObject(tree_in_filename, &ctx_dep);
     bool binary_read;
     Input ki(model_in_filename, &binary_read);
     trans_model.Read(ki.Stream(), binary_read);
     am_gmm.Read(ki.Stream(), binary_read);
     for (i = 0; i < am_gmm.NumPdfs(); i++) {
       pdf = &am_gmm.GetPdf(i);
       // only one guassian allowed
       if (pdf->NumGauss() != 1) {
         KALDI_ERR << "Model as more than 1 Guassian (" << pdf->NumGauss() << ")";
       }
       weights = pdf->weights();
       // output weights
       //std::cout << weights(0) << " ";
       pdf->GetMeans(&means);
       pdf->GetVars(&vars);
       // output means
       //std::cout << "MEANS: ";
       for (j = 0; j < pdf->Dim(); j++) {
         //std::cout << means(0, j) << " ";
         //if (j < pdf->Dim() - 1) std::cout << " ";
         //else std::cout << "\n";
       }
       // output variances
       //std::cout << "VARS: ";
       for (j = 0; j < pdf->Dim(); j++) {
         //std::cout << vars(0, j);
         //if (j < pdf->Dim() - 1) std::cout << " ";
         //else std::cout << "\n";
       }
     }
     // Input htsqset;
     // htsqset.OpenTextMode(htsqset_filename);
     // Input kaldiqset;
     // kaldiqset.OpenTextMode(kaldiqset_filename);
     // _readqsets(kaldiqset.Stream(), htsqset.Stream(), &kaldi2htsqset);
     std::vector<TreeNodeVector> treenode_array_array;
     for (kaldi::int32 s = 0; s < num_states; s++) {
       // write zeros to fill in later for number of leafs per state
       os.write((const char *)(&leafno), sizeof(leafno));
       TreeNodeVector treenode_array;
       _convert_tree(tab, &ctx_dep.ToPdfMap(), false, cvncex_array, &treenode_array,
                    &contextname2index, s, NULL);
       //output questions
       for(TreeNodeVector::iterator iter = treenode_array.begin();
           iter != treenode_array.end();
           iter++) {
         treeout.Stream() << "QS " << (*iter)->GetHtsQuestion() << "\n";
       }
       treenode_array_array.push_back(treenode_array);
     }
     treeout.Stream() << "\n";
     stateno = 2;
     for (std::vector<TreeNodeVector>::iterator iterv = treenode_array_array.begin();
          iterv != treenode_array_array.end();
          stateno++, iterv++) {
       treeout.Stream() << "{*}[" << stateno << "]\n{\n";
       nodeno = 0;
       leafno = 1;
       totleaves = 0;
       for(TreeNodeVector::iterator iter = iterv->begin();
           iter != iterv->end();
           nodeno++, iter++) {
         //output tree
         if (nodeno) treeout.Stream() << "-";
         treeout.Stream() << nodeno << " " << (*iter)->GetHtsName() << " ";
         //no value
         if ((*iter)->IsTerminalNo()) {
           treeout.Stream() << "lf0_s" << stateno << "_" << leafno << " ";
           //output the pdf
           pdf = &am_gmm.GetPdf((*iter)->GetNo());
           pdf->GetMeans(&means);
           pdf->GetVars(&vars);
           if (pitchdata) j = 1;
           else j = 0;
           for (; j < pdf->Dim(); j++) {
             float m = means(0, j);
             os.write((const char *)&m, sizeof(m));
             //if (leafno > 205 && leafno < 227)
             //  cout << leafno << "MEAN " << m << "\n";
           }
           if (pitchdata) j = 1;
           else j = 0;
           for (; j < pdf->Dim(); j++) {
             float v = vars(0, j);
             os.write((const char *)&v, sizeof(v));
             //if (leafno > 205 && leafno < 227)
             //  cout << leafno << "VAR " << v << "\n";
           }
           if (pitchdata) {
             float w = means(0, 0);
             os.write((const char *)&w, sizeof(w));
             //if (leafno > 205 && leafno < 227)
             //  cout << leafno << "WEIGHT " << w << "\n";
           }
           totmodels++;
           totleaves++;
           leafno++;
         }
         else {
           treeout.Stream() << "-" << (*iter)->GetNo() << " ";
         }
         //yes value
         if ((*iter)->IsTerminalYes()) {
           treeout.Stream() << "lf0_s" << stateno << "_" << leafno << "\n";
           //output the pdf
           pdf = &am_gmm.GetPdf((*iter)->GetYes());
           pdf->GetMeans(&means);
           pdf->GetVars(&vars);
           if (pitchdata) j = 1;
           else j = 0;
           for (; j < pdf->Dim(); j++) {
             float m = means(0, j);
             os.write((const char *)&m, sizeof(m));
             //if (leafno > 205 && leafno < 227)
             //  cout << leafno << "MEAN " << m << "\n";
           }
           if (pitchdata) j = 1;
           else j = 0;
           for (; j < pdf->Dim(); j++) {
             float v = vars(0, j);
             os.write((const char *)&v, sizeof(v));
             //if (leafno > 205 && leafno < 227)
             //  cout << leafno << "VAR " << v << "\n";
           }
           if (pitchdata) {
             float w = means(0, 0);
             os.write((const char *)&w, sizeof(w));
             //if (leafno > 205 && leafno < 227)
             //  cout << leafno << "WEIGHT " << w << "\n";
           }
           totmodels++;
           totleaves++;
           leafno++;
         }
         else {
           treeout.Stream() << "-" << (*iter)->GetYes() << "\n";
         }
       }
       treeout.Stream() << "}\n\n";
       std::cout << stateno << " " << leafno << "\n";
       os.flush();
       os.seekp((stateno - 2) * 4, std::ios_base::beg);
       os.write((const char *)(&totleaves), sizeof(leafno));
       os.seekp(0, std::ios_base::end);
     }
     fb.close();
     std::cout << "TOT:" << totmodels << "\n";
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }