Kaldi: cudamatrix/cu-compressed-matrix-test.cc File Reference
cu-compressed-matrix-test.cc File Reference
#include <iostream>
#include <vector>
#include <cstdlib>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "cudamatrix/cu-matrix-lib.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void CuCompressedMatrixTestSign ()
void CuCompressedMatrixTestNonnegative ()
void CuCompressedMatrixTestSymmetric ()
int main ()
Function Documentation
main()
int main ()
Definition at line 165 of file cu-compressed-matrix-test.cc.
References kaldi::CuCompressedMatrixTestNonnegative(), kaldi::CuCompressedMatrixTestSign(), kaldi::CuCompressedMatrixTestSymmetric(), rnnlm::i, and kaldi::SetVerboseLevel().
            {
   SetVerboseLevel(1);
   // we don't run this test if CUDA is not compiled in, since
   // you can't instantiate class CuCompressedMatrix in that case.
 #if HAVE_CUDA == 1
   CuDevice::Instantiate().SelectGpuId("yes");
   for (int32 i = 1; i < 10; i++) {
     CuCompressedMatrixTestSign();
     CuCompressedMatrixTestNonnegative();
     CuCompressedMatrixTestSymmetric();
   }
 #endif
   return 0;
 }