Kaldi: cudamatrix/cu-vector-test.cc File Reference
cu-vector-test.cc File Reference
#include <iostream>
#include <vector>
#include <cstdlib>
#include <cmath>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "cudamatrix/cu-matrix.h"
#include "cudamatrix/cu-vector.h"
#include "cudamatrix/cu-tp-matrix.h"
#include "cudamatrix/cu-sp-matrix.h"
#include "cudamatrix/cu-math.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
template<class Real >
static void UnitTestCuVectorIO ()
template<typename Real , typename OtherReal >
static void UnitTestCuVectorCopyFromVec ()
template<typename Real >
static void UnitTestCuSubVector ()
template<typename Real >
static void UnitTestCuVectorMulTp ()
template<typename Real >
static void UnitTestCuVectorAddTp ()
template<typename Real >
void CuVectorUnitTestVecVec ()
template<typename Real >
void CuVectorUnitTestAddVec ()
template<typename Real >
void CuVectorUnitTestAddVecCross ()
template<typename Real >
void CuVectorUnitTestAddVecExtra ()
template<typename Real >
void CuVectorUnitTestCopyElements ()
template<typename Real >
void UnitTestVecMatVec ()
template<typename Real >
void CuVectorUnitTestAddRowSumMat ()
template<typename Real >
void CuVectorUnitTestAddColSumMat ()
template<typename Real >
void CuVectorUnitTestApproxEqual ()
template<typename Real >
static void UnitTestCuVectorReplaceValue ()
template<typename Real >
static void UnitTestCuVectorSum ()
template<typename Real >
void CuVectorUnitTestInvertElements ()
template<typename Real >
void CuVectorUnitTestSum ()
template<typename Real >
void CuVectorUnitTestScale ()
template<typename Real >
void CuVectorUnitTestCopyFromMat ()
template<typename Real >
void CuVectorUnitTestCopyDiagFromPacked ()
template<typename Real >
void CuVectorUnitTestCopyCross ()
template<typename Real >
void CuVectorUnitTestCopyCross2 ()
template<typename Real >
void CuVectorUnitTestCopyDiagFromMat ()
template<typename Real >
void CuVectorUnitTestNorm ()
template<typename Real >
void CuVectorUnitTestMin ()
template<typename Real >
void CuVectorUnitTestMax ()
template<typename Real >
void CuVectorUnitTestApplySoftMax ()
template<typename Real >
void CuVectorUnitTestApplyExp ()
template<typename Real >
void CuVectorUnitTestApplyLog ()
template<typename Real >
void CuVectorUnitTestApplyFloor ()
template<typename Real >
void CuVectorUnitTestApplyFloorNoCount ()
template<typename Real >
void CuVectorUnitTestApplyCeiling ()
template<typename Real >
void CuVectorUnitTestApplyCeilingNoCount ()
template<typename Real >
void CuVectorUnitTestApplyPow ()
template<typename Real >
void CuVectorUnitTestAddVecVec ()
template<typename Real >
void CuVectorUnitTestAddDiagMat2 ()
template<typename Real >
static void CuVectorUnitTestAddDiagMatMat ()
template<typename Real >
void CuVectorUnitTestAddMatVec ()
template<typename Real >
void CuVectorUnitTestAddSpVec ()
template<typename Real >
void CuVectorUnitTest ()
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 831 of file cu-vector-test.cc.
References KALDI_LOG, KALDI_WARN, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), and kaldi::SetVerboseLevel().
{
   using namespace kaldi;
   SetVerboseLevel(1);
   const char *usage = "Usage: cu-vector-test [options]";
   ParseOptions po(usage);
   std::string use_gpu = "yes";
   po.Register("use-gpu", &use_gpu, "yes|no|optional");
   po.Read(argc, argv);
   if (po.NumArgs() != 0) {
     po.PrintUsage();
     exit(1);
   }
   int32 loop = 0;
 #if HAVE_CUDA == 1
   for (; loop < 2; loop++) {
     CuDevice::Instantiate().SetDebugStrideMode(true);
     if (loop == 0)
       CuDevice::Instantiate().SelectGpuId("no"); // -1 means no GPU
     else
       CuDevice::Instantiate().SelectGpuId(use_gpu);
 #endif
     kaldi::CuVectorUnitTest<float>();
 #if HAVE_CUDA == 1
     if (CuDevice::Instantiate().DoublePrecisionSupported()) {
       kaldi::CuVectorUnitTest<double>();
     } else {
       KALDI_WARN << "Double precision not supported";
     }
 #else
     kaldi::CuVectorUnitTest<double>();
 #endif
     if (loop == 0)
       KALDI_LOG << "Tests without GPU use succeeded.";
     else
       KALDI_LOG << "Tests with GPU use (if available) succeeded.";
 #if HAVE_CUDA == 1
   }
   CuDevice::Instantiate().PrintProfile();
 #endif
   return 0;
 }