Kaldi: bin/decode-faster-mapped.cc File Reference
decode-faster-mapped.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "tree/context-dep.h"
#include "hmm/transition-model.h"
#include "fstext/fstext-lib.h"
#include "decoder/faster-decoder.h"
#include "decoder/decodable-matrix.h"
#include "base/timer.h"
#include "lat/kaldi-lattice.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 32 of file decode-faster-mapped.cc.
References FasterDecoder::Decode(), SequentialTableReader< Holder >::Done(), Timer::Elapsed(), ParseOptions::GetArg(), FasterDecoder::GetBestPath(), fst::GetLinearSymbolSequence(), ParseOptions::GetOptArg(), rnnlm::i, TableWriter< Holder >::IsOpen(), KALDI_ERR, KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), FasterDecoder::ReachedFinal(), ParseOptions::Read(), fst::ReadFstKaldi(), kaldi::ReadKaldiObject(), FasterDecoderOptions::Register(), ParseOptions::Register(), SequentialTableReader< Holder >::Value(), LatticeWeightTpl< FloatType >::Value1(), LatticeWeightTpl< FloatType >::Value2(), words, and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     using fst::SymbolTable;
     using fst::VectorFst;
     using fst::StdArc;
     const char *usage =
         "Decode, reading log-likelihoods as matrices\n"
         " (model is needed only for the integer mappings in its transition-model)\n"
         "Usage:   decode-faster-mapped [options] <model-in> <fst-in> "
         "<loglikes-rspecifier> <words-wspecifier> [<alignments-wspecifier>]\n";
     ParseOptions po(usage);
     bool binary = true;
     BaseFloat acoustic_scale = 0.1;
     bool allow_partial = true;
     std::string word_syms_filename;
     FasterDecoderOptions decoder_opts;
     decoder_opts.Register(&po, true);  // true == include obscure settings.
     po.Register("binary", &binary, "Write output in binary mode");
     po.Register("acoustic-scale", &acoustic_scale, "Scaling factor for acoustic likelihoods");
     po.Register("allow-partial", &allow_partial, "Produce output even when final state was not reached");
     po.Register("word-symbol-table", &word_syms_filename, "Symbol table for words [for debug output]");
     po.Read(argc, argv);
     if (po.NumArgs() < 4 || po.NumArgs() > 5) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_in_filename = po.GetArg(1),
         fst_in_filename = po.GetArg(2),
         loglikes_rspecifier = po.GetArg(3),
         words_wspecifier = po.GetArg(4),
         alignment_wspecifier = po.GetOptArg(5);
     TransitionModel trans_model;
     ReadKaldiObject(model_in_filename, &trans_model);
     Int32VectorWriter words_writer(words_wspecifier);
     Int32VectorWriter alignment_writer(alignment_wspecifier);
     fst::SymbolTable *word_syms = NULL;
     if (word_syms_filename != "") {
       word_syms = fst::SymbolTable::ReadText(word_syms_filename);
       if (!word_syms)
         KALDI_ERR << "Could not read symbol table from file "<<word_syms_filename;
     }
     SequentialBaseFloatMatrixReader loglikes_reader(loglikes_rspecifier);
     // It's important that we initialize decode_fst after loglikes_reader, as it
     // can prevent crashes on systems installed without enough virtual memory.
     // It has to do with what happens on UNIX systems if you call fork() on a
     // large process: the page-table entries are duplicated, which requires a
     // lot of virtual memory.
     VectorFst<StdArc> *decode_fst = fst::ReadFstKaldi(fst_in_filename);
     BaseFloat tot_like = 0.0;
     kaldi::int64 frame_count = 0;
     int num_success = 0, num_fail = 0;
     FasterDecoder decoder(*decode_fst, decoder_opts);
     Timer timer;
     for (; !loglikes_reader.Done(); loglikes_reader.Next()) {
       std::string key = loglikes_reader.Key();
       const Matrix<BaseFloat> &loglikes (loglikes_reader.Value());
       if (loglikes.NumRows() == 0) {
         KALDI_WARN << "Zero-length utterance: " << key;
         num_fail++;
         continue;
       }
       DecodableMatrixScaledMapped decodable(trans_model, loglikes, acoustic_scale);
       decoder.Decode(&decodable);
       VectorFst<LatticeArc> decoded;  // linear FST.
       if ( (allow_partial || decoder.ReachedFinal())
            && decoder.GetBestPath(&decoded) ) {
         num_success++;
         if (!decoder.ReachedFinal())
           KALDI_WARN << "Decoder did not reach end-state, outputting partial traceback.";
         std::vector<int32> alignment;
         std::vector<int32> words;
         LatticeWeight weight;
         frame_count += loglikes.NumRows();
         GetLinearSymbolSequence(decoded, &alignment, &words, &weight);
         words_writer.Write(key, words);
         if (alignment_writer.IsOpen())
           alignment_writer.Write(key, alignment);
         if (word_syms != NULL) {
           std::cerr << key << ' ';
           for (size_t i = 0; i < words.size(); i++) {
             std::string s = word_syms->Find(words[i]);
             if (s == "")
               KALDI_ERR << "Word-id " << words[i] <<" not in symbol table.";
             std::cerr << s << ' ';
           }
           std::cerr << '\n';
         }
         BaseFloat like = -weight.Value1() -weight.Value2();
         tot_like += like;
         KALDI_LOG << "Log-like per frame for utterance " << key << " is "
                   << (like / loglikes.NumRows()) << " over "
                   << loglikes.NumRows() << " frames.";
       } else {
         num_fail++;
         KALDI_WARN << "Did not successfully decode utterance " << key
                    << ", len = " << loglikes.NumRows();
       }
     }
     double elapsed = timer.Elapsed();
     KALDI_LOG << "Time taken [excluding initialization] "<< elapsed
               << "s: real-time factor assuming 100 frames/sec is "
               << (elapsed*100.0/frame_count);
     KALDI_LOG << "Done " << num_success << " utterances, failed for "
               << num_fail;
     KALDI_LOG << "Overall log-likelihood per frame is " << (tot_like/frame_count)
               << " over " << frame_count << " frames.";
     delete word_syms;
     delete decode_fst;
     if (num_success != 0) return 0;
     else return 1;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }