var dir_a84b5eb70f2ccdbb2511e65c4f09356e =
[
    [ "agglomerative-cluster.cc", "agglomerative-cluster_8cc.html", "agglomerative-cluster_8cc" ],
    [ "compute-eer.cc", "compute-eer_8cc.html", "compute-eer_8cc" ],
    [ "compute-vad-from-frame-likes.cc", "compute-vad-from-frame-likes_8cc.html", "compute-vad-from-frame-likes_8cc" ],
    [ "compute-vad.cc", "compute-vad_8cc.html", "compute-vad_8cc" ],
    [ "ivector-adapt-plda.cc", "ivector-adapt-plda_8cc.html", "ivector-adapt-plda_8cc" ],
    [ "ivector-compute-dot-products.cc", "ivector-compute-dot-products_8cc.html", "ivector-compute-dot-products_8cc" ],
    [ "ivector-compute-lda.cc", "ivector-compute-lda_8cc.html", "ivector-compute-lda_8cc" ],
    [ "ivector-compute-plda.cc", "ivector-compute-plda_8cc.html", "ivector-compute-plda_8cc" ],
    [ "ivector-copy-plda.cc", "ivector-copy-plda_8cc.html", "ivector-copy-plda_8cc" ],
    [ "ivector-extract-online.cc", "ivector-extract-online_8cc.html", "ivector-extract-online_8cc" ],
    [ "ivector-extract.cc", "ivector-extract_8cc.html", "ivector-extract_8cc" ],
    [ "ivector-extractor-acc-stats.cc", "ivector-extractor-acc-stats_8cc.html", "ivector-extractor-acc-stats_8cc" ],
    [ "ivector-extractor-est.cc", "ivector-extractor-est_8cc.html", "ivector-extractor-est_8cc" ],
    [ "ivector-extractor-init.cc", "ivector-extractor-init_8cc.html", "ivector-extractor-init_8cc" ],
    [ "ivector-extractor-sum-accs.cc", "ivector-extractor-sum-accs_8cc.html", "ivector-extractor-sum-accs_8cc" ],
    [ "ivector-mean.cc", "ivector-mean_8cc.html", "ivector-mean_8cc" ],
    [ "ivector-normalize-length.cc", "ivector-normalize-length_8cc.html", "ivector-normalize-length_8cc" ],
    [ "ivector-plda-scoring-dense.cc", "ivector-plda-scoring-dense_8cc.html", "ivector-plda-scoring-dense_8cc" ],
    [ "ivector-plda-scoring.cc", "ivector-plda-scoring_8cc.html", "ivector-plda-scoring_8cc" ],
    [ "ivector-subtract-global-mean.cc", "ivector-subtract-global-mean_8cc.html", "ivector-subtract-global-mean_8cc" ],
    [ "ivector-transform.cc", "ivector-transform_8cc.html", "ivector-transform_8cc" ],
    [ "logistic-regression-copy.cc", "logistic-regression-copy_8cc.html", "logistic-regression-copy_8cc" ],
    [ "logistic-regression-eval.cc", "logistic-regression-eval_8cc.html", "logistic-regression-eval_8cc" ],
    [ "logistic-regression-train.cc", "logistic-regression-train_8cc.html", "logistic-regression-train_8cc" ],
    [ "merge-vads.cc", "merge-vads_8cc.html", "merge-vads_8cc" ],
    [ "select-voiced-frames.cc", "select-voiced-frames_8cc.html", "select-voiced-frames_8cc" ]
];