var dir_109f68d84cef4a133396a0be144fa9b1 =
[
    [ "cblas-wrappers.h", "cblas-wrappers_8h.html", "cblas-wrappers_8h" ],
    [ "compressed-matrix.cc", "compressed-matrix_8cc.html", null ],
    [ "compressed-matrix.h", "compressed-matrix_8h.html", "compressed-matrix_8h" ],
    [ "jama-eig.h", "jama-eig_8h.html", [
      [ "EigenvalueDecomposition", "classkaldi_1_1EigenvalueDecomposition.html", "classkaldi_1_1EigenvalueDecomposition" ]
    ] ],
    [ "jama-svd.h", "jama-svd_8h.html", null ],
    [ "kaldi-blas.h", "kaldi-blas_8h.html", null ],
    [ "kaldi-matrix-inl.h", "kaldi-matrix-inl_8h.html", "kaldi-matrix-inl_8h" ],
    [ "kaldi-matrix.cc", "kaldi-matrix_8cc.html", "kaldi-matrix_8cc" ],
    [ "kaldi-matrix.h", "kaldi-matrix_8h.html", "kaldi-matrix_8h" ],
    [ "kaldi-vector-inl.h", "kaldi-vector-inl_8h.html", "kaldi-vector-inl_8h" ],
    [ "kaldi-vector.cc", "kaldi-vector_8cc.html", "kaldi-vector_8cc" ],
    [ "kaldi-vector.h", "kaldi-vector_8h.html", "kaldi-vector_8h" ],
    [ "matrix-common.h", "matrix-common_8h.html", "matrix-common_8h" ],
    [ "matrix-functions-inl.h", "matrix-functions-inl_8h.html", "matrix-functions-inl_8h" ],
    [ "matrix-functions.cc", "matrix-functions_8cc.html", "matrix-functions_8cc" ],
    [ "matrix-functions.h", "matrix-functions_8h.html", "matrix-functions_8h" ],
    [ "matrix-lib-speed-test.cc", "matrix-lib-speed-test_8cc.html", "matrix-lib-speed-test_8cc" ],
    [ "matrix-lib-test.cc", "matrix-lib-test_8cc.html", "matrix-lib-test_8cc" ],
    [ "matrix-lib.h", "matrix-lib_8h.html", null ],
    [ "optimization.cc", "optimization_8cc.html", "optimization_8cc" ],
    [ "optimization.h", "optimization_8h.html", "optimization_8h" ],
    [ "packed-matrix.cc", "packed-matrix_8cc.html", null ],
    [ "packed-matrix.h", "packed-matrix_8h.html", "packed-matrix_8h" ],
    [ "qr.cc", "qr_8cc.html", "qr_8cc" ],
    [ "sp-matrix-inl.h", "sp-matrix-inl_8h.html", "sp-matrix-inl_8h" ],
    [ "sp-matrix.cc", "sp-matrix_8cc.html", "sp-matrix_8cc" ],
    [ "sp-matrix.h", "sp-matrix_8h.html", "sp-matrix_8h" ],
    [ "sparse-matrix-test.cc", "sparse-matrix-test_8cc.html", "sparse-matrix-test_8cc" ],
    [ "sparse-matrix.cc", "sparse-matrix_8cc.html", "sparse-matrix_8cc" ],
    [ "sparse-matrix.h", "sparse-matrix_8h.html", "sparse-matrix_8h" ],
    [ "srfft.cc", "srfft_8cc.html", null ],
    [ "srfft.h", "srfft_8h.html", null ],
    [ "tp-matrix.cc", "tp-matrix_8cc.html", null ],
    [ "tp-matrix.h", "tp-matrix_8h.html", null ]
];