var dir_67a0a17020b8eedc08ffa5626b1d53a1 =
[
    [ "am-nnet-simple.cc", "am-nnet-simple_8cc.html", null ],
    [ "am-nnet-simple.h", "am-nnet-simple_8h.html", [
      [ "AmNnetSimple", "classkaldi_1_1nnet3_1_1AmNnetSimple.html", "classkaldi_1_1nnet3_1_1AmNnetSimple" ]
    ] ],
    [ "attention-test.cc", "attention-test_8cc.html", "attention-test_8cc" ],
    [ "attention.cc", "attention_8cc.html", "attention_8cc" ],
    [ "attention.h", "attention_8h.html", "attention_8h" ],
    [ "convolution-test.cc", "convolution-test_8cc.html", "convolution-test_8cc" ],
    [ "convolution.cc", "convolution_8cc.html", "convolution_8cc" ],
    [ "convolution.h", "convolution_8h.html", "convolution_8h" ],
    [ "decodable-online-looped.cc", "decodable-online-looped_8cc.html", null ],
    [ "decodable-online-looped.h", "decodable-online-looped_8h.html", [
      [ "DecodableNnetLoopedOnlineBase", "classkaldi_1_1nnet3_1_1DecodableNnetLoopedOnlineBase.html", "classkaldi_1_1nnet3_1_1DecodableNnetLoopedOnlineBase" ],
      [ "DecodableNnetLoopedOnline", "classkaldi_1_1nnet3_1_1DecodableNnetLoopedOnline.html", "classkaldi_1_1nnet3_1_1DecodableNnetLoopedOnline" ],
      [ "DecodableAmNnetLoopedOnline", "classkaldi_1_1nnet3_1_1DecodableAmNnetLoopedOnline.html", "classkaldi_1_1nnet3_1_1DecodableAmNnetLoopedOnline" ]
    ] ],
    [ "decodable-simple-looped.cc", "decodable-simple-looped_8cc.html", null ],
    [ "decodable-simple-looped.h", "decodable-simple-looped_8h.html", [
      [ "NnetSimpleLoopedComputationOptions", "structkaldi_1_1nnet3_1_1NnetSimpleLoopedComputationOptions.html", "structkaldi_1_1nnet3_1_1NnetSimpleLoopedComputationOptions" ],
      [ "DecodableNnetSimpleLoopedInfo", "classkaldi_1_1nnet3_1_1DecodableNnetSimpleLoopedInfo.html", "classkaldi_1_1nnet3_1_1DecodableNnetSimpleLoopedInfo" ],
      [ "DecodableNnetSimpleLooped", "classkaldi_1_1nnet3_1_1DecodableNnetSimpleLooped.html", "classkaldi_1_1nnet3_1_1DecodableNnetSimpleLooped" ],
      [ "DecodableAmNnetSimpleLooped", "classkaldi_1_1nnet3_1_1DecodableAmNnetSimpleLooped.html", "classkaldi_1_1nnet3_1_1DecodableAmNnetSimpleLooped" ]
    ] ],
    [ "discriminative-supervision.cc", "discriminative-supervision_8cc.html", "discriminative-supervision_8cc" ],
    [ "discriminative-supervision.h", "discriminative-supervision_8h.html", "discriminative-supervision_8h" ],
    [ "discriminative-training.cc", "discriminative-training_8cc.html", "discriminative-training_8cc" ],
    [ "discriminative-training.h", "discriminative-training_8h.html", "discriminative-training_8h" ],
    [ "natural-gradient-online-test.cc", "natural-gradient-online-test_8cc.html", "natural-gradient-online-test_8cc" ],
    [ "natural-gradient-online.cc", "natural-gradient-online_8cc.html", null ],
    [ "natural-gradient-online.h", "natural-gradient-online_8h.html", [
      [ "OnlineNaturalGradient", "classkaldi_1_1nnet3_1_1OnlineNaturalGradient.html", "classkaldi_1_1nnet3_1_1OnlineNaturalGradient" ]
    ] ],
    [ "nnet-am-decodable-simple.cc", "nnet-am-decodable-simple_8cc.html", null ],
    [ "nnet-am-decodable-simple.h", "nnet-am-decodable-simple_8h.html", [
      [ "NnetSimpleComputationOptions", "structkaldi_1_1nnet3_1_1NnetSimpleComputationOptions.html", "structkaldi_1_1nnet3_1_1NnetSimpleComputationOptions" ],
      [ "DecodableNnetSimple", "classkaldi_1_1nnet3_1_1DecodableNnetSimple.html", "classkaldi_1_1nnet3_1_1DecodableNnetSimple" ],
      [ "DecodableAmNnetSimple", "classkaldi_1_1nnet3_1_1DecodableAmNnetSimple.html", "classkaldi_1_1nnet3_1_1DecodableAmNnetSimple" ],
      [ "DecodableAmNnetSimpleParallel", "classkaldi_1_1nnet3_1_1DecodableAmNnetSimpleParallel.html", "classkaldi_1_1nnet3_1_1DecodableAmNnetSimpleParallel" ]
    ] ],
    [ "nnet-analyze-test.cc", "nnet-analyze-test_8cc.html", "nnet-analyze-test_8cc" ],
    [ "nnet-analyze.cc", "nnet-analyze_8cc.html", "nnet-analyze_8cc" ],
    [ "nnet-analyze.h", "nnet-analyze_8h.html", "nnet-analyze_8h" ],
    [ "nnet-attention-component.cc", "nnet-attention-component_8cc.html", null ],
    [ "nnet-attention-component.h", "nnet-attention-component_8h.html", [
      [ "RestrictedAttentionComponent", "classkaldi_1_1nnet3_1_1RestrictedAttentionComponent.html", "classkaldi_1_1nnet3_1_1RestrictedAttentionComponent" ],
      [ "PrecomputedIndexes", "classkaldi_1_1nnet3_1_1RestrictedAttentionComponent_1_1PrecomputedIndexes.html", "classkaldi_1_1nnet3_1_1RestrictedAttentionComponent_1_1PrecomputedIndexes" ],
      [ "Memo", "structkaldi_1_1nnet3_1_1RestrictedAttentionComponent_1_1Memo.html", "structkaldi_1_1nnet3_1_1RestrictedAttentionComponent_1_1Memo" ]
    ] ],
    [ "nnet-chain-diagnostics.cc", "nnet-chain-diagnostics_8cc.html", "nnet-chain-diagnostics_8cc" ],
    [ "nnet-chain-diagnostics.h", "nnet-chain-diagnostics_8h.html", "nnet-chain-diagnostics_8h" ],
    [ "nnet-chain-example.cc", "nnet-chain-example_8cc.html", "nnet-chain-example_8cc" ],
    [ "nnet-chain-example.h", "nnet-chain-example_8h.html", "nnet-chain-example_8h" ],
    [ "nnet-chain-training.cc", "nnet-chain-training_8cc.html", [
      [ "ChainTrainerMemoryHolder", "classkaldi_1_1nnet3_1_1ChainTrainerMemoryHolder.html", "classkaldi_1_1nnet3_1_1ChainTrainerMemoryHolder" ]
    ] ],
    [ "nnet-chain-training.h", "nnet-chain-training_8h.html", [
      [ "NnetChainTrainingOptions", "structkaldi_1_1nnet3_1_1NnetChainTrainingOptions.html", "structkaldi_1_1nnet3_1_1NnetChainTrainingOptions" ],
      [ "NnetChainTrainer", "classkaldi_1_1nnet3_1_1NnetChainTrainer.html", "classkaldi_1_1nnet3_1_1NnetChainTrainer" ]
    ] ],
    [ "nnet-common-test.cc", "nnet-common-test_8cc.html", "nnet-common-test_8cc" ],
    [ "nnet-common.cc", "nnet-common_8cc.html", "nnet-common_8cc" ],
    [ "nnet-common.h", "nnet-common_8h.html", "nnet-common_8h" ],
    [ "nnet-compile-looped.cc", "nnet-compile-looped_8cc.html", "nnet-compile-looped_8cc" ],
    [ "nnet-compile-looped.h", "nnet-compile-looped_8h.html", "nnet-compile-looped_8h" ],
    [ "nnet-compile-test.cc", "nnet-compile-test_8cc.html", "nnet-compile-test_8cc" ],
    [ "nnet-compile-utils-test.cc", "nnet-compile-utils-test_8cc.html", "nnet-compile-utils-test_8cc" ],
    [ "nnet-compile-utils.cc", "nnet-compile-utils_8cc.html", "nnet-compile-utils_8cc" ],
    [ "nnet-compile-utils.h", "nnet-compile-utils_8h.html", "nnet-compile-utils_8h" ],
    [ "nnet-compile.cc", "nnet-compile_8cc.html", "nnet-compile_8cc" ],
    [ "nnet-compile.h", "nnet-compile_8h.html", [
      [ "CompilerOptions", "structkaldi_1_1nnet3_1_1CompilerOptions.html", "structkaldi_1_1nnet3_1_1CompilerOptions" ],
      [ "Compiler", "classkaldi_1_1nnet3_1_1Compiler.html", "classkaldi_1_1nnet3_1_1Compiler" ],
      [ "StepInfo", "structkaldi_1_1nnet3_1_1Compiler_1_1StepInfo.html", "structkaldi_1_1nnet3_1_1Compiler_1_1StepInfo" ]
    ] ],
    [ "nnet-component-itf.cc", "nnet-component-itf_8cc.html", null ],
    [ "nnet-component-itf.h", "nnet-component-itf_8h.html", "nnet-component-itf_8h" ],
    [ "nnet-component-test.cc", "_2nnet-component-test_8cc.html", "_2nnet-component-test_8cc" ],
    [ "nnet-computation-graph.cc", "nnet-computation-graph_8cc.html", "nnet-computation-graph_8cc" ],
    [ "nnet-computation-graph.h", "nnet-computation-graph_8h.html", "nnet-computation-graph_8h" ],
    [ "nnet-computation.cc", "nnet-computation_8cc.html", "nnet-computation_8cc" ],
    [ "nnet-computation.h", "nnet-computation_8h.html", "nnet-computation_8h" ],
    [ "nnet-compute-test.cc", "nnet3_2nnet-compute-test_8cc.html", "nnet3_2nnet-compute-test_8cc" ],
    [ "nnet-compute.cc", "nnet3_2nnet-compute_8cc.html", null ],
    [ "nnet-compute.h", "nnet3_2nnet-compute_8h.html", [
      [ "NnetComputeOptions", "structkaldi_1_1nnet3_1_1NnetComputeOptions.html", "structkaldi_1_1nnet3_1_1NnetComputeOptions" ],
      [ "NnetComputer", "classkaldi_1_1nnet3_1_1NnetComputer.html", "classkaldi_1_1nnet3_1_1NnetComputer" ],
      [ "CommandDebugInfo", "structkaldi_1_1nnet3_1_1NnetComputer_1_1CommandDebugInfo.html", "structkaldi_1_1nnet3_1_1NnetComputer_1_1CommandDebugInfo" ]
    ] ],
    [ "nnet-convolutional-component.cc", "nnet-convolutional-component_8cc.html", null ],
    [ "nnet-convolutional-component.h", "_2nnet-convolutional-component_8h.html", [
      [ "TimeHeightConvolutionComponent", "classkaldi_1_1nnet3_1_1TimeHeightConvolutionComponent.html", "classkaldi_1_1nnet3_1_1TimeHeightConvolutionComponent" ],
      [ "PrecomputedIndexes", "classkaldi_1_1nnet3_1_1TimeHeightConvolutionComponent_1_1PrecomputedIndexes.html", "classkaldi_1_1nnet3_1_1TimeHeightConvolutionComponent_1_1PrecomputedIndexes" ],
      [ "TdnnComponent", "classkaldi_1_1nnet3_1_1TdnnComponent.html", "classkaldi_1_1nnet3_1_1TdnnComponent" ],
      [ "PrecomputedIndexes", "classkaldi_1_1nnet3_1_1TdnnComponent_1_1PrecomputedIndexes.html", "classkaldi_1_1nnet3_1_1TdnnComponent_1_1PrecomputedIndexes" ]
    ] ],
    [ "nnet-derivative-test.cc", "nnet-derivative-test_8cc.html", "nnet-derivative-test_8cc" ],
    [ "nnet-descriptor-test.cc", "nnet-descriptor-test_8cc.html", "nnet-descriptor-test_8cc" ],
    [ "nnet-descriptor.cc", "nnet-descriptor_8cc.html", "nnet-descriptor_8cc" ],
    [ "nnet-descriptor.h", "nnet-descriptor_8h.html", [
      [ "ForwardingDescriptor", "classkaldi_1_1nnet3_1_1ForwardingDescriptor.html", "classkaldi_1_1nnet3_1_1ForwardingDescriptor" ],
      [ "SimpleForwardingDescriptor", "classkaldi_1_1nnet3_1_1SimpleForwardingDescriptor.html", "classkaldi_1_1nnet3_1_1SimpleForwardingDescriptor" ],
      [ "OffsetForwardingDescriptor", "classkaldi_1_1nnet3_1_1OffsetForwardingDescriptor.html", "classkaldi_1_1nnet3_1_1OffsetForwardingDescriptor" ],
      [ "SwitchingForwardingDescriptor", "classkaldi_1_1nnet3_1_1SwitchingForwardingDescriptor.html", "classkaldi_1_1nnet3_1_1SwitchingForwardingDescriptor" ],
      [ "RoundingForwardingDescriptor", "classkaldi_1_1nnet3_1_1RoundingForwardingDescriptor.html", "classkaldi_1_1nnet3_1_1RoundingForwardingDescriptor" ],
      [ "ReplaceIndexForwardingDescriptor", "classkaldi_1_1nnet3_1_1ReplaceIndexForwardingDescriptor.html", "classkaldi_1_1nnet3_1_1ReplaceIndexForwardingDescriptor" ],
      [ "SumDescriptor", "classkaldi_1_1nnet3_1_1SumDescriptor.html", "classkaldi_1_1nnet3_1_1SumDescriptor" ],
      [ "OptionalSumDescriptor", "classkaldi_1_1nnet3_1_1OptionalSumDescriptor.html", "classkaldi_1_1nnet3_1_1OptionalSumDescriptor" ],
      [ "SimpleSumDescriptor", "classkaldi_1_1nnet3_1_1SimpleSumDescriptor.html", "classkaldi_1_1nnet3_1_1SimpleSumDescriptor" ],
      [ "ConstantSumDescriptor", "classkaldi_1_1nnet3_1_1ConstantSumDescriptor.html", "classkaldi_1_1nnet3_1_1ConstantSumDescriptor" ],
      [ "BinarySumDescriptor", "classkaldi_1_1nnet3_1_1BinarySumDescriptor.html", "classkaldi_1_1nnet3_1_1BinarySumDescriptor" ],
      [ "Descriptor", "classkaldi_1_1nnet3_1_1Descriptor.html", "classkaldi_1_1nnet3_1_1Descriptor" ],
      [ "GeneralDescriptor", "structkaldi_1_1nnet3_1_1GeneralDescriptor.html", "structkaldi_1_1nnet3_1_1GeneralDescriptor" ]
    ] ],
    [ "nnet-diagnostics.cc", "nnet-diagnostics_8cc.html", "nnet-diagnostics_8cc" ],
    [ "nnet-diagnostics.h", "nnet-diagnostics_8h.html", "nnet-diagnostics_8h" ],
    [ "nnet-discriminative-diagnostics.cc", "nnet-discriminative-diagnostics_8cc.html", null ],
    [ "nnet-discriminative-diagnostics.h", "nnet-discriminative-diagnostics_8h.html", [
      [ "NnetDiscriminativeComputeObjf", "classkaldi_1_1nnet3_1_1NnetDiscriminativeComputeObjf.html", "classkaldi_1_1nnet3_1_1NnetDiscriminativeComputeObjf" ]
    ] ],
    [ "nnet-discriminative-example.cc", "nnet-discriminative-example_8cc.html", "nnet-discriminative-example_8cc" ],
    [ "nnet-discriminative-example.h", "nnet-discriminative-example_8h.html", "nnet-discriminative-example_8h" ],
    [ "nnet-discriminative-training.cc", "nnet-discriminative-training_8cc.html", null ],
    [ "nnet-discriminative-training.h", "nnet-discriminative-training_8h.html", [
      [ "NnetDiscriminativeOptions", "structkaldi_1_1nnet3_1_1NnetDiscriminativeOptions.html", "structkaldi_1_1nnet3_1_1NnetDiscriminativeOptions" ],
      [ "DiscriminativeObjectiveFunctionInfo", "structkaldi_1_1nnet3_1_1DiscriminativeObjectiveFunctionInfo.html", "structkaldi_1_1nnet3_1_1DiscriminativeObjectiveFunctionInfo" ],
      [ "NnetDiscriminativeTrainer", "classkaldi_1_1nnet3_1_1NnetDiscriminativeTrainer.html", "classkaldi_1_1nnet3_1_1NnetDiscriminativeTrainer" ]
    ] ],
    [ "nnet-example-test.cc", "nnet-example-test_8cc.html", "nnet-example-test_8cc" ],
    [ "nnet-example-utils.cc", "nnet-example-utils_8cc.html", "nnet-example-utils_8cc" ],
    [ "nnet-example-utils.h", "nnet-example-utils_8h.html", "nnet-example-utils_8h" ],
    [ "nnet-example.cc", "nnet3_2nnet-example_8cc.html", null ],
    [ "nnet-example.h", "nnet3_2nnet-example_8h.html", "nnet3_2nnet-example_8h" ],
    [ "nnet-general-component.cc", "nnet-general-component_8cc.html", "nnet-general-component_8cc" ],
    [ "nnet-general-component.h", "nnet-general-component_8h.html", [
      [ "DistributeComponent", "classkaldi_1_1nnet3_1_1DistributeComponent.html", "classkaldi_1_1nnet3_1_1DistributeComponent" ],
      [ "DistributeComponentPrecomputedIndexes", "classkaldi_1_1nnet3_1_1DistributeComponentPrecomputedIndexes.html", "classkaldi_1_1nnet3_1_1DistributeComponentPrecomputedIndexes" ],
      [ "StatisticsExtractionComponent", "classkaldi_1_1nnet3_1_1StatisticsExtractionComponent.html", "classkaldi_1_1nnet3_1_1StatisticsExtractionComponent" ],
      [ "StatisticsExtractionComponentPrecomputedIndexes", "classkaldi_1_1nnet3_1_1StatisticsExtractionComponentPrecomputedIndexes.html", "classkaldi_1_1nnet3_1_1StatisticsExtractionComponentPrecomputedIndexes" ],
      [ "StatisticsPoolingComponent", "classkaldi_1_1nnet3_1_1StatisticsPoolingComponent.html", "classkaldi_1_1nnet3_1_1StatisticsPoolingComponent" ],
      [ "StatisticsPoolingComponentPrecomputedIndexes", "classkaldi_1_1nnet3_1_1StatisticsPoolingComponentPrecomputedIndexes.html", "classkaldi_1_1nnet3_1_1StatisticsPoolingComponentPrecomputedIndexes" ],
      [ "BackpropTruncationComponent", "classkaldi_1_1nnet3_1_1BackpropTruncationComponent.html", "classkaldi_1_1nnet3_1_1BackpropTruncationComponent" ],
      [ "BackpropTruncationComponentPrecomputedIndexes", "classkaldi_1_1nnet3_1_1BackpropTruncationComponentPrecomputedIndexes.html", "classkaldi_1_1nnet3_1_1BackpropTruncationComponentPrecomputedIndexes" ],
      [ "ConstantComponent", "classkaldi_1_1nnet3_1_1ConstantComponent.html", "classkaldi_1_1nnet3_1_1ConstantComponent" ],
      [ "DropoutMaskComponent", "classkaldi_1_1nnet3_1_1DropoutMaskComponent.html", "classkaldi_1_1nnet3_1_1DropoutMaskComponent" ],
      [ "GeneralDropoutComponent", "classkaldi_1_1nnet3_1_1GeneralDropoutComponent.html", "classkaldi_1_1nnet3_1_1GeneralDropoutComponent" ],
      [ "GeneralDropoutComponentPrecomputedIndexes", "classkaldi_1_1nnet3_1_1GeneralDropoutComponentPrecomputedIndexes.html", "classkaldi_1_1nnet3_1_1GeneralDropoutComponentPrecomputedIndexes" ]
    ] ],
    [ "nnet-graph-test.cc", "nnet-graph-test_8cc.html", "nnet-graph-test_8cc" ],
    [ "nnet-graph.cc", "nnet-graph_8cc.html", "nnet-graph_8cc" ],
    [ "nnet-graph.h", "nnet-graph_8h.html", "nnet-graph_8h" ],
    [ "nnet-nnet-test.cc", "nnet3_2nnet-nnet-test_8cc.html", "nnet3_2nnet-nnet-test_8cc" ],
    [ "nnet-nnet.cc", "_2nnet-nnet_8cc.html", null ],
    [ "nnet-nnet.h", "_2nnet-nnet_8h.html", "_2nnet-nnet_8h" ],
    [ "nnet-normalize-component.cc", "nnet-normalize-component_8cc.html", null ],
    [ "nnet-normalize-component.h", "nnet-normalize-component_8h.html", [
      [ "NormalizeComponent", "classkaldi_1_1nnet3_1_1NormalizeComponent.html", "classkaldi_1_1nnet3_1_1NormalizeComponent" ],
      [ "BatchNormComponent", "classkaldi_1_1nnet3_1_1BatchNormComponent.html", "classkaldi_1_1nnet3_1_1BatchNormComponent" ],
      [ "Memo", "structkaldi_1_1nnet3_1_1BatchNormComponent_1_1Memo.html", "structkaldi_1_1nnet3_1_1BatchNormComponent_1_1Memo" ]
    ] ],
    [ "nnet-optimize-test.cc", "nnet-optimize-test_8cc.html", "nnet-optimize-test_8cc" ],
    [ "nnet-optimize-utils.cc", "nnet-optimize-utils_8cc.html", "nnet-optimize-utils_8cc" ],
    [ "nnet-optimize-utils.h", "nnet-optimize-utils_8h.html", "nnet-optimize-utils_8h" ],
    [ "nnet-optimize.cc", "nnet-optimize_8cc.html", "nnet-optimize_8cc" ],
    [ "nnet-optimize.h", "nnet-optimize_8h.html", "nnet-optimize_8h" ],
    [ "nnet-parse-test.cc", "nnet-parse-test_8cc.html", "nnet-parse-test_8cc" ],
    [ "nnet-parse.cc", "nnet-parse_8cc.html", "nnet-parse_8cc" ],
    [ "nnet-parse.h", "nnet-parse_8h.html", "nnet-parse_8h" ],
    [ "nnet-simple-component.cc", "nnet-simple-component_8cc.html", "nnet-simple-component_8cc" ],
    [ "nnet-simple-component.h", "nnet-simple-component_8h.html", [
      [ "PnormComponent", "classkaldi_1_1nnet3_1_1PnormComponent.html", "classkaldi_1_1nnet3_1_1PnormComponent" ],
      [ "DropoutComponent", "classkaldi_1_1nnet3_1_1DropoutComponent.html", "classkaldi_1_1nnet3_1_1DropoutComponent" ],
      [ "ElementwiseProductComponent", "classkaldi_1_1nnet3_1_1ElementwiseProductComponent.html", "classkaldi_1_1nnet3_1_1ElementwiseProductComponent" ],
      [ "SigmoidComponent", "classkaldi_1_1nnet3_1_1SigmoidComponent.html", "classkaldi_1_1nnet3_1_1SigmoidComponent" ],
      [ "TanhComponent", "classkaldi_1_1nnet3_1_1TanhComponent.html", "classkaldi_1_1nnet3_1_1TanhComponent" ],
      [ "RectifiedLinearComponent", "classkaldi_1_1nnet3_1_1RectifiedLinearComponent.html", "classkaldi_1_1nnet3_1_1RectifiedLinearComponent" ],
      [ "AffineComponent", "classkaldi_1_1nnet3_1_1AffineComponent.html", "classkaldi_1_1nnet3_1_1AffineComponent" ],
      [ "BlockAffineComponent", "classkaldi_1_1nnet3_1_1BlockAffineComponent.html", "classkaldi_1_1nnet3_1_1BlockAffineComponent" ],
      [ "RepeatedAffineComponent", "classkaldi_1_1nnet3_1_1RepeatedAffineComponent.html", "classkaldi_1_1nnet3_1_1RepeatedAffineComponent" ],
      [ "NaturalGradientRepeatedAffineComponent", "classkaldi_1_1nnet3_1_1NaturalGradientRepeatedAffineComponent.html", "classkaldi_1_1nnet3_1_1NaturalGradientRepeatedAffineComponent" ],
      [ "SoftmaxComponent", "classkaldi_1_1nnet3_1_1SoftmaxComponent.html", "classkaldi_1_1nnet3_1_1SoftmaxComponent" ],
      [ "LogSoftmaxComponent", "classkaldi_1_1nnet3_1_1LogSoftmaxComponent.html", "classkaldi_1_1nnet3_1_1LogSoftmaxComponent" ],
      [ "NaturalGradientAffineComponent", "classkaldi_1_1nnet3_1_1NaturalGradientAffineComponent.html", "classkaldi_1_1nnet3_1_1NaturalGradientAffineComponent" ],
      [ "LinearComponent", "classkaldi_1_1nnet3_1_1LinearComponent.html", "classkaldi_1_1nnet3_1_1LinearComponent" ],
      [ "FixedAffineComponent", "classkaldi_1_1nnet3_1_1FixedAffineComponent.html", "classkaldi_1_1nnet3_1_1FixedAffineComponent" ],
      [ "SumGroupComponent", "classkaldi_1_1nnet3_1_1SumGroupComponent.html", "classkaldi_1_1nnet3_1_1SumGroupComponent" ],
      [ "FixedScaleComponent", "classkaldi_1_1nnet3_1_1FixedScaleComponent.html", "classkaldi_1_1nnet3_1_1FixedScaleComponent" ],
      [ "FixedBiasComponent", "classkaldi_1_1nnet3_1_1FixedBiasComponent.html", "classkaldi_1_1nnet3_1_1FixedBiasComponent" ],
      [ "NoOpComponent", "classkaldi_1_1nnet3_1_1NoOpComponent.html", "classkaldi_1_1nnet3_1_1NoOpComponent" ],
      [ "SumBlockComponent", "classkaldi_1_1nnet3_1_1SumBlockComponent.html", "classkaldi_1_1nnet3_1_1SumBlockComponent" ],
      [ "ClipGradientComponent", "classkaldi_1_1nnet3_1_1ClipGradientComponent.html", "classkaldi_1_1nnet3_1_1ClipGradientComponent" ],
      [ "PermuteComponent", "classkaldi_1_1nnet3_1_1PermuteComponent.html", "classkaldi_1_1nnet3_1_1PermuteComponent" ],
      [ "PerElementScaleComponent", "classkaldi_1_1nnet3_1_1PerElementScaleComponent.html", "classkaldi_1_1nnet3_1_1PerElementScaleComponent" ],
      [ "PerElementOffsetComponent", "classkaldi_1_1nnet3_1_1PerElementOffsetComponent.html", "classkaldi_1_1nnet3_1_1PerElementOffsetComponent" ],
      [ "ConstantFunctionComponent", "classkaldi_1_1nnet3_1_1ConstantFunctionComponent.html", "classkaldi_1_1nnet3_1_1ConstantFunctionComponent" ],
      [ "NaturalGradientPerElementScaleComponent", "classkaldi_1_1nnet3_1_1NaturalGradientPerElementScaleComponent.html", "classkaldi_1_1nnet3_1_1NaturalGradientPerElementScaleComponent" ],
      [ "ScaleAndOffsetComponent", "classkaldi_1_1nnet3_1_1ScaleAndOffsetComponent.html", "classkaldi_1_1nnet3_1_1ScaleAndOffsetComponent" ],
      [ "ConvolutionComponent", "classkaldi_1_1nnet3_1_1ConvolutionComponent.html", "classkaldi_1_1nnet3_1_1ConvolutionComponent" ],
      [ "LstmNonlinearityComponent", "classkaldi_1_1nnet3_1_1LstmNonlinearityComponent.html", "classkaldi_1_1nnet3_1_1LstmNonlinearityComponent" ],
      [ "MaxpoolingComponent", "classkaldi_1_1nnet3_1_1MaxpoolingComponent.html", "classkaldi_1_1nnet3_1_1MaxpoolingComponent" ],
      [ "CompositeComponent", "classkaldi_1_1nnet3_1_1CompositeComponent.html", "classkaldi_1_1nnet3_1_1CompositeComponent" ]
    ] ],
    [ "nnet-tdnn-component.cc", "nnet-tdnn-component_8cc.html", null ],
    [ "nnet-test-utils.cc", "nnet-test-utils_8cc.html", "nnet-test-utils_8cc" ],
    [ "nnet-test-utils.h", "nnet-test-utils_8h.html", "nnet-test-utils_8h" ],
    [ "nnet-training.cc", "nnet-training_8cc.html", "nnet-training_8cc" ],
    [ "nnet-training.h", "nnet-training_8h.html", "nnet-training_8h" ],
    [ "nnet-utils-test.cc", "nnet-utils-test_8cc.html", "nnet-utils-test_8cc" ],
    [ "nnet-utils.cc", "nnet-utils_8cc.html", "nnet-utils_8cc" ],
    [ "nnet-utils.h", "_2nnet-utils_8h.html", "_2nnet-utils_8h" ]
];