Kaldi: util/edit-distance-test.cc File Reference
edit-distance-test.cc File Reference
#include "base/kaldi-common.h"
#include "util/edit-distance.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void TestEditDistance ()
void TestEditDistanceString ()
void TestEditDistance2 ()
void TestEditDistance2String ()
void TestLevenshteinAlignment ()
int main ()
Function Documentation
main()
int main ()
Definition at line 256 of file edit-distance-test.cc.
References kaldi::TestEditDistance(), kaldi::TestEditDistance2(), kaldi::TestEditDistance2String(), kaldi::TestEditDistanceString(), and kaldi::TestLevenshteinAlignment().
            {
   using namespace kaldi;
   TestEditDistance();
   TestEditDistanceString();
   TestEditDistance2();
   TestEditDistance2String();
   TestLevenshteinAlignment();
   std::cout << "Test OK\n";
 }