Kaldi: featbin/extend-transform-dim.cc File Reference
extend-transform-dim.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-matrix.h"
#include "transform/transform-common.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void IncreaseTransformDimension (int32 new_dimension, Matrix< BaseFloat > *mat)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 54 of file extend-transform-dim.cc.
References kaldi::ClassifyRspecifier(), kaldi::ClassifyWspecifier(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), kaldi::IncreaseTransformDimension(), KALDI_ERR, KALDI_LOG, SequentialTableReader< Holder >::Key(), kaldi::kNoRspecifier, kaldi::kNoWspecifier, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), SequentialTableReader< Holder >::Value(), TableWriter< Holder >::Write(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     const char *usage =
         "Read in transform from dimension d -> d (affine or linear), and output a transform\n"
         "from dimension e -> e (with e >= d, and e controlled by option --new-dimension).\n"
         "This new transform will leave the extra dimension unaffected, and transform the old\n"
         "dimensions in the same way.\n"
         "Usage: extend-transform-dim [options] (transform-A-rspecifier|transform-A-rxfilename) (transform-out-wspecifier|transform-out-wxfilename)\n"
         "E.g.: extend-transform-dim --new-dimension=117 in.mat big.mat\n";
     bool binary = true;
     int32 new_dimension = -1;
     ParseOptions po(usage);
     po.Register("binary", &binary, "Write in binary mode (only relevant if output is a wxfilename)");
     po.Register("new-dimension", &new_dimension,
                 "Larger dimension we are changing matrix to");
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string transform_in_fn = po.GetArg(1);
     std::string transform_out_fn = po.GetArg(2);
     // all these "fn"'s are either rspecifiers or filenames.
     bool in_is_rspecifier =
         (ClassifyRspecifier(transform_in_fn, NULL, NULL)
          != kNoRspecifier),
         out_is_wspecifier =
         (ClassifyWspecifier(transform_out_fn, NULL, NULL, NULL)
          != kNoWspecifier);
     if (in_is_rspecifier != out_is_wspecifier)
       KALDI_ERR << "Either none or both of the (input, output) must be a Table.";
     if (in_is_rspecifier) {
       SequentialBaseFloatMatrixReader reader(transform_in_fn);
       BaseFloatMatrixWriter writer(transform_out_fn);
       int32 num_done = 0;
       for (; !reader.Done(); reader.Next()) {
         std::string key = reader.Key();
         Matrix<BaseFloat> mat(reader.Value());
         IncreaseTransformDimension(new_dimension, &mat);
         writer.Write(key, mat);
         num_done++;
       }
       KALDI_LOG << "Increased transform dim to " << new_dimension
                 << " for " << num_done << " matrices.";
       return (num_done != 0 ? 0 : 1);
     } else {
       Matrix<BaseFloat> mat;
       ReadKaldiObject(transform_in_fn, &mat);
       int32 old_dim = mat.NumRows();
       IncreaseTransformDimension(new_dimension, &mat);
       WriteKaldiObject(mat, transform_out_fn, binary);
       KALDI_LOG << "Increased transform dim from " << old_dim << " to "
                 << mat.NumRows() << " and wrote to " << transform_out_fn;
       return 0;
     }
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }