Kaldi: nnetbin/feat-to-post.cc File Reference
feat-to-post.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/posterior.h"
Functions
int main (int argc, char *argv[])
Converts features into posterior format, which is the generic format of NN training targets in 'nnet1'.
Function Documentation
main()
int main (int argc, char * argv[])
Converts features into posterior format, which is the generic format of NN training targets in 'nnet1'.
Definition at line 27 of file feat-to-post.cc.
References rnnlm::d, SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_ASSERT, KALDI_LOG, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), ParseOptions::Read(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   using namespace kaldi;
   typedef kaldi::int32 int32;
   try {
     const char *usage =
       "Convert features into posterior format, which is the generic format \n"
       "of NN training targets in Karel's nnet1 tools.\n"
       "(speed is not an issue for reasonably low NN-output dimensions)\n"
       "Usage:  feat-to-post [options] feat-rspecifier posteriors-wspecifier\n"
       "e.g.:\n"
       " feat-to-post scp:feats.scp ark:feats.post\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string feats_rspecifier = po.GetArg(1);
     std::string posteriors_wspecifier = po.GetArg(2);
     int32 num_done = 0;
     SequentialBaseFloatMatrixReader feats_reader(feats_rspecifier);
     PosteriorWriter posterior_writer(posteriors_wspecifier);
     for (; !feats_reader.Done(); feats_reader.Next()) {
       num_done++;
       const Matrix<BaseFloat> &mat = feats_reader.Value();
       int32 num_frames = mat.NumRows(),
         num_dims = mat.NumCols();
       // Posterior is vector<vector<pair<int32, BaseFloat> > >
       Posterior post(num_frames);
       // Fill posterior with matrix values,
       for (int32 f = 0; f < num_frames; f++) {
         for (int32 d = 0; d < num_dims; d++) {
           post[f].push_back(std::make_pair(d, mat(f, d)));
         }
         KALDI_ASSERT(post[f].size() == num_dims);
       }
       // Store
       posterior_writer.Write(feats_reader.Key(), post);
     }
     KALDI_LOG << "Converted " << num_done << " alignments.";
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }