Kaldi: fgmmbin/fgmm-global-est.cc File Reference
fgmm-global-est.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "gmm/full-gmm.h"
#include "gmm/mle-full-gmm.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 25 of file fgmm-global-est.cc.
References count, ParseOptions::GetArg(), KALDI_LOG, kaldi::MleFullGmmUpdate(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), AccumFullGmm::Read(), ParseOptions::Read(), FullGmm::Read(), MleFullGmmOptions::Register(), ParseOptions::Register(), FullGmm::Split(), Input::Stream(), kaldi::StringToGmmFlags(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     typedef int32 int32;
     MleFullGmmOptions gmm_opts;
     const char *usage =
         "Estimate a full-covariance GMM from the accumulated stats.\n"
         "Usage:  fgmm-global-est [options] <model-in> <stats-in> <model-out>\n";
     bool binary_write = true;
     int32 mixup = 0;
     BaseFloat perturb_factor = 0.01;
     std::string update_flags_str = "mvw";
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("update-flags", &update_flags_str, "Which GMM parameters will be "
                 "updated: subset of mvw.");
     po.Register("mix-up", &mixup, "Increase number of mixture components to "
                 "this overall target.");
     po.Register("perturb-factor", &perturb_factor, "While mixing up, perturb "
         "means by standard deviation times this factor.");
     gmm_opts.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_in_filename = po.GetArg(1),
         stats_filename = po.GetArg(2),
         model_out_filename = po.GetArg(3);
     FullGmm fgmm;
     {
       bool binary_read;
       Input ki(model_in_filename, &binary_read);
       fgmm.Read(ki.Stream(), binary_read);
     }
     AccumFullGmm gmm_accs;
     {
       bool binary;
       Input ki(stats_filename, &binary);
       gmm_accs.Read(ki.Stream(), binary, true /* add accs, doesn't matter */);
     }
     {  // Update GMMs.
       BaseFloat objf_impr, count;
       MleFullGmmUpdate(gmm_opts, gmm_accs, StringToGmmFlags(update_flags_str),
                        &fgmm, &objf_impr, &count);
       KALDI_LOG << "Overall objective function improvement is "
                 << (objf_impr/count) << " per frame over "
                 <<  (count) <<  " frames.";
     }
     if (mixup != 0)
       fgmm.Split(mixup, perturb_factor);
     WriteKaldiObject(fgmm, model_out_filename, binary_write);
     KALDI_LOG << "Written model to " << model_out_filename;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }