Kaldi: fgmmbin/fgmm-global-merge.cc File Reference
fgmm-global-merge.cc File Reference
#include "util/common-utils.h"
#include "gmm/full-gmm.h"
#include "gmm/mle-full-gmm.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void MergeFullGmm (const FullGmm &src, FullGmm *dst)
merges GMMs by appending Gaussians in "src" to "dst".
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 65 of file fgmm-global-merge.cc.
References ParseOptions::GetArg(), rnnlm::i, KALDI_LOG, kaldi::MergeFullGmm(), ParseOptions::NumArgs(), FullGmm::NumGauss(), ParseOptions::PrintUsage(), ParseOptions::Read(), FullGmm::Read(), ParseOptions::Register(), Output::Stream(), Input::Stream(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Combine a number of GMMs into a larger GMM, with #Gauss = \n"
         "  sum(individual #Gauss)).  Output full GMM, and a text file with\n"
         "  sizes of each individual GMM.\n"
         "Usage: fgmm-global-merge [options] fgmm-out sizes-file-out fgmm-in1 fgmm-in2 ...\n";
     bool binary = true;
     ParseOptions po(usage);
     po.Register("binary", &binary, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() < 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string fgmm_out_filename = po.GetArg(1),
         sizes_out_filename = po.GetArg(2);
     FullGmm fgmm;
     Output sizes_ko(sizes_out_filename, false); // false == not binary.
     for (int i = 3, max = po.NumArgs(); i <= max; i++) {
       std::string stats_in_filename = po.GetArg(i);
       bool binary_read;
       Input ki(stats_in_filename, &binary_read);
       if (i==3) {
         fgmm.Read(ki.Stream(), binary_read);
         sizes_ko.Stream() << fgmm.NumGauss() << ' ';
       } else {
         FullGmm fgmm2;
         fgmm2.Read(ki.Stream(), binary_read);
         sizes_ko.Stream() << fgmm2.NumGauss() << ' ';
         MergeFullGmm(fgmm2, &fgmm);
       }
     }
     sizes_ko.Stream() << "\n";
     // Write out the model
     WriteKaldiObject(fgmm, fgmm_out_filename, binary);
     KALDI_LOG << "Written merged GMM to " << fgmm_out_filename;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }