Kaldi: featbin/fmpe-est.cc File Reference
fmpe-est.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "transform/fmpe.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 24 of file fmpe-est.cc.
References FmpeStats::DoChecks(), ParseOptions::GetArg(), KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), FmpeUpdateOptions::Register(), Fmpe::Update(), and kaldi::WriteKaldiObject().
{
   using namespace kaldi;
   try {
     const char *usage =
         "Do one iteration of learning (modified gradient descent)\n"
         "on fMPE transform\n"
         "Usage: fmpe-est [options...] <fmpe-in> <stats-in> <fmpe-out>\n"
         "E.g. fmpe-est 1.fmpe 1.accs 2.fmpe\n";
     ParseOptions po(usage);
     FmpeUpdateOptions opts;
     bool binary = true;
     po.Register("binary", &binary, "If true, output fMPE object in "
                 "binary mode.");
     opts.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string fmpe_rxfilename = po.GetArg(1),
         stats_rxfilename = po.GetArg(2),
         fmpe_wxfilename = po.GetArg(3);
     Fmpe fmpe;
     ReadKaldiObject(fmpe_rxfilename, &fmpe);
     FmpeStats stats;
     ReadKaldiObject(stats_rxfilename, &stats);
     stats.DoChecks(); // checks certain checksums.
     fmpe.Update(opts, stats);
     WriteKaldiObject(fmpe, fmpe_wxfilename, binary);
     KALDI_LOG << "Updated fMPE object and wrote to "
               << fmpe_wxfilename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }