Kaldi: fstbin/fstaddsubsequentialloop.cc File Reference
fstaddsubsequentialloop.cc File Reference
#include "base/kaldi-common.h"
#include "util/kaldi-io.h"
#include "util/parse-options.h"
#include "util/text-utils.h"
#include "fst/fstlib.h"
#include "fstext/fstext-utils.h"
#include "fstext/context-fst.h"
#include "fstext/kaldi-fst-io.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 37 of file fstaddsubsequentialloop.cc.
References fst::AddSubsequentialLoop(), kaldi::ConvertStringToInteger(), ParseOptions::GetArg(), ParseOptions::GetOptArg(), fst::HighestNumberedInputSymbol(), KALDI_ERR, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), fst::ReadFstKaldi(), ParseOptions::Register(), and fst::WriteFstKaldi().
{
   try {
     using namespace kaldi;
     using namespace fst;
     using kaldi::int32;
     const char *usage =
         "Minimizes FST after encoding [this algorithm applicable to all FSTs in tropical semiring]\n"
         "\n"
         "Usage:  fstaddsubsequentialloop subseq_sym [in.fst [out.fst] ]\n"
         "E.g.:   fstaddsubsequentialloop 52 < LG.fst > LG_sub.fst\n";
     float delta = kDelta;
     ParseOptions po(usage);
     po.Register("delta", &delta,
                 "Delta likelihood used for quantization of weights");
     po.Read(argc, argv);
     if (po.NumArgs() < 1 || po.NumArgs() > 3) {
       po.PrintUsage();
       exit(1);
     }
     int32 subseq_sym;
     if (!ConvertStringToInteger(po.GetArg(1), &subseq_sym))
       KALDI_ERR << "Invalid subsequential symbol "<<po.GetArg(1);
     std::string fst_in_filename = po.GetOptArg(2);
     std::string fst_out_filename = po.GetOptArg(3);
     VectorFst<StdArc> *fst = ReadFstKaldi(fst_in_filename);
     int32 h = HighestNumberedInputSymbol(*fst);
     if (subseq_sym <= h) {
       std::cerr << "fstaddsubsequentialloop.cc: subseq symbol does not seem right, "<<subseq_sym<<" <= "<<h<<'\n';
     }
     AddSubsequentialLoop(subseq_sym, fst);
     WriteFstKaldi(*fst, fst_out_filename);
     delete fst;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }