Kaldi: fstbin/fstaddselfloops.cc File Reference
fstaddselfloops.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "fst/fstlib.h"
#include "fstext/determinize-star.h"
#include "fstext/fstext-utils.h"
#include "fstext/kaldi-fst-io.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 36 of file fstaddselfloops.cc.
References kaldi::AddSelfLoops(), ParseOptions::GetArg(), ParseOptions::GetOptArg(), KALDI_ERR, ParseOptions::NumArgs(), kaldi::PrintableRxfilename(), ParseOptions::PrintUsage(), ParseOptions::Read(), fst::ReadFstKaldi(), kaldi::ReadIntegerVectorSimple(), and fst::WriteFstKaldi().
{
   try {
     using namespace kaldi;
     using namespace fst;
     using kaldi::int32;
     const char *usage =
         "Adds self-loops to states of an FST to propagate disambiguation symbols through it\n"
         "They are added on each final state and each state with non-epsilon output symbols\n"
         "on at least one arc out of the state.  Useful in conjunction with predeterminize\n"
         "\n"
         "Usage:  fstaddselfloops in-disambig-list out-disambig-list  [in.fst [out.fst] ]\n"
         "E.g:  fstaddselfloops in.list out.list < in.fst > withloops.fst\n"
         "in.list and out.list are lists of integers, one per line, of the\n"
         "same length.\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() < 2 || po.NumArgs() > 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string disambig_in_rxfilename = po.GetArg(1),
         disambig_out_rxfilename = po.GetArg(2),
         fst_in_filename = po.GetOptArg(3),
         fst_out_filename = po.GetOptArg(4);
     VectorFst<StdArc> *fst = ReadFstKaldi(fst_in_filename);
     std::vector<int32> disambig_in;
     if (!ReadIntegerVectorSimple(disambig_in_rxfilename, &disambig_in))
       KALDI_ERR << "fstaddselfloops: Could not read disambiguation symbols from "
                  << kaldi::PrintableRxfilename(disambig_in_rxfilename);
     std::vector<int32> disambig_out;
     if (!ReadIntegerVectorSimple(disambig_out_rxfilename, &disambig_out))
       KALDI_ERR << "fstaddselfloops: Could not read disambiguation symbols from "
                 << kaldi::PrintableRxfilename(disambig_out_rxfilename);
     if (disambig_in.size() != disambig_out.size())
       KALDI_ERR << "fstaddselfloops: mismatch in size of disambiguation symbols";
     AddSelfLoops(fst, disambig_in, disambig_out);
     WriteFstKaldi(*fst, fst_out_filename);
     delete fst;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
   return 0;
 }