Kaldi: fstbin/fstisstochastic.cc File Reference
fstisstochastic.cc File Reference
#include "base/kaldi-common.h"
#include "util/kaldi-io.h"
#include "util/parse-options.h"
#include "fst/fstlib.h"
#include "fstext/fstext-utils.h"
#include "fstext/kaldi-fst-io.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 43 of file fstisstochastic.cc.
References ParseOptions::GetOptArg(), fst::IsStochasticFst(), fst::IsStochasticFstInLog(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), fst::ReadFstKaldiGeneric(), and ParseOptions::Register().
{
   try {
     using namespace kaldi;
     using namespace fst;
     using kaldi::int32;
     const char *usage =
         "Checks whether an FST is stochastic and exits with success if so.\n"
         "Prints out maximum error (in log units).\n"
         "\n"
         "Usage:  fstisstochastic [ in.fst ]\n";
     float delta = 0.01;
     bool test_in_log = true;
     ParseOptions po(usage);
     po.Register("delta", &delta, "Maximum error to accept.");
     po.Register("test-in-log", &test_in_log, "Test stochasticity in log semiring.");
     po.Read(argc, argv);
     if (po.NumArgs() > 1) {
       po.PrintUsage();
       exit(1);
     }
     std::string fst_in_filename = po.GetOptArg(1);
     Fst<StdArc> *fst = ReadFstKaldiGeneric(fst_in_filename);
     bool ans;
     StdArc::Weight min, max;
     if (test_in_log)  ans = IsStochasticFstInLog(*fst, delta, &min, &max);
     else ans = IsStochasticFst(*fst, delta, &min, &max);
     std::cout << min.Value() << " " << max.Value() << '\n';
     delete fst;
     if (ans) return 0;  // success;
     else return 1;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }