Kaldi: fstbin/fstmakecontextsyms.cc File Reference
fstmakecontextsyms.cc File Reference
#include "tree/context-dep.h"
#include "util/common-utils.h"
#include "fst/fstlib.h"
#include "fstext/fstext-utils.h"
#include "fstext/context-fst.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 55 of file fstmakecontextsyms.cc.
References fst::CreateILabelInfoSymbolTable(), ParseOptions::GetArg(), ParseOptions::GetOptArg(), KALDI_ERR, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), fst::ReadILabelInfo(), ParseOptions::Register(), and Input::Stream().
{
   try {
     using namespace kaldi;
     using namespace fst;
     typedef fst::StdArc::Label Label;
     const char *usage =  "Create input symbols for CLG\n"
         "Usage: fstmakecontextsyms phones-symtab ilabels_input_file [output-symtab.txt]\n"
         "E.g.:  fstmakecontextsyms  phones.txt ilabels.sym > context_symbols.txt\n";
     ParseOptions po(usage);
     std::string disambig_list_file = "",
         phone_separator = "/",
         initial_disambig = "#-1";
     po.Register("phone-separator", &phone_separator,
                 "Separator for phones in phone-in-context symbols.");
     po.Register("initial-disambig", &initial_disambig,
                 "Name for special disambiguation symbol that occurs at start "
                 "of context-dependent phone sequences");
     po.Read(argc, argv);
     if (po.NumArgs() < 2 || po.NumArgs() > 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string phones_symtab_filename = po.GetArg(1),
         ilabel_info_filename = po.GetArg(2),
         clg_symtab_filename = po.GetOptArg(3);
     std::vector<std::vector<kaldi::int32> > ilabel_info;
     {
       bool binary;
       Input ki(ilabel_info_filename, &binary);
       ReadILabelInfo(ki.Stream(),
                      binary, &ilabel_info);
     }
     fst::SymbolTable *phones_symtab = NULL;
     {  // read phone symbol table.
       std::ifstream is(phones_symtab_filename.c_str());
       phones_symtab = fst::SymbolTable::ReadText(is, phones_symtab_filename);
       if (!phones_symtab) KALDI_ERR << "Could not read phones symbol-table file "<<phones_symtab_filename;
     }
     fst::SymbolTable *clg_symtab =
         CreateILabelInfoSymbolTable(ilabel_info,
                                     *phones_symtab,
                                     phone_separator,
                                     initial_disambig);
     if (clg_symtab_filename == "") {
       if (!clg_symtab->WriteText(std::cout))
         KALDI_ERR << "Cannot write symbol table to standard output.";
     } else {
       if (!clg_symtab->WriteText(clg_symtab_filename))
         KALDI_ERR << "Cannot open symbol table file "<<clg_symtab_filename<<" for writing.";
     }
     delete clg_symtab;
     delete phones_symtab;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }