Kaldi: fstbin/fstrmsymbols.cc File Reference
fstrmsymbols.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "fst/fstlib.h"
#include "fstext/determinize-star.h"
#include "fstext/fstext-utils.h"
#include "fstext/kaldi-fst-io.h"
Namespaces
fst
For an extended explanation of the framework of which grammar-fsts are a part, please see Support for grammars and graphs with on-the-fly parts. (i.e.
Functions
template<class Arc , class I >
void RemoveArcsWithSomeInputSymbols (const std::vector< I > &symbols_in, VectorFst< Arc > *fst)
template<class Arc , class I >
void PenalizeArcsWithSomeInputSymbols (const std::vector< I > &symbols_in, float penalty, VectorFst< Arc > *fst)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 85 of file fstrmsymbols.cc.
References fst::CastOrConvertToVectorFst(), ParseOptions::GetArg(), ParseOptions::GetOptArg(), KALDI_ERR, ParseOptions::NumArgs(), fst::PenalizeArcsWithSomeInputSymbols(), ParseOptions::PrintUsage(), ParseOptions::Read(), fst::ReadFstKaldiGeneric(), kaldi::ReadIntegerVectorSimple(), ParseOptions::Register(), fst::RemoveArcsWithSomeInputSymbols(), fst::RemoveSomeInputSymbols(), and fst::WriteFstKaldi().
{
   try {
     using namespace kaldi;
     using namespace fst;
     using kaldi::int32;
     bool apply_to_output = false;
     bool remove_arcs = false;
     float penalty = -std::numeric_limits<BaseFloat>::infinity();
     const char *usage =
         "With no options, replaces a subset of symbols with epsilon, wherever\n"
         "they appear on the input side of an FST."
         "With --remove-arcs=true, will remove arcs that contain these symbols\n"
         "on the input\n"
         "With --penalty=<float>, will add the specified penalty to the\n"
         "cost of any arc that has one of the given symbols on its input side\n"
         "In all cases, the option --apply-to-output=true (or for\n"
         "back-compatibility, --remove-from-output=true) makes this apply\n"
         "to the output side.\n"
         "\n"
         "Usage:  fstrmsymbols [options] <in-disambig-list>  [<in.fst> [<out.fst>]]\n"
         "E.g:  fstrmsymbols in.list  < in.fst > out.fst\n"
         "<in-disambig-list> is an rxfilename specifying a file containing list of integers\n"
         "representing symbols, in text form, one per line.\n";
     ParseOptions po(usage);
     po.Register("remove-from-output", &apply_to_output, "If true, this applies to symbols "
                 "on the output, not the input, side.  (For back compatibility; use "
                 "--apply-to-output insead)");
     po.Register("apply-to-output", &apply_to_output, "If true, this applies to symbols "
                 "on the output, not the input, side.");
     po.Register("remove-arcs", &remove_arcs, "If true, instead of converting the symbol "
                 "to <eps>, remove the arcs.");
     po.Register("penalty", &penalty, "If specified, instead of converting "
                 "the symbol to <eps>, penalize the arc it is on by adding this "
                 "value to its cost.");
     po.Read(argc, argv);
     if (remove_arcs &&
         penalty != -std::numeric_limits<BaseFloat>::infinity())
       KALDI_ERR << "--remove-arc and --penalty options are mutually exclusive";
     if (po.NumArgs() < 1 || po.NumArgs() > 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string disambig_rxfilename = po.GetArg(1),
         fst_rxfilename = po.GetOptArg(2),
         fst_wxfilename = po.GetOptArg(3);
     VectorFst<StdArc> *fst = CastOrConvertToVectorFst(
         ReadFstKaldiGeneric(fst_rxfilename));
     std::vector<int32> disambig_in;
     if (!ReadIntegerVectorSimple(disambig_rxfilename, &disambig_in))
       KALDI_ERR << "fstrmsymbols: Could not read disambiguation symbols from "
                 << (disambig_rxfilename == "" ? "standard input" : disambig_rxfilename);
     if (apply_to_output) Invert(fst);
     if (remove_arcs) {
       RemoveArcsWithSomeInputSymbols(disambig_in, fst);
     } else if (penalty != -std::numeric_limits<BaseFloat>::infinity()) {
       PenalizeArcsWithSomeInputSymbols(disambig_in, penalty, fst);
     } else {
       RemoveSomeInputSymbols(disambig_in, fst);
     }
     if (apply_to_output) Invert(fst);
     WriteFstKaldi(*fst, fst_wxfilename);
     delete fst;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }