Kaldi: gmmbin/gmm-global-est-fmllr.cc File Reference
gmm-global-est-fmllr.cc File Reference
#include <string>
#include <vector>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "gmm/am-diag-gmm.h"
#include "hmm/transition-model.h"
#include "transform/fmllr-diag-gmm.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
bool AccumulateForUtterance (const Matrix< BaseFloat > &feats, const DiagGmm &gmm, const std::string &key, RandomAccessBaseFloatVectorReader *weights_reader, RandomAccessInt32VectorVectorReader *gselect_reader, AccumFullGmm *fullcov_stats)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 83 of file gmm-global-est-fmllr.cc.
References kaldi::AccumulateForUtterance(), DiagGmm::Dim(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), RandomAccessTableReader< Holder >::HasKey(), rnnlm::i, KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), kaldi::kGmmAll, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), DiagGmm::NumGauss(), ParseOptions::PrintUsage(), ParseOptions::Read(), DiagGmm::Read(), kaldi::ReadKaldiObject(), FmllrOptions::Register(), ParseOptions::Register(), MatrixBase< Real >::SetUnit(), Input::Stream(), FmllrDiagGmmAccs::Update(), RandomAccessTableReader< Holder >::Value(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     typedef kaldi::int32 int32;
     using namespace kaldi;
     const char *usage =
         "Estimate global fMLLR transforms, either per utterance or for the supplied\n"
         "set of speakers (spk2utt option).  Reads features, and (with --weights option)\n"
         "weights for each frame (also see --gselect option)\n"
         "Usage: gmm-global-est-fmllr [options] <gmm-in> <feature-rspecifier> <transform-wspecifier>\n";
     ParseOptions po(usage);
     FmllrOptions fmllr_opts;
     string spk2utt_rspecifier, gselect_rspecifier, weights_rspecifier,
         alignment_model;
     po.Register("spk2utt", &spk2utt_rspecifier, "rspecifier for speaker to "
                 "utterance-list map");
     po.Register("gselect", &gselect_rspecifier, "rspecifier for gselect objects "
                 "to limit the #Gaussians accessed on each frame.");
     po.Register("weights", &weights_rspecifier, "rspecifier for a vector of floats "
                 "for each utterance, that's a per-frame weight.");
     po.Register("align-model", &alignment_model, "rxfilename for a model in the "
                 "speaker-independent space, to get Gaussian alignments from");
     fmllr_opts.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     string gmm_rxfilename = po.GetArg(1),
         feature_rspecifier = po.GetArg(2),
         trans_wspecifier = po.GetArg(3);
     DiagGmm gmm;
     ReadKaldiObject(gmm_rxfilename, &gmm);
     DiagGmm ali_gmm_read;
     if (alignment_model != "") {
       bool binary;
       Input ki(gmm_rxfilename, &binary);
       ali_gmm_read.Read(ki.Stream(), binary);
     }
     DiagGmm &ali_gmm = (alignment_model != "" ? ali_gmm_read : gmm);
     RandomAccessBaseFloatVectorReader weights_reader(weights_rspecifier);
     RandomAccessInt32VectorVectorReader gselect_reader(gselect_rspecifier);
     double tot_impr = 0.0, tot_t = 0.0;
     BaseFloatMatrixWriter transform_writer(trans_wspecifier);
     int32 num_done = 0, num_err = 0;
     if (spk2utt_rspecifier != "") {  // per-speaker adaptation
       SequentialTokenVectorReader spk2utt_reader(spk2utt_rspecifier);
       RandomAccessBaseFloatMatrixReader feature_reader(feature_rspecifier);
       for (; !spk2utt_reader.Done(); spk2utt_reader.Next()) {
         AccumFullGmm fullcov_stats(gmm.NumGauss(), gmm.Dim(), kGmmAll);
         string spk = spk2utt_reader.Key();
         const vector<string> &uttlist = spk2utt_reader.Value();
         for (size_t i = 0; i < uttlist.size(); i++) {
           std::string utt = uttlist[i];
           if (!feature_reader.HasKey(utt)) {
             KALDI_WARN << "Did not find features for utterance " << utt;
             continue;
           }
           const Matrix<BaseFloat> &feats = feature_reader.Value(utt);
           if (AccumulateForUtterance(feats, ali_gmm, utt, &weights_reader,
                                      &gselect_reader, &fullcov_stats)) num_done++;
           else num_err++;
         }  // end looping over all utterances of the current speaker
         BaseFloat impr, spk_tot_t;
         {  // Compute the transform and write it out.
           Matrix<BaseFloat> transform(gmm.Dim(), gmm.Dim()+1);
           transform.SetUnit();
           FmllrDiagGmmAccs spk_stats(gmm, fullcov_stats);
           spk_stats.Update(fmllr_opts, &transform, &impr, &spk_tot_t);
           transform_writer.Write(spk, transform);
         }
         KALDI_LOG << "For speaker " << spk << ", auxf-impr from fMLLR is "
                   << (impr/spk_tot_t) << ", over " << spk_tot_t << " frames.";
         tot_impr += impr;
         tot_t += spk_tot_t;
       }  // end looping over speakers
     } else {  // per-utterance adaptation
       SequentialBaseFloatMatrixReader feature_reader(feature_rspecifier);
       for (; !feature_reader.Done(); feature_reader.Next()) {
         string utt = feature_reader.Key();
         const Matrix<BaseFloat> &feats = feature_reader.Value();
         AccumFullGmm fullcov_stats(gmm.NumGauss(), gmm.Dim(), kGmmAll);
         if (AccumulateForUtterance(feats, ali_gmm, utt, &weights_reader,
                                    &gselect_reader, &fullcov_stats)) {
           BaseFloat impr, utt_tot_t;
           {  // Compute the transform and write it out.
             Matrix<BaseFloat> transform(gmm.Dim(), gmm.Dim()+1);
             transform.SetUnit();
             FmllrDiagGmmAccs spk_stats(gmm, fullcov_stats);
             spk_stats.Update(fmllr_opts, &transform, &impr, &utt_tot_t);
             transform_writer.Write(utt, transform);
           }
           KALDI_LOG << "For utterance " << utt << ", auxf-impr from fMLLR is "
                     << (impr/utt_tot_t) << ", over " << utt_tot_t << " frames.";
           tot_impr += impr;
           tot_t += utt_tot_t;
           num_done++;
         } else num_err++;
       }
     }
     KALDI_LOG << "Done " << num_done << " files, " << num_err
               << " with errors.";
     KALDI_LOG << "Overall fMLLR auxf impr per frame is "
               << (tot_impr / tot_t) << " over " << tot_t << " frames.";
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }