Kaldi: gmmbin/gmm-acc-mllt.cc File Reference
gmm-acc-mllt.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "gmm/am-diag-gmm.h"
#include "hmm/transition-model.h"
#include "transform/mllt.h"
#include "hmm/posterior.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 30 of file gmm-acc-mllt.cc.
References kaldi::ConvertPosteriorToPdfs(), AmDiagGmm::Dim(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), AmDiagGmm::GetPdf(), RandomAccessTableReader< Holder >::HasKey(), rnnlm::i, rnnlm::j, KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), AmDiagGmm::Read(), ParseOptions::Read(), TransitionModel::Read(), ParseOptions::Register(), MatrixBase< Real >::Row(), Input::Stream(), RandomAccessTableReader< Holder >::Value(), SequentialTableReader< Holder >::Value(), and kaldi::WriteKaldiObject().
{
   using namespace kaldi;
   try {
     const char *usage =
         "Accumulate MLLT (global STC) statistics\n"
         "Usage:  gmm-acc-mllt [options] <model-in> <feature-rspecifier> <posteriors-rspecifier> <stats-out>\n"
         "e.g.: \n"
         " gmm-acc-mllt 1.mdl scp:train.scp ark:1.post 1.macc\n";
     ParseOptions po(usage);
     bool binary = true;
     BaseFloat rand_prune = 0.25;
     po.Register("binary", &binary, "Write output in binary mode");
     po.Register("rand-prune", &rand_prune, "Randomized pruning parameter to speed up "
                 "accumulation (larger -> more pruning.  May exceed one).");
     po.Read(argc, argv);
     if (po.NumArgs() != 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_filename = po.GetArg(1),
         feature_rspecifier = po.GetArg(2),
         posteriors_rspecifier = po.GetArg(3),
         accs_wxfilename = po.GetArg(4);
     using namespace kaldi;
     typedef kaldi::int32 int32;
     AmDiagGmm am_gmm;
     TransitionModel trans_model;
     {
       bool binary;
       Input ki(model_filename, &binary);
       trans_model.Read(ki.Stream(), binary);
       am_gmm.Read(ki.Stream(), binary);
     }
     MlltAccs mllt_accs(am_gmm.Dim(), rand_prune);
     double tot_like = 0.0;
     double tot_t = 0.0;
     SequentialBaseFloatMatrixReader feature_reader(feature_rspecifier);
     RandomAccessPosteriorReader posteriors_reader(posteriors_rspecifier);
     int32 num_done = 0, num_no_posterior = 0, num_other_error = 0;
     for (; !feature_reader.Done(); feature_reader.Next()) {
       std::string key = feature_reader.Key();
       if (!posteriors_reader.HasKey(key)) {
         num_no_posterior++;
       } else {
         const Matrix<BaseFloat> &mat = feature_reader.Value();
         const Posterior &posterior = posteriors_reader.Value(key);
         if (static_cast<int32>(posterior.size()) != mat.NumRows()) {
           KALDI_WARN << "Posterior vector has wrong size "<< (posterior.size()) << " vs. "<< (mat.NumRows());
           num_other_error++;
           continue;
         }
         num_done++;
         BaseFloat tot_like_this_file = 0.0, tot_weight = 0.0;
         Posterior pdf_posterior;
         ConvertPosteriorToPdfs(trans_model, posterior, &pdf_posterior);
         for (size_t i = 0; i < posterior.size(); i++) {
           for (size_t j = 0; j < pdf_posterior[i].size(); j++) {
             int32 pdf_id = pdf_posterior[i][j].first;
             BaseFloat weight = pdf_posterior[i][j].second;
             tot_like_this_file += mllt_accs.AccumulateFromGmm(am_gmm.GetPdf(pdf_id),
                                                               mat.Row(i),
                                                               weight) * weight;
             tot_weight += weight;
           }
         }
         KALDI_LOG << "Average like for this file is "
                   << (tot_like_this_file/tot_weight) << " over "
                   << tot_weight << " frames.";
         tot_like += tot_like_this_file;
         tot_t += tot_weight;
         if (num_done % 10 == 0)
           KALDI_LOG << "Avg like per frame so far is "
                     << (tot_like/tot_t);
       }
     }
     KALDI_LOG << "Done " << num_done << " files, " << num_no_posterior
               << " with no posteriors, " << num_other_error
               << " with other errors.";
     KALDI_LOG << "Overall avg like per frame (Gaussian only) = "
               << (tot_like/tot_t) << " over " << tot_t << " frames.";
     WriteKaldiObject(mllt_accs, accs_wxfilename, binary);
     KALDI_LOG << "Written accs.";
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }