Kaldi: gmmbin/gmm-sum-accs.cc File Reference
gmm-sum-accs.cc File Reference
#include "util/common-utils.h"
#include "gmm/mle-am-diag-gmm.h"
#include "hmm/transition-model.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 25 of file gmm-sum-accs.cc.
References ParseOptions::GetArg(), rnnlm::i, KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), AccumAmDiagGmm::Read(), ParseOptions::Read(), Vector< Real >::Read(), ParseOptions::Register(), Output::Stream(), Input::Stream(), AccumAmDiagGmm::TotCount(), AccumAmDiagGmm::TotLogLike(), AccumAmDiagGmm::TotStatsCount(), AccumAmDiagGmm::Write(), and VectorBase< Real >::Write().
{
   try {
     typedef kaldi::int32 int32;
     const char *usage =
         "Sum multiple accumulated stats files for GMM training.\n"
         "Usage: gmm-sum-accs [options] <stats-out> <stats-in1> <stats-in2> ...\n"
         "E.g.: gmm-sum-accs 1.acc 1.1.acc 1.2.acc\n";
     bool binary = true;
     kaldi::ParseOptions po(usage);
     po.Register("binary", &binary, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() < 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string stats_out_filename = po.GetArg(1);
     kaldi::Vector<double> transition_accs;
     kaldi::AccumAmDiagGmm gmm_accs;
     int num_accs = po.NumArgs() - 1;
     for (int i = 2, max = po.NumArgs(); i <= max; i++) {
       std::string stats_in_filename = po.GetArg(i);
       bool binary_read;
       kaldi::Input ki(stats_in_filename, &binary_read);
       transition_accs.Read(ki.Stream(), binary_read, true /*add read values*/);
       gmm_accs.Read(ki.Stream(), binary_read, true /*add read values*/);
     }
     // Write out the accs
     {
       kaldi::Output ko(stats_out_filename, binary);
       transition_accs.Write(ko.Stream(), binary);
       gmm_accs.Write(ko.Stream(), binary);
     }
     KALDI_LOG << "Summed " << num_accs << " stats, total count "
               << gmm_accs.TotCount() << ", avg like/frame "
               << (gmm_accs.TotLogLike() / gmm_accs.TotCount());
     KALDI_LOG << "Total count of stats is " << gmm_accs.TotStatsCount();
     KALDI_LOG << "Written stats to " << stats_out_filename;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }