Kaldi: gmmbin/gmm-init-biphone.cc File Reference
gmm-init-biphone.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "gmm/am-diag-gmm.h"
#include "tree/event-map.h"
#include "hmm/hmm-topology.h"
#include "hmm/transition-model.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void ReadSharedPhonesList (std::string rxfilename, std::vector< std::vector< int32 > > *list_out)
EventMap * GetFullBiphoneStubMap (const std::vector< std::vector< int32 > > &phone_sets, const std::vector< int32 > &phone2num_pdf_classes, const std::vector< bool > &share_roots)
ContextDependency * BiphoneContextDependencyFull (const std::vector< std::vector< int32 > > phone_sets, const std::vector< int32 > phone2num_pdf_classes)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 137 of file gmm-init-biphone.cc.
References AmDiagGmm::AddPdf(), kaldi::BiphoneContextDependencyFull(), DiagGmm::ComputeGconsts(), kaldi::ConvertStringToInteger(), ParseOptions::GetArg(), HmmTopology::GetPhones(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, ParseOptions::NumArgs(), HmmTopology::NumPdfClasses(), ContextDependency::NumPdfs(), ParseOptions::PrintUsage(), ParseOptions::Read(), HmmTopology::Read(), kaldi::ReadSharedPhonesList(), ParseOptions::Register(), DiagGmm::Resize(), MatrixBase< Real >::Row(), VectorBase< Real >::Set(), DiagGmm::SetInvVarsAndMeans(), DiagGmm::SetWeights(), Output::Stream(), Input::Stream(), AmDiagGmm::Write(), ContextDependency::Write(), and TransitionModel::Write().
{
   try {
     using namespace kaldi;
     using kaldi::int32;
     const char *usage =
         "Initialize a biphone context-dependency tree with all the\n"
         "leaves (i.e. a full tree). Intended for end-to-end tree-free models.\n"
         "Usage:  gmm-init-biphone <topology-in> <dim> <model-out> <tree-out> \n"
         "e.g.: \n"
         " gmm-init-biphone topo 39 bi.mdl bi.tree\n";
     bool binary = true;
     std::string shared_phones_rxfilename;
     ParseOptions po(usage);
     po.Register("binary", &binary, "Write output in binary mode");
     po.Register("shared-phones", &shared_phones_rxfilename,
                 "rxfilename containing, on each line, a list of phones "
                 "whose pdfs should be shared.");
     po.Read(argc, argv);
     if (po.NumArgs() != 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string topo_filename = po.GetArg(1);
     int dim = 0;
     if (!ConvertStringToInteger(po.GetArg(2), &dim) || dim <= 0 || dim > 10000)
       KALDI_ERR << "Bad dimension:" << po.GetArg(2)
                 << ". It should be a positive integer.";
     std::string model_filename = po.GetArg(3);
     std::string tree_filename = po.GetArg(4);
     Vector<BaseFloat> glob_inv_var(dim);
     glob_inv_var.Set(1.0);
     Vector<BaseFloat> glob_mean(dim);
     glob_mean.Set(1.0);
     HmmTopology topo;
     bool binary_in;
     Input ki(topo_filename, &binary_in);
     topo.Read(ki.Stream(), binary_in);
     const std::vector<int32> &phones = topo.GetPhones();
     std::vector<int32> phone2num_pdf_classes(1 + phones.back());
     for (size_t i = 0; i < phones.size(); i++) {
       phone2num_pdf_classes[phones[i]] = topo.NumPdfClasses(phones[i]);
       // For now we only support 1 or 2 pdf's per phone
       KALDI_ASSERT(phone2num_pdf_classes[phones[i]] == 1 ||
                    phone2num_pdf_classes[phones[i]] == 2);
     }
     // Now the tree:
     ContextDependency *ctx_dep = NULL;
     std::vector<std::vector<int32> > shared_phones;
     if (shared_phones_rxfilename == "") {
       shared_phones.resize(phones.size());
       for (size_t i = 0; i < phones.size(); i++)
         shared_phones[i].push_back(phones[i]);
     } else {
       ReadSharedPhonesList(shared_phones_rxfilename, &shared_phones);
       // ReadSharedPhonesList crashes on error.
     }
     ctx_dep = BiphoneContextDependencyFull(shared_phones, phone2num_pdf_classes);
     int32 num_pdfs = ctx_dep->NumPdfs();
     AmDiagGmm am_gmm;
     DiagGmm gmm;
     gmm.Resize(1, dim);
     {  // Initialize the gmm.
       Matrix<BaseFloat> inv_var(1, dim);
       inv_var.Row(0).CopyFromVec(glob_inv_var);
       Matrix<BaseFloat> mu(1, dim);
       mu.Row(0).CopyFromVec(glob_mean);
       Vector<BaseFloat> weights(1);
       weights.Set(1.0);
       gmm.SetInvVarsAndMeans(inv_var, mu);
       gmm.SetWeights(weights);
       gmm.ComputeGconsts();
     }
     for (int i = 0; i < num_pdfs; i++)
       am_gmm.AddPdf(gmm);
     // Now the transition model:
     TransitionModel trans_model(*ctx_dep, topo);
     {
       Output ko(model_filename, binary);
       trans_model.Write(ko.Stream(), binary);
       am_gmm.Write(ko.Stream(), binary);
     }
     // Now write the tree.
     ctx_dep->Write(Output(tree_filename, binary).Stream(),
                    binary);
     delete ctx_dep;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }