Kaldi: gmmbin/gmm-mixup.cc File Reference
gmm-mixup.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "gmm/am-diag-gmm.h"
#include "tree/context-dep.h"
#include "hmm/transition-model.h"
#include "gmm/mle-am-diag-gmm.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 27 of file gmm-mixup.cc.
References VectorBase< Real >::Dim(), ParseOptions::GetArg(), KALDI_ERR, KALDI_LOG, AmDiagGmm::MergeByCount(), ParseOptions::NumArgs(), AmDiagGmm::NumPdfs(), ParseOptions::PrintUsage(), AmDiagGmm::Read(), ParseOptions::Read(), TransitionModel::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), AmDiagGmm::SplitByCount(), Output::Stream(), Input::Stream(), AmDiagGmm::Write(), and TransitionModel::Write().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Does GMM mixing up (and Gaussian merging)\n"
         "Usage:  gmm-mixup [options] <model-in> <state-occs-in> <model-out>\n"
         "e.g. of mixing up:\n"
         " gmm-mixup --mix-up=4000 1.mdl 1.occs 2.mdl\n"
         "e.g. of merging:\n"
         " gmm-mixup --mix-down=2000 1.mdl 1.occs 2.mdl\n";
     bool binary_write = true;
     int32 mixup = 0;
     int32 mixdown = 0;
     BaseFloat perturb_factor = 0.01;
     BaseFloat power = 0.2;
     BaseFloat min_count = 20.0;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("mix-up", &mixup, "Increase number of mixture components to "
                 "this overall target.");
     po.Register("min-count", &min_count,
                 "Minimum count enforced while mixing up.");
     po.Register("mix-down", &mixdown, "If nonzero, merge mixture components to this "
                 "target.");
     po.Register("power", &power, "If mixing up, power to allocate Gaussians to"
         " states.");
     po.Register("perturb-factor", &perturb_factor, "While mixing up, perturb "
         "means by standard deviation times this factor.");
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_in_filename = po.GetArg(1),
         occs_in_filename = po.GetArg(2),
         model_out_filename = po.GetArg(3);
     AmDiagGmm am_gmm;
     TransitionModel trans_model;
     {
       bool binary_read;
       Input ki(model_in_filename, &binary_read);
       trans_model.Read(ki.Stream(), binary_read);
       am_gmm.Read(ki.Stream(), binary_read);
     }
     if (mixup != 0 || mixdown != 0) {
       Vector<BaseFloat> occs;
       ReadKaldiObject(occs_in_filename, &occs);
       if (occs.Dim() != am_gmm.NumPdfs())
         KALDI_ERR << "Dimension of state occupancies " << occs.Dim()
                    << " does not match num-pdfs " << am_gmm.NumPdfs();
       if (mixdown != 0)
         am_gmm.MergeByCount(occs, mixdown, power, min_count);
       if (mixup != 0)
         am_gmm.SplitByCount(occs, mixup, perturb_factor,
                             power, min_count);
     }
     {
       Output ko(model_out_filename, binary_write);
       trans_model.Write(ko.Stream(), binary_write);
       am_gmm.Write(ko.Stream(), binary_write);
     }
     KALDI_LOG << "Written model to " << model_out_filename;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }