Kaldi: DiagGmm
DiagGmm
kaldi Diagonal Gaussian Mixture Models
Classes
class AmDiagGmm
struct UbmClusteringOptions
Functions
AmDiagGmm ()
~AmDiagGmm ()
void Init (const DiagGmm &proto, int32 num_pdfs)
Initializes with a single "prototype" GMM.
void AddPdf (const DiagGmm &gmm)
Adds a GMM to the model, and increments the total number of PDFs.
void CopyFromAmDiagGmm (const AmDiagGmm &other)
Copies the parameters from another model. Allocates necessary memory.
void SplitPdf (int32 idx, int32 target_components, float perturb_factor)
void SplitByCount (const Vector< BaseFloat > &state_occs, int32 target_components, float perturb_factor, BaseFloat power, BaseFloat min_count)
void MergeByCount (const Vector< BaseFloat > &state_occs, int32 target_components, BaseFloat power, BaseFloat min_count)
int32 ComputeGconsts ()
Sets the gconsts for all the PDFs.
BaseFloat LogLikelihood (const int32 pdf_index, const VectorBase< BaseFloat > &data) const
void Read (std::istream &in_stream, bool binary)
void Write (std::ostream &out_stream, bool binary) const
int32 Dim () const
int32 NumPdfs () const
int32 NumGauss () const
int32 NumGaussInPdf (int32 pdf_index) const
DiagGmm & GetPdf (int32 pdf_index)
Accessors.
const DiagGmm & GetPdf (int32 pdf_index) const
void GetGaussianMean (int32 pdf_index, int32 gauss, VectorBase< BaseFloat > *out) const
void GetGaussianVariance (int32 pdf_index, int32 gauss, VectorBase< BaseFloat > *out) const
void SetGaussianMean (int32 pdf_index, int32 gauss_index, const VectorBase< BaseFloat > &in)
Mutators.
void RemovePdf (int32 pdf_index)
KALDI_DISALLOW_COPY_AND_ASSIGN (AmDiagGmm)
UbmClusteringOptions ()
UbmClusteringOptions (int32 ncomp, BaseFloat red, int32 interm_gauss, BaseFloat vfloor, int32 max_am_gauss)
void Register (OptionsItf *opts)
void Check ()
void ClusterGaussiansToUbm (const AmDiagGmm &am, const Vector< BaseFloat > &state_occs, UbmClusteringOptions opts, DiagGmm *ubm_out)
Clusters the Gaussians in an acoustic model to a single GMM with specified number of components.
Variables
std::vector< DiagGmm * > densities_
int32 ubm_num_gauss
BaseFloat reduce_state_factor
int32 intermediate_num_gauss
BaseFloat cluster_varfloor
int32 max_am_gauss
Detailed Description
kaldi Diagonal Gaussian Mixture Models
Function Documentation
AddPdf()
void AddPdf (const DiagGmm & gmm)
Adds a GMM to the model, and increments the total number of PDFs.
Definition at line 57 of file am-diag-gmm.cc.
References CopyFromDiagGmm(), AmDiagGmm::densities_, Dim(), AmDiagGmm::Dim(), and KALDI_ASSERT.
Referenced by AmDiagGmm::AmDiagGmm(), kaldi::InitAmGmm(), kaldi::InitAmGmmFromOld(), main(), UnitTestAmDiagGmm(), UnitTestMleAmDiagGmm(), UnitTestRegressionTree(), and kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   if (densities_.size() != 0)  // not the first gmm
     KALDI_ASSERT(gmm.Dim() == this->Dim());
   DiagGmm *gmm_ptr = new DiagGmm();
   gmm_ptr->CopyFromDiagGmm(gmm);
   densities_.push_back(gmm_ptr);
 }
AmDiagGmm()
AmDiagGmm () inline
Definition at line 38 of file am-diag-gmm.h.
References AmDiagGmm::AddPdf(), AmDiagGmm::ComputeGconsts(), AmDiagGmm::CopyFromAmDiagGmm(), AmDiagGmm::Init(), AmDiagGmm::LogLikelihood(), AmDiagGmm::MergeByCount(), AmDiagGmm::Read(), AmDiagGmm::SplitByCount(), AmDiagGmm::SplitPdf(), AmDiagGmm::Write(), and AmDiagGmm::~AmDiagGmm().
 {}
Check()
void Check ()
Definition at line 178 of file am-diag-gmm.cc.
References KALDI_ERR.
Referenced by kaldi::ClusterGaussiansToUbm(), and main().
{
   if (ubm_num_gauss > intermediate_num_gauss)
     KALDI_ERR << "Invalid parameters: --ubm-num_gauss=" << ubm_num_gauss
               << " > --intermediate-num_gauss=" << intermediate_num_gauss;
   if (ubm_num_gauss > max_am_gauss)
     KALDI_ERR << "Invalid parameters: --ubm-num_gauss=" << ubm_num_gauss
               << " > --max-am-gauss=" << max_am_gauss;
   if (ubm_num_gauss <= 0)
     KALDI_ERR << "Invalid parameters: --ubm-num_gauss=" << ubm_num_gauss;
   if (cluster_varfloor <= 0)
     KALDI_ERR << "Invalid parameters: --cluster-varfloor="
               << cluster_varfloor;
   if (reduce_state_factor <= 0 || reduce_state_factor > 1)
     KALDI_ERR << "Invalid parameters: --reduce-state-factor="
               << reduce_state_factor;
 }
ClusterGaussiansToUbm()
void ClusterGaussiansToUbm (const AmDiagGmm & am, const Vector< BaseFloat > & state_occs, UbmClusteringOptions opts, DiagGmm * ubm_out)
Clusters the Gaussians in an acoustic model to a single GMM with specified number of components.
First the each state is mixed-down to a single Gaussian, then the states are clustered by clustering these Gaussians in a bottom-up fashion. Number of clusters is determined by reduce_state_factor. The Gaussians for each cluster of states are then merged based on the least likelihood reduction till there are intermediate_numcomp Gaussians, which are then merged into ubm_num_gauss Gaussians. This is the UBM initialization algorithm described in section 2.1 of Povey, et al., "The subspace Gaussian mixture model - A structured model for speech recognition", In Computer Speech and Language, April 2011.
Definition at line 195 of file am-diag-gmm.cc.
References VectorBase< Real >::AddVec2(), UbmClusteringOptions::Check(), UbmClusteringOptions::cluster_varfloor, kaldi::ClusterBottomUp(), kaldi::ClusterBottomUpCompartmentalized(), AmDiagGmm::CopyFromAmDiagGmm(), CopyFromDiagGmm(), VectorBase< Real >::CopyFromVec(), MatrixBase< Real >::CopyRowFromVec(), GaussClusterable::count(), kaldi::DeletePointers(), AmDiagGmm::Dim(), GetComponentMean(), GetComponentVariance(), AmDiagGmm::GetGaussianMean(), AmDiagGmm::GetGaussianVariance(), AmDiagGmm::GetPdf(), rnnlm::i, UbmClusteringOptions::intermediate_num_gauss, MatrixBase< Real >::InvertElements(), KALDI_ASSERT, KALDI_LOG, KALDI_VLOG, KALDI_WARN, UbmClusteringOptions::max_am_gauss, Merge(), AmDiagGmm::MergeByCount(), NumGauss(), AmDiagGmm::NumGauss(), AmDiagGmm::NumPdfs(), UbmClusteringOptions::reduce_state_factor, Resize(), MatrixBase< Real >::Row(), VectorBase< Real >::Scale(), SetInvVarsAndMeans(), SetWeights(), VectorBase< Real >::Sum(), UbmClusteringOptions::ubm_num_gauss, weights(), GaussClusterable::x2_stats(), and GaussClusterable::x_stats().
Referenced by main(), UbmClusteringOptions::Register(), and TestClustering().
{
   opts.Check();  // Make sure the various # of Gaussians make sense.
   if (am.NumGauss() > opts.max_am_gauss) {
     KALDI_LOG << "ClusterGaussiansToUbm: first reducing num-gauss from " << am.NumGauss()
               << " to " << opts.max_am_gauss;
     AmDiagGmm tmp_am;
     tmp_am.CopyFromAmDiagGmm(am);
     BaseFloat power = 1.0, min_count = 1.0; // Make the power 1, which I feel
     // is appropriate to the way we're doing the overall clustering procedure.
     tmp_am.MergeByCount(state_occs, opts.max_am_gauss, power, min_count);
     if (tmp_am.NumGauss() > opts.max_am_gauss) {
       KALDI_LOG << "Clustered down to " << tmp_am.NumGauss()
                 << "; will not cluster further";
       opts.max_am_gauss = tmp_am.NumGauss();
     }
     ClusterGaussiansToUbm(tmp_am, state_occs, opts, ubm_out);
     return;
   }
   int32 num_pdfs = static_cast<int32>(am.NumPdfs()),
       dim = am.Dim(),
       num_clust_states = static_cast<int32>(opts.reduce_state_factor*num_pdfs);
   Vector<BaseFloat> tmp_mean(dim);
   Vector<BaseFloat> tmp_var(dim);
   DiagGmm tmp_gmm;
   vector<Clusterable*> states;
   states.reserve(num_pdfs);  // NOT resize(); uses push_back.
   // Replace the GMM for each state with a single Gaussian.
   KALDI_VLOG(1) << "Merging densities to 1 Gaussian per state.";
   for (int32 pdf_index = 0; pdf_index < num_pdfs; pdf_index++) {
     KALDI_VLOG(3) << "Merging Gausians for state : " << pdf_index;
     tmp_gmm.CopyFromDiagGmm(am.GetPdf(pdf_index));
     tmp_gmm.Merge(1);
     tmp_gmm.GetComponentMean(0, &tmp_mean);
     tmp_gmm.GetComponentVariance(0, &tmp_var);
     tmp_var.AddVec2(1.0, tmp_mean);  // make it x^2 stats.
     // It may cause problems downstream if we add states with zero weights (see
     // KALDI_ASSERT(weight > 0) below), so we put in a very small floor.
     // These states with tiny weights will later get merged into other states.
     BaseFloat this_weight = 1.0e-10 + state_occs(pdf_index);
     tmp_mean.Scale(this_weight);
     tmp_var.Scale(this_weight);
     states.push_back(new GaussClusterable(tmp_mean, tmp_var,
                           opts.cluster_varfloor, this_weight));
   }
   // Bottom-up clustering of the Gaussians corresponding to each state, which
   // gives a partial clustering of states in the 'state_clusters' vector.
   vector<int32> state_clusters;
   KALDI_VLOG(1) << "Creating " << num_clust_states << " clusters of states.";
   ClusterBottomUp(states, std::numeric_limits<BaseFloat>::max(), num_clust_states,
                   NULL /*actual clusters not needed*/,
                   &state_clusters /*get the cluster assignments*/);
   DeletePointers(&states);
   // For each cluster of states, create a pool of all the Gaussians in those
   // states, weighted by the state occupancies. This is done so that initially
   // only the Gaussians corresponding to "similar" states (similarity as
   // determined by the previous clustering) are merged.
   vector< vector<Clusterable*> > state_clust_gauss;
   state_clust_gauss.resize(num_clust_states);
   for (int32 pdf_index = 0; pdf_index < num_pdfs; pdf_index++) {
     int32 current_cluster = state_clusters[pdf_index];
     for (int32 num_gauss = am.GetPdf(pdf_index).NumGauss(),
         gauss_index = 0; gauss_index < num_gauss; ++gauss_index) {
       am.GetGaussianMean(pdf_index, gauss_index, &tmp_mean);
       am.GetGaussianVariance(pdf_index, gauss_index, &tmp_var);
       tmp_var.AddVec2(1.0, tmp_mean);  // make it x^2 stats.
       // adding 1.0e-10 to the weight will prevent problems later on, see
       // the line KALDI_ASSERT(weight > 0.0).
       BaseFloat this_weight =  (1.0e-10 + state_occs(pdf_index)) *
           (am.GetPdf(pdf_index).weights())(gauss_index);
       tmp_mean.Scale(this_weight);
       tmp_var.Scale(this_weight);
       state_clust_gauss[current_cluster].push_back(new GaussClusterable(
           tmp_mean, tmp_var, opts.cluster_varfloor, this_weight));
     }
   }
   // This is an unlikely operating scenario, no need to handle this in a more
   // optimized fashion.
   if (opts.intermediate_num_gauss > am.NumGauss()) {
     KALDI_WARN << "Intermediate num_gauss " << opts.intermediate_num_gauss
                << " is more than num-gauss " << am.NumGauss()
                << ", reducing it to " << am.NumGauss();
     opts.intermediate_num_gauss = am.NumGauss();
   }
   // The compartmentalized clusterer used below does not merge compartments.
   if (opts.intermediate_num_gauss < num_clust_states) {
     KALDI_WARN << "Intermediate num_gauss " << opts.intermediate_num_gauss
                << " is less than # of preclustered states " << num_clust_states
                << ", increasing it to " << num_clust_states;
     opts.intermediate_num_gauss = num_clust_states;
   }
   KALDI_VLOG(1) << "Merging from " << am.NumGauss() << " Gaussians in the "
                 << "acoustic model, down to " << opts.intermediate_num_gauss
                 << " Gaussians.";
   vector< vector<Clusterable*> > gauss_clusters_out;
   ClusterBottomUpCompartmentalized(state_clust_gauss, std::numeric_limits<BaseFloat>::max(),
                                    opts.intermediate_num_gauss,
                                    &gauss_clusters_out, NULL);
   for (int32 clust_index = 0; clust_index < num_clust_states; clust_index++)
     DeletePointers(&state_clust_gauss[clust_index]);
   // Next, put the remaining clustered Gaussians into a single GMM.
   KALDI_VLOG(1) << "Putting " << opts.intermediate_num_gauss << " Gaussians "
                 << "into a single GMM for final merge step.";
   Matrix<BaseFloat> tmp_means(opts.intermediate_num_gauss, dim);
   Matrix<BaseFloat> tmp_vars(opts.intermediate_num_gauss, dim);
   Vector<BaseFloat> tmp_weights(opts.intermediate_num_gauss);
   Vector<BaseFloat> tmp_vec(dim);
   int32 gauss_index = 0;
   for (int32 clust_index = 0; clust_index < num_clust_states; clust_index++) {
     for (int32 i = gauss_clusters_out[clust_index].size()-1; i >=0; --i) {
       GaussClusterable *this_cluster = static_cast<GaussClusterable*>(
           gauss_clusters_out[clust_index][i]);
       BaseFloat weight = this_cluster->count();
       KALDI_ASSERT(weight > 0.0);
       tmp_weights(gauss_index) = weight;
       tmp_vec.CopyFromVec(this_cluster->x_stats());
       tmp_vec.Scale(1.0 / weight);
       tmp_means.CopyRowFromVec(tmp_vec, gauss_index);
       tmp_vec.CopyFromVec(this_cluster->x2_stats());
       tmp_vec.Scale(1.0 / weight);
       tmp_vec.AddVec2(-1.0, tmp_means.Row(gauss_index));  // x^2 stats to var.
       tmp_vars.CopyRowFromVec(tmp_vec, gauss_index);
       gauss_index++;
     }
     DeletePointers(&(gauss_clusters_out[clust_index]));
   }
   tmp_gmm.Resize(opts.intermediate_num_gauss, dim);
   tmp_weights.Scale(1.0/tmp_weights.Sum());
   tmp_gmm.SetWeights(tmp_weights);
   tmp_vars.InvertElements();  // need inverse vars...
   tmp_gmm.SetInvVarsAndMeans(tmp_vars, tmp_means);
   // Finally, cluster to the desired number of Gaussians in the UBM.
   if (opts.ubm_num_gauss < tmp_gmm.NumGauss()) {
     tmp_gmm.Merge(opts.ubm_num_gauss);
     KALDI_VLOG(1) << "Merged down to " << tmp_gmm.NumGauss() << " Gaussians.";
   } else {
     KALDI_WARN << "Not merging Gaussians since " << opts.ubm_num_gauss
                << " < " << tmp_gmm.NumGauss();
   }
   ubm_out->CopyFromDiagGmm(tmp_gmm);
 }
ComputeGconsts()
int32 ComputeGconsts ()
Sets the gconsts for all the PDFs.
Returns the total number of Gaussians over all PDFs that are "invalid" e.g. due to zero weights or variances.
Definition at line 90 of file am-diag-gmm.cc.
References AmDiagGmm::densities_, and KALDI_WARN.
Referenced by AmDiagGmm::AmDiagGmm(), kaldi::DoRescalingUpdate(), and RegtreeMllrDiagGmm::TransformModel().
{
   int32 num_bad = 0;
   for (std::vector<DiagGmm*>::iterator itr = densities_.begin(),
       end = densities_.end(); itr != end; ++itr) {
     num_bad += (*itr)->ComputeGconsts();
   }
   if (num_bad > 0)
     KALDI_WARN << "Found " << num_bad << " Gaussian components.";
   return num_bad;
 }
CopyFromAmDiagGmm()
void CopyFromAmDiagGmm (const AmDiagGmm & other)
Copies the parameters from another model. Allocates necessary memory.
Definition at line 79 of file am-diag-gmm.cc.
References kaldi::DeletePointers(), AmDiagGmm::densities_, rnnlm::i, and AmDiagGmm::NumPdfs().
Referenced by AmDiagGmm::AmDiagGmm(), kaldi::ClusterGaussiansToUbm(), main(), TestAmDiagGmmAccsIO(), TestMllrAccsIO(), TestSplitStates(), and TestXformMean().
{
   if (densities_.size() != 0) {
     DeletePointers(&densities_);
   }
   densities_.resize(other.NumPdfs(), NULL);
   for (int32 i = 0, end = densities_.size(); i < end; i++) {
     densities_[i] = new DiagGmm();
     densities_[i]->CopyFromDiagGmm(*other.densities_[i]);
   }
 }
Dim()
int32 Dim () const inline
Definition at line 79 of file am-diag-gmm.h.
References AmDiagGmm::densities_.
Referenced by AmDiagGmm::AddPdf(), RegressionTree::BuildTree(), kaldi::ClusterGaussiansToUbm(), BasisFmllrEstimate::ComputeAmDiagPrecond(), DecodableAmDiagGmmRegtreeMllr::GetXformedMeanInvVars(), main(), kaldi::MapAmDiagGmmUpdate(), kaldi::MleAmDiagGmmUpdate(), TestAmDiagGmmIO(), TestMllrAccsIO(), TestSplitStates(), TestXformMean(), and AmDiagGmm::Write().
                     {
     return (densities_.size() > 0)? densities_[0]->Dim() : 0;
   }
GetGaussianMean()
void GetGaussianMean (int32 pdf_index, int32 gauss, VectorBase< BaseFloat > * out) const inline
Definition at line 131 of file am-diag-gmm.h.
References AmDiagGmm::densities_, and KALDI_ASSERT.
Referenced by RegressionTree::BuildTree(), kaldi::ClusterGaussiansToUbm(), RegtreeMllrDiagGmm::GetTransformedMeans(), AmDiagGmm::NumPdfs(), and RegtreeMllrDiagGmm::TransformModel().
{
   KALDI_ASSERT((static_cast<size_t>(pdf_index) < densities_.size())
       && (densities_[pdf_index] != NULL));
   densities_[pdf_index]->GetComponentMean(gauss, out);
 }
GetGaussianVariance()
void GetGaussianVariance (int32 pdf_index, int32 gauss, VectorBase< BaseFloat > * out) const inline
Definition at line 138 of file am-diag-gmm.h.
References AmDiagGmm::densities_, and KALDI_ASSERT.
Referenced by RegressionTree::BuildTree(), kaldi::ClusterGaussiansToUbm(), and AmDiagGmm::NumPdfs().
{
   KALDI_ASSERT((static_cast<size_t>(pdf_index) < densities_.size())
                && (densities_[pdf_index] != NULL));
   densities_[pdf_index]->GetComponentVariance(gauss, out);
 }
GetPdf() [1/2]
DiagGmm & GetPdf (int32 pdf_index) inline
Accessors.
Definition at line 119 of file am-diag-gmm.h.
References AmDiagGmm::densities_, and KALDI_ASSERT.
Referenced by kaldi::AccStatsForUtterance(), AccumAmDiagGmm::AccumulateForGaussian(), RegtreeMllrDiagGmmAccs::AccumulateForGaussian(), RegtreeFmllrDiagGmmAccs::AccumulateForGaussian(), AccumAmDiagGmm::AccumulateForGmm(), RegtreeMllrDiagGmmAccs::AccumulateForGmm(), RegtreeFmllrDiagGmmAccs::AccumulateForGmm(), AccumAmDiagGmm::AccumulateForGmmTwofeats(), kaldi::AccumulateForUtterance(), RegressionTree::BuildTree(), kaldi::ClusterGaussiansToUbm(), BasisFmllrEstimate::ComputeAmDiagPrecond(), kaldi::ComputeAmGmmFeatureDeriv(), kaldi::DoRescalingUpdate(), kaldi::GetStatsDerivative(), RegtreeMllrDiagGmm::GetTransformedMeans(), DecodableAmDiagGmmRegtreeMllr::GetXformedMeanInvVars(), AccumAmDiagGmm::Init(), kaldi::InitAmGmmFromOld(), kaldi::IsmoothStatsAmDiagGmmFromModel(), DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), main(), kaldi::MapAmDiagGmmUpdate(), kaldi::MleAmDiagGmmUpdate(), AmDiagGmm::NumPdfs(), kaldi::ResizeModel(), TestXformMean(), kaldi::UpdateEbwAmDiagGmm(), and kaldi::UpdateEbwWeightsAmDiagGmm().
{
   KALDI_ASSERT((static_cast<size_t>(pdf_index) < densities_.size())
                && (densities_[pdf_index] != NULL));
   return *(densities_[pdf_index]);
 }
GetPdf() [2/2]
const DiagGmm & GetPdf (int32 pdf_index) const inline
Definition at line 125 of file am-diag-gmm.h.
References AmDiagGmm::densities_, and KALDI_ASSERT.
{
   KALDI_ASSERT((static_cast<size_t>(pdf_index) < densities_.size())
                && (densities_[pdf_index] != NULL));
   return *(densities_[pdf_index]);
 }
Init()
void Init (const DiagGmm & proto, int32 num_pdfs)
Initializes with a single "prototype" GMM.
Definition at line 38 of file am-diag-gmm.cc.
References kaldi::DeletePointers(), AmDiagGmm::densities_, and KALDI_WARN.
Referenced by AmDiagGmm::AmDiagGmm(), and UnitTestRegtreeMllrDiagGmm().
{
   if (densities_.size() != 0) {
     KALDI_WARN << "Init() called on a non-empty object. Contents will be "
         "overwritten";
     DeletePointers(&densities_);
   }
   if (num_pdfs == 0) {
     KALDI_WARN << "Init() called with number of pdfs = 0. Will do nothing.";
     return;
   }
   densities_.resize(num_pdfs, NULL);
   for (vector<DiagGmm*>::iterator itr = densities_.begin(),
       end = densities_.end(); itr != end; ++itr) {
     *itr = new DiagGmm();
     (*itr)->CopyFromDiagGmm(proto);
   }
 }
KALDI_DISALLOW_COPY_AND_ASSIGN()
KALDI_DISALLOW_COPY_AND_ASSIGN (AmDiagGmm) private
LogLikelihood()
BaseFloat LogLikelihood (const int32 pdf_index, const VectorBase< BaseFloat > & data) const inline
Definition at line 108 of file am-diag-gmm.h.
References AmDiagGmm::densities_.
Referenced by AmDiagGmm::AmDiagGmm(), main(), TestAmDiagGmmAccsIO(), TestAmDiagGmmIO(), TestMllrAccsIO(), TestSplitStates(), and TestXformMean().
{
   return densities_[pdf_index]->LogLikelihood(data);
 }
MergeByCount()
void MergeByCount (const Vector< BaseFloat > & state_occs, int32 target_components, BaseFloat power, BaseFloat min_count)
Definition at line 125 of file am-diag-gmm.cc.
References AmDiagGmm::densities_, kaldi::GetSplitTargets(), rnnlm::i, KALDI_LOG, AmDiagGmm::NumGauss(), and AmDiagGmm::NumPdfs().
Referenced by AmDiagGmm::AmDiagGmm(), kaldi::ClusterGaussiansToUbm(), and main().
{
   int32 gauss_at_start = NumGauss();
   std::vector<int32> targets;
   GetSplitTargets(state_occs, target_components,
                   power, min_count, &targets);
   for (int32 i = 0; i < NumPdfs(); i++) {
     if (targets[i] == 0) targets[i] = 1;  // can't merge below 1.
     if (densities_[i]->NumGauss() > targets[i])
       densities_[i]->Merge(targets[i]);
   }
   KALDI_LOG << "Merged " << NumPdfs() << " states with target = "
             << target_components << ", power = " << power
             << " and min_count = " << min_count
             << ", merged from " << gauss_at_start << " to "
             << NumGauss();
 }
NumGauss()
int32 NumGauss () const
Definition at line 72 of file am-diag-gmm.cc.
References AmDiagGmm::densities_, and rnnlm::i.
Referenced by RegressionTree::BuildTree(), kaldi::ClusterGaussiansToUbm(), main(), RegressionTree::MakeGauss2Bclass(), AmDiagGmm::MergeByCount(), kaldi::MleAmDiagGmmUpdate(), AmDiagGmm::NumPdfs(), RegressionTree::Read(), AmDiagGmm::SplitByCount(), TestClustering(), and TestSplitStates().
{
   int32 ans = 0;
   for (size_t i = 0; i < densities_.size(); i++)
     ans += densities_[i]->NumGauss();
   return ans;
 }
NumGaussInPdf()
int32 NumGaussInPdf (int32 pdf_index) const inline
Definition at line 113 of file am-diag-gmm.h.
References AmDiagGmm::densities_, and KALDI_ASSERT.
Referenced by RegressionTree::MakeGauss2Bclass(), AmDiagGmm::NumPdfs(), and kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   KALDI_ASSERT((static_cast<size_t>(pdf_index) < densities_.size())
       && (densities_[pdf_index] != NULL));
   return densities_[pdf_index]->NumGauss();
 }
NumPdfs()
int32 NumPdfs () const inline
Definition at line 82 of file am-diag-gmm.h.
References AmDiagGmm::densities_, AmDiagGmm::GetGaussianMean(), AmDiagGmm::GetGaussianVariance(), AmDiagGmm::GetPdf(), AmDiagGmm::NumGauss(), AmDiagGmm::NumGaussInPdf(), and AmDiagGmm::SetGaussianMean().
Referenced by RegressionTree::BuildTree(), kaldi::ClusterGaussiansToUbm(), BasisFmllrEstimate::ComputeAmDiagPrecond(), AmDiagGmm::CopyFromAmDiagGmm(), kaldi::DoRescalingUpdate(), kaldi::GetStatsDerivative(), AccumAmDiagGmm::Init(), kaldi::InitAmGmmFromOld(), DecodableAmDiagGmmRegtreeMllr::InitCache(), kaldi::IsmoothStatsAmDiagGmmFromModel(), main(), RegressionTree::MakeGauss2Bclass(), kaldi::MapAmDiagGmmUpdate(), AmDiagGmm::MergeByCount(), kaldi::MleAmDiagGmmUpdate(), DecodableAmDiagGmmUnmapped::NumIndices(), DecodableAmDiagGmmUnmapped::ResetLogLikeCache(), kaldi::ResizeModel(), AmDiagGmm::SplitByCount(), TestAmDiagGmmAccsIO(), TestAmDiagGmmIO(), TestClustering(), TestSplitStates(), kaldi::UpdateEbwAmDiagGmm(), and kaldi::UpdateEbwWeightsAmDiagGmm().
 { return densities_.size(); }
Read()
void Read (std::istream & in_stream, bool binary)
Definition at line 147 of file am-diag-gmm.cc.
References AmDiagGmm::densities_, kaldi::ExpectToken(), rnnlm::i, KALDI_ASSERT, and kaldi::ReadBasicType().
Referenced by AmDiagGmm::AmDiagGmm(), kaldi::InitAmGmmFromOld(), main(), and TestAmDiagGmmIO().
{
   int32 num_pdfs, dim;
   ExpectToken(in_stream, binary, "<DIMENSION>");
   ReadBasicType(in_stream, binary, &dim);
   ExpectToken(in_stream, binary, "<NUMPDFS>");
   ReadBasicType(in_stream, binary, &num_pdfs);
   KALDI_ASSERT(num_pdfs > 0);
   densities_.reserve(num_pdfs);
   for (int32 i = 0; i < num_pdfs; i++) {
     densities_.push_back(new DiagGmm());
     densities_.back()->Read(in_stream, binary);
     KALDI_ASSERT(densities_.back()->Dim() == dim);
   }
 }
Register()
void Register (OptionsItf * opts) inline
Definition at line 176 of file am-diag-gmm.h.
References kaldi::ClusterGaussiansToUbm(), and OptionsItf::Register().
Referenced by main().
{
     std::string module = "UbmClusteringOptions: ";
     opts->Register("max-am-gauss", &max_am_gauss, module+
                    "We first reduce acoustic model to this max #Gauss before clustering.");
     opts->Register("ubm-num-gauss", &ubm_num_gauss, module+
                    "Number of Gaussians components in the final UBM.");
     opts->Register("ubm-numcomps", &ubm_num_gauss, module+
                    "Backward compatibility option (see ubm-num-gauss)");
     opts->Register("reduce-state-factor", &reduce_state_factor, module+
                    "Intermediate number of clustered states (as fraction of total states).");
     opts->Register("intermediate-num-gauss", &intermediate_num_gauss, module+
                    "Intermediate number of merged Gaussian components.");
     opts->Register("intermediate-numcomps", &intermediate_num_gauss, module+
                    "Backward compatibility option (see intermediate-num-gauss)");
     opts->Register("cluster-varfloor", &cluster_varfloor, module+
                    "Variance floor used in bottom-up state clustering.");
   }
RemovePdf()
void RemovePdf (int32 pdf_index) private
Definition at line 66 of file am-diag-gmm.cc.
References AmDiagGmm::densities_, and KALDI_ASSERT.
{
   KALDI_ASSERT(static_cast<size_t>(pdf_index) < densities_.size());
   delete densities_[pdf_index];
   densities_.erase(densities_.begin() + pdf_index);
 }
SetGaussianMean()
void SetGaussianMean (int32 pdf_index, int32 gauss_index, const VectorBase< BaseFloat > & in) inline
Mutators.
Definition at line 145 of file am-diag-gmm.h.
References AmDiagGmm::densities_, and KALDI_ASSERT.
Referenced by AmDiagGmm::NumPdfs(), and RegtreeMllrDiagGmm::TransformModel().
{
   KALDI_ASSERT((static_cast<size_t>(pdf_index) < densities_.size())
                && (densities_[pdf_index] != NULL));
   densities_[pdf_index]->SetComponentMean(gauss_index, in);
 }
SplitByCount()
void SplitByCount (const Vector< BaseFloat > & state_occs, int32 target_components, float perturb_factor, BaseFloat power, BaseFloat min_count)
Definition at line 102 of file am-diag-gmm.cc.
References AmDiagGmm::densities_, kaldi::GetSplitTargets(), rnnlm::i, KALDI_LOG, AmDiagGmm::NumGauss(), and AmDiagGmm::NumPdfs().
Referenced by AmDiagGmm::AmDiagGmm(), main(), and TestSplitStates().
{
   int32 gauss_at_start = NumGauss();
   std::vector<int32> targets;
   GetSplitTargets(state_occs, target_components, power,
                   min_count, &targets);
   for (int32 i = 0; i < NumPdfs(); i++) {
     if (densities_[i]->NumGauss() < targets[i])
       densities_[i]->Split(targets[i], perturb_factor);
   }
   KALDI_LOG << "Split " << NumPdfs() << " states with target = "
             << target_components << ", power = " << power
             << ", perturb_factor = " << perturb_factor
             << " and min_count = " << min_count
             << ", split #Gauss from " << gauss_at_start << " to "
             << NumGauss();
 }
SplitPdf()
void SplitPdf (int32 idx, int32 target_components, float perturb_factor) inline
Definition at line 152 of file am-diag-gmm.h.
References AmDiagGmm::densities_, and KALDI_ASSERT.
Referenced by AmDiagGmm::AmDiagGmm(), and kaldi::UnitTestRegtreeFmllrDiagGmm().
{
   KALDI_ASSERT((static_cast<size_t>(pdf_index) < densities_.size())
                && (densities_[pdf_index] != NULL));
   densities_[pdf_index]->Split(target_components, perturb_factor);
 }
UbmClusteringOptions() [1/2]
UbmClusteringOptions () inline
Definition at line 167 of file am-diag-gmm.h.
       : ubm_num_gauss(400), reduce_state_factor(0.2),
         intermediate_num_gauss(4000), cluster_varfloor(0.01),
         max_am_gauss(20000) {}
UbmClusteringOptions() [2/2]
UbmClusteringOptions (int32 ncomp, BaseFloat red, int32 interm_gauss, BaseFloat vfloor, int32 max_am_gauss) inline
Definition at line 171 of file am-diag-gmm.h.
         : ubm_num_gauss(ncomp), reduce_state_factor(red),
           intermediate_num_gauss(interm_gauss), cluster_varfloor(vfloor),
           max_am_gauss(max_am_gauss) {}
Write()
void Write (std::ostream & out_stream, bool binary) const
Definition at line 163 of file am-diag-gmm.cc.
References AmDiagGmm::densities_, AmDiagGmm::Dim(), KALDI_WARN, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by AmDiagGmm::AmDiagGmm(), main(), and TestAmDiagGmmIO().
{
   int32 dim = this->Dim();
   if (dim == 0) {
     KALDI_WARN << "Trying to write empty AmDiagGmm object.";
   }
   WriteToken(out_stream, binary, "<DIMENSION>");
   WriteBasicType(out_stream, binary, dim);
   WriteToken(out_stream, binary, "<NUMPDFS>");
   WriteBasicType(out_stream, binary, static_cast<int32>(densities_.size()));
   for (std::vector<DiagGmm*>::const_iterator it = densities_.begin(),
       end = densities_.end(); it != end; ++it) {
     (*it)->Write(out_stream, binary);
   }
 }
~AmDiagGmm()
~AmDiagGmm ()
Definition at line 34 of file am-diag-gmm.cc.
References kaldi::DeletePointers(), and AmDiagGmm::densities_.
Referenced by AmDiagGmm::AmDiagGmm().
                       {
   DeletePointers(&densities_);
 }
Variable Documentation
cluster_varfloor
BaseFloat cluster_varfloor
Definition at line 164 of file am-diag-gmm.h.
Referenced by kaldi::ClusterGaussiansToUbm().
densities_
std::vector<DiagGmm*> densities_ private
Definition at line 99 of file am-diag-gmm.h.
Referenced by AmDiagGmm::AddPdf(), AmDiagGmm::ComputeGconsts(), AmDiagGmm::CopyFromAmDiagGmm(), AmDiagGmm::Dim(), AmDiagGmm::GetGaussianMean(), AmDiagGmm::GetGaussianVariance(), AmDiagGmm::GetPdf(), AmDiagGmm::Init(), AmDiagGmm::LogLikelihood(), AmDiagGmm::MergeByCount(), AmDiagGmm::NumGauss(), AmDiagGmm::NumGaussInPdf(), AmDiagGmm::NumPdfs(), AmDiagGmm::Read(), AmDiagGmm::RemovePdf(), AmDiagGmm::SetGaussianMean(), AmDiagGmm::SplitByCount(), AmDiagGmm::SplitPdf(), AmDiagGmm::Write(), and AmDiagGmm::~AmDiagGmm().
intermediate_num_gauss
int32 intermediate_num_gauss
Definition at line 163 of file am-diag-gmm.h.
Referenced by kaldi::ClusterGaussiansToUbm().
max_am_gauss
int32 max_am_gauss
Definition at line 165 of file am-diag-gmm.h.
Referenced by kaldi::ClusterGaussiansToUbm().
reduce_state_factor
BaseFloat reduce_state_factor
Definition at line 162 of file am-diag-gmm.h.
Referenced by kaldi::ClusterGaussiansToUbm().
ubm_num_gauss
int32 ubm_num_gauss
Definition at line 161 of file am-diag-gmm.h.
Referenced by kaldi::ClusterGaussiansToUbm().