Kaldi: Classes and functions related to HMM topology and transition modeling
Classes and functions related to HMM topology and transition modeling
Modules
Classes and functions for creating FSTs from HMMs
Classes
class HmmTopology
A class for storing topology information for phones.
struct MleTransitionUpdateConfig
struct MapTransitionUpdateConfig
class TransitionModel
Functions
bool SplitToPhones (const TransitionModel &trans_model, const std::vector< int32 > &alignment, std::vector< std::vector< int32 > > *split_alignment)
SplitToPhones splits up the TransitionIds in "alignment" into their individual phones (one vector per instance of a phone).
bool ConvertAlignment (const TransitionModel &old_trans_model, const TransitionModel &new_trans_model, const ContextDependencyInterface &new_ctx_dep, const std::vector< int32 > &old_alignment, int32 subsample_factor, bool repeat_frames, bool reorder, const std::vector< int32 > *phone_map, std::vector< int32 > *new_alignment)
ConvertAlignment converts an alignment that was created using one model, to another model.
bool ConvertPhnxToProns (const std::vector< int32 > &phnx, const std::vector< int32 > &words, int32 word_start_sym, int32 word_end_sym, std::vector< std::vector< int32 > > *prons)
void GetRandomAlignmentForPhone (const ContextDependencyInterface &ctx_dep, const TransitionModel &trans_model, const std::vector< int32 > &phone_window, std::vector< int32 > *alignment)
void ChangeReorderingOfAlignment (const TransitionModel &trans_model, std::vector< int32 > *alignment)
bool GetPdfsForPhones (const TransitionModel &trans_model, const std::vector< int32 > &phones, std::vector< int32 > *pdfs)
Works out which pdfs might correspond to the given phones.
bool GetPhonesForPdfs (const TransitionModel &trans_model, const std::vector< int32 > &pdfs, std::vector< int32 > *phones)
Works out which phones might correspond to the given pdfs.
Variables
static const int32 kNoPdf = -1
A constant used in the HmmTopology class as the pdf-class kNoPdf, which is used when a HMM-state is nonemitting (has no associated PDF).
Integer mapping functions
int32 TransitionIdToPdf (int32 trans_id) const
bool ConvertFullCtxAlignment (const TransitionModel &old_trans_model, const TransitionModel &new_trans_model, const ContextDependencyInterface &new_ctx_dep, const std::vector< int32 > &tid_ali, const std::vector< std::vector< int32 > > &full_ali, std::vector< int32 > *new_tid_ali)
ConvertFullCtxAlignment converts an alignment that was created using one model, to another model.
bool GetPhoneWindows (const TransitionModel &trans_model, const std::vector< int32 > &alignment, int32 context_width, int32 central_pos, bool per_frame, std::vector< std::vector< int32 > > *phone_windows, std::vector< int32 > *phones)
GetPhoneWindows takes an alignment in terms of transition-ids and works out the phonetic context windows for a given context-width and central position.
Detailed Description
Function Documentation
ChangeReorderingOfAlignment()
void ChangeReorderingOfAlignment (const TransitionModel & trans_model, std::vector< int32 > * alignment)
Definition at line 1260 of file hmm-utils.cc.
References TransitionModel::IsSelfLoop(), kaldi::swap(), and TransitionModel::TransitionIdToTransitionState().
Referenced by kaldi::ConvertAlignmentForPhone().
{
   int32 start_pos = 0, size = alignment->size();
   while (start_pos != size) {
     int32 start_tid = (*alignment)[start_pos];
     int32 cur_tstate = trans_model.TransitionIdToTransitionState(start_tid);
     bool start_is_self_loop = trans_model.IsSelfLoop(start_tid) ? 0 : 1;
     int32 end_pos = start_pos + 1;
     // If the first instance of this transition-state was a self-loop, then eat
     // only non-self-loops of this state; if it was a non-self-loop, then eat
     // only self-loops of this state.  Imposing this condition on self-loops
     // would only actually matter in the rare circumstances that phones can
     // have length 1.
     while (end_pos != size &&
            trans_model.TransitionIdToTransitionState((*alignment)[end_pos]) ==
            cur_tstate) {
       bool this_is_self_loop = trans_model.IsSelfLoop((*alignment)[end_pos]);
       if (!this_is_self_loop) {
         if (start_is_self_loop) {
           break;  // stop before including this transition-id.
         } else {
           end_pos++;
           break;  // stop after including this transition-id.
         }
       }
       end_pos++;
     }
     std::swap((*alignment)[start_pos], (*alignment)[end_pos - 1]);
     start_pos = end_pos;
   }
 }
ConvertAlignment()
bool ConvertAlignment (const TransitionModel & old_trans_model, const TransitionModel & new_trans_model, const ContextDependencyInterface & new_ctx_dep, const std::vector< int32 > & old_alignment, int32 subsample_factor, bool repeat_frames, bool reorder, const std::vector< int32 > * phone_map, std::vector< int32 > * new_alignment)
ConvertAlignment converts an alignment that was created using one model, to another model.
Returns false if it could not be split to phones (e.g. because the alignment was partial), or because some other error happened, such as we couldn't convert the alignment because there were too few frames for the new topology.
Parameters
old_trans_model [in] The transition model that the original alignment used.
new_trans_model [in] The transition model that we want to use for the new alignment.
new_ctx_dep [in] The new tree
old_alignment [in] The alignment we want to convert
subsample_factor [in] The frame subsampling factor... normally 1, but might be > 1 if we're converting to a reduced-frame-rate system.
repeat_frames [in] Only relevant when subsample_factor != 1 If true, repeat frames of alignment by 'subsample_factor' after alignment conversion, to keep the alignment the same length as the input alignment. [note: we actually do this by interpolating 'subsample_factor' separately generated alignments, to keep the phone boundaries the same as the input where possible.]
reorder [in] True if you want the pdf-ids on the new alignment to be 'reordered'. (vs. the way they appear in the HmmTopology object)
phone_map [in] If non-NULL, map from old to new phones.
new_alignment [out] The converted alignment.
Definition at line 1013 of file hmm-utils.cc.
References kaldi::ConvertAlignmentInternal(), rnnlm::i, and KALDI_ASSERT.
Referenced by main(), and kaldi::TestConvertAlignment().
{
   if (!repeat_frames || subsample_factor == 1) {
     return ConvertAlignmentInternal(old_trans_model,
                                     new_trans_model,
                                     new_ctx_dep,
                                     old_alignment,
                                     subsample_factor - 1,
                                     subsample_factor,
                                     new_is_reordered,
                                     phone_map,
                                     new_alignment);
    // The value "subsample_factor - 1" for conversion_shift above ensures the
    // alignments have the same length as the output of 'subsample-feats'
   } else {
     std::vector<std::vector<int32> > shifted_alignments(subsample_factor);
     for (int32 conversion_shift = subsample_factor - 1;
          conversion_shift >= 0; conversion_shift--) {
       if (!ConvertAlignmentInternal(old_trans_model,
                                     new_trans_model,
                                     new_ctx_dep,
                                     old_alignment,
                                     conversion_shift,
                                     subsample_factor,
                                     new_is_reordered,
                                     phone_map,
                                     &shifted_alignments[conversion_shift]))
         return false;
     }
     KALDI_ASSERT(new_alignment != NULL);
     new_alignment->clear();
     new_alignment->reserve(old_alignment.size());
     int32 max_shifted_ali_length = (old_alignment.size() / subsample_factor)
                                    + (old_alignment.size() % subsample_factor);
     for (int32 i = 0; i < max_shifted_ali_length; i++)
       for (int32 conversion_shift = subsample_factor - 1;
            conversion_shift >= 0; conversion_shift--)
         if (i < static_cast<int32>(shifted_alignments[conversion_shift].size()))
           new_alignment->push_back(shifted_alignments[conversion_shift][i]);
   }
   KALDI_ASSERT(new_alignment->size() == old_alignment.size());
   return true;
 }
ConvertFullCtxAlignment()
bool ConvertFullCtxAlignment (const TransitionModel & old_trans_model, const TransitionModel & new_trans_model, const ContextDependencyInterface & new_ctx_dep, const std::vector< int32 > & tid_ali, const std::vector< std::vector< int32 > > & full_ali, std::vector< int32 > * new_tid_ali)
ConvertFullCtxAlignment converts an alignment that was created using one model, to another model.
They must use a compatible topology (so we know the state alignments of the new model). It returns false if it could not be split to phones (probably because the alignment was partial), but for other kinds of error that are more likely a coding error, it will throw an exception.
Definition at line 94 of file hmm-utils-idlak.cc.
References ContextDependencyInterface::CentralPosition(), ContextDependencyInterface::Compute(), ContextDependencyInterface::ContextWidth(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, TransitionModel::PairToTransitionId(), TransitionModel::TransitionIdToHmmState(), TransitionModel::TransitionIdToPhone(), TransitionModel::TransitionIdToTransitionIndex(), TransitionModel::TransitionIdToTransitionState(), TransitionModel::TransitionStateToForwardPdfClass(), TransitionModel::TransitionStateToSelfLoopPdfClass(), TransitionModel::TupleToTransitionState(), and kaldi::WriteIntegerVector().
{
   KALDI_ASSERT(new_tid_ali != NULL);
   KALDI_ASSERT(tid_ali.size() == full_ali.size() &&
                "Regular and full-context alignments must be of same size.");
   new_tid_ali->clear();
   int32 num_frames = tid_ali.size(),
       ctx_width = new_ctx_dep.ContextWidth(),
       central_pos = new_ctx_dep.CentralPosition();
   for (int32 i = 0; i < num_frames; ++i) {
     KALDI_ASSERT(full_ali[i].size() == ctx_width);
     int32 old_tid = tid_ali[i],
         phone = old_trans_model.TransitionIdToPhone(old_tid),
         old_tstate = old_trans_model.TransitionIdToTransitionState(old_tid);
     int32 forward_pdf_class =
         old_trans_model.TransitionStateToForwardPdfClass(old_tstate),
         self_loop_pdf_class =
         old_trans_model.TransitionStateToSelfLoopPdfClass(old_tstate);
     int32 hmm_state = old_trans_model.TransitionIdToHmmState(old_tid),
         trans_idx = old_trans_model.TransitionIdToTransitionIndex(old_tid);
     KALDI_ASSERT(full_ali[i][central_pos] == phone &&
                  "Mismatched regular and full-context alignments.");
     KALDI_ASSERT((*full_ali[i].end()) == forward_pdf_class &&
                  "Mismatched regular and full-context alignments.");
     std::vector<int32> fullctx(full_ali[i].begin(), full_ali[i].end()-1);
     int32 new_forward_pdf, new_self_loop_pdf;
     if (!new_ctx_dep.Compute(fullctx, forward_pdf_class, &new_forward_pdf)
         || !new_ctx_dep.Compute(fullctx, self_loop_pdf_class, &new_self_loop_pdf)) {
       std::ostringstream ctx_ss;
       WriteIntegerVector(ctx_ss, false, full_ali[i]);
       KALDI_ERR << "Decision tree did not produce an answer for: pdf-class = "
                 << forward_pdf_class << " context window = " << ctx_ss.str();
     }
     int32 new_trans_state =
         new_trans_model.TupleToTransitionState(phone,
                                                hmm_state,
                                                new_forward_pdf,
                                                new_self_loop_pdf);
     int32 new_tid = new_trans_model.PairToTransitionId(new_trans_state,
                                                        trans_idx);
     new_tid_ali->push_back(new_tid);
   }
   KALDI_ASSERT(new_tid_ali->size() == tid_ali.size());
   return true;
 }
ConvertPhnxToProns()
bool ConvertPhnxToProns (const std::vector< int32 > & phnx, const std::vector< int32 > & words, int32 word_start_sym, int32 word_end_sym, std::vector< std::vector< int32 > > * prons)
Definition at line 1161 of file hmm-utils.cc.
References rnnlm::i, and rnnlm::j.
Referenced by main(), and kaldi::TestConvertPhnxToProns().
{
   size_t i = 0, j = 0;
   while (i < phnx.size()) {
     if (phnx[i] == 0) return false; // zeros not valid here.
     if (phnx[i] == word_start_sym) { // start a word...
       std::vector<int32> pron;
       if (j >= words.size()) return false; // no word left..
       if (words[j] == 0) return false; // zero word disallowed.
       pron.push_back(words[j++]);
       i++;
       while (i < phnx.size()) {
         if (phnx[i] == 0) return false;
         if (phnx[i] == word_start_sym) return false; // error.
         if (phnx[i] == word_end_sym) { i++; break; }
         pron.push_back(phnx[i]);
         i++;
       }
       // check we did see the word-end symbol.
       if (!(i > 0 && phnx[i-1] == word_end_sym))
         return false;
       prons->push_back(pron);
     } else if (phnx[i] == word_end_sym) {
       return false;  // error.
     } else {
       // start a non-word sequence of phones (e.g. opt-sil).
       std::vector<int32> pron;
       pron.push_back(0); // 0 serves as the word-id.
       while (i < phnx.size()) {
         if (phnx[i] == 0) return false;
         if (phnx[i] == word_start_sym) break;
         if (phnx[i] == word_end_sym) return false; // error.
         pron.push_back(phnx[i]);
         i++;
       }
       prons->push_back(pron);
     }
   }
   return (j == words.size());
 }
GetPdfsForPhones()
bool GetPdfsForPhones (const TransitionModel & trans_model, const std::vector< int32 > & phones, std::vector< int32 > * pdfs)
Works out which pdfs might correspond to the given phones.
Will return true if these pdfs correspond *just* to these phones, false if these pdfs are also used by other phones.
Parameters
trans_model [in] Transition-model used to work out this information
phones [in] A sorted, uniq vector that represents a set of phones
pdfs [out] Will be set to a sorted, uniq list of pdf-ids that correspond to one of this set of phones.
Returns
Returns true if all of the pdfs output to "pdfs" correspond to phones from just this set (false if they may be shared with phones outside this set).
Definition at line 843 of file transition-model.cc.
References kaldi::IsSortedAndUniq(), KALDI_ASSERT, TransitionModel::NumTransitionStates(), kaldi::SortAndUniq(), TransitionModel::TransitionStateToForwardPdf(), TransitionModel::TransitionStateToPhone(), and TransitionModel::TransitionStateToSelfLoopPdf().
Referenced by main(), and TransitionModel::TransitionIdToPdf().
{
   KALDI_ASSERT(IsSortedAndUniq(phones));
   KALDI_ASSERT(pdfs != NULL);
   pdfs->clear();
   for (int32 tstate = 1; tstate <= trans_model.NumTransitionStates(); tstate++) {
     if (std::binary_search(phones.begin(), phones.end(),
              trans_model.TransitionStateToPhone(tstate))) {
       pdfs->push_back(trans_model.TransitionStateToForwardPdf(tstate));
       pdfs->push_back(trans_model.TransitionStateToSelfLoopPdf(tstate));
     }
   }
   SortAndUniq(pdfs);
   for (int32 tstate = 1; tstate <= trans_model.NumTransitionStates(); tstate++)
     if ((std::binary_search(pdfs->begin(), pdfs->end(),
                           trans_model.TransitionStateToForwardPdf(tstate)) ||
          std::binary_search(pdfs->begin(), pdfs->end(),
                           trans_model.TransitionStateToSelfLoopPdf(tstate)))
        && !std::binary_search(phones.begin(), phones.end(),
                               trans_model.TransitionStateToPhone(tstate)))
       return false;
   return true;
 }
GetPhonesForPdfs()
bool GetPhonesForPdfs (const TransitionModel & trans_model, const std::vector< int32 > & pdfs, std::vector< int32 > * phones)
Works out which phones might correspond to the given pdfs.
Similar to the above GetPdfsForPhones(, ,)
Definition at line 869 of file transition-model.cc.
References kaldi::IsSortedAndUniq(), KALDI_ASSERT, TransitionModel::NumTransitionStates(), kaldi::SortAndUniq(), TransitionModel::TransitionStateToForwardPdf(), TransitionModel::TransitionStateToPhone(), and TransitionModel::TransitionStateToSelfLoopPdf().
Referenced by kaldi::InitAmGmm(), and TransitionModel::TransitionIdToPdf().
{
   KALDI_ASSERT(IsSortedAndUniq(pdfs));
   KALDI_ASSERT(phones != NULL);
   phones->clear();
   for (int32 tstate = 1; tstate <= trans_model.NumTransitionStates(); tstate++) {
     if (std::binary_search(pdfs.begin(), pdfs.end(),
                            trans_model.TransitionStateToForwardPdf(tstate)) ||
         std::binary_search(pdfs.begin(), pdfs.end(),
                            trans_model.TransitionStateToSelfLoopPdf(tstate)))
       phones->push_back(trans_model.TransitionStateToPhone(tstate));
   }
   SortAndUniq(phones);
   for (int32 tstate = 1; tstate <= trans_model.NumTransitionStates(); tstate++)
     if (std::binary_search(phones->begin(), phones->end(),
                            trans_model.TransitionStateToPhone(tstate))
         && !(std::binary_search(pdfs.begin(), pdfs.end(),
                                trans_model.TransitionStateToForwardPdf(tstate)) &&
              std::binary_search(pdfs.begin(), pdfs.end(),
                                trans_model.TransitionStateToSelfLoopPdf(tstate))) )
       return false;
   return true;
 }
GetPhoneWindows()
bool GetPhoneWindows (const TransitionModel & trans_model, const std::vector< int32 > & alignment, int32 context_width, int32 central_pos, bool per_frame, std::vector< std::vector< int32 > > * phone_windows, std::vector< int32 > * phones)
GetPhoneWindows takes an alignment in terms of transition-ids and works out the phonetic context windows for a given context-width and central position.
It also returns the list of phones seen in the alignment if the 'phones' argument is not NULL. If the 'per_frame' option is true, then the phonetic context windows (and phones) are repeated for the number of frames they span.
Definition at line 30 of file hmm-utils-idlak.cc.
References rnnlm::i, KALDI_ASSERT, kaldi::SplitToPhones(), and TransitionModel::TransitionIdToPhone().
Referenced by main().
{
   KALDI_ASSERT(phone_windows != NULL);
   phone_windows->clear();
   std::vector< std::vector<int32> > split;  // split into phones
   if (!SplitToPhones(trans_model, alignment, &split))
     return false;
   int32 num_phones = split.size();  // Number of distinct phones in alignment
   std::vector<int32> tmp_phones(num_phones);
   for (int32 i = 0; i < num_phones; i++) {
     KALDI_ASSERT(!split[i].empty());
     tmp_phones[i] = trans_model.TransitionIdToPhone(split[i][0]);
   }
   for (int32 win_start = -context_width;
       win_start < static_cast<int32>(num_phones+context_width);
       win_start++) {  // start of a context window.
     int32 current_phone_pos = win_start + central_pos;
     if (current_phone_pos >= 0 && current_phone_pos  < num_phones) {
       std::vector<int32> phone_window(context_width, 0);
       for (int32 offset = 0; offset < context_width; offset++)
         if ((win_start+offset) >= 0 && (win_start+offset) < num_phones)
           phone_window[offset] = tmp_phones[win_start+offset];
       if (per_frame) {
         int32 num_frames = split[current_phone_pos].size();
         for (int32 i = 0; i < num_frames; ++i)
           phone_windows->push_back(phone_window);
       } else {
         phone_windows->push_back(phone_window);
       }
     }
   }
   if (per_frame) {
     KALDI_ASSERT(phone_windows->size() == alignment.size());
   } else {
     KALDI_ASSERT(phone_windows->size() == num_phones);
   }
   if (phones != NULL) {
     if (per_frame) {
       phones->clear();
       for (int32 i = 0; i < num_phones; ++i) {
         int32 num_frames = split[i].size();
         for (int32 f = 0; f < num_frames; ++f)
           phones->push_back(tmp_phones[i]);
       }
       KALDI_ASSERT(phones->size() == alignment.size());
     } else {
       (*phones) = tmp_phones;
     }
   }
   return true;
 }
GetRandomAlignmentForPhone()
void GetRandomAlignmentForPhone (const ContextDependencyInterface & ctx_dep, const TransitionModel & trans_model, const std::vector< int32 > & phone_window, std::vector< int32 > * alignment)
Definition at line 1207 of file hmm-utils.cc.
References ContextDependencyInterface::CentralPosition(), kaldi::GetHmmAsFsaSimple(), fst::GetInputSymbols(), TransitionModel::GetTopo(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_ERR, and HmmTopology::MinLength().
Referenced by kaldi::ConvertAlignmentForPhone().
{
   typedef fst::StdArc Arc;
   int32 length = alignment->size();
   BaseFloat prob_scale = 0.0;
   fst::VectorFst<Arc> *fst = GetHmmAsFsaSimple(phone_window, ctx_dep,
                                                trans_model, prob_scale);
   fst::RmEpsilon(fst);
   fst::VectorFst<Arc> length_constraint_fst;
   {  // set up length_constraint_fst.
     std::vector<int32> symbols;
     bool include_epsilon = false;
     // note: 'fst' is an acceptor so ilabels == olabels.
     GetInputSymbols(*fst, include_epsilon, &symbols);
     int32 cur_state = length_constraint_fst.AddState();
     length_constraint_fst.SetStart(cur_state);
     for (int32 i = 0; i < length; i++) {
       int32 next_state = length_constraint_fst.AddState();
       for (size_t j = 0; j < symbols.size(); j++) {
         length_constraint_fst.AddArc(cur_state,
                                      Arc(symbols[j], symbols[j],
                                          fst::TropicalWeight::One(),
                                          next_state));
       }
       cur_state = next_state;
     }
     length_constraint_fst.SetFinal(cur_state, fst::TropicalWeight::One());
   }
   fst::VectorFst<Arc> composed_fst;
   fst::Compose(*fst, length_constraint_fst, &composed_fst);
   fst::VectorFst<Arc> single_path_fst;
   {  // randomly generate a single path.
     fst::UniformArcSelector<Arc> selector;
     fst::RandGenOptions<fst::UniformArcSelector<Arc> > randgen_opts(selector);
     fst::RandGen(composed_fst, &single_path_fst, randgen_opts);
   }
   if (single_path_fst.NumStates() == 0) {
     KALDI_ERR << "Error generating random alignment (wrong length?): "
               << "requested length is " << length << " versus min-length "
               << trans_model.GetTopo().MinLength(
                   phone_window[ctx_dep.CentralPosition()]);
   }
   std::vector<int32> symbol_sequence;
   bool ans = fst::GetLinearSymbolSequence<Arc, int32>(
       single_path_fst, &symbol_sequence, NULL, NULL);
   KALDI_ASSERT(ans && symbol_sequence.size() == length);
   symbol_sequence.swap(*alignment);
   delete fst;
 }
SplitToPhones()
bool SplitToPhones (const TransitionModel & trans_model, const std::vector< int32 > & alignment, std::vector< std::vector< int32 > > * split_alignment)
SplitToPhones splits up the TransitionIds in "alignment" into their individual phones (one vector per instance of a phone).
At output, the sum of the sizes of the vectors in split_alignment will be the same as the corresponding sum for "alignment". The function returns true on success. If the alignment appears to be incomplete, e.g. not ending at the end-state of a phone, it will still break it up into phones but it will return false. For more serious errors it will die or throw an exception. This function works out by itself whether the graph was created with "reordering", and just does the right thing.
Definition at line 723 of file hmm-utils.cc.
References kaldi::IsReordered(), KALDI_ASSERT, and kaldi::SplitToPhonesInternal().
Referenced by kaldi::AccumulateTreeStats(), kaldi::CompactLatticeToWordProns(), kaldi::ConvertAlignmentInternal(), kaldi::GetPhoneWindows(), kaldi::IsPlausibleWord(), main(), kaldi::TestConvertAlignment(), and kaldi::TestSplitToPhones().
{
   KALDI_ASSERT(split_alignment != NULL);
   split_alignment->clear();
   bool is_reordered = IsReordered(trans_model, alignment);
   return SplitToPhonesInternal(trans_model, alignment,
                                is_reordered, split_alignment);
 }
TransitionIdToPdf()
int32 TransitionIdToPdf (int32 trans_id) const inline
Definition at line 324 of file transition-model.h.
References kaldi::GetPdfsForPhones(), kaldi::GetPhonesForPdfs(), and KALDI_ASSERT.
Referenced by kaldi::AccumulateForUtterance(), DiscriminativeExampleSplitter::CollapseTransitionIds(), DiscriminativeSupervisionSplitter::CollapseTransitionIds(), kaldi::ComputeAmGmmFeatureDeriv(), DiscriminativeExampleSplitter::ComputeFrameInfo(), kaldi::ConvertPosteriorToPdfs(), kaldi::GetPdfToTransitionIdTransducer(), kaldi::LatticeAcousticRescore(), kaldi::nnet1::LatticeAcousticRescore(), NnetDiscriminativeUpdater::LatticeComputations(), kaldi::LatticeForwardBackwardMpeVariants(), DecodableAmDiagGmmRegtreeFmllr::LogLikelihood(), DecodableAmSgmm2::LogLikelihood(), DecodableMatrixScaledMapped::LogLikelihood(), DecodableNnet2Online::LogLikelihood(), DecodableAmNnet::LogLikelihood(), DecodableAmDiagGmmRegtreeMllr::LogLikelihood(), DecodableAmSgmm2Scaled::LogLikelihood(), DecodableAmNnetParallel::LogLikelihood(), DecodableMatrixMappedOffset::LogLikelihood(), DecodableAmNnetSimple::LogLikelihood(), DecodableAmNnetSimpleLooped::LogLikelihood(), DecodableAmNnetSimpleParallel::LogLikelihood(), DiscriminativeComputation::LookupNnetOutput(), main(), ComparePosteriorByPdfs::operator()(), kaldi::PosteriorToPdfMatrix(), kaldi::RescoreCompactLatticeInternal(), kaldi::nnet2::SetPriors(), and kaldi::nnet3::SetPriors().
{
   KALDI_ASSERT(static_cast<size_t>(trans_id) < id2pdf_id_.size() &&
                "Likely graph/model mismatch (graph built from wrong model?)");
   return id2pdf_id_[trans_id];
 }
Variable Documentation
kNoPdf
const int32 kNoPdf = -1 static
A constant used in the HmmTopology class as the pdf-class kNoPdf, which is used when a HMM-state is nonemitting (has no associated PDF).
Definition at line 87 of file hmm-topology.h.
Referenced by HmmTopology::Check(), TransitionModel::ComputeTuplesIsHmm(), TransitionModel::ComputeTuplesNotHmm(), kaldi::GetHmmAsFsa(), kaldi::GetHmmAsFsaSimple(), HmmTopology::Read(), kaldi::SplitToPhonesInternal(), and HmmTopology::Write().