Kaldi: Idlak_utils
Idlak_utils
Classes
class TxpPcre
Simple C++ wrapper around pcre.
class TxpUtf8
Utility class to manage a very limited set of utf8 string manipulatation functions.
Functions
int32 Clen (const char *input)
Return the size of the next utf8 character.
Variables
static const char trailingBytesForUTF8_ [256]
Lookup table for determining number of trailing characters given the first byte of a utf8 character.
Detailed Description
Function Documentation
Clen()
int32 Clen (const char * input) inline
Return the size of the next utf8 character.
Definition at line 37 of file txputf8.h.
References TxpUtf8::trailingBytesForUTF8_.
Referenced by kaldi::ApplyQuestion(), TxpNRules::ConsumeToken(), TxpTrules::ConsumeToken(), TxpTrules::ConsumeWhitespaceToken(), TxpPbreak::GetPbreak(), TxpLts::GetPron(), TxpPbreak::GetWhitespaceBreaks(), TxpTrules::NormCaseCharacter(), TxpNRules::NormCaseCharacter(), TxpTrules::ReplaceUtf8Punc(), and TxpNRules::ReplaceUtf8Punc().
{
     return trailingBytesForUTF8_[static_cast<unsigned int>(
         static_cast<unsigned const char>(input[0]))] + 1;
   }
Variable Documentation
trailingBytesForUTF8_
const char trailingBytesForUTF8_ static private
Initial value:
= {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5
}
Lookup table for determining number of trailing characters given the first byte of a utf8 character.
Definition at line 45 of file txputf8.h.
Referenced by TxpUtf8::Clen().