Kaldi: Matrix-vector functions returning scalars
Matrix-vector functions returning scalars
%Matrix and vector classes
Functions
template<typename Real >
bool ApproxEqual (const MatrixBase< Real > &A, const MatrixBase< Real > &B, Real tol=0.01)
template<typename Real >
void AssertEqual (const MatrixBase< Real > &A, const MatrixBase< Real > &B, float tol=0.01)
template<typename Real >
double TraceMat (const MatrixBase< Real > &A)
Returns trace of matrix.
template<typename Real >
Real TraceMatMatMat (const MatrixBase< Real > &A, MatrixTransposeType transA, const MatrixBase< Real > &B, MatrixTransposeType transB, const MatrixBase< Real > &C, MatrixTransposeType transC)
Returns tr(A B C)
template<typename Real >
Real TraceMatMatMatMat (const MatrixBase< Real > &A, MatrixTransposeType transA, const MatrixBase< Real > &B, MatrixTransposeType transB, const MatrixBase< Real > &C, MatrixTransposeType transC, const MatrixBase< Real > &D, MatrixTransposeType transD)
Returns tr(A B C D)
template<typename Real >
bool ApproxEqual (const VectorBase< Real > &a, const VectorBase< Real > &b, Real tol=0.01)
template<typename Real >
void AssertEqual (VectorBase< Real > &a, VectorBase< Real > &b, float tol=0.01)
template<typename Real >
Real VecVec (const VectorBase< Real > &v1, const VectorBase< Real > &v2)
Returns dot product between v1 and v2.
template<typename Real , typename OtherReal >
Real VecVec (const VectorBase< Real > &ra, const VectorBase< OtherReal > &rb)
template<typename Real >
Real VecMatVec (const VectorBase< Real > &v1, const MatrixBase< Real > &M, const VectorBase< Real > &v2)
Returns .
float TraceSpSp (const SpMatrix< float > &A, const SpMatrix< float > &B)
Returns tr(A B).
double TraceSpSp (const SpMatrix< double > &A, const SpMatrix< double > &B)
template<typename Real >
bool ApproxEqual (const SpMatrix< Real > &A, const SpMatrix< Real > &B, Real tol=0.01)
template<typename Real >
void AssertEqual (const SpMatrix< Real > &A, const SpMatrix< Real > &B, Real tol=0.01)
template<typename Real , typename OtherReal >
Real TraceSpSp (const SpMatrix< Real > &A, const SpMatrix< OtherReal > &B)
Returns tr(A B).
template<typename Real >
Real TraceSpSpLower (const SpMatrix< Real > &A, const SpMatrix< Real > &B)
template<typename Real >
Real TraceSpMat (const SpMatrix< Real > &A, const MatrixBase< Real > &B)
Returns tr(A B).
template<typename Real >
Real TraceMatSpMat (const MatrixBase< Real > &A, MatrixTransposeType transA, const SpMatrix< Real > &B, const MatrixBase< Real > &C, MatrixTransposeType transC)
Returns tr(A B C) (A and C may be transposed as specified by transA and transC).
template<typename Real >
Real TraceMatSpMatSp (const MatrixBase< Real > &A, MatrixTransposeType transA, const SpMatrix< Real > &B, const MatrixBase< Real > &C, MatrixTransposeType transC, const SpMatrix< Real > &D)
Returns tr (A B C D) (A and C may be transposed as specified by transA and transB).
template<typename Real >
Real VecSpVec (const VectorBase< Real > &v1, const SpMatrix< Real > &M, const VectorBase< Real > &v2)
Computes v1^T * M * v2.
Detailed Description
Function Documentation
ApproxEqual() [1/3]
bool kaldi::ApproxEqual (const SpMatrix< Real > & A, const SpMatrix< Real > & B, Real tol = 0.01) inline
Definition at line 375 of file sp-matrix.h.
{
   return  A.ApproxEqual(B, tol);
 }
ApproxEqual() [2/3]
bool kaldi::ApproxEqual (const VectorBase< Real > & a, const VectorBase< Real > & b, Real tol = 0.01)
Definition at line 560 of file kaldi-vector.h.
References VectorBase< Real >::ApproxEqual().
{
   return a.ApproxEqual(b, tol);
 }
ApproxEqual() [3/3]
bool kaldi::ApproxEqual (const MatrixBase< Real > & A, const MatrixBase< Real > & B, Real tol = 0.01)
Definition at line 983 of file kaldi-matrix.h.
References MatrixBase< Real >::ApproxEqual().
{
   return A.ApproxEqual(B, tol);
 }
AssertEqual() [1/3]
void kaldi::AssertEqual (const SpMatrix< Real > & A, const SpMatrix< Real > & B, Real tol = 0.01) inline
Definition at line 381 of file sp-matrix.h.
References SpMatrix< Real >::ApproxEqual(), KALDI_ASSERT, kaldi::TraceMatSpMat(), kaldi::TraceMatSpMatSp(), kaldi::TraceSpMat(), kaldi::TraceSpSp(), kaldi::TraceSpSpLower(), and kaldi::VecSpVec().
{
   KALDI_ASSERT(ApproxEqual(A, B, tol));
 }
AssertEqual() [2/3]
void kaldi::AssertEqual (VectorBase< Real > & a, VectorBase< Real > & b, float tol = 0.01) inline
Definition at line 566 of file kaldi-vector.h.
References VectorBase< Real >::ApproxEqual(), KALDI_ASSERT, kaldi::VecMatVec(), and kaldi::VecVec().
{
   KALDI_ASSERT(a.ApproxEqual(b, tol));
 }
AssertEqual() [3/3]
void kaldi::AssertEqual (const MatrixBase< Real > & A, const MatrixBase< Real > & B, float tol = 0.01) inline
Definition at line 989 of file kaldi-matrix.h.
References MatrixBase< Real >::ApproxEqual(), and KALDI_ASSERT.
{
   KALDI_ASSERT(A.ApproxEqual(B, tol));
 }
TraceMat()
double kaldi::TraceMat (const MatrixBase< Real > & A)
Returns trace of matrix.
Definition at line 996 of file kaldi-matrix.h.
References kaldi::AttemptComplexPower(), kaldi::CreateEigenvalueMatrix(), kaldi::operator>>(), kaldi::SortSvd(), MatrixBase< Real >::Trace(), kaldi::TraceMatMatMat(), and kaldi::TraceMatMatMatMat().
Referenced by kaldi::CalBasisFmllrStepSize(), kaldi::CalcFmllrStepSize(), and kaldi::UnitTestTrace().
 { return A.Trace(); }
TraceMatMatMat()
Real TraceMatMatMat (const MatrixBase< Real > & A, MatrixTransposeType transA, const MatrixBase< Real > & B, MatrixTransposeType transB, const MatrixBase< Real > & C, MatrixTransposeType transC)
Returns tr(A B C)
Definition at line 2456 of file kaldi-matrix.cc.
References MatrixBase< Real >::AddMatMat(), KALDI_ASSERT, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), kaldi::swap(), kaldi::TraceMatMat(), and kaldi::TraceMatMatMat().
Referenced by kaldi::TraceMat(), and kaldi::UnitTestTrace().
{
   MatrixIndexT ARows = A.NumRows(), ACols = A.NumCols(), BRows = B.NumRows(), BCols = B.NumCols(),
       CRows = C.NumRows(), CCols = C.NumCols();
   if (transA == kTrans) std::swap(ARows, ACols);
   if (transB == kTrans) std::swap(BRows, BCols);
   if (transC == kTrans) std::swap(CRows, CCols);
   KALDI_ASSERT( CCols == ARows && ACols == BRows && BCols == CRows && "TraceMatMatMat: args have mismatched dimensions.");
   if (ARows*BCols < std::min(BRows*CCols, CRows*ACols)) {
     Matrix<Real> AB(ARows, BCols);
     AB.AddMatMat(1.0, A, transA, B, transB, 0.0);  // AB = A * B.
     return TraceMatMat(AB, C, transC);
   } else if ( BRows*CCols < CRows*ACols) {
     Matrix<Real> BC(BRows, CCols);
     BC.AddMatMat(1.0, B, transB, C, transC, 0.0);  // BC = B * C.
     return TraceMatMat(BC, A, transA);
   } else {
     Matrix<Real> CA(CRows, ACols);
     CA.AddMatMat(1.0, C, transC, A, transA, 0.0);  // CA = C * A
     return TraceMatMat(CA, B, transB);
   }
 }
TraceMatMatMatMat()
Real TraceMatMatMatMat (const MatrixBase< Real > & A, MatrixTransposeType transA, const MatrixBase< Real > & B, MatrixTransposeType transB, const MatrixBase< Real > & C, MatrixTransposeType transC, const MatrixBase< Real > & D, MatrixTransposeType transD)
Returns tr(A B C D)
Definition at line 2492 of file kaldi-matrix.cc.
References MatrixBase< Real >::AddMatMat(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), kaldi::swap(), kaldi::TraceMatMatMat(), and kaldi::TraceMatMatMatMat().
Referenced by kaldi::TraceMat(), and kaldi::UnitTestTrace().
{
   MatrixIndexT ARows = A.NumRows(), ACols = A.NumCols(), BRows = B.NumRows(), BCols = B.NumCols(),
       CRows = C.NumRows(), CCols = C.NumCols(), DRows = D.NumRows(), DCols = D.NumCols();
   if (transA == kTrans) std::swap(ARows, ACols);
   if (transB == kTrans) std::swap(BRows, BCols);
   if (transC == kTrans) std::swap(CRows, CCols);
   if (transD == kTrans) std::swap(DRows, DCols);
   KALDI_ASSERT( DCols == ARows && ACols == BRows && BCols == CRows && CCols == DRows && "TraceMatMatMat: args have mismatched dimensions.");
   if (ARows*BCols < std::min(BRows*CCols, std::min(CRows*DCols, DRows*ACols))) {
     Matrix<Real> AB(ARows, BCols);
     AB.AddMatMat(1.0, A, transA, B, transB, 0.0);  // AB = A * B.
     return TraceMatMatMat(AB, kNoTrans, C, transC, D, transD);
   } else if ((BRows*CCols) < std::min(CRows*DCols, DRows*ACols)) {
     Matrix<Real> BC(BRows, CCols);
     BC.AddMatMat(1.0, B, transB, C, transC, 0.0);  // BC = B * C.
     return TraceMatMatMat(BC, kNoTrans, D, transD, A, transA);
   } else if (CRows*DCols < DRows*ACols) {
     Matrix<Real> CD(CRows, DCols);
     CD.AddMatMat(1.0, C, transC, D, transD, 0.0);  // CD = C * D
     return TraceMatMatMat(CD, kNoTrans, A, transA, B, transB);
   } else {
     Matrix<Real> DA(DRows, ACols);
     DA.AddMatMat(1.0, D, transD, A, transA, 0.0);  // DA = D * A
     return TraceMatMatMat(DA, kNoTrans, B, transB, C, transC);
   }
 }
TraceMatSpMat()
Real TraceMatSpMat (const MatrixBase< Real > & A, MatrixTransposeType transA, const SpMatrix< Real > & B, const MatrixBase< Real > & C, MatrixTransposeType transC)
Returns tr(A B C) (A and C may be transposed as specified by transA and transC).
Definition at line 415 of file sp-matrix.cc.
References MatrixBase< Real >::AddMatMat(), KALDI_ASSERT, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), PackedMatrix< Real >::NumRows(), and kaldi::TraceSpMat().
Referenced by kaldi::AssertEqual(), kaldi::UnitTestSolve(), and kaldi::UnitTestTrace().
{
   KALDI_ASSERT((transA == kTrans?A.NumCols():A.NumRows()) ==
                (transC == kTrans?C.NumRows():C.NumCols()) &&
                (transA == kTrans?A.NumRows():A.NumCols()) == B.NumRows() &&
                (transC == kTrans?C.NumCols():C.NumRows()) == B.NumRows() &&
                "TraceMatSpMat: arguments have wrong dimension.");
   Matrix<Real> tmp(B.NumRows(), B.NumRows());
   tmp.AddMatMat(1.0, C, transC, A, transA, 0.0);  // tmp = C * A.
   return TraceSpMat(B, tmp);
 }
TraceMatSpMatSp()
Real TraceMatSpMatSp (const MatrixBase< Real > & A, MatrixTransposeType transA, const SpMatrix< Real > & B, const MatrixBase< Real > & C, MatrixTransposeType transC, const SpMatrix< Real > & D)
Returns tr (A B C D) (A and C may be transposed as specified by transA and transB).
Definition at line 438 of file sp-matrix.cc.
References MatrixBase< Real >::AddMatSp(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, MatrixBase< Real >::NumCols(), PackedMatrix< Real >::NumCols(), MatrixBase< Real >::NumRows(), PackedMatrix< Real >::NumRows(), and kaldi::TraceMatMat().
Referenced by kaldi::AssertEqual(), kaldi::CalcFmllrStepSize(), kaldi::UnitTestSolve(), and kaldi::UnitTestTrace().
{
   KALDI_ASSERT((transA == kTrans ?A.NumCols():A.NumRows() == D.NumCols()) &&
                (transA == kTrans ? A.NumRows():A.NumCols() == B.NumRows()) &&
                (transC == kTrans ? A.NumCols():A.NumRows() == B.NumCols()) &&
                (transC == kTrans ? A.NumRows():A.NumCols() == D.NumRows()) &&
                "KALDI_ERR: TraceMatSpMatSp: arguments have mismatched dimension.");
   // Could perhaps optimize this more depending on dimensions of quantities.
   Matrix<Real> tmpAB(transA == kTrans ? A.NumCols():A.NumRows(), B.NumCols());
   tmpAB.AddMatSp(1.0, A, transA, B, 0.0);
   Matrix<Real> tmpCD(transC == kTrans ? C.NumCols():C.NumRows(), D.NumCols());
   tmpCD.AddMatSp(1.0, C, transC, D, 0.0);
   return TraceMatMat(tmpAB, tmpCD, kNoTrans);
 }
TraceSpMat()
Real TraceSpMat (const SpMatrix< Real > & A, const MatrixBase< Real > & B)
Returns tr(A B).
No option to transpose B because would make no difference.
Definition at line 389 of file sp-matrix.cc.
References MatrixBase< Real >::Data(), PackedMatrix< Real >::Data(), KALDI_ASSERT, MatrixBase< Real >::NumCols(), PackedMatrix< Real >::NumCols(), MatrixBase< Real >::NumRows(), PackedMatrix< Real >::NumRows(), and MatrixBase< Real >::Stride().
Referenced by kaldi::AssertEqual(), kaldi::TraceMatSpMat(), and kaldi::UnitTestTrace().
{
   KALDI_ASSERT(A.NumRows() == B.NumRows() && A.NumCols() == B.NumCols() &&
                "KALDI_ERR: TraceSpMat: arguments have mismatched dimension");
   MatrixIndexT R = A.NumRows();
   Real ans = (Real)0.0;
   const Real *Aptr = A.Data(), *Bptr = B.Data();
   MatrixIndexT bStride = B.Stride();
   for (MatrixIndexT r = 0;r < R;r++) {
     for (MatrixIndexT c = 0;c < r;c++) {
       // ans += A(r, c) * (B(r, c) + B(c, r));
       ans += *(Aptr++) * (Bptr[r*bStride + c] + Bptr[c*bStride + r]);
     }
     // ans += A(r, r) * B(r, r);
     ans += *(Aptr++) * Bptr[r*bStride + r];
   }
   return ans;
 }
TraceSpSp() [1/3]
double TraceSpSp (const SpMatrix< double > & A, const SpMatrix< double > & B)
Definition at line 326 of file sp-matrix.cc.
References kaldi::cblas_Xdot(), PackedMatrix< Real >::Data(), KALDI_ASSERT, and PackedMatrix< Real >::NumRows().
Referenced by kaldi::AssertEqual(), MleAmSgmm2Updater::ComputeMPrior(), PldaEstimator::ComputeObjfPart1(), IvectorExtractor::GetAcousticAuxfMean(), IvectorExtractor::GetAcousticAuxfVariance(), IvectorExtractor::GetAcousticAuxfWeight(), CuSpMatrix< Real >::IsUnit(), SpMatrix< float >::LimitCondDouble(), kaldi::MlObjective(), kaldi::SolveQuadraticMatrixProblem(), kaldi::TraceSpSp(), kaldi::UnitTestCuSpMatrixTraceSpSp(), kaldi::UnitTestDeterminant(), kaldi::UnitTestTraceSpSpLower(), IvectorExtractorStats::UpdateVariances(), EbwAmSgmm2Updater::UpdateVars(), and MleAmSgmm2Updater::UpdateVars().
{
   KALDI_ASSERT(A.NumRows() == B.NumRows());
   const double *Aptr = A.Data();
   const double *Bptr = B.Data();
   MatrixIndexT R = A.NumRows();
   MatrixIndexT RR = (R * (R + 1)) / 2;
   double all_twice = 2.0 * cblas_Xdot(RR, Aptr, 1, Bptr, 1);
   // "all_twice" contains twice the vector-wise dot-product... this is
   // what we want except the diagonal elements are represented
   // twice.
   double diag_once = 0.0;
   for (MatrixIndexT row_plus_two = 2; row_plus_two <= R + 1; row_plus_two++) {
     diag_once += *Aptr * *Bptr;
     Aptr += row_plus_two;
     Bptr += row_plus_two;
   }
   return all_twice - diag_once;
 }
TraceSpSp() [2/3]
float TraceSpSp (const SpMatrix< float > & A, const SpMatrix< float > & B)
Returns tr(A B).
Definition at line 346 of file sp-matrix.cc.
References kaldi::cblas_Xdot(), PackedMatrix< Real >::Data(), KALDI_ASSERT, and PackedMatrix< Real >::NumRows().
{
   KALDI_ASSERT(A.NumRows() == B.NumRows());
   const float *Aptr = A.Data();
   const float *Bptr = B.Data();
   MatrixIndexT R = A.NumRows();
   MatrixIndexT RR = (R * (R + 1)) / 2;
   float all_twice = 2.0 * cblas_Xdot(RR, Aptr, 1, Bptr, 1);
   // "all_twice" contains twice the vector-wise dot-product... this is
   // what we want except the diagonal elements are represented
   // twice.
   float diag_once = 0.0;
   for (MatrixIndexT row_plus_two = 2; row_plus_two <= R + 1; row_plus_two++) {
     diag_once += *Aptr * *Bptr;
     Aptr += row_plus_two;
     Bptr += row_plus_two;
   }
   return all_twice - diag_once;
 }
TraceSpSp() [3/3]
Real TraceSpSp (const SpMatrix< Real > & A, const SpMatrix< OtherReal > & B)
Returns tr(A B).
Definition at line 367 of file sp-matrix.cc.
References PackedMatrix< Real >::Data(), KALDI_ASSERT, PackedMatrix< Real >::NumRows(), kaldi::TraceSpSp< double, float >(), and kaldi::TraceSpSp< float, double >().
{
   KALDI_ASSERT(A.NumRows() == B.NumRows());
   Real ans = 0.0;
   const Real *Aptr = A.Data();
   const OtherReal *Bptr = B.Data();
   MatrixIndexT row, col, R = A.NumRows();
   for (row = 0; row < R; row++) {
     for (col = 0; col < row; col++)
       ans += 2.0 * *(Aptr++) * *(Bptr++);
     ans += *(Aptr++) * *(Bptr++);  // Diagonal.
   }
   return ans;
 }
TraceSpSpLower()
Real TraceSpSpLower (const SpMatrix< Real > & A, const SpMatrix< Real > & B)
Definition at line 1171 of file sp-matrix.cc.
References kaldi::cblas_Xdot(), PackedMatrix< Real >::Data(), KALDI_ASSERT, PackedMatrix< Real >::NumRows(), kaldi::SolveDoubleQuadraticMatrixProblem(), and kaldi::SolveQuadraticMatrixProblem().
Referenced by kaldi::AssertEqual(), FullGmm::LogLikelihoods(), FullGmm::LogLikelihoodsPreselect(), and kaldi::UnitTestTraceSpSpLower().
{
   MatrixIndexT adim = A.NumRows();
   KALDI_ASSERT(adim == B.NumRows());
   MatrixIndexT dim = (adim*(adim+1))/2;
   return cblas_Xdot(dim, A.Data(), 1, B.Data(), 1);
 }
VecMatVec()
Real VecMatVec (const VectorBase< Real > & v1, const MatrixBase< Real > & M, const VectorBase< Real > & v2)
Returns .
Not as efficient as it could be where v1 == v2.
Definition at line 1280 of file kaldi-vector.cc.
References VectorBase< Real >::AddMatVec(), VectorBase< Real >::Dim(), KALDI_ASSERT, kaldi::kNoTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), kaldi::VecMatVec(), and kaldi::VecVec().
Referenced by kaldi::AssertEqual(), kaldi::UnitTestVecMatVec(), kaldi::VecMatVec(), and Vector< float >::Vector().
{
   KALDI_ASSERT(v1.Dim() == M.NumRows() && v2.Dim() == M.NumCols());
   Vector<Real> vtmp(M.NumRows());
   vtmp.AddMatVec(1.0, M, kNoTrans, v2, 0.0);
   return VecVec(v1, vtmp);
 }
VecSpVec()
Real VecSpVec (const VectorBase< Real > & v1, const SpMatrix< Real > & M, const VectorBase< Real > & v2)
Computes v1^T * M * v2.
Not as efficient as it could be where v1 == v2 (but no suitable blas routines available).Returns Not as efficient as it could be where v1 == v2.
Definition at line 964 of file sp-matrix.cc.
References kaldi::cblas_Xspmv(), VectorBase< Real >::Data(), PackedMatrix< Real >::Data(), VectorBase< Real >::Dim(), KALDI_ASSERT, PackedMatrix< Real >::NumRows(), and kaldi::VecVec().
Referenced by kaldi::AssertEqual(), FullGmm::ComponentLogLikelihood(), FullGmm::ComputeGconsts(), PldaEstimator::ComputeObjfPart2(), IvectorExtractor::GetAcousticAuxfMean(), FmllrRawAccs::GetAuxf(), GetLogLikeTest(), main(), OnlineIvectorEstimationStats::Objf(), kaldi::SolveDoubleQuadraticMatrixProblem(), kaldi::SolveQuadraticProblem(), kaldi::UnitTestFloorChol(), UnitTestFullGmm(), kaldi::UnitTestInnerProd(), kaldi::UnitTestLbfgs(), kaldi::UnitTestSolve(), MlltAccs::Update(), MleAmSgmm2Updater::UpdatePhoneVectorsInternal(), MleAmSgmm2Updater::UpdateW(), and MleSgmm2SpeakerAccs::UpdateWithU().
{
   MatrixIndexT D = M.NumRows();
   KALDI_ASSERT(v1.Dim() == D && v1.Dim() == v2.Dim());
   Vector<Real> tmp_vec(D);
   cblas_Xspmv(D, 1.0, M.Data(), v1.Data(), 1, 0.0, tmp_vec.Data(), 1);
   return VecVec(tmp_vec, v2);
 }
VecVec() [1/2]
Real VecVec (const VectorBase< Real > & a, const VectorBase< Real > & b)
Returns dot product between v1 and v2.
Definition at line 37 of file kaldi-vector.cc.
References kaldi::cblas_Xdot(), VectorBase< Real >::Data(), VectorBase< Real >::Dim(), and KALDI_ASSERT.
Referenced by OptimizeLbfgs< Real >::AcceptStep(), OnlinePitchFeatureImpl::AcceptWaveform(), FmllrRawAccs::AccumulateForGmm(), kaldi::AddNoise(), kaldi::AssertEqual(), kaldi::CalBasisFmllrStepSize(), FullGmm::ComponentLogLikelihood(), DiagGmm::ComponentLogLikelihood(), SpectrogramComputer::Compute(), MelBanks::Compute(), MfccComputer::Compute(), FbankComputer::Compute(), PlpComputer::Compute(), FrequencyBanks::Compute(), kaldi::ComputeCorrelation(), kaldi::ComputeEarlyReverbEnergy(), OptimizeLbfgs< Real >::ComputeHifNeeded(), OptimizeLbfgs< Real >::ComputeNewDirection(), AmSgmm2::ComputeNormalizersInternal(), AmSgmm2::ComputePerFrameVars(), EbwAmSgmm2Updater::ComputePhoneVecStats(), kaldi::CuVectorUnitTestInvertElements(), kaldi::CuVectorUnitTestSum(), kaldi::CuVectorUnitTestVecVec(), TimeHeightConvolutionComponent::DotProduct(), TdnnComponent::DotProduct(), RepeatedAffineComponent::DotProduct(), ConstantComponent::DotProduct(), AffineComponent::DotProduct(), BlockAffineComponent::DotProduct(), PerElementScaleComponent::DotProduct(), PerElementOffsetComponent::DotProduct(), ConstantFunctionComponent::DotProduct(), Convolutional1dComponent::DotProduct(), ScaleAndOffsetComponent::DotProduct(), ConvolutionComponent::DotProduct(), kaldi::FmllrAuxfGradient(), kaldi::FmllrAuxFuncDiagGmm(), kaldi::FmllrInnerUpdate(), IvectorExtractor::GetAcousticAuxfGconst(), IvectorExtractor::GetAcousticAuxfMean(), IvectorExtractor::GetAcousticAuxfWeight(), FmllrRawAccs::GetAuxf(), Plda::GetNormalizationFactor(), IvectorExtractor::GetPriorAuxf(), AffineComponentPreconditioned::GetScalingFactor(), AffineComponent::Info(), AffineComponentPreconditioned::Info(), AffineComponentPreconditionedOnline::Info(), FixedAffineComponent::Info(), FixedScaleComponent::Info(), FixedBiasComponent::Info(), Convolutional1dComponent::Info(), kaldi::LinearCgd(), AmSgmm2::LogLikelihood(), Plda::LogLikelihoodRatio(), FullGmm::LogLikelihoodsPreselect(), DiagGmm::LogLikelihoodsPreselect(), DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), main(), kaldi::MllrAuxFunction(), kaldi::MlObjective(), VectorClusterable::Objf(), OnlineIvectorEstimationStats::Objf(), MatrixBase< float >::OrthogonalizeRows(), kaldi::nnet2::PreconditionDirections(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), kaldi::nnet3::PrintParameterStats(), kaldi::ProcessWindow(), ArbitraryResample::Resample(), LinearResample::Resample(), kaldi::SolveDoubleQuadraticMatrixProblem(), kaldi::SolveQuadraticProblem(), OptimizeLbfgs< Real >::StepSizeIteration(), kaldi::nnet3::SummarizeVector(), kaldi::TestCuVectorVecVecOne(), kaldi::nnet3::TestNnetComponentUpdatable(), SpMatrix< float >::TopEigs(), kaldi::TraceSpSp(), kaldi::UnitTestDotprod(), kaldi::UnitTestLbfgs(), UnitTestLinearResample2(), kaldi::UnitTestSnipEdges(), kaldi::UnitTestSolve(), kaldi::UnitTestSparseVectorVecSvec(), MlltAccs::Update(), MleAmSgmm2Updater::UpdatePhoneVectorsInternal(), OnlinePitchFeatureImpl::UpdateRemainder(), MleAmSgmm2Updater::UpdateW(), MleAmSgmm2Updater::UpdateWGetStats(), MleSgmm2SpeakerAccs::UpdateWithU(), kaldi::VecMatVec(), kaldi::VecSpVec(), VectorClusterable::VectorClusterable(), and kaldi::VecVec().
{
   MatrixIndexT adim = a.Dim();
   KALDI_ASSERT(adim == b.Dim());
   return cblas_Xdot(adim, a.Data(), 1, b.Data(), 1);
 }
VecVec() [2/2]
Real VecVec (const VectorBase< Real > & ra, const VectorBase< OtherReal > & rb)
Definition at line 52 of file kaldi-vector.cc.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), rnnlm::i, and KALDI_ASSERT.
{
   MatrixIndexT adim = ra.Dim();
   KALDI_ASSERT(adim == rb.Dim());
   const Real *a_data = ra.Data();
   const OtherReal *b_data = rb.Data();
   Real sum = 0.0;
   for (MatrixIndexT i = 0; i < adim; i++)
     sum += a_data[i]*b_data[i];
   return sum;
 }