Kaldi: Some simple functions used in clustering algorithms
Some simple functions used in clustering algorithms
Classes and functions related to clustering
See Clustering mechanisms in Kaldi for context.
Functions
BaseFloat SumClusterableObjf (const std::vector< Clusterable * > &vec)
Returns the total objective function after adding up all the statistics in the vector (pointers may be NULL).
BaseFloat SumClusterableNormalizer (const std::vector< Clusterable * > &vec)
Returns the total normalizer (usually count) of the cluster (pointers may be NULL).
Clusterable * SumClusterable (const std::vector< Clusterable * > &vec)
Sums stats (ptrs may be NULL). Returns NULL if no non-NULL stats present.
void EnsureClusterableVectorNotNull (std::vector< Clusterable * > *stats)
Fills in any (NULL) holes in "stats" vector, with empty stats, because certain algorithms require non-NULL stats.
void AddToClusters (const std::vector< Clusterable * > &stats, const std::vector< int32 > &assignments, std::vector< Clusterable * > *clusters)
Given stats and a vector "assignments" of the same size (that maps to cluster indices), sums the stats up into "clusters." It will add to any stats already present in "clusters" (although typically "clusters" will be empty when called), and it will extend with NULL pointers for any unseen indices.
void AddToClustersOptimized (const std::vector< Clusterable * > &stats, const std::vector< int32 > &assignments, const Clusterable &total, std::vector< Clusterable * > *clusters)
AddToClustersOptimized does the same as AddToClusters (it sums up the stats within each cluster, except it uses the sum of all the stats ("total") to optimize the computation for speed, if possible.
Detailed Description
See Clustering mechanisms in Kaldi for context.
Function Documentation
AddToClusters()
void AddToClusters (const std::vector< Clusterable * > & stats, const std::vector< int32 > & assignments, std::vector< Clusterable * > * clusters)
Given stats and a vector "assignments" of the same size (that maps to cluster indices), sums the stats up into "clusters." It will add to any stats already present in "clusters" (although typically "clusters" will be empty when called), and it will extend with NULL pointers for any unseen indices.
Call EnsureClusterableStatsNotNull afterwards if you want to ensure all non-NULL clusters. Pointer in "clusters" are owned by caller. Pointers in "stats" do not have to be non-NULL.
Definition at line 108 of file cluster-utils.cc.
References rnnlm::i, and KALDI_ASSERT.
Referenced by kaldi::FindBestSplitForKey(), kaldi::TestAddToClusters(), and kaldi::TestAddToClustersOptimized().
{
   KALDI_ASSERT(assignments.size() == stats.size());
   int32 size = stats.size();
   if (size == 0) return;  // Nothing to do.
   KALDI_ASSERT(clusters != NULL);
   int32 max_assignment = *std::max_element(assignments.begin(),
                                            assignments.end());
   if (static_cast<int32> (clusters->size()) <= max_assignment)
     clusters->resize(max_assignment + 1, NULL);  // extend with NULLs.
   for (int32 i = 0; i < size; i++) {
     if (stats[i] != NULL) {
       if ((*clusters)[assignments[i]] == NULL)
         (*clusters)[assignments[i]] = stats[i]->Copy();
       else
         (*clusters)[assignments[i]]->Add(*(stats[i]));
     }
   }
 }
AddToClustersOptimized()
void AddToClustersOptimized (const std::vector< Clusterable * > & stats, const std::vector< int32 > & assignments, const Clusterable & total, std::vector< Clusterable * > * clusters)
AddToClustersOptimized does the same as AddToClusters (it sums up the stats within each cluster, except it uses the sum of all the stats ("total") to optimize the computation for speed, if possible.
This will generally only be a significant speedup in the case where there are just two clusters, which can happen in algorithms that are doing binary splits; the idea is that we sum up all the stats in one cluster (the one with the fewest points in it), and then subtract from the total.
Definition at line 130 of file cluster-utils.cc.
References Clusterable::Add(), kaldi::AssertEqual(), Clusterable::Copy(), rnnlm::i, KALDI_ASSERT, Clusterable::Normalizer(), and kaldi::SumClusterableNormalizer().
Referenced by kaldi::ComputeInitialSplit(), and kaldi::TestAddToClustersOptimized().
{
 #ifdef KALDI_PARANOID
   // Make sure "total" is actually the sum of stats in "stats".
   {
     BaseFloat stats_norm = SumClusterableNormalizer(stats),
     tot_norm = total.Normalizer();
     AssertEqual(stats_norm, tot_norm, 0.01);
   }
 #endif
   KALDI_ASSERT(assignments.size() == stats.size());
   int32 size = stats.size();
   if (size == 0) return;  // Nothing to do.
   KALDI_ASSERT(clusters != NULL);
   int32 num_clust = 1 + *std::max_element(assignments.begin(),
                                           assignments.end());
   if (static_cast<int32> (clusters->size()) < num_clust)
     clusters->resize(num_clust, NULL);  // extend with NULLs.
   std::vector<int32> num_stats_for_cluster(num_clust, 0);
   int32 num_total_stats = 0;
   for (int32 i = 0; i < size; i++) {
     if (stats[i] != NULL) {
       num_total_stats++;
       num_stats_for_cluster[assignments[i]]++;
     }
   }
   if (num_total_stats == 0) return;  // Nothing to do.
   //  it will only ever be efficient to subtract for at most one index.
   int32 subtract_index = -1;
   for (int32 c = 0; c < num_clust; c++) {
     if (num_stats_for_cluster[c] > num_total_stats - num_stats_for_cluster[c]) {
       subtract_index = c;
       if ((*clusters)[c] == NULL)
         (*clusters)[c] = total.Copy();
       else
         (*clusters)[c]->Add(total);
       break;
     }
   }
   for (int32 i = 0; i < size; i++) {
     if (stats[i] != NULL) {
       int32 assignment = assignments[i];
       if (assignment != (int32) subtract_index) {
         if ((*clusters)[assignment] == NULL)
           (*clusters)[assignment] = stats[i]->Copy();
         else
           (*clusters)[assignment]->Add(*(stats[i]));
       }
       if (subtract_index != -1 && assignment != subtract_index)
         (*clusters)[subtract_index]->Sub(*(stats[i]));
     }
   }
 }
EnsureClusterableVectorNotNull()
void EnsureClusterableVectorNotNull (std::vector< Clusterable * > * stats)
Fills in any (NULL) holes in "stats" vector, with empty stats, because certain algorithms require non-NULL stats.
If "stats" nonempty, requires it to contain at least one non-NULL pointer that we can call Copy() on.
Definition at line 82 of file cluster-utils.cc.
References Clusterable::Copy(), KALDI_ASSERT, KALDI_ERR, and Clusterable::SetZero().
Referenced by kaldi::AutomaticallyObtainQuestions(), kaldi::FindBestSplitForKey(), kaldi::KMeansClusterPhones(), and kaldi::TestEnsureClusterableVectorNotNull().
{
   KALDI_ASSERT(stats != NULL);
   std::vector<Clusterable*>::iterator itr = stats->begin(), end = stats->end();
   if (itr == end) return;  // Nothing to do.
   Clusterable *nonNullExample = NULL;
   for (; itr != end; ++itr) {
     if (*itr != NULL) {
       nonNullExample = *itr;
       break;
     }
   }
   if (nonNullExample == NULL) {
     KALDI_ERR << "All stats are NULL.";  // crash. logic error.
   }
   itr = stats->begin();
   Clusterable *nonNullExampleCopy = nonNullExample->Copy();
   // sets stats to zero. do this just once (on copy) for efficiency.
   nonNullExampleCopy->SetZero();
   for (; itr != end; ++itr) {
     if (*itr == NULL) {
       *itr = nonNullExampleCopy->Copy();
     }
   }
   delete nonNullExampleCopy;
 }
SumClusterable()
Clusterable * SumClusterable (const std::vector< Clusterable *> & vec)
Sums stats (ptrs may be NULL). Returns NULL if no non-NULL stats present.
Definition at line 69 of file cluster-utils.cc.
References Clusterable::Add(), Clusterable::Copy(), and rnnlm::i.
Referenced by kaldi::ClusterKMeansOnce(), kaldi::ComputeInitialSplit(), TreeClusterer::Init(), kaldi::InitAmGmm(), kaldi::TestAddToClustersOptimized(), and kaldi::TestSum().
{
   Clusterable *ans = NULL;
   for (size_t i = 0; i < vec.size(); i++) {
     if (vec[i] != NULL) {
       if (ans == NULL)
         ans = vec[i]->Copy();
       else
         ans->Add(*(vec[i]));
     }
   }
   return ans;
 }
SumClusterableNormalizer()
BaseFloat SumClusterableNormalizer (const std::vector< Clusterable *> & vec)
Returns the total normalizer (usually count) of the cluster (pointers may be NULL).
Definition at line 54 of file cluster-utils.cc.
References rnnlm::i, KALDI_ISNAN, and KALDI_WARN.
Referenced by kaldi::AddToClustersOptimized(), kaldi::ClusterEventMapGetMapping(), kaldi::ClusterEventMapToNClustersRestrictedByMap(), kaldi::ClusterKMeansOnce(), kaldi::KMeansClusterPhones(), kaldi::TestAddToClustersOptimized(), and kaldi::TestSumObjfAndSumNormalizer().
{
   BaseFloat ans = 0.0;
   for (size_t i = 0; i < vec.size(); i++) {
     if (vec[i] != NULL) {
       BaseFloat objf = vec[i]->Normalizer();
       if (KALDI_ISNAN(objf)) {
         KALDI_WARN << "SumClusterableObjf, NaN objf";
       } else {
         ans += objf;
       }
     }
   }
   return ans;
 }
SumClusterableObjf()
BaseFloat SumClusterableObjf (const std::vector< Clusterable * > & vec)
Returns the total objective function after adding up all the statistics in the vector (pointers may be NULL).
Definition at line 39 of file cluster-utils.cc.
References rnnlm::i, KALDI_ISNAN, and KALDI_WARN.
Referenced by kaldi::ClusterKMeansOnce(), kaldi::ComputeInitialSplit(), kaldi::ObjfGivenMap(), kaldi::TestClusterKMeans(), kaldi::TestClusterKMeansVector(), kaldi::TestClusterTopDown(), kaldi::TestRefineClusters(), kaldi::TestSumObjfAndSumNormalizer(), and kaldi::TestTreeCluster().
{
   BaseFloat ans = 0.0;
   for (size_t i = 0; i < vec.size(); i++) {
     if (vec[i] != NULL) {
       BaseFloat objf = vec[i]->Objf();
       if (KALDI_ISNAN(objf)) {
         KALDI_WARN << "SumClusterableObjf, NaN objf";
       } else {
         ans += objf;
       }
     }
   }
   return ans;
 }