Kaldi: "Implementation classes for Table types"
"Implementation classes for Table types"
This group is for classes that implement specific ways of reading and writing Tables; see also "Table types and related functions", "Specific Table types", "Specific Table types", and for a description of the Table concept see The Table concept.
Classes
class SequentialTableReaderImplBase< Holder >
class SequentialTableReaderScriptImpl< Holder >
class SequentialTableReaderArchiveImpl< Holder >
class SequentialTableReaderBackgroundImpl< Holder >
class TableWriterImplBase< Holder >
class TableWriterArchiveImpl< Holder >
class TableWriterScriptImpl< Holder >
class TableWriterBothImpl< Holder >
class RandomAccessTableReaderImplBase< Holder >
class RandomAccessTableReaderScriptImpl< Holder >
class RandomAccessTableReaderArchiveImplBase< Holder >
class RandomAccessTableReaderDSortedArchiveImpl< Holder >
class RandomAccessTableReaderSortedArchiveImpl< Holder >
class RandomAccessTableReaderUnsortedArchiveImpl< Holder >
Functions
SequentialTableReader (const std::string &rspecifier)
bool Open (const std::string &rspecifier)
bool Close ()
bool IsOpen () const
std::string Key ()
void FreeCurrent ()
T & Value ()
void Next ()
bool Done ()
~SequentialTableReader ()
TableWriter (const std::string &wspecifier)
bool IsOpen () const
bool Open (const std::string &wspecifier)
void Write (const std::string &key, const T &value) const
void Flush ()
bool Close ()
~TableWriter ()
RandomAccessTableReader (const std::string &rspecifier)
bool Open (const std::string &rspecifier)
bool HasKey (const std::string &key)
const T & Value (const std::string &key)
bool Close ()
~RandomAccessTableReader ()
void CheckImpl () const
void CheckImpl () const
void CheckImpl () const
RandomAccessTableReaderMapped (const std::string &table_rxfilename, const std::string &utt2spk_rxfilename)
Note: "utt2spk_rxfilename" will in the normal case be an rxfilename for an utterance to speaker map, but this code is general; it accepts a generic map.
bool Open (const std::string &table_rxfilename, const std::string &utt2spk_rxfilename)
Note: when calling Open, utt2spk_rxfilename may be empty.
bool HasKey (const std::string &key)
const T & Value (const std::string &key)
Detailed Description
This group is for classes that implement specific ways of reading and writing Tables; see also "Table types and related functions", "Specific Table types", "Specific Table types", and for a description of the Table concept see The Table concept.
Function Documentation
CheckImpl() [1/3]
void CheckImpl () const private
Definition at line 2590 of file kaldi-table-inl.h.
{
   if (!impl_) {
     KALDI_ERR << "Trying to use empty RandomAccessTableReader (perhaps you "
               << "passed the empty string as an argument to a program?)";
   }
 }
CheckImpl() [2/3]
void CheckImpl () const private
Definition at line 2582 of file kaldi-table-inl.h.
References KALDI_ERR.
Referenced by SequentialTableReader< Holder >::Close(), SequentialTableReader< Holder >::Done(), SequentialTableReader< Holder >::FreeCurrent(), SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), and SequentialTableReader< Holder >::Value().
{
   if (!impl_) {
     KALDI_ERR << "Trying to use empty SequentialTableReader (perhaps you "
               << "passed the empty string as an argument to a program?)";
   }
 }
CheckImpl() [3/3]
void CheckImpl () const private
Definition at line 2598 of file kaldi-table-inl.h.
References KALDI_ERR.
Referenced by TableWriter< Holder >::Close(), TableWriter< Holder >::Flush(), and TableWriter< Holder >::Write().
{
   if (!impl_) {
     KALDI_ERR << "Trying to use empty TableWriter (perhaps you "
               << "passed the empty string as an argument to a program?)";
   }
 }
Close() [1/3]
bool Close ()
Definition at line 2567 of file kaldi-table-inl.h.
{
   CheckImpl();
   bool ans =impl_->Close();
   delete impl_;
   impl_ = NULL;
   return ans;
 }
Close() [2/3]
bool Close ()
Definition at line 901 of file kaldi-table-inl.h.
References SequentialTableReader< Holder >::CheckImpl(), and SequentialTableReader< Holder >::impl_.
Referenced by main(), SequentialTableReader< Holder >::Open(), TableWriterArchiveImpl< Holder >::Open(), TableWriterBothImpl< Holder >::Open(), kaldi::ReadData(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), kaldi::UnitTestTableSequentialInt32VectorVectorBoth(), TableWriterArchiveImpl< Holder >::~TableWriterArchiveImpl(), and TableWriterBothImpl< Holder >::~TableWriterBothImpl().
{
   CheckImpl();
   bool ans = impl_->Close();
   delete impl_;  // We don't keep around empty impl_ objects.
   impl_ = NULL;
   return ans;
 }
Close() [3/3]
bool Close ()
Definition at line 1527 of file kaldi-table-inl.h.
References TableWriter< Holder >::CheckImpl(), and TableWriter< Holder >::impl_.
Referenced by TableWriter< Holder >::Open(), RandomAccessTableReaderArchiveImplBase< Holder >::Open(), kaldi::TestCompactLatticeTable(), kaldi::TestCompactLatticeTableCross(), kaldi::TestLatticeTable(), kaldi::TestLatticeTableCross(), kaldi::UnitTestTableRandomBothDouble(), kaldi::UnitTestTableRandomBothDoubleMatrix(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), kaldi::UnitTestTableSequentialInt32VectorVectorBoth(), RandomAccessTableReaderDSortedArchiveImpl< Holder >::~RandomAccessTableReaderDSortedArchiveImpl(), RandomAccessTableReaderSortedArchiveImpl< Holder >::~RandomAccessTableReaderSortedArchiveImpl(), RandomAccessTableReaderUnsortedArchiveImpl< Holder >::~RandomAccessTableReaderUnsortedArchiveImpl(), and TableWriter< Holder >::~TableWriter().
{
   CheckImpl();
   bool ans = impl_->Close();
   delete impl_;  // We don't keep around non-open impl_ objects
                  // [c.f. definition of IsOpen()]
   impl_ = NULL;
   return ans;
 }
Done()
bool Done () inline
Definition at line 948 of file kaldi-table-inl.h.
References SequentialTableReader< Holder >::CheckImpl(), and SequentialTableReader< Holder >::impl_.
Referenced by ComputeLogPosteriors(), ComputeScores(), CopyExcludedFeats(), CopyIncludedFeats(), kaldi::CopySubsetLattices(), kaldi::nnet2::DoBackpropParallel(), kaldi::GetEditsDualHyp(), kaldi::GetEditsSingleHyp(), kaldi::GetFeatureMeanAndVariance(), main(), kaldi::nnet2::NnetDiscriminativeUpdateParallel(), kaldi::ReadData(), NnetExampleBackgroundReader::ReadExamples(), kaldi::RunPerSpeaker(), CRnnLM::setUnkPenalty(), kaldi::TypeOneUsage(), kaldi::TypeOneUsageAverage(), kaldi::UnitTestRangesMatrix(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   return impl_->Done();
 }
Flush()
void Flush ()
Definition at line 1521 of file kaldi-table-inl.h.
References TableWriter< Holder >::CheckImpl(), and TableWriter< Holder >::impl_.
{
   CheckImpl();
   impl_->Flush();
 }
FreeCurrent()
void FreeCurrent ()
Definition at line 926 of file kaldi-table-inl.h.
References SequentialTableReader< Holder >::CheckImpl(), and SequentialTableReader< Holder >::impl_.
Referenced by main(), CRnnLM::setUnkPenalty(), kaldi::TypeOneUsage(), and kaldi::TypeOneUsageAverage().
{
   CheckImpl();
   impl_->FreeCurrent();
 }
HasKey() [1/2]
bool HasKey (const std::string & key)
Definition at line 2551 of file kaldi-table-inl.h.
Referenced by kaldi::AccCmvnStatsWrapper(), kaldi::AccMinmaxStatsWrapper(), kaldi::AccumulateForUtterance(), ComputeScores(), kaldi::GetEditsDualHyp(), kaldi::GetEditsSingleHyp(), main(), kaldi::ProcessUtterance(), kaldi::ReadData(), kaldi::RunPerSpeaker(), kaldi::UnitTestRangesMatrix(), kaldi::UnitTestTableRandomBothDouble(), and kaldi::UnitTestTableRandomBothDoubleMatrix().
{
   CheckImpl();
   if (!IsToken(key))
     KALDI_ERR << "Invalid key \"" << key << '"';
   return impl_->HasKey(key);
 }
HasKey() [2/2]
bool HasKey (const std::string & key)
Definition at line 2633 of file kaldi-table-inl.h.
References KALDI_ERR, kaldi::PrintableRxfilename(), RandomAccessTableReaderMapped< Holder >::reader_, RandomAccessTableReaderMapped< Holder >::token_reader_, and RandomAccessTableReaderMapped< Holder >::utt2spk_rxfilename_.
Referenced by main(), and kaldi::ProcessUtterance().
{
   // We don't check IsOpen, we let the call go through to the member variable
   // (reader_), which will crash with a more informative error message than
   // we can give here, as we don't any longer know the rxfilename.
   if (token_reader_.IsOpen()) {  // We need to map the key from utt to spk.
     if (!token_reader_.HasKey(utt))
       KALDI_ERR << "Attempting to read key " << utt << ", which is not present "
                 << "in utt2spk map or similar map being read from "
                 << PrintableRxfilename(utt2spk_rxfilename_);
     const std::string &spk = token_reader_.Value(utt);
     return reader_.HasKey(spk);
   } else {
     return reader_.HasKey(utt);
   }
 }
IsOpen() [1/2]
bool IsOpen () const
Definition at line 911 of file kaldi-table-inl.h.
References SequentialTableReader< Holder >::impl_.
Referenced by TableWriterArchiveImpl< Holder >::Close(), TableWriterScriptImpl< Holder >::Close(), TableWriterBothImpl< Holder >::Close(), SequentialTableReader< Holder >::Open(), TableWriterScriptImpl< Holder >::Write(), TableWriterArchiveImpl< Holder >::~TableWriterArchiveImpl(), and TableWriterBothImpl< Holder >::~TableWriterBothImpl().
{
   return (impl_ != NULL);  // Because we delete the object whenever
   // that object is not open.  Thus, the IsOpen functions of the
   // Impl objects are not really needed.
 }
IsOpen() [2/2]
bool IsOpen () const
Definition at line 1474 of file kaldi-table-inl.h.
References TableWriter< Holder >::impl_.
Referenced by kaldi::AlignUtteranceWrapper(), RandomAccessTableReaderScriptImpl< Holder >::Close(), RandomAccessTableReaderArchiveImplBase< Holder >::CloseInternal(), kaldi::DecodeUtterance(), DecodeUtterance(), kaldi::DecodeUtteranceLatticeFaster(), kaldi::DecodeUtteranceLatticeSimple(), main(), TableWriter< Holder >::Open(), DecodeUtteranceLatticeFasterClass::~DecodeUtteranceLatticeFasterClass(), RandomAccessTableReaderDSortedArchiveImpl< Holder >::~RandomAccessTableReaderDSortedArchiveImpl(), RandomAccessTableReaderSortedArchiveImpl< Holder >::~RandomAccessTableReaderSortedArchiveImpl(), RandomAccessTableReaderUnsortedArchiveImpl< Holder >::~RandomAccessTableReaderUnsortedArchiveImpl(), and TableWriter< Holder >::~TableWriter().
{
   return (impl_ != NULL);
 }
Key()
std::string Key () inline
Definition at line 918 of file kaldi-table-inl.h.
References SequentialTableReader< Holder >::CheckImpl(), and SequentialTableReader< Holder >::impl_.
Referenced by ComputeLogPosteriors(), ComputeScores(), CopyExcludedFeats(), CopyIncludedFeats(), kaldi::CopySubsetLattices(), kaldi::GetEditsDualHyp(), kaldi::GetEditsSingleHyp(), main(), kaldi::ReadData(), kaldi::RunPerSpeaker(), CRnnLM::setUnkPenalty(), kaldi::TypeOneUsage(), kaldi::TypeOneUsageAverage(), kaldi::UnitTestRangesMatrix(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   return impl_->Key();  // this call may throw if called wrongly in other ways,
   // e.g. eof.
 }
Next()
void Next ()
Definition at line 942 of file kaldi-table-inl.h.
References SequentialTableReader< Holder >::CheckImpl(), and SequentialTableReader< Holder >::impl_.
Referenced by ComputeLogPosteriors(), ComputeScores(), CopyExcludedFeats(), CopyIncludedFeats(), kaldi::CopySubsetLattices(), kaldi::nnet2::DoBackpropParallel(), kaldi::GetEditsDualHyp(), kaldi::GetEditsSingleHyp(), kaldi::GetFeatureMeanAndVariance(), main(), kaldi::nnet2::NnetDiscriminativeUpdateParallel(), kaldi::ReadData(), NnetExampleBackgroundReader::ReadExamples(), kaldi::RunPerSpeaker(), CRnnLM::setUnkPenalty(), kaldi::TypeOneUsage(), kaldi::TypeOneUsageAverage(), kaldi::UnitTestRangesMatrix(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   impl_->Next();
 }
Open() [1/4]
bool Open (const std::string & rspecifier)
Definition at line 2517 of file kaldi-table-inl.h.
Referenced by main().
{
   if (IsOpen())
     KALDI_ERR << "Already open.";
   RspecifierOptions opts;
   RspecifierType rs = ClassifyRspecifier(rspecifier, NULL, &opts);
   switch (rs) {
     case kScriptRspecifier:
       impl_ = new RandomAccessTableReaderScriptImpl<Holder>();
       break;
     case kArchiveRspecifier:
       if (opts.sorted) {
         if (opts.called_sorted)  // "doubly" sorted case.
           impl_ = new RandomAccessTableReaderDSortedArchiveImpl<Holder>();
         else
           impl_ = new RandomAccessTableReaderSortedArchiveImpl<Holder>();
       } else {
         impl_ = new RandomAccessTableReaderUnsortedArchiveImpl<Holder>();
       }
       break;
     case kNoRspecifier: default:
       KALDI_WARN << "Invalid rspecifier: "
                  << rspecifier;
       return false;
   }
   if (!impl_->Open(rspecifier)) {
     // A warning will already have been printed.
     delete impl_;
     impl_ = NULL;
     return false;
   }
   return true;
 }
Open() [2/4]
bool Open (const std::string & rspecifier)
Definition at line 864 of file kaldi-table-inl.h.
References RspecifierOptions::background, kaldi::ClassifyRspecifier(), SequentialTableReader< Holder >::Close(), SequentialTableReader< Holder >::impl_, SequentialTableReader< Holder >::IsOpen(), KALDI_ERR, KALDI_WARN, kaldi::kArchiveRspecifier, kaldi::kNoRspecifier, and kaldi::kScriptRspecifier.
Referenced by main(), and SequentialTableReader< Holder >::SequentialTableReader().
{
   if (IsOpen())
     if (!Close())
       KALDI_ERR << "Could not close previously open object.";
   // now impl_ will be NULL.
   RspecifierOptions opts;
   RspecifierType wt = ClassifyRspecifier(rspecifier, NULL, &opts);
   switch (wt) {
     case kArchiveRspecifier:
       impl_ = new SequentialTableReaderArchiveImpl<Holder>();
       break;
     case kScriptRspecifier:
       impl_ = new SequentialTableReaderScriptImpl<Holder>();
       break;
     case kNoRspecifier: default:
       KALDI_WARN << "Invalid rspecifier " << rspecifier;
       return false;
   }
   if (!impl_->Open(rspecifier)) {
     delete impl_;
     impl_ = NULL;
     return false;  // sub-object will have printed warnings.
   }
   if (opts.background) {
     impl_ = new SequentialTableReaderBackgroundImpl<Holder>(
         impl_);
     if (!impl_->Open("")) {
       // the rxfilename is ignored in that Open() call.
       // It should only return false on code error.
       return false;
     }
   }
   return true;
 }
Open() [3/4]
bool Open (const std::string & wspecifier)
Definition at line 1480 of file kaldi-table-inl.h.
References kaldi::ClassifyWspecifier(), TableWriter< Holder >::Close(), TableWriter< Holder >::impl_, TableWriter< Holder >::IsOpen(), KALDI_ASSERT, KALDI_ERR, KALDI_WARN, kaldi::kArchiveWspecifier, kaldi::kBothWspecifier, kaldi::kNoWspecifier, and kaldi::kScriptWspecifier.
Referenced by main(), and TableWriter< Holder >::TableWriter().
{
   if (IsOpen()) {
     if (!Close())  // call Close() yourself to suppress this exception.
       KALDI_ERR << "Failed to close previously open writer.";
   }
   KALDI_ASSERT(impl_ == NULL);
   WspecifierType wtype = ClassifyWspecifier(wspecifier, NULL, NULL, NULL);
   switch (wtype) {
     case kBothWspecifier:
       impl_ = new TableWriterBothImpl<Holder>();
       break;
     case kArchiveWspecifier:
       impl_ = new TableWriterArchiveImpl<Holder>();
       break;
     case kScriptWspecifier:
       impl_ = new TableWriterScriptImpl<Holder>();
       break;
     case kNoWspecifier: default:
       KALDI_WARN << "ClassifyWspecifier: invalid wspecifier " << wspecifier;
       return false;
   }
   if (impl_->Open(wspecifier)) {
     return true;
   } else {  // The class will have printed a more specific warning.
     delete impl_;
     impl_ = NULL;
     return false;
   }
 }
Open() [4/4]
bool Open (const std::string & table_rxfilename, const std::string & utt2spk_rxfilename)
Note: when calling Open, utt2spk_rxfilename may be empty.
Definition at line 2614 of file kaldi-table-inl.h.
References KALDI_ASSERT, RandomAccessTableReaderMapped< Holder >::reader_, and RandomAccessTableReaderMapped< Holder >::token_reader_.
Referenced by main().
{
   if (reader_.IsOpen()) reader_.Close();
   if (token_reader_.IsOpen()) token_reader_.Close();
   KALDI_ASSERT(!table_rxfilename.empty());
   if (!reader_.Open(table_rxfilename)) return false;  // will have printed
   // warning internally, probably.
   if (!utt2spk_rxfilename.empty()) {
     if (!token_reader_.Open(utt2spk_rxfilename)) {
       reader_.Close();
       return false;
     }
   }
   return true;
 }
RandomAccessTableReader()
RandomAccessTableReader (const std::string & rspecifier) explicit
Definition at line 2508 of file kaldi-table-inl.h.
                                                                              :
     impl_(NULL) {
   if (rspecifier != "" && !Open(rspecifier))
     KALDI_ERR << "Error opening RandomAccessTableReader object "
         " (rspecifier is: " << rspecifier << ")";
 }
RandomAccessTableReaderMapped()
RandomAccessTableReaderMapped (const std::string & table_rxfilename, const std::string & utt2spk_rxfilename)
Note: "utt2spk_rxfilename" will in the normal case be an rxfilename for an utterance to speaker map, but this code is general; it accepts a generic map.
Definition at line 2606 of file kaldi-table-inl.h.
                                         :
     reader_(table_rxfilename), token_reader_(table_rxfilename.empty() ? "" :
                                              utt2spk_rxfilename),
     utt2spk_rxfilename_(utt2spk_rxfilename) { }
SequentialTableReader()
SequentialTableReader (const std::string & rspecifier) explicit
Definition at line 857 of file kaldi-table-inl.h.
References KALDI_ERR, and SequentialTableReader< Holder >::Open().
                                                                  : impl_(NULL) {
   if (rspecifier != "" && !Open(rspecifier))
     KALDI_ERR << "Error constructing TableReader: rspecifier is " << rspecifier;
 }
TableWriter()
TableWriter (const std::string & wspecifier) explicit
Definition at line 1467 of file kaldi-table-inl.h.
References KALDI_ERR, and TableWriter< Holder >::Open().
                                                            : impl_(NULL) {
   if (wspecifier != "" && !Open(wspecifier))
     KALDI_ERR << "Failed to open table for writing with wspecifier: " << wspecifier
               << ": errno (in case it's relevant) is: " << strerror(errno);
 }
Value() [1/3]
const RandomAccessTableReader< Holder >::T & Value (const std::string & key)
Definition at line 2561 of file kaldi-table-inl.h.
Referenced by kaldi::AccCmvnStatsWrapper(), kaldi::AccMinmaxStatsWrapper(), kaldi::AccumulateForUtterance(), ComputeScores(), kaldi::GetEditsDualHyp(), kaldi::GetEditsSingleHyp(), main(), kaldi::ProcessUtterance(), kaldi::ReadData(), kaldi::RunPerSpeaker(), kaldi::TestCompactLatticeTable(), kaldi::TestCompactLatticeTableCross(), kaldi::TestLatticeTable(), kaldi::TestLatticeTableCross(), kaldi::UnitTestRangesMatrix(), kaldi::UnitTestTableRandomBothDouble(), and kaldi::UnitTestTableRandomBothDoubleMatrix().
{
   CheckImpl();
   return impl_->Value(key);
 }
Value() [2/3]
SequentialTableReader< Holder >::T & Value ()
Definition at line 934 of file kaldi-table-inl.h.
References SequentialTableReader< Holder >::CheckImpl(), and SequentialTableReader< Holder >::impl_.
Referenced by ComputeLogPosteriors(), ComputeScores(), CopyExcludedFeats(), CopyIncludedFeats(), kaldi::CopySubsetLattices(), kaldi::nnet2::DoBackpropParallel(), kaldi::GetEditsDualHyp(), kaldi::GetEditsSingleHyp(), kaldi::GetFeatureMeanAndVariance(), main(), kaldi::nnet2::NnetDiscriminativeUpdateParallel(), kaldi::ReadData(), NnetExampleBackgroundReader::ReadExamples(), kaldi::RunPerSpeaker(), CRnnLM::setUnkPenalty(), kaldi::TypeOneUsage(), kaldi::TypeOneUsageAverage(), kaldi::UnitTestRangesMatrix(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   return impl_->Value();  // This may throw (if EnsureObjectLoaded() returned false you
                           // are safe.).
 }
Value() [3/3]
const Holder::T & Value (const std::string & key)
Definition at line 2650 of file kaldi-table-inl.h.
References KALDI_ERR, kaldi::PrintableRxfilename(), RandomAccessTableReaderMapped< Holder >::reader_, RandomAccessTableReaderMapped< Holder >::token_reader_, and RandomAccessTableReaderMapped< Holder >::utt2spk_rxfilename_.
Referenced by main(), and kaldi::ProcessUtterance().
{
   if (token_reader_.IsOpen()) {  // We need to map the key from utt to spk.
     if (!token_reader_.HasKey(utt))
       KALDI_ERR << "Attempting to read key " << utt << ", which is not present "
                 << "in utt2spk map or similar map being read from "
                 << PrintableRxfilename(utt2spk_rxfilename_);
     const std::string &spk = token_reader_.Value(utt);
     return reader_.Value(spk);
   } else {
     return reader_.Value(utt);
   }
 }
Write()
void Write (const std::string & key, const T & value) const inline
Definition at line 1511 of file kaldi-table-inl.h.
References TableWriter< Holder >::CheckImpl(), TableWriter< Holder >::impl_, and KALDI_ERR.
Referenced by kaldi::AlignUtteranceWrapper(), ComputeLogPosteriors(), CopyExcludedFeats(), CopyIncludedFeats(), kaldi::CopySubsetLattices(), kaldi::DecodeUtterance(), DecodeUtterance(), kaldi::DecodeUtteranceLatticeFaster(), kaldi::DecodeUtteranceLatticeSimple(), main(), OutputDetailedStatistics(), kaldi::nnet2::ProcessFile(), kaldi::nnet3::ProcessFile(), kaldi::RunPerSpeaker(), kaldi::TestCompactLatticeTable(), kaldi::TestCompactLatticeTableCross(), kaldi::TestLatticeTable(), kaldi::TestLatticeTableCross(), kaldi::TypeOneUsage(), kaldi::TypeOneUsageAverage(), kaldi::UnitTestRangesMatrix(), kaldi::UnitTestTableRandomBothDouble(), kaldi::UnitTestTableRandomBothDoubleMatrix(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), kaldi::UnitTestTableSequentialInt32VectorVectorBoth(), DiscriminativeExampleMerger::WriteMinibatch(), ChainExampleMerger::WriteMinibatch(), ExampleMerger::WriteMinibatch(), DecodeUtteranceLatticeFasterClass::~DecodeUtteranceLatticeFasterClass(), DeterminizeLatticeTask::~DeterminizeLatticeTask(), and IvectorExtractTask::~IvectorExtractTask().
{
   CheckImpl();
   if (!impl_->Write(key, value))
     KALDI_ERR << "Error in TableWriter::Write";
   // More specific warning will have
   // been printed in the Write function.
 }
~RandomAccessTableReader()
~RandomAccessTableReader ()
Definition at line 2576 of file kaldi-table-inl.h.
{
   if (IsOpen() && !Close())  // call Close() yourself to stop this being thrown.
     KALDI_ERR << "failure detected in destructor.";
 }
~SequentialTableReader()
~SequentialTableReader ()
Definition at line 955 of file kaldi-table-inl.h.
References SequentialTableReader< Holder >::impl_.
{
   delete impl_;
   // Destructor of impl_ may throw.
 }
~TableWriter()
~TableWriter ()
Definition at line 1537 of file kaldi-table-inl.h.
References TableWriter< Holder >::Close(), TableWriter< Holder >::IsOpen(), and KALDI_ERR.
{
   if (IsOpen() && !Close()) {
     KALDI_ERR << "Error closing TableWriter [in destructor].";
   }
 }