Kaldi: "Low-level I/O functions"
"Low-level I/O functions"
These functions are provided to write fundamental types, strings, and a few STL types to and from C++ streams; see Input/output mechanisms for fundamental types and STL types for how this fits into the bigger picture of Kaldi-style I/O.
Functions
template<class T >
void WriteBasicType (std::ostream &os, bool binary, T t)
WriteBasicType is the name of the write function for bool, integer types, and floating-point types.
template<class T >
void ReadBasicType (std::istream &is, bool binary, T *t)
ReadBasicType is the name of the read function for bool, integer types, and floating-point types.
template<>
void WriteBasicType< bool > (std::ostream &os, bool binary, bool b)
template<>
void ReadBasicType< bool > (std::istream &is, bool binary, bool *b)
template<>
void WriteBasicType< float > (std::ostream &os, bool binary, float f)
template<>
void WriteBasicType< double > (std::ostream &os, bool binary, double f)
template<>
void ReadBasicType< float > (std::istream &is, bool binary, float *f)
template<>
void ReadBasicType< double > (std::istream &is, bool binary, double *d)
template<class T >
void ReadBasicType (std::istream &is, bool binary, T *t, bool add)
template<class T >
void WriteIntegerVector (std::ostream &os, bool binary, const std::vector< T > &v)
Function for writing STL vectors of integer types.
template<class T >
void ReadIntegerVector (std::istream &is, bool binary, std::vector< T > *v)
Function for reading STL vector of integer types.
template<class T >
void WriteIntegerPairVector (std::ostream &os, bool binary, const std::vector< std::pair< T, T > > &v)
Function for writing STL vectors of pairs of integer types.
template<class T >
void ReadIntegerPairVector (std::istream &is, bool binary, std::vector< std::pair< T, T > > *v)
Function for reading STL vector of pairs of integer types.
void WriteToken (std::ostream &os, bool binary, const char *token)
The WriteToken functions are for writing nonempty sequences of non-space characters.
void WriteToken (std::ostream &os, bool binary, const std::string &token)
int Peek (std::istream &is, bool binary)
Peek consumes whitespace (if binary == false) and then returns the peek() value of the stream.
void ReadToken (std::istream &is, bool binary, std::string *token)
ReadToken gets the next token and puts it in str (exception on failure).
int PeekToken (std::istream &is, bool binary)
PeekToken will return the first character of the next token, or -1 if end of file.
void ExpectToken (std::istream &is, bool binary, const char *token)
ExpectToken tries to read in the given token, and throws an exception on failure.
void ExpectToken (std::istream &is, bool binary, const std::string &token)
void ExpectPretty (std::istream &is, bool binary, const char *token)
ExpectPretty attempts to read the text in "token", but only in non-binary mode.
void ExpectPretty (std::istream &is, bool binary, const std::string &token)
Detailed Description
These functions are provided to write fundamental types, strings, and a few STL types to and from C++ streams; see Input/output mechanisms for fundamental types and STL types for how this fits into the bigger picture of Kaldi-style I/O.
Function Documentation
ExpectPretty() [1/2]
void kaldi::ExpectPretty (std::istream & is, bool binary, const char * token)
ExpectPretty attempts to read the text in "token", but only in non-binary mode.
Throws exception on failure. It expects an exact match except that arbitrary whitespace matches arbitrary whitespace.
Referenced by kaldi::ReadBasicType().
ExpectPretty() [2/2]
void kaldi::ExpectPretty (std::istream & is, bool binary, const std::string & token)
ExpectToken() [1/2]
void ExpectToken (std::istream & is, bool binary, const char * token)
ExpectToken tries to read in the given token, and throws an exception on failure.
Definition at line 194 of file io-funcs.cc.
References kaldi::CheckToken(), KALDI_ASSERT, and KALDI_ERR.
Referenced by kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), Component::Init(), AccumAmDiagGmm::Read(), AffineXformStats::Read(), CompressedAffineXformStats::Read(), MlltAccs::Read(), ScalarClusterable::Read(), NnetExample::Read(), RegressionTree::Read(), QuestionsForKey::Read(), CuBlockMatrix< Real >::Read(), RegtreeMllrDiagGmm::Read(), LogisticRegression::Read(), LinearVtln::Read(), AmDiagGmm::Read(), ContextDependency::Read(), BasisFmllrAccus::Read(), AccumFullGmm::Read(), LdaEstimate::Read(), RegtreeFmllrDiagGmm::Read(), Sgmm2FmllrGlobalParams::Read(), GaussClusterable::Read(), SparseVector< Real >::Read(), AccumDiagGmm::Read(), BasisFmllrEstimate::Read(), Questions::Read(), RegtreeMllrDiagGmmAccs::Read(), FmllrSgmm2Accs::Read(), DiscriminativeSupervision::Read(), MleAmSgmm2Accs::Read(), TransitionModel::Read(), FullGmm::Read(), HmmTopology::Read(), RefineClustersOptions::Read(), Plda::Read(), VectorClusterable::Read(), GrammarFst::Read(), Component::Read(), EventMap::Read(), DiagGmm::Read(), DiscriminativeNnetExample::Read(), RegtreeFmllrDiagGmmAccs::Read(), SparseMatrix< float >::Read(), ConstantEventMap::Read(), Nnet::Read(), AmSgmm2::Read(), IvectorExtractor::Read(), TableEventMap::Read(), OnlineCmvnState::Read(), SplitEventMap::Read(), OnlineIvectorEstimationStats::Read(), NonlinearComponent::Read(), MaxoutComponent::Read(), IvectorExtractorStats::Read(), MaxpoolingComponent::Read(), PnormComponent::Read(), Sgmm2GauPost::Read(), PowerComponent::Read(), ScaleComponent::Read(), AffineComponent::Read(), AffineComponentPreconditioned::Read(), AffineComponentPreconditionedOnline::Read(), SpliceComponent::Read(), SpliceMaxComponent::Read(), BlockAffineComponent::Read(), BlockAffineComponentPreconditioned::Read(), PermuteComponent::Read(), DctComponent::Read(), FixedLinearComponent::Read(), FixedAffineComponent::Read(), FixedScaleComponent::Read(), FixedBiasComponent::Read(), DropoutComponent::Read(), AdditiveNoiseComponent::Read(), Convolutional1dComponent::Read(), kaldi::ReadBasicType(), kaldi::ReadBuildTreeStats(), AveragePoolingComponent::ReadData(), MaxPoolingComponent::ReadData(), ParametricRelu::ReadData(), SimpleSentenceAveragingComponent::ReadData(), AveragePooling2DComponent::ReadData(), AffineTransform::ReadData(), MaxPooling2DComponent::ReadData(), RecurrentComponent::ReadData(), LinearTransform::ReadData(), LstmProjected::ReadData(), ParallelComponent::ReadData(), FramePoolingComponent::ReadData(), ConvolutionalComponent::ReadData(), BlstmProjected::ReadData(), MultiBasisComponent::ReadData(), Convolutional2DComponent::ReadData(), Dropout::ReadData(), AddShift::ReadData(), Rescale::ReadData(), kaldi::ReadEventType(), ConstArpaLm::ReadInternal(), TreeRenderer::Render(), TreeRenderer::RenderConstant(), TreeRenderer::RenderSplit(), TreeRenderer::RenderSubTree(), TreeRenderer::RenderTable(), kaldi::UnitTestIo(), kaldi::UnitTestIoNew(), and kaldi::UnitTestIoPipe().
{
   int pos_at_start = is.tellg();
   KALDI_ASSERT(token != NULL);
   CheckToken(token);  // make sure it's valid (can be read back)
   if (!binary) is >> std::ws;  // consume whitespace.
   std::string str;
   is >> str;
   is.get();  // consume the space.
   if (is.fail()) {
     KALDI_ERR << "Failed to read token [started at file position "
               << pos_at_start << "], expected " << token;
   }
   // The second half of the '&&' expression below is so that if we're expecting
   // "<Foo>", we will accept "Foo>" instead.  This is so that the model-reading
   // code will tolerate errors in PeekToken where is.unget() failed; search for
   // is.clear() in PeekToken() for an explanation.
   if (strcmp(str.c_str(), token) != 0 &&
       !(token[0] == '<' && strcmp(str.c_str(), token + 1) == 0)) {
     KALDI_ERR << "Expected token \"" << token << "\", got instead \""
               << str <<"\".";
   }
 }
ExpectToken() [2/2]
void ExpectToken (std::istream & is, bool binary, const std::string & token)
Definition at line 217 of file io-funcs.cc.
References kaldi::ExpectToken().
{
   ExpectToken(is, binary, token.c_str());
 }
Peek()
int Peek (std::istream & is, bool binary)
Peek consumes whitespace (if binary == false) and then returns the peek() value of the stream.
Definition at line 145 of file io-funcs.cc.
Referenced by CuBlockMatrix< Real >::Read(), CompressedMatrix::Read(), PackedMatrix< float >::Read(), Component::Read(), EventMap::Read(), Vector< float >::Read(), Matrix< BaseFloat >::Read(), kaldi::ReadBasicType(), ParametricRelu::ReadData(), AffineTransform::ReadData(), SimpleSentenceAveragingComponent::ReadData(), RecurrentComponent::ReadData(), LinearTransform::ReadData(), LstmProjected::ReadData(), BlstmProjected::ReadData(), MultiBasisComponent::ReadData(), Dropout::ReadData(), AddShift::ReadData(), Rescale::ReadData(), TreeRenderer::RenderSubTree(), kaldi::UnitTestIo(), kaldi::UnitTestIoNew(), and kaldi::UnitTestIoPipe().
{
   if (!binary) is >> std::ws;  // eat up whitespace.
   return is.peek();
 }
PeekToken()
int PeekToken (std::istream & is, bool binary)
PeekToken will return the first character of the next token, or -1 if end of file.
It's the same as Peek(), except if the first character is '<' it will skip over it and will return the next character. It will unget the '<' so the stream is where it was before you did PeekToken().
Definition at line 170 of file io-funcs.cc.
References KALDI_WARN.
Referenced by NnetOptimizeOptions::Read(), Component::Read(), Nnet::Read(), AffineComponent::Read(), BlockAffineComponent::Read(), RepeatedAffineComponent::Read(), NonlinearComponent::Read(), DropoutMaskComponent::Read(), NaturalGradientAffineComponent::Read(), GeneralDropoutComponent::Read(), LinearComponent::Read(), NoOpComponent::Read(), PerElementScaleComponent::Read(), PerElementOffsetComponent::Read(), kaldi::ReadBasicType(), ParametricRelu::ReadData(), AffineTransform::ReadData(), SimpleSentenceAveragingComponent::ReadData(), RecurrentComponent::ReadData(), LinearTransform::ReadData(), LstmProjected::ReadData(), ConvolutionalComponent::ReadData(), BlstmProjected::ReadData(), MultiBasisComponent::ReadData(), Dropout::ReadData(), kaldi::UnitTestIo(), and kaldi::UnitTestIoPipe().
{
   if (!binary) is >> std::ws;  // consume whitespace.
   bool read_bracket;
   if (static_cast<char>(is.peek()) == '<') {
     read_bracket = true;
     is.get();
   } else {
     read_bracket = false;
   }
   int ans = is.peek();
   if (read_bracket) {
     if (!is.unget()) {
       KALDI_WARN << "Error ungetting '<' in PeekToken";
       // Clear the bad bit.  It seems to be possible for this code to be
       // reached, and the C++ standard is very vague on whether even a single
       // call to unget() should succeed; see
       // http://www.cplusplus.com/reference/istream/istream/unget/
       is.clear();
     }
   }
   return ans;
 }
ReadBasicType() [1/2]
void ReadBasicType (std::istream & is, bool binary, T * t) inline
ReadBasicType is the name of the read function for bool, integer types, and floating-point types.
They all throw on error.
Definition at line 55 of file io-funcs-inl.h.
References rnnlm::i, KALDI_ASSERT_IS_INTEGER_TYPE, KALDI_ERR, and KALDI_PARANOID_ASSERT.
Referenced by Component::Init(), AffineTransform::InitData(), LinearTransform::InitData(), MultiBasisComponent::InitData(), ParametricRelu::InitData(), AveragePoolingComponent::InitData(), MaxPoolingComponent::InitData(), RecurrentComponent::InitData(), AveragePooling2DComponent::InitData(), MaxPooling2DComponent::InitData(), FramePoolingComponent::InitData(), SimpleSentenceAveragingComponent::InitData(), LstmProjected::InitData(), BlstmProjected::InitData(), ConvolutionalComponent::InitData(), Convolutional2DComponent::InitData(), Rbm::InitData(), SentenceAveragingComponent::InitData(), Dropout::InitData(), AddShift::InitData(), Rescale::InitData(), AccumAmDiagGmm::Read(), AffineXformStats::Read(), CompressedAffineXformStats::Read(), MlltAccs::Read(), ScalarClusterable::Read(), NnetExample::Read(), RegressionTree::Read(), AmNnetSimple::Read(), QuestionsForKey::Read(), CuBlockMatrix< Real >::Read(), RegtreeMllrDiagGmm::Read(), LinearVtln::Read(), AmDiagGmm::Read(), Index::Read(), DistributeComponent::Read(), ContextDependency::Read(), FmpeOptions::Read(), BasisFmllrAccus::Read(), AccumFullGmm::Read(), LdaEstimate::Read(), RegtreeFmllrDiagGmm::Read(), Sgmm2FmllrGlobalParams::Read(), IoSpecification::Read(), GaussClusterable::Read(), NormalizeComponent::Read(), SparseVector< Real >::Read(), GaussPostHolder::Read(), AccumDiagGmm::Read(), NnetDiscriminativeExample::Read(), BasisFmllrEstimate::Read(), Questions::Read(), NnetChainExample::Read(), RegtreeMllrDiagGmmAccs::Read(), FmllrSgmm2Accs::Read(), DiscriminativeSupervision::Read(), MleAmSgmm2Accs::Read(), TransitionModel::Read(), HmmTopology::Read(), RefineClustersOptions::Read(), VectorClusterable::Read(), BasicHolder< BasicType >::Read(), PackedMatrix< float >::Read(), NnetOptimizeOptions::Read(), RestrictedAttentionComponent::Read(), ComputationRequest::Read(), GrammarFst::Read(), Component::Read(), DiscriminativeNnetExample::Read(), RegtreeFmllrDiagGmmAccs::Read(), ElementwiseProductComponent::Read(), SparseMatrix< float >::Read(), ConstantEventMap::Read(), BatchNormComponent::Read(), StatisticsExtractionComponent::Read(), Nnet::Read(), AmSgmm2::Read(), ConvolutionModel::Read(), TimeHeightConvolutionComponent::Read(), IvectorExtractor::Read(), TableEventMap::Read(), BasicVectorHolder< BasicType >::Read(), SplitEventMap::Read(), NnetComputation::MatrixInfo::Read(), NnetComputation::MatrixDebugInfo::Read(), NnetComputation::SubMatrixInfo::Read(), ConvolutionComputation::Read(), NnetComputation::Command::Read(), OnlineIvectorEstimationStats::Read(), NonlinearComponent::Read(), StatisticsPoolingComponent::Read(), BasicVectorVectorHolder< BasicType >::Read(), ConvolutionComputationIo::Read(), MaxoutComponent::Read(), Vector< float >::Read(), NnetComputation::Read(), TdnnComponent::Read(), IvectorExtractorStats::Read(), MaxpoolingComponent::Read(), BackpropTruncationComponent::Read(), TdnnComponent::PrecomputedIndexes::Read(), BasicPairVectorHolder< BasicType >::Read(), PnormComponent::Read(), Sgmm2GauPost::Read(), BackpropTruncationComponentPrecomputedIndexes::Read(), RepeatedAffineComponent::Read(), ComputationCache::Read(), ConstantComponent::Read(), PowerComponent::Read(), DropoutMaskComponent::Read(), ScaleComponent::Read(), NaturalGradientAffineComponent::Read(), Matrix< BaseFloat >::Read(), GeneralDropoutComponent::Read(), AffineComponent::Read(), GeneralDropoutComponentPrecomputedIndexes::Read(), LinearComponent::Read(), AffineComponentPreconditioned::Read(), AffineComponentPreconditionedOnline::Read(), SpliceComponent::Read(), SpliceMaxComponent::Read(), NoOpComponent::Read(), BlockAffineComponent::Read(), SumBlockComponent::Read(), BlockAffineComponentPreconditioned::Read(), ClipGradientComponent::Read(), DctComponent::Read(), PerElementScaleComponent::Read(), DropoutComponent::Read(), PerElementOffsetComponent::Read(), AdditiveNoiseComponent::Read(), ConstantFunctionComponent::Read(), Convolutional1dComponent::Read(), NaturalGradientPerElementScaleComponent::Read(), ScaleAndOffsetComponent::Read(), ConvolutionComponent::Read(), LstmNonlinearityComponent::Read(), CompositeComponent::Read(), kaldi::ReadBasicType(), kaldi::ReadBasicType< double >(), kaldi::ReadBasicType< float >(), kaldi::ReadBuildTreeStats(), kaldi::nnet3::ReadCindexVector(), kaldi::nnet3::ReadCindexVectorElementBinary(), AveragePoolingComponent::ReadData(), MaxPoolingComponent::ReadData(), ParametricRelu::ReadData(), AveragePooling2DComponent::ReadData(), AffineTransform::ReadData(), SimpleSentenceAveragingComponent::ReadData(), MaxPooling2DComponent::ReadData(), RecurrentComponent::ReadData(), LinearTransform::ReadData(), LstmProjected::ReadData(), ParallelComponent::ReadData(), FramePoolingComponent::ReadData(), ConvolutionalComponent::ReadData(), BlstmProjected::ReadData(), MultiBasisComponent::ReadData(), Convolutional2DComponent::ReadData(), Dropout::ReadData(), AddShift::ReadData(), Rescale::ReadData(), kaldi::ReadEventType(), fst::ReadILabelInfo(), kaldi::nnet3::ReadIndexVector(), kaldi::nnet3::ReadIndexVectorElementBinary(), ConstArpaLm::ReadInternal(), ConstArpaLm::ReadInternalOldFormat(), kaldi::ReadPosterior(), UpdatableComponent::ReadUpdatableCommon(), TreeRenderer::Render(), TreeRenderer::RenderConstant(), TreeRenderer::RenderSplit(), TreeRenderer::RenderTable(), kaldi::UnitTestIo(), kaldi::UnitTestIoNew(), and kaldi::UnitTestIoPipe().
{
   KALDI_PARANOID_ASSERT(t != NULL);
   // Compile time assertion that this is not called with a wrong type.
   KALDI_ASSERT_IS_INTEGER_TYPE(T);
   if (binary) {
     int len_c_in = is.get();
     if (len_c_in == -1)
       KALDI_ERR << "ReadBasicType: encountered end of stream.";
     char len_c = static_cast<char>(len_c_in), len_c_expected
       = (std::numeric_limits<T>::is_signed ? 1 :  -1)
       * static_cast<char>(sizeof(*t));
     if (len_c !=  len_c_expected) {
       KALDI_ERR << "ReadBasicType: did not get expected integer type, "
                 << static_cast<int>(len_c)
                 << " vs. " << static_cast<int>(len_c_expected)
                 << ".  You can change this code to successfully"
                 << " read it later, if needed.";
       // insert code here to read "wrong" type.  Might have a switch statement.
     }
     is.read(reinterpret_cast<char *>(t), sizeof(*t));
   } else {
     if (sizeof(*t) == 1) {
       int16 i;
       is >> i;
       *t = i;
     } else {
       is >> *t;
     }
   }
   if (is.fail()) {
     KALDI_ERR << "Read failure in ReadBasicType, file position is "
               << is.tellg() << ", next char is " << is.peek();
   }
 }
ReadBasicType() [2/2]
void kaldi::ReadBasicType (std::istream & is, bool binary, T * t, bool add) inline
Definition at line 167 of file io-funcs.h.
References kaldi::ExpectPretty(), kaldi::ExpectToken(), kaldi::InitKaldiInputStream(), kaldi::InitKaldiOutputStream(), kaldi::Peek(), kaldi::PeekToken(), kaldi::ReadBasicType(), kaldi::ReadIntegerPairVector(), kaldi::ReadIntegerVector(), kaldi::ReadToken(), kaldi::WriteIntegerPairVector(), kaldi::WriteIntegerVector(), and kaldi::WriteToken().
{
   if (!add) {
     ReadBasicType(is, binary, t);
   } else {
     T tmp = T(0);
     ReadBasicType(is, binary, &tmp);
     *t += tmp;
   }
 }
ReadBasicType< bool >()
void ReadBasicType< bool > (std::istream & is, bool binary, bool * b)
Definition at line 34 of file io-funcs.cc.
References kaldi::CharToString(), KALDI_ERR, and KALDI_PARANOID_ASSERT.
{
   KALDI_PARANOID_ASSERT(b != NULL);
   if (!binary) is >> std::ws;  // eat up whitespace.
   char c = is.peek();
   if (c == 'T') {
       *b = true;
       is.get();
   } else if (c == 'F') {
       *b = false;
       is.get();
   } else {
     KALDI_ERR << "Read failure in ReadBasicType<bool>, file position is "
               << is.tellg() << ", next char is " << CharToString(c);
   }
 }
ReadBasicType< double >()
void ReadBasicType< double > (std::istream & is, bool binary, double * d)
Definition at line 98 of file io-funcs.cc.
References rnnlm::d, KALDI_ERR, KALDI_PARANOID_ASSERT, and kaldi::ReadBasicType().
{
   KALDI_PARANOID_ASSERT(d != NULL);
   if (binary) {
     float f;
     int c = is.peek();
     if (c == sizeof(*d)) {
       is.get();
       is.read(reinterpret_cast<char*>(d), sizeof(*d));
     } else if (c == sizeof(f)) {
       ReadBasicType(is, binary, &f);
       *d = f;
     } else {
       KALDI_ERR << "ReadBasicType: expected float, saw " << is.peek()
                 << ", at file position " << is.tellg();
     }
   } else {
     is >> *d;
   }
   if (is.fail()) {
     KALDI_ERR << "ReadBasicType: failed to read, at file position "
               << is.tellg();
   }
 }
ReadBasicType< float >()
void ReadBasicType< float > (std::istream & is, bool binary, float * f)
Definition at line 73 of file io-funcs.cc.
References rnnlm::d, KALDI_ERR, KALDI_PARANOID_ASSERT, and kaldi::ReadBasicType().
{
   KALDI_PARANOID_ASSERT(f != NULL);
   if (binary) {
     double d;
     int c = is.peek();
     if (c == sizeof(*f)) {
       is.get();
       is.read(reinterpret_cast<char*>(f), sizeof(*f));
     } else if (c == sizeof(d)) {
       ReadBasicType(is, binary, &d);
       *f = d;
     } else {
       KALDI_ERR << "ReadBasicType: expected float, saw " << is.peek()
                 << ", at file position " << is.tellg();
     }
   } else {
     is >> *f;
   }
   if (is.fail()) {
     KALDI_ERR << "ReadBasicType: failed to read, at file position "
               << is.tellg();
   }
 }
ReadIntegerPairVector()
void ReadIntegerPairVector (std::istream & is, bool binary, std::vector< std::pair< T, T > > * v) inline
Function for reading STL vector of pairs of integer types.
Definition at line 131 of file io-funcs-inl.h.
References KALDI_ASSERT, KALDI_ASSERT_IS_INTEGER_TYPE, and KALDI_ERR.
Referenced by DistributeComponentPrecomputedIndexes::Read(), ConvolutionModel::Read(), StatisticsExtractionComponentPrecomputedIndexes::Read(), StatisticsPoolingComponentPrecomputedIndexes::Read(), NnetComputation::Read(), kaldi::ReadBasicType(), and kaldi::UnitTestIo().
{
   KALDI_ASSERT_IS_INTEGER_TYPE(T);
   KALDI_ASSERT(v != NULL);
   if (binary) {
     int sz = is.peek();
     if (sz == sizeof(T)) {
       is.get();
     } else {  // this is currently just a check.
       KALDI_ERR << "ReadIntegerPairVector: expected to see type of size "
                 << sizeof(T) << ", saw instead " << sz << ", at file position "
                 << is.tellg();
     }
     int32 vecsz;
     is.read(reinterpret_cast<char *>(&vecsz), sizeof(vecsz));
     if (is.fail() || vecsz < 0) goto bad;
     v->resize(vecsz);
     if (vecsz > 0) {
       is.read(reinterpret_cast<char *>(&((*v)[0])), sizeof(T)*vecsz*2);
     }
   } else {
     std::vector<std::pair<T, T> > tmp_v;  // use temporary so v doesn't use extra memory
                            // due to resizing.
     is >> std::ws;
     if (is.peek() != static_cast<int>('[')) {
       KALDI_ERR << "ReadIntegerPairVector: expected to see [, saw "
                 << is.peek() << ", at file position " << is.tellg();
     }
     is.get();  // consume the '['.
     is >> std::ws;  // consume whitespace.
     while (is.peek() != static_cast<int>(']')) {
       if (sizeof(T) == 1) {  // read/write chars as numbers.
         int16 next_t1, next_t2;
         is >> next_t1;
         if (is.fail()) goto bad;
         if (is.peek() != static_cast<int>(','))
           KALDI_ERR << "ReadIntegerPairVector: expected to see ',', saw "
                     << is.peek() << ", at file position " << is.tellg();
         is.get();  // consume the ','.
         is >> next_t2 >> std::ws;
         if (is.fail()) goto bad;
         else
             tmp_v.push_back(std::make_pair<T, T>((T)next_t1, (T)next_t2));
       } else {
         T next_t1, next_t2;
         is >> next_t1;
         if (is.fail()) goto bad;
         if (is.peek() != static_cast<int>(','))
           KALDI_ERR << "ReadIntegerPairVector: expected to see ',', saw "
                     << is.peek() << ", at file position " << is.tellg();
         is.get();  // consume the ','.
         is >> next_t2 >> std::ws;
         if (is.fail()) goto bad;
         else
             tmp_v.push_back(std::pair<T, T>(next_t1, next_t2));
       }
     }
     is.get();  // get the final ']'.
     *v = tmp_v;  // could use std::swap to use less temporary memory, but this
     // uses less permanent memory.
   }
   if (!is.fail()) return;
  bad:
   KALDI_ERR << "ReadIntegerPairVector: read failure at file position "
             << is.tellg();
 }
ReadIntegerVector()
void ReadIntegerVector (std::istream & is, bool binary, std::vector< T > * v) inline
Function for reading STL vector of integer types.
Definition at line 232 of file io-funcs-inl.h.
References KALDI_ASSERT, KALDI_ASSERT_IS_INTEGER_TYPE, and KALDI_ERR.
Referenced by kaldi::ConvertSpliceComponent(), FramePoolingComponent::InitData(), main(), NnetExample::Read(), RegressionTree::Read(), QuestionsForKey::Read(), RegtreeMllrDiagGmm::Read(), LogisticRegression::Read(), ConstIntegerSet< EventValueType >::Read(), RegtreeFmllrDiagGmm::Read(), DiscriminativeSupervision::Read(), HmmTopology::Read(), CuArray< Int32Pair >::Read(), DiscriminativeNnetExample::Read(), AmSgmm2::Read(), ConvolutionModel::Read(), StatisticsExtractionComponentPrecomputedIndexes::Read(), ConvolutionComputation::Read(), NnetComputation::Command::Read(), NnetComputation::Read(), TdnnComponent::Read(), TdnnComponent::PrecomputedIndexes::Read(), Sgmm2GauPost::Read(), SpliceComponent::Read(), SpliceMaxComponent::Read(), SumGroupComponent::Read(), PermuteComponent::Read(), kaldi::ReadBasicType(), FramePoolingComponent::ReadData(), BlockSoftmax::ReadData(), fst::ReadILabelInfo(), kaldi::nnet3::ReadVectorAsChar(), kaldi::UnitTestIo(), kaldi::UnitTestIoNew(), and kaldi::UnitTestIoPipe().
{
   KALDI_ASSERT_IS_INTEGER_TYPE(T);
   KALDI_ASSERT(v != NULL);
   if (binary) {
     int sz = is.peek();
     if (sz == sizeof(T)) {
       is.get();
     } else {  // this is currently just a check.
       KALDI_ERR << "ReadIntegerVector: expected to see type of size "
                 << sizeof(T) << ", saw instead " << sz << ", at file position "
                 << is.tellg();
     }
     int32 vecsz;
     is.read(reinterpret_cast<char *>(&vecsz), sizeof(vecsz));
     if (is.fail() || vecsz < 0) goto bad;
     v->resize(vecsz);
     if (vecsz > 0) {
       is.read(reinterpret_cast<char *>(&((*v)[0])), sizeof(T)*vecsz);
     }
   } else {
     std::vector<T> tmp_v;  // use temporary so v doesn't use extra memory
                            // due to resizing.
     is >> std::ws;
     if (is.peek() != static_cast<int>('[')) {
       KALDI_ERR << "ReadIntegerVector: expected to see [, saw "
                 << is.peek() << ", at file position " << is.tellg();
     }
     is.get();  // consume the '['.
     is >> std::ws;  // consume whitespace.
     while (is.peek() != static_cast<int>(']')) {
       if (sizeof(T) == 1) {  // read/write chars as numbers.
         int16 next_t;
         is >> next_t >> std::ws;
         if (is.fail()) goto bad;
         else
             tmp_v.push_back((T)next_t);
       } else {
         T next_t;
         is >> next_t >> std::ws;
         if (is.fail()) goto bad;
         else
             tmp_v.push_back(next_t);
       }
     }
     is.get();  // get the final ']'.
     *v = tmp_v;  // could use std::swap to use less temporary memory, but this
     // uses less permanent memory.
   }
   if (!is.fail()) return;
  bad:
   KALDI_ERR << "ReadIntegerVector: read failure at file position "
             << is.tellg();
 }
ReadToken()
void ReadToken (std::istream & is, bool binary, std::string * str)
ReadToken gets the next token and puts it in str (exception on failure).
Definition at line 154 of file io-funcs.cc.
References kaldi::CharToString(), KALDI_ASSERT, and KALDI_ERR.
Referenced by kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectOneOrTwoTokens(), Component::Init(), LinearTransform::InitData(), AffineTransform::InitData(), MultiBasisComponent::InitData(), ParallelComponent::InitData(), ParametricRelu::InitData(), Splice::InitData(), AveragePooling2DComponent::InitData(), AveragePoolingComponent::InitData(), MaxPoolingComponent::InitData(), RecurrentComponent::InitData(), MaxPooling2DComponent::InitData(), FramePoolingComponent::InitData(), SimpleSentenceAveragingComponent::InitData(), LstmProjected::InitData(), BlstmProjected::InitData(), ConvolutionalComponent::InitData(), Convolutional2DComponent::InitData(), Rbm::InitData(), BlockSoftmax::InitData(), CopyComponent::InitData(), SentenceAveragingComponent::InitData(), Dropout::InitData(), AddShift::InitData(), Rescale::InitData(), NnetExample::Read(), LogisticRegression::Read(), LinearVtln::Read(), NnetIo::Read(), ContextDependency::Read(), FmpeOptions::Read(), AccumFullGmm::Read(), LdaEstimate::Read(), NnetDiscriminativeSupervision::Read(), IoSpecification::Read(), Sgmm2FmllrGlobalParams::Read(), NormalizeComponent::Read(), NnetChainSupervision::Read(), AccumDiagGmm::Read(), DropoutComponent::Read(), Questions::Read(), MleAmSgmm2Accs::Read(), TransitionModel::Read(), FullGmm::Read(), HmmTopology::Read(), CompressedMatrix::Read(), PackedMatrix< float >::Read(), Component::Read(), DiagGmm::Read(), Nnet::Read(), AmSgmm2::Read(), NnetComputation::MatrixInfo::Read(), OnlineIvectorEstimationStats::Read(), Vector< float >::Read(), NnetComputation::Read(), TdnnComponent::Read(), BackpropTruncationComponent::Read(), NonlinearComponent::Read(), ConstantComponent::Read(), NaturalGradientAffineComponent::Read(), Matrix< BaseFloat >::Read(), AffineComponent::Read(), AffineComponentPreconditioned::Read(), AffineComponentPreconditionedOnline::Read(), SpliceComponent::Read(), SpliceMaxComponent::Read(), NoOpComponent::Read(), SumGroupComponent::Read(), ClipGradientComponent::Read(), DctComponent::Read(), ConstantFunctionComponent::Read(), Convolutional1dComponent::Read(), NaturalGradientPerElementScaleComponent::Read(), ConvolutionComponent::Read(), LstmNonlinearityComponent::Read(), CompositeComponent::Read(), kaldi::ReadBasicType(), ParametricRelu::ReadData(), AffineTransform::ReadData(), RecurrentComponent::ReadData(), LinearTransform::ReadData(), LstmProjected::ReadData(), BlstmProjected::ReadData(), MultiBasisComponent::ReadData(), Rbm::ReadData(), Dropout::ReadData(), ComponentPrecomputedIndexes::ReadNew(), Component::ReadNew(), UpdatableComponent::ReadUpdatableCommon(), kaldi::UnitTestIo(), kaldi::UnitTestIoNew(), and kaldi::UnitTestIoPipe().
{
   KALDI_ASSERT(str != NULL);
   if (!binary) is >> std::ws;  // consume whitespace.
   is >> *str;
   if (is.fail()) {
     KALDI_ERR << "ReadToken, failed to read token at file position "
               << is.tellg();
   }
   if (!isspace(is.peek())) {
     KALDI_ERR << "ReadToken, expected space after token, saw instead "
               << CharToString(static_cast<char>(is.peek()))
               << ", at file position " << is.tellg();
   }
   is.get();  // consume the space.
 }
WriteBasicType()
void WriteBasicType (std::ostream & os, bool binary, T t)
WriteBasicType is the name of the write function for bool, integer types, and floating-point types.
They all throw on error.
Definition at line 34 of file io-funcs-inl.h.
References KALDI_ASSERT_IS_INTEGER_TYPE.
Referenced by kaldi::TestBuildTree(), kaldi::TestGenRandStats(), kaldi::UnitTestIo(), kaldi::UnitTestIoNew(), kaldi::UnitTestIoPipe(), AccumAmDiagGmm::Write(), ScalarClusterable::Write(), AffineXformStats::Write(), CompressedAffineXformStats::Write(), MlltAccs::Write(), NnetExample::Write(), AmNnetSimple::Write(), RegressionTree::Write(), CuBlockMatrix< Real >::Write(), QuestionsForKey::Write(), RegtreeMllrDiagGmm::Write(), Index::Write(), LinearVtln::Write(), AmDiagGmm::Write(), GaussClusterable::Write(), FmpeOptions::Write(), DistributeComponent::Write(), BasisFmllrAccus::Write(), AccumFullGmm::Write(), RegtreeFmllrDiagGmm::Write(), LdaEstimate::Write(), ContextDependency::Write(), Sgmm2FmllrGlobalParams::Write(), IoSpecification::Write(), NormalizeComponent::Write(), SparseVector< Real >::Write(), GaussPostHolder::Write(), NnetDiscriminativeExample::Write(), BasisFmllrEstimate::Write(), AccumDiagGmm::Write(), Questions::Write(), NnetChainExample::Write(), RegtreeMllrDiagGmmAccs::Write(), FmllrSgmm2Accs::Write(), DiscriminativeSupervision::Write(), BasicHolder< BasicType >::Write(), TransitionModel::Write(), MleAmSgmm2Accs::Write(), RefineClustersOptions::Write(), HmmTopology::Write(), VectorClusterable::Write(), PackedMatrix< float >::Write(), GrammarFst::Write(), NnetOptimizeOptions::Write(), RestrictedAttentionComponent::Write(), ComputationRequest::Write(), Component::Write(), DiscriminativeNnetExample::Write(), RegtreeFmllrDiagGmmAccs::Write(), ElementwiseProductComponent::Write(), SparseMatrix< float >::Write(), ConstantEventMap::Write(), BatchNormComponent::Write(), BasicVectorHolder< BasicType >::Write(), Nnet::Write(), ConvolutionModel::Write(), AmSgmm2::Write(), StatisticsExtractionComponent::Write(), TimeHeightConvolutionComponent::Write(), IvectorExtractor::Write(), TableEventMap::Write(), ConstArpaLm::Write(), SplitEventMap::Write(), NnetComputation::MatrixInfo::Write(), NnetComputation::MatrixDebugInfo::Write(), NnetComputation::SubMatrixInfo::Write(), ConvolutionComputation::Write(), BasicVectorVectorHolder< BasicType >::Write(), VectorBase< float >::Write(), NnetComputation::Command::Write(), OnlineIvectorEstimationStats::Write(), NonlinearComponent::Write(), StatisticsPoolingComponent::Write(), ConvolutionComputationIo::Write(), MaxoutComponent::Write(), NnetComputation::Write(), TdnnComponent::Write(), BasicPairVectorHolder< BasicType >::Write(), IvectorExtractorStats::Write(), MaxpoolingComponent::Write(), BackpropTruncationComponent::Write(), TdnnComponent::PrecomputedIndexes::Write(), PnormComponent::Write(), Sgmm2GauPost::Write(), BackpropTruncationComponentPrecomputedIndexes::Write(), RepeatedAffineComponent::Write(), ComputationCache::Write(), ConstantComponent::Write(), PowerComponent::Write(), MatrixBase< float >::Write(), DropoutMaskComponent::Write(), ScaleComponent::Write(), NaturalGradientAffineComponent::Write(), GeneralDropoutComponent::Write(), AffineComponent::Write(), GeneralDropoutComponentPrecomputedIndexes::Write(), LinearComponent::Write(), AffineComponentPreconditioned::Write(), AffineComponentPreconditionedOnline::Write(), SpliceComponent::Write(), SpliceMaxComponent::Write(), NoOpComponent::Write(), BlockAffineComponent::Write(), SumBlockComponent::Write(), BlockAffineComponentPreconditioned::Write(), ClipGradientComponent::Write(), DctComponent::Write(), DropoutComponent::Write(), PerElementOffsetComponent::Write(), AdditiveNoiseComponent::Write(), ConstantFunctionComponent::Write(), Convolutional1dComponent::Write(), NaturalGradientPerElementScaleComponent::Write(), ScaleAndOffsetComponent::Write(), ConvolutionComponent::Write(), LstmNonlinearityComponent::Write(), CompositeComponent::Write(), Rbm::WriteAsNnet(), kaldi::WriteBuildTreeStats(), kaldi::nnet3::WriteCindexVector(), kaldi::nnet3::WriteCindexVectorElementBinary(), MaxPoolingComponent::WriteData(), AveragePoolingComponent::WriteData(), ParametricRelu::WriteData(), SimpleSentenceAveragingComponent::WriteData(), AffineTransform::WriteData(), RecurrentComponent::WriteData(), AveragePooling2DComponent::WriteData(), MaxPooling2DComponent::WriteData(), LinearTransform::WriteData(), ParallelComponent::WriteData(), LstmProjected::WriteData(), FramePoolingComponent::WriteData(), MultiBasisComponent::WriteData(), Convolutional2DComponent::WriteData(), ConvolutionalComponent::WriteData(), BlstmProjected::WriteData(), Dropout::WriteData(), AddShift::WriteData(), Rescale::WriteData(), kaldi::WriteEventType(), fst::WriteILabelInfo(), kaldi::nnet3::WriteIndexVector(), kaldi::nnet3::WriteIndexVectorElementBinary(), kaldi::WritePosterior(), and UpdatableComponent::WriteUpdatableCommon().
{
   // Compile time assertion that this is not called with a wrong type.
   KALDI_ASSERT_IS_INTEGER_TYPE(T);
   if (binary) {
     char len_c = (std::numeric_limits<T>::is_signed ? 1 :  -1)
         * static_cast<char>(sizeof(t));
     os.put(len_c);
     os.write(reinterpret_cast<const char *>(&t), sizeof(t));
   } else {
     if (sizeof(t) == 1)
       os << static_cast<int16>(t) << " ";
     else
       os << t << " ";
   }
   if (os.fail()) {
     throw std::runtime_error("Write failure in WriteBasicType.");
   }
 }
WriteBasicType< bool >()
void WriteBasicType< bool > (std::ostream & os, bool binary, bool b)
Definition at line 26 of file io-funcs.cc.
References KALDI_ERR.
{
   os << (b ? "T":"F");
   if (!binary) os << " ";
   if (os.fail())
     KALDI_ERR << "Write failure in WriteBasicType<bool>";
 }
WriteBasicType< double >()
void WriteBasicType< double > (std::ostream & os, bool binary, double f)
Definition at line 62 of file io-funcs.cc.
{
   if (binary) {
     char c = sizeof(f);
     os.put(c);
     os.write(reinterpret_cast<const char *>(&f), sizeof(f));
   } else {
     os << f << " ";
   }
 }
WriteBasicType< float >()
void WriteBasicType< float > (std::ostream & os, bool binary, float f)
Definition at line 51 of file io-funcs.cc.
{
   if (binary) {
     char c = sizeof(f);
     os.put(c);
     os.write(reinterpret_cast<const char *>(&f), sizeof(f));
   } else {
     os << f << " ";
   }
 }
WriteIntegerPairVector()
void WriteIntegerPairVector (std::ostream & os, bool binary, const std::vector< std::pair< T, T > > & v) inline
Function for writing STL vectors of pairs of integer types.
Definition at line 93 of file io-funcs-inl.h.
References KALDI_ASSERT, and KALDI_ASSERT_IS_INTEGER_TYPE.
Referenced by kaldi::ReadBasicType(), kaldi::UnitTestIo(), DistributeComponentPrecomputedIndexes::Write(), ConvolutionModel::Write(), StatisticsExtractionComponentPrecomputedIndexes::Write(), StatisticsPoolingComponentPrecomputedIndexes::Write(), and NnetComputation::Write().
{
   // Compile time assertion that this is not called with a wrong type.
   KALDI_ASSERT_IS_INTEGER_TYPE(T);
   if (binary) {
     char sz = sizeof(T);  // this is currently just a check.
     os.write(&sz, 1);
     int32 vecsz = static_cast<int32>(v.size());
     KALDI_ASSERT((size_t)vecsz == v.size());
     os.write(reinterpret_cast<const char *>(&vecsz), sizeof(vecsz));
     if (vecsz != 0) {
       os.write(reinterpret_cast<const char *>(&(v[0])), sizeof(T) * vecsz * 2);
     }
   } else {
     // focus here is on prettiness of text form rather than
     // efficiency of reading-in.
     // reading-in is dominated by low-level operations anyway:
     // for efficiency use binary.
     os << "[ ";
     typename std::vector<std::pair<T, T> >::const_iterator iter = v.begin(),
                                                             end = v.end();
     for (; iter != end; ++iter) {
       if (sizeof(T) == 1)
         os << static_cast<int16>(iter->first) << ','
            << static_cast<int16>(iter->second) << ' ';
       else
         os << iter->first << ','
            << iter->second << ' ';
     }
     os << "]\n";
   }
   if (os.fail()) {
     throw std::runtime_error("Write failure in WriteIntegerPairVector.");
   }
 }
WriteIntegerVector()
void WriteIntegerVector (std::ostream & os, bool binary, const std::vector< T > & v) inline
Function for writing STL vectors of integer types.
Definition at line 198 of file io-funcs-inl.h.
References KALDI_ASSERT, and KALDI_ASSERT_IS_INTEGER_TYPE.
Referenced by kaldi::ConvertAlignmentForPhone(), kaldi::ConvertFullCtxAlignment(), kaldi::GetIlabelMapping(), main(), kaldi::ProcessTopo(), kaldi::ReadBasicType(), kaldi::TestBuildTree(), kaldi::TestGenRandStats(), kaldi::UnitTestIo(), kaldi::UnitTestIoNew(), kaldi::UnitTestIoPipe(), NnetExample::Write(), RegressionTree::Write(), QuestionsForKey::Write(), RegtreeMllrDiagGmm::Write(), LogisticRegression::Write(), ConstIntegerSet< EventValueType >::Write(), RegtreeFmllrDiagGmm::Write(), DiscriminativeSupervision::Write(), HmmTopology::Write(), CuArray< Int32Pair >::Write(), DiscriminativeNnetExample::Write(), ConvolutionModel::Write(), AmSgmm2::Write(), StatisticsExtractionComponentPrecomputedIndexes::Write(), ConvolutionComputation::Write(), NnetComputation::Command::Write(), NnetComputation::Write(), TdnnComponent::Write(), TdnnComponent::PrecomputedIndexes::Write(), Sgmm2GauPost::Write(), SpliceComponent::Write(), SpliceMaxComponent::Write(), SumGroupComponent::Write(), PermuteComponent::Write(), FramePoolingComponent::WriteData(), BlockSoftmax::WriteData(), fst::WriteILabelInfo(), and kaldi::nnet3::WriteVectorAsChar().
{
   // Compile time assertion that this is not called with a wrong type.
   KALDI_ASSERT_IS_INTEGER_TYPE(T);
   if (binary) {
     char sz = sizeof(T);  // this is currently just a check.
     os.write(&sz, 1);
     int32 vecsz = static_cast<int32>(v.size());
     KALDI_ASSERT((size_t)vecsz == v.size());
     os.write(reinterpret_cast<const char *>(&vecsz), sizeof(vecsz));
     if (vecsz != 0) {
       os.write(reinterpret_cast<const char *>(&(v[0])), sizeof(T)*vecsz);
     }
   } else {
     // focus here is on prettiness of text form rather than
     // efficiency of reading-in.
     // reading-in is dominated by low-level operations anyway:
     // for efficiency use binary.
     os << "[ ";
     typename std::vector<T>::const_iterator iter = v.begin(), end = v.end();
     for (; iter != end; ++iter) {
       if (sizeof(T) == 1)
         os << static_cast<int16>(*iter) << " ";
       else
         os << *iter << " ";
     }
     os << "]\n";
   }
   if (os.fail()) {
     throw std::runtime_error("Write failure in WriteIntegerVector.");
   }
 }
WriteToken() [1/2]
void WriteToken (std::ostream & os, bool binary, const char * token)
The WriteToken functions are for writing nonempty sequences of non-space characters.
They are not for general strings.
Definition at line 134 of file io-funcs.cc.
References kaldi::CheckToken(), and KALDI_ASSERT.
Referenced by kaldi::ReadBasicType(), kaldi::UnitTestIo(), kaldi::UnitTestIoNew(), kaldi::UnitTestIoPipe(), AccumAmDiagGmm::Write(), ScalarClusterable::Write(), AffineXformStats::Write(), CompressedAffineXformStats::Write(), MlltAccs::Write(), NnetExample::Write(), RegressionTree::Write(), AmNnetSimple::Write(), QuestionsForKey::Write(), CuBlockMatrix< Real >::Write(), RegtreeMllrDiagGmm::Write(), LogisticRegression::Write(), LinearVtln::Write(), Index::Write(), AmDiagGmm::Write(), NnetIo::Write(), FmpeOptions::Write(), GaussClusterable::Write(), DistributeComponent::Write(), BasisFmllrAccus::Write(), RegtreeFmllrDiagGmm::Write(), AccumFullGmm::Write(), LdaEstimate::Write(), NnetDiscriminativeSupervision::Write(), Sgmm2FmllrGlobalParams::Write(), ContextDependency::Write(), NnetChainSupervision::Write(), IoSpecification::Write(), NormalizeComponent::Write(), SparseVector< Real >::Write(), NnetDiscriminativeExample::Write(), BasisFmllrEstimate::Write(), AccumDiagGmm::Write(), Questions::Write(), NnetChainExample::Write(), RegtreeMllrDiagGmmAccs::Write(), FmllrSgmm2Accs::Write(), DiscriminativeSupervision::Write(), FullGmm::Write(), MleAmSgmm2Accs::Write(), TransitionModel::Write(), RefineClustersOptions::Write(), VectorClusterable::Write(), HmmTopology::Write(), Plda::Write(), CompressedMatrix::Write(), Nnet::Write(), DistributeComponentPrecomputedIndexes::Write(), GrammarFst::Write(), PackedMatrix< float >::Write(), NnetOptimizeOptions::Write(), RestrictedAttentionComponent::Write(), ComputationRequest::Write(), Component::Write(), EventMap::Write(), DiagGmm::Write(), DiscriminativeNnetExample::Write(), RegtreeFmllrDiagGmmAccs::Write(), ElementwiseProductComponent::Write(), RestrictedAttentionComponent::PrecomputedIndexes::Write(), SparseMatrix< float >::Write(), ConstantEventMap::Write(), BatchNormComponent::Write(), ConvolutionModel::Write(), AmSgmm2::Write(), StatisticsExtractionComponent::Write(), TimeHeightConvolutionComponent::Write(), IvectorExtractor::Write(), TableEventMap::Write(), OnlineCmvnState::Write(), ConstArpaLm::Write(), TimeHeightConvolutionComponent::PrecomputedIndexes::Write(), StatisticsExtractionComponentPrecomputedIndexes::Write(), SplitEventMap::Write(), NnetComputation::MatrixInfo::Write(), NnetComputation::MatrixDebugInfo::Write(), NnetComputation::SubMatrixInfo::Write(), ConvolutionComputation::Write(), VectorBase< float >::Write(), NnetComputation::Command::Write(), OnlineIvectorEstimationStats::Write(), NonlinearComponent::Write(), StatisticsPoolingComponent::Write(), ConvolutionComputationIo::Write(), StatisticsPoolingComponentPrecomputedIndexes::Write(), MaxoutComponent::Write(), NnetComputation::Write(), TdnnComponent::Write(), IvectorExtractorStats::Write(), MaxpoolingComponent::Write(), BackpropTruncationComponent::Write(), TdnnComponent::PrecomputedIndexes::Write(), PnormComponent::Write(), Sgmm2GauPost::Write(), BackpropTruncationComponentPrecomputedIndexes::Write(), RepeatedAffineComponent::Write(), ComputationCache::Write(), ConstantComponent::Write(), PowerComponent::Write(), MatrixBase< float >::Write(), DropoutMaskComponent::Write(), ScaleComponent::Write(), NaturalGradientAffineComponent::Write(), GeneralDropoutComponent::Write(), AffineComponent::Write(), GeneralDropoutComponentPrecomputedIndexes::Write(), LinearComponent::Write(), AffineComponentPreconditioned::Write(), AffineComponentPreconditionedOnline::Write(), SpliceComponent::Write(), SpliceMaxComponent::Write(), NoOpComponent::Write(), BlockAffineComponent::Write(), SumBlockComponent::Write(), BlockAffineComponentPreconditioned::Write(), SumGroupComponent::Write(), PermuteComponent::Write(), ClipGradientComponent::Write(), DctComponent::Write(), FixedLinearComponent::Write(), FixedAffineComponent::Write(), FixedScaleComponent::Write(), PerElementScaleComponent::Write(), FixedBiasComponent::Write(), DropoutComponent::Write(), PerElementOffsetComponent::Write(), AdditiveNoiseComponent::Write(), ConstantFunctionComponent::Write(), Convolutional1dComponent::Write(), NaturalGradientPerElementScaleComponent::Write(), ScaleAndOffsetComponent::Write(), ConvolutionComponent::Write(), LstmNonlinearityComponent::Write(), CompositeComponent::Write(), Rbm::WriteAsNnet(), kaldi::WriteBuildTreeStats(), kaldi::nnet3::WriteCindexVector(), MaxPoolingComponent::WriteData(), AveragePoolingComponent::WriteData(), ParametricRelu::WriteData(), SimpleSentenceAveragingComponent::WriteData(), AffineTransform::WriteData(), AveragePooling2DComponent::WriteData(), RecurrentComponent::WriteData(), MaxPooling2DComponent::WriteData(), LinearTransform::WriteData(), ParallelComponent::WriteData(), FramePoolingComponent::WriteData(), LstmProjected::WriteData(), MultiBasisComponent::WriteData(), ConvolutionalComponent::WriteData(), Convolutional2DComponent::WriteData(), BlstmProjected::WriteData(), Rbm::WriteData(), Dropout::WriteData(), AddShift::WriteData(), Rescale::WriteData(), kaldi::WriteEventType(), kaldi::nnet3::WriteIndexVector(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   // binary mode is ignored;
   // we use space as termination character in either case.
   KALDI_ASSERT(token != NULL);
   CheckToken(token);  // make sure it's valid (can be read back)
   os << token << " ";
   if (os.fail()) {
     throw std::runtime_error("Write failure in WriteToken.");
   }
 }
WriteToken() [2/2]
void WriteToken (std::ostream & os, bool binary, const std::string & token)
Definition at line 150 of file io-funcs.cc.
References kaldi::WriteToken().
{
   WriteToken(os, binary, token.c_str());
 }