Kaldi: hmm/hmm-utils-test.cc File Reference
hmm-utils-test.cc File Reference
#include "hmm/hmm-utils.h"
#include "hmm/tree-accu.h"
#include "hmm/hmm-test-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void TestConvertPhnxToProns ()
void TestAccumulateTreeStatsOptions ()
void TestSplitToPhones ()
void TestConvertAlignment ()
int main ()
Function Documentation
main()
int main ()
Definition at line 328 of file hmm-utils-test.cc.
References rnnlm::i, kaldi::TestAccumulateTreeStatsOptions(), kaldi::TestConvertAlignment(), kaldi::TestConvertPhnxToProns(), and kaldi::TestSplitToPhones().
            {
   kaldi::TestConvertPhnxToProns();
 #ifndef _MSC_VER
   kaldi::TestAccumulateTreeStatsOptions();
 #endif
   for (int32 i = 0; i < 2; i++)
     kaldi::TestSplitToPhones();
   for (int32 i = 0; i < 5; i++)
     kaldi::TestConvertAlignment();
   std::cout << "Test OK.\n";
 }