Kaldi: bin/hmm-info.cc File Reference
hmm-info.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 24 of file hmm-info.cc.
References ParseOptions::GetArg(), TransitionModel::GetPhones(), ParseOptions::NumArgs(), TransitionModel::NumPdfs(), TransitionModel::NumTransitionIds(), TransitionModel::NumTransitionStates(), ParseOptions::PrintUsage(), ParseOptions::Read(), TransitionModel::Read(), and Input::Stream().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Write to standard output various properties of HMM-based transition model\n"
         "Usage:  hmm-info [options] <model-in>\n"
         "e.g.:\n"
         " hmm-info trans.mdl\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 1) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_in_filename = po.GetArg(1);
     TransitionModel trans_model;
     {
       bool binary_read;
       Input ki(model_in_filename, &binary_read);
       trans_model.Read(ki.Stream(), binary_read);
     }
     std::cout << "number of phones " << trans_model.GetPhones().size() << '\n';
     std::cout << "number of pdfs " << trans_model.NumPdfs() << '\n';
     std::cout << "number of transition-ids " << trans_model.NumTransitionIds()
               << '\n';
     std::cout << "number of transition-states "
               << trans_model.NumTransitionStates() << '\n';
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }