Kaldi: idlaktxpbin/idlaktxp.cc File Reference
idlaktxp.cc File Reference
#include <pugixml.hpp>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "idlaktxp/idlaktxp.h"
Functions
int main (int argc, char *argv[])
Example program that runs all modules in idlaktxp and produces XML output You need a text processing database (tpdb) to run this.
Function Documentation
main()
int main (int argc, char * argv[])
Example program that runs all modules in idlaktxp and produces XML output You need a text processing database (tpdb) to run this.
An example is in ../../idlak-data/arctic-bdl/tpdb
Definition at line 28 of file idlaktxp.cc.
References ParseOptions::GetArg(), TxpPosTag::Init(), TxpTokenise::Init(), TxpPhrasing::Init(), TxpPauses::Init(), TxpSyllabify::Init(), TxpPronounce::Init(), KALDI_ERR, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), TxpPosTag::Process(), TxpTokenise::Process(), TxpPhrasing::Process(), TxpSyllabify::Process(), TxpPauses::Process(), TxpPronounce::Process(), TxpParseOptions::Read(), ParseOptions::Register(), Output::Stream(), and Input::Stream().
{
   const char *usage =
       "Tokenise utf8 input xml\n"
       "Usage:  idlaktxp --tpdb=<idlak-data-root> --general-lang=<language iso code> [options] xml_input xml_output\n"
       "e.g.: ./idlaktxp --pretty --tpdb=../../idlak-data --general-lang=en ../idlaktxp/test_data/mod-test001.xml output.xml\n" //NOLINT
       "e.g.: cat  ../idlaktxp/test_data/mod-test001.xml output.xml | idlaktxp --pretty --tpdb=../../idlak-data --general-lang=en --general-acc=ga - - > output.xml\n" //NOLINT
       "language and tpdb must be set and for most modules with accent specific data accent must also be set"; //NOLINT
   // input output variables
   std::string filein;
   std::string fileout;
   //std::string tpdb;
   std::string input;
   std::ofstream fout;
   // defaults to non-pretty XML output
   bool pretty = false;
   try {
     kaldi::TxpParseOptions po(usage);
     //po.SetTpdb(tpdb);
     po.Register("pretty", &pretty,
                 "Output XML with tabbing and line breaks to make it readable");
     po.Read(argc, argv);
     // Must have input and output filenames for XML
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     filein = po.GetArg(1);
     fileout = po.GetArg(2);
     // Set up input/output streams
     bool binary;
     kaldi::Input ki(filein, &binary);
     kaldi::Output kio(fileout, binary);
     // Set up each module
     kaldi::TxpTokenise t;
     kaldi::TxpPosTag p;
     kaldi::TxpPauses pz;
     kaldi::TxpPhrasing ph;
     kaldi::TxpPronounce pr;
     kaldi::TxpSyllabify sy;
     // Use pujiXMl to read input file
     pugi::xml_document doc;
     pugi::xml_parse_result r = doc.load(ki.Stream(), pugi::encoding_utf8 | pugi::parse_escapes);
     if (!r) {
       KALDI_ERR << "PugiXML Parse Error in Input Stream" << r.description()
                 << "Error offset: " << r.offset;
     }
     // Initialise each module
     t.Init(po);
     p.Init(po);
     pz.Init(po);
     ph.Init(po);
     pr.Init(po);
     sy.Init(po);
     // Run each module on the input XML
     t.Process(&doc);
     p.Process(&doc);
     pz.Process(&doc);
     ph.Process(&doc);
     pr.Process(&doc);
     sy.Process(&doc);
     // Output result
     if (!pretty)
       doc.save(kio.Stream(), "", pugi::format_raw);
     else
       doc.save(kio.Stream(), "\t");
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }