Kaldi: featbin/interpolate-pitch.cc File Reference
interpolate-pitch.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
Classes
struct PitchInterpolatorOptions
struct PitchInterpolatorStats
class PitchInterpolator
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void LinearlyInterpolatePitch (Matrix< BaseFloat > *mat)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 292 of file interpolate-pitch.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_ERR, KALDI_LOG, KALDI_VLOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), kaldi::LinearlyInterpolatePitch(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), TableWriter< Holder >::Open(), PitchInterpolatorStats::Print(), ParseOptions::PrintUsage(), ParseOptions::Read(), PitchInterpolatorOptions::Register(), ParseOptions::Register(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     const char *usage =
         "This is a rather special-purpose program which processes 2-dimensional\n"
         "features consisting of (prob-of-voicing, pitch).  By default we do model-based\n"
         "pitch smoothing and interpolation (see code), or if --linear-interpolation=true,\n"
         "just linear interpolation across gaps where pitch == 0 (not predicted).\n"
         "Usage:  interpolate-pitch [options...] <feats-rspecifier> <feats-wspecifier>\n";
     // construct all the global objects
     ParseOptions opts(usage);
     bool linear_interpolation = false;
     PitchInterpolatorOptions interpolate_opts;
     opts.Register("linear-interpolation",
                 &linear_interpolation, "If true, just do simple linear "
                 "interpolation across gaps (else, model-based)");
     interpolate_opts.Register(&opts);
     // parse options (+filling the registered variables)
     opts.Read(argc, argv);
     if (opts.NumArgs() != 2) {
       opts.PrintUsage();
       exit(1);
     }
     std::string input_rspecifier = opts.GetArg(1);
     std::string output_wspecifier = opts.GetArg(2);
     SequentialBaseFloatMatrixReader reader(input_rspecifier);
     BaseFloatMatrixWriter kaldi_writer;  // typedef to TableWriter<something>.
     if (!kaldi_writer.Open(output_wspecifier))
        KALDI_ERR << "Could not initialize output with wspecifier "
                 << output_wspecifier;
     int32 num_done = 0, num_err = 0;
     PitchInterpolatorStats stats;
     for (; !reader.Done(); reader.Next()) {
       std::string utt = reader.Key();
       Matrix<BaseFloat> features = reader.Value();
       int num_frames = features.NumRows();
       if (num_frames == 0 && features.NumCols() != 2) {
         KALDI_WARN << "Feature file has bad size "
                    << features.NumRows() << " by " << features.NumCols();
         num_err++;
         continue;
       }
       if (linear_interpolation) LinearlyInterpolatePitch(&features);
       else {
         // work happens in constructor of this class.
         PitchInterpolator pi(interpolate_opts, &features, &stats);
       }
       kaldi_writer.Write(utt, features);
       num_done++;
       if (num_done % 10 == 0)
         KALDI_LOG << "Processed " << num_done << " utterances";
       KALDI_VLOG(2) << "Processed features for key " << utt;
     }
     if (!linear_interpolation) stats.Print();
     KALDI_LOG << "Done " << num_done << " utterances, " << num_err
               << " with errors.";
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }