Kaldi: ivectorbin/ivector-extractor-acc-stats.cc File Reference
ivector-extractor-acc-stats.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "gmm/am-diag-gmm.h"
#include "ivector/ivector-extractor.h"
#include "util/kaldi-thread.h"
Classes
class IvectorTask
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 62 of file ivector-extractor-acc-stats.cc.
References SequentialTableReader< Holder >::Done(), kaldi::g_num_threads, ParseOptions::GetArg(), RandomAccessTableReader< Holder >::HasKey(), IvectorTask::IvectorTask(), KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), TaskSequencerConfig::num_threads, ParseOptions::NumArgs(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), TaskSequencerConfig::Register(), IvectorExtractorStatsOptions::Register(), TaskSequencer< C >::Run(), Output::Stream(), RandomAccessTableReader< Holder >::Value(), SequentialTableReader< Holder >::Value(), and IvectorExtractorStats::Write().
{
   using namespace kaldi;
   typedef kaldi::int32 int32;
   typedef kaldi::int64 int64;
   try {
     const char *usage =
         "Accumulate stats for iVector extractor training\n"
         "Reads in features and Gaussian-level posteriors (typically from a full GMM)\n"
         "Supports multiple threads, but won't be able to make use of too many at a time\n"
         "(e.g. more than about 4)\n"
         "Usage:  ivector-extractor-acc-stats [options] <model-in> <feature-rspecifier>"
         "<posteriors-rspecifier> <stats-out>\n"
         "e.g.: \n"
         " fgmm-global-gselect-to-post 1.fgmm '$feats' 'ark:gunzip -c gselect.1.gz|' ark:- | \\\n"
         "  ivector-extractor-acc-stats 2.ie '$feats' ark,s,cs:- 2.1.acc\n";
     ParseOptions po(usage);
     bool binary = true;
     IvectorExtractorStatsOptions stats_opts;
     TaskSequencerConfig sequencer_opts;
     po.Register("binary", &binary, "Write output in binary mode");
     stats_opts.Register(&po);
     sequencer_opts.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string ivector_extractor_rxfilename = po.GetArg(1),
         feature_rspecifier = po.GetArg(2),
         posteriors_rspecifier = po.GetArg(3),
         accs_wxfilename = po.GetArg(4);
     // Initialize these Reader objects before reading the IvectorExtractor,
     // because it uses up a lot of memory and any fork() after that will
     // be in danger of causing an allocation failure.
     SequentialBaseFloatMatrixReader feature_reader(feature_rspecifier);
     RandomAccessPosteriorReader posteriors_reader(posteriors_rspecifier);
     // This is a bit of a mess... the code that reads in the extractor calls
     // ComputeDerivedVars, and it can do this multi-threaded, controlled by
     // g_num_threads.  So if the user specified the --num-threads option, which
     // goes to sequencer_opts in this case, copy it to g_num_threads.
     g_num_threads = sequencer_opts.num_threads;
     IvectorExtractor extractor;
     ReadKaldiObject(ivector_extractor_rxfilename, &extractor);
     IvectorExtractorStats stats(extractor, stats_opts);
     int64 tot_t = 0;
     int32 num_done = 0, num_err = 0;
     {
       TaskSequencer<IvectorTask> sequencer(sequencer_opts);
       for (; !feature_reader.Done(); feature_reader.Next()) {
         std::string key = feature_reader.Key();
         if (!posteriors_reader.HasKey(key)) {
           KALDI_WARN << "No posteriors for utterance " << key;
           num_err++;
           continue;
         }
         const Matrix<BaseFloat> &mat = feature_reader.Value();
         const Posterior &posterior = posteriors_reader.Value(key);
         if (static_cast<int32>(posterior.size()) != mat.NumRows()) {
           KALDI_WARN << "Size mismatch between posterior " << (posterior.size())
                      << " and features " << (mat.NumRows()) << " for utterance "
                      << key;
           num_err++;
           continue;
         }
         sequencer.Run(new IvectorTask(extractor, mat, posterior, &stats));
         tot_t += posterior.size();
         num_done++;
       }
       // destructor of "sequencer" will wait for any remaining tasks that
       // have not yet completed.
     }
     KALDI_LOG << "Done " << num_done << " files, " << num_err
               << " with errors.  Total frames " << tot_t;
     {
       Output ko(accs_wxfilename, binary);
       stats.Write(ko.Stream(), binary);
     }
     KALDI_LOG << "Wrote stats to " << accs_wxfilename;
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }