Kaldi: ivectorbin/ivector-plda-scoring-dense.cc File Reference
ivector-plda-scoring-dense.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "util/stl-utils.h"
#include "ivector/plda.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
bool EstPca (const Matrix< BaseFloat > &ivector_mat, BaseFloat target_energy, Matrix< BaseFloat > *mat)
void TransformIvectors (const Matrix< BaseFloat > &ivectors_in, const PldaConfig &plda_config, const Plda &plda, Matrix< BaseFloat > *ivectors_out)
void ApplyPca (const Matrix< BaseFloat > &ivectors_in, const Matrix< BaseFloat > &pca_mat, Matrix< BaseFloat > *ivectors_out)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 105 of file ivector-plda-scoring-dense.cc.
References kaldi::ApplyPca(), Plda::ApplyTransform(), SequentialTableReader< Holder >::Done(), kaldi::EstPca(), ParseOptions::GetArg(), RandomAccessTableReader< Holder >::HasKey(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_ERR, KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), Plda::LogLikelihoodRatio(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), PldaConfig::Register(), ParseOptions::Register(), MatrixBase< Real >::Row(), kaldi::TransformIvectors(), RandomAccessTableReader< Holder >::Value(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   using namespace kaldi;
   typedef kaldi::int32 int32;
   try {
     const char *usage =
       "Perform PLDA scoring for speaker diarization.  The input reco2utt\n"
       "should be of the form <recording-id> <seg1> <seg2> ... <segN> and\n"
       "there should be one iVector for each segment.  PLDA scoring is\n"
       "performed between all pairs of iVectors in a recording and outputs\n"
       "an archive of score matrices, one for each recording-id.  The rows\n"
       "and columns of the the matrix correspond the sorted order of the\n"
       "segments.\n"
       "Usage: ivector-plda-scoring-dense [options] <plda> <reco2utt>"
       " <ivectors-rspecifier> <scores-wspecifier>\n"
       "e.g.: \n"
       "  ivector-plda-scoring-dense plda reco2utt scp:ivectors.scp"
       " ark:scores.ark ark,t:ivectors.1.ark\n";
     ParseOptions po(usage);
     BaseFloat target_energy = 0.5;
     PldaConfig plda_config;
     plda_config.Register(&po);
     po.Register("target-energy", &target_energy,
       "Reduce dimensionality of i-vectors using a recording-dependent"
       " PCA such that this fraction of the total energy remains.");
     KALDI_ASSERT(target_energy <= 1.0);
     po.Read(argc, argv);
     if (po.NumArgs() != 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string plda_rxfilename = po.GetArg(1),
       reco2utt_rspecifier = po.GetArg(2),
       ivector_rspecifier = po.GetArg(3),
       scores_wspecifier = po.GetArg(4);
     Plda plda;
     ReadKaldiObject(plda_rxfilename, &plda);
     SequentialTokenVectorReader reco2utt_reader(reco2utt_rspecifier);
     RandomAccessBaseFloatVectorReader ivector_reader(ivector_rspecifier);
     BaseFloatMatrixWriter scores_writer(scores_wspecifier);
     int32 num_reco_err = 0,
           num_reco_done = 0;
     for (; !reco2utt_reader.Done(); reco2utt_reader.Next()) {
       Plda this_plda(plda);
       std::string reco = reco2utt_reader.Key();
       std::vector<std::string> uttlist = reco2utt_reader.Value();
       std::vector<Vector<BaseFloat> > ivectors;
       for (size_t i = 0; i < uttlist.size(); i++) {
         std::string utt = uttlist[i];
         if (!ivector_reader.HasKey(utt)) {
           KALDI_ERR << "No iVector present in input for utterance " << utt;
         }
         Vector<BaseFloat> ivector = ivector_reader.Value(utt);
         ivectors.push_back(ivector);
       }
       if (ivectors.size() == 0) {
         KALDI_WARN << "Not producing output for recording " << reco
                    << " since no segments had iVectors";
         num_reco_err++;
       } else {
         Matrix<BaseFloat> ivector_mat(ivectors.size(), ivectors[0].Dim()),
                           ivector_mat_pca,
                           ivector_mat_plda,
                           pca_transform,
                           scores(ivectors.size(), ivectors.size());
         for (size_t i = 0; i < ivectors.size(); i++) {
           ivector_mat.Row(i).CopyFromVec(ivectors[i]);
         }
         if (EstPca(ivector_mat, target_energy, &pca_transform)) {
           // Apply the PCA transform to the raw i-vectors.
           ApplyPca(ivector_mat, pca_transform, &ivector_mat_pca);
           // Apply the PCA transform to the parameters of the PLDA model.
           this_plda.ApplyTransform(Matrix<double>(pca_transform));
           // Now transform the i-vectors using the reduced PLDA model.
           TransformIvectors(ivector_mat_pca, plda_config, this_plda,
             &ivector_mat_plda);
         } else {
           KALDI_WARN << "Unable to compute conversation dependent PCA for"
             << " recording " << reco << ".";
           TransformIvectors(ivector_mat, plda_config, this_plda,
           &ivector_mat_plda);
         }
         for (int32 i = 0; i < ivector_mat_plda.NumRows(); i++) {
           for (int32 j = 0; j < ivector_mat_plda.NumRows(); j++) {
             scores(i, j) = this_plda.LogLikelihoodRatio(Vector<double>(
               ivector_mat_plda.Row(i)), 1.0,
               Vector<double>(ivector_mat_plda.Row(j)));
           }
         }
         scores_writer.Write(reco, scores);
         num_reco_done++;
       }
     }
     KALDI_LOG << "Processed " << num_reco_done << " recordings, "
               << num_reco_err << " had errors.";
     return (num_reco_done != 0 ? 0 : 1 );
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }