Kaldi: lat/kaldi-lattice-test.cc File Reference
kaldi-lattice-test.cc File Reference
#include "lat/kaldi-lattice.h"
#include "fstext/rand-fst.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
CompactLattice * RandCompactLattice ()
Lattice * RandLattice ()
void TestCompactLatticeTable (bool binary)
void TestCompactLatticeTableCross (bool binary)
void TestLatticeTable (bool binary)
void TestLatticeTableCross (bool binary)
int main ()
Function Documentation
main()
int main ()
Definition at line 161 of file kaldi-lattice-test.cc.
References rnnlm::i, kaldi::TestCompactLatticeTable(), kaldi::TestCompactLatticeTableCross(), kaldi::TestLatticeTable(), and kaldi::TestLatticeTableCross().
            {
   using namespace kaldi;
   for (int i = 0; i < 2; i++) {
     bool binary = (i%2 == 0);
     TestCompactLatticeTable(binary);
     TestCompactLatticeTableCross(binary);
     TestLatticeTable(binary);
     TestLatticeTableCross(binary);
   }
   std::cout << "Test OK\n";
   unlink("tmpf");
 }