Kaldi: util/kaldi-io-test.cc File Reference
kaldi-io-test.cc File Reference
#include <unistd.h>
#include "base/io-funcs.h"
#include "util/kaldi-io.h"
#include "base/kaldi-math.h"
#include "base/kaldi-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void UnitTestClassifyRxfilename ()
void UnitTestClassifyWxfilename ()
void UnitTestIoNew (bool binary)
void UnitTestIoPipe (bool binary)
void UnitTestIoStandard ()
void UnitTestNativeFilename ()
int main (int argc, const char **argv)
Function Documentation
main()
int main (int argc, const char ** argv)
Definition at line 351 of file kaldi-io-test.cc.
References KALDI_ASSERT, kaldi::UnitTestClassifyRxfilename(), kaldi::UnitTestClassifyWxfilename(), kaldi::UnitTestIoNew(), kaldi::UnitTestIoPipe(), kaldi::UnitTestIoStandard(), and kaldi::UnitTestNativeFilename().
{
   using namespace kaldi;
 #if defined(_MSC_VER) && !defined(KALDI_CYGWIN_COMPAT)
   if (argc > 1 && strcmp(argv[1], "cat") == 0)
     return TinyCat(argc - 2, argv + 2);
 #endif
   UnitTestNativeFilename();
   UnitTestIoNew(false);
   UnitTestIoNew(true);
   UnitTestIoPipe(true);
   UnitTestIoPipe(false);
   UnitTestIoStandard();
   UnitTestClassifyRxfilename();
   UnitTestClassifyWxfilename();
   KALDI_ASSERT(1);  // just wanted to check that KALDI_ASSERT does not fail
   // for 1.
   return 0;
 }