Kaldi: util/kaldi-table-test.cc File Reference
kaldi-table-test.cc File Reference
#include "base/io-funcs.h"
#include "util/kaldi-io.h"
#include "base/kaldi-math.h"
#include "util/kaldi-table.h"
#include "util/kaldi-holder.h"
#include "util/table-types.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void UnitTestReadScriptFile ()
void UnitTestClassifyWspecifier ()
void UnitTestClassifyRspecifier ()
void UnitTestTableSequentialInt32 (bool binary)
void UnitTestTableSequentialBool (bool binary)
void UnitTestTableSequentialDouble (bool binary)
void UnitTestTableSequentialDoubleBoth (bool binary, bool read_scp)
void UnitTestTableSequentialInt32VectorBoth (bool binary, bool read_scp)
void UnitTestTableSequentialInt32PairVectorBoth (bool binary, bool read_scp)
void UnitTestTableSequentialInt32VectorVectorBoth (bool binary, bool read_scp)
void UnitTestTableSequentialInt32Script (bool binary)
void UnitTestTableSequentialDoubleMatrixBoth (bool binary, bool read_scp)
void UnitTestTableSequentialBaseFloatVectorBoth (bool binary, bool read_scp)
template<class T >
void RandomizeVector (std::vector< T > *v)
void UnitTestTableRandomBothDouble (bool binary, bool read_scp, bool sorted, bool called_sorted, bool once)
void UnitTestRangesMatrix (bool binary)
void UnitTestTableRandomBothDoubleMatrix (bool binary, bool read_scp, bool sorted, bool called_sorted, bool once)
int main ()
Function Documentation
main()
int main ()
Definition at line 1057 of file kaldi-table-test.cc.
References rnnlm::d, rnnlm::i, rnnlm::j, kaldi::UnitTestClassifyRspecifier(), kaldi::UnitTestClassifyWspecifier(), kaldi::UnitTestRangesMatrix(), kaldi::UnitTestReadScriptFile(), kaldi::UnitTestTableRandomBothDouble(), kaldi::UnitTestTableRandomBothDoubleMatrix(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
            {
   using namespace kaldi;
   UnitTestReadScriptFile();
   UnitTestClassifyWspecifier();
   UnitTestClassifyRspecifier();
   for (int i = 0; i < 10; i++) {
     bool b = (i == 0);
     UnitTestTableSequentialBool(b);
     UnitTestTableSequentialInt32(b);
     UnitTestTableSequentialInt32Script(b);
     UnitTestTableSequentialDouble(b);
     UnitTestRangesMatrix(b);
     for (int j = 0; j < 2; j++) {
       bool c = (j == 0);
       UnitTestTableSequentialDoubleBoth(b, c);
       UnitTestTableSequentialDoubleMatrixBoth(b, c);
       UnitTestTableSequentialInt32VectorBoth(b, c);
       UnitTestTableSequentialInt32PairVectorBoth(b, c);
       UnitTestTableSequentialInt32VectorVectorBoth(b, c);
       UnitTestTableSequentialBaseFloatVectorBoth(b, c);
       for (int k = 0; k < 2; k++) {
         bool d = (k == 0);
         for (int l = 0; l < 2; l++) {
           bool e = (l == 0);
           for (int m = 0; m < 2; m++) {
             bool f = (m == 0);
             UnitTestTableRandomBothDouble(b, c, d, e, f);
             UnitTestTableRandomBothDoubleMatrix(b, c, d, e, f);
           }
         }
       }
     }
   }
   std::cout << "Test OK.\n";
   return 0;
 }