Kaldi: base/kaldi-math-test.cc File Reference
kaldi-math-test.cc File Reference
#include "base/kaldi-math.h"
#include <limits>
#include "base/timer.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
template<class I >
void UnitTestGcdLcmTpl ()
void UnitTestRoundUpToNearestPowerOfTwo ()
void UnitTestDivideRoundingDown ()
void UnitTestGcdLcm ()
void UnitTestRand ()
void UnitTestLogAddSub ()
void UnitTestDefines ()
void UnitTestAssertFunc ()
template<class I >
void UnitTestFactorizeTpl ()
void UnitTestFactorize ()
void UnitTestApproxEqual ()
template<class Real >
void UnitTestExpSpeed ()
template<class Real >
void UnitTestLogSpeed ()
int main ()
Function Documentation
main()
int main ()
Definition at line 318 of file kaldi-math-test.cc.
References kaldi::UnitTestApproxEqual(), kaldi::UnitTestAssertFunc(), kaldi::UnitTestDefines(), kaldi::UnitTestDivideRoundingDown(), kaldi::UnitTestFactorize(), kaldi::UnitTestGcdLcm(), kaldi::UnitTestLogAddSub(), kaldi::UnitTestRand(), and kaldi::UnitTestRoundUpToNearestPowerOfTwo().
            {
   using namespace kaldi;
   UnitTestApproxEqual();
   UnitTestGcdLcm();
   UnitTestFactorize();
   UnitTestDefines();
   UnitTestLogAddSub();
   UnitTestRand();
   UnitTestAssertFunc();
   UnitTestRoundUpToNearestPowerOfTwo();
   UnitTestDivideRoundingDown();
   UnitTestExpSpeed<float>();
   UnitTestExpSpeed<double>();
   UnitTestLogSpeed<float>();
   UnitTestLogSpeed<double>();
 }