Kaldi: latbin/lattice-copy.cc File Reference
lattice-copy.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "fstext/fstext-lib.h"
#include "lat/kaldi-lattice.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
int32 CopySubsetLattices (std::string filename, SequentialLatticeReader *lattice_reader, LatticeWriter *lattice_writer, bool include=true, bool ignore_missing=false, bool sorted=false)
int32 CopySubsetLattices (std::string filename, SequentialCompactLatticeReader *lattice_reader, CompactLatticeWriter *lattice_writer, bool include=true, bool ignore_missing=false, bool sorted=false)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 131 of file lattice-copy.cc.
References kaldi::ClassifyRspecifier(), kaldi::CopySubsetLattices(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_ERR, KALDI_LOG, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), RspecifierOptions::sorted, SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     using fst::SymbolTable;
     using fst::VectorFst;
     using fst::StdArc;
     const char *usage =
         "Copy lattices (e.g. useful for changing to text mode or changing\n"
         "format to standard from compact lattice.)\n"
         "The --include and --exclude options can be used to copy only a subset "
         "of lattices, where are the --include option specifies the "
         "whitelisted utterances that would be copied and --exclude option "
         "specifies the blacklisted utterances that would not be copied.\n"
         "Only one of --include and --exclude can be supplied.\n"
         "Usage: lattice-copy [options] lattice-rspecifier lattice-wspecifier\n"
         " e.g.: lattice-copy --write-compact=false ark:1.lats ark,t:text.lats\n"
         "See also: lattice-scale, lattice-to-fst, and\n"
         "   the script egs/wsj/s5/utils/convert_slf.pl\n";
     ParseOptions po(usage);
     bool write_compact = true, ignore_missing = false;
     std::string include_rxfilename;
     std::string exclude_rxfilename;
     po.Register("write-compact", &write_compact, "If true, write in normal (compact) form.");
     po.Register("include", &include_rxfilename,
                 "Text file, the first field of each "
                 "line being interpreted as the "
                 "utterance-id whose lattices will be included");
     po.Register("exclude", &exclude_rxfilename,
                 "Text file, the first field of each "
                 "line being interpreted as an utterance-id "
                 "whose lattices will be excluded");
     po.Register("ignore-missing", &ignore_missing,
                 "Exit with status 0 even if no lattices are copied");
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string lats_rspecifier = po.GetArg(1),
         lats_wspecifier = po.GetArg(2);
     RspecifierOptions opts;
     ClassifyRspecifier(lats_rspecifier, NULL, &opts);
     bool sorted = opts.sorted;
     int32 n_done = 0;
     if (write_compact) {
       SequentialCompactLatticeReader lattice_reader(lats_rspecifier);
       CompactLatticeWriter lattice_writer(lats_wspecifier);
       if (include_rxfilename != "") {
         if (exclude_rxfilename != "") {
           KALDI_ERR << "should not have both --exclude and --include option!";
         }
         return CopySubsetLattices(include_rxfilename,
             &lattice_reader, &lattice_writer,
             true, ignore_missing, sorted);
       } else if (exclude_rxfilename != "") {
         return CopySubsetLattices(exclude_rxfilename,
             &lattice_reader, &lattice_writer,
             false, ignore_missing);
       }
       for (; !lattice_reader.Done(); lattice_reader.Next(), n_done++)
         lattice_writer.Write(lattice_reader.Key(), lattice_reader.Value());
     } else {
       SequentialLatticeReader lattice_reader(lats_rspecifier);
       LatticeWriter lattice_writer(lats_wspecifier);
       if (include_rxfilename != "") {
         if (exclude_rxfilename != "") {
           KALDI_ERR << "should not have both --exclude and --include option!";
         }
         return CopySubsetLattices(include_rxfilename,
             &lattice_reader, &lattice_writer,
             true, ignore_missing, sorted);
       } else if (exclude_rxfilename != "") {
         return CopySubsetLattices(exclude_rxfilename,
             &lattice_reader, &lattice_writer,
             true, ignore_missing);
       }
       for (; !lattice_reader.Done(); lattice_reader.Next(), n_done++)
         lattice_writer.Write(lattice_reader.Key(), lattice_reader.Value());
     }
     KALDI_LOG << "Done copying " << n_done << " lattices.";
     if (ignore_missing) return 0;
     return (n_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }