Kaldi: bin/matrix-sum.cc File Reference
matrix-sum.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-matrix.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
int32 TypeOneUsage (const ParseOptions &po, BaseFloat scale1, BaseFloat scale2)
int32 TypeOneUsageAverage (const ParseOptions &po)
int32 TypeTwoUsage (const ParseOptions &po, bool binary)
int32 TypeThreeUsage (const ParseOptions &po, bool binary, bool average)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 261 of file matrix-sum.cc.
References kaldi::ClassifyRspecifier(), kaldi::ClassifyWspecifier(), ParseOptions::GetArg(), KALDI_ASSERT, KALDI_ERR, kaldi::kNoRspecifier, kaldi::kNoWspecifier, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), kaldi::TypeOneUsage(), kaldi::TypeOneUsageAverage(), kaldi::TypeThreeUsage(), and kaldi::TypeTwoUsage().
{
   try {
     using namespace kaldi;
     const char *usage =
         "Add matrices (supports various forms)\n"
         "\n"
         "Type one usage:\n"
         " matrix-sum [options] <matrix-in-rspecifier1> [<matrix-in-rspecifier2>"
         " <matrix-in-rspecifier3> ...] <matrix-out-wspecifier>\n"
         "  e.g.: matrix-sum ark:1.weights ark:2.weights ark:combine.weights\n"
         "  This usage supports the --scale1 and --scale2 options to scale the\n"
         "  first two input tables.\n"
         "Type two usage (sums a single table input to produce a single output):\n"
         " matrix-sum [options] <matrix-in-rspecifier> <matrix-out-wxfilename>\n"
         " e.g.: matrix-sum --binary=false mats.ark sum.mat\n"
         "Type three usage (sums or averages single-file inputs to produce\n"
         "a single output):\n"
         " matrix-sum [options] <matrix-in-rxfilename1> <matrix-in-rxfilename2> ..."
         " <matrix-out-wxfilename>\n"
         " e.g.: matrix-sum --binary=false 1.mat 2.mat 3.mat sum.mat\n"
         "See also: matrix-sum-rows, copy-matrix\n";
     BaseFloat scale1 = 1.0, scale2 = 1.0;
     bool average = false;
     bool binary = true;
     ParseOptions po(usage);
     po.Register("scale1", &scale1, "Scale applied to first matrix "
                 "(only for type one usage)");
     po.Register("scale2", &scale2, "Scale applied to second matrix "
                 "(only for type one usage)");
     po.Register("binary", &binary, "If true, write output as binary (only "
                 "relevant for usage types two or three");
     po.Register("average", &average, "If true, compute average instead of "
                 "sum; currently compatible with type 3 or type 1 usage.");
     po.Read(argc, argv);
     int32 N = po.NumArgs(), exit_status;
     if (po.NumArgs() >= 2 &&
         ClassifyWspecifier(po.GetArg(N), NULL, NULL, NULL) != kNoWspecifier) {
       if (average)
         // average option with type one usage.";
             exit_status = TypeOneUsageAverage(po);
           else
         // output to table.
         exit_status = TypeOneUsage(po, scale1, scale2);
     } else if (po.NumArgs() == 2 &&
                ClassifyRspecifier(po.GetArg(1), NULL, NULL) != kNoRspecifier &&
                ClassifyWspecifier(po.GetArg(N), NULL, NULL, NULL) ==
                kNoWspecifier) {
       KALDI_ASSERT(scale1 == 1.0 && scale2 == 1.0);
       if (average)
         KALDI_ERR << "--average option not compatible with type two usage.";
       // input from a single table, output not to table.
       exit_status = TypeTwoUsage(po, binary);
     } else if (po.NumArgs() >= 2 &&
                ClassifyRspecifier(po.GetArg(1), NULL, NULL) == kNoRspecifier &&
                ClassifyWspecifier(po.GetArg(N), NULL, NULL, NULL) == kNoWspecifier) {
       KALDI_ASSERT(scale1 == 1.0 && scale2 == 1.0);
       // summing flat files.
       exit_status = TypeThreeUsage(po, binary, average);
     } else {
       po.PrintUsage();
       exit(1);
     }
     return exit_status;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }