Kaldi: kaldi::unittest Namespace Reference
kaldi::unittest Namespace Reference
Functions
void RandPosdefSpMatrix (int32 dim, SpMatrix< BaseFloat > *matrix, TpMatrix< BaseFloat > *matrix_sqrt, BaseFloat *logdet)
void RandDiagGaussFeatures (int32 num_samples, const VectorBase< BaseFloat > &mean, const VectorBase< BaseFloat > &sqrt_var, MatrixBase< BaseFloat > *feats)
void RandFullGaussFeatures (int32 num_samples, const VectorBase< BaseFloat > &mean, const TpMatrix< BaseFloat > &sqrt_var, MatrixBase< BaseFloat > *feats)
void InitRandDiagGmm (int32 dim, int32 num_comp, DiagGmm *gmm)
void InitRandFullGmm (int32 dim, int32 num_comp, FullGmm *gmm)
Function Documentation
InitRandDiagGmm()
void InitRandDiagGmm (int32 dim, int32 num_comp, DiagGmm * gmm)
Definition at line 91 of file model-test-common.cc.
References DiagGmm::ComputeGconsts(), rnnlm::d, kaldi::Exp(), kaldi::RandGauss(), DiagGmm::Resize(), VectorBase< Real >::Scale(), DiagGmm::SetInvVarsAndMeans(), DiagGmm::SetWeights(), and VectorBase< Real >::Sum().
Referenced by kaldi::TestFmpe(), TestMllrAccsIO(), UnitTestAmDiagGmm(), UnitTestMleAmDiagGmm(), and UnitTestRegtreeMllrDiagGmm().
{
   Vector<BaseFloat> weights(num_comp);
   Matrix<BaseFloat> means(num_comp, dim), inv_vars(num_comp, dim);
   for (int32 m = 0; m < num_comp; m++) {
     weights(m) = Exp(RandGauss());
     for (int32 d= 0; d < dim; d++) {
       means(m, d) = RandGauss() / (1 + d);
       inv_vars(m, d) = Exp(RandGauss() / (1 + d)) + 1e-2;
     }
   }
   weights.Scale(1.0 / weights.Sum());
   gmm->Resize(num_comp, dim);
   gmm->SetWeights(weights);
   gmm->SetInvVarsAndMeans(inv_vars, means);
   gmm->ComputeGconsts();
 }
InitRandFullGmm()
void InitRandFullGmm (int32 dim, int32 num_comp, FullGmm * gmm)
Definition at line 110 of file model-test-common.cc.
References FullGmm::ComputeGconsts(), rnnlm::d, kaldi::RandGauss(), RandPosdefSpMatrix(), kaldi::RandUniform(), FullGmm::Resize(), VectorBase< Real >::Scale(), FullGmm::SetInvCovarsAndMeans(), and FullGmm::SetWeights().
Referenced by TestSgmm2Fmllr(), UnitTestEstimateSgmm2(), UnitTestFullGmmEst(), kaldi::UnitTestIvectorExtractor(), and UnitTestSgmm2().
{
   Vector<BaseFloat> weights(num_comp);
   Matrix<BaseFloat> means(num_comp, dim);
   std::vector< SpMatrix<BaseFloat> > invcovars(num_comp);
   for (int32 mix = 0; mix < num_comp; mix++) {
     invcovars[mix].Resize(dim);
   }
   BaseFloat tot_weight = 0.0;
   for (int32 m = 0; m < num_comp; m++) {
     weights(m) = RandUniform() + 1e-2;
     for (int32 d= 0; d < dim; d++) {
       means(m, d) = RandGauss();
     }
     RandPosdefSpMatrix(dim, &invcovars[m], NULL, NULL);
     invcovars[m].InvertDouble();
     tot_weight += weights(m);
   }
   weights.Scale(1/tot_weight);
   gmm->Resize(num_comp, dim);
   gmm->SetWeights(weights);
   gmm->SetInvCovarsAndMeans(invcovars, means);
   gmm->ComputeGconsts();
 }
RandDiagGaussFeatures()
void RandDiagGaussFeatures (int32 num_samples, const VectorBase< BaseFloat > & mean, const VectorBase< BaseFloat > & sqrt_var, MatrixBase< BaseFloat > * feats)
Definition at line 52 of file model-test-common.cc.
References rnnlm::d, VectorBase< Real >::Dim(), KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), kaldi::RandGauss(), and MatrixBase< Real >::Row().
Referenced by TestSgmm2Fmllr(), UnitTestEstimateSgmm2(), and UnitTestMleAmDiagGmm().
{
   int32 dim = mean.Dim();
   KALDI_ASSERT(feats != NULL);
   KALDI_ASSERT(feats->NumRows() == num_samples &&
                feats->NumCols() == dim);
   KALDI_ASSERT(sqrt_var.Dim() == dim);
   Vector<BaseFloat> rnd_vec(dim);
   for (int32 counter = 0; counter < num_samples; counter++) {
     for (int32 d = 0; d < dim; d++) {
       rnd_vec(d) = RandGauss();
     }
     feats->Row(counter).CopyFromVec(mean);
     feats->Row(counter).AddVecVec(1.0, sqrt_var, rnd_vec, 1.0);
   }
 }
RandFullGaussFeatures()
void RandFullGaussFeatures (int32 num_samples, const VectorBase< BaseFloat > & mean, const TpMatrix< BaseFloat > & sqrt_var, MatrixBase< BaseFloat > * feats)
Definition at line 72 of file model-test-common.cc.
References rnnlm::d, VectorBase< Real >::Dim(), KALDI_ASSERT, kaldi::kNoTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), PackedMatrix< Real >::NumRows(), kaldi::RandGauss(), and MatrixBase< Real >::Row().
{
   int32 dim = mean.Dim();
   KALDI_ASSERT(feats != NULL);
   KALDI_ASSERT(feats->NumRows() == num_samples && feats->NumCols() == dim);
   KALDI_ASSERT(sqrt_var.NumRows() == dim);
   Vector<BaseFloat> rnd_vec(dim);
   for (int32 counter = 0; counter < num_samples; counter++) {
     for (int32 d = 0; d < dim; d++) {
       rnd_vec(d) = RandGauss();
     }
     feats->Row(counter).CopyFromVec(mean);
     feats->Row(counter).AddTpVec(1.0, sqrt_var, kNoTrans, rnd_vec, 1.0);
   }
 }
RandPosdefSpMatrix()
void RandPosdefSpMatrix (int32 dim, SpMatrix< BaseFloat > * matrix, TpMatrix< BaseFloat > * matrix_sqrt, BaseFloat * logdet)
Definition at line 30 of file model-test-common.cc.
References SpMatrix< Real >::AddMat2(), TpMatrix< Real >::Cholesky(), MatrixBase< Real >::Cond(), KALDI_LOG, kaldi::kNoTrans, SpMatrix< Real >::LogPosDefDet(), and MatrixBase< Real >::SetRandn().
Referenced by InitRandFullGmm().
{
   // generate random (non-singular) matrix
   Matrix<BaseFloat> tmp(dim, dim);
   while (1) {
     tmp.SetRandn();
     if (tmp.Cond() < 100) break;
     KALDI_LOG << "Condition number of random matrix large "
               << static_cast<float>(tmp.Cond())
               << ", trying again (this is normal)\n";
   }
   // tmp * tmp^T will give positive definite matrix
   matrix->AddMat2(1.0, tmp, kNoTrans, 0.0);
   if (matrix_sqrt != NULL) matrix_sqrt->Cholesky(*matrix);
   if (logdet != NULL) *logdet = matrix->LogPosDefDet();
   if ((matrix_sqrt == NULL) && (logdet == NULL)) {
     TpMatrix<BaseFloat> sqrt(dim);
     sqrt.Cholesky(*matrix);
   }
 }