Kaldi: nnet3bin/nnet3-acc-lda-stats.cc File Reference
nnet3-acc-lda-stats.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet3/nnet-nnet.h"
#include "nnet3/nnet-example-utils.h"
#include "nnet3/nnet-optimize.h"
#include "transform/lda-estimate.h"
Classes
class NnetLdaStatsAccumulator
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 135 of file nnet3-acc-lda-stats.cc.
References NnetLdaStatsAccumulator::AccStats(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_LOG, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), SequentialTableReader< Holder >::Value(), and NnetLdaStatsAccumulator::WriteStats().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Accumulate statistics in the same format as acc-lda (i.e. stats for\n"
         "estimation of LDA and similar types of transform), starting from nnet\n"
         "training examples.  This program puts the features through the network,\n"
         "and the network output will be the features; the supervision in the\n"
         "training examples is used for the class labels.  Used in obtaining\n"
         "feature transforms that help nnet training work better.\n"
         "\n"
         "Usage:  nnet3-acc-lda-stats [options] <raw-nnet-in> <training-examples-in> <lda-stats-out>\n"
         "e.g.:\n"
         "nnet3-acc-lda-stats 0.raw ark:1.egs 1.acc\n"
         "See also: nnet-get-feature-transform\n";
     bool binary_write = true;
     BaseFloat rand_prune = 0.0;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("rand-prune", &rand_prune,
                 "Randomized pruning threshold for posteriors");
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string nnet_rxfilename = po.GetArg(1),
         examples_rspecifier = po.GetArg(2),
         lda_accs_wxfilename = po.GetArg(3);
     Nnet nnet;
     ReadKaldiObject(nnet_rxfilename, &nnet);
     NnetLdaStatsAccumulator accumulator(rand_prune, nnet);
     int64 num_egs = 0;
     SequentialNnetExampleReader example_reader(examples_rspecifier);
     for (; !example_reader.Done(); example_reader.Next(), num_egs++)
       accumulator.AccStats(example_reader.Value());
     KALDI_LOG << "Processed " << num_egs << " examples.";
     // the next command will die if we accumulated no stats.
     accumulator.WriteStats(lda_accs_wxfilename, binary_write);
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }