Kaldi: nnet2bin/nnet-train-parallel.cc File Reference
nnet-train-parallel.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet2/nnet-update-parallel.h"
#include "nnet2/am-nnet.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 27 of file nnet-train-parallel.cc.
References kaldi::nnet2::DoBackpropParallel(), kaldi::g_num_threads, ParseOptions::GetArg(), AmNnet::GetNnet(), KALDI_ASSERT, KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), AmNnet::Read(), ParseOptions::Read(), TransitionModel::Read(), ParseOptions::Register(), Output::Stream(), Input::Stream(), AmNnet::Write(), TransitionModel::Write(), and Nnet::ZeroStats().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet2;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Train the neural network parameters with backprop and stochastic\n"
         "gradient descent using minibatches.  As nnet-train-simple, but\n"
         "uses multiple threads in a Hogwild type of update (for CPU, not GPU).\n"
         "\n"
         "Usage:  nnet-train-parallel [options] <model-in> <training-examples-in> <model-out>\n"
         "\n"
         "e.g.:\n"
         "nnet-train-parallel --num-threads=8 1.nnet ark:1.1.egs 2.nnet\n";
     bool binary_write = true;
     bool zero_stats = true;
     int32 minibatch_size = 1024;
     int32 srand_seed = 0;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("zero-stats", &zero_stats, "If true, zero stats "
                 "stored with the neural net (only affects mixing up).");
     po.Register("srand", &srand_seed,
                 "Seed for random number generator (e.g., for dropout)");
     po.Register("num-threads", &g_num_threads, "Number of training threads to use "
                 "in the parallel update. [Note: if you use a parallel "
                 "implementation of BLAS, the actual number of threads may be larger.]");
     po.Register("minibatch-size", &minibatch_size, "Number of examples to use for "
                 "each minibatch during training.");
     po.Read(argc, argv);
     srand(srand_seed);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string nnet_rxfilename = po.GetArg(1),
         examples_rspecifier = po.GetArg(2),
         nnet_wxfilename = po.GetArg(3);
     TransitionModel trans_model;
     AmNnet am_nnet;
     {
       bool binary_read;
       Input ki(nnet_rxfilename, &binary_read);
       trans_model.Read(ki.Stream(), binary_read);
       am_nnet.Read(ki.Stream(), binary_read);
     }
     KALDI_ASSERT(minibatch_size > 0);
     if (zero_stats) am_nnet.GetNnet().ZeroStats();
     double num_examples = 0;
     SequentialNnetExampleReader example_reader(examples_rspecifier);
     DoBackpropParallel(am_nnet.GetNnet(),
                        minibatch_size,
                        &example_reader,
                        &num_examples,
                        &(am_nnet.GetNnet()));
     {
       Output ko(nnet_wxfilename, binary_write);
       trans_model.Write(ko.Stream(), binary_write);
       am_nnet.Write(ko.Stream(), binary_write);
     }
     KALDI_LOG << "Finished training, processed " << num_examples
               << " training examples (weighted).  Wrote model to "
               << nnet_wxfilename;
     return (num_examples == 0 ? 1 : 0);
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }