Kaldi: nnet3bin/nnet3-am-info.cc File Reference
nnet3-am-info.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "nnet3/am-nnet-simple.h"
#include "hmm/transition-model.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 25 of file nnet3-am-info.cc.
References ParseOptions::GetArg(), AmNnetSimple::Info(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), AmNnetSimple::Read(), ParseOptions::Read(), TransitionModel::Read(), and Input::Stream().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     const char *usage =
         "Print some text information about an nnet3 neural network, to\n"
         "standard output\n"
         "\n"
         "Usage:  nnet3-am-info [options] <nnet>\n"
         "e.g.:\n"
         " nnet3-am-info 0.mdl\n"
         "See also: nnet3-am-info\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 1) {
       po.PrintUsage();
       exit(1);
     }
     std::string  nnet_rxfilename = po.GetArg(1);
     TransitionModel trans_model;
     AmNnetSimple am_nnet;
     {
       bool binary;
       Input ki(nnet_rxfilename, &binary);
       trans_model.Read(ki.Stream(), binary);
       am_nnet.Read(ki.Stream(), binary);
     }
     std::cout << am_nnet.Info();
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }