Kaldi: nnet3/nnet-compile-utils-test.cc File Reference
nnet-compile-utils-test.cc File Reference
#include "util/common-utils.h"
#include "nnet3/nnet-compile-utils.h"
Classes
struct ComparePair
struct PairIsEqualComparator
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
void PrintVectorVectorPair (std::vector< std::vector< std::pair< int32, int32 > > > vec_vec_pair)
void UnitTestSplitLocationsBackward (bool verbose)
void UnitTestHasContiguousProperty ()
void UnitTestEnsureContiguousProperty ()
void UnitTestSplitLocations (bool verbose)
int main ()
Function Documentation
main()
int main ()
Definition at line 363 of file nnet-compile-utils-test.cc.
References KALDI_LOG, kaldi::nnet3::UnitTestEnsureContiguousProperty(), kaldi::nnet3::UnitTestHasContiguousProperty(), kaldi::nnet3::UnitTestSplitLocations(), and kaldi::nnet3::UnitTestSplitLocationsBackward().
             {
   using namespace kaldi;
   using namespace kaldi::nnet3;
   bool verbose = false;
   for (int32 loop = 0; loop < 10; loop++)  {
     UnitTestSplitLocations(verbose);
     UnitTestSplitLocationsBackward(verbose);
     UnitTestHasContiguousProperty();
     UnitTestEnsureContiguousProperty();
   }
   KALDI_LOG << "Tests passed.";
   return 0;
 }