Kaldi: nnet2bin/nnet1-to-raw-nnet.cc File Reference
nnet1-to-raw-nnet.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet/nnet-nnet.h"
#include "nnet/nnet-affine-transform.h"
#include "nnet/nnet-activation.h"
#include "nnet/nnet-various.h"
#include "nnet2/nnet-nnet.h"
#include "nnet2/nnet-component.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
nnet2::Component * ConvertAffineTransformComponent (const nnet1::Component &nnet1_component, const bool use_preconditioned_affine_component)
nnet2::Component * ConvertSoftmaxComponent (const nnet1::Component &nnet1_component)
nnet2::Component * ConvertSigmoidComponent (const nnet1::Component &nnet1_component)
nnet2::Component * ConvertSpliceComponent (const nnet1::Component &nnet1_component)
nnet2::Component * ConvertAddShiftComponent (const nnet1::Component &nnet1_component)
nnet2::Component * ConvertRescaleComponent (const nnet1::Component &nnet1_component)
nnet2::Component * ConvertComponent (const nnet1::Component &nnet1_component, const bool use_preconditioned_affine_component)
nnet2::Nnet * ConvertNnet1ToNnet2 (const nnet1::Nnet &nnet1, const bool use_preconditioned_affine_component)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 176 of file nnet1-to-raw-nnet.cc.
References kaldi::ConvertNnet1ToNnet2(), ParseOptions::GetArg(), KALDI_LOG, ParseOptions::NumArgs(), kaldi::PrintableWxfilename(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Convert nnet1 neural net to nnet2 'raw' neural net\n"
         "\n"
         "Usage:  nnet1-to-raw-nnet [options] <nnet1-in> <nnet2-out>\n"
         "e.g.:\n"
         " nnet1-to-raw-nnet srcdir/final.nnet - | nnet-am-init dest/tree dest/topo - dest/0.mdl\n";
     bool binary_write = true, use_preconditioned_affine_component = false;
     int32 srand_seed = 0;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("use_preconditioned_affine_component",
         &use_preconditioned_affine_component,
         "Using AffineComponentPreconditionOnline instead AffineComponent");
     po.Read(argc, argv);
     srand(srand_seed);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string nnet1_rxfilename = po.GetArg(1),
         raw_nnet2_wxfilename = po.GetArg(2);
     nnet1::Nnet nnet1;
     ReadKaldiObject(nnet1_rxfilename, &nnet1);
     nnet2::Nnet *nnet2 = ConvertNnet1ToNnet2(nnet1,
         use_preconditioned_affine_component);
     WriteKaldiObject(*nnet2, raw_nnet2_wxfilename, binary_write);
     KALDI_LOG << "Converted nnet1 neural net to raw nnet2 and wrote it to "
               << PrintableWxfilename(raw_nnet2_wxfilename);
     delete nnet2;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }