Kaldi: nnet3bin/nnet3-discriminative-get-egs.cc File Reference
nnet3-discriminative-get-egs.cc File Reference
#include <sstream>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "hmm/posterior.h"
#include "nnet3/nnet-discriminative-example.h"
#include "nnet3/discriminative-supervision.h"
#include "nnet3/nnet-example-utils.h"
#include "chain/chain-supervision.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
static bool ProcessFile (const discriminative::SplitDiscriminativeSupervisionOptions &config, const TransitionModel &tmodel, const MatrixBase< BaseFloat > &feats, const MatrixBase< BaseFloat > *ivector_feats, int32 ivector_period, const discriminative::DiscriminativeSupervision &supervision, const std::string &utt_id, bool compress, UtteranceSplitter *utt_splitter, NnetDiscriminativeExampleWriter *example_writer)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 155 of file nnet3-discriminative-get-egs.cc.
References ExampleGenerationConfig::ComputeDerived(), SequentialTableReader< Holder >::Done(), UtteranceSplitter::ExitStatus(), ParseOptions::GetArg(), RandomAccessTableReader< Holder >::HasKey(), DiscriminativeSupervision::Initialize(), KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), kaldi::nnet3::ProcessFile(), ParseOptions::Read(), TransitionModel::Read(), SplitDiscriminativeSupervisionOptions::Register(), ParseOptions::Register(), ExampleGenerationConfig::Register(), Input::Stream(), RandomAccessTableReader< Holder >::Value(), and SequentialTableReader< Holder >::Value().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Get frame-by-frame examples of data for nnet3+sequence neural network\n"
         "training.  This involves breaking up utterances into pieces of sizes\n"
         "determined by the --num-frames option.\n"
         "\n"
         "Usage:  nnet3-discriminative-get-egs [options] <model> <features-rspecifier> "
         "<denominator-lattice-rspecifier> <numerator-alignment-rspecifier> <egs-wspecifier>\n"
         "\n"
         "An example [where $feats expands to the actual features]:\n"
         "  nnet3-discriminative-get-egs --left-context=25 --right-context=9 --num-frames=150,100,90 \\\n"
         "  \"$feats\" \"ark,s,cs:gunzip -c lat.1.gz\" scp:ali.scp ark:degs.1.ark\n";
     bool compress = true;
     int32 length_tolerance = 100, online_ivector_period = 1;
     std::string online_ivector_rspecifier;
     ExampleGenerationConfig eg_config;  // controls num-frames,
                                         // left/right-context, etc.
     discriminative::SplitDiscriminativeSupervisionOptions splitter_config;
     ParseOptions po(usage);
     eg_config.Register(&po);
     po.Register("compress", &compress, "If true, write egs in "
                 "compressed format (recommended)");
     po.Register("ivectors", &online_ivector_rspecifier, "Alias for --online-ivectors "
                 "option, for back compatibility");
     po.Register("online-ivectors", &online_ivector_rspecifier, "Rspecifier of ivector "
                 "features, as a matrix.");
     po.Register("online-ivector-period", &online_ivector_period, "Number of frames "
                 "between iVectors in matrices supplied to the --online-ivectors "
                 "option");
     po.Register("length-tolerance", &length_tolerance, "Tolerance for "
                 "difference in num-frames between feat and ivector matrices");
     splitter_config.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 5) {
       po.PrintUsage();
       exit(1);
     }
     eg_config.ComputeDerived();
     UtteranceSplitter utt_splitter(eg_config);
     std::string model_wxfilename = po.GetArg(1),
         feature_rspecifier = po.GetArg(2),
         den_lat_rspecifier = po.GetArg(3),
         num_ali_rspecifier = po.GetArg(4),
         examples_wspecifier = po.GetArg(5);
     TransitionModel tmodel;
     {
       bool binary;
       Input ki(model_wxfilename, &binary);
       tmodel.Read(ki.Stream(), binary);
     }
     SequentialBaseFloatMatrixReader feat_reader(feature_rspecifier);
     RandomAccessLatticeReader den_lat_reader(den_lat_rspecifier);
     RandomAccessInt32VectorReader ali_reader(num_ali_rspecifier);
     NnetDiscriminativeExampleWriter example_writer(examples_wspecifier);
     RandomAccessBaseFloatMatrixReader online_ivector_reader(
         online_ivector_rspecifier);
     int32 num_err = 0;
     for (; !feat_reader.Done(); feat_reader.Next()) {
       std::string key = feat_reader.Key();
       const Matrix<BaseFloat> &feats = feat_reader.Value();
       if (!den_lat_reader.HasKey(key)) {
         KALDI_WARN << "No denominator lattice for key " << key;
         num_err++;
       } else if (!ali_reader.HasKey(key)) {
         KALDI_WARN << "No numerator alignment for key " << key;
         num_err++;
       } else {
         discriminative::DiscriminativeSupervision supervision;
         if (!supervision.Initialize(ali_reader.Value(key),
                                     den_lat_reader.Value(key),
                                     1.0)) {
           KALDI_WARN << "Failed to convert lattice to supervision "
                      << "for utterance " << key;
           num_err++;
           continue;
         }
         const Matrix<BaseFloat> *online_ivector_feats = NULL;
         if (!online_ivector_rspecifier.empty()) {
           if (!online_ivector_reader.HasKey(key)) {
             KALDI_WARN << "No iVectors for utterance " << key;
             num_err++;
             continue;
           } else {
             // this address will be valid until we call HasKey() or Value()
             // again.
             online_ivector_feats = &(online_ivector_reader.Value(key));
           }
         }
         if (online_ivector_feats != NULL &&
             (abs(feats.NumRows() - (online_ivector_feats->NumRows() *
                                     online_ivector_period)) > length_tolerance
              || online_ivector_feats->NumRows() == 0)) {
           KALDI_WARN << "Length difference between feats " << feats.NumRows()
                      << " and iVectors " << online_ivector_feats->NumRows()
                      << "exceeds tolerance " << length_tolerance;
           num_err++;
           continue;
         }
         if (!ProcessFile(splitter_config, tmodel,
                          feats, online_ivector_feats, online_ivector_period,
                          supervision, key, compress,
                          &utt_splitter, &example_writer))
           num_err++;
       }
     }
     if (num_err > 0)
       KALDI_WARN << num_err << " utterances had errors and could "
           "not be processed.";
     // utt_splitter prints diagnostics.
     return utt_splitter.ExitStatus();
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }