Kaldi: nnet/nnet-randomizer-test.cc File Reference
nnet-randomizer-test.cc File Reference
#include "nnet/nnet-randomizer.h"
#include <numeric>
#include <vector>
#include <algorithm>
Functions
template<class Real >
static void InitRand (VectorBase< Real > *v)
template<class Real >
static void InitRand (MatrixBase< Real > *M)
template<class Real >
static void AssertEqual (const VectorBase< Real > &A, const VectorBase< Real > &B, float tol=0.001)
template<class RandomAccessIterator >
static void AssertEqual (RandomAccessIterator begin1, RandomAccessIterator end1, RandomAccessIterator begin2, RandomAccessIterator end2)
void UnitTestRandomizerMask ()
void UnitTestMatrixRandomizer ()
void UnitTestVectorRandomizer ()
void UnitTestStdVectorRandomizer ()
int main ()
Function Documentation
AssertEqual() [1/2]
static void AssertEqual (const VectorBase< Real > & A, const VectorBase< Real > & B, float tol = 0.001) static
Definition at line 48 of file nnet-randomizer-test.cc.
References VectorBase< Real >::Dim(), rnnlm::i, and KALDI_ASSERT.
{
   KALDI_ASSERT(A.Dim() == B.Dim());
   for (MatrixIndexT i = 0; i < A.Dim(); i++) {
     KALDI_ASSERT(std::abs(A(i)-B(i)) < tol);
   }
 }
AssertEqual() [2/2]
static void AssertEqual (RandomAccessIterator begin1, RandomAccessIterator end1, RandomAccessIterator begin2, RandomAccessIterator end2) static
Definition at line 59 of file nnet-randomizer-test.cc.
References KALDI_ASSERT.
{
   KALDI_ASSERT((end1 - begin1) == (end2 - begin2));
   KALDI_ASSERT(end1 > begin1);
   for ( ; begin1 < end1; ++begin1, ++begin2) {
     KALDI_ASSERT(*begin1 == *begin2);
   }
 }
InitRand() [1/2]
static void InitRand (VectorBase< Real > * v) static
Definition at line 32 of file nnet-randomizer-test.cc.
References VectorBase< Real >::Dim(), rnnlm::i, and kaldi::nnet1::RandGauss().
{
   for (MatrixIndexT i = 0;i < v->Dim();i++)
     (*v)(i) = RandGauss();
 }
InitRand() [2/2]
static void InitRand (MatrixBase< Real > * M) static
Definition at line 38 of file nnet-randomizer-test.cc.
References MatrixBase< Real >::Cond(), rnnlm::i, rnnlm::j, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and kaldi::nnet1::RandGauss().
{
   do {
     for (MatrixIndexT i = 0;i < M->NumRows();i++)
       for (MatrixIndexT j = 0;j < M->NumCols();j++)
         (*M)(i, j) = RandGauss();
   } while (M->NumRows() != 0 && M->Cond() > 100);
 }
main()
int main ()
Definition at line 232 of file nnet-randomizer-test.cc.
References UnitTestMatrixRandomizer(), UnitTestRandomizerMask(), UnitTestStdVectorRandomizer(), and UnitTestVectorRandomizer().
            {
   UnitTestRandomizerMask();
   UnitTestMatrixRandomizer();
   UnitTestVectorRandomizer();
   UnitTestStdVectorRandomizer();
   std::cout << "Tests succeeded.\n";
 }
UnitTestMatrixRandomizer()
void UnitTestMatrixRandomizer ()
Definition at line 81 of file nnet-randomizer-test.cc.
References MatrixRandomizer::AddData(), kaldi::AssertEqual(), CuMatrixBase< Real >::CopyToMat(), MatrixRandomizer::Done(), rnnlm::i, MatrixRandomizer::Init(), kaldi::InitRand(), MatrixRandomizer::IsFull(), KALDI_ASSERT, KALDI_LOG, NnetDataRandomizerOptions::minibatch_size, MatrixRandomizer::Next(), CuMatrixBase< Real >::NumCols(), MatrixRandomizer::NumFrames(), CuMatrixBase< Real >::NumRows(), MatrixRandomizer::Randomize(), NnetDataRandomizerOptions::randomizer_size, MatrixBase< Real >::RowRange(), and MatrixRandomizer::Value().
Referenced by main().
{
   Matrix<BaseFloat> m(1111, 10);
   InitRand(&m);
   CuMatrix<BaseFloat> m2(m);
   // config
   NnetDataRandomizerOptions c;
   c.randomizer_size = 1000;
   c.minibatch_size = 100;
   // randomizer
   MatrixRandomizer r;
   r.Init(c);
   r.AddData(m2);
   KALDI_ASSERT(r.IsFull());
   // create vector with consecutive indices
   std::vector<int32> mask(1111);
   for (int32 i = 0; i < 1111; i++) {
     mask[i] = i;
   }
   r.Randomize(mask);  // no shuffling
   // make sure we get same data we put to randomizer
   int32 i=0;
   for ( ; !r.Done(); r.Next(), i++) {
     KALDI_LOG << i;
     const CuMatrixBase<BaseFloat> &m3 = r.Value();
     Matrix<BaseFloat> m4(m3.NumRows(), m3.NumCols());
     m3.CopyToMat(&m4);
     AssertEqual(m4, m.RowRange(i * c.minibatch_size, c.minibatch_size));
   }
   KALDI_ASSERT(i == 11);  // 11 minibatches
   KALDI_LOG << "Filling for 2nd time";
   // try to fill buffer one more time, and empty it
   KALDI_ASSERT(!r.IsFull());
   r.AddData(m2);
   KALDI_ASSERT(r.IsFull());
   KALDI_ASSERT(r.NumFrames() == 11 + 1111);
   {  // check last 11 rows were copied to the front in the buffer
     const CuMatrixBase<BaseFloat> &m3 = r.Value();
     Matrix<BaseFloat> m4(m3.NumRows(), m3.NumCols());
     m3.CopyToMat(&m4);
     AssertEqual(m4.RowRange(0, 11), m.RowRange(1100, 11));
   }
   KALDI_ASSERT(!r.Done());
   for ( ; !r.Done(); r.Next(), i++) {
     KALDI_LOG << i;
     const CuMatrixBase<BaseFloat>& m3 = r.Value();
     static_cast<const void>(m3);  // variable no longer unused,
   }
   KALDI_ASSERT(i == 22);  // 22 minibatches
 }
UnitTestRandomizerMask()
void UnitTestRandomizerMask ()
Definition at line 71 of file nnet-randomizer-test.cc.
References RandomizerMask::Generate(), RandomizerMask::Init(), and KALDI_ASSERT.
Referenced by main().
{
   NnetDataRandomizerOptions c;
   RandomizerMask r;
   r.Init(c);
   const std::vector<int32>& m = r.Generate(5);
   KALDI_ASSERT(m.size() == 5);
   int32 sum_of_elems = std::accumulate(m.begin(), m.end(),0);
   KALDI_ASSERT(sum_of_elems == 4 + 3 + 2 + 1 + 0);
 }
UnitTestStdVectorRandomizer()
void UnitTestStdVectorRandomizer ()
Definition at line 178 of file nnet-randomizer-test.cc.
References StdVectorRandomizer< T >::AddData(), kaldi::AssertEqual(), StdVectorRandomizer< T >::Done(), rnnlm::i, StdVectorRandomizer< T >::Init(), StdVectorRandomizer< T >::IsFull(), KALDI_ASSERT, KALDI_LOG, StdVectorRandomizer< T >::Next(), StdVectorRandomizer< T >::NumFrames(), StdVectorRandomizer< T >::Randomize(), NnetDataRandomizerOptions::randomizer_size, and StdVectorRandomizer< T >::Value().
Referenced by main().
{
   // prepare vector with some data,
   std::vector<int32> v(1111);
   for (int32 i = 0; i < v.size(); i++) {
     v.at(i) = i;
   }
   std::random_shuffle(v.begin(), v.end());
   // config
   NnetDataRandomizerOptions c;
   c.randomizer_size = 1000;
   c.minibatch_size = 100;
   // randomizer
   Int32VectorRandomizer r;
   r.Init(c);
   r.AddData(v);
   KALDI_ASSERT(r.IsFull());
   // create vector with consecutive indices
   std::vector<int32> mask(1111);
   for (int32 i = 0; i < 1111; i++) {
     mask[i]=i;
   }
   r.Randomize(mask);  // no shuffling
   // make sure we get same data we put to randomizer
   int32 i = 0;
   for ( ; !r.Done(); r.Next(), i++) {
     KALDI_LOG << i;
     std::vector<int32> v2 = r.Value();
     AssertEqual(v2.begin(),
                 v2.end(),
                 v.begin() + (i * c.minibatch_size),
                 v.begin() + ((i+1) * c.minibatch_size));
   }
   KALDI_ASSERT(i == 11);  // 11 minibatches
   KALDI_LOG << "Filling for 2nd time";
   // try to fill buffer one more time, and empty it
   KALDI_ASSERT(!r.IsFull());
   r.AddData(v);
   KALDI_ASSERT(r.IsFull());
   KALDI_ASSERT(r.NumFrames() == 11 + 1111);
   {  // check last 11 rows were copied to the front in the buffer
     std::vector<int32> v2 = r.Value();
     AssertEqual(v2.begin(), v2.begin()+11, v.begin()+1100, v.begin()+1100+11);
   }
   KALDI_ASSERT(!r.Done());
   for ( ; !r.Done(); r.Next(), i++) {
     KALDI_LOG << i;
     std::vector<int32> v2 = r.Value();
   }
   KALDI_ASSERT(i == 22);  // 22 minibatches
 }
UnitTestVectorRandomizer()
void UnitTestVectorRandomizer ()
Definition at line 132 of file nnet-randomizer-test.cc.
References VectorRandomizer::AddData(), kaldi::AssertEqual(), VectorRandomizer::Done(), rnnlm::i, VectorRandomizer::Init(), kaldi::InitRand(), VectorRandomizer::IsFull(), KALDI_ASSERT, KALDI_LOG, NnetDataRandomizerOptions::minibatch_size, VectorRandomizer::Next(), VectorRandomizer::NumFrames(), VectorRandomizer::Randomize(), NnetDataRandomizerOptions::randomizer_size, VectorBase< Real >::Range(), and VectorRandomizer::Value().
Referenced by main().
{
   Vector<BaseFloat> v(1111);
   InitRand(&v);
   // config
   NnetDataRandomizerOptions c;
   c.randomizer_size = 1000;
   c.minibatch_size = 100;
   // randomizer
   VectorRandomizer r;
   r.Init(c);
   r.AddData(v);
   KALDI_ASSERT(r.IsFull());
   // create vector with consecutive indices
   std::vector<int32> mask(1111);
   for (int32 i = 0; i < 1111; i++) {
     mask[i] = i;
   }
   r.Randomize(mask);  // no shuffling
   // make sure we get same data we put to randomizer
   int32 i = 0;
   for ( ; !r.Done(); r.Next(), i++) {
     KALDI_LOG << i;
     const VectorBase<BaseFloat> &v2 = r.Value();
     AssertEqual(v2, v.Range(i * c.minibatch_size, c.minibatch_size));
   }
   KALDI_ASSERT(i == 11);  // 11 minibatches
   KALDI_LOG << "Filling for 2nd time";
   // try to fill buffer one more time, and empty it
   KALDI_ASSERT(!r.IsFull());
   r.AddData(v);
   KALDI_ASSERT(r.IsFull());
   KALDI_ASSERT(r.NumFrames() == 11 + 1111);
   {  // check last 11 rows were copied to the front in the buffer
     const VectorBase<BaseFloat> &v2 = r.Value();
     AssertEqual(v2.Range(0, 11), v.Range(1100, 11));
   }
   KALDI_ASSERT(!r.Done());
   for ( ; !r.Done(); r.Next(), i++) {
     KALDI_LOG << i;
     const VectorBase<BaseFloat>& v2 = r.Value();
     static_cast<const void>(v2);  // variable no longer unused,
   }
   KALDI_ASSERT(i == 22);  // 22 minibatches
 }