Kaldi: nnet3bin/nnet3-am-adjust-priors.cc File Reference
nnet3-am-adjust-priors.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "nnet3/am-nnet-simple.h"
#include "hmm/transition-model.h"
#include "tree/context-dep.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
BaseFloat KlDivergence (const Vector< BaseFloat > &p, const Vector< BaseFloat > &q)
void PrintPriorDiagnostics (const Vector< BaseFloat > &old_priors, const Vector< BaseFloat > &new_priors)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 70 of file nnet3-am-adjust-priors.cc.
References ParseOptions::GetArg(), KALDI_ASSERT, KALDI_LOG, ParseOptions::NumArgs(), kaldi::nnet3::PrintPriorDiagnostics(), ParseOptions::PrintUsage(), AmNnetSimple::Priors(), AmNnetSimple::Read(), ParseOptions::Read(), TransitionModel::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), VectorBase< Real >::Scale(), AmNnetSimple::SetPriors(), Output::Stream(), Input::Stream(), VectorBase< Real >::Sum(), AmNnetSimple::Write(), and TransitionModel::Write().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     const char *usage =
         "Set the priors of the nnet3 neural net to the computed posterios from the net,\n"
         "on typical data (e.g. training data). This is correct under more general\n"
         "circumstances than using the priors of the class labels in the training data\n"
         "\n"
         "Typical usage of this program will involve computation of an average pdf-level\n"
         "posterior with nnet3-compute or nnet3-compute-from-egs, piped into matrix-sum-rows\n"
         "and then vector-sum, to compute the average posterior\n"
         "\n"
         "Usage: nnet3-am-adjust-priors [options] <nnet-in> <summed-posterior-vector-in> <nnet-out>\n"
         "e.g.:\n"
         " nnet3-am-adjust-priors final.mdl counts.vec final.mdl\n";
     bool binary_write = true;
     BaseFloat prior_floor = 1.0e-15; // Have a very low prior floor, since this method
                                      // isn't likely to have a problem with very improbable
                                      // classes.
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("prior-floor", &prior_floor, "When setting priors, floor for "
                 "priors (only used to avoid generating NaNs upon inversion)");
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string nnet_rxfilename = po.GetArg(1),
         posterior_vec_rxfilename = po.GetArg(2),
         nnet_wxfilename = po.GetArg(3);
     TransitionModel trans_model;
     AmNnetSimple am_nnet;
     {
       bool binary_read;
       Input ki(nnet_rxfilename, &binary_read);
       trans_model.Read(ki.Stream(), binary_read);
       am_nnet.Read(ki.Stream(), binary_read);
     }
     Vector<BaseFloat> posterior_vec;
     ReadKaldiObject(posterior_vec_rxfilename, &posterior_vec);
     KALDI_ASSERT(posterior_vec.Sum() > 0.0);
     posterior_vec.Scale(1.0 / posterior_vec.Sum()); // Renormalize
     Vector<BaseFloat> old_priors(am_nnet.Priors());
     PrintPriorDiagnostics(old_priors, posterior_vec);
     am_nnet.SetPriors(posterior_vec);
     {
       Output ko(nnet_wxfilename, binary_write);
       trans_model.Write(ko.Stream(), binary_write);
       am_nnet.Write(ko.Stream(), binary_write);
     }
     KALDI_LOG << "Modified priors of neural network model and wrote it to "
               << nnet_wxfilename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }