Kaldi: nnet3bin/nnet3-xvector-get-egs.cc File Reference
nnet3-xvector-get-egs.cc File Reference
#include <sstream>
#include "util/common-utils.h"
#include "nnet3/nnet-example.h"
Classes
struct ChunkInfo
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
static void ProcessRangeFile (const std::string &range_rxfilename, unordered_map< std::string, std::vector< ChunkInfo *> > *utt_to_chunks)
static void WriteExamples (const MatrixBase< BaseFloat > &feats, const std::vector< ChunkInfo *> &chunks, const std::string &utt, bool compress, int32 num_pdfs, int32 *num_egs_written, std::vector< NnetExampleWriter *> *example_writers)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 133 of file nnet3-xvector-get-egs.cc.
References kaldi::DeletePointers(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), rnnlm::i, KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), kaldi::nnet3::ProcessRangeFile(), ParseOptions::Read(), ParseOptions::Register(), SequentialTableReader< Holder >::Value(), and kaldi::nnet3::WriteExamples().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     const char *usage =
         "Get examples for training an nnet3 neural network for the xvector\n"
         "system.  Each output example contains a chunk of features from some\n"
         "utterance along with a speaker label.  The location and length of\n"
         "the feature chunks are specified in the 'ranges' file.  Each line\n"
         "is interpreted as follows:\n"
         "  <source-utterance> <relative-output-archive-index> "
         "<absolute-archive-index> <start-frame-index> <num-frames> "
         "<speaker-label>\n"
         "where <relative-output-archive-index> is interpreted as a zero-based\n"
         "index into the wspecifiers provided on the command line (<egs-0-out>\n"
         "and so on), and <absolute-archive-index> is ignored by this program.\n"
         "For example:\n"
         "  utt1  3  13  65  300  3\n"
         "  utt1  0  10  50  400  3\n"
         "  utt2  ...\n"
         "\n"
         "Usage:  nnet3-xvector-get-egs [options] <ranges-filename> "
         "<features-rspecifier> <egs-0-out> <egs-1-out> ... <egs-N-1-out>\n"
         "\n"
         "For example:\n"
         "nnet3-xvector-get-egs ranges.1 \"$feats\" ark:egs_temp.1.ark"
         "  ark:egs_temp.2.ark ark:egs_temp.3.ark\n";
     bool compress = true;
     int32 num_pdfs = -1;
     ParseOptions po(usage);
     po.Register("compress", &compress, "If true, write egs in "
                 "compressed format.");
     po.Register("num-pdfs", &num_pdfs, "Number of speakers in the training "
                 "list.");
     po.Read(argc, argv);
     if (po.NumArgs() < 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string  range_rspecifier = po.GetArg(1),
         feature_rspecifier = po.GetArg(2);
     std::vector<NnetExampleWriter *> example_writers;
     for (int32 i = 3; i <= po.NumArgs(); i++)
       example_writers.push_back(new NnetExampleWriter(po.GetArg(i)));
     unordered_map<std::string, std::vector<ChunkInfo *> > utt_to_chunks;
     ProcessRangeFile(range_rspecifier, &utt_to_chunks);
     SequentialBaseFloatMatrixReader feat_reader(feature_rspecifier);
     int32 num_done = 0,
           num_err = 0,
           num_egs_written = 0;
     for (; !feat_reader.Done(); feat_reader.Next()) {
       std::string key = feat_reader.Key();
       const Matrix<BaseFloat> &feats = feat_reader.Value();
       unordered_map<std::string, std::vector<ChunkInfo*> >::iterator
         got = utt_to_chunks.find(key);
       if (got == utt_to_chunks.end()) {
         KALDI_WARN << "Could not create examples from utterance "
                    << key << " because it has no entry in the ranges "
                   <<  "input file.";
         num_err++;
       } else {
         std::vector<ChunkInfo *> chunks = got->second;
         WriteExamples(feats, chunks, key, compress, num_pdfs,
                       &num_egs_written, &example_writers);
         num_done++;
       }
     }
     // Free memory
     for (unordered_map<std::string, std::vector<ChunkInfo*> >::iterator
         map_it = utt_to_chunks.begin();
         map_it != utt_to_chunks.end(); ++map_it) {
       DeletePointers(&map_it->second);
     }
     DeletePointers(&example_writers);
     KALDI_LOG << "Finished generating examples, "
               << "successfully processed " << num_done
               << " feature files, wrote " << num_egs_written << " examples; "
               << num_err << " files had errors.";
     return (num_egs_written == 0 || num_err > num_done ? 1 : 0);
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }