Kaldi: nnet/nnet-component-test.cc File Reference
nnet-component-test.cc File Reference
#include <sstream>
#include <fstream>
#include <algorithm>
#include "nnet/nnet-component.h"
#include "nnet/nnet-nnet.h"
#include "nnet/nnet-convolutional-component.h"
#include "nnet/nnet-convolutional-2d-component.h"
#include "nnet/nnet-max-pooling-component.h"
#include "nnet/nnet-max-pooling-2d-component.h"
#include "nnet/nnet-average-pooling-2d-component.h"
#include "util/common-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet1
Functions
template<typename Real >
void ReadCuMatrixFromString (const std::string &s, CuMatrix< Real > *m)
Component * ReadComponentFromString (const std::string &s)
void UnitTestLengthNorm ()
void UnitTestSimpleSentenceAveragingComponent ()
void UnitTestConvolutionalComponentUnity ()
void UnitTestConvolutionalComponent3x3 ()
void UnitTestMaxPoolingComponent ()
void UnitTestMaxPooling2DComponent ()
void UnitTestAveragePooling2DComponent ()
void UnitTestConvolutional2DComponent ()
void UnitTestDropoutComponent ()
int main ()
Function Documentation
main()
int main ()
Definition at line 418 of file nnet-component-test.cc.
References KALDI_LOG, kaldi::nnet1::UnitTestAveragePooling2DComponent(), kaldi::nnet1::UnitTestConvolutional2DComponent(), kaldi::nnet1::UnitTestConvolutionalComponent3x3(), kaldi::nnet1::UnitTestConvolutionalComponentUnity(), kaldi::nnet1::UnitTestDropoutComponent(), kaldi::nnet1::UnitTestLengthNorm(), kaldi::nnet1::UnitTestMaxPooling2DComponent(), kaldi::nnet1::UnitTestMaxPoolingComponent(), and kaldi::nnet1::UnitTestSimpleSentenceAveragingComponent().
            {
   using namespace kaldi;
   using namespace kaldi::nnet1;
   for (kaldi::int32 loop = 0; loop < 2; loop++) {
 #if HAVE_CUDA == 1
     if (loop == 0)
       // use no GPU,
       CuDevice::Instantiate().SelectGpuId("no");
     else
       // use GPU when available,
       CuDevice::Instantiate().SelectGpuId("optional");
 #endif
     // unit-tests :
     UnitTestLengthNorm();
     UnitTestSimpleSentenceAveragingComponent();
     UnitTestConvolutionalComponentUnity();
     UnitTestConvolutionalComponent3x3();
     UnitTestMaxPoolingComponent();
     UnitTestConvolutional2DComponent();
     UnitTestMaxPooling2DComponent();
     UnitTestAveragePooling2DComponent();
     UnitTestDropoutComponent();
     // end of unit-tests,
     if (loop == 0)
         KALDI_LOG << "Tests without GPU use succeeded.";
       else
         KALDI_LOG << "Tests with GPU use (if available) succeeded.";
   }
 #if HAVE_CUDA == 1
   CuDevice::Instantiate().PrintProfile();
 #endif
   return 0;
 }