Kaldi: nnet2bin/nnet-copy-egs-discriminative.cc File Reference
nnet-copy-egs-discriminative.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet2/nnet-example-functions.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet2
Functions
int32 GetCount (double expected_count)
void AverageConstPart (int32 const_feat_dim, DiscriminativeNnetExample *eg)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 65 of file nnet-copy-egs-discriminative.cc.
References kaldi::nnet2::AverageConstPart(), count, SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), kaldi::nnet2::GetCount(), rnnlm::i, KALDI_LOG, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), kaldi::Rand(), ParseOptions::Read(), ParseOptions::Register(), and SequentialTableReader< Holder >::Value().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet2;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Copy examples for discriminative neural\n"
         "network training.  Supports multiple wspecifiers, in\n"
         "which case it will write the examples round-robin to the outputs.\n"
         "\n"
         "Usage:  nnet-copy-egs-discriminative [options] <egs-rspecifier> <egs-wspecifier1> [<egs-wspecifier2> ...]\n"
         "\n"
         "e.g.\n"
         "nnet-copy-egs-discriminative ark:train.degs ark,t:text.degs\n"
         "or:\n"
         "nnet-copy-egs-discriminative ark:train.degs ark:1.degs ark:2.degs\n";
     bool random = false;
     int32 srand_seed = 0;
     BaseFloat keep_proportion = 1.0;
     int32 const_feat_dim = 0;
     ParseOptions po(usage);
     po.Register("random", &random, "If true, will write frames to output "
                 "archives randomly, not round-robin.");
     po.Register("keep-proportion", &keep_proportion, "If <1.0, this program will "
                 "randomly keep this proportion of the input samples.  If >1.0, it will "
                 "in expectation copy a sample this many times.  It will copy it a number "
                 "of times equal to floor(keep-proportion) or ceil(keep-proportion).");
     po.Register("srand", &srand_seed, "Seed for random number generator "
                 "(only relevant if --random=true or --keep-proportion != 1.0)");
     po.Register("const-feat-dim", &const_feat_dim,
                 "Dimension of part of features (last dims) which varies little "
                 "or not at all with time, and which should be stored as a single "
                 "vector for each example rather than in the feature matrix."
                 "Useful in systems that use iVectors.  Helpful to save space.");
     po.Read(argc, argv);
     srand(srand_seed);
     if (po.NumArgs() < 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string examples_rspecifier = po.GetArg(1);
     SequentialDiscriminativeNnetExampleReader example_reader(
         examples_rspecifier);
     int32 num_outputs = po.NumArgs() - 1;
     std::vector<DiscriminativeNnetExampleWriter*> example_writers(num_outputs);
     for (int32 i = 0; i < num_outputs; i++)
       example_writers[i] = new DiscriminativeNnetExampleWriter(
           po.GetArg(i+2));
     int64 num_read = 0, num_written = 0, num_frames_written = 0;
     for (; !example_reader.Done(); example_reader.Next(), num_read++) {
       int32 count = GetCount(keep_proportion);
       for (int32 c = 0; c < count; c++) {
         int32 index = (random ? Rand() : num_written) % num_outputs;
         std::ostringstream ostr;
         ostr << num_written;
         if (const_feat_dim == 0) {
           example_writers[index]->Write(ostr.str(),
                                         example_reader.Value());
         } else {
           DiscriminativeNnetExample eg = example_reader.Value();
           AverageConstPart(const_feat_dim, &eg);
           example_writers[index]->Write(ostr.str(), eg);
         }
         num_written++;
         num_frames_written +=
             static_cast<int64>(example_reader.Value().num_ali.size());
       }
     }
     for (int32 i = 0; i < num_outputs; i++)
       delete example_writers[i];
     KALDI_LOG << "Read " << num_read << " discriminative neural-network training"
               << " examples, wrote " << num_written << ", consisting of "
               << num_frames_written << " frames.";
     return (num_written == 0 ? 1 : 0);
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }