Kaldi: nnet3bin/nnet3-average.cc File Reference
nnet3-average.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet3/nnet-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void GetWeights (const std::string &weights_str, int32 num_inputs, std::vector< BaseFloat > *weights)
void ReadModels (std::vector< std::pair< std::string, BaseFloat > > models_and_weights, nnet3::Nnet *output_nnet, int32 *success)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 79 of file nnet3-average.cc.
References kaldi::nnet3::AddNnet(), ParseOptions::GetArg(), kaldi::GetWeights(), rnnlm::j, KALDI_ERR, KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadModels(), ParseOptions::Register(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "This program averages the parameters over a number of 'raw' nnet3 neural nets.\n"
         "\n"
         "Usage:  nnet3-average [options] <model1> <model2> ... <modelN> <model-out>\n"
         "\n"
         "e.g.:\n"
         " nnet3-average 1.1.nnet 1.2.nnet 1.3.nnet 2.nnet\n";
     bool binary_write = true;
     int32 num_threads = -1;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     std::string weights_str;
     po.Register("weights", &weights_str, "Colon-separated list of weights, one "
                 "for each input model.  These will be normalized to sum to one.");
     po.Register("num-threads", &num_threads, "Number of threads to read the "
                 "models (will be set automatically if not set.");
     po.Read(argc, argv);
     if (po.NumArgs() < 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string
         first_nnet_rxfilename = po.GetArg(1),
         nnet_wxfilename = po.GetArg(po.NumArgs());
     int32 num_inputs = po.NumArgs() - 1;
     if (num_threads <= 0) {
       // Default logic for selecting the number of threads.
       if (num_inputs > 10) num_threads = 3;
       else if (num_inputs > 5) num_threads = 2;
       else num_threads = 1;
     }
     if (num_threads > 1 && num_threads * 2 > num_inputs) {
       num_threads = num_inputs / 2;
     }
     std::vector<BaseFloat> model_weights;
     GetWeights(weights_str, num_inputs, &model_weights);
     std::vector<Nnet> nnets(num_threads);
     std::vector<int32> return_statuses(num_threads);
     std::vector<std::thread*> threads(num_threads);
     for (int32 thread_id = 0; thread_id < num_threads; thread_id++) {
       std::vector<std::pair<std::string, BaseFloat> > this_models_and_weights;
       for (int32 j = 1 + thread_id; j < po.NumArgs(); j += num_threads) {
         this_models_and_weights.push_back(std::pair<std::string, BaseFloat>(
             po.GetArg(j), model_weights[j - 1]));
       }
       threads[thread_id] = new std::thread(ReadModels, this_models_and_weights,
                                            &(nnets[thread_id]),
                                            &(return_statuses[thread_id]));
     }
     bool success = true;
     for (int32 thread_id = 0; thread_id < num_threads; thread_id++) {
       threads[thread_id]->join();
       delete threads[thread_id];
       if (!return_statuses[thread_id])
         success = false;
       if (success && thread_id > 0)
         AddNnet(nnets[thread_id], 1.0, &(nnets[0]));
     }
     if (!success) {
       KALDI_ERR << "Error detected in a model-reading thread.";
     }
     WriteKaldiObject(nnets[0], nnet_wxfilename, binary_write);
     KALDI_LOG << "Averaged parameters of " << num_inputs
               << " neural nets, and wrote to " << nnet_wxfilename;
     return 0; // it will throw an exception if there are any problems.
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }