Kaldi: nnet3/nnet-derivative-test.cc File Reference
nnet-derivative-test.cc File Reference
#include "nnet3/nnet-nnet.h"
#include "nnet3/nnet-compile.h"
#include "nnet3/nnet-analyze.h"
#include "nnet3/nnet-test-utils.h"
#include "nnet3/nnet-optimize.h"
#include "nnet3/nnet-compute.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
void ComputeMinAndMaxTimes (const std::vector< Index > &indexes, int32 *min_t, int32 *max_t)
void SetDerivTimesOptions (const ComputationRequest &request, NnetOptimizeOptions *opt_config)
void UnitTestNnetModelDerivatives ()
void UnitTestNnetInputDerivatives ()
int main ()
Function Documentation
main()
int main ()
Definition at line 421 of file nnet-derivative-test.cc.
References KALDI_LOG, kaldi::SetVerboseLevel(), kaldi::nnet3::UnitTestNnetInputDerivatives(), and kaldi::nnet3::UnitTestNnetModelDerivatives().
            {
   using namespace kaldi;
   using namespace kaldi::nnet3;
   SetVerboseLevel(3);
 #if HAVE_CUDA == 1
   kaldi::int32 loop = 0;
   for (loop = 0; loop < 2; loop++) {
     CuDevice::Instantiate().SetDebugStrideMode(true);
     if (loop == 0)
       CuDevice::Instantiate().SelectGpuId("no");
     else
       CuDevice::Instantiate().SelectGpuId("yes");
 #endif
     UnitTestNnetModelDerivatives();
     UnitTestNnetInputDerivatives();
 #if HAVE_CUDA == 1
   } // No for loop if 'HAVE_CUDA != 1',
   CuDevice::Instantiate().PrintProfile();
 #endif
   KALDI_LOG << "Nnet derivative tests succeeded.";
   return 0;
 }