Kaldi: nnet3bin/nnet3-copy-egs.cc File Reference
nnet3-copy-egs.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet3/nnet-example.h"
#include "nnet3/nnet-example-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
void RenameOutputs (const std::string &new_name, NnetExample *eg)
void ScaleSupervisionWeight (BaseFloat weight, NnetExample *eg)
int32 GetCount (double expected_count)
bool ContainsSingleExample (const NnetExample &eg, int32 *min_input_t, int32 *max_input_t, int32 *min_output_t, int32 *max_output_t)
Returns true if the "eg" contains just a single example, meaning that all the "n" values in the indexes are zero, and the example has NnetIo members named both "input" and "output".
void FilterExample (const NnetExample &eg, int32 min_input_t, int32 max_input_t, int32 min_output_t, int32 max_output_t, NnetExample *eg_out)
This function filters the indexes (and associated feature rows) in a NnetExample, removing any index/row in an NnetIo named "input" with t < min_input_t or t > max_input_t and any index/row in an NnetIo named "output" with t < min_output_t or t > max_output_t.
bool SelectFromExample (const NnetExample &eg, std::string frame_str, int32 left_context, int32 right_context, int32 frame_shift, NnetExample *eg_out)
This function is responsible for possibly selecting one frame from multiple supervised frames, and reducing the left and right context as specified.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 290 of file nnet3-copy-egs.cc.
References count, SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), kaldi::nnet3::GetCount(), RandomAccessTableReader< Holder >::HasKey(), rnnlm::i, KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), kaldi::Rand(), ParseOptions::Read(), ParseOptions::Register(), kaldi::nnet3::RenameOutputs(), kaldi::nnet3::ScaleSupervisionWeight(), kaldi::nnet3::SelectFromExample(), RandomAccessTableReader< Holder >::Value(), and SequentialTableReader< Holder >::Value().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Copy examples (single frames or fixed-size groups of frames) for neural\n"
         "network training, possibly changing the binary mode.  Supports multiple wspecifiers, in\n"
         "which case it will write the examples round-robin to the outputs.\n"
         "\n"
         "Usage:  nnet3-copy-egs [options] <egs-rspecifier> <egs-wspecifier1> [<egs-wspecifier2> ...]\n"
         "\n"
         "e.g.\n"
         "nnet3-copy-egs ark:train.egs ark,t:text.egs\n"
         "or:\n"
         "nnet3-copy-egs ark:train.egs ark:1.egs ark:2.egs\n"
         "See also: nnet3-subset-egs, nnet3-get-egs, nnet3-merge-egs, nnet3-shuffle-egs\n";
     bool random = false;
     int32 srand_seed = 0;
     int32 frame_shift = 0;
     BaseFloat keep_proportion = 1.0;
     // The following config variables, if set, can be used to extract a single
     // frame of labels from a multi-frame example, and/or to reduce the amount
     // of context.
     int32 left_context = -1, right_context = -1;
     // you can set frame to a number to select a single frame with a particular
     // offset, or to 'random' to select a random single frame.
     std::string frame_str,
       eg_weight_rspecifier, eg_output_name_rspecifier;
     ParseOptions po(usage);
     po.Register("random", &random, "If true, will write frames to output "
                 "archives randomly, not round-robin.");
     po.Register("frame-shift", &frame_shift, "Allows you to shift time values "
                 "in the supervision data (excluding iVector data).  Only really "
                 "useful in clockwork topologies (i.e. any topology for which "
                 "modulus != 1).  Shifting is done after any frame selection.");
     po.Register("keep-proportion", &keep_proportion, "If <1.0, this program will "
                 "randomly keep this proportion of the input samples.  If >1.0, it will "
                 "in expectation copy a sample this many times.  It will copy it a number "
                 "of times equal to floor(keep-proportion) or ceil(keep-proportion).");
     po.Register("srand", &srand_seed, "Seed for random number generator "
                 "(only relevant if --random=true or --keep-proportion != 1.0)");
     po.Register("frame", &frame_str, "This option can be used to select a single "
                 "frame from each multi-frame example.  Set to a number 0, 1, etc. "
                 "to select a frame with a given index, or 'random' to select a "
                 "random frame.");
     po.Register("left-context", &left_context, "Can be used to truncate the "
                 "feature left-context that we output.");
     po.Register("right-context", &right_context, "Can be used to truncate the "
                 "feature right-context that we output.");
     po.Register("weights", &eg_weight_rspecifier,
                 "Rspecifier indexed by the key of egs, providing a weight by "
                 "which we will scale the supervision matrix for that eg. "
                 "Used in multilingual training.");
     po.Register("outputs", &eg_output_name_rspecifier,
                 "Rspecifier indexed by the key of egs, providing a string-valued "
                 "output name, e.g. 'output-0'.  If provided, the NnetIo with "
                 "name 'output' will be renamed to the provided name. Used in "
                 "multilingual training.");
     po.Read(argc, argv);
     srand(srand_seed);
     if (po.NumArgs() < 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string examples_rspecifier = po.GetArg(1);
     SequentialNnetExampleReader example_reader(examples_rspecifier);
     // In the normal case, these would not be used. These are only applicable
     // for multi-task or multilingual training.
     RandomAccessTokenReader output_name_reader(eg_output_name_rspecifier);
     RandomAccessBaseFloatReader egs_weight_reader(eg_weight_rspecifier);
     int32 num_outputs = po.NumArgs() - 1;
     std::vector<NnetExampleWriter*> example_writers(num_outputs);
     for (int32 i = 0; i < num_outputs; i++)
       example_writers[i] = new NnetExampleWriter(po.GetArg(i+2));
     int64 num_read = 0, num_written = 0, num_err = 0;
     for (; !example_reader.Done(); example_reader.Next(), num_read++) {
       const std::string &key = example_reader.Key();
       NnetExample &eg = example_reader.Value();
       // count is normally 1; could be 0, or possibly >1.
       int32 count = GetCount(keep_proportion);
       if (!eg_weight_rspecifier.empty()) {
         BaseFloat weight = 1.0;
         if (!egs_weight_reader.HasKey(key)) {
           KALDI_WARN << "No weight for example key " << key;
           num_err++;
           continue;
         }
         weight = egs_weight_reader.Value(key);
         ScaleSupervisionWeight(weight, &eg);
       }
       std::string new_output_name;
       if (!eg_output_name_rspecifier.empty()) {
         if (!output_name_reader.HasKey(key)) {
           KALDI_WARN << "No new output-name for example key " << key;
           num_err++;
           continue;
         }
         new_output_name = output_name_reader.Value(key);
       }
       for (int32 c = 0; c < count; c++) {
         int32 index = (random ? Rand() : num_written) % num_outputs;
         if (frame_str == "" && left_context == -1 && right_context == -1 &&
             frame_shift == 0) {
           if (!new_output_name.empty() && c == 0)
             RenameOutputs(new_output_name, &eg);
           example_writers[index]->Write(key, eg);
           num_written++;
         } else { // the --frame option or context options were set.
           NnetExample eg_modified;
           if (SelectFromExample(eg, frame_str, left_context, right_context,
                                 frame_shift, &eg_modified)) {
             if (!new_output_name.empty())
               RenameOutputs(new_output_name, &eg_modified);
             // this branch of the if statement will almost always be taken (should only
             // not be taken for shorter-than-normal egs from the end of a file.
             example_writers[index]->Write(key, eg_modified);
             num_written++;
           }
         }
       }
     }
     for (int32 i = 0; i < num_outputs; i++)
       delete example_writers[i];
     KALDI_LOG << "Read " << num_read << " neural-network training examples, wrote "
               << num_written << ", "
               << num_err <<  " examples had errors.";
     return (num_written == 0 ? 1 : 0);
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }