Kaldi: nnet3bin/nnet3-get-egs-dense-targets.cc File Reference
nnet3-get-egs-dense-targets.cc File Reference
#include <sstream>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "hmm/posterior.h"
#include "nnet3/nnet-example.h"
#include "nnet3/nnet-example-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
static bool ProcessFile (const GeneralMatrix &feats, const MatrixBase< BaseFloat > *ivector_feats, int32 ivector_period, const MatrixBase< BaseFloat > &targets, const std::string &utt_id, bool compress, int32 num_targets, int32 length_tolerance, UtteranceSplitter *utt_splitter, NnetExampleWriter *example_writer)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 148 of file nnet3-get-egs-dense-targets.cc.
References ExampleGenerationConfig::ComputeDerived(), SequentialTableReader< Holder >::Done(), UtteranceSplitter::ExitStatus(), ParseOptions::GetArg(), RandomAccessTableReader< Holder >::HasKey(), KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumRows(), GeneralMatrix::NumRows(), ParseOptions::PrintUsage(), kaldi::nnet3::ProcessFile(), ParseOptions::Read(), ParseOptions::Register(), ExampleGenerationConfig::Register(), RandomAccessTableReader< Holder >::Value(), and SequentialTableReader< Holder >::Value().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Get frame-by-frame examples of data for nnet3 neural network training.\n"
         "This program is similar to nnet3-get-egs, but the targets here are "
         "dense matrices instead of posteriors (sparse matrices).\n"
         "This is useful when you want the targets to be continuous real-valued "
         "with the neural network possibly trained with a quadratic objective\n"
         "\n"
         "Usage:  nnet3-get-egs-dense-targets --num-targets=<n> [options] "
         "<features-rspecifier> <targets-rspecifier> <egs-out>\n"
         "\n"
         "An example [where $feats expands to the actual features]:\n"
         "nnet-get-egs-dense-targets --num-targets=26 --left-context=12 \\\n"
         "--right-context=9 --num-frames=8 \"$feats\" \\\n"
         "\"ark:copy-matrix ark:exp/snrs/snr.1.ark ark:- |\"\n"
         "   ark:- \n";
     bool compress = true;
     int32 num_targets = -1, length_tolerance = 100,
         targets_length_tolerance = 2,
         online_ivector_period = 1;
     ExampleGenerationConfig eg_config;  // controls num-frames,
                                         // left/right-context, etc.
     std::string online_ivector_rspecifier;
     ParseOptions po(usage);
     po.Register("compress", &compress, "If true, write egs with input features "
                 "in compressed format (recommended).  This is "
                 "only relevant if the features being read are un-compressed; "
                 "if already compressed, we keep we same compressed format when "
                 "dumping egs.");
     po.Register("num-targets", &num_targets, "Output dimension in egs, "
                 "only used to check targets have correct dim if supplied.");
     po.Register("ivectors", &online_ivector_rspecifier, "Alias for "
                 "--online-ivectors option, for back compatibility");
     po.Register("online-ivectors", &online_ivector_rspecifier, "Rspecifier of "
                 "ivector features, as a matrix.");
     po.Register("online-ivector-period", &online_ivector_period, "Number of "
                 "frames between iVectors in matrices supplied to the "
                 "--online-ivectors option");
     po.Register("length-tolerance", &length_tolerance, "Tolerance for "
                 "difference in num-frames between feat and ivector matrices");
     po.Register("targets-length-tolerance", &targets_length_tolerance,
                 "Tolerance for "
                 "difference in num-frames (after subsampling) between "
                 "feature and target matrices");
     eg_config.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     eg_config.ComputeDerived();
     UtteranceSplitter utt_splitter(eg_config);
     std::string feature_rspecifier = po.GetArg(1),
         matrix_rspecifier = po.GetArg(2),
         examples_wspecifier = po.GetArg(3);
     // SequentialGeneralMatrixReader can read either a Matrix or
     // CompressedMatrix (or SparseMatrix, but not as relevant here),
     // and it retains the type.  This way, we can generate parts of
     // the feature matrices without uncompressing and re-compressing.
     SequentialGeneralMatrixReader feat_reader(feature_rspecifier);
     RandomAccessBaseFloatMatrixReader matrix_reader(matrix_rspecifier);
     NnetExampleWriter example_writer(examples_wspecifier);
     RandomAccessBaseFloatMatrixReader online_ivector_reader(
         online_ivector_rspecifier);
     int32 num_err = 0;
     for (; !feat_reader.Done(); feat_reader.Next()) {
       std::string key = feat_reader.Key();
       const GeneralMatrix &feats = feat_reader.Value();
       if (!matrix_reader.HasKey(key)) {
         KALDI_WARN << "No target matrix for key " << key;
         num_err++;
       } else {
         const Matrix<BaseFloat> &target_matrix = matrix_reader.Value(key);
         const Matrix<BaseFloat> *online_ivector_feats = NULL;
         if (!online_ivector_rspecifier.empty()) {
           if (!online_ivector_reader.HasKey(key)) {
             KALDI_WARN << "No iVectors for utterance " << key;
             num_err++;
             continue;
           } else {
             // this address will be valid until we call HasKey() or Value()
             // again.
             online_ivector_feats = &(online_ivector_reader.Value(key));
           }
         }
         if (online_ivector_feats != NULL &&
             (abs(feats.NumRows() - (online_ivector_feats->NumRows() *
                                     online_ivector_period)) > length_tolerance
              || online_ivector_feats->NumRows() == 0)) {
           KALDI_WARN << "Length difference between feats " << feats.NumRows()
                      << " and iVectors " << online_ivector_feats->NumRows()
                      << "exceeds tolerance " << length_tolerance;
           num_err++;
           continue;
         }
         if (!ProcessFile(feats, online_ivector_feats, online_ivector_period,
                          target_matrix, key, compress, num_targets,
                          targets_length_tolerance,
                          &utt_splitter, &example_writer))
           num_err++;
       }
     }
     if (num_err > 0)
       KALDI_WARN << num_err << " utterances had errors and could "
           "not be processed.";
     // utt_splitter prints stats in its destructor.
     return utt_splitter.ExitStatus();
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }