Kaldi: nnet3/nnet-parse-test.cc File Reference
nnet-parse-test.cc File Reference
#include "nnet3/nnet-parse.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
void UnitTestConfigLineParse ()
void UnitTestReadConfig ()
void UnitTestDescriptorTokenize ()
void UnitTestSummarizeVector ()
void UnitTestNameMatchesPattern ()
int main ()
Function Documentation
main()
int main ()
Definition at line 280 of file nnet-parse-test.cc.
References KALDI_LOG, kaldi::nnet3::UnitTestConfigLineParse(), kaldi::nnet3::UnitTestDescriptorTokenize(), kaldi::nnet3::UnitTestNameMatchesPattern(), kaldi::nnet3::UnitTestReadConfig(), and kaldi::nnet3::UnitTestSummarizeVector().
            {
   using namespace kaldi;
   using namespace kaldi::nnet3;
   UnitTestConfigLineParse();
   UnitTestReadConfig();
   UnitTestDescriptorTokenize();
   UnitTestSummarizeVector();
   UnitTestNameMatchesPattern();
   KALDI_LOG << "Parse tests succeeded.";
   return 0;
 }