Kaldi: nnet3bin/nnet3-align-compiled.cc File Reference
nnet3-align-compiled.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "gmm/am-diag-gmm.h"
#include "hmm/transition-model.h"
#include "hmm/hmm-utils.h"
#include "fstext/fstext-lib.h"
#include "decoder/decoder-wrappers.h"
#include "decoder/training-graph-compiler.h"
#include "nnet3/nnet-am-decodable-simple.h"
#include "nnet3/nnet-utils.h"
#include "lat/kaldi-lattice.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 35 of file nnet3-align-compiled.cc.
References NnetSimpleComputationOptions::acoustic_scale, kaldi::AddTransitionProbs(), kaldi::AlignUtteranceWrapper(), kaldi::nnet3::CollapseModel(), SequentialTableReader< Holder >::Done(), SequentialTableReader< Holder >::FreeCurrent(), ParseOptions::GetArg(), AmNnetSimple::GetNnet(), ParseOptions::GetOptArg(), RandomAccessTableReader< Holder >::HasKey(), RandomAccessTableReaderMapped< Holder >::HasKey(), KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumRows(), NnetSimpleComputationOptions::optimize_config, ParseOptions::PrintUsage(), AmNnetSimple::Read(), ParseOptions::Read(), TransitionModel::Read(), AlignConfig::Register(), NnetSimpleComputationOptions::Register(), ParseOptions::Register(), kaldi::nnet3::SetBatchnormTestMode(), kaldi::nnet3::SetDropoutTestMode(), Input::Stream(), RandomAccessTableReader< Holder >::Value(), SequentialTableReader< Holder >::Value(), and RandomAccessTableReaderMapped< Holder >::Value().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     using fst::SymbolTable;
     using fst::VectorFst;
     using fst::StdArc;
     const char *usage =
         "Align features given nnet3 neural net model\n"
         "Usage:   nnet3-align-compiled [options] <nnet-in> <graphs-rspecifier> "
         "<features-rspecifier> <alignments-wspecifier>\n"
         "e.g.: \n"
         " nnet3-align-compiled 1.mdl ark:graphs.fsts scp:train.scp ark:1.ali\n"
         "or:\n"
         " compile-train-graphs tree 1.mdl lex.fst 'ark:sym2int.pl -f 2- words.txt text|' \\\n"
         "   ark:- | nnet3-align-compiled 1.mdl ark:- scp:train.scp t, ark:1.ali\n";
     ParseOptions po(usage);
     AlignConfig align_config;
     NnetSimpleComputationOptions decodable_opts;
     std::string use_gpu = "yes";
     BaseFloat transition_scale = 1.0;
     BaseFloat self_loop_scale = 1.0;
     std::string per_frame_acwt_wspecifier;
     std::string ivector_rspecifier,
         online_ivector_rspecifier,
         utt2spk_rspecifier;
     int32 online_ivector_period = 0;
     align_config.Register(&po);
     decodable_opts.Register(&po);
     po.Register("use-gpu", &use_gpu,
                 "yes|no|optional|wait, only has effect if compiled with CUDA");
     po.Register("transition-scale", &transition_scale,
                 "Transition-probability scale [relative to acoustics]");
     po.Register("self-loop-scale", &self_loop_scale,
                 "Scale of self-loop versus non-self-loop "
                 "log probs [relative to acoustics]");
     po.Register("write-per-frame-acoustic-loglikes", &per_frame_acwt_wspecifier,
                 "Wspecifier for table of vectors containing the acoustic log-likelihoods "
                 "per frame for each utterance. E.g. ark:foo/per_frame_logprobs.1.ark");
     po.Register("ivectors", &ivector_rspecifier, "Rspecifier for "
                 "iVectors as vectors (i.e. not estimated online); per utterance "
                 "by default, or per speaker if you provide the --utt2spk option.");
     po.Register("online-ivectors", &online_ivector_rspecifier, "Rspecifier for "
                 "iVectors estimated online, as matrices.  If you supply this,"
                 " you must set the --online-ivector-period option.");
     po.Register("online-ivector-period", &online_ivector_period, "Number of frames "
                 "between iVectors in matrices supplied to the --online-ivectors "
                 "option");
     po.Read(argc, argv);
     if (po.NumArgs() < 4 || po.NumArgs() > 5) {
       po.PrintUsage();
       exit(1);
     }
 #if HAVE_CUDA==1
     CuDevice::Instantiate().SelectGpuId(use_gpu);
 #endif
     std::string model_in_filename = po.GetArg(1),
         fst_rspecifier = po.GetArg(2),
         feature_rspecifier = po.GetArg(3),
         alignment_wspecifier = po.GetArg(4),
         scores_wspecifier = po.GetOptArg(5);
     int num_done = 0, num_err = 0, num_retry = 0;
     double tot_like = 0.0;
     kaldi::int64 frame_count = 0;
     {
       TransitionModel trans_model;
       AmNnetSimple am_nnet;
       {
         bool binary;
         Input ki(model_in_filename, &binary);
         trans_model.Read(ki.Stream(), binary);
         am_nnet.Read(ki.Stream(), binary);
       }
       SetBatchnormTestMode(true, &(am_nnet.GetNnet()));
       SetDropoutTestMode(true, &(am_nnet.GetNnet()));
       CollapseModel(CollapseModelConfig(), &(am_nnet.GetNnet()));
       // this compiler object allows caching of computations across
       // different utterances.
       CachingOptimizingCompiler compiler(am_nnet.GetNnet(),
                                          decodable_opts.optimize_config);
       RandomAccessBaseFloatMatrixReader online_ivector_reader(
           online_ivector_rspecifier);
       RandomAccessBaseFloatVectorReaderMapped ivector_reader(
           ivector_rspecifier, utt2spk_rspecifier);
       SequentialTableReader<fst::VectorFstHolder> fst_reader(fst_rspecifier);
       RandomAccessBaseFloatMatrixReader feature_reader(feature_rspecifier);
       Int32VectorWriter alignment_writer(alignment_wspecifier);
       BaseFloatWriter scores_writer(scores_wspecifier);
       BaseFloatVectorWriter per_frame_acwt_writer(per_frame_acwt_wspecifier);
       for (; !fst_reader.Done(); fst_reader.Next()) {
         std::string utt = fst_reader.Key();
         if (!feature_reader.HasKey(utt)) {
           KALDI_WARN << "No features for utterance " << utt;
           num_err++;
           continue;
         }
         const Matrix<BaseFloat> &features = feature_reader.Value(utt);
         VectorFst<StdArc> decode_fst(fst_reader.Value());
         fst_reader.FreeCurrent();  // this stops copy-on-write of the fst
         // by deleting the fst inside the reader, since we're about to mutate
         // the fst by adding transition probs.
         if (features.NumRows() == 0) {
           KALDI_WARN << "Zero-length utterance: " << utt;
           num_err++;
           continue;
         }
         const Matrix<BaseFloat> *online_ivectors = NULL;
         const Vector<BaseFloat> *ivector = NULL;
         if (!ivector_rspecifier.empty()) {
           if (!ivector_reader.HasKey(utt)) {
             KALDI_WARN << "No iVector available for utterance " << utt;
             num_err++;
             continue;
           } else {
             ivector = &ivector_reader.Value(utt);
           }
         }
         if (!online_ivector_rspecifier.empty()) {
           if (!online_ivector_reader.HasKey(utt)) {
             KALDI_WARN << "No online iVector available for utterance " << utt;
             num_err++;
             continue;
           } else {
             online_ivectors = &online_ivector_reader.Value(utt);
           }
         }
         {  // Add transition-probs to the FST.
           std::vector<int32> disambig_syms;  // empty.
           AddTransitionProbs(trans_model, disambig_syms,
                              transition_scale, self_loop_scale,
                              &decode_fst);
         }
         DecodableAmNnetSimple nnet_decodable(
             decodable_opts, trans_model, am_nnet,
             features, ivector, online_ivectors,
             online_ivector_period, &compiler);
         AlignUtteranceWrapper(align_config, utt,
                               decodable_opts.acoustic_scale,
                               &decode_fst, &nnet_decodable,
                               &alignment_writer, &scores_writer,
                               &num_done, &num_err, &num_retry,
                               &tot_like, &frame_count, &per_frame_acwt_writer);
       }
       KALDI_LOG << "Overall log-likelihood per frame is "
                 << (tot_like/frame_count)
                 << " over " << frame_count<< " frames.";
       KALDI_LOG << "Retried " << num_retry << " out of "
                 << (num_done + num_err) << " utterances.";
       KALDI_LOG << "Done " << num_done << ", errors on " << num_err;
     }
 #if HAVE_CUDA==1
     CuDevice::Instantiate().PrintProfile();
 #endif
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }