Kaldi: nnet3/nnet-descriptor-test.cc File Reference
nnet-descriptor-test.cc File Reference
#include "nnet3/nnet-descriptor.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
ForwardingDescriptor * GenRandForwardingDescriptor (int32 num_nodes)
SumDescriptor * GenRandSumDescriptor (int32 num_nodes)
void GenRandDescriptor (int32 num_nodes, Descriptor *desc)
void UnitTestDescriptorIo ()
void UnitTestGeneralDescriptor ()
std::string NormalizeTextDescriptor (const std::vector< std::string > &node_names, const std::string &desc_str)
void UnitTestGeneralDescriptorSpecial ()
int main ()
Function Documentation
main()
int main ()
Definition at line 229 of file nnet-descriptor-test.cc.
References KALDI_LOG, kaldi::nnet3::UnitTestDescriptorIo(), kaldi::nnet3::UnitTestGeneralDescriptor(), and kaldi::nnet3::UnitTestGeneralDescriptorSpecial().
            {
   using namespace kaldi;
   using namespace kaldi::nnet3;
   UnitTestGeneralDescriptorSpecial();
   UnitTestGeneralDescriptor();
   UnitTestDescriptorIo();
   KALDI_LOG << "Nnet descriptor tests succeeded.";
   return 0;
 }