Kaldi: nnet3bin/nnet3-compute-prob.cc File Reference
nnet3-compute-prob.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "nnet3/nnet-diagnostics.h"
#include "nnet3/nnet-utils.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 26 of file nnet3-compute-prob.cc.
References kaldi::nnet3::CollapseModel(), NnetComputeProb::Compute(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), NnetComputeProb::PrintTotalStats(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), NnetComputeProbOptions::Register(), kaldi::nnet3::SetBatchnormTestMode(), kaldi::nnet3::SetDropoutTestMode(), and SequentialTableReader< Holder >::Value().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Computes and prints in logging messages the average log-prob per frame of\n"
         "the given data with an nnet3 neural net.  The input of this is the output of\n"
         "e.g. nnet3-get-egs | nnet3-merge-egs.\n"
         "\n"
         "Usage:  nnet3-compute-prob [options] <raw-model-in> <training-examples-in>\n"
         "e.g.: nnet3-compute-prob 0.raw ark:valid.egs\n";
     bool batchnorm_test_mode = true, dropout_test_mode = true,
         collapse_model = true;
     // This program doesn't support using a GPU, because these probabilities are
     // used for diagnostics, and you can just compute them with a small enough
     // amount of data that a CPU can do it within reasonable time.
     NnetComputeProbOptions opts;
     ParseOptions po(usage);
     po.Register("batchnorm-test-mode", &batchnorm_test_mode,
                 "If true, set test-mode to true on any BatchNormComponents.");
     po.Register("dropout-test-mode", &dropout_test_mode,
                 "If true, set test-mode to true on any DropoutComponents and "
                 "DropoutMaskComponents.");
     po.Register("collapse-model", &collapse_model,
                 "If true, collapse model to the extent possible before "
                 "using it (for efficiency).");
     opts.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string raw_nnet_rxfilename = po.GetArg(1),
         examples_rspecifier = po.GetArg(2);
     Nnet nnet;
     ReadKaldiObject(raw_nnet_rxfilename, &nnet);
     if (batchnorm_test_mode)
       SetBatchnormTestMode(true, &nnet);
     if (dropout_test_mode)
       SetDropoutTestMode(true, &nnet);
     if (collapse_model)
       CollapseModel(CollapseModelConfig(), &nnet);
     NnetComputeProb prob_computer(opts, nnet);
     SequentialNnetExampleReader example_reader(examples_rspecifier);
     for (; !example_reader.Done(); example_reader.Next())
       prob_computer.Compute(example_reader.Value());
     bool ok = prob_computer.PrintTotalStats();
     return (ok ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }