Kaldi: nnet2bin/nnet-am-average.cc File Reference
nnet-am-average.cc File Reference
#include <algorithm>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet2/combine-nnet-a.h"
#include "nnet2/am-nnet.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void GetWeights (const std::string &weights_str, int32 num_inputs, std::vector< BaseFloat > *weights)
std::vector< bool > GetSkipLayers (const std::string &skip_layers_str, const int32 first_layer_idx, const int32 last_layer_idx)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 112 of file nnet-am-average.cc.
References UpdatableComponent::Add(), NonlinearComponent::Add(), ParseOptions::GetArg(), Nnet::GetComponent(), AmNnet::GetNnet(), kaldi::GetSkipLayers(), kaldi::GetWeights(), rnnlm::i, KALDI_ASSERT, KALDI_LOG, KALDI_VLOG, Nnet::LastUpdatableComponent(), ParseOptions::NumArgs(), Nnet::NumComponents(), ParseOptions::PrintUsage(), AmNnet::Read(), ParseOptions::Read(), TransitionModel::Read(), ParseOptions::Register(), UpdatableComponent::Scale(), NonlinearComponent::Scale(), Output::Stream(), Input::Stream(), AmNnet::Write(), and TransitionModel::Write().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet2;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "This program averages (or sums, if --sum=true) the parameters over a\n"
         "number of neural nets.  If you supply the option --skip-last-layer=true,\n"
         "the parameters of the last updatable layer are copied from <model1> instead\n"
         "of being averaged (useful in multi-language scenarios).\n"
         "The --weights option can be used to weight each model differently.\n"
         "\n"
         "Usage:  nnet-am-average [options] <model1> <model2> ... <modelN> <model-out>\n"
         "\n"
         "e.g.:\n"
         " nnet-am-average 1.1.nnet 1.2.nnet 1.3.nnet 2.nnet\n";
     bool binary_write = true;
     bool sum = false;
     ParseOptions po(usage);
     po.Register("sum", &sum, "If true, sums instead of averages.");
     po.Register("binary", &binary_write, "Write output in binary mode");
     string weights_str;
     bool skip_last_layer = false;
     string skip_layers_str;
     po.Register("weights", &weights_str, "Colon-separated list of weights, one "
                 "for each input model.  These will be normalized to sum to one.");
     po.Register("skip-last-layer", &skip_last_layer, "If true, averaging of "
                 "the last updatable layer is skipped (result comes from model1)");
     po.Register("skip-layers", &skip_layers_str, "Colon-separated list of "
                 "indices of the layers that should be skipped during averaging."
                 "Be careful: this parameter uses an absolute indexing of "
                 "layers, i.e. iterates over all components, not over updatable "
                 "ones only.");
     po.Read(argc, argv);
     if (po.NumArgs() < 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string
         nnet1_rxfilename = po.GetArg(1),
         nnet_wxfilename = po.GetArg(po.NumArgs());
     TransitionModel trans_model1;
     AmNnet am_nnet1;
     {
       bool binary_read;
       Input ki(nnet1_rxfilename, &binary_read);
       trans_model1.Read(ki.Stream(), binary_read);
       am_nnet1.Read(ki.Stream(), binary_read);
     }
     int32 num_inputs = po.NumArgs() - 1;
     std::vector<BaseFloat> model_weights;
     GetWeights(weights_str, num_inputs, &model_weights);
     int32 c_begin = 0,
         c_end = (skip_last_layer ?
                  am_nnet1.GetNnet().LastUpdatableComponent() :
                  am_nnet1.GetNnet().NumComponents());
     KALDI_ASSERT(c_end != -1 && "Network has no updatable components.");
     int32 last_layer_idx = am_nnet1.GetNnet().NumComponents();
     std::vector<bool> skip_layers = GetSkipLayers(skip_layers_str,
                                              0,
                                              last_layer_idx);
     // scale the components - except the last layer, if skip_last_layer == true.
     for (int32 c = c_begin; c < c_end; c++) {
       if (skip_layers[c]) {
         KALDI_VLOG(2) << "Not averaging layer " << c << " (as requested)";
         continue;
       }
       bool updated = false;
       UpdatableComponent *uc =
         dynamic_cast<UpdatableComponent*>(&(am_nnet1.GetNnet().GetComponent(c)));
       if (uc != NULL)  {
         KALDI_VLOG(2) << "Averaging layer " << c << " (UpdatableComponent)";
         uc->Scale(model_weights[0]);
         updated = true;
       }
       NonlinearComponent *nc =
         dynamic_cast<NonlinearComponent*>(&(am_nnet1.GetNnet().GetComponent(c)));
       if (nc != NULL) {
         KALDI_VLOG(2) << "Averaging layer " << c << " (NonlinearComponent)";
         nc->Scale(model_weights[0]);
         updated = true;
       }
       if (! updated) {
         KALDI_VLOG(2) << "Not averaging layer " << c
           << " (unscalable component)";
       }
     }
     for (int32 i = 2; i <= num_inputs; i++) {
       bool binary_read;
       Input ki(po.GetArg(i), &binary_read);
       TransitionModel trans_model;
       trans_model.Read(ki.Stream(), binary_read);
       AmNnet am_nnet;
       am_nnet.Read(ki.Stream(), binary_read);
       for (int32 c = c_begin; c < c_end; c++) {
         if (skip_layers[c]) continue;
         UpdatableComponent *uc_average =
           dynamic_cast<UpdatableComponent*>(&(am_nnet1.GetNnet().GetComponent(c)));
         const UpdatableComponent *uc_this =
           dynamic_cast<const UpdatableComponent*>(&(am_nnet.GetNnet().GetComponent(c)));
         if (uc_average != NULL) {
           KALDI_ASSERT(uc_this != NULL &&
                        "Networks must have the same structure.");
           uc_average->Add(model_weights[i-1], *uc_this);
         }
         NonlinearComponent *nc_average =
           dynamic_cast<NonlinearComponent*>(&(am_nnet1.GetNnet().GetComponent(c)));
         const NonlinearComponent *nc_this =
           dynamic_cast<const NonlinearComponent*>(&(am_nnet.GetNnet().GetComponent(c)));
         if (nc_average != NULL) {
           KALDI_ASSERT(nc_this != NULL &&
                        "Networks must have the same structure.");
           nc_average->Add(model_weights[i-1], *nc_this);
         }
       }
     }
     {
       Output ko(nnet_wxfilename, binary_write);
       trans_model1.Write(ko.Stream(), binary_write);
       am_nnet1.Write(ko.Stream(), binary_write);
     }
     KALDI_LOG << "Averaged parameters of " << num_inputs
               << " neural nets, and wrote to " << nnet_wxfilename;
     return 0; // it will throw an exception if there are any problems.
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }