Kaldi: nnet3bin/nnet3-discriminative-compute-from-egs.cc File Reference
nnet3-discriminative-compute-from-egs.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet3/nnet-nnet.h"
#include "nnet3/nnet-example-utils.h"
#include "nnet3/nnet-discriminative-example.h"
#include "nnet3/nnet-optimize.h"
Classes
class NnetComputerFromEg
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 63 of file nnet3-discriminative-compute-from-egs.cc.
References MatrixBase< Real >::ApplyExp(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), rnnlm::i, NnetIo::indexes, NnetDiscriminativeExample::inputs, NnetExample::io, KALDI_ASSERT, KALDI_LOG, SequentialTableReader< Holder >::Key(), NnetIo::name, SequentialTableReader< Holder >::Next(), NnetComputerFromEg::NnetComputerFromEg(), ParseOptions::NumArgs(), MatrixBase< Real >::NumRows(), NnetDiscriminativeExample::outputs, ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Read input nnet discriminative training examples, and compute the "
         "output for each one. This program is similar to "
         "nnet3-compute-from-egs, but works with discriminative egs. \n"
         "If --apply-exp=true, apply the Exp() function to the output before writing\n"
         "it out.\n"
         "Note: This program uses only the input; it does not do forward-backward\n"
         "over the lattice. See nnet3-discriminative-compute-objf for that.\n"
         "\n"
         "Usage:  nnet3-discriminative-compute-from-egs [options] <raw-nnet-in> <training-examples-in> <matrices-out>\n"
         "e.g.:\n"
         "nnet3-discriminative-compute-from-egs --apply-exp=true 0.raw ark:1.degs ark:- | matrix-sum-rows ark:- ... \n"
         "See also: nnet3-compute nnet3-compute-from-egs\n";
     bool binary_write = true,
         apply_exp = false;
     std::string use_gpu = "yes";
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("apply-exp", &apply_exp, "If true, apply exp function to "
                 "output");
     po.Register("use-gpu", &use_gpu,
                 "yes|no|optional|wait, only has effect if compiled with CUDA");
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
 #if HAVE_CUDA==1
     CuDevice::Instantiate().SelectGpuId(use_gpu);
 #endif
     std::string nnet_rxfilename = po.GetArg(1),
         examples_rspecifier = po.GetArg(2),
         matrix_wspecifier = po.GetArg(3);
     Nnet nnet;
     ReadKaldiObject(nnet_rxfilename, &nnet);
     NnetComputerFromEg computer(nnet);
     int64 num_egs = 0;
     SequentialNnetDiscriminativeExampleReader example_reader(examples_rspecifier);
     BaseFloatMatrixWriter matrix_writer(matrix_wspecifier);
     for (; !example_reader.Done(); example_reader.Next(), num_egs++) {
       Matrix<BaseFloat> output;
       NnetExample eg;
       NnetDiscriminativeExample disc_eg = example_reader.Value();
       eg.io.swap(disc_eg.inputs);
       for (int32 i = 0; i < disc_eg.outputs.size(); i++) {
         NnetIo io;
         io.name = disc_eg.outputs[i].name;
         io.indexes = disc_eg.outputs[i].indexes;
         eg.io.push_back(io);
       }
       computer.Compute(eg, &output);
       KALDI_ASSERT(output.NumRows() != 0);
       if (apply_exp)
         output.ApplyExp();
       matrix_writer.Write(example_reader.Key(), output);
     }
 #if HAVE_CUDA==1
     CuDevice::Instantiate().PrintProfile();
 #endif
     KALDI_LOG << "Processed " << num_egs << " examples.";
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }