Kaldi: nnet3bin/nnet3-merge-egs.cc File Reference
nnet3-merge-egs.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet3/nnet-example.h"
#include "nnet3/nnet-example-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
int32 NumOutputIndexes (const NnetExample &eg)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 42 of file nnet3-merge-egs.cc.
References ExampleMerger::AcceptExample(), ExampleMergingConfig::ComputeDerived(), SequentialTableReader< Holder >::Done(), ExampleMerger::ExitStatus(), ExampleMerger::Finish(), ParseOptions::GetArg(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ExampleMergingConfig::Register(), and SequentialTableReader< Holder >::Value().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "This copies nnet training examples from input to output, but while doing so it\n"
         "merges many NnetExample objects into one, forming a minibatch consisting of a\n"
         "single NnetExample.\n"
         "\n"
         "Usage:  nnet3-merge-egs [options] <egs-rspecifier> <egs-wspecifier>\n"
         "e.g.\n"
         "nnet3-merge-egs --minibatch-size=512 ark:1.egs ark:- | nnet3-train-simple ... \n"
         "See also nnet3-copy-egs\n";
     ParseOptions po(usage);
     ExampleMergingConfig merging_config;
     merging_config.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string examples_rspecifier = po.GetArg(1),
         examples_wspecifier = po.GetArg(2);
     merging_config.ComputeDerived();
     SequentialNnetExampleReader example_reader(examples_rspecifier);
     NnetExampleWriter example_writer(examples_wspecifier);
     ExampleMerger merger(merging_config, &example_writer);
     for (; !example_reader.Done(); example_reader.Next()) {
       const NnetExample &cur_eg = example_reader.Value();
       merger.AcceptExample(new NnetExample(cur_eg));
     }
     // the merger itself prints the necessary diagnostics.
     merger.Finish();
     return merger.ExitStatus();
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }