Kaldi: nnet3/nnet-graph-test.cc File Reference
nnet-graph-test.cc File Reference
#include "nnet3/nnet-graph.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
bool AssertGraphEqual (const std::vector< std::vector< int32 > > &graph1, const std::vector< std::vector< int32 > > &graph2)
bool AssertVectorEqual (const std::vector< int32 > &vec1, const std::vector< int32 > &vec2)
void BuildTestGraph (std::vector< std::vector< int32 > > *graph)
void BuildTestGraphTranspose (std::vector< std::vector< int32 > > *graph)
void BuildTestSccs (std::vector< std::vector< int32 > > *sccs)
void BuildTestSccGraph (std::vector< std::vector< int32 > > *scc_graph)
void BuildTestTopSortOrder (std::vector< int32 > *node_to_order)
void UnitTestComputeGraphTranspose ()
void UnitTestFindSccs ()
void UnitTestMakeSccGraph ()
void UnitTestComputeTopSortOrder ()
void UnitTestComputeTopSortOrder2 ()
int main ()
Function Documentation
main()
int main ()
Definition at line 231 of file nnet-graph-test.cc.
References KALDI_LOG, kaldi::nnet3::UnitTestComputeGraphTranspose(), kaldi::nnet3::UnitTestComputeTopSortOrder(), kaldi::nnet3::UnitTestComputeTopSortOrder2(), kaldi::nnet3::UnitTestFindSccs(), and kaldi::nnet3::UnitTestMakeSccGraph().
            {
   using namespace kaldi;
   using namespace kaldi::nnet3;
   UnitTestComputeGraphTranspose();
   UnitTestFindSccs();
   UnitTestMakeSccGraph();
   UnitTestComputeTopSortOrder();
   UnitTestComputeTopSortOrder2();
   KALDI_LOG << "Nnet graph tests succeeded.";
   return 0;
 }