Kaldi: nnet3/nnet-compile-test.cc File Reference
nnet-compile-test.cc File Reference
#include "nnet3/nnet-nnet.h"
#include "nnet3/nnet-compile.h"
#include "nnet3/nnet-compile-looped.h"
#include "nnet3/nnet-test-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
kaldi::nnet3
Functions
void UnitTestNnetCompile ()
void UnitTestNnetCompileMulti ()
void UnitTestNnetCompileLooped ()
int main ()
Function Documentation
main()
int main ()
Definition at line 177 of file nnet-compile-test.cc.
References KALDI_LOG, kaldi::SetVerboseLevel(), kaldi::nnet3::UnitTestNnetCompile(), kaldi::nnet3::UnitTestNnetCompileLooped(), and kaldi::nnet3::UnitTestNnetCompileMulti().
            {
   using namespace kaldi;
   using namespace kaldi::nnet3;
   SetVerboseLevel(4);
   UnitTestNnetCompileLooped();
   UnitTestNnetCompile();
   UnitTestNnetCompileMulti();
   KALDI_LOG << "Nnet tests succeeded.";
   return 0;
 }