Kaldi: nnetbin/nnet-concat.cc File Reference
nnet-concat.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "nnet/nnet-nnet.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 24 of file nnet-concat.cc.
References Nnet::AppendNnet(), ParseOptions::GetArg(), rnnlm::i, KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), Nnet::Read(), ParseOptions::Register(), Output::Stream(), Input::Stream(), and Nnet::Write().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet1;
     typedef kaldi::int32 int32;
     const char *usage =
       "Concatenate Neural Networks (and possibly change binary/text format)\n"
       "Usage: nnet-concat [options] <nnet-in1> <...> <nnet-inN> <nnet-out>\n"
       "e.g.:\n"
       " nnet-concat --binary=false nnet.1 nnet.2 nnet.1.2\n";
     ParseOptions po(usage);
     bool binary_write = true;
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() < 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_in_filename = po.GetArg(1);
     std::string model_in_filename_next;
     std::string model_out_filename = po.GetArg(po.NumArgs());
     // read the first nnet,
     KALDI_LOG << "Reading " << model_in_filename;
     Nnet nnet;
     {
       bool binary_read;
       Input ki(model_in_filename, &binary_read);
       nnet.Read(ki.Stream(), binary_read);
     }
     // read all the other nnets,
     for (int32 i = 2; i < po.NumArgs(); i++) {
       // read the nnet,
       model_in_filename_next = po.GetArg(i);
       KALDI_LOG << "Concatenating " << model_in_filename_next;
       Nnet nnet_next;
       {
         bool binary_read;
         Input ki(model_in_filename_next, &binary_read);
         nnet_next.Read(ki.Stream(), binary_read);
       }
       // append nnet_next to the network nnet,
       nnet.AppendNnet(nnet_next);
     }
     // finally write the nnet to disk,
     {
       Output ko(model_out_filename, binary_write);
       nnet.Write(ko.Stream(), binary_write);
     }
     KALDI_LOG << "Written model to " << model_out_filename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }