Kaldi: feat/pitch-functions-test.cc File Reference
pitch-functions-test.cc File Reference
#include <iostream>
#include "base/kaldi-math.h"
#include "feat/feature-plp.h"
#include "feat/pitch-functions.h"
#include "feat/wave-reader.h"
#include "sys/stat.h"
#include "sys/types.h"
#include "base/timer.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
std::string ConvertIntToString (const int &number)
bool DirExist (const std::string &dirname)
static void UnitTestSimple ()
static void UnitTestSnipEdges ()
static void UnitTestPieces ()
static void UnitTestDelay ()
static void UnitTestSearch ()
static void UnitTestComputeGPE ()
static void UnitTestKeele ()
static void UnitTestPenaltyFactor ()
static void UnitTestKeeleNccfBallast ()
static void UnitTestPitchExtractionSpeed ()
static void UnitTestPitchExtractorCompareKeele ()
void UnitTestDiffSampleRate ()
void UnitTestProcess ()
static void UnitTestFeatNoKeele ()
static void UnitTestFeatWithKeele ()
int main ()
Variables
bool pitch_use_naive_search = false
Function Documentation
main()
int main ()
Definition at line 617 of file pitch-functions-test.cc.
References kaldi::DirExist(), KALDI_ERR, KALDI_LOG, kaldi::SetVerboseLevel(), kaldi::UnitTestFeatNoKeele(), and kaldi::UnitTestFeatWithKeele().
            {
   using namespace kaldi;
   SetVerboseLevel(3);
   try {
     UnitTestFeatNoKeele();
     if (DirExist("keele/16kHz")) {
       UnitTestFeatWithKeele();
     } else {
       KALDI_LOG
           << "Not running tests that require the Keele database, "
           << "please ask g.meyer@liverpool.ac.uk for the database if you need it.\n"
           << "Once you have the keele/ subdirectory, containing *.{pel,pet,pev,raw,wav}, do this:\n"
           << "cd keele; mkdir -p 16kHz; mkdir -p tmp; for x in *.wav; do \n"
           << "sox $x -r 16000 16kHz/$x; done  \n"
           << "mkdir -p keele-true-lags; for f in *.pev; do \n"
           << "out_f=keele-true-lags/$(echo $f | sed s:pev:txt:); ( echo ' ['; len=`cat $f | wc -l`; \n"
           << "head -n $(($len-1)) $f | tail -n $(($len-14)) ; echo -n ']') >$out_f; done \n"
           << "\n"
           << "Note: the GPE reported in paper is computed using pseudo-ground-truth pitch obtained\n"
           << "by voting among the pitch trackers mentioned in the paper.\n";
     }
     KALDI_LOG << "Tests succeeded.";
     return 0;
   } catch(const std::exception &e) {
     KALDI_ERR << e.what();
     return 1;
   }
 }