Kaldi: featbin/process-pitch-feats.cc File Reference
process-pitch-feats.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void ProcessPovFeatures (Matrix< BaseFloat > *mat)
void TakeLogOfPitch (Matrix< BaseFloat > *mat)
void SubtractMovingAverage (int32 normalization_window_size, Matrix< BaseFloat > *mat)
void SetToMovingAverage (int32 average_window_size, Matrix< BaseFloat > *mat)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 105 of file process-pitch-feats.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_ASSERT, KALDI_ERR, KALDI_LOG, KALDI_VLOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), TableWriter< Holder >::Open(), ParseOptions::PrintUsage(), kaldi::ProcessPovFeatures(), ParseOptions::Read(), ParseOptions::Register(), kaldi::SetToMovingAverage(), kaldi::SubtractMovingAverage(), kaldi::TakeLogOfPitch(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     const char *usage =
         "This is a rather special-purpose program which processes 2-dimensional\n"
         "features consisting of (prob-of-voicing, pitch) into something suitable\n"
         "to put into a speech recognizer.  First use interpolate-feats\n"
         "Usage:  process-pitch-feats [options...] <feats-rspecifier> <feats-wspecifier>\n";
     // construct all the global objects
     ParseOptions po(usage);
     int32 normalization_window_size = 151; // should be odd number
     int32 average_window_size = 5;
     // Register the options
     po.Register("normalization-window-size",
                 &normalization_window_size, "Size of window used for "
                 "moving window nomalization (must be odd).");
     po.Register("average-window-size",
                 &average_window_size,
                 "Size of moving average window (must be odd).");
     // parse options (+filling the registered variables)
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     KALDI_ASSERT(average_window_size > 0 && average_window_size % 2 == 1 &&
                  "--average-window-size option must be an odd positive number.");
     KALDI_ASSERT(normalization_window_size > 0 && normalization_window_size % 2 == 1 &&
                  "--normalization-window-size option must be an odd positive number.");
     std::string input_rspecifier = po.GetArg(1);
     std::string output_wspecifier = po.GetArg(2);
     SequentialBaseFloatMatrixReader reader(input_rspecifier);
     BaseFloatMatrixWriter kaldi_writer;  // typedef to TableWriter<something>.
     if (!kaldi_writer.Open(output_wspecifier))
        KALDI_ERR << "Could not initialize output with wspecifier "
                 << output_wspecifier;
     int32 num_done = 0, num_err = 0;
     for (; !reader.Done(); reader.Next()) {
       std::string utt = reader.Key();
       Matrix<BaseFloat> features = reader.Value();
       int num_frames = features.NumRows();
       if (num_frames == 0 && features.NumCols() != 2) {
         KALDI_WARN << "Feature file has bad size "
                    << features.NumRows() << " by " << features.NumCols();
         num_err++;
         continue;
       }
       ProcessPovFeatures(&features);
       TakeLogOfPitch(&features);
       SubtractMovingAverage(normalization_window_size, &features);
       SetToMovingAverage(average_window_size, &features);
       kaldi_writer.Write(utt, features);
       num_done++;
       if (num_done % 10 == 0)
         KALDI_LOG << "Processed " << num_done << " utterances";
       KALDI_VLOG(2) << "Processed features for key " << utt;
     }
     KALDI_LOG << "Done " << num_done << " utterances, " << num_err
               << " with errors.";
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }