Kaldi: sgmm2bin/sgmm2-project.cc File Reference
sgmm2-project.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "util/kaldi-thread.h"
#include "hmm/transition-model.h"
#include "sgmm2/am-sgmm2-project.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 27 of file sgmm2-project.cc.
References MatrixBase< Real >::AddMatMat(), Sgmm2Project::ApplyProjection(), AmSgmm2::ComputeDerivedVars(), Sgmm2Project::ComputeProjection(), ParseOptions::GetArg(), KALDI_ASSERT, KALDI_LOG, kaldi::kNoTrans, ParseOptions::NumArgs(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), ParseOptions::Read(), TransitionModel::Read(), AmSgmm2::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), Output::Stream(), Input::Stream(), kaldi::StringToSgmmWriteFlags(), TransitionModel::Write(), AmSgmm2::Write(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Compute SGMM model projection that only models a part of a pre-LDA space.\n"
         "Used in predictive SGMMs.  Takes as input an LDA+MLLT transform,\n"
         "and outputs a transform from the pre-LDA+MLLT space to the space that\n"
         "we want to model\n"
         "Usage: sgmm2-project [options] <model-in> <lda-mllt-mat-in> <model-out> <new-projection-out>\n"
         "e.g.: sgmm2-project --start-dim=0 --end-dim=52 final.mdl final.inv_full_mat final_proj1.mdl proj1.mat\n";
     std::string write_flags_str = "gsnu";
     bool binary_write = false;
     int32 start_dim = 0;
     int32 end_dim = 0;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("start-dim", &start_dim, "Starting dimension to keep in "
                 "pre-LDA-MLLT space.");
     po.Register("end-dim", &end_dim, "Ending dimension to keep in "
                 "pre-LDA-MLLT space (equals last retained dimension plus one)");
     po.Read(argc, argv);
     if (po.NumArgs() != 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_rxfilename = po.GetArg(1),
         lda_mllt_rxfilename = po.GetArg(2),
         model_wxfilename = po.GetArg(3),
         proj_wxfilename = po.GetArg(4);
     kaldi::SgmmWriteFlagsType write_flags =
         StringToSgmmWriteFlags(write_flags_str);
     AmSgmm2 am_sgmm;
     TransitionModel trans_model;
     {
       bool binary;
       Input ki(model_rxfilename, &binary);
       trans_model.Read(ki.Stream(), binary);
       am_sgmm.Read(ki.Stream(), binary);
     }
     Matrix<BaseFloat> lda_mllt_mat;
     ReadKaldiObject(lda_mllt_rxfilename, &lda_mllt_mat);
     // Need the full LDA+MLLT matrix, including the extra rows.
     // See featbin/extend-transform.cc
     KALDI_ASSERT(lda_mllt_mat.NumRows() == lda_mllt_mat.NumCols());
     Matrix<BaseFloat> inv_lda_mllt_mat(lda_mllt_mat);
     inv_lda_mllt_mat.Invert();
     Matrix<BaseFloat> projection;
     Sgmm2Project sgmm_project;
     sgmm_project.ComputeProjection(am_sgmm, inv_lda_mllt_mat, start_dim, end_dim,
                                    &projection);
     Matrix<BaseFloat> total_projection(projection.NumRows(), projection.NumCols());
     total_projection.AddMatMat(1.0, projection, kNoTrans,
                                inv_lda_mllt_mat, kNoTrans, 0.0);
     sgmm_project.ApplyProjection(total_projection, &am_sgmm);
     am_sgmm.ComputeDerivedVars(); // recompute normalizers, and possibly
     // weights.
     {
       Output ko(model_wxfilename, binary_write);
       trans_model.Write(ko.Stream(), binary_write);
       am_sgmm.Write(ko.Stream(), binary_write, write_flags);
     }
     KALDI_LOG << "Wrote model to " << model_wxfilename;
     WriteKaldiObject(projection, proj_wxfilename, binary_write);
     KALDI_LOG << "Wrote projection matrix to " << proj_wxfilename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }