Kaldi: featbin/shift-feats.cc File Reference
shift-feats.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-matrix.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
void ShiftFeatureMatrix (const Matrix< BaseFloat > &src, int32 shift, Matrix< BaseFloat > *rearranged)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 37 of file shift-feats.cc.
References kaldi::ClassifyRspecifier(), ParseOptions::GetArg(), KALDI_ERR, KALDI_LOG, KALDI_WARN, kaldi::kNoRspecifier, ParseOptions::NumArgs(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), kaldi::ShiftFeatureMatrix(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     const char *usage =
         "Copy features, and possibly shift them while maintaining the "
         "num-frames.\n"
         "Usage: shift-feats [options] <feature-rspecifier> "
         "<feature-wspecifier>\n"
         "or:  shift-feats [options] <feats-rxfilename> <feats-wxfilename>\n"
         "e.g.: shift-feats --shift=-1 foo.scp bar.ark\n"
         "or: shift-feats --shift=1 foo.mat bar.mat\n"
         "See also: copy-feats, copy-matrix, select-feats, subset-feats,\n"
         "subsample-feats, splice-feats, paste-feats, concat-feats, "
         "extract-feature-segments\n";
     ParseOptions po(usage);
     bool binary = true;
     int32 shift = 0;
     po.Register("shift", &shift, "Number of frames by which to shift the "
                                  "features.");
     po.Register("binary", &binary, "Binary-mode output (not relevant if "
                 "writing to archive)");
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     int32 num_done = 0, num_err = 0;
     if (ClassifyRspecifier(po.GetArg(1), NULL, NULL) != kNoRspecifier) {
       SequentialBaseFloatMatrixReader feat_reader(po.GetArg(1));
       BaseFloatMatrixWriter feat_writer(po.GetArg(2));
       for (; !feat_reader.Done(); feat_reader.Next()) {
         const std::string &key = feat_reader.Key();
         const Matrix<BaseFloat> &src = feat_reader.Value();
         if (src.NumRows() == 0) {
           KALDI_WARN << "Empty matrix for key " << key;
           num_err++;
           continue;
         }
         Matrix<BaseFloat> rearranged(src.NumRows(), src.NumCols());
         ShiftFeatureMatrix(src, shift, &rearranged);
         feat_writer.Write(key, rearranged);
         num_done++;
       }
       KALDI_LOG << "Shifted " << num_done << " features by "
                 << shift << " frames; " << num_err << " with errors.";
       return (num_done > 0 ? 0 : 1);
     } else {
       std::string feat_rxfilename = po.GetArg(1),
                   feat_wxfilename = po.GetArg(2);
       Matrix<BaseFloat> src;
       ReadKaldiObject(feat_rxfilename, &src);
       if (src.NumRows() == 0)
         KALDI_ERR << "Empty input matrix";
       Matrix<BaseFloat> rearranged(src.NumRows(), src.NumCols());
       ShiftFeatureMatrix(src, shift, &rearranged);
       WriteKaldiObject(rearranged, feat_wxfilename, binary);
       // we do not print any log messages here
     }
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }