Kaldi: util/stl-utils-test.cc File Reference
stl-utils-test.cc File Reference
#include "base/kaldi-common.h"
#include "util/stl-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
static void TestIsSorted ()
static void TestIsSortedAndUniq ()
static void TestUniq ()
static void TestSortAndUniq ()
void TestCopySetToVector ()
void TestCopyMapToVector ()
void TestCopyMapKeysToVector ()
void TestCopyMapValuesToVector ()
void TestCopyMapKeysToSet ()
void TestCopyMapValuesToSet ()
void TestContainsNullPointers ()
void TestReverseVector ()
void TestMergePairVectorSumming ()
int main ()
Function Documentation
main()
int main ()
Definition at line 255 of file stl-utils-test.cc.
References kaldi::TestContainsNullPointers(), kaldi::TestCopyMapKeysToSet(), kaldi::TestCopyMapKeysToVector(), kaldi::TestCopyMapToVector(), kaldi::TestCopyMapValuesToSet(), kaldi::TestCopyMapValuesToVector(), kaldi::TestCopySetToVector(), kaldi::TestIsSorted(), kaldi::TestIsSortedAndUniq(), kaldi::TestMergePairVectorSumming(), kaldi::TestReverseVector(), kaldi::TestSortAndUniq(), and kaldi::TestUniq().
            {
   using namespace kaldi;
   TestIsSorted();
   TestIsSortedAndUniq();
   TestUniq();
   TestSortAndUniq();
   TestCopySetToVector();
   TestCopyMapToVector();
   TestCopyMapKeysToVector();
   TestCopyMapValuesToVector();
   TestCopyMapKeysToSet();
   TestCopyMapValuesToSet();
   TestContainsNullPointers();
   TestReverseVector();
   TestMergePairVectorSumming();
   // CopyVectorToSet implicitly tested by last 2.
   std::cout << "Test OK\n";
 }