Kaldi: AlignConfig Struct Reference
AlignConfig Struct Reference
#include <decoder-wrappers.h>
Public Member Functions
AlignConfig ()
void Register (OptionsItf *opts)
Public Attributes
BaseFloat beam
BaseFloat retry_beam
bool careful
Detailed Description
Definition at line 34 of file decoder-wrappers.h.
Constructor & Destructor Documentation
AlignConfig()
AlignConfig () inline
Definition at line 39 of file decoder-wrappers.h.
 : beam(200.0), retry_beam(0.0), careful(false) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 41 of file decoder-wrappers.h.
References kaldi::AlignUtteranceWrapper(), kaldi::DecodeUtteranceLatticeFaster(), kaldi::ModifyGraphForCarefulAlignment(), and OptionsItf::Register().
Referenced by main().
{
     opts->Register("beam", &beam, "Decoding beam used in alignment");
     opts->Register("retry-beam", &retry_beam,
                    "Decoding beam for second try at alignment");
     opts->Register("careful", &careful,
                    "If true, do 'careful' alignment, which is better at detecting "
                    "alignment failure (involves loop to start of decoding graph).");
   }
Member Data Documentation
beam
BaseFloat beam
Definition at line 35 of file decoder-wrappers.h.
Referenced by kaldi::AlignUtteranceWrapper().
careful
bool careful
Definition at line 37 of file decoder-wrappers.h.
Referenced by kaldi::AlignUtteranceWrapper().
retry_beam
BaseFloat retry_beam
Definition at line 36 of file decoder-wrappers.h.
Referenced by kaldi::AlignUtteranceWrapper().
The documentation for this struct was generated from the following file:
decoder/decoder-wrappers.h