Kaldi: EbwWeightOptions Struct Reference
EbwWeightOptions Struct Reference
#include <ebw-diag-gmm.h>
Public Member Functions
EbwWeightOptions ()
void Register (OptionsItf *opts)
Public Attributes
BaseFloat min_num_count_weight_update
BaseFloat min_gaussian_weight
BaseFloat tau
Detailed Description
Definition at line 47 of file ebw-diag-gmm.h.
Constructor & Destructor Documentation
EbwWeightOptions()
EbwWeightOptions () inline
Definition at line 52 of file ebw-diag-gmm.h.
                     : min_num_count_weight_update(10.0),
                       min_gaussian_weight(1.0e-05),
                       tau(0.0) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 55 of file ebw-diag-gmm.h.
References kaldi::DiagGmmToStats(), kaldi::IsmoothStatsAmDiagGmm(), kaldi::IsmoothStatsAmDiagGmmFromModel(), kaldi::IsmoothStatsDiagGmm(), OptionsItf::Register(), EbwOptions::tau, kaldi::UpdateEbwAmDiagGmm(), kaldi::UpdateEbwDiagGmm(), kaldi::UpdateEbwWeightsAmDiagGmm(), and kaldi::UpdateEbwWeightsDiagGmm().
Referenced by main().
{
     std::string module = "EbwWeightOptions: ";
     opts->Register("min-num-count-weight-update", &min_num_count_weight_update,
                  module+"Minimum numerator count required at "
                  "state level before we update the weights (only active if tau == 0.0)");
     opts->Register("min-gaussian-weight", &min_gaussian_weight,
                  module+"Minimum Gaussian weight allowed in EBW update of weights");
     opts->Register("weight-tau", &tau,
                  module+"Tau value for smoothing Gaussian weight update.");
   }
Member Data Documentation
min_gaussian_weight
BaseFloat min_gaussian_weight
Definition at line 49 of file ebw-diag-gmm.h.
Referenced by kaldi::UpdateEbwWeightsDiagGmm().
min_num_count_weight_update
BaseFloat min_num_count_weight_update
Definition at line 48 of file ebw-diag-gmm.h.
Referenced by kaldi::UpdateEbwWeightsDiagGmm().
tau
BaseFloat tau
Definition at line 50 of file ebw-diag-gmm.h.
Referenced by kaldi::UpdateEbwWeightsDiagGmm().
The documentation for this struct was generated from the following file:
gmm/ebw-diag-gmm.h