Kaldi: ImageAugmentationConfig Struct Reference
ImageAugmentationConfig Struct Reference
Public Member Functions
ImageAugmentationConfig ()
void Register (ParseOptions *po)
void Check () const
FillMode GetFillMode () const
Public Attributes
int32 num_channels
BaseFloat horizontal_flip_prob
BaseFloat horizontal_shift
BaseFloat vertical_shift
BaseFloat rotation_degree
BaseFloat rotation_prob
std::string fill_mode_string
Detailed Description
Definition at line 33 of file nnet3-egs-augment-image.cc.
Constructor & Destructor Documentation
ImageAugmentationConfig()
ImageAugmentationConfig () inline
Definition at line 42 of file nnet3-egs-augment-image.cc.
                            :
       num_channels(1),
       horizontal_flip_prob(0.0),
       horizontal_shift(0.0),
       vertical_shift(0.0),
       rotation_degree(0.0),
       rotation_prob(0.0),
       fill_mode_string("nearest") { }
Member Function Documentation
Check()
void Check () const inline
Definition at line 73 of file nnet3-egs-augment-image.cc.
References KALDI_ASSERT.
Referenced by kaldi::nnet3::PerturbImage().
                      {
     KALDI_ASSERT(num_channels >= 1);
     KALDI_ASSERT(horizontal_flip_prob >= 0 &&
                  horizontal_flip_prob <= 1);
     KALDI_ASSERT(horizontal_shift >= 0 && horizontal_shift <= 1);
     KALDI_ASSERT(vertical_shift >= 0 && vertical_shift <= 1);
     KALDI_ASSERT(rotation_degree >=0 && rotation_degree <= 180);
     KALDI_ASSERT(rotation_prob >=0 && rotation_prob <= 1);
     KALDI_ASSERT(fill_mode_string == "nearest" || fill_mode_string == "reflect");
   }
GetFillMode()
FillMode GetFillMode () const inline
Definition at line 84 of file nnet3-egs-augment-image.cc.
References ImageAugmentationConfig::fill_mode_string, KALDI_ERR, kaldi::nnet3::kNearest, and kaldi::nnet3::kReflect.
Referenced by kaldi::nnet3::PerturbImage().
{
     FillMode fill_mode;
     if (fill_mode_string == "reflect") {
       fill_mode = kReflect;
     } else {
       if (fill_mode_string != "nearest") {
         KALDI_ERR << "Choices for --fill-mode are 'nearest' or 'reflect', got: "
                   << fill_mode_string;
       } else {
         fill_mode = kNearest;
       }
     }
     return fill_mode;
   }
Register()
void Register (ParseOptions * po) inline
Definition at line 52 of file nnet3-egs-augment-image.cc.
References ParseOptions::Register().
Referenced by main().
{
     po->Register("num-channels", &num_channels, "Number of colors in the image."
                  "It is important to specify this (helps interpret the image "
                  "correctly.");
     po->Register("horizontal-flip-prob", &horizontal_flip_prob,
                  "Probability of doing horizontal flip");
     po->Register("horizontal-shift", &horizontal_shift,
                  "Maximum allowed horizontal shift as proportion of image "
                  "width.  Padding is with closest pixel.");
     po->Register("vertical-shift", &vertical_shift,
                  "Maximum allowed vertical shift as proportion of image "
                  "height.  Padding is with closest pixel.");
     po->Register("rotation-degree", &rotation_degree,
                  "Maximum allowed degree to rotate the image");
     po->Register("rotation-prob", &rotation_prob,
                  "Probability of doing rotation");
     po->Register("fill-mode", &fill_mode_string, "Mode for dealing with "
                  "points outside the image boundary when applying transformation. "
                  "Choices = {nearest, reflect}");
   }
Member Data Documentation
fill_mode_string
std::string fill_mode_string
Definition at line 40 of file nnet3-egs-augment-image.cc.
Referenced by ImageAugmentationConfig::GetFillMode().
horizontal_flip_prob
BaseFloat horizontal_flip_prob
Definition at line 35 of file nnet3-egs-augment-image.cc.
Referenced by kaldi::nnet3::PerturbImage().
horizontal_shift
BaseFloat horizontal_shift
Definition at line 36 of file nnet3-egs-augment-image.cc.
Referenced by kaldi::nnet3::PerturbImage().
num_channels
int32 num_channels
Definition at line 34 of file nnet3-egs-augment-image.cc.
Referenced by kaldi::nnet3::ApplyAffineTransform(), and kaldi::nnet3::PerturbImage().
rotation_degree
BaseFloat rotation_degree
Definition at line 38 of file nnet3-egs-augment-image.cc.
Referenced by kaldi::nnet3::PerturbImage().
rotation_prob
BaseFloat rotation_prob
Definition at line 39 of file nnet3-egs-augment-image.cc.
Referenced by kaldi::nnet3::PerturbImage().
vertical_shift
BaseFloat vertical_shift
Definition at line 37 of file nnet3-egs-augment-image.cc.
Referenced by kaldi::nnet3::PerturbImage().
The documentation for this struct was generated from the following file:
nnet3bin/nnet3-egs-augment-image.cc