Kaldi: ComposeLatticePrunedOptions Struct Reference
ComposeLatticePrunedOptions Struct Reference
#include <compose-lattice-pruned.h>
Public Member Functions
ComposeLatticePrunedOptions ()
void Register (OptionsItf *po)
Public Attributes
float lattice_compose_beam
int32 max_arcs
int32 initial_num_arcs
BaseFloat growth_ratio
Detailed Description
Definition at line 94 of file compose-lattice-pruned.h.
Constructor & Destructor Documentation
ComposeLatticePrunedOptions()
ComposeLatticePrunedOptions () inline
Definition at line 124 of file compose-lattice-pruned.h.
                                : lattice_compose_beam(6.0),
                                  max_arcs(100000),
                                  initial_num_arcs(100),
                                  growth_ratio(1.5) { }
Member Function Documentation
Register()
void Register (OptionsItf * po) inline
Definition at line 128 of file compose-lattice-pruned.h.
References kaldi::ComposeCompactLatticePruned(), and OptionsItf::Register().
Referenced by main().
{
     po->Register("lattice-compose-beam", &lattice_compose_beam,
                  "Beam used in pruned lattice composition, which determines how "
                  "large the composed lattice may be.");
     po->Register("max-arcs", &max_arcs, "Maximum number of arcs we allow in "
                  "any given lattice, during pruned composition (limits max size "
                  "of lattices; also see lattice-compose-beam).");
     po->Register("growth-ratio", &growth_ratio, "Factor used in the lattice "
                  "composition algorithm; must be >1.0.  Affects speed vs. "
                  "the optimality of the best-first composition.");
   }
Member Data Documentation
growth_ratio
BaseFloat growth_ratio
Definition at line 122 of file compose-lattice-pruned.h.
Referenced by PrunedCompactLatticeComposer::GetCurrentArcLimit().
initial_num_arcs
int32 initial_num_arcs
Definition at line 115 of file compose-lattice-pruned.h.
Referenced by PrunedCompactLatticeComposer::GetCurrentArcLimit().
lattice_compose_beam
float lattice_compose_beam
Definition at line 104 of file compose-lattice-pruned.h.
Referenced by PrunedCompactLatticeComposer::ComputeBackwardCosts().
max_arcs
int32 max_arcs
Definition at line 110 of file compose-lattice-pruned.h.
Referenced by PrunedCompactLatticeComposer::Compose(), and PrunedCompactLatticeComposer::GetCurrentArcLimit().
The documentation for this struct was generated from the following file:
lat/compose-lattice-pruned.h