Kaldi: DeterminizeLatticePhonePrunedOptions Struct Reference
DeterminizeLatticePhonePrunedOptions Struct Reference
Fst_extensions
#include <determinize-lattice-pruned.h>
Public Member Functions
DeterminizeLatticePhonePrunedOptions ()
void Register (kaldi::OptionsItf *opts)
Public Attributes
float delta
int max_mem
bool phone_determinize
bool word_determinize
bool minimize
Detailed Description
Definition at line 145 of file determinize-lattice-pruned.h.
Constructor & Destructor Documentation
DeterminizeLatticePhonePrunedOptions()
DeterminizeLatticePhonePrunedOptions () inline
Definition at line 158 of file determinize-lattice-pruned.h.
                                         : delta(kDelta),
                                           max_mem(50000000),
                                           phone_determinize(true),
                                           word_determinize(true),
                                           minimize(false) {}
Member Function Documentation
Register()
void Register (kaldi::OptionsItf * opts) inline
Definition at line 163 of file determinize-lattice-pruned.h.
References fst::DeterminizeLatticeDeletePhones(), fst::DeterminizeLatticeInsertPhones(), fst::DeterminizeLatticePhonePruned(), fst::DeterminizeLatticePhonePrunedWrapper(), fst::DeterminizeLatticePruned(), DeterminizeLatticePrunedOptions::DeterminizeLatticePrunedOptions(), and OptionsItf::Register().
Referenced by main(), LatticeSimpleDecoderConfig::Register(), and LatticeFasterDecoderConfig::Register().
{
     opts->Register("delta", &delta, "Tolerance used in determinization");
     opts->Register("max-mem", &max_mem, "Maximum approximate memory usage in "
                    "determinization (real usage might be many times this).");
     opts->Register("phone-determinize", &phone_determinize, "If true, do an "
                    "initial pass of determinization on both phones and words (see"
                    " also --word-determinize)");
     opts->Register("word-determinize", &word_determinize, "If true, do a second "
                    "pass of determinization on words only (see also "
                    "--phone-determinize)");
     opts->Register("minimize", &minimize, "If true, push and minimize after "
                    "determinization.");
   }
Member Data Documentation
delta
float delta
Definition at line 147 of file determinize-lattice-pruned.h.
Referenced by fst::DeterminizeLatticePhonePruned().
max_mem
int max_mem
Definition at line 150 of file determinize-lattice-pruned.h.
Referenced by fst::DeterminizeLatticePhonePruned(), LatticeSimpleDecoder::GetLattice(), LatticeBiglmFasterDecoder::GetLattice(), and main().
minimize
bool minimize
Definition at line 157 of file determinize-lattice-pruned.h.
Referenced by fst::DeterminizeLatticePhonePruned().
phone_determinize
bool phone_determinize
Definition at line 153 of file determinize-lattice-pruned.h.
Referenced by fst::DeterminizeLatticePhonePruned().
word_determinize
bool word_determinize
Definition at line 155 of file determinize-lattice-pruned.h.
Referenced by fst::DeterminizeLatticePhonePruned().
The documentation for this struct was generated from the following file:
lat/determinize-lattice-pruned.h