Kaldi: VadEnergyOptions Struct Reference
VadEnergyOptions Struct Reference
#include <voice-activity-detection.h>
Public Member Functions
VadEnergyOptions ()
void Register (OptionsItf *opts)
Public Attributes
BaseFloat vad_energy_threshold
BaseFloat vad_energy_mean_scale
int32 vad_frames_context
BaseFloat vad_proportion_threshold
Detailed Description
Definition at line 42 of file voice-activity-detection.h.
Constructor & Destructor Documentation
VadEnergyOptions()
VadEnergyOptions () inline
Definition at line 48 of file voice-activity-detection.h.
                     : vad_energy_threshold(5.0),
                       vad_energy_mean_scale(0.5),
                       vad_frames_context(0),
                       vad_proportion_threshold(0.6) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 52 of file voice-activity-detection.h.
References kaldi::ComputeVadEnergy(), and OptionsItf::Register().
Referenced by main().
{
     opts->Register("vad-energy-threshold", &vad_energy_threshold,
                    "Constant term in energy threshold for MFCC0 for VAD (also see "
                    "--vad-energy-mean-scale)");
     opts->Register("vad-energy-mean-scale", &vad_energy_mean_scale,
                    "If this is set to s, to get the actual threshold we "
                    "let m be the mean log-energy of the file, and use "
                    "s*m + vad-energy-threshold");
     opts->Register("vad-frames-context", &vad_frames_context,
                    "Number of frames of context on each side of central frame, "
                    "in window for which energy is monitored");
     opts->Register("vad-proportion-threshold", &vad_proportion_threshold,
                    "Parameter controlling the proportion of frames within "
                    "the window that need to have more energy than the "
                    "threshold");
   }
Member Data Documentation
vad_energy_mean_scale
BaseFloat vad_energy_mean_scale
Definition at line 44 of file voice-activity-detection.h.
Referenced by kaldi::ComputeVadEnergy().
vad_energy_threshold
BaseFloat vad_energy_threshold
Definition at line 43 of file voice-activity-detection.h.
Referenced by kaldi::ComputeVadEnergy().
vad_frames_context
int32 vad_frames_context
Definition at line 45 of file voice-activity-detection.h.
Referenced by kaldi::ComputeVadEnergy().
vad_proportion_threshold
BaseFloat vad_proportion_threshold
Definition at line 46 of file voice-activity-detection.h.
Referenced by kaldi::ComputeVadEnergy().
The documentation for this struct was generated from the following file:
ivector/voice-activity-detection.h