Kaldi: WordBoundaryInfo Struct Reference
WordBoundaryInfo Struct Reference
#include <word-align-lattice.h>
Public Types
enum PhoneType {
kNoPhone = 0, kWordBeginPhone, kWordEndPhone, kWordBeginAndEndPhone,
kWordInternalPhone, kNonWordPhone
}
Public Member Functions
WordBoundaryInfo (const WordBoundaryInfoOpts &opts)
WordBoundaryInfo (const WordBoundaryInfoNewOpts &opts)
WordBoundaryInfo (const WordBoundaryInfoNewOpts &opts, std::string word_boundary_file)
void Init (std::istream &stream)
PhoneType TypeOfPhone (int32 p) const
Public Attributes
std::vector< PhoneType > phone_to_type
int32 silence_label
int32 partial_word_label
bool reorder
Private Member Functions
void SetOptions (const std::string int_list, PhoneType phone_type)
Detailed Description
Definition at line 119 of file word-align-lattice.h.
Member Enumeration Documentation
PhoneType
enum PhoneType
Enumerator
kNoPhone
kWordBeginPhone
kWordEndPhone
kWordBeginAndEndPhone
kWordInternalPhone
kNonWordPhone
Definition at line 136 of file word-align-lattice.h.
                  {
     kNoPhone = 0,
     kWordBeginPhone,
     kWordEndPhone,
     kWordBeginAndEndPhone,
     kWordInternalPhone,
     kNonWordPhone // non-word phones are typically silence phones; but the point
     // is that there is
     // no word label associated with them in the lattice.  If a silence phone
     // had a word label with it, we'd have to call it kWordBeginAndEndPhone.
   };
Constructor & Destructor Documentation
WordBoundaryInfo() [1/3]
WordBoundaryInfo (const WordBoundaryInfoOpts & opts)
Definition at line 669 of file word-align-lattice.cc.
References WordBoundaryInfoOpts::partial_word_label, WordBoundaryInfoOpts::reorder, WordBoundaryInfoOpts::silence_has_olabels, WordBoundaryInfoOpts::silence_label, WordBoundaryInfoOpts::silence_phones, WordBoundaryInfoOpts::wbegin_and_end_phones, WordBoundaryInfoOpts::wbegin_phones, WordBoundaryInfoOpts::wend_phones, and WordBoundaryInfoOpts::winternal_phones.
{
   SetOptions(opts.wbegin_phones, kWordBeginPhone);
   SetOptions(opts.wend_phones, kWordEndPhone);
   SetOptions(opts.wbegin_and_end_phones, kWordBeginAndEndPhone);
   SetOptions(opts.winternal_phones, kWordInternalPhone);
   SetOptions(opts.silence_phones, (opts.silence_has_olabels ?
                                    kWordBeginAndEndPhone : kNonWordPhone));
   reorder = opts.reorder;
   silence_label = opts.silence_label;
   partial_word_label = opts.partial_word_label;
 }
WordBoundaryInfo() [2/3]
WordBoundaryInfo (const WordBoundaryInfoNewOpts & opts)
Definition at line 681 of file word-align-lattice.cc.
References WordBoundaryInfoNewOpts::partial_word_label, WordBoundaryInfoNewOpts::reorder, and WordBoundaryInfoNewOpts::silence_label.
{
   reorder = opts.reorder;
   silence_label = opts.silence_label;
   partial_word_label = opts.partial_word_label;
 }
WordBoundaryInfo() [3/3]
WordBoundaryInfo (const WordBoundaryInfoNewOpts & opts, std::string word_boundary_file)
Definition at line 687 of file word-align-lattice.cc.
References KALDI_ASSERT, WordBoundaryInfoNewOpts::partial_word_label, WordBoundaryInfoNewOpts::reorder, WordBoundaryInfoNewOpts::silence_label, and Input::Stream().
{
   reorder = opts.reorder;
   silence_label = opts.silence_label;
   partial_word_label = opts.partial_word_label;
   bool binary_in;
   Input ki(word_boundary_file, &binary_in);
   KALDI_ASSERT(!binary_in && "Not expecting binary word-boundary file.");
   Init(ki.Stream());
 }
Member Function Documentation
Init()
void Init (std::istream & stream)
Definition at line 698 of file word-align-lattice.cc.
References kaldi::ConvertStringToInteger(), KALDI_ASSERT, KALDI_ERR, and kaldi::SplitStringToVector().
{
   std::string line;
   while (std::getline(stream, line)) {
     std::vector<std::string> split_line;
     SplitStringToVector(line, " \t\r", true, &split_line);// split the line by space or tab
     int32 p = 0;
     if (split_line.size() != 2 ||
         !ConvertStringToInteger(split_line[0], &p))
       KALDI_ERR << "Invalid line in word-boundary file: " << line;
     KALDI_ASSERT(p > 0);
     if (phone_to_type.size() <= static_cast<size_t>(p))
       phone_to_type.resize(p+1, kNoPhone);
     std::string t = split_line[1];
     if (t == "nonword") phone_to_type[p] = kNonWordPhone;
     else if (t == "begin") phone_to_type[p] = kWordBeginPhone;
     else if (t == "singleton") phone_to_type[p] = kWordBeginAndEndPhone;
     else if (t == "end") phone_to_type[p] = kWordEndPhone;
     else if (t == "internal") phone_to_type[p] = kWordInternalPhone;
     else
       KALDI_ERR << "Invalid line in word-boundary file: " << line;
   }
   if (phone_to_type.empty())
     KALDI_ERR << "Empty word-boundary file";
 }
SetOptions()
void SetOptions (const std::string int_list, PhoneType phone_type) private
Definition at line 650 of file word-align-lattice.cc.
References rnnlm::i, KALDI_ASSERT, KALDI_ERR, and kaldi::SplitStringToIntegers().
{
   KALDI_ASSERT(!int_list.empty() && phone_type != kNoPhone);
   std::vector<int32> phone_list;
   if (!kaldi::SplitStringToIntegers(int_list, ":",
                                     false,
                                     &phone_list)
       || phone_list.empty())
     KALDI_ERR << "Invalid argument to --*-phones option: " << int_list;
   for (size_t i= 0; i < phone_list.size(); i++) {
     if (phone_to_type.size() <= phone_list[i])
       phone_to_type.resize(phone_list[i]+1, kNoPhone);
     if (phone_to_type[phone_list[i]] != kNoPhone)
       KALDI_ERR << "Phone " << phone_list[i] << "was given two incompatible "
           "assignments.";
     phone_to_type[phone_list[i]] = phone_type;
   }
 }
TypeOfPhone()
PhoneType TypeOfPhone (int32 p) const inline
Definition at line 147 of file word-align-lattice.h.
References KALDI_ERR.
Referenced by kaldi::IsPlausibleWord(), LatticeWordAligner::ComputationState::OutputArcForce(), LatticeWordAligner::ComputationState::OutputNormalWordArc(), LatticeWordAligner::ComputationState::OutputOnePhoneWordArc(), LatticeWordAligner::ComputationState::OutputSilenceArc(), WordAlignedLatticeTester::TestArcNormalWord(), WordAlignedLatticeTester::TestArcOnePhoneWord(), and WordAlignedLatticeTester::TestArcSilence().
{
     if ((p < 0 || p > phone_to_type.size()))
       KALDI_ERR << "Phone " << p << " was not specified in "
           "word-boundary file (or options)";
     return phone_to_type[p];
   }
Member Data Documentation
partial_word_label
int32 partial_word_label
Definition at line 158 of file word-align-lattice.h.
Referenced by LatticeWordAligner::LatticeWordAligner(), LatticeWordAligner::ComputationState::OutputArcForce(), LatticeWordAligner::RemoveEpsilonsFromLattice(), and WordAlignedLatticeTester::TestArcPartialWord().
phone_to_type
std::vector<PhoneType> phone_to_type
Definition at line 154 of file word-align-lattice.h.
reorder
bool reorder
Definition at line 162 of file word-align-lattice.h.
Referenced by kaldi::IsPlausibleWord(), LatticeWordAligner::ComputationState::OutputArcForce(), LatticeWordAligner::ComputationState::OutputNormalWordArc(), LatticeWordAligner::ComputationState::OutputOnePhoneWordArc(), LatticeWordAligner::ComputationState::OutputSilenceArc(), WordAlignedLatticeTester::TestArcNormalWord(), WordAlignedLatticeTester::TestArcOnePhoneWord(), and WordAlignedLatticeTester::TestArcSilence().
silence_label
int32 silence_label
Definition at line 156 of file word-align-lattice.h.
Referenced by LatticeWordAligner::LatticeWordAligner(), LatticeWordAligner::ComputationState::OutputArcForce(), LatticeWordAligner::ComputationState::OutputSilenceArc(), LatticeWordAligner::RemoveEpsilonsFromLattice(), WordAlignedLatticeTester::TestArcSilence(), and WordAlignedLatticeTester::TestEquivalent().
The documentation for this struct was generated from the following files:
lat/word-align-lattice.h
lat/word-align-lattice.cc