Kaldi: NnetComputeOptions Struct Reference
NnetComputeOptions Struct Reference
#include <nnet-compute.h>
Public Member Functions
NnetComputeOptions ()
void Register (OptionsItf *opts)
Public Attributes
bool debug
Detailed Description
Definition at line 39 of file nnet-compute.h.
Constructor & Destructor Documentation
NnetComputeOptions()
NnetComputeOptions () inline
Definition at line 41 of file nnet-compute.h.
 : debug(false) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 42 of file nnet-compute.h.
References OptionsItf::Register().
Referenced by NnetTrainerOptions::Register(), NnetSimpleLoopedComputationOptions::Register(), NnetSimpleComputationOptions::Register(), and NnetComputeProbOptions::Register().
{
     opts->Register("debug", &debug, "If true, turn on "
                    "debug for the neural net computation (very verbose!) "
                    "Will be turned on regardless if --verbose >= 5");
   }
Member Data Documentation
debug
bool debug
Definition at line 40 of file nnet-compute.h.
Referenced by NnetLdaStatsAccumulator::AccStats(), NnetComputerFromEg::Compute(), NnetComputer::Init(), kaldi::nnet3::UnitTestNnetCompute(), kaldi::nnet3::UnitTestNnetInputDerivatives(), kaldi::nnet3::UnitTestNnetModelDerivatives(), and kaldi::nnet3::UnitTestNnetOptimizeWithOptions().
The documentation for this struct was generated from the following file:
nnet3/nnet-compute.h