Kaldi: RefineClustersOptions Struct Reference
RefineClustersOptions Struct Reference
Classes and functions related to clustering » Algorithms for clustering
#include <cluster-utils.h>
Public Member Functions
RefineClustersOptions ()
RefineClustersOptions (int32 num_iters_in, int32 top_n_in)
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
Public Attributes
int32 num_iters
int32 top_n
Detailed Description
Definition at line 129 of file cluster-utils.h.
Constructor & Destructor Documentation
RefineClustersOptions() [1/2]
RefineClustersOptions () inline
Definition at line 132 of file cluster-utils.h.
Referenced by RefineClustersOptions::RefineClustersOptions().
 : num_iters(100), top_n(5) {}
RefineClustersOptions() [2/2]
RefineClustersOptions (int32 num_iters_in, int32 top_n_in) inline
Definition at line 133 of file cluster-utils.h.
References RefineClustersOptions::Read(), kaldi::RefineClusters(), RefineClustersOptions::RefineClustersOptions(), and RefineClustersOptions::Write().
       : num_iters(num_iters_in), top_n(top_n_in) {}
Member Function Documentation
Read()
void Read (std::istream & is, bool binary)
Definition at line 1283 of file cluster-utils.cc.
References kaldi::ExpectToken(), and kaldi::ReadBasicType().
Referenced by QuestionsForKey::Read(), and RefineClustersOptions::RefineClustersOptions().
{
   ExpectToken(is, binary, "<RefineClustersOptions>");
   ReadBasicType(is, binary, &num_iters);
   ReadBasicType(is, binary, &top_n);
   ExpectToken(is, binary, "</RefineClustersOptions>");
 }
Write()
void Write (std::ostream & os, bool binary) const
Definition at line 1276 of file cluster-utils.cc.
References kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by RefineClustersOptions::RefineClustersOptions(), and QuestionsForKey::Write().
{
   WriteToken(os, binary, "<RefineClustersOptions>");
   WriteBasicType(os, binary, num_iters);
   WriteBasicType(os, binary, top_n);
   WriteToken(os, binary, "</RefineClustersOptions>");
 }
Member Data Documentation
num_iters
int32 num_iters
Definition at line 130 of file cluster-utils.h.
Referenced by kaldi::FindBestSplitForKey(), Questions::InitRand(), kaldi::RefineClusters(), and kaldi::TestRefineClusters().
top_n
int32 top_n
Definition at line 131 of file cluster-utils.h.
Referenced by kaldi::TestRefineClusters().
The documentation for this struct was generated from the following files:
tree/cluster-utils.h
tree/cluster-utils.cc