Kaldi: LatticeFasterOnlineDecoderTpl< FST >::BestPathIterator Struct Reference
LatticeFasterOnlineDecoderTpl< FST >::BestPathIterator Struct Reference
#include <lattice-faster-online-decoder.h>
Public Member Functions
BestPathIterator (void *t, int32 f)
bool Done ()
Public Attributes
void * tok
int32 frame
Detailed Description
template<typename FST>
struct kaldi::LatticeFasterOnlineDecoderTpl< FST >::BestPathIterator
Definition at line 78 of file lattice-faster-online-decoder.h.
Constructor & Destructor Documentation
BestPathIterator()
BestPathIterator (void * t, int32 f) inline
Definition at line 86 of file lattice-faster-online-decoder.h.
 : tok(t), frame(f) { }
Member Function Documentation
Done()
bool Done () inline
Definition at line 87 of file lattice-faster-online-decoder.h.
References LatticeFasterOnlineDecoderTpl< FST >::BestPathEnd(), LatticeFasterOnlineDecoderTpl< FST >::GetBestPath(), LatticeFasterOnlineDecoderTpl< FST >::GetRawLatticePruned(), LatticeFasterOnlineDecoderTpl< FST >::KALDI_DISALLOW_COPY_AND_ASSIGN(), LatticeFasterOnlineDecoderTpl< FST >::TestGetBestPath(), and LatticeFasterOnlineDecoderTpl< FST >::TraceBackBestPath().
Referenced by LatticeFasterOnlineDecoderTpl< FST >::GetBestPath(), and LatticeFasterOnlineDecoderTpl< FST >::TraceBackBestPath().
 { return tok == NULL; }
Member Data Documentation
frame
int32 frame
Definition at line 80 of file lattice-faster-online-decoder.h.
Referenced by LatticeFasterOnlineDecoderTpl< FST >::TraceBackBestPath().
tok
void* tok
Definition at line 79 of file lattice-faster-online-decoder.h.
Referenced by LatticeFasterOnlineDecoderTpl< FST >::TraceBackBestPath().
The documentation for this struct was generated from the following file:
decoder/lattice-faster-online-decoder.h