Kaldi: NnetDiscriminativeSupervision Struct Reference
NnetDiscriminativeSupervision Struct Reference
#include <nnet-discriminative-example.h>
Public Member Functions
NnetDiscriminativeSupervision ()
NnetDiscriminativeSupervision (const std::string &name, const discriminative::DiscriminativeSupervision &supervision, const VectorBase< BaseFloat > &deriv_weights, int32 first_frame, int32 frame_skip)
NnetDiscriminativeSupervision (const NnetDiscriminativeSupervision &other)
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
void Swap (NnetDiscriminativeSupervision *other)
void CheckDim () const
bool operator== (const NnetDiscriminativeSupervision &other) const
Public Attributes
std::string name
std::vector< Index > indexes
discriminative::DiscriminativeSupervision supervision
Vector< BaseFloat > deriv_weights
Detailed Description
Definition at line 42 of file nnet-discriminative-example.h.
Constructor & Destructor Documentation
NnetDiscriminativeSupervision() [1/3]
NnetDiscriminativeSupervision () inline
Definition at line 74 of file nnet-discriminative-example.h.
References NnetDiscriminativeSupervision::CheckDim(), NnetDiscriminativeSupervision::operator==(), NnetDiscriminativeSupervision::Read(), NnetDiscriminativeSupervision::Swap(), and NnetDiscriminativeSupervision::Write().
 { }
NnetDiscriminativeSupervision() [2/3]
NnetDiscriminativeSupervision (const std::string & name, const discriminative::DiscriminativeSupervision & supervision, const VectorBase< BaseFloat > & deriv_weights, int32 first_frame, int32 frame_skip)
Definition at line 91 of file nnet-discriminative-example.cc.
References NnetDiscriminativeSupervision::CheckDim(), DiscriminativeSupervision::frames_per_sequence, rnnlm::i, NnetDiscriminativeSupervision::indexes, rnnlm::j, KALDI_ASSERT, and DiscriminativeSupervision::num_sequences.
                      :
     name(name),
     supervision(supervision),
     deriv_weights(deriv_weights) {
   // note: this will set the 'x' index to zero.
   indexes.resize(supervision.num_sequences *
                  supervision.frames_per_sequence);
   int32 k = 0, num_sequences = supervision.num_sequences,
       frames_per_sequence = supervision.frames_per_sequence;
   for (int32 i = 0; i < frames_per_sequence; i++) {
     for (int32 j = 0; j < num_sequences; j++,k++) {
       indexes[k].n = j;
       indexes[k].t = i * frame_skip + first_frame;
     }
   }
   KALDI_ASSERT(k == indexes.size());
   CheckDim();
 }
NnetDiscriminativeSupervision() [3/3]
NnetDiscriminativeSupervision (const NnetDiscriminativeSupervision & other)
Definition at line 85 of file nnet-discriminative-example.cc.
References NnetDiscriminativeSupervision::CheckDim().
                                                                                                       :
     name(other.name),
     indexes(other.indexes),
     supervision(other.supervision),
     deriv_weights(other.deriv_weights) { CheckDim(); }
Member Function Documentation
CheckDim()
void CheckDim () const
Definition at line 57 of file nnet-discriminative-example.cc.
References NnetDiscriminativeSupervision::deriv_weights, DiscriminativeSupervision::frames_per_sequence, rnnlm::i, NnetDiscriminativeSupervision::indexes, rnnlm::j, KALDI_ASSERT, rnnlm::n, DiscriminativeSupervision::num_sequences, and NnetDiscriminativeSupervision::supervision.
Referenced by kaldi::nnet3::MergeSupervision(), NnetDiscriminativeSupervision::NnetDiscriminativeSupervision(), NnetDiscriminativeSupervision::Read(), NnetDiscriminativeSupervision::Swap(), and NnetDiscriminativeSupervision::Write().
{
   if (supervision.frames_per_sequence == -1) {
     // this object has not been set up.
     KALDI_ASSERT(indexes.empty());
     return;
   }
   KALDI_ASSERT(indexes.size() == supervision.num_sequences *
                supervision.frames_per_sequence && !indexes.empty() &&
                supervision.frames_per_sequence > 1);
   int32 first_frame = indexes[0].t,
       frame_skip = indexes[supervision.num_sequences].t - first_frame,
       num_sequences = supervision.num_sequences,
       frames_per_sequence = supervision.frames_per_sequence;
   int32 k = 0;
   for (int32 i = 0; i < frames_per_sequence; i++) {
     for (int32 j = 0; j < num_sequences; j++,k++) {
       int32 n = j, t = i * frame_skip + first_frame, x = 0;
       Index index(n, t, x);
       KALDI_ASSERT(indexes[k] == index);
     }
   }
   if (deriv_weights.Dim() != 0) {
     KALDI_ASSERT(deriv_weights.Dim() == indexes.size());
     KALDI_ASSERT(deriv_weights.Min() >= 0.0 &&
                  deriv_weights.Max() <= 1.0);
   }
 }
operator==()
bool operator== (const NnetDiscriminativeSupervision & other) const
Definition at line 39 of file nnet-discriminative-example.cc.
References NnetDiscriminativeSupervision::deriv_weights, NnetDiscriminativeSupervision::indexes, NnetDiscriminativeSupervision::name, and NnetDiscriminativeSupervision::supervision.
Referenced by NnetDiscriminativeSupervision::NnetDiscriminativeSupervision().
{
   return name == other.name && indexes == other.indexes &&
       supervision == other.supervision &&
       deriv_weights.ApproxEqual(other.deriv_weights);
 }
Read()
void Read (std::istream & is, bool binary)
Definition at line 45 of file nnet-discriminative-example.cc.
References NnetDiscriminativeSupervision::CheckDim(), NnetDiscriminativeSupervision::deriv_weights, kaldi::nnet3::ExpectToken(), NnetDiscriminativeSupervision::indexes, NnetDiscriminativeSupervision::name, DiscriminativeSupervision::Read(), kaldi::nnet3::ReadIndexVector(), kaldi::ReadToken(), kaldi::nnet3::ReadVectorAsChar(), and NnetDiscriminativeSupervision::supervision.
Referenced by NnetDiscriminativeSupervision::NnetDiscriminativeSupervision(), and NnetDiscriminativeExample::Read().
{
   ExpectToken(is, binary, "<NnetDiscriminativeSup>");
   ReadToken(is, binary, &name);
   ReadIndexVector(is, binary, &indexes);
   supervision.Read(is, binary);
   ExpectToken(is, binary, "<DW>");
   ReadVectorAsChar(is, binary, &deriv_weights);
   ExpectToken(is, binary, "</NnetDiscriminativeSup>");
   CheckDim();
 }
Swap()
void Swap (NnetDiscriminativeSupervision * other)
Definition at line 115 of file nnet-discriminative-example.cc.
References NnetDiscriminativeSupervision::CheckDim(), NnetDiscriminativeSupervision::deriv_weights, NnetDiscriminativeSupervision::indexes, NnetDiscriminativeSupervision::name, kaldi::RandInt(), NnetDiscriminativeSupervision::supervision, and DiscriminativeSupervision::Swap().
Referenced by NnetDiscriminativeSupervision::NnetDiscriminativeSupervision().
{
   name.swap(other->name);
   indexes.swap(other->indexes);
   supervision.Swap(&(other->supervision));
   deriv_weights.Swap(&(other->deriv_weights));
   if (RandInt(0, 5) == 0)
     CheckDim();
 }
Write()
void Write (std::ostream & os, bool binary) const
Definition at line 28 of file nnet-discriminative-example.cc.
References NnetDiscriminativeSupervision::CheckDim(), NnetDiscriminativeSupervision::deriv_weights, NnetDiscriminativeSupervision::indexes, NnetDiscriminativeSupervision::name, NnetDiscriminativeSupervision::supervision, DiscriminativeSupervision::Write(), kaldi::nnet3::WriteIndexVector(), kaldi::WriteToken(), and kaldi::nnet3::WriteVectorAsChar().
Referenced by NnetDiscriminativeSupervision::NnetDiscriminativeSupervision().
{
   CheckDim();
   WriteToken(os, binary, "<NnetDiscriminativeSup>");
   WriteToken(os, binary, name);
   WriteIndexVector(os, binary, indexes);
   supervision.Write(os, binary);
   WriteToken(os, binary, "<DW>");  // for DerivWeights.  Want to save space.
   WriteVectorAsChar(os, binary, deriv_weights);
   WriteToken(os, binary, "</NnetDiscriminativeSup>");
 }
Member Data Documentation
deriv_weights
Vector<BaseFloat> deriv_weights
Definition at line 71 of file nnet-discriminative-example.h.
Referenced by NnetDiscriminativeSupervision::CheckDim(), kaldi::nnet3::MergeSupervision(), NnetDiscriminativeSupervision::operator==(), NnetDiscriminativeTrainer::ProcessOutputs(), NnetDiscriminativeSupervision::Read(), NnetDiscriminativeSupervision::Swap(), and NnetDiscriminativeSupervision::Write().
indexes
std::vector<Index> indexes
Definition at line 54 of file nnet-discriminative-example.h.
Referenced by NnetDiscriminativeSupervision::CheckDim(), kaldi::nnet3::GetDiscriminativeComputationRequest(), kaldi::nnet3::MergeSupervision(), NnetDiscriminativeSupervision::NnetDiscriminativeSupervision(), NnetDiscriminativeExampleStructureHasher::operator()(), NnetDiscriminativeSupervision::operator==(), NnetDiscriminativeSupervision::Read(), NnetDiscriminativeSupervision::Swap(), and NnetDiscriminativeSupervision::Write().
name
std::string name
Definition at line 45 of file nnet-discriminative-example.h.
Referenced by kaldi::nnet3::GetDiscriminativeComputationRequest(), kaldi::nnet3::MergeSupervision(), NnetDiscriminativeExampleStructureHasher::operator()(), NnetDiscriminativeSupervision::operator==(), NnetDiscriminativeComputeObjf::ProcessOutputs(), NnetDiscriminativeTrainer::ProcessOutputs(), NnetDiscriminativeSupervision::Read(), NnetDiscriminativeSupervision::Swap(), and NnetDiscriminativeSupervision::Write().
supervision
discriminative::DiscriminativeSupervision supervision
Definition at line 58 of file nnet-discriminative-example.h.
Referenced by NnetDiscriminativeSupervision::CheckDim(), kaldi::nnet3::MergeSupervision(), NnetDiscriminativeSupervision::operator==(), NnetDiscriminativeComputeObjf::ProcessOutputs(), NnetDiscriminativeTrainer::ProcessOutputs(), NnetDiscriminativeSupervision::Read(), NnetDiscriminativeSupervision::Swap(), and NnetDiscriminativeSupervision::Write().
The documentation for this struct was generated from the following files:
nnet3/nnet-discriminative-example.h
nnet3/nnet-discriminative-example.cc