Kaldi: Sgmm2PerFrameDerivedVars Struct Reference
Sgmm2PerFrameDerivedVars Struct Reference
Holds the per-frame precomputed quantities x(t), x_{i}(t), z_{i}(t), and n_{i}(t) (cf.
#include <am-sgmm2.h>
Public Member Functions
void Resize (int32 ngauss, int32 feat_dim, int32 phn_dim)
Public Attributes
std::vector< int32 > gselect
Vector< BaseFloat > xt
x'(t), FMLLR-adapted, dim = [D], eq.(33)
Matrix< BaseFloat > xti
x_{i}(t) = x'(t) - o_i(s): dim = [I][D], eq.(34)
Matrix< BaseFloat > zti
z_{i}(t), dim = [I][S], eq.(35)
Vector< BaseFloat > nti
n_{i}(t), dim = [I], eq.
Detailed Description
Holds the per-frame precomputed quantities x(t), x_{i}(t), z_{i}(t), and n_{i}(t) (cf.
Eq. (33)-(36)) for the SGMM, as well as the cached Gaussian selection records.
Definition at line 142 of file am-sgmm2.h.
Member Function Documentation
Resize()
void Resize (int32 ngauss, int32 feat_dim, int32 phn_dim) inline
Definition at line 151 of file am-sgmm2.h.
References VectorBase< Real >::Dim(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), Vector< Real >::Resize(), and Matrix< Real >::Resize().
Referenced by AmSgmm2::ComputePerFrameVars(), TestSgmm2AccsIO(), TestSgmm2FmllrAccsIO(), TestSgmm2FmllrSubspace(), TestSgmm2Init(), and TestSgmm2IO().
                                                            { // resizes but does
     // not necessarily zero things.
     if (xt.Dim() != feat_dim) xt.Resize(feat_dim);
     if (xti.NumRows() != ngauss || xti.NumCols() != feat_dim)
       xti.Resize(ngauss, feat_dim);
     if (zti.NumRows() != ngauss || zti.NumCols() != phn_dim)
       zti.Resize(ngauss, phn_dim);
     if (nti.Dim() != ngauss)
       nti.Resize(ngauss);
   }
Member Data Documentation
gselect
std::vector<int32> gselect
Definition at line 143 of file am-sgmm2.h.
Referenced by FmllrSgmm2Accs::Accumulate(), MleAmSgmm2Accs::AccumulateFromPosteriors(), MleSgmm2SpeakerAccs::AccumulateFromPosteriors(), AmSgmm2::ComponentLogLikes(), and AmSgmm2::ComputePerFrameVars().
nti
Vector<BaseFloat> nti
n_{i}(t), dim = [I], eq.
(36) in CSL paper, but [SSGMM] with extra term log b_i^{(s)}, see eq. (24) of techreport.
Definition at line 147 of file am-sgmm2.h.
Referenced by AmSgmm2::ComponentLogLikes(), and AmSgmm2::ComputePerFrameVars().
xt
Vector<BaseFloat> xt
x'(t), FMLLR-adapted, dim = [D], eq.(33)
Definition at line 144 of file am-sgmm2.h.
Referenced by MleAmSgmm2Accs::AccumulateFromPosteriors(), MleSgmm2SpeakerAccs::AccumulateFromPosteriors(), and AmSgmm2::ComputePerFrameVars().
xti
Matrix<BaseFloat> xti
x_{i}(t) = x'(t) - o_i(s): dim = [I][D], eq.(34)
Definition at line 145 of file am-sgmm2.h.
Referenced by MleAmSgmm2Accs::AccumulateFromPosteriors(), and AmSgmm2::ComputePerFrameVars().
zti
Matrix<BaseFloat> zti
z_{i}(t), dim = [I][S], eq.(35)
Definition at line 146 of file am-sgmm2.h.
Referenced by MleAmSgmm2Accs::AccumulateFromPosteriors(), AmSgmm2::ComponentLogLikes(), and AmSgmm2::ComputePerFrameVars().
The documentation for this struct was generated from the following file:
sgmm2/am-sgmm2.h