Kaldi: NnetDiscriminativeExampleStructureCompare Struct Reference
NnetDiscriminativeExampleStructureCompare Struct Reference
This comparator object compares just the structural aspects of the NnetDiscriminativeExample without looking at the value of the features.
#include <nnet-discriminative-example.h>
Public Member Functions
bool operator() (const NnetDiscriminativeExample &a, const NnetDiscriminativeExample &b) const
bool operator() (const NnetDiscriminativeExample *a, const NnetDiscriminativeExample *b) const
Detailed Description
This comparator object compares just the structural aspects of the NnetDiscriminativeExample without looking at the value of the features.
Definition at line 147 of file nnet-discriminative-example.h.
Member Function Documentation
operator()() [1/2]
bool operator() (const NnetDiscriminativeExample & a, const NnetDiscriminativeExample & b) const
Definition at line 410 of file nnet-discriminative-example.cc.
References rnnlm::i, NnetDiscriminativeExample::inputs, and NnetDiscriminativeExample::outputs.
{
   NnetIoStructureCompare io_compare;
   if (a.inputs.size() != b.inputs.size() ||
       a.outputs.size() != b.outputs.size())
     return false;
   size_t size = a.inputs.size();
   for (size_t i = 0; i < size; i++)
     if (!io_compare(a.inputs[i], b.inputs[i]))
       return false;
   size = a.outputs.size();
   for (size_t i = 0; i < size; i++)
     if (a.outputs[i].name != b.outputs[i].name ||
         a.outputs[i].indexes != b.outputs[i].indexes)
       return false;
   return true;
 }
operator()() [2/2]
bool operator() (const NnetDiscriminativeExample * a, const NnetDiscriminativeExample * b) const inline
Definition at line 151 of file nnet-discriminative-example.h.
References kaldi::nnet3::GetDiscriminativeComputationRequest(), kaldi::nnet3::MergeDiscriminativeExamples(), kaldi::nnet3::MergeSupervision(), and kaldi::nnet3::ShiftDiscriminativeExampleTimes().
{
     return (*this)(*a, *b);
   }
The documentation for this struct was generated from the following files:
nnet3/nnet-discriminative-example.h
nnet3/nnet-discriminative-example.cc