Kaldi: DiscriminativeObjectiveInfo Struct Reference
DiscriminativeObjectiveInfo Struct Reference
#include <discriminative-training.h>
Public Member Functions
void Print (const std::string &criterion, bool print_avg_gradients=false, bool print_avg_output=false) const
void PrintAll (const std::string &criterion) const
void PrintAvgGradientForPdf (int32 pdf_id) const
void Add (const DiscriminativeObjectiveInfo &other)
double TotalObjf (const std::string &criterion) const
bool AccumulateGradients () const
bool AccumulateOutput () const
DiscriminativeObjectiveInfo ()
DiscriminativeObjectiveInfo (int32 num_pdfs)
DiscriminativeObjectiveInfo (const DiscriminativeOptions &opts)
void Reset ()
void Configure (const DiscriminativeOptions &opts)
Public Attributes
double tot_t
double tot_t_weighted
double tot_objf
double tot_num_count
double tot_den_count
double tot_num_objf
double tot_l2_term
bool accumulate_gradients
bool accumulate_output
int32 num_pdfs
CuVector< double > gradients
CuVector< double > output
Detailed Description
Definition at line 130 of file discriminative-training.h.
Constructor & Destructor Documentation
DiscriminativeObjectiveInfo() [1/3]
DiscriminativeObjectiveInfo ()
Definition at line 28 of file discriminative-training.cc.
{
   std::memset(this, 0, sizeof(*this));
 }
DiscriminativeObjectiveInfo() [2/3]
DiscriminativeObjectiveInfo (int32 num_pdfs)
Definition at line 32 of file discriminative-training.cc.
References DiscriminativeObjectiveInfo::gradients, DiscriminativeObjectiveInfo::output, DiscriminativeObjectiveInfo::Reset(), and CuVector< Real >::Resize().
                                                                        :
   accumulate_gradients(false),
   accumulate_output(false),
   num_pdfs(num_pdfs) {
   gradients.Resize(num_pdfs);
   output.Resize(num_pdfs);
   Reset();
 }
DiscriminativeObjectiveInfo() [3/3]
DiscriminativeObjectiveInfo (const DiscriminativeOptions & opts)
Definition at line 42 of file discriminative-training.cc.
References DiscriminativeObjectiveInfo::gradients, DiscriminativeOptions::num_pdfs, DiscriminativeObjectiveInfo::output, DiscriminativeObjectiveInfo::Reset(), and CuVector< Real >::Resize().
                                        :
   accumulate_gradients(opts.accumulate_gradients),
   accumulate_output(opts.accumulate_output),
   num_pdfs(opts.num_pdfs) {
   gradients.Resize(opts.num_pdfs);
   output.Resize(opts.num_pdfs);
   Reset();
 }
Member Function Documentation
AccumulateGradients()
bool AccumulateGradients () const inline
Definition at line 188 of file discriminative-training.h.
References CuVectorBase< Real >::Dim().
Referenced by DiscriminativeComputation::Compute().
{
     return accumulate_gradients && gradients.Dim() > 0;
   }
AccumulateOutput()
bool AccumulateOutput () const inline
Definition at line 195 of file discriminative-training.h.
References kaldi::discriminative::ComputeDiscriminativeObjfAndDeriv(), and CuVectorBase< Real >::Dim().
Referenced by DiscriminativeComputation::Compute().
{
     return accumulate_output && output.Dim() > 0;
   }
Add()
void Add (const DiscriminativeObjectiveInfo & other)
Definition at line 560 of file discriminative-training.cc.
References DiscriminativeObjectiveInfo::gradients, DiscriminativeObjectiveInfo::output, DiscriminativeObjectiveInfo::tot_den_count, DiscriminativeObjectiveInfo::tot_l2_term, DiscriminativeObjectiveInfo::tot_num_count, DiscriminativeObjectiveInfo::tot_num_objf, DiscriminativeObjectiveInfo::tot_objf, DiscriminativeObjectiveInfo::tot_t, and DiscriminativeObjectiveInfo::tot_t_weighted.
Referenced by DiscriminativeComputation::Compute().
{
   tot_t += other.tot_t;
   tot_t_weighted += other.tot_t_weighted;
   tot_objf += other.tot_objf;             // Actually tot_den_objf for mmi
   tot_num_count += other.tot_num_count;
   tot_den_count += other.tot_den_count;
   tot_num_objf += other.tot_num_objf;     // Only for mmi
   tot_l2_term += other.tot_l2_term;
   if (AccumulateGradients()) {
     gradients.AddVec(1.0, other.gradients);
   }
   if (AccumulateOutput()) {
     output.AddVec(1.0, other.output);
   }
 }
Configure()
void Configure (const DiscriminativeOptions & opts)
Definition at line 66 of file discriminative-training.cc.
References DiscriminativeOptions::accumulate_gradients, DiscriminativeObjectiveInfo::accumulate_gradients, DiscriminativeOptions::accumulate_output, DiscriminativeObjectiveInfo::accumulate_output, DiscriminativeObjectiveInfo::gradients, DiscriminativeOptions::num_pdfs, DiscriminativeObjectiveInfo::num_pdfs, DiscriminativeObjectiveInfo::output, and CuVector< Real >::Resize().
{
   accumulate_gradients = opts.accumulate_gradients;
   accumulate_output = opts.accumulate_output;
   num_pdfs = opts.num_pdfs;
   gradients.Resize(opts.num_pdfs);
   output.Resize(opts.num_pdfs);
 }
Print()
void Print (const std::string & criterion, bool print_avg_gradients = false, bool print_avg_output = false) const
Definition at line 577 of file discriminative-training.cc.
References KALDI_LOG, KALDI_VLOG, and VectorBase< Real >::Scale().
Referenced by DiscriminativeComputation::Compute().
{
   if (criterion == "mmi") {
     double num_objf = tot_num_objf / tot_t_weighted,
            den_objf = tot_objf / tot_t_weighted;
     double objf = num_objf - den_objf;
     double avg_post_per_frame = tot_num_count / tot_t_weighted;
     KALDI_LOG << "Number of frames is " << tot_t
               << " (weighted: " << tot_t_weighted
               << "), average (num or den) posterior per frame is "
               << avg_post_per_frame;
     KALDI_LOG << "MMI objective function is " << num_objf << " - "
               << den_objf << " = " << objf << " per frame, over "
               << tot_t_weighted << " frames.";
   } else if (criterion == "mpfe") {
     double avg_gradients = (tot_num_count + tot_den_count) / tot_t_weighted;
     double objf = tot_objf / tot_t_weighted;
     KALDI_LOG << "Average num+den count of MPFE stats is " << avg_gradients
               << " per frame, over "
               << tot_t_weighted << " frames";
     KALDI_LOG << "MPFE objective function is " << objf
               << " per frame, over " << tot_t_weighted << " frames.";
   } else if (criterion == "smbr") {
     double avg_gradients = (tot_num_count + tot_den_count) / tot_t_weighted;
     double objf = tot_objf / tot_t_weighted;
     KALDI_LOG << "Average num+den count of SMBR stats is " << avg_gradients
               << " per frame, over "
               << tot_t_weighted << " frames";
     KALDI_LOG << "SMBR objective function is " << objf
               << " per frame, over " << tot_t_weighted << " frames.";
   }
   if (AccumulateGradients()) {
     Vector<double> temp(gradients);
     temp.Scale(1.0/tot_t_weighted);
     if (print_avg_gradients) {
       KALDI_LOG << "Vector of average gradients wrt output activations is: \n" << temp;
     } else {
       KALDI_VLOG(4) << "Vector of average gradients wrt output activations is: \n" << temp;
     }
   }
   if (AccumulateOutput()) {
     Vector<double> temp(output);
     temp.Scale(1.0/tot_t_weighted);
     if (print_avg_output) {
       KALDI_LOG << "Average DNN output is: \n" << temp;
     } else {
       KALDI_VLOG(4) << "Average DNN output is: \n" << temp;
     }
   }
 }
PrintAll()
void PrintAll (const std::string & criterion) const inline
Definition at line 169 of file discriminative-training.h.
References fst::Print().
Referenced by DiscriminativeComputation::Compute(), and NnetDiscriminativeComputeObjf::PrintTotalStats().
{
     Print(criterion, true, true);
   }
PrintAvgGradientForPdf()
void PrintAvgGradientForPdf (int32 pdf_id) const
Definition at line 632 of file discriminative-training.cc.
References KALDI_LOG.
{
   if (pdf_id < gradients.Dim() && pdf_id >= 0) {
     KALDI_LOG << "Average gradient wrt output activations of pdf " << pdf_id
               << " is " << gradients(pdf_id) / tot_t_weighted
               << " per frame, over "
               << tot_t_weighted << " frames";
   }
 }
Reset()
void Reset ()
Definition at line 53 of file discriminative-training.cc.
References DiscriminativeObjectiveInfo::gradients, DiscriminativeObjectiveInfo::output, CuVectorBase< Real >::SetZero(), DiscriminativeObjectiveInfo::tot_den_count, DiscriminativeObjectiveInfo::tot_l2_term, DiscriminativeObjectiveInfo::tot_num_count, DiscriminativeObjectiveInfo::tot_num_objf, DiscriminativeObjectiveInfo::tot_objf, DiscriminativeObjectiveInfo::tot_t, and DiscriminativeObjectiveInfo::tot_t_weighted.
Referenced by DiscriminativeComputation::Compute(), and DiscriminativeObjectiveInfo::DiscriminativeObjectiveInfo().
{
   gradients.SetZero();
   output.SetZero();
   tot_t = 0.0;
   tot_t_weighted = 0.0;
   tot_objf = 0.0;
   tot_num_count = 0.0;
   tot_den_count = 0.0;
   tot_num_objf = 0.0;
   tot_l2_term = 0.0;
 }
TotalObjf()
double TotalObjf (const std::string & criterion) const inline
Definition at line 180 of file discriminative-training.h.
Referenced by DiscriminativeComputation::Compute(), and NnetDiscriminativeComputeObjf::PrintTotalStats().
{
     if (criterion == "mmi") return (tot_num_objf - tot_objf);
     return tot_objf;
   }
Member Data Documentation
accumulate_gradients
bool accumulate_gradients
Definition at line 148 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Configure().
accumulate_output
bool accumulate_output
Definition at line 151 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Configure().
gradients
CuVector<double> gradients
Definition at line 159 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Add(), DiscriminativeComputation::Compute(), DiscriminativeObjectiveInfo::Configure(), DiscriminativeObjectiveInfo::DiscriminativeObjectiveInfo(), and DiscriminativeObjectiveInfo::Reset().
num_pdfs
int32 num_pdfs
Definition at line 155 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Configure().
output
CuVector<double> output
Definition at line 161 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Add(), DiscriminativeComputation::Compute(), DiscriminativeObjectiveInfo::Configure(), DiscriminativeObjectiveInfo::DiscriminativeObjectiveInfo(), and DiscriminativeObjectiveInfo::Reset().
tot_den_count
double tot_den_count
Definition at line 136 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Add(), DiscriminativeComputation::Compute(), and DiscriminativeObjectiveInfo::Reset().
tot_l2_term
double tot_l2_term
Definition at line 140 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Add(), DiscriminativeComputation::Compute(), NnetDiscriminativeComputeObjf::PrintTotalStats(), and DiscriminativeObjectiveInfo::Reset().
tot_num_count
double tot_num_count
Definition at line 135 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Add(), DiscriminativeComputation::Compute(), and DiscriminativeObjectiveInfo::Reset().
tot_num_objf
double tot_num_objf
Definition at line 137 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Add(), DiscriminativeComputation::Compute(), and DiscriminativeObjectiveInfo::Reset().
tot_objf
double tot_objf
Definition at line 133 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Add(), DiscriminativeComputation::Compute(), NnetDiscriminativeComputeObjf::ProcessOutputs(), NnetDiscriminativeTrainer::ProcessOutputs(), and DiscriminativeObjectiveInfo::Reset().
tot_t
double tot_t
Definition at line 131 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Add(), DiscriminativeComputation::Compute(), and DiscriminativeObjectiveInfo::Reset().
tot_t_weighted
double tot_t_weighted
Definition at line 132 of file discriminative-training.h.
Referenced by DiscriminativeObjectiveInfo::Add(), DiscriminativeComputation::Compute(), NnetDiscriminativeComputeObjf::PrintTotalStats(), NnetDiscriminativeComputeObjf::ProcessOutputs(), NnetDiscriminativeTrainer::ProcessOutputs(), and DiscriminativeObjectiveInfo::Reset().
The documentation for this struct was generated from the following files:
nnet3/discriminative-training.h
nnet3/discriminative-training.cc