Kaldi: WordAlignLatticeLexiconOpts Struct Reference
WordAlignLatticeLexiconOpts Struct Reference
#include <word-align-lattice-lexicon.h>
Public Member Functions
WordAlignLatticeLexiconOpts ()
void Register (OptionsItf *opts)
Public Attributes
int32 partial_word_label
bool reorder
bool test
bool allow_duplicate_paths
BaseFloat max_expand
Detailed Description
Definition at line 120 of file word-align-lattice-lexicon.h.
Constructor & Destructor Documentation
WordAlignLatticeLexiconOpts()
WordAlignLatticeLexiconOpts () inline
Definition at line 127 of file word-align-lattice-lexicon.h.
                                : partial_word_label(0), reorder(true),
                                  test(false), allow_duplicate_paths(false),
                                  max_expand(-1.0) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 131 of file word-align-lattice-lexicon.h.
References OptionsItf::Register(), kaldi::TestWordAlignedLatticeLexicon(), and kaldi::WordAlignLatticeLexicon().
Referenced by main().
{
     opts->Register("partial-word-label", &partial_word_label, "Numeric id of "
                    "word symbol that is to be used for arcs in the word-aligned "
                    "lattice corresponding to partial words at the end of "
                    "\"forced-out\" utterances (zero is OK)");
     opts->Register("reorder", &reorder, "True if the lattices were generated "
                    "from graphs that had the --reorder option true, relating to "
                    "reordering self-loops (typically true)");
     opts->Register("test", &test, "If true, testing code will be activated "
                    "(the purpose of this is to validate the algorithm).");
     opts->Register("allow-duplicate-paths", &allow_duplicate_paths, "Only "
                    "has an effect if --test=true.  If true, does not die "
                    "(only prints warnings) if duplicate paths are found. "
                    "This should only happen with very pathological lexicons, "
                    "e.g. as encountered in testing code.");
     opts->Register("max-expand", &max_expand, "If >0.0, the maximum ratio "
                    "by which we allow the lattice-alignment code to increase the #states"
                    "in a lattice (vs. the phone-aligned lattice) before we fail and "
                    "refuse to align the lattice.  This is helpful in order to "
                    "prevent 'pathological' lattices from causing the program to "
                    "exhaust memory.  Actual max-states is 1000 + max-expand * "
                    "orig-num-states.");
   }
Member Data Documentation
allow_duplicate_paths
bool allow_duplicate_paths
Definition at line 124 of file word-align-lattice-lexicon.h.
Referenced by kaldi::TestWordAlignLatticeLexicon(), and kaldi::WordAlignLatticeLexicon().
max_expand
BaseFloat max_expand
Definition at line 125 of file word-align-lattice-lexicon.h.
Referenced by kaldi::WordAlignLatticeLexicon().
partial_word_label
int32 partial_word_label
Definition at line 121 of file word-align-lattice-lexicon.h.
Referenced by kaldi::WordAlignLatticeLexicon().
reorder
bool reorder
Definition at line 122 of file word-align-lattice-lexicon.h.
Referenced by kaldi::TestWordAlignLatticeLexicon(), and kaldi::WordAlignLatticeLexicon().
test
bool test
Definition at line 123 of file word-align-lattice-lexicon.h.
Referenced by kaldi::TestWordAlignLatticeLexicon(), and kaldi::WordAlignLatticeLexicon().
The documentation for this struct was generated from the following file:
lat/word-align-lattice-lexicon.h