Kaldi: NnetCombineConfig Struct Reference
NnetCombineConfig Struct Reference
Configuration class that controls neural net combination, where we combine a number of neural nets, trying to find for each layer the optimal weighted combination of the different neural-net parameters.
#include <combine-nnet.h>
Public Member Functions
NnetCombineConfig ()
void Register (OptionsItf *opts)
Public Attributes
int32 initial_model
int32 num_bfgs_iters
BaseFloat initial_impr
bool test_gradient
Detailed Description
Configuration class that controls neural net combination, where we combine a number of neural nets, trying to find for each layer the optimal weighted combination of the different neural-net parameters.
Definition at line 35 of file combine-nnet.h.
Constructor & Destructor Documentation
NnetCombineConfig()
NnetCombineConfig () inline
Definition at line 46 of file combine-nnet.h.
                      : initial_model(-1), num_bfgs_iters(30),
                        initial_impr(0.01),
                        test_gradient(false) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 50 of file combine-nnet.h.
References kaldi::nnet2::CombineNnets(), and OptionsItf::Register().
Referenced by main().
{
     opts->Register("initial-model", &initial_model, "Specifies where to start the "
                    "optimization from.  If 0 ... #models-1, then specifies the model; "
                    "if #models, then the average of all inputs; otherwise, chosen "
                    "automatically from the previous options.");
     opts->Register("num-bfgs-iters", &num_bfgs_iters, "Maximum number of function "
                    "evaluations for BFGS to use when optimizing combination weights");
     opts->Register("initial-impr", &initial_impr, "Amount of objective-function change "
                    "we aim for on the first iteration.");
     opts->Register("test-gradient", &test_gradient, "If true, activate code that "
                    "tests the gradient is accurate.");
   }
Member Data Documentation
initial_impr
BaseFloat initial_impr
Definition at line 44 of file combine-nnet.h.
Referenced by kaldi::nnet2::CombineNnets().
initial_model
int32 initial_model
Definition at line 36 of file combine-nnet.h.
Referenced by kaldi::nnet2::GetInitialScaleParams().
num_bfgs_iters
int32 num_bfgs_iters
Definition at line 38 of file combine-nnet.h.
Referenced by kaldi::nnet2::CombineNnets().
test_gradient
bool test_gradient
Definition at line 45 of file combine-nnet.h.
Referenced by kaldi::nnet2::CombineNnets().
The documentation for this struct was generated from the following file:
nnet2/combine-nnet.h