Kaldi: PitchInterpolatorOptions Struct Reference
PitchInterpolatorOptions Struct Reference
Public Member Functions
PitchInterpolatorOptions ()
void Register (OptionsItf *opts)
void Check () const
Public Attributes
BaseFloat pitch_interval
BaseFloat interpolator_factor
BaseFloat max_voicing_prob
BaseFloat max_pitch_change_per_frame
Detailed Description
Definition at line 26 of file interpolate-pitch.cc.
Constructor & Destructor Documentation
PitchInterpolatorOptions()
PitchInterpolatorOptions () inline
Definition at line 34 of file interpolate-pitch.cc.
                             : pitch_interval(4.0),
                               interpolator_factor(1.0e-05),
                               max_voicing_prob(0.9),
                               max_pitch_change_per_frame(10.0) { }
Member Function Documentation
Check()
void Check () const inline
Definition at line 52 of file interpolate-pitch.cc.
References KALDI_ASSERT.
Referenced by PitchInterpolator::PitchInterpolator().
                      {
     KALDI_ASSERT(pitch_interval > 0.0 && pitch_interval < 20.0 &&
                  interpolator_factor > 0.0 && interpolator_factor < 1.0 &&
                  max_voicing_prob <= 1.0 && max_voicing_prob >= 0.5 &&
                  max_pitch_change_per_frame > 2.0 * pitch_interval);
   }
Register()
void Register (OptionsItf * opts) inline
Definition at line 38 of file interpolate-pitch.cc.
References OptionsItf::Register().
Referenced by main().
{
     opts->Register("pitch-interval", &pitch_interval, "Frequency interval in Hz, used "
                    "for the pitch interpolation and smoothing algorithm.");
     opts->Register("interpolator-factor", &interpolator_factor, "Factor affecting the "
                    "interpolation algorithm; setting it closer to zero will cause "
                    "it to follow the measured pitch more faithfully but less "
                    "smoothly");
     opts->Register("max-voicing-prob", &max_voicing_prob, "Probability of voicing the "
                    "algorithm uses as the observed p(voicing) approaches 1; having "
                    "value <1 allows it to interpolate even if p(voicing) = 1");
     opts->Register("max-pitch-change-per-frame", &max_pitch_change_per_frame,
                    "This value should be set large enough to no longer affect the "
                    "results, but the larger it is the slower the algorithm will be.");
   }
Member Data Documentation
interpolator_factor
BaseFloat interpolator_factor
Definition at line 28 of file interpolate-pitch.cc.
max_pitch_change_per_frame
BaseFloat max_pitch_change_per_frame
Definition at line 33 of file interpolate-pitch.cc.
max_voicing_prob
BaseFloat max_voicing_prob
Definition at line 31 of file interpolate-pitch.cc.
pitch_interval
BaseFloat pitch_interval
Definition at line 27 of file interpolate-pitch.cc.
Referenced by PitchInterpolator::Backtrace(), PitchInterpolator::ComputeTransitionProb(), and PitchInterpolator::InitValues().
The documentation for this struct was generated from the following file:
featbin/interpolate-pitch.cc