Kaldi: NnetDiscriminativeOptions Struct Reference
NnetDiscriminativeOptions Struct Reference
#include <nnet-discriminative-training.h>
Public Member Functions
NnetDiscriminativeOptions ()
void Register (OptionsItf *opts)
Public Attributes
NnetTrainerOptions nnet_config
discriminative::DiscriminativeOptions discriminative_config
bool apply_deriv_weights
Detailed Description
Definition at line 35 of file nnet-discriminative-training.h.
Constructor & Destructor Documentation
NnetDiscriminativeOptions()
NnetDiscriminativeOptions () inline
Definition at line 41 of file nnet-discriminative-training.h.
 : apply_deriv_weights(true) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 43 of file nnet-discriminative-training.h.
References OptionsItf::Register(), NnetTrainerOptions::Register(), and DiscriminativeOptions::Register().
Referenced by main().
{
     nnet_config.Register(opts);
     discriminative_config.Register(opts);
     opts->Register("apply-deriv-weights", &apply_deriv_weights,
                    "If true, apply the per-frame derivative weights stored with "
                    "the example.");
   }
Member Data Documentation
apply_deriv_weights
bool apply_deriv_weights
Definition at line 39 of file nnet-discriminative-training.h.
Referenced by NnetDiscriminativeTrainer::ProcessOutputs().
discriminative_config
discriminative::DiscriminativeOptions discriminative_config
Definition at line 37 of file nnet-discriminative-training.h.
Referenced by NnetDiscriminativeTrainer::PrintTotalStats(), NnetDiscriminativeTrainer::ProcessOutputs(), and NnetDiscriminativeTrainer::Train().
nnet_config
NnetTrainerOptions nnet_config
Definition at line 36 of file nnet-discriminative-training.h.
Referenced by NnetDiscriminativeTrainer::NnetDiscriminativeTrainer(), NnetDiscriminativeTrainer::ProcessOutputs(), NnetDiscriminativeTrainer::Train(), and NnetDiscriminativeTrainer::~NnetDiscriminativeTrainer().
The documentation for this struct was generated from the following file:
nnet3/nnet-discriminative-training.h