Kaldi: Component Class Reference
Component Class Reference abstract
Abstract class, building block of the network.
#include <nnet-component.h>
Classes
struct key_value
A pair of type and marker,.
Public Types
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjected, kBlstmProjected,
kRecurrentComponent, kActivationFunction = 0x0200, kSoftmax, kHiddenSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kParametricRelu,
kDropout, kLengthNormComponent, kTranform = 0x0400, kRbm,
kSplice, kCopy, kTranspose, kBlockLinearity,
kAddShift, kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent,
kSimpleSentenceAveragingComponent, kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent,
kMaxPooling2DComponent, kFramePoolingComponent, kParallelComponent, kMultiBasisComponent
}
Component type identification mechanism,.
Public Member Functions
Component (int32 input_dim, int32 output_dim)
Generic interface of a component,.
virtual ~Component ()
virtual Component * Copy () const =0
Copy component (deep copy),.
virtual ComponentType GetType () const =0
Get Type Identification of the component,.
virtual bool IsUpdatable () const
Check if componeny has 'Updatable' interface (trainable components),.
virtual bool IsMultistream () const
Check if component has 'Recurrent' interface (trainable and recurrent),.
int32 InputDim () const
Get the dimension of the input,.
int32 OutputDim () const
Get the dimension of the output,.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward-pass propagation 'in' -> 'out',.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
void Write (std::ostream &os, bool binary) const
Write the component to a stream,.
virtual std::string Info () const
Print some additional info (after <ComponentName> and the dims),.
virtual std::string InfoGradient () const
Print some additional info about gradient (after <...> and dims),.
Static Public Member Functions
static const char * TypeToMarker (ComponentType t)
Converts component type to marker,.
static ComponentType MarkerToType (const std::string &s)
Converts marker to component type (case insensitive),.
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file,.
static Component * Read (std::istream &is, bool binary)
Read the component from a stream (static method),.
Static Public Attributes
static const struct key_value kMarkerMap []
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Protected Member Functions
virtual void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)=0
Abstract interface for propagation/backpropagation.
virtual void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)=0
Backward pass transformation (to be implemented by descending class...)
virtual void InitData (std::istream &is)
Virtual interface for initialization and I/O,.
virtual void ReadData (std::istream &is, bool binary)
Reads the component content.
virtual void WriteData (std::ostream &os, bool binary) const
Writes the component content.
Protected Attributes
int32 input_dim_
Data members,.
int32 output_dim_
Dimension of the output of the Component,.
Static Private Member Functions
static Component * NewComponentOfType (ComponentType t, int32 input_dim, int32 output_dim)
Private members (descending classes cannot call this),.
Detailed Description
Abstract class, building block of the network.
It is able to propagate (PropagateFnc: compute the output based on its input) and backpropagate (BackpropagateFnc: i.e. transform loss derivative w.r.t. output to derivative w.r.t. the input) the formulas are implemented in descendant classes (AffineTransform,Sigmoid,Softmax,...).
Definition at line 55 of file nnet-component.cc.
Member Enumeration Documentation
ComponentType
enum ComponentType
Component type identification mechanism,.
Types of Components,
Enumerator
kUnknown
kUpdatableComponent
kAffineTransform
kLinearTransform
kConvolutionalComponent
kConvolutional2DComponent
kLstmProjected
kBlstmProjected
kRecurrentComponent
kActivationFunction
kSoftmax
kHiddenSoftmax
kBlockSoftmax
kSigmoid
kTanh
kParametricRelu
kDropout
kLengthNormComponent
kTranform
kRbm
kSplice
kCopy
kTranspose
kBlockLinearity
kAddShift
kRescale
kKlHmm
kSentenceAveragingComponent
kSimpleSentenceAveragingComponent
kAveragePoolingComponent
kAveragePooling2DComponent
kMaxPoolingComponent
kMaxPooling2DComponent
kFramePoolingComponent
kParallelComponent
kMultiBasisComponent
Definition at line 47 of file nnet-component.h.
                {
     kUnknown = 0x0,
     kUpdatableComponent = 0x0100,
     kAffineTransform,
     kLinearTransform,
     kConvolutionalComponent,
     kConvolutional2DComponent,
     kLstmProjected,
     kBlstmProjected,
     kRecurrentComponent,
     kActivationFunction = 0x0200,
     kSoftmax,
     kHiddenSoftmax,
     kBlockSoftmax,
     kSigmoid,
     kTanh,
     kParametricRelu,
     kDropout,
     kLengthNormComponent,
     kTranform = 0x0400,
     kRbm,
     kSplice,
     kCopy,
     kTranspose,
     kBlockLinearity,
     kAddShift,
     kRescale,
     kKlHmm = 0x0800,
     kSentenceAveragingComponent, /* deprecated */
     kSimpleSentenceAveragingComponent,
     kAveragePoolingComponent,
     kAveragePooling2DComponent,
     kMaxPoolingComponent,
     kMaxPooling2DComponent,
     kFramePoolingComponent,
     kParallelComponent,
     kMultiBasisComponent
   } ComponentType;
Constructor & Destructor Documentation
Component()
Component (int32 input_dim, int32 output_dim) inline
Generic interface of a component,.
Definition at line 108 of file nnet-component.h.
                                               :
     input_dim_(input_dim),
     output_dim_(output_dim)
   { }
~Component()
virtual ~Component () inline virtual
Definition at line 113 of file nnet-component.h.
References Component::Copy(), and Component::GetType().
   { }
Member Function Documentation
Backpropagate()
void Backpropagate (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrix< BaseFloat > * in_diff) inline
Perform backward-pass propagation 'out_diff' -> 'in_diff'.
Note: 'in' and 'out' will be used only sometimes...
Definition at line 328 of file nnet-component.h.
References Component::BackpropagateFnc(), Component::InputDim(), KALDI_ASSERT, KALDI_ERR, kaldi::kSetZero, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::OutputDim(), and CuMatrix< Real >::Resize().
Referenced by Component::OutputDim(), kaldi::nnet1::UnitTestAveragePooling2DComponent(), kaldi::nnet1::UnitTestConvolutional2DComponent(), kaldi::nnet1::UnitTestConvolutionalComponent3x3(), kaldi::nnet1::UnitTestConvolutionalComponentUnity(), kaldi::nnet1::UnitTestDropoutComponent(), kaldi::nnet1::UnitTestMaxPooling2DComponent(), kaldi::nnet1::UnitTestMaxPoolingComponent(), and kaldi::nnet1::UnitTestSimpleSentenceAveragingComponent().
{
   // Check the dims,
   if (OutputDim() != out_diff.NumCols()) {
     KALDI_ERR << "Non-matching dims! Component output dim " << OutputDim()
               << ", the dim of output derivatives " << out_diff.NumCols();
   }
   int32 num_frames = out_diff.NumRows();
   KALDI_ASSERT(num_frames == in.NumRows());
   KALDI_ASSERT(num_frames == out.NumRows());
   KALDI_ASSERT(InputDim() == in.NumCols());
   KALDI_ASSERT(OutputDim() == out.NumCols());
   // Allocate target buffer,
   KALDI_ASSERT(in_diff != NULL);
   in_diff->Resize(num_frames, InputDim(), kSetZero);  // reset,
   // Call the 'virtual' backprop function,
   BackpropagateFnc(in, out, out_diff, in_diff);
 }
BackpropagateFnc()
virtual void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) protected pure virtual
Backward pass transformation (to be implemented by descending class...)
Implemented in BlstmProjected, Rescale, LstmProjected, AddShift, ConvolutionalComponent, Dropout, MultiBasisComponent, Convolutional2DComponent, LengthNormComponent, SentenceAveragingComponent, ParallelComponent, Tanh, RecurrentComponent, FramePoolingComponent, Sigmoid, CopyComponent, BlockSoftmax, AffineTransform, LinearTransform, ParametricRelu, MaxPooling2DComponent, AveragePooling2DComponent, SimpleSentenceAveragingComponent, AveragePoolingComponent, MaxPoolingComponent, Splice, KlHmm, HiddenSoftmax, RbmBase, and Softmax.
Referenced by Component::Backpropagate(), and Component::InfoGradient().
Copy()
virtual Component* Copy () const pure virtual
Copy component (deep copy),.
Implemented in Rescale, AddShift, Dropout, LengthNormComponent, Tanh, Sigmoid, SentenceAveragingComponent, CopyComponent, BlockSoftmax, Rbm, Convolutional2DComponent, ConvolutionalComponent, HiddenSoftmax, BlstmProjected, LstmProjected, FramePoolingComponent, SimpleSentenceAveragingComponent, MaxPooling2DComponent, AveragePooling2DComponent, AveragePoolingComponent, MaxPoolingComponent, RecurrentComponent, Splice, ParametricRelu, KlHmm, Softmax, MultiBasisComponent, ParallelComponent, AffineTransform, and LinearTransform.
Referenced by Nnet::AppendComponent(), Nnet::Nnet(), Nnet::operator=(), Nnet::ReplaceComponent(), and Component::~Component().
GetType()
virtual ComponentType GetType () const pure virtual
Get Type Identification of the component,.
Implemented in Rescale, AddShift, Dropout, LengthNormComponent, Tanh, Sigmoid, SentenceAveragingComponent, CopyComponent, BlockSoftmax, Rbm, Convolutional2DComponent, ConvolutionalComponent, HiddenSoftmax, BlstmProjected, LstmProjected, SimpleSentenceAveragingComponent, FramePoolingComponent, MaxPooling2DComponent, AveragePooling2DComponent, AveragePoolingComponent, MaxPoolingComponent, RecurrentComponent, Splice, ParametricRelu, KlHmm, Softmax, MultiBasisComponent, ParallelComponent, AffineTransform, and LinearTransform.
Referenced by kaldi::ConvertComponent(), main(), Component::Propagate(), Nnet::SetDropoutRate(), Component::Write(), and Component::~Component().
Info()
virtual std::string Info () const inline virtual
Print some additional info (after <ComponentName> and the dims),.
Reimplemented in Rescale, BlstmProjected, AddShift, Dropout, LstmProjected, Convolutional2DComponent, ConvolutionalComponent, MultiBasisComponent, SentenceAveragingComponent, CopyComponent, BlockSoftmax, ParallelComponent, FramePoolingComponent, RecurrentComponent, AffineTransform, LinearTransform, ParametricRelu, SimpleSentenceAveragingComponent, and Splice.
Definition at line 162 of file nnet-component.h.
 { return ""; }
InfoGradient()
virtual std::string InfoGradient () const inline virtual
Print some additional info about gradient (after <...> and dims),.
Reimplemented in Rescale, BlstmProjected, AddShift, LstmProjected, MultiBasisComponent, Convolutional2DComponent, ConvolutionalComponent, SentenceAveragingComponent, ParallelComponent, FramePoolingComponent, RecurrentComponent, AffineTransform, LinearTransform, ParametricRelu, and SimpleSentenceAveragingComponent.
Definition at line 165 of file nnet-component.h.
References Component::BackpropagateFnc(), and Component::PropagateFnc().
 { return ""; }
Init()
Component * Init (const std::string & conf_line) static
Initialize component from a line in config file,.
Definition at line 219 of file nnet-component.cc.
References kaldi::ExpectToken(), Component::InitData(), Component::MarkerToType(), Component::NewComponentOfType(), kaldi::ReadBasicType(), and kaldi::ReadToken().
Referenced by Nnet::Init(), Component::OutputDim(), kaldi::nnet1::UnitTestAveragePooling2DComponent(), kaldi::nnet1::UnitTestMaxPooling2DComponent(), and kaldi::nnet1::UnitTestMaxPoolingComponent().
{
   std::istringstream is(conf_line);
   std::string component_type_string;
   int32 input_dim, output_dim;
   // initialize component w/o internal data
   ReadToken(is, false, &component_type_string);
   ComponentType component_type = MarkerToType(component_type_string);
   ExpectToken(is, false, "<InputDim>");
   ReadBasicType(is, false, &input_dim);
   ExpectToken(is, false, "<OutputDim>");
   ReadBasicType(is, false, &output_dim);
   Component *ans = NewComponentOfType(component_type, input_dim, output_dim);
   // initialize internal data with the remaining part of config line
   ans->InitData(is);
   return ans;
 }
InitData()
virtual void InitData (std::istream & is) inline protected virtual
Virtual interface for initialization and I/O,.
Initialize internal data of a component
Reimplemented in Rescale, AddShift, Dropout, UpdatableComponent, SentenceAveragingComponent, CopyComponent, BlockSoftmax, Rbm, Convolutional2DComponent, ConvolutionalComponent, BlstmProjected, LstmProjected, SimpleSentenceAveragingComponent, FramePoolingComponent, MaxPooling2DComponent, AveragePooling2DComponent, AveragePoolingComponent, MaxPoolingComponent, RecurrentComponent, Splice, ParametricRelu, ParallelComponent, MultiBasisComponent, AffineTransform, and LinearTransform.
Definition at line 183 of file nnet-component.h.
Referenced by Component::Init(), and UpdatableComponent::SetBiasLearnRateCoef().
 { }
InputDim()
int32 InputDim () const inline
Get the dimension of the input,.
Definition at line 133 of file nnet-component.h.
References Component::input_dim_.
Referenced by Component::Backpropagate(), kaldi::ConvertSigmoidComponent(), kaldi::ConvertSoftmaxComponent(), kaldi::ConvertSpliceComponent(), LinearTransform::InitData(), AffineTransform::InitData(), MultiBasisComponent::InitData(), ParallelComponent::InitData(), Splice::InitData(), FramePoolingComponent::InitData(), Rbm::InitData(), CopyComponent::InitData(), SentenceAveragingComponent::InitData(), AddShift::InitData(), Rescale::InitData(), SimpleSentenceAveragingComponent::PropagateFnc(), Nnet::Read(), Splice::ReadData(), ParallelComponent::ReadData(), FramePoolingComponent::ReadData(), MultiBasisComponent::ReadData(), SentenceAveragingComponent::ReadData(), AddShift::Update(), Rescale::Update(), Component::Write(), and Rbm::WriteAsNnet().
{
     return input_dim_;
   }
IsMultistream()
virtual bool IsMultistream () const inline virtual
Check if component has 'Recurrent' interface (trainable and recurrent),.
Reimplemented in MultistreamComponent.
Definition at line 128 of file nnet-component.h.
Referenced by Nnet::ResetStreams(), and Nnet::SetSeqLengths().
{
     return false;
   }
IsUpdatable()
virtual bool IsUpdatable () const inline virtual
Check if componeny has 'Updatable' interface (trainable components),.
Reimplemented in UpdatableComponent.
Definition at line 123 of file nnet-component.h.
Referenced by main(), and Nnet::SetTrainOptions().
{
     return false;
   }
MarkerToType()
Component::ComponentType MarkerToType (const std::string & s) static
Converts marker to component type (case insensitive),.
Definition at line 101 of file nnet-component.cc.
References rnnlm::i, KALDI_ERR, Component::kMarkerMap, Component::kUnknown, and Component::key_value::value.
Referenced by Component::Init(), and Component::Read().
{
   std::string s_lowercase(s);
   std::transform(s.begin(), s.end(), s_lowercase.begin(), ::tolower);  // lc
   int32 N = sizeof(kMarkerMap) / sizeof(kMarkerMap[0]);
   for (int i = 0; i < N; i++) {
     std::string m(kMarkerMap[i].value);
     std::string m_lowercase(m);
     std::transform(m.begin(), m.end(), m_lowercase.begin(), ::tolower);
     if (s_lowercase == m_lowercase) return kMarkerMap[i].key;
   }
   KALDI_ERR << "Unknown 'Component' marker : '" << s << "'\n"
             << "(isn't the model 'too old' or incompatible?)";
   return kUnknown;
 }
NewComponentOfType()
Component * NewComponentOfType (ComponentType t, int32 input_dim, int32 output_dim) static private
Private members (descending classes cannot call this),.
Create a new intance of component,
Definition at line 117 of file nnet-component.cc.
References Component::kAddShift, Component::kAffineTransform, KALDI_ERR, Component::kAveragePooling2DComponent, Component::kAveragePoolingComponent, Component::kBlockSoftmax, Component::kBlstmProjected, Component::kConvolutional2DComponent, Component::kConvolutionalComponent, Component::kCopy, Component::kDropout, Component::kFramePoolingComponent, Component::kHiddenSoftmax, Component::kKlHmm, Component::kLengthNormComponent, Component::kLinearTransform, Component::kLstmProjected, Component::kMaxPooling2DComponent, Component::kMaxPoolingComponent, Component::kMultiBasisComponent, Component::kParallelComponent, Component::kParametricRelu, Component::kRbm, Component::kRecurrentComponent, Component::kRescale, Component::kSentenceAveragingComponent, Component::kSigmoid, Component::kSimpleSentenceAveragingComponent, Component::kSoftmax, Component::kSplice, Component::kTanh, Component::kUnknown, kaldi::cu::Splice(), and Component::TypeToMarker().
Referenced by Component::Init(), and Component::Read().
{
   Component *ans = NULL;
   switch (comp_type) {
     case Component::kAffineTransform :
       ans = new AffineTransform(input_dim, output_dim);
       break;
     case Component::kLinearTransform :
       ans = new LinearTransform(input_dim, output_dim);
       break;
     case Component::kConvolutionalComponent :
       ans = new ConvolutionalComponent(input_dim, output_dim);
       break;
     case Component::kConvolutional2DComponent :
       ans = new Convolutional2DComponent(input_dim, output_dim);
       break;
     case Component::kLstmProjected :
       ans = new LstmProjected(input_dim, output_dim);
       break;
     case Component::kBlstmProjected :
       ans = new BlstmProjected(input_dim, output_dim);
       break;
     case Component::kRecurrentComponent :
       ans = new RecurrentComponent(input_dim, output_dim);
       break;
     case Component::kSoftmax :
       ans = new Softmax(input_dim, output_dim);
       break;
     case Component::kHiddenSoftmax :
       ans = new HiddenSoftmax(input_dim, output_dim);
       break;
     case Component::kBlockSoftmax :
       ans = new BlockSoftmax(input_dim, output_dim);
       break;
     case Component::kSigmoid :
       ans = new Sigmoid(input_dim, output_dim);
       break;
     case Component::kTanh :
       ans = new Tanh(input_dim, output_dim);
       break;
     case Component::kParametricRelu :
       ans = new ParametricRelu(input_dim, output_dim);
       break;
     case Component::kDropout :
       ans = new Dropout(input_dim, output_dim);
       break;
     case Component::kLengthNormComponent :
       ans = new LengthNormComponent(input_dim, output_dim);
       break;
     case Component::kRbm :
       ans = new Rbm(input_dim, output_dim);
       break;
     case Component::kSplice :
       ans = new Splice(input_dim, output_dim);
       break;
     case Component::kCopy :
       ans = new CopyComponent(input_dim, output_dim);
       break;
     case Component::kAddShift :
       ans = new AddShift(input_dim, output_dim);
       break;
     case Component::kRescale :
       ans = new Rescale(input_dim, output_dim);
       break;
     case Component::kKlHmm :
       ans = new KlHmm(input_dim, output_dim);
       break;
     case Component::kSentenceAveragingComponent :
       ans = new SentenceAveragingComponent(input_dim, output_dim);
       break;
     case Component::kSimpleSentenceAveragingComponent :
       ans = new SimpleSentenceAveragingComponent(input_dim, output_dim);
       break;
     case Component::kAveragePoolingComponent :
       ans = new AveragePoolingComponent(input_dim, output_dim);
       break;
     case Component::kAveragePooling2DComponent :
       ans = new AveragePooling2DComponent(input_dim, output_dim);
       break;
     case Component::kMaxPoolingComponent :
       ans = new MaxPoolingComponent(input_dim, output_dim);
       break;
     case Component::kMaxPooling2DComponent :
       ans = new MaxPooling2DComponent(input_dim, output_dim);
       break;
     case Component::kFramePoolingComponent :
       ans = new FramePoolingComponent(input_dim, output_dim);
       break;
     case Component::kParallelComponent :
       ans = new ParallelComponent(input_dim, output_dim);
       break;
     case Component::kMultiBasisComponent :
       ans = new MultiBasisComponent(input_dim, output_dim);
       break;
     case Component::kUnknown :
     default :
       KALDI_ERR << "Missing type: " << TypeToMarker(comp_type);
   }
   return ans;
 }
OutputDim()
int32 OutputDim () const inline
Get the dimension of the output,.
Definition at line 138 of file nnet-component.h.
References Component::Backpropagate(), Component::Init(), Component::output_dim_, Component::Propagate(), Component::Read(), and Component::Write().
Referenced by Component::Backpropagate(), SimpleSentenceAveragingComponent::BackpropagateFnc(), MultiBasisComponent::BackpropagateFnc(), AffineTransform::InitData(), LinearTransform::InitData(), MultiBasisComponent::InitData(), ParallelComponent::InitData(), Splice::InitData(), Rbm::InitData(), BlockSoftmax::InitData(), CopyComponent::InitData(), SentenceAveragingComponent::InitData(), Splice::ReadData(), ParallelComponent::ReadData(), MultiBasisComponent::ReadData(), BlockSoftmax::ReadData(), CopyComponent::ReadData(), SentenceAveragingComponent::ReadData(), AffineTransform::Update(), RecurrentComponent::Update(), Component::Write(), and Rbm::WriteAsNnet().
{
     return output_dim_;
   }
Propagate()
void Propagate (const CuMatrixBase< BaseFloat > & in, CuMatrix< BaseFloat > * out) inline
Perform forward-pass propagation 'in' -> 'out',.
Definition at line 314 of file nnet-component.h.
References Component::GetType(), Component::input_dim_, KALDI_ERR, kaldi::kSetZero, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, Component::PropagateFnc(), CuMatrix< Real >::Resize(), and Component::TypeToMarker().
Referenced by Component::OutputDim(), kaldi::nnet1::UnitTestAveragePooling2DComponent(), kaldi::nnet1::UnitTestConvolutional2DComponent(), kaldi::nnet1::UnitTestConvolutionalComponent3x3(), kaldi::nnet1::UnitTestConvolutionalComponentUnity(), kaldi::nnet1::UnitTestDropoutComponent(), kaldi::nnet1::UnitTestLengthNorm(), kaldi::nnet1::UnitTestMaxPooling2DComponent(), kaldi::nnet1::UnitTestMaxPoolingComponent(), and kaldi::nnet1::UnitTestSimpleSentenceAveragingComponent().
{
   // Check the dims
   if (input_dim_ != in.NumCols()) {
     KALDI_ERR << "Non-matching dims on the input of " << TypeToMarker(GetType())
               << " component. The input-dim is " << input_dim_
               << ", the data had " << in.NumCols() << " dims.";
   }
   // Allocate target buffer
   out->Resize(in.NumRows(), output_dim_, kSetZero);  // reset
   // Call the propagation implementation of the component
   PropagateFnc(in, out);
 }
PropagateFnc()
virtual void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) protected pure virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implemented in BlstmProjected, Rescale, AddShift, LstmProjected, Dropout, MultiBasisComponent, Convolutional2DComponent, ConvolutionalComponent, LengthNormComponent, Tanh, SentenceAveragingComponent, ParallelComponent, Rbm, Sigmoid, FramePoolingComponent, CopyComponent, RecurrentComponent, AffineTransform, BlockSoftmax, LinearTransform, ParametricRelu, MaxPooling2DComponent, AveragePooling2DComponent, SimpleSentenceAveragingComponent, Splice, AveragePoolingComponent, MaxPoolingComponent, HiddenSoftmax, KlHmm, and Softmax.
Referenced by Component::InfoGradient(), and Component::Propagate().
Read()
Component * Read (std::istream & is, bool binary) static
Read the component from a stream (static method),.
Definition at line 240 of file nnet-component.cc.
References kaldi::ExpectToken(), Component::MarkerToType(), Component::NewComponentOfType(), kaldi::Peek(), kaldi::PeekToken(), kaldi::ReadBasicType(), Component::ReadData(), and kaldi::ReadToken().
Referenced by Component::OutputDim(), Nnet::Read(), and kaldi::nnet1::ReadComponentFromString().
{
   int32 dim_out, dim_in;
   std::string token;
   int first_char = Peek(is, binary);
   if (first_char == EOF) return NULL;
   ReadToken(is, binary, &token);
   // Skip the optional initial token,
   if (token == "<Nnet>") {
     ReadToken(is, binary, &token);
   }
   // Network ends after terminal token appears,
   if (token == "</Nnet>") {
     return NULL;
   }
   // Read the dims,
   ReadBasicType(is, binary, &dim_out);
   ReadBasicType(is, binary, &dim_in);
   // Create the component,
   Component *ans = NewComponentOfType(MarkerToType(token), dim_in, dim_out);
   // Read the content,
   ans->ReadData(is, binary);
   // 'Eat' the component separtor (can be already consumed by 'ReadData(.)'),
   if ('<' == Peek(is, binary) && '!' == PeekToken(is, binary)) {
     ExpectToken(is, binary, "<!EndOfComponent>");
   }
   return ans;
 }
ReadData()
virtual void ReadData (std::istream & is, bool binary) inline protected virtual
Reads the component content.
Reimplemented in Rescale, AddShift, Dropout, SentenceAveragingComponent, CopyComponent, Rbm, BlockSoftmax, Convolutional2DComponent, MultiBasisComponent, BlstmProjected, ConvolutionalComponent, FramePoolingComponent, KlHmm, ParallelComponent, LstmProjected, LinearTransform, Splice, RecurrentComponent, MaxPooling2DComponent, AffineTransform, AveragePooling2DComponent, SimpleSentenceAveragingComponent, ParametricRelu, AveragePoolingComponent, and MaxPoolingComponent.
Definition at line 186 of file nnet-component.h.
Referenced by Component::Read().
 { }
TypeToMarker()
const char * TypeToMarker (ComponentType t) static
Converts component type to marker,.
Definition at line 91 of file nnet-component.cc.
References rnnlm::i, KALDI_ERR, Component::key_value::key, and Component::kMarkerMap.
Referenced by CopyComponent::BackpropagateFnc(), Nnet::Check(), kaldi::ConvertComponent(), Nnet::Info(), Nnet::InfoBackPropagate(), Nnet::InfoGradient(), Nnet::InfoPropagate(), main(), Component::NewComponentOfType(), Component::Propagate(), Component::Write(), and Rbm::WriteAsNnet().
{
   // Retuns the 1st '<string>' corresponding to the type in 'kMarkerMap',
   int32 N = sizeof(kMarkerMap) / sizeof(kMarkerMap[0]);
   for (int i = 0; i < N; i++) {
     if (kMarkerMap[i].key == t) return kMarkerMap[i].value;
   }
   KALDI_ERR << "Unknown type : " << t;
   return NULL;
 }
Write()
void Write (std::ostream & os, bool binary) const
Write the component to a stream,.
Definition at line 276 of file nnet-component.cc.
References Component::GetType(), Component::InputDim(), Component::OutputDim(), Component::TypeToMarker(), kaldi::WriteBasicType(), Component::WriteData(), and kaldi::WriteToken().
Referenced by Component::OutputDim().
{
   WriteToken(os, binary, Component::TypeToMarker(GetType()));
   WriteBasicType(os, binary, OutputDim());
   WriteBasicType(os, binary, InputDim());
   if (!binary) os << "\n";
   this->WriteData(os, binary);
   WriteToken(os, binary, "<!EndOfComponent>");  // Write component separator.
   if (!binary) os << "\n";
 }
WriteData()
virtual void WriteData (std::ostream & os, bool binary) const inline protected virtual
Writes the component content.
Reimplemented in Rescale, AddShift, Dropout, SentenceAveragingComponent, Rbm, CopyComponent, BlstmProjected, Convolutional2DComponent, ConvolutionalComponent, MultiBasisComponent, BlockSoftmax, FramePoolingComponent, LstmProjected, ParallelComponent, KlHmm, LinearTransform, MaxPooling2DComponent, AveragePooling2DComponent, RecurrentComponent, AffineTransform, SimpleSentenceAveragingComponent, ParametricRelu, Splice, AveragePoolingComponent, and MaxPoolingComponent.
Definition at line 189 of file nnet-component.h.
Referenced by Component::Write().
 { }
Member Data Documentation
input_dim_
int32 input_dim_ protected
Data members,.
Dimension of the input of the Component,
Definition at line 193 of file nnet-component.h.
Referenced by MaxPoolingComponent::BackpropagateFnc(), AveragePoolingComponent::BackpropagateFnc(), AveragePooling2DComponent::BackpropagateFnc(), MaxPooling2DComponent::BackpropagateFnc(), Convolutional2DComponent::BackpropagateFnc(), LstmProjected::BackpropagateFnc(), BlstmProjected::BackpropagateFnc(), RecurrentComponent::InitData(), LstmProjected::InitData(), BlstmProjected::InitData(), ConvolutionalComponent::InitData(), Convolutional2DComponent::InitData(), Component::InputDim(), Component::Propagate(), MaxPoolingComponent::PropagateFnc(), AveragePoolingComponent::PropagateFnc(), AveragePooling2DComponent::PropagateFnc(), MaxPooling2DComponent::PropagateFnc(), ConvolutionalComponent::PropagateFnc(), Convolutional2DComponent::PropagateFnc(), Rbm::RbmUpdate(), MaxPoolingComponent::ReadData(), AveragePoolingComponent::ReadData(), AveragePooling2DComponent::ReadData(), AffineTransform::ReadData(), MaxPooling2DComponent::ReadData(), LinearTransform::ReadData(), KlHmm::ReadData(), FramePoolingComponent::ReadData(), ConvolutionalComponent::ReadData(), Convolutional2DComponent::ReadData(), Rbm::ReadData(), Rbm::Reconstruct(), ConvolutionalComponent::ReverseIndexes(), and KlHmm::SetStats().
kMarkerMap
const struct key_value kMarkerMap[] static
The table with pairs of Component types and markers (defined in nnet-component.cc),.
Definition at line 98 of file nnet-component.h.
Referenced by Component::MarkerToType(), and Component::TypeToMarker().
output_dim_
int32 output_dim_ protected
Dimension of the output of the Component,.
Definition at line 194 of file nnet-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), RecurrentComponent::InitData(), ConvolutionalComponent::InitData(), Convolutional2DComponent::InitData(), Component::OutputDim(), Component::Propagate(), Convolutional2DComponent::PropagateFnc(), Rbm::RbmUpdate(), MaxPoolingComponent::ReadData(), AveragePoolingComponent::ReadData(), ParametricRelu::ReadData(), AveragePooling2DComponent::ReadData(), AffineTransform::ReadData(), MaxPooling2DComponent::ReadData(), LinearTransform::ReadData(), KlHmm::ReadData(), FramePoolingComponent::ReadData(), ConvolutionalComponent::ReadData(), Convolutional2DComponent::ReadData(), Rbm::ReadData(), Rbm::Reconstruct(), KlHmm::SetStats(), and Convolutional2DComponent::Update().
The documentation for this class was generated from the following files:
nnet/nnet-component.cc
nnet/nnet-component.h