Kaldi: NnetCombineFastConfig Struct Reference
NnetCombineFastConfig Struct Reference
Configuration class that controls neural net combination, where we combine a number of neural nets, trying to find for each layer the optimal weighted combination of the different neural-net parameters.
#include <combine-nnet-fast.h>
Public Member Functions
NnetCombineFastConfig ()
void Register (OptionsItf *opts)
Public Attributes
int32 initial_model
int32 num_lbfgs_iters
int32 num_threads
BaseFloat initial_impr
BaseFloat fisher_floor
BaseFloat alpha
int32 fisher_minibatch_size
int32 minibatch_size
int32 max_lbfgs_dim
BaseFloat regularizer
Detailed Description
Configuration class that controls neural net combination, where we combine a number of neural nets, trying to find for each layer the optimal weighted combination of the different neural-net parameters.
Definition at line 50 of file combine-nnet-fast.h.
Constructor & Destructor Documentation
NnetCombineFastConfig()
NnetCombineFastConfig () inline
Definition at line 68 of file combine-nnet-fast.h.
                          : initial_model(-1), num_lbfgs_iters(10),
                            num_threads(1), initial_impr(0.01), fisher_floor(1.0e-20),
                            alpha(0.01), fisher_minibatch_size(64), minibatch_size(1024),
                            max_lbfgs_dim(10), regularizer(0.0) {}
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 73 of file combine-nnet-fast.h.
References kaldi::nnet2::CombineNnetsFast(), and OptionsItf::Register().
Referenced by main().
{
     opts->Register("initial-model", &initial_model, "Specifies where to start the "
                    "optimization from.  If 0 ... #models-1, then specifies the model; "
                    "if >= #models, then the average of all inputs; if <0, chosen "
                    "automatically from the previous options.");
     opts->Register("num-lbfgs-iters", &num_lbfgs_iters, "Maximum number of function "
                    "evaluations for L-BFGS to use when optimizing combination weights");
     opts->Register("initial-impr", &initial_impr, "Amount of objective-function change "
                    "We aim for on the first iteration.");
     opts->Register("num-threads", &num_threads, "Number of threads to use in "
                    "multi-core computation");
     opts->Register("fisher-floor", &fisher_floor,
                    "Floor for diagonal of Fisher matrix (used in preconditioning)");
     opts->Register("alpha", &alpha, "Value we use in smoothing the Fisher matrix "
                    "with its diagonal, in preconditioning the update.");
     opts->Register("fisher-minibatch-size", &fisher_minibatch_size, "Size of minibatch "
                    "used in computation of Fisher matrix (smaller -> better "
                    "preconditioning");
     opts->Register("minibatch-size", &minibatch_size, "Minibatch size used in computing "
                    "gradients (only affects speed)");
     opts->Register("max-lbfgs-dim", &max_lbfgs_dim, "Maximum dimension to use in "
                    "L-BFGS (will not get higher than this even if the dimension "
                    "of the space gets higher.)");
     opts->Register("regularizer", &regularizer, "Add to the objective "
                    "function (which is average log-like per frame), -0.5 * "
                    "regularizer * square of parameters.");
   }
Member Data Documentation
alpha
BaseFloat alpha
Definition at line 59 of file combine-nnet-fast.h.
fisher_floor
BaseFloat fisher_floor
Definition at line 56 of file combine-nnet-fast.h.
fisher_minibatch_size
int32 fisher_minibatch_size
Definition at line 60 of file combine-nnet-fast.h.
initial_impr
BaseFloat initial_impr
Definition at line 55 of file combine-nnet-fast.h.
initial_model
int32 initial_model
Definition at line 51 of file combine-nnet-fast.h.
max_lbfgs_dim
int32 max_lbfgs_dim
Definition at line 65 of file combine-nnet-fast.h.
minibatch_size
int32 minibatch_size
Definition at line 63 of file combine-nnet-fast.h.
num_lbfgs_iters
int32 num_lbfgs_iters
Definition at line 53 of file combine-nnet-fast.h.
num_threads
int32 num_threads
Definition at line 54 of file combine-nnet-fast.h.
Referenced by main().
regularizer
BaseFloat regularizer
Definition at line 66 of file combine-nnet-fast.h.
The documentation for this struct was generated from the following file:
nnet2/combine-nnet-fast.h