Kaldi: QuestionsForKey Struct Reference
QuestionsForKey Struct Reference
Modules involved in tree building » Question sets for decision-tree clustering
QuestionsForKey is a class used to define the questions for a key, and also options that allow us to refine the question during tree-building (i.e.
#include <build-tree-questions.h>
Public Member Functions
QuestionsForKey (int32 num_iters=5)
void Check () const
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
Public Attributes
std::vector< std::vector< EventValueType > > initial_questions
RefineClustersOptions refine_opts
Detailed Description
QuestionsForKey is a class used to define the questions for a key, and also options that allow us to refine the question during tree-building (i.e.
make a question specific to the location in the tree). The Questions class handles aggregating these options for a set of different keys.
Definition at line 50 of file build-tree-questions.h.
Constructor & Destructor Documentation
QuestionsForKey()
QuestionsForKey (int32 num_iters = 5) inline
Definition at line 56 of file build-tree-questions.h.
Referenced by Questions::SetQuestionsOf().
                                       : refine_opts(num_iters, 2) {
     // refine_cfg with 5 iters and top-n = 2 (this is no restriction because
     // RefineClusters called with 2 clusters; would get set to that anyway as
     // it's the only possible value for 2 clusters).  User has to add questions.
     // This config won't work as-is, as it has no questions.
   }
Member Function Documentation
Check()
void Check () const inline
Definition at line 63 of file build-tree-questions.h.
References rnnlm::i, kaldi::IsSorted(), KALDI_ASSERT, QuestionsForKey::Read(), and QuestionsForKey::Write().
Referenced by Questions::SetQuestionsOf().
                      {
     for (size_t i = 0;i < initial_questions.size();i++) KALDI_ASSERT(IsSorted(initial_questions[i]));
   }
Read()
void Read (std::istream & is, bool binary)
Definition at line 37 of file build-tree-questions.cc.
References kaldi::ExpectToken(), rnnlm::i, QuestionsForKey::initial_questions, RefineClustersOptions::Read(), kaldi::ReadBasicType(), kaldi::ReadIntegerVector(), and QuestionsForKey::refine_opts.
Referenced by QuestionsForKey::Check(), Questions::Questions(), and Questions::Read().
{
   int32 size;
   ExpectToken(is, binary, "<QuestionsForKey>");
   ReadBasicType(is, binary, &size);
   initial_questions.resize(size);
   for (int32 i = 0; i < size; i++)
     ReadIntegerVector(is, binary, &(initial_questions[i]));
   refine_opts.Read(is, binary);
   ExpectToken(is, binary, "</QuestionsForKey>");
 }
Write()
void Write (std::ostream & os, bool binary) const
Definition at line 27 of file build-tree-questions.cc.
References rnnlm::i, QuestionsForKey::initial_questions, QuestionsForKey::refine_opts, RefineClustersOptions::Write(), kaldi::WriteBasicType(), kaldi::WriteIntegerVector(), and kaldi::WriteToken().
Referenced by QuestionsForKey::Check(), Questions::Questions(), and Questions::Write().
{
   WriteToken(os, binary, "<QuestionsForKey>");
   int32 size = initial_questions.size();
   WriteBasicType(os, binary, size);
   for (int32 i = 0; i < size; i++)
     WriteIntegerVector(os, binary, initial_questions[i]);
   refine_opts.Write(os, binary);
   WriteToken(os, binary, "</QuestionsForKey>");
 }
Member Data Documentation
initial_questions
std::vector<std::vector<EventValueType> > initial_questions
Definition at line 52 of file build-tree-questions.h.
Referenced by kaldi::ComputeInitialSplit(), main(), QuestionsForKey::Read(), kaldi::TestBuildTree(), kaldi::TestQuestionsInitRand(), kaldi::TestSplitDecisionTree(), and QuestionsForKey::Write().
refine_opts
RefineClustersOptions refine_opts
Definition at line 53 of file build-tree-questions.h.
Referenced by kaldi::FindBestSplitForKey(), Questions::InitRand(), QuestionsForKey::Read(), and QuestionsForKey::Write().
The documentation for this struct was generated from the following files:
tree/build-tree-questions.h
tree/build-tree-questions.cc