Kaldi: NnetMixupConfig Struct Reference
NnetMixupConfig Struct Reference
#include <mixup-nnet.h>
Public Member Functions
NnetMixupConfig ()
void Register (OptionsItf *opts)
Public Attributes
BaseFloat power
BaseFloat min_count
int32 num_mixtures
BaseFloat perturb_stddev
Detailed Description
Definition at line 30 of file mixup-nnet.h.
Constructor & Destructor Documentation
NnetMixupConfig()
NnetMixupConfig () inline
Definition at line 37 of file mixup-nnet.h.
                    : power(0.25), min_count(1000.0),
                      num_mixtures(-1), perturb_stddev(0.01) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 40 of file mixup-nnet.h.
References kaldi::nnet2::MixupNnet(), and OptionsItf::Register().
Referenced by main().
{
     opts->Register("power", &power, "Scaling factor used in determining the "
                    "number of mixture components to use for each HMM state "
                    "(or group of HMM states)");
     opts->Register("min-count", &min_count, "Minimum count for a quasi-Gaussian, "
                    "enforced while allocating mixtures (obscure parameter).");
     opts->Register("num-mixtures", &num_mixtures, "If specified, total number of "
                    "mixture components to mix up to (should be at least the "
                    "#leaves in the system");
     opts->Register("perturb-stddev", &perturb_stddev, "Standard deviation used "
                    "when perturbing parameters during mixing up");
   }
Member Data Documentation
min_count
BaseFloat min_count
Definition at line 32 of file mixup-nnet.h.
Referenced by kaldi::nnet2::MixupNnet().
num_mixtures
int32 num_mixtures
Definition at line 33 of file mixup-nnet.h.
Referenced by kaldi::nnet2::MixupNnet().
perturb_stddev
BaseFloat perturb_stddev
Definition at line 34 of file mixup-nnet.h.
Referenced by kaldi::nnet2::MixupNnet().
power
BaseFloat power
Definition at line 31 of file mixup-nnet.h.
Referenced by kaldi::nnet2::MixupNnet().
The documentation for this struct was generated from the following file:
nnet2/mixup-nnet.h