Kaldi: SpectrogramOptions Struct Reference
SpectrogramOptions Struct Reference
FeatureExtraction
SpectrogramOptions contains basic options for computing spectrogram features.
#include <feature-spectrogram.h>
Public Member Functions
SpectrogramOptions ()
void Register (OptionsItf *opts)
Public Attributes
FrameExtractionOptions frame_opts
BaseFloat energy_floor
bool raw_energy
Detailed Description
SpectrogramOptions contains basic options for computing spectrogram features.
Definition at line 38 of file feature-spectrogram.h.
Constructor & Destructor Documentation
SpectrogramOptions()
SpectrogramOptions () inline
Definition at line 43 of file feature-spectrogram.h.
                        :
     energy_floor(0.0),
     raw_energy(true) {}
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 47 of file feature-spectrogram.h.
References OptionsItf::Register(), and FrameExtractionOptions::Register().
Referenced by main().
{
     frame_opts.Register(opts);
     opts->Register("energy-floor", &energy_floor,
                    "Floor on energy (absolute, not relative) in Spectrogram "
                    "computation.  Caution: this floor is applied to the zeroth "
                    "component, representing the total signal energy.  The "
                    "floor on the individual spectrogram elements is fixed at "
                    "std::numeric_limits<float>::epsilon().");
     opts->Register("raw-energy", &raw_energy,
                    "If true, compute energy before preemphasis and windowing");
   }
Member Data Documentation
energy_floor
BaseFloat energy_floor
Definition at line 40 of file feature-spectrogram.h.
Referenced by SpectrogramComputer::Compute(), and SpectrogramComputer::SpectrogramComputer().
frame_opts
FrameExtractionOptions frame_opts
Definition at line 39 of file feature-spectrogram.h.
Referenced by SpectrogramComputer::Compute(), main(), and SpectrogramComputer::SpectrogramComputer().
raw_energy
bool raw_energy
Definition at line 41 of file feature-spectrogram.h.
Referenced by SpectrogramComputer::Compute().
The documentation for this struct was generated from the following file:
feat/feature-spectrogram.h