Kaldi: WspecifierOptions Struct Reference
WspecifierOptions Struct Reference
"Table types and related functions"
#include <kaldi-table.h>
Public Member Functions
WspecifierOptions ()
Public Attributes
bool binary
bool flush
bool permissive
Detailed Description
Definition at line 113 of file kaldi-table.h.
Constructor & Destructor Documentation
WspecifierOptions()
WspecifierOptions () inline
Definition at line 117 of file kaldi-table.h.
References kaldi::ClassifyWspecifier(), kaldi::ReadScriptFile(), and kaldi::WriteScriptFile().
 : binary(true), flush(false), permissive(false) { }
Member Data Documentation
binary
bool binary
Definition at line 114 of file kaldi-table.h.
Referenced by kaldi::ClassifyWspecifier(), and kaldi::UnitTestClassifyWspecifier().
flush
bool flush
Definition at line 115 of file kaldi-table.h.
Referenced by kaldi::ClassifyWspecifier(), and kaldi::UnitTestClassifyWspecifier().
permissive
bool permissive
Definition at line 116 of file kaldi-table.h.
Referenced by kaldi::ClassifyWspecifier().
The documentation for this struct was generated from the following file:
util/kaldi-table.h