Kaldi: CachingOptimizingCompilerOptions Struct Reference
CachingOptimizingCompilerOptions Struct Reference
#include <nnet-optimize.h>
Public Member Functions
CachingOptimizingCompilerOptions ()
void Register (OptionsItf *opts)
Public Attributes
bool use_shortcut
int32 cache_capacity
Detailed Description
Definition at line 192 of file nnet-optimize.h.
Constructor & Destructor Documentation
CachingOptimizingCompilerOptions()
CachingOptimizingCompilerOptions () inline
Definition at line 196 of file nnet-optimize.h.
                                     :
       use_shortcut(true),
       cache_capacity(64) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 200 of file nnet-optimize.h.
References OptionsItf::Register().
Referenced by main(), NnetTrainerOptions::Register(), and NnetComputeProbOptions::Register().
{
     opts->Register("use-shortcut", &use_shortcut,
                    "If true, use the 'shortcut' in compilation whereby "
                    "computation requests with regular structure are identified "
                    "as such, a computation with a smaller number of distinct "
                    "values of 'n' is compiled (e.g. 2), and the compiled "
                    "computation is expanded to match the size of the real "
                    "computation request.");
     opts->Register("cache-capacity", &cache_capacity,
                    "Determines how many computations the computation-cache will "
                    "store (most-recently-used).");
   }
Member Data Documentation
cache_capacity
int32 cache_capacity
Definition at line 194 of file nnet-optimize.h.
Referenced by NnetSimpleComputationOptions::NnetSimpleComputationOptions().
use_shortcut
bool use_shortcut
Definition at line 193 of file nnet-optimize.h.
Referenced by CachingOptimizingCompiler::CompileInternal(), and kaldi::nnet3::UnitTestNnetOptimizeInternal().
The documentation for this struct was generated from the following file:
nnet3/nnet-optimize.h