Kaldi: NnetSimpleComputationOptions Struct Reference
NnetSimpleComputationOptions Struct Reference
#include <nnet-am-decodable-simple.h>
Public Member Functions
NnetSimpleComputationOptions ()
void Register (OptionsItf *opts)
Public Attributes
int32 extra_left_context
int32 extra_right_context
int32 extra_left_context_initial
int32 extra_right_context_final
int32 frame_subsampling_factor
int32 frames_per_chunk
BaseFloat acoustic_scale
bool debug_computation
NnetOptimizeOptions optimize_config
NnetComputeOptions compute_config
CachingOptimizingCompilerOptions compiler_config
Detailed Description
Definition at line 43 of file nnet-am-decodable-simple.h.
Constructor & Destructor Documentation
NnetSimpleComputationOptions()
NnetSimpleComputationOptions () inline
Definition at line 56 of file nnet-am-decodable-simple.h.
References CachingOptimizingCompilerOptions::cache_capacity, and NnetSimpleComputationOptions::frames_per_chunk.
                                 :
       extra_left_context(0),
       extra_right_context(0),
       extra_left_context_initial(-1),
       extra_right_context_final(-1),
       frame_subsampling_factor(1),
       frames_per_chunk(50),
       acoustic_scale(0.1),
       debug_computation(false) {
     compiler_config.cache_capacity += frames_per_chunk;
   }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 68 of file nnet-am-decodable-simple.h.
References OptionsItf::Register(), NnetComputeOptions::Register(), and NnetOptimizeOptions::Register().
Referenced by main().
{
     opts->Register("extra-left-context", &extra_left_context,
                    "Number of frames of additional left-context to add on top "
                    "of the neural net's inherent left context (may be useful in "
                    "recurrent setups");
     opts->Register("extra-right-context", &extra_right_context,
                    "Number of frames of additional right-context to add on top "
                    "of the neural net's inherent right context (may be useful in "
                    "recurrent setups");
     opts->Register("extra-left-context-initial", &extra_left_context_initial,
                    "If >= 0, overrides the --extra-left-context value at the "
                    "start of an utterance.");
     opts->Register("extra-right-context-final", &extra_right_context_final,
                    "If >= 0, overrides the --extra-right-context value at the "
                    "end of an utterance.");
     opts->Register("frame-subsampling-factor", &frame_subsampling_factor,
                    "Required if the frame-rate of the output (e.g. in 'chain' "
                    "models) is less than the frame-rate of the original "
                    "alignment.");
     opts->Register("acoustic-scale", &acoustic_scale,
                    "Scaling factor for acoustic log-likelihoods (caution: is a no-op "
                    "if set in the program nnet3-compute");
     opts->Register("frames-per-chunk", &frames_per_chunk,
                    "Number of frames in each chunk that is separately evaluated "
                    "by the neural net.  Measured before any subsampling, if the "
                    "--frame-subsampling-factor options is used (i.e. counts "
                    "input frames");
     opts->Register("debug-computation", &debug_computation, "If true, turn on "
                    "debug for the actual computation (very verbose!)");
     // register the optimization options with the prefix "optimization".
     ParseOptions optimization_opts("optimization", opts);
     optimize_config.Register(&optimization_opts);
     // register the compute options with the prefix "computation".
     ParseOptions compute_opts("computation", opts);
     compute_config.Register(&compute_opts);
   }
Member Data Documentation
acoustic_scale
BaseFloat acoustic_scale
Definition at line 50 of file nnet-am-decodable-simple.h.
Referenced by main().
compiler_config
CachingOptimizingCompilerOptions compiler_config
Definition at line 54 of file nnet-am-decodable-simple.h.
compute_config
NnetComputeOptions compute_config
Definition at line 53 of file nnet-am-decodable-simple.h.
debug_computation
bool debug_computation
Definition at line 51 of file nnet-am-decodable-simple.h.
extra_left_context
int32 extra_left_context
Definition at line 44 of file nnet-am-decodable-simple.h.
extra_left_context_initial
int32 extra_left_context_initial
Definition at line 46 of file nnet-am-decodable-simple.h.
extra_right_context
int32 extra_right_context
Definition at line 45 of file nnet-am-decodable-simple.h.
extra_right_context_final
int32 extra_right_context_final
Definition at line 47 of file nnet-am-decodable-simple.h.
frame_subsampling_factor
int32 frame_subsampling_factor
Definition at line 48 of file nnet-am-decodable-simple.h.
Referenced by DecodableNnetSimple::DecodableNnetSimple(), and main().
frames_per_chunk
int32 frames_per_chunk
Definition at line 49 of file nnet-am-decodable-simple.h.
Referenced by NnetSimpleComputationOptions::NnetSimpleComputationOptions(), and kaldi::nnet3::TestNnetDecodable().
optimize_config
NnetOptimizeOptions optimize_config
Definition at line 52 of file nnet-am-decodable-simple.h.
Referenced by main().
The documentation for this struct was generated from the following file:
nnet3/nnet-am-decodable-simple.h