Kaldi: NnetFixConfig Struct Reference
NnetFixConfig Struct Reference
#include <nnet-fix.h>
Public Member Functions
NnetFixConfig ()
void Register (OptionsItf *opts)
Public Attributes
BaseFloat min_average_deriv
BaseFloat max_average_deriv
BaseFloat parameter_factor
BaseFloat relu_bias_change
Detailed Description
Definition at line 42 of file nnet-fix.h.
Constructor & Destructor Documentation
NnetFixConfig()
NnetFixConfig () inline
Definition at line 52 of file nnet-fix.h.
                  : min_average_deriv(0.1), max_average_deriv(0.75),
                    parameter_factor(2.0), relu_bias_change(1.0) { }
Member Function Documentation
Register()
void Register (OptionsItf * opts) inline
Definition at line 54 of file nnet-fix.h.
References kaldi::nnet2::FixNnet(), and OptionsItf::Register().
Referenced by main().
{
     opts->Register("min-average-deriv", &min_average_deriv, "Miniumum derivative, "
                    "averaged over the training data, that we allow for a nonlinearity,"
                    "expressed relative to the maximum derivative of the nonlinearity,"
                    "i.e. 1.0 for tanh or 0.25 for sigmoid, 1.0 for rectified linear.");
     opts->Register("max-average-deriv", &max_average_deriv, "Maximum derivative, "
                    "averaged over the training data, that we allow for the nonlinearity "
                    "associated with one neuron.");
     opts->Register("parameter-factor", &parameter_factor, "Maximum factor by which we change "
                    "the set of parameters associated with a neuron.");
     opts->Register("relu-bias-change", &relu_bias_change, "For ReLUs, change in bias when "
                    "we identify a component that's too frequently on or off.");
   }
Member Data Documentation
max_average_deriv
BaseFloat max_average_deriv
Definition at line 46 of file nnet-fix.h.
Referenced by kaldi::nnet2::FixNnet().
min_average_deriv
BaseFloat min_average_deriv
Definition at line 43 of file nnet-fix.h.
Referenced by kaldi::nnet2::FixNnet().
parameter_factor
BaseFloat parameter_factor
Definition at line 48 of file nnet-fix.h.
Referenced by kaldi::nnet2::FixNnet().
relu_bias_change
BaseFloat relu_bias_change
Definition at line 50 of file nnet-fix.h.
Referenced by kaldi::nnet2::FixNnet().
The documentation for this struct was generated from the following file:
nnet2/nnet-fix.h