Kaldi: featbin/subsample-feats.cc File Reference
subsample-feats.cc File Reference
#include <sstream>
#include <algorithm>
#include <iterator>
#include <utility>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-matrix.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 30 of file subsample-feats.cc.
References VectorBase< Real >::CopyFromVec(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), rnnlm::i, KALDI_ASSERT, KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), rnnlm::n, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), MatrixBase< Real >::Row(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     using namespace std;
     const char *usage =
         "Sub-samples features by taking every n'th frame.\n"
         "With negative values of n, will repeat each frame n times\n"
         "(e.g. --n=-2 will repeat each frame twice)\n"
         "\n"
         "Usage: subsample-feats [options] <in-rspecifier> <out-wspecifier>\n"
         "  e.g. subsample-feats --n=2 ark:- ark:-\n";
     ParseOptions po(usage);
     int32 n = 1, offset = 0;
     po.Register("n", &n, "Take every n'th feature, for this value of n"
                 "(with negative value, repeats each feature n times)");
     po.Register("offset", &offset, "Start with the feature with this offset, "
                 "then take every n'th feature.");
     KALDI_ASSERT(n != 0);
     if (n < 0)
       KALDI_ASSERT(offset == 0 &&
                    "--offset option cannot be used with negative n.");
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     string rspecifier = po.GetArg(1);
     string wspecifier = po.GetArg(2);
     SequentialBaseFloatMatrixReader feat_reader(rspecifier);
     BaseFloatMatrixWriter feat_writer(wspecifier);
     int32 num_done = 0, num_err = 0;
     int64 frames_in = 0, frames_out = 0;
     // process all keys
     for (; !feat_reader.Done(); feat_reader.Next()) {
       std::string utt = feat_reader.Key();
       const Matrix<BaseFloat> feats(feat_reader.Value());
       if (n > 0) {
         // This code could, of course, be much more efficient; I'm just
         // keeping it simple.
         int32 num_indexes = 0;
         for (int32 k = offset; k < feats.NumRows(); k += n)
           num_indexes++; // k is the index.
         frames_in += feats.NumRows();
         frames_out += num_indexes;
         if (num_indexes == 0) {
           KALDI_WARN << "For utterance " << utt << ", output would have no rows, "
                      << "producing no output.";
           num_err++;
           continue;
         }
         Matrix<BaseFloat> output(num_indexes, feats.NumCols());
         int32 i = 0;
         for (int32 k = offset; k < feats.NumRows(); k += n, i++) {
           SubVector<BaseFloat> src(feats, k), dest(output, i);
           dest.CopyFromVec(src);
         }
         KALDI_ASSERT(i == num_indexes);
         feat_writer.Write(utt, output);
         num_done++;
       } else {
         int32 repeat = -n;
         Matrix<BaseFloat> output(feats.NumRows() * repeat, feats.NumCols());
         for (int32 i = 0; i < output.NumRows(); i++)
           output.Row(i).CopyFromVec(feats.Row(i / repeat));
         frames_in += feats.NumRows();
         frames_out += feats.NumRows() * repeat;
         feat_writer.Write(utt, output);
         num_done++;
       }
     }
     KALDI_LOG << "Processed " << num_done << " feature matrices; " << num_err
               << " with errors.";
     KALDI_LOG << "Processed " << frames_in << " input frames and "
               << frames_out << " output frames.";
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }