Kaldi: util/text-utils-test.cc File Reference
text-utils-test.cc File Reference
#include "base/kaldi-common.h"
#include "util/text-utils.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
char GetRandChar ()
char GetRandDelim ()
void TestSplitStringToVector ()
void TestSplitStringToIntegers ()
void TestSplitStringToFloats ()
void TestConvertStringToInteger ()
template<class Real >
void TestConvertStringToReal ()
template<class Real >
void TestNan ()
template<class Real >
void TestInf ()
std::string TrimTmp (std::string s)
void TestTrim ()
void TestSplitStringOnFirstSpace ()
void TestIsToken ()
void TestIsLine ()
void TestStringsApproxEqual ()
int main ()
Variables
const char * ws_delim = " \t\n\r"
Function Documentation
main()
int main ()
Definition at line 330 of file text-utils-test.cc.
References kaldi::TestConvertStringToInteger(), kaldi::TestIsLine(), kaldi::TestIsToken(), kaldi::TestSplitStringOnFirstSpace(), kaldi::TestSplitStringToFloats(), kaldi::TestSplitStringToIntegers(), kaldi::TestSplitStringToVector(), kaldi::TestStringsApproxEqual(), and kaldi::TestTrim().
            {
   using namespace kaldi;
   TestSplitStringToVector();
   TestSplitStringToIntegers();
   TestSplitStringToFloats();
   TestConvertStringToInteger();
   TestConvertStringToReal<float>();
   TestConvertStringToReal<double>();
   TestTrim();
   TestSplitStringOnFirstSpace();
   TestIsToken();
   TestIsLine();
   TestStringsApproxEqual();
   TestNan<float>();
   TestNan<double>();
   TestInf<float>();
   TestInf<double>();
   std::cout << "Test OK\n";
 }