Kaldi: bin/transform-vec.cc File Reference
transform-vec.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-matrix.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 26 of file transform-vec.cc.
References VectorBase< Real >::AddMatVec(), VectorBase< Real >::CopyColFromMat(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_ERR, KALDI_LOG, SequentialTableReader< Holder >::Key(), kaldi::kNoTrans, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), MatrixBase< Real >::Range(), ParseOptions::Read(), kaldi::ReadKaldiObject(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     const char *usage =
         "This program applies a linear or affine transform to individual vectors, e.g.\n"
         "iVectors.  It is transform-feats, except it works on vectors rather than matrices,\n"
         "and expects a single transform matrix rather than possibly a table of matrices\n"
         "\n"
         "Usage: transform-vec [options] <transform-rxfilename> <feats-rspecifier> <feats-wspecifier>\n"
         "See also: transform-feats, est-pca\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string transform_rxfilename = po.GetArg(1);
     std::string vec_rspecifier = po.GetArg(2);
     std::string vec_wspecifier = po.GetArg(3);
     SequentialBaseFloatVectorReader vec_reader(vec_rspecifier);
     BaseFloatVectorWriter vec_writer(vec_wspecifier);
     Matrix<BaseFloat> transform;
     ReadKaldiObject(transform_rxfilename, &transform);
     int32 num_done = 0;
     for (; !vec_reader.Done(); vec_reader.Next()) {
       std::string key = vec_reader.Key();
       const Vector<BaseFloat> &vec(vec_reader.Value());
       int32 transform_rows = transform.NumRows(),
           transform_cols = transform.NumCols(),
           vec_dim = vec.Dim();
       Vector<BaseFloat> vec_out(transform_rows);
       if (transform_cols == vec_dim) {
         vec_out.AddMatVec(1.0, transform, kNoTrans, vec, 0.0);
       } else {
         if (transform_cols != vec_dim + 1) {
           KALDI_ERR << "Dimension mismatch: input vector has dimension "
                     << vec.Dim() << " and transform has " << transform_cols
                     << " columns.";
         }
         vec_out.CopyColFromMat(transform, vec_dim);
         vec_out.AddMatVec(1.0, transform.Range(0, transform.NumRows(),
                                                0, vec_dim), kNoTrans, vec, 1.0);
       }
       vec_writer.Write(key, vec_out);
       num_done++;
     }
     KALDI_LOG << "Applied transform to " << num_done << " vectors.";
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }