Kaldi: bin/vector-sum.cc File Reference
vector-sum.cc File Reference
#include <vector>
#include <string>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-vector.h"
#include "transform/transform-common.h"
Namespaces
kaldi
Relabels neural network egs with the read pdf-id alignments.
Functions
int32 TypeOneUsage (const ParseOptions &po)
int32 TypeTwoUsage (const ParseOptions &po, bool binary, bool average=false)
int32 TypeThreeUsage (const ParseOptions &po, bool binary)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 184 of file vector-sum.cc.
References kaldi::ClassifyRspecifier(), kaldi::ClassifyWspecifier(), ParseOptions::GetArg(), kaldi::kNoRspecifier, kaldi::kNoWspecifier, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), kaldi::TypeOneUsage(), kaldi::TypeThreeUsage(), and kaldi::TypeTwoUsage().
{
   try {
     using namespace kaldi;
     const char *usage =
         "Add vectors (e.g. weights, transition-accs; speaker vectors)\n"
         "If you need to scale the inputs, use vector-scale on the inputs\n"
         "\n"
         "Type one usage:\n"
         " vector-sum [options] <vector-in-rspecifier1> [<vector-in-rspecifier2>"
         " <vector-in-rspecifier3> ...] <vector-out-wspecifier>\n"
         "  e.g.: vector-sum ark:1.weights ark:2.weights ark:combine.weights\n"
         "Type two usage (sums a single table input to produce a single output):\n"
         " vector-sum [options] <vector-in-rspecifier> <vector-out-wxfilename>\n"
         " e.g.: vector-sum --binary=false vecs.ark sum.vec\n"
         "Type three usage (sums single-file inputs to produce a single output):\n"
         " vector-sum [options] <vector-in-rxfilename1> <vector-in-rxfilename2> ..."
         " <vector-out-wxfilename>\n"
         " e.g.: vector-sum --binary=false 1.vec 2.vec 3.vec sum.vec\n"
         "See also: copy-vector, dot-weights\n";
     bool binary, average = false;
     ParseOptions po(usage);
     po.Register("binary", &binary, "If true, write output as binary (only "
                 "relevant for usage types two or three");
     po.Register("average", &average, "Do average instead of sum");
     po.Read(argc, argv);
     int32 N = po.NumArgs(), exit_status;
     if (po.NumArgs() >= 2 &&
         ClassifyWspecifier(po.GetArg(N), NULL, NULL, NULL) != kNoWspecifier) {
       // output to table.
       exit_status = TypeOneUsage(po);
     } else if (po.NumArgs() == 2 &&
                ClassifyRspecifier(po.GetArg(1), NULL, NULL) != kNoRspecifier &&
                ClassifyWspecifier(po.GetArg(N), NULL, NULL, NULL) ==
                kNoWspecifier) {
       // input from a single table, output not to table.
       exit_status = TypeTwoUsage(po, binary, average);
     } else if (po.NumArgs() >= 2 &&
                ClassifyRspecifier(po.GetArg(1), NULL, NULL) == kNoRspecifier &&
                ClassifyWspecifier(po.GetArg(N), NULL, NULL, NULL) ==
                kNoWspecifier) {
       // summing flat files.
       exit_status = TypeThreeUsage(po, binary);
     } else {
       po.PrintUsage();
       exit(1);
     }
     return exit_status;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }