Kaldi: feat/wave-reader-test.cc File Reference
wave-reader-test.cc File Reference
#include <iostream>
#include "base/kaldi-math.h"
#include "feat/wave-reader.h"
#include "matrix/kaldi-matrix.h"
Macros
#define BY(n, k) ((char)((uint32)(n) >> (8 * (k)) & 0xFF))
#define WRD(n) BY(n,0), BY(n,1)
#define DWRD(n) BY(n,0), BY(n,1), BY(n,2), BY(n,3)
Functions
static void UnitTestStereo8K ()
static void UnitTestMono22K ()
static void UnitTestEndless1 ()
static void UnitTestEndless2 ()
static void UnitTest ()
int main ()
Macro Definition Documentation
BY
#define BY (n, k) ((char)((uint32)(n) >> (8 * (k)) & 0xFF))
Definition at line 29 of file wave-reader-test.cc.
DWRD
#define DWRD (n) BY(n,0), BY(n,1), BY(n,2), BY(n,3)
Definition at line 31 of file wave-reader-test.cc.
Referenced by UnitTestEndless1(), UnitTestEndless2(), UnitTestMono22K(), and UnitTestStereo8K().
WRD
#define WRD (n) BY(n,0), BY(n,1)
Definition at line 30 of file wave-reader-test.cc.
Referenced by UnitTestEndless1(), UnitTestEndless2(), UnitTestMono22K(), and UnitTestStereo8K().
Function Documentation
main()
int main ()
Definition at line 208 of file wave-reader-test.cc.
References UnitTest().
            {
   try {
     UnitTest();
     std::cout << "LGTM\n";
     return 0;
   } catch (const std::exception &e) {
     std::cerr << e.what();
     return 1;
   }
 }
UnitTest()
static void UnitTest () static
Definition at line 201 of file wave-reader-test.cc.
References UnitTestEndless1(), UnitTestEndless2(), UnitTestMono22K(), and UnitTestStereo8K().
Referenced by main().
{
   UnitTestStereo8K();
   UnitTestMono22K();
   UnitTestEndless1();
   UnitTestEndless2();
 }
UnitTestEndless1()
static void UnitTestEndless1 () static
Definition at line 127 of file wave-reader-test.cc.
References kaldi::AssertEqual(), WaveData::Data(), DWRD, WaveData::Read(), Matrix< Real >::Read(), and WRD.
Referenced by UnitTest().
{
   const int hz = 8000;
   const int byps = hz * 1 /* channels */ * 2 /* bytes/sample */;
   const char file_data[] = {
     'R', 'I', 'F', 'F',
     DWRD(0),    // File length unknown
     'W', 'A', 'V', 'E',
     'f', 'm', 't', ' ',
     DWRD(18),   // sizeof(struct WAVEFORMATEX)
     WRD(1),     // WORD  wFormatTag;
     WRD(1),     // WORD  nChannels;
     DWRD(hz),   // DWORD nSamplesPerSec;
     DWRD(byps), // DWORD nAvgBytesPerSec;
     WRD(2),     // WORD  nBlockAlign;
     WRD(16),    // WORD  wBitsPerSample;
     WRD(0),     // WORD  cbSize;
     'd', 'a', 't', 'a',
     DWRD(0),    // 'data' chunk length unknown.
     WRD(1), WRD(2), WRD(3)
   };
   const char expect_mat[] = "[ 1 2 3 ]";
   // Read binary file data.
   std::istringstream iws(std::string(file_data, sizeof file_data),
                          std::ios::in | std::ios::binary);
   WaveData wave;
   wave.Read(iws);
   // Read expected matrix.
   std::istringstream ies(expect_mat, std::ios::in);
   Matrix<BaseFloat> expected;
   expected.Read(ies, false /* text */);
   AssertEqual(wave.Data(), expected);
 }
UnitTestEndless2()
static void UnitTestEndless2 () static
Definition at line 164 of file wave-reader-test.cc.
References kaldi::AssertEqual(), WaveData::Data(), DWRD, WaveData::Read(), Matrix< Real >::Read(), and WRD.
Referenced by UnitTest().
{
   const int hz = 8000;
   const int byps = hz * 1 /* channels */ * 2 /* bytes/sample */;
   const char file_data[] = {
     'R', 'I', 'F', 'F',
     DWRD(-1),   // File length unknown
     'W', 'A', 'V', 'E',
     'f', 'm', 't', ' ',
     DWRD(18),   // sizeof(struct WAVEFORMATEX)
     WRD(1),     // WORD  wFormatTag;
     WRD(1),     // WORD  nChannels;
     DWRD(hz),   // DWORD nSamplesPerSec;
     DWRD(byps), // DWORD nAvgBytesPerSec;
     WRD(2),     // WORD  nBlockAlign;
     WRD(16),    // WORD  wBitsPerSample;
     WRD(0),     // WORD  cbSize;
     'd', 'a', 't', 'a',
     DWRD(-1),   // 'data' chunk length unknown.
     WRD(1), WRD(2), WRD(3)
   };
   const char expect_mat[] = "[ 1 2 3 ]";
   // Read binary file data.
   std::istringstream iws(std::string(file_data, sizeof file_data),
                          std::ios::in | std::ios::binary);
   WaveData wave;
   wave.Read(iws);
   // Read expected matrix.
   std::istringstream ies(expect_mat, std::ios::in);
   Matrix<BaseFloat> expected;
   expected.Read(ies, false /* text */);
   AssertEqual(wave.Data(), expected);
 }
UnitTestMono22K()
static void UnitTestMono22K () static
Definition at line 81 of file wave-reader-test.cc.
References kaldi::AssertEqual(), WaveData::Data(), WaveData::Duration(), DWRD, WaveData::Read(), Matrix< Real >::Read(), WaveData::SampFreq(), and WRD.
Referenced by UnitTest().
{
   /* Reference file written with Adobe Audition (random data):
 00000000  52 49 46 46 30 00 00 00  57 41 56 45 66 6d 74 20  |RIFF0...WAVEfmt |
 00000010  12 00 00 00 01 00 01 00  22 56 00 00 44 ac 00 00  |........"V..D...|
 00000020  02 00 10 00 00 00 64 61  74 61 0a 00 00 00 25 36  |......data....%6|
 00000030  cb 41 1b 4d 04 4e 62 3d                           |.A.M.Nb=|
   */
   const int hz = 22050;
   const int byps = hz * 1 /* channels */ * 2 /* bytes/sample */;
   const char file_data[] = {
     'R', 'I', 'F', 'F',
     DWRD(48),   // File length after this point.
     'W', 'A', 'V', 'E',
     'f', 'm', 't', ' ',
     DWRD(18),   // sizeof(struct WAVEFORMATEX)
     WRD(1),     // WORD  wFormatTag;
     WRD(1),     // WORD  nChannels;
     DWRD(hz),   // DWORD nSamplesPerSec;
     DWRD(byps), // DWORD nAvgBytesPerSec;
     WRD(2),     // WORD  nBlockAlign;
     WRD(16),    // WORD  wBitsPerSample;
     WRD(0),     // WORD  cbSize;
     'd', 'a', 't', 'a',
     DWRD(10),   // 'data' chunk length.
     WRD(0), WRD(-1), WRD(-32768), WRD(32767), WRD(1)
   };
   const char expect_mat[] = "[ 0 -1 -32768 32767 1 ]";
   // Read binary file data.
   std::istringstream iws(std::string(file_data, sizeof file_data),
                          std::ios::in | std::ios::binary);
   WaveData wave;
   wave.Read(iws);
   // Read expected matrix.
   std::istringstream ies(expect_mat, std::ios::in);
   Matrix<BaseFloat> expected;
   expected.Read(ies, false /* text */);
   AssertEqual(wave.SampFreq(), hz, 0);
   AssertEqual(wave.Duration(), 5.0 /* samples */ / hz /* Hz */, 1E-6);
   AssertEqual(wave.Data(), expected);
 }
UnitTestStereo8K()
static void UnitTestStereo8K () static
Definition at line 33 of file wave-reader-test.cc.
References kaldi::AssertEqual(), WaveData::Data(), WaveData::Duration(), DWRD, WaveData::Read(), Matrix< Real >::Read(), WaveData::SampFreq(), and WRD.
Referenced by UnitTest().
{
   /* Reference file written with Adobe Audition (random data):
 00000000  52 49 46 46 32 00 00 00  57 41 56 45 66 6d 74 20  |RIFF2...WAVEfmt |
 00000010  12 00 00 00 01 00 02 00  40 1f 00 00 00 7d 00 00  |........@....}..|
 00000020  04 00 10 00 00 00 64 61  74 61 0c 00 00 00 00 00  |......data......|
 00000030  31 51 ff 21 f4 63 38 4c  26 60                    |1Q.!.c8L&`|
   */
   const int hz = 8000;
   const int byps = hz * 2 /* channels */ * 2 /* bytes/sample */;
   const char file_data[] = {
     'R', 'I', 'F', 'F',
     DWRD(50),   // File length after this point.
     'W', 'A', 'V', 'E',
     'f', 'm', 't', ' ',
     DWRD(18),   // sizeof(struct WAVEFORMATEX)
     WRD(1),     // WORD  wFormatTag;
     WRD(2),     // WORD  nChannels;
     DWRD(hz),   // DWORD nSamplesPerSec; 40 1f 00 00
     DWRD(byps), // DWORD nAvgBytesPerSec; 00 7d 00 00
     WRD(4),     // WORD  nBlockAlign;
     WRD(16),    // WORD  wBitsPerSample;
     WRD(0),     // WORD  cbSize;
     'd', 'a', 't', 'a',
     DWRD(12),   // 'data' chunk length.
     WRD(0), WRD(-1),
     WRD(-32768), WRD(0),
     WRD(32767), WRD(1)
   };
   const char expect_mat[] = "[ 0 -32768 32767 \n -1 0 1 ]";
   // Read binary file data.
   std::istringstream iws(std::string(file_data, sizeof file_data),
                          std::ios::in | std::ios::binary);
   WaveData wave;
   wave.Read(iws);
   // Read expected wave data.
   std::istringstream ies(expect_mat, std::ios::in);
   Matrix<BaseFloat> expected;
   expected.Read(ies, false /* text */);
   AssertEqual(wave.SampFreq(), hz, 0);
   AssertEqual(wave.Duration(), 3.0 /* samples */ / hz /* Hz */, 1E-6);
   AssertEqual(wave.Data(), expected);
 }