"""voices table

Revision ID: ba035d257f37
Revises: d7f48fe1e039
Create Date: 2018-07-19 14:41:45.016471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba035d257f37'
down_revision = 'd7f48fe1e039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('accent', sa.String(length=2), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('directory', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice')
    # ### end Alembic commands ###
