# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyIdlak_nnet_forward', [dirname(__file__)])
        except ImportError:
            import _pyIdlak_nnet_forward
            return _pyIdlak_nnet_forward
        if fp is not None:
            try:
                _mod = imp.load_module('_pyIdlak_nnet_forward', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyIdlak_nnet_forward = swig_import_helper()
    del swig_import_helper
else:
    import _pyIdlak_nnet_forward
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIdlak_nnet_forward.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _pyIdlak_nnet_forward.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyIdlak_nnet_forward.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyIdlak_nnet_forward.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyIdlak_nnet_forward.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyIdlak_nnet_forward.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyIdlak_nnet_forward.SwigPyIterator_copy(self)

    def next(self):
        return _pyIdlak_nnet_forward.SwigPyIterator_next(self)

    def __next__(self):
        return _pyIdlak_nnet_forward.SwigPyIterator___next__(self)

    def previous(self):
        return _pyIdlak_nnet_forward.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyIdlak_nnet_forward.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyIdlak_nnet_forward.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyIdlak_nnet_forward.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyIdlak_nnet_forward.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyIdlak_nnet_forward.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyIdlak_nnet_forward.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyIdlak_nnet_forward.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _pyIdlak_nnet_forward.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIdlak_nnet_forward.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyIdlak_nnet_forward.IntVector___nonzero__(self)

    def __bool__(self):
        return _pyIdlak_nnet_forward.IntVector___bool__(self)

    def __len__(self):
        return _pyIdlak_nnet_forward.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _pyIdlak_nnet_forward.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyIdlak_nnet_forward.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyIdlak_nnet_forward.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyIdlak_nnet_forward.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIdlak_nnet_forward.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIdlak_nnet_forward.IntVector___setitem__(self, *args)

    def pop(self):
        return _pyIdlak_nnet_forward.IntVector_pop(self)

    def append(self, x):
        return _pyIdlak_nnet_forward.IntVector_append(self, x)

    def empty(self):
        return _pyIdlak_nnet_forward.IntVector_empty(self)

    def size(self):
        return _pyIdlak_nnet_forward.IntVector_size(self)

    def swap(self, v):
        return _pyIdlak_nnet_forward.IntVector_swap(self, v)

    def begin(self):
        return _pyIdlak_nnet_forward.IntVector_begin(self)

    def end(self):
        return _pyIdlak_nnet_forward.IntVector_end(self)

    def rbegin(self):
        return _pyIdlak_nnet_forward.IntVector_rbegin(self)

    def rend(self):
        return _pyIdlak_nnet_forward.IntVector_rend(self)

    def clear(self):
        return _pyIdlak_nnet_forward.IntVector_clear(self)

    def get_allocator(self):
        return _pyIdlak_nnet_forward.IntVector_get_allocator(self)

    def pop_back(self):
        return _pyIdlak_nnet_forward.IntVector_pop_back(self)

    def erase(self, *args):
        return _pyIdlak_nnet_forward.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyIdlak_nnet_forward.new_IntVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _pyIdlak_nnet_forward.IntVector_push_back(self, x)

    def front(self):
        return _pyIdlak_nnet_forward.IntVector_front(self)

    def back(self):
        return _pyIdlak_nnet_forward.IntVector_back(self)

    def assign(self, n, x):
        return _pyIdlak_nnet_forward.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIdlak_nnet_forward.IntVector_resize(self, *args)

    def insert(self, *args):
        return _pyIdlak_nnet_forward.IntVector_insert(self, *args)

    def reserve(self, n):
        return _pyIdlak_nnet_forward.IntVector_reserve(self, n)

    def capacity(self):
        return _pyIdlak_nnet_forward.IntVector_capacity(self)
    __swig_destroy__ = _pyIdlak_nnet_forward.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _pyIdlak_nnet_forward.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIdlak_nnet_forward.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyIdlak_nnet_forward.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _pyIdlak_nnet_forward.DoubleVector___bool__(self)

    def __len__(self):
        return _pyIdlak_nnet_forward.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _pyIdlak_nnet_forward.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyIdlak_nnet_forward.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyIdlak_nnet_forward.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyIdlak_nnet_forward.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIdlak_nnet_forward.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIdlak_nnet_forward.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _pyIdlak_nnet_forward.DoubleVector_pop(self)

    def append(self, x):
        return _pyIdlak_nnet_forward.DoubleVector_append(self, x)

    def empty(self):
        return _pyIdlak_nnet_forward.DoubleVector_empty(self)

    def size(self):
        return _pyIdlak_nnet_forward.DoubleVector_size(self)

    def swap(self, v):
        return _pyIdlak_nnet_forward.DoubleVector_swap(self, v)

    def begin(self):
        return _pyIdlak_nnet_forward.DoubleVector_begin(self)

    def end(self):
        return _pyIdlak_nnet_forward.DoubleVector_end(self)

    def rbegin(self):
        return _pyIdlak_nnet_forward.DoubleVector_rbegin(self)

    def rend(self):
        return _pyIdlak_nnet_forward.DoubleVector_rend(self)

    def clear(self):
        return _pyIdlak_nnet_forward.DoubleVector_clear(self)

    def get_allocator(self):
        return _pyIdlak_nnet_forward.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _pyIdlak_nnet_forward.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _pyIdlak_nnet_forward.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyIdlak_nnet_forward.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _pyIdlak_nnet_forward.DoubleVector_push_back(self, x)

    def front(self):
        return _pyIdlak_nnet_forward.DoubleVector_front(self)

    def back(self):
        return _pyIdlak_nnet_forward.DoubleVector_back(self)

    def assign(self, n, x):
        return _pyIdlak_nnet_forward.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIdlak_nnet_forward.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _pyIdlak_nnet_forward.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _pyIdlak_nnet_forward.DoubleVector_reserve(self, n)

    def capacity(self):
        return _pyIdlak_nnet_forward.DoubleVector_capacity(self)
    __swig_destroy__ = _pyIdlak_nnet_forward.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _pyIdlak_nnet_forward.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIdlak_nnet_forward.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyIdlak_nnet_forward.StringVector___nonzero__(self)

    def __bool__(self):
        return _pyIdlak_nnet_forward.StringVector___bool__(self)

    def __len__(self):
        return _pyIdlak_nnet_forward.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _pyIdlak_nnet_forward.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyIdlak_nnet_forward.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyIdlak_nnet_forward.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyIdlak_nnet_forward.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIdlak_nnet_forward.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIdlak_nnet_forward.StringVector___setitem__(self, *args)

    def pop(self):
        return _pyIdlak_nnet_forward.StringVector_pop(self)

    def append(self, x):
        return _pyIdlak_nnet_forward.StringVector_append(self, x)

    def empty(self):
        return _pyIdlak_nnet_forward.StringVector_empty(self)

    def size(self):
        return _pyIdlak_nnet_forward.StringVector_size(self)

    def swap(self, v):
        return _pyIdlak_nnet_forward.StringVector_swap(self, v)

    def begin(self):
        return _pyIdlak_nnet_forward.StringVector_begin(self)

    def end(self):
        return _pyIdlak_nnet_forward.StringVector_end(self)

    def rbegin(self):
        return _pyIdlak_nnet_forward.StringVector_rbegin(self)

    def rend(self):
        return _pyIdlak_nnet_forward.StringVector_rend(self)

    def clear(self):
        return _pyIdlak_nnet_forward.StringVector_clear(self)

    def get_allocator(self):
        return _pyIdlak_nnet_forward.StringVector_get_allocator(self)

    def pop_back(self):
        return _pyIdlak_nnet_forward.StringVector_pop_back(self)

    def erase(self, *args):
        return _pyIdlak_nnet_forward.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyIdlak_nnet_forward.new_StringVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _pyIdlak_nnet_forward.StringVector_push_back(self, x)

    def front(self):
        return _pyIdlak_nnet_forward.StringVector_front(self)

    def back(self):
        return _pyIdlak_nnet_forward.StringVector_back(self)

    def assign(self, n, x):
        return _pyIdlak_nnet_forward.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIdlak_nnet_forward.StringVector_resize(self, *args)

    def insert(self, *args):
        return _pyIdlak_nnet_forward.StringVector_insert(self, *args)

    def reserve(self, n):
        return _pyIdlak_nnet_forward.StringVector_reserve(self, n)

    def capacity(self):
        return _pyIdlak_nnet_forward.StringVector_capacity(self)
    __swig_destroy__ = _pyIdlak_nnet_forward.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _pyIdlak_nnet_forward.StringVector_swigregister
StringVector_swigregister(StringVector)

class ConstCharVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ConstCharVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ConstCharVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIdlak_nnet_forward.ConstCharVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyIdlak_nnet_forward.ConstCharVector___nonzero__(self)

    def __bool__(self):
        return _pyIdlak_nnet_forward.ConstCharVector___bool__(self)

    def __len__(self):
        return _pyIdlak_nnet_forward.ConstCharVector___len__(self)

    def __getslice__(self, i, j):
        return _pyIdlak_nnet_forward.ConstCharVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyIdlak_nnet_forward.ConstCharVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyIdlak_nnet_forward.ConstCharVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyIdlak_nnet_forward.ConstCharVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIdlak_nnet_forward.ConstCharVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIdlak_nnet_forward.ConstCharVector___setitem__(self, *args)

    def pop(self):
        return _pyIdlak_nnet_forward.ConstCharVector_pop(self)

    def append(self, x):
        return _pyIdlak_nnet_forward.ConstCharVector_append(self, x)

    def empty(self):
        return _pyIdlak_nnet_forward.ConstCharVector_empty(self)

    def size(self):
        return _pyIdlak_nnet_forward.ConstCharVector_size(self)

    def swap(self, v):
        return _pyIdlak_nnet_forward.ConstCharVector_swap(self, v)

    def begin(self):
        return _pyIdlak_nnet_forward.ConstCharVector_begin(self)

    def end(self):
        return _pyIdlak_nnet_forward.ConstCharVector_end(self)

    def rbegin(self):
        return _pyIdlak_nnet_forward.ConstCharVector_rbegin(self)

    def rend(self):
        return _pyIdlak_nnet_forward.ConstCharVector_rend(self)

    def clear(self):
        return _pyIdlak_nnet_forward.ConstCharVector_clear(self)

    def get_allocator(self):
        return _pyIdlak_nnet_forward.ConstCharVector_get_allocator(self)

    def pop_back(self):
        return _pyIdlak_nnet_forward.ConstCharVector_pop_back(self)

    def erase(self, *args):
        return _pyIdlak_nnet_forward.ConstCharVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyIdlak_nnet_forward.new_ConstCharVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _pyIdlak_nnet_forward.ConstCharVector_push_back(self, x)

    def front(self):
        return _pyIdlak_nnet_forward.ConstCharVector_front(self)

    def back(self):
        return _pyIdlak_nnet_forward.ConstCharVector_back(self)

    def assign(self, n, x):
        return _pyIdlak_nnet_forward.ConstCharVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIdlak_nnet_forward.ConstCharVector_resize(self, *args)

    def insert(self, *args):
        return _pyIdlak_nnet_forward.ConstCharVector_insert(self, *args)

    def reserve(self, n):
        return _pyIdlak_nnet_forward.ConstCharVector_reserve(self, n)

    def capacity(self):
        return _pyIdlak_nnet_forward.ConstCharVector_capacity(self)
    __swig_destroy__ = _pyIdlak_nnet_forward.delete_ConstCharVector
    __del__ = lambda self: None
ConstCharVector_swigregister = _pyIdlak_nnet_forward.ConstCharVector_swigregister
ConstCharVector_swigregister(ConstCharVector)


def ForwardPass(opts):
    return _pyIdlak_nnet_forward.ForwardPass(opts)
ForwardPass = _pyIdlak_nnet_forward.ForwardPass
class PyNnetForwardOpts(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyNnetForwardOpts, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PyNnetForwardOpts, name)
    __repr__ = _swig_repr
    __swig_setmethods__["class_frame_counts"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_class_frame_counts_set
    __swig_getmethods__["class_frame_counts"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_class_frame_counts_get
    if _newclass:
        class_frame_counts = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_class_frame_counts_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_class_frame_counts_set)
    __swig_setmethods__["prior_scale"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_prior_scale_set
    __swig_getmethods__["prior_scale"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_prior_scale_get
    if _newclass:
        prior_scale = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_prior_scale_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_prior_scale_set)
    __swig_setmethods__["prior_floor"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_prior_floor_set
    __swig_getmethods__["prior_floor"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_prior_floor_get
    if _newclass:
        prior_floor = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_prior_floor_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_prior_floor_set)
    __swig_setmethods__["feature_transform"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_feature_transform_set
    __swig_getmethods__["feature_transform"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_feature_transform_get
    if _newclass:
        feature_transform = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_feature_transform_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_feature_transform_set)
    __swig_setmethods__["reverse_transform"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_reverse_transform_set
    __swig_getmethods__["reverse_transform"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_reverse_transform_get
    if _newclass:
        reverse_transform = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_reverse_transform_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_reverse_transform_set)
    __swig_setmethods__["no_softmax"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_no_softmax_set
    __swig_getmethods__["no_softmax"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_no_softmax_get
    if _newclass:
        no_softmax = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_no_softmax_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_no_softmax_set)
    __swig_setmethods__["apply_log"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_apply_log_set
    __swig_getmethods__["apply_log"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_apply_log_get
    if _newclass:
        apply_log = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_apply_log_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_apply_log_set)
    __swig_setmethods__["use_gpu"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_use_gpu_set
    __swig_getmethods__["use_gpu"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_use_gpu_get
    if _newclass:
        use_gpu = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_use_gpu_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_use_gpu_set)
    __swig_setmethods__["model_filename"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_model_filename_set
    __swig_getmethods__["model_filename"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_model_filename_get
    if _newclass:
        model_filename = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_model_filename_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_model_filename_set)
    __swig_setmethods__["feature_rspecifier"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_feature_rspecifier_set
    __swig_getmethods__["feature_rspecifier"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_feature_rspecifier_get
    if _newclass:
        feature_rspecifier = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_feature_rspecifier_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_feature_rspecifier_set)
    __swig_setmethods__["feature_wspecifier"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_feature_wspecifier_set
    __swig_getmethods__["feature_wspecifier"] = _pyIdlak_nnet_forward.PyNnetForwardOpts_feature_wspecifier_get
    if _newclass:
        feature_wspecifier = _swig_property(_pyIdlak_nnet_forward.PyNnetForwardOpts_feature_wspecifier_get, _pyIdlak_nnet_forward.PyNnetForwardOpts_feature_wspecifier_set)

    def __init__(self):
        this = _pyIdlak_nnet_forward.new_PyNnetForwardOpts()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _pyIdlak_nnet_forward.delete_PyNnetForwardOpts
    __del__ = lambda self: None
PyNnetForwardOpts_swigregister = _pyIdlak_nnet_forward.PyNnetForwardOpts_swigregister
PyNnetForwardOpts_swigregister(PyNnetForwardOpts)

# This file is compatible with both classic and new-style classes.


