# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pyIdlak_pylib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pyIdlak_pylib')
    _pyIdlak_pylib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyIdlak_pylib', [dirname(__file__)])
        except ImportError:
            import _pyIdlak_pylib
            return _pyIdlak_pylib
        try:
            _mod = imp.load_module('_pyIdlak_pylib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _pyIdlak_pylib = swig_import_helper()
    del swig_import_helper
else:
    import _pyIdlak_pylib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyIdlak_pylib.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _pyIdlak_pylib.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyIdlak_pylib.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyIdlak_pylib.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyIdlak_pylib.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyIdlak_pylib.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyIdlak_pylib.SwigPyIterator_copy(self)

    def next(self):
        return _pyIdlak_pylib.SwigPyIterator_next(self)

    def __next__(self):
        return _pyIdlak_pylib.SwigPyIterator___next__(self)

    def previous(self):
        return _pyIdlak_pylib.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyIdlak_pylib.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyIdlak_pylib.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyIdlak_pylib.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyIdlak_pylib.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyIdlak_pylib.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyIdlak_pylib.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyIdlak_pylib.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _pyIdlak_pylib.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIdlak_pylib.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyIdlak_pylib.IntVector___nonzero__(self)

    def __bool__(self):
        return _pyIdlak_pylib.IntVector___bool__(self)

    def __len__(self):
        return _pyIdlak_pylib.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _pyIdlak_pylib.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyIdlak_pylib.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyIdlak_pylib.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyIdlak_pylib.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIdlak_pylib.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIdlak_pylib.IntVector___setitem__(self, *args)

    def pop(self):
        return _pyIdlak_pylib.IntVector_pop(self)

    def append(self, x):
        return _pyIdlak_pylib.IntVector_append(self, x)

    def empty(self):
        return _pyIdlak_pylib.IntVector_empty(self)

    def size(self):
        return _pyIdlak_pylib.IntVector_size(self)

    def swap(self, v):
        return _pyIdlak_pylib.IntVector_swap(self, v)

    def begin(self):
        return _pyIdlak_pylib.IntVector_begin(self)

    def end(self):
        return _pyIdlak_pylib.IntVector_end(self)

    def rbegin(self):
        return _pyIdlak_pylib.IntVector_rbegin(self)

    def rend(self):
        return _pyIdlak_pylib.IntVector_rend(self)

    def clear(self):
        return _pyIdlak_pylib.IntVector_clear(self)

    def get_allocator(self):
        return _pyIdlak_pylib.IntVector_get_allocator(self)

    def pop_back(self):
        return _pyIdlak_pylib.IntVector_pop_back(self)

    def erase(self, *args):
        return _pyIdlak_pylib.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyIdlak_pylib.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyIdlak_pylib.IntVector_push_back(self, x)

    def front(self):
        return _pyIdlak_pylib.IntVector_front(self)

    def back(self):
        return _pyIdlak_pylib.IntVector_back(self)

    def assign(self, n, x):
        return _pyIdlak_pylib.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIdlak_pylib.IntVector_resize(self, *args)

    def insert(self, *args):
        return _pyIdlak_pylib.IntVector_insert(self, *args)

    def reserve(self, n):
        return _pyIdlak_pylib.IntVector_reserve(self, n)

    def capacity(self):
        return _pyIdlak_pylib.IntVector_capacity(self)
    __swig_destroy__ = _pyIdlak_pylib.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _pyIdlak_pylib.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIdlak_pylib.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyIdlak_pylib.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _pyIdlak_pylib.DoubleVector___bool__(self)

    def __len__(self):
        return _pyIdlak_pylib.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _pyIdlak_pylib.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyIdlak_pylib.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyIdlak_pylib.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyIdlak_pylib.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIdlak_pylib.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIdlak_pylib.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _pyIdlak_pylib.DoubleVector_pop(self)

    def append(self, x):
        return _pyIdlak_pylib.DoubleVector_append(self, x)

    def empty(self):
        return _pyIdlak_pylib.DoubleVector_empty(self)

    def size(self):
        return _pyIdlak_pylib.DoubleVector_size(self)

    def swap(self, v):
        return _pyIdlak_pylib.DoubleVector_swap(self, v)

    def begin(self):
        return _pyIdlak_pylib.DoubleVector_begin(self)

    def end(self):
        return _pyIdlak_pylib.DoubleVector_end(self)

    def rbegin(self):
        return _pyIdlak_pylib.DoubleVector_rbegin(self)

    def rend(self):
        return _pyIdlak_pylib.DoubleVector_rend(self)

    def clear(self):
        return _pyIdlak_pylib.DoubleVector_clear(self)

    def get_allocator(self):
        return _pyIdlak_pylib.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _pyIdlak_pylib.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _pyIdlak_pylib.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyIdlak_pylib.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyIdlak_pylib.DoubleVector_push_back(self, x)

    def front(self):
        return _pyIdlak_pylib.DoubleVector_front(self)

    def back(self):
        return _pyIdlak_pylib.DoubleVector_back(self)

    def assign(self, n, x):
        return _pyIdlak_pylib.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIdlak_pylib.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _pyIdlak_pylib.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _pyIdlak_pylib.DoubleVector_reserve(self, n)

    def capacity(self):
        return _pyIdlak_pylib.DoubleVector_capacity(self)
    __swig_destroy__ = _pyIdlak_pylib.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _pyIdlak_pylib.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIdlak_pylib.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyIdlak_pylib.StringVector___nonzero__(self)

    def __bool__(self):
        return _pyIdlak_pylib.StringVector___bool__(self)

    def __len__(self):
        return _pyIdlak_pylib.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _pyIdlak_pylib.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyIdlak_pylib.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyIdlak_pylib.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyIdlak_pylib.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIdlak_pylib.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIdlak_pylib.StringVector___setitem__(self, *args)

    def pop(self):
        return _pyIdlak_pylib.StringVector_pop(self)

    def append(self, x):
        return _pyIdlak_pylib.StringVector_append(self, x)

    def empty(self):
        return _pyIdlak_pylib.StringVector_empty(self)

    def size(self):
        return _pyIdlak_pylib.StringVector_size(self)

    def swap(self, v):
        return _pyIdlak_pylib.StringVector_swap(self, v)

    def begin(self):
        return _pyIdlak_pylib.StringVector_begin(self)

    def end(self):
        return _pyIdlak_pylib.StringVector_end(self)

    def rbegin(self):
        return _pyIdlak_pylib.StringVector_rbegin(self)

    def rend(self):
        return _pyIdlak_pylib.StringVector_rend(self)

    def clear(self):
        return _pyIdlak_pylib.StringVector_clear(self)

    def get_allocator(self):
        return _pyIdlak_pylib.StringVector_get_allocator(self)

    def pop_back(self):
        return _pyIdlak_pylib.StringVector_pop_back(self)

    def erase(self, *args):
        return _pyIdlak_pylib.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyIdlak_pylib.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyIdlak_pylib.StringVector_push_back(self, x)

    def front(self):
        return _pyIdlak_pylib.StringVector_front(self)

    def back(self):
        return _pyIdlak_pylib.StringVector_back(self)

    def assign(self, n, x):
        return _pyIdlak_pylib.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIdlak_pylib.StringVector_resize(self, *args)

    def insert(self, *args):
        return _pyIdlak_pylib.StringVector_insert(self, *args)

    def reserve(self, n):
        return _pyIdlak_pylib.StringVector_reserve(self, n)

    def capacity(self):
        return _pyIdlak_pylib.StringVector_capacity(self)
    __swig_destroy__ = _pyIdlak_pylib.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _pyIdlak_pylib.StringVector_swigregister
StringVector_swigregister(StringVector)

class ConstCharVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ConstCharVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ConstCharVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyIdlak_pylib.ConstCharVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyIdlak_pylib.ConstCharVector___nonzero__(self)

    def __bool__(self):
        return _pyIdlak_pylib.ConstCharVector___bool__(self)

    def __len__(self):
        return _pyIdlak_pylib.ConstCharVector___len__(self)

    def __getslice__(self, i, j):
        return _pyIdlak_pylib.ConstCharVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyIdlak_pylib.ConstCharVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyIdlak_pylib.ConstCharVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyIdlak_pylib.ConstCharVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyIdlak_pylib.ConstCharVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyIdlak_pylib.ConstCharVector___setitem__(self, *args)

    def pop(self):
        return _pyIdlak_pylib.ConstCharVector_pop(self)

    def append(self, x):
        return _pyIdlak_pylib.ConstCharVector_append(self, x)

    def empty(self):
        return _pyIdlak_pylib.ConstCharVector_empty(self)

    def size(self):
        return _pyIdlak_pylib.ConstCharVector_size(self)

    def swap(self, v):
        return _pyIdlak_pylib.ConstCharVector_swap(self, v)

    def begin(self):
        return _pyIdlak_pylib.ConstCharVector_begin(self)

    def end(self):
        return _pyIdlak_pylib.ConstCharVector_end(self)

    def rbegin(self):
        return _pyIdlak_pylib.ConstCharVector_rbegin(self)

    def rend(self):
        return _pyIdlak_pylib.ConstCharVector_rend(self)

    def clear(self):
        return _pyIdlak_pylib.ConstCharVector_clear(self)

    def get_allocator(self):
        return _pyIdlak_pylib.ConstCharVector_get_allocator(self)

    def pop_back(self):
        return _pyIdlak_pylib.ConstCharVector_pop_back(self)

    def erase(self, *args):
        return _pyIdlak_pylib.ConstCharVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyIdlak_pylib.new_ConstCharVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pyIdlak_pylib.ConstCharVector_push_back(self, x)

    def front(self):
        return _pyIdlak_pylib.ConstCharVector_front(self)

    def back(self):
        return _pyIdlak_pylib.ConstCharVector_back(self)

    def assign(self, n, x):
        return _pyIdlak_pylib.ConstCharVector_assign(self, n, x)

    def resize(self, *args):
        return _pyIdlak_pylib.ConstCharVector_resize(self, *args)

    def insert(self, *args):
        return _pyIdlak_pylib.ConstCharVector_insert(self, *args)

    def reserve(self, n):
        return _pyIdlak_pylib.ConstCharVector_reserve(self, n)

    def capacity(self):
        return _pyIdlak_pylib.ConstCharVector_capacity(self)
    __swig_destroy__ = _pyIdlak_pylib.delete_ConstCharVector
    __del__ = lambda self: None
ConstCharVector_swigregister = _pyIdlak_pylib.ConstCharVector_swigregister
ConstCharVector_swigregister(ConstCharVector)

NONE = _pyIdlak_pylib.NONE
AperiodicEnergyOptions = _pyIdlak_pylib.AperiodicEnergyOptions

def PySimpleOptions_new(opttype):
    return _pyIdlak_pylib.PySimpleOptions_new(opttype)
PySimpleOptions_new = _pyIdlak_pylib.PySimpleOptions_new

def PySimpleOptions_delete(pyopts):
    return _pyIdlak_pylib.PySimpleOptions_delete(pyopts)
PySimpleOptions_delete = _pyIdlak_pylib.PySimpleOptions_delete

def PySimpleOptions_option_names(pyopts):
    return _pyIdlak_pylib.PySimpleOptions_option_names(pyopts)
PySimpleOptions_option_names = _pyIdlak_pylib.PySimpleOptions_option_names

def PySimpleOptions_option_pytype(pyopts, key):
    return _pyIdlak_pylib.PySimpleOptions_option_pytype(pyopts, key)
PySimpleOptions_option_pytype = _pyIdlak_pylib.PySimpleOptions_option_pytype

def PySimpleOptions_get_numeric(pyopts, key):
    return _pyIdlak_pylib.PySimpleOptions_get_numeric(pyopts, key)
PySimpleOptions_get_numeric = _pyIdlak_pylib.PySimpleOptions_get_numeric

def PySimpleOptions_get_string(pyopts, key):
    return _pyIdlak_pylib.PySimpleOptions_get_string(pyopts, key)
PySimpleOptions_get_string = _pyIdlak_pylib.PySimpleOptions_get_string

def PySimpleOptions_set_float(pyopts, key, value):
    return _pyIdlak_pylib.PySimpleOptions_set_float(pyopts, key, value)
PySimpleOptions_set_float = _pyIdlak_pylib.PySimpleOptions_set_float

def PySimpleOptions_set_int(pyopts, key, value):
    return _pyIdlak_pylib.PySimpleOptions_set_int(pyopts, key, value)
PySimpleOptions_set_int = _pyIdlak_pylib.PySimpleOptions_set_int

def PySimpleOptions_set_bool(pyopts, key, value):
    return _pyIdlak_pylib.PySimpleOptions_set_bool(pyopts, key, value)
PySimpleOptions_set_bool = _pyIdlak_pylib.PySimpleOptions_set_bool

def PySimpleOptions_set_str(pyopts, key, value):
    return _pyIdlak_pylib.PySimpleOptions_set_str(pyopts, key, value)
PySimpleOptions_set_str = _pyIdlak_pylib.PySimpleOptions_set_str

def PyIdlakBuffer_newfromstr(data):
    return _pyIdlak_pylib.PyIdlakBuffer_newfromstr(data)
PyIdlakBuffer_newfromstr = _pyIdlak_pylib.PyIdlakBuffer_newfromstr

def PyIdlakBuffer_delete(pybuf):
    return _pyIdlak_pylib.PyIdlakBuffer_delete(pybuf)
PyIdlakBuffer_delete = _pyIdlak_pylib.PyIdlakBuffer_delete

def PyIdlakBuffer_get(pybuf):
    return _pyIdlak_pylib.PyIdlakBuffer_get(pybuf)
PyIdlakBuffer_get = _pyIdlak_pylib.PyIdlakBuffer_get
# This file is compatible with both classic and new-style classes.


